### ISSUE TITLE
Project System: Improve linked file rename experience

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#10076]
When renaming a file that is a target of one or more links the links should be updated. Currently, after the rename all links are broken. To fix them one needs to unload projects and manually change the links or remove and add the links again.

**Comment by tamlin-mike** [comment]
"links" is a devious word, and this is a non-obvious problem.

What if you have a source file/class "Bar", but decide "Nah, I want this to be "BarBase", while intending to (re-) create "Bar" after that change, to inherit from BarBase.

This is just one possible scenario, but a possibility.

Perhaps a question would be better; Do you want to auto-convert/adjust .... (granted, opening for the possibility there will be pointers to "nothing") rather than silently than auto-convert any and all references?

Just a thought.

(the next person calling this an "Experience" I will send a null-pointer to)

**Comment by tmat** [comment]
@tamlin-mike I don't think the scenario you describe isn't as common as just renaming the file. You can still achieve that by simply Ctrl+A and copy & paste the content of the Bar into the new file BarBase.

**Comment by birbilis** [comment]
Does this system cover solution files too or just project files? Currently when I have a Diagrams solution folder in my Solution and multiple .CD (class diagram) files from projects in that solution dropped into that folder (this makes links to the original items), when I rename a class diagram in one of the projects, I have to remove the link from the Diagrams folder in the solution and add it again

**Comment by davkean** [comment]
This issue was moved to dotnet/roslyn-project-system#100
