### ISSUE TITLE
Cyan pixel showing in code style Severity

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#10155]
![cyanpixel](https://cloud.githubusercontent.com/assets/235241/14089136/1f9aeac8-f4e8-11e5-8a98-e0b3b163d773.jpg)

See the cyan pixels in the upper-right of the Warning/Info/Error icons.

**Comment by dpoeschl** [comment]
FYI @balajikris

**Comment by balajikris** [comment]
thanks, I'll take this. If you happen to have more information about this, please share.

**Comment by leppie** [comment]
Looks like the classic 24/32-bit mismatch in WinForms.

**Comment by CyrusNajmabadi** [comment]
@dpoeschl is this on us?  don't we just use KnownMonikers.XXX?  Should this go to the platform?

**Comment by CyrusNajmabadi** [comment]
@olegtk Can you move this to Editor/Platform?  This is not in Roslyn.  Thanks!

**Comment by olegtk** [comment]
I think this is fixed long time ago, at least I cannot repro it on 16.5 or 16.6.
This UI is actually owned by Roslyn: https://github.com/dotnet/roslyn/blob/e704ca635bd6de70a0250e34c4567c7a28fa9f6d/src/VisualStudio/Core/Impl/Options/GridOptionPreviewControl.xaml#L161

Such pixel usually means theming issue and fixed by adding ImageThemingUtilities.ImageBackgroundColor property on some ancestor element with background.

**Comment by CyrusNajmabadi** [comment]
Things look good now:

![image](https://user-images.githubusercontent.com/4564579/198722094-f10f381b-2489-45dd-99f9-4d4629fdef7b.png)
