### ISSUE TITLE
retry(attempts) statement in catch area

### ISSUE THREAD

**Issue by iHateInventNames** [dotnet/roslyn#10162]
**Version Used**: 

**Steps to Reproduce**:
1. try{
      code
   } catch (SomeException){
      do workaround
      retry(1);  /// one attempt by default may be written just "retry;"
   }
2. 
3. 

**Expected Behavior**:

**Actual Behavior**:

**Comment by svick** [comment]
I think that retrying is something that's relatively common, but not something that you can easily generalize: for example, somebody will want to retry until a method returns `true`, etc.

But more importantly, you can already get pretty close to what you want by using a library method, e.g.:

```c#
Retry(1, () => code, () => do workaround);
```

Language features that can be easily replaced by library methods generally shouldn't exist, in my opinion.

**Comment by iHateInventNames** [comment]
Yes, that is why boost::bind was replacing lambdas in c++ for such a long time. Thank you for pointing me to the function. Looks like [nobody knows about it](http://stackoverflow.com/questions/1563191/c-sharp-cleanest-way-to-write-retry-logic). Could you, please, point us to MSDN reference? I guess it is efficient enough and language feature would not optimize much more on this. Except it causing code in framework increasing its size a bit. But not as much to make it a language feature. The first language that has such feature.

**Comment by SLaks** [comment]
You're proposing to turn `try` into a potential looping construct.

However, `try` is not obviously a loop, and people reading your code will have to look carefully through every `catch` block to see if there is a `retry` statement.

This feels like an over-specialized and too-confusing language feature.

**Comment by svick** [comment]
@iHateInventNames There is no such method that I know of. What I meant is that you can write such method (or it can be part of some library), which is a reason why it shouldn't be a language feature.

Sorry for the confusion.

**Comment by fsacer** [comment]
This is really bad idea, because a new keyword should really be a last resort. And this really can be achieved with method as @svick said.

**Comment by iHateInventNames** [comment]
oh yes, await was a last resort

**Comment by fsacer** [comment]
@iHateInventNames Probably not, but it was necessary to introduce totally new concept of programming which couldn't be achieved without support of compiler and it was revolution in the language.

**Comment by iHateInventNames** [comment]
oh mine, Task class and its ContinueWith method was introduced in 1.0 framework

**Comment by fsacer** [comment]
@iHateInventNames You are correct, didn't know that async/await is really just syntactic sugar. But really it's just a few lines of code to make such a method: 
```
static void Retry(int times, Action code, Action workaround)
{
    if (times <= 0) return;
    try {
        code?.Invoke();
    } catch (Exception) {
        Retry(--times, code, workaround);
    }
}
```

**Comment by HaloFour** [comment]
`Task` was added in .NET 4.0, and `await` is **significantly** more than syntactic sugar and requires quite a bit of compiler magic to implement.  Comparing asynchronous coroutines to `ContinueWith` is like comparing LINQ to `for` loops.

Implementing retry logic around exceptions is as simple as writing a loop.  You don't need a helper method and you don't need any special language features.  I'd even argue against trying to write a helper method because frankly it will take longer to write and if you ever have to use it more than once odds are you'll need it to do something slightly different.

**Comment by fsacer** [comment]
Of course it depends on what you are trying to achieve and of course tail recursion can be simply converted to loop which could make it a bit faster. And also you should have a really good to use exceptions (they are expensive) and you shouldn't abuse them where there are no exceptions happening really. Exceptions shouldn't happen really often.

**Comment by iHateInventNames** [comment]
@fsacer 


what if its static constructor?
```
        static DataContext()
        {
            using (var stream = new Windows.Storage.Streams.InMemoryRandomAccessStream())
            {
                DataContractSerializer serializer = new DataContractSerializer(typeof(StackPanel));
                using (var isf = IsolatedStorageFile.GetUserStoreForApplication())
                {
                    string sFileName = "name";
                    try
                    {
                        if (isf.FileExists(sFileName))
                            using (var stream1 = isf.OpenFile(sFileName, System.IO.FileMode.Open))
                            {
                                object obj = serializer.ReadObject(stream1);

                                data.AddRange(obj as List<Data>);
                            }
                    }
                    catch
                    {
                        isf.DeleteFile(sFileName);
                        repeat;
                    }
                }
            }
        }
```

@HaloFour, your statement "Comparing asynchronous coroutines to ContinueWith is like comparing LINQ to for loops." lacks an argument. Also "compiler magic" not understood.

**Comment by HaloFour** [comment]
@iHateInventNames 

No, it is the argument.  `await` provides a massive benefit to the language by unwrapping otherwise very complicated asynchronous code.  If you think that `await` is just a basic `ContinueWith` I dare you to implement two methods with multiple looping constructs and asynchronous error handling routines, one with `await` and one without, and tell me that they are even remotely comparable.  `await` is such a fundamental improvement that other languages like JavaScript and C++ are adopting it in one form or another.

Retrying a `try` block?  Wrap it in a loop.  Done:

```cs
        static DataContext()
        {
            using (var stream = new Windows.Storage.Streams.InMemoryRandomAccessStream())
            {
                DataContractSerializer serializer = new DataContractSerializer(typeof(StackPanel));
                using (var isf = IsolatedStorageFile.GetUserStoreForApplication())
                {
                    string sFileName = "name";
                    bool done = false;
                    do 
                    {
                        try
                        {
                            if (isf.FileExists(sFileName))
                                using (var stream1 = isf.OpenFile(sFileName, System.IO.FileMode.Open))
                                {
                                    object obj = serializer.ReadObject(stream1);

                                    data.AddRange(obj as List<Data>);
                                }
                            done = true;
                        }
                        catch
                        {
                            isf.DeleteFile(sFileName);
                            continue;
                        }
                    } while (!done);
                }
            }
        }
```

**Comment by gafter** [comment]
We are now taking language feature discussion in other repositories:
- https://github.com/dotnet/csharplang for C# specific issues
- https://github.com/dotnet/vblang for VB-specific features
- https://github.com/dotnet/csharplang for features that affect both languages

Features that are under active design or development, or which are "championed" by someone on the language design team, have already been moved either as issues or as checked-in design documents. For example, the proposal in this repo "Proposal: Partial interface implementation a.k.a. Traits" (issue 16139 and a few other issues that request the same thing) are now tracked by the language team at issue 52 in https://github.com/dotnet/csharplang/issues, and there is a draft spec at https://github.com/dotnet/csharplang/blob/master/proposals/default-interface-methods.md and further discussion at issue 288 in https://github.com/dotnet/csharplang/issues. Prototyping of the compiler portion of language features is still tracked here; see, for example, https://github.com/dotnet/roslyn/tree/features/DefaultInterfaceImplementation and issue 17952.

In order to facilitate that transition, we have started closing language design discussions from [the roslyn repo](https://github.com/dotnet/roslyn) with a note briefly explaining why. When we are aware of an existing discussion for the feature already in the new repo, we are adding a link to that. But we're not adding new issues to the new repos for existing discussions in this repo that the language design team does not currently envision taking on. Our intent is to eventually close the language design issues in the Roslyn repo and encourage discussion in one of the new repos instead.

Our intent is not to shut down discussion on language design - you can still continue discussion on the closed issues if you want - but rather we would like to encourage people to move discussion to where we are more likely to be paying attention (the new repo), or to abandon discussions that are no longer of interest to you.

If you happen to notice that one of the closed issues has a relevant issue in the new repo, and we have not added a link to the new issue, we would appreciate you providing a link from the old to the new discussion. That way people who are still interested in the discussion can start paying attention to the new issue.

Also, we'd welcome any ideas you might have on how we could better manage the transition. Comments and discussion about closing and/or moving issues should be directed to https://github.com/dotnet/roslyn/issues/18002. Comments and discussion about this issue can take place here or on an issue in the relevant repo.

-----------------

I am not moving this particular issue because I don't have confidence that the LDM would likely consider doing this.
