### ISSUE TITLE
Building roslyn from VS *always* does work, even if nothing has changed.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#10177]
Open Roslyn.sln from closed and build the solution.  Once complete built hte solution again.
Expected: VS does nothing, says "all projects up to date."  
Action: VS rebuilds several projects.  Gives reasons like:

```
1>Project 'MSBuildTask.Desktop' is not up to date. Copy to output file 'C:\GitHub\roslyn-internal\Open\Binaries\Shared\Microsoft.CSharp.Core.targets' missing from output location.
1>------ Build started: Project: MSBuildTask.Desktop, Configuration: Debug Any CPU ------
1>  MSBuildTask.Desktop -> C:\GitHub\roslyn-internal\Open\Binaries\Debug\Microsoft.Build.Tasks.CodeAnalysis.dll
```

**Comment by davkean** [comment]
I'm tracking my projects here: https://github.com/dotnet/roslyn/issues/10184.

Others in the tree are probably for other reasons.

**Comment by davkean** [comment]
Not a project system bug - this is a general Roslyn infrastructure issue.

**Comment by davkean** [comment]
Looked into this, there are 7 projects that are causing this on top of the two called out in #10184.

1>------ Build started: Project: ServicesVisualStudio, Configuration: Debug Any CPU ------
2>------ Build started: Project: MSBuildTask.Desktop, Configuration: Debug Any CPU ------
2>  MSBuildTask.Desktop -> C:\Roslyn With Spaces\Binaries\Debug\Microsoft.Build.Tasks.CodeAnalysis.dll
3>------ Build started: Project: MSBuildTaskTests, Configuration: Debug Any CPU ------
4>------ Build started: Project: VBCSCompilerTests, Configuration: Debug Any CPU ------
5>------ Build started: Project: CompilerExtension, Configuration: Debug Any CPU ------
6>------ Build started: Project: MSBuildTask, Configuration: Debug Any CPU ------

ServicesVisualStudio appears to because it's copying a different version Microsoft.VisualStudio.Threading.dll to the output directory than what someone else is after it.

**Comment by jasonmalinowski** [comment]
@CyrusNajmabadi Are you see thing this these days?

**Comment by CyrusNajmabadi** [comment]
Nope.  It's been good for a few months.
