### ISSUE TITLE
String interpolation and overload resolution.

### ISSUE THREAD

**Issue by ig-sinicyn** [dotnet/roslyn#10221]
Hi!

I know that it was discussed multiple times (#46 , for example) but I want to rebump as we've got a serious performance hit with it and I'm hoping to get recommendations what to do in situations like this.

Long story short: do not refactor string formatting methods if the format is conditional.
```
			Assert(x > 0, "Value of x ({0}) should be greater than zero.", x); // ok
			Assert(x > 0, $"Value of x ({x}) should be greater than zero.");  // bad idea.
```

Here's [quick-and-dirty benchmark](https://gist.github.com/ig-sinicyn/857ed5e239138e17e7e830bd4c82ff89) and the results:
```
Format+args:           149,2424
Interpolated:          2839,4277
Formattable(explicit): 148,9976

Done.
```

Now, the question: any chance that the overload resoluton will change on FormattableString?
All in all, if you do not want to get the FormattableString overload called you will not add it, right?

If not: what's the best way to prevent the misuse of sting interpolation in situations like this?

Thanks!

**Comment by gafter** [comment]
> Now, the question: any chance that the overload resoluton will change on `FormattableString`?

If we wanted to do that, we would make the type of an interpolated string `FormattableString` with a conversion to `String`, rather than vice versa. However, we are unlikely to make that change, as it would change the behavior of existing programs. It would also change any program that does this:
```cs
var s = $"...";
```
As it changes the type of `s`. Your best option is to use different names for the two methods.
