### ISSUE TITLE
Offer code fix to add usings for pasted code snippets

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#10272]
Filed on behalf of a customer from interviews

**Comment by DustinCampbell** [comment]
I don't auto-add these on paste. I think we should offer a code fix after pasting so that my file isn't dramatically changed simply by pasting code from one to another unless I, as the developer, choose to. :smile:

**Comment by justcla** [comment]
Posting on behalf of customer from interviews May-2017.

The request is to have the ability to resolve all imports with one action.
Similar to Eclipse (and maybe ReSharper), a user can paste code without typing in the usings.
The editor will prompt (or the user can call an explicit action) to have all the unresolved references imported (prompting the user in turn for any ambiguous references / multiple choices).

**Comment by justcla** [comment]
Note: Request includes the ability to activate this refactoring with a single key action.
We could assign a default shortcut key to it. Or just have a command that users can assign their own shortcut to.

**Comment by justcla** [comment]
Thought: Could this action be triggered when users call "Remove and Sort Usings"?
Perhaps that's a bad idea.

**Comment by justcla** [comment]
Scenario:
It’s possible that I have just added a Util file to my project – copied from another project.
When I first open the file, many of the references are invalid or missing.
I apply to the command to fix all usings.
If there are no ambiguities, it adds all required usings to the top of the file.
If there are ambiguities (either multiple options, or no valid option), it steps the user through them one-by-one.
If the user has a selection when they activate the command, it will only resolve missing references for the selection.

**Comment by justcla** [comment]
Suggestion: Scope to Current Document only.

**Comment by danroth27** [comment]
The shortcut everyone uses to organize and add missing imports in Java is ctrl-shift-O. The request here is for the same feature for C#.

**Comment by DustinCampbell** [comment]
Specifically Ctrl+shift+O? I think that's a global VS "open project" shortcut

**Comment by danroth27** [comment]
The point is not the specific keyboard shortcut, but the functionality it provides.

**Comment by DustinCampbell** [comment]
Of course. I just wanted to clarify what you meant.

**Comment by justcla** [comment]
In IntelliJ, the shortcut is Ctrl+Alt+O to organize imports.
They use Alt+Enter to import missing usings (one by one). But unlike other refactorings, this one pops up pro-actively as a suggestion.

**Comment by jinujoseph** [comment]
feature will be available via [PR](#29516) in 16.0.Preview1

**Comment by JoeRobich** [comment]
@justcla  A code refactoring that is available following a paste operation where there are missing imports.

**Comment by justcla** [comment]
Nice.

Now if only we could go one step further and have the refactoring appear for any unused imports.
Should I create a new issue for that?

**Comment by JoeRobich** [comment]
If it is a behavior that you want, please do. =)

**Comment by CyrusNajmabadi** [comment]
> Now if only we could go one step further and have the refactoring appear for any unused imports.
Should I create a new issue for that?

Could you clarify what you mean by that?

**Comment by justcla** [comment]
Ideally, any time there is a missing import, a suggestion should be given to import the missing namespace.
We can do this after paste. But we could also do this on file open. And when text is typed.

IntelliJ do this by popping a tooltip near the closest instance of missing import. Pressing Alt-Enter activates the refactoring, which gives a choice of namespaces to import.

As soon as one missing import is resolved, focus moves to the next instance, allowing you to easily resolve all the missing imports in the file.

**Comment by CyrusNajmabadi** [comment]
> Ideally, any time there is a missing import, a suggestion should be given to import the missing namespace.

Sorry... how is this different from teh existing 'add import' feature?  Thanks!

> IntelliJ do this by popping a tooltip near the closest instance of missing import. Pressing Alt-Enter activates the refactoring, which gives a choice of namespaces to import.

Yup.  We've had that since 2005 :)

> As soon as one missing import is resolved, focus moves to the next instance, allowing you to easily resolve all the missing imports in the file.

I'm not a fan of that idea at all...  if i add an import on one line, i often want to then just keep working on that line.  Jumping to the next issue seems like that would really screw things up.  If you do want that, i would prefer you just navigate using the error list.  Or we have a keystroke to navigate through fixable errors.

**Comment by justcla** [comment]
> > Ideally, any time there is a missing import, a suggestion should be given to import the missing namespace.
> 
> Sorry... how is this different from the existing 'add import' feature? Thanks!

The key difference is in how it proactively pops up. No need to navigate to the error, then invoke an action.

> > IntelliJ do this by popping a tooltip near the closest instance of missing import. Pressing Alt-Enter activates the refactoring, which gives a choice of namespaces to import.
> 
> Yup. We've had that since 2005 :)

No, we don't have this. In our version, the user must painfully navigate to the error first (as you described later), then separately invoke the lightbulb, then start looking for import choices. Instead, without moving your cursor, you could see a pop-up that says "Press Alt+Enter to import System.X.Y". You press Alt+Enter, errors go away and you keep coding without taking your caret away from where you were.

> > As soon as one missing import is resolved, focus moves to the next instance, allowing you to easily resolve all the missing imports in the file.
> 
> I'm not a fan of that idea at all... if i add an import on one line, i often want to then just keep working on that line. Jumping to the next issue seems like that would really screw things up. If you do want that, i would prefer you just navigate using the error list. Or we have a keystroke to navigate through fixable errors.

Maybe the view can stay in place. But when you think about it, do you really want to do anything at all while your file has missing imports? The model of "address all missing imports as soon as possible" seems fairly sensible. The file you're working with will be much more usable one the compiler understands all the classes. And to fix all without having to manually navigate to each one, is a huge timesaver. It's the sort of thing you appreciate once you've used it.
And then the act of having to navigate to every single missing import in the file is massively tiresome!

**Comment by CyrusNajmabadi** [comment]
>The key difference is in how it proactively pops up. No need to navigate to the error, then invoke an action.

I'm not getting why this is a desirable interaction experience.  Why am i getting prompted to do things unrelated to the code i'm working on?  

> No, we don't have this. In our version, the user must painfully navigate to the error first

Why is this painful?  If i'm not even at the code in question... how do i know what the right thing is to do?  

> Instead, without moving your cursor, you could see a pop-up that says "Press Alt+Enter to import System.X.Y"

That seems super random.  Why am i being asked this?  Is System.X.Y useful in some way?  Do i need it?  Why is it appropriate to add it?

> You press Alt+Enter, errors go away and you keep coding without taking your caret away from where you were.

I mean, if editor wants to add a feature where alt-enter just opens the lightbulb up if one exists somewhere in the file, i guess that can happen.  But it seems super weird to me.  Will it also have things like "generate method foo" and all the other fixes that could be applied depending on errors in unrelated locations in the file?

> And then the act of having to navigate to every single missing import in the file is massively tiresome!

I don't have any idea waht that means.  I just hit f8 to cycle through my issues.  If you want an editor shortcut to cycle through fixable problems in the file, i would not be opposed to it.  However, i definitely want to actually see (or have some understanding) of what code is triggering the fix suggestion.  Otherwise, it just feels like some random suggestion that doesn't make sense to me as to why it is happening.

> Maybe the view can stay in place. But when you think about it, do you really want to do anything at all while your file has missing imports? 

Missing imports arise for me when i'm writing new code (in which case, i'm in the right location), or i'm doing something like taking a chunk of other code and pasting it in (in which case this feature applies).  It's unclear to me the scenario where somehow i now have a bunch of unimported namespaces, but i'm now someplace else totally random in the file...

**Comment by justcla** [comment]
I understand it seems strange. I suppose you've never used it before. Some things just need to be seen and tried to understand their usefulness.

This would be a pop-up specific for imports only - not for any other kind of lightbulb action.
And the reason you'd want it is because the imports are missing and files are pretty useless with missing imports.

Of course, there are many slow and painful ways to address fixes and imports. (Stepping through an error list is one.) But it's nice to be looking for ways to improve the process. Similar to a one-click code cleanup. You could argue that a user can simply navigate to each issue and address. But isn't it nice when the tooling helps you out a bit? ;-)

**Comment by justcla** [comment]
The first time I saw this, I thought "Hey that's odd... why are you prompting me to fix this missing import?" But I just pressed Alt+Enter, the import was added, the error went away, and I kept typing.

You get left thinking... "Thanks!" Delightful!

**Comment by CyrusNajmabadi** [comment]
I'm available on gitter.  i'd like to chat about this more.

**Comment by CyrusNajmabadi** [comment]
> And the reason you'd want it is because the imports are missing and files are pretty useless with missing imports.

Files are useless without missing references as well :)   and without missing nuget packages.   And without other missing files in the same project containing the types they need.  Etc. etc.  I mean, code that doesn't compile is pretty useless :)

**Comment by CyrusNajmabadi** [comment]
>The first time I saw this, I thought "Hey that's odd... why are you prompting me to fix this missing import?" But I just pressed Alt+Enter, the import was added, the error went away, and I kept typing.

Sure.  Which is the experience you get today when... you know... you're typing :D

**Comment by justcla** [comment]
> > The first time I saw this, I thought "Hey that's odd... why are you prompting me to fix this missing import?" But I just pressed Alt+Enter, the import was added, the error went away, and I kept typing.
> 
> Sure. Which is the experience you get today when... you know... you're typing :D

Today, you must first navigate to the line that contains the missing import.
Then you must press Alt+Enter just to open the lightbulb.
Then you must press Enter to select the import (if it's the first choice), or else press arrow keys to get the import, then press Enter.

This feature would do all that with one keypress, and without the need to navigate to the offending line.

**Comment by CyrusNajmabadi** [comment]
@justcla : https://github.com/dotnet/roslyn/issues/10272#issuecomment-429995430

**Comment by CyrusNajmabadi** [comment]
> Today, you must first navigate to the line that contains the missing import.

Right.  but you said: But I just pressed Alt+Enter, the import was added, the error went away, *and I kept typing.*

Presumably you had the missing import because you typed something that needed that import.  So you had contxt about what it was going to add.  I'm trying to figure out the scenario of:

> i was typing in some totally different location, and the editor then told me: hey, for you should add an import, so that these other non-visible locations will be fixed.

**Comment by CyrusNajmabadi** [comment]
> Today, you must first navigate to the line that contains the missing import.

Sure.... that seems good.  Now i know what code it's trying to fix :)

> Then you must press Alt+Enter just to open the lightbulb.

Yup.  Because maybe adding the import is appropriate.  Or maybe adding a package is appropriate.  Or maybe a reference. Or maybe i need to fix the spelling of something :)  etc. etc.

> Then you must press Enter to select the import (if it's the first choice), or else press arrow keys to get the import, then press Enter.

Right... hence why this is good.  If you have to make a decision, then being *at the code in question* is really useful.

**Comment by justcla** [comment]
Agreed. Nicely put, Cyrus. Thanks.
