### ISSUE TITLE
[SpecialName] is not considered when referencing operators from the same assembly

### ISSUE THREAD

**Issue by svick** [dotnet/roslyn#10347]
**Version Used**: VS 2015 Update 2

**Steps to Reproduce**:

1. Create two types, one defining `operator +`, the other `op_UnaryPlus` marked with `[SpecialName]`:
 ```c#
  public class C
  {
      public static C operator +(C x)
      {
          return x;
      }
  }

  public class D
  {
      [SpecialName]
      public static D op_UnaryPlus(D x)
      {
          return x;
      }
  }
```
2. Try to use both methods as unary `+`, from the same assembly and from another assembly:

 ```c#
var c = +new C();
var d = +new D();
```

**Expected Behavior**:

In both cases (same assembly and another assembly), both methods are recognized and used as unary `+`.

**Actual Behavior**:

When using the methods from another assembly, it works fine. But from the same assembly, only `C` works, for `D` I get:

> CS0023	Operator '+' cannot be applied to operand of type 'D'

**Comment by orthoxerox** [comment]
The missing check seems to be in `SourceMemberMethodSymbol.cs`, `CreateMethodSymbol(...)`:

```c#
            var methodKind = interfaceSpecifier == null
                ? MethodKind.Ordinary
                : MethodKind.ExplicitInterfaceImplementation;
```

**Comment by gafter** [comment]
Actually, I believe this is by design.

**Comment by svick** [comment]
@gafter Could you expand on that? Why is it okay for the same code to work or not work, depending on where it is? (Except for the obvious situations where visibility is involved, which isn't the case here.)

**Comment by svick** [comment]
Also, while @orthoxerox made me look into this due to pattern matching, I don't think this is actually related to pattern matching. I'm only using old features on an old compiler.

**Comment by gafter** [comment]
When we import metadata, we try to infer what C# source code it came from in order to to give it the most appropriate language semantics. For example, when importing metadata we look for `[System.Runtime.InteropServices.OutAttribute]` on any `ref` parameters, and treat them as `out` parameters, because that is how the compiler represents `out` parameters in metadata. This is of course a best guess, as there is no way for us to know where the metadata came from. It is possible for a user to place an `[OutAttribute]` on a `ref` parameter, thereby fooling the compiler when the metadata is imported.

The same is true of the attribute `[System.Runtime.CompilerServices.SpecialName]`. Like `[OutAttribute]`, it is designed to be used by the compiler to convey information through metadata to a consuming compilation. But here too it is possible to fool the compiler by adding such an attribute yourself.

Since the _language_ does not give any special meaning to these attributes, you should not expect them to consistently affect language semantics. If anything, it would be a bug that they *ever* affect language semantics when written by the user. While it would be theoretically possible for the compiler to add yet further information in metadata to indicate which attributes were compiler-generated and which were user-added, such an effort would not benefit anyone.

Perhaps you would prefer that we mark these attributes `[Obsolete]` so that you are warned that they are intended only for use by compilers?

**Comment by svick** [comment]
@gafter Thank you for the explanation.
