### ISSUE TITLE
Add named indexer properties (Feature Request, Language-C#)

### ISSUE THREAD

**Issue by Corey-M** [dotnet/roslyn#10399]
### Concept

C# currently supports indexer properties but restricts them to the level of the class using the `this[]` specifier.  This should be extended to allow arbitrary properties to be declared as indexers.
### Existing indexers

In C# an indexer is a property-like element in the form:

```
public TValue this[TIndex index] { get {...} set {...} }
```

Access to this is similar to array access:

```
class_instance[some_index] = some_value;
```

Class indexers may include either or both of the `get` or `set` methods.

There are a few distinctions between indexers and properties:
- Indexers are declared with the `this` reserved word and an index parameter specification `[type name]`
- The `get` and `set` methods take an additional parameter as defined by the parameter specification
- Indexers are never referred to by name, only used to determine what is done when a class instance is used as the target of an array member access operation.
### Named indexers

A named indexer follow the same general form as indexers currently do with the primary difference that they are referenced by name.  The syntax remains similar, with the `this` reserved word replaced with the name of the indexer:

```
public TValue indexer_name[TIndex index] { get {...} set {...} }
```

Access to this would then be:

```
class_instance.indexer_name[some_index] = some_value;
```
### Current Code-based Simulation

It is currently possible to simulate named indexers using generic classes and function delegates.  For instance:

```
public class Indexer<TIndex, TValue>
{
    private readonly Func<TIndex, TValue> getter;
    private readonly Action<TIndex, TValue> setter;

    public TValue this[TIndex index] 
    {
        get { return getter(index); } 
        set { setter(index, value); }
    }

    public Indexer(Func<TIndex, TValue> getter, Action<TIndex, TValue> setter)
    {
        this.getter = getter;
        this.setter = setter;
    }
}

public class Example1
{
    private readonly Dictionary<string, object> _variables = new Dictionary<string, object>();

    public readonly Indexer<string, object> Variables;

    private object get_Variable(string name)
    {
        if (!_variables.ContainsKey(name))
            return null;
        return _variables[name];
    }

    private void set_Variable(string name, object value)
    {
        _variables[name] = value;
    }

    public Example1()
    {
        Variables = new Variable<string, object>(get_Variable, set_Variable);
    }
}
```

While this achieves the goal of allowing me to use `some_instance.Variables["name"] = 1;` to assign to the internal dictionary there are several things that are wrong with this method including:
- The constructor of `Example1` only exists to ensure the creation of the indexer, which cannot be done as a direct initializer since it references non-static class members
- All constructors must replicate the creation of the indexer object
- A constructor could assign `null` to the indexer leading to null reference exceptions on access
- Different methods could be assigned to the get/set depending on how it was initialized, leading to inconsistent operation
- Code is separated from declaration so it is not immediately clear what the field is doing
- The code is more complex than the equivalent using a named indexer (see below)
- Assymetric indexing is not supported without additional types to support get-only and set-only indexers.

It is possible to address some of those issues but only by increasing the complexity of the code.
### Named Indexer version

The same functionality implemented with a named indexer:

```
public class Example2
{
    private Dictionary<string, object> _variables = new Dictionary<string, object>();

    public object Variables[string name]
    {
        get
        {
            if (!_variables.ContainsKey(name))
                return null;
            return _variables[name];
        }
        set
        {
            _variables[name] = value;
        }
    }
}
```

This code suffers from none of the previously mentioned issues: no superfluous constructor, no possibility of a null reference of the property itself, access methods are consistent and visually tied to declaration, code is significantly easier to read and to maintain.

If named indexers are implemented with the same basic syntax as class indexers then assymetric named indexers - implementing only one of get/set - would also be supported without additional code complexity.
### Implementation: CLR concerns

It appears that this functionality is already present in VB.NET so I do not believe that any change to the CLR would be required.  C# implementation could simply mirror the VB.NET implementation.

**Comment by alrz** [comment]
Dup of #2144.

**Comment by Corey-M** [comment]
@alrz I did search for various terms before posting.  Apparently I didn't go back far enough in the history to find that particular item.  Doesn't seem to be much movement on that request however.

**Comment by Corey-M** [comment]
Two more issues with the `Indexer` class:

1) it captures a reference (or two) to the instance where the actual get/set delegates are defined, 

2) A copy can be made of the `Variables` object, which can potentially outlive the objects it depends on.

Both of these would be non-issues with a true named indexer implementation.

**Comment by HaloFour** [comment]
You could make `Indexer` a `struct`, avoiding the allocation.  You could make it a nested type with a limited-visibility constructor, avoiding potential abuse.  You can't avoid lifecycle issues by an errant consumer, but you can't avoid that anyway as anyone can just hold onto an `Example1` reference and achieve the same behavior.

VB.NET only has indexable properties due to legacy.  They exist, and the CLR supports them just fine, but that's not a reason for them to be implemented.  Per the teams' response to this request it seems that it encourages a pattern that they don't feel should be encouraged or common, and that since the same behavior can be achieved through an indexable proxy class that it doesn't warrant a separate language feature unto itself.

**Comment by gafter** [comment]
We are now taking language feature discussion in other repositories:
- https://github.com/dotnet/csharplang for C# specific issues
- https://github.com/dotnet/vblang for VB-specific features
- https://github.com/dotnet/csharplang for features that affect both languages

Features that are under active design or development, or which are "championed" by someone on the language design team, have already been moved either as issues or as checked-in design documents. For example, the proposal in this repo "Proposal: Partial interface implementation a.k.a. Traits" (issue 16139 and a few other issues that request the same thing) are now tracked by the language team at issue 52 in https://github.com/dotnet/csharplang/issues, and there is a draft spec at https://github.com/dotnet/csharplang/blob/master/proposals/default-interface-methods.md and further discussion at issue 288 in https://github.com/dotnet/csharplang/issues. Prototyping of the compiler portion of language features is still tracked here; see, for example, https://github.com/dotnet/roslyn/tree/features/DefaultInterfaceImplementation and issue 17952.

In order to facilitate that transition, we have started closing language design discussions from [the roslyn repo](https://github.com/dotnet/roslyn) with a note briefly explaining why. When we are aware of an existing discussion for the feature already in the new repo, we are adding a link to that. But we're not adding new issues to the new repos for existing discussions in this repo that the language design team does not currently envision taking on. Our intent is to eventually close the language design issues in the Roslyn repo and encourage discussion in one of the new repos instead.

Our intent is not to shut down discussion on language design - you can still continue discussion on the closed issues if you want - but rather we would like to encourage people to move discussion to where we are more likely to be paying attention (the new repo), or to abandon discussions that are no longer of interest to you.

If you happen to notice that one of the closed issues has a relevant issue in the new repo, and we have not added a link to the new issue, we would appreciate you providing a link from the old to the new discussion. That way people who are still interested in the discussion can start paying attention to the new issue.

Also, we'd welcome any ideas you might have on how we could better manage the transition. Comments and discussion about closing and/or moving issues should be directed to https://github.com/dotnet/roslyn/issues/18002. Comments and discussion about this issue can take place here or on an issue in the relevant repo.

-----------------

Discussion can continue at https://github.com/dotnet/csharplang/issues/471
