### ISSUE TITLE
Changes do not get deployed to the Roslyn hive with CTP 6

### ISSUE THREAD

**Issue by EricArndt** [dotnet/roslyn#1041]
When trying to fix #780, I was unable to see any of the changes I had made in the Roslyn hive. When I submitted the pull request to test it on the build machine, [tests failed](http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest/690/) in such a way that showed that the changes I made did indeed have an effect. You can see this on the pull request for the issue (#984). Here is what I see in the Roslyn Hive with the changes in the pull request:

![image](https://cloud.githubusercontent.com/assets/2079517/6499444/3909ce90-c2c9-11e4-89c1-0d83cd9cba0e.png)

**Comment by jaredpar** [comment]
Hey @EricArndt,
 
Thanks for taking the time to report this issue.  Unfortunately at this time there is no supported way for customers to deploy the changes made above the Workspaces layer to the installation of VS 2015 on their machine.  We understand this is a decidedly bad place to be and it’s one that we are working hard to remedy.  The solution will hopefully come in the VS 2015 Update 1 time frame.  

The underlying issue is that it’s not possible to override MEF components that ship in the Visual Studio box with a MEF component in a developer hive.  Visual Studio will always prefer the in the box component.  Virtually everything above Workspaces layer is a MEF component and can’t be dogfooded by customers.  

Fixing this though is unfortunately something Roslyn does not directly control.    It involves work from a number of teams and it’s unlikely it will all be done in time for RTM.

**Comment by jaredpar** [comment]
@romanov that would because it's included in the workspaces layer.

**Comment by petr-k** [comment]
@jaredpar If that's the unfortunate case, is there an *unsupported* way of doing this?
