### ISSUE TITLE
Need to confirm how extra compiler generated blocks affect caching

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#10604]
@AlekseyTs You added the following PROTOTYPE comment, but I'm not sure exactly what it means. Please rewrite this issue to describe it.

``` cs
            /// <summary>
            /// Decides whether to the add the bound node to the cache or not.
            /// </summary>
            /// <param name="currentBoundNode">The bound node.</param>
            private bool ShouldAddNode(BoundNode currentBoundNode)
            {
                BoundBlock block;

                // PROTOTYPE(patterns): Need to confirm how extra compiler generated blocks affect caching.
                //                      Do we actually benefit from adding them to the cache, or effect is negative or neutral.

```

**Comment by AlekseyTs** [comment]
@gafter Let's discuss this offline.

**Comment by AlekseyTs** [comment]
Some statements are going to be surrounded with compiler generated BoundBlock that holds pattern variables declared within the statement. Both the statement and the block are associated with the same syntax node. We are trying to cache both. We need to understand how the cache will look like at the end, and whether that state helps us, or possibly hurts us (we might get wrong node from the cache, not find a node in the cache, etc.).

**Comment by gafter** [comment]
@AlekseyTs What do you imagine needs to be done to resolve this issue? i.e. how will you know when you have a sufficient level of understanding?

**Comment by gafter** [comment]
@AlekseyTs Can you please clarify the questions you would like answered? Is this blocking RTM?

**Comment by AlekseyTs** [comment]
The code in question was added in https://github.com/dotnet/roslyn/pull/10431.

**Comment by AlekseyTs** [comment]
@gafter I think that sufficient level of understanding will be reached when we will have an answer to the question: "Do we actually benefit from adding the nodes to the cache and how exactly, or effect is negative or neutral."

**Comment by AlekseyTs** [comment]
I think the motivation for adding those nodes into the cache was to ensure that, when SemanticModel binds  statements and reuses result of previous binding, it wouldn't drop the blocks representing the scope from the tree and wouldn't end up with a tree that doesn't match the tree that is produced by the normal method binding process. This, however, conflicts with the goal to ignore compiler generated nodes for the purpose of producing semantic information, #16306 could be one of the issues caused by that. It is possible that the following function is going to be affected as well when the local function declaration is an embedded statement.
```
        public override ISymbol GetDeclaredSymbol(LocalFunctionStatementSyntax declarationSyntax, CancellationToken cancellationToken = default(CancellationToken))
        {
            var boundLocalFunction = GetLowerBoundNode(declarationSyntax) as BoundLocalFunctionStatement;
            return boundLocalFunction?.Symbol;
        }
```
