### ISSUE TITLE
Make CaseCorrector public

### ISSUE THREAD

**Issue by michalhosala** [dotnet/roslyn#10653]
**Version Used**: latest sources, i.e. SHA 1569c002a5998ebeb3b3a31182946583be773c6a

**Expected Behavior**:
`Microsoft.CodeAnalysis.CaseCorrection.CaseCorrector` should be made `public`.

**Actual Behavior**:
`Microsoft.CodeAnalysis.CaseCorrection.CaseCorrector` is `private`.

**Reason**:
Similarly to `Formatter` class, which is `public`, I would expect and _need_ class `CaseCorrector` to be `public` as well. Ultimate goal I am trying to achieve is to mimic the behavior of the `Edit.FormatDocument` Visual Studio command which performs work of both the `Formatter` and `CaseCorrector` roslyn classes (and many more, but that's off topic). I raised the question on how to perform case correction on VB.NET files on stackoverflow as well, see [here](http://stackoverflow.com/q/36649209/3242721) and the advice from roslyn team member was as follows:

> you can easily fork us and make it public for your own tools. But of course, file the bug too

**Comment by DustinCampbell** [comment]
At one point, we had decided to just pull the CaseCorrector functionality (and all VB pretty-listing) into the Formatter API, but that didn't happen for 1.0. Since then, I think it fell off our backlog. Thanks for filing!

**Comment by CyrusNajmabadi** [comment]
This would need to go through an API proposal.  in general, the reason we don't just make things public is because it increases maintenance costs and locks down our ability to change things in teh future.  We can open things up, but we have a process that requests need to go through to make sure the appropriate people weigh in and the right API shape is determined and shipped.
