### ISSUE TITLE
CS0185 (C#) experienced on 'lock' statement in unconstrained type parameter

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#1067]
A customer reports:

Fairly easy to workaround, but as far as I can tell it's perfectly valid code (and definitely worked in previous versions of VS). When lock is used on a template parameter, it seems to always generate `"error CS0185: 'T' is not a reference type as required by the lock statement"`

```cs
class SOptions { } 
class Driver 
{ 
    public void DoSomething<T>(T Data) 
    { 
        lock (Data) // << Generates CS0185 
        {} 
    } 
    public void DoSomethingElse( SOptions Data ) 
    { 
        lock(Data) // << Works fine 
        {} 
    } 
} 
class Program 
{ 
    static void Main(string[] args) 
    { 
        SOptions SOpt = new SOptions(); 
        Driver D = new Driver(); 
        D.DoSomething<SOptions>(SOpt); 
        D.DoSomethingElse(SOpt); 
    } 
} 
```

**Comment by gafter** [comment]
@theoy says:

> This is a known issue for 'lock' statement on unconstrained T. On further reflection, while this pattern is technically unsafe, there are users that are likely using this without any harm in their codebase because in practice they always instantiate the type parameters to reference types.

> Assigning to Neal to remove from the default case and to make a note to add it to our first warning wave.

**Comment by svick** [comment]
I take it that generating code that throws at runtime when `T` is a value type is not worth it?

**Comment by gafter** [comment]
@svick what IL sequence do you recommend for that effect?

**Comment by mikedn** [comment]
I don't think that throwing an exception at runtime solves the compatibility problem. Code like that can actually work correctly even if T is a value type. In this particular case Data is a parameter, a copy of what other threads my access at the same time. The fact that lock is ineffective in this case has no ill side-effects.

**Comment by svick** [comment]
@gafter I can't think of anything better than using reflection:

```c#
if (typeof(T).IsValueType)
    throw new SomeException();
```

**Comment by theoy** [comment]
@mikedn is correct, it's unfortunate that the lock is ineffective when a value type, but that doesn't mean that we can graduate that to a `throw`. :frowning:

@svick - standard way to condition for value type is: `(default(T) == null)` (and any other `null` conditions that you need). Several versions of the JIT will statically determine that result at JIT time so that it has very little overhead. We use that approach for codegen for certain features such as `?.`, when ensuring that references to value-type receivers are preserved in case the RHS of `?.` has a side effect. It's understood that `default(int?) == null` will be true at runtime, so technically while `int?` is a valuetype, it may behave like a reference type. But it's often the case that you actually *do* want it to behave like a reference type.

**Comment by svick** [comment]
@theoy I don't think you want nullable types to behave like reference types when it comes to locking.

**Comment by gafter** [comment]
@agocke Can you please "Verify" that this is fixed?
