### ISSUE TITLE
Compiling dynamic fails with "Missing compiler required member" when running Roslyn from coreclr

### ISSUE THREAD

**Issue by svick** [dotnet/roslyn#10693]
**Version Used**: Roslyn 1.3.0-beta1-20160410-01 from dotnet-core MyGet, dotnet CLI 1.0.0-beta-002202

**Steps to Reproduce**:

1. Take code from [this SO question](http://stackoverflow.com/q/36718506/41071) (targeting DNX), modified to use `dotnet` and simplified: https://gist.github.com/svick/07588ad5b93e0cb943861e96b9d47b55

 The code attempts to compile code that uses `dynamic`.
2. `dotnet restore`
3. `dotnet run`

**Expected Behavior**: Code executes fine.

**Actual Behavior**: `compilation.Emit()` fails, `compileResult.Diagnostics` contains:

> error CS0656: Missing compiler required member 'Microsoft.CSharp.RuntimeBinder.Binder.SetMember'

The assemblies used for metadata references:

* C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.0-rc2-23931\mscorlib.ni.dll
* C:\Users\Svick\.nuget\packages\System.Dynamic.Runtime\4.0.11-rc2-24008\lib\netstandard1.3\System.Dynamic.Runtime.dll
* C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.0-rc2-23931\Microsoft.CSharp.dll

**Comment by jaredpar** [comment]
Thanks for taking the time to report this.  

This behavior is "By Design" from the perspective of the compiler.  It's simply reporting that in attempting to generate code for `dynamic` it was unable to locate necessary members.  The underlying issue here is that the `dotnet run` process is not setting up the compilation with the correct set of references.
