### ISSUE TITLE
Behavior change for extension methods in global namespace

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#1079]
I observed a breaking change in Visual Studio 2015 CTP 6.

### Steps to reproduce

1. Create a new console project.
2. Install the [dnpextensions](https://www.nuget.org/packages/dnpextensions/) library from NuGet.
3. In Visual Studio, set the **Aliases** property for the **PGK.Extensions** assembly reference to `pgk` (instead of the default `global`).
4. Add the following line to the `Main` method.

    ```csharp
    Console.WriteLine(default(object).IsNull());
    ```

### Actual behavior in Visual Studio 2010 through 2013

The application compiles and writes `true` to the console.

### Actual behavior in Visual Studio 2015 CTP 6

The application does not compile.

### Impact

This strategy is used by an application I'm working on to alleviate an acute IntelliSense problem caused by the introduction of hundreds of extension methods in the global namespace for common base types including but not limited to `object`. Reassigning the alias for the assembly reference allowed us to hide these extension methods from IntelliSense to discourage use and improve productivity until such time as the dependency can be removed altogether. The extension methods are used in hundreds of locations, each of which must be carefully evaluated before removing the dependency altogether.

**Comment by gafter** [comment]
Possibly related to #1027

**Comment by VladimirReshetnikov** [comment]
@gafter @sharwell The old beahavior was incorrect (and I guess very annoying to many users). If you remove a referenced assembly from `global` alias, and assign it a different one (`pgk` in this case), it seems expected that top-level extension methods declared in that reference should not be globally visible. If you specifically want them in some file or namespace declaration, you should say `using pgk;`. But in previous versions of the compiler this behavior was broken - all top-level extension methods from all referenced assemblies were in scope no matter what extern aliases are assigned to them, and there was no way to opt-out. This bug is fixed in Roslyn. I understand that this fix introduced a breaking change, but workarounds are easy (add `global` alias to the reference, or add `using pgk;` in the source). We should estimate if benefits of this fix outweigh its beaking effect.

@sharwell It's not very clear from the description of the issue if you celebrate the fix and just want let us know that it might be breaking, or you really want the old behavior back. Could you please clarify?

**Comment by sharwell** [comment]
The old behavior did not really make sense to me. My goal was removing items from the IntelliSense list, which it did despite still being able to compile the code. I haven't taken a strong position on the issue of how to handle it (document the intentional deviation from the spec, or leave it corrected). I'm weakly in favor of correcting the behavior since "it's more correct", but would leave the final decision to the compatibility council.

In either case, it should be documented as (another) case where the previous compiler deviated from the language specification, along with the final design choice made for Roslyn.

**Comment by gafter** [comment]
I agree with @sharwell - whether we copy the "bug" from the native compiler or take a bug fix that is technically incompatible, we should document this issue in the compiler specification. Please don't close this bug until it is documented (you can assign the bug to me to add the documentation when we get to that stage).

**Comment by gafter** [comment]
Hey compat council: @AnthonyDGreen @DustinCampbell @ljw1004 @MadsTorgersen @gafter @srivatsn @theoy

I'm prepared to document the new (more correct) behavior and close this Issue if you're OK with that. The only customer who reported it to us is good with keeping the new behavior.
