### ISSUE TITLE
Replace the inter-branch pull request tool with a WebJob in Azure

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#10855]
Our tool that produces the pull requests to do our daily merges between branches currently runs on a fixed machine that might go offline. We should move this job to an Azure WebJob to give it better uptime.

**Comment by jasonmalinowski** [comment]
FYI @jaredpar

**Comment by jasonmalinowski** [comment]
@brettfo and @agocke: @natidea was looking at this and was confused by the fact we still have the internal tool that is only powering F#. What would it take to completely sunset the old tool?

**Comment by brettfo** [comment]
Short answer: we need final support for open source LOC work, e.g., XLIFF.  Last I checked, @nguerrera said it wasn't quite ready for consumption.

Long answer: since F# LOC lives in an internal repo, we have daily merges from `GitHub/master` to `VSO/microbuild` and to allow merges between remotes requires an actual clone, which WebJobs don't support because they're stateless and can't maintain an on-disk repo.  We could spend the time to have an Azure VHD with this repo, but by the time we got that up and running appropriately, the XLIFF stuff will likely be done and at that point we would fully live on GitHub which the existing tool fully supports.

**Comment by jaredpar** [comment]
Given we are abandoning roslyn-internal in a month or so ... do we need this issue anymore?

**Comment by brettfo** [comment]
It should still live while F# is in a cross-repo state, but after that it can go.

**Comment by jasonmalinowski** [comment]
@jaredpar: this bug is unrelated. This isn't for the pump, this is for the merge tool we use to do daily merges between branches targeting milestones.
