### ISSUE TITLE
Add comment in dynamic analysis tests to improve clarity 

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn#10931]
Currently the test output from dynamic analysis tests are something like this:

```
1
True
4
True
False
True
True
True
True
True
True
True
True
True
True
```

@jcouv has suggested adding comments in the test input source to help a reader correlate the test input and output. (Simply commenting each executable line with the corresponding number in the output would help a lot.)

**Comment by jcouv** [comment]
There's different levels of suggestion, depending on the cost to implement ;-)

An ideal output would correlate the collected data with the original spans (that is the most readable when it comes to code reviewing or maintaining the tests):

```
Main() {
[T] if (false) {
[F]      throw new Exception();
    }
[T] return 42;
```

A slightly less ideal would be (only correlating the instrumentation to find the containing function name, like `Main` instead of `1`):

```
Main
true
false
true
```

The third best option would be manually doing the association as a comment:
```
1 // Main
true
false
true
```

**Comment by Pilchie** [comment]
@jinujoseph can you re-triage? This was in the 2.0 milestone.

**Comment by jinujoseph** [comment]
cc @ManishJayaswal  as this is related to LUT

**Comment by jcouv** [comment]
This was fixed in https://github.com/dotnet/roslyn/pull/15819 already
