### ISSUE TITLE
Array.Empty<T>() optimization issues

### ISSUE THREAD

**Issue by controlflow** [dotnet/roslyn#1103]
```c#
using System;
using System.Linq.Expressions;

namespace System {
    public static class Array {
        public static T[] Empty<T>() => new T[0];
    }
}

public class C {
    public static void M(params int[] xs) {
        // expression tree with empty-arguments-params-call
        Expression<Action> f = () => M();
    }
}
```

Produces this code:
```c#
public class C {
    public static void M(params int[] xs) {
        Expression.Lambda<Action>(
            Expression.Call(null, methodof(C.M(int[])), new Expression[] {
                Expression.Call(null, methodof(System.Array.Empty()), new Expression[0])
            }),
            new ParameterExpression[0]);
    }
}
```

1. This C# 6.0 change can break various LINQ quotation translators, since nobody knows what `System.Array.Empty<T>` method actually do and how to translate it. We should disable this optimization inside expression trees.

2. When expression tree code is lowered, we can see a lot of `new Expression[0]` or `new ParameterExpression[0]` expressions (passed to `params` parameters) produced - exactly the cases for this optimization.

**Comment by stephentoub** [comment]
Thanks, @controlflow.  I'll take a look.

**Comment by VladimirReshetnikov** [comment]
Note that the C# spec explicitly requires to create a new array instance for every invocation with expanded `params`. It might be observable in many ways, e.g., by using an array in a lock statement. We should only consider optimization to `Array.Empty<T>` if we know for sure the method being invoked does not depend on it (unless we agree to take a breaking change and relax the spec rules here).

**Comment by stephentoub** [comment]
We'd discussed this back before I checked in the optimization, and the decision then was that it was acceptable and we went ahead with it. Is that no longer the case? I'd never intended for it to apply to expression lamdas and can fix that.

**Comment by VSadov** [comment]
This should get fixed since it is a compat break.
Expression trees suppress many optimizations like this because the point of the trees is just to represent semantics of expressions. Since we do not know how expressions will be used, we can't really tell what is more optimal.

**Comment by VladimirReshetnikov** [comment]
@stephentoub I was unaware of this decision. Was it supposed to be a change both in the spec and the compiler, or only in the compiler? Could you please forward me any e-mails related to this? Thanks.

**Comment by stephentoub** [comment]
@controlflow, thanks for reporting this.

The first issue is addressed in #1117.

The second issue is more of a separate feature; I've not addressed that.

**Comment by NickCraver** [comment]
We deployed .Net 4.6 on a few canary servers over at Stack Overflow yesterday in prep for the move after RyuJIT was fixed up and are now hitting an issue related to this. I'm just getting into this so feel free to shout anything obvious at me - I'll get into it much deeper tomorrow.

What's happening since the .Net 4.6 install (that we didn't get using the Roslyn compilers on 4.5.2, which we've done for some time) is that we're now seeing the `Array.Empty<T>` optimization in play. Here's an example and I don't think this is unexpected:

<img width="509" alt="screen shot 2015-08-30 at 6 27 52 am" src="https://cloud.githubusercontent.com/assets/454813/9566807/26ac3ef0-4ee1-11e5-86ac-8f12c7c1a7ff.png">

What *is* unexpected is that an app built on a .Net 4.6 machine deploys this optimization and **that makes any method call on a .Net 4.5.2 break**. .Net 4.5.2 not having an `Array.Empty<T>` makes this not really surprising. I'm not really sure that's intended behavior - was this thought through and decided an acceptable break? 

Importantly: **The project in question is targeting 4.5.2**, not 4.6. @stephentoub can you chime in here please? I'm happy to (and intend to) open a much more detailed/dedicated issue specifically for this, but I'm sanity checking here that we're not missing something glaringly obvious first.

**Comment by Manishearth** [comment]
It looks like [this line](https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Call.cs#L630) should be handling that, unless `GetWellKnownTypeMember` checks against the target instead of host.

**Comment by stephentoub** [comment]
@NickCraver, that's definitely not the indended behavior; the compiler should only be using Array.Empty if it's available in the assemblies being compiled against.  However, I'm also not able to repro it.  On my machine with VS2015, I compile this:
```C#
using System.Text;

class Program
{
    static void Main()
    {
        new StringBuilder().AppendFormat("test");
    }
}
```
When I change the project in VS to target .NET 4.6, I get this IL for Main:
```
.method private hidebysig static void  Main() cil managed
{
  .entrypoint
  // Code size       23 (0x17)
  .maxstack  8
  IL_0000:  nop
  IL_0001:  newobj     instance void [mscorlib]System.Text.StringBuilder::.ctor()
  IL_0006:  ldstr      "test"
  IL_000b:  call       !!0[] [mscorlib]System.Array::Empty<object>()
  IL_0010:  call       instance class [mscorlib]System.Text.StringBuilder [mscorlib]System.Text.StringBuilder::AppendFormat(string,
                                                                                                                            object[])
  IL_0015:  pop
  IL_0016:  ret
} // end of method Program::Main
```
When I then change the project to target .NET 4.5.2, I get this IL for Main:
```
.method private hidebysig static void  Main() cil managed
{
  .entrypoint
  // Code size       24 (0x18)
  .maxstack  8
  IL_0000:  nop
  IL_0001:  newobj     instance void [mscorlib]System.Text.StringBuilder::.ctor()
  IL_0006:  ldstr      "test"
  IL_000b:  ldc.i4.0
  IL_000c:  newarr     [mscorlib]System.Object
  IL_0011:  call       instance class [mscorlib]System.Text.StringBuilder [mscorlib]System.Text.StringBuilder::AppendFormat(string,
                                                                                                                            object[])
  IL_0016:  pop
  IL_0017:  ret
} // end of method Program::Main
```
You're seeing otherwise?

**Comment by NickCraver** [comment]
@stephentoub Yep we're seeing different - but root cause looks like the build servers did not get a 4.5.2 reference assembly install upon the upgrade (not expected, but actually a DSC glitch not deploying them).

I'm not sure if this is a roslyn issue or not, I think it's debatable. `Array.Empty` is in **what it was compiled against**, but not **what was targeted**. Should that be the case? It's going to break, and we're seeing it break as a result by not really respecting the target framework's capabilities, but rather the compilation resolution's abilities. 

I can see setting the blame on either side of the fence, but given that the current .Net failback behavior resolution is to continue with warnings (which many developers don't think anything of) - I don't think silent application of features beyond that framework are a good idea if preventable. At the same time, it's a tip-of-the-iceberg deal, and this is one of a thousand things that can be wrong from mis-targeting and getting a *newer* framework than intended. Further, the issue count would certainly be amplified the greater the difference in targeted vs. resolved assemblies.

Ideally, I'd rather see the build tools fail resolution to go *back* to the highest available prior version to the target - if you're using a code feature that needed newer, you'd get breaks due to raw compilation breaks. That's admittedly a much larger change and a build tools issue instead...but I'll think it out and pitch the change on that side of things.

I would think the Roslyn team had the discussion on resolved assemblies capabilities vs. targeted assemblies capabilities...or am I wrong? I'd be very interested in reading any discussion there if it's available.

**Comment by FransBouma** [comment]
An assembly which was compiled against 4.6, does that run on a system with only 4.5.2? I am guessing here (have to try it out) it will (as 4.6 is an in-place update), and if it will, this will indeed break as the IL has the Array.Empty reference. But I'm guessing also that this already has been discussed, as it's so obvious. 

To me optimizations like this, if the assembly can run on BCLs with lower versions than the one compiled against, should be hints for the JIT, which are obviously ignored at runtime on a system without the newer bits, and will be used on a system with the supported JIT. (so not optimize compilations with references to classes only available in newer versions of the BCL, but optimize with hints for the JIT at runtime).

**Comment by MrJul** [comment]
> did not get a 4.5.2 reference assembly install upon the upgrade

This is the core of the problem. The compiler should fail if it doesn't find the targeted reference assemblies, even if implementation assemblies are available. This could be a flag (true for new projects, false for old ones) since it's probably a breaking change.

**Comment by NickCraver** [comment]
To clearly layout what happened:

Project target: 4.5.2
Build server: 4.6 (**without** 4.5.2 reference assemblies properly available)
Runtime server: 4.5.2

Here's the resulting stack when a method with this optimization is called:

```
System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at Calculon.Web.Scheduled.Tasks.ReportRedisInfoToBosunTask.<Execute>d__5.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Calculon.Web.Scheduled.Tasks.ReportRedisInfoToBosunTask.Execute(DateTime started)
   at Calculon.Web.Scheduled.ScheduledTasks.<RunScheduledTaskAsync>d__7.MoveNext()
```

This is a **runtime only** break. There's only a warning in the build chain about resolution that something *may* happen (which, to be fair, is innocuous the vast majority of the time and often not a priority to fix). And by warning, I mean the wrong assembly resolution - you have to be aware of how everything works to really know *this* can happen.

To answer @FransBouma, yep - a 4.6 compiled assembly runs fine on a 4.5.2 server...until you hit something newer than 4.5.2 in use like `Array.Empty`. That's exactly what happened here. I do think moving this optimization into the JIT is an excellent idea, was this option discussed? 

I think at this point a separate issue is warranted as it's a different scope of problem, I'll split this out into something more proper in just a bit.

**Comment by NickCraver** [comment]
I opened an issue specific to what happened in #4889 above - thanks for the input everyone.

**Comment by tmat** [comment]
@davkean

**Comment by gafter** [comment]
@NickCraver Re
> I do think moving this optimization into the JIT is an excellent idea, was this option discussed?

It isn't a valid optimization at the JIT level. The original expression `new Type[0]` observably creates a new instance distinct from every previous one, while `Array.Empty<Type>()` observably creates an instance the *same* as all the previous ones. It is only because we accepted a change in language semantics that the change in the compilers is acceptable.

**Comment by FransBouma** [comment]
The idea behind the hint is that the compiler knows when Array.Empty<T> is possible, and accordingly can insert hints for the JIT: the compiler has all the time in the world compared to the JIT which has to decide on much less information to make a decision. But this is a bigger topic (i.e. compile time analysis resulting in hints in the IL for the JIT to make more informed decisions)

**Comment by gafter** [comment]
@FransBouma This isn't an *optimization* or a *hint* - it is a change in language semantics made for performance. The JIT should not be changing code with well-defined meaning and turning it into something with a different meaning.
