### ISSUE TITLE
Source Generators

### ISSUE THREAD

**Issue by biqas** [dotnet/roslyn#11038]
Hi,
I somehow dislike the idea to bring in keyword’s and constructs into the language which do not belong to it (I think and hope Anders Heilsberg is representing similar opinions). 
Disliking it as a pure language feature does not mean that you can’t have it as tool features (like the analyzers). Therefor I would encourage to think more in this direction. To be concrete, if keywords are needed they should be only existing in the boundaries of the generator editor. Use multiple editor layers to augment, highlight and lock the different bits and bytes. I tried to make it more visible with the following examples (The names are just for example purposes).

[Roslyn Proposal - Source code generator.pdf](https://github.com/dotnet/roslyn/files/247900/Roslyn.Proposal.-.Source.code.generator.pdf)

https://github.com/dotnet/roslyn/blob/features/generators/docs/features/generators.md

Related issues:
#5292
#5561

**Original code**

_Normal editor_
_Code lense layer 0_

> ```
> class C
> {
>     void F() { //Body of F }
> 
>     int P { get; set; }
> 
>     object this[int index] { get { return null; } }
> 
>     event EventHandler E;
> }
> 
> ```

**Source generator code**

_Generator editor_
_Code lense layer 1_

```
class C
{
    void F()
    {
        Console.WriteLine(“Before”);
        MemberCall(member::F);
        Console.WriteLine(“After”);
        MemberCall(ModifyF(member::F));
    }

    int P { get; set; }

    object this[int index] { get { return null; } }

    event EventHandler E; 
}

```

Then the result should look like this =>

_Normal editor_
_Code lense layer 2_

```
class C
{
    void F()
    {
        Console.WriteLine(“Before”);  // Line is augmented
        //Body of F
        Console.WriteLine(“After”);   // Line is augmented
        WriteLine(“F”);               // Line is augmented
        //Body of F                   // Line is augmented
    }

    int P { get; set; }

    object this[int index] { get { return null; } }

    event EventHandler E;
}

```

Self-written helper:

```
// Output => void F() { WriteLine("F"); //Body of F }
public static CompilationUnitSyntax ModifyF(SyntaxNode node)
{
    return CompilationUnit().WithMembers(
        SingletonList<MemberDeclarationSyntax>(
            MethodDeclaration(
                PredefinedType(
                    Token(SyntaxKind.VoidKeyword)),
                Identifier("F"))
            .WithBody(
                Block(
                    SingletonList<StatementSyntax>(
                        ExpressionStatement(
                            InvocationExpression(
                                IdentifierName("WriteLine"))
                            .WithArgumentList(
                                ArgumentList(
                                    SingletonSeparatedList<ArgumentSyntax>(
                                        Argument(
                                            LiteralExpression(
                                                SyntaxKind.StringLiteralExpression,
                                                Literal("F"))))))))))));
}

```

Assume there is a generated helper library created based on the  original code.
Example: MemberCall(SyntaxNode node) would produce F();

`CompilationUnit() .WithMembers( SingletonList<MemberDeclarationSyntax>( MethodDeclaration( PredefinedType( MissingToken(SyntaxKind.VoidKeyword)), Identifier("F")) .WithSemicolonToken( Token(SyntaxKind.SemicolonToken))))`

Selectors:
global::{NAME}      (context global)
namespace::{NAME}   (context sensitive)
class::{NAME}       (context sensitive)
member::{NAME}  (context sensitive)
…
Selectors will return syntax node of original source code.

Regarding to the example:
Select syntax node of class C:
global::MyNamespace.C | namespace:: MyNamespace.C | class::C  
Select syntax node of member method C:
global:: MyNamespace.C.F | namespace:: MyNamespace.C.F | class::C.F | member::F

Raw class C

Assign to generator editor as _global_.

```
CompilationUnit()
    .WithMembers(
        SingletonList<MemberDeclarationSyntax>(
            ClassDeclaration("C")
            .WithMembers(
                List<MemberDeclarationSyntax>(
                    new MemberDeclarationSyntax[]{
                        MethodDeclaration(
                            PredefinedType(
                                Token(SyntaxKind.VoidKeyword)),
                            Identifier("F"))
                        .WithBody(
                            Block()),
                        PropertyDeclaration(
                            PredefinedType(
                                Token(SyntaxKind.IntKeyword)),
                            Identifier("P"))
                        .WithAccessorList(
                            AccessorList(
                                List<AccessorDeclarationSyntax>(
                                    new AccessorDeclarationSyntax[]{
                                        AccessorDeclaration(
                                            SyntaxKind.GetAccessorDeclaration)
                                        .WithSemicolonToken(
                                            Token(SyntaxKind.SemicolonToken)),
                                        AccessorDeclaration(
                                            SyntaxKind.SetAccessorDeclaration)
                                        .WithSemicolonToken(
                                            Token(SyntaxKind.SemicolonToken))}))),
                        IndexerDeclaration(
                            PredefinedType(
                                Token(SyntaxKind.ObjectKeyword)))
                        .WithParameterList(
                            BracketedParameterList(
                                SingletonSeparatedList<ParameterSyntax>(
                                    Parameter(
                                        Identifier("index"))
                                    .WithType(
                                        PredefinedType(
                                            Token(SyntaxKind.IntKeyword))))))
                        .WithAccessorList(
                            AccessorList(
                                SingletonList<AccessorDeclarationSyntax>(
                                    AccessorDeclaration(
                                        SyntaxKind.GetAccessorDeclaration,
                                        Block(
                                            SingletonList<StatementSyntax>(
                                                ReturnStatement(
                                                    LiteralExpression(
                                                        SyntaxKind.NullLiteralExpression)))))))),
                        EventFieldDeclaration(
                            VariableDeclaration(
                                IdentifierName("EventHandler"))
                            .WithVariables(
                                SingletonSeparatedList<VariableDeclaratorSyntax>(
                                    VariableDeclarator(
                                        Identifier("E")))))}))))
    .NormalizeWhitespace();

```

**Comment by biqas** [comment]
And by the way there are not really keywords needed like the selectors described above:

> Selectors:
> global::{NAME} (context global)
> namespace::{NAME} (context sensitive)
> class::{NAME} (context sensitive)
> member::{NAME} (context sensitive)

of course it would be syntactical sugar to have such keywords.

And for the augmented code experience, there is already today something similar with Code Contracts.

And to highlight the topic again, editor or tool bounded language extensions or specific DSL's (Domain Specific Languages) are a better fit to describe the intensions of source code enhancements.

**Comment by gafter** [comment]
We are now taking language feature discussion in other repositories:
- https://github.com/dotnet/csharplang for C# specific issues
- https://github.com/dotnet/vblang for VB-specific features
- https://github.com/dotnet/csharplang for features that affect both languages

Features that are under active design or development, or which are "championed" by someone on the language design team, have already been moved either as issues or as checked-in design documents. For example, the proposal in this repo "Proposal: Partial interface implementation a.k.a. Traits" (issue 16139 and a few other issues that request the same thing) are now tracked by the language team at issue 52 in https://github.com/dotnet/csharplang/issues, and there is a draft spec at https://github.com/dotnet/csharplang/blob/master/proposals/default-interface-methods.md and further discussion at issue 288 in https://github.com/dotnet/csharplang/issues. Prototyping of the compiler portion of language features is still tracked here; see, for example, https://github.com/dotnet/roslyn/tree/features/DefaultInterfaceImplementation and issue 17952.

In order to facilitate that transition, we have started closing language design discussions from [the roslyn repo](https://github.com/dotnet/roslyn) with a note briefly explaining why. When we are aware of an existing discussion for the feature already in the new repo, we are adding a link to that. But we're not adding new issues to the new repos for existing discussions in this repo that the language design team does not currently envision taking on. Our intent is to eventually close the language design issues in the Roslyn repo and encourage discussion in one of the new repos instead.

Our intent is not to shut down discussion on language design - you can still continue discussion on the closed issues if you want - but rather we would like to encourage people to move discussion to where we are more likely to be paying attention (the new repo), or to abandon discussions that are no longer of interest to you.

If you happen to notice that one of the closed issues has a relevant issue in the new repo, and we have not added a link to the new issue, we would appreciate you providing a link from the old to the new discussion. That way people who are still interested in the discussion can start paying attention to the new issue.

Also, we'd welcome any ideas you might have on how we could better manage the transition. Comments and discussion about closing and/or moving issues should be directed to https://github.com/dotnet/roslyn/issues/18002. Comments and discussion about this issue can take place here or on an issue in the relevant repo.

The most relevant issue in the csharplang repo appears to be https://github.com/dotnet/csharplang/issues/107
