### ISSUE TITLE
(VB) Make AddressOf optional / implicit

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#1107]
Let's say we have the following method signature
`Function Where(Of T)( xs As IEnumerable(Of T), pred As Func(T,Boolean) As IEnumerable`
and we want to call .

We could use
* a lambda function:   `Where( MyPileOfClothes, Function(c) c.Smell = Smells.Ok )`
* a named lambda `SmellsOk`  `Where( MyPileOfClothes, SmellsOk )`
* a normal function `SmellsOk` `Where( MyPileOfClothes, AddressOf SmellsOk )`

I think it would good if the `AddressOf` can be implied or implicit in this case.
It would make the code more readable, doesn't suggest that where are using a pointer.

**Comment by AdamSpeight2008** [comment]
An issue with is disambiguating between return the result of a function call used as a method argument and use this method. 
How does C# handle this?

**Comment by VladimirReshetnikov** [comment]
VB, unlike C#, does not require explicit empty argument list `()` for method invocations. So, making `AddressOf` optional will either be a breaking change, or will introduce an additional complexity to overload resolution rules (that are already complicated enough).

**Comment by jaredpar** [comment]
Was thinking about this proposal over the weekend and I agree with @VladimirReshetnikov that the biggest problem here is the implicit empty argument list.  It makes samples like the following immediately ambiguous with this proposal:

``` vb
Class C1
    Delegate Function Func() As Object

    Function Target() As Func
        Return Nothing
    End Function

    Sub M(p As Func)

    End Sub

    Sub Test()
        M(Target)
        M(AddressOf Target)
    End Sub
End Class
```

This code is completely legal today.  In order to be accepted this proposal would need to be adjusted to ensure this code kept compiling.  That would require further complicating overload resolution which is already very complicated in VB.

**Comment by gafter** [comment]
Because it is a breaking change, we would not do it.
