### ISSUE TITLE
Auto-implemented IDisposable for classes with disposable fields.

### ISSUE THREAD

**Issue by Mr-Byte** [dotnet/roslyn#111]
Currently, implementing `IDisposable` requires a significant amount of boiler plate code.  I would like to propose a way to auto-implement IDisposable for fields.  Using the following syntax:

```csharp
public class Foo : IDisposable
{
    private using Bar _barResource;
}
```

Here the `using` keyword is being used as a modifier on the field.  It indicates that the field should be disposed when the `Dispose` method is called.  These fields would act the same way as `readonly` fields in that they can only be set from inside constructors or with field initializers.

This syntax would then have the compiler auto-implement IDisposable that handles disposing all fields marked `using` and also a finalizer to call `Dispose` if it has not yet been called.  The above code sample would expand into the typical dispose pattern.

There are a few considerations that need to be made, though.  These include, but are not limited to:

* What to do with potential circular references between resources?
* How to handle dispose logic that doesn't fit the typical pattern?
* How to differentiate between managed and unmanaged disposable resources?

The value I could see this feature providing is a reduction in the amount of code needed to write classes that are composed of `IDisposable` resources to ensure proper cleanup of those resources.

**Comment by scalablecory** [comment]
I think there's a lot of value in automatic scope-bound resource management. This needs to be extended to work with the method body as well.

I would prefer a lighter syntax to it, though. Something like:

    private Bar! _barResource;

**Comment by matwilko** [comment]
:+1: I like how this makes the resource ownership and lifetime management more explicit and simpler to implement.

@scalablecory I disagree, I think the syntax is light enough as is, and succinctly expresses intent, along with reusing syntax that many developers are already used to. It also clearly annotates the **field**, while your example syntax would at first glance be saying something about the **type**, rather than the field itself.

Thoughts on unmanaged resources and finalizers:

Isn't the current best practice for unmanaged resources to wrap them in a SafeHandle or otherwise into their own does-nothing-but-contain-the-resource class? In that case, it's already considered an "advanced" programming feature, and the developer should be expected to use the IDisposable pattern and finalizer logic properly.

If we assume that best practice, then it eliminates the need in the classes that use SafeHandle or it's ilk to consider unmanaged resources/resources that need to be finalized, because they'll always be abstracted away into an IDisposable.

It also eliminates the need to generate a finalizer, which I think is a good thing anyway; it reduces the GC's overhead because it doesn't add yet another object to the finalizer queue.

Circular references:
If the IDisposable pattern is followed properly (i.e. the check for whether disposal has already occured) then surely circular references don't matter? If A.Dispose() calls B.Dispose() calls A.Dispose(), the second A.Dispose() call should just immediately return, allowing the disposal to move forward.

**Comment by sharwell** [comment]
I would lean towards:

```
private disposable Bar _barResource;
```

> * What to do with potential circular references between resources?

The generated implementation of `Dispose(bool)` could be implemented in a manner where recursive calls are simply ignored.

> * How to handle dispose logic that doesn't fit the typical pattern?

Probably in a manner similar to constructors. For example, the following doesn't cause a problem:

```csharp
public class Foo
{
  object _bar = new object();

  public Foo()
  {
    // things here
  }
}
```

> * How to differentiate between managed and unmanaged disposable resources?

There is no need to. Only allow this syntax on a field where the static type of the field is a type that implements `IDisposable`. These are always managed objects.

**Comment by sharwell** [comment]
@matwilko wrote:
> If the IDisposable pattern is followed properly (i.e. the check for whether disposal has already occured) then surely circular references don't matter?

This is often not a correct assumption. For example, all of the example code in [DG Update: Dispose, Finalization, and Resource Management](http://joeduffyblog.com/2005/04/08/dg-update-dispose-finalization-and-resource-management/) (the most comprehensive resource available on the subject) set the `disposed` field *after* disposing of fields. Considering the manner in which the .NET Runtime handles a `StackOverflowException` (unrecoverable termination of the process), it will be very import to specifically consider this case during the design of the feature.

**Comment by matwilko** [comment]
@sharwell I'll admit, it was a very big if :P

**Comment by sharwell** [comment]
@matwilko It was not an unreasonable assumption.

**Comment by Mr-Byte** [comment]
@sharwell wrote:
> I would lean towards:
> 
> ```private disposable Bar _barResource;```

I have to agree with this.  I initially picked `using` since it was a familiar keyword, but it would end up just giving further meaning to a keyword that's used in several different contexts as it stands.  Picking `disposable` would make the intent more clear and not overload an existing keyword's meaning.

As for the rest of your response, I think you adequately addressed the open questions I had on the idea.

**Comment by gafter** [comment]
We are unlikely to provide direct language support for this, however, we expect there will likely be solutions built on #5292/#5561.
