### ISSUE TITLE
Feature Request:  Make working with Generic Type Parameters Easier for classes with lots of Generics

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/roslyn#11172]
It would be really nice if I could do something like a generic "typedef" using the syntax below.
I really like how this allows me to progressively specify type parameters to a class in a more readable fashion, however, I don't like that my final types end up being a "WithDriver" or a "WithLaser".  Any suggestions or ideas?

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ConsoleApplication17 {
    class Program {
        static void Main(string[] args) {
            var C = new Spaceship
                .WithDriver<int>
                ();

            var D = new Spaceship
                .WithEngine<String>
                .WithLasers<long>
                ();

        }
    }

    public class Spaceship : Spaceship<object, object, object> {    }

    public class Spaceship<TDriver, TEngine, TLasers> {

        public class WithDriver<TNewDriver> : Spaceship<TNewDriver, TEngine, TLasers> {
        }

        public class WithEngine<TNewEngine> : Spaceship<TDriver, TNewEngine, TLasers> {
        }

        public class WithLasers<TNewLasers> : Spaceship<TDriver, TEngine, TNewLasers> {
        }
    }
}
```

**Comment by dsaf** [comment]
As far as I understand the suggestion is to introduce named type arguments similarly to [named method arguments](https://msdn.microsoft.com/en-us/library/dd264739.aspx):

```csharp
var s = new Spaceship<TDriver:int, TEngine:string, TLasers:long>();
```

I see some value in this for generic types where arguments are not constrained in a meaningful way:

```csharp
var d = new Dictionary<TKey:string, TValue:int>();
```

**Comment by alrz** [comment]
Related: #6207 #6248

**Comment by gafter** [comment]
We are now taking language feature discussion in other repositories:
- https://github.com/dotnet/csharplang for C# specific issues
- https://github.com/dotnet/vblang for VB-specific features
- https://github.com/dotnet/csharplang for features that affect both languages

Features that are under active design or development, or which are "championed" by someone on the language design team, have already been moved either as issues or as checked-in design documents. For example, the proposal in this repo "Proposal: Partial interface implementation a.k.a. Traits" (issue 16139 and a few other issues that request the same thing) are now tracked by the language team at issue 52 in https://github.com/dotnet/csharplang/issues, and there is a draft spec at https://github.com/dotnet/csharplang/blob/master/proposals/default-interface-methods.md and further discussion at issue 288 in https://github.com/dotnet/csharplang/issues. Prototyping of the compiler portion of language features is still tracked here; see, for example, https://github.com/dotnet/roslyn/tree/features/DefaultInterfaceImplementation and issue 17952.

In order to facilitate that transition, we have started closing language design discussions from [the roslyn repo](https://github.com/dotnet/roslyn) with a note briefly explaining why. When we are aware of an existing discussion for the feature already in the new repo, we are adding a link to that. But we're not adding new issues to the new repos for existing discussions in this repo that the language design team does not currently envision taking on. Our intent is to eventually close the language design issues in the Roslyn repo and encourage discussion in one of the new repos instead.

Our intent is not to shut down discussion on language design - you can still continue discussion on the closed issues if you want - but rather we would like to encourage people to move discussion to where we are more likely to be paying attention (the new repo), or to abandon discussions that are no longer of interest to you.

If you happen to notice that one of the closed issues has a relevant issue in the new repo, and we have not added a link to the new issue, we would appreciate you providing a link from the old to the new discussion. That way people who are still interested in the discussion can start paying attention to the new issue.

Also, we'd welcome any ideas you might have on how we could better manage the transition. Comments and discussion about closing and/or moving issues should be directed to https://github.com/dotnet/roslyn/issues/18002. Comments and discussion about this issue can take place here or on an issue in the relevant repo.

-----------------

I am closing this issue because discussion appears to have died down. You are welcome to open a new issue in the csharplang repo if you would like to kick-start discussion again.
