### ISSUE TITLE
"Inconsistent Line Endings" warning generated for verbatim string literals

### ISSUE THREAD

**Issue by MaceWindu** [dotnet/roslyn#11174]
Sorry if it is not Roslyn's responsibility. I will fill connect (ugh...) issue if it is VS issue.

**Version Used**: 
VS2015U2

**Steps to Reproduce**:

1. Create C# source file with CR LF endings used in code
2. Add verbatim string literal with CR without following by LF or LF without preceding CR
3. Reopen document

**Expected Behavior**:
Document opened without any warnings, because those "inconsistent" line endings are part of data and "fixing" them will change application behavior.

**Actual Behavior**:
![WAT](https://cloud.githubusercontent.com/assets/1099238/15109165/47859336-15da-11e6-84fc-35de1d77af6a.png)

**Comment by DustinCampbell** [comment]
You're right that this isn't a Roslyn issue. The line ending detection is handled by the core editor, so it's probably better to file on Connect. However, it might require significant work to fix since the editor doesn't have the language insight to know when the line ending appears in a verbatim string. :disappointed:
