### ISSUE TITLE
Missing file is reported as build break, but not in error list

### ISSUE THREAD

**Issue by AArnott** [dotnet/roslyn#1119]
When I have a missing file in my C# project, the build fails and I can see the error in the output window. But the error does not show up in the error list of Visual Studio 2015.

**Comment by heejaechang** [comment]
@AArnott live error shouldn't show up since it is simply ignored and live compilation doesn't know about the missing file. but any reference to symbols defined in the missing file should show up as unknown symbols.

but once built, errors from csc should show up in error list. and it works fine in current vspro_1.

![image](https://cloud.githubusercontent.com/assets/1333179/7389888/446cd596-ee27-11e4-8b19-812c02cfc473.png)

I will close this bug, let me know if you have other question.
