### ISSUE TITLE
Allow use of generic types as arguments in specifying known types 

### ISSUE THREAD

**Issue by waynebrantley** [dotnet/roslyn#11265]
Consider this code
```
public TResult Process<TResult>(IQuery<TResult> query)
{
	var handlerType = typeof(IQueryHandler<,>).MakeGenericType(query.GetType(), typeof(TResult));
	dynamic handler = _container.Resolve(handlerType);
	return handler.Handle((dynamic)query);
}
```

Instead, I should be able to write this:

```
public TResult Process<TResult>(IQuery<TResult> query)
{
	var handlerType = typeof(IQueryHandler<IQuery<TResult>,TResult>);
	var handler = (IQueryHandler<IQuery<TResult>,TResult>)_container.Resolve(handlerType);
	return handler.Handle(query);
}
```

All the types to create the IQueryHandler are known from the generic arguments, seems like this type of thing would be possible.

**Comment by nil4** [comment]
@waynebrantley you can write something like that already: see it on [Try Roslyn](http://tryroslyn.azurewebsites.net/#K4Zwlgdg5gBAygTxAFwKYFsDcAoUlaIoYB0AKgBYBOqAhgCb457TxJrplW0PRk0gBrEDmwQa6VCAAONAMaoYAYQD2EEMoA2qAIJSpGsLJrIwq7AG9sMazEhpKAMzkKAkgEVgqSggA8pAEqSwBrIAHww5gC+2FY2dl5O8jAuABI0EHRalD6QMKQeXggANHmBIMFhEbE2NgFBITBpGVp+Bd6hABT5nt4wAI49CACUMADu5F4K3YUwAFzJbb515SGhODU1pPwCfmUV4U2ZOiAIELKtg53TvQOFJYrp8hoaxqYQpMoCqBAwRmeoGiG1Q2NXGkzyizmC0Gu3qYXWNmiwPijmcyRUEGQNEgXiqIOsygARgArVCyZAwMqaABuqC6CCkCmQDNQQwR1iRNSkwEJBlkvxeIBAMAACpRlFBKOJgZZ8TAUK9+dR6KoNAh0aosTjKDAAPqyTXYiBeERy7m8wzyrEmfnU5RgOgwACyRo6KEo+AA2gBdGA0ShQEBAuWyuU2DHqLTEADqHrQABkcR0AEQpAEaZQwaPKSgaOgAQmTbOBNU5+OWFVF4vkQthKzCHXcMIrq36gxGobDMGp/pg5HSR0opBZMAAvDBmYzlA5G4csj4m4U6/sii2wsWu9Yezr+81cePZwP54vvMvVqu9qsRvrDdriFSNLSOrvB8PGRvN9RkMBKD8X1liDnOlbm8D8QTLEEtkEM9KjFZQaxAGDOhPJZL0qEDiiUR501eVQPi+H4/ieYN8U7MNtz7I8vDfBRx0nVBp0PPdshQpCLzhUIwPI3t/33GAmMHBdFjYtdOL1A1MSNLx70kGk6V4ocWS4uUvx/P8qMoQCqO0E4zg6DCSiIgFlMRYFomiIA). I had to improvise a bit since I don't know how `IQuery<>` and `IQueryHandler<>` are declared.

**Comment by HaloFour** [comment]
The following is already legal:

```cs
public interface IQuery<TResult> { }
public interface IQueryHandler<TQuery, TResult> where TQuery : IQuery<TResult> { }

public TResult Process<TResult>(IQuery<TResult> query) {
    Type handlerType = typeof(IQueryHandler<IQuery<TResult>, TResult>);
}
```

However, this is not the same as the code that you're trying to duplicate as you are extracting the run-time type of `query` and using that as a generic type argument, so the closed generic type of `IQueryHandler<,>` is more specific than `IQueryHandler<IQuery<TResult>, TResult>`.  There's no way for the compiler to actually know that run-time type short of you adding another generic type parameter to the `Process` method.

**Comment by waynebrantley** [comment]
@HaloFour Right, as you indicated, if I do it the way I wrote the code, I end up with a different type than the code from @nil4 .  

Essentially, I am trying to get rid of the dynamic as it seems it should not be necessary.
Given this
```
  var handlerType = typeof(IQueryHandler<,>).MakeGenericType(query.GetType(), typeof(TResult));
  dynamic handler = _container.Resolve(handlerType);
```

I know what returns implements the interface of ```IQueryHandler<TQuery, TResult> ``` but I cannot cast it, because to cast it I would need the runtime type of query.

The query parameter will be IAsyncQuery<TResult> of some kind the compiler creates a method for every type when creating the generic.  So, why can't I used that type?   Need to use the final evaluated generic type in the code somewhere.

Any of my ramblings make any sense?

**Comment by HaloFour** [comment]
@waynebrantley 

Unfortunately it is necessary.  In C# `typeof()` expressions are constants and they must be based on types known to the compiler, including generic type parameters.  The compiler can't know the actual run-time type of the `query` parameter.

Let's assume that the C# language could introduce a new expression syntax which would be instead evaluated at run-time.  We'll go with `typeof(IQueryHandler<typeof(query), TResult>`.  The C# compiler would still be forced to emit the equivalent of `typeof(IQueryHandler<,>).MakeGenericType(query.GetType(), typeof(TResult))` because that's the only way that such an expression can be evaluated.  And this new expression form of `typeof()` can't be used in other places that `typeof()` normally could be used, such as with attributes.  And you have the potential of `NullReferenceException` if `query` is `null`, and *potentially* `ArgumentException` if the C# compiler can't ensure that `query` is actually a type that would meet the constraints.

At the end of the day reflection code like this isn't terribly common and isn't onerously verbose or difficult to write.

**Comment by waynebrantley** [comment]
@HaloFour Yes, I get what you are saying.
But in my understanding of the generic types, the classes to implement each generic type are created at runtime by the compiler.  
> At runtime, when your application makes its first reference to List, the system looks to see if anyone already asked for  List<int>. If not, it feeds into the JIT the IL and metadata for List<T> and the type argument int. The JITer, in the process of JITing the IL, also substitutes the type parameter.
http://www.artima.com/intv/generics2.html

So, my thought is once the List<int> is Jitted, it could just as easily used the final type it ended up with in the code.

Are you with me?

**Comment by HaloFour** [comment]
@waynebrantley 

> But in my understanding of the generic types, the classes to implement each generic type are created at runtime by the compiler.

Sorta, but that's an implementation detail and not relevant here.  Either the type handle is something that can be calculated by Roslyn and embedded directly (as a constant) in the assembly metadata, or the type handle must be manually constructed through reflection.  If the generic type arguments aren't known at compile time then there is simply no choice but to do the latter.  What the JIT happens to do with the type handle after that is besides the point.

**Comment by waynebrantley** [comment]
@HaloFour Makes sense.  The IL produced is the same.  It is the jitter that could eliminate this type of reflection when doing generics.  That is too bad.

**Comment by gafter** [comment]
@waynebrantley Do you consider your question to be answered?
