### ISSUE TITLE
Microsoft.CodeAnalysis.VisualBasic.UnitTests.MyTemplateTests.MyWinformApp sporatically failing

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#11278]
http://dotnet-ci.cloudapp.net/job/roslyn_master_win_rel_unit32/1213/

```
Microsoft.CodeAnalysis.Test.Utilities.ExecutionException : 
Execution failed for assembly 'D:\j\workspace\roslyn_master---0938d3a7\Binaries\Temp\'.
Exception: System.InvalidOperationException: An error occurred creating the form. See Exception.InnerException for details. The error is: Font 'Microsoft Sans Serif' does not support style 'Regular'. ---> System.ArgumentException: Font 'Microsoft Sans Serif' does not support style 'Regular'.
 at System.Drawing.Font.CreateNativeFont()
 at System.Drawing.Font.Initialize(FontFamily family, Single emSize, FontStyle style, GraphicsUnit unit, Byte gdiCharSet, Boolean gdiVerticalFont)
 at System.Drawing.Font..ctor(FontFamily family, Single emSize)
 at System.Drawing.SystemFonts.get_DefaultFont()
 at System.Windows.Forms.Control.get_DefaultFont()
 at System.Windows.Forms.Control.GetDefaultFontHandleWrapper()
 at System.Windows.Forms.Control.get_FontHandle()
 at System.Windows.Forms.ContainerControl.GetFontAutoScaleDimensions()
 at System.Windows.Forms.ContainerControl.get_CurrentAutoScaleDimensions()
 at System.Windows.Forms.ContainerControl.get_AutoScaleFactor()
 at System.Windows.Forms.ContainerControl.PerformAutoScale(Boolean includedBounds, Boolean excludedBounds)
 at System.Windows.Forms.ContainerControl.PerformNeededAutoScaleOnLayout()
 at System.Windows.Forms.ContainerControl.OnLayoutResuming(Boolean performLayout)
 at System.Windows.Forms.Control.ResumeLayout(Boolean performLayout)
 at Form1.InitializeComponent()
 at Form1..ctor()
 --- End of inner exception stack trace ---
 at My.MyProject.MyForms.Create__Instance__[T](T Instance)
 at Form1.Main()
---- System.InvalidOperationException : An error occurred creating the form. See Exception.InnerException for details. The error is: Font 'Microsoft Sans Serif' does not support style 'Regular'.
-------- System.ArgumentException : Font 'Microsoft Sans Serif' does not support style 'Regular'.
```

FYI to @jaredpar, as this is a flaky test issue.

**Comment by jaredpar** [comment]
Did some investigation into this.  The failure here, from the research I've done, only occurs when a machine has a corrupted or uninstalled font.  Given that we run this suites on VM images corruption seems to be the problem.  If it were an installation issue it would fail on 100% of the VMs.

Digging deeper it seems there are two actual failures and three cache hits of the failure.  The failures occurred on the following machines:

- dci-win-rbld-10: machine from the static pool.
- Azure0512113138: machine from the dynamic pool.  

Not much to be done for the dynamic pool as the machine is recycled.  The static pool machine though I was able to take a look at.  It has successfully run suites before and since then, although quite rarely.  Hence it doesn't seem to be inherently corrupted.  

I've removed the Urgency tag for now since it only affected two machines and hasn't repo'd on the static pool since then.  

Going forward I'm not entirely sure what to do with this suite.  It is possible to detect this problem when it happens and catch the error.  At that point I could fail the suite which doesn't seem to get us anywhere or I could ignore the failure and let the suite succeed but that's just masking problems.  

Thoughts?

**Comment by jasonmalinowski** [comment]
Is the corruption specific to the font? Would using some other font be better? Can the test be changed in some way to not depend upon font loading at all?

**Comment by jaredpar** [comment]
@jasonmalinowski checked and we have to load some font from what I can see.  Could pick a diff one but don't see any evidence that will make it better / worse.

**Comment by jasonmalinowski** [comment]
Should we open a thread with either WinForms or Windows itself?

**Comment by jaredpar** [comment]
I can mime their response for you: 

> The font is corrupted hence throwing an exception is the right thing to do.

It's hard to argue with that.  If the font is corrupted then they are in a bind.  Can't really render the text unless they have a font to render against.  

Really we need to figure out why the font is getting corrupted, occasionally, on these machines.  That seems trikcy though given it happens so infrequently.

**Comment by jasonmalinowski** [comment]
@jaredpar this failed on the signed build machines just now too. Can this test be disabled, or adjusted so it's not actually needing to load the WinForms assembly? Does this test bring us significant value?

**Comment by jaredpar** [comment]
Unfortunately there is no way to avoid loading fonts here (dug through the code).  Think we need to just disable this test.  Want to take one last look at the machine state when this happens.  So leaving open till next failure then will disable.

**Comment by jasonmalinowski** [comment]
@jaredpar There was a failure this morning in our 20160824.5 signed build.

**Comment by jaredpar** [comment]
Link?
