### ISSUE TITLE
Language Feature: allow typeof on any expression

### ISSUE THREAD

**Issue by lostmsu** [dotnet/roslyn#11286]
Example usage:

``` csharp
class MyControl: Control {
  public long MyProperty{ ... }
  public static DependencyProperty MyPropertyProperty =
    DependencyProperty.Register(name: nameof(MyProperty), type: typeof(MyProperty));
}
```

Currently, type: typeof(MyProperty) is not allowed.
If any expression is impossible, can allow on some, like type members.

**Comment by HaloFour** [comment]
See #11265.

This would be a breaking change and introduce ambiguities into the language in the following scenario:

```cs
public class MyProperty { }

class MyControl: Control {
  public long MyProperty{ ... }
  public static DependencyProperty MyPropertyProperty =
    DependencyProperty.Register(name: nameof(MyProperty), type: typeof(MyProperty));
}
```

**Comment by dsaf** [comment]
Maybe somehow via #1653?

**Comment by HaloFour** [comment]
@dsaf 

I could see that working:  `memberof(MyProperty).Type`

**Comment by alrz** [comment]
@HaloFour you could disambiguate it via a parenthesised expression,
```cs
typeof(MyProperty) // MyProperty class
typeof((MyProperty)) // MyProperty property
```
 `memberof(MyProperty).Type` wouldn't be a constant anymore.

**Comment by HaloFour** [comment]
@alrz 

Changing the entire nature of the statement based on a second set of parenthesis seems very confusing.  I'd rather consider a method reference-like syntax:

`typeof(MyControl::MyProperty)`

Although that specific syntax would also be a breaking change if you have a type `MyProperty` under a reference alias `MyControl`.  But something along those lines.

> `memberof(MyProperty).Type` wouldn't be a constant anymore.

That it wouldn't, which isn't necessary for this specific use case but I agree would be nice.

**Comment by alrz** [comment]
@HaloFour Method reference is still an expression and makes a little sense to be special cased in this context. However, #10972 proposes that it should be a compile-time constant for `typeof`, I think same is applicable to something like "`memberof`".

**Comment by HaloFour** [comment]
@alrz

I meant using the syntax, not actually creating a delegate that happens to point to the given member.  `memberof` only gets you part of the way there, though.  You'd still need syntax to extract the type.  I'd be fine if the compiler would evaluate said expressions as constants, though.

**Comment by lostmsu** [comment]
@HaloFour , how about introducing new keyword? Like expressiontype(any_definitely_typed_expression)?

**Comment by s-arash** [comment]
typeof(() => expr) could easily be a method:
Type TypeOf<T>(Expression<Func<T>> expr)

**Comment by gafter** [comment]
We are now taking language feature discussion in other repositories:
- https://github.com/dotnet/csharplang for C# specific issues
- https://github.com/dotnet/vblang for VB-specific features
- https://github.com/dotnet/csharplang for features that affect both languages

Features that are under active design or development, or which are "championed" by someone on the language design team, have already been moved either as issues or as checked-in design documents. For example, the proposal in this repo "Proposal: Partial interface implementation a.k.a. Traits" (issue 16139 and a few other issues that request the same thing) are now tracked by the language team at issue 52 in https://github.com/dotnet/csharplang/issues, and there is a draft spec at https://github.com/dotnet/csharplang/blob/master/proposals/default-interface-methods.md and further discussion at issue 288 in https://github.com/dotnet/csharplang/issues. Prototyping of the compiler portion of language features is still tracked here; see, for example, https://github.com/dotnet/roslyn/tree/features/DefaultInterfaceImplementation and issue 17952.

In order to facilitate that transition, we have started closing language design discussions from [the roslyn repo](https://github.com/dotnet/roslyn) with a note briefly explaining why. When we are aware of an existing discussion for the feature already in the new repo, we are adding a link to that. But we're not adding new issues to the new repos for existing discussions in this repo that the language design team does not currently envision taking on. Our intent is to eventually close the language design issues in the Roslyn repo and encourage discussion in one of the new repos instead.

Our intent is not to shut down discussion on language design - you can still continue discussion on the closed issues if you want - but rather we would like to encourage people to move discussion to where we are more likely to be paying attention (the new repo), or to abandon discussions that are no longer of interest to you.

If you happen to notice that one of the closed issues has a relevant issue in the new repo, and we have not added a link to the new issue, we would appreciate you providing a link from the old to the new discussion. That way people who are still interested in the discussion can start paying attention to the new issue.

Also, we'd welcome any ideas you might have on how we could better manage the transition. Comments and discussion about closing and/or moving issues should be directed to https://github.com/dotnet/roslyn/issues/18002. Comments and discussion about this issue can take place here or on an issue in the relevant repo.

-----------------

I am not moving this particular issue because I don't have confidence that the LDM would likely consider doing this.
