### ISSUE TITLE
Some arithmetic operations of float (Single) constants are broken in Visual Studio 2015 Update 2

### ISSUE THREAD

**Issue by zijianhuang** [dotnet/roslyn#11311]
**Version Used**: 

Visual Studio 2015 Professional Update 2

**Steps to Reproduce**:

`        [TestMethod]
        public void TestFloatConst()
        {
            Assert.AreNotEqual(0f, 0.1f + 0.2f - 0.3f);//Broken in VS 2015 Update 2
        }

        [TestMethod]
        public void TestFloatConstComparison()
        {
            Assert.AreNotEqual(0.3f, 0.1f + 0.2f);//Broken in VS 2015 Update 2
        }

        [TestMethod]
        public void TestDoubleConst()
        {
            Assert.AreNotEqual(0d, 0.1d + 0.2d - 0.3d);
        }

        [TestMethod]
        public void TestDoubleConstComparison()
        {
            Assert.AreNotEqual(0.3d, 0.1d + 0.2d);
        }

        [TestMethod]
        public void TestDecimalConst()
        {
            Assert.AreEqual(0m, 0.1m + 0.2m - 0.3m);
        }

        [TestMethod]
        public void TestFloatVariable()
        {
            var a = 0.1f;
            var b = 0.2f;
            var c = 0.3f;
            Assert.AreNotEqual(0f, a+b-c);//OK in both debug and release builds
        }

`

**Expected Behavior**:

0.1+0.2 is expected to be 0.30000000000000004 in floating point calculation

**Actual Behavior**:

As shown in the test cases, and consistent across .NET 4.0, 4.5 and 4.6.1 compiled by the same compiler (roslyn) of VS 2015 Update 2. 

All test cases pass green in VS 2012, 2013 and 2015 Update 1.

**Comment by HaloFour** [comment]
I don't know what it did prior to Update 2 but looking at the IL I see that the Roslyn compiler is performing the calculation at compile time, so you ultimately end up with `Assert.AreNotEqual(0.3f, 0.3f);`

I don't understand the point of such a test, though.  Floating point values are just as imprecise with inequality as they are with equality.  You should expect the two values to be equal within epsilon, nothing else.

**Comment by zijianhuang** [comment]
@HaloFour, so the new behavior in update 2 is by design? some sort of improvement? however, not consistent with test case TestFloatVariable() which calculation is done at runtime. The point is that floating point calculations should have consistent behavior while presumably the calculation is done in the floating point unit of a processor either in compile time or runtime, so programmers who have little idea of the dangers of floating data in monetary calculations won't accidentally use floating types rather than decimal/currency types for monetary calculations.

**Comment by HaloFour** [comment]
@zijianhuang 

> so the new behavior in update 2 is by design? some sort of improvement?

Beats me, that's just what I suspected what I saw your issue.

> however, not consistent with test case TestFloatVariable() which calculation is done at runtime.

The difference is the assignment to variables and then performing the calculation on variables, which is different than performing the calculation on literals/constants.  The compiler is free to make optimizations in those cases.  Frankly, it's free to make optimizations in both cases, but it doesn't have to be consistent about it.

> The point is that floating point calculations should have consistent behavior while presumably the calculation is done in the floating point unit of a processor either in compile time or runtime, so programmers who have little idea of the dangers of floating data in monetary calculations won't accidentally use floating types rather than decimal/currency types for monetary calculations.

The point is that floating point values and calculations are imprecise.  You can't know how the calculation will be done at run-time, and the CLR spec allows for implementations to carry them out differently.  The only thing that should be consistent is equality within the tolerance of epsilon.  There's nothing in the spec (either C# or CLR) that dictates that your test should pass.  I don't believe that the fact that the test fails now indicates a regression in the compiler.

**Comment by gafter** [comment]
This behavior is by design. See #7262 for the error report whose bug fix results in the behavior you are seeing.  The C# compiler now performs compile-time floating-point operations on constants correctly according to IEEE rules for that data type (i.e. using no excess precision), instead of trying to guess what would occur on whatever runtime you decide to run the program, or allowing the generated assembly's behavior to depend on the compile-time platform. Operations on non-constants, such as those in your program, may occur in extended precision.

> 0.1+0.2 is expected to be 0.30000000000000004 in floating point calculation

That is true for a `double` calculation. This is not a `double` floating-point calculation. It is a `float` floating-point calculation. The reason for the difference you see is that you are depending on undefined behavior in the C# language specification (quoted below). 

> ### 4.1.6 Floating-point types
Floating-point operations may be performed with higher precision than the result type of the operation. For example, some hardware architectures support an “extended” or “long double” floating-point type with greater range and precision than the `double` type, and implicitly perform all floating-point operations using this higher precision type. Only at excessive cost in performance can such hardware architectures be made to perform floating-point operations with less precision, and rather than require an implementation to forfeit both performance and precision, C# allows a higher precision type to be used for all floating-point operations. Other than delivering more precise results, this rarely has any measurable effects. However, in expressions of the form `x * y / z`, where the multiplication produces a result that is outside the `double` range, but the subsequent division brings the temporary result back into the `double` range, the fact that the expression is evaluated in a higher range format may cause a finite result to be produced instead of an infinity. To force a value of a floating point type to the exact precision of its type, an explicit cast can be used.

A concise demonstration of the underlying issue you're seeing is the following:

```cs
using System;

class Program
{
    static void Main(string[] args)
    {
        float f1 = 0.1f, f2 = 0.2f, f3 = 0.3f;
        float sum = f1 + f2;
        PrintFloat(f3, "f3");
        PrintFloat(sum, "sum");
        PrintFloat(sum - f3, "sum - f3");
        Console.WriteLine();
        sum = (float)(f1 + f2); // same as before, but with a cast
        PrintFloat(sum, "sum");
        PrintFloat(sum - f3, "sum - f3");
    }

    private static void PrintFloat(float value, string name)
    {
        Console.WriteLine($"{value:g17} == {name}"); // print all precision
    }
}
```

Which outputs, for me,

```none
0.300000012 = f3
0.300000012 = sum
-7.4505806e-09 = sum - f3

0.300000012 = sum
0 = sum - f3
```

If you want reproducible floating-point behavior, you need to cast every intermediate result to an appropriate floating-point type.
