### ISSUE TITLE
Use Multi-Line String Literal in VB Unit Test

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#11315]
Since the VB language now supports multi-line string literals, it now possible to rewrite the unit test to use them. Instead of the current work around of

``` vb
<![CDATA[
             Namespace N1.N2(of T)
             End Namespace
        ]]>.Value
```

It should reduce allocations as in doesn't build a XML Node.

Possible analyzer and code-fix for someone to write?

**Comment by jmarolf** [comment]
> It should reduce allocations as in doesn't build a XML Node.

Do we have memory pressure issues in tests? I have no problem with ensuring new tests use string literals where it makes sense but there is not need to change the existing tests.

**Comment by AdamSpeight2008** [comment]
> **@jmarolf wrote:** 
>Do we have memory pressure issues in tests?

 Potentially. I suspect *(ie not tested)* that the tests would also run slightly quicker.

**Comment by jmarolf** [comment]
If you can prove that the tests would be perceptibly quicker then I'm all for it.

**Comment by CyrusNajmabadi** [comment]
We shoudl do this just because the current approach was a major cludge to get around VB's lack of multiline literals at the time.

Xml literals are good for when we have structured data (like Workspace literals).  For multiline purposes they serve no purpose.  

That said, since the tests work and are fine, this will likely never be assigned to someone to do.  So if you're actually passionate about this Adam, i'd just do the work if i were you.  Otherwise, i'm not seeing much value in actually keeping this issue around.

**Comment by AdamSpeight2008** [comment]
@CyrusNajmabadi 
The XML-Literal approach does effectively make it a verbatim string, but now has different escaped characters.

**Comment by AdamSpeight2008** [comment]
- [ ] Implement an overload of `CreateCompilationWithReferences`  that accepts a string for the first parameter. Maybe a collection of strings?

**Comment by AdamSpeight2008** [comment]
Initial PR #12551
Converting over to Mulit-Line String Literals.
Targeting `expectedOutput` and `expectedIL` and simple `source` or `compilation`

**Comment by AdamSpeight2008** [comment]
Though not perfect the unit-test timings from the PR build system, suggest (to me at least) that it worth continuing pursuing the change. As we approaching over a minute of savings so far.

**Comment by gafter** [comment]
We would consider doing this as a target of convenient opportunity.
