### ISSUE TITLE
Find All references doesn't find static imports of modules

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#11366]
``` VB
Imports StaticModule

Public Class Class1

    Public Sub Foo()

        ValidateArgumentNotNothing(Nothing, Nothing)

    End Sub

End Class

Namespace StaticModule

    Friend Module ArgumentValidation

        Public Sub ValidateArgumentNotNothing(ByVal argument As Object, ByVal parameter As String)

        End Sub

    End Module
End Namespace
```

Find All References on `ArgumentValidation`

__Expected:__ 1 usage
__Actual:__ No usages

Ran into this here: https://github.com/dotnet/roslyn-project-system/pull/156.

**Comment by Pilchie** [comment]
Is there a way we could cascade out from a module to the members of it to find this sort of thing?

**Comment by CyrusNajmabadi** [comment]
Possibly.  Though i'm on the fence about this one.  For example, if i have an extension method in a class "C", then FAR on "C" won't show you results at extension method callsites.

That said, i'm sympathetic about this issue.  In general we tend to not show implicit references (usually because they're hard to find in the first place).  But it's a reasonable request to still want to see them.

**Comment by CyrusNajmabadi** [comment]
I'm going to close this out.  this is very far out from anything supported by FAR today.  For example, if you FAR on a namespace, we don't find the implicit references to them when you access them through types.  If you FAR on a type, we don't find that type if you accessed it through a static extension method in it that you invoked as an instance method.  etc. etc.

**Comment by davkean** [comment]
I don't agree on this - basically leads me to not be able to trust results of FAR. I'm trying to use it find dead code. You don't delete namespace to remove dead code, so I don't care about the results of them.

Don't really understand the complexity here in Roslyn - from a static binary reader standpoint I can see how I would approach this.

**Comment by CyrusNajmabadi** [comment]
> from a static binary reader standpoint I can see how I would approach this.

Roslyn FAR doesn't operate on metadata.  It operates on source, and it works in manner whereby it tries to be efficient about finding references, but in a way that means it might not find 'implicit' references.  Specifically, when you do a FAR operation on a symbol, we have to go search the entire solution to see if there are references to that symbol.  

1. Literally binding everything in the solution would be far too slow.  You'd effectively pay the price you have today to compile everything just to do a FAR.
2. The compiler has no public APIs today to find implicit references to symbols.  The IOperation APIs will let us get this information in the future, but we're still not going to be able to use them for this purpose due to '1'.

The solution we have for this are effectively 'smarts' that tell us, lexically and syntactically, "you should look over here to see if this piece of code binds to the symbol the user is looking for".  The problem space then decreases from having to search through the set of all symbols to the set of *likely* symbols.

We decided on lexical and syntactic smarts because it means that we can keep all our indices up to date on a file by file basis.  i.e. a modification to a file means we only need to update the index for that file.  

> basically leads me to not be able to trust results of FAR.

That may be a limitation we just have to accept.  As mentioned already, this limitation exists with several language constructs.  Search for a static type and we won't find the references to it through extension method calls.  Search for implicit operators and we simply won't find them at all.  Search for special intrinsics (like GetAwaiter) and we won't find them.  Search for a normal type and you won't see references through it to statics accessed by inner classes.  etc. etc.

We optimized FAR for being efficient for the 99.9% use case.  i.e. the user searching for normal symbols that are referenced explicitly in code.  FAR is very fast and accurate for those cases.  Building a system for implicit cases just hasn't been warranted.

Now, if you want, feel free to reopen.  But i would put this on the backlog as it would be a lot of of work to enable just a couple of corner case scenarios for this feature.
