### ISSUE TITLE
workspace.ProjectTracker.DocumentProvider.TryGetDocumentForFile throws exception absolute path required for dynamic documents

### ISSUE THREAD

**Issue by sheetalkamat** [dotnet/roslyn#11400]
**Version Used**: 
Latest

**Steps to Reproduce**:

1. https://github.com/Microsoft/TypeScript/issues/8214  build and run project from here
2. Notice the dynamic document is created and there is no hovering data tool tip or outlining on the file since the document is not created. (we are not creating the Roslyn document right now because it throws the exception)

**Expected Behavior**:
No exception and the document should be created

**Actual Behavior**:
Exception is thrown

workspace.ProjectTracker.DocumentProvider.TryGetDocumentForFile should work for dynamic documents that get created during debugging (hence no absolute path). The documents have the name like ^ScriptDocument app.ts and there is no backing typescript file for it on the disk.

**Comment by jasonmalinowski** [comment]
What's the exception?

**Comment by sheetalkamat** [comment]
It fails in 
```c#
        public FileTextLoader(string path, Encoding defaultEncoding)
        {
            FilePathUtilities.RequireAbsolutePath(path, "path");

            _path = path;
            _defaultEncoding = defaultEncoding;
        }
```

**Comment by Pilchie** [comment]
What's the right thing here?  It seems like this shouldn't be using `StandardTextDocument`, which expects to be backed by an on-disk file.

**Comment by jasonmalinowski** [comment]
We don't have support for dynamic documents at all in VS, given VS's weak support for them in the first place. @sheetalkamat you're definitely going outside our expected support here. What's your scenario?

**Comment by sheetalkamat** [comment]
This is needed to make sure that the dynamic document created as part of debugging (because the text didn't match or because the file doesn't exist on the disk) should be able to hover over and show evaluation result. Currently the tooltip doesn't show up because Roslyn cant find the document being hovered over. There are many instances in debugging that land up creating these dynamic documents which aren't backed by the file on the disk.. They are sort of readonly files with content known if that would help fix this somehow.

**Comment by Pilchie** [comment]
It still sounds to me like either:

* these should not be using `StandardTextDocument`
* They should be explicitly saved to the temp directory and loaded from there.  As @jasonmalinowski notes, VS generally doesn't do very well with truly dynamic documents 😦

**Comment by mhegazy** [comment]
@Pilchie, we never create a `StandardTextDocument`, all we use is `Workspace.ProjectTracker.DocumentProvider.TryGetDocumentForFile`, and this does not allow us any way to say that we do not need a backing document on disk. moreover, we really have no way of sub classing/overriding the Document implementation. 

Saving to disk is not really a good option here either since this is a debugger extension, and these files are dynamical loaded from source map files or loaded from script tags. We do not really have control when they are created, and or when they should be deleted.

This results in all our LS operations to be failing on dynamic documents created by the debugger, which is a rather common thing for JS/TS. What is the alternative here?
