### ISSUE TITLE
It is possible for slow analyzers to be cancelled before reporting all diagnostics.

### ISSUE THREAD

**Issue by VSadov** [dotnet/roslyn#11470]
When compiler is done compiling it signals to the queue that it is complete. That currently cancels all pending listeners.
In a case of slow analyzers it could lead to randomly dropping some diagnostics.

One way to repro: 

Add some random delays to AsyncQueue.Enqueue, like

```C#
for(int i = 0; i < 1000000; i++) {Task.Yield();}
 ```
run tests. 
Tests like NoWarnAndWarnAsError_InfoDiagnostic for both C# and VB may fail.

**Comment by mavasani** [comment]
> That currently cancels all pending listeners. In a case of slow analyzers it could lead to randomly dropping some diagnostics.

I don't understand how this is possible. All the pending listeners [here](http://source.roslyn.io/#Microsoft.CodeAnalysis/DiagnosticAnalyzer/AsyncQueue.cs,183), when queue is being marked complete, should be waiting on DequeueAwaitAsync - they shouldn't be executing analyzers. If all background threads attempting to run analyzers were waiting on DequeueAwaitAsync, then it must mean all events have been processed, otherwise EnqueueCore would ensure that it dequeues one of those waiters and hands it out the new event to process.

I guess my question is: do you have a proposed sequence of steps where you see some event being dropped or partially processed based on your theory?

I feel only possibility of missing out on some diagnostics or analyzer execution seems to be if [GetDiagnosticsAsync](http://source.roslyn.io/Microsoft.CodeAnalysis/R/d749fc73955832f4.html) is being called by the command line compiler before the compilation queue is complete. Otherwise, we would always wait for the driver's [WhenCompletedTask to finish](http://source.roslyn.io/#Microsoft.CodeAnalysis/DiagnosticAnalyzer/AnalyzerDriver.cs,534), which guarantees that [DiagnosticQueue is complete](http://source.roslyn.io/#Microsoft.CodeAnalysis/DiagnosticAnalyzer/AnalyzerDriver.cs,376) for dequeueing diagnostics.

**Comment by mavasani** [comment]
+@gafter for expertise on AsyncQueue.

**Comment by mavasani** [comment]
> for(int i = 0; i < 1000000; i++) {Task.Yield();}

Where in AsyncQueue.Enqueue should I add this code to repro it locally?

**Comment by VSadov** [comment]
@mavasani  anywhere in AsyncQueue.Enqueue. Could be the start of the method.

Note that now the queue contains a mitigation for the race and waits 10 sec. for the items to be consumed. That could make reproducing much harder.

You probably should remove that code while reproducing. 

Also, even if eventual solution will end up doing similar spin-wait. Doing that in inside the queue is not the right place. As @gafter  tells me, there are plans to productize async queue and in such case the spinwait would clearly be out of place inside the queue implementation.
At very least the delay should be a parameter to the Complete method.

**Comment by VSadov** [comment]
I am not very familiar with the overall protocol of the queue, but the diagnostics is definitely being dropped when analyzers are slow.
My theory is that we set the tcs to cancel after we are done compiling. After that analyzers are unable to fetch events since all attempts to get anything from the queue would result in cancellation. If any of those events would otherwise result in a diagnostics, such diagnostics gets effectively lost.

I am not sure what is the right solution here. It seems that we want to be able to cancel/complete the build, but we also want deterministic diagnostics. I do not know what we want more.

**Comment by mavasani** [comment]
> My theory is that we set the tcs to cancel after we are done compiling. After that analyzers are unable to fetch events since all attempts to get anything from the queue would result in cancellation

The waiters/threads getting cancelled on TryComplete, is per the protocol. However, all waiters cannot get cancelled without processing the events, ensuring all events are processed and diagnostics are raised. I feel the race condition is not due to us cancelling the waiters on complete, it is somewhere else. I'll investigate further to see if I can get some context on the failure.

**Comment by mavasani** [comment]
NOTE: Cancelling the existingWaiters in TryComplete doesn't cancel analysis - it cancels just the threads that were waiting on DequeueAsync on the event queue. Other threads should pick up the unprocessed events and continue analysis/reporting diagnostics.

**Comment by VSadov** [comment]
I do not think other threads can process events after queue is in completed state. It seems like their attempts to fetch anything from the queue would be eagerly cancelled. But I could be wrong.

Also once the queue is in complete state and waiters are cancelled, WhenCompletedTask is signaled so getting diagnostics does not block and gets whatever is in the diagnostics queue at that time.

**Comment by mavasani** [comment]
> I do not think other threads can process events after queue is in completed state. It seems like their attempts to fetch anything from the queue would be eagerly cancelled.

You cannot enqueue into a completed queue, but dequeue will work till count is zero. See [here](http://source.roslyn.io/#Microsoft.CodeAnalysis/DiagnosticAnalyzer/AsyncQueue.cs,245)

> Also once the queue is in complete state and waiters are cancelled, WhenCompletedTask is signaled so getting diagnostics does not block and gets whatever is in the diagnostics queue at that time.

[AsyncQueue.WhenCompletedTask](http://source.roslyn.io/Microsoft.CodeAnalysis/R/cb1badb0a8c80563.html) is only referenced by tests. I was talking about [AnalyzerDriver.WhenCompletedTask](http://source.roslyn.io/#Microsoft.CodeAnalysis/DiagnosticAnalyzer/AnalyzerDriver.cs,708), which ensures that all tasks processing events and executing analyzers have complated, and it also has a [sychronous continuation](http://source.roslyn.io/#Microsoft.CodeAnalysis/DiagnosticAnalyzer/AnalyzerDriver.cs,376) to ensure diagnostic queue is complete - so awaiting the driver's when completed task should guarantee all analyzers have executed and diagnostics reported.

**Comment by mavasani** [comment]
@VSadov I also noticed that the test flakiness/fix was only done in future branch - can't the fix be reproed in master? There were no differences between master and future branch in analyzer driver/async queue prior to your fix.

**Comment by mavasani** [comment]
Okay, so I found at least one bug in the command line compilers in the future branch: We are invoking GetAnalyzerDiagnostics in a code path without completing trees. See [here](https://github.com/dotnet/roslyn/blob/future/src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs#L512). If `compilation.CompileMethods` returns false, then we will attempt to get analyzer diagnostics without completing trees - this will lead to partial analyzer diagnostics.

**Comment by mavasani** [comment]
I added lot of random delays in AsyncQueue.Enqueue and tried to repro this in both master and future branch (in future I also commented out 10s spin wait added by Vlad). I ran the mentioned test in a loop for more than 30 minutes and also tried running all command line tests multiple times. I am still unable to repro the missing diagnostic failure. Unless we have a repro, even if it happens once in 5-10 times, there is not much actionable here. @VSadov can you verify this still repros after your command line compiler fix?

**Comment by srivatsn** [comment]
This has been fixed by Vlad.
