### ISSUE TITLE
<param/> incorrectly offered within summary, exception, etc.

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#11487]
1. At $ CTRL+Space

``` C#
        /// <summary>
        ///     Returns a value indicating whether the current project has the specified capability
        /// </summary>
        /// <exception cref="ArgumentNullException">
        ///     <$
        /// </exception>
        bool Contains(string capability);
```

Expected: `<param name="capability"` to not show up
Actual: `<param name="capability"` shows up.

`<param/>` is a sister tag to summary and exception, and shouldn't show inside them. You want `<paramref` instead to refer to parameter names.

**Comment by lorcanmooney** [comment]
It's not just `param`; `typeparam`, `returns` and `value` also behave the same, and I'm pretty sure they're all top-level-only tags as well.

In C# at least, it's caused by [`GetTagsForSymbol`](https://github.com/dotnet/roslyn/blob/0eb87a517bfb30cb4676c58d4539966e8da8d1b9/src/Features/CSharp/Portable/Completion/CompletionProviders/XmlDocCommentCompletionProvider.cs#L148) which handles both top-level and "name" attribute suggestions, but it doesn't specifically check for the former.

VB seems to have the same/similar behaviour, but with a completely different implementation. A lot of the logic could be shared via the base class, with just the syntax queries left in the language-specific implementations.
