### ISSUE TITLE
Make reformat on rename optional.

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#1156]
After an rename operation the editor? does a reformatting of the document / project / solution (depending on what is selected). This should be an option for the developer to decide.

**Comment by Pilchie** [comment]
It should only reformat the spans that are affected by the rename, not the whole document.  Are you seeing something different?

**Comment by AdamSpeight2008** [comment]
It just effects the renames, but should it if the pretty printer is turned off.

**Comment by dpoeschl** [comment]
Hi @AdamSpeight2008, can you give an example of what's being formatted unacceptably? Rename can cause new code to be introduced (by qualifying members, introducing casts, etc.) and we probably really do need to format that new code regardless of the setting (sometimes the unformatted code produced by our syntax generation APIs don't even have forced spaces between words until they are formatted). But maybe you're referring to a simpler situation where an identifier is directly renamed with no new code introduced as a result and yet suddenly your code is formatted differently. Some clarity on the scenario will help us figure out how to handle this, and also to determine if it's a problem just with rename or with all of our refactorings. Thanks!

**Comment by AdamSpeight2008** [comment]
@dpoeschl  I'll describe my view
Let's say that I have the following.
```
  |0000000000000000111111111111111122222222222222223333333333333333
  |0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF
--+----------------------------------------------------------------
00|Public Function Foo( xxxx As Integer,
01|                     yyyy As Integer ) As Integer
02|  Return xxxx + yyyy
03|End Function
04|
```
then I rename `xxxx` to `xx`, this is what I'd expected
```
  |0000000000000000111111111111111122222222222222223333333333333333
  |0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF
--+----------------------------------------------------------------
00|Public Function Foo( xx   As Integer,
01|                     yyyy As Integer ) As Integer
02|  Return xxxx + yyyy
03|End Function
04|
```
Actual result
```
  |0000000000000000111111111111111122222222222222223333333333333333
  |0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF
--+----------------------------------------------------------------
00|Public Function Foo( xx As Integer,
01|                     yyyy As Integer ) As Integer
02|  Return xxxx + yyyy
03|End Function
04|
```

The existing `(x,y)` positions of other element shouldn't be affected. If the user has decided to turn of automatic syntax formatting (for whatever reason) the IDE should respect that.

**Comment by dpoeschl** [comment]
@AdamSpeight2008 Thanks for the clarification. I think there are actually three things going on here:

1. There does appear to be a regression from VS2013 where we now format VB code on paste & save even if pretty listing is disabled. We should look through the set of places we invoke formatting to ensure they either check the pretty listing option first or document why they choose to ignore the option.
I've filed this separately as #1944

2. Rename appears to format more than it should in some cases. Consider this case:
    ```VB
    Sub M(abc As Integer) ' Rename abc to def
        Dim a     = 7
        Dim bbbbb = 7
    End Sub
    ```
The declaration of a is formatted even though we've only renamed a parameter. This is a bug in Rename.
I've filed this separately as #1945

3. For the specific case you listed, what would you expect to happen if ```xxxx``` were renamed to ```xxxxxx```? The ```As Integer``` part would be forced to the right, and things go out of alignment anyway, unless that operation goes and adds spaces after the ```yyyy``` to keep the alignment. It seems like rather than needing *no formatting*, you'd actually need a new type of (somewhat aggressive) formatting that looks for and maintains vertically aligned elements. This part seems like a broader formatting topic that could impact other refactorings as well (nothing currently preserves or forces specific **columns** in this way).
Let's continue to use this bug (#1156) for this discussion separately from items 1 and 2 above. I'm removing the milestone so this can be retriaged. If we think that column-aligned coding styles are prevalent enough to justify this work, then we'll need to engage the formatting experts.

**Comment by dpoeschl** [comment]
@Pilchie Do we have telemetry about how many people turn off VB prettylisting? That could give us a starting point for estimating how many people try to style their code this way...

**Comment by AdamSpeight2008** [comment]
@dpoeschl On case 3. Personally if the new name is longer, then adjusting only the affected lines.

The user may go to do additional formatting manually that ok. We (the IDE) should respect that if the user has explicitly told it to apply automatic formatting.. If the line also has user based formatting, that should also remain unaffected.

If the new name is shorter, add whitespace (spaces) after the name, to maintain the existing placement.

-----
> If we think that column-aligned coding styles are prevalent enough to justify this work, then we'll need to engage the formatting experts.

Or making it easier for others to implement custom formatting styles, or complex rule based styles.

**Comment by Pilchie** [comment]
I don't think formatting will ever add this sort of heuristic to try to align things sometimes but not other times.  As you both suggested, I think this would be better served by richer formatting rules (either in the box or through extensibility).  I'm going to close this bug though, as there isn't anything actionable here in the short term, and nothing specific to rename.
