### ISSUE TITLE
Provide a public API to parse generated names

### ISSUE THREAD

**Issue by pharring** [dotnet/roslyn#11565]
I'd like to have a public API to parse compiler generated names, such as `PlatformBlobStore+<>c__DisplayClass52_0+<<TryReferenceInternalAsync>b__0>d.MoveNext` so that I can build more user-friendly names.

It would appear that [`GeneratedNames.TryParseGeneratedName`](https://github.com/dotnet/roslyn/blob/56f605c41915317ccdb925f66974ee52282609e7/src/Compilers/CSharp/Portable/Symbols/Synthesized/GeneratedNames.cs#L276) is a good start.

Apart from my own scenario (providing friendly names in stack views for performance traces), I've heard of other interesting scenarios:
1. In the xUnit runner to show better stacks in async cases (@jasonmalinowski)
2. In scripting (@tmat).
3. Xamarin Workbooks (@tmat)

**Comment by pharring** [comment]
+1 from the App Insights team

**Comment by CyrusNajmabadi** [comment]
This would need to go through an API proposal.  in general, the reason we don't just make things public is because it increases maintenance costs and locks down our ability to change things in teh future.  We can open things up, but we have a process that requests need to go through to make sure the appropriate people weigh in and the right API shape is determined and shipped.
