### ISSUE TITLE
Proposal: Support other assignment operators as part of the object initializer 

### ISSUE THREAD

**Issue by eyalsk** [dotnet/roslyn#11602]
So as an example, today to combine flags you have to do something like this:

```
XmlReaderSettings settings = new XmlReaderSettings {
    ValidationType = ValidationType.Schema
};

settings.ValidationFlags |= XmlSchemaValidationFlags.ProcessInlineSchema;
settings.ValidationFlags |= XmlSchemaValidationFlags.ProcessSchemaLocation;
settings.ValidationFlags |= XmlSchemaValidationFlags.ReportValidationWarnings;
```

We can't use the or assigning operator as part of the object initializer, so this proposal aims to change that by allowing it like this: (based on @HaloFour's suggestion.)

```
var settings = new XmlReaderSettings {
    ValidationType = ValidationType.Schema,
    ValidationFlags |= (XmlSchemaValidationFlags.ProcessInlineSchema 
                       | XmlSchemaValidationFlags.ProcessSchemaLocation 
                       | XmlSchemaValidationFlags.ReportValidationWarnings)
};
```

A very small proposal but nonetheless useful.

**Comment by HaloFour** [comment]
The only reason that the results are different between your two cases is because `XmlReaderSettings.ValidationFlags` has a default set of flags.  An initializer will overwrite it regardless of the syntax.  Your proposed syntax doesn't imply that you intended to add those flags to the existing value.  In fact, your proposed syntax is legal syntax already if you add a `using static`.

Instead I might propose to allow the other assignment operators in an object initializer:

```cs
var settings = new XmlReaderSettings {
    ValidationType = ValidationType.Schema,
    ValidationFlags |= (XmlSchemaValidationFlags.ProcessInlineSchema | XmlSchemaValidationFlags.ProcessSchemaLocation | XmlSchemaValidationFlags.ReportValidationWarnings)
};
```

**Comment by eyalsk** [comment]
@HaloFour thanks, I'll update the suggestion. :)
