### ISSUE TITLE
Cannot open projects in the Roslyn solution in VS2015 with Update 2

### ISSUE THREAD

**Issue by adamralph** [dotnet/roslyn#11634]
**Version Used**: 
A fresh installation of "Visual Studio Enterprise 2015 with Update 2".

**Steps to Reproduce**:

1. Open Roslyn.sln

**Expected Behavior**:

The solution and all its projects are loaded.

**Actual Behavior**:
Most of the projects are not loaded. If I right click -> "Reload Project" on one of them, e.g. Scripting, I get:

![image](https://cloud.githubusercontent.com/assets/677704/15630189/92b7e2e6-252f-11e6-9906-516565b34411.png)

If I click "Install", I get the VS setup dialog, but, unsurprisingly, I have no option to install Update 1 because I'm already on Update 2.

**Comment by Pilchie** [comment]
I believe @rchande was already looking at this, but in our experience if you pick `Skip`, and then when the solution has finished loading, manually go find the project and choose to reload in the Solution Explorer context menu, then it *does* load successfully.

We haven't figured out the root cause yet though :-(

**Comment by adamralph** [comment]
@Pilchie I found the cause. It was because I didn't have the VS SDK installed. I added it via the VS setup   dialog and now all the projects load successfully.

So, the dialog regarding Update 1 is extremely misleading. I guess you may want to document this somewhere to prevent more people tripping over like I did.

I'll leave this issue open in case you want to use it track documentation of this. Feel free to close it otherwise.

**Comment by adamralph** [comment]
BTW - I already was loading the project manually. I guess the problem you are referring to is something else.

**Comment by jaredpar** [comment]
The underlying issue here turned out to be the lack of the VS SDK being installed.  @Pilchie do we have a bug on the VS team to have a clearer error message here?

**Comment by davkean** [comment]
This bug is a portable bug, we basically register a query that runs after a project has failed to open, that causes this dialog to show - that query thinks that "Update 1" isn't installed, when clearly it is implicitly installed by Update 2.

**Comment by davkean** [comment]
Without that query, the project would have failed to load with an error about missing targets.

**Comment by adamralph** [comment]
It sounds like the error about missing targets would be much more helpful. Presumably it would contain some clue to the VS SDK being absent.

**Comment by davkean** [comment]
Absolutely, it's a mistake that this dialog is showing - the check for Update 1 is supposed to succeed, and hence it shouldn't kick in.

**Comment by adamjcook** [comment]
Actually, in my case, I have the Visual Studio Extensibility Tools installed (always had them) and I cannot load this solution. See below.

![image](https://cloud.githubusercontent.com/assets/654607/15966042/d6f08ef2-2ee6-11e6-8da5-cd0eec3105d2.png)

Attempting to reload the "Rolsyn" project (among many others) yields the following message:

![image](https://cloud.githubusercontent.com/assets/654607/15966169/916cef28-2ee7-11e6-8a79-5ec75bda26ba.png)

It seems that it is missing this NuGet package (https://www.nuget.org/packages/Microsoft.VSSDK.BuildTools/) but I cannot really install it because solution-level Visual Studio NuGet installations are not supported in Visual Studio 2015 and onward.

If I attempt to "Install Missing Feature(s)", I receive the same "Update 1" dialog as it described above. As mentioned before, I am on Update 2.

This is probably the same effect that everyone is seeing in this issue, but in my case, installing the Visual Studio SDK seems to not be enough. Perhaps I will try and repair my Visual Studio install.

**Comment by Pilchie** [comment]
@adamjcook - can you run the `Restore.cmd` script in the root of the repo?  We have a couple of extra project.json files that we rely on being restored that don't happen if you restore just the solution file.

See https://github.com/dotnet/roslyn/blob/master/docs/contributing/Building%2C%20Debugging%2C%20and%20Testing%20on%20Windows.md.

**Comment by adamjcook** [comment]
@Pilchie Yes, sir. This fixes my issue. Looks like I did not drill down into the documentation enough. Thank you.

![image](https://cloud.githubusercontent.com/assets/654607/15971162/72f8673c-2efd-11e6-884f-801930ebdf6c.png)

**Comment by kedarkolhatkar** [comment]
Please follow instructions on this page. [Building, Debugging, and Testing on Windows](https://github.com/dotnet/roslyn/blob/master/docs/contributing/Building,%20Debugging,%20and%20Testing%20on%20Windows.md)

**Comment by Shiko1st** [comment]
I've made everything as in the document, but it doesn't help.
Restore.cmd returns this:
```
Property 'PositionalBinding' cannot be found for type 'System.Management.Automation.CmdletBindingAttribute'.
At E:\projects\roslyn\build\scripts\build.ps1:17 char:15
+ [CmdletBinding <<<< (PositionalBinding=$false)]
    + CategoryInfo          : InvalidOperation: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : PropertyAssignmentException
```

**Comment by jaredpar** [comment]
@Shiko1st what OS are you running?

**Comment by Shiko1st** [comment]
@jaredpar Win7, all updates up to May 2017

**Comment by jaredpar** [comment]
That is the issue. Win7 uses an old version of powershell that we dont support for development. Need to use a newer version (3 or higher)

**Comment by jasonmalinowski** [comment]
@jaredpar Is it upgradable, or is Windows 7 not supported at all? Do we need to document the requirement now?

**Comment by jaredpar** [comment]
iirc it is upgradable

**Comment by jasonmalinowski** [comment]
@Shiko1st I guess you can get the download links from https://docs.microsoft.com/en-us/powershell/scripting/setup/installing-windows-powershell? Maybe try a newer version there?

**Comment by Shiko1st** [comment]
Thank you, new version was installed and code were successfully built!

**Comment by jasonmalinowski** [comment]
Since this wasn't the first time we've had this question: #22178 is out to formally state the requirement.
