### ISSUE TITLE
Audit caching of syntax trees within the Document type

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#11726]
In Document.cs, there's a `_syntaxTreeResultTask` that caches a `Task<SyntaxTree>`. This seems terribly fishy to @CyrusNajmabadi and I. We expect one of two things to be true:
1. `SyntaxTree`s are expensive, and this shouldn't be cached like this. Instead it should be cached via our usual weak model, or something else.
2. `SyntaxTree`s are cheap, so GetSyntaxTreeAsync() shouldn't need to be async in the first place.

It's also fishy to me that we populate this on second or third calls to syntax trees if they're still alive. Why this isn't just flipping the flag on the underlying AsyncLazy to cache the result isn't clear.

**Comment by Pilchie** [comment]
Tag @mattwar

**Comment by mattwar** [comment]
GetSyntaxTreeAsync is cheap sometimes, not others.  The first time its not cheap because it needs to get the text (load the document sometimes, etc) and parse it.  Later times it is likely cheap, unless it get kicked out of memory and must be reloaded / reparsed.

Once its first constructed, the SyntaxTree instance is always permanent, its contents are what get kicked out of memory, so its safe to hold onto it.

I believe the Task<SyntaxTree> is an optimization that Paul added to avoid constructing the Tasks.

**Comment by jasonmalinowski** [comment]
But why does this not just get cached once the first thing is returned, instead of what this does which is cache the *second* time it's asked for? And why not just use AsyncLazy's support for this automatically?

**Comment by mattwar** [comment]
@jasonmalinowski  no idea.

**Comment by Pilchie** [comment]
Can we decide what to do here and do it?

**Comment by mattwar** [comment]
First off.. the syntax tree is okay to hold onto forever, since its the nodes of the tree that are managed by the tree cache.. The actual tree instance never changes.  The document state already keeps this instance alive for the duration.

As for what is really happening here, I don't know why it is necessary. I assume this was added by Paul Harrington because these task instances showed up on the perf radar.

Originally, the task for this was cached in the AsyncLazy, but eventually the type being computed by the AsyncLazy was changed to TreeAndVersion instead of just SyntaxTree.  So each time we call GetSyntaxTreeAsync() we are needing to create a new Task over and over again to hold the result.  So caching the Task here is probably okay.

However, the rest of the code that tries to figure out the SyntaxTree from the SemanticModel or using TryGet is completely bonkers.. Because if the model exists then the tree is already computed and already available in the TextAndVersion.  So maybe what they really meant to add here was a call to TryGetTextAndVersion on DocumentState.
