### ISSUE TITLE
CompilationOptions are missing With- method for some properties

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#1185]
Review common compilation options and add missing With- methods (DelaySign, CryptoPublicKey, CryptoKeyFile, CryptoKeyContainer, Platform, etc.)

**Comment by keyboardDrummer** [comment]
I was hoping I can ask a question related to this issue.

I'm wondering why CompilationOptions uses such a particular pattern for its With methods. Instead of defining abstract With methods that are implemented in the derived classes, it uses a more complicated pattern. CompilationOptions defines an abstract method CommonWith<memberName>, and then implements a method With<memberName> which redirect to CommonWith<memberName>. Then in the derived classes the abstract method CommonWith<memberName>is implemented by redirecting to With<memberName>, which would cause recursion, if it wasn't so that the derived class also redefines (using new or shadows) the method With<memberName>, where the actual implementation is located.

What's the purpose of this seemingly overly complicated pattern?

**Comment by bbarry** [comment]
It has been that way since the initial commit. It removes some `callvirt` instructions when the derived types are known to be used. 

in other words with `CompilationOptions options`: 

```csharp
options = options.WithPlatform(...);
```
would have a `call` with an internal `callvirt` to create the new `CSharpCompilationOptions`, but if you knew it was `CSharpCompilationOptions options`, the same code would be a single `call`.

**Comment by keyboardDrummer** [comment]
Alright I get that. Wouldn't you also get a direct call if you make the overridden method sealed in the derived class? 

Anyways I'll try to make a PR for this issue. I guess I should only add With methods for properties that can be set using the public constructor, so not for currentLocalTime for example, right? Also I see that a few With methods have comments, but most don't. What's the policy here?

**Comment by bbarry** [comment]
No you wouldn't. 

The virtual call is in the base method. For example `CompilationOptions::WithPlatform` contains a virtual call to `::CommonWithPlatform`. 

So this code:

    CompilationOptions options = ...;
    options = options.WithPlatform(...); //calling CompilationOptions::WithPlatform

must do a virtual call. But if you have:

    CSharpCompilationOptions options = ...;
    options = options.WithPlatform(...); //calling CSharpCompilationOptions::WithPlatform

you never call `CommonWithOptions` and so you don't have the virtual call because of the `new` on the method signature.

---

I would say publicly accessible methods should have xml documentation but I am not aware of any formal policy decision here and in this particular file set I don't see any consistent choice either way. On the other hand these particular methods are rather self documenting. @tmat, is there an official stance on this?

**Comment by keyboardDrummer** [comment]
@bbarry Actually I think virtual calls have nothing to do with this complicated base/derived class construction. I think its like this because the methods in the derived classes have a different signature than in the base class. In the base class they return CompilationOptions, while in the derived class they return the type of the derived class. I imagine this is quite useful if you want to chain calls to With methods. I guess something like a 'This' type could potentially make this boilerplate obsolete, but that's not part of the language.

**Comment by gafter** [comment]
Fixed by @keyboardDrummer in #13826. Thanks for your contribution!
