### ISSUE TITLE
Allow preprocessor directives using a TFM in AssemblyInfo.cs

### ISSUE THREAD

**Issue by Auersberg** [dotnet/roslyn#11885]
**Version Used**: 
Latest public Net Core SDK (1.0.0-preview1-002702)

**Steps to Reproduce**:
<pre>
Try to compile assembly attributes based on a TFM:
#if NET451
[assembly: AssemblyDescription("Library version NET 4.5.1")]
#elif NETCOREAPP1_0 
[assembly: AssemblyDescription("Library version NET Core 1.0.0")]
#endif
</pre>

**Expected Behavior**:
Assembly compiles with assembly description attribute set.

**Actual Behavior**:
Error: 	CS0579	Duplicate 'AssemblyDescription' attribute	Backload	I:\Backload.Demo.CLI\src\_Backload\Properties\AssemblyInfo.cs	10	

**Project**
http://github.com/blackcity/backload

**Comment by svick** [comment]
I think the problem is that you're also setting `"description"` in your project.json. [`dotnet` has logic to detect if you're setting `[AssemblyDescription]` from code](https://github.com/dotnet/cli/blob/6802e23/src/Microsoft.DotNet.Compiler.Common/AssemblyInfoFileGenerator.cs#L23-L44), but it parsers your code without setting any symbols. It means that in your case, it doesn't see the `[AssemblyDescription]` and sets it too, causing the conflict.

To solve this, remove `"description"` from your project.json. Another option would be to include `#else` section in your `[AssemblyDescription]` code.

**Comment by Pilchie** [comment]
Sounds like this should either go over on http://github.com/dotnet/cli or be resolved as @svick suggests?
