### ISSUE TITLE
String literals containing charcters from range 0x80-0xff behave differently when compiled/run on Windows vs. Linux

### ISSUE THREAD

**Issue by moozzyk** [dotnet/roslyn#11932]
**Version Used**: 
```
.NET Command Line Tools (1.0.0-preview2-002996)

Product Information:
 Version:            1.0.0-preview2-002996
 Commit SHA-1 hash:  cff4f37456

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 RID:         ubuntu.14.04-x64
```
(not sure what version of Roslyn is that)

**Steps to Reproduce**:

1. Clone the repo https://github.com/moozzyk/non-ascii-repro/
2. dotnet run on Windows and Linux 
3. The result is different

Windows:
```
48 eb 6c 6c f6 20 57 f6 72 6c 64 21
```

Linux:
```
48 fffd 6c 6c fffd 20 57 fffd 72 6c 64 21
```

I checked the file and the code file has the same content:

hexdump on Linux shows: 

![image](https://cloud.githubusercontent.com/assets/1438884/15981393/ade588ee-2f29-11e6-998f-79087329592d.png)

Binary editor in VS shows:
![image](https://cloud.githubusercontent.com/assets/1438884/15981421/f6efeb4c-2f29-11e6-8200-982506f8462e.png)

so this is not that characters in the source file are getting mangled.

This seems to be a compiler and not a runtime issue since if I publish my application on Windows for Linux the application behaves the same as on Windows:

```
moozzyk@moozzyk-ubuntu:~/tmp$ ~/.dotnet/dotnet non-ascii-repro.dll
48 eb 6c 6c f6 20 57 f6 72 6c 64 21
```

**Comment by miloush** [comment]
The fact that the binary file content is the same suggests that this is not a compiler issue, as that is where compiler's job ends. Possibly Core CLR?

**Comment by svick** [comment]
This happens, because your file is encoded using the Windows-1252 encoding. Roslyn first attempts to decode the file using UTF-8 and if that fails, it uses ["the default ANSI codepage"](http://source.roslyn.codeplex.com/#Microsoft.CodeAnalysis/EncodedStringText.cs,21) (returned by `Encoding.GetEncoding(0)`). On Windows, that can be Windows-1252 (depending on your regional settings). On Linux, it tends to be UTF-8 again, which is why it fails to decode and why you're getting U+FFFD REPLACEMENT CHARACTER.

To fix this, save your Program.cs in UTF-8:

```hexdump
000000c0  20 20 20 63 6f 6e 73 74  20 73 74 72 69 6e 67 20  |   const string |
000000d0  74 65 78 74 20 3d 20 22  48 c3 ab 6c 6c c3 b6 20  |text = "H..ll.. |
000000e0  57 c3 b6 72 6c 64 21 22  3b 0d 0a 0d 0a 20 20 20  |W..rld!";....   |
```

Another option would be to explicitly set the encoding by adding `"additionalArguments": ["/codepage:1252"]` to `"buildOptions"` in your project.json, but that doesn't work for me. I think it's because at the time when `/codepage` is parsed, `Encoding.RegisterProvider()` hasn't been called yet.

**Comment by miloush** [comment]
Alright, missed that the hex dumps are of code, not the final binary, sorry!

**Comment by moozzyk** [comment]
If I save the file as UTF-8 then, as you expected, the result is the same on both Windows and Linux.

**Comment by gafter** [comment]
See https://github.com/dotnet/roslyn/blob/master/docs/compilers/Deterministic%20Inputs.md which says

> The following will be considered inputs to the compiler for the purpose of determinism:
> ...
> - The default encoding (or the current code page) if the encoding is not specified
