### ISSUE TITLE
Proposal: Tackling the Non-Nullable Reference Types Problem

### ISSUE THREAD

**Issue by eyalsk** [dotnet/roslyn#11940]
**Disclaimer:** _I've done a fast search and didn't find exactly the same idea so I'm writing this to voice my opinion and maybe provide an alternative_.

The current approach as far as I know by reading this [document](https://github.com/dotnet/roslyn/blob/features/NullableReferenceTypes/docs/features/NullableReferenceTypes/Nullable%20reference%20types.md) is to provide static analysis which is great, the compiler will provide warnings and we will know exactly **where** to guard against nulls but then another problem remains and is the fact that we will still need to bloat our code with null checks everywhere! 

We can't go back in time and introduce non-nullable reference types by default in the language or fix it today without a major breaking change but we can tackle it on different levels and different ways to help everyone.

I guess I can generalize here and say that everyone deal with legacy code and for many people it's not feasible to rewrite a large codebase that works perfectly fine today just because C# introduces non-nullable reference types into the language.

So for legacy code static analysis can work pretty well, generally, people have their own mechanism or libraries to guard against nulls.

But the question is do we really need/want to follow the same pattern for our new code? well, I don't think so.

I don't think people want to continue writing the same boilerplate code over and over again, it's even worst, some people have their own creative ways to solve this problem some use libraries, other use tools and other just live with the boilerplate, so we don't have a unified and succinct way to do it in the language.

We can't eliminate the problem today but we can minimize the problem tomorrow and _maybe_ eliminate it in the future.

C++ has this notion of _const correctness_ in a nutshell it means that parts that are annotated with `const` cannot be mutated and in C++ as _ugly_ as it is you can put `const` anywhere in the function and it can get really bad from readability standpoint but anyway the point is that a const member function _cannot_ call a non-const memeber function. (_well, we can force it but this isn't the point._)

In C++ the following code won't compile because `Foo` isn't annotated with const.
```
class Qaz {
public:
	int Foo()
	{
		return 0;
	}

	int Bar() const
	{
		return Foo();
	}
};
```
However, the following code will compile just fine.
```
class Qaz {
public:
	int Foo()
	{
		return Bar();
	}

	int Bar() const
	{
		return 0;
	}
};
```
We can use almost the same principle to tackle the null problem by introducing a new keyword into the language that will allow us to annotate classes as non-nullable reference types.

So the syntax is something like this:
```
nonnull class Qaz {
}
```
We can also go with nonull or notnull or whatever, it's not important.

Now, at first I thought great! let's make non-nullable reference types only call members of other non-nullable reference types! but it wouldn't make sense to disallow any interaction between non-nullable reference types to nullable reference types because we wouldn't be able to create anything useful, we wouldn't be able to even use something as basic as strings.

So we need a bridge! now, the bridge I have in mind is quite _simple_, when non-nullable reference types makes calls to methods of a nullable reference type before that we need to verify these calls and guard against nulls pretty much like we do today! either through a condition or an assert call or the elvis operator or whatever...

So how is this different? what's the benefit of annotating the class with `nonnull`? well, when you annotate the class with `nonnull` then few things happen, the compiler will no longer provide warnings for nulls in cases where calls are made to methods that belong to nullable reference types and instead will provide errors! it will force you to verify the calls before their usage.

A `null` value cannot be passed to any of the members of classes that are annotated with `nonnull`! well, not exactly, we can! but we need to be explicit about it and and to do it we annotate the type with `?` like we do today with value types, like this:
```
nonnull class MessagePrinter
{
	public void Print(string? message)
	{
		Console.WriteLine(message);
	}
}
```
Now, the compiler will automatically generate the null checks for argument validation so something like this:
```
nonnull class MessagePrinter
{
	public void Print(string message)
	{
		Console.WriteLine(message.ToLower());
	}
}
```
Will turn into something like this:
```
class MessagePrinter
{
	public void Print(string message)
	{
		if (message == null) throw new ArgumentNullException(nameof(message));
		
		Console.WriteLine(message.ToLower());
	}
}
```
I think that the default behaviour should be to automatically generate these null checks for public, protected and internal members but not for private members but we still need to have some control over it so people would get to decide whether they want internal and/or protected and/or private to be checked too.

Just a note, when we use the class `MessagePrinter` in another non-nullable reference type like this:
```
nonnull class Printer
{
	public void Print(MessagePrinter printer)
	{
		printer.Print("Hello World");
	}
}
```
I don't think that we should allow the _nullable_ construct on types that are marked with `nonnull` so the following should result an error.
```
nonnull class Printer
{
	public void Print(MessagePrinter? printer)
	{
		printer.Print("Hello World");
	}
}
```

**Comment by HaloFour** [comment]
This seems more syntactically invasive and less useful than the `?` suffix for reference types as already proposed by the C# team.  I'd rather pull the band-aid once and move fully towards non-nullable by default.

**Comment by eyalsk** [comment]
@HaloFour okay, if I understand you correctly then you're speaking about the proposed nullable keyword, right? yeah sure we can use `?` instead, I'll update it but this wasn't really the whole proposal only half of it.

Are you expecting them to rewrite the framework? are you expecting that everyone will rewrite their codebases? what does `non-nullable by default` means?

**Comment by HaloFour** [comment]
I do fully expect the BCL team to amend the framework to annotate those parameters and return values that may be nullable.  It should be the minority case and would require a lot less work than trying to explicitly notate those that shouldn't be null.

Apple had to go through the same exercise with Swift.  All Cocoa reference types are nullable by nature.

**Comment by alrz** [comment]
I think nullability should be tackled in the use-site, not the declaration-site, because you might have a nullable value of any reference type, otherwise you cannot use this feature with third-parties that are not opt-in to non-nullable classes just yet.

**Comment by eyalsk** [comment]
@alrz, Well the way I proposed it, you can, you just need to guard it with some null checks and the compiler will make sure it's guarded.

**Comment by eyalsk** [comment]
@HaloFour Well in this case the proposal still stands, if they will annotate it then we won't need to have many guards in the codebase. :)

**Comment by HaloFour** [comment]
I disagree, mostly because I don't think it's a good idea to have two completely different ways of dealing with non-nullability both syntactically and behaviorally.  I think that the incorrect use should be caught at the call site, not the declaration, and that the granularity should be at the local/parameter/field level, not at the type declaration.

The team proposal isn't perfect and there are still numerous issues to be resolved.  I agree that it would be nice if appropriate guards could be automatically generated if desired.  I hope that the severity of the compiler diagnostic can quickly escalate to an error.  It would be nice if the nature of the `?` suffix could be normaliced between reference and value types.  But I think it's worth to work towards these goals under one unified proposal.

**Comment by eyalsk** [comment]
@HaloFour but their proposal is just (as far as I know) and read is to provide static analysis that will print warnings! it's not that it's not perfect it's really not what we even want to have to begin with! 

If they will allow us to change it into errors then that would be cool! but then we have errors so how would we handle it? we still need to have guards all over the place, I'm trying to minimize it without changing the world! 

if we can do that without annotating the types with `nonnull` I'm really all for it to happen but I really can't see it, can you enlighten me? maybe there are some ways that I'm not aware of and there are better ways to handle it than what I proposed, I don't know.

**Comment by HaloFour** [comment]
Both of those issues could be resolved within the proposal.  For example, even if the compiler just spit out warnings you could always instruct the compiler to treat those warnings as errors.  Hopefully they'llll be errors by default eventually.  Perhaps the compiler could also spit out argument validation guards within `#if` directives so that they could be easily kept or elided source file- or project-wide.

**Comment by eyalsk** [comment]
@HaloFour okay, but how do you tell a nullable type from a non-nullable type I don't really understand how this process will work, like what are the step?

1. Implement static analysis to warn against nulls.

2. Introduce nullable reference types.

3. Change everything in the BCL that is nullable to be treated as such by annotating them with `?`.

4. _Force_ the world to evolve as in 3rd-party code and do the same thing.

To me it looks huge effort but of course not impossible so if the BCL guys will do it then 3rd-party code that rely only on the BCL will just work based on the C++ example I gave above but the issue is when people rely on 3rd-party libraries that their authors will not do these changes as fast as people would like them to but in this case we can just use guards to satisfy the compiler and actually people need to have these guards today anyway... so maybe it's not even an issue.

p.s. I don't know if I like the idea of ##if directives but if you could give an example then that would be great, I mean, I don't like the idea that the compiler will write to my source files but maybe you mean something completely different. :)

**Comment by HaloFour** [comment]
@eyalsk 

> okay, but how would you distinguish a nullable type from a non-nullable type

You don't.  Types are just types.  It's not really the role of the type to assert non-nullability or to declare nullability.  The direction that #5032 takes is to change C# so that all *variables* are considered non-nullable by default, regardless of whether the type is a value type or a reference type.  You make the variable nullable via the `?` suffix on the type.

> I don't really understand how this process will work, like what are the step? do you expect the following to happen?

I expect 1 to 3 to happen in tandem.  The analysis work is already happening as you can see if you explore issues under the tag [New Language Feature - Nullable Reference Types](https://github.com/dotnet/roslyn/labels/New%20Language%20Feature%20-%20Nullable%20Reference%20Types).  The changes to the BCL will undoubtedly be tedious but should only impact a minority of the code and even then the majority of cases could probably be identified through code analysis.

Regardless of which strategy the teams take, if the BCL isn't updated there's practically no point to the feature at all.  It all has to start there, and from there it will percolate through the rest of the ecosystem.  It won't happen overnight, and it won't be painless.  It took Apple some time to completely these same changes across their frameworks so that they would work well with Swift.

> p.s. I don't know if I like the idea of `#if` directives but if you could give an example then that would be great, I mean, I don't like the idea that the compiler will write to my source files but maybe you mean something completely different. :)

This is just spaghetti I've tossed against the wall.  I thought that one thing the compiler could do is if you've enabled non-nullability (which is likely to be an opt-in flag initially) that the compiler could auto-emit code within the method which would perform the guard for you, perhaps only if the compiler detects that you aren't performing guards yourself:

```cs
public int GetStringLength(string s) {
    return s.Length;
}

// translates into

public int GetStringLength(string s) {
#if GENERATE_NULL_CHECKS
    if (s == null) throw new ArgumentNullException(nameof(s));
#endif
    return s.Length;
}
```

Then enable the `GENERATE_NULL_CHECKS` directive in your source file or project wide and you'd get those guards automatically.

Another possible solution would be to have a code generator automatically add them.

The theory is, though, that the more the compiler can help to prevent people from accidentally calling those methods with a `null` reference that the less necessary said guards would need to be.  It's not perfect and it's very easy to defeat intentionally, but there are no practical reasons for doing so.

Take Java generics.  The erasures make it insanely simple to defeat the type-safety they afford.  But in practice they do a good job of keeping the vast majority of source on the correct path, so much that actually writing defensive code to ensure that somebody didn't stick a `String` into your `List<Integer>` isn't considered at all necessary.

**Comment by eyalsk** [comment]
@HaloFour thanks for for elaborating.
