### ISSUE TITLE
Microsoft.VisualStudio.LanguageServices nuget package is missing reference to Elfie

### ISSUE THREAD

**Issue by shyamnamboodiripad** [dotnet/roslyn#12017]
@tmat just pointed out offline that the nuspec for Microsoft.VisualStudio.LanguageServices nuget package is missing reference to Elfie.

If we add this dependency, then today we will not be able to produce release nuget for this package because the Elfie dependency is a prerelease package. So we will probably need to move to a release version of Elfie as well when we fix this...

**Comment by jasonmalinowski** [comment]
This is not a problem, at least not yet. Unlike the other NuGet packages, this one represents a reference assembly that lives in Visual Studio, and doesn't need to support running anywhere else. Thus, it only needs dependencies to satisfy the public surface area, rather than implementation details. @CyrusNajmabadi, you can confirm we don't expose any types from Elfie publically?

**Comment by tmat** [comment]
We should fix it anyways. project.json references should correspond to references in nuspec.

**Comment by CyrusNajmabadi** [comment]
We do not expose any types from Elfie publicly

**Comment by Pilchie** [comment]
I agree with @jasonmalinowski I think we should *not* include this dependency in the nuspec.
