### ISSUE TITLE
[API Request] Map index from constant value to literal span

### ISSUE THREAD

**Issue by Suchiman** [dotnet/roslyn#12028]
To provide accurate diagnostic TextSpans on DSLs in strings it would be really handy to have an API that maps, for example, given an `index` and `length` in a string from `semanticModel.GetConstantValue(expression)` to a TextSpan in the literal text (respecting more complex scenarios such as escape sequences, concat, etc.).

In my analyzer i wrote this method https://github.com/Suchiman/SerilogAnalyzer/blob/master/SerilogAnalyzer/SerilogAnalyzer/DiagnosticAnalyzer.cs#L234 which deals with escape sequences but is nowhere complex enough to understand all the complex scenarios where the C# compiler can still provide a constant value.

**Comment by CyrusNajmabadi** [comment]
This would need to go through an API proposal.  in general, the reason we don't just make things public is because it increases maintenance costs and locks down our ability to change things in teh future.  We can open things up, but we have a process that requests need to go through to make sure the appropriate people weigh in and the right API shape is determined and shipped.
