### ISSUE TITLE
Intermittent test failure: "xunit produced no error output but had exit code -2146233082"

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#12106]
http://dotnet-ci.cloudapp.net/job/dotnet_roslyn/job/master/job/windows_debug_unit32_prtest/660/console

Unfortunately there is nothing helpful in the output or log.

**Comment by jasonmalinowski** [comment]
And now that's gone too. @tmat let's reactivate if we see it again.

**Comment by 333fred** [comment]
Necro resurrection, but I saw this again: https://ci.dot.net/job/dotnet_roslyn/view/Official%20Builds/job/dev15.7.x/job/windows_release_unit32/108

**Comment by sharwell** [comment]
Filed #25908 to help diagnose this.

**Comment by sharwell** [comment]
I tracked this down finally. It's caused by us throwing an exception from within a first chance exception filter:

https://github.com/dotnet/roslyn/blob/d0781848ade51ae8813ecffff1042cf5ec774ee7/src/VisualStudio/IntegrationTest/TestUtilities/VisualStudioInstanceFactory.cs#L54-L85

The exception message at the time of one recent crash is the following: 

> Could not find a part of the path 'F:\vsagent\1\s\artifacts\bin\Microsoft.VisualStudio.LanguageServices.IntegrationTests\Release\net472\xUnitResults\Screenshots\BasicAutomaticBraceCompletion.Braces_OnReturnNoFormattingOnlyIndentationBeforeCloseBrace-TargetInvocationException-02.13.58.Watson.log'.

This path is 261 characters long. We need to _at minimum_ not attempt to write files with paths that are too long, but ideally truncate the name of the test to ensure that the full path will fit in the allowed space.

**Comment by tmat** [comment]
Or rather enable long paths everywhere.

**Comment by jasonmalinowski** [comment]
@sharwell Why didn't procdump catch any of this?

**Comment by sharwell** [comment]
@jasonmalinowski I have no idea

**Comment by jasonmalinowski** [comment]
@sharwell Who should we ask? I'm guessing this should be easy to repro at least with a nice standalone test that triggers an exception within a first chance exception?

**Comment by sharwell** [comment]
@jasonmalinowski We disabled procdump monitoring in our tests because it was causing instability, so that would need to be fixed first.
