### ISSUE TITLE
Questionable logic in Binder.GetCorrespondingParameterType around dealing with extension methods

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#12138]
@AlekseyTs is concerned about something in `Binder.GetCorrespondingParameterType` that he wants to investigate. See also https://github.com/dotnet/roslyn/pull/11981/files/19ceb3d58486ac3345e772df8a80bfd74041e839#r67933728

**Comment by AlekseyTs** [comment]
This issue is related to the work that @gafter has done for improving lambda type inference in erroneous scenarios.

The logic in ```Binder.GetCorrespondingParameterType``` about looking up parameters by name might not do the right thing for extension methods. For example, it should never bind to the first parameter if the method is used as an extension. However, it doesn't look like anything prevents the function from doing just that.

**Comment by gafter** [comment]
The current logic is intentional, but I look forward to your investigation.
