### ISSUE TITLE
#pragma warning disable IDE0002 does not disable graying out

### ISSUE THREAD

**Issue by ashmind** [dotnet/roslyn#12213]
**Version Used**: 
Visual Studio 2015 Update 2

**Steps to Reproduce**:
1. Use the following code to reproduce:

``` csharp
class C {
    string f;
    public string M() {
        #pragma warning disable IDE0002
        return nameof(C.f);
        #pragma warning restore IDE0002
    }
}
```

**Expected Behavior**:
In `nameof`, `C` is not grayed out since `IDE0002` was disabled.

**Actual Behavior**:
In `nameof`, `C` is grayed out.

**Comment by mavasani** [comment]
This is not an analyzer/fixer issue, but probably an IDE colorization/classification issue. Adding the pragma does suppress the diagnostic and no fix for simplify name appears either.

**Comment by binki** [comment]
The editor falsely displays a suggestion mark hint in the scrollbar in addition to showing the false squiggly.

This is confusing because the shown Quick Actions menu does omits the suppressed codefix. Unless if the `#pragma warning disable…#pragma warning restore` are in view, the user will assume that one of the shown Quick Actions which is unrelated to the suggestion mark is related to the suggestion marking.

**Comment by CyrusNajmabadi** [comment]
Closing out.  This does not repro for me.  I presume much of our rewrites around fading addressed thsis.
