### ISSUE TITLE
Conditional logical operator && not functioning as described in spec when working with 'corrupted' bool values

### ISSUE THREAD

**Issue by a-ctor** [dotnet/roslyn#12211]
**Version Used**: 
VS 2015 14.0.25123.00 Update 2
with Microsoft (R) Visual C# Compiler version 1.2.0.60317

**Steps to Reproduce**:
Given the following method:

```csharp
private static bool Test(bool a, bool b)
{
	if (a && b) return false;
	if (a) if (b) return true; // should be unreachable
	return false;
}
```

**Expected Behavior**:
The method should always return `false` and the `return true` statement should be unreachable.

> The operation `x && y` is evaluated as `x ? y : false`. In other words, `x` is first evaluated and converted to type `bool`. Then, if `x` is `true`, `y` is evaluated and converted to type `bool`, and this becomes the result of the operation. Otherwise, the result of the operation is `false`.

Citation from the [C# 6 WIP Spec](https://github.com/ljw1004/csharpspec/blob/gh-pages/expressions.md#boolean-conditional-logical-operators) (Does not differ from the C# 5 spec)

**Actual Behavior**:
When we supply a _corrupted_ bool value (a boolean which has a value other than `0` or `1`) and a normal `true` value as parameters the method will actually return `true` (see below).

With the following struct (pointers can also be used to achieve the same result) we can create a boolean with the value `2`:

```csharp
[StructLayout(LayoutKind.Explicit)]
struct Corrupter
{
	[FieldOffset(0)]
	public byte ByteValue;
	[FieldOffset(0)]
	public bool BoolValue;
}
```

And then supply it to the method like this (we are supplying booleans with byte values of `1` and `2`):

```csharp
Test(true, new Corrupter { ByteValue = 2 }.BoolValue)
```

If we were to print the result to the console it would print `true`, at least in my case. If we compile the same thing with mono the output will be `false`.

 It seems like there is a difference between language spec and compiler implementation. If we were to replace the `a && b` with `x ? y : false`, which should be the compiler behavior when compiling `&&` (at least if the spec is correct), the method would work like expected and return `false`, even if we supply a corrupted boolean.

**Comment by gafter** [comment]
The spec doesn't say what is supposed to happen with corrupted bool values.

**Comment by gafter** [comment]
We'll investigate if there is an easy way to "fix" this without loss of performance.

**Comment by weltkante** [comment]
Please consider these additional reasons while reviewing this issue:

1) it is totally unintuitive that `if(a) if(b)` evaluates to something different than `if(a && b)` - whenever that happens you are asking people to spend days debugging why the code does not do what it looks like.

2) when stepping through the code the visual studio debugger shows `a && b` is true but the code does not step into the `if`. **This is a bug in either the compiler or the debugger.** (I'd prefer the compiler to be fixed to what it did before, due to the other reasons mentioned.)

3) it can break existing interop code because in C/C++ any nonzero value is treated as true, in C# it previously worked the same, so people may have started to rely on it (perhaps without noticing they are triggering undefined behavior - assuming it really is undefined, I didn't read the spec).

The point here is that some (valid!) C/C++ code may return nonzero as a result and people may have defined interop structs which map this to a 'bool' property. This would have worked before but now could start breaking, but only when used together with `&&` operators!

```csharp
[StructLayout(LayoutKind.Sequential)]
struct NativeStruct1
{
    public int NumericValue;
}

[StructLayout(LayoutKind.Sequential)]
struct NativeStruct2
{
    public bool BoolValue;
}

// The point here is that some C/C++ code might write an arbitrary numeric value
// assuming nonzero is treated as true. The C# interop struct may have been defined
// with 'bool' for convenience, implicitely relying on previous behavior of nonzero
// being true in C# as well.
var n1 = new NativeStruct1 { NumericValue = 2 };
var p1 = &n1;
var p2 = (NativeStruct2*)(void*)p1;
var n2 = *p2;
Test(true, n2.BoolValue);
```

**Comment by AdamSpeight2008** [comment]
@gafter  See #14262 for result of tests of C#'s `&&` vs VB.net's `AndAlso`.  C# is (to me) producing the incorrect IL for C#
