### ISSUE TITLE
Interpolated string "comma" clause should be colored red

### ISSUE THREAD

**Issue by ljw1004** [dotnet/roslyn#12264]
![interpolation](https://cloud.githubusercontent.com/assets/3316258/16432215/d97c6582-3d38-11e6-8ba8-b6d20648d92d.png)

```csharp
var s3 = $"hello {15,20:C0}";
```

I think that all of `,20:C0` should be colored red here. At the moment the 20 is black, which makes it sort of blend into the expression in the hole. But folks should understand it as part of the string formatting directives, just like `C0` is part of the formatting directives, and so it should be colored red like the rest of the string formatting directives.

@gafter

**Comment by AdamSpeight2008** [comment]
@ljw1004 
I disagree, I don't think to colour should be the same the enclosing text.
The existing colour of `:` is because it seen as `punctuation`. 
If anything needs to be changed it is the `Format` argument colour, as isn't part of the enclosing text, but part of the argument hole.

```
{       Punc
15	Number
,	Punctuation
20	Number
:	Punctuation
C0	Text
}
```
There are other formatting aspects of string we (Roslyn/IDE) don't colourise, like `\t \n {{ }}`
Also the result produce is contextual to the argument supplied ( which could throw exception.), which is highlighted or squiggled. .

**Comment by Pilchie** [comment]
IDE agrees with @AdamSpeight2008  on this one.
