### ISSUE TITLE
.ToString(IFormatProvider) on an interpollated string should evaluate to FormattableString.ToString(IFormatProvider)

### ISSUE THREAD

**Issue by KrisVandermotten** [dotnet/roslyn#12298]
**Version Used**: Visual Studio 2015 Update 3

**Steps to Reproduce**:

Consider this program:

```
using System;
using System.Globalization;

static class Program
{
    static void Main()
    {
        System.Threading.Thread.CurrentThread.CurrentCulture = new CultureInfo("nl-BE");

        FormattableString s = $"Pi = {Math.PI}";

        Console.WriteLine(s.ToString(CultureInfo.InvariantCulture));

        Console.WriteLine($"Pi = {Math.PI}".ToString(CultureInfo.InvariantCulture));
    }
}
```

**Expected Behavior**:

```
Pi = 3.14159265358979
Pi = 3.14159265358979
```

**Actual Behavior**:

```
Pi = 3.14159265358979
Pi = 3,14159265358979
```

Don't get me wrong, I'm not saying `$"Pi = {Math.PI}".ToString(CultureInfo.InvariantCulture)` should be compiled to actually create an instance of `FormattableString` at runtime. But this behavior is confusing, and not really "the pit of success".

**Comment by gafter** [comment]
Unless target-typed to `FormattableString` or one of its friends, an interpolated string syntax is of type `string`, after being formatted in the current locale. The presence of [the `IConvertible.ToString(IFormatProvider)` method on `string` as a public method of `string`](https://msdn.microsoft.com/en-us/library/29dxe1x2(v=vs.110).aspx) simply makes that confusing. However, it would be incompatible to change that, and I'm not sure what language rules we would use to change it.

/cc @MadsTorgersen

**Comment by KrisVandermotten** [comment]
Yes it would be incompatible to change that. But the probability that one writing  `$"Pi = {Math.PI}".ToString(CultureInfo.InvariantCulture)` intents the current behavior is virtually zero.

**Comment by whut** [comment]
As interpolated strings are just syntatic sugar over string.Format, the current behavior is OK. It is just the same as in string.Format case:

```csharp
string.Format{"PI = {0}", Math.PI).ToString(CultureInfo.InvariantCulture)
```

This is a bit confusing only because of the possiblity of auto-conversion to FormattableString. This suggests that the FormattableString class is not needed in the language/framework:)

**Comment by whut** [comment]
BTW #12336 shows how to avoid the only valid use-case (IMO) of FormattableString, the FormattableString.Invariant.

**Comment by gafter** [comment]
We are now taking language feature discussion in other repositories:
- https://github.com/dotnet/csharplang for C# specific issues
- https://github.com/dotnet/vblang for VB-specific features
- https://github.com/dotnet/csharplang for features that affect both languages

Features that are under active design or development, or which are "championed" by someone on the language design team, have already been moved either as issues or as checked-in design documents. For example, the proposal in this repo "Proposal: Partial interface implementation a.k.a. Traits" (issue 16139 and a few other issues that request the same thing) are now tracked by the language team at issue 52 in https://github.com/dotnet/csharplang/issues, and there is a draft spec at https://github.com/dotnet/csharplang/blob/master/proposals/default-interface-methods.md and further discussion at issue 288 in https://github.com/dotnet/csharplang/issues. Prototyping of the compiler portion of language features is still tracked here; see, for example, https://github.com/dotnet/roslyn/tree/features/DefaultInterfaceImplementation and issue 17952.

In order to facilitate that transition, we have started closing language design discussions from [the roslyn repo](https://github.com/dotnet/roslyn) with a note briefly explaining why. When we are aware of an existing discussion for the feature already in the new repo, we are adding a link to that. But we're not adding new issues to the new repos for existing discussions in this repo that the language design team does not currently envision taking on. Our intent is to eventually close the language design issues in the Roslyn repo and encourage discussion in one of the new repos instead.

Our intent is not to shut down discussion on language design - you can still continue discussion on the closed issues if you want - but rather we would like to encourage people to move discussion to where we are more likely to be paying attention (the new repo), or to abandon discussions that are no longer of interest to you.

If you happen to notice that one of the closed issues has a relevant issue in the new repo, and we have not added a link to the new issue, we would appreciate you providing a link from the old to the new discussion. That way people who are still interested in the discussion can start paying attention to the new issue.

Also, we'd welcome any ideas you might have on how we could better manage the transition. Comments and discussion about closing and/or moving issues should be directed to https://github.com/dotnet/roslyn/issues/18002. Comments and discussion about this issue can take place here or on an issue in the relevant repo.

-----------------

I have not moved this feature request to the csharplang repo because I don't believe we would make the requested breaking language change. However, you are welcome to move discussion to the new repo if this still interests you.
