### ISSUE TITLE
Flag a release that match .NET Compiler Platform SDK.

### ISSUE THREAD

**Issue by malylemire1** [dotnet/roslyn#12339]
**Version Used**: Roslyn version is 1.3.2 on vs2015

**Steps to Reproduce**:

1. After updating Microsoft.CodeAnalysis to version 1.3.2 and updating a Visual Studio Package, I get a file not found error for System.Collections.Immutable 1.2.0. The copy local option is ignored and the Visual Studio Package uses .NET Compiler Platform SDK Extension packages.

**Expected Behavior**:

Know which Microsoft.CodeAnalysis version to use in a Visual Studio Package that matches the .NET Compiler Platform SDK Extension packages.

**Actual Behavior**:

We have to go to C:\Users\CurrentUser\AppData\Local\Microsoft\VisualStudio\14.0\Extensions\Roslyn and verify the packages to find the Microsoft.CodeAnalysis version to use.

**Comment by Maly-Lemire** [comment]
It's seems that the error has been reported in #12255

**Comment by Pilchie** [comment]
There should be tags for each released version of visual studio (e.g. https://github.com/dotnet/roslyn/tree/version-1.3.2).  However, in general if you're developing an analyzer/etc, you probably want to target the v1.0 packages unless you *need* something newer.  Otherwise, your analyzer won't run for users that haven't installed the update that ships that version of Roslyn yet.
