### ISSUE TITLE
[Suggestion] SyntaxNodeOrTokenList should be a IReadOnlyList<SyntaxNodeOrToken>

### ISSUE THREAD

**Issue by MatthieuMEZIL** [dotnet/roslyn#12355]
IMHO SyntaxNodeOrTokenList should be a IReadOnlyList<SyntaxNodeOrToken> instead of just being a IReadOnlyCollection<SyntaxNodeOrToken> with an int indexer.

**Comment by gafter** [comment]
@mattwar What do you think of this?

**Comment by CyrusNajmabadi** [comment]
This would need to go through an API proposal.  in general, the reason we don't just make things public is because it increases maintenance costs and locks down our ability to change things in teh future.  We can open things up, but we have a process that requests need to go through to make sure the appropriate people weigh in and the right API shape is determined and shipped.
