### ISSUE TITLE
Review usage of null vs ErrorType for Types

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#12428]
In some cases, an expression has a null `Type`. For instance, the `null` in `var x = null;` or `var x = (null, null);`.
But in other cases, an expression has an `ErrorType`. For instance, `var x = undefined;`.
We should review whether there is a clear rule for this.

The question came up in [this PR](https://github.com/dotnet/roslyn/pull/12411#discussion_r70196505).

**Comment by gafter** [comment]
There is a clear rule.

If the expression does not have a type, its type is `null`.

If the expression has an error, so that it doesn't make sense to speak of its type, we represent its type as an `ErrorType`. This serves to suppress cascaded diagnostics.

As a rule, we do not use a type of `null` to represent error situations. We do not use an `ErrorType` to represent a non-error situation where an expression does not have a type. There are exceptions to these rules, but they are very local and temporary situations within the compiler.

**Comment by jcouv** [comment]
Thanks Neal! 
FYI for @jaredpar who was curious about the rule for types and null.
