### ISSUE TITLE
Add support for edit-and-continue for tuples

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#12436]
The implementation of tuples (in particular, deconstruction) should support edit-and-continue.

**Comment by VSadov** [comment]
Deconstruction is an expression and therefore most scenarios "should just work" since EnC is allowed only on statement level. The only potentially tricky scenario could be local declarations. 

Supporting EnC for tuples in general could be a bigger problem though, because we need to reason about field names. - Is it a rude edit to change a field name of a tuple variable? (I am not sure...).

**Comment by gafter** [comment]
Because deconstruction involves the use of compiler-generated temporaries, and can call user-declared code such as conversion operators and `Deconstruct` (within which breakpoints can be set), edit-and-continue needs to track these temps and realign them during edits.
