### ISSUE TITLE
Feature Request: Trailing commas in method signatures and invocations

### ISSUE THREAD

**Issue by MgSam** [dotnet/roslyn#12496]
### Proposal

Allow trailing commas in method/constructor declarations and invocations.

``` C#
void Foo(
    int bar, 
    int baz,
) { }

Foo(
    bar: 5,
    baz: 3,
);
```
### Rational

One very small but appreciated feature in C# is the tolerance of the compiler for trailing commas in array initialization or object initialization:

``` C#
var a = new int[] { 3, 4, 5, };
var b = new { Bark = "woof", Bite = "chomp", }
```

This makes it easier to reorder or edit the item order without taking time to make sure that last comma gets deleted. 

It would be nice if this feature also extended to method signatures and invocation. It would be especially useful in the post C# 4.0 where named parameters can be reordered or used to make a highly descriptive method call.
### Example

``` C#
void Foo (int bar, String baz, Func<int> cat, Action<String> dot, int elf) { }

Foo(
    bar: 5, 
    baz: "",
    cat: () => 6,
    dot: p => Console.WriteLine(p),
    elf: 10
);
```

Wait, having elf last is confusing, let me group it with bar

``` C#
//Rather than just copy and paste the relevant line...
Foo(
    bar: 5, 
    elf: 10, //Now I need to add this comma here!
    baz: "",
    cat: () => 6,
    dot: p => Console.WriteLine(p) //And I need to remove this comma here!
);
```

Instead, if method invocations were also tolerant of an extra comma, it would make editing easier:

``` C#
Foo(
    bar: 5, 
    elf: 10, 
    baz: "",
    cat: () => 6,
    dot: p => Console.WriteLine(p), //Extra comma here, it's not hurting anyone!
);
```
### Final thoughts

Since I originally proposed this issue on [CodePlex](https://roslyn.codeplex.com/workitem/147), it has since become a feature of [TypeScript](https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#trailing-commas-in-function-parameter-and-argument-lists) (and soon JavaScript). It's now officially mainstream. Get with the program, people.

**Comment by HaloFour** [comment]
Personally I find the practice to just be sloppy.  I'd rather see the tools in the IDE make it easier to shift things around than to have the syntax allow extraneous punctuation just for that purpose.  But, since C# already allows it in a number of places it's better to be internally consistent.

**Comment by AdamSpeight2008** [comment]
Would also clash with optional parameters.

**Comment by HaloFour** [comment]
@AdamSpeight2008 

That would be true in VB.NET but not in C#.  This syntax isn't currently at all legal in C# and you can't simply omit an expression for an optional argument.  I don't think that there would be any expectations that if C# were to permit dangling commas in invocation that it would apply the same overload resolution logic from VB.NET.

**Comment by dsaf** [comment]
It would be nice if trailing commas were disallowed everywhere retroactively.

**Comment by MgSam** [comment]
My opinion is the language shouldn't try to dictate style conventions. If you want a language like that there is Python or F#. There's no semantic reason why trailing commas are problematic, so why not allow them?

**Comment by dsaf** [comment]
Comma is not a white space. I just want to avoid cleaning this after other people in future.

**Comment by HaloFour** [comment]
@MgSam 

> My opinion is the language shouldn't try to dictate style conventions.

But the language does *heavily* dictate style conventions, primarily through what it considers legal syntax.  If C# had no instances of permitting dangling commas I'd probably argue more against it, that it's a sloppy syntax workaround akin to (but more innocuous than) semicolon insertion in JavaScript.  I'd rather my programming syntax be specific and painstakingly explicit instead of allowing the parser to just ignore what are actually nonsensical syntax errors because it offers minor convenience.  That said, C# does allow it in certain circumstances (IIRC always has with enums), and the state of source diff tools is abysmal (being very generous) so I understand the usefulness of this particular bit of syntax.

There is some minor concern about ambiguity with overloads as well:

```cs
void Foo(int x) { }
void Foo(int x, int y = 123) { }

Foo(456,); // which overload should this call?
```

Note that the VB.NET equivalent to the above calls the overload *with* the optional argument.

**Comment by MgSam** [comment]
I disagree. The semi-colon insertion in JS can result in code that is ambiguous to the reader if you're not intimately acquainted with the rules. Trailing commas can be considered trivia, the same as whitespace, extra semi-colons or comments. Adding/removing them should have no impact on the semantics of the code.

It's also useful for more than diff tools. As I illustrated in my example, methods with a long list of named parameters are possible in C#, and reordering, commenting out, or adding additional parameters shouldn't require extra pain due to comma wrangling.

**Comment by theunrepentantgeek** [comment]
I've always found the diff tool argument a bit weak - I'd suggest we shouldn't be modifying the syntax of the language to accommodate weak tooling.

The (existing) trailing comma support for sequence and object initialization is at least benign - it enables compilation purely (and only) for cases that would otherwise be syntax errors.

With the existing language support for method overloads and optional parameters, I'd suggest that adding support for optional trailing commas would create significant ambiguity and confusion.

**Comment by gafter** [comment]
We are now taking language feature discussion in other repositories:
- https://github.com/dotnet/csharplang for C# specific issues
- https://github.com/dotnet/vblang for VB-specific features
- https://github.com/dotnet/csharplang for features that affect both languages

Features that are under active design or development, or which are "championed" by someone on the language design team, have already been moved either as issues or as checked-in design documents. For example, the proposal in this repo "Proposal: Partial interface implementation a.k.a. Traits" (issue 16139 and a few other issues that request the same thing) are now tracked by the language team at issue 52 in https://github.com/dotnet/csharplang/issues, and there is a draft spec at https://github.com/dotnet/csharplang/blob/master/proposals/default-interface-methods.md and further discussion at issue 288 in https://github.com/dotnet/csharplang/issues. Prototyping of the compiler portion of language features is still tracked here; see, for example, https://github.com/dotnet/roslyn/tree/features/DefaultInterfaceImplementation and issue 17952.

In order to facilitate that transition, we have started closing language design discussions from [the roslyn repo](https://github.com/dotnet/roslyn) with a note briefly explaining why. When we are aware of an existing discussion for the feature already in the new repo, we are adding a link to that. But we're not adding new issues to the new repos for existing discussions in this repo that the language design team does not currently envision taking on. Our intent is to eventually close the language design issues in the Roslyn repo and encourage discussion in one of the new repos instead.

Our intent is not to shut down discussion on language design - you can still continue discussion on the closed issues if you want - but rather we would like to encourage people to move discussion to where we are more likely to be paying attention (the new repo), or to abandon discussions that are no longer of interest to you.

If you happen to notice that one of the closed issues has a relevant issue in the new repo, and we have not added a link to the new issue, we would appreciate you providing a link from the old to the new discussion. That way people who are still interested in the discussion can start paying attention to the new issue.

Also, we'd welcome any ideas you might have on how we could better manage the transition. Comments and discussion about closing and/or moving issues should be directed to https://github.com/dotnet/roslyn/issues/18002. Comments and discussion about this issue can take place here or on an issue in the relevant repo.

-----------------

I have not moved this feature request to the csharplang repo because I don't believe it would ever rise in priority over other requests to be something we would ever do in any particular release. However, you are welcome to move discussion to the new repo if this still interests you.
