### ISSUE TITLE
Unable to apply changes to g.i.cs files generated by XAML compiler

### ISSUE THREAD

**Issue by debonte** [dotnet/roslyn#12531]
**Version Used**: 2.00.0.0 -- Dev15 preview

**Steps to Reproduce**:
1. Open a WPF or UWP project in Visual Studio.
2. Build
3. Obtain the Document object for one of the .g.i.cs files from the VisualStudioWorkspace.
4. Make a change to the document root.  I was adding a field to the (only) class in the file.
5. Call visualStudioWorkspace.TryApplyChanges(newDocument.Project.Solution).

**Expected Behavior**:
g.i.cs file on disk is updated with whatever change you made in step 4.

**Actual Behavior**:
g.i.cs file is not updated.  However, if you make the same change to some other file in the project (ex. MainPage.xaml.cs), the file _will_ be updated.

**Comment by debonte** [comment]
@heejaechang suggested that "we might have something that prevent updating generated files to prevent normal usage/people messing up generated files."

I'm trying to write an incremental XAML compiler to run (when appropriate) in place of the normal, slower XAML compiler.  So I'm intentionally changing this generated file even though I didn't generate it myself.

**Comment by Pilchie** [comment]
@brettfo can you take a look and see if there is something happening here in the workspace?

**Comment by mattwar** [comment]
From quick code review, we don't have any logic in Workspace or VS Workspace that is blocking this text update.  I have not tried to repro yet.

**Comment by mattwar** [comment]
I've debugged this.  There are two problems I've discovered so far.  

One is that Roslyn fails to request that the document be updated if only one document is changed and it is not an open document.. this has to do with some logic that I don't fully understand about invisible editors and undo transactions.  We seem to think that the invisibly edited document needs saving (by us) only if there is an undo transaction in progress... but there is no undo transaction when there is only one document that is being changed.

However, even with this by-pass so Roslyn does submit an save request to the VS running document table, VS does not write that change to disk.  I'm still tracking down whether this is expected behavior or not.

**Comment by mattwar** [comment]
Aside from the Roslyn issue that is related to editing a single unopened document, from further investigation it looks like these particular generated files are not saved because they do not appear as part of the VS solution heirarchy.

**Comment by mattwar** [comment]
@debonte is this explanation satisfactory or would you prefer that the generate file still get saved as opposed to a work around that you might do yourself?

**Comment by debonte** [comment]
Sorry I missed your responses last year.  My workaround for this in VS 2017 seems to be working, so I'm OK with not fixing this.
