### ISSUE TITLE
Completion unnecessarily qualifies class name (inconsistently, but usually)

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#12552]
**Version Used**: VS 2015 Update 3

**Steps to Reproduce**:

1. Paste C#
  ```C#
      class C1
      {
          void M()
          {
              C2 n = new
          }
      }
      class C2 { }
  ```

2. Immediately after `new`, type `<space>C2(`

**Expected Behavior**:
```C#
C2 n = new C2()
```
**Actual Behavior**:
```C#
C2 n = new global::C2()
```
with `global` grayed out.

It _occasionally_ decides to work correctly, and once it starts working correctly it seems to keep working correctly on subsequent attempts until I cut/paste the entire file. But almost every time I cut/paste the whole file and then do the exact repro above it reproduces. ¯\\(°_o)/¯ :smile:

/cc: @rchande Is this known? Didn't see an existing bug for it after a couple quick searches.

**Comment by ljw1004** [comment]
I've observed this a lot over the past weeks. I've not yet reported it myself because it's so intermittent.

**Comment by DustinCampbell** [comment]
passing to @CyrusNajmabadi since he's looking at completion right now.

**Comment by CyrusNajmabadi** [comment]
I've recently refactored completion to not have the pattern of serializing out and rehydrating a symbol on commit.  This pattern was very error prone and caused numerous problems especially around creating the minimal name for the symbol.

This was because we were mixing/matching different semantic models.  Sometimes it would be a speculative semantic model.  Sometimes it would be hte document semantic model.  When different models were used minimization would not work.

I believe this is totally fixed now.  If you encounter it again on a new roslyn drop, please let me know.
