### ISSUE TITLE
[Proposal] Method group extra parameter binding

### ISSUE THREAD

**Issue by UnoSD** [dotnet/roslyn#12569]
Would be nice to be able to bind extra parameters to a method group to avoid an extra call in the stack and to reduce syntax noise:

```
void Method(Action<int> action) { }

void AsGroup(int value, string other) { }

Method(AsGroup("extra"));
// Or
Method(AsGroup.Bind("extra"));
// Or
Method(bind(AsGroup, "extra"));
```

Of course AsGroup("extra") could be an issue if AsGroup(string) is declared so it will need extra checks.

The values will be captured at runtime and reused on invocation of the AsGroup in the same fashion as the lambdas.

The bind keyword would resemble the function:

`static Action<T1> bind<T1, T2>(Action<T1, T2> action, T2 parameter) => t1 => action(t1, parameter);`

Without having to explicitly specify T1, T2 and with any number of type arguments and the implementation should not add a call to the stack.

**Comment by HaloFour** [comment]
You can already achieve this through the following syntax:

```cs
Method(value => AsGroup(value, "extra"));
```

Why is this so cumbersome (or common) to necessitate new syntax and a new keyword?

You mention that the `bind` keyword would be equivalent to a function using `Action<T1, T2>`, but why?  What delegate should the compiler choose if the method accepts a different delegate type?  What if the original delegate type has `ref` or `out` parameters?

Also, given the equivalent function would produce two delegates it would certainly be less efficient than the current syntax which would produce a single delegate instance.  Considering that the end result is a delegate I doubt that you could produce a more efficient implementation than what the compiler produces now.

**Comment by dsaf** [comment]
Perhaps some of other features #3661, #11159, #12043 would allow defining a generic implicit cast extension operator(s) on delegate(s) that would allow effectively ignoring the unused parameter(s)?

**Comment by axel-habermaier** [comment]
@HaloFour: I think @UnoSD asks for support of function currying, which is indeed a very useful concept in both mathematics and functional programming. However, I'm not sure if it can be implemented any more efficiently that the double delegate dispatch you show. At least as long as delegates are used. F#, by contrast, does not use delegates likely for this very reason.

**Comment by HaloFour** [comment]
@axel-habermaier 

He's using a backwards order of arguments for traditional currying.  I believe that he'd still be required to manually use a higher order function (or pipe operator?) to massage the second parameter into the invocation.  And if the target method he's called accepts a delegate then he doesn't have much choice than to pass a delegate anyway.

The current normal C# syntax for this does not require a double delegate invocation.  Depending on how you supply the additional parameter at best you get a single delegate invocation to a cached static delegate instance.  If the extra parameter is a variable then you add in the cost of an allocation for the closure class.

**Comment by gafter** [comment]
We are now taking language feature discussion in other repositories:
- https://github.com/dotnet/csharplang for C# specific issues
- https://github.com/dotnet/vblang for VB-specific features
- https://github.com/dotnet/csharplang for features that affect both languages

Features that are under active design or development, or which are "championed" by someone on the language design team, have already been moved either as issues or as checked-in design documents. For example, the proposal in this repo "Proposal: Partial interface implementation a.k.a. Traits" (issue 16139 and a few other issues that request the same thing) are now tracked by the language team at issue 52 in https://github.com/dotnet/csharplang/issues, and there is a draft spec at https://github.com/dotnet/csharplang/blob/master/proposals/default-interface-methods.md and further discussion at issue 288 in https://github.com/dotnet/csharplang/issues. Prototyping of the compiler portion of language features is still tracked here; see, for example, https://github.com/dotnet/roslyn/tree/features/DefaultInterfaceImplementation and issue 17952.

In order to facilitate that transition, we have started closing language design discussions from [the roslyn repo](https://github.com/dotnet/roslyn) with a note briefly explaining why. When we are aware of an existing discussion for the feature already in the new repo, we are adding a link to that. But we're not adding new issues to the new repos for existing discussions in this repo that the language design team does not currently envision taking on. Our intent is to eventually close the language design issues in the Roslyn repo and encourage discussion in one of the new repos instead.

Our intent is not to shut down discussion on language design - you can still continue discussion on the closed issues if you want - but rather we would like to encourage people to move discussion to where we are more likely to be paying attention (the new repo), or to abandon discussions that are no longer of interest to you.

If you happen to notice that one of the closed issues has a relevant issue in the new repo, and we have not added a link to the new issue, we would appreciate you providing a link from the old to the new discussion. That way people who are still interested in the discussion can start paying attention to the new issue.

Also, we'd welcome any ideas you might have on how we could better manage the transition. Comments and discussion about closing and/or moving issues should be directed to https://github.com/dotnet/roslyn/issues/18002. Comments and discussion about this issue can take place here or on an issue in the relevant repo.

-----------------

I have not moved this feature request to the csharplang repo because I don't believe it would ever rise in priority over other requests to be something we would ever do in any particular release. However, you are welcome to move discussion to the new repo if this still interests you.
