### ISSUE TITLE
Breaking out of multiple loops

### ISSUE THREAD

**Issue by tomspilman** [dotnet/roslyn#12583]
A fairly minor annoyance...  but sometimes you end up with code like this:

```
void function()
{
   foreach ()
   {
      bool stop = false;
      foreach ()
      {
          if (condition)
          {
             stop = true;
             break;
          }
      }
      if (stop)
         break;
   }
   // Do some final work.
}
```

Often suggestions are to use a temporary like this or split this into two different functions.

It would be nice if you could just call break more than once in a single statement to jump out of nested loops:

```
void function()
{
   foreach ()
   {
      foreach ()
      {
          if (condition)
             break break;
      }
   }
   // Do some final work.
}
```

Specifying one too many `break` statements would cause a syntax error at compile time.

**Comment by 0xd4d** [comment]
`goto` has existed since C#1 and works.

```C#
void function()
{
   foreach ()
   {
//not needed, using goto power now:      bool stop = false;
      foreach ()
      {
          if (condition)
          {
//not needed, using goto power now:             stop = true;
//not needed, using goto power now:             break;
              goto done;
          }
      }
//not needed, using goto power now:      if (stop)
//not needed, using goto power now:         break;
   }
done:;
   // Do some final work.
}
```

**Comment by tomspilman** [comment]
> `goto` has existed since C#1 and works.

Sure... that is a valid work around, but I would say that it isn't ideal.  A `goto` can jump almost anywhere and requires the reader to figure out what the code is actually doing. 

Seeing `break break` alone alerts the reader specifically you are breaking out of the two most inner loops.  The intent is very clear and less error prone.

**Comment by surfasb** [comment]
I think `goto` looks better. Breaking out of multiple loops is already a weird pattern (refactor it). Putting the `goto` will help make it stand out.

**Comment by Joe4evr** [comment]
> A `goto` can jump almost anywhere

Not really, the C# compiler actually restricts the places where a `goto` can jump to by quite a lot. From the C# 5 spec:

> If a label with the given name does not exist in the current function member, or if the `goto` statement is not within the scope of the label, a compile-time error occurs. This rule permits the use of a `goto` statement to transfer control out of a nested scope, but not into a nested scope.

**Comment by alanfo** [comment]
VB.NET has a partial solution to this problem in that you can use `Exit Do`, `Exit For` etc. to jump out of the nearest loop of that particular kind. However, if the loops are all of the same type, then it's of no help.

Java has a labelled `break` but, frankly, it's just `goto` by another name.

The best solution I've seen is (surprisingly) PHP in which `break` and `continue` can be followed by an optional integer to specify how many nested structures should be broken out of. So` break 2` would break out of the two nearest nested loops and so on. To my mind this is more elegant than `break break`.

Whether it's worth adding this to the language with so much else going on must be doubtful. Personally, I'm happy to just use `goto` rather than tie myself in knots testing `bool` variables.

**Comment by AdamSpeight2008** [comment]
If the usage of `goto` reasonably limited and not spaghetti-fied, then sometimes it is the best solution.

**Comment by gafter** [comment]
We are now taking language feature discussion in other repositories:
- https://github.com/dotnet/csharplang for C# specific issues
- https://github.com/dotnet/vblang for VB-specific features
- https://github.com/dotnet/csharplang for features that affect both languages

Features that are under active design or development, or which are "championed" by someone on the language design team, have already been moved either as issues or as checked-in design documents. For example, the proposal in this repo "Proposal: Partial interface implementation a.k.a. Traits" (issue 16139 and a few other issues that request the same thing) are now tracked by the language team at issue 52 in https://github.com/dotnet/csharplang/issues, and there is a draft spec at https://github.com/dotnet/csharplang/blob/master/proposals/default-interface-methods.md and further discussion at issue 288 in https://github.com/dotnet/csharplang/issues. Prototyping of the compiler portion of language features is still tracked here; see, for example, https://github.com/dotnet/roslyn/tree/features/DefaultInterfaceImplementation and issue 17952.

In order to facilitate that transition, we have started closing language design discussions from [the roslyn repo](https://github.com/dotnet/roslyn) with a note briefly explaining why. When we are aware of an existing discussion for the feature already in the new repo, we are adding a link to that. But we're not adding new issues to the new repos for existing discussions in this repo that the language design team does not currently envision taking on. Our intent is to eventually close the language design issues in the Roslyn repo and encourage discussion in one of the new repos instead.

Our intent is not to shut down discussion on language design - you can still continue discussion on the closed issues if you want - but rather we would like to encourage people to move discussion to where we are more likely to be paying attention (the new repo), or to abandon discussions that are no longer of interest to you.

If you happen to notice that one of the closed issues has a relevant issue in the new repo, and we have not added a link to the new issue, we would appreciate you providing a link from the old to the new discussion. That way people who are still interested in the discussion can start paying attention to the new issue.

Also, we'd welcome any ideas you might have on how we could better manage the transition. Comments and discussion about closing and/or moving issues should be directed to https://github.com/dotnet/roslyn/issues/18002. Comments and discussion about this issue can take place here or on an issue in the relevant repo.

-----------------

I am not moving this particular issue because I don't have confidence that the LDM would likely consider doing this.
