### ISSUE TITLE
Clean up GetAttributes in Cci.IReference/Cci.IDefinition

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#12677]
CCI, and the CLR, clearly differentiate between a definition and a reference. Both, however, may have attributes placed on them. In our symbol model, the distinction is far looser, which produces various ambiguity problems. There is no `GetAttributes` method on `IDefinition`, only on `IReference`. This leads to us often implementing both `IDefinition` and `IReference` for various symbols, including `NamedTypeSymbol`. This is especially problematic when the current implementation has implemented `IReference.GetAttributes` to GetAttributes for the definition, meaning that there's no place to stick attributes for the type reference itself.

`Cci.TypeReferenceWithAttributes` is really a work-around for this problem. Unfortunately, fixing it is not quite as simple as moving all existing `GetAttributes` implementations to `IDefinition` because 1) some definitions do not implement IDefinition and 2) some uses of `IReference.GetAttributes` *do* actually intend to put attributes on the reference (like in generic type parameters).

This entire area really just needs a cleanup and clear distinction as to what is a reference and what is a definition.

**Comment by tmat** [comment]
I propose that we delete CCI interfaces completely and access Roslyn symbols directly in the emitter. We do a lot of transformations that are not really necessary just to fit Roslyn's symbol model to CCI's. In some cases the CCI interfaces serve as a unification between VB and C#, so that the emit layer can be language agnostic. However, such interfaces can be replaces by better interfaces that match the Roslyn's symbol model. See, for example, ```IMethodSymbolInternal```, ```IAssembylSymbolInternal```, ```ILocalSymbolInternal``` etc.

**Comment by agocke** [comment]
I concur with @tmat's suggestion
