### ISSUE TITLE
SeparatedSyntaxList conversion should be explicit

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#12743]
**From API Review***

The follow conversion operator on `SeparatedSyntaxList<TNode>` should be `explicit`.

``` cs
public static implicit operator SeparatedSyntaxList<TNode> (SeparatedSyntaxList<SyntaxNode> nodes);
```

**Comment by CyrusNajmabadi** [comment]
@jaredpar I've looked back into this and i remember the logic for why this was an implicit instead of explicit operator.

The problem, essentially, is that there's no way to actually tell (AFAICT**) if the cast will succeed at cast time.  The time you find out about the problem is when you actually try to get an item.

As such, forcing hte user to write an explicit cast (which will never fail) didn't seem to be valuable since you'd still get the error later.

--

** Technically we could walk the entire separated list at cast time to tell if the cast is legal or not.  That seemed quite costly, so it was just made implicit so you could easily convert between things, without having to put the cast in.  

What are your thoughts on what we should do here?  Here are a few options

1.  Keep things as they are.
2. Make the cast explicit.  Have the explicit cast always succeed.
3. Make the cast explicit.  Do an actual O(n) check that the cast is legal.

Anything else?

**Comment by jaredpar** [comment]
Let's assume for a second that we're in the case where the cast is invalid (succeeds but later operation fails).  Can we give an example of what methods will begin failing?  

My worry is that there is a code path with a runtime failure that doesn't have any danger signs in user code.  An explicit cast would at least be a warning sign that something dangerous was happening here.  I definitely get now that it will always succeed but it will also be some level of warning to the user about dangers.

**Comment by CyrusNajmabadi** [comment]
A simple example of a method that would fail is the indexer.  You'll get a casting exception when that happens.

Note, that will happen in cases '1' and '2'.  Only case '3' can prevent it.  

> An explicit cast would at least be a warning sign that something dangerous was happening here. I definitely get now that it will always succeed but it will also be some level of warning to the user about dangers.

Maybe... though i'm unconvinced.  :)

**Comment by jaredpar** [comment]
I feel like we've ended in a bad place if I get a casting error without ever having to insert a cast into the code.  Consider it from a bug report perspective:

- Customer: I'm getting an invalid cast exception using an indexer on a syntax list.  What gives? 
- Roslyn Team: Oh you must have an invalid conversion between different `SeparatedSyntaxList<TNode>` types.
- Customer: Okay.  How do I find where that conversion may be happening?
- Roslyn Team: ...  

At that point how do we help the customer find the bad code?  If there is a cast we can at least tell them to look for explicit casts as one of them is likely wrong.

**Comment by CyrusNajmabadi** [comment]
I believe this should be 'by designed'.  Here's why: we already shipped the same pattern with ```SyntaxList<T>```.  i.e. SyntaxList already has both these conversion operators and both are *implicit*.  My work to add this operator to SeparatedSyntaxList just brought it inline with SyntaxList.  

IMO, these types should be consistent here and we should just accept that this implicit conversion is allowed, even if it is slightly 'wonky' from a type-safety perspective.  

@jaredpar @Pilchie What do you think?

**Comment by CyrusNajmabadi** [comment]
Giving to Jared to decide what we should do with this.  IMO consistency trumps the other concerns here.  We shipped SyntaxList like this since day1 and it hasn't been a problem.  So i think we should make SeparatedSyntaxList work the same way.

**Comment by Pilchie** [comment]
Bump to make this show up on @jaredpar's radar.
