### ISSUE TITLE
Changes to debug argument

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#12753]
In order to support easier migration to compiling projects across operating systems we're going to make the following changes to the `/debug` compiler flag:
- `/debug:full` and `/debug:pdbonly`: on windows produces a native windows PDB, on any other OS produces a portable PDB.
- `/debug:windows`: always produces a native windows PDB irrespective of operating system. 
- `/debug:portable`: unchanged, always produces a portable PDB.

This will help facilitate transitioning to non-Windows OS.  Pretty much every csproj in existence today ends up passing `/debug:full` due to the setup of targets.  Making this a flexible value will remove one blocker to migrating existing projects across OS.  The `/debug:windows` flag will be added as a way to force windows should that be important for any customers.

**Comment by jaredpar** [comment]
CC @tmat

**Comment by tmat** [comment]
Do we want to amend the spec above to say ```/debug:{full|pdbonly}``` produce Windows PDB iff on Desktop FX?

**Comment by tmat** [comment]
@marek-safar

**Comment by jaredpar** [comment]
That would break CoreCLR and we have a dependency on producing Windows PDBs on CoreCLR.

**Comment by tmat** [comment]
Ah, right.

**Comment by tmat** [comment]
Explicitly excluding Mono on Windows seems wrong. Not sure what to do here.

**Comment by jaredpar** [comment]
Have we confirmed that Mono definitely can't handle the very limited COM we do here?  Or is it possible for us to simplify the COM in any way to make it work with Mono?

**Comment by tmat** [comment]
Confirmed. I don't think it can be any simpler. It fails to call Initialize:

```
        void Initialize([MarshalAs(UnmanagedType.IUnknown)] object emitter, string filename, [MarshalAs(UnmanagedType.IUnknown)] object ptrIStream, bool fullBuild);
```

**Comment by marek-safar** [comment]
Maybe we can instead of checking UnixPath check if we can initialise that COM interface. I don't know how you handle xbox support but would it help there as well?

**Comment by tmat** [comment]
Falling back to portable if Windows PDB doesn't work has a couple of problems: first, it's unpredictable -- even on Desktop FX the initialization might potentially fail due to corrupted files, bad setup, etc. So the fallback would just hide the root cause and emit something that was not expected. Second, how do you explain what /debug:full does? Something like "sometimes it's Windows PDB if everything works fine and otherwise it's Portable" isn't a great specification.

**Comment by marek-safar** [comment]
Yeah, I agree that's not great. We are back to check if you are running on Mono runtime. It looks like you already have the check in GlobalAssemblyCache

https://github.com/dotnet/roslyn/blob/8bf5cc41fa92887fea90b9d67f5c01d2a5f5609e/src/Compilers/Shared/GlobalAssemblyCacheHelpers/GlobalAssemblyCache.cs#L20

**Comment by tmat** [comment]
We do. The check itself isn't the problem. GAC just has a different implementation but the experience for the user is the same. Here the output would be different and documenting /debug:full as on "Windows but not Mono" it's Windows PDB otherwise Portable is again not ideal. Is Mono on Windows an important scenario to address **by default**? One can always explicitly switch to Portable PDB.

**Comment by jcouv** [comment]
What's the latest status on this?

**Comment by jaredpar** [comment]
This should be fixed now.
