### ISSUE TITLE
Permissions for vslsnap/roslyn are set up incorrectly

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#12788]
The permissions for `vslsnap/roslyn-internal` use teams, such as Roslyn and Roslyn Infrastructure.
But the permissions for `vslsnap/roslyn` only has a list of individual collaborators.

**Comment by jasonmalinowski** [comment]
GitHub seems strange here -- public repositories can't be given access by teams, but private ones can. I'm not sure if their real belief is that we shouldn't be using vslsnap's fork at all for this, and should just be creating branches directly in the main roslyn repo so that way everybody has permissions.

**Comment by jasonmalinowski** [comment]
According to GitHub support, you can't add teams as collaborators to public repositories, only internal ones. So we have to live with this silliness for now.

**Comment by jasonmalinowski** [comment]
Thankfully with new GitHub features we can fix this. #13740 tracks that now.
