### ISSUE TITLE
Hang in PersistentStorageService.GetStorage

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#12845]
**Version Used**: 
2.0.0.6073101

**Steps to Reproduce**:
Not consistent, but in my case:

1. Open Roslyn.sln
2. Browsed code for a while
3. Invoked "Go To Implementation" on `AbstractOleCommandTarget`

UI thread, and many threadpool threads all blocked in:
>	Microsoft.VisualStudio.LanguageServices.dll!Microsoft.VisualStudio.LanguageServices.Implementation.PersistentStorageService.GetStorage(Microsoft.CodeAnalysis.Solution solution, string workingFolderPath) Line 106	C#

Dump file at \\\\ddfiles\team\public\kevinpi\GetStorageHang.dmp

**Comment by Pilchie** [comment]
@heejaechang Does this look related to anything you've changed recently?

**Comment by heejaechang** [comment]
@Pilchie let me take a look. but my recent change didn't touch anything related to this though.

**Comment by heejaechang** [comment]
@Pilchie this is not dead lock but looks like creating the very first esent db is taking long time. basically, it calls into esent.init which will create the db the very first time. while esent is being created, it does that under lock, so all other calls are blocked by that lock until esent comes back from initialization (there is no call back to us, and lock is our lock)

is this the very first time Roslyn is opened, or it got crashed so VS is recovering from previous crash?

asking since recovery can take a while depends on how much persisted data got corrupted due to crash.

if it is very first time db is created, it should be reasonably fast enough, not sure why it is so slow..

unfortunately, there is no time out on init in Esent.

**Comment by Pilchie** [comment]
I don't remember if it was after a crash, but it was on a relatively slow VM with a slow disk.  Still I waiting 5 minutes after VS stopped responding before attaching and capturing the dump.

**Comment by heejaechang** [comment]
I think I need actual repro machine to find out why creating roslyn is so slow, dump just show it is still creating, it doesn't show why it is slow.

**Comment by Pilchie** [comment]
Now I forget what machine this was on, but I'll let you know if I see it again.

**Comment by heejaechang** [comment]
I will close this since it haven't repro. please re-active if it repro.
