### ISSUE TITLE
Roslyn TODOs

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#12844]
Within the Roslyn codebase there seems to be a lot of `ToDo` comments, we should have an issue which lists the all and tracks them. So that they can be reviewed to see if they're still relevant, if not remove them. If they require additional work, we can potentially tag them as `Up For Grabs`, for the community to work on.

**Comment by dsaf** [comment]
Maybe they are doing a field testing of a ReSharper-like [TODO window](https://www.jetbrains.com/help/resharper/2016.1/Reference__Windows__To-do_Explorer.html)?

**Comment by AdamSpeight2008** [comment]
@dsaf  They seem to be more about what the code so do, or changes to do, which is an issue as external contributors can not refer to some of the notes mentioned in them. Or those issues have been corrected and the `ToDo` has not been deleted. 

I've attach a text file containing all of the `ToDo`
[todo.txt](https://github.com/dotnet/roslyn/files/393985/todo.txt)

**Comment by gafter** [comment]
While I agree with the original issue, and it is work that we are planning, this issue is not likely to help us organize that work in any way (it represents hundreds of individual small work items spread across many teams). Therefore we are going to close this and track the items separately as we work on them.
