### ISSUE TITLE
RuntimeBinderException on inherited interfaces

### ISSUE THREAD

**Issue by IAmTheCShark** [dotnet/roslyn#12995]
When using the dynamic-Keyword there is a bug regarding interface-methods that are inherited from "baseinterfaces"

It seems, that those methods that are defined in a base interface cannot be resolved and thus result in a RuntimeBinderException

Here is the related [StackOverFlowQuestion Question](http://stackoverflow.com/questions/38828713/runtimebinderexception-on-inherited-interfaces) where i initially asked and Jon Skeet suggested to raise an issue here. 

Example to reproduce the Bug:

```
using System;

class Program
{
    static void Main(string[] args)
    {
        dynamic dyn = new Record();

        IAdvancedTable advTable = new Table();
        ITable table = advTable;

        // works like a charm using the "base-interface"
        table.Insert(dyn);


        // using the inherited interface throws the RuntimeBinderException
        advTable.Insert(dyn);

        Console.ReadKey();
    }
}

public interface ITable
{
    void Insert(Record record);
}

public interface IAdvancedTable : ITable{}

public class Table : IAdvancedTable
{
    public void Insert(Record record){ /*STUB*/ }
}

public class Record{}
```

**Comment by jcouv** [comment]
It looks like this is a problem in .NET Framework (the desktop framework) and it was fixed in .NET Core (see [sharplab](https://sharplab.io/#v2:C4LgTgrgdgNAJiA1AHwAICYCMBYAUHjAAlUwHY8BvPQm4zANmIBZCBZAQwEsoAKEgBgDaAXULswAcwDOASmq0quWssJwAnlHYBbTgGNVGwgF5CUAKYB3QgCUzugPZg4PGQG488lYQCSAQTgAbuxQumZwACrsAEYANmZigZGx8SbmVklxLu5KXj4Z8cDRccYJAfnZnioA9FWEFo4A1lKEMZwN8eyEugAW4lrE/ITA3fEARFHsUmYAtNzAZmAAZuyho5XKhckAdN5QU2DAPOpQbh74OV41A0MjhNwjYJzzcHdQ80srBd1g9hbNw/FrNBgJwtGYAELcOALACiAA9QgAHEH2KDrWjsRJFMw7PYLQ7HU7nXKEGoAYVRUnscS2tkxAGkzGospUAL54dnnVAAZle72WoTy2MolVQLF2+0OtgcTkIYDsjjgRM5BF5cwWAvifkCwVCEWxhBAQuSFBVuB5xHQhHyhp8/iCITC+RFF2IvLFPjxBx40sVcoVThkFDoAE4eKMwMFRm5CJyzRaiL6nKagA) shows no RuntimeBinderException when selecting the "Run" mode).
I'm going to close as Won't Fix because the bar for fixing issues in the desktop framework is exceptionally high and this wouldn't meet the bar.
