### ISSUE TITLE
[Idea] Initializer List: advanced constructor for child objects

### ISSUE THREAD

**Issue by moser96** [dotnet/roslyn#13173]
I think it would be nice if we could get the option to forward some arguments from the constructur to a child object's constructor. In C++ this technique is called Initializer List (http://www.geeksforgeeks.org/when-do-we-use-initializer-list-in-c/).

Here is an example:

```
    public class Kunde
    {
        public int Money { get; set; }
        public Person Person { get; set; }

        public Kunde(int money, string firstname, string lastname):Person(firstname, lastname)
        {
            Money = money;
        }
    }

```

```
    public class Person
    {
        public string Firstname { get; set; }
        public string Lastname { get; set; }

        public Person(string firstname, string lastname)
        {
            Firstname = firstname;
            Lastname = lastname;
        }
    }
```

**Comment by svick** [comment]
How is that better than the following?

```
public Kunde(int money, string firstname, string lastname):
{
    Money = money;
    Person = new Person(firstname, lastname);
}
```

Is the advantage just saving a few characters?

In C++, this is an important feature, because you need to ensure fields are initialized. In C#, all fields are initialized to `default(T)`, so that is not an issue.

**Comment by moser96** [comment]
In C++ this technique is also increasing the performance as mentioned in the link I posted section 6: http://www.geeksforgeeks.org/when-do-we-use-initializer-list-in-c/

**Comment by svick** [comment]
I don't see how that is applicable to C#. C# does not have copy constructors, assignment operators or destructors on value types. Do you have any reason to think the performance in C# could be improved by this? I.e. how would the generated IL differ?

**Comment by moser96** [comment]
I don't know. I just though it would be a nice short way and maybe it could also improve the performance like in C++, but if it isn't like that this issue is obsolete.

**Comment by gafter** [comment]
We are now taking language feature discussion in other repositories:
- https://github.com/dotnet/csharplang for C# specific issues
- https://github.com/dotnet/vblang for VB-specific features
- https://github.com/dotnet/csharplang for features that affect both languages

Features that are under active design or development, or which are "championed" by someone on the language design team, have already been moved either as issues or as checked-in design documents. For example, the proposal in this repo "Proposal: Partial interface implementation a.k.a. Traits" (issue 16139 and a few other issues that request the same thing) are now tracked by the language team at issue 52 in https://github.com/dotnet/csharplang/issues, and there is a draft spec at https://github.com/dotnet/csharplang/blob/master/proposals/default-interface-methods.md and further discussion at issue 288 in https://github.com/dotnet/csharplang/issues. Prototyping of the compiler portion of language features is still tracked here; see, for example, https://github.com/dotnet/roslyn/tree/features/DefaultInterfaceImplementation and issue 17952.

In order to facilitate that transition, we have started closing language design discussions from [the roslyn repo](https://github.com/dotnet/roslyn) with a note briefly explaining why. When we are aware of an existing discussion for the feature already in the new repo, we are adding a link to that. But we're not adding new issues to the new repos for existing discussions in this repo that the language design team does not currently envision taking on. Our intent is to eventually close the language design issues in the Roslyn repo and encourage discussion in one of the new repos instead.

Our intent is not to shut down discussion on language design - you can still continue discussion on the closed issues if you want - but rather we would like to encourage people to move discussion to where we are more likely to be paying attention (the new repo), or to abandon discussions that are no longer of interest to you.

If you happen to notice that one of the closed issues has a relevant issue in the new repo, and we have not added a link to the new issue, we would appreciate you providing a link from the old to the new discussion. That way people who are still interested in the discussion can start paying attention to the new issue.

Also, we'd welcome any ideas you might have on how we could better manage the transition. Comments and discussion about closing and/or moving issues should be directed to https://github.com/dotnet/roslyn/issues/18002. Comments and discussion about this issue can take place here or on an issue in the relevant repo.

-----------------

I am not moving this particular issue because I don't have confidence that the LDM would likely consider doing this.
