### ISSUE TITLE
[C# Feature Request] Nested Enums / Enum groups

### ISSUE THREAD

**Issue by lmcarreiro** [dotnet/roslyn#13192]
Is there a chance to add Nested Enum feature in C# 7? It's annoying to create nested classes to group constants... It could have some way to define if an intermediate level of the tree (a non-leaf node) is a valid enum value or not... And it would be even better if when specifying a type, I could use the enum name or an intermediate node.

Something like:

``` c#
enum Color
{
    !Primary // ! means that Primary is an enum group, not an enum value
    {
        Red,
        Green,
        Blue
        {
            LightBlue,
            DarkBlue,
        },
    },
    !Secundary
    {
        Yellow,
        Cyan,
        Magenta,
    },
}


// Method definitions

void Method1(Color color);                  // ok
void Method2(Color.Primary primaryColor);   // ok
void Method3(Color.Primary.Blue blueColor); // error: 'Color.Primary.Blue' is an enum value, not a group


// Method calls

Method1(Color.Primary);                // error: 'Color.Primary' is a group, not a value
Method1(Color.Primary.Red);            // ok
Method1(Color.Secundary.Yellow);       // ok

Method2(Color.Primary.Blue);           // ok
Method2(Color.Primary.Blue.LightBlue); // ok
Method2(Color.Secundary.Yellow);       // error: 'Color.Secundary.Yellow' value is not from 'Color.Primary' group
```

**Comment by dsaf** [comment]
> ...in C# 7?

No. https://github.com/dotnet/roslyn/blob/master/docs/Language%20Feature%20Status.md

> ...to group constants...

https://github.com/dotnet/roslyn/issues/11165

> ...

I would imagine something that relies on #728 and/or #4586.

**Comment by gafter** [comment]
We are now taking language feature discussion in other repositories:
- https://github.com/dotnet/csharplang for C# specific issues
- https://github.com/dotnet/vblang for VB-specific features
- https://github.com/dotnet/csharplang for features that affect both languages

Features that are under active design or development, or which are "championed" by someone on the language design team, have already been moved either as issues or as checked-in design documents. For example, the proposal in this repo "Proposal: Partial interface implementation a.k.a. Traits" (issue 16139 and a few other issues that request the same thing) are now tracked by the language team at issue 52 in https://github.com/dotnet/csharplang/issues, and there is a draft spec at https://github.com/dotnet/csharplang/blob/master/proposals/default-interface-methods.md and further discussion at issue 288 in https://github.com/dotnet/csharplang/issues. Prototyping of the compiler portion of language features is still tracked here; see, for example, https://github.com/dotnet/roslyn/tree/features/DefaultInterfaceImplementation and issue 17952.

In order to facilitate that transition, we have started closing language design discussions from [the roslyn repo](https://github.com/dotnet/roslyn) with a note briefly explaining why. When we are aware of an existing discussion for the feature already in the new repo, we are adding a link to that. But we're not adding new issues to the new repos for existing discussions in this repo that the language design team does not currently envision taking on. Our intent is to eventually close the language design issues in the Roslyn repo and encourage discussion in one of the new repos instead.

Our intent is not to shut down discussion on language design - you can still continue discussion on the closed issues if you want - but rather we would like to encourage people to move discussion to where we are more likely to be paying attention (the new repo), or to abandon discussions that are no longer of interest to you.

If you happen to notice that one of the closed issues has a relevant issue in the new repo, and we have not added a link to the new issue, we would appreciate you providing a link from the old to the new discussion. That way people who are still interested in the discussion can start paying attention to the new issue.

Also, we'd welcome any ideas you might have on how we could better manage the transition. Comments and discussion about closing and/or moving issues should be directed to https://github.com/dotnet/roslyn/issues/18002. Comments and discussion about this issue can take place here or on an issue in the relevant repo.

-----------------

I am not moving this particular issue because I don't have confidence that the LDM would likely consider doing this.

**Comment by lmcarreiro** [comment]
There is a similar request in https://github.com/dotnet/csharplang/issues/587
