### ISSUE TITLE
diagnostic analyzer tagger needs to listen to WorkspaceRegistration.WorkspaceChanged event

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#13260]
for this particular case which cache data based on workspace/projectid/documentid that it got from ITextBuffer should consider that workspace ITextBuffer is associated to can be changed over time.

for example, when a user add/open/close/remove document, its associated ITextBuffer will move between misc workspace and host workspace.

diagnostic analyzer tagger should clear and refresh tags when WorkspaceChanged events are raised.

...

* NOTE * there could be more tagger or service than diagnostic analyzer tagger that needs to listen to this event. we might need to audit our code base that is working on top of ITextBuffer

**Comment by CyrusNajmabadi** [comment]
I do not understand the contract of the analyzer service.  I asked @heejaechang to open this bug because it's clear that there's a lot of confusion here.  I'd prefer if heejae or @mavasani could put this sort of logic into the core diagnostic service API so that any clients could get data from it without having to guess at a lot of the contracts/assumptions it makes.  They are best suited to appropriately exposing this API.

**Comment by heejaechang** [comment]
I believe @CyrusNajmabadi already fixed it.
