### ISSUE TITLE
Phase ordering and bound node design issues for tuple deconstruction

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#13270]
The current bound node for tuple deconstruction contains both the bindings and an execution plan for the deconstruction operation. Consequently, the execution plan ("steps") for deconstruction are computed in initial binding. That is inconsistent with the design principles for the initial bound nodes, and the phase ordering of the compiler.

Generally speaking, the initial binding phase should do just binding (e.g. of names to the things the names refer to). Execution order is the responsibility of lowering (and to a lesser extent flow analysis). When the execution plan is constructed in lowering, it can be reflected in a fully lowered body of code that uses the more primitive operations. Related to this, the tuple conversion is likely to need to represent the sequence of underlying element-wise conversions (as that is part of binding the meaning of a tuple conversion).

When the refactoring needed to make the internal representation of deconstruction consistent with these design principles is completed, I suspect the placeholder nodes will no longer be needed.

**Comment by jcouv** [comment]
Fixed by #17027

The `BoundDeconstructionAssignmentOperator` now has:
 - a `BoundTupleLiteral` as its Left,
 - a `BoundConversion` as its Right, holding:
     - a tree of `Conversion` objects with Kind=Deconstruction, information about a Deconstruct method (optional) and an array of nested `Conversions` (like a tuple conversion),
     - an `BoundExpression` as its Operand.

There are some further refinements we could consider, such as re-using the `BoundAssignmentOperator` bound node (but this is somewhat visible through IOperation public APIs). Also, there is still one use of placeholders.
If you feel those should be fixed or tracked, let me know and we can create an issue.
