### ISSUE TITLE
Iterator Function return an Interface inheriting IEnumerable(Of T)

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#13284]
Allow `Iterator Function` to return an interface that inherits from `IEnumerable(Of T)`

```
    Private Iterator Function _Ascending_(x As Integer, y As Integer) As IOrderedEnumerable(Of Integer)
        Debug.Assert(x <= y)
        For i = x To y
            Yield i
        Next
    End Function
```

**Comment by HaloFour** [comment]
How would the compiler implement the remaining required members?

**Comment by svick** [comment]
What would be the point? `IOrderedEnumerable(Of T)` is useful, because you can call `ThenBy()` on it. But I don't know how would that be useful here, at least not without adding some way to specify the groups that can be reordered internally.

**Comment by HaloFour** [comment]
It's only useful if it provides an implementation of `CreateOrderedEnumerable` that actually does that work.  `ThenBy`, etc. are just fluent wrappers to calling that interface method.

If the CLR ever gets default interface implementations then it might make sense to allow for iterators to return an interface where the only require member is `GetEnumerable`.  Otherwise the appropriate route would be to define a type that implements the interface and have the iterator logic in `GetEnumerable`.

**Comment by gafter** [comment]
Closing, as we don't know the meaning of the proposal (as seen by the lack of answers to the questions). If the OP is interested in pursuing this further, please do so on `vbland` or `csharplang`.
