### ISSUE TITLE
[Idea] Stylistic Independence.

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#13313]
Our personal preference to the look of code, should be independent of the repositories preference.
Eg. 
When I open code in the editor I see it in my preferred style.
Saving the code, I reverts to the repositories style.
It could do a run of the Roslyn Code Formatter.

**Comment by DavidArno** [comment]
I think this would have limited use, probably just being limited to `{}` placement and tabs/spaces. Anything else risks information loss. For example, we might have three options around using expression bodies for single line methods:

1. Always use expression bodies,
2. Leave as is,
3. Never use expression bodies.

If we then have three people accessing the following piece of code:

````cs
void F1() => (some behaviour);

void F2()
{
     (some other behaviour);
}
````
If person 2 accesses this file, all will be well. When either person 1 or 3 access it though, the fact that the two styles were being used (maybe because `(some other behaviour)` is a long expression spanning multiple lines that are ungainly with an expression body) will be lost. There-after, person 2 will just get the format of whomever of 1 & 2 had last edited it.

**Comment by AdamSpeight2008** [comment]
More that the diff should more focused on semantic changes, rather stylistic one. For example whitespace changes (generally don't affect semantic meaning, in c# and vb).

**Comment by whoisj** [comment]
This is almost an ideal thing for git filters to do, of course the complexity comes from Windows rather slow start up of processes and the cost of checkout. Use of a tool like donet/codeformatter this way could make style wars a thing of the past - though git-checkout could get cumbersome.

**Comment by HaloFour** [comment]
It annoys me to no end how much trivial whitespace completely screws up diff tools for source control.  It stinks that we haven't reached the point where the source could just retain the semantics whereas style can be driven entirely by user preference.

@DavidArno 

IntelliJ actually has a nice feature where it will take known code patterns that can be simplified using new language features and displays it using the new syntax.  The replaced code in the view is highlighted differently and you can click on the section to see/edit the underlying code.  It's kind of nice when a blob of anonymous class definitions in existing code is reduced to a few lines of lambdas in the editor.

**Comment by Joe4evr** [comment]
Well, looking at [The Future of Visual Studio "15"](https://channel9.msdn.com/Events/Visual-Studio/Visual-Studio-Live-Redmond-2016/W15), `.editorconfig` will get first class support in the next release of the IDE, which at least will be useful for the language-agnostic .

**Comment by Pilchie** [comment]
I don't expect that this is something we will do any time soon - instead, as @Joe4evr notes, we're working on making it easier to enforce a consistent style for teams.

**Comment by sharwell** [comment]
Tentatively marking as **Won't Fix**, but will leave it open until I can get feedback from a design review meeting.

**Comment by sharwell** [comment]
During our 8 October design review, we agreed that rather than striving for "stylistic independence", we are working to avoid the headaches of different styles via "stylistic automation and uniformity". The high-level feature request in this issue is certainly interesting, but at this point it doesn't align with our overall direction and we believe that our current direction will address many of the same underlying team development challenges that lead to feature requests like this.
