### ISSUE TITLE
Code fix for CS0103 suggests to change non-existing name to snippet shortcut

### ISSUE THREAD

**Issue by JosefPihrt** [dotnet/roslyn#13345]
I have following code:
```csharp
var x = foo; // CS0103: The name 'foo' does not exists in the current context
```
Code fix for this error suggests to change 'foo' to 'for', 'ifoo', 'oo' which are snippet shortcuts.

Is it intentional behavior to include snippet shortcuts in the list of possible fixes?

In any case, ```for``` is keyword, so It should not be suggested.

**Comment by Pilchie** [comment]
IIRC - the design here is that we basically use the contents of your completion list as the "dictionary" for the spell check algorithm, so if snippets are in completion, then they are possible corrections.

**Comment by Pilchie** [comment]
@CyrusNajmabadi Is there anything we can leverage to remove nonsensical items from the dictionary?

**Comment by CyrusNajmabadi** [comment]
Snippets def seem like something that we likely shouldn't be spell-checking to.  That's because the purpose of spell check is to take something wrong and make it 'right' in the context of the code there.  Whereas a snippet still isn't 'right', it's merely a trigger to insert something else.  I find it fairly unlikely that anyone would want to correct to a snippet, then hit tab to insert it.

--

I think we should be able to filter this out without much problem.  As we're calling directly into the CompletionService and getting real CompletionItems out, we should be able to see if their tags indicate that they're a snippet.
