### ISSUE TITLE
Proposal: Extended ConditionalAttribute 

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#13454]
- Option to not keep source method in the resultant assembly:

``` cs
[Conditional("DEBUG", KeepInSource = false)]
public static void Test() { .. }
```
- Ability to use on static classes (public methods can only return `void`):

``` cs
[Conditional("DEBUG", KeepInSource = false)]
internal static class Verification
{
  public static void M1() { .. }
  private static int F1() { .. }
}
```

**Comment by svick** [comment]
Number 2 sounds quite similar to a more general proposal you made, https://github.com/dotnet/roslyn/issues/12887.

**Comment by tannergooding** [comment]
I feel like this would have some weird implications for determinism.

It is also completely different from the way ConditionalAttributes work today. Today the method calls are just not emitted, but you can still execute code marked with Conditional via Reflection. This would no longer be possible if you chose not to emit the source code.

It also feels like this is easily achieved (although possibly not as 'cleanly') using either `#if DEBUG` or conditionally including the file in your  project (msbuild, make, etc).

**Comment by alrz** [comment]
@svick I though you are mentioning #7875. Either way, the point is to not ship the type to the production binaries (for example) which #12887 doesn't accomplish. I'm using existing concepts here while #7875 is mostly inspired by Java and Rust and depends on source attributes.

@tannergooding 

>It is also completely different from the way ConditionalAttributes work today. Today the method calls are just not emitted, but you can still execute code marked with Conditional via Reflection. This would no longer be possible if you chose not to emit the source code.

That is actually a clever idea but it doesn't prevent shipping the method to the production (when you are not intended to) and it can't be done with `#if` either because it doesn't affect method calls.

>I feel like this would have some weird implications for determinism. [...] It also feels like this is easily achieved (although possibly not as 'cleanly') using either #if DEBUG

I'm not sure  what is the different between `#if` and `ConditionalAttirbute` in terms of determinism. In the bright side, `ConditionalAttirbute` always compiles while `#if` may break the build (rel. #13282).

**Comment by HaloFour** [comment]
```cs
#if DEBUG
internal static class Verification
{
  [Conditional("DEBUG")]
  public static void M1() { .. }
  [Conditional("DEBUG")]
  private static int F1() { .. }
}
#endif
```

Even assuming modifications to `ConditionalAttribute` are worth it, I'd go with a different name than `KeepInSource`.  Maybe `ExcludeFromAssembly` or something.

**Comment by alrz** [comment]
@HaloFour Your example surely works but I'm reluctant to use `#if` overall, it seems too hacky IMO.

PS: I'm not very good at naming things.

**Comment by gafter** [comment]
We are now taking language feature discussion in other repositories:
- https://github.com/dotnet/csharplang for C# specific issues
- https://github.com/dotnet/vblang for VB-specific features
- https://github.com/dotnet/csharplang for features that affect both languages

Features that are under active design or development, or which are "championed" by someone on the language design team, have already been moved either as issues or as checked-in design documents. For example, the proposal in this repo "Proposal: Partial interface implementation a.k.a. Traits" (issue 16139 and a few other issues that request the same thing) are now tracked by the language team at issue 52 in https://github.com/dotnet/csharplang/issues, and there is a draft spec at https://github.com/dotnet/csharplang/blob/master/proposals/default-interface-methods.md and further discussion at issue 288 in https://github.com/dotnet/csharplang/issues. Prototyping of the compiler portion of language features is still tracked here; see, for example, https://github.com/dotnet/roslyn/tree/features/DefaultInterfaceImplementation and issue 17952.

In order to facilitate that transition, we have started closing language design discussions from [the roslyn repo](https://github.com/dotnet/roslyn) with a note briefly explaining why. When we are aware of an existing discussion for the feature already in the new repo, we are adding a link to that. But we're not adding new issues to the new repos for existing discussions in this repo that the language design team does not currently envision taking on. Our intent is to eventually close the language design issues in the Roslyn repo and encourage discussion in one of the new repos instead.

Our intent is not to shut down discussion on language design - you can still continue discussion on the closed issues if you want - but rather we would like to encourage people to move discussion to where we are more likely to be paying attention (the new repo), or to abandon discussions that are no longer of interest to you.

If you happen to notice that one of the closed issues has a relevant issue in the new repo, and we have not added a link to the new issue, we would appreciate you providing a link from the old to the new discussion. That way people who are still interested in the discussion can start paying attention to the new issue.

Also, we'd welcome any ideas you might have on how we could better manage the transition. Comments and discussion about closing and/or moving issues should be directed to https://github.com/dotnet/roslyn/issues/18002. Comments and discussion about this issue can take place here or on an issue in the relevant repo.

I am not moving this particular issue because I don't have confidence that the LDM would likely consider doing this.
