### ISSUE TITLE
Autocompletion does not preselect typed keyword if it appeared on delete

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#13481]
**Version Used**: 15.0.25618.0/2.0.0.60808

**Steps to Reproduce**:

1. Ensure you have Options > Text Editor > C# > IntelliSense > Show completion list after character is _deleted_ checked.
2. Type `DateTimeOffset.`
3. Backspace to `DateTime`

**Expected Behavior**:
The `DateTime` to get preselected, so that typing a dot will result in `DateTime.`
**Actual Behavior**:
`DateTimeOffset` stays selected and typing a dot will result in `DateTimeOffset.`

Note that if the final dot is not typed at step 2., it behaves as expected.

**Comment by CyrusNajmabadi** [comment]
Looks like the same behavior exists for VB.  

We've got the following code:

```c#
                else if (model != null && model.Trigger.Kind != CompletionTriggerKind.Deletion)
                {
                    // Filter the model if it wasn't invoked on backspace.
                    sessionOpt.FilterModel(
                        CompletionFilterReason.BackspaceOrDelete,
                        recheckCaretPosition: false,
                        dismissIfEmptyAllowed: true,
                        filterState: null);
                }
```

@Pilchie @DustinCampbell  I think this was so that if you brought up completion by deleting, we would show you everything in the list, and not just the filtered down items.  I think that's reasonable, however we might want to still do the appropriate work to select an appropriate item, even if we don't filter out items.

What do you think?

**Comment by DustinCampbell** [comment]
I seem to remember VB filtering on backspace.

**Comment by Pilchie** [comment]
Tagging @rchande and @jasonmalinowski in case they remember the behavior for VB.  My memory tends to agree with @CyrusNajmabadi though.  Maybe this is something we changed from VS2013?
