### ISSUE TITLE
[caret placement] Convert property to method

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#13495]
This is part of our effort to make our quick actions more discoverable by having them triggered where expected.

![image](https://cloud.githubusercontent.com/assets/1402694/18141254/aa80132a-6f6d-11e6-9384-1ff6546e4d68.png)

Today, I only get this quick fix if I am in (1-3). In order to avoid clutter, this makes sense. However, if I select the entire property `Gpa` and press `Ctrl+.`, I only get the quick fix to "Generate constructor":
![image](https://cloud.githubusercontent.com/assets/1402694/18143364/8aa91b7e-6f76-11e6-8afa-ce6ca624e6ab.png)
Let's offer the Convert property to method quick fix for the entire selection.

**Comment by CyrusNajmabadi** [comment]
Closing out.  Our locations for offering this are now correct as per the design we came up with for refactorings + nodes.  Specifically, we offer in 1-3, and at the end of the property.  Also, if you select the entire property, we'll offer the feature.  

This fits the general models of:
1. we offer anywhere in hte header.
2. we offer at teh end.
3. we offer if you select the entire construct.

**Comment by jmarolf** [comment]
I really wish we would re-consider this design. It makes it almost impossible to trigger these refactorings unless you wrote them or are on the team that wrote them. What is the rational for not offer this refactoring in locations 4-11? This feels similar to the research that was done for [this](https://github.com/dotnet/roslyn/pull/38271) pull request. 

Basically, in every UX lab where we sit a customer down, _even if they know a refactoring exists_, they cannot figure out how to trigger it. Perhaps this is the wrong approach for this refactoring but I wish we had something to track discoverability because I think its something that is worth revisiting.

**Comment by CyrusNajmabadi** [comment]
> What is the rational for not offer this refactoring in locations 4-11?

When we redesigned the refactoring selection logic, we did a bunch fo experimenting and found that refactorings were far too annoying and noisy when they appeared *inside* constructs.  i.e. when they appeared within things that are commonly felt to be children of the construct they apply to.  

We also found that it was common to try to invoke this stuff on the 'header' of a symbol, or the end, or with the entire thing selected.

So we've implemented a generalized system that we can move all refactorings to that attempts to codify this in a generally consistent fashion.  That way we can put fixes in one location instead of having to do one-off fixes for all refactorings.

> Basically, in every UX lab where we sit a customer down, even if they know a refactoring exists, they cannot figure out how to trigger it. Perhaps this is the wrong approach for this refactoring but I wish we had something to track discoverability because I think its something that is worth revisiting.

Note: this is an example of a feature that we've *updated* based on that experience.  i.e. this used to be allowed in a much narrower range.  I'm closing this out because we've at least expanded this to the known types of locations that we found people were trying.

**Comment by jmarolf** [comment]
@CyrusNajmabadi I think its fine that this has been closed, as long as we do some validation that the new behavior did fix the problem :)

**Comment by CyrusNajmabadi** [comment]
Talked with @mikadumont .  We definitely have work to do here for lots of features.  We're going to continue to track those with a top level issue (as well as any individual feature issues that come up).  But as we close down on particular features, we will close out the issues for them.

We're definitely not done here by a long shot :)   but we do have a mch better internal mechanism to update our individual features to as we get time to do it :)
