### ISSUE TITLE
Please implement CS0075 for casting a negative number

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#13585]
The code

``` cs
var x = (MyEnum)-1;
```

used to give a more useful diagnostic in the native compiler than is given by Roslyn.

Please reinstate the old diagnostic for this.

See also http://stackoverflow.com/questions/39091380/why-isnt-the-c-sharp-compiler-able-to-cast-a-literal-negative-value-to-an-enum

**Comment by a-ctor** [comment]
I did a basic implementation of the issue [here](/a-ctor/roslyn/commit/330accb543e2a2301bdd0700ddcf5fe1d30df06d). The implementation adds back the Error code for `CS0075`, the error message and emits the error (seen below).

-----

*Example input: (Example.cs)*

```c#
class Program
{
    static void Main()
    {
        var z = (System.ConsoleColor) - 1;
    }
}
```

*Compiled with:*

```
Binaries\Debug\Exes\csc\csc.exe Example.cs
```

*Output:*
```
Microsoft (R) Visual C# Compiler version 42.42.42.42424
Copyright (C) Microsoft Corporation. All rights reserved.

Example.cs(5,18): error CS0119: 'ConsoleColor' is a type, which is not valid in the given context
Example.cs(5,17): error CS0075: To cast a negative value, you must enclose the value in parentheses.
```

----

I have a question regarding the implementation:

 - As seen in the output above the implementation _adds_ the `CS0075` error instead of replacing `CS0119`. Should the error replace the previous one?

**Comment by gafter** [comment]
@jaredpar Please assign this to someone guide this through the PR process (me, if you like).

**Comment by OmarTawfik** [comment]
@a-ctor regarding your question, I think we should try and match the native compiler in all cases. For example, compiling your `Example.cs` on my machine using `c:\Windows\Microsoft.NET\Framework\v4.0.30319\csc.exe` gives:

`error CS0075: To cast a negative value, you must enclose the value in parentheses
error CS0119: 'System.ConsoleColor' is a 'type', which is not valid in the given context`

Would you please file a PR for your implementation and tag me? Please let me know if you've any questions regarding implementation or testing.

**Comment by a-ctor** [comment]
@OmarTawfik PR has been merged so this issue can be closed.

**Comment by OmarTawfik** [comment]
@a-ctor thanks for your contribution!
