### ISSUE TITLE
Proposal: Implicitly dereferenced nullables

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#13598]
With non-nullable references on the way (#5032), would something like Swift's "implicitly unwrapped optionals" makes sense for C#?
```cs
class C : IInitializable  {

  protected void OnPropertyChanged([CallerMemberName] string! propertyName = null) {
    // propertyName must be able to be assigned to null as the default argument value
    // but we know it wouldn't be null, otherwise a runtime error will be produced
    // however in this case we could define it as a string? and ignore nulls
  }

  // _state wouldn't be initialized in the constructor
  // but we know that it will be initialized at some point
  private string! _state;

  public C() {
    // leave _state uninitialized with no compile-time error
  }

  string? P { get; }

  // this interface is defined pre nullable reference types
  // but we know that the argument wouldn't be null
  // so that we can write o.GetType() without "dereferencing possible null pointer" error
  // otherwise it should be o?.GetType() if we're not sure or o!.GetType() if we are
  void IInitializable.Initialize(object! o) {
    // assignment to null is also permited
    _state = "initialized";

    var tp = new ThirdParty();

    // defined as void Run(Action<string> action) pre non-nullable references
    // so that string is a nullable reference
    tp.Run((string! arg) => {
      // we know that arg wouldn't be null at this point
    });

    // or 
    tp.Run((arg!) => { ... });
  
    if(o is C { P: var! p }) {
      // p is definitely not null 
    }
  }
}
```
Although, usage should be discouraged outside of these use cases.

**Comment by stepanbenes** [comment]
@alzr Aren't todays reference types already implicitly unwrapped nullables?

**Comment by HaloFour** [comment]
Too lazy to look up the references at the moment but I recall the team had already debated the merits of having three types like Swift and decided to not go that route.  Rather they were exploring an `!` operator which would forcibly dereference a nullable type in place:

```cs
string? name = person?.Name;
int length = name!.Length;  // no warning but will throw a NullReferenceException if name is null
```

**Comment by alrz** [comment]
@stepanbenes This proposal is an extension to non-nullable reference types (#5032) so there will be some difference. And there ain't no "unwrapping" is happening because there is no wrapper type. They're just regular reference types with semantic analysis for null checks. `T!` type is a nullable type that doesn't need to be proven to be not null at the compile-time. because it is already proven externally, or by other means. 

@HaloFour Sure. But if the type was defined as `string!` you don't need to use `!.` operator in **every** member access. It is just a convenient way to indicate that we know a specific variable wouldn't be null at any given part of the code that we're going to use it. For example, in the code above `string? field` doesn't really show that `null` is not a valid value; rather, we are just not able to initialize it in the constructor.

**Comment by HaloFour** [comment]
@alrz 

Indeed, but you'd then need a way to convert from one to the other.  Rather than defining it as a special type, just use the operator to convert.  It also provides nice symmetry with the null-propagation operator:

```cs
string? s = ...;
int? length1 = s?.Length;
int length2 = s!.Length;
int length3 = s?.Length!;
```

Here are the design notes where the Swift three-type approach was considered:  #3910

> We think that the "three-type" approach is not very helpful, leads to massively rewritten over-adorned code, and is essentially not viable.

**Comment by alrz** [comment]
@HaloFour The proposal is not against `!.` operator as I mentioned it above the `Initialize` method.

Swift which was designed with nullable types from the very beginning had to introduce `T!` to be able to [deal with the exact same scenarios](http://krakendev.io/blog/when-to-use-implicitly-unwrapped-optionals). I think all of them are applicable to C# as well. You can live without it but it wouldn't be elegant and expressive.

**Comment by HaloFour** [comment]
@alrz

C# wasn't, which is why it can't take the same approach as Swift.  Swift wanted to pretend to discard all legacy but had to interop with Cocoa which had no concept of non-nullable types.  Having strictly non-nullable types worked very poorly with Cocoa.  If it weren't for that the implicitly unwrapped type suffix would be largely unnecessary.  With Cocoa now more appropriately annotated its now considered bad practice to rely on them for almost every scenario.

If C# were to go with the three-type approach, for maximum compatibility it would make more sense for the default notation to be the implicitly unwrapped type and add `!` as a prefix for non-nullable types.  That would avoid the mess of new warnings in existing code.  But that would also require the tons of adornment and probably stymy adoption.  The two-type approach better forces the issue and maintains consistency.

If C# were to be reinvented tomorrow with rigidly non-nullable reference types like Swift and the existing .NET framework I might be more inclined to agree.  But I still think that the dereference operator fills that need just as well.

**Comment by stepanbenes** [comment]
Two-type approach is clearly superior to three-type approach. @alzr I must say that I admire your passion about language design. You love C# at least as I do, but sometimes I think you make proposals only to make proposals. Do you really want to write exclamations all over you code?

**Comment by alrz** [comment]
@stepanbenes I wasn't aware of the aforementioned design notes and I am already convinced with @HaloFour's last comment. I don't think discussing ideas would hurt anybody though.

**Comment by alrz** [comment]
Closing per #3910.

**Comment by alrz** [comment]
> In the "three-type" approach, both "meant to be null" and "not meant to be null" are expressed as new type annotations (T? and T! respectively) and the existing syntax (T) takes on a legacy "unsafe" status.

@HaloFour I should note that there is a subtle difference between this proposal and the one that was discussed in #3910. In my examples `T!` takes the legacy unsafe status (explicitly)  and `T` remains as the non-nullable type as currently planned. However, it's still a three-type approach.
