### ISSUE TITLE
Assignment after incomplete invocation expression breaks new preselection

### ISSUE THREAD

**Issue by SLaks** [dotnet/roslyn#1372]
```C#
class A {
	object e;
	A() {
		int.Parse(new 
		e = AppDomain.CurrentDomain;
	}
}
```

Pressing Space after `new` will preselect `AppDomain` instead of `string`.

This is quite annoying when inserting generic types above existing code.

**Comment by Pilchie** [comment]
This is the same issue as https://connect.microsoft.com/VisualStudio/feedback/details/1046005/connect-intellisense-provides-incorrect-auto-completion-suggestion-when-using-object-initializers, and a couple of other internal reports we've had.  We'll use that bug to track it for now.

**Comment by SLaks** [comment]
I don't have access to that either :)

**Comment by SLaks** [comment]
BTW, if you press Ctrl+Space at the end of the following code, the field name shows as an error type.
I filed a similar bug on Connect a long time ago; should I file this separately?

```C#
		int.Parse(new
		e = new 
```

**Comment by Pilchie** [comment]
It's weird that you don't have access - it's listed as a public connect bug filed against VS2015 Preview.  Maybe you have to register in the Visual Studio section of connect to be able to see it?

For the error type issue, if you are thinking of the one with the title "IntelliSense shows fake error type" that you filed on an insider Preview, we're still tracking it, but I'd be happy to have it here instead of in an private connect database :wink:

**Comment by SLaks** [comment]
I cleared my cookies, and I now have access.
