### ISSUE TITLE
[Proposal] Family AND Assembly access modifier (aka infamous "private protected")

### ISSUE THREAD

**Issue by dsaf** [dotnet/roslyn#1384]
https://roslyn.codeplex.com/discussions/541194

It seems that there is no satisfactory conclusion.

IMHO C# is the primary language for the platform. If something is supported by CLR, then it absolutely has to be supported by C#.

PS: maybe there should be a separate label for things like this (e.g. enum generic constraint, generic custom attributes etc.).

**Comment by SolalPirelli** [comment]
>  If something is supported by CLR, then it absolutely has to be supported by C#.

That doesn't seem to be C#'s goal. There are quite a lot of features in the CLR not found in C#, e.g. `try...fault`, method overloads that differ only by the return value, static interface constructors, static indexed properties, tail calls...

**Comment by agocke** [comment]
@dsaf This is 100% not a goal of C#. The CLR is the common language runtime, not the C# language runtime. C# happens to run on the CLR, but is in no way the canonical CLR targeting language.

That said, I'm not opposed to the general idea of the modifier. :)

**Comment by alanfo** [comment]
In the CodePlex discussion nearly everybody agreed that `Family AND Assembly` access would be a useful feature. 

Indeed, Mads said as much and presumably the feature wouldn't have been proposed in the first place if the C# team didn't believe this to be the case.

The only point of disagreement was what to call it given that `protected internal` is already used for `Family OR Assembly` access.

I'd imagine that the original proposal to use `private protected` came about because this is what C++/CLI uses and it wouldn't have required any new keywords.

Anyway, I agree with @dsaf that this proposal should be resurrected and I'd also like to propose that there should be no further discussion on the name. The C# team should exercise a little muscle here and simply choose what in their view is the best name.  

If the rest of us don't like it, then that's just tough - at least we'll have the feature :)

**Comment by dsaf** [comment]
I agree with everything said :).

**Comment by MgSam** [comment]
Agree with @alanfo. It was silly for this useful feature to be dropped because of minor disagreements about the name. Just vote internally on the name and go with that.

**Comment by badja** [comment]
I was also disappointed that this useful feature was dropped and believe the originally proposed name of `private protected` would have been fine.

The C++/CLI designers got it right when naming the access modifiers for that language. If anyone has any doubts about the proposed name they should read the C++/CLI [Member visibility](https://msdn.microsoft.com/en-us/library/ke3a209d.aspx#BKMK_Member_visibility) documentation. The rationale behind the naming makes perfect sense:

> You can make access to a member of a class from within the same assembly different than access to it from outside the assembly by using pairs of the access specifiers `public`, `protected`, and `private`.

But I don't want to ignite another debate on the name, so I'll end by just urging the C# team to stick to their guns and implement the feature as they originally proposed.

**Comment by whoisj** [comment]
> The C++/CLI designers got it right when naming the access modifiers for that language.

:+1:

**Comment by gafter** [comment]
This feature is cut from C# 7.

**Comment by MgSam** [comment]
What a troubled life this feature has had.

**Comment by dotnetchris** [comment]
Hopefully this is the end.

**Comment by gafter** [comment]
Moved to https://github.com/dotnet/csharplang/issues/37

When the feature is assigned a release, I'll open an issue here to integrate the implementation.
