### ISSUE TITLE
Roslyn could not find references for some projects

### ISSUE THREAD

**Issue by isanych** [dotnet/roslyn#13859]
Versions tested 1.3.2, 2.0.0-beta3, master.

When loading solution from https://github.com/flagbug/Espera some projects don't have references (we also have internal project with the same issue).

``` c#
var workspace = MSBuildWorkspace.Create();
var solution = workspace.OpenSolutionAsync(@"C:\w\Espera\Espera.sln").Result;
var projects = solution.Projects.ToArray();
foreach (var project in solution.Projects)
{
    Console.WriteLine($"{project.Name} has {project.MetadataReferences.Count} references");
}
```

Output:

```
Espera.Core has 0 references
Espera.View has 0 references
Espera.Core.Tests has 74 references
Espera.View.Tests has 84 references
```

Solution building fine in visual studio 2015 (I'm building solution in VS before running test, so all nuget dependencies are downloaded too).
So far I've tracked difference between projects with and without references to this point:

``` c#
public override async Task<ProjectFileInfo> GetProjectFileInfoAsync(CancellationToken cancellationToken)
{
    var compilerInputs = new CSharpCompilerInputs(this);

    var executedProject = await this.BuildAsync("Csc", compilerInputs, cancellationToken).ConfigureAwait(false);

    if (!compilerInputs.Initialized)
    {
        // if msbuild didn't reach the CSC task for some reason, attempt to initialize using the variables that were defined so far.
        this.InitializeFromModel(compilerInputs, executedProject);
    }

    return CreateProjectFileInfo(compilerInputs, executedProject);
}
```

If compilerInputs.Initialized is false, there are no references in project.

SO question - http://stackoverflow.com/questions/39530923/roslyn-could-not-find-references-for-some-projects

**Comment by Pilchie** [comment]
`MSBuildWorkspace` basically does a "Design Time Build" in order to find out the command line arguments.  In the case where `!compilerInputs.Initialized` it means the design time build failed before it got to the `CoreCompile` target.  

This page https://github.com/dotnet/roslyn-project-system/blob/master/docs/design-time-builds.md details some more information about design time builds and how to diagnose failures.

**Comment by isanych** [comment]
Somehow I'm not getting design time log for both solution - will continue in Monday. Are there any setting/workarounds in roslyn for such cases? As I'm opening project/solutions which I don't control and would not be able to change them anyway - and these solutions are building fine in Visual Strudio.

**Comment by Pilchie** [comment]
Unfortunately, without knowing *why* the build is failing, I can't suggest a workaround :(

**Comment by Pilchie** [comment]
Note - you'll have to do something different than the env var to get `MSBuildWorkspace` to generate design-time logs.  I believe @mattwar  did it recently though and might be able to help with how.

**Comment by mattwar** [comment]
I've experimented with capturing the msbuild log errors and presenting them as workspace diagnostics.

When this failure happens it is typically due to missing msbuild API redirects that the app using the msbuild workspace needs to have.  

Also until recently (last week), msbuild workspace would not work correctly on a machine without dev14. So if you only have dev15, you'd likely get this type of failure.

**Comment by CyrusNajmabadi** [comment]
NOt seeing this problem when i try things out myself.  My guess is there was some MSBuild diagnostic happening back then.  Would need a more up to date report on this.
