### ISSUE TITLE
The specification says ternary operator shouldn't compile when both alternatives have the same type

### ISSUE THREAD

**Issue by svick** [dotnet/roslyn#13881]
[The C# specification says this about the type of the ternary/conditional operator](https://github.com/ljw1004/csharpspec/blob/gh-pages/expressions.md#conditional-operator):

> The second and third operands, `x` and `y`, of the `?:` operator control the type of the conditional expression.
> -  If `x` has type `X` and `y` has type `Y` then
>   - If an implicit conversion ([Implicit conversions](https://github.com/ljw1004/csharpspec/blob/gh-pages/conversions.md#implicit-conversions)) exists from `X` to `Y`, but not from `Y` to `X`, then `Y` is the type of the conditional expression.
>   - If an implicit conversion ([Implicit conversions](https://github.com/ljw1004/csharpspec/blob/gh-pages/conversions.md#implicit-conversions)) exists from `Y` to `X`, but not from `X` to `Y`, then `X` is the type of the conditional expression.
>   - Otherwise, no expression type can be determined, and a compile-time error occurs.
> -  If only one of `x` and `y` has a type, and both `x` and `y`, of are implicitly convertible to that type, then that is the type of the conditional expression.
> -  Otherwise, no expression type can be determined, and a compile-time error occurs.

As far as I can tell, according to this, if `x` and `y` have the same type, it should be a compile-time error, because:
- `x` and `y` both have a type
- an implicit conversion (specifically, [identity conversion](https://github.com/ljw1004/csharpspec/blob/gh-pages/conversions.md#identity-conversion)) exists from `X` to `Y` and from `Y` to `X`

Since obviously code like that should (and does) compile, I think the specification should be fixed.

**Comment by svick** [comment]
Also, I think this would imply that a conditional expression when one of the alternatives is `dynamic` shouldn't compile, because:

* there is an implicit conversion ([implicit dynamic conversion](https://github.com/ljw1004/csharpspec/blob/gh-pages/conversions.md#implicit-dynamic-conversions)) from `dynamic` to any type
* there is an implicit conversion (either [implicit reference conversions](https://github.com/ljw1004/csharpspec/blob/gh-pages/conversions.md#implicit-reference-conversions) or [boxing conversion](https://github.com/ljw1004/csharpspec/blob/gh-pages/conversions.md#boxing-conversions)) from almost any type to `dynamic`

**Comment by gafter** [comment]
The future ECMA spec that will be the basis of the C# 6, and 7 specs is a bit better here:

> The second and third operands, x and y, of the ?: operator control the type of the conditional expression.
- If x has type X and y has type Y then,
  - If X and Y are the same type, then this is the type of the conditional expression.
  - Otherwise, if an implicit conversion (§12.2) exists from X to Y, but not from Y to X, then Y is the type of the conditional expression.
  - Otherwise, if an implicit conversion (§12.2) exists from Y to X, but not from X to Y, then X is the type of the conditional expression.
  - Otherwise, no expression type can be determined, and a compile-time error occurs.
- If only one of x and y has a type, and both x and y are implicitly convertible to that type, then that is the type of the conditional expression.
- Otherwise, no expression type can be determined, and a compile-time error occurs.

**Comment by svick** [comment]
This issue was moved to dotnet/csharplang#358
