### ISSUE TITLE
VS Intellisense for csx files does not support #load

### ISSUE THREAD

**Issue by adamralph** [dotnet/roslyn#13888]
**Version Used**: 

Visual Studio Enterprise 2015 Update 3.

**Steps to Reproduce**:
1. Create a csx file `foo.csx` containing the definition of a class named `Foo`.
2. Create another csx file.
3. Add a line `#load "foo.csx"`
4. On the next line type `Foo.`.

**Expected Behavior**:

Intellisense is shown for `Foo`.

**Actual Behavior**:

Intellisense is not shown for `Foo`.

**Comment by adamralph** [comment]
:tada:

**Comment by adamralph** [comment]
https://twitter.com/adamralph/status/837573323223609346

**Comment by forki** [comment]
One question about syntax coloring. In visualfsharp we noticed that a change in the string literal of a #r and #load triggers reparsing of the script in the ide and intellisense works as expected, but syntax recoloing is not triggered. @vasily-kirichenko and myself believe that a change in a string literal is maybe handled differently by roslyn. Probably in order to be faster in coloring.

**Comment by forki** [comment]
Here is a video of what I described:

![colors](https://cloud.githubusercontent.com/assets/57396/23543063/b18efbcc-fff0-11e6-9910-cee1c3052438.gif)

**Comment by tmat** [comment]
@KevinRansom

**Comment by forki** [comment]
@tmat we believe this is a roslyn issue. VisualF# doesn't do much intersting stuff here. Will try to reproduce in C#.

**Comment by vasily-kirichenko** [comment]
@forki it's our problem.

**Comment by forki** [comment]
ok. then forget what I wrote ;-)

**Comment by vasily-kirichenko** [comment]
@forki see https://github.com/Microsoft/visualfsharp/issues/2520

**Comment by forki** [comment]
Ok @vasily-kirichenko fixed it. Sorry for the noise
