### ISSUE TITLE
C# Support for First Class Delegation

### ISSUE THREAD

**Issue by bordoley** [dotnet/roslyn#139]
The delegation pattern is a very common alternative to inheritance for sharing a common implementation of an interface. However in C# utilizing delegation is very heavy weight requiring lots of boiler point code which could easily be generated by the compiler. The [Kotlin](http://kotlinlang.org/docs/reference/delegation.html) language includes such a feature which greatly reduces the effort and cost of utilizing the pattern. It would be great if C# 7 included such a feature as well.

**Comment by lyubomyr-shaydariv** [comment]
As far as I understand, this request is very similar to mine, #124 . I really would like to have this feature too.

**Comment by zekethegeke** [comment]
yes!

**Comment by thomaslevesque** [comment]
Yes, this would be very useful. However I think it's not as straightforwards as it seems. For instance, how would you handle events? Because if the generated code does this:
```
public event EventHandler MyEvent
{
    add { decoratee.MyEvent += value; }
    remove { decoratee.MyEvent -= value; }
}
```
Then the subscribers will receive `decoratee` as the sender, which is probably not what we want. Instead the correct way to implement it would be this:

```
// in ctor
decoratee.MyEvent += decoratee_MyEvent;

public event EventHandler MyEvent;

private void decoratee_MyEvent(object sender, EventArgs e)
{
    MyEvent?.Invoke(this, e);
}
```
This means the compiler has to understand the semantic of the `sender` parameter in `EventHandler`; but it's not a language concept, just a convention in the framework. Should the compiler know about this? I don't think so...

**Comment by gafter** [comment]
Treating as a dup of #124.
