### ISSUE TITLE
Stale tags are stuck in the editor

### ISSUE THREAD

**Issue by vladima** [dotnet/roslyn#13917]
![stale_squigglies](https://cloud.githubusercontent.com/assets/8052307/18651513/92152bc8-7e80-11e6-87cf-3d39c0ba20f7.png)

In TypeScript we derive our diagnostics analyzer from `DocumentDiagnosticAnalyzer` and override `SupportedDiagnostics`, `AnalyzeSyntaxAsync` and `AnalyzeSemanticsAsync`. Sometimes squigglies in the editor are not cleaned up and still sit there. Error list reflects the right state of  things, also I've placed the breakpoint in `AnalyzeSyntaxAsync` and verified that amount of errors that we return is correct (i.e. it is 0 for the screenshot above)

**Comment by CyrusNajmabadi** [comment]
@heejaechang @mavasani Hey guys, TypeScript is seeing the issue where diagnostics aren't getting cleared.  I know you've been looking at this area and have fixed some stuff.  Is it possible the fixes aren't being applied to Document-Diagnostics?

**Comment by heejaechang** [comment]
the one we fixed is in preview.. @vladima do you want to sit down together and debug through?

**Comment by heejaechang** [comment]
the fact that error list show right info seems bug is somewhere in the tagger.

**Comment by CyrusNajmabadi** [comment]
I imagine it is in the tagger.  As mentioned the last time we looked at the tagger, there is no clear API to get diagnostics and it's quite likely that the features that get diagnostics for the buffer are likely wrong.  The IDE *really* needs an API we can talk to that properly gets us the dianogstics and handles things like responding to all the right Workspace events and whatnot.

Right now this cannot be done because it requires the consumign features to know the implementation details of the diagnostics API.  With the complexity of the diagnostics subsystem, this simply isn't feasible (unless it is done by someone who has written that system).  This ties into several bugs/issues filed on this (from several releases ago) that we need simpler APIs here so we can avoid these classes of bugs entirely.  

Thanks!

**Comment by heejaechang** [comment]
@vladima anyway, let me know if you want to debug things together.

**Comment by Pilchie** [comment]
@kuhlenh and I have both seen this as well in C#.  Who are the right people to investigate further?

**Comment by vladima** [comment]
@heejaechang  the repro is quite unstable, I'll ping you if I'll see it once again. 
// cc @minestarks who've seen it as well.

**Comment by CyrusNajmabadi** [comment]
@heejaechang @mavasani  Could this be caused by https://github.com/dotnet/roslyn/commit/8cc31fe512a47b055b34767e237837f4d832ea8d ?

That's the only change we've gotten to diagnostic tagging.  And it specifically changes things so that we do *not* remove some diagnostics in some situations.  

Is it possible we have a race with something like the following:

1. Diagnostics are reported in some document.
2. Buffer changes to another document.
3. Diagnostics are removed from the original document.
4. Tagger doesn't remove the tags because your change makes it so we ignore the 'removal' event because it's not against the current document?

If this is the issue then, as mentioned before, IDE would really like an API from diagnostics that appropriately encapsulates all these complexities.  Right now we hear about diagnostics, but tehn have to do a lot of checks that involve knowing the internal details of the diagnostics engine and having to know what invariants and external stimuli it responds to.  This is very brittle and difficult to get right.  

Currently I do not know all those internal details of the diagnostics infrastructure, and attempting to reverse engineer it has proven to not provide an adequate, bug-free experience for users.

**Comment by heejaechang** [comment]
This is not the job of “Buffer changes to another document” diagnostic service. Since It work on top of documentId not buffer. Tagger is the one that work on top of buffer. If that is the issue, the tagger should clear its state since documentId it is associated with is changed. For diagnostic service, nothing has changed.

-          heejae

**Comment by CyrusNajmabadi** [comment]
We were clearing the state :)

You changed it to stop doing that.

**Comment by heejaechang** [comment]
Ah, I see. That sounds like a bug then. It should clear all state regardless if buffer has changed.


-          heejae

**Comment by zhengbli** [comment]
I actually can still repro this issue on today's preview build (clean install). I have a stable repro steps:

> 1. Create a new loose TypeScript file, do not save it yet.
> 2. Type the following code:
> type t: "Test";
> var s: t;
> And wait until the red lines show up indicating there are errors in the first line
> 3. Save the file now on the disk.
> 4. Fix the error, so the code looks like
> type t = "Test";
> var s: t;
> 5. See the error in the Error List goes away, but the red lines are still there.
> 6. Save the file now, see the Error List shows a wierd error message:
>     "The file {0} doesn't exist"

**Comment by CyrusNajmabadi** [comment]
The fix didn't go into Preview, it went into master.

**Comment by zhengbli** [comment]
Oh ok, never mind then.
