### ISSUE TITLE
An Assert in VB.Symbols.EmbeddedSymbolManager.MarkSymbolAsReferenced

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#13925]
see https://github.com/dotnet/roslyn/issues/13884#issuecomment-248174097

This is the preview 5 Roslyn solution running, opened the preview 5 Roslyn solution with full solution analysis enabled and switched to Release mode.

**Comment by gafter** [comment]
@jaredpar FYI

**Comment by AlekseyTs** [comment]
This isn't a real crash, this is just an assert, VS continues running after it is ignored. However, it looks like Declaration Table is missing all embedded syntax trees and, therefore, all embedded types (VBCore, XML helpers, etc) are not available even though the compilation expects them to be available. Basically different parts of the compilation are in inconsistent state.

**Comment by AlekseyTs** [comment]
I wasn't able to crash compiler due to this issue, though I am not claiming that there is no chance of that in some rare scenario. However, compiler is likely to report unexpected errors due to the fact that, for example, VBCore APIs are not really available. Another negative effect could be that, if there is also an explicit reference to Micrososft.VisualBasic.Dll, the /vbruntime* switch will be essentially ignored and the compiler will silently compile against that runtime.

**Comment by AlekseyTs** [comment]
Moved to RC by triage.
