### ISSUE TITLE
Allow struct constructors to have no formal parameters.

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#13921]
Also support field initializers in struct declarations.

This issue tracks reinstating the aborted C# 6 feature reverted per
- https://github.com/dotnet/roslyn/issues/1029
  which was aborted because of CLR bug
- https://github.com/dotnet/coreclr/issues/6843

Design notes are primarily here:
- http://roslyn.codeplex.com/discussions/562559
- http://roslyn.codeplex.com/discussions/562558

**Comment by ig-sinicyn** [comment]
Err, as for me this will be __very__ bad design decision. There're too much unexpected gotchas for  "we're making it easier" feature. 

Let's forget about `Activator.CreateInstance<T>()`. What about a case when someone passes
 `(new StructWithDefaultCtor[1])[0]` 
into a method that expects its args to be initialized properly? Errors like this cannot be spotted easily. For ref types there is NullReferenceException. For value types there's nothing.

**Comment by gafter** [comment]
@ig-sinicyn That problem already exists, bor both reference and value types. What about a case when someone passes `(new string[1])[0]` into a method that expects its args to be initialized properly? The caller failed to perform the initialization, with or without this feature.

**Comment by ig-sinicyn** [comment]
@gafter , agreed.

"Empty" instances for reference types can be detected with a simple check for null and non-nul references in c#8 will fix the issue completely.

Empty instances for value types never were a problem too as there were no CLS-compatible way to declare struct with parameterless ctor. Therefore the case "all fields set to default" was legal by design.


Now, the introduction of .ctor() for structs gives an illusion that all fields can be safely set to non-default values and the rest of the struct code can omit checks for `(field != null)` etc.

Obviously the illusion is false and the code written with the illusion in mind will fail. The worst part is, this error is much harder to spot than passing a null reference and therefore it going to be a billion dollar mistake v2.

**Comment by tenor** [comment]
I see @ig-sinicyn's point. 
Today, a reference type can either be null or properly constructed. (Not always true but that's the expectation). A struct can exist without being constructed or initialized by constructors with parameters.
With this change, a struct can exist as 1) initialized but not constructed, 2) initialized by a parameterless constructor 3) initialized by constructors with parameters.

I'll say that many devs will be surprised that their struct was initialized but not constructed if the struct has a parameterless constructor.

**Comment by alrz** [comment]
What are the actual use cases (other than being confusing and possibly breaking existing code by introducing new semantical differences between `default` and `new` for structs)? Personally, I haven't ever missed this compared to gazillion other ideas proposed for C#. Supposedly, this is just me.

**Comment by VSadov** [comment]
Example:

The following should crash. Code clearly contains a bug and accesses unitialized data.

```cs
var arrays = new ImmutableArray<int>[1];
var x = arrays[0].Length;         // length of an uninitialized array
```

But should the following crash?

```cs
var arrays = new ImmutableArray<int>[1];
arrays[0] = new ImmutableArray<int>();
var x = arrays[0].Length;         // length of an _initialized_ array ?
```

Empty array and uninitialized array are conceptually different things.
It would be logical for ```new ImmutableArray<int>()``` to result in an empty array which has Length 0, distinct from ```default(new ImmutableArray<int>)``` which does not have Length at all. 

The datatype has a trivial state distinct from unconstructed one. You'd expect the trivial constructor to  construct such state. That is not possible because ImmutableArray is a struct.

Not the end of the world, but not the most convenient situation either.

**Comment by JuanOnGit** [comment]
This may depend on "requirements", though does it not make sense to initialize the values within the constructor based on the usage of an empty or needed values. By my understanding, a constructor is used for the purpose to help initialize an object to avoid inconsistencies, I think this bolds true for a struct constructor. With the exclusion of :base, the demonstrates a need for parameters for a constructor(struct constructor).

**Comment by tenor** [comment]
> though does it not make sense to initialize the values within the constructor based on the usage of an empty or needed values.

It sort of makes sense from a consistency perspective but not practically. The performance hit involved with initializing a large array of structs, which is a common use case, will be awful.

**Comment by gafter** [comment]
> though does it not make sense to initialize the values within the constructor based on the usage of an empty or needed values.

Why not? It makes sense for structs just as much as it makes sense for classes. @VSadov gave one particular example.

> It sort of makes sense from a consistency perspective but not practically. The performance hit involved with initializing a large array of structs, which is a common use case, will be awful.

I don't think you understand the feature. This would have no effect on array creation.

Once we allow `new Struct()`, then adding a constructor to `Struct` would cause the two expressions `new Struct()` and `default(Struct)` to have different behavior - the former calling the constructor, and the latter returning an instance that has been cleared. Actually, the compiler and runtime mostly already respect the difference between these two forms if a `struct` in metadata has a default (no-args) constructor. It is just that the compiler prevents you from declaring it in source.

**Comment by tenor** [comment]
@gafter, I (mis)understood @JuanOnGit's question as: shouldn't the constructor always be called, even in the case of `default(Struct)`?

**Comment by gafter** [comment]
@tenor No. The constructor should only be invoked if the constructor is invoked in source, just the same as for classes.

**Comment by ig-sinicyn** [comment]
@VSadov 
>The following should crash. Code clearly contains a bug and accesses unitialized data.

The following obviously should not crash. There never were a concept of uninitialized struct and majority of developers will expect default(TStruct) to behave as empty one. 
```
var x = arrays[0].Length;         // 0, length of an _empty_ array
```

That's exactly the reason I dislike the feature: it provocate you to write unfriendly code.
Take a customer side: let's assume you have a method
```
public void DoSomething(ImmutableArray<int> values)
{
  foreach (var item in values) ...
}
```

Now, you have to proof that values are initialized. This means you have to reinvent all the tricks that are used to prevent null references but without runtime / compiler support. 
You cannot just write `DoSomething(ImmutableArray<int>! values)`. Instead, you have to add a custom property `IsInitialized` and check it's value in every method that uses `ImmutableArray<>`. 
You have to add a naming convention for such properties or may be add an interface for that.
You have to add a analyzer rule to prevent using such structures as nullables (seriously, you have handmade null reference already, why do you wish to pass nullable and not initialized value anywhere?).
Heck, the ones who will be happy with that are only VB guys with theirs Nothing/Empty/Null triplet.

I won't call it good design. Really.

Please, DO read FDG,. At least the _2.2 Fundamental Principles of Framework Design_ section. 
New features should induce good code, not bad one:)

**Comment by CyrusNajmabadi** [comment]
> Once we allow new Struct(), then adding a constructor to Struct would cause the two expressions new Struct() and default(Struct) 

I'm finding that this very much worries me.  It's been really nice that, since the beginning, i knew that structs in c# behaved a certain way.  And it was nice that there was absolutely no difference between these two forms.  

Introducing a difference makes the language adopt a very subtle distinction that never occurred before.  

Perhaps if this had been supported since very early on in C# i would feel differently.  However, now this seems like a super subtle thing to add (for honestly very minor gain).

**Comment by CyrusNajmabadi** [comment]
> The following should crash. Code clearly contains a bug and accesses unitialized data.

```
var arrays = new ImmutableArray<int>[1];
var x = arrays[0].Length;         // length of an uninitialized array
But should the following crash?
```

I disagree with your statement that the following should crash.  If i create an array of ints, i don't think of it as being 'uninitialized'.  I can use that array of ints just fine.  Indeed, we could have made it so that ImmutableArray supported that concept.  i.e. '.Length' could have returned 0 in the case where the underlying array wasn't even there.  That would have been a perfectly fine design that makes ImmutableArray truly a value-type (like 'int').  In this world there would be no sentinel "non-initialized" ImmutableArray.  If you wanted such a thing, you'd have to do something like use an "ImmutableArray<T>?", using 'null' to actually indicate uninitialized (just like with classes).

--

Also, even if we did add this language feature, we still wouldn't be able to actually update something like ImmutableArray.  If we did, that would be a breaking change as someone who had the following code would observe different behavior:

```
var array = new ImmutableArray<int>();
...
if (array.IsDefault) { ... }
```

As such, ImmutableArray will keep its current behavior (as will any actual .net types that behave like this).  As such, this benefit will only come to new types, which will then have the distinction of having this subtle difference compared to *practically* every other struct in the .Net universe.  (I say 'practically', because i know this can come about through metadata.  But, really, it's not something that people are really doing).  

I'm highly opposed to having such a subtlety added for hypothetical structs that we may write in the future.

**Comment by VSadov** [comment]
ImmutableArray<int> is nothing like int. 
It has a distinct default state which is commonly used in scenarios like atomic lazy initialization. Nullables cannot be atomically updated without locking. 

We are not discussing the design of ImmutableArray here though. 
I am just giving an example of a very common struct that could have meaningful constructor that takes no additional data. 
Someone was asking for an example.

(But it does sound like your default reaction would be to sacrifice the design to accommodate deficiencies of the language)



Structs that need initialization to be in a valid state do come up once in a while and require unnatural workarounds. A static singleton/factory named something like  "Empty" or "Instance" is a good indication it is one of such structs.
Most common case is turning an existing class into a struct and discovering that it has a parameterless constructor. ImmutableArray started as a ```class ReadOnlyArray``` BTW.

Currently, users have to resort to adding a constructor with an unused dummy argument and tell everybody to use that constructor and carefully audit and change all the creation points.
The common mistake is to make the dummy argument optional. That does not help and is actually very dangerous since ```new S()``` would prefer the default constructor over the constructor that has an optional parameter. We had bug reports suggesting that this should not be happening - at least not silently, but that is how overload resolution works.

Another way is to use a static factory/singleton. That still requires auditing all the usage.

Either approach is not composable with generic code. - you can't tell "newT()" to use the factory. 
Although there were suggestions to add an attribute on a factory - "this is actually my New". I am not sure that was serious, just brainstorming on a solution, perhaps..

Another way is to implement parameterless ctor via IL rewrite or just implement it in IL and put in a separate dll. That is rarely attempted due to obvious complexity.

Parameterless constructors on structs is just as supported as on classes.

Why do we tell users to jump through the hoops when they are in need to declare one?

>> it's not something that people are really doing  

Because we are not letting them. 
Hardly a reason to continue the practice.

**Comment by CyrusNajmabadi** [comment]
> Currently, users have to resort to adding a constructor with an unused dummy argument and tell everybody to use that constructor and carefully audit and change all the creation points.

With structs you *always* have to do this.  Even if you make it so that parameterless constructors do what you want, you still have the problem that any array of these structs still needs to be manually initialized.  

There is no way to avoid the auditing problem.  And, indeed, IMO, the auditing problem becomes *harder* because things will "work" in some cases, but not work in others.  Contrasted with today where it *never* works.

> But it does sound like your default reaction would be to sacrifice the design to accommodate deficiencies of the language

Yes.  Because, then, at least i know about this deficiency and i'm always alert for it.  THe more subtle the deficiencies become, the easier they are to miss.  

If we could solve this problem entirely, i'd be happy.  But this seems like a half-measure which ends up making things worse.

--

And, as mentioned again, it's not clear to me that htere's value in addressing this given that all the code that has already shipped around this cannot change.  We're then going to have two classes of struct based APIs.  Those before this feature, which have all that behavior people need to know about, and those after this feature.  This is *another* layer of subtlety that i think actually makes .net and structs more confusing.

**Comment by CyrusNajmabadi** [comment]
> ImmutableArray is nothing like int. 

To you :)

To me, i would have been totally fine with them being nearly identical.  A value-typle that always was in a valid state.  That might have made other patterns more difficult (i.e. you might have had to lock when trying to do atomic things), but that doesn't bother me.  I have to lock when i use nullables, and that's acceptable.  I still view nullables like i do other value types.

**Comment by CyrusNajmabadi** [comment]
Also, finally, even if i did want ImmutableArray to have a default 'uninitialized' state, it's not at all clear ot me that i wasn "new ImmutableArray()" to *not* put the object in hte uninitialized state.  To me, it's the nature of structs.  If i 'new' it up with no args, it's in the uninitialized state.  That's how all other structs work, so it makes sense to me that that's how ImmutableArray would work.  I would find it strange that ImmutableArray would behave *differently* here

**Comment by lorcanmooney** [comment]
I couldn't agree more with @CyrusNajmabadi and @ig-sinicyn. Value-types should be designed so that they're in a valid, usable state, regardless of how they are created. It's [hard enough to get that right today](https://github.com/dotnet/roslyn/blob/77191f8cf3b47b16c77ff7d74897a28b994c7a1a/src/EditorFeatures/Test/Completion/AbstractCompletionProviderTests.cs#L111). Introducing yet another mechanism isn't going to make things better.

This philosophy was even [echoed by the BCL team](https://blogs.msdn.microsoft.com/dotnet/2013/09/12/immutable-collections-are-now-rc/) when `ImmutableArray` was introduced:

> In order to provide meaningful semantics, we believe it’s best for an immutable array in its default state to behave exactly like an empty array. That’s consistent with the way the .NET Framework [deals with value types in general](http://msdn.microsoft.com/en-us/library/ms229031.aspx).

And, speaking of `ImmutableArray`, it seems the current, suboptimal design is actually a product of Roslyn perf requirements. From the same blog:

> ...an additional null check to provide the behavior I explained. This causes the JIT to no longer be able to eliminate the bounds checks. Our partner Roslyn uses ImmutableArray<T> throughout its system, so this caused an unacceptable performance loss.

**Comment by ig-sinicyn** [comment]
@lorcanmooney  +1

And [here's](https://github.com/cwensley/Portable.Xaml/issues/22) [how](https://github.com/dotnet/roslyn/issues/7236) it shoots you into your leg. 

I do not want errors like this spread through my codebase.

**Comment by gafter** [comment]
@ig-sinicyn Can you please explain how those two issues have anything to do with this?

**Comment by ig-sinicyn** [comment]
@gafter 
Oups. looks like I posted wrong link for xaml-related issue, could not find the correct one so let's forget about it.

About VB issue - we've troubleshooted something like this some time ago.
The root reason was the [ThrowNullRefIfNotInitialized()](https://github.com/dotnet/corefx/blob/6a718ebd25ffedcaf3dadff1f4cc6d3c2f387edb/src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableArray_1.cs#L1629) method that is
called from most ImmutableArray methods [or even extensions](https://github.com/dotnet/corefx/blob/bffef76f6af208e2042a2f27bc081ee908bb390b/src/System.Collections.Immutable/src/System/Linq/ImmutableArrayExtensions.cs#L32).

Here's assertion [added](https://github.com/dotnet/roslyn/blob/614299ff83da9959fa07131c6d0ffbc58873b6ae/src/Compilers/VisualBasic/Portable/Symbols/Source/SourceFile.vb#L67-L68) into fixed code. Yep, there's no easy way to prevent yourself from passing uninitialized value and client code quickly becomes poisoned with `!x.IsDefault` checks.

**Comment by gafter** [comment]
@ig-sinicyn This would not likely have any impact on the declaration or use of the `ImmutableArray` APIs.

**Comment by ig-sinicyn** [comment]
@gafter, yes. 

At the same time ImmutableArray is a good example of design problem I'm talking about. Any struct with custom default .ctor will have the same issue: the code will fail if uninitialised instance passed and there's no easy way to prevent it at compile-time. For null referenves there's #5032, for uninitialized structs there's nothing.

**Comment by DavidArno** [comment]
Initially, I upvoted this, as I naively thought it was going to fix the fundamental problem with structs: the inability to control their default values. Having read through the whole thread though, that has changed to a downvote. What is actually proposed here is a very very bad design.

For example, if I have a `Fraction` struct (written here for brevity, rather than correctness):
````cs
struct Fraction
{
    int Numerator {get;}
    int Denominator {get;}
    Fraction(int numerator, int denominator) { ....

    double ToDouble() => (Numerator * 1.0) / Denominator;
}
````
Then, its default state is `0/0`, which is clearly a problem. If I call `ToDouble()` on a default fraction, I'll get a `DivideByZeroException`. In other words, I have a struct with the same flaws as a reference type (though in the latter case, the curse is the NullReferenceException).

Often people want to use structs to escape the `null` problem, but we all too often then run straight into the equivalent problem with structs: the inability to affect the default value of that struct.

It is therefore with near despair that I read comments from @gafter of:
> Once we allow new Struct(), then adding a constructor to Struct would cause the two expressions new Struct() and default(Struct) to have different behavior - the former calling the constructor, and the latter returning an instance that has been cleared.

and 

> @tenor No. The constructor should only be invoked if the constructor is invoked in source, just the same as for classes.

These statements couldn't miss the point more if they tried. The reason for wanting to be able to define a parameterless constructor in a struct is **not** so I can call, eg `new Fraction()`. Why on earth would I want to do that!? What I'd want to do is have that constructor called when I do `default(Fraction)`. "returning an instance that has been cleared" is fine as the default behaviour for a struct, but it's not always good. In those latter cases, custom behaviour should be specifiable via a parameterless constructor.

What @gafter is arguing for is taking a broken feature and "fixing" it by leaving it broken, but adding a confusing third way of creating a struct instance. That is complete madness. Can we just have the option of a parameterless constructor that is invoked by `default(T)`, please.

**Comment by HaloFour** [comment]
@DavidArno 

Who is actually responsible for ensuring that said constructor is ever invoked?  The CLR won't and in any except the simplest cases C# can't.  Given how leaky it would inevitably be I don't think it makes a lot of sense to have `default(T)` invoke some constructor when most of the time it couldn't happen.

**Comment by DavidArno** [comment]
@HaloFour, The CLR has to. So if the CLR doesn't support it then this is a non-feature until it does.

**Comment by Thaina** [comment]
> I'll say that many devs will be surprised that their struct was initialized but not constructed if the struct has a parameterless constructor.

It go back to this reason and I agree with this wise words

**Comment by gafter** [comment]
This request is now tracked at https://github.com/dotnet/csharplang/issues/99
