### ISSUE TITLE
Support VS Editor Completion List tabs

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#14021]
Ported from DevDiv 

The VS Editor completion list can contain multiple tabs populated by different language services. Roslyn does not track the state of this selection and will prevent tabs populated by other language services from committing.

**Comment by AArnott** [comment]
In my scenario, it wasn't another language service. It was my [GuidGen tool](https://visualstudiogallery.msdn.microsoft.com/e00f525e-50cc-4c42-85a0-73519ee289b1) that was supplying an autocomplete entry in this list to immediately enter a new guid.

**Comment by AArnott** [comment]
1. Install the [GuidGen 2.0 VSIX](https://1drv.ms/u/s!Aj3kll8mDD0GgaXsEGmL_dPwRLLCt64).
1. Launch VS (Dev12 or Dev14)
1. Create a VB project
1. In the VB source file, type "guid" within the class or module.
1. In the completion list, select the Guids tab.
1. Select the GuidF completion.

**Dev12 behavior:**
The completion for GuidA is inserted instead of GuidF.
(Note if a C# project is attempted, the completions are all correct)
 
**Dev14 behavior:**
No completion at all is inserted.
(Note if a C# project is attempted, all completions are broken just like in VB)

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
