### ISSUE TITLE
Reads and writes are propagated differently from unreachable code in local functions and behavior is not consistent across different types of unrachable code.

### ISSUE THREAD

**Issue by TessenR** [dotnet/roslyn#14046]
In the following code the call to 'Local' should either propagate both the write to 'x' and the read from 'y' or neither of them or mark all code after the call as unreachable.
Currently the call propagates write to 'x' though it is unreachable but doesn't propagate unreachable read from 'y'.

```cs
class C
{
  public void M3()
  {
    int x, y;
    void Local()
    {
      while(true) continue;
      x = 5; // unreachable code
      System.Console.WriteLine(y);
    }

    Local(); // the call doesn't require 'y' to be assigned since its usage is unreachable
    System.Console.WriteLine(x); // 'x' is assigned here but it shouldn't since assignment is unreachable

    // the error here implies the branch itself is reachable
    System.Console.WriteLine(y); // error CS0165: Use of unassigned local variable 'y'
  }
}
```

unreachable code after a 'throw' statement behaves the same way.

```cs
class C
{
  public void M3()
  {
    int x, y;
    void Local()
    {
      throw null;
      x = 5; // unreachable code
      System.Console.WriteLine(y);
    }

    Local(); // the call doesn't require 'y' to be assigned since its usage is unreachable
    System.Console.WriteLine(x); // 'x' is assigned here but it shouldn't since assignment is unreachable

    // the error here implies the branch itself is reachable
    System.Console.WriteLine(y); // error CS0165: Use of unassigned local variable 'y'
  }
}
```

Unreachable code after 'return' statement behaves differently and usages there don't affect compilation.

```cs
class C
{
  public void M3()
  {
    int x, y;
    void Local()
    {
      return;
      x = 5;
      System.Console.WriteLine(y);
    }

    Local();
    System.Console.WriteLine(x); // error CS0165: Use of unassigned local variable 'x'
    System.Console.WriteLine(y);
  }
}
```

**Comment by gafter** [comment]
The compiler's behavior is correct. The use of `y` in `Local` is at a location where it is definitely assigned, whether or not it is assigned by the caller. Is does not need to be assigned in the caller for that usage point to be definitely assigned. Similarly, `x` is definitely assigned by the call to `Local`, since `x` is definitely assigned at every (i.e. all zero of them) reachable return point from `Local`.

However, you are correct about the incorrect error on the use of `y` in the caller. It should also be treated as definitely assigned by the call to `Local`.

**Comment by gafter** [comment]
@agocke I believe this is the same issue as #13739.

**Comment by TessenR** [comment]
@gafter Thanks for clarification. Does it mean that call to any local function without reachable returns should make all variables definitely assigned even if they aren't used in the local function?

I.e. should following code compile without errors?
```cs
class C
{
  void M()
  {
    int z;
    void Local() { throw null; }
    Local();
    Console.WriteLine(z);
  }

  void M2()
  {
    int z;
    void Local() { Local2(); }
    void Local2() { Local(); }
    Local();
    Console.WriteLine(z);
  }
}
```

**Comment by gafter** [comment]
@TessenR Yes, that should compile without error.

**Comment by TessenR** [comment]
@agocke 
Now this is correct local function but incorrect method:

```cs
void Smth()
{
  int x;
  Smth();
  x++; // if Smth is a local function this line isn't reachable. 
  x++; // If Smth is a method it's reachable and there is a compilation error
}
```

Is it supposed to be so? Having different rules for similar language elements is somewhat confusing and counterintuitive.

**Comment by agocke** [comment]
@TessenR I believe this is by design.

The way C# is designed, all method calls are assumed to return. The reasoning is pretty straightforward: since the compiler doesn't and can't do inter-procedural flow analysis for most method calls, we have no way of knowing whether or not the call will complete, so we must assume that it does. Given this, all statements after method calls are deemed reachable. It's true that there's one exception to this -- recursive calls. In this case we wouldn't have to do any inter-procedural analysis since the call is inherently in the current procedure. However, this would be an exception to the general rule for flow analysis for method calls.

On the other hand, local function calls are fully analyzable by the compiler, so we can do a full set of inter-procedural call analysis for every local function call. This means we can treat local function calls as flow branches and, like intra-method branches, assume that these branches are unreachable until proven otherwise. In this instance, recursion isn't treat specially, it's just treated as any other local function call.

So, to look at this from a different perspective, for recursion method calls and local functions behave differently, but the rules are consistent among the set of "method call rules" and "local function rules", and simply inconsistent in the specific case of recursion.
