### ISSUE TITLE
Suggestion: Convert out var to local

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#14130]
**Version Used**: preview/25725

``` C#
class C
{
    void M()
    {
        int.TryParse("", out var [|x|]);
    }
}
```

Nothing is available here to convert it to a local.

**Comment by jcouv** [comment]
Note: the converse operation works though.

![image](https://user-images.githubusercontent.com/12466233/38451369-68ec0fee-39e3-11e8-901b-468523910121.png)

**Comment by jcouv** [comment]
I probably won't have time to look at this in 15.8 timeframe. Freeing the issue for anyone interested.

**Comment by stcahlon** [comment]
The out variable in the argument list of the method call now exists beyond the scope of the if. Therefore, this has become redundant. 

Furthermore:
Starting with C# 7.0, you can declare the out variable in the argument list of the method call, rather than in a separate variable declaration. This produces more compact, readable code, and also prevents you from inadvertently assigning a value to the variable before the method call. taken from: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/out-parameter-modifier
