### ISSUE TITLE
Link to Test Source on Failure

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#14165]
Is there a way to provide a link to source code of the test failure? on jenkins.

**Comment by jasonmalinowski** [comment]
Good question. @mmitche or @jaredpar?

**Comment by mmitche** [comment]
I don't think the xunit test result format actually includes that data (file/line number info).  If it did, it would be possible.

**Comment by jaredpar** [comment]
@mmitche is correct.  It's not reliably in the log data.  In order to do this we essentially need a service to navigate between fully qualified test name and source.  If that is present though then sure we could do it. 

Certainly could be written: DLL and PDB are available.  But probably lower on the infra list IMHO.

**Comment by jasonmalinowski** [comment]
Moving to the backlog then.
