### ISSUE TITLE
Support Move Type to File for every type in file/project/solution

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#14203]
Move Type to File is great because it lets users extract a type into a separate file with the same name. However, often developers have multiple types in a single file and want to do this operation for every type in the file/project/solution in a single click. 

Right now, you have to manually trigger the refactoring for each type.

**Comment by adamralph** [comment]
:+1: also useful for when you inherit a legacy code base.

**Comment by CyrusNajmabadi** [comment]
We should be able to do this if we make this feature into an analyzer instead of into a refactoring.  Then you should be able to just to "Fix all in document/project/solution".  It very much seems like 'refactorings' are purely for things where you need to select some range of code in order for the refactoring to know what it will even operate on.

**Comment by alrz** [comment]
I figured it should.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback and high impl/complexity cost.
