### ISSUE TITLE
Change to ?: semantics when both types are implicitly convertible to one another

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#14213]
The following code

``` cs
        List<dynamic> l1 = null;
        List<object> l2 = null;
        var l3 = b ? l1 : l2;
```

previously failed to compile, as required by the specification, due to

``` none
Error CS0172 Type of conditional expression cannot be determined because 'List<dynamic>' and 'List<object>' implicitly convert to one another
```

It now compiles without error and assigns `l3` the type `List<dynamic>`. This is either (1) a bug, or (2) an intentional change. If it is a bug, it needs to be fixed. If it is intentional, it needs to be specified.

[I believe this is an intentional effect due to the addition of tuples.]

**Comment by VSadov** [comment]
Need to let Mads know. I think the new behavior actually follows the spec (or the spirit?) of the language. Perhaps need to add something to the spec though.

**Comment by MadsTorgersen** [comment]
This was always intended to work when `dynamic` was added, but it was realized late that the compiler didn't fully support it, and so we left it out of the spec. Note that it _did_ prefer `dynamic` over `object`, but "forgot" to prefer/infer `List<dynamic>` over `List<object>`. 

The issue is that "Fixing" of type parameters doesn't take into account the nuance of types that have identity conversion to each other, but aren't the same type. This used to affect just the corner case of `dynamic` versus `object` (as in `List<dynamic>` vs `List<object>` above), but with tuples it becomes a lot more common: Tuple types with the same types but different names are also different types with identity conversions between them.

So when updating the "fixing" rules for tuples, the always-intended-but-never-implemented behavior for `dynamic` came along for the ride. The spec for C# 7.0 needs to reflect this of course.

**Comment by jcouv** [comment]
This was reviewed by compat council and LDM and the conclusion is to keep the behavior as currently implemented, despite a small compat break. 
@gafter will add the documentation for it.
