### ISSUE TITLE
Diagnostics reported in additional files do not show line information in Error List

### ISSUE THREAD

**Issue by tmeschter** [dotnet/roslyn#1431]
The error shows up, but the line and column do not show.

**Comment by heejaechang** [comment]
@srivatsn @tmeschter @mavasani @JohnHamby @shyamnamboodiripad is this something we want or suggestion?

currently whole system expect Document, we can change system to expect TextDocument to support this.

but support will be limited to error list since our tagger is limited to Roslyn Content type. to support tagger, we need text content type tagger but that will make us to be loaded for all random text file.

let me know what we want.

**Comment by tmeschter** [comment]
@heejaechang For now I would just make it show line/column information in the Error List. Expanding the tagger to work in all text files is something we can do later.

**Comment by mavasani** [comment]
I agree with Tom. If possible, we should show location info in error list, and ensure that double clicking on it takes you to the correct line in the doc. Tagger support can come later.

**Comment by shyamnamboodiripad** [comment]
+1

**Comment by JohnHamby** [comment]
I agree with Tom, Manish, and Shyam.

**Comment by heejaechang** [comment]
@srivatsn @tmeschter @mavasani @JohnHamby @shyamnamboodiripad I looked a bit more on this. it require a bit of work to make this one working through out the system. many of them expects SyntaxTree or location to be in source. location we create for additional files are externalfilelocation which can point any random file in the file system.

need to go through whole system to make sure everything is working properly so I dont think it is a bug but a story to support this.

currently, external location will not show up in error list at all. I am not sure how it showed up before. since the way we find documentId for location is using SyntaxTree (since we can't use path which are ambiguous with linked/shared/project k file) which additional file doesnt have.

anyway, I am moving this to 1.1

**Comment by twsouthwick** [comment]
We are creating some analyzers that check other "AdditionalFiles" such as XAML and config files. I see that the milestone was moved to Unknown - is this not being investigated anymore?

**Comment by heejaechang** [comment]
@twsouthwick I have an issue that are related to this. but as I thinking more, people seems abusing additional files because they can put random thing as additional files. analyzer is supposed to analyze only code, not those random files. I think we either need to add official support for analyzing any files or tight up what additional files are meant to.

**Comment by twsouthwick** [comment]
Makes sense. The thing about analyzers that make it useful for our project is to analyze the project files (not just code files) since non-code files affect runtime behavior (such as external config files). Having a full story for things like XAML, config, xml, etc would be awesome!

For curiosity, why was AdditionalFiles created instead of just exposing the other files in the project, such as those marked in a csproj with None, Page, etc, with a generic "OtherFiles" property?

**Comment by ejohn20** [comment]
+1 - Please add the ability to set the location for additional files and populate the File and Line columns.

**Comment by heejaechang** [comment]
we do have prototype for this
https://github.com/dotnet/roslyn/pull/8525

and related issue.
https://github.com/dotnet/roslyn/issues/6649

but didn't decide whether we want to enable this or not.

**Comment by ejohn20** [comment]
@heejaechang Any idea if this will be released anytime soon. Or if I can turn on the feature flag in a particular version? I'd like to test it out a bit when it's available.

**Comment by srivatsn** [comment]
The change required is fairly large and we are not currently planning to pick up this work soon. As input for prioritization though, could you please tell us about your scenario? Why do you need to report a diagnostic in an additional file? Are you analyzing the file itself and finding some error in the additional file or are you analyzing a source file but have to report the diagnostic in the additional file?

**Comment by heejaechang** [comment]
@ejohn20 sorry not in right now. @mavasani @srivatsn do we want to support this scenario?

**Comment by ejohn20** [comment]
My particular interest is analyzing an "AdditionalFile" and reporting a diagnostic in that file. For example, the web.config or app.config file. I'm writing a number of rules around insecure settings in the web / app config files that I would like to alert my developers about as they are building their applications. For example, forgetting to enable custom errors, placing a cleartext password in the app settings, or disabling encryption on the auth cookie.

Queries such as this can also apply to other web content files (.aspx, .cshtml, JavaScript, etc.) that are considered "AdditionalFiles". There is a lot of code in these files that can contain security issues that I will be exploring writing rules for to catch during development. For example, looking for calls to Html.Raw with user-supplied input or looking for insecure JavaScript libraries being referenced.

Right now, I have worked around this by adding the file path, line number, and snippet to the diagnostic message that shows up in the list. But, having the file and line number populated with the ability to double click on the file to go directly to the issue would be icing on the cake.

**Comment by heejaechang** [comment]
@ejohn20 I think an issue is that analyzer in current form is not designed to support your scenario. you found a way to make it work for you, but none of engine is written that kind of scenario in mind. basically current design is analyze code (C#/VB) and report diagnostics on code. additional file is used as an input to find issue in code not the other way around.

for example, the scenario we are supporting is 
analyzer check additional file, and tell users "you need to change code A to B since you have C in the additional file" 

not the other way around, like
analyzer check additional file, and tell users "you need to change string in additional file A to B since you have C in the code"

or completely ignore code and do things like
analyzer check additional file, and tell users "you need to change string in additional file A to B since it has C problem"

...

but that being said, if there is enough need/request, we probably should start thinking about adding generic text analyzers that can analyze any text involved in a project/solution rather than current compiler centric view.

**Comment by ejohn20** [comment]
Correct, I think I've managed to hack a solution together to work for my current requirements. 

But, I would definitely up vote the addition of a generic text analyzer. There is a lot of non-code in a project, especially web projects, that effect on how the code in the project behaves at runtime.

**Comment by heejaechang** [comment]
anyone interested in adding general text analyzer in roslyn, we will appreciate if you leave your opinion on #11097

**Comment by heejaechang** [comment]
closing. this issue is basically same as #11097 . if we do that, it will be automatically work. if not, we can't support this properly.
