### ISSUE TITLE
Add support for /instrument codecoverage for new language features

### ISSUE THREAD

**Issue by ManishJayaswal** [dotnet/roslyn#14337]
@JohnHamby mentioned that it does not work for all new C# language features.

**Comment by ManishJayaswal** [comment]
FYI - @JohnHamby @jaredpar @VSadov @jcouv @gafter

**Comment by gafter** [comment]
We already support instrumentation for
1. the deconstruction declaration statement (currently `Instrumenter.InstrumentLocalDeconstructionDeclaration`)
2. deconstruction in a for-each (currently `Instrumenter.InstrumentForEachStatementDeconstructionVariablesDeclaration`)
3. the pattern switch statement (currently `Instrumenter.InstrumentPatternSwitchStatement`)
4. the new switch `when` clause (currently `Instrumenter.InstrumentPatternSwitchWhenClauseConditionalGotoBody`)

These are already implemented for `Instrumenter`, `CompoundInstrumenter`, and `DebugInfoInjector`, and invoked appropriately from the compilers.

Code coverage support will need to be specified and then implemented. I'll set up a meeting to decide what the spec is.

**Comment by gafter** [comment]
See also https://github.com/dotnet/roslyn/issues/14156

**Comment by JohnHamby** [comment]
Just to be sure that there's no confusion, the instrumentation requested here is done by DynamicAnalysisInjector, which is absent from the list of already-enhanced instrumenters mentioned above.

**Comment by ManishJayaswal** [comment]
FYI @AlekseyTs

**Comment by gafter** [comment]
The desired behavior is as follows

- [ ] For `InstrumentLocalDeconstructionDeclaration`, it should be instrumented just like any other statement.

- [ ] For `InstrumentForEachStatementDeconstructionVariablesDeclaration`, it should be instrumented the same way as `InstrumentForEachStatementIterationVarDeclaration`.

- [ ] For `InstrumentPatternSwitchStatement`, it should be handled the same way as `InstrumentSwitchStatement`.

- [ ] For InstrumentPatternSwitchWhenClauseConditionalGotoBody, the ‘when’ clause should be instrumented as if it were a separate statement. There doesn’t appear to be a suitable helper to do that, because the clause isn’t syntactically a Statement, but the instrumentation should do something morally equivalent.
