### ISSUE TITLE
ENC0063 Updating 'out variable' when not updating it

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#14544]
**Version Used**: 25807

**Steps to Reproduce**:

``` C#
class Program
{
    static void Main(string[] args)
    {
        List<int> l = null;
        string s = "4";

        try
        {
            l.Clear();

            if (int.TryParse(s, out int i))
                Console.WriteLine(i);
        }
        catch (Exception e) { }
    }
}
```
1. Put breakpoint on the catch line or step there.
2. Delete the `l.Clear();` line.

**Expected Behavior**:
Be able to edit and continue.

**Actual Behavior**:
ENC0063 Updating a 'out variable' statement around an active statement will prevent the debug session from continuing.

I am cool with updating an 'out variable' not being supported but that's not what I did.

**Comment by miloush** [comment]
I hit the same with 'is pattern', the code being something like
```
try {
 ...
 string s = "test";
 if (request is HttpWebRequest webRequest)
    s = webRequest.RequestUrl;

 XElement el = new XElement("element", "replace");
 ...
}
catch (ThreadAbortException) { ... }
```
when I tried to replace `"replace"` with `s`.

**Comment by f00f** [comment]
I created a minimal sample for this bug:

# Code
```
namespace EditContinueOutVariableTest
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");

            Foo(out int bar);

            Console.WriteLine("Make sure `bar` is used: " + bar);
        }

        static void Foo(out int bar)
        {
            bar = 2;
        }
    }
}
```

# Steps to reproduce
1. Set breakpoint on the line where Foo is called.
1. Run in debug, with debugger.
1. Modify the string "Hello World", e.g. remove the exclamation mark.
1. Try to continue

# Observed behaviour
VS will not allow to continue and give the error code ENC0063 with the description "Updating a 'out variable' statement around an active statement will prevent the debug session from continuing."

# Expected behaviour
Continuing should be possible. At the very least an appropriate error message should be produced.

**Comment by tmat** [comment]
This behavior is currently expected. https://github.com/dotnet/roslyn/issues/17896 tracks enabling EnC in methods with ```out var```. 

Yes, the error message is not ideal. No point in fixing it though since the plan is to enable the edit.
