### ISSUE TITLE
VB Language service not able to handle the case where /nostdlib is passed, but no mscorlib is passed

### ISSUE THREAD

**Issue by huizhonglong** [dotnet/roslyn#14584]
Right now, VB language service is broken (broken Intellisense, false squiggles etc) in **DPL** mode.
AnyCode gets the command line args by running CoreCompile target, passes them to Roslyn.
•     In C# case:
o   /nostdlib+ is passed
o   /reference:"….\mscorlib.dll" is explicitly passed

•     In VB case:
o   /nostdlib is passed
o   No mscorlib is passed

Per Kevin:
In VB, unlike in C#, if /nostdlib is passed, a reference to mscorlib is still implicitly added based on the sdkpath directory (see here for how this happens in normal IDE code).  That isn’t happening for CPSProject though.

@mavasani 

1)  This specific issue of us not passing an implicit mscorlib in presence of non-null sdkpath. Please assign this one to me.
2)  Test issue: Currently we only have IWorkspaceProjectContext unit tests for C#, we need to add the same set for VB.

**Comment by ManishJayaswal** [comment]
Assigning to @mavasani as per email thread. 
@Pilchie it would be great to have this fixed in RC - primarily so that we can continue dynamic analysis testing with DPL

**Comment by mavasani** [comment]
I looked at this more closely and it seems the DefaultCoreLibReference cannot be exposed (and is not the right thing to expose) because VB compiler has additional logic in ResolveMetadataReferences to decide whether or not the implicit core lib reference is added.

So basically, this needs to be handled by the specific project systems. For this specific issue, the DPL loading code here needs to iterate over “.ResolveMetadataReferences()” instead of “.MetadataReferences”, which should include the resolved mscorlib reference. @Pilchie moving this over to you.

**Comment by Pilchie** [comment]
Moving to RC.2 as this was rejected by shiproom.

**Comment by Pilchie** [comment]
Fixed in #14848 for lightweight solution load.

CPS projects and Open Folder will need different solutions.
