### ISSUE TITLE
CS0012 in Microsoft.CodeAnalysis.CSharp.Scripting on .NET Core: Cannot find System.Object

### ISSUE THREAD

**Issue by GeirGrusom** [dotnet/roslyn#14614]
When trying to run scripts on .NET Core with Roslyn.Scripting I always get a failure that it cannot find System.Object. There are three references to `Object`'s assembly in the source code, but none of them resolve correctly.

**Versions used:**
Microsoft.CodeAnalysis.CSharp: 1.3.2,
Microsoft.CodeAnalysis.CSharp.Scripting: 1.3.2

```json
   "frameworks": {
    "netcoreapp1.0": {
      "imports": [ "dnxcore50" ]
    }
  }
```

**To reproduce**:
1. [Clone](https://github.com/GeirGrusom/RoslynScript.git)
2. Run
3. Observe failure

**Expected Behavior**:
prints "Hello World!"

**Actual Behavior**:
>  error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.

Without the global object parameter it works as expected.

**Comment by GeirGrusom** [comment]
Related issue: #12393

**Comment by tmat** [comment]
Your code has a couple of issues:

```C#
var options = ScriptOptions.Default
     .WithReferences(@"C:\Programs\dotnet\bin\System.Runtime.dll")
     .WithReferences(typeof(object).GetTypeInfo().Assembly);

    Microsoft.CodeAnalysis.CSharp.Scripting.CSharpScript.RunAsync("System.Console.WriteLine(Foo);", options, new { Foo ="Hello World!" } );
```

First, ```WithReferences``` replaces the current references with the specified ones. It doesn't add references. ```AddReferences``` does. As a result the script options will only have a single reference:

![image](https://cloud.githubusercontent.com/assets/41759/19630567/d063325e-9941-11e6-8be4-a8ff5b1113ab.png)

Second, after changing ```With``` to ```Add``` you'll run into accessibility issue. Anonymous types are internal to the assembly that declares them. The script is compiled to a separate runtime assembly that currently doesn't have access to the host assembly, so you'll get type access exception. To work around you can declare and use a public type instead of the anonymous type.

**Comment by GeirGrusom** [comment]
Did you actually try that? I've been trying to get this to work for *days* and `AddReference` makes no difference (and in this case I don't think it should either). The DLL reference is the correct one. That's where the assembly containing System.Object is located according to `GetTypeInfo().Assembly`.

It doesn't get far enough to complain about the anonymous type.

I've updated the repository to remove the anonymous type and use `AddReference` instead. It still doesn't work.

**Comment by tmat** [comment]
I forgot to state the third issue: ```"System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"``` doesn't get resolved since there is no GAC on CoreCLR and we only support resolving assembly display names against the GAC. In the snippet above I replaced it with a full path to ```System.Runtime.dll```

**Comment by GeirGrusom** [comment]
> doesn't get resolved since there is no GAC on CoreCLR and we only support resolving assembly display names against the GAC.

I get that, and I suspected as much (and I've been down this road during some frustrating days), but why doesn't `AddReference(typeof(object).GetTypeInfo().Assembly)` work? It seems to be that at that point I'm asking it to use the assembly that contains `object` or is there something I don't understand?

>  In the snippet above I replaced it with a full path to System.Runtime.dll

That is not a solution at all.

You need to admit that there is something missing here and open the issue. You can't expect that the user need to inject the freaking *runtime* by *it's filesystem path* in order to execute a freaking script.

**Comment by tmat** [comment]
```AddReference(typeof(object).GetTypeInfo().Assembly)``` works. It adds System.Private.CoreLib.dll, which defines ```System.Object```. The problem is that other assemblies compiled against .NET Core (including Microsoft.CodeAnalysis.Scripting) reference ```System.Object``` thru ```System.Runtime``` assembly, which forwards the type to ```System.Private.CoreLib```. So you need both.

I agree it's not an ideal experience. Note however, that .NET Core is not currently supported (see https://github.com/dotnet/roslyn/wiki/Scripting-API-Samples#supported-platforms) hence the experience hasn't been optimized yet. We plan to make it better once we support targeting .NET Core.
