### ISSUE TITLE
Audit our analyzers to see if we can make them concurrent

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#14639]
There's a flag that enables/disables concurrent analysis, and we should see if we can use it.

**Comment by dpoeschl** [comment]
FYI @heejaechang @CyrusNajmabadi

**Comment by heejaechang** [comment]
the flag just let engine know whether they are okay to run concurrent. and engine decide whether concurrency will be used or not.

IDE in proc engine, always says no. and never run anything concurrent. OOP engine, always says yes. and run analyzers that are marked as concurrent ready concurrent.

**Comment by tamlin-mike** [comment]
@heejaechang
Provided the analyzers are run by FxCop (if not, please disregard this comment),

> OOP engine, always says yes.

I believe that's an error, especially when it's a 32-bit process.

See: https://developercommunity.visualstudio.com/content/problem/1512/fxcop-even-when-out-of-process-runs-out-of-memory.html

Even the OOP engine should throttle parallelism under resource constrained conditions.

**Comment by heejaechang** [comment]
@tamlin-mike this is different than FxCop the link is refering to. and code consuming a lot of memory won't use less because it is not run concurrent. the reason VS didn't run those concurrent inproc is not due to VM but due to allocation rate+GC which cause VS to freeze and cause responsiveness issue. this shouldn't be issue for out of proc engine since 1. there is no UI user interact with 2. everything is async from beginning which let VS not affected by GC on OOP.

**Comment by tamlin-mike** [comment]
@heejaechang
Thanks for explaining and putting my worries to rest.

**Comment by heejaechang** [comment]
@tamlin-mike I think your worry is valid one. we still can get OOM by bad analyzers or a solution having a lot of analyzers installed. which by running things concurrent, more easily get to OOM than not running analyzer concurrent.

if we start to see such situation commonly occurs, we probably need to start moving to 64bit OOP. 64bit process gets more memory space, but it also uses more memory than 32bit process since all pointers become twice big + GC will less aggressive on compacting memory.

**Comment by tamlin-mike** [comment]
@heejaechang
OK, so the throttling idea was perhaps not completely wasted after all?

As it seems you're on top of this, would you mind opening an issue (even if just as a reminder) about this very thing? In my mind, it's not really a question about "if", but "when". :-)

**Comment by heejaechang** [comment]
@tamlin-mike I have this work item - https://github.com/dotnet/roslyn/issues/14664

**Comment by tamlin-mike** [comment]
@heejaechang
While a good idea, it didn't address your concern that in 64-bit process pointers will be double size.

If one AST-producer (or even just plain src text) could share in a read-only section, the consumers could run in separate (reasonably) lightweight 32-bit processes. That was my thinking.

I don't know how much memory is _actually_ saved 32- vs 64-bit "VM" (i.e. .NET runtime). You probably have a lot more data on that.

Anyway, I just wanted to bounce this idea. I _think_ it may have some merit, but profiling is proof.
