### ISSUE TITLE
Expression-bodied function members doesnt accept MethodImpl attribute

### ISSUE THREAD

**Issue by redknightlois** [dotnet/roslyn#14776]
**Version Used**: 
C# 6.0

**Steps to Reproduce**:

```csharp
        public struct Sum
        {           
            public int X;
            public int Y;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public int Value => X + Y;
        }
```

**Expected Behavior**:
Be able to hint the JIT to apply aggresive optimization on the expression-bodied function members (aka apply the ```MethodImpl``` attribute)

**Actual Behavior**:
Does not compile with: ```error CS0592: Attribute 'MethodImpl' is not valid on this declaration type. It is only valid on 'constructor, method' declarations.```

**Comment by gafter** [comment]
That attribute is restricted to be applied to constructors and methods, but not properties. If you want to apply it to the get method, you'll have to use the more verbose syntax so that the get method is present and can have the attribute applied to it. In C# 7 you should be able to write this:

```cs
public struct Sum
{
    public int X;
    public int Y;

    public int Value
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => X + Y;
    }
}
```

Your alternative is to request a change in the `MethodImpl` attribute, but I don't expect you are likely to get a change.

**Comment by redknightlois** [comment]
Good to know that would be solved on C# 7. We have been using the workaround but it gets old to not being able to use the new syntax specially where it is useful for us.
