### ISSUE TITLE
Fix All for Code Styles is broken

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#14978]
If I `Ctrl+.` to convert 'var' to 'explicit' type and then 'Fix All in Document', the entire lightbulb menu+preview dialog disappears and nothing happens (no code fix is applied).

**Comment by kuhlenh** [comment]
@CyrusNajmabadi ran into this as well

**Comment by CyrusNajmabadi** [comment]
@mavasani Can you help me out here?  From debugging through we eventually make it to FixAllContext.GetDocumentDiagnosticsAsync, which returns an empty array of diagnostics.  So, obviously, no changes happen.

**Comment by CyrusNajmabadi** [comment]
also @heejaechang   @mavasani speculates this might possibly be an OOP issue.

**Comment by mavasani** [comment]
@CyrusNajmabadi Which CodeFixProvider fixes this diagnostic?

**Comment by CyrusNajmabadi** [comment]
UseImplicitTypeCodeFixProvider

**Comment by mavasani** [comment]
@heejaechang I debugged through this and verified that this is an issue in OOP. Basically, if I set a breakpoint in [VisualStudioDiagnosticAnalyzerExecutor.AnalyzeAsync](http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices/Implementation/Diagnostics/VisualStudioDiagnosticAnalyzerExecutor.cs,53) and force `remoteHostClient` to be null, then it correctly returns all document diagnostics, otherwise it does not.

FYI: To repro this issue, you can use the source code and options in the below screenshot.

![codestylerepro](https://cloud.githubusercontent.com/assets/10605811/20370839/b76add4c-ac15-11e6-9e04-2a7991ba9e5a.png)

**Comment by heejaechang** [comment]
sounds like dup of this.
https://github.com/dotnet/roslyn/issues/15041

can you check whether there is 2 roslyn code analysis exe?

**Comment by heejaechang** [comment]
fixed https://github.com/dotnet/roslyn/pull/15566
