### ISSUE TITLE
DPL: Roslyn syntax generators not run on solution open

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#14987]
Clone http://github.com/dotnet/roslyn.git and run restore.cmd and *do not build*.
Open Roslyn.sln with DPL enabled.
The compiler's SyntaxNode generators do not get run when the project is opened, leading to numerous errors because no node types can be found.

**Comment by rchande** [comment]
cc @Pilchie

**Comment by Pilchie** [comment]
Thinking more about this, I think this is probably the same behavior in non-DPL.  Those tools are built by other projects in the solution, and I don't think our design-time builds are set up to build those other tools.

(This is different from things like the IVT and AssemlyInfo files that *are* generated by Design time builds).

@jasonmalinowski does that sound right to you?

**Comment by Pilchie** [comment]
Can you double check the behavior in non-dpl?

**Comment by jasonmalinowski** [comment]
@Pilchie Yes, that sounds right.
