### ISSUE TITLE
Newly added .editorconfig only applied after reloading files

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#15003]
Create a new C# console app.
Open `program.cs`
Right click -> add new item -> text file.
Rename the file to `.editorconfig` 
Paste the following into the file and save
```
[*.cs]
indent_style = tab
indent_size = 10
```
Switch to the `program.cs` tab and invoke `Edit.FormatDocument`.

Expected:
The document is formatted to use tabs and a wider indent.
Actual: Nothing happens
After closing and reopening program.cs, `Edit.FormatDocument` applies the new formattnig settings.

**Comment by dpoeschl** [comment]
Also repros when changing an existing .editorconfig file.

**Comment by Pilchie** [comment]
The issue here is in the core editor.  They are tracking with a bug in VSTS.

**Comment by DustinCampbell** [comment]
This still repros for me in 15.5 preview 1. Also, every speaker at VS Live who I've seen demonstrate this feature has had to call out this as a gotcha and complained loudly (to their audience) about it needing to be fixed. It's been nearly a year, can we get this issue bubbled up appropriately?

**Comment by sharwell** [comment]
The core editor already resolved this for the base settings. Reopening this issue to fix the Roslyn side.

**Comment by sharwell** [comment]
@olegtk if you can describe the events that need to be hooked up, I'm sure someone from the community will be able to help out :smile:

**Comment by olegtk** [comment]
ICodingConventionContext.CodingConventionsChangedAsync  is the event. There is a catch though, you have to import ICodingConventionsManager now instead of using a factory method.

From https://devdiv.visualstudio.com/DevDiv/_workitems/edit/508207:

Editor team has inserted file watcher support to editorconfig files in vsuvscore. With this insertion all universal coding conventions will react to changes in editorconfig files immediately without having to close and reopen code files.

However, language specific conventions will have to make the following changes:

1. Instead of getting ICodingConventionsManager from CodingConventionsManagerFactory.CreateCodingConventionsManager(), Language Service teams will have to import ICodingConventionsManager  and then proceed as usual.

2. To listen to changes in editor config file, components will have to listen to CodingConventionsChangedAsync of ICodingConventionContext. When the event is raised, the context will have the new updated conventions present in it and you will just have to reapply it.

**Comment by heejaechang** [comment]
let me take a look

**Comment by jinujoseph** [comment]
closed via #26221

**Comment by jinujoseph** [comment]
this was reverted as part of https://github.com/dotnet/roslyn/pull/26374
