### ISSUE TITLE
Iteration variable in ForEachStatementSyntax should be an IdentifierNameSyntax

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#1503]
Currently the structure of foreach statement node is following:
```
<Node Name="ForEachStatementSyntax" Base="StatementSyntax">
    <Field Name="ForEachKeyword" Type="SyntaxToken">
    <Field Name="OpenParenToken" Type="SyntaxToken">
    <Field Name="Type" Type="TypeSyntax"/>
    <Field Name="Identifier" Type="SyntaxToken">
    <Field Name="InKeyword" Type="SyntaxToken">
    <Field Name="Expression" Type="ExpressionSyntax"/>
    <Field Name="Statement" Type="StatementSyntax"/>
  </Node>
```

The iteration variable is represented as a token. Hence we have no distinct syntax node that could represent the scope of the variable. If we associate the variable with the foreach statement itself, it will collide in C# 7 with scope of variables declared in the expression. If we associate the variable with the embedded statement it will collide with the variables declared there.

The proposal is to wrap the identifier in an IdentiriferNameSyntax for RTM.

**Comment by gafter** [comment]
This has to be done by 1.0 (stable) as it would be a breaking change if done later.

**Comment by AnthonyDGreen** [comment]
A long time ago we made a decision that declarations wouldn't use nodes but directly embedded Identifier tokens. This is consistent with all member declarations. Changing as you've proposed would break this convention. We'll need to come up with a different approach for declaration expressions in C# 7. I don't think we can reasonably anticipate or prepare for all the ways that proposed feature might break assumptions now.

**Comment by gafter** [comment]
The foreach node is not a declaration. Making it contain a declaration is another way to address the issue.

**Comment by AnthonyDGreen** [comment]
I'm not entirely sure why the "<_Type_> <_Identifier_>" portion isn't a variable declarator (perhaps because it lacks an initializer?) but that would be a fix to consider. In any event we wouldn't use an IdentifierNameSyntax node, we reserve that node for references. We may be able to make the change to use a declarator node in 1.1 so I'm moving to that milestone.

**Comment by gafter** [comment]
@AnthonyDGreen how would we make that change without affecting all clients of the syntax tree API.

**Comment by gafter** [comment]
We might make a change in the context of adding support for deconstruction in the foreach loop that would make this possible.

**Comment by jaredpar** [comment]
I thought we had an issue tracking identifiers, `foreach` and deconstruction but can't find it off hand.  @jcouv please close or dupe as appropriate based on the work here.

**Comment by gafter** [comment]
Since the existing `foreach` node has a mandatory type and identifier, and we do not make mandatory fields optional in future versions for compatibility reasons, we will address this by adding a new node to represent `foreach` with a node for the declaration.

It is a separate question whether the parser uses this new node for all `foreach` loops, or only for `foreach`  loops that involve deconstruction.
