### ISSUE TITLE
InvalidCastException thrown for converting between types for which explicit/implicit conversions are declared

### ISSUE THREAD

**Issue by johndog** [dotnet/roslyn#15174]
I put this here for discussion, I don't know whether there is a good solution.  This isn't a new problem, but I've seen it surface more frequently in the context of generic enumerables and refactoring, both of which are more popular than they used to be.

**Version Used**: 4.5

**Repro Summary**
The runtime is unable to cast an object of type 'Foo' to type 'Bar', yielding InvalidCastException, even though there is a conversion path.

Consider the following code:

```
        public class Foo
        {
            public Foo(Bar bar)
            {
            }

            public static implicit operator Foo(Bar bar)
            {
                return new Foo(bar);
            }
            //....
        }

        public class Bar
        {
            public Bar()
            {
            }

            public Bar(Foo foo)
            {
            }

            public static implicit operator Bar(Foo foo)
            {
                return new Bar(foo);
            }
            //....
        }
```

With the above code, this operation succeeds:

     ((Foo)new Bar())

However, both of these fail:

1. Cast from object:  `((Foo)(object)new Bar())`
2. IEnumerable.Cast<>: `new[] { new Bar() }.Cast<Foo>()`

They both issue the same exception:

     System.InvalidCastException: Unable to cast object of type 'Bar' to type 'Foo'.

The second one is especially surprising because, by appearances, there is no intermediate type, and we've already shown that a direct conversion is possible.

**Problem Details**
The behavior described here helps create a brittle framework in which types appear to be universally convertible between each other, whereas in reality they are only convertible in one specific manner.  Without the conversion operators, the compiler would error on the direct cast of (Bar)Foo, because the types are unrelated.  The introduction of the conversion operators allows the direct cast to work, and code that takes advantage of this sets the stage for code patterns that allow the two repro cases to sneak in and manifest as runtime exceptions.  Who would look at the successful use of `(Foo)bar` and still think `barArray.Cast<Foo>()` would not work?

This is also a problem for refactoring.  For example:  Bar previously inherited from Foo, and the developer has refactored from inheritance to composition, using the conversion operators to smooth the transition, resolving compiler errors.  However, the compiler will not identify all the cases in which casts will no longer function, and lines of code which were never touched in the refactoring will begin throwing **InvalidCastException** at runtime.  Many non-generic collection types still treat elements as type **object**, and while explicit cast would work when the types are related by inheritance, it will not work when they have to be converted via the conversion operator.

**Hypothetical Solutions**
My hope would be to drive out as many runtime exceptions as possible, preferring compiler errors instead.  This means either making fewer things work at compile time, or making more things work at runtime.

With this in mind, I can think of several plausible improvements:

1. Enable `((Foo)(object)new Bar())` to work in the above scenario.  This would likely fix the Cast<> scenario as well.  I suppose the runtime would have to have the ability to discover whether the target type of an object had an explicit conversion operator defined for it.  It would also have choose between conversion operators if they exist on both the source and target.  Still, this seems doable; the types are certainly well known when the exception is thrown.  Is it too expensive for the non-exceptional case?  Too difficult to resolve the ambiguity when multiple conversions exist?
2. Drive out the unintended conversion from object to custom types with warnings.  With the surge of generics, it should be less necessary to convert from **object** than in the past.  But apart from the use of Cast<>, I don't know how you can recognize unintended conversions from object, so this path seems very difficult.
3. Deprecate conversion operators.  They are only a partial solution, and therefore a dangerous temptation.  They might be more trouble than they are worth.  If the developer isn't allowed to conflate casting and conversion, they are more likely to use safer patterns in all conversion scenarios.
4. Reimplement Cast<TResult> as  `.Select(_ => (TResult)_)`.  This won't fix the "cast from object" case, but it will at least enable Cast<TResult> to work between types that have conversion operators defined, and stop it from always using object as an intermediate step.  This means it will also result in a compiler error when there is no conversion path between TSource and TResult, instead of a runtime exception, which is great.

Of these, I think the first is the only one that can make refactoring safe.  I haven't thought of a way to use compiler errors to drive out all conversion errors that could be introduced by refactoring.

**Comment by svick** [comment]
> making fewer things work at compile time

That would be a breaking change, and those generally are not accepted by the C# compiler.

> I suppose the runtime would have to have the ability to discover whether the target type of an object had an explicit conversion operator defined for it.

As far as I know, the runtime currently has no knowledge of any operators. It's the responsibility of each .Net language to make them work (or not, as is the case of conversion operators in F#).

Also, this would be a breaking change too (code that did one thing before would do something else now).

> Deprecate conversion operators.

You're effectively saying that because the feature is not perfect, it should be completely removed? Also again, that would be a huge breaking change.

> Reimplement Cast<TResult> as `.Select(_ => (TResult)_)`.

Are you proposing that the compiler should translate `Cast` to `Select` or that the implementation of `Cast` should be changed?

In the latter case, it wouldn't work, you can't cast between generic types that have no relationship.

In the former case, it's not the compiler's job to know what the implementation of methods is and it's certainly not its job to change the implementation if it doesn't like it.

**Comment by johndog** [comment]
@svick - It sounds like you're taking the position that there are no good solutions.  Do you have any ideas?

> > Deprecate conversion operators.

> You're effectively saying that because the feature is not perfect, it should be completely removed? Also again, that would be a huge breaking change.

I used the word "deprecate", which typically suggests giving people a non-breaking path forward.  Still, I suppose something like this could be done with static analysis rather than changing the compiler.  I'd want to hear some debate whether the feature does more good than harm before doing even that.

> > I suppose the runtime would have to have the ability to discover whether the target type of an object had an explicit conversion operator defined for it.

> As far as I know, the runtime currently has no knowledge of any operators. It's the responsibility of each .Net language to make them work (or not, as is the case of conversion operators in F#).

That sounds right, but doesn't seem like a barrier; every language could turn operators into discoverable conversion instructions, perhaps located on the Type itself.  

Yes, it's a breaking change.  Clearly there are strategies for managing breaking changes, I don't want to presume whether any of these ideas are worth employing them.  That's the point of discussing them.

> > Reimplement Cast as .Select(_ => (TResult)_).

> Are you proposing that the compiler should translate Cast to Select or that the implementation of Cast should be changed?

I specifically meant the latter, but both are interesting.

> it wouldn't work, you can't cast between generic types that have no relationship.

Drat, you're right.  The concept depends again on the same mechanism as concept 1.

> In the former case, it's not the compiler's job to know what the implementation of methods is and it's certainly not its job to change the implementation if it doesn't like it.

I'd frame it differently.  C++ style templates could handle this, since they are compiled with the types in hand.  I understand that C# doesn't have anything like this, though this wouldn't be the first time I wish it did.  At any rate, the inability to fully implement a Cast<> speaks to me as a glaring hole _somewhere_.  

Any other ideas?  Maybe it's not a great idea to have a function called Cast<Foo>() when it's not literally the same as (Foo)bar; it could through the obsolete/rename protocol.

**Comment by CyrusNajmabadi** [comment]
> I'd frame it differently. C++ style templates could handle this, since they are compiled with the types in hand. I understand that C# doesn't have anything like this, though this wouldn't be the first time I wish it did. At any rate, the inability to fully implement a Cast<> speaks to me as a glaring hole somewhere.

I believe you can fully implement this.   Using the 'dynamic' solution already presented.  By using 'dynamic' you'll then get, at runtime, the same sort of conversion logic that you want.  It will be slow.  But that's precisely because you're asking for the full gamut of conversion logic to be available instead of a simply inheritance/implementation check.

**Comment by geoff-m** [comment]
The existence of an alternative to `Cast<T>()` aside, I would like to comment that despite the method's name, the fact that it refers only to conversion via _casting_ and not via the syntactically identical _(explicit) conversion operators_ is a surprise for users, and a design weakness. If conversion operators cannot be considered interchangeable with casts (for performance or whatever reason), they should not look the same where they are used--so says, I think, the developer's intuition.

It is one thing to explain this distinction to someone, but quite another to verify that it has been correctly observed in some codebase, due to syntax hiding what could be a crucial difference and a runtime error.

Perhaps we need a new Linq method `Convert<T>(),` which will attempt to use conversion operators. This would good as a matter of convenience, but we would continue to see bugs from incorrect usage of `Cast<T>()`. Like @johndog said, refactoring is a prominent cause. The underlying cause is that `(A)b` is surprisingly not equivalent to `(new B[] {b}).Cast<A>().Single()` in terms of correctness. (As we've seen, the two expressions are only equivalent if the former is a cast and not a conversion operator, but there's not even a way to tell which it is by looking at it.)

Thinking ahead a bit, in a world where both `Cast<T>()` and `Convert<T>()` exist, the former will be faster and less general/safe, and the latter will be slower and safer (more likely to behave correctly). We might start writing `Convert<T>()` by default (because it is less likely to break under refactoring, say), but the compiler ought to help us out here by choosing the simpler, better performing operation when it is possible. And the compiler can indeed know when it is possible (at least in most cases). This is to say, I see no reason from a language perspective that there shouldn't be a bit of concise syntax achieving the desired item-wise conversion of IEnumerables having no increased runtime cost compared to `Cast<T>()` in those situations where casting (not converting) is to be done. From a language implementation perspective, it calls for is answering whether a conversion operator has been defined for two types, but this is a question that the compiler already knows how to answer.

**Comment by CyrusNajmabadi** [comment]
> Perhaps we need a new Linq method Convert<T>(), which will attempt to use conversion operators. 

Conversion operators are language specific.  The set of C# conversions doesn't match the set of VB conversions for example.

**Comment by johndog** [comment]
@geoff-m I think you hit it on the head with naming.  I think I could trace my complaint to the regret that the terms "cast" and "convert" are two different things, when I want them to be the same -- as they are in C++.  That is where the confusion starts.

It occurs to me that what I'm usually looking for when I use .Cast<>() is syntactic sugar for:

```
IEnumerable<Foo> StaticConvert(IEnumerable<Bar> array)
{
    foreach (var item in array)
    {
        yield return (Foo)item;
    }
}
```

Where:

- Foo and Bar are concrete, related types, not generics, and
- The cast syntax would result in compile-time binding to any appropriate conversion operators in the context of the callsite.

The fact that no such thing exists, nor is it possible to exist in a generic way, is in itself a source of confusion.  The developer sees .Cast<>(), and thinks "ah! static conversion!", but it's really just a mirage.

I'm realizing that I never really wanted a dynamic conversion -- what I actually wanted was to not be surprised at runtime about something that could reasonably have been caught a compile time.

As such, I would be happy to see .Cast<> deprecated (not a breaking-change deletion).  If you read the [MSDN article ](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.cast?redirectedfrom=MSDN&view=netframework-4.8#System_Linq_Enumerable_Cast__1_System_Collections_IEnumerable_) closely, it's clear that IEnumerable.Cast<> exists essentially as a workaround for the typelessness of non-generic collections.  Which makes it ironic and misleading that it is implemented as a generic and an extension of IEnumerable.  If you're already working with generic collections, you are unlikely to be in a mindset where you recognize the intended limitations of this function.  I think Cast<>() would have been better implemented as an extension of ArrayList itself, and even duplicated for the other small handful of non-generic collection types, rather than as a generic for IEnumerable.

It also appears the only way to provide the "generic" StaticConvert<> functionality I actually think we all want is not through generics at all; C# would have to provide it through syntactic sugar.

For example:

```
var myBarArray = new[] { new Bar() };
var myFoArray = myBarArray **each as** Foo;
```

This could evaluate directly to an inlined implementation of StaticConvert() as described above (hand-waving on the yield-return):

```
    var myBarArray = new[] { new Bar() } 
    var myFooArray = foreach (var item in myBarArray )
    {
        yield return (Foo)item;
    }

```

If there was no appropriate conversion operator converting Foo() to Bar(), this would yield a compiler error.

**Comment by geoff-m** [comment]
> Conversion operators are language specific. The set of C# conversions doesn't match the set of VB conversions for example.
In what way does this matter here? What are the implications for this issue?

**Comment by geoff-m** [comment]
> Conversion operators are language specific. The set of C# conversions doesn't match the set of VB conversions for example.

In what way does this matter here? What are the implications for this issue?

**Comment by CyrusNajmabadi** [comment]
> ```c#
> var myBarArray = new[] { new Bar() };
> var myFooArray = myBarArray each as Foo;
> ```

> This could evaluate directly to an inlined implementation of StaticConvert() as described above (hand-waving on the yield-return):

You could just write this like so:

```c#
var myBarArray = new[] { new Bar() };
// var myFooArray = myBarArray each as Foo;
var myFooArray = myBarArray.Select(each => (Foo)each);
```

This gives the exact semantics you want, but deferring to the language to do cast/conversion precisely using the syntax the language has always used for this purpose.

**Comment by CyrusNajmabadi** [comment]
> The fact that no such thing exists, nor is it possible to exist in a generic way, is in itself a source of confusion. The developer sees .Cast<>(), and thinks "ah! static conversion!", but it's really just a mirage.

The BCL is not just for C#, it's for any .net language.  

> As such, I would be happy to see .Cast<> deprecated (not a breaking-change deletion). 

Deprecation is a breaking change.  Many people run with warnings as errors.  So all the code which uses .Cast properly will now break.

> If you're already working with generic collections, you are unlikely to be in a mindset where you recognize the intended limitations of this function

This is a very broad statement to make.  In Roslyn itself i found several hundred usages of this method, using it in the intended and documented fashion..

Note: if you want to deprecate the function, this is not the repo to file the issue. You'd have to do it over at dotnet/corefx.  Thanks!

**Comment by geoff-m** [comment]
> If there was no appropriate conversion operator converting Foo to Bar, this would yield a compiler error.

I guess the reason the compiler doesn't warn/error even when it's obvious the cast will fail is that it takes place inside a separate generic function. Taking into account how the compiler treats it (incl. checking errors), not only is `aIEnumerable.Cast<B>()` not syntactic sugar for `aIEnumerable.Select(a => (B)a)`, it isn't even syntactic sugar for the latter expression plus the constraint that `(B)a` is a cast. If I'm understanding correctly, that is why you said the implementation should be "inlined", because at least this way the compiler would give `Cast<T>()` first-class recognition as a cast.

It would really help if this were different, but as @CyrusNajmabadi says it sounds like an issue for C# and not roslyn. roslyn is probably already doing everything we'd need as concerns this issue.

I think getting more errors reported is preferable to deprecating Cast at this point.

**Comment by CyrusNajmabadi** [comment]
You could trivially add an error using an analyzer.  It can check for `.Cast<X>` calls and produce a message/warning/error if the source type is one that it thinks are problematic.

**Comment by CyrusNajmabadi** [comment]
Closing this out.  We're doing all language design now at dotnet/csharplang.  If you're still interested in this idea let us know and we can migrate this over to a discussion in that repo.  Thanks!
