### ISSUE TITLE
CodeFix adds first attribute in invalid place.

### ISSUE THREAD

**Issue by tom-englert** [dotnet/roslyn#15191]
**Version Used**: 
Visual Studio 2015 Update 3

**Steps to Reproduce**:
1. Analyze code with SingleLineDocumentationCommentTrivia
```
class Class
{
    /// <summary>
    /// This is a Test!
    /// </summary>
    public object Test { get; set; }
```
1. Locate the syntax node of the property declaration (same behavior for other types)
```
PropertyDeclarationSyntax propertySyntaxNode = syntaxRoot.FindNode(diagnosticSpan);
```
2. Add an attribute
```
var newPropertySyntaxNode = propertySyntaxNode.WithAttributeLists(
    propertySyntaxNode.AttributeLists.Add(GenerateMyAttributeSyntax()))

root = root.ReplaceNode(propertySyntaxNode, newPropertySyntaxNode)
```

**Expected Behavior**:
Valid code is generated:
```
class Class
{
    /// <summary>
    /// This is a Test!
    /// </summary>
    [MyAttribute]
    public object Test { get; set; }
```

**Actual Behavior**:
Warning CS1587: XML comment is not placed on a valid language element
```
class Class
{
    [MyAttribute]
    /// <summary>
    /// This is a Test!
    /// </summary>
    public object Test { get; set; }
```

**Comment by CyrusNajmabadi** [comment]
The onus is on you to keep code correct.  The APIs will not do it for you.  In this case, you'll have to do something akin to ```var newProp = oldProp.WithoutLeadingTrivia().WithAttributes(newAttributes.WithLeadingTrivia(oldProp.GetLeadingTrivia()))```

**Comment by tom-englert** [comment]
So you really say the method "WithAttributes" is designed to create invalid code by default, and everyone has to step into this trap and implement dull and ugly workarounds to make it work?

The workaround described does not work properly, because it fails if the element has already attributes, or if the trivia does not contain any comment!

**Comment by CyrusNajmabadi** [comment]
> So you really say the method "WithAttributes" is designed to create invalid code by default

No.  I would say: none of the 'WithXXX' methods do any sort of validation that they create correct code.  They simply do one thing.  They replace the existing XXX value on the node with the new one you provided.  That's it.  With every single WithXXX method i can create invalid code, and the onus is on the user of the API to not do that.

> The workaround described does not work properly, because it fails if the element has already attributes

Why would it fail if the element already has attributes.  In that case, the existing comments will be moved over from the old attributes to the new attributes.

> or if the trivia does not contain any comment!

Then only copy the comments :)

> and everyone has to step into this trap and implement dull and ugly workarounds to make it work?

I would describe it more as needing to know the limitations of the APIs.  Just wait till you get to deal with fun stuff like preprocessor directives :)

If you wanted to write an API to smooth out this experience, that would certainly be nice!

**Comment by CyrusNajmabadi** [comment]
Note: we've considered in the past trying to make it so that the methods only generate 'correct' code.  But we quickly realized htat the set of issues we'd have to codify would be enormous.  Furthermore, it would become extremely difficult for people using the API to get the precise sort of control that we do want sometimes.

Finally, we have scenarios where we do want to be able to create incorrect code (for example, so that we can continue with a refactoring, while telling the user about the issue that will arise).  So we opted for an API that behaves *very uniformly*.  The uniform nature of it precisely allows us to avoid the "dull and ugly" workarounds we used to have in our previous codebase where every piece of code needed to know all the interesting quirks of how all the APIs used to work, in their effort to "do the right thing".  

It turned out to be far better to just be consistent than not.

Thanks for your feedback!  I hope this helps!

**Comment by tom-englert** [comment]
The problem here is not when the WithXXX replaces existing values with other values - then it's working fine - but when there are no values and the WithXXX generates the first one. 

In the case of attributes the default position of the first attribute just has some unfortunate default. 
If the first attribute would be located near to the method or property instead of in front of the trivia of the method, the outcome would be much more likely to be correct than with the current default. 
It does not need to know how to do the right thing - just the probability that its the right thing would be much higher.

**Comment by CyrusNajmabadi** [comment]
Tom, as mentioned before, the goal was to make a completely consistent API without the need for consumers to understand when and how the API would actually "be smart" in ways that might not be expected or desired.   

I've worked with APIs like this for 15+ years, and i can tell you i vastly prefer an API that works the same way 100% of the time and doesn't have these types of corner cases.

> The problem here is not when the WithXXX replaces existing values with other values - then it's working fine - but when there are no values and the WithXXX generates the first one.

I'm still not seeing the problem.  If there are multiple attributes already, then the code example i specified will get the comments off the start of the node and will attach them to the attributes you are adding.  If there are no values, then the code example works the same way.  It will grab the comments from the start of the node and attach them to the attributes you are adding.

In either case, the comments that were at teh start of the node will stay at the start of the node.  Another way you could write this would be:

```var newProp = oldProp.WithoutLeadingTrivia().WithAttributes(newAttributes).WithLeadingTrivia(oldProp.GetLeadingTrivia()))```

Here, the intent is clear, you're removing the initial trivia, adding in the attribute, then adding back the initial trivia.  That will ensure that the attributes get added in between the trivia and the node.

**Comment by CyrusNajmabadi** [comment]
> just the probability that its the right thing would be much higher.

I'd like an API that works consistently 100% of the time versus one that behaves inconsistently but which may be better for some consumers some of the time :)

**Comment by tom-englert** [comment]
I get the feeling that you have never tried to use your on code.

Using the workaround like you recommend (`var newProp = oldProp.WithoutLeadingTrivia().WithAttributes(newAttributes).WithLeadingTrivia(oldProp.GetLeadingTrivia()))`) will get totally inconsitent results, depending on what the type of trivia was (white space only or white space and comments)

Since the WithXXX methods are trying to be smart about the indent of the parts they are adding, removing the trivia will confuse it, and the result with or without this workaround is totally different, if the trivia is only whitespace. 

So I wonder what you mean by "the API works consistently 100% of the times" - do you mean it's OK to generate garbage, if it's guaranteed that the same garbage is generated every time, is that what you call consistent?

**Comment by CyrusNajmabadi** [comment]
> I get the feeling that you have never tried to use your on code.

I've used the API extensively and I own a huge amount of IDE features that leverage this code and heavily use the 'WithXXX' methods :)

> Since the WithXXX methods are trying to be smart about the indent of the parts they are adding, 

The WithXXX methods do *not* try to be smart.  They do precisely what you asked.  They leave control of trivia in your hands.

> So I wonder what you mean by "the API works consistently 100% of the times" - do you mean it's OK to generate garbage, if it's guaranteed that the same garbage is generated every time, is that what you call consistent?

Actually, yes.  THat's how i would describe it.  It means that i know *every time* what the WithXXX methods will do.  And it means i know *every time* what things i may need to take care of.  Again, i'd rather have that then have an inconsistent API that behaved differently in lots of circumstances that i would then have to go internalize.  As mentioned before, this comes from ~15 years of experience here, and having first hand usage of APIs that operate in the manner you mentioned.  They turned out to actually be extremely hard to use, and it was very hard to maintain them as it was never clear what subtle behaviors people might be depending on.

These APIs are extremely simple and are the building blocks for you to layer on additional smarts.  

Cheers!
