### ISSUE TITLE
Compiler generates an infinite loop with finally block 

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#15297]
The problem is described in detail in the following Stackoverflow question:

> http://stackoverflow.com/questions/40182734/compiler-generates-infinite-loop-after-finally-block-when#

It looks like there is an issue in our dead code analysis in finally blocks.

**Comment by AdamSpeight2008** [comment]
I remember an issue like this popping up before. Is it the same source?

**Comment by roterdam** [comment]
can you describe what the impact of this is? I read it but I don't quite understand what is happening here that it is a bug.

**Comment by Belorus** [comment]
It doesn't look like a bug. It is a bit contr-intuive but this doesn't introduce any unexpected behavior in compiled code.

**Comment by svick** [comment]
@Belorus It seems @VSadov agrees with you. From [this answer on the SO question](http://stackoverflow.com/a/40644645/41071):

> This is by design. As long as you cannot reach that infinite loop :-)

> When "finally" does not terminate (contains a throw or an infinite loop), the code after the try statement becomes unreachable form the language prospective. Since it is unreachable, it is allowed to have no code there whatsoever, even if, for example, the method needs to return a value.
In fact, because various invariants, which typically hold in normal code are not enforced in unreachable code, compiler defensively removes code that is unreachable even if it is present. This is not just an optimization, it is often required for correctness. Instead of preventing/detecting/fixing violations in unreachable code it is cleaner to just remove it.

> Now, IL specification requires that the "leave" opcode points to a valid target instruction. In particular it does not care whether the branch is blocked by a nonterminating finally. But we do not have any valid code to point to, so we need to inject a "landing" piece of code. It must be small. We also know that it would not be ever reachable, but it also must not endanger already established static correctness of the method.

> An infinite loop is a smallest piece of code like that.
> BTW, another possibility could be "throw null", but historically an infinite loop is used.

**Comment by jaredpar** [comment]
Closing as per discussion.
