### ISSUE TITLE
Internal helpers in ISymbolExtensions (and other internal functionality)

### ISSUE THREAD

**Issue by daveaglick** [dotnet/roslyn#15462]
There's a ton of really great functionality locked away as internal inside the [Workspaces Shared folders](https://github.com/dotnet/roslyn/tree/master/src/Workspaces/Core/Portable/Shared) (and particularly in the [Extensions folder](https://github.com/dotnet/roslyn/tree/master/src/Workspaces/Core/Portable/Shared/Extensions)). I've occasionally needed access to various functionality in these classes and have either copied them out or used [ReflectionMagic](https://github.com/davidebbo/ReflectionMagic), and have even seen an interesting proxy concept using an assembly with the same name as one of the registered `InternalsVisibleTo`.

None of the approaches above are ideal. For example, I recently needed to get a set of all accessible members from a type hierarchy. There's a wonderful `GetAccessibleMembersInThisAndBaseTypes()` extension, but copying that one out requires a rabbit hole of supporting code.

Are there plans to periodically review some of this helper code that's currently marked as internal for greater accessibility? Is there a recommended approach to consuming it externally when needed? Are there reasons why we shouldn't be consuming it?

**Comment by Pilchie** [comment]
Our general thoughts are:
1. Not to expose things that are just an obvious combination of primitives, because:
a. The API surface is already huge.
b. Doing so causes people to wonder what *else* it does, apart from the simple combination of primitives.
2. Not to pro-actively expose much, since once we commit to a public API it can't be changed and incurs a significant cost.

However, we're open to considering individual APIs that there is a proven need for.

Giving to @mattwar to consider for the specific question of `GetAccessibleMembersInThisAndBaseTypes()`

**Comment by daveaglick** [comment]
That makes sense, thanks.

I'll sit tight and see what you think about opening up that specific method. When I attempted to copy it and replicate what it's doing in my own code it cascaded into a huge spaghetti mess, so it might be a good candidate.

**Comment by tmat** [comment]
A good approach could be to keep these internal but factor them to standalone shared projects. These can then be packaged up as source packages. We already do so for a [pooled objects](https://github.com/dotnet/roslyn/tree/master/src/Dependencies/PooledObjects) and [debugging helpers](https://github.com/dotnet/roslyn/tree/master/src/Dependencies/CodeAnalysis.Debugging).

The code in these packages can change in any way. Consumers of these packages can stay on their fixed version that works for them, or update and deal with breaking changes. Either way the choice is on the consumer side.

**Comment by Pilchie** [comment]
That only works if the helpers contain every internal access and only reference public APIs of Roslyn itself (which would of course be necessary for source packages, since we couldn't give IVT access to every consumer of the source package).  Otherwise they are a versioning problem since any change to an internal API that is consumed by helper packages would break existing applications using the helper packages.

@harrisse in general - if there are *specific* things you use that contain logic (aren't just forwarding conveniences) and you can describe why you need it, we should discuss making them public.  We're not against doing it for individual, provably useful cases, just against a blanket switch to make things public.

**Comment by tmat** [comment]
> only reference public APIs of Roslyn itself

That's correct. But if they can't be implemented via public APIs then we are missing some primitives. I meant this approach would be viable for those helpers that compose existing, more primitive public APIs.

**Comment by CyrusNajmabadi** [comment]
This is now possible.  We've effectively been more and more code to our shared libraries.  These shared libraries are compilable without any references to internal data.  We use this specifically so that we can share this code in `Microsoft.CodeAnalysis.CodeStyle` and `Microsoft.CodeAnalysis.CodeStyle.Fixes`.

Customers are welcome to use these shared projects.  However, they must be aware that this is not a public API guarantee and that this code can and will change at any moment.

**Comment by tmat** [comment]
@CyrusNajmabadi I wouldn't consider it ready to use yet. We would want to create source packages to make it easy to consume.
