### ISSUE TITLE
Invalid keyword recommender tests after #15049

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#15523]
We are preparing in #15049 for the ability to declare variables in a deconstruction in an expression. As a consequence, in the future you would be able to write

```cs
var q = (int a, int b) = e;
```

Note that this is not a lambda expression, but a deconstruction assignment in the initializer of q. So inside the parens, neither `ref` nor `out` would be permitted.

Since the parser is changing to support this, two existing keyword recommender tests are invalidated by this: `RefKeywordRecommenderTests.TestInLambdaDeclaration3` and `OutKeywordRecommenderTests.TestInLambdaDeclaration3`. I am marking them skipped with this issue until we can decide what to do about them.

**Comment by CyrusNajmabadi** [comment]
> So inside the parens, neither ref nor out would be permitted.

Intuitively, IntelliSense takes a "left valid" view of the world.  in other words, it makes its decisions based on the code that has come before (and is therefore more 'complete') and ignored what comes after (as that is being changes/written).  

In a case like this, ref/out *shoud* be recommended, because when you have something like:

```var q = (int a, $$``` then you could definitely be in the middle of writing a lambda.  We shouldn't take the code to the right to make an errant determination here.

--

Note: Making htis work should be very trivial.  All logic for this sort of thing will be in the RefKeywordRecommender and OutKeywordRecommender.  Updating them accordingly should be easy.

**Comment by gafter** [comment]
OK, I'll fix the recommender and make the test work rather than skipping the test.

**Comment by CyrusNajmabadi** [comment]
Thanks!
