### ISSUE TITLE
Add IsPrimitive property to the ITypeSymbol interface

### ISSUE THREAD

**Issue by denis-tsv** [dotnet/roslyn#1567]
Please add IsPrimitive property to the ITypeSymbol interface. It can be useful for checking primitivity of type.

bool IsPrimitive { get; }

**Comment by essoperagma** [comment]
I hope this gets some attention. Now that we can write our source generators, it will be even more useful.

**Comment by CyrusNajmabadi** [comment]
@essoperagma what would you use this for?  What would be the semantics of this operation?

**Comment by essoperagma** [comment]
I'm using SG to serialize some data into a buffer. If the type allows and no encoding is needed, the source generator simply produces the following code:
```
*(<type>*)(_pointer + offset) = value;
```

This only works on integral numeric types and I though this is what `IsPrimitive` would tell me. After my inital comment, however, I realized that `object` and `string` are also primitives and `IsPrimitive` isn't exactly what I need. What I need is something like `IsIntegralNumeric`. Do we have an alternative to `IsIntegralNumeric` today?

Even though it isn't what I need exactly, having `IsPrimitive` still helps my case since I can do this:
```
if (type.IsPrimitive && !type.SpecialType == SpecialType.System_Object && !type.SpecialType == SpecialType.System_String)
```

**Comment by CyrusNajmabadi** [comment]
> Even though it isn't what I need exactly, having IsPrimitive still helps my case since I can do this:

It would depend on what IsPrimitive returned true for. For example, Dates are primitive in vb.  

Is there a reason you can't just write an extension here that checks for the exact types you support?

**Comment by essoperagma** [comment]
Nope. In fact, I ended up copying and turning this into an extension method:
https://github.com/dotnet/roslyn/blob/d056cbe4bc221dea3b76272acb7d5129bac912f9/src/Compilers/Core/Portable/Symbols/TypedConstant.cs#L160-L168

This isn't a blocker. It would just be simpler and other people who need this wouldn't need to look for an alternative.

**Comment by CyrusNajmabadi** [comment]
> Nope. In fact, I ended up copying and turning this into an extension method:

Note that those aren't integral numerics :)  'boolean' for example would not match.  So i think it would be very much in the air how people would expect tehse to all react.

**Comment by essoperagma** [comment]
Oh, I didn't realize this was a valid statement:
```
*(bool*)_pointer = true;
```
In that case yes, knowing if something is integral numeric isn't going to help :/

**Comment by CyrusNajmabadi** [comment]
You want:

```
        /// <summary>
        /// True if the type is unmanaged according to language rules. False if managed or if the language
        /// has no concept of unmanaged types.
        /// </summary>
        bool IsUnmanagedType { get; }
```

This property already exists :)
