### ISSUE TITLE
Parent and LINQ variable scope conflicting

### ISSUE THREAD

**Issue by AbubakerB** [dotnet/roslyn#1569]
Consider the follow snippet:
---

```C#
using System.Linq;
					
public class Program
{
	public static void Main()
	{		
		var aRandomList = Enumerable.Repeat<string>("don't repeat me!", 100);
		aRandomList.Select(a => a).Where(a => a == "sorry, i had to");
		
		var a = 0;
	}
}
```

In Visual Studio 2013.4 i get an error on the following line
```C#
var a = 0; // ERROR: A local variable named 'a' cannot be declared in this scope because it would give a different meaning to 'a', which is already used in a 'child' scope to denote something else
```

Running this code on VS2015 Preview (and also https://dotnetfiddle.net/ [using the roslyn 1.0.0-rc1 and .NET 4.5 Compilers]) gives me an error on the following line
```C#
aRandomList.Select(a => a).Where(a => a == "itself"); // ERROR (x2): A local or parameter named 'a' cannot be declared in this scope because that name is used in an enclosing local scope to define a local or parameter
```

Question
---

Should this be throwing an error?

I understand that if ```var a = 0; ``` was defined before the LINQ statement, then ```a``` in the LINQ scope would conflict with the parent scope, but if its defined afterwards, it seems like it should be valid (in my opinion).

Moreover, ```a``` isn't even defined or accessible in the functions context (after the LINQ statement - ask intellisense!). So it makes sense for ```var a = 0;``` to be valid.

**Comment by HaloFour** [comment]
The compiler is applying the same lexical scoping rules that it does for any other construct.  The following is similarly illegal:

```cs
if (foo == bar) {
    int baz = foo;
    // do something with baz here
}
int baz = bar;
// do something with baz here
```

**Comment by VSadov** [comment]
That is correct. Variable visibility does not vary within a given lexical scope. The actual location of declaration is irrelevant - as long as a variable is declared in a given scope it is visible throughout the scope.
As a result a variable in an outer scope will conflict with a variable in an inner scope regardless of the order of declaration.

**Comment by AbubakerB** [comment]
Interesting! 
> The actual location of declaration is irrelevant - as long as a variable is declared in a given scope it is visible throughout the scope.

Out of curiosity, can i ask why it was designed like that?

**Comment by svick** [comment]
@AbubakerB Eric Lippert has a nice explanation here: [*Simple names are not so simple, part one*](http://ericlippert.com/2009/11/02/simple-names-are-not-so-simple/).

In short, it's to prevent you from writing confusing code (where `a` would mean both `this.a` and the local `a` in the same scope) and to make sure refactoring (moving the declaration of the local) doesn't change the meaning of your code.

**Comment by VSadov** [comment]
Note that the rule 4 in the Eric's blog (single meaning) has been relaxed in Roslyn. Violations of the rule were extremely rare in real code and were fairly puzzling to the user when they happened. It also required significant machinery on the compiler side to implement this rule. In addition it was found to be hard to generalize for some of the prospective features like declaration expressions or pattern matching. And on top of that the old compiler did not follow the rules precisely forcing a choice between spec-correctness and backwards compatibility.
At some point it was decided that the rule was just not worth the trouble.

All other rules still remain.

IMO the main reason for the rule 3 is simplicity. It basically says that you can only ask "what is visible in this scope" and not "what is visible at this position". As a result, in general case, reasoning about visibility can be more abstract since you do not need to consider locations. That makes code easier to analyze/read/compile.

**Comment by AbubakerB** [comment]
I see, i get your reasons. Thanks for the explanation and link.
