### ISSUE TITLE
EditorConfig code style/formatting options with "dotnet" prefix are somewhat language agnostic

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#15785]
@CyrusNajmabadi brought up a good point that all of our options with the "dotnet" prefix can also apply to TypeScript, for example. 

To make these options available to other Microsoft languages, let's rename them to instead start with the "ms" prefix...or something along those lines.

**Comment by kuhlenh** [comment]
FYI @jmarolf

**Comment by Pilchie** [comment]
And Java or any curly-brace language...

**Comment by jmarolf** [comment]
If C++ and typescript and a bunch of curly branch languages add this we may change the name.  The plan has always been that we would work with the editorconfig folks if certain options became popular.  I don't really see a good way of future proofing the name.  What if you use MS but then a non-microsoft language adopts these settings?  `dotnet` isn't all that great because there are a lot more .NET languages than just C# and VB, but I can't think of anything that would be better.

**Comment by Pilchie** [comment]
Also, do we think that people will want to have different values for different languages?

For example, braces on the same line is quite common in Java, but not in C#...

**Comment by Pilchie** [comment]
Let's close this for now, but we can revisit as more language start adopting editorconfig...

**Comment by jmarolf** [comment]
> Also, do we think that people will want to have different values for different languages?

They can just filter by file extension is they need different settings for different languages.
```
[*.cs]
setting = true

[*.ts]
setting = false
```

**Comment by Pilchie** [comment]
Ah, right.  Ignore that then.
