### ISSUE TITLE
Proposal: Allow block-statements with return values everywhere an expression is expected

### ISSUE THREAD

**Issue by YaakovDavis** [dotnet/roslyn#15821]
I propose to allow the following syntax:  

`var x = {var foo = Foo(); return foo * 3;};`

As another example, in ternary operators, this will look like:
`var x = condition ? {var foo = Bar(); return foo + 1;} : 2;`

Such a syntax increases the composability of the language, allowing one to express logic using a natural flow, while also limiting the scope of local intermediary variables.  
F# has a similar syntax, allowing to define arbitrarily nested expressions.

**Comment by orthoxerox** [comment]
#6182

**Comment by qrli** [comment]
also related to #15651

**Comment by binki** [comment]
I think seeing `return` inside of a straight up block would be confusing with existing syntax. This code is valid syntax currently and causes a return from `MyMethod`:

```csharp
static int MyMethod()
{
    var x = 2;
    {
        return x + 4;
    }
    // unreachable.
}
```

With this proposed syntax, you could do:

```csharp
static in MyMethod()
{
    var x = 2;
    var y = {
        return x + 4;
    };
    // Suddenly this is reachable.
    return y;
}
```

In quickly visually scanning a method, it seems like the `return` in a “returnable block” is not visually distinguishable from a `return` in a nested block which causes the outer function to return. This issue is [described here too](https://github.com/dotnet/csharplang/issues/377#issuecomment-291957292).

**Comment by YaakovDavis** [comment]
@binki 

To me, the 2 snippets look visually distinct.
In any case, it has been proposed [elsewhere](https://github.com/dotnet/csharplang/issues/249#issuecomment-287038656) to use the following syntax:
```
var y = ({
   return 4;
});
```

**Comment by CyrusNajmabadi** [comment]
Closing this out.  We're doing all language design now at dotnet/csharplang.  If you're still interested in this idea let us know and we can migrate this over to a discussion in that repo.  Thanks!
