### ISSUE TITLE
Performing a Find All References before another has finished, doesn't cancel existing search

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#15832]
1. Clone this repo to this commit: https://github.com/dotnet/roslyn-project-system/commit/e8f444a1ebe3d78b6b494d5dc355e95b7da19086
2. From a VS command prompt, run build.cmd from the root
3. Open src\ProjectSystem.sln (build 26005.0 D15PreRel)
4. Open src\Microsoft.VisualStudio.ProjectSystem.Managed\Threading\Tasks\TaskResult.cs
5. Right-click on TaskResult and choose Find All References
6. Right-click on TaskResult and choose Find All References
7. Right-click on TaskResult and choose Find All References

Notice that the progress bar completes to 100% 3 times and takes 3 times as long as a single search.

**Comment by CyrusNajmabadi** [comment]
Hrmm.  According to the docs the editor should be unsubscribing from the table source.  However, looking through their code, i can't see where they would do that.  So it might be right for us to preemptively remove those sources.

I'm guessing this regressed when the editor added multi-instancing to find-refs.  They probably didn't want to cancel the existing work if the user locked the current window and a new window was being created.  However, when that's not hte user flow we should def be cancelling.  Will talk to Daofa about this.

**Comment by CyrusNajmabadi** [comment]
I debugged through this and talked to Daofo.  The actual issue is that the progress bar is not implemented well on their side.

Each time we call ReportProgress, they enqueue a UI request to update the progress bar.  If we search N files, we'll report progress N times.  Just processing all those messages takes forever, and also interferes when a new search starts. 

FindRefs window needs to use a better approach for aggregating and reporting progress results that is not a 1:1 processing of each REportProgress call on the UI thread.

**Comment by CyrusNajmabadi** [comment]
https://devdiv.visualstudio.com/DevDiv/_workitems?id=359162&fullScreen=false&_a=edit

Opened to track this.

**Comment by natidea** [comment]
Mitigated with https://github.com/dotnet/roslyn/pull/15873
