### ISSUE TITLE
Proposal: Name aliases for members of generic types

### ISSUE THREAD

**Issue by vbcodec** [dotnet/roslyn#15847]
This will allow to use more suitable member's names in language.

```
Public Class C1 (Of T1)
<MemberAliasOrder(1)> Public Item1 As T1
<MemberAliasOrder(2)> Public Item2 As T1
End Class

Public Delegate Function GenDel(Of T1)(<MemberAlias()> ByVal Item1 As T1)

' Initialization

Dim proc As GenDel(Of Boolean) Alias (NewMane)

Dim inst = New C1 (Of String) Alias (S1, S2) ()
inst.S1 = "To Item1"

proc(NewName:=True) 
```

Aliases exist only at language level, and won't be included into generated code.

**Comment by HaloFour** [comment]
Why would you want to do this?  When would you be defining some new type like this just to have its members renamed by some consumer?  What problems would this solve not already handled by tuples or anonymous types?

**Comment by vbcodec** [comment]
@HaloFour 
Tuples are limited, and anonymous methods are closed inside function. 
But what I really mean, was generic delegates, to get better names where necessary. Updated proposal for this case.

**Comment by HaloFour** [comment]
@vbcodec 

Where is that ever necessary?  Especially since your proposal still relies on someone writing new custom annotated delegates.  And even then the only time the parameter names are relevant is in the case of invoking that delegate directly while reordering or omitting arguments, which is exceptionally rare to the degree that you could probably scour all C# and VB.NET projects on github and never see it once.

You can already solve this "problem" by writing your methods to accept custom delegates that have better named parameters.

**Comment by vbcodec** [comment]
@HaloFour 
>still relies on someone writing new custom annotated delegates

But they are defined only once. 

New names also provide better intelisense than `argx` with current `Funct` and `Action` delegates. Unfortunatelly it is impossible to show intelisense here.

I want to use generic delegates also to events, to avoid create plethora custom delegates. But existing `Action`delegates have fixed unfriendly names. Could be even better, if editor generate event handler with new names than `argx`.

**Comment by HaloFour** [comment]
@vbcodec 

VB.NET already has a simplified syntax for defining events with custom signatures.  I see no need for yet another syntax.

Not to mention the recommended convention for .NET events have exactly two arguments, `sender` and `args`.  This proposal would only ever serve deviating from those guidelines.

**Comment by jnm2** [comment]
The only time I've wished for something like this was where I was extending a generic base collection class with a closed `T` and adding a second `Add` method where there was a better name for the `T` parameter than `item`, and being unhappy with the inconsistency with the existing `Add`(T item)` param name.

**Comment by HaloFour** [comment]
@jnm2 

Could always fix that by shadowing that member:

```cs
public abstract class CollectionBase<T> {
    public void Add(T item) { ... }
}

public class FooCollection : CollectionBase<Foo> {
    public new void Add(Foo foo) => base.Add(foo);
}
```

Any code consuming `FooCollection` would see the parameter `foo` rather than `item`.  Although any code consuming the base type would still see the parameter `item`.

In either case I'm not sure how the above would resolve such a situation.  The aliases seem to exist at the point of instantiation and there's no mention of how the aliases would be used in normal declarations or how they might flow.  You'd probably be required to declare the aliases everywhere you intended to consume the type, as you will with tuples.

**Comment by CyrusNajmabadi** [comment]
Closing this out.  We're doing all language design now at dotnet/csharplang.  If you're still interested in this idea let us know and we can migrate this over to a discussion in that repo.  Thanks!
