### ISSUE TITLE
Wrong IntelliSense list in nested With statement

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#15878]
Description: Consider typing this code sequentially. Cursor position is marked by pipe character |. One "End With" is missing, because current With statement has not been completed yet. 
Typing the last dot (before cursor |) will offer IntelliSense list of Point data type. 
It should provide IntelliSense list of Button datatype. 

Dim B As New Button 
With B 
With .PointToScreen(.|) 

End With 

Compilation works fine. Problem is only with IntelliSense that is providing PointToScreen result type instead of current With statemetn type (Button). 

Repro Steps:Just type this code: 

Dim B As New Button 
With B 
With .PointToScreen(.|) 

End With 

Impact:Correct IntelliSense list is missing.

**Comment by gafter** [comment]
I suspect this is caused by the behavior of the compiler APIs. We should investigate from the compiler side first.

**Comment by CyrusNajmabadi** [comment]
Likely a bug in: MemberAccessExpressionSyntaxExtensions.GetExpressionOfMemberAccessExpression.

**Comment by CyrusNajmabadi** [comment]
Hey Ravi, can you look if this is a bug in our extension method?  i.e. are we finding the wrong "implicif expression" that is being dotted off of?  If so, this is our bug.  Otherwise, if we have the right 'implicit expression', then this should go back to the compiler with some detailed info as to what incorrect information is being returned.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback from customers that this is an issue.
