### ISSUE TITLE
Live Unit Tests adds a menu at the top of an unloaded project, killing my muscle memory

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#15882]
Live Unit Tests adds the following to the top of an unloaded project:

![image](https://cloud.githubusercontent.com/assets/1103906/21164677/c5e34fc8-c1ee-11e6-9c8d-a2f78a8798ff.png)

This is killing my muscle memory, as "Reload project" is the most common thing I want to do with a unloaded project. Can we please move this menu item?

**Comment by CyrusNajmabadi** [comment]
Why are 'live tests' even offered on an unloaded project?

**Comment by tmat** [comment]
If you tell me how to check for unloaded project I'll be happy to do that :)

**Comment by davkean** [comment]
Why is important that this menu item is on the context menu? Context menu is for repeatable actions - I'm going to do this once, and never do it again right?

**Comment by tmat** [comment]
@davkean I don't follow. By the same logic Reload Project should also not be on the context menu since you do it once. 

You can add/remove tests in selected project from the context menu any time you want, depending on what code you're working on at the time. For example, if I'm working in Roslyn solution on a compiler feature I'd just want to run compiler tests, not IDE tests. I'd select compiler test projects from the context menu for that particular work.

**Comment by tmat** [comment]
BTW, TestDriven.NET has the similar context menu items.

**Comment by davkean** [comment]
You continually use Unload/Reload for loaded/unloaded projects. 

If it's only for tests, why does it show up for non-test containing projects? Why does it show up if I'm not using Live Unit Testing?

**Comment by tmat** [comment]
https://github.com/dotnet/testimpact/issues/1119

**Comment by Pilchie** [comment]
Tracked at dotnet/testimpact#1119.
