### ISSUE TITLE
var preferred over interface (inline an out variable)

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#15985]
**Version Used**: 2.0.0.61205

**Steps to Reproduce**:
```C#
class Program
{
    static void Main(string[] args)
    {
        IFace f;
        Test(out f);
    }

    interface IFace { }
    static void Test(out IFace f) { f = null; }
}
```

**Expected Behavior**: Quick fix to inline f into `Test(out IFace f)`.

**Actual Behavior**:
1. Quick fix to inline f into `Test(out var f)`.
2. No change to explicit type offered on `Test(out var f)`.
    Neither for built-in types i.e. `int.TryParse("4", out var i);`

**Comment by bbarry** [comment]
Perhaps there is or should be a setting involved here (`Naming rules - 'var' preferences - elsewhere`, or should there be something more specific). I prefer the actual behavior here (and think it should be default).

**Comment by CyrusNajmabadi** [comment]
So, i see:

![image](https://cloud.githubusercontent.com/assets/4564579/21297463/dd67d43a-c535-11e6-9f60-62db3b2d73a8.png)

Because my option is:

![image](https://cloud.githubusercontent.com/assets/4564579/21297466/eea6411e-c535-11e6-9a82-78271f94606b.png)

If i change to:

![image](https://cloud.githubusercontent.com/assets/4564579/21297470/f892703a-c535-11e6-83dd-8ca2af435af7.png)

Then i get:

![image](https://cloud.githubusercontent.com/assets/4564579/21297476/01c8dfb8-c536-11e6-80cd-563207d8573a.png)

**Comment by CyrusNajmabadi** [comment]
Fixed with: https://github.com/dotnet/roslyn/pull/15306

I believe the current behavior (which i showed an image of) is correct and desirable.  Please reactivate if you feel otherwise.  Thanks!

**Comment by miloush** [comment]
@CyrusNajmabadi That is indeed desirable, but not what I am seeing. Is this fix meant to be in RC2?

**Comment by CyrusNajmabadi** [comment]
It went into Master.  Which i believe is RC.3.

**Comment by miloush** [comment]
Thanks, sorted then.
