### ISSUE TITLE
Ruleset changes don't cause error list to change unless I save the file

### ISSUE THREAD

**Issue by shyamnamboodiripad** [dotnet/roslyn#1599]
This is a minor issue and it is probably ok not to fix this.

I noticed that if I make changes to rule severities in the rule set editor, the severity changes are not reflected in the error list as soon as I make the changes. I have to save the file in order for the changes to be reflected.

Changes in other project properties are applied instantaneously without having to save. For instance, checking "Treat all warnings as errors" the project properties pane instantly updates the warnings in the error list to errors without having to save the project.

**Comment by srivatsn** [comment]
This may or may not be desirable behavior because you may treat ruleset editor as entering a batch mode of changing a bunch of options instead of a single one (for which soln explorer exists). Also this is fairly complicated to implement with the current setup. Given this wouldn't happen too often it's not worth the effort. Won't fixing the issue.
