### ISSUE TITLE
"Open Files" analysis doesn't occur on files that were opened from a previous solution session

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#16026]
1. Create a project
2. Create two files containing a violation on something that only occurs in open files (for example, interfaces must start with I
3. Open both files

-- Note that you see both errors in the error list --

4. File -> Close Solution
5. Open the solution you just closed

Expected: For both errors to appear in the error list
Actual: Only error from the file that current the selected tab is in the error list

Very confusing - especially when I was using the "Open Documents" filter.

**Comment by heejaechang** [comment]
this is happening because files are not considered as opened until it gets first focus. so for workspace, those files are not considered as open. and it looks like workspace think that way since shell doesn't raise events for those files.

not sure what would be right approach for this issue.

tagging @jasonmalinowski @Pilchie @davkean

**Comment by heejaechang** [comment]
is this some optimization platform team did to make perf better on solution open? so that things doesn't get initialized until it gets first focus?

**Comment by heejaechang** [comment]
@lineralpha is this something editor team did to make solution open perf better? by the way, what is david pugh's alias in github?

**Comment by Pilchie** [comment]
Yes - this is an optimization added in VS2013 "Lazy tabs".  There are now document flags where "RDTA_DocumentInitialized" isn't set. (See [here](http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices/Implementation/ProjectSystem/DocumentProvider.cs,520) where we handle initialized, instead of opened.

**Comment by heejaechang** [comment]
@Pilchie I am not 100% sure how things are supposed to work together but I see file that exist in tab but didnt have focus never get called for OnAfterAttributeChangeEx

so at the end, what should happen? should workspace's GetOpenDocumentIds return all documentId even if its document is not initialized?

currently, I see that everything happens once the file has first focus. is this behavior a bug?

**Comment by heejaechang** [comment]
@Pilchie @jasonmalinowski @srivatsn @davkean  ping? should I give this bug to IDE team? otherwise, please let me know what experience we want.

..

if we somehow make those files opened, will it defeat the effort of lazy tab? since we get buffer for the open document from editor, I guess we need to somehow force the tab to be initialized.

otherwise, we need to add new concept in workspace where open files buffer is not backed from editor's buffer.

**Comment by heejaechang** [comment]
gave the bug to @dotnet/roslyn-ide

**Comment by Pilchie** [comment]
Clearing milestone for triage.

**Comment by Pilchie** [comment]
I'm not sure what to do about this either :(

**Comment by CyrusNajmabadi** [comment]
I don't repro this.
