### ISSUE TITLE
Extensions won't install in RoslynDev 

### ISSUE THREAD

**Issue by lachbaer** [dotnet/roslyn#16031]
On the current master branch I can compile the whole solution, but the VSIX of VisualStudioSetup or CompilerExtensions do not install in the RoslynDev hive. No errors, soever.

Nuget packages all seem to be current. RC Insider VSIX is installed. I'm on VS 2015 Community (14.0) and Win7 Home (x64).

Are there any more requisites different from what there was in September 2016?

PS: Just saw #16016 from 14 hours ago. Bit late, I've been trying for already the last 30 hours ;-)

**Comment by lachbaer** [comment]
The main problem seems to be that all projects reference the VSSDK 15 build tools, though they cannot work as e.g. Microsoft.VisualStudio.Settings.15.0.dll does not exist on the machine.
Also "Deploy VSIX content to experimental instance for debugging" isn't anymore checked on any VSIX project.

**Comment by jaredpar** [comment]
This behavior is "By Design" now.  Our code base has shifted over to targeting VS 2017 now.  Changes to the underlying VSIX format and capabilities mean that our extensions can no longer install in VS 2015. 

If you need to continue developing in VS 2015 sync back to the dev15-rc branch.  That will still be installable.
