### ISSUE TITLE
A tooltip bug or just a decision?

### ISSUE THREAD

**Issue by eyalsk** [dotnet/roslyn#16100]
**Version Used**: Visual Studio 15

In the following code:
```
console.Use(next => context => {
	context.Write('s');
	context.Write('s');
	context.Write('s');
	context.Delete();

	next(context);
});
```
The method `Write` is implemented whereas `Delete` isn't so I get two errors.

1. Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1662	Cannot convert lambda expression to intended delegate type because some of the return types in the block are not implicitly convertible to the delegate return type	Gogo	D:\Projects\Gogo\src\Gogo\Program.cs	13	Active

2. Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'ConsoleContext' does not contain a definition for 'Delete' and no extension method 'Delete' accepting a first argument of type 'ConsoleContext' could be found (are you missing a using directive or an assembly reference?)	Gogo	D:\Projects\Gogo\src\Gogo\Program.cs	17	Active

Now, when I hover over the `Write` methods the tooltip shows only the first error and only when I hover the `Delete` method it shows both but the quick action to generate the method showing up regardless to the position of the cursor as long as it's inside the red squiggles area.

I don't know but it _seems_ like the tooltip shows errors that are relevant to a specific context but in addition it might make sense to show/include the last error everywhere regardless to context.

**Comment by Pilchie** [comment]
In general, the tooltip only shows the error if you are over the squiggled area.  It's hard to tell in this case because there are two overlapping squiggles though.  We wouldn't expand the squiggle for the Delete error because:

1. The rest of the block has nothing to do with it.
2. Having giant sections of the code squiggled is generally not very useful.

**Comment by eyalsk** [comment]
@Pilchie It's pretty odd but what you're saying is actually the complete opposite! 

> The rest of the block has nothing to do with it.

I actually get the error **because** the `Delete` method doesn't exist, removing the call to the Delete method fixes both of these issues!

> Having giant sections of the code squiggled is generally not very useful.

But that's what I'm getting _a giant section of code squiggle_ instead of getting a single a squiggle underneath the `Delete` method which again is the result of both errors.

_p.s. Something looks off here and from what you're saying it seems more like a bug to me._

**Comment by Pilchie** [comment]
Right, there are two errors, where one is caused by the other.

1. Type inference failure because the lambda type can't be inferred, because
2. The lambda contains an error - the missing Delete()

The giant squiggle is for 1.  If we were to change anything here, I would want it to be to get the compiler to *reduce* the span of the error for 1, not increase the span of the error for 2.

@gafter / @CyrusNajmabadi is this fallout from the change to more aggressively report the underlying errors in lambda type inference failures?

**Comment by eyalsk** [comment]
@Pilchie Okay, this makes more sense now, thank you.
