### ISSUE TITLE
Block scenario for accessing member of tuple returned from deconstruction

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#16127]
In C#7.0, you could write `var p = ((var x, var y) = M()).Property;` by implementing your own `ValueTuple'2`.
In the future, we may decide that the return type of a deconstruction is a tuple with names (instead of a tuple without names) where the names are inferred.

Depending on the rules for inferring such names, we could break existing code.

FYI @gafter @VSadov @AlekseyTs

**Comment by gafter** [comment]
No, you cannot write that in C# 7, because declaration expressions are not permitted to be used that way yet.

In any case, the type of an assignment expression is the type of its left-hand-side, not its right-hand-side. Since the left-hand-side has no names, the resulting tuple type is without element names. I don't imagine that changing.

**Comment by gafter** [comment]
When I say the left-hand-side is without names, I mean it is a tuple expression without the element name syntax.

**Comment by jcouv** [comment]
> declaration expressions are not permitted to be used that way yet.

Thanks. I'd lost track of this current restriction. I'll close this issue.

Regarding names, we had discussed inferring names. For instance, `(var x, var y) = M()` could return a tuple with names "x" and "y". We had also discussed an explicit alternative `(x: var x, y: var y) = M()`.
