### ISSUE TITLE
NameOf(Me) 

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#16130]
`NameOf(Me)` should evaluate to the Class / Structure / Module name, it is used in.

```VB
Module Exts
  Public Function Foo() As Object
    Debug.WriteLine(NameOf(Me)) ' output "Exs"
 End Function
End Module
```
*Advantage*
Doesn't require reflection. 
Doesn't require repetition of the TypeName

**Comment by eyalsk** [comment]
@AdamSpeight2008 What's wrong with NameOf(Exts)? or to put it otherwise what's the benefit of NameOf(Me) over NameOf(Exts)?

**Comment by jnm2** [comment]
Unless `Me` is already a legitimate substitute for `Exts` in non-NameOf situations, giving it special treatment is inconsistent.

**Comment by eyalsk** [comment]
@AdamSpeight2008 

> But why should the name be evaluated at runtime when it can gotten at compile-time?

Why should planes fly when they can move on the ground? 

You can do that today with `NameOf` the argument just can't be a _pointer_ because this is what `Me` represents, it refers to an object.

> The D.R.Y. principle. 

It's unfortunate that so many people don't get the idea behind D.R.Y, so many software development principles and practices become _anti_ just because they are abused and this is _probably_ one more case.

The D.R.Y principle doesn't say you shouldn't duplicate code as in text, instead, it states that you shouldn't represent the same piece of knowledge in the system more than once and it really, really aims to reduce maintenance time and therefor costs, many times when the principle is applied the amount of duplication at the source code level is reduced but this is just a side-effect, at least that's how I look at it.

*Read the book* The Pragmatic Programmer: Page 26. 😉 

> Why should I need to repeat the name of the class / structure / module? When it is viable to have the compile do the work for us, at the relatively minor expense of a few keystrokes.

You got intellisense and autocomplete... I'm serious.

> Think about the situation if the class / structure has long name? Or we allow generic type arguments to include? We added var to much the similar function (ie reduce repetition of typing type names.

No, `var` wasn't added to reduce repetition of typing, back then it was added _mostly_ to support anonymous types and it was probably cheap enough for them to support user-defined types.

> To me makes senses to have an "alias" to the class / structure / module 's name.

But here is the thing `Me` is not an alias it has a specific role in the language and that is to point to an instance of the type.

Based on your logic we can access `Shared` members through `Me` I mean why not?

> Produces an error 'MyClass' must be followed by '.' and an identifier., whereas using Me doesn't (except in the Module case)

`Me` should still produce an error, I'm not sure why it gives a different error for `MyClass` iirc it's _similar_ to `Me` but I rarely touch VB.NET code so dunno.

**Comment by jnm2** [comment]
Agree about DRY, good to bring that out. NameOf repeats the name by design.

MyClass is used to constrain calls so that you don't call derived virtual method implementations, same as My Base does with the base class.

**Comment by AdamSpeight2008** [comment]
@eyalsk  What about development costs?

**Comment by eyalsk** [comment]
@AdamSpeight2008 Maintenance starts after the first line of code you write so I'm not sure what do you mean by _development costs_ however I'd really want to know how this adds up to your costs?

**Comment by AdamSpeight2008** [comment]
[Ported to VBLang](https://github.com/dotnet/vblang/issues/20)
