### ISSUE TITLE
Running a long running "Fix all" results in "Microsoft Visual Studio Is Busy" notification

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#16135]
After https://github.com/dotnet/roslyn/pull/15767, when running a long running "Fix all" such as removing "Me." from the Project System, I get the following if I attempt to give VS focus:

![image](https://cloud.githubusercontent.com/assets/1103906/21535604/897d4eec-cdcb-11e6-94a4-5625a0dc81ba.png)

Is this notification expected?

**Comment by davkean** [comment]
tag @jmarolf @CyrusNajmabadi

**Comment by davkean** [comment]
Just ALT+TABing between another and VS will also result in the same "Microsoft Visual Studio is Busy" notification./

**Comment by CyrusNajmabadi** [comment]
I believe this may be by design given hte limitations of VS.  VS is effectively hung.  But we at least have a wait-dialog up so that the user can cancel whatever is going on.  VS has no mechanism to state "i will continue painting, but you cannot interact with me".  AFAIK, everyone who uses hte wait dialog uses it to get around this issue.

**Comment by davkean** [comment]
@CyrusNajmabadi The rest of VS features that I've used show this dialog (such as File -> New Project):

![image](https://cloud.githubusercontent.com/assets/1103906/21536307/4b46cd24-cdd5-11e6-9372-b58e8e968f70.png)

VS does not enter a hung state in these situations.

**Comment by CyrusNajmabadi** [comment]
Are they blocked on the UI thread?  We're literally using the VS 'show a wait dialog because hte UI is actually hung" mechanism.

**Comment by davkean** [comment]
When we're blocked on the UI thread, how are we still painting?

**Comment by davkean** [comment]
Maybe WPF's render thread?

**Comment by davkean** [comment]
In some cases, still after applying Jon's change, I don't see the ThreadAwaitDialog after I've clicked Apply in the preview window.

**Comment by davkean** [comment]
@CyrusNajmabadi Are adding suppressions a similar problem to fixing the code? When I add a  suppression I get: 

![image](https://cloud.githubusercontent.com/assets/1103906/21600773/ac64da34-d1d5-11e6-9fb3-381f256d9b2e.png).

In this case - I do get the "Not Responding" VS - but not the "Visual Studio is busy nofication"

**Comment by davkean** [comment]
I went back to VS2015, and the behaviour is such much better there:

1. I get progress, above has no progress.

2. The dialog has more information about what it's doing - the above just says "Solution"

3. I never see the "Visual Studio is busy notification"

@CyrusNajmabadi @Pilchie This seems like a huge regression, can we got back to the previous behavior?

**Comment by jmarolf** [comment]
@davkean if you go back to your update 3 machine you will see that you can also type in the editor while the codefix is applied (previously we never blocked the UI).  1 and 3 were regressed as a result of blocking.  We can either not block (not a regression I guess) or write our own wait dialog that updates itself correctly in this scenario.  2 is just a bug, we'll need to figure out at which point we stopped plumbing the correct strings through.

**Comment by davkean** [comment]
I'm not sure I understand the jump from "prevent the user from interacting with VS features" to "stop providing progress" and "make VS itself think that it's the UI is hanging"

**Comment by jmarolf** [comment]
@davkean in update 3 we don't block the UI.  We compute the fix on the background thread and show a non-modal progress dialog. This means that the UI is not blocked and progress reports go through because we don't need to wait for the UI thread pump to show progress.  As it exists today, we block the UI thread so the user cannot interact with the editor while the codefix is applied.  We rely on the UI pumping  of the threaded wait dialog to show progress and it doesn't do a great job in this context.  Creating our own modal progress dialog for this is simple enough.

**Comment by CyrusNajmabadi** [comment]
This should all be async now.
