### ISSUE TITLE
Roslyn should embed interop structs with [ComVisible(true)]

### ISSUE THREAD

**Issue by yizhang82** [dotnet/roslyn#16177]
**Version**: VS 2015 Update 3

**Steps to Reproduce**:

1. Create a ATL COM library:

```
import "oaidl.idl";
import "ocidl.idl";

[
	uuid(E9832E6C-053B-4E7B-9F94-624964D2177B),
	version(1.0),
]
library FooLib
{
	importlib("stdole2.tlb");

	 [uuid(823F7C79-0238-4830-A7F2-8610ED1B3550),
	 version(1.0)]
	 typedef struct FooStruct {

		long operand1;
		long operand2;

	} FooStruct;
	[
		uuid(C58291E0-9474-438A-97E4-F7976B919C30)		
	]
	coclass Bar
	{
		[default] interface IBar;
	};

	[
		object,
		uuid(57D5CCE9-B3E2-4884-95F8-5B268DDF3DF2),
		oleautomation,
		dual,
		nonextensible,
		pointer_default(unique)
	]
	interface IBar : IDispatch {
		[id(1)]
		HRESULT CallFoos([in] SAFEARRAY(FooStruct)* ppFoos);
	};

};
```

2. Create a C# desktop/console project, reference ATL com library (Add reference), and set Embed Interop Types = true, and make sure [ComVisible(false)] in the assemblyInfo.cs.

3. Try to call CallFoos with following code:

```
new Bar().CallFoos(new FooStruct[] {  new FooStruct() })
```

**Expected Behavior**:
Succeed

**Actual Behavior**:
Fail. CLR throws ArgumentException with HRESULT=0x80070057 (E_INVALIDARG).

**Reason**:
The underlying problem is caused by interop type embeding. When marshaling SAFEARRAY of structs, CLR needs to locate the IRecordInfo from the typelib in order to be able to correctly represent them in VARIANTs. 
Due to interop embeding, CLR is not able to correctly locate the type lib GUID (the right GUID is on the interop assembly that is not inherited into the main app, and in the case of multiple embedding interop assemblies, it simply can't), so registering the TLB actually don't work. As a result, CLR has to resort back to dynamically export a tlb on the fly to solve the issue. 
This usually works well for embedded interop classes and interfaces since they are [ComImport], but not for structs since it can't have [ComImport]. Therefore, CLR uses [ComVisible()] setting on struct to determine whether the importing is needed. If [ComVisible(false)] is set on assembly level (which is the **default**), CLR would ignore the struct and the struct would fail to be found in the exported type lib. 
If you turn off embed interop types, or change the default [ComVisible(false)] to true, you wouldn't see this issue. 
To work well with CLR, it might be reasonable to make such structs [ComVisible(true)] when embedding them.

**Comment by tcostin** [comment]
Hello, I created the [original issue](https://connect.microsoft.com/VisualStudio/feedback/details/3110071/marshalling-safearray-of-an-embedded-com-struct-fails-when-assembly-comvisible-false-is-set). I also submitted a sample project, but I don't know if anyone ever saw it. (possibly blocked by virus scanners?) At any rate, it never appeared on that page, but I can provide it upon request.

I never noticed until now that [ComImport] is limited to classes and interfaces. I would argue this no longer makes sense as of .Net 4.0, given type embedding. Granted, this is a more drastic change than having the compiler automatically set the [ComVisible(true)] attribute on embedded structs.

**Comment by yizhang82** [comment]
@tcostin hi! I did debug your sample project and discover the problem (it was more complicated than I'd assumed). I also sent your sample to Roslyn team offline (they asked for it).

**Comment by yizhang82** [comment]
@tcostin And yes, I don't see strong reason why we can't put ComImport on structs (metadata supports it - it's just a flag), but that'd be a much more broader change with significant amount of development/testing required.

**Comment by yizhang82** [comment]
@AlekseyTs That was fast! Thanks!

**Comment by AlekseyTs** [comment]
We reverted the proposed fix because it changes the output of tlbexp, which is likely to cause a build break in a project that uses the output. We should investigate if there is a non-breaking way to enable the scenario.

**Comment by AlekseyTs** [comment]
@yizhang82 Could you recommend an alternative way to enable the scenario that wouldn't affect the output of tlbexp as that is known to break existing build environments?

**Comment by tcostin** [comment]
In increasing order of complexity:

1. Change [ComImport] to work on value types (a significant change, but at a glance it shouldn't break anything to remove a type restriction from the attribute's possible targets). It also "makes sense" intuitively, since these value types really do originate from COM :)

2. If that's not possible, invent a new attribute that serves the equivalent purpose. It can probably be internal to mscorlib since only the compiler and the CLR would need to know about it.

3. If neither of the above options work, then this issue probably needs to be fixed at the CLR: when it searches for ITypeInfo for the struct, it should search the (executing?) assembly for an embedded type with a matching GUID (which is embedded at compile time), then use that type to get the ITypeInfo (think Marshal.GetITypeInfoForType() but with some way to override the missing [ComVisible(true)] attribute on the type. This option is the only one that would also work with existing compiled assemblies.

4. Apply [ComVisible(true)] and fix tlbexp so that it doesn't include these types in its output. This is possible, because the  compiler embeds the GUID of the original type library via the TypeIdentifier attribute, so it can tell these types don't originate from the current assembly (which has its own library GUID). But now this gets complicated; the tlb created 'on-the-fly' (cf. first post) would need to contain these types, but the 'regular' tlbexp output would need to exclude them.
