### ISSUE TITLE
Need a way to detect if changes made to code are ok for EnC

### ISSUE THREAD

**Issue by Przemyslaw-W** [dotnet/roslyn#1617]
Hi,

I need a way to detect if changes made to code during debugging will be ok for Edit and Continue. Is there a supported way to detect such thing?
I _think_ that it is about to detect if syntax tree contains "rude edits", but I am not sure if "rude edit" is proper term here. Can you point me how can I detect this? Is there some API available for this?
To get more context about my scenario - [here is forum post I asked few months ago](https://social.msdn.microsoft.com/Forums/vstudio/en-US/c591f090-f682-4073-a56e-9df29d480027/is-there-a-way-to-know-if-changes-applied-to-code-will-be-ok-for-edit-and-continue?forum=vsx)

**Comment by gafter** [comment]
@tmat Ideas?

**Comment by tmat** [comment]
We don't currently have a public API that you could use.

**Comment by Przemyslaw-W** [comment]
Is there anything like this built into Roslyn somewhere? I don't mind
working with private or internal API via reflection until this gets
(hopefully) sorted out.

2015-03-27 23:50 GMT+01:00 Tomáš Matoušek <notifications@github.com>:

**Comment by Przemyslaw-W** [comment]
I will happily submit a PR for this. Please point me to proper place in the code to start

**Comment by JoshVarty** [comment]
FWIW I've written a blog post that might be able to get you started. Currently I was using reflection to get access to the bits and pieces I needed: https://joshvarty.wordpress.com/2016/04/21/edit-and-continue-part-2-roslyn/

**Comment by Przemyslaw-W** [comment]
Great blog serie! I will definitely try your approach. Thank you

**Comment by CyrusNajmabadi** [comment]
This would need to go through an API proposal.  in general, the reason we don't just make things public is because it increases maintenance costs and locks down our ability to change things in teh future.  We can open things up, but we have a process that requests need to go through to make sure the appropriate people weigh in and the right API shape is determined and shipped.  Importantly, any extension points need strong evidence that they can be provided in ways that do not impact scalability, and can have good debugging/editing experiences around them.
