### ISSUE TITLE
You can either do a rename across the tree, or rename file to match type, but not both

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#16254]
1. Create a new Console Application
2. Change "class Program" -> "class Program2"
3. Drop down lightbulb and choose Rename file to "Program2.cs"
4. Navigate to "class Program2"

Expected: To be able to rename session to rename usages of "Program" to "Program2"
Actual: The lightbulb is gone and cannot fix up usages

The reverse is also true, if I rename type I cannot rename file.

**Comment by davkean** [comment]
No, I think you've misunderstood:

1. Change "class Program" -> "class Program2"
2. Drop ligthbulb and choose "Rename Program -> Program2"

My file is called "Program.cs" and I'd expect to use the codefix to change that. I can't.

**Comment by Pilchie** [comment]
You can in current d15prerel bits (haven't tried latest Roslyn yet). However, since the rename to match is a *refactoring* it doesn't preemptively show the lightbulb, you have to know to hit `Ctrl+.` or right click and choose Quick Actions and Refactorings.

(We might change this for RTW - currently trying to run an A/B experiment on always showing the lightbulb if a refactoring is available)

**Comment by davkean** [comment]
Yes, you are right CTRL+. brings up the refactoring. Okay that was a little confusing.

**Comment by Pilchie** [comment]
Yeah.  I hope we change it to always show the refactoring.  For now, it sounds like this is either a dupe of #6261 or By Design?

**Comment by davkean** [comment]
Yeah.
