### ISSUE TITLE
Promote local function to method

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#16288]
```cs
class X
{
  void F(int p)
  {
    bool M1() => p == 1;
    void M2() => p = 1;
    void M3() => F(3);
    M1();
    M2();
    M3();
  }
}
```
Apply to each local function ->
```cs
class X
{
  private static bool M1(int p) => p == 1;
  private static void M2(ref int p) => p = 1;
  private void M3() => F(3);
  void F(int p)
  {
    M1(p);
    M2(ref p);
    M3();
  }
}
```

**Comment by alrz** [comment]
By the way, this has been disabled in #16021. However, I think the need for select the whole function is not convenient. I'd rather it to show up on function name.

**Comment by agocke** [comment]
@alrz I like this idea -- but what I was actually disabling was "standard" extract method. This would be a new feature since the IDE doesn't currently understand the idea of extracting a local function as its own method (extract method only understands creating a new method and then extracting the region into it).

**Comment by CyrusNajmabadi** [comment]
@jcouv Personally, i think offering a minimal-capturing local function, vs. a maximal-capturing local function would be nice.  Of course, only one would be offered if they were the same thing.

Note: if you do a minimal-capture local function, you now need to figure out how to rename everything so that there are no conflicts in the local function and the outer scope.  That sounds very non-trivial.

**Comment by alrz** [comment]
can you please give an example for each style? The current impl just "adds" any capture as a parameter to the resultant method and updates usages.

There are difficulties in case of method group (wrap to lambda doesn't always work), making `out` parameters (e.g. capture doesn't flow in) and sibling local functions (results in invalid code).

**Comment by jcouv** [comment]
Here's an illustration:

Initial code:
```c#
void M()
{
   var x = 0;
   [| System.Console.Write(x); |]
}
```

Extract with minimal captures:
```c#
void M()
{
   var x = 0;
   local(x);

   void local(int v) // same parameters that ExtractMethod would produce
   {
       System.Console.Write(v);
   }
}
```

Extract with maximal captures:
```c#
void M()
{
   var x = 0;
   local();

   void local() // no parameters
   {
       System.Console.Write(x);
   }
}
```

**Comment by CyrusNajmabadi** [comment]
> Extract with minimal captures:

Your example gave me the heebie jeebies since you had to rename everything captured.  I'm not sure how i feel about this.

**Comment by jcouv** [comment]
Sorry I had misunderstood the scenario.
For promoting a local function to be a method, I think the only condition is that the local function should have no captures. Other than that, it seems doable.
