### ISSUE TITLE
"Find All References" window blinking and unusable until all references are found

### ISSUE THREAD

**Issue by vasily-kirichenko** [dotnet/roslyn#16323]
VS 2017 RC2:

![1](https://cloud.githubusercontent.com/assets/873919/21742877/ccd424a6-d508-11e6-95f4-b195692e5bca.gif)

Finding all references in large solution may take some time (up to minutes if it contains many F# projects). As the API is asynchronous, I expect the window to be responsive and not blinking while the search process is running: I'd like to be able to click on already found references, scroll the results freely and stop the finding process (however, it's a separate issue).

**Comment by CyrusNajmabadi** [comment]
Tagging @lineralpha

**Comment by CyrusNajmabadi** [comment]
Talked to David Pugh about this.  This is a known issue on the editor side.  their PR to fix this is: https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/VS/pullrequest/51498?_a=overview

**Comment by CyrusNajmabadi** [comment]
We believe the fix will be in RC3.  Thanks!

**Comment by vasily-kirichenko** [comment]
wow. cool!

**Comment by Pilchie** [comment]
@cartermp or @brettfo can you verify this on a recent build?

**Comment by cartermp** [comment]
Seems to work okay on my machine with the signed release build.  Below is me executing FAR on `World`, which is referenced1439 times.  It's responsive and doesn't blink.

![find-all-refs-no-blink](https://cloud.githubusercontent.com/assets/6309070/22159604/99cddf82-def6-11e6-8d65-74325944acd2.gif)


(Note that I can't test this on VisualFSharp.sln because for some reason it's having trouble loading on my machine.  I can load any other solution I try, but VisualFSharp.sln seems to be an issue.)

**Comment by vasily-kirichenko** [comment]
@cartermp unload FSharp.Core project.

**Comment by cartermp** [comment]
@vasily-kirichenko Unfortunately that doesn't work either on the signed build I have.  It's strange.  I can open and work with any solution other than VisualFSharp.
