### ISSUE TITLE
Update Extract Method to consume the new DataFlowAnalysis API

### ISSUE THREAD

**Issue by balajikris** [dotnet/roslyn#1639]
see #1545

**Comment by Pilchie** [comment]
It looks like the compiler side of this is not happening for 1.0.  Should this also move to 1.1?

**Comment by balajikris** [comment]
Yes, I did not see any API change with the commit (#1501) associated with #1545. So, I believe this work is being pushed to 1.1. If that is the case, we can also move this to 1.1

cc: @gafter

**Comment by jcouv** [comment]
@Pilchie Should this still be in RTM?

**Comment by Pilchie** [comment]
No - since the dependent work in the compiler is now scheduled for 3.0, this should be too.

**Comment by CyrusNajmabadi** [comment]
I don't believe htere's any actual work to be done here.  The existing API remains and is suitable for the feature purpose.  Moving to the new api doesn't really change anything (it just means we make multiple calls instead of one).  I'm closing this out as changing our impl doesn't seem to improve things and doesn't lead to any user visible behavior.

if tehre is some user visible feature benefit that would benefit from this, we should explain what that is and drive the code change off of htat.
