### ISSUE TITLE
Invalid indent guides on else-if with multiline condition

### ISSUE THREAD

**Issue by josefpihrt** [dotnet/roslyn#16395]
**Version Used**: Visual Studio 2017 RC 15.0.26020.0

![invalidindentguides](https://cloud.githubusercontent.com/assets/11931318/21818926/ef53508e-d769-11e6-8156-f2c20bc764f6.png)

:link: Also reported in https://developercommunity.visualstudio.com/content/problem/111474/guides-for-code-level-constructs-misaligned-in-c-e.html

**Comment by dpoeschl** [comment]
Possible duplicate case: https://developercommunity.visualstudio.com/content/problem/115785/bracket-dotted-line-detects-wrong-scope-when-first.html

**Comment by uniqueiniquity** [comment]
@dpoeschl Another possible duplicate case. Please let me know if this is a different issue, but previous investigation of TypeScript indent guide issues have boiled down to our usage of Roslyn.
https://developercommunity.visualstudio.com/content/problem/139664/structure-guidelines-broken-typescript.html

**Comment by uniqueiniquity** [comment]
One more duplicate case: https://github.com/dotnet/roslyn/issues/16395https://developercommunity.visualstudio.com/content/problem/148578/indent-guide-lines-in-javascript-is-misaligned.html
Again, let me know if you determine that this is a different issue from the above.

**Comment by gundermanc** [comment]
Hi all, lmk if I can assist with this issue. I've debugged into it and the problem is that that the Roslyn block tags treat the 'if' in else if as the start of the block's header span, so, the structure guide is aligned to there.

IBlockTag is now deprecated in favor of IStructureTag, which supports setting the horizontal alignment of the guide explicitly via a HorizontalAnchor SnapshotPoint. As long as this point resolves to the 'e' in 'else if' the guide will be properly aligned. The simplest fix for Roslyn would probably be to make the horizontal anchor point be the first non-whitespace character in the line containing the header span (else if (...)). This doesn't require any knowledge that you don't already know from your AST and will work fine for every case except for labels and when else/if are on different lines:

    FooLabel:      else if (...)
    |              {
    |
    |              }

    else
        if (...) {
        |
        |
    }   |

**Comment by CyrusNajmabadi** [comment]
I can try to make this change.

**Comment by CyrusNajmabadi** [comment]
> will work fine for every case except for labels and when else/if are on different lines:

I'd much rather this not be a heuristic, but rather something the language can explicitly opt into.  To do that, we would have to add a field to https://github.com/dotnet/roslyn/blob/master/src/Features/Core/Portable/Structure/BlockSpan.cs stating where the span would start/stop.  It would be optional and would default to whatever BlockSpan.TextSpan was.  

For the block in an 'if' in an 'else', the language could say that it needed to start on the 'else'.

**Comment by CyrusNajmabadi** [comment]
> and will work fine for every case except for labels and when else/if are on different lines:

I'm also worried about more cases than this.  For example, VB xml literals, or people who have lambdas with blocks that are indented, etc. etc...

**Comment by CyrusNajmabadi** [comment]
> The simplest fix for Roslyn would probably be to make the horizontal anchor point be the first non-whitespace character in the line containing the header span (else if (...)). 

Out of curiosity, if the problem can be solved this way, then why not have that be the default of hte horizontal anchor point is not specified?

**Comment by gundermanc** [comment]
Though this is a reasonable behavior, after much discussion, it was thought that heuristics would always be suboptimal, so the decision was made to let the language owner specify the horizontal location for the guide via the GuideLineHorizontalAnchorPoint. In this way, the owner has full control over the adornments and are not limited by the half dozen cases we may have thought of ahead of time.

**Comment by RayKoopa** [comment]
Any news on this? Just wanted to report this in the following case:
![image](https://user-images.githubusercontent.com/9631152/108087488-ca287400-7077-11eb-9a23-c592067d6d04.png)

It also happens in C++ so I'm not sure if it's just a Roslyn issue to begin with...
![image](https://user-images.githubusercontent.com/9631152/108087660-f2b06e00-7077-11eb-8315-e117960419c5.png)

**Comment by gundermanc** [comment]
>I'm not sure if it's just a Roslyn issue to begin with...

Both Roslyn and C++ are omitting the 'guidelineHorizontalAnchor' parameter to the constructor of IStructureTag/IBlockTag. Without it, Editor can at best, guess where the structure guides should be painted.

IIRC, these are the spans we're being given. Red is 'Header span' and blue is 'guideline span' or 'outlining span'.

![image](https://user-images.githubusercontent.com/5387680/108102792-e4456080-703d-11eb-95bb-bd39c2b71599.png)

The guideline/outline span determines the vertical extent of the structure guide and the header span is used to guess the guidelineHorizontalAnchor, when it's omitted. In this case, we guess 'i' in 'else if' as the guidelineHorizontalAnchor because that's the first character of the given header span, which is usually the first non-whitespace character on the line. See this example:

![image](https://user-images.githubusercontent.com/5387680/108103192-70f01e80-703e-11eb-9031-9c74d04d9bf0.png)

This behavior is important from more than just a line-drawing perspective. It also determines the contents of the structure tips:

![image](https://user-images.githubusercontent.com/5387680/108103758-3e92f100-703f-11eb-8d84-b29af8192374.png)

FWIW: I can't repro this in C# anymore in Microsoft Visual Studio Enterprise 2019 Int Preview Version 16.9.0 Preview 3.0 [30817.202.main] but it repros in 16.8.3 in the Release channel.

@jasonmalinowski, has this been fixed? IIRC you were evaluating switching from IBlockTag to IStructureTag and some other housekeeping.

@RayKoopa thanks for poking this thread! I've forwarded your Developer Community issue to the C++ IDE team to get it fixed.

**Comment by RayKoopa** [comment]
@gundermanc Thanks for the insight into why this happens. Since I opened a VS issue about it at https://developercommunity2.visualstudio.com/t/indent-guide-misplaced-in-wrapped-else-if-statemen/1340122 since the only other issue I found there was closed due to it being clamed to be Roslyn-related only, you may want to merge that issue too.

**Comment by CyrusNajmabadi** [comment]
@gundermanc from previous conversations on this topic: this is not something we can't realistically provide.  It's inherently something that needs to understand the view to make a statement on, but we don't have access to the view here as this is just a buffer tagger.

> Without it, Editor can at best, guess where the structure guides should be painted.

My recollection from teh last time we talked about this is that hte guess should *always* pick the leftmost point in the view of hte two points to decide where to draw things.  We looked at all our examples (xml, code, strings, etc.) and leftmost was a more appropriate heuristic.

This is needed because if you go with a point that is more to the right, you are almost certain to intersect real code.

**Comment by jasonmalinowski** [comment]
> @jasonmalinowski, has this been fixed? IIRC you were evaluating switching from IBlockTag to IStructureTag and some other housekeeping.

I have a cleanup of our system in #50889, it looks like the behavior might be changing to:

![image](https://user-images.githubusercontent.com/201340/108114440-a51f0b80-704d-11eb-8301-594051428513.png)

Because I'm now returning the entire span (including the "else if") as a part of the header span:

![image](https://user-images.githubusercontent.com/201340/108114499-bcf68f80-704d-11eb-96ac-16881b69a68c.png)

That probably means my logic in src/EditorFeatures/Core/Implementation/Structure/StructureTag.cs isn't quite matching what we did before, but maybe that's a feature? We didn't have any tests on the old code and the old code was fairly opaque.

**Comment by jasonmalinowski** [comment]
@RayKoopa Your timing is impeccable, that you happened to ping a four year old bug right when this code happened to be looked at.

**Comment by RayKoopa** [comment]
@jasonmalinowski I felt like reporting it several times throughout the last years whenever I stumbled over it, but somehow had a _hunch_ to do so just today.

**Comment by RayKoopa** [comment]
@jasonmalinowski Sorry for the extra ping, but I noticed that in your code example posted above, your `||` is indented to be in the same column as the `if`, and not indented by 4 spaces / 1 tab, e.g.:
```cs
        else if (x == 1
             || x == 2)
```
rather than my example
```cs
        else if (x == 1
            || x == 2)
```

Is it supposed to be that way?

**Comment by jasonmalinowski** [comment]
@RayKoopa ah, I wasn't careful enough, but behaves the same way either way.

**Comment by CyrusNajmabadi** [comment]
@olegtk Can you move this to platform?  roslyn is returning the correct data here afaict.  This can all be handled based on the data provided in the rendering side of things.
