### ISSUE TITLE
Completion item filters conflict

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#16418]
**Version Used**: 2.0.0.61308

**Steps to Reproduce**:

```C#
using System;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
             new Exc|
        }
    }
}
```
The autocomplete list contains `Exception` item as a snippet entry, which hides the `Exception` class entry. That is fine, but when I filter to classes only, there is no `Exception` entry at all.

**Comment by Pilchie** [comment]
This is an interesting case - it happens because when building the list of items, we *replace* the type with the snippet.  You could imagine shadowing in some way instead so that we reveal the type when filtering away exceptions. 

However, given that we only ship with 2 snippets that match type names (Exception and Attribute), I'm not terribly worried about.

@CyrusNajmabadi for thoughts.

**Comment by CyrusNajmabadi** [comment]
Closing out given lack of feedback here.
