### ISSUE TITLE
Visual Studio 15 RC - New File/Item dialog

### ISSUE THREAD

**Issue by eyalalonn** [dotnet/roslyn#16522]
Just a minor issue but when you open the New File/Item dialog using Ctrl+N/Ctrl+Shift+A you have to use the mouse to either select the item that you want from the list or select the search box and then search for whatever.

Now, if you don't want to use the mouse you have to go through these steps:

1. Press Ctrl+N/Ctrl+Shift+A to open the dialog.

2. Press tab 3 times to get to the list of item templates and then select the desired item from the list.

    Alternatively, you can press tab 4 times (or Ctrl+E) and get to the search box.

3. Press enter.

I _think_ that it would be _sensible_ that when a project is selected or a file of project is selected in the solution explorer to imply that the user is looking for the same kind of items (prior to any selection), currently, the focus is on _installed templates_.

Just to explain what I mean I'll give an example say I have a solution and a C# project, when I select either one of them in the solution explorer and open the New File dialog or the New Item dialog I'd expect the focus to be on the list of _item templates_, when I'm selecting the C# project and then open the New File dialog I'd expect to see the C# _item templates_ at the top of the list.

The second thing that might need to change in the New Item dialog is how it behaves when the user already added an item to the project before and now he/she wants to add another one, in this case I think the focus should change to the textbox to give the user a chance to name the file but I don't know maybe that's too _clever_.

_I really don't know if these suggestion make sense, maybe it isn't as intuitive as I think, in this case just close it or tell me and I'll do it._

p.s. I find the default keybind Ctrl+Shift+A for the New Item dialog a bit weird, I always change it to Ctrl+N but that's a personal preference.

**Comment by miloush** [comment]
That's because Ctrl+Shift+A _adds_ new item to the project, while Ctrl+N just creates _new_ item.
(They are different dialogs and your suggestion does not actually make sense for the new item dialog, as there are no project templates in that one.)

Isn't the search box reachable using Ctrl+E?

You didn't really state your suggestion, is it to _change the default focus of the Add New Item dialog to the list of item templates_?

**Comment by eyalsk** [comment]
@miloush 

> That's because Ctrl+Shift+A adds new item to the project, while Ctrl+N just creates it (out of project).

Can you elaborate on this? what do you mean by "That's because..."?

> (They are different dialogs and your suggestion does not actually make sense for the new item dialog, as there are no project templates in that one.)

Thank you, I'll clarify that and update the post.

> Isn't the search box reachable using Ctrl+E?

Yes but the point is that I think the focus should be on the list of items and that it should be sorted accordingly to the project you're working on so for example if you're working on a C# project then you may want to see item templates that are related to C# at the top.

Just a minor quality of life improvement that I thought to bring up.

> You didn't really state your suggestion, is it to change the default focus of the Add New Item dialog to the list of item templates?

Yes, it is.

**Comment by miloush** [comment]
@eyalsk 
> Can you elaborate on this? what do you mean by "That's because..."?

That was to your note about the keybind to be weird. I tried to say that 'A' stands for 'add', Ctrl+A is taken so Ctrl+Shift+A is the next logical one, but maybe that wasn't the source of weirdness to you. :)

> Yes, it is.

I support your suggestion then!

**Comment by eyalsk** [comment]
@miloush 

> That was to your note about the keybind to be weird. I tried to say that 'A' stands for 'add', Ctrl+A is taken so Ctrl+Shift+A is the next logical one, but maybe that wasn't the source of weirdness to you. :)

Well, personally, I don't like the combination of Ctrl+Shift+A because all these keys are too close to one another but it depends on the hands and the way you lay them on the keyboard and the kind of keyboard you have so maybe it's only me! 

> I support your suggestion then!

Thanks! 😉 

_I know it's a small improvement and maybe a silly one but I feel like it's better to share it than keep it to myself and torment myself! 😆

**Comment by Pilchie** [comment]
@kuhlenh can you work with the platform team about improving this experience.

**Comment by miloush** [comment]
This sounds like the kind of feedback that could go to the _Report a problem_ tool btw.

**Comment by eyalsk** [comment]
@miloush I'm not using this tool. :)

**Comment by CyrusNajmabadi** [comment]
Closing out as this is not in roslyn.  If tehr's a desire for this, please file feedback using the existing VS feedback mechanisms.  Thanks!
