### ISSUE TITLE
Refactoring: Make method static or warn if the method can be made static as-is

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#16621]
"The method can be made static" warns if `this` is not referenced throughout the method body. The compiler will emit non-virtual call sites for static members and also they do not need `this` parameters, so it's always preferable if it's applicable, but it's not immediately noticeable.

**Comment by Pilchie** [comment]
This is a good example of another thing that might be either a refactoring or an analyzer - e.g. There is an FxCop rule saying that things that can be static should be.

Actually - that fxcop rule is already implemented as an analyzer in https://github.com/dotnet/roslyn-analyzers/blob/569bd373a4831d3035597197e02980b57602a7f2/src/Microsoft.QualityGuidelines.Analyzers/Core/MarkMembersAsStatic.cs

**Comment by Pilchie** [comment]
Marking as "In Progress", but I'm not sure if we actually want this to be part of the core Roslyn code, or we just want to make the FxCop nugets more discoverable/on by default as suggestions/something.

Tagging @kuhlenh and @srivatsn for thoughts here.

**Comment by alrz** [comment]
I agree, if this is part of FxCop analyzers, it shouldn't be part of Roslyn, but perhaps this could be built-in in the IDE? Installing a nuget for this is *really* inconvenient.

**Comment by Pilchie** [comment]
We have a general desire to take our existing code style analyzers and factor them into NuGet packages so that you can get enforcement at build/CI time.  In doing that, we'd like to build a story where we can default things on in the IDE and then have an easy way to "promote" that to being a NuGet.

**Comment by alrz** [comment]
So that's quite the opposite! But consider this, if I want to run this on `CSharpSyntaxGenerator` I shouldn't really need to install FxCop on Roslyn! There are analyzers that does not necessarily need to be enforced at the build time but they will be useful as an insight for the developers anytime.

**Comment by Pilchie** [comment]
I don't think I explained myself very well :(

Currently our code style analyzers *only* work inside Visual Studio, but don't work as part of "build" or CI.  We would like to enable the CI scenario, which implies factoring them out so that the *can* be referenced via NuGet packages.  That doesn't mean that we want that to be the *only* way to get them.

At the same time, we should be pulling in some of the FxCop analyzers so that you can see them easily as suggestions in the IDE.

For both of these we then need a better way for people to understand the difference between analyzers they only get through the IDE (via VSIX) and ones that are part of their build (via NuGet) and how to transition from one to the other.  Also tagging @kuhlenh and @srivatsn here.

**Comment by CyrusNajmabadi** [comment]
Is this supposed to be assigned to me?  Seems like something outside of the realm of IDE.  Maybe it would be better under the 'Analyzers' Bucket?  @Pilchie ?

**Comment by CyrusNajmabadi** [comment]
@Pilchie I'm making this unassigned.  I don't think this was meant to be assigned to me.

**Comment by CyrusNajmabadi** [comment]
Closing out as we have a roslyn-analyzers analyzer for this.
