### ISSUE TITLE
Bumping diagnostic severity for some IDE analyzers to error/warning doesn't cause it to run for closed files.

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#16700]
**Version Used**: 
D15PreRel 26120.4

**Steps to Reproduce**:

1. Enable full solution analysis for C#
2. Create a C# console app with the following source code:
```
namespace ConsoleApp1
{
    class Program
    {
        void F(object o)
        {
            var x = o as Program;
        }

        static void Main(string[] args)
        {
        }
    }
}
```
3. Verify IDE0008 is shown in the error list.
3. In solution explorer, right click on Analyzers node under `Project -> References -> Analyzers` and click "Open active ruleset".
4. Search "IDE0008" in the ruleset editor, and change the severity of both the listed diagnostics to "Error".
5. Verify IDE0008 is now shown as "Error" in the error list
6. Close the source file

**Expected Behavior**:
Error IDE0008 is still shown in the error list. Any diagnostics marked as error in the project's ruleset should always be executed for closed files.

**Actual Behavior**:
IDE0008 will disappear, and only show for open files. Even closing and re-opening solution/VS doesn't seem to help.
The problem seems to be that many IDE analyzers compute OpenFileOnly value using just the Workspace level NotificationOption, see [here](http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/QualifyMemberAccess/AbstractQualifyMemberAccessDiagnosticAnalyzer.cs,25). They should instead be using the effective severity of the diagnostic ID for the current compilation to decide this value.

**Comment by Pilchie** [comment]
Is this related to the `IBuiltinAnalyzer` stuff?  Do we need to just get rid of that and get these running properly OOP?

**Comment by CyrusNajmabadi** [comment]
I don't really understand what that code is doing @mavasani .  You say "Any diagnostics marked as error in the project's ruleset should always be executed for closed files."  But that code checks for warnings and for errors.  

Also, the code doesn't check for 'info'.  

> They should instead be using the effective severity of the diagnostic ID for the current compilation to decide this value.

I dont' know what this means.  Can you give us an example of what the code should be doing and how it shoudl be written so that this works properly?

Note: my understanding was this operation affected if things would run out of proc or not.  It's unclear to me what relation this option has to rulesets and whatnot.

**Comment by mavasani** [comment]
[OpenFileOnly](http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/Diagnostics/IBuiltInAnalyzer.cs,28) method should also pass in the current compilation/project and the analyzer should check if any of its reported DiagnosticDescriptors have error or warning effective severity using this API: http://source.roslyn.io/#Microsoft.CodeAnalysis/Diagnostic/DiagnosticDescriptor.cs,298bc3617e8352cc,references. If so, they should return false for this method.

**Comment by CyrusNajmabadi** [comment]
This API seems super difficult to get right.  We have to know which descriptors we're going to generate.  But that requires duplicating knowledge about those descriptors from our analysis code to the OpenFileOnly codepath.

Can you guys show us how you think this should be written?  And demonstrate an approach that is clear and easy to implement so that we don't risk continuing to get this wrong (as we apperantly have been doing so for the last X number of years)?

**Comment by mavasani** [comment]
Correct fix here is to completely get rid of IBuildInAnalyzer and OpenFileOnly hacks in the IDE. All this functionality currently works perfectly fine for non-built in analyzers. I think we should really aim to get rid of this interface and WorkspaceAnalyzerOptions hacks once we can move IOptions into the Analyzer API.

**Comment by CyrusNajmabadi** [comment]
ok... so should i just assign this back to you guys?

**Comment by mavasani** [comment]
Yes, either HeeJae or me can clean this up once IDE analyzers don't need Workspace.

**Comment by CyrusNajmabadi** [comment]
Yeah.  as far as i can tell, this API is impossible to implement.  Because we don't know what the severity even is if we don't know what document you are processing.  That's because options are document-based (thanks to Editor-Config).  So we can't even answer the question if all we get passed is the Workspace.

**Comment by CyrusNajmabadi** [comment]
Ok.  Giving back to you.   Let's see what we can do here in the U1 timeframe.

**Comment by CyrusNajmabadi** [comment]
Closing out as we removed the "open files only" concept.
