### ISSUE TITLE
BlockCommentEditingTests failing on recent VS2017 builds

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#16802]
When our master branch is compiled / ran against the 26127.00 build of VS a number of BlockCommentEditingTests are failing.  This is a recent regression as it doesn't happen in our build from 2 weeks ago.

Microsoft.CodeAnalysis.Editor.CSharp.UnitTests.BlockCommentEditing.BlockCommentEditingTests

- InsertOnMiddleLine6
- InsertOnStartLine2
- InsertOnMiddleLine3
- InsertOnMiddleLine2_Tab
- InsertOnStartLine3
- InsertOnStartLine3_Tab
- InsertOnMiddleLine2
- BoundCheckInsertOnStartLine1
- InsertOnStartLine2_Tab
- InsertOnMiddleLine3_Tab
- InsertOnEndLine3
- BoundCheckInsertOnMiddleLine

Here is a branch which can be used to repro the problem. 

https://github.com/jaredpar/roslyn/tree/dev15-test

**Comment by CyrusNajmabadi** [comment]
This change seems to be happening due to the editor's change to "smart indent".  Specifically, their new smart-indent system trims trailing whitespace when you hit enter.  This makes a visible change in how enter is processed when editing in a block comment.

My initial assessment is that the new behavior is acceptable.  However, i would like @kuhlenh @DustinCampbell @Pilchie to weigh in on if the old behavior was actually desirable and if we'd want to do work to return to it.

**Comment by Pilchie** [comment]
These changes look fine to me.  @diryboy - I think you wrote most of them.  What do you think?

**Comment by diryboy** [comment]
The change in 71e064f05c35639b586e7ec218f8e8eeddc61114 is acceptable to me. IIRC there was a PR implementing similar changes for XML doc comments.
