### ISSUE TITLE
Too many tuple elements cause VS crash

### ISSUE THREAD

**Issue by ufcpp** [dotnet/roslyn#16847]
**Version Used**: 

Visual Studio 2017 RC3 (VS 15.0.0-RC.3+26127.0)

**Steps to Reproduce**:

1. Create a tuple that has too many elements. That's all.

I tried to create a tuple of 65537 elements:
https://gist.github.com/ufcpp/066e7e558cb2ca184bba1bc7d0b5dd63

**Expected Behavior**:

Should the C# compiler have limitation on the max number of tuple elements?

**Actual Behavior**:

Visual Studio 2017 is crashed.

**Comment by bbarry** [comment]
tryroslyn gives an error on the 1110th element

    error CS8078: An expression is too long or complex to compile

The server takes progressively longer as more elements are added and appears to time out before 4000.

**Comment by jaredpar** [comment]
Thanks for filing this issue.  It's a duplicate of #9795.  

The underlying problem is there is a limit to the level of nesting we support in the compiler for a given expression / statement.  This is due to the recursive nature of parts of the compiler.  We're looking into some ways to remove this limitation and that is covered by #9795.

**Comment by jaredpar** [comment]
@jcouv FYI
