### ISSUE TITLE
Visual Studio 2017 Xaml Format Code Issue

### ISSUE THREAD

**Issue by SokHeangKhun** [dotnet/roslyn#16899]
Visual Studio 2017: 

I've been written xaml for a whole document and when I cut  or copy it it make unformat xaml code.
And I try to use the Format Document under Edit->Adcance->Format Document, but  it won't work. How can I fix this?

**Comment by mgoertz-msft** [comment]
Hi George,

Are you saying that just by doing a cut or copy of some parts of the XAML it messes up the formatting of the document?

To better illustrate the problem, it would be helpful to see both the formatted and unformatted XAML. You may also want to check/modify the formatting settings under Tools->Options...->Text Editor->XAML->Formatting->General/Spacing and let us know what they have been set too when this problem occurs.

Another good way to reprot this problem is to use the Send Feedback button in the title bar of VS, which will allow you to record the exact repro steps.

Marco

**Comment by GeorgeHeang** [comment]
I'm afraid that I'm fool. Here is the photos.
![screenshot_2](https://cloud.githubusercontent.com/assets/19168159/22615550/2ac6d056-eac9-11e6-9fe3-10fd9497d891.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/19168159/22615552/2eb2277e-eac9-11e6-9f84-46eec6b4d771.png)

Hope You'll help me.

**Comment by jeranio** [comment]
I have same problem cannot formay XAML code using CTRL+K+D

**Comment by mgoertz-msft** [comment]
Hi Jeranio,

I would suggest you use the VS Feedback tool to record the problem step by step. Include my alias "mgoertz" in the comments so I can easily find the feedback item. It would also be helpful to see you invoke the command by going through Edit->Advanced->Format Document instead of Ctrl+K+D just to make sure the command is not disabled or somehow associated with another shortcut.

Another thing to keep in mind is that the format commands are only enabled when the focus is in the XAML editor (as opposed to the designer) but the status bar usually warns you when a command is not available.

**Comment by pmuessig** [comment]
For those who have this issue, I think i figured out what the issue is and how to solve it.

My specific problem is that when I was pasting xaml content into a new resource dictionary, usually an elements attributes would be all misaligned. That is - in the source document each property (besides the first) would be on a new line and they would be vertically aligned. While in my target document all the attributes would not be aligned with the first attribute. They would either be shifted over to the left or the right several "widths". I would attempt to reformat the document (ctrl+k+d or selecting the option in the menus) to no effect and much frustration.

Looking at this issue prompted me to inspect my xaml formatting options and to my surprise the **Attribute Spacing** option was not what I expected! The first option - "Preserve new lines and spaces between attributes" was select as opposed to what I thought was select - "Position each element on a new line". The fix was as simple as selecting the correct option then reformatting the document with ctrl+k+d.

I suppose between installs of different versions of visual studio that particular formatting option somehow didn't get imported over.  I guess the first option is the default. 

Mystery solved!
