### ISSUE TITLE
VS2017 IDE will not accept decimal constants as attribute arguments (CS0181, CS0182)

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#16898]
_From @ericwj on January 26, 2017 3:0_

Declaring a `decimal` typed argument to an attribute constructor in VS 2017 will produce CS0181.
Providing a `decimal` typed argument to an attribute constructor that takes say `object` in VS 2017 will produce CS0182.

In both cases, building from the command line will work.

```CSharp
using System;

class DecimalAttribute : Attribute
{
	public DecimalAttribute(decimal value) { }
}
class AnyAttribute : Attribute
{
	public AnyAttribute(object value) { }
}
class Program
{
	// 1>Program.cs(14,3,14,5): error CS0181: Attribute constructor parameter 'value' has type 'decimal', which is not a valid attribute parameter type
	[Decimal(123m)] public int CS0181 { get; set; }
	// 1>Program.cs(15,7,15,11): error CS0182: An attribute argument must be a constant expression, typeof expression or array creation expression of an attribute parameter type
	[Any(123m)] public int CS0182 { get; set; }
}
```

_Copied from original issue: aspnet/Tooling#971_

**Comment by mikedn** [comment]
This has nothing to do with VS2017, it works like this since C# 1.0. Decimal isn't a primitive type and the runtime doesn't allow its use with attributes.

**Comment by gafter** [comment]
From https://github.com/dotnet/csharplang/blob/master/spec/attributes.md#attribute-specification

> An expression `E` is an _attribute_argument_expression_ if all of the following statements are true:
> 
> - The type of `E` is an attribute parameter type ([Attribute parameter types](https://github.com/dotnet/csharplang/blob/master/spec/attributes.md#attribute-parameter-types)).
> - At compile-time, the value of `E` can be resolved to one of the following:
>   - A constant value.
>   - A `System.Type` object.
>   - A one-dimensional array of _attribute_argument_expressions_.

**Comment by ericwj** [comment]
Okay well that's slightly unexpected. I write `decimal` in navy blue. Blindly expect the compiler to be able to write constants of it...

But then how do you explain I can build from the command line but VS 2017 will give me those errors and refuse to build?

**Comment by jnm2** [comment]
@ericwj Can you provide a minimal sample to reproduce this? I've never seen a successful build from the command line with a `decimal` where a constant is expected.

**Comment by ericwj** [comment]
I basically cannot reproduce. I'm guessing the issue is not so very important as it appears at least the latest version of dotnet shows the behavior you explained to be correct.

If I build it with rc3, it'll complain with `CS0181` as it appears it should.

If I build it with any other version on the machine on which I originally ran into this, it'll complain about Program missing a suitable Main method. It does that even after adding one. I'm guessing there are issues with my .csproj. I can't figure out what my global.json and csproj looked like when it did build. I can't get it to build right now, although I can get rid of the CS0181 without removing the code for them. I'm guessing these are MSBuild issues basically. E.g. I had it complain that I had two '&lt;Compile/&gt;' elements.

Console output:
![Console Output](https://rij9ma.bn1301.livefilestore.com/y3mqlrwE2FU4Huaha-DmgPpUQLR7QZHAGI7Cg02KXGKojloj7R2k2z771aLFbNHB_iq6aXulOARp45d1X5WpVGP70R54ZsF76Ix8ksOO3CaQIy6wOxRg9o72ZCITD1xfUjhg1zY0L150QjIohcfOMpqSGitOxarBG873_221EAv-G8?width=1348&height=848&cropmode=none)

**Comment by aaronfranke** [comment]
Are there any plans to add support for decimal constants as attribute arguments? Having to use double literals and round them properly when converting to decimal is annoying. I'm tempted to just have an array of structures that contain the parameters I need and having the NUnit test cases provide each index in the array.

**Comment by tullo-x86** [comment]
I see that this was closed "by design". My question is simple.

### Why?

Why is `decimal` the red-headed stepchild of the inbuilt numeric types? I understand that it was probably _really hard_ to do this in .NET Framework 1.0 (if I had to guess, I'd say it's because `decimal` was a hack in the first place), but **why has the community stuck with this convention through the full rebuild that is .NET Core**?

It's a really frustrating convention to stick to "for old time's sake", so what's the technical consideration here that I'm not seeing from the outside?

**Comment by CyrusNajmabadi** [comment]
> why?

Because this is the Roslyn repo. The goal here is to implement the language specification. The specification currently disallows this. If you would like this to be allowed the change must happen at dotnet/csharplang first. Thanks!

**Comment by tullo-x86** [comment]
Ah. Serves me right for not checking where I am before posting 😅
