### ISSUE TITLE
Insert close curly braces at the end of the statement

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#16949]
```cs
if (expr) $$ return;
```
Typing open curly brace <kbd>{</kbd> at the `$$` position should also insert the close curly brace.
```cs
if (expr) { $$ return; }
```
And hitting <kbd>Enter</kbd> should format the whole statement.
```cs
if (expr)
{
    return;
}
```

**Comment by CyrusNajmabadi** [comment]
Do be clear, you mean that we should do this if the statement after the ```{``` is on the same line as the ```{``` and the containing construct?

**Comment by alrz** [comment]
This is just a recurring use case but that shouldn't necessarily depend on the containing construct, since a block is valid anywhere a statement is.

If there is a single line statement after { we should insert the close curly at the end of that statement
```
{ single-line-statement;
{ single-line-statement; }
```

Similarly, if there is a single atomic expression (i.e. no operators) after ( we should insert close paren at the end of that expression.
```
M ( expr
M ( expr )
```

**Comment by CyrusNajmabadi** [comment]
My poiint was about if this was only done if hte '{' and the statement were on the same line.  You wouldn't do this if the 'return' was on the next line, right?

**Comment by alrz** [comment]
I see, not if the cursor was not immediately before it, 

```
  if (expr) { // no
     return;
```
but the following should work,
```
if (expr)
  { return;

if (expr)
  { return; }
```

**Comment by CyrusNajmabadi** [comment]
I see.  Both this, and the recommendation for expressions seem reasonable.  @DustinCampbell @Pilchie Do you see any problem with this approach?  One concern i have is simply that it changes behavior of a core typing experience.  That might be unexpected/undesirable for some people.  However, the change does seem sensible and intuitive... so i think it might be ok.  After all, how often would you be typing this sort of thing (where the cosntructs are on hte same line) and you wouldn't want to be surrounding things?

**Comment by miloush** [comment]
My concerns would be that it could make things worse if there are errors in the document?

**Comment by alrz** [comment]
@miloush It could only work if the following expr/statement is syntactically correct.

**Comment by Pilchie** [comment]
I think this is reasonable.  I know that @DustinCampbell did a LOT of thinking about ways to make brace insertion smarter in the past, so I'd like his input as well.

Also @balajikris implemented automatic brace insertion for Roslyn and might have ideas too.

**Comment by DustinCampbell** [comment]
I have a few concerns about this. @Pilchie's right that I *have* done a lot of thinking about this because it's super-tricky and more likely to break people in normal typing scenarios rather than help. (I even hold a patent on one potential solution to this problem.)

**First question**: Don't we have an "add braces" refactoring that does this?

**Second question**: Why is the coding scenario as described above useful? I think it's not as common that somebody would have the following code...

```C#
if (true)
    return;
```

...and then choose to type a `{` at the start of the return keyword. I think it's more likely that they'd put the caret at the end of the `)` and either type the `{` there or press enter and type the `{` on a blank line. If I'm right about that, this doesn't seem useful in the common case. And if it's a more esoteric typing scenario, maybe it isn't worth it?

**Third question**: How do we handle the scenario where the user wants to wrap several statements in an `if` (or some other statement that has an embedded statement). Consider the following scenario:

1. The user has code like the following:

    ```C#
    var x = 19;
    var y = 23;
    Console.WriteLine(x + y);
    ```

2. The user wants to wrap that code in an `if` statement, so they put the caret in front of the first statement and start typing.

    ```C#
    if (true) var x = 19;
    var y = 23;
    Console.WriteLine(x + y);
    ```

3. Then, they type ENTER and `{` on the next line.

    ```C#
    if (true)
    { var x = 19; }
    var y = 23;
    Console.WriteLine(x + y);
    ```

That leaves the user in a pretty broken state that is *more* awkward to fix than if we hadn't introduced the `}` at all. The point here is that you can't assume that, just because the tree is syntactically correct that its valid to introduce a `}` because the user may be in the middle of a larger edit and the tree happens to be syntactically accurate at that moment.

**Comment by alrz** [comment]
>First question: Don't we have an "add braces" refactoring that does this?

Sure but it ain't "refactoring" really. This is more of a code editing scenario. So I wouldn't prefer a code action for this simple case. This may have been addressed with a proper code style setting but not all code bases use braces for single-line embedded statements.


>Second question: Why is the coding scenario as described above useful? I think it's not as common that somebody would have the following code...

If you put the caret at the end of the `)` it's possible that you just want to move `return` out of the statement. I'm saying that if we insert `}` in a specific case (e.g. when the caret is immediately before a statement) users will take advantage of it and next time will explicitly put the care before a statement when they want `}` to be automatically inserted. Some text editors do this for `(` described above, but I never found it unexpected, actually it feels rather initiative and you will get used to it.

>Third question: How do we handle the scenario where the user wants to wrap several statements in an if
>
> ```
> if (true) var x = 19;
> var y = 23;
> Console.WriteLine(x + y);
> ```

That'd be awkward anyways unless we have a "surround with" refactoring. I'd use<kbd>Alt</kbd>+<kbd>Up</kbd> or <kbd>Alt</kbd>+<kbd>Down</kbd> to wrap that two lines in an `if` statement which is required regardless of the `}` being inserted automatically. So I think this is still useful because at least you don't have to type it yourself.

**Comment by DustinCampbell** [comment]
> That'd be awkward anyways unless we have a "surround with" refactoring. I'd use Alt+Up or Alt+Down to wrap that two lines in an if statement which is required regardless of the } being inserted automatically. So I think this is still useful because at least you don't have to type it yourself.

I don't see why this is awkward. A user is used to typing `if (true)<ENTER>{<DOWN><DOWN><END>}` but we'd break that. When creating such typing experiences, I'm always leery of the "blind typist" scenario--that is, the user who doesn't look at the screen as they type. I'm really concerned that this will break people who don't expect us to do things they aren't watching for. After all, inserting the closing brace might turn out to be truly confusing if the statement extends past the editor view port. In that case, the user wouldn't even know it happened.

My feeling is that this *may* be an interesting feature to flight. We could use telemetry to see if people find and whether they use or delete the brace. However, I don't think it's a slam dunk, and I'm unconvinced that it's worth the effort.

**Comment by alrz** [comment]
It'd break if they start typing with the caret located immediate before the first var,  but I expect they would start typing in the previous line. I don't have the data to prove that but it seems more likely. Anyways, I feel this would make the IDE smarter, could be an option for users to opt-in but it won't make the current situation worst IMO and they could actually adopt and embrace it.

**Comment by alrz** [comment]
In Roslyn, however, I never felt that this would be useful because we always use braces, but in code bases that I've been working on, this could be a huge advantage.

**Comment by DustinCampbell** [comment]
I agree that it'd be more likely that they'd start typing on the previous line. That's why I feel like this is a fairly low value change. However, I'm not sure it makes the IDE smarter -- especially in the case where the user has a long line and the brace is introduced off-screen.  In that scenario this feature would definitely make the experience worse if the user had wanted to enclose more than a single statement in curly braces.

**Comment by alrz** [comment]
So probably you'd agree this could be an opt-in feature? I'd be happy to work on this if there is a chance for it to make sense for a wider audience than just me. :)

**Comment by DustinCampbell** [comment]
Possibly. I'm just offering opinions and trying to see how bulletproof it is as a general feature. I do think it'd be interesting to flight and A/B test with people. @CyrusNajmabadi, @Pilchie: How do you feel?

**Comment by Pilchie** [comment]
@kuhlenh, @DustinCampbell, and I discussed this - we don't think this is high enough value, and has enough doubt to work on right now.  We'd rather see improvements to "Add Braces" to work as a refactoring if there is a selection, and to adjust the trigger span to work in the embedded statement, not just on the `if`.

If you wanted to work on your proposal, I would suggest making it a separate extension so that people can try it and we can see if it hampers their muscle memory, or improves things.
