### ISSUE TITLE
MSBuild Task needs to respect diagnostics flag

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#17070]
In several places the compiler MSBuild task catches Exception and only logs it to the Roslyn specific log.  This is preventing us from getting good diagnostics in large builds scenarios like the Visual Studio lab.  Our code needs to change to hook into standard MSBuild logging and environment variables to enable us to track down some hard to repro issues.  

- https://github.com/Microsoft/msbuild/issues/911
- https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems?id=277324&_a=edit

**Comment by jaredpar** [comment]
@agocke can provide some guidance here.  At a glance though in the places where we are catching Exception in the main ExecuteTool loop I think we should be logging directly to MSBuild there.  Any exception htat reaches that point needs to be put into the standard logging. 

https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/MSBuildTask/ManagedCompiler.cs#L470

**Comment by agocke** [comment]
@jaredpar It looks like we are logging the full exception (`exception.ToString()`) to MSBuild's logger (`Log.LogError`). I'm not clear what you mean by "Roslyn specific log". Since the `Exception.ToString()` contains the stack trace I'm not sure what more information we could gather here.

**Comment by jaredpar** [comment]
@agocke 

Is that their log or our log?  There are cases in the code base where we use `using static` to get direct access to our methods named `Log`.

Also that doesn't include the stack trace.   The MSBuild APIs support passing an exception down to them for processing where they can determine if an exception stack trace should be logged (see referenced MSBuild issue).  Need to ensure that we are properly deferring to this mechanism.

**Comment by agocke** [comment]
@jaredpar Light bulb moment.

I bet what's happening here is the reverse: we're getting an exception in the BuildServerConnection.IsCompilerServerSupported method, which is not guarded by a try-catch. This causes the MSBuild exception message to take over, which only logs the exception message, not the full strack frame.

I think broadening the try-catch here may solve our problem.

**Comment by agocke** [comment]
@jaredpar (Also, regarding logic for getting full stack frame, I made the decision to always print the full stack frame. I'm not sure why they didn't, but since we absolutely never expect to get an exception from the compiler in non-failing operation, I made the decision to always log the full stack frame for debugging purposes).

**Comment by jaredpar** [comment]
I considered if that was the method throwing.  But the code in there is so ... boring and basic.  If it was throwing I'd just assume the machine was in a terrible state.  

> I think broadening the try-catch here may solve our problem.

Possibly.  At the same time though we need to be handling the full exception object in such a way thot MSBuild can log the stack trace when needed.  I'm not sure exactly what the best mechanism is but @rainersigwald will know.

**Comment by rainersigwald** [comment]
It looks like we only call the dump-stack-if-in-diagnostics-mode when we catch an `ArgumentException`, `Win32Exception`, `IOException`, or `UnauthorizedAccessException` when calling the task's `ToolTask.ExecuteTool`: https://github.com/Microsoft/msbuild/blob/204cfd215fdc1c92322b0b22165cc8c4c3259e02/src/Utilities/ToolTask.cs#L1648-L1679

If an exception of any other type is thrown from a ToolTask, it gets caught by the standard Task-exception-handling mechanism and should eventually percolate to [`LogFatalError`](https://github.com/Microsoft/msbuild/blob/08753ec2a7f596e38b175efa27f31a89bd3c8e1f/src/Build/BackEnd/Components/Logging/LoggingServiceLogMethods.cs#L298-L317) which always logs the stack.

I suspect the original intention of that set of exceptions was an attempt to catch create-process failures and soften the error message for the user. But that seems fairly broken now because something else entirely could be throwing those exceptions--as would be the case here if the error is the currently-suspected one.

**Comment by TyOverby** [comment]
@rainersigwald 

Right now we are catching most of the exceptions that come from our ToolTask, printing them (to your log), and then returning a failure error-code.  (you can see our current implementation (here)[http://source.roslyn.io/#Microsoft.Build.Tasks.CodeAnalysis/ManagedCompiler.cs,473])

Should we be doing error handling at this level, or should we allow our exceptions to percolate up to MSBuild for it to be handled there?

**Comment by rainersigwald** [comment]
As long as the task fails, the rest of MSBuild should behave identically. If it weren't for the exception-filtering behavior, I'd say that you could just not catch. But since it is there and there's reasonable suspicion that it might be hurting diagnosability in this case, catching everything and failing inside `ExecuteTool` seems better.

**Comment by TyOverby** [comment]
Closed in https://github.com/dotnet/roslyn/pull/17074
