### ISSUE TITLE
"Debug Integration" and "Release Integration" queues are usually hanging, occasionally failing

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#17093]
Debug: https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_vs-integration/
Release: https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_release_vs-integration/

I hopped on to one of the machines where it was in the middle of failing, and there were ~64 copies of VS running with nothing open in them (completely blank, no start page, nothing). One of the copies said that the EditorPackage failed to load.

**Comment by dpoeschl** [comment]
@tannergooding I'm told that these are your new integration tests. Any idea what's going wrong? They haven't passed since February 2nd.

**Comment by dpoeschl** [comment]
FYI @tmat in case this runs over into next sprint.

**Comment by tannergooding** [comment]
It seems that one or more of the tests is failing and the VS instance is not being shutdown completely leading to a hang on subsequent runs.

Looks like the tests are failing because:
```
System.IO.FileNotFoundException : Could not load file or assembly 'Microsoft.VisualStudio.LanguageServices, Version=42.42.42.42, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
      Stack Trace:
           at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.VisualStudioWorkspace_InProc..ctor()
           at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.VisualStudioWorkspace_InProc.Create()
```

Why it is trying to load the v42.42.42.42 binaries I don't know (these are commit jobs, so they should be getting `-OfficialBuild=true`)

**Comment by tmat** [comment]
@tannergooding Was the reason why there are unofficial binaries being used figured out?

**Comment by tannergooding** [comment]
Not yet

**Comment by jasonmalinowski** [comment]
@tmat @dpoeschl How is this coming?

**Comment by tannergooding** [comment]
They should no longer be hanging at all and should be running and consistently passing now (they are running on PRs by default now even).

A run will occasionally fail due to the following error: `The "EnableExtension" task failed unexpectedly.`. This seems to be general flakiness with `/p:DeployExtension=true`

**Comment by dpoeschl** [comment]
Everything appears to be good here. Closing.
