### ISSUE TITLE
HostAnalyzerManager.GetAnalyzerReferenceId should generate a unique ID

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#1710]
See: http://source.roslyn.io/Microsoft.CodeAnalysis.Features/R/a1c94dbeedc15fae.html

This method uses Display as the analyzer reference ID, which is incorrect as that can return just the assembly name or path name. Both of these can't really be a unique ID for an analyzer reference. We need AnalyzerReference to expose an ID which can be used to de-duplicate different instances of analyzer references created with same underlying analyzer assembly but from different sources, e.g. same analyzer assembly added as a VSIX analyzer reference and a project analyzer reference.

see #1703 for more comments on this issue.

**Comment by tmeschter** [comment]
@mavasani Do we really need an ID property on `AnalyzerReference`, or should we just update `HostAnalyzerManager` to create better unique IDs? Is this problem specific to VS scenarios because it has multiple sources of analyzers, or could it conceivably occur in other hosts as well?

Or would it make more sense to de-duplicate at the individual analyzer level, rather than the `AnalyzerReference` level?

**Comment by mavasani** [comment]
Probably doing the de-duplication at just the analyzer level is fine, in fact we already do this to handle duplicate analyzer instances within different AnalyzerImageReferences. In that case, HostAnalyzerManager probably needs to use the AnalyzerReference instance as the key for its caches and needs to make sure it doesn't leak it when the reference is disposed. @heejaechang your thoughts?

**Comment by heejaechang** [comment]
@tmeschter @mavasani I am not sure what you mean by analyzer level? are you talking about we creating some kind of hash for each analyzer? if we can do that, we should be able to do that for analyzer reference as well. I would prefer de-dup in reference than analyzer since de-dup is always simpler and easy to understand as it happens earlier in the pipeline.

...

by the way, I don't think it is good idea to do de-dup based on heuristic. it is always hard to explain, and will have cases it just does wrong thing.

but we could reduce scope of de-dup and say, we will do de-duplication of AnalyzerFileReference and AnalyzerFileReference only, and we use some kind of Assembly Identity from dll.

**Comment by heejaechang** [comment]
Sorry that I am replying to one already checked in. but can we make ID property to return object rather than string? Also, is filename good enough ID for such generic class (AnalyzerFileReference)? Anything that has same filename will now get de-duped.


-          heejae

**Comment by tmeschter** [comment]
@mavasani Assigning back to you for verification.
