### ISSUE TITLE
Could we drop CS1612 on setting struct property?

### ISSUE THREAD

**Issue by Thaina** [dotnet/roslyn#17207]
Sometimes I made struct just for being wrapper to another class object

```C#
public struct DictVector
{
	Dictionary<string,float> dict;
	public void SetX(float value)
	{
		if(dict == null)
			dict	= new Dictionary<string,float>();

		dict["X"] = value;
	}

	public float X
	{
		set { SetX(value); }
		get
		{
			if(dict == null)
				return 0;

			float value;
			return dict.TryGetValue("X",out value) ? value : 0;
		}
	}

	public static Dictionary<string,DictVector> NameDict;
	public static void Initial()
	{
		NameDict = new Dictionary<string,DictVector>();
		NameDict["Test"].SetX(1); // No error
		NameDict["Test"].X = 1; // Error CS1612
	}
}
```

Like so, when that struct was being returned from another property or indexer, it cause `error CS1612: Cannot modify the return value of 'Dictionary<string, DictVector>.this[string]' because it is not a variable`

Changing that struct to be class work fine. I just think it has no reason to cause error for property while method seem OK. It should error just for set field

**Comment by jskeet** [comment]
It's an error because it's definitely buggy code. You'd be setting a property on a *copy* of the value in the dictionary - the value in the dictionary itself wouldn't be affected.

Likewise your `SetX` method wouldn't actually change the value in the dictionary, so again you've got a bug - but the compiler doesn't know that the method is actually trying to modify the state of the struct. It (reasonably) assumes that using a property setter *does* try to modify the state, so it's protecting you from the bug in that case.

**Comment by Thaina** [comment]
@jskeet It's affect. Because copy of this kind of struct will copy reference field

**Comment by jskeet** [comment]
@Thaina: See my edit - whether the effect is visible or not will depend on previous state, making it an even more subtle bug. You really, really don't want to use a struct like this - it's a recipe for problems.
