### ISSUE TITLE
Go To Definition fails "Cannot navigate to the symbol under the caret"

### ISSUE THREAD

**Issue by 0xd4d** [dotnet/roslyn#17360]
**Version Used**: VS2017RC.4

**Steps to Reproduce**:

- Create a new .NET Framework 4.6 Console App and add this code

```C#
namespace N {
	class Program {
		static void Main(string[] args) {
			var d = new System.Collections.Generic.Dictionary<Program, int>();
		}
	}
}
```

- Press F12 @ `Dictionary` (should work)

- Add a new .NET Framework 4.6 Class Library

- Add a reference to the new class library

- Add a project.json to the Console App project

```json
{
	"dependencies": {
		"System.ValueTuple": "4.3.0"
	},
	"frameworks": {
		"net46": { }
	},
	"runtimes": {
		"win": { }
	}
}
```

- Close solution and reopen it

- Move caret to `Dictionary` and press F12

**Expected Behavior**:

It moves the caret to the correct symbol.

**Actual Behavior**:

Message box that says: "Cannot navigate to the symbol under the caret."

**Comment by Pilchie** [comment]
I'm unable to reproduce this, but I wonder if it's related to the issue that @tmat saw in Roslyn.sln?  Some facade issue with types being forwarded maybe?

**Comment by CyrusNajmabadi** [comment]
Repros for me.  Investigating.

**Comment by CyrusNajmabadi** [comment]
I see what the problem is.  We're trying to navigate to "System.Collections.Generic.Dictionary<Program, int>", but we're trying to resolve that type in the class library, and not the console app.  'Program' doesn't exist in the class library, so resolution fails and the whole op dies.  

There are many things wrong here and i'm trying to decide the right point to place the fix.

**Comment by cnblogs-dudu** [comment]
Same issue in Visual Studio 2017 15.3.1.
