### ISSUE TITLE
Editorconfig not working for .config files

### ISSUE THREAD

**Issue by GerjanOnline** [dotnet/roslyn#17660]
**Version Used**: 
Microsoft Visual Studio Enterprise 2017
Version 15.0.26228.4 D15RTWSVC
Microsoft .NET Framework
Version 4.6.01055

**Steps to Reproduce**:

1.  Create ASP.NET MVC 5 project (Full fx) with an Web.config file
2.  Add an .editorconfig file to the solution 
3.  Add the following setting:

```
# Xml config files
[*.{props,targets,ruleset,config,nuspec,resx,vsixmanifest,vsct}]
indent_style = space
indent_size  = 2
```

4. Press CTRL + K, CTRL + D

**Expected Behavior**:
The web.config should be formatted with spaces

**Actual Behavior**:
It is not properly formatted (still tabs)

![image](https://cloud.githubusercontent.com/assets/1153419/23748239/0f9976da-04c3-11e7-81d9-9160f0b5b084.png)

**Comment by Pilchie** [comment]
Tagging @olegtk, since this is not a roslyn content type.  @GerjanOnline Can you try closing and re-opening the `.config` file after adding/modifying the `.editorconfig` file?  I think we don't react to file changes properly.

Alternatively, it's possible that the xml language service caches these values at load time, and doesn't work with editorconfig at all?

**Comment by olegtk** [comment]
As noted in [VS 2017 Release Notes](https://www.visualstudio.com/en-us/news/releasenotes/vs2017-relnotes#KIeditoride), editorconfig is not supported yet in XML files.
This is because language services typically need to update their formatters as described [here](https://docs.microsoft.com/en-us/visualstudio/ide/create-portable-custom-editor-options) and XML language service hasn't done that work yet.
Please file an internal bug for the XML language service though.

**Comment by Pilchie** [comment]
@GerjanOnline can you report this through the `Send Feedback` tool in Visual Studio so that it appears on https://developercommunity.visualstudio.com and other users can vote for it.

**Comment by GerjanOnline** [comment]
@Pilchie Thanks, will do

**Comment by ChristopherHaws** [comment]
@GerjanOnline Can you provide the link to your issue on the developer community site? I would like to upvote it, but I can't seem to find it.

Thanks!
