### ISSUE TITLE
Different behavior depending on compile constness in conditional operator

### ISSUE THREAD

**Issue by Zereges** [dotnet/roslyn#17756]
**Version Used**: Visual Studio 2015, Update 3

**Steps to Reproduce**:
Following code produces such behaviour

    struct Value
    {
        public int Magic { get; private set; }
        public void Increment() { ++Magic; }
    }

    static void Main()
    {
            Value v1 = new Value(), v2 = new Value();
            Console.WriteLine(v1.Magic + " " + v2.Magic);
    
            bool condition1 = true;
            (condition1 ? v1 : v2).Increment();
            Console.WriteLine(v1.Magic + " " + v2.Magic);

            const bool condition2 = true;
            (condition2 ? v1 : v2).Increment();
            Console.WriteLine(v1.Magic + " " + v2.Magic);
    }

**Expected Behavior**:
It is expected to output either

> 0 0
> 1 0
> 2 0

or

> 0 0
> 0 0
> 0 0

depending on semantics of conditional operator.

**Actual Behavior**:
Output is 
> 0 0
> 0 0
> 1 0

Which is weird, because it should not differ whether `condition` is known at compile time or not.

**Comment by CyrusNajmabadi** [comment]
Fascinating catch.  I cannot see anything in the language specification that would allow for the behavior you're seeing.  If this is as-per spec, i would love to see which section of it allows for this.

**Comment by gafter** [comment]
@VSadov @AlekseyTs I believe you were talking about this area of the compiler's behavior recently. The compiler silently treats an rvalue as an lvalue in some contexts, and this issue exposes some cracks in how we do that.

**Comment by tamlin-mike** [comment]
"The compiler silently treats an rvalue as an lvalue in some contexts"

Sweet lord. That is... bad. I mean really, really bad. This need to be addressed ASAP!

**Comment by CyrusNajmabadi** [comment]
> I mean really, really bad. 

The conditions (no pun intended) where this seems to happen seem very esoteric.  You'd need a mutable struct, a conditional, and a condition which is always true or false.  We should definitely fix this, but it doesn't seem very likely that this would actually be causing significant problems in practice.

**Comment by tamlin-mike** [comment]
> We should definitely fix this, but it doesn't seem very likely that this would actually be causing significant problems in practice.

That was also said about the .NET 4.6.0 (or what it was) JIT bug, and the Intel Pentium (P5) math divide bug, and the Intel conditional jump bug (also in P5, and later IIRC).

We may be of differing opinions re. the severity of this bug, but I consider it #1 - showstopper.
This is pretty much as bad as it gets. If an rvalue is EVER treated as an lvalue, no matter how esoteric or theoretically implausible, that's an "Emergency brakes on, all stop!" bug. It NEEDS to be addressed, ASAP. I find your lack of fright (re. this bug) very disturbing. I hope this is not representative for all people in the C# compiler team.

**Comment by CyrusNajmabadi** [comment]
>  I find your lack of fright (re. this bug) very disturbing.

My lack of fright is due to my analysis that this is unlikely to be wildly hit.  Nor it is it likely to cause an issue even if it is hit.  It requires an extremely unlikely set of conditions to be hit.  I've seen far more impactful compiler bugs over the years that we addressed without any need for "fright".  

Now, as mentioned already, i think we should fix this (even though it could cause breaks for people who may have depended on the behavior).  But i don't see anything about this that would, in any way, be considered a show-stopper.

**Comment by CyrusNajmabadi** [comment]
Note: i just tested this with the 4.6.1586.0 compiler (i.e. the one we shipped for C# 5.0).  When i tried out the code i got:

```
0 0
0 0
1 0
```

This means that we've been shipping with this bug for a minimum of 5 years now.  So far it hasn't even been noticed until now.  That makes me strongly believe that the impact of this bug is extremely low.  Definitely something to be fixed.  But clearly not deeply impactful or broadly felt by the existing C# ecosystem.

**Comment by CyrusNajmabadi** [comment]
This also reproes with the compiler we shipped for v2.0.50727.  That means this behavior has existing for >10 years now.  Note: i don't have a 1.0 compiler to test currently.  Anyone have one available to see if this even predates C# 2.0?

**Comment by Zereges** [comment]
I would like to see what the standard says about lvalueness in conditional operator with struct.

**Comment by CyrusNajmabadi** [comment]
Interestingly, i'm not exactly certain why this wouldn't be an lvalue in all circumstances.  The spec says this about conditionals:


Evaluating an identifier says this:

First:

> The run-time processing of a function member invocation consists of the following steps, where M is the function member and, if M is an instance member, E is the instance expression:
> •	If M is an instance function member declared in a value-type:
o	E is evaluated. If this evaluation causes an exception, then no further steps are executed.
o	If E is not classified as a variable, then a temporary local variable of E’s type is created and the value of E is assigned to that variable. E is then reclassified as a reference to that temporary local variable. The temporary variable is accessible as this within M, but not in any other way. Thus, only when E is a true variable is it possible for the caller to observe the changes that M makes to this.

So we need to see what E is classified as when it evaluated.  That jumps us to:


> •If K is zero and the simple-name appears within a block and if the block’s (or an enclosing block’s) local variable declaration space (§3.3) contains a local variable, parameter or constant with name I, then the simple-name refers to that local variable, parameter or constant and is *classified as a variable or value.*


The question for me is how "is classified as a variable or value" is interpreted.

**Comment by gafter** [comment]
@CyrusNajmabadi See https://github.com/dotnet/csharplang/blob/master/spec/expressions.md#conditional-operator . The spec for the runtime behavior of `?:` makes it clear that there is always a conversion involved. That should be a hint that the result is not an rvalue, but I agree the spec should simply state that fact.

You're not quoting the sepc

**Comment by CyrusNajmabadi** [comment]
>  That should be a hint that the result is not an rvalue, but I agree the spec should simply state that fact.

I agree.  I could find nothing in the spec that says that a conversion to a type means that a variable-reference becomes a value.  Explicitly calling that out in some location would make this super crisp.

**Comment by VSadov** [comment]
FWIW - it is clearly a bug, as in - the behavior is not derived from the spec and is likely unintentional consequence of overly aggressive optimization.

However, considering it is a 10 years old issue, I wonder if fixing it would be necessarily beneficial.  
Since we did not hear any complaints and there could be code inadvertently relying on it (and would be broken if recompiled with the bug no longer present).

It is not an easy call - whether this should be fixed or just added to the spec as long-standing pecularity.

The counter argument would be, of course, is that both const conditions and mutable structs are not very frequent. The intersection of these would be extremely rare.
So perhaps fixing this would not affect anyone.

**Comment by gafter** [comment]
I have requested that @dotnet/roslyn-compat-council consider what we should do here.

**Comment by gafter** [comment]
Compat council is OK with fixing this.

**Comment by gafter** [comment]
@VSadov Should this be grouped with your conditional-lvalue feature, or should it be fixed separately?

**Comment by VSadov** [comment]
@gafter I' just fix this in master to get it out quicker.

**Comment by gafter** [comment]
@VSadov Thanks! Please add a note to the breaking changes doc in your PR.
