### ISSUE TITLE
Warning should not mention target tuple type when the type is not specified explicitly.

### ISSUE THREAD

**Issue by VSadov** [dotnet/roslyn#17785]
The warning is quite confusing when it mentions the target type which was not specified.

![image](https://cloud.githubusercontent.com/assets/8218165/23870680/7977978e-07e4-11e7-81f4-adfc21d900f5.png)

**Comment by VSadov** [comment]
I think simply making a separate error that does not mention the target type would be acceptable.   

Somehing like:  
"The tuple element name '{0}' is ignored because the expression is not converted to a type that uses the same element name"

**Comment by jcouv** [comment]
Relates to https://github.com/dotnet/roslyn/issues/18169

**Comment by jcouv** [comment]
We had previously fixed the message to print the target type including element names. I also further refined the diagnostic by tweaking the message (PR #18454).
`warning CS8123: The tuple element name 'b' is ignored because a different name or no name is specified by the target type '(int a, int)'.`

I think that should close this issue.
