### ISSUE TITLE
[Proposal] 'switch all' enhancement for enums

### ISSUE THREAD

**Issue by tpetrina** [dotnet/roslyn#179]
When switching on enums, I would like to get a compile time error if I missed a case. Simple usage would be:
```
enum EnumValues { First, Second, Third }

EnumValues myEnumValue;

switch all (myEnumValue)
{
  case First:
  case Second:
   <--- compile time error if default statement is missing or any other enum value
}
```

All is obviously optional and only works for enums.

**Comment by mariusGundersen** [comment]
Similarly the compiler should use static analysis to see that all possible execution paths in the following method have been covered:
```cs
enum Color { Red, Blue, Green };
public string ToString(Color color){
  switch(color){
    case Color.Red: return "red";
    case Color.Blue: return "blue";
    case Color.Green: return "green";
  }
}
```
Unfortunately the problem isn't with switch, but with enums, since ints can be cast to enums. In my example I could cast `4` to `Color`, and in that case there would be no case for it in the method. 

To get better static analysis of enums in switch cases we need better enums.

**Comment by thomaslevesque** [comment]
Having this feature would have an unintended consequence: if you add new members to an enum, you can break existing code that uses your enum...

**Comment by axel-habermaier** [comment]
@thomaslevesque: That is _precisely_ the use case for that feature! ;)

**Comment by fschmied** [comment]
@thomaslevesque The point is that you would get a compiler error if you added a new enum member without adding a `case`.

I would propose the `switch all` feature should work for enums (even as they are now) and transparently include a `default` case that throws an exception (or, possibly, invokes the same behavior as a failed contract check, see #119).

Consider the following scenario:

    public enum MyEnum { One, Two, Three };
    public string GetText (MyEnum myEnum)
    {
      switch (myEnum)
      {
        case One: return "Single";
        case Two: return "Pair";
        case Three: return "Triple";
        // default: throw new UnreachableCodeException();
      }
    }

This currently causes the compiler to report that not all paths return a value, you need to uncomment the default branch due to the possibility that someone could cast an undefined value to the `MyEnum` type. `switch all` could remedy that by automatically generating the default branch.

    public enum MyEnum { One, Two, Three };
    public string GetText (MyEnum myEnum)
    {
      switch all (myEnum)
      {
        case One: return "Single";
        case Two: return "Pair";
        case Three: return "Triple";
      }
    }

If this is considered to be too implicit, one could combine it with #119: `switch all` could be combined with a special `requires` clause that causes a contract violation failure if an undefined value is passed to the method. That way, the compiler could now be sure there is no missing branch.

    public enum MyEnum { One, Two, Three };
    public string GetText (MyEnum myEnum)
      requires defined(myEnum)
    {
      switch all (myEnum)
      {
        case One: return "Single";
        case Two: return "Pair";
        case Three: return "Triple";
      }
    }

**Comment by paulomorgado** [comment]
What would happen if another value is added to the enum and the consumer code isn't recompiled?

**Comment by fschmied** [comment]
@paulomorgado In the variant with `requires`, a contract violation would arise (e.g., an exception or a fail-fast approach). In the variant without `requires`, the automatically implemented default branch would run.

**Comment by orthoxerox** [comment]
I think there should be two compiler error codes: one for switches with no default clause, and one for switches with one. This way you could elevate the first one to an error and keep the other one as a warning. I also do not think turning this into a real runtime check is necessary, since this might cause problems for existing consumers, as @paulmorgado suggested.

**Comment by gafter** [comment]
Given enums as they are in the language today, there are (unnamed) values of the enum corresponding to all values of the enum underlying type. Therefore the compiler cannot guarantee that a switch is complete unless you handle all possible values (of the underlying type). As such I don't think the feature would be that useful, and therefore this is not something we'd likely do.
