### ISSUE TITLE
For-loop variable not instanced properly in local functions

### ISSUE THREAD

**Issue by Esidar** [dotnet/roslyn#17958]
**Version Used**: 
VS2017 RTM
```

static void Main( string[] args )
{
	Action[] tests = new Action[ 4 ];

	string[] names = { "Add", "Sub", "Mul", "Div" };
	for( int i = 0; i < 4; i++ )
	{
		int k = i;
		void TestLocal()
		{
			System.Diagnostics.Debug.WriteLine( names[ k ] );
			System.Diagnostics.Debug.WriteLine( names[ i ] );
		}

		Action test = TestLocal;
		tests[ i ] = test;
	}

	CheckTests( tests );
}

private static void CheckTests( Action[] tests )
{
	for( int j = 0; j < 4; j++ )
		tests[ j ]();
}

```

It will crash in second WriteLine. variable K is properly instanced per each delegate, but variable I is not. It's not even clear why it has value 4 (CheckTests can be called some seconds later and "i" will be still 4).

**Comment by hozuki** [comment]
It's caused by closure.

In C#, closures are compiled to internal classes. Local functions are compiled as delegates (local variable, or a class member). For example, your code is compiled as:

```csharp
// Token: 0x02000002 RID: 2
internal class Program
{
    // Token: 0x06000001 RID: 1 RVA: 0x00002050 File Offset: 0x00000250
    private static void Main(string[] args)
    {
        Program.<>c__DisplayClass0_0 <>c__DisplayClass0_ = new Program.<>c__DisplayClass0_0();
        Action[] tests = new Action[4];
        <>c__DisplayClass0_.names = new string[]
        {
            "Add",
            "Sub",
            "Mul",
            "Div"
        };
        int i;
        int j;
        for (i = 0; i < 4; i = j + 1)
        {
            int k = i;
            Action test = delegate
            {
                Debug.WriteLine(<>c__DisplayClass0_.names[k]);
                Debug.WriteLine(<>c__DisplayClass0_.names[i]);
            };
            tests[i] = test;
            j = i;
        }
        Program.CheckTests(tests);
    }

    // Token: 0x06000002 RID: 2 RVA: 0x00002114 File Offset: 0x00000314
    private static void CheckTests(Action[] tests)
    {
        for (int i = 0; i < 4; i++)
        {
            tests[i]();
        }
    }
}
```

You can use ILSpy or dnSpy to verify this.

As you can see, when you are accessing `i` in a local function, you are actually accessing `i` inside a delegate. So `i` is actually "captured" from outside the loop, and `k` is captured from inside the loop. Capture behaves like references. So the `i` you are accessing is actually a reference to the **changing** `i` variable. As the loop ends, `i` outside the local function is set to `4`, and that's the value that `i` in local function has.

This behavior is also common in other functional programming languages. For example, JavaScript.

Also if you use some productivity tools, you can see the warning:

![image](https://cloud.githubusercontent.com/assets/7345875/24072689/15808c6c-0beb-11e7-9d25-0572e727fdcf.png)

**Comment by Esidar** [comment]
You explanation makes sense, although it is not what I would expect. What I would expect is to local function behave as if it was part of the loop.Just like stated in https://github.com/dotnet/roslyn/blob/features/patterns/docs/features/local-functions.md  "every variable read inside a local function be definitely assigned, as if executing the local function at its point of definition".

**Comment by hozuki** [comment]
Thank you for citing that. Here is another paragraph from the same file:

> Unless you convert a local function to a delegate, capturing is done into frames that are value types. That means you don't get any GC pressure from using local functions with capturing.

So it did mentioned this behavior (capturing).

Since in many people's minds local functions are syntax sugar for anonymous methods, they may expect local functions acting as closures, like those in everywhere else. But I agree that either the document or the implementation should be updated to clarify its behavior.

**Comment by gafter** [comment]
Your for loop increments the captured variable up to the value 4. That is why it is observed to be 4. You do not get a separate variable for each instance of the loop body, like you do for your declared `k`, whose declaration is inside the loop.
