### ISSUE TITLE
Editor/Codelens bug using C#7 style Tuple

### ISSUE THREAD

**Issue by raffaeler** [dotnet/roslyn#18001]
**Version Used**: Visual Studio 2017 RTM

**Steps to Reproduce**:
1. Create a method returning a C#7 style tuple
2. Hit a return right after the final tuple parenthesis
3. Look at the codelens info

**Expected Behavior**:
The codelens info should always precede the method signature

**Actual Behavior**:
The codelens info is between the tuple and the method name

![codelens](https://cloud.githubusercontent.com/assets/5183152/24121257/effe4d0c-0db7-11e7-8268-06eb768c83f8.jpg)

**Comment by Pilchie** [comment]
@jcouv - did you file this already?

**Comment by jcouv** [comment]
Yes (https://github.com/dotnet/roslyn/issues/10575), but you had closed it as "won't fix" at the time.
This has been reported at least once or twice since (https://developercommunity.visualstudio.com/content/problem/1888/codelens-not-appearing-in-correct-place.html), so it may be worth re-considering.

**Comment by sharwell** [comment]
I changed this to feature request. For cases where the return type and method name do not appear on the same line, CodeLens has appeared in the location described above since it was introduced.

**Comment by CyrusNajmabadi** [comment]
Closing out as this is unrealted to tuples.  It's about where CodeLens places the line on wrapped code.  Haven't heard about this from otehrs, so going to keep the current behavior.
