### ISSUE TITLE
Star ( * ) in out variable. Possible or not?

### ISSUE THREAD

**Issue by nikhilagrawaldotnet** [dotnet/roslyn#18016]
**Version Used**: 
Microsoft Visual Studio Community 2017
Version 15.0.26228.9 D15RTWSVC
Microsoft .NET Framework
Version 4.6.01586

In "More expression bodied members" section of Mark's blog [here](https://blogs.msdn.microsoft.com/dotnet/2017/03/09/new-features-in-c-7-0/), it's stated that `*` can be used in `out` variable. 

    names.TryRemove(id, out *)

Both this gives compile time error.

[Its asked on SO too.](http://stackoverflow.com/questions/42920622/c7-underscore-star-in-out-variable)

**Expected Behavior**:
* Should work in out variable.

**Actual Behavior**:
Throws error in VS.

**Comment by CnSimonChan** [comment]
The discard operator had changed to `_` and had shipped with Visual Studio 2017.

```` C#
// Discard the `out` value.
int.TryParse("42", out _);
````

[Try Roslyn](https://tryroslyn.azurewebsites.net/#b:features-default/f:r/K4Zwlgdg5gBAygTxAFwKYFsDcBYAUAB2ACMAbMAYxnJIEMQQYBhGAbzxg5kNIpgDcA9mAAmMALIAKAJSt2neZGQA6ACoAnBAAUaakKgkAiACwAmAwBoYA4MhgB9KTlzyAvnhdA==)

Basically if there is no local variable named `_`, it will means discard, otherwise it's a reference to the variable.

**Comment by jaredpar** [comment]
@CnSimonChan is correct that `_` is the final syntax for this feature.  The `*` syntax was used in earlier prototypes and presentations but changed before release.
