### ISSUE TITLE
Shift-Enter commits completion, but doesn't complete the current statement

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#18065]
**Version Used**: VS2015 and VS2017

**Steps to Reproduce**:

1. Paste C# code:
```C#
class Program
{
    static void Main(string[] args)
    {
        Main
    }
}
```
2. Type `(ar`
3. The completion list should be up with "args" selected
4. Type <kbd>Shift</kbd>+<kbd>Enter</kbd>

**Expected Behavior**: Completion is committed, and the current statement is completed (semicolon added, newline added, caret moved to next line)

**Actual Behavior**: Completion is committed.

**Comment by dpoeschl** [comment]
I'm not porting a CSharpFormatting integration test that asserts the wrong behavior, so there is no integration test coverage. Please make sure this is appropriately tested.

**Comment by sharwell** [comment]
Additional information here:

* Visual Studio 2013 introduced brace matching sessions, but did not have the **Edit.SmartBreakLine** command. In that release <kbd>Enter</kbd> and <kbd>Shift</kbd>+<kbd>Enter</kbd> are bound to the same command (**Edit.BreakLine**).
* In both Visual Studio 2015 and Visual Studio 2017, the <kbd>Shift</kbd>+<kbd>Enter</kbd> command works as you describe when a completion session is not active. The bug here only occurs when a completion session is active.

**Comment by dpoeschl** [comment]
In VB, it completes the current statement but doesn't commit completion...

**Comment by rchande** [comment]
In C#, the automatic line ender command handler is ordered after completion, which never passes along the automatic line ender command.
In VB, the automatic line ender command handler is ordered before completion and never passes long the command.
This appears to be the case even in Dev14 RTM...
