### ISSUE TITLE
Code Style: Wrapping

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#18282]
There should be an option to limit width of the text, and formatting code cause it to wrap inside that limitation.

**Comment by Pilchie** [comment]
I agree that we want this.  However, having written it a dozen years ago and then pulled it from the product because of it's seemingly infinite tail of bugs and giant set of additional preferences, I'm not eager to take it on again :)

**Comment by sharwell** [comment]
StyleCop's rules define *how* to wrap, but not *when* to wrap, which I've found keeps it quite usable in practice. I've seen many attempts by IDEs to implement line-width-based wrapping for code, but I've never seen one that produced a result that improved upon even the basic "word wrap" feature provided by viewers.

**Comment by DavidArno** [comment]
@sharwell,

You should try ReSharper. It does wrapping like this very well indeed. 😝

**Comment by tamlin-mike** [comment]
@Pilchie _and giant set of additional preferences_
Perhaps that's why f.ex. IDEA _have_ that giant set of options. Jetbrains invest development time to implement what customers want. Such customer care obviously raise the bar for the whole industry,  Microsoft included. Except... Microsoft isn't even willing to lift a finger to try to compete!

With that mindset, and Rider "just around the corner"...

**Comment by CyrusNajmabadi** [comment]
@tamlin-mike @DavidArno  PRs welcome :)

**Comment by jinujoseph** [comment]
@sharwell good to close this ?

**Comment by CyrusNajmabadi** [comment]
@sharwell @jinujoseph We could consider closing this now that we have a general wrapping-refactoring.  Future requests could just be about specific wrap areas we don't currently support.  I'd prefer that those come in with specific requests about those lang features.

**Comment by jinujoseph** [comment]
@alrz closing this issue as completed. let us know if you think otherwise
