### ISSUE TITLE
Flaky Interactive Integration Tests

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#18283]
The following tests have been failing (only one failed per build) in the latest debug integration test runs:

* [Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpInteractive.TypingHelpDirectiveWorks](https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_vs-integration/638/)
* [Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpSendToInteractive.ExecuteInInteractiveWithKeyboardShortcut](https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_vs-integration/639/)
* [Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpInteractiveCommands.CutDeletePasteSelectAll](https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_vs-integration/640/)

**Comment by 333fred** [comment]
FYI @dotnet/roslyn-infrastructure

**Comment by ivanbasov** [comment]
[Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpInteractiveCommands.CutDeletePasteSelectAll](https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_vs-integration/640/)
is flaky. Fixing it now.

Two others failures seem to be caused by Visual Studio crash between two integration tests. I assume that 
AddAssemblyReferenceAndTypesToInteractive and ResetInteractiveFromProjectAndVerify were root cause for the failures. Those tests executed fine but failed on the clean up. Then, succeeding tests fail. See the stack trace:

> Stacktrace

MESSAGE:
System.Runtime.Remoting.RemotingException : Failed to read from an IPC Port: The pipe has been ended.\r\n
+++++++++++++++++++
STACK TRACE:
Server stack trace: at System.Runtime.Remoting.Channels.Ipc.IpcPort.Read(Byte[] data, Int32 offset, Int32 length) at System.Runtime.Remoting.Channels.Ipc.PipeStream.Read(Byte[] buffer, Int32 offset, Int32 size) at System.Runtime.Remoting.Channels.SocketHandler.ReadFromSocket(Byte[] buffer, Int32 offset, Int32 count) at System.Runtime.Remoting.Channels.SocketHandler.Read(Byte[] buffer, Int32 offset, Int32 count) at System.Runtime.Remoting.Channels.SocketHandler.ReadAndMatchFourBytes(Byte[] buffer) at System.Runtime.Remoting.Channels.Tcp.TcpSocketHandler.ReadAndMatchPreamble() at System.Runtime.Remoting.Channels.Tcp.TcpSocketHandler.ReadVersionAndOperation(UInt16& operation) at System.Runtime.Remoting.Channels.Ipc.IpcClientHandler.ReadHeaders() at System.Runtime.Remoting.Channels.Ipc.IpcClientTransportSink.ProcessMessage(IMessage msg, ITransportHeaders requestHeaders, Stream requestStream, ITransportHeaders& responseHeaders, Stream& responseStream) at System.Runtime.Remoting.Channels.BinaryClientFormatterSink.SyncProcessMessage(IMessage msg) Exception rethrown at [0]: at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg) at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type) at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.VisualStudio_InProc.WaitForSystemIdle() at Microsoft.VisualStudio.IntegrationTest.Utilities.VisualStudioInstance..ctor(Process hostProcess, DTE dte, ImmutableHashSet`1 supportedPackageIds, String installationPath) at Microsoft.VisualStudio.IntegrationTest.Utilities.VisualStudioInstanceFactory.UpdateCurrentlyRunningInstance(ImmutableHashSet`1 requiredPackageIds, Boolean shouldStartNewInstance) at Microsoft.VisualStudio.IntegrationTest.Utilities.VisualStudioInstanceFactory.GetNewOrUsedInstance(ImmutableHashSet`1 requiredPackageIds) at Roslyn.VisualStudio.IntegrationTests.AbstractIntegrationTest..ctor(VisualStudioInstanceFactory instanceFactory, Func`2 textViewWindowBuilder) in q:\roslyn\src\VisualStudio\IntegrationTest\IntegrationTests\AbstractIntegrationTest.cs:line 25 at Roslyn.VisualStudio.IntegrationTests.AbstractInteractiveWindowTest..ctor(VisualStudioInstanceFactory instanceFactory) in q:\roslyn\src\VisualStudio\IntegrationTest\IntegrationTests\AbstractInteractiveWindowTest.cs:line 13 at Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpSendToInteractive..ctor(VisualStudioInstanceFactory instanceFactory) in q:\roslyn\src\VisualStudio\IntegrationTest\IntegrationTests\CSharp\CSharpSendToInteractive.cs:line 18


@dotnet/roslyn-infrastructure, @dotnet/roslyn-ide, do you have any idea how to approach proper cleanup/reset between integration tests?

**Comment by sharwell** [comment]
@ivanbasov I'm not sure how our test harness implements the current cleanup (specifically the one which is failing), but one important improvement we could make is updating the cleanup to execute at a point where it is captured as a failure of the preceding test (i.e. the cleanup code for a test executes prior to setting the final test result for that test).

**Comment by ivanbasov** [comment]
Agree with @sharwell. Created #18293. Thank you!

**Comment by TyOverby** [comment]
Here's another one: 

https://ci.dot.net/job/dotnet_roslyn/job/features_async-main/job/windows_debug_unit64_prtest/18/consoleFull#-19950339682d31e50d-1517-49fc-92b3-2ca637122019

**Comment by ivanbasov** [comment]
Renamed the current issue to cover integration interactive tests.
Moved CompilationChain_SubmissionSlotResize to a new issue: #18304
