### ISSUE TITLE
Complete list of .editorconfig supported names

### ISSUE THREAD

**Issue by angelsix** [dotnet/roslyn#18342]
I'm struggling to find any kind of complete list of supported values that can be used in VS .editorconfig file

I see a few sparse lists like https://github.com/dotnet/roslyn/pull/15029 and https://github.com/dotnet/roslyn/pull/15065 but thats about it.

I learn more of whats available from just looking at a config you guys created here https://github.com/dotnet/roslyn/blob/master/.editorconfig

Is there no documentation on the editorconfig support that isn't just a bunch of pull requests that shows a complete up-to-date list of supported values?

**Comment by Pilchie** [comment]
https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference is the documentation we already have for this, but it doesn't include formatting options, or naming styles yet.

**Comment by kuhlenh** [comment]
Yes this is on our radar, and we hope to get to it soon...

In the meantime, is there a specific rule you want to write that we can help you with?

**Comment by angelsix** [comment]
I managed to look at existing configs to figure out what I needed through trial and error. So I'm on now. I discovered a bug with namespaces though https://github.com/dotnet/roslyn/issues/18345

**Comment by nvankesteren** [comment]
I have the same issue. I disabled ReSharper to not interfere with my EditorConfig rules, but even then -through lots of trial and error- I'm beginning to make sense of where the Visual Studio settings end and where Code Analyzer rules begin.

I made a fresh new project, and turned off all code analyzer rulesets explicity. Then I began building up a root EditorConfig file, rule by rule. Turns out, for example, to get 'dotnet_style_object_initializer' to work, I have to reenable the code analyzer ruleset rule 'IDE0017' and have it set to 'hidden' for the EditorConfig rule to do its thing in Visual Studio 2017... Is this by design?

**Comment by kintar0** [comment]
@kuhlenh Is there a rule to replace consecutive empty lines with a single empty line?

**Comment by jmarolf** [comment]
>  I have to reenable the code analyzer ruleset rule 'IDE0017' and have it set to 'hidden' for the EditorConfig rule to do its thing in Visual Studio 2017... Is this by design?

@nvankesteren if you disable IDE rules you are disabling IDE functionality.  This is by design

**Comment by kuhlenh** [comment]
Hey all, I updated the documentation this August here: https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference. This is the complete official list for 15.3.
