### ISSUE TITLE
Generate Constructor: doesn't offer to pick base members for new location

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#18439]
We added a new location for triggering "Generate Constructor" when you are in the body of a class:
![image](https://cloud.githubusercontent.com/assets/1402694/24680661/a30df9bc-1946-11e7-8694-f88919430913.png)

However, if your class implements a base class, we don't offer to Generate Constructor with the base members, like we do if your cursor is in the declaration of your class:
![image](https://cloud.githubusercontent.com/assets/1402694/24680646/94e82010-1946-11e7-8f8b-c9f0ccadb48b.png)

I would suggest that we leave the bulb items as is, except in the Generate Constructor pop-up that appears, you can add all the base type members:
![image](https://cloud.githubusercontent.com/assets/1402694/24680799/3219a930-1947-11e7-9f4c-1b1a28b2fd95.png)

(so in the above screenshot, you would see the base type's ```DateTime date, TimeSpan duration, ...``` instead of just ```interval```)

**Comment by CyrusNajmabadi** [comment]
Do i did a little work here to see what we can do.  The problem is this:

Given a specific constructor we're generating in a derived type, there is a *lot* of flexibility, and little knowledge we could use to try to determine what to do here.  First, having the dialog show you members of the derived type is not really suitable.  Those members may not be writable, and may not have any relation to the base type constructor.  i.e. the base type may take in vastly different data to initialize these fields/properties (which are unrelated to its parameters).

really, what someone wants here is "initialize these fields with new parameters, but also take in the parameters necessary to call a specific base constructor."  This means several open questions:

1. how does the user pick which base constructor they want to call?  There could be many.  Do we expose all of them as options somehow?
2. if they do want to pass along parameters to the base, do those go in front of the parameters it is going to use, or after?

There's a fair amount of complexity here and not really great ways to show it to the user.  We'd need to do a lot of work to enable this and i'm just not seeing it as worth it.  

If you want to make a base-constructing constructor, you can do so from the squiggle.  You can then select specific fields/properties and ask to add them to the constructor you just made.

I feel like having these be individual steps seperates out all these concerns while still enabling the experience.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
