### ISSUE TITLE
CodeFix CS4033: Make method async (stay void) adds the Async suffix

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#18467]
From: https://developercommunity.visualstudio.com/content/problem/39889/codefix-cs4033-make-method-async-stay-void-adds-th.html

>The CodeFix CS4033 'Make method async (stay void)' adds the Async suffix to the methodname. If it stays void I don't want the Async suffix. Only when the methods returns a Task it must add this Async suffix to the name.

**Comment by Pilchie** [comment]
@kuhlenh @CyrusNajmabadi what do you think?

**Comment by Pilchie** [comment]
@MadsTorgersen @AnthonyDGreen @stephentoub do we have guidance here?

**Comment by CyrusNajmabadi** [comment]
I think we should not add 'Async'.   There's two types of 'async'.   

1. 'async' the keyword, which allows you to use 'await' in your body.  And
2. actually Task (or task-like) async, regardless of how you actually implement your body.

Your task/task-like methods should be called 'Async' to make it clear that these are Task returning and you should do something about that.  Something void, is not task-async, and only uses the 'async' keyword to enable usage of await.  As such, it name doesn't need to indicate that it is async.

Indeed, putting 'Async' as hte suffix seems wrong as the user may now wait to 'await' it, which they cannot.

**Comment by stephentoub** [comment]
I have mixed opinions here.

On the one hand, I like being able to look at a method and know whether it's going to have initiated work that may continue on beyond when it returns to me synchronously.  That gives me a very strong hint as to whether I can immediately use state that method may have had access to (e.g. a byte[] buffer I passed to it), or whether I need to worry about possible race conditions.  Naming a method with an Async suffix or a Begin prefix or some such thing, even if it's void returning, helps to highlight the forking nature of its functionality, regardless of whether it also provides a built-in way to join with it via its return value.  This has nothing to do with it being an `async` method that uses `await`... I'd say the same thing about any forking void-returning method, including one that just queues work with QueueUserWorkItem or some such thing.

On the other hand, I agree that there's a nice clarity that comes with expecting to be able to `await` most anything that has an Async suffix.  It's already not the case, due to some existing patterns that employed Async per my previous description (e.g. the Event-based Async Pattern), but the vast majority of public APIs in .NET do follow this, so it can generally be expected.

Given this, I personally prefer having the Async suffix even for non-awaitable return values (i.e. void), but I can see the opposing arguments and don't feel particularly strong about it.

**Comment by sharwell** [comment]
I'm in favor of keeping the `Async` suffix. A more appropriate way to avoid the suffix for this case is to remove `async void` methods from the code altogether.

**Comment by CyrusNajmabadi** [comment]
I don't feel strongly about this one way or the other.  And i like stephen's point that it still helps indicate to your caller that this isn't just a synchronous do-all-work-and-return method.

**Comment by CyrusNajmabadi** [comment]
Based on the three pieces of feedback i've heard, i'm going to consider this by-design for 'make async'.
