### ISSUE TITLE
IDE offers suggestion to "Inline temporary variable" where it results in a build error

### ISSUE THREAD

**Issue by debonte** [dotnet/roslyn#18504]
**Version Used**: 2.01.0.61520 (d15prerel 26404.00)

**Steps to Reproduce**:

This is similar to #3846, but results in a build error instead of a code behavior change, so perhaps Roslyn should be able to detect this scenario and not offer "Inline temporary variable"?

1. Create a blank C# console app
2. Add the following methods to the Program class:
```
public void Method(object value)
{
    string stringValue = value as string;
    if (stringValue != null || value == null)
    {
        DoSomethingWithStringsOrNull(stringValue);
    }
}

private void DoSomethingWithStringsOrNull(string stringValue)
{
}
```
3. IDE provides lightbulb to "Inline temporary variable" on stringValue in Method.  Use it

**Expected Behavior**: "Inline temporary variable" is not suggested because it will result in a build error.

**Actual Behavior**: Using "Inline temporary variable" results in build error CS0165 -- "Use of unassigned local variable 'stringValue'"

**Comment by Pilchie** [comment]
Hmm - I can't repro this.  It did the inline correctly for me.

In any case, our general design is *NOT* to block refactorings like this.  Once users know about them, they often want to do the refactoring even if it temporarily introduces a problem, because it's still a shortcut on the way to their final destination.
