### ISSUE TITLE
Make the Roslyn wiki editable by the public

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#18516]
The [Roslyn wiki](https://github.com/dotnet/roslyn/wiki) is woefully out of date and contradicts some of the documentation checked into Roslyn/master.  We should either delete this wiki or update it and make it possible for the community to submit PRs against it[ like what typescript has done](https://github.com/Microsoft/TypeScript-wiki).

**Comment by jaredpar** [comment]
My 2 cents: move it to mark down files in the doc folder and delete.  Making it public is not a good idea because it's too easy to abuse.  Or for even well intentioned developers to accidentally put up bad information.  

I still remember my horror when I got an email from a developer who appologized because they had deleted several pages from my VsVim WIKI.  I was able to recover but then looking through I found tons of edits I'd never known about (some good, some bad).  Had to make it read-only because there's really no other option.

**Comment by tmat** [comment]
I keep Scripting and ENC up to date. If we move it elsewhere we should add links to the new location.

**Comment by tmat** [comment]
The benefit of wiki is that updates don't go thru Jenkins.

**Comment by jmarolf** [comment]
Typescript has a public github repo that people can submit pull requests to (https://github.com/Microsoft/TypeScript-wiki) that they then push to the github wiki site (https://github.com/Microsoft/TypeScript/wiki).

**Comment by jasonmalinowski** [comment]
I think the TypeScript approach is probably a good thing to do. I'm in favor of moving docs to branches when there is branch-specific docs, but there's a few things that shouldn't be in branch docs because people will be looking at the wrong branch. For example, how to pick which branch you should be contributing too. :smile:

**Comment by RikkiGibson** [comment]
The wiki has been moved to be in-repo so I think this issue has been resolved.
