### ISSUE TITLE
Symbols are not been published to the internal symbol server

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#18592]
Unlike the rest of Visual Studio, Roslyn symbols are not being published to the internal symbol server and hence you cannot debug Roslyn binaries simply by pointing to it.

**Comment by davkean** [comment]
@jasonmalinowski Are you aware of this?

**Comment by jasonmalinowski** [comment]
@davkean: We are (in general) indexing symbols. Looking at builds this morning indexing is happening. We do know that the particular build that is in vsumain as of this writing wasn't retained due to a bug in our build retainment logic; that bug has since been fixed.

In general, our request for any reports like this is to point to the VS build you're not getting symbols for so we can chase down the problem since there's four or five pieces in the chain, and sometimes a particular piece breaks down for specific builds. For example, we've seen at least one case where the indexing job was sent to the index server, it said it was indexed, and just forgot about the binaries and symbols after that point. :-)

**Comment by davkean** [comment]
I don't have symbols for this build:

```
Version 15.2 (26410.1-Preview) vsuwpt vsuwpt
VisualStudio.15.int.vsuwpt/15.2.0-Preview+26410.1.vsuwpt
```

**Comment by jasonmalinowski** [comment]
@davkean: yep, that's pointing to the specific build that we lost. We have just delivered a new build to vsumain, so at this point my advice (which I fully admit isn't good) is to consider pulling those changes in. If that's not an option then @natidea could do a one-off insertion into your branch if you feel that would help.

**Comment by natidea** [comment]
vsuwpt is locked right now, so that's not an option either unfortunately

**Comment by davkean** [comment]
Nah, I ended up building Roslyn myself. If this is just one build, I'll close it.
