### ISSUE TITLE
Spell checker doesn't run on explicit interface implementations

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#18626]
_From @davkean on April 12, 2017 5:15_

``` C#
using System.Collections;
using System.Threading.Tasks;

namespace ConsoleApp282
{
    public interface IProjectConfigurationsService
    {
          void Method();
    }

    class Program : IProjectConfigurationsService
    {
        void IProjectConfigurationService.Method()
        {

        }
    }
}

```
1. Attempt to CTRL+. on IProjectConfigurationService in the interface implementation

Expected: To get spell checker to change `IProjectConfigurationService` to `IProjectConfigurationsService`
Actual: Don't get spell checker results

Note I do get add using results in the same position if the problem is just that the namespace is not imported.

_Copied from original issue: dotnet/project-system#1975_

**Comment by CyrusNajmabadi** [comment]
This happens because this is not an area where we offer completion.  If we make a completion provider that suggests explicit interface type-names after you type the return type of a member, then this should light up.

Note: if we do make a completion provider for this, it will need to always be in suggestion mode, as this is a locatoin where a member name can be written.

**Comment by Pilchie** [comment]
Actually I think we *do* get name suggestions now in suggestion mode, but they will be too far from the spell check results.

Given that we will now always be showing a list in this context anyway, it does make sense to show interface names of interfaces that the current type implements.

**Comment by CyrusNajmabadi** [comment]
I agree.  It's something i could whip in quickly if you want.
