### ISSUE TITLE
Provide a way for Razor completion providers to not be loaded for normal C# documents.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#18650]
Razor would like to be able to provide specific types of completion when in a cshtml file.  For example, offering "import" after an "@" token.  At the point where @ is written, this will now be a C# document, so it would be clean for there just ot be customer C# completion provider that handles this case (provided by razor).

However, it would be bad to load this completion provider in a normal C# scenario as it could end up loading lots of razor dlls inappropriately in non-web scenarios.  

So we need a way to export these completion providers such that they are not actually loaded for non-applicable documents.  One possibility for this would be to have some mef way for a provider to specify the extensions or content-types that it applies to.  TBD what the right approach is.

**Comment by CyrusNajmabadi** [comment]
Tagging @Pilchie @toddgrun @jasonmalinowski

**Comment by madskristensen** [comment]
We would like this for 15.4. The change is important so Razor can provide Intellisense for Razor directives which is a highly requested feature. The lack of the feature makes the Razor editor seem broken and incomplete and we've received many many bugs on it from users

**Comment by dpoeschl** [comment]
FYI @AmadeusW -- it looks like we need a way for Razor completion to happen in C# buffers, but only on .cshtml files. That is, we may need to allow providers to (optionally, probably) specify extensions in their mef export.

**Comment by sharwell** [comment]
@dpoeschl Extensions are bad for this. It should be a separate derived content type instead.

**Comment by jasonmalinowski** [comment]
I wonder if the right design here is that Razor can export the provider on the surface buffer, and Roslyn can export ours on our C# buffer, and the intellisense API we're designing should just request both and merge both. Arguably, the fact that "import" after @ is a valid syntax is valid not in C#, but in the surface razor buffer and so that's exactly the level it should be applied at. This would be somewhat consistent with how other things get merged for projection scenarios like tags. Then Roslyn is out of the whole business altogether.

**Comment by dpoeschl** [comment]
@NTaylorMullen We plan to use your linked issue to track this work going forward. Let us know if you need us to keep this one open for whatever reason.
