### ISSUE TITLE
Hanging BasicReferenceErrors Test

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#18676]
BasicReferenceErrors hung during a test run on https://github.com/dotnet/roslyn/pull/18646.

Screenshot:
![pasted image at 2017_04_13 10_31](https://cloud.githubusercontent.com/assets/2371880/25017036/21912b8c-2037-11e7-8b71-3207876bfe3f.png)

Dump and pdbs: "\\mlangfs1\public\frsilb\dumps\devenv_referenceerrors_hang.dmp"

Assigning to @jmarolf.

**Comment by Pilchie** [comment]
Tagging @CyrusNajmabadi as I think that assert is his.

**Comment by 333fred** [comment]
Updated the image, now not sized for ants and with less jpg!

**Comment by CyrusNajmabadi** [comment]
Sorry, i can't read the assert!

**Comment by 333fred** [comment]
@CyrusNajmabadi just updated it

**Comment by CyrusNajmabadi** [comment]
Ah, i see it now :)  yes, that's bad.  Will look when i get into the office.

**Comment by CyrusNajmabadi** [comment]
Hey Fred, so a small problem: the assert is coming from *another* process.  Specifically the OOP process.  We'd have to capture a dump of that to get good info.  In the meantime, i've made https://github.com/dotnet/roslyn/pull/18681 so that we no longer assert, but instead report an NFW.  This should help unblock tings, while still allowing us to collect information to address this problem.

**Comment by CyrusNajmabadi** [comment]
This should be addressed by https://github.com/dotnet/roslyn/pull/18681   It should at least stop the hang.

**Comment by Pilchie** [comment]
It occurred to me that we have an `AssertListener` for unit tests that logs the assert and fails the test instead of displaying a dialog.  I guess it's not hooked up in the VS process during integration tests though, which we should do.
