### ISSUE TITLE
Using System.Linq Select w/ Named ValueTuple Variables causes .Net Native Compilation Errors

### ISSUE THREAD

**Issue by WilliamABradley** [dotnet/roslyn#18737]
After Hours on Hours of combing through my over 50,000 lines of code and trying different conditions after days on days of confusion, I discovered an issue with the ValueTuple that caused my app to fail to compile in .Net Native.

I managed to replicate it in the solution below.

**Version Used**: 
System.ValueTuple 4.3.0
Microsoft.NETCore.UniversalWindowsPlatform 5.3.2

**Steps to Reproduce**:

```C#
        public static void TupleTest(IEnumerable<(int name1, int name2)> testSubjects)
        {
            var result = testSubjects.Select(item => (item.name1, item.name2, 3));
        }

        //comment out the first method, and this one will compile just fine
        public static void WorkingTupleTest(IEnumerable<(int, int)> testSubjects)
        {
            var result = testSubjects.Select(item => (item.Item1, item.Item2, 3));
        }
```

**Expected Behavior**:
Produces a list of new Tuples with 3 Int Values out of a list of 2.

**Actual Behavior**:
`C:\Program Files (x86)\MSBuild\15.0\.Net\.NetNative\15.0.24211\x86\ilc\IlcInternals.targets(936,5): error : Internal compiler error: Object reference not set to an instance of an object.`

**Comment by WilliamABradley** [comment]
[TupleLinqIssue.zip](https://github.com/dotnet/roslyn/files/924190/TupleLinqIssue.zip)

Here is the Solution that I used to replicate the issue.

**Comment by jcouv** [comment]
@WilliamABradley Thanks for reporting this. Sorry for the trouble.
Let me try to repro with the project file you provided. The failure didn't include a stacktrace, by any chance? I'll get back to you if I have additional questions.

**Comment by jcouv** [comment]
The probject built fine for me. Here's the VS information for my setup. I'll try a different one tomorrow. Could you share yours as well (from Help > About ... menu)?

```
Microsoft Visual Studio Enterprise 2017
Version 15.1 (26403.0) Release
VisualStudio.15.Release/15.1.0+26403.0
```

**Comment by CyrusNajmabadi** [comment]
tagging @tmeschter as he might have some .Net Native insight.

**Comment by BattleRush** [comment]
@jcouv I was able to replicate this error (with the download from the comments)

Microsoft Visual Studio Community 2017 
Version 15.1 (26403.3) Release
VisualStudio.15.Release/15.1.0+26403.3

In Debug mode it builded just fine but in Release mode I received the exception shown in the post.

Commenting out the TupleTest method would also let me build in Release mode.

**Comment by WilliamABradley** [comment]
Mine happened on VS Community 2017 (15.1 26403.3), with .Net Native Compiler 1.6.1 & 1.6 & .Net Native 15.0.24211.

**Comment by jcouv** [comment]
Thanks. I can repro with Release mode.

The problem seems to be in `ILTransformTask`. I'll ping some .NET Native folks for assistance.

```
1>  Starting .NET Native compilation
1>  Processing application code
1>  Computing application closure and generating interop code
1>  Generating serialization code
1>  Compiling interop code
1>C:\Program Files (x86)\MSBuild\15.0\.Net\.NetNative\15.0.24211\x86\ilc\IlcInternals.targets(936,5): error : Internal compiler error: Object reference not set to an instance of an object.
```

```
1>  Running 'DisableOptimization' transform, heap at 129 MB. (TaskId:264)
1>  Running 'CreateMetadata' transform, heap at 129 MB. (TaskId:264)
1>C:\Program Files (x86)\MSBuild\15.0\.Net\.NetNative\15.0.24211\x86\ilc\IlcInternals.targets(936,5): error : Internal compiler error: Object reference not set to an instance of an object.
1>  Done executing task "ILTransformTask" -- FAILED. (TaskId:264)
```

**Comment by jcouv** [comment]
@WilliamABradley I talked with the .NET Native folks today and this hit a known issue. 
The C# 7.0 compiler makes use of `null` strings in attributes for tuple names, which the .NET Native toolset cannot properly serialize to metadata.
One example is `[TupleElementNames(new string[] {"name1", "name2", null, null})]`.

This was already fixed in the next major release of .NET Native (which I could not find any announced dates for yet).
In the meantime, the only known workaround is to avoid tuple names in your code. 

Also, we are investigating a short(er)-term mitigation for dev15.3: not serializing this specific attribute into native metadata format. I'll keep this issue updated once I get more details.

As a side-note, I filed a follow-up issue to increase our systematic validation of C# compiler in integration with .NET Native (https://github.com/dotnet/roslyn/issues/18754).

**Comment by WilliamABradley** [comment]
@jcouv Perhaps a more Verbose Error message next time :) I originally thought it was an issue with EFCore, and after copying my code into a new project, and then disabling and re-enabling parts of the project all over for hours on end, I finally stumbled upon it.

**Comment by ljw1004** [comment]
@jcouv I wonder is there *every* any good reason to serialize this attribute in .NETNative? I think the attribute is solely used for compile-time assistance (produce errors, provide intellisense) and never affects the runtime semantics of the code. Moreover, if someone is digging through this attribute at runtime, then they're doing something genuinely goofy.

**Comment by jcouv** [comment]
@ljw1004 I agree. I'm hard-pressed to think of a scenario where tuple names are useful through runtime reflection.

**Comment by tmat** [comment]
@ljw1004 How about the debugger?

**Comment by jcouv** [comment]
@tmat I think the debugger gets tuple names from PDBs. I assume that's also the case in .NET Native stack.

**Comment by tmat** [comment]
@jcouv Only for local variables, because those can't have metadata attributes. For return values, parameters, field types, etc. it decodes the metadata attributes.

**Comment by ljw1004** [comment]
The expected scenario is you use CoreCLR for debugging (where you get a good debug experience) and .NETNative for release builds. There are many reasons why .NETNative has worse debugging experience than CoreCLR -- it feels like it'd be going against the tide and the goal of the project to enlarge metadata solely to provide better debugging in .NETNative...

**Comment by jcouv** [comment]
@ljw1004 Just to be clear, not producing this metadata would be a short-term fix that would be reverted at the first opportunity (ie with the next shipping window for shared framework). 
I think it is preferable for metadata to be degraded in the interim rather than let the compilation fail, this can be reverted once the full fix (which is already checked in to .NET Native and shared framework) will ship.

@MichalStrehovsky can confirm that matches his plan.

**Comment by ljw1004** [comment]
@jcouv why? I think the correct long-term strategy should be NOT to include this metadata in the binary, in order to keep sizes down...

**Comment by jcouv** [comment]
Sorry, I had misunderstood your concern. 
@MichalStrehovsky, what do you think of making the short-term workaround (not serializing tuple names attribute in .NET Native) permanent?

**Comment by MichalStrehovsky** [comment]
> what do you think of making the short-term workaround (not serializing tuple names attribute in .NET Native) permanent?

We haven't been making decisions about what public custom attribute types should be visible to reflection and blacklisting ones that we consider "unnecessary". Maybe someone who writes a DLR-like environment on top of reflection would still want to see them. Does `dynamic` keyword consume them, for example?

What you can already do in .NET Native is not generate reflection metadata for the entire thing that has the attribute - if you never want to reflection invoke a method, don't generate metadata for the entire method and none of the attributes on parameters, return types, etc. will be generated either. The runtime doesn't need the reflection metadata to operate (because everything already got compiled to native code). The only thing that needs the reflection metadata is the reflection stack itself.

The reflection metadata emission can be controlled using [Runtime Directives](https://msdn.microsoft.com/en-us/library/dn600639(v=vs.110).aspx). The default.rd.xml file (that is part of all new UWP app projects) specifies to retain reflection metadata for everything in the user's app (because it's the most compatible thing to do since reflection usage is really hard to predict). The file can be updated not to do that. (It might be a possible workaround for this issue too, but it comes with potential time investment required to create a more tailored RD.XML for that specific apps reflection use).

**Comment by jcouv** [comment]
Note to self: this is tracked on .NET Native in VSO 409209. Still scheduled for dev15.3.

**Comment by jcouv** [comment]
@MichalStrehovsky just checked in the .NET Native short-term fix. Thanks!
Michal, let me know if I should file a follow-up issue to undo this (moving to long-term solution).

@WilliamABradley Thanks for reporting the problem.
I'll go ahead and close OP as fixed. The fix will ship with Visual Studio 2017 version 15.3.

**Comment by MichalStrehovsky** [comment]
> Michal, let me know if I should file a follow-up issue to undo this 

No need to follow up. There are two fixes:

1. Our mainline branch has the full fix (https://github.com/dotnet/corert/commit/b5b11ab9fd71022377bbfeadc0cf6ae4178ef757). It will ship in the next .NET Native major release.
2. The short-term fix was checked in to the .NET Native 1.6 servicing branch and will ship soon-ish. The exact scheduling and versioning to be announced later.
