### ISSUE TITLE
Two Errors.vb in Solution Explorer?

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#1876]
VS2015 + Roslyn Solution

Does anyone see two `Errors.vb` in the solution explorer?
![vs2015_2_errors](https://cloud.githubusercontent.com/assets/900107/7058497/88ab61f0-de5a-11e4-8a7f-b0cf9f759a92.jpg)

**Comment by Pilchie** [comment]
Yes, I see too.  It's by design.  This happens because Errors.vb is included in two different ItemGroups in the .vbproj.  If you open the Properties Window, you can see that one of them has Build Action set to Compile and the other to "ErrorCode".

I'll add some metadata to make the "ErrorCode" one not display in Solution Explorer.

**Comment by Pilchie** [comment]
Can you verify this?
