### ISSUE TITLE
Microsoft.CodeAnalysis.Differencing.Match makes not optimal matches

### ISSUE THREAD

**Issue by ivanbasov** [dotnet/roslyn#18801]
Consider two switch statements:
1. Before:
```
case Point p: ...
case Circle c: ...
```
2. After:
```
case Circle c1: ...
```
We expected to match "case Circle c: ..." vs. "case Circle c1: ...". However, the distance between these nodes is  0.15. Also the distance between "case Point p: ..." vs. "case Circle c1: ..." is 0.4.

Then, consider that following thresholds defined in Match.cs: 10E-5, 0.5, 1, 1.5 and 2.

The first iteration of matching skips both items. However, the second iteration of matching will match 
"case Point p: ..." vs. "case Circle c1: ..." because this is the first pair below the threshold of 0.5. After that the expected pair will be skipped.

It sounds reasonable to match pairs ordered by distance. The algorithm seems to be O(n1 * n2). However we should keep the first pass, which is the almost exact match, as "linear" (n1 + n2).

Playing with threshold values can be a workaround but there can be closer distances.

**Comment by sharwell** [comment]
@ivanbasov Can you clarify that my interpretation of the current and expected behavior is correct?

**Input:**

```patch
-case Point p: ...
-case Circle c: ...
+case Circle c1: ...
```

**Current behavior:**

The difference shows this as two lines getting removed, and a new line getting added which is unrelated to either of the previous lines.

**Expected behavior:**

The difference shows as one line getting removed, and a second line getting modified by just the addition of a character `1`.

**Comment by ivanbasov** [comment]
Thank you, @sharwell!

**Input:**

```patch
switch(shape)
{
-    case Point p: return 0;
-    case Circle c: return 1;
+    case Circle circle: return 1;
}
```

**Current behavior:**

The match shows that the first line was edited and the second line was removed.

**Expected behavior:**

The match should show that the first line was removed and the second line was edited.
