### ISSUE TITLE
Don't show "Object initialization can be simplified" for ExpandoObject

### ISSUE THREAD

**Issue by hughbe** [dotnet/roslyn#18847]
**Version Used**: 
Microsoft (R) Visual C# Compiler version 2.0.0.61501

**Steps to Reproduce**:

Click lightbulb on `new ExpandoObject`

```cs
dynamic d = new ExpandoObject();
d.Date = DateTime.Now;
```

**Expected Behavior**:

IDE 0017 not shown.

**Actual Behavior**:

Results in code that doesn't compile:
```cs
dynamic d = new ExpandoObject()
{
    Date = DateTime.Now
};
```

> error CS0117: 'ExpandoObject' does not contain a definition for 'Date'

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/17860

**Comment by miloush** [comment]
I wonder whether the initializer shouldn't be a supported syntax too, and the bug in the compiler not realizing the object with initializer is dynamic?

**Comment by CyrusNajmabadi** [comment]
The copiler is doing hte right thing, it rewrite the above int:

```c#
ExpandoObject __someTempName = new ExpandoObject();
__someTempName.Date = DateTime.Now;
dynamic d = __someTempName;
```

This is as per the language spec, and is really what you want.  Otherwise, if you used the type on the left, all sorts of strange differences could happen (including not seeing properties that hsould be there, not being able write into assignable fields/props, because you'd be looking at an interface, etc. etc.)
