### ISSUE TITLE
Intellisense failure for await in non-async method (regression from VS2013)

### ISSUE THREAD

**Issue by ljw1004** [dotnet/roslyn#1884]
**Summary** VS2015 C# intellisense fails to show intellisense for the result of an await operator in a non-async method. VS2015 VB intellisense fails to colorize await in a non-async method, fails to show intellisense for the await operand, and fails to show intellisense for the result of the await operator. These four bugs are all regressions from VS2013 and break muscle memory.

**Detail**

It's a typical scenario to use "await" in a non-async method. For instance, you double-click on a button to edit its Click handler, then you start typing away, then you use an await, then you Ctrl+Dot to do the quickfix "mark method as async". Folks have learned this as muscle-memory. To support this, we should be doing three things:

[1] colorize "await" blue as an operator, optimistically, even in a non-async method, since 99.9% of the time you wanted to use the await operator and you're going to mark the method async within a few seconds.

[2] provide expression-intellisense after the "await"

[3] provide intellisense for the return-value of the await operator.

SCORECARD:
VS2013 did almost all perfectly (except it failed to do [1] for C#)
VS2015 fails to do [1,2,3] for VB, and fails to do [3] for C#.

I've attached some screenshots for illustration...

VS2013 VB does [1,2,3] correctly:
![vs2013-vb-1](https://cloud.githubusercontent.com/assets/3316258/7063634/3330ad3e-dea0-11e4-8328-3214f8fe5e2f.png)
![vs2013-vb-2](https://cloud.githubusercontent.com/assets/3316258/7063633/332cbe22-dea0-11e4-866a-5f181d8c4f3c.png)

VS2013 C# does [2,3] correctly but fails [1]
![vs2013-cs-1](https://cloud.githubusercontent.com/assets/3316258/7063635/3338e79c-dea0-11e4-8d17-606a71a9ba8e.png)
![vs2013-cs-2](https://cloud.githubusercontent.com/assets/3316258/7063636/33412ac4-dea0-11e4-8296-a18b13a105e5.png)

VS2015 VB does nothing right. It even gets indentation wrong.
![vs2015-vb-1](https://cloud.githubusercontent.com/assets/3316258/7063637/33451d82-dea0-11e4-8e0e-a71ce5ff9731.png)
![vs2015-vb-2](https://cloud.githubusercontent.com/assets/3316258/7063638/334808d0-dea0-11e4-9199-81820a03f79a.png)

VS2015 C# does [1,2] right but fails [3]
![vs2015-cs-1](https://cloud.githubusercontent.com/assets/3316258/7063639/334a5afe-dea0-11e4-9a8d-94767fc44a87.png)
![vs2015-cs-2](https://cloud.githubusercontent.com/assets/3316258/7063640/334e0d0c-dea0-11e4-857f-5bc774ebd694.png)

**Comment by gafter** [comment]
@Pilchie Can you please describe the compiler issue you ascribe this behavior to, and how it could be changed to improve things?

**Comment by Pilchie** [comment]
@gafter I think there are 3 compiler issues here (which we can split out into different issues if you want), and 1 IDE issue.

Compiler Issues:
=============

1. In a C# method without `async`, fault tolerance doesn't understand the result type of an `AwaitExpressionSyntax`, even though it parses fine.
2. In a VB `Sub` or `Function` without `Async`, the parser falls apart after `Await`, such that the remaindder of the expression marked as skipped tokens trivia, instead of being parsed as an `AwaitExpressionSyntax` anyway.  This prevents IntelliSense from showing anything in the expression part after `Await`, because `LookupSymbols` doesn't return anything in the skipped tokens.
3. Assuming 2 is fixed, then the same problem as 1 would presumably happen for VB.

IDE Issue:
========
`await` and `Await` should be optimistically classified as keywords immediately after they are typed in an expression context, without waiting for the parser to recognize them as being part of an await expression. (I've filed #2301 to track this part).

**Comment by sharwell** [comment]
@jaredpar I hit the items described in this issue fairly frequently. Reopening to track as an IDE bug.

**Comment by jaredpar** [comment]
@sharwell please confirm with your lead before reactivating. We've been given pretty explicit instructions on how to handle stale issues.

**Comment by ljw1004** [comment]
I personally feel strongly about this one :)

**Comment by CyrusNajmabadi** [comment]
c# appears to do 1, 2 and 3:

![image](https://github.com/dotnet/roslyn/assets/4564579/09b1ab73-c3fb-480d-a52b-4c74f1a2e259)
