### ISSUE TITLE
Excess Variables in Tuple Decomposition

### ISSUE THREAD

**Issue by merthsoft** [dotnet/roslyn#18916]
**Version Used**: 
2.1.0.61520 (just installed 2017 tonight, and that's what comes up when I do csc)

**Steps to Reproduce**:

Playing with Tuples I wrote this code:

```C#
private static (decimal, string) Add((decimal a, decimal b) input) {
    decimal v = input.a + input.b;
    return (v, v.ToString());
}

private void updateEqualsText() {
    (var _, var text) = Add((numericUpDown1.Value, numericUpDown2.Value));
    textBox1.Text = text;
}
```
On decompiling with ILSpy, I see that it generated this code:

```C#
private void updateEqualsText()
{
	ValueTuple<decimal, string> expr_20 = Adder.Add(new ValueTuple<decimal, decimal>(this.numericUpDown1.Value, this.numericUpDown2.Value));
	decimal item = expr_20.Item1;
	string item2 = expr_20.Item2;
	string text = item2;
	this.textBox1.Text = text;
}
```

It seems `item` and `item2` are both not needed, and this could be optimized to:

```C#
private void updateEqualsText()
{
	ValueTuple<decimal, string> expr_20 = Adder.Add(new ValueTuple<decimal, decimal>(this.numericUpDown1.Value, this.numericUpDown2.Value));
	string text = expr_20.Item2;
	this.textBox1.Text = text;
}
```
When making a smaller example, I came up with this:

```C#
    class Program {
        private static (int, string) Add((int a, int b) input) {
            int v = input.a + input.b;
            return (v, v.ToString());
        }

        static void Main(string[] args) {
            (var _, var text) = Add((10, 10));
            Console.WriteLine(text);
            Console.ReadKey();
        }
    }
```

Which actually does optimize this, though keeps `item`:

```C#
private static void Main(string[] args)
{
	ValueTuple<int, string> expr_0E = Program.Add(new ValueTuple<int, int>(10, 10));
	int item = expr_0E.Item1;
	string item2 = expr_0E.Item2;
	Console.WriteLine(item2);
	Console.ReadKey();
}
```

I'd expect, especially when the variable name is `_`, that it wouldn't need to generate unused variables.

**Comment by jcouv** [comment]
There was a significant re-work of deconstruction after VS2017 shipped (see PR https://github.com/dotnet/roslyn/pull/17027), which led to fewer temporaries being used and also not instantiating ValueTuple in a number of scenario. This will ship in dev15.3.

I put your [code sample into TryRolsyn](https://tryroslyn.azurewebsites.net/#b:master/LAKADgrgRgNglgYwAQJgQwM4aQYSQb1CWKTACc4A3NAFwFMkMbbEkAKAEzoTgFs0YAGkY0KAOwDmASiQBBDhzadufAUjTCuPfjCRQZcMZBoyiJQiBJIAkFtW7KSALxJDxgHRokAaldGINO5QANxmxNZkdDQQZGLslMKU7gAqAPYAyqKGEmxSUqEg1gC+oKDW5FS0DJSpcBxIEGAcVQCiAI4QAhjJdAAeNLlIYQTD1mzUZEgA+olok/T9Mi7yimwA4lEAagIQdMIbNNswu3kFVlbpAJ5MdLzuOKliGKkwdO4A6hT0bAsmZyQlSwkYYVaj0JB2HRIA5HXbOAB8SAAjAUikA===). The `master` branch is selected and the output decompiles to `C#` (as ILSpy does).
As you can see, the number of variables was significantly reduced. And there is no variable introduced for the discard in this scenario.
That said, there may be other discard scenarios that could be further optimized, such as https://github.com/dotnet/roslyn/issues/15437.

 I'll go ahead and close this issue as fixed. Feel free to ping me if the problem was not adequately resolved. 
Thanks for reporting the issue and in great/clear details.

**Comment by merthsoft** [comment]
Oh, awesome! Thanks for the info!
