### ISSUE TITLE
Improve resource management in OOP communication layer

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#18935]
**Version Used**: Latest master branch

**Steps to Reproduce**:

1. Launch Roslyn under the debugger in an experimental instance
2. Open **Roslyn.sln** in the experimental instance

**Expected Behavior**:

* The OOP communication layer cleanly cancels connections

**Actual Behavior**:

* Exceptions of type `ObjectDisposedException` are regularly seen.

**Additional Details**:

1. The StreamJsonRpc library provides asynchronous methods which take a `CancellationToken`. These methods are not currently used, and Roslyn is relying on calling `Dispose` on the RPC instance to side-step the normal cancellation approach.
2. Roslyn is not waiting for outstanding connections to be cancelled prior to disposing of the host.
3. As mentioned by @CyrusNajmabadi in #18887, the streams created during initialization of the session will not be disposed in some exceptional scenarios. When proper resource management is implemented in the communication layer, these should be cleanly disposed in exceptional scenarios (including cancellation).

**Comment by Pilchie** [comment]
@heejaechang was just in a discussion with @AArnott about this I think.

**Comment by AArnott** [comment]
Yes we did. It was in regards to [Bug 411573](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/411573?fullScreen=false): Servicehub.client is using streamingjsonrpc and throwing 9700 exceptions of “The semaphore has been disposed”

**Comment by heejaechang** [comment]
our code is written before StreamJson added support to CancellationToken. they added support but we didn't move to the new support since our cancellation is on session itself, but added support is per InvokeAsync.

so, moving to it require some changes in our side. right now, just moving to it means, it used to throw ObjectDisposed exception and now it throws RemoteInvocation exception (that is what StreamJson throws when cancellation token is raised).

it gives us a benefit only if we change our code to take advantage of reusing connections which is not how things were designed. so require quite a bit of change. so right now, moving to new API doesn't give us a lot of benefit yet. so that is why we didn't adapt the new API.

anyway, leaking Pinned Snapshot has nothing to do with ObjectDisposed exception StreamJson is throwing. if we are not translating ObjectDisposed exception to Cancellation exception properly or leak Pinned Snapshot that are just its own bug.

**Comment by heejaechang** [comment]
this is done.
