### ISSUE TITLE
Lambdas throwing exception infer to Func<object> overload instead of Action

### ISSUE THREAD

**Issue by krwq** [dotnet/roslyn#18952]
**Version Used**: 
Whichever ships with VS 2017 (15.0.0+26228.9.d15rtwsvc) when creating .NET Framework project - also repros on .NET Core

**Steps to Reproduce**:
```csharp
        static void Test(Func<object> foo)
        {
            Console.WriteLine("Test(Func<object> foo)");
        }

        static void Test(Action foo)
        {
            Console.WriteLine("Test(Action foo)");
        }

        static void Main(string[] args)
        {
            Test(() => { throw new InvalidOperationException(); });
        }
```

**Expected Behavior**:
```
Test(Action foo)
```

**Actual Behavior**:
```
Test(Func<object> foo)
```

If this is by design I'd like to understand it.

**Comment by jaredpar** [comment]
This behavior is indeed by design. The reason why is multi-part. The first is the structure of the lambda expression itself. 

```csharp
() => { throw new InvalidOperationException(); }
```

This lambda does not return because it has an unconditional throw. This means the method never actually returns. As such it can convert to delegates that have any return type. That means the conversion to `Action` and `Func<object>` are both valid. 

This may seem strange at a glance but it's a long standing behavior of C#. Consider that a method body, all the way back to C# 1.0, can be simply `throw new Exceptionl` no matter the signature of the method. requires a return, has `out` parameters, etc ... 

Given that behavior it's down to which conversion is _better_. In this case the compiler considers the delegate with a return type  to be _better_ than the one without a return type. Together these behaviors mean that overload resolution picks `Test(Func<object>)`. 

Even though this is by design, I do agree it's not intuitive. So much so that when I hit this a few years ago it took me a few hours to track down and I eventually wrote a [blog post](https://blog.paranoidcoding.com/2015/02/23/curious-case-of-task-run.html) about it. At the same time though it is a long standing behavior of the language.
