### ISSUE TITLE
Warning when comparing IntPtr/UIntPtr with null (and for other value types)

### ISSUE THREAD

**Issue by xanatos** [dotnet/roslyn#18975]
If you write:

```
int a = 0;
if (a == null) {}
```

you get a warning *CS0472 The result of the expression is always 'false'*.

If you do the same with *IntPtr* you don't get a warning:

```
IntPtr d = IntPtr.Zero;
if (d == null) {}
```

The same seems to happen for all the non-primitive value types, like

```
DateTime c = DateTime.MinValue;
if (c == null) {}
```

(no warning)

I think it would be better if the compiler returned the warning when comparing *null* with non-nullable value types.

(for the specific bug for *IntPtr*, I had an instance where I had to lose an afternoon finding an error that was a *if (someIntPtr == null)* instead of being *if (someIntPtr == IntPtr.Zero)*.)

**Comment by BattleRush** [comment]
I assume this has to do with the stack/heap memory management.
While int is being stored in the stack with the value, the others(IntPtr, DateTime) are stored in the stack/heap memory but with a pointer to the heap memory that contains the value. 
You could change the value of a heap memory, without modifying the pointer to the memory address.

In short you can change int only directly by modifying its value.
For IntPtr/DateTime you can change the value, without modifying the variable, so "The result of the expression is always 'false'/'true'." could not be said.

**Comment by KrisVandermotten** [comment]
At first I was thinking that a warning is not shown because `IntPtr` has an overloaded == operator ([Reference Source](https://referencesource.microsoft.com/#mscorlib/system/intptr.cs) line 218). An overloaded operator could indeed implement semantics for comparing with `null`.

But then I realized that the overloaded operator is not used for `someIntPtr == null`, because it takes two `IntPtr` arguments. So indeed, I see no reason why the compiler could not issue this warning.

**Comment by sharwell** [comment]
I believe Roslyn originally did produce this warning. However, it turned out that it broke real-world projects that were using warnings-as-errors and was permanently removed prior to Visual Studio 2015's release. @jaredpar can provide details regarding whether this is accurate, and also whether or not there remains a way to manually enable this warning.

**Comment by jaredpar** [comment]
@sharwell is correct.  The warning is limited to primitive types due the large base of customer code which depended on this warning not firing in versions 3 - 5 of C#.  Here is actually where we implement it 

https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Portable/Lowering/DiagnosticsPass_Warnings.cs#L789

**Comment by sharwell** [comment]
@xanatos You can get this warning by enabling the `strict` feature for your project, by adding the following to the `<PropertyGroup>` at the top of your project file:

```
<Features>strict</Features>
```
