### ISSUE TITLE
IDE0004 "Cast is redundant" when casting `object[]` to `object` calling a method that takes `params object[]` changes behavior

### ISSUE THREAD

**Issue by jlennox** [dotnet/roslyn#18978]
**Version Used**: VS2017 15.1 (26403.7)

**Steps to Reproduce**:
```
public static void Main(string[] args)
{
    var takesArgs = new[] { "Hello", "World" };
    TakesParams(takesArgs);
    TakesParams((object)takesArgs);
}

private static void TakesParams(params object[] foo)
{
    Console.WriteLine(foo.Length);
}
```

This correctly prints:
>2
>1

Following the "Cast is redundant" refactoring:
```
public static void Main(string[] args)
{
    var takesArgs = new[] { "Hello", "World" };
    TakesParams(takesArgs);
    TakesParams(takesArgs);
}

private static void TakesParams(params object[] foo)
{
    Console.WriteLine(foo.Length);
}
```

Produces:
>2
>2

**Comment by MaStr11** [comment]
I would like to fix this. I started my work [here](https://github.com/MaStr11/roslyn/commit/5d36b856f8f1c872f988bed0b29c4113599de316). (The only change by now was the removal of [this check](https://github.com/MaStr11/roslyn/commit/5d36b856f8f1c872f988bed0b29c4113599de316#diff-6f8f267309a989ee1a5a92a703afe42bL164). All the other differences are caused by the changed indentation.) I also added a test based on the reported bug. All tests in [RemoveUnnecessaryCastTests.cs](https://github.com/MaStr11/roslyn/blob/5d36b856f8f1c872f988bed0b29c4113599de316/src/EditorFeatures/CSharpTest/Diagnostics/RemoveUnnecessaryCast/RemoveUnnecessaryCastTests.cs) are green after the change. @sharwell What else should I provide before I create a pull-Request (CLA is already signed).

**Comment by sharwell** [comment]
@MaStr11 Go ahead and submit a pull request when you get to a point you think it's complete. 👍
