### ISSUE TITLE
Bad startup performance with .NET Framework 4.6.2

### ISSUE THREAD

**Issue by jairbubbles** [dotnet/roslyn#19131]
**Version Used**:  2.1.0

**Steps to Reproduce**:

1. Clone my depot https://github.com/jairbubbles/RoslynCompiler
2. Launch Comparer.exe

**Expected Behavior**:

Compilation time should be fairly identical with all .NET framework 4.6.x versions.

**Actual Behavior**:

Compilation time with .NET Framework 4.6.2 is doubled compared to 4.6.1 or 4.6

*I would be really interested to see if those timings are consistent on different machines. I've also had weird results regarding Roslyn versions 2.1 vs 2.0 on two identical machines (2.1 is much slower one one and much faster on the other one)*

**Comment by jairbubbles** [comment]
@daveaglick As you play a lot with Roslyn you might be interested by this subject.

**Comment by jairbubbles** [comment]
I was able to  test on several other machines. It appears that it's not consistent at all:
- on some machines it's slow for all frameworks
- it seems there is some hidden per framework parameter that double the compilation time

**Comment by jairbubbles** [comment]
I've made some progress and it's seems it's only linked to the way NuGet packages are resolved depending on the framework.  

These differences happen on many packages resulting in really different output. When comparing 4.6.1 and 4.6.2 output the differences are subtle:
![image](https://cloud.githubusercontent.com/assets/15875066/25764660/3ebd90f6-31e9-11e7-9154-9b8339c83415.png)

The automatic redirect bindings also differ by adding those 4 redirections:
```xml
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Runtime" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.1.1.0" newVersion="4.1.1.0" />
      </dependentAssembly>
    </assemblyBinding>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Runtime.InteropServices" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.1.0.0" newVersion="4.1.0.0" />
      </dependentAssembly>
    </assemblyBinding>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Runtime.Extensions" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.1.1.0" newVersion="4.1.1.0" />
      </dependentAssembly>
    </assemblyBinding>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Reflection" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.1.1.0" newVersion="4.1.1.0" />
      </dependentAssembly>
    </assemblyBinding>
```
If I manually remove the extra assemblies and the bindind redirects, the performance go back to normal.

**I believe these are just facade assemblies for .Net standard. They are just containing type forwardings to the real assemblies (which are ngened).  This must be adding some JIT overhead.**

**Comment by jairbubbles** [comment]
Hello @terrajobst do you know .Net standard experts that could confirm my theory?

**Comment by terrajobst** [comment]
Thanks for the detailed report! We're taking a look and will come back to you.

**Comment by jkotas** [comment]
The difference that you are seeing is most likely caused by fragile ngen images being available on your machine in the global ngen image cache for one configuration, but not for other configurations. 

You can try running `ngen install /ExeConfig:<path to the RoslynCompiler.exe.config> <path to RoslynCompiler.exe>` against the different configuration and check whether it will make the difference go away.

If it does not help, collecting traces using perfview tool should give you ultimate answer on where the time is going.

**Comment by jairbubbles** [comment]
Thank you @jkotas for looking into it!

As we could expect ngening the .exe do fix the issues but I'm in a scenario where I do not want to install my application.

I've tried only nging the new dependencies (`System.Runtime`, `System.Runtime.InteropServices`, `System.Runtime.Extensions`, `System.Reflection`) but it doesn't make any difference.

The real question is: "**do .Net standard libraries increase the JIT time (vs PCL)?**" If so, I think it's a serious matter that is outside of this issue's scope and should be looked into it.

I'll look at perfview to see what I can find.

**Comment by jairbubbles** [comment]
Perfview is prety cool, it helps visualize the issue but I still don't get why.

With 4.6.2 it's JITing 2000+ methods in `Microsfot.CodeAnalysis.Csharp.dll` while only 78 with 4.6.1:
![image](https://cloud.githubusercontent.com/assets/15875066/25770930/f6e611ea-3242-11e7-8b42-43b168098a69.png)

They are both the same assemblies.

**Comment by jkotas** [comment]
Thanks for confirming the problem with perfview.

The problem you are seeing is not really caused by netstandard facades. It is result of how .NET Framework NGen image cache works. Let me explain:

Images in .NET Framework NGen image cache are generated and looked up based on the transitive closure of assembly dependencies. It means that Microsoft.CodeAnalysis.CSharp.dll bound against one set of netstandard facades needs one NGen image, and Microsoft.CodeAnalysis.CSharp.dll bound against a different set of netstandard facades needs a different NGen image.

Also, .NET Framework image cache is based on assembly identities, not on absolute paths. If something else on the machine happened to run "ngen install" on  same Microsoft.CodeAnalysis.CSharp.dll bound to the same set of netstandard facades as you have, you will get the NGen image for free.

So the one configuration is better in your case because of something else (Visual Studio?) happened to run "ngen install" on the exact configuration that you are using. If you run your app on pristine machine without Visual Studio, you will see slow startup in both configurations. Also, once you install next major Visual Studio update on the machine where it is fast, it will likely become slow because of Visual Studio will come with a updated version of Microsoft.CodeAnalysis.CSharp.dll that won't match yours anymore and so you won't get the benefit of the NGen image generated by Visual Studio for free.

**Comment by jkotas** [comment]
> I'm in a scenario where I do not want to install my application.

You may want to look shipping your application as standalone .NET Core app.

**Comment by jairbubbles** [comment]
> You may want to look shipping your application as standalone .NET Core app.

Seems clearly an option !

Thanks for all the information, it explains all the inconsistent performance I was getting on different machines.

I just updated my win 10 beta and it seems it cleared the nativecache as now I have bad performance for all. 

Now that we have nuget packages who are released more and more often it seems we're more likely to have a cache miss and have bad performance. Would be great to have a way to simulate the worst case.

**Comment by jairbubbles** [comment]
@jkotas I quickly tested a self contained .NET Core application but the compilation time was worse than with .NET framework. Are assemblies supposed to be native?

**Comment by jkotas** [comment]
dotnet cli does not have integration with crossgen for standalone apps yet, unfortunately: https://github.com/dotnet/sdk/issues/593

You can workaround it by running crossgen directly on the output of `dotnet publish -c Release`. Here is a small .bat file that should do the trick:

https://gist.github.com/jkotas/d6b5d9584137252d2351c47471c41ef1

**Comment by jaredpar** [comment]
Closing for now as this issue seems to have gotten stale and doesn't seem to be an actual issue in roslyn, rather a CLR issue around startup peformance.

**Comment by anakic** [comment]
Just ran into this issue and this thread was quite helpful, at the very least to confirm I'm not insane. 

After adding the "Microsoft.CodeAnalysis.CSharp.Features" nuget package to my VSTO project, opening up a WPF window started taking 9s due to massive jitting of methods in PersentationCore and other WPF dlls (verified in perfview). I'm using .NET 4.6 in my project.

I was able to resolve the issue (at least on my machine) by narrowing down the binding redirects e.g. instead of "0.0.0.0-4.1.2.0" I used "4.0.1.0-4.1.2.0". 

Here's what I ended up with in my binding redirects section:

```
<assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Collections.Immutable" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="1.0.0.0-1.2.1.0" newVersion="1.2.1.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.IO.Compression" publicKeyToken="b77a5c561934e089" culture="neutral" />
        <bindingRedirect oldVersion="4.0.1.0-4.1.2.0" newVersion="4.1.2.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.IO.FileSystem" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="4.0.1.0-4.0.2.0" newVersion="4.0.2.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.IO.FileSystem.Primitives" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="4.0.1.0-4.0.2.0" newVersion="4.0.2.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Security.Cryptography.Primitives" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="4.0.0.0-4.0.1.0" newVersion="4.0.1.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Xml.XPath.XDocument" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="4.0.1.0-4.0.2.0" newVersion="4.0.2.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Threading.Thread" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="4.0.1.0-4.0.1.0" newVersion="4.0.1.0" />
      </dependentAssembly>
    </assemblyBinding>
```

Roslyn seems to work fine with these redirects, and the wpf window opens quickly with very few jitted methods (<100, instead of ~11k)

I didn't yet investigate why this helps yet, nor did I try on other machines. Will update here if I find out anything more.
