### ISSUE TITLE
default value for class

### ISSUE THREAD

**Issue by divyang4481** [dotnet/roslyn#1917]
can we define  some thing like

var instanceOfMyClass = default(MyClass);

public class MyClass
{

  default  = new MyClass(){ Prop2="myDefaultValue", Prop1=1 };

 public MyClass()
{
}

   public  string Prop2{get;set;} 
  public  int Prop1{get;set;}
}

**Comment by henkmollema** [comment]
You could assign those values as defaults for the properties:
```
public class MyClass
{
    public string Prop2 { get; set; } = "MyDefaultValue";
   
    public int Prop1 { get; set; } = 1;
}
```

**Comment by HaloFour** [comment]
Sounds like he wants to override what the CLR considers to be the "default" for the reference type itself.  Not sure that's really possible as when the CLR inits any locals/fields it zero-fills them, which is why references are `null` by default.  The C# compiler could potentially consider `default(MyClass)` to actually mean `MyClass.SomeDefaultProperty` but only in non-generic circumstances and only where the compiler actually has control over how that is determined, which is probably in fairly limited cases.  For example, `MyClass[] array = new MyClass[1];` would still contain a `null` element and not some default value for `MyClass`.

**Comment by jnm2** [comment]
I see `default(T) == null` a lot to determine if T is a value type or a reference type, since the default of a reference type is defined to be null. That would break.

What is the gain you're looking for?

**Comment by orthoxerox** [comment]
I've written in #71 that the goal of having an overridden default() is avoiding NREs and the Elvis operator. It's not something that you might want for *all* of your types, but it is really, really useful for some of them.

**Comment by jnm2** [comment]
I'm not necessarily disagreeing but it's worth reading [Is it Really Better to 'Return an Empty List Instead of null'?](http://www.codeproject.com/Articles/797453/Is-it-Really-Better-to-Return-an-Empty-List-Inst).

In the cases where the null object pattern is really useful, what does `default()` give you that a static property `NullT.Default` doesn't?

**Comment by divyang4481** [comment]
@orthoxerox , I am thinking for override of default operator for  class. in way supporting NULL design pattern  in CLR or  compiler level.

**Comment by GeirGrusom** [comment]
What about generics? If FirstOrDefault() suddenly returns something other than null for classes a lot of code could break.

**Comment by orthoxerox** [comment]
Well, if you override default() it's a breaking change, so don't do that if consumers of your code won't adapt. To help them adapt, comparisons with null should generate a warning for classes with overridden default().

**Comment by HaloFour** [comment]
If it were implemented as an operator the class could be modified to have a `default` value and consumers never know unless/until they were recompiled.

I'm having trouble thinking of any real use case for a feature like this.  It could only possibly work in scenarios where you are requesting `default(SpecificClass)`, which is really uncommon.  Otherwise the compiler could never possibly resolve the fact that there is a `default` operator and it would have to emit the standard default value, which would be `null` for reference types.  It's also completely incompatible with generics as the generic method has to have the same common IL for all possible types and cannot selectively call some static method.

I think that this feature is a part of the larger "non-nullability" proposal already being deeply discussed.  The problems are the same in that nullability is deeply ingrained in the CLR and it would be impossible to offer any guarantees.

**Comment by VSadov** [comment]
The whole point of default operator is to generically produce an uninitialized zero-inited instance.

There could be some point in some feature that allows types to designate special singleton instances. That should not be done by changing semantics of "default". 
Default should continue mean default.

**Comment by gafter** [comment]
We are now taking language feature discussion on https://github.com/dotnet/csharplang for C# specific issues, https://github.com/dotnet/vblang for VB-specific features, and https://github.com/dotnet/csharplang for features that affect both languages.
