### ISSUE TITLE
Bad sorting from Metadata as source

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#19185]
GTD on `Humanizer.On`. This is the result:
![image](https://cloud.githubusercontent.com/assets/3751401/25627312/ffc14ac0-2f16-11e7-8a99-9163b66179d1.png)

We have a LogicalStringComparer in the VS layer that could be used for this sorting.

**Comment by miloush** [comment]
Couldn't that be misleading in some cases like COM interfaces where the order of methods matters? Or enum members, for that matter.

Also I assume this would be used only when the source code is not available and the view is generated form metadata, in which case the output would differ based on whether you have a source code and when you don't?

**Comment by Pilchie** [comment]
@CyrusNajmabadi wrote some code here to respect metadata order if things came from COM (maybe for Implement interface?)

Are we applying our own sort here, is this "random" or does it come from the metadata order?  I've definitely heard arguments for presenting in metadata order because type authors group "related" methods together in source.

**Comment by SolderedMushroom** [comment]
+1 For preserving the order in source. If it's currently "random," then alphabetizing is an improvement, but it shouldn't alphabetize rather than preserve source order. Who wants metadata-as-source for `Person: Age, FirstName, Height, LastName, Weight`?

**Comment by CyrusNajmabadi** [comment]
Closing out as not planned.  The number of places this would matter is too little to warrant investment here.  And this made even more marginal with ILSpy and sourcelink as alternatives.
