### ISSUE TITLE
Spell checker gives me a suggestion to change an assignment to assign a variable to itself

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#19241]
``` C#
    class Program
    {
        internal static void ToLower(string value)
        {
            $_value = value;
        }
    }
```

1. CTRL+. where indicated by $

Expected: No given a spell check to assign value to itself:
Actual:

![image](https://cloud.githubusercontent.com/assets/1103906/25687938/ce58c23a-30bd-11e7-9706-6bbbf71fbae5.png)

**Comment by CyrusNajmabadi** [comment]
This is by design.  The spell checker suggest potential names that would have been legal in that context. "value" would be legal, and it might be what you want to correct to *given* that you might be changing code, and don't intend the final code to be an assignment.

Note: this is also why completion offers 'value' in that context as well.  Because perhaps you want to actually intend to be using 'value' and want to do something with it.

**Comment by davkean** [comment]
V
