### ISSUE TITLE
Completion grouping

### ISSUE THREAD

**Issue by mhutch** [dotnet/roslyn#19256]
In VS for Mac / MonoDevelop we have a toggleable completion grouping feature that groups members by the type on which they are declared. The rationale is explained here: http://tirania.org/blog/archive/2010/May-09.html

In order to switch to the Roslyn completion engine without regressing, we need this feature.

**Comment by Pilchie** [comment]
No need to sell me on the rationale - I'd like to have this feature too :)

**Comment by Pilchie** [comment]
Tagging @kuhlenh @DustinCampbell @rchande @CyrusNajmabadi @markw-t @hemchans @olegtk.

This is a feature we've discussed a few times for VS, but haven't implemented.  VS for Mac shows one possible way of presenting it, though it's still not very discoverable...

**Comment by markw-t** [comment]
It looks a very cool feature to me; combined with filtering it looks like it provides a very powerful API explorer 👍

**Comment by rchande** [comment]
Very cool 👍

**Comment by mhutch** [comment]
Update: we switched to the Roslyn completion engine in VS for Mac 7.4, and as a result we have lost this feature.

**Comment by migueldeicaza** [comment]
It is the default, so it does not need to be discoverable - the discoverable part is how to switch it off.   It can be shown as a hint perhaps at the bottom of the UI?

**Comment by olegtk** [comment]
@AmadeusW FYI. Would be awesome if such relations were possible on express on provider API level in the modern completion, even if the UI won't support it for now.

**Comment by AmadeusW** [comment]
Grouping by the declaring type is a fantastic idea, I need it every time I see .xaml completions.
While this is beyond the scope of current efforts to platformize completion, I want to make the new API easily extensible so that we can get started on this asap. Here are a few considerations that I'd like to discuss:

Assumptions: 
* there will be no nested groups. 
* Each item has one or no group. 
* Propsoed `CompletionGroup` object has a display text, icon and sort order (with respect to other grouping objects)
* Discussion below pertains proposed completion API known to few individuals in this thread

**Solution 1:** _this is currently possible with the property bag_
CompletionItem gets a new property that determines which group it will be in. Language service who sorts and filters creates `CompletionGroup` objects based on contents of this property. 

Here, the language service which sorts and filters has full control over groups it builds, but it needs a convention to correctly communicate grouping intentions with extenders.

**Solution 2:**
CompletionItem gets a new property that stores a reference to a `CompletionGroup` object, similarly to filters. 

We need to establish a convention for extenders - for example, Razor (.cshtml) adds markup directives - what kind of `CompletionGroup` do they provide, and how are they sorted with respect to other groups? 

**Rendering:**
The UI currently takes list of `CompletionItemWithHighlight`. The API will change so that UI gets list of `ICompletionDisplayItem`, implemented by `CompletionItemWithHighlight` and in the future by the `CompletionGroup`. Group items won't be selectable or scrollable to, without further changes to the API.


Given solution 1 and 2, and future improvements to CompletionItem, do we want to improve extensibility story for this class? Currently, we create types such as `Completion4: Completion3: Completion2: Completion` to accommodate for changes. I heard that abstract pattern is quite extensible: in short, `CompletionItem` is abstract, we can introduce new internal types in the future. Extenders use a static `Create` method instead of constructors to guarantee backwards compatibility. should I adopt it in the new API?

**Comment by genlu** [comment]
This is a good idea, but not in scope of our planning for near future. Closed.
