### ISSUE TITLE
Provide option to disable formatting on copy

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#19330]
**Version Used**: d15rel 26505.0

**Steps to Reproduce**:

1. Copy any text 

**Expected Behavior**:
No delay 

**Actual Behavior**:
A dialog pops up indicating that the text is being fomatted

**NOTE:**  I would at least like an option to disable formatting the copied text.  Honestly what do we lose be not formatting the text?

**Comment by Pilchie** [comment]
This isn't "formatting" as you expect, it's classifying so that rich text copy/paste works.

If you have instances where you are seeing this, we should try to get perf traces and see what's going on.

However, adding an option would need to happen in the VS Platform team.  Tagging @olegtk @markw-t about that.

**Comment by jmarolf** [comment]
> If you have instances where you are seeing this

It happens all the time.  I am very aware of when I copy text now because it takes so long.  I never care about rich formatted text.  I would prefer to turn this off an not need to pay the enormous cost.

**Comment by Pilchie** [comment]
Please collect a trace so that it can be investigated.
