### ISSUE TITLE
[C# Feature] Make LINQ query syntax less dependent on LINQ method syntax

### ISSUE THREAD

**Issue by dsaf** [dotnet/roslyn#1937]
Currently:

```csharp
return (from item in someSource
        where item.Name == "Dude"
        select item).FirstOrDefault();
```

Suggested version - inferring a method group:

```csharp
return from item in someSource
       where item.Name == "Dude"
       select FirstOrDefault;
```

Supporting opinions:

http://stackoverflow.com/a/214610/486561
> As soon as I have to add (parentheses) and ```.MethodCalls()```, I change.

http://stackoverflow.com/a/279738/486561
> One advantage to using the extension methods is that you can define your own and it will still read fine

**Comment by svick** [comment]
I do think that a similar feature should exist, but I don't like this specific syntax, because it means it's not clear what you're selecting.

Consider:

```c#
from department in departments
from employee in department.Employees
select FirstOrDefault
```

What should this return? Right now, a LINQ query always clearly says what object is returned. You're proposing to change that principle. A logical extension of your proposal would be to also allow queries that have no `select`, like:

```c#
from department in departments
from employee in department.Employees
```

I don't think such query reads well and the same applies to your query.

Also, the general idea is a duplicate of #100.

**Comment by dsaf** [comment]
@svick Yeah, it's a duplicate.
