### ISSUE TITLE
Local Functions do not support attributes

### ISSUE THREAD

**Issue by redknightlois** [dotnet/roslyn#19372]
**Version Used**: 
C# 7 on Visual Studio 2017

**Steps to Reproduce**:

```csharp
public int Fibonacci(int x)
{
    if (x < 0) throw new ArgumentException("Less negativity please!", nameof(x));
    return Fib(x).current;
    
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    (int current, int previous) Fib(int i)
    {
        if (i == 0) return (1, 0);
        var (p, pp) = Fib(i - 1);
        return (p + pp, p);
    }
}
```

**Expected Behavior**:
Signal the JIT to inline the function for performance. (I know that recursive functions will not inline, I just copied the function from the blog  post detailing local functions and stamped the attribute in there).

**Actual Behavior**:
Does not compile

cc @Pilchie

**Comment by gafter** [comment]
This is a language feature proposal, so any work on this would have to be coordinated with corrseponding work in the `csharplang` repo.

**Comment by redknightlois** [comment]
@gafter Looks more like missing syntax / bug than a feature proposal. Local functions do not behave consistently with the rest of the language without attribute support.

**Comment by gafter** [comment]
@redknightlois One could make exactly the same argument because local variables do not support attributes but fields do.

[Our spec for local functions](https://github.com/dotnet/csharplang/blob/master/proposals/csharp-7.0/local-functions.md) simply does not include attributes in the syntax. Whether it should or should not be that way would be a discussion worth taking to the [`csharplang`](https://github.com/dotnet/csharplang) repo. It would be a bug for us to make the compiler accept things that are not described by the language specification.

**Comment by redknightlois** [comment]
Makes sense.

**Comment by agocke** [comment]
@jcouv @jaredpar I'm going to close this for now. If LDM wants to take this up in language design, that's fine, but for now there is no bug or work for the compiler to do.

**Comment by jcouv** [comment]
Opened csharplang issue https://github.com/dotnet/csharplang/issues/794
