### ISSUE TITLE
GoToAll for Generics doesn't find results, e.g. "Query<T" does not find "Query<T>"

### ISSUE THREAD

**Issue by NickCraver** [dotnet/roslyn#19380]
**Version Used**: 15.1 (26403.7)

**Steps to Reproduce**:

1. Open Dapper Solution ([repo link](https://github.com/StackExchange/Dapper/tree/4915071380d3f9a4c44f5257927a09facc847ab3))
2. Edit.GoToAll (I have it as `Ctrl+T`)
3. Type `Query<`
4. Observe results
5. Add `T`

**Expected Behavior**:
`Query<T>` is found as a result, which was clearly in the list in step 4, pictured here:

<img width="478" alt="screen shot 2017-05-08 at 19 23 32" src="https://cloud.githubusercontent.com/assets/454813/25875385/20345e9a-34e5-11e7-9440-2db4296e6a03.png">

**Actual Behavior**:
`Query<T>` is missing from the list entirely, results pictured here:

<img width="474" alt="screen shot 2017-05-08 at 19 23 39" src="https://cloud.githubusercontent.com/assets/454813/25875407/3a23aa40-34e5-11e7-99e0-6cc8204c5d25.png">

**Comment by NickCraver** [comment]
Context info from @CyrusNajmabadi in #19376:
> We don't support any sort of special syntax for generic types. Note that we're also moving our pattern matching code down to the platform layer (so all managed languages in VS could use it). As such, it gets even more difficult to put in support for matching all the sorts of special constructs that could be different across languages.

**Comment by jnm2** [comment]
It's possible to index the display text for every consuming language, but I can see why you'd want to avoid that because you'd have to index the same thing in multiple syntaxes.

What about simply adding a Go to Text capability to Go to All? That would pick up the `ClassName<T` search quite easily. In almost all cases, you'll be typing what you want to jump to in the same language that it was written in.
It's very natural. ReSharper has this and I've been missing it kinda badly since I've been pushing myself to adopt the native VS capabilities now. ReSharper's Go to Text is even faster than Go to Type or Member.

Without ReSharper, if you need to move between kinds of search, you have to press Ctrl+Shift+F and start over, and fix the search scope and file type and fiddle with match case and whole word and regex from the last time you needed to do something complex. It would be nice if simple text search was built into VS's Go to All, with higher score being given to the lines containing type or member definitions.

**Comment by CyrusNajmabadi** [comment]
> What about simply adding a Go to Text capability to Go to All? 

That would certainly be nice.  It would be something VS would have to supply (like they do for 'nav-to' wrt to checking the pattern against filenames).

**Comment by Pilchie** [comment]
Tagging @kuhlenh and @markw-t to see this too.

**Comment by onovotny** [comment]
Bump?

**Comment by NickCraver** [comment]
It seems to me that we don't need to index all the language patterns to search if we can convert *from* the search term to a common pattern based on fairly naive patterns, e.g. (`<` isn't crazy to figure out). Maybe there's a way we could match not to every language, but *from* the search term to a single target...possibly one that already exists? 

Here's an example of typing things today, the results are progressively less useful when generics come in:
![image](https://user-images.githubusercontent.com/454813/60669872-610dd180-9e3d-11e9-8c89-7b34fe3c6eb8.png)
![image](https://user-images.githubusercontent.com/454813/60669875-62d79500-9e3d-11e9-9db7-56af412127a8.png)
![image](https://user-images.githubusercontent.com/454813/60669878-6408c200-9e3d-11e9-915c-71986a0e01fe.png)

So if it's anything that matches more than a few things, I just give up and `Ctrl+Shift+F`.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
