### ISSUE TITLE
Generated source files are not regenerated before CodeAnalysis projects are built.

### ISSUE THREAD

**Issue by orthoxerox** [dotnet/roslyn#19399]
**Version Used**: master HEAD

**Steps to Reproduce**:

1. Change Syntax.xml or BoundNodes.xml 
2. Build Roslyn
3. Try using new nodes

**Expected Behavior**: new nodes are available as types

**Actual Behavior**: new nodes are not available as types

**Comment by Pilchie** [comment]
Tagging @jaredpar who just changed it to be this way.

**Comment by jaredpar** [comment]
This behavior is by design.

The old approach of generating files as a part of the build had a number of downsides for development:

1. Complicated our code editing story.  To open Roslyn.sln you first had to build Roslyn.sln, or at least the subset which contained our generator projects. 
1. Made dump debugging difficult because we couldn't use gitlink on our generated files.
1. Unnecessarily increased the depth of our build graph.  This slows down our develop loop a bit and was a continuous source of infrastructure pain. 

When we looked at this one item we observed is these files change fairly rarely.  It's a bit active when developing a language feature but day to day these files don't change very often.  Hence all of these downsides were to support a relatively rare scenario. 

After some discussion we decided to use the current approach:

1. Check the generated files in.
1. Add a [simple script](https://github.com/dotnet/roslyn/blob/master/build/scripts/generate-compiler-code.cmd) for generating the files. 
1. Add Jenkins validation to fail a build if the XML and generated files get out of sync.
