### ISSUE TITLE
Compiler uses user-defined well known members as attributes even though the containing type doesn't satisfy Attribute requirements

### ISSUE THREAD

**Issue by OmarTawfik** [dotnet/roslyn#19395]
Example code:

```csharp
namespace System.Runtime.CompilerServices
{
	public class NotAnAttribute { }
    
    public class DynamicAttribute : NotAnAttribute
    {
    	public DynamicAttribute() { }
    
        public DynamicAttribute(bool[] transformFlags)
        {
        }
	}
}
class T
{ 
    void M(dynamic x) {}
}
```

Compiler will use that type even though it does not inherit `System.Attribute`.
Also, it is the same case when inheriting `System.Object` directly.

**Comment by OmarTawfik** [comment]
cc @AlekseyTs

**Comment by AlekseyTs** [comment]
We match well-known types by name and well-known members by container and signature. As long as these criteria satisfied, we assume the type/member fulfills the contract, after all these are documented APIs with well-defined contract. We do not check base types, etc. because that is not part of metadata that we emit. Technically, at runtime the type/member could be OK. We have to draw a line somewhere. For example, for attributes, should we also verify that targets match what we expect? I would say that as long as compiler doesn't crash and metadata that we emit correct, we are fine.

**Comment by OmarTawfik** [comment]
Makes sense. Closing.
