### ISSUE TITLE
Rename formats unrelated code in method body

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#1945]
Forking this issue from #1156.

This is a regression from VS2013.

1. Copy/paste VB:
    ```VB
    Sub M(abc As Integer) ' Rename abc to def
        Dim a     = 7
        Dim bbbbb = 7
    End Sub
    ```

2. Rename ```abc``` to ```def```

**Expected**: The method body has the same formatting as above (with lots of spaces after ```a```).
**Actual**: The method body is formatted.

**Note**: Similarly formatted declarations in *other* methods are not formatted, so this is not due to some larger document format.

**Comment by Pilchie** [comment]
Can you take a look and see what's triggering it.

**Comment by basoundr** [comment]
On discussion with @jasonmalinowski we have realized that we cannot make this fix given the current design because the span to format is used by Case Correction Service.

Given the case where we change the casing of an identifier's name in the declaration statement we would like to see the identifier name updated in all the references. what the user wants is aligning the 'as' keyword rule. Opening issue #2161 to track this issue. Closing this issue
