### ISSUE TITLE
Completion list should prefer variables instead of type when typing all lower-case

### ISSUE THREAD

**Issue by jeremymeng** [dotnet/roslyn#19465]
**Version Used**: 

**Steps to Reproduce**:

1. paste the code into a C# file

```csharp

public class SyntaxNode
{
    void Test()
    {
        // type "SyntaxNode syntaxNode" to declare a local variable below

        // then type "syntaxn" below
    }
}
```
2. follow the instructions in comments to type code

**Expected Behavior**:
variable syntaxNode is pre-selected in the completion list

**Actual Behavior**:
the type SyntaxNode is preselected

I often find myself completing a type name at places where variable name is expected. If I want the type name I can get it pre-selected by starting with capital S.

**Comment by sharwell** [comment]
I lean in favor of your expected behavior, though I think I draw a different conclusion regarding the expected rule (the reason why `syntaxNode` should be preferred). Either one of the following two disambiguation rules in completion selection would have led to the desired outcome. It is not clear to me which of the two would be "better".

1. `syntaxn` only deviates in case from `syntaxN` by one character, while it deviates from `SyntaxN` by two characters.
2. `syntaxNode` is declared in a more local scope than `SyntaxNode`.

💭 With the changes already made for Visual Studio 15.3, it may be less likely for this to occur. When declaring the `syntaxNode` variable, the name `syntaxNode` would have been offered in the completion list, and if selected would have led to this identifier being added to the "recently used" completion items, thus taking priority.

**Comment by jeremymeng** [comment]
> When declaring the `syntaxNode` variable, the name `syntaxNode` would have been offered in the completion list

Is `syntaxNode` offered when I start the declaration with `SyntaxNode` in VS 15.3? If I use `var syntaxNode = new SyntaxNode();` it won't help then. Also the completed type name in ` new SyntaxNode()` would be the most recently used one.

**Comment by Pilchie** [comment]
Let's consider tweaking this in the future.

**Comment by Rychu-Pawel** [comment]
Could you please prioritze this bug? It is extremly frustrating, ruining whole pleasure of coding! :tired_face:

**Comment by stijnherreman** [comment]
Why would the completion list prioritise the type name here?

![image](https://user-images.githubusercontent.com/1618054/114351845-731cb800-9b6b-11eb-8a83-53166b0ae076.png)

**Comment by CyrusNajmabadi** [comment]
Because:

1.  it looks like you could be typing a new variable here.
2. because the list is alphabetically sorted
3. because you have an inexect match for both hits.  Neither is 'better' here given that the casing is off for both hits.

**Comment by CyrusNajmabadi** [comment]
I think we'd take a community PR that was motivated by either of the rules specified by @sharwell  here: https://github.com/dotnet/roslyn/issues/19465#issuecomment-301320933

**Comment by KashouC** [comment]
This is still the case and quite frankly I don't see how more people don't have an issue with this.
Just going strictly by case comparison would be a vast improvement when I can't adjust the priorities manually.

![image](https://user-images.githubusercontent.com/17066488/210067477-175bec3b-222c-4147-b243-27aa8d8eaa0a.png)

**Comment by CyrusNajmabadi** [comment]
@KashouC as I mentioned above: I think we'd take a community PR that was motivated by either of the rules specified by @sharwell here: https://github.com/dotnet/roslyn/issues/19465#issuecomment-301320933

If you are interested, def open a pr here! :-)

**Comment by stijnherreman** [comment]
I had a look around in the code and `SymbolMatchPriority` may be controlling the behaviour. But I'm not sure as there is a lot of code involved.

https://github.com/dotnet/roslyn/blob/2a383c15229f744db4c59856697cdad5e2820a0e/src/Features/Core/Portable/Completion/Providers/SymbolMatchPriority.cs#L9-L17

**Comment by CyrusNajmabadi** [comment]
Working for me:

![image](https://user-images.githubusercontent.com/4564579/216681645-d3824fa9-44d0-46bb-8951-7dff1f7cdb1f.png)
