### ISSUE TITLE
MSBuildWorkspace.Create().OpenSolutionAsync() Project.Documents empty

### ISSUE THREAD

**Issue by piotr-polanski** [dotnet/roslyn#19747]
Here is the source code https://github.com/piotr-polanski/EyeOfBeholder
1. Load any solution trough https://github.com/piotr-polanski/EyeOfBeholder/blob/develop/EyeOfBeholder.Uml.Tests/IntegrationTests/EyeOfBeholderIntegrationTests.cs#L25
2. and look at solution.Projects Documents at
https://github.com/piotr-polanski/EyeOfBeholder/blob/develop/EyeOfBeholder.Uml/ClassesExtractor.cs#L19

I have two machines, and it works only on one.

**Expected Behavior**:
Documents in Project should not be emtpy
**Actual Behavior**:
Documents in Project are empty

Any help will be appreciated.
thx in advance

**Comment by Pilchie** [comment]
I suspect that the issue is that one machine doesn't have msbuild or some of the targeting packs/tasks/targets/sdks/etc that your project depends on installed.

If you use the 2.3 or later packages from our [MyGet feed](https://dotnet.myget.org/gallery/roslyn) and subscribe to the `WorkspaceFailed` event, you should get more details about why MSBuild fails to evaluate the project.

**Comment by piotr-polanski** [comment]
Thx, it helped.
