### ISSUE TITLE
Unary operators and default literal

### ISSUE THREAD

**Issue by akarpov89** [dotnet/roslyn#19751]
**Version Used**: 
Master branch on May 19
**Steps to Reproduce**:

Compile the following code:

```csharp
class C
{
  void M()
  {
    var a = +default;
    var b = -default;
    var c = ~default;
    var d = !default;
  }
}
```
**Expected Behavior**:
Compiler emits errors CS0023: Operator '+' / '-' / '~' / '!' cannot be applied to operand of type 'default'
**Actual Behavior**:
Code compiles without errors. The local variables have the following types and values:

```ml
a: int = 0
b: int = 0
c: int = -1
d: bool = true
```

Apart from unary operators there are others undocumented operators which are currently legal to use with default literal:
```csharp
var e = __reftype(default);
var f = __refvalue(default, int);
Foo(__arglist(default)); // where `Foo` is defined as `void Foo(__arglist)`
```

I understand that this is an effect of unary operator overload resolution using predefined operator implementations. But I see absolutely no benefit in allowing such a weird code.
The [original proposal](https://github.com/dotnet/csharplang/blob/master/proposals/target-typed-default.md) mentions couple of usages that are considered illegal (`throw default` and `default == default`). Could you please consider extending this list?

**Comment by gafter** [comment]
We are now taking language feature discussion in other repositories:
- https://github.com/dotnet/csharplang for C# specific issues
- https://github.com/dotnet/vblang for VB-specific features
- https://github.com/dotnet/csharplang for features that affect both languages

Features that are under active design or development, or which are "championed" by someone on the language design team, have already been moved either as issues or as checked-in design documents. For example, the proposal in this repo "Proposal: Partial interface implementation a.k.a. Traits" (issue 16139 and a few other issues that request the same thing) are now tracked by the language team at issue 52 in https://github.com/dotnet/csharplang/issues, and there is a draft spec at https://github.com/dotnet/csharplang/blob/master/proposals/default-interface-methods.md and further discussion at issue 288 in https://github.com/dotnet/csharplang/issues. Prototyping of the compiler portion of language features is still tracked here; see, for example, https://github.com/dotnet/roslyn/tree/features/DefaultInterfaceImplementation and issue 17952.

In order to facilitate that transition, we have started closing language design discussions from [the roslyn repo](https://github.com/dotnet/roslyn) with a note briefly explaining why. When we are aware of an existing discussion for the feature already in the new repo, we are adding a link to that. But we're not adding new issues to the new repos for existing discussions in this repo that the language design team does not currently envision taking on. Our intent is to eventually close the language design issues in the Roslyn repo and encourage discussion in one of the new repos instead.

Our intent is not to shut down discussion on language design - you can still continue discussion on the closed issues if you want - but rather we would like to encourage people to move discussion to where we are more likely to be paying attention (the new repo), or to abandon discussions that are no longer of interest to you.

If you happen to notice that one of the closed issues has a relevant issue in the new repo, and we have not added a link to the new issue, we would appreciate you providing a link from the old to the new discussion. That way people who are still interested in the discussion can start paying attention to the new issue.

Also, we'd welcome any ideas you might have on how we could better manage the transition. Comments and discussion about closing and/or moving issues should be directed to https://github.com/dotnet/roslyn/issues/18002. Comments and discussion about this issue can take place here or on an issue in the relevant repo.

----------------------

Please reopen this issue in csharplang if you'd like it to be considered.
