### ISSUE TITLE
Lightbulb doesn't work in the latest build of VS

### ISSUE THREAD

**Issue by tannergooding** [dotnet/roslyn#1976]
**Repro:**
 * Install Visual Studio (22814.0)
 * Create a new C# Console Application

**Expected Results:**
 * All 5 using statements should be *greyed* out
 * A lightbulb action for 'Remove Unnecessary Usings' should appear when hovering over any of the using statements
 * The reference count indicators should load for the solution (*this does not always repro*)

**Note:**
Lightbulb does not appear to work in any tested scenarios for C# or VB

**Comment by jcotton42** [comment]
@tannergooding Where is this build available? It does not seem to be CTP 6

**Comment by tannergooding** [comment]
@jcotton42 This is an internal build that is not currently available.

**Comment by jcotton42** [comment]
Oh

**Comment by shyamnamboodiripad** [comment]
This turned out to be a problem with the diagnostic service (VSDiagnosticAnalyzerProviderService) and the problem was introduced in 2ad819727e4db82c04dd584661776d84f1ac4b82. 

The diagnostic service was failing to resolve analyzer dlls present in VSIXes when the paths of these analyzer dlls as specified in the vsixmanifest required expansion of $RootFolder$ strings. Because these analyzers (including the analyzers responsible for producing compiler errors) were not getting loaded we weren't producing diagnostics (no squiggles, no errors in error list) for any loaded projects. Consequently VS light bulb was failing to offer code fixes (since code fixes are triggered off of diagnostics in the IDE).

This should be fixed by @heejaechang's PR #2001 merged in commit b46d458eba7fbe8986f30d37e8161f522499df17.

**Comment by shyamnamboodiripad** [comment]
@tannergooding Please validate and reactivate if you notice that this is not fixed in tomorrow's build. Thanks!

**Comment by tannergooding** [comment]
@shyamnamboodiripad Will do. Thanks!
