### ISSUE TITLE
Cannot drop inline lightbulb

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#19772]
1. 
``` C#
using System;
using System.Threading.Tasks;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            Lamda(() =>
            {
                Console.WriteLine("Foo");

            });
        }

        public static void Lamda(Func<Task> asyncMethod)
        {

        }
    }
}
```

2. Hover mouse over =>
3. Click on lightbulb that shows

Expected: Light bulb to drop (or not even be there?)
Actual: Nothing

**Comment by Pilchie** [comment]
@olegtk / @gundermanc :  I can repro this one.  It works with Ctrl+. and with the mouse from the margin.  I also noticed that the lightbulb isn't shown on hover unless the caret is actually in the error span.  Could this be related to the lightbulb changes in 15.3?

**Comment by olegtk** [comment]
I can repro this too on 26524.3003 D15PreRel - I mean I get no LightBulb when hovering over the red squiggle. keyboard wise seems ok to me, I get LightBulb on the margin in any caret position on that line.

**Comment by davkean** [comment]
@olegtk In my repro there's a lightbulb that does not open - are you not seeing that? Not that Pilchie mentioned you need to have caret in the error span.

**Comment by olegtk** [comment]
Yeah, you are right. If the caret is on the error span I get a LightBulb that won't expand. @gundermanc is currently investigating.

**Comment by gundermanc** [comment]
Hi all, I have investigated this issue and noticed something curious: in the provided example, we're calling into HasSuggestedActionsAsync() with requestActionsCategorySet of { CODEFIX } and trackingSpan from 173 to 175 and getting a return value of `true` and then calling into GetSuggestedActions() when the button is pressed with the same parameters and getting back null.

From what I can tell by eye-balling the [SuggestedActionSource.HasSuggestedActionsAsync()](https://github.com/dotnet/roslyn/blob/26488b780dd0fe25be5c2f438afacc7754b7ab77/src/EditorFeatures/Core/Implementation/Suggestions/SuggestedActionsSource.cs#L696) implementation, it looks like requestedActionsSource isn't respected when we ask if actions are available but that it is respected in the SuggestedActionSource.GetSuggestedActions() [GetRefactorings()](https://github.com/dotnet/roslyn/blob/26488b780dd0fe25be5c2f438afacc7754b7ab77/src/EditorFeatures/Core/Implementation/Suggestions/SuggestedActionsSource.cs#L562) and the [GetFixes()](https://github.com/dotnet/roslyn/blob/26488b780dd0fe25be5c2f438afacc7754b7ab77/src/EditorFeatures/Core/Implementation/Suggestions/SuggestedActionsSource.cs#L279) call, causing the lightbulb to be displayed for Quick Info, but to have no actions.

I think that HasSuggestedActionsAsync() should be returning false here. It doesn't make sense to display the LightBulb on hover on the error tag because the QuickInfo lightbulb is only asking for CodeFixes, and there is only a refactor available and the refactor operation doesn't really help the user address the error.

**Comment by CyrusNajmabadi** [comment]
Ah, this is the change we made to not actually respect code-action-categories.  Looks like we didn't fix up GetSuggestedActions to not respect the category either.  

@gundermanc This was by design on our part.  We basically want these features to always be avialable, and always be proferred to the user. 

Once we get your the recent editor changes around lightbulbs, we'll properly update our SuggestedActions to have the right category so that the user won't see a lightbulb here, but will instead see the hammer/wrench.

**Comment by davkean** [comment]
@CyrusNajmabadi Which would result in a weird interaction, here I want to fix the error, it tells me here are some possible fixes and I drop the light bulb and gives me a refactoring.

**Comment by CyrusNajmabadi** [comment]
It won't tell you there are fixes.  It will tell you "there are refactorings"  We have separate icons for fixes and refactorings.  

If there are any actual fixes you'll see the lightbulb.  If there aren't, you'll just see a wrench indicating there are things that you *can* do with your code, but nothing that actually fixes an issue.

        -- Cyrus

**Comment by Pilchie** [comment]
But you should never see the refactoring from hovering over an error, right?

**Comment by davkean** [comment]
What build is that in? If I understand correctly, if you make a change right now based on my build I'm going to see the following:

![image](https://cloud.githubusercontent.com/assets/1103906/26476779/55cd2f6a-4204-11e7-8457-19f1dd12e20d.png)

**Comment by CyrusNajmabadi** [comment]
> What build is that in?

We haven't done any of the work for it.  AFAIK, we're still waiting on the API changes to be published to nuget so we can reference them.  @gundermanc is there a nuget drop of the SDK we can reference that has all this stuff in it yet?

**Comment by olegtk** [comment]
Latest nugets on the editor's myget feed contain those LightBulb API changes.

**Comment by CyrusNajmabadi** [comment]
@rchande Are you consuming the latest editor Myget feed now as part of your 'ctrl click' work?

**Comment by Pilchie** [comment]
https://github.com/dotnet/roslyn/blob/master/NuGet.Config#L29 makes it look like yes, but @rchande is OOF right now.

**Comment by CyrusNajmabadi** [comment]
Hrmm... I didn't see the new APIs when i did metadata-as-source on my own box.  @olegtk Can you point me at the changes you expect us to see in your source code repo?

**Comment by Pilchie** [comment]
Oh - I should clarify, @rchande added the feed, and referenced the 15.3 P1 binaries, but I think this API is newer than that, so this might require updating references/doing things with lightup until P2 ships.

**Comment by olegtk** [comment]
The API I'd expect you to see is ISuggestedActionsSource2. It's present in the  Microsoft.VisualStudio.Language.Intellisense.dll 15.0.26508.55 available on 
the editor myget feed.

**Comment by CyrusNajmabadi** [comment]
Ok.  We don't have ISuggestedActionsSource2 in our copy.  Will have to discuss with teh team how we get your version sucked into Roslyn.

**Comment by gundermanc** [comment]
As I understand it, there are two distinct issues here, the second of which is more important:
- GetSuggestedActionCategoriesAsync() respects requestedActionCategories, but GetSuggestedActions() does not, causing the QI lightbulb to occasionally popup with no items.
- Quick Info lightbulb is not displayed unless the caret is within the error tag.

**Comment by dpoeschl** [comment]
@rchande Should this be closed since your PR says it fixes both of these issues?
