### ISSUE TITLE
Is it possible to reuse a local for discards with the same type?

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#19826]
```cs
obj.Deconstruct(out int x, out int _, out int _);
```
->
```cs
int x;
int discarded;
obj.Deconstruct(out x, out discarded, out discarded);
```

**Comment by jcouv** [comment]
I don't think it is possible to do such optimization, as any method with multiple `out` parameters will expect space to be reserved on the stack for returning both values. The fact that the values returned will be ignored is irrelevant to the method (which may be in a different assembly/project/etc) and the method calling protocol must be respected.

FYI @VSadov in case I'm missing something.

**Comment by VSadov** [comment]
The optimization is actually possible. However the profit is not huge - we would just avoid some extra temps. There is also one problem with the optimization being observable in the callee via the aliasing of the out variables. If the callee reads from either of `out` parameters it will see the "discarded" value from whichever out parameter was written last - since they would share the storage. 
The worst part is that it is possible to take dependency on the aliasing and that would make the keeping such optimization a compatibility requirement/burden.
It feels like not sharing the discard temps is simpler and safer solution.

**Comment by alrz** [comment]
>However the profit is not huge - we would just avoid some extra temps. 

Hopefully, when we introduce recursive patterns we can do this for different branches,
```cs
case X(_, 1): break;
case X(1, _): break;
```
afaik we already do this for pattern vars with the same type:
```cs
case string s when c: break;
case string s: break;
```
There, string variables share a single local.

**Comment by VSadov** [comment]
We generally reuse temps between statements. Should also be happening for discards.

It is reusing within the same expression for the variables whose lifetimes overlap, that is less useful and more observable.
