### ISSUE TITLE
NameOf( ) make first suggestion in Intellisense the current method.

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#19869]
When typing `NameOf(..)` the first suggestion in Intellisense should be the current method.

**Comment by cH40z-Lord** [comment]
I'm not too sure about that whether that's a good idea. Is using the current method really the most used use-case for `nameof``? What about variable names? Arguments?

**Comment by AdamSpeight2008** [comment]
It's a good initial guess, to what the user may want.

**Comment by Pilchie** [comment]
We don't re-order completion in general, so that's not likely something we would do here.  We could _consider_ using pre-selection to highlight the method by default, but I agree with @cH40z-Lord.  In fact, in most of my usage, I use `nameof` for `ArgumentNullException`, so I'd prefer parameters.

Going to close this as won't fix for now.
