### ISSUE TITLE
BatchFixer introduces syntax errors

### ISSUE THREAD

**Issue by pdelvo** [dotnet/roslyn#199]
In this [code fix](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/StyleCop.Analyzers/StyleCop.Analyzers/MaintainabilityRules/SA1407SA1408CodeFixProvider.cs#L42) the BatchFixer will create invalid syntax, the code fix itself does not. Is this a bug or is the BatchFixer not meant to be used when multiple code fixes can appear this close together? What would be the best approach to fix this?

**Comment by jmarolf** [comment]
The Batchfixer naively assumes that all of your fixes can be committed in parallel because this is the best assumption for performance. If this is not the case you will need to implement your own fix all provider.  We've [already](http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/CodeFixes/FixAllOccurrences/BatchSimplificationFixAllProvider.cs,19) needed to do this for cases such as simply type name.  You will need to create a new implementation derived from [FixAllProvider](http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/CodeFixes/FixAllOccurrences/FixAllProvider.cs,14) that merges your changes correctly.

**Comment by pdelvo** [comment]
Where exactly is the line between what BatchFixer can do and what it can't? I implemented a FixAllProvider for this case but It would be good to have a deterministic way to decide if BatchFixer will work for a code fix or not.

**Comment by jmarolf** [comment]
If you apply all of your codefixes at once, will they collide?  will any of them reference the same nodes?  If they do then you can't use the BatchFixer since it assumes all fixes can be applied in parallel.

**Comment by sharwell** [comment]
I'm facing a dilemma here. Ideally what we would do here is create our own `FixAllProvider` that handles the changes for a single document, but use "off-the-shelf" handling to handle applying changes to a project or solution.

Unfortunately it looks like customizing the `FixAllProvider` is an all-or-nothing option. I'm concerned we may have failed to address scenarios like linked files appearing in multiple projects, etc.

**Comment by jmarolf** [comment]
I see your point.  We could provide an abstract class that people could override for their scenario.  Our current requirements are "If the merge can't happen in parallel, let the programmer figure out the most efficient way to merge things" because if your fix requires custom merge logic its hard to know what will be helpful and what won't. In your case, you just need to provide logic for merging documents, but someone else may need different logic for each scope. I think we should provide some more well-known fix-all providers, we'll just need to noodle on what those should be and how we implement them in a performant way.

**Comment by sharwell** [comment]
If you had to pick just one or two, I think these would be a great place to start:

1. (First addition to current setup) User provides behavior for fixing all diagnostics within a document, but the library-provided abstract `FixAllProvider` implements merge support to expand that behavior to a project or solution.
2. (Second addition to current setup, after the previous one) User provides behavior for fixing all diagnostics within a project, but the library-provided abstract `FixAllProvider` implements merge support to expand that behavior to a solution.

For many diagnostics that already work with the batch fixer, providing the ability to correct all instances within a document might produce performance gains due to the fact that the merge algorithm no longer has to operate within documents. (I say 'might' because I haven't actually tested this idea.)

**Comment by jmarolf** [comment]
Seems reasonable.  I assume that any programmer will be able to get extra performance by implementing their own merge logic.  Can you file a bug for us to implement these apis?

**Comment by srivatsn** [comment]
Closing this thread since the work is being tracked by #201.
