### ISSUE TITLE
TupleElementNamesAttribute receives extraneous null values for large tuple types

### ISSUE THREAD

**Issue by tuespetre** [dotnet/roslyn#19946]
**Version Used**: 

I was using the C# interactive window in Visual Studio 2017 Version 15.2 (26430.6) (`Microsoft (R) Roslyn C# Compiler version 2.2.0.61624`) when I first noticed the issue and did subsequent tests using `dotnet` version `2.0.0-preview1-005418`.

**Steps to Reproduce**:

1. Declare a large (more than seven elements) tuple literal field, property, or similar that would result in the `TupleElementNamesAttribute` being emitted
2. Inspect the value of the resulting `TupleElementNamesAttribute`'s `TransformNames` property

**Expected Behavior**:

Given `int elements` equal to the number of elements within the tuple type, the `TransformNames` property will contain `elements` non-null values.

**Actual Behavior**:

Given `int elements` equal to the number of elements within the tuple type, the `TransformNames` property will contain `elements` non-null values and `Enumerable.Range(1, elements / 7).Select(i => elements - 7 * i).Sum() + elements % 7` null values.

**Comment by jcouv** [comment]
That's by-design. We explicitly [test for that](https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Test/Emit/Attributes/AttributeTests_Tuples.cs#L481).
If I remember correctly, we visit all the `ValueTuple` types and serialize each of their names. Since a 9-tuple is lowered to `ValueTuple<T1, ..., T7, ValueTuple<T8, T9>>`, both potentially carry names and thus need to be serialized.
Consider `ValueTuple<int, ..., int, (long y8, long y9)>` versus `(int x1, ..., int x9)`. We need to encode the names ("y8", "y9") in the first case as well.

Ping @agocke @VSadov in case anything to add.

**Comment by tuespetre** [comment]
I could see there being a null value per unnamed 'lifted' tuple element (i.e., the TRest tuple) but why are there so many null values in the example I gave? What purpose are they serving? 

In the example you linked to, why is that null value there?

**Comment by jcouv** [comment]
Each occurrence of ValueTuple is an opportunity to carry names. For each of those possibly named positions, there must either be a null or a name. 
As illustrated in the example with y8 and y9, you can have names in those two extra positions. That means you need repo bulls nulls when they are not actually named. 
The example that I linked could be part of a more complex type (key value pair of two long tuples with names, for example). So positions cannot be omitted, otherwise you will lose track of where names go.

**Comment by tuespetre** [comment]
@jcouv sorry, my phone apparently scrolled to the wrong line when I opened your link. Here is what I saw:

https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Test/Emit/Attributes/AttributeTests_Tuples.cs#L369

```
// Delegate1<(dynamic e1, ValueTuple<(dynamic e2, dynamic e3)> e4)>
// new [] { "e1", "e4", null, "e2", "e3" }
```

Now looking at it with fresh eyes I see why the `null` would be there (because `(dynamic e2, dynamic e3)` is the unnamed single element of `ValueTuple<>`.)

But this...

```
private static (
    int a, int b, int c, int d, int e, int f, int g, 
    int h, int i, int j, int k, int l, int m, int n
    ) x;
```

...is resulting in the following values:

```
new [] { "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", null, null, null, null, null, null, null }
```

Shouldn't it instead be:

```
new [] { "a", "b", "c", "d", "e", "f", "g", null, "h", "i", "j", "k", "l", "m", "n" }
```

Otherwise, what are the seven `null` values each representing?

If I instead declare `x` as:

```
private static (
    int a, int b, int c, int d, int e, int f, int g, 
    (int h, int i, int j, int k, int l, int m, int n)
    ) x;
```

We get:

```
new [] { "a", "b", "c", "d", "e", "f", "g", null, null, "h", "i", "j", "k", "l", "m", "n" }
```

...which makes sense.

**Comment by jcouv** [comment]
Exercise for the reader: try to encode the following cases, such that they can be roundtripped (ie not get mixed up with each other):
- `ValueTuple<int, ..., int, (int y8, int y9)>`
- `(int x1, ..., int x9)`.
- `(int x1, ..., int x7, int, int)`

The first case is important, as it creates the requirement to store 11 names for `ValueTuple<int, ..., int, ValueTuple<int, int>` (9 integers).
The same logic expand to the 14-tuple from the link (which requires 14 names for the top-level ValueTuple and 7 names for the nested ValueTuple, which could in some cases have names).

Beyond that, I'm only going to repeat myself. You have all the keys to understand.

**Comment by tuespetre** [comment]
@jcouv thank you, the 'roundtripping' concept made it click for me. 👍

**Comment by jcouv** [comment]
Glad to hear :-)
I took a note to add some details to the tuples feature document.
