### ISSUE TITLE
change yahoo link in the Wiki Interactive Window

### ISSUE THREAD

**Issue by ltlombardi** [dotnet/roslyn#19993]
This, doesn't work anymore
"http://ichart.finance.yahoo.com/table.csv?s=MSFT&d=10&e=10&f=2015&g=d&a=2&b=13&c=1986&ignore=.csv";

In https://github.com/dotnet/roslyn/wiki/C%23-Interactive-Walkthrough

**Comment by ltlombardi** [comment]
Hi, May I ask why the issue as closed, without any indication of why?

**Comment by tmat** [comment]
Sorry, misclick. My bad.

**Comment by tmat** [comment]
Also simplify the web request:
```c#
var client = new HttpClient();
var result = await client.GetStringAsync(url);
client.Dispose();
```

**Comment by tmat** [comment]
@ericstj FYI

**Comment by eriawan** [comment]
@tmat 

I would like to create PR but I couldn't do it because this is a Wiki page. CMIIW.
The fix is easy, just replace the Yahoo URL with this URL:
`http://www.google.com/finance/historical?q=MSFT&output=csv`

This URL is taken from this sample code of FSharp.Data CSV type providers: 
https://github.com/fsharp/FSharp.Data/blob/904a7b4cc446257061809993f059b6d6b32eae37/docs/content/library/CsvProvider.fsx

So I think this issue can be closed 🙂

**Comment by eriawan** [comment]
@tmat 
Oops, my bad...
Looks like the Wiki can be cloned. OK, I'll submit a PR for this Wiki page!

**Comment by eriawan** [comment]
hi @tmat 

Just a friendly reminder, please review. Or do I have to add/tag other person for notification to review this?

cc @kuhlenh (the author of the wiki page)

**Comment by eriawan** [comment]
@tmat and the rest of @dotnet/roslyn 

Is this issue still open for contributions?
Just a humble reminder, if this issue is still open, please review.

I have created a gist for the wiki page on my github's gist: https://gist.github.com/eriawan/948a140b338c5ee7416287a6caff51a7

Apologize if I may bother you by keep asking for attentions, because this issue seems to be ignored but it still has `up for grabs` tag. You can close or should close this issue if this issue should be ignored 🙂

**Comment by tmat** [comment]
@eriawan I have applied your changes. Thanks for the contribution.
