### ISSUE TITLE
SyntaxGenerator: support generating extension methods

### ISSUE THREAD

**Issue by tmds** [dotnet/roslyn#20002]
Does the SyntaxGenerator support generating extension methods?

**Comment by Pilchie** [comment]
I would think this would be just a matter of adding the`this` modifier?

**Comment by CyrusNajmabadi** [comment]
That would work for C#, but not for VB.  For VB you'd have to add the right attribute.  And that will be difficult to do correctly since these APIs don't take in compilations.  We could just hack it for VB by manually adding ```<Global.System.Runtime.CompilerServices.Extension>```, but it wouldn't properly simplify.  

Do you think we should do that @Pilchie ?

**Comment by CyrusNajmabadi** [comment]
@tmds Do you need to generate VB as well?  or just C#?

**Comment by tmds** [comment]
@CyrusNajmabadi c# is my interest. Is it possible using the C# SyntaxFactory.MethodDeclaration?

**Comment by CyrusNajmabadi** [comment]
Yes.  It would be trivial with SyntaxFactory.  Just pass the right modifiers when you call SyntaxFactory.Parameter so that it has the 'this' modifier on it.
