### ISSUE TITLE
Previews for light bulbs leaks solutions

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#20065]
**Version Used**: 400238e370ef760e178dd7a9db790e5feae7f3fb

**Steps to Reproduce**:

1. Create a new console app.
2. Invoke removed unused usings on the top.
3. Wait for the preview to appear.
4. Dismiss the preview.
5. GC.
6. Run !dumpheap -type PreviewWorkspace

**Expected Behavior**: There shouldn't be any.
**Actual Behavior**: There are two, because the solutions created to drive the preview are being leaked. The bad part of the GC root is I believe here:

            ->  27343b70 Microsoft.CodeAnalysis.CSharp.UseCollectionInitializer.CSharpUseCollectionInitializerDiagnosticAnalyzer
            ->  2733fea0 Microsoft.CodeAnalysis.Diagnostics.AnalyzerManager+AnalyzerExecutionContext (dependent handle)
            ->  27381f58 System.Collections.Generic.Dictionary`2[[Microsoft.CodeAnalysis.Diagnostics.AnalyzerOptions, Microsoft.CodeAnalysis],[System.Runtime.CompilerServices.ConditionalWeakTable`2[[Microsoft.CodeAnalysis.Compilation, Microsoft.CodeAnalysis],[System.Threading.Tasks.Task`1[[Microsoft.CodeAnalysis.Diagnostics.HostCompilationStartAnalysisScope, Microsoft.CodeAnalysis]], mscorlib]], mscorlib]]
            ->  27382050 System.Collections.Generic.Dictionary`2+Entry[[Microsoft.CodeAnalysis.Diagnostics.AnalyzerOptions, Microsoft.CodeAnalysis],[System.Runtime.CompilerServices.ConditionalWeakTable`2[[Microsoft.CodeAnalysis.Compilation, Microsoft.CodeAnalysis],[System.Threading.Tasks.Task`1[[Microsoft.CodeAnalysis.Diagnostics.HostCompilationStartAnalysisScope, Microsoft.CodeAnalysis]], mscorlib]], mscorlib]][]
            ->  27644ef0 Microsoft.CodeAnalysis.Diagnostics.WorkspaceAnalyzerOptions
            ->  275a6700 Microsoft.CodeAnalysis.Solution

**Comment by jasonmalinowski** [comment]
FYI to @Pilchie, @heejaechang, @CyrusNajmabadi, and @jinujoseph....this seems bad.

**Comment by jasonmalinowski** [comment]
Translating the gc root output a bit, the offender here seems to be https://github.com/dotnet/roslyn/blob/400238e370ef760e178dd7a9db790e5feae7f3fb/src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerManager.AnalyzerExecutionContext.cs#L23. We are starting analysis and using the AnalyzerOptions as the key, but that's never being removed. In the in-proc case the WorkspaceAnalyzerOptions holds onto the solution, which is rooting the Solution from there.

**Comment by heejaechang** [comment]
this seems due to this PR.

https://github.com/dotnet/roslyn/pull/19277

I will revert the last commit which seems caused the issue.
https://github.com/dotnet/roslyn/pull/19277/commits/a68da9dbf8fb5cebb7461a271cf6c32d28261cec

**Comment by heejaechang** [comment]
@jasonmalinowski curious. the solution leaked, is it from PreviewWorkspace? trying to figure out what caused PreviewWorkspace from being leaked.

**Comment by CyrusNajmabadi** [comment]
That last commit was added to address race conditions in the code prior to the commit.  Do you know how you can handle the race conditions that will arise if we're not accessing the solution snapshot, but instead accessing .CurrentSolution?

**Comment by CyrusNajmabadi** [comment]
> We are starting analysis and using the AnalyzerOptions as the key, but that's never being removed. 

This seems to be the issue.  Why is AnalyzerOptions not bein removed once analysis is complete?

**Comment by jasonmalinowski** [comment]
@heejaechang The Solution is holding onto the PreviewWorkspace, since Solutions root their workspace.

Reverting that commit is not the correct fix: that would still mean the AnalyzerOptions object _itself_ is being leaked, and would still be leaking all the Workspace objects.

**Comment by CyrusNajmabadi** [comment]
The whole chain here is weird.  We have a singleton AnalyzerManager which then has this:

```C#
        // This cache stores the analyzer execution context per-analyzer (i.e. registered actions, supported descriptors, etc.).
        private readonly ConditionalWeakTable<DiagnosticAnalyzer, AnalyzerExecutionContext> _analyzerExecutionContextMap =
            new ConditionalWeakTable<DiagnosticAnalyzer, AnalyzerExecutionContext>();
```

So... from a single DiagnosticAnalyzer, we hold onto an AnalyzerExecutionContext.  So once a DiagnosticAnlayzer is instantiated and placed into this cache, we hold onto the AnalyzerExecutionContext forever...

Then AnalyzerExecutionContext has this:

```c#
            // This map stores the tasks to compute HostCompilationStartAnalysisScope for per-compilation analyzer actions, i.e. AnalyzerActions registered by analyzer's CompilationStartActions.
            // Compilation start actions will get executed once per-each AnalyzerAndOptions as user might want to return different set of custom actions for each compilation/analyzer options.
            private Dictionary<AnalyzerOptions, ConditionalWeakTable<Compilation, Task<HostCompilationStartAnalysisScope>>> _lazyCompilationScopeMap;
```

This seems super weird.  

How does any of this stuff every get cleaned up.  We'll never let go of the context.  And the context will never let go of AnalyzerOptions.

**Comment by jasonmalinowski** [comment]
@CyrusNajmabadi My reading is the context is intended to be a singleton per analyzer, and then the stuff inside that context is supposed to get cleaned up. But it's not.

**Comment by heejaechang** [comment]
@jasonmalinowski @CyrusNajmabadi code was that was for long time though.

this is original code 
https://github.com/dotnet/roslyn/pull/19277/commits/e846ff7a8c2322d4a760ba03805aeff8e46cf678#diff-9669ae7e608e196288da6193aebd3a53L123

**Comment by heejaechang** [comment]
@mavasani hey manish, is this due to AnalyzerManager singleton issue? how the lifetime of context work here? is it because someone not calling some cleanup on AnalyzerManager?

**Comment by heejaechang** [comment]
@mavasani should we push again to make AnalyzerManager's life time not to be singleton but can be explicitly managed by host? this AnalyhzerManager being singleton is making things to be too complex.

**Comment by heejaechang** [comment]
@mavasani for preview workspace who should call this? http://source.roslyn.io/#Microsoft.CodeAnalysis/DiagnosticAnalyzer/CompilationWithAnalyzers.cs,171a3b0b590b2734,references

but also, this has been this way for long time, not sure why this suddenly happen. my gut feeling is due to conditionalweaktable referencing things in reverse way.

**Comment by heejaechang** [comment]
@mavasani now with OOP, this host context being maintained for the life time of diagnostic analyzer is no longer true. and we have no evidence that anyone actually care about it since with OOP, all those analyzer must have been all broken no we have no feedback at all for it. so can we remove it now?

**Comment by mavasani** [comment]
This is a requirement of analyzer execution semantics - Initialize method should get executed only once for the lifetime of the analyzer, which for VSIX Analyzers is lifetime of VS. We cannot get rid of the context when executed in VS workspace. Ideally, we would expose the AnalyzerManager or some variation of it as a public API and the workspace host will control its lifetime and cleanup on Dispose - this was pushed back by the design team due to API complexity, but I believe we should expose it given the high chances of leaks.

**Comment by mavasani** [comment]
@heejaechang Whoever creates and maintains analyzer instances owns clearing the analyzer execution state.

If the design team agrees to break the single Initialize call requirement, then we can remove the singleton. Though this will regress perf for Analyzers with expensive Initialize method.

If we decide to retain this requirement, we should move the responsibility of handling the lifetime of analyzer execution context to the host.

**Comment by heejaechang** [comment]
@mavasani but that requirement is already broken? OOP does that on every single time it runs analyzers. I believe only one person who insist that requirement was John and I don't believe we need to keep it anymore.

**Comment by mavasani** [comment]
So I digged more into this and it seems this regressed recently with our editor config related work. [WorkspaceAnalyzerOptions](http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/Diagnostics/WorkspaceAnalyzerOptions.cs,f7c93afef035f537,references), which is really a super hack for IDE analyzers to consume workspace, now strongly holds onto the solution snapshot. I see couple of trivial fixes for this for 15.3 to avoid the leak:

1. WorkspaceAnalyzerOptions should not hold onto solution snapshot. Even as a hack, it was only meant to give access to the workspace wide, solution agnostic options. Now it is more of solution options, not workspace options.
2. Switch the map [here](http://source.roslyn.io/#Microsoft.CodeAnalysis/DiagnosticAnalyzer/AnalyzerManager.AnalyzerExecutionContext.cs,23) to be a CWT instead of a dictionary.

Long term fix (15.6):
1. AnalyzerManager has always being a singleton since Dev14, and the design time have always pushed back on exposing some public API on CompilationWithAnalyzers that controls the lifetime of the analyzer execution state. I agree with HeeJae that we should strongly push to expose something here so host controls lifetime. I don't think we should require changing analyzer semantics, and possibly causing functional/perf regressions in shipped analyzers. Logically, analyzer host instantiates the analyzers, and should be tracking its lifetime and disposing the analyzer execution state when it is done with it. Let me come up with an API proposal here and start a thread with the API design team.

2. Delete internal types WorkspaceAnalyzerOptions and IBuiltInAnalyzer - these two are hacks that we have always want to get rid of an invariably lead to lot of subtle performance and functional bugs. I presume we can get rid of them only when the IDE analyzers become completely agnostic of Workspace and everything flows via editorconfig. A follow up work item would be to seal AnalyzerOptions.

**Comment by jasonmalinowski** [comment]
> WorkspaceAnalyzerOptions should not hold onto solution snapshot. Even as a hack, it was only meant to give access to the workspace wide, solution agnostic options. Now it is more of solution options, not workspace options.

That will happen for 15.6, but I think for 15.3 we need to leave this as is.

> Switch the map here to be a CWT instead of a dictionary.

What is the intended lifetime of the AnalyzerOptions? That's potentially a long-lived type, is that the right pattern? I admit I would have expected that dictionary to be `ConditionalWeakTable<Compilation, Dictionary<AnalyzerOptions, ...>>` so that way as soon as a compilation falls away everything else falls away.

**Comment by jasonmalinowski** [comment]
I'm also not sure if the WorkspaceAnalyzerOptions change was actually the precipitating cause: it turns out we create a PreviewWorkspace for each file in a lightbulb preview, so if we were previously holding onto the Workspace we were still leaking all solutions and workspaces, since the workspace has it's CurrentSolution. We're leaking in the reverse direction (this is solution holding to workspace, rather than the other way around), but both would have been leaked.

**Comment by heejaechang** [comment]
@jasonmalinowski there are too many ConditaionalWeakTables, so it might start to leak since someone somewhere put a type in ConditaionalWeakTable. one thing we know was PreviewWorkspace didn't leak before which I know since I did some work to make sure it doesn't leak.

also, editor's LB will cache last preview window until caret gets moved (LB refreshed) so PreviewWorkspace will be alive until that happen.

anyway, lets do some cheap thing to remove leak in 15.3 and remove root cause of all these in 15.6 which was known issue for a long time - https://github.com/dotnet/roslyn/issues/2830

**Comment by heejaechang** [comment]
@mavasani information on #2830 is slightly outdated. but regardless, end goal is making AnalyzerManager not singleton but something one can create and throw away as one sees.

**Comment by jasonmalinowski** [comment]
> one thing we know was PreviewWorkspace didn't leak before which I know since I did some work to make sure it doesn't leak.

Given we didn't have any tests on this, I'm not sure I share your confidence there. I agree it didn't leak when you last fixed bugs here...and it was probably regressed thereafter but prior to the WorkspaceAnalyzerOptions change.

**Comment by heejaechang** [comment]
@jasonmalinowski well, if you have an idea on how to detect leak in test, I believe many people will welcome that new tool. I believe Kyale tried to add such tool to unit tests and eventually gave up.

**Comment by sharwell** [comment]
@mavasani Can you clarify which release this bug first appeared in?

**Comment by mavasani** [comment]
I and Heejae feel this happened when Workspace analyzer options started holding onto the solution. Previously it held onto workspace options only. Heejae, did this change happen post Dev15 RTW?

**Comment by heejaechang** [comment]
yep after RTM. I believe it happens for 15.3
