### ISSUE TITLE
Private constant fields can be used in attribute declarations on containing class

### ISSUE THREAD

**Issue by JamesFaix** [dotnet/roslyn#20186]
**Version Used**: C# 6

**Steps to Reproduce**:

1.  Create a class declaration with a private `const` field.
2.  Put an attribute on that declaration and use the constant as a parameter.

**Expected Behavior**:
I would expect that the constant would be undefined / out-of-scope where the attribute is.

**Actual Behavior**:
It compiles just fine.  However, if the constant is made into a `readonly` field, it will not compile.  Likewise, a `const` local in a method body cannot be used as a parameter of an attribute on the containing method's declaration.

```
[MyCustomAttribute(MY_CONST)] //Compiles
public class MyClass {
    private const int MY_CONST = 1;
}
```

```
[MyCustomAttribute(MY_READONLY )] //Does not compile
public class MyClass {
    private readonly int MY_READONLY = 1;
}
```

```
public class MyClass {
    [MyCustomAttribute(MY_CONST)] //Does not compile
    public void MyMethod() {
        const int MY_CONST = 1;
    }    
}
```

**Comment by jaredpar** [comment]
> I would expect that the constant would be undefined / out-of-scope where the attribute is.

The C# rules allow for this behavior. It's mostly covered in section 7.5.2 (Simple Names). Specifically the following section. 

- Otherwise, if a member lookup (§7.3) of I in T with K type arguments produces a match:
    - ... 
    - Otherwise, the result is the same as a member access (§7.5.4) of the form **T.I** or T.I<A1, ..., AK>. In this case, it is a compile-time error for the simple-name to refer to an instance member.

Hence the compiler essentially interprets `MY_CONST` as `MyClass.MY_CONST`.

> It compiles just fine. However, if the constant is made into a readonly field, it will not compile.

That is "By Design". All attribute arguments must be either

- A constant value.
- A System.Type object.
- A one-dimensional array of attribute-argument-expressions.

A `readonly` field doesn't meet this requirement and hence is properly an error. 

> Likewise, a const local in a method body cannot be used as a parameter of an attribute on the containing method's declaration.

The name lookup rules described in 7.5.2 don't allow for attributes to use members declared within a function body.

**Comment by vladd** [comment]
@jaredpar I understand your point, but doesn't this contradict §3.7 *Scopes*?

> * The scope of a member declared by a *class-member-declaration* (§10.1.6) is the *class-body* in which the declaration occurs.

The *class-body* (according to §10.1.6) includes braces and class member declarations between them. 

Shouldn't we amend §3.7 to include the whole *class-declaration* and not only *class-body*?
