### ISSUE TITLE
Bad error messages for virtual local functions

### ISSUE THREAD

**Issue by svick** [dotnet/roslyn#20279]
**Version Used**: master (5fbdd5c5)

**Steps to Reproduce**:

[Create a `virtual` local function](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQBMQGoA+ABATAAgGEBYAKAG8z9r9sAWfAWQAoBKKmy0mn/ANwCWCGAFcIAG1oMAYm3zkAvh2pLSCoA=):

```c#
class C
{
    void M()
    {
        virtual void F() {}
    }
}
```

The `abstract`, `extern` and `partial` modifiers behave the same way (and few others probably too).

**Expected Behavior**:

> error CS0106: The modifier 'virtual' is not valid for this item 

**Actual Behavior**:

>    error CS1513: } expected
>    error CS1022: Type or namespace definition, or end-of-file expected
>    error CS0621: 'C.F()': virtual or abstract members cannot be private

The only reason I can think of why anyone would attempt to write such a local function is because they don't realize they're writing a local function (i.e. they think they're in a class scope, but they're actually in a method scope). So this issue is probably not very important.

**Comment by svick** [comment]
[Attributes on local functions have a similar issue.](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQBMQGoA+ABADAAmwEYBuAWAChsAmfAYUoG9L9XCAWfAWQAoBKFm2YU2o/AG0A8sCgB7ADZx4AXQ74AYv3yMAvoNZ6KOoA==)

**Comment by jcouv** [comment]
FYI @agocke

**Comment by agocke** [comment]
@jcouv @jaredpar This behavior was intentional. This is incorrect code behavior that has an unfortunate ambiguity. One case is @svick's, where `virtual` is just misused as a local function modifier. Another case is the following:

```csharp
class C
{
    void M()
    {

    virtual protected void M2()
    {
    }
...
}
```

As you can probably guess, the behavior for that example is that the user is in the middle of typing a new method, `M`, above the existing method `M2`. If we parsed virtual as valid modifier for local functions and then gave an error, this would produce the behavior of parsing the entirety of `M2` as a local function, not a method, like it actually is.

Unfortunately, it is ambiguous what situation we're actually in when parsing the `virtual` modifier, so there's no real way of knowing what the user intended. However, I think the latter case is far more likely than the previous, so I prefer the behavior of parsing the `virtual` as the start of a new member instead of the start of a local function.

Do you agree?

**Comment by jcouv** [comment]
Thanks for the clarification. I agree that the trade-off in error recovery makes sense. Typing a new method is very common compared to writing a local function (especially one with bad modifiers).

Tagging @t-camaia FYI, since we discussed that earlier today.

**Comment by svick** [comment]
@agocke 

> I think the latter case is far more likely than the previous

Is it? Both in VS and in VS Code, when I type the opening brace of a method, the editor automatically adds the closing brace. So I'm never in a situation where just the opening brace exists, at least with default settings. (It might be interesting to know how many people have "Acutomatic brace completion" disabled for C#, but I don't know how easily are such statistics accessible for you, if they are at all.)

---

Another option that I considered was to take indentation into account in this case. It wouldn't make the language itself depend on indentation, since it's pretty much only about deciding which error to show.

Though I assume doing that could require significant changes to the parser, so it probably wouldn't be worth it.

**Comment by agocke** [comment]
Well, you also have to approximate how many people type `virtual` for a local function. I suspect very few, less than the number of people with automatic brace completion disabled.

**Comment by CyrusNajmabadi** [comment]
To give some more context on this.  When the parser encounters an error, it has to decide what to do (and it wants to make that decision quick, so as to to not slow down parsing excessively).  In the case of an error, it has to decide "is the user typing something i would expect in my current context" (and thus, it should be parses locally in the current parser context), or "is the user typing something i would expect in an outer context" (and thus i should stop what i'm doing and let a higher context decide).

In cases of non-ambiguities (i.e. 'class' inside a method) the choice is pretty obvious and clear.  However, with something like "virtual void" there are multiple choices hte parser could make.  In such ambiguous cases we err on both how likely each branch of the ambiguity is.  Similarly, when one branch of the ambiguity is strictly illegal, and the other isn't, the legal interpretation is strongly preferred.

This makes a ton of sense as telling the user "you can't have a virtual local function" is going to be very confusing to people who just say "but... this isn't a virtual local function, it's a method!".

--

Note: we generally do not consider things like "brace completion" as it's *completely* normal to end up in these situations *even* with brace completion on.  That's because users are constantly editing existing code, changing indentation, deleting braces, etc.  So even with brace completion, it would be expected and normal to still run into cases where sibling method become nested.

--

Finally, there can be very severe consequences for making sibling code into child code (i.e. making a method into a local function).  Specifically, it ends up causing tons of cascading errors as a lot of existing code that does things like "this.SiblingMethod()" no longer binds properly.  When all your following methods become local functions it's a *bad* time for intellisense.  Indeed, it's so bad, that when we find cases where we accidenly suck in sibling members into the local method, we work hard in the parser to try to undo that so that it doesn't so negatively impact hte experience.

**Comment by CyrusNajmabadi** [comment]
> Is it? Both in VS and in VS Code, when I type the opening brace of a method, the editor automatically adds the closing brace. So I'm never in a situation where just the opening brace exists, at least with default settings

This is not actually true (though i bet you didn't realize it even with your own typing).  Users *very* often run into mismatched braces even when they have "brace matching on".  This happens because of things like cut/paste, standard editing, and all sorts of other code manipulation patterns that end up easily deleting a brace as they're in the middle of things.  We've actually worked hard in the parser to ensure that in these cases, we don't get tripped up, and we can still properly understand the shape of your class/struct as otherwise you get a huge swath of cascading errors once all successive sibling members are pulled into the type.

Given that there are two interpretations:
1. user has a sibling virtual method.   Totally reasonable.  Exists in millions of lines of code.
2. user is trying to write a bogus virtual local function.  Not very reasonable.  Not actually ever allowed/legal in C#.  

Going with the first interpretation is not only sensible, but necessary so that these types of edits don't lead to an utterly terrible intellisense/error-squiggle situation when all sibling members are reinterpreted as nested functions.

**Comment by svick** [comment]
Thank you all for the explanations, you've convinced me that it's better the way it is. As far as I can tell, that means that everyone agrees and that there is nothing to do here, so I'm closing this issue.

**Comment by agocke** [comment]
@svick Thanks for your patience!

**Comment by CyrusNajmabadi** [comment]
Any time :)
