### ISSUE TITLE
clean up CodeGen Service

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#2037]
we have 2 different CodeGen services, a new one and old one. we need to start clean up and make all of our features to rely on the new CodeGen service.

also, while doing that, we need to rationalize what we will do when code generation is failed such as no good place to inject code and etc.

**Comment by shyamnamboodiripad** [comment]
I was looking into TFS bug 1164126 which was about a crash when code generation service is trying to generate a property into some node that's not TypeDeclarationSyntax (most likely in a broken code scenario).

Looking at the code, AbstractCodeGenerationService.CheckDeclarationNode() is called all over the place and all overloads of AbstractCodeGenerationService.CheckDeclarationNode() throw ArgumentException if an unexpected node type is encountered.

Code Fixes / Refactorings that rely on AbstractCodeGenerationService don't seem to be resilient against these ArgumentExceptions. In other words, they seem to expect that AbstractCodeGenerationService will never throw. So whenever AbstractCodeGenerationService throws, the corresponding Fix / Refactoring will fail and we will end up disabling it for the rest of the user's VS session. User will have to restart VS in order to get that Fix / Refactoring back.

We either need to change the Code Fixes / Refactorings to be able to recover from these exceptions somehow OR thread success / failure status back to the calling Code Fix / Refactoring. Perhaps moving Code Fixes / Refactorings to the new service will solve this issue? I am not sure whether it suffers from similar problems, but this is something we need to consider when we get to fixing this issue.

**Comment by CyrusNajmabadi** [comment]
> We either need to change the Code Fixes / Refactorings to be able to recover from these exceptions somehow OR thread success / failure status back to the calling Code Fix / Refactoring.

I disagree.  This is a problem with the code-fixes/refactorings.  They should not be trying to do things that are just not possible.

**Comment by CyrusNajmabadi** [comment]
Closing this out as it's not really actionable currently.  We have made some progress on this.  If htere are further places we need this, we should drive it with real use cases and PRs.
