### ISSUE TITLE
Give me a way to easily find the base of an override, or an interface method of an interface

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#20383]
Run into this in the past and I find that there's no good way to do this today that I can find.

**Problem:**
I found a `GetHashCode` override that was allocating, which is a big no no. I decide to find all overrides of GetHashCode in our code to inspect everyone of them and fix them as needed.

**First Approach:**
I right-click on the `GetHashCode` override and choose **Find All References**, as I remember that this shows me all overrides regardless of at what point in the hierarchy chain they override .
This takes forever > 1 minute (I thought it was supposed to show progressive results?), and I quickly realize this isn't a good approach as this ends up give me lots of results and intermixes usages with overrides. I would love an http://index like experience here, where implementations are separate to assignments/usages.

**Second Approach:**
**Go To Implementation** to the rescue! I right-click on the override and choose **Go To Implementation**, this gives me zero results. In contrast to **Find All References**, **Go To Implementation** only considers _actual_ overrides of the method you invoked it on. (This behavior does make sense, but why is **Find All References** different in this regard?)

**Third Approach:**
I realize that I want to do a **Go To Implementation**, but on the base method. How do I get myself to the base method? The only way I could quickly find the method I was overriding, was to manually type `base.GetHashCode()` in the method body and then **Go To Implementation** on that.

**Conclusion**
There has to be an easier way. I'm thinking I want a **Go To Base** that takes to the base method or interface method that this thing is implementing (the reverse of **Go To Implementation**) or something like that, but also open to better ways to make this work.

**Comment by davkean** [comment]
tag @CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
Talking to @Pilchie about reinvesting in this area.

**Comment by jcouv** [comment]
Relates to https://github.com/dotnet/roslyn/pull/22963

**Comment by jcouv** [comment]
GoToDefinition can [now ](https://github.com/dotnet/roslyn/pull/22963) be invoked on the keyword `override`, and it will take you to the overridden method on the right base class.

As for finding which interface a certain method implements, this was discussed by the IDE team, but I don't know if a decision was made (@jinujoseph @kuhlenh would know).
The solution of using GoToDefinition doesn't work since implicit interface implementations have no keyword that you could invoke GoToDefinition on...
In the meantime, Sam has an extension ([InheritanceMargin](https://github.com/tunnelvisionlabs/InheritanceMargin/)) that solves that scenario.

**Comment by jcouv** [comment]
FWIW, the way I currently manage such situations is to use GoToDef on `override` keyword until I find base I want, then GoToImplementation on that method.

**Comment by ivanbasov** [comment]
Completed implementation with #35779
