### ISSUE TITLE
Annotations get lost during tryapplychanges

### ISSUE THREAD

**Issue by TFTomSun** [dotnet/roslyn#20411]
**Version Used**: 

**Steps to Reproduce**:

1. Create a msbuild workspace by e.g opening an existing solution
2. Get a document and annotate some nodes to keep track of them
3. Apply the changes (added annotations) to the workspace
4. Get the solution instance from the workspace 

**Expected Behavior**:
The solution of the workspace contains the documents with annotated syntax nodes

**Actual Behavior**:
The annotations are lost. All other changes are applied

I assume that this behavior is wanted, however i would like to know how to track nodes over multiple changes when my annotations are lost/not applied.

Best regards, Tom

**Comment by Pilchie** [comment]
This happens because we actually apply textual changes to the file in `TryApplyChanges` and then reparse a new tree (so that the tree in the workspace is always guaranteed to be round-trippable, etc).

In the IDE, we have an internal helper [`SyntaxPath`](http://source.roslyn.io/#q=SyntaxPath) to help find nodes again after an edit.
