### ISSUE TITLE
"Neither 'is' nor 'as' are valid on void type"

### ISSUE THREAD

**Issue by Logerfo** [dotnet/roslyn#20452]
**Version Used**: Visual Studio Enterprise 2017 15.2 (26430.12), .NET Framework 4.6.2

Consider the following line of code:
```c#
bool b = Console.Write("A") is var _;
```
Visual Studio shows a red squiggle with the following error:
>Neither 'is' nor 'as' are valid on void type

However, the code successfully builds. 

I suspect this is not the desired behavior.

**Comment by jaredpar** [comment]
@gafter can you take a look at this?

**Comment by Logerfo** [comment]
I could not find the error [resource](https://github.com/dotnet/roslyn/blob/94ca919c6b4c94857dc5d58df4e6e10cb8d55c3c/src/Compilers/CSharp/Portable/CSharpResources.resx). The closer I [got](https://github.com/dotnet/roslyn/blob/94ca919c6b4c94857dc5d58df4e6e10cb8d55c3c/src/Compilers/CSharp/Portable/CSharpResources.resx#L1012) was `Neither 'is' nor 'as' is valid on pointer types`. Has this been fixed already?

**Comment by TessenR** [comment]
@Logerfo it looks like Roslyn doesn't highlight the line. Probably an extension like ReSharper does.

However I wonder if the example should really compile since an ability to declare a variable of 'void' type probably isn't intended. Especially since the 'var' pattern can't introduce variables of some other types e.g. pointers.

For example the following program
```cs
bool b = Console.Write("A") is var a;
```
Compiles but crashes at runtime with the following exception:
```
System.InvalidProgramException: 'Common Language Runtime detected an invalid program.
```

**Comment by Logerfo** [comment]
@TessenR You're right, it was Resharper fault. My bad.

I suspended Resharper and the squiggle was gone, but now I tried [this](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxASwDZICYgNQA+AAgAwAERAjANwCwAUEQMwUBMZAwmQN4Nn8UWRACxkAsgAoAlDz4D5aAGZkJHAPYA7KGoxwAdAHUEaeABk0GuNLJooZAG4QEZAB5S58z55dkAvJ01tXUNjeAkAInCpOnp5AF8GOKA) and weird stuff is happening.
