### ISSUE TITLE
[Completion] Need a way to control override completion

### ISSUE THREAD

**Issue by mkrueger** [dotnet/roslyn#20474]
For some methods it would be nice if it would be possible to create a specialized method stub:

For example for overriding ToString it would look like:
----
        public class Test
        {
                public int FooBar { get;  }

                public override string ToString ()
                {
                    return $"[Test: FooBar={FooBar}]";
                }
        }
-----
Instead of:

----
        public class Test
        {
            public int FooBar { get; }

            public override string ToString()
            {
                return base.ToString();
            }
        }
----

**Comment by CyrusNajmabadi** [comment]
This would need to go through an API proposal.  in general, the reason we don't just make things public is because it increases maintenance costs and locks down our ability to change things in teh future.  We can open things up, but we have a process that requests need to go through to make sure the appropriate people weigh in and the right API shape is determined and shipped.
