### ISSUE TITLE
[Completion] Request to add a new text tag.

### ISSUE THREAD

**Issue by mkrueger** [dotnet/roslyn#20477]
If a completion item is a code snippet. The press twice text is marked as 'Text' in the tagged parts of the description. 

It would be nice if it could get another tag like 'SnippetText' or something else to make a difference. In the XS tooltip that text appeared a bit below the other text and in a different font/color. 

Would help - but it's just a minor issue.

**Comment by CyrusNajmabadi** [comment]
This would need to go through an API proposal.  in general, the reason we don't just make things public is because it increases maintenance costs and locks down our ability to change things in teh future.  We can open things up, but we have a process that requests need to go through to make sure the appropriate people weigh in and the right API shape is determined and shipped.
