### ISSUE TITLE
Named tuples in interfaces / overrides do not round trip to C# 6

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#20528]
Consider the following interface from a DLL which was authored in C# 7.0:

``` c#
public interface IUtil {
  void M((int a, int b) x);
}
```

It is possible to implement this interface in C# 6 or C# 7. However there is no single code snippet which will compile in both C# 6 and C# .  This is due to restrictions around tuple name matching. In C# 7 the names on the tuples must match exactly hence the only legal implementation is the following:

``` c# 
// C# 7 
class Class1 : IUtil {
  public void M((int a, int b) x);
}
```

In C# 6 the tuple syntax does not exist hence the only possible option is to use the long form tuple name:

``` c# 
// C# 6
class Class1 : IUtil {
  public void M(Tuple<int, int> x);
}
```

As stated earlier though, this syntax won't compile in C# 7 because it lacks names and hence doesn't match according to language rules. This means it's impossible to have a single implementation that compiles in C# 6 and 7 that doesn't resort to `#if / #else` blocks. 

After some discussion in LDM today we decided that we will relax our OHI (override, hiding, implementing) rules for tuples. Signatures which contain only tuples without names will match signatures that have tuples of any name.

**Comment by sharwell** [comment]
I'm not a particular fan of this change for the following reasons:

1. If compiling with C# 6 is needed, then either the C# 6 compiler (Roslyn 1.x) is being used, or the `<LangVersion>` element in the project will be set to 6. In either case, only one syntax is needed.
2. If compiling with C# 6 is not needed, then C# 7 is in use and only one syntax is needed.

The only people this is burdensome for is a group that is *incrementally* switching to C# 7 and *also* leveraging C# 7 features in the process.

If a workaround is necessary to handle this case, I would prefer it be one that places the burden solely on users clinging partially to C# 6, as opposed to the solution above which takes away from C# 7 users. As a specific example, the C# 7 compiler could be modified to accept the desugared form of a tuple with named elements (`ValueTuple<int, int>` with explicitly-added attributes) in place of the C# 7 syntax.

**Comment by jcouv** [comment]
@sharwell The scenario as you describe it (users incrementally adopting C# 7) is less likely than the scenario where a C# 6 user references a library from nuget which includes C# 7 metadata.

**Comment by sharwell** [comment]
Seems like the solution here is to make sure that a good (reliable + accurate) code fix for the resulting compiler error is in place so users who upgrade from C# 6 to C# 7 can easily correct this in the rare case where it appears.

**Comment by jcouv** [comment]
In the case Jared raised, the project needs to compile both with VS2015 and VS2017, with language version 6. Without the relaxation proposed in this issue, that is not possible. Any fix offered by the code fixer will cause a compilation failure either in VS2015 or VS2017.

**Comment by sharwell** [comment]
@jcouv It was my understanding that the fix proposed by Jared would apply regardless of the `<LangVersion>` value. I believe that the following changes are more appropriate:

1. Roslyn 2.x should allow the `ValueTuple<int, int>` type to implement a signature with named tuple members if (and only if) `<LangVersion>` is less than 7.
2. Relax the restriction that `[TupleElementNames]` cannot be used directly; it should only be enforced in cases where the new tuple syntax appears. The attribute should be allowed to appear in source code for users who instead choose the `ValueTuple<int, int>` syntax.

**Comment by jcouv** [comment]
I'm confused by your comment. Yes, the proposal of OP would apply regardless of language version. I did not claim otherwise. I simply described problematic scenarios.

1. For the OHI problem, the option you propose is still a break (users are forced to fix their code when they upgrade to a new language version). But we did not discuss that option with LDM. 
My feeling is this is too big of a break (perfectly good/mainstream C# 6 code compiled against new metadata, which we intend to work, but which breaks when you upgrade your language version).

2. For the attribute problem, we discussed something along those lines, but it is challenging to define from a language perspective and also to implement. What if you have partial method declarations (one with VT and one with tuple syntax)? What if you have a `Pair<(int, int), ValueTuple<int, int>>` (can you use the attribute here)? Also, from the start we have tried to unify the concepts (similarly to nullable, where the symbols for `int?` and `Nullable<int>` are the same), but now we'd introduce a difference based on syntax.
More importantly, the attribute is intended for compiler usage, not for usage in source, LDM confirmed that we do not want to support using the attribute in source (even with a C# 6 compiler). If you do it, you're on your own (that will break when you update to a C# 7 compiler, and that is acceptable).
We discussed marking the attribute as `Obsolete` and `EditorBrowsable(Never)` to dissuade such usage and prevent the IDE from inserting it (with "Implement Interface" for example).

**Comment by sharwell** [comment]
Can we correct this my simply changing the error to a warning? That way, in the exceedingly rare cases where it becomes relevant, users will have the option of writing the form without names with a warning suppression as a way to round-trip the values.

**Comment by jcouv** [comment]
Warnings are still source breaks, like errors. This was considered in LDM, which preferred to stick with the principle that "C# 6.0 code should never break when you upgrade to C# 7.0."

Once we implement warning waves, we could implement the stricter behavior again, as users opt-into warning waves willingly.
