### ISSUE TITLE
Create a helper to walk up conditional access expressions

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#20576]
We need an extension that handles proper walking of conditional access expressions so every feature doesn't have to rewrite the same code (see https://github.com/dotnet/roslyn/pull/20509).

**Comment by CyrusNajmabadi** [comment]
Closing out.  Code that actually walks up these is often suspect.  I've found a bunch of cases where we do walk up this, opting to think of `a?.b.c` as if it was more `(a?.b).c`, instead of `a?(.b.c)`.  But it's really not appropraite to think of it as the former and it often causes bugs.  I think code should be explicit here and should have be quite specific about what behavior it expect if it were in the when-not-null portion of the conditional.
