### ISSUE TITLE
PersistentStorageService doesn't have primary solution registration

### ISSUE THREAD

**Issue by Therzok** [dotnet/roslyn#20581]
**Version Used**: 
411e6061c76d6549b9111c33d310c6c6bbccb99c

**Steps to Reproduce**:

1. Create your own Host
2. Try using the IPersistentStorageService
3. Every query to the persistent storage ends up reading the whole database each time because nothing registers the primary solution. That is done by hosts (eiither Remote or VS Workspace) via http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces.Desktop/Workspace/Storage/PersistentStorageService.cs,0441a6597eb54901,references

**Expected Behavior**:
Ref-counting with an extra ref for the main solution should be handled by the default host implementation, not derived ones, thus the lookup shouldn't be cleared on every storage operation

**Actual Behavior**:
The ref is removed, the lookup is always empty when querying the storage so we reconstruct it every time

**Workaround**:
Cast the storage to an `AbstractPersistentStorageService` and register the solution yourself.

**Comment by CyrusNajmabadi** [comment]
Tagging @heejaechang 

VS4Mac ran into this with their host implementation.  It's a very strange API requirement that hosts have to know to call certain functions and cast to certain low level implementation details like this:

http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices/Implementation/ProjectSystem/VisualStudioWorkspaceImpl.cs,1325

If you don't do this, you will have a very poor performing storage subsystem.  But this is not documented or discoverable.  It's also only possible if you have IVT.

**Comment by heejaechang** [comment]
IPersistentStorageService itself doesn't force or has contract on what data will be saved and not. that is up to implementer. they can decide how to implement the service.

for example, they can have IPersistentStorageService per workspace. which remove need to register primary workspace since each service for each workspace can decide to use different implementation.

also they can decide whether they will support all solution or just primary soluation (one that is accessibly through Workspace.CurrentSolution)

when it doesn't support persistent service, one can either not export the service at all, or return false for Write and null for Read.

once data is saved, it is up to the implementation when the data will be removed.

for simplicity, in our implementation of the PersistentService in VS Workspace layer decide to support only primary solution. due to that, we need to know what is the primary solution. 

other implementation of the persistent service might or might not need it depends on how they implement their persistent service.

**Comment by heejaechang** [comment]
@Therzok how do you have IPersistentService when you are creating your own host? behavior of persistent service is tied to Host. our implementation of Persistent service is not general enough to be re-used. it should only exist in VSWorkspace. you should create your own one if you are doing your own Roslyn host.

for example, the interface
http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Workspace/Host/PersistentStorage/IPersistentStorageService.cs,8

just accept the solution, and but our implementation just throw away if solution is not from Workspace.CurrentSolution, or once data is saved, we never delete it since we only save one for primary solution.

depends on what behavior your host wants, you need to implement your own persistent service.

Roslyn internally should be guarded on either IPersistentService not exist or it being failed when try to save data.

**Comment by Therzok** [comment]
The main problem is that nothing is keeping the refcount around for the `IPersistentStorage` and that means that every time you query for the storage, roslyn will recompute the whole in-memory database.

Every operation is ref-unref, with an initial refcount of 0. You never have cached results and there is no way for the implementation to say hold on to the primary workspace

Register primary solution is not available as API [0] from `IPersistentStorageService` and the normal code flow does not register the first solution it hits as the primary one (because there is no way to set the primary solution id) [1]

We're not doing any special work, everything is just initialized for a workspace of kind `Host` and if we register our own `IPersistentStorageLocationService` [2]

[0] - http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces.Desktop/Workspace/Storage/PersistentStorageService.cs,277
[1] -http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces.Desktop/Workspace/Storage/PersistentStorageService.cs,190
[2] - https://github.com/mono/monodevelop/blob/roslyn-persistent-storage-services/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopPersistentStorageLocationService.cs#L46

**Comment by Therzok** [comment]
As a note, we're using the stock SQLiteStorageService.

**Comment by Therzok** [comment]
By having CodeAnalysis.Workspaces.Desktop.dll in the composition (for a lot of other things), we cannot define our own `IPersistentStorageService`, so we rely on the default.

**Comment by Therzok** [comment]
Actually, if RegisterPrimarySolutionifNeeded [0] checked whether the Solution that's passed is Workspace.CurrentSolution, that would work for me!

[0] -
 http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces.Desktop/Workspace/Storage/PersistentStorageService.cs,190

**Comment by heejaechang** [comment]
@Therzok you can implement your own.

give it ServiceLayer.Host.

[ExportWorkspaceServiceFactory(typeof(IPersistentStorageService), ServiceLayer.Host), Shared]

then yours will be picked up.

**Comment by CyrusNajmabadi** [comment]
@heejaechang the problem is that we don't have an actual API here.  We have implementation details which are known about innapropriately by other parts of the system (like VSWorkspaceImpl).  VSWorkspaceImpl shouldn't have to know how the storage system is implemented in order for things to be efficient.  If it needs to communicate in some manner, that should be exposed through some actual documented API.

**Comment by CyrusNajmabadi** [comment]
in other words, we should design this with the assumption that the VS layer doesn't have IVT do the workspace (or storage subsystem) layer.

**Comment by heejaechang** [comment]
@CyrusNajmabadi ya, that's why we never provided implementation to people who create their own host. since the service is very specific to host. now the problem is that persistent service is picked up by default. it should always be this. 
http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Workspace/Host/PersistentStorage/PersistentStorageServiceFactory.cs,12

**Comment by heejaechang** [comment]
if we do want to provide default implementation, we need to design it that way so that its behavior is general. such as delete unused data, support all solution given in, define behavior on shared access, and etc.

right now, our implementation doesn't do any of those, its implementation is specific to VS, and it return false for all cases it doesnt support.

**Comment by CyrusNajmabadi** [comment]
> its implementation is specific to VS

If it's speciifc to VS, it should be in the VS layer.  :)

**Comment by Therzok** [comment]
Given that the services are provided by default, they should work under the assumption of any user (with no performance hit). Wouldn't it be simpler to keep backwards compatibility by checking whether `solution.Workspace.CurrentSolution == solution` in case `primarySolutionId` is `null`?

I think that if the services are provided by default, they should work under the assumption that the stock provided storages function properly. Thoughts?

**Comment by heejaechang** [comment]
@CyrusNajmabadi yes. it used to be there. let's move it back.

**Comment by heejaechang** [comment]
@Therzok what we are saying is the IPersistentService was never provided by default. the bug is that we accidentally provided one in recent bit. we should remove the default implementation again. so that if host want persistent service, they should provide one themselves.

**Comment by heejaechang** [comment]
@Therzok once we provide default implementation, we need to provide support for it. and current implementation is never written to do such. so, I dont think we want to start expose the default behavior. persistency is really really tricky thing to support generally.

**Comment by Therzok** [comment]
https://github.com/dotnet/roslyn/blob/master/src/Workspaces/Core/Desktop/Workspace/Storage/PersistenceStorageServiceFactory.cs#L15

This is the storage service factory that gets imported. I think it's host-agnostic and it works fine, it's just that the service itself should know when to ref/unref itself. And, albeit untested, I think the suggestion I made above, to check the solution when the primarySolutionId is not set (with matching unref when the current solution is removed), is a good enough fix. That way we don't get in the way of whatever the VS layer does and other users have a thing which just works. 

Mind if I open a PR for that so we can retain currently exposed services?

**Comment by heejaechang** [comment]
@Therzok the factory used to exist in VS Layer and we move it down to attempt to share it with remote host not realizing other people will get it by default as well. we never intended to expose it or support it other than our own usage in VSLayer and ServiceHub.

if you want to re-use our implementation, you are fine to fork that code and export it yourself in your host.

as you know, there are a lot of code (for example, signature help service, syntax fact or semantic fact service, and a lot of helper extensions and etc.) in roslyn that people think good enough to make public but we can't for various reasons. (supporting backward compatibility will make us changing its behavior really really hard)

I am sorry. and also sorry for causing this confusion. if we haven't exposed it, you won't got into this issue at the first place.

**Comment by CyrusNajmabadi** [comment]
Let's not do any of that :)

The service works well for VS, VS4Mac and OOP.  We just need to not have VSWorkspace have special knowledge of it.  We should just define the capabilities we care about and make a real API for it.

**Comment by heejaechang** [comment]
Sure, if you want to add default implementation for persistent service for public, that's fine as well. just currently it is not designed for that.

**Comment by Therzok** [comment]
Seems fixed via https://github.com/dotnet/roslyn/commit/093be5af2f15abe411383f4c2f24d2434012d561#diff-95eabf2d9695966879d6bd572153790d
