### ISSUE TITLE
Is looking at ConvertedType of any of the two operands in a expression always valid?

### ISSUE THREAD

**Issue by halivingston** [dotnet/roslyn#2067]
In cases where an implicit or explicit conversion takes place, you can get TypeInfo for both operands. From the way Roslyn APIs are exposed it seems like looking at either left or right operand and looking at the ConvertedType field is good enough to know the final type of an expression?

Do I have this right?

**Comment by AnthonyDGreen** [comment]
@halivingston,

Sorry for the slow reply. This isn't the case. Take this example:

``` VB.NET
Module Module1
	Sub Main()
		Dim left As New ADerived, right As New BDerived

		Dim result As C = left + right
	End Sub
End Module

Class A
	Shared Operator +(left As A, right As B) As CDerived
		Return New CDerived
	End Operator
End Class

Class ADerived
	Inherits A
End Class

Class B
End Class

Class BDerived
	Inherits B
End Class

Class C
End Class

Class CDerived
	Inherits C
End Class
```
In this example both operands are converted from their actual types to their base types, neither of which is the result type of the expression. And the expression itself is being converted to yet another type. Because when dealing with overloaded operators the result type needn't match either of the types of the operands checking the converted type of the binary expression itself is always necessary.

Regards,

**-ADG**
