### ISSUE TITLE
Literal should escape surrogate unicode

### ISSUE THREAD

**Issue by vwxyzh** [dotnet/roslyn#20693]
**Version Used**: 2.2

**Steps to Reproduce**:

1. Run following code:

    ```cs
    var sw = new StreamWriter(new MemoryStream());
    sw.Write(SyntaxFactory.LiteralExpression(
        SyntaxKind.CharacterLiteralExpression,
        SyntaxFactory.Literal('\uDBFF')));
    sw.Flush();
    ```

**Expected Behavior**:
'\uDBFF'

**Actual Behavior**:
System.Text.EncoderFallbackException: Unable to translate Unicode character \uDBFF at index 1 to specified code page.

https://github.com/dotnet/docfx/issues/1817

**Comment by jaredpar** [comment]
CC @gafter

**Comment by gafter** [comment]
It is a bug that we don't escape surrogates. It is a one-line fix.

**Comment by gafter** [comment]
I see we have the same problem, and other related problems in VB that were previously fixed in C#. I'll fix those too at the same time.

**Comment by gafter** [comment]
My investigation has revealed: our code for producing the source for character and string literals assumes that surrogates do not have to be escaped (because they are assumed to appear next to a matching surrotate to form a valid pair). This assumption is never correct inside a character literal (because a single character can never be a pair of characters). The assumption is not checked inside a string literal (the code to do so is nontrivial).

There are two possible approaches to fix the compilers:
1. Make the compilers always escape surrogates. This is a simple and correct fix.
2. Make the compilers analyze the character to be escaped in the context of previous and following characters, to compute if escaping is required. This is more complex but may produce more pleasing source where surrogate pairs appear.

I have submitted #20720 which takes the first approach, should we decide to go that way. Assigning back to @jaredpar, as investigation is complete.

**Comment by gafter** [comment]
I've modified the PR to take the second approach.
