### ISSUE TITLE
C# Named params argument in attribute constructor gets assigned wrong.

### ISSUE THREAD

**Issue by MaStr11** [dotnet/roslyn#20741]
**Version Used**: 
Visual Studio 15.1 (26403.7)
**Steps to Reproduce**:

Using named arguments in conjunction with params arguments seems to assign the wrong parameter in attribute constructor calls.

```CSharp
using System;
using System.Reflection;

sealed class MarkAttribute : Attribute
{
    public MarkAttribute(bool otherArg, params object[] args)
    {
        Args = args;
        OtherArg = otherArg;
    }
    public object[] Args { get;  }
    public bool OtherArg { get; }
}

[Mark(args: new string[] { "Hello", "World" }, otherArg: true)]
static class Program
{
    private static void Test(bool otherArg, params object[] args)
        => PrintOutArgsInfo(args);

    public static void Main()
    {
        Console.WriteLine("Method call");
        Test(args: new string[] { "Hello", "World" }, otherArg: true);

        var attr = typeof(Program).GetCustomAttribute<MarkAttribute>();
        Console.WriteLine("\nAttribute constructor call");
        PrintOutArgsInfo(attr.Args);
    }

    private static void PrintOutArgsInfo(object[] args)
    {
        Console.WriteLine($"Length: { args.Length } ");
        Console.WriteLine($"Value of Arr[0]: { args[0] } ");
        Console.WriteLine($"Type of Value[0]: { args[0].GetType().ToString() } ");
    }
}
```
**Expected Behavior**:
Does not compile or print out:
```
Method call
Length: 2
Value of Arr[0]: Hello
Type of Value[0]: System.String

Attribute constructor call
Length: 2
Value of Arr[0]: Hello
Type of Value[0]: System.String
```

**Actual Behavior**:
```
Method call
Length: 2
Value of Arr[0]: Hello
Type of Value[0]: System.String

Attribute constructor call
Length: 1
Value of Arr[0]: True
Type of Value[0]: System.Boolean
```

Discovered during working on #20630.

**Comment by gafter** [comment]
I think you misunderstand how GetCustomAttribute is supposed to work. The args yielded from it is an array, containing the arguments to the constructor call in the order of the declared parameters. Since the first parameter is a bool, that is what you should get.

**Comment by MaStr11** [comment]
In the call `PrintOutArgsInfo(attr.Args);` the `attr.Args` part is referring to the `public object[] Args { get;  }` property of the MarkAttribute. This property is initialized in the constructor of the attribute. This initialization is what seems to go wrong because the constructor parameters `bool otherArg, params object[] args` are not assigned properly if the constructor is called like this `[Mark(args: new string[] { "Hello", "World" }, otherArg: true)]`. So I still think that this is a bug.

**Comment by svick** [comment]
This indeed looks like a bug to me. Decompiled code for the version above and some variants:

* `[Mark(args: new string[] { "Hello", "World" }, otherArg: true)]`
  Decompiled: `[Mark(true, new object[] { true })]`
* `[Mark(otherArg: true, args: new string[] { "Hello", "World" })]`
 error CS0182: An attribute argument must be a constant expression, typeof expression or array creation expression of an attribute parameter type
* `[Mark(true, new string[] { "Hello", "World" })]`
  error CS0182: An attribute argument must be a constant expression, typeof expression or array creation expression of an attribute parameter type
* `[Mark(otherArg: true, args: new object[] { "Hello", "World" })]`
  Decompiled: `[Mark(true, new object[] { "Hello", "World" })]`
* `[Mark(true, new object[] { "Hello", "World" })]`
  Decompiled: `[Mark(true, new object[] { "Hello", "World" })]`
* `[Mark(true, "Hello", "World")]`
  Decompiled: `[Mark(true, new object[] { "Hello", "World" })]`

So, the array being `new object[] { true }` clearly looks wrong. And the fact that it accepts `string[]` (instead of `object[]`) looks suspicious too.

**Comment by gafter** [comment]
I see. Thanks, @svick !
