### ISSUE TITLE
should we include IsInvalid in OperationAnalysisContext ?

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#20760]
adding it there instead of using extension method can let us to improve perf of IsInvalid check since we could do that in bulk.

**Comment by heejaechang** [comment]
from this comment - https://github.com/dotnet/roslyn/pull/20436#pullrequestreview-48764191

**Comment by heejaechang** [comment]
@jinujoseph design question.

**Comment by jinujoseph** [comment]
**Design Team Decision**

We can potentially do multiple things to improve the performance here ... 
- .EnableConcurrentRun , where user might be able to define , don't call me when there is errors  
- We can provide .Invalid method in the context cache and hold on to errors  
- We can also have compiler flag which says , don’t call be if there is any error in a scenario etc.

Lets not do any for V1 and lets wait to hear back on feedback/specific scenario to tackle this.

**Comment by jinujoseph** [comment]
regressed https://github.com/dotnet/roslyn/pull/20990#issuecomment-317134305

**Comment by jinujoseph** [comment]
**Design Team Decision**

We need to do some investigation here.

- Is the API just too slow because we are lacking a caching mechanism, look into ClsComplianceChecker 
- Is it slow because we are just calling it so many times , that it adds up to the time . 
- Investigate if we should introduce a flag which says don't bother running on a method that has errors, to avoid recursive call.

**Comment by cston** [comment]
Perhaps add a simple `IOperation.HasErrors` property that represents whether this particular operation has errors, not whether there are errors beneath the operation. In most cases, the value would be the value of `HasErrors` on the associated `BoundNode`.
