### ISSUE TITLE
"Go to Implementation" didn't list implementations off of an interface method when implementations exist

### ISSUE THREAD

**Issue by jamesqo** [dotnet/roslyn#20862]
Currently, it brings up a dialog box saying 'The symbol has no implementations.' Maybe it would be better to bring up a new window instead, like

<img width="913" alt="hl_refs" src="https://user-images.githubusercontent.com/9159214/28181693-8b75223c-67d7-11e7-8b44-2fde6efe5ea7.PNG">

except titled `'Highlight' implementations` instead of `'Highlight' references`. It would list all of the method definitions implementing `Highlight`.

I can tell you I would very much appreciate this feature being added, since right now it's [totally non-obvious how to do it](https://stackoverflow.com/a/5883981/4077294). (I don't even know what a 'call hierarchy' is, why would I click that option?) I end up forgetting and Googling that SO answer every time I want to find implementing methods.

**Comment by Pilchie** [comment]
This should work exactly as described already - do you have a repro for the case where it shows the dialog instead of finding references?

**Comment by jasonmalinowski** [comment]
@jamesqo Are you able to share a repro or the code where you saw this didn't work correctly? "Go to Implementation" should have done what you want; something meant our detection of the implementations didn't work right.

**Comment by aedwill** [comment]
I'm seeing the same problem.  I have an ASP.NET Core Azure Function project that dynamically loads a DLL at runtime.  That dll is referenced by the loader just so that I don't have to manually copy the DLL to to the pickup folder.  At runtime it makes a call to another function through a third assembly referenced by both, but that call fails.  No breakpoints are hit in the common assembly.

Project A is loaded and running.  
Project B is loaded by an Assembly.LoadFrom command in common Project CX.
Project C is loaded by Project B at runtime by an Assembly.LoadFrom command in common Project CX.
Project C calls a common method in Project CX, which throws and exception.

The breakpoints in project CX are never hit, and when trying to navigate to the method from Project B in the solution (which includes all projects) I get that error.

**Comment by CyrusNajmabadi** [comment]
Resolving no repro as we haven't heard any way to cause this to be hit.
