### ISSUE TITLE
Friend vs internal in dotnet_naming_symbols.*.applicable_accessibilities

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#20893]
What's the difference between `friend` and `internal`, and `protected_friend` and `protected_internal`? Is one C#-only and one VB-only?

**Comment by Pilchie** [comment]
@jmarolf or @dpoeschl do you know the answer herre?

**Comment by jmarolf** [comment]
@jnm2 There is no difference from a semantics perspective.  [Looking at the code](http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/NamingStyles/EditorConfig/EditorConfigNamingStyleParser_SymbolSpec.cs,177) they are both synonymous.  The only reason there is a difference is so that VB and C# users can use the terms they are familiar with.

**Comment by jnm2** [comment]
Thanks! Perfect. This'll be included in the upcoming documentation, right?

**Comment by Pilchie** [comment]
Assigning to @kuhlenh for the doc aspect.

**Comment by CyrusNajmabadi** [comment]
UNlikely to do anything here.
