### ISSUE TITLE
Default values for ImmutableArray of IOperations

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#20974]
See @cston's comment: https://github.com/dotnet/roslyn/pull/20962#discussion_r128275551

We need to decide if we are fine to expose default ImmutableArray operation nodes or they should always be set to empty when default, and then fix this consistently across our operation factories.

**Comment by sharwell** [comment]
I believe the API should not expose default instances of `ImmutableArray<T>`, since it does not provide useful information to the user in the form of API signatures.

* If you need to represent "doesn't have a value", use `ImmutableArray<T>?`
* Otherwise, use `ImmutableArray<T>.Empty` for arrays with no elements

**Comment by jinujoseph** [comment]
**Design Team Decision**

Decision was to always set to empty when default.
