### ISSUE TITLE
Add Xunit.Runner.VisualStudio to test projects so the VS Addin is not needed anymore

### ISSUE THREAD

**Issue by giggio** [dotnet/roslyn#210]
Right now the test projects contain only the Xunit package/reference. So we need the Xunit runner vsix to detect the tests.
Right now the recommended way is to use [Xunit.Runner.VisualStudio](https://www.nuget.org/packages/xunit.runner.visualstudio), so that package/reference should be added to all test projects on the Roslyn solution.

**Comment by KevinH-MS** [comment]
Finally got to look at this today...  It appears we need to be using xunit 2.0.0 in order for this to work.  I'll try to see if there's still a good reason we need to be on 1.9.2.

**Comment by KevinH-MS** [comment]
Actually, I take that back.  The problem is not that we use xunit 1.9.2, it's that we target .NET 4.6 (and that isn't one of the supported frameworks for xunit.runner.visualstudio 2.0.0).  Trying a pre-release version instead...

**Comment by KevinH-MS** [comment]
Hmmm...it's not that either...  CSharpVisualStudioTests targets 4.6 and works fine "as-is" with xunit.runner.visualstudio 2.0.0.  Continuing to dig...

**Comment by KevinH-MS** [comment]
There were also issues with the way that we sign our assemblies.  I have a branch where this is working:  https://github.com/KevinH-MS/roslyn/tree/VSTT.  However, the overhead of test discovery on each build is quite high (over 5 minutes on my machine).  I've reached out to the VSTT team with this information.

Until we figure out how to reduce the overhead, I'm reluctant to add the reference (turn the vs runner on by default) since this would affect all developers using Roslyn.sln (regardless of which test runner they use).

**Comment by davkean** [comment]
Going to dup this against #4886, as they are both tracking the same issue.
