### ISSUE TITLE
Use PackageReference for compiler toolset package and roslyn analyzers package

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#21005]
See the discussion here: https://github.com/dotnet/roslyn/pull/20990#issuecomment-316772287

This is likely a NuGet bug as mentioned by Srivatsn. We need to investigate this further and enable PackageReference based approach for non-Window OSes.

**Comment by mavasani** [comment]
This issue now tracks moving us to PackageReference for compiler toolset package and roslyn analyzers package for both Windows and non-Windows OSes.

**Comment by jasonmalinowski** [comment]
@mavasani @srivatsn The discussion there was long and windy. Who do you imagine has the next step here? Honestly it looks like either a NuGet request or something else.

If the problem was also just the determinism build, could we slot a target before CoreCompile that just removes all the analyzers that came from NuGet if the desire is really "no analyzers period?" It's hacky but a bit more matching what the intent might be.

**Comment by mavasani** [comment]
I think the primary request from @jaredpar was that we should be able to selectively disable analyzers during build, and the current support only allows it during restore, which I feel is a very reasonable expectation.

We need to either add support to Roslyn to add a MSBuild project property to allow disabling analyzer execution OR add NuGet/MSBuild support to allow selectively dropping some package references at build time, even though they are in the assets file.
