### ISSUE TITLE
Change to behaviour of simple names - deliberate?

### ISSUE THREAD

**Issue by jskeet** [dotnet/roslyn#2110]
Inspired by http://stackoverflow.com/questions/29750618

Looking at C# 5.0 specification, section 7.6.2.1, the following example is *meant* to raise an error:

```csharp
class Test
{
	double x;
	void F(bool b) {
		x = 1.0;
		if (b) {
			int x;
			x = 1;
		}
	}
}
```

It *does* raise an error in the "old" native compiler, but Roslyn from CTP6 allows it to compile with no problems.

Is this a deliberate change which will be in the C# 6 specification, or an oversight?

**Comment by MadsTorgersen** [comment]
It is a deliberate change. Not quite up there to advertise as a feature, we have nevertheless gotten rid of the "invariant meaning" rule that used to cause your example to error.

The rule was well intended, in that it was supposed to minimize the risk of "moving code around" in a way that would silently change its meaning. However, everyone we talked to only seemed to know about the rule from when it was causing them unnecessary grief - no-one had ever been saved by its prohibitions.

Furthermore, the extra tracking necessary in the compiler to enforce the rule interactively was causing significant complications to the code, as well as non-trivial performance overhead. Now, if it were a good rule we would have kept it anyway, but it isn't! So it's gone.

Good job for spotting it!

**Comment by VSadov** [comment]
Also old compiler implementation had holes where the rule was not enforced, so we would have to implement all the quirks of old compiler, which was in places not trivial since the holes were implementation-specific.
The other possibility was intoroducing compat breaks in places where spec was stronger than what old compiler implemented, which also did not seem a good choice.
