### ISSUE TITLE
Cannot "Find References to Literal" on negative numbers

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#21111]
This is a duplicate of https://developercommunity.visualstudio.com/content/problem/81959/b06-find-all-references-on-literals-positive-and-n.html which was resolved "Not a Bug", but I would like to reopen the discussion.

**Version Used**: 26717.1.d15rel

**Steps to Reproduce**:

1. Paste C#:

```C#
int a = -1;
int b = -1;
int c = 1;
int d = 1;
```

2. Invoke Find References on the `-1` being assigned to `a`.

**Expected Behavior**: the assignments to `a` and `b` are found

**Actual Behavior**: the assignments to `a`, `b`, `c`, and `d` are all found, because it's searching for the literal `1`, because `-1` is not a literal in the language but a negation operator being applied to the literal `1`. This may be strictly correct from a language grammar perspective, but from an "IDE feature" perspective it feels unexpected.

**Note** There would need to be some design decisions here about how to deal with `~`, etc.

**Comment by AdamSpeight2008** [comment]
@gafter Will inform us that the negative sign isn't part of the literal, but a prefix unary operator.

I agree @dpoeschl, if `-1` is be perceived as a literal *even though strictly it isn't* we should treat it as so because it is a common usage pattern. So we should check for the presence of the negative (and positive) unary operators.

**Comment by CyrusNajmabadi** [comment]
I disagree.  If i'm looking for a literal, it's so i can replace it with a constant.  I want to replace all usages of that constant, even if they're used in a context where they are negated, or bitwise twiddled, or otherwise involved in any sort of arithmetic operation.  Now if i want to replace all usages of 1, i'll have to search for '1', and then write down -1 and then search for that.  

> but from an "IDE feature" perspective it feels unexpected.

It actually feels like exactly what i want.  i can now take that code and do:

```c#
const One = 1;
int a = -One;
int b = -One;
int c = One;
int d = One;
```

Note: from an implementation, this would be easy to support.  I just don't think it's actually what i want.

**Comment by CyrusNajmabadi** [comment]
> is be perceived as a literal even though strictly it isn't we should treat it as so because it is a common usage pattern

Why?  What upside is there to that?  If you want to strictly fine all -1s, then fine just do a textual search for "-1".  The point of this feature is to tell you what all the places the language *actually* thinks you're using the same literal. 

--

(FWIW, i think this is unnecessary bikeshedding).

**Comment by alrz** [comment]
tbh "Find References" on a string/numeric literal hardly makes sense.

>If you want to strictly find all -1s, then fine just do a textual search

You could just do that for other cases as well. you may argue that you don't want "commented code" but I don't see how that could help.

**Comment by dpoeschl** [comment]
Talked about this further, and splitting the results into two sections for -1 and 1 would be a nice solution.
Talked about this further, and splitting the results into two sections for -1 and 1 would be a nice solution.

**Comment by CyrusNajmabadi** [comment]
Talked about this further, and splitting the results into two sections for 1 and -1 would be a nice solution.

**Comment by CyrusNajmabadi** [comment]
Talked about this further, and splitting the results into two sections for 1 and -1 would be a nice solution.

**Comment by CyrusNajmabadi** [comment]
Closing out.  The results are accurate, and we haven't heard anything from customers about this being an actual issue.
