### ISSUE TITLE
Dispose() call for foreach is incorrectly invoked on struct enumerators

### ISSUE THREAD

**Issue by Tamschi** [dotnet/roslyn#2111]
It seems there is a C# compiler bug that causes foreach to emit boxing instructions when the enumerator has a generic-type-parameter-type constrained to `IDisposable`:

    using System.Collections.Generic;
    
    public interface IEnumerable<T, TEnumerator> : IEnumerable<T>
    { new TEnumerator GetEnumerator(); }
    
    static class Test
    {
        public static void TestMethod<TEnumerable, TEnumerator, T>(TEnumerable enumerable)
        where TEnumerable : IEnumerable<T, TEnumerator>
            where TEnumerator : IEnumerator<T>
        {
            foreach (var item in enumerable) { }
        }
    }

I discovered this in VS 2013 Community Version 12.0.31101.00 Update 4 (default Release configuration) where the resulting CIL code (disassembled with ILSpy version 2.2.0.1706) is

    .method public hidebysig static 
        void TestMethod<(class IEnumerable`2<!!T, !!TEnumerator>) TEnumerable, (class [mscorlib]System.Collections.Generic.IEnumerator`1<!!T>) TEnumerator, T> (
            !!TEnumerable enumerable
        ) cil managed 
    {
        // Method begins at RVA 0x2050
        // Code size 70 (0x46)
        .maxstack 1
        .locals init (
            [0] !!TEnumerator
        )

        IL_0000: ldarga.s enumerable
        IL_0002: constrained. !!TEnumerable
        IL_0008: callvirt instance !1 class IEnumerable`2<!!T, !!TEnumerator>::GetEnumerator()
        IL_000d: stloc.0
        .try
        {
            IL_000e: br.s IL_001e
            // loop start (head: IL_001e)
                IL_0010: ldloca.s 0
                IL_0012: constrained. !!TEnumerator
                IL_0018: callvirt instance !0 class [mscorlib]System.Collections.Generic.IEnumerator`1<!!T>::get_Current()
                IL_001d: pop

                IL_001e: ldloca.s 0
                IL_0020: constrained. !!TEnumerator
                IL_0026: callvirt instance bool [mscorlib]System.Collections.IEnumerator::MoveNext()
                IL_002b: brtrue.s IL_0010
            // end loop

            IL_002d: leave.s IL_0045
        } // end .try
        finally
        {
            IL_002f: ldloc.0
            IL_0030: box !!TEnumerator
            IL_0035: brfalse.s IL_0044

            IL_0037: ldloca.s 0
            IL_0039: constrained. !!TEnumerator
            IL_003f: callvirt instance void [mscorlib]System.IDisposable::Dispose()

            IL_0044: endfinally
        } // end handler

        IL_0045: ret
    } // end of method Test::TestMethod

The problem seems to have gotten worse in Roslyn (CTP 6, Microsoft Visual Studio Ultimate 2015 CTP Version 14.0.22609.0 D14REL) so there are now effectively two unconditional boxing operations if `TEnumerable` is a struct:

    .method public hidebysig static 
        void TestMethod<(class BoxTest.IEnumerable`2<!!T, !!TEnumerator>) TEnumerable, (class [mscorlib]System.Collections.Generic.IEnumerator`1<!!T>) TEnumerator, T> (
            !!TEnumerable enumerable
        ) cil managed 
    {
        // Method begins at RVA 0x2054
        // Code size 68 (0x44)
        .maxstack 1
        .locals init (
            [0] !!TEnumerator
        )

        IL_0000: ldarga.s enumerable
        IL_0002: constrained. !!TEnumerable
        IL_0008: callvirt instance !1 class BoxTest.IEnumerable`2<!!T, !!TEnumerator>::GetEnumerator()
        IL_000d: stloc.0
        .try
        {
            IL_000e: br.s IL_001e
            // loop start (head: IL_001e)
                IL_0010: ldloca.s 0
                IL_0012: constrained. !!TEnumerator
                IL_0018: callvirt instance !0 class [mscorlib]System.Collections.Generic.IEnumerator`1<!!T>::get_Current()
                IL_001d: pop

                IL_001e: ldloca.s 0
                IL_0020: constrained. !!TEnumerator
                IL_0026: callvirt instance bool [mscorlib]System.Collections.IEnumerator::MoveNext()
                IL_002b: brtrue.s IL_0010
            // end loop

            IL_002d: leave.s IL_0043
        } // end .try
        finally
        {
            IL_002f: ldloc.0
            IL_0030: box !!TEnumerator
            IL_0035: brfalse.s IL_0042

            IL_0037: ldloc.0
            IL_0038: box !!TEnumerator
            IL_003d: callvirt instance void [mscorlib]System.IDisposable::Dispose()

            IL_0042: endfinally
        } // end handler

        IL_0043: ret
    } // end of method Program::TestMethod

(Thanks to @Rohansi for testing this with VS 2015.)

**Comment by theoy** [comment]
Nice catch. We're not happy with the codegen you described in CTP6 because unexpected boxing has correctness issues with mutable structs.

However, in this case the boxing occurs at the end of the scope of the variable, so any side-effects that failed to occur on the original struct reference are probably unobservable.

Either way, it'd be good to clean up the codegen here so that should we make subsequent changes that we don't inadvertently introduce a case where this invalid copying suddenly becomes significant.

**Comment by Tamschi** [comment]
As a side note, there is an identical issue with `using` blocks in VS 2013, e.g. with

    public static void UsingTestMethod<TDisposable>(TDisposable disposable)
        where TDisposable : IDisposable
    {
        using (disposable) { }
    }

I don't have VS 2015 installed so I can't quickly test this, but it wouldn't surprise me if that happened here too. (The CIL code in the finally block is identical to the foreach loop's with the current C# 5 compiler.)

**Comment by VSadov** [comment]
using does not emit "box" instruction. it uses constrained calvirt.
foreach does in fact emit "box", I do not know yet why it does not use constrained call.

Note that there is no correctness issue here. That is just because "box" has no effect on reference types, and has copying effect on structs. However since in either foreach or using cases box is appied to a synthesized temporary that is not available to the user after disposal, there is no way to the user to tell the difference whether there was actual boxing or not.

So the only observable effect of that "box" is potential extra allocation of boxed enumerator when calling its Dispose.

**Comment by VSadov** [comment]
BTW:   "box", followed by "brfalse" is not interesting here. That is just a null-check. There is no other way to do it and JIT will not do actual boxing/allocation here since it can see that boxing is done only for the purpose of a null check. In a case if T is a reference type, JIT will emit a null-check directly, and in a case of regular (not nullable) struct will just assume the condition is false (since result of boxing would not be null).

**Comment by Tamschi** [comment]
I see, it's good to hear that I don't need to use a try/finally + while loop workaround to avoid all allocations. (I'm only familiar with the .NET side of things, so I was unaware of that runtime optimisation.)

**Comment by sharwell** [comment]
You could actually replace the `brfalse.s` with `brnull.s` in the listing for clarity (it's the same instruction). I agree with @VSadov this is not a correctness issue.

It does appear the instruction at `IL_0038` could be a `constrained.` prefix for the `callvirt` instead of the current `box` instruction.

**Comment by Tamschi** [comment]
Right, if I'm not mistaken the only exception that could be hidden is the original `NullReferenceException` from the virtual call to `.MoveNext()`, but since the `box` `brfalse.s` combination (with runtime optimisation) is so fast (and throwing two exceptions would be much slower) I can see why that's preferable.

**Comment by sharwell** [comment]
@Tamschi I'm not sure what you are referring to. Aside from an additional allocation (with no observable side effects), the runtime behavior of the two alternatives is identical.

**Comment by Tamschi** [comment]
@sharwell I checked and it seems I made a mistaken assumption based on behaviour I saw elsewhere:

The line number masking on `foreach` and `using` is different (in VS 2013 at least), so exceptions thrown by/from `foreach`'s `Dispose()` call still show up on the loop header (displayed on the `in` keyword by VS).

When a `Dispose()` call throws from the end of a `using` block, the line number and exception highlight match the block's closing brace instead, which is what I expected to happen here too.

**Comment by MattGertz** [comment]
Needs validation.
