### ISSUE TITLE
'Inline temporary variable' fix breaks code and doesn't actually remove the variable

### ISSUE THREAD

**Issue by TessenR** [dotnet/roslyn#21191]
**Version Used**: 
```
Microsoft Visual Studio Professional 2017 
Version 15.2 (26430.14) Release
VisualStudio.15.Release/15.2.0+26430.14
Microsoft .NET Framework
Version 4.7.02053
```

**Steps to Reproduce**:

Paste the following code into VS:
```cs
public class C
{
  public void M(int i)
  {
    var y = i;
    M(out y);
    Console.WriteLine(y);
  }

  public static extern void M(out int x);
}
```

**Expected Behavior**:
No suggestion to inline variable

**Actual Behavior**:

Roslyn suggests to 'inline tempoarary variable' and rewrite the code to following:

```cs
public class C
{
  public void M(int i)
  {
    var y = i;
    M(out y);
    Console.WriteLine(i);
  }

  public static extern void M(out int x);
}
```
So the suggestion neither removes the variable nor preserves the program's behavior.

**Comment by Pilchie** [comment]
Tagging @kuhlenh and @DustinCampbell, but a couple of thoughts here:

1. This is the refactoring, not the suggestion, though the two are conflated right now while we have the glyph the same.
2. There should be a red conflict marker and warning in the preview, but we've got several reports about this for this feature in the last few months.  I wonder if we need a more obvious treatment.

@TessenR the reason we still offer the refactoring though it might break code is that we don't want you to wonder why it isn't there if you come to expect it, and we also think that there are cases when a developer is willing to accept a break because they already have a path forward that includes fixing the break.

**Comment by CyrusNajmabadi** [comment]
> There should be a red conflict marker and warning in the preview, but we've got several reports about this for this feature in the last few months. I wonder if we need a more obvious treatment.

How about a special glyph in the lightbulb menu as well?  It could convey that this change coudl cause an error.

**Comment by Vlad-Stryapko** [comment]
I've just encountered the same issue with VS replacing every usage of a variable assigned with  `Console.ReadLine()` with `Console.ReadLine()`. It obviously breaks program's logic if the right part of the assignment isn't side-effect free. 

This is not something expected from the IDE and people are clearly not happy about it when they first encounter this flawed behaviour.

@CyrusNajmabadi 
I've seen your argument about the light-bulb not being a 100% safe refactoring and I think that in unsafe case there ought to be some indication. I don't think I'm the only one to expect Ctrl + . to not break my code or at least to tell me if it might do so. 

If I'm not mistaken, Intellij IDEA directly asks you to review the changes if they aren't 100% safe. That's a nice option if VS has a mechanism to ask for a review explicitly. Special glyph is pretty good option as well.

**Comment by CyrusNajmabadi** [comment]
I think we're good with the existing treatment:

![image](https://user-images.githubusercontent.com/4564579/198749497-5d7cc2fb-1e3b-4d8b-ac6e-3513c81d2cb9.png)

There's been minimal feedback on this, so given this behavior for the last 10+ years, it seems fine to keep as is.

**Comment by CyrusNajmabadi** [comment]
Meant to close this with the last message.
