### ISSUE TITLE
Optimize default(T) deconstruction

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#21232]
**Version Used**: master

**Steps to Reproduce**:
```cs
void M(out int i, out string j) {
  (i, j) = default((int, string));
}
```
**Expected Behavior**: (decompiled)
```cs
void M(out int i, out string j) {
  i = 0;    // default(int)
  j = null; // default(string)
}
```
**Actual Behavior**:
```cs
void M(out int i, out string j) {
  i = default((int, string)).Item1;
  j = default((int, string)).Item2;
}
```
PS: Ideally, this should work for `default` literal as well (https://github.com/dotnet/csharplang/issues/583).

**Comment by HaloFour** [comment]
Interesting case.  I bet the confusion is the compiler dealing with a default of the tuple literal.  If you used `(default(string), default(int))` instead the compiler does optimize out the tuple.  What's particularly strange is that the compiler is emitting and initializing two tuples instead of one.

At least the JIT is correctly optimizing away the use of the tuples, but I agree that the compiler could be handling this better.

**Comment by alrz** [comment]
>What's particularly strange is that the compiler is emitting and initializing two tuples instead of one.

I think that's because `default(..)` is known to be side-effect free between reads so it's not stored in a local.

**Comment by jcouv** [comment]
Fixed in the feature branch for "deconstruction on default". Actual release not yet finalized.
