### ISSUE TITLE
IParameterInitializer, IFieldInitializer, IPropertyInitializer, ISymbolInitializer API Review

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#21293]
**Design Team Decision**

One of the reasons where some one whould wants to process the whole tree , where  they don't want to register for every node. One of the alternative for the same was using Operation block analyzer, which basically analysis all the code block and can replace the need for this API's.
So the decision was to remove all this API's , we need to see if there are analyzers using this API and see if the alternative would work.

**Comment by mavasani** [comment]
@CyrusNajmabadi @jinujoseph @AlekseyTs - a side effect of removing ISymbolInitializer and associated interfaces/OperationKinds will mean that EqualsValueClauseSyntax nodes for fields, parameters and properties will have no corresponding IOperation. Does this sound fine?

I found another related bug - CodeBlockAnalysisContext and OperationBlockAnalysisContext only expose a single OwningSymbol. However, for VB field declarations, multiple declarations can share a single initializer code block. This was correctly exposed by IFieldInitializer.InitializedFields. We should now fix the above two analysis contexts to expose multiple owning symbols, otherwise analyzers using `IFieldInitializer.InitializedFields` cannot be implemented in a language agnostic way.

Let us discuss these 2 issues at this week's design meeting.

**Comment by CyrusNajmabadi** [comment]
1. Still remove these Initialize apis.
2. Don't get multiple codeblocks at a time.

**Comment by mavasani** [comment]
Filed https://github.com/dotnet/roslyn/issues/22251 to track work for `Don't get multiple codeblocks at a time`. This issue now just tracks removal of these APIs.

Filed https://github.com/dotnet/roslyn/issues/22252 to track for exposing all owning symbols from a context.

This issue now only tracks removal of the ISymbolAnalyzer APIs.

**Comment by mavasani** [comment]
We would like to bring this up again for discussion.

1. The current initializer API shape already has good amount of unit tests for both C# and VB
2. The current API shape looks reasonable and exposes a richer API (pending official approval)
3. The language specs already mention initializers as executable code (for example see https://github.com/dotnet/csharplang/blob/0bffa700dba61735c79fdee7f189d1eda3246835/spec/classes.md#variable-initializers), and hence exposing an IOperation for it shouldn't be an issue.

So the decision is between:
1. Remove the API and unit tests and reduce public API surface. Follow up work is to fix existing Roslyn analyzer using this API.
2. Review and refine existing API shape and make changes, if any. Follow up work is to fix https://github.com/dotnet/roslyn/issues/17813 to handle multi-field case in VB.

**Comment by mavasani** [comment]
**Update:** I tried implementing the API removal and noted one big breaking change to existing code block syntax analyzers, which would likely prevent us from removing these APIs.

Current implementation of code block analyzer callbacks returns the `EqualsValueSyntax` node for all field/property/parameter initializers. If we end up not having any IOperation for these initalizer equals value node, invoking `GetOperation` on the root of code block will return null, which is not a good user experience. If we try to change the code block analyzer callbacks to pass the underlying value of the equals value initializer, it will very likely break existing code block analyzers (which could be large number given it has shipped since Dev14). I talked with @jinujoseph and @AlekseyTs and they both agree we should retain the current ISymbolInitializer APIs and possibly consider adding an ILocalSymbolInitializer for local declaration for parity with other symbol initializations. In v2, we can add new APIs for constructor initializers, attributes, etc. which are missing now. @DustinCampbell, your thoughts?

**Comment by DustinCampbell** [comment]
This seems reasonable. I wish we could do something for constructor initializers and attributes before v2, but I understand.

**Comment by mavasani** [comment]
Thanks Dustin - I will open separate issues to track (a) Add ILocalSymbolInitializer and (b) Handle constructor initializers and attributes.

**Comment by mavasani** [comment]
Filed (a) https://github.com/dotnet/roslyn/issues/22429 and (b) https://github.com/dotnet/roslyn/issues/22430.

Closing this issue.
