### ISSUE TITLE
Could not find a part of the path ...\AspNetCompileMerge\Source\bin\roslyn\csc.exe

### ISSUE THREAD

**Issue by jamesgurung** [dotnet/roslyn#21340]
I have an ASP.NET Web Application project which builds successfully.

After updating `Microsoft.CodeDom.Providers.DotNetCompilerPlatform` from `1.0.5` to `1.0.6` it still builds, but when publishing I get the error:

> Transformed Web.config using D:\Visual Studio Projects\MySolution\MyProject\Web.Release.config into obj\Release\TransformWebConfig\transformed\Web.config.
> Copying all files to temporary location below for package/publish:
obj\Release\AspnetCompileMerge\Source.
> C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\aspnet_compiler.exe -v / -p "D:\Visual Studio Projects\MySolution\MyProject\obj\Release\AspnetCompileMerge\Source" -c "D:\Visual Studio Projects\MySolution\MyProject\obj\Release\AspnetCompileMerge\TempBuildDir" 
> **ASPNETCOMPILER(0,0): Error ASPRUNTIME: Could not find a part of the path 'D:\Visual Studio Projects\MySolution\MyProject\obj\Release\AspnetCompileMerge\Source\bin\roslyn\csc.exe'.**

There is no `roslyn` folder in `\obj\Release\AspnetCompileMerge\Source\bin`.

Reverting to version `1.0.5` stops the error from occurring. With this version, there is no attempt during publish to open `csc.exe` from the `bin` folder. Instead of the bold error line above, the output reads:

> D:\Visual Studio Projects\MySolution\packages\Microsoft.Net.Compilers.2.3.1\tools\csc.exe /out:obj\Release\AssemblyInfo\AssemblyInfo.dll /target:library Properties\AssemblyInfo.cs
> ...

**Comment by Oipo** [comment]
Same error on my project.

**Comment by knopa** [comment]
Got it too. 
Whild build ok, while publishing or building in teamcity no.

**Comment by lguilhou** [comment]
I "fixed" it on my projects (locally) by essentially stumbling my way through various attempts at reverting the update, updating again and using Update-Package -Reinstall. At some point, recompiling the web project brought back the /bin/roslyn directory.

I unfortunately didn't write down every attempt I made, since those things always happen when we're pressed for time and don't expect a minor version update to break everything.

However this only made the websites work again *locally*. There are sadly no build servers for those projects (yet. I'm working my way up to spreading those weird ideas to the customer, bit by bit), but it may point to a possible workaround with a *complete* reset of the working directory on TeamCity&co.

Still, something is clearly wrong with the package for this version.

**Comment by Pilchie** [comment]
Tag @jaredpar

**Comment by jaredpar** [comment]
CC @Jinhuafei

**Comment by Jinhuafei** [comment]
It is being tracked through [this issue](https://github.com/aspnet/RoslynCodeDomProvider/issues/13).

**Comment by jamesgurung** [comment]
Thanks. Closing as this is tracked elsewhere.

**Comment by beflint** [comment]
Am using VS2015 Update 3 to create new ASP.NET MVC 5 project.  Default "Microsoft.CodeDom.Providers.DotNetCompilerPlatform 1.0.7" package was included.
Could not publish.   Resolved publish problem by uninstalling 1.0.7 and re-installing 1.0.5 version.

**Comment by Jinhuafei** [comment]
@beflint Would you please share more details? If possible, please share the publish msbuild log.

**Comment by beflint** [comment]
VS2015 Publish/Build Output in "detailed format".

[publish-build.log.txt](https://github.com/dotnet/roslyn/files/1342366/publish-build.log.txt)
