### ISSUE TITLE
GetBoundNodes returns BoundBadExpression for RefExpressionSyntax

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#21406]
Given the following code:

```C#
namespace ConsoleApp1
{
    class C1
    {
        int i = 1;

        void M1()
        {
            ref int i2 = ref i;
        }
    }
}
```

Attempting to get the IOperation for `ref i` returns an IInvalidExpression. This is because the underlying GetBoundNodes call for the RefExpressionSyntax node returns a BoundBadExpression. This is because there is no corresponding BoundNode for the RefExpressionSyntax, and we probably should be adjusting the RefExpressionSyntax to the parent variable declaration syntax in GetBindableSyntaxNode. FYI @dotnet/roslyn-compiler.

**Comment by 333fred** [comment]
Note: this is likely going to block complete implementation of https://github.com/dotnet/roslyn/issues/21311.

**Comment by CyrusNajmabadi** [comment]
You may need to walk into the RefExpressoinSyntax, get the bound node for what it points at, and then make a ReferenceCreationExpression around that.

**Comment by 333fred** [comment]
Yeah, that's what we'll have to do for GetOperation. But first GetBoundNodes will need to not return a BoundBadExpression :).

**Comment by 333fred** [comment]
My current plan is that, hopefully, RefExpressionSyntax will be adjusted to return the entire BoundVariableDeclaration. Then, we can get the IVariableDeclaration and pull the IReferenceCreationExpression out of it. This will make sure that we aren't synthesizing nodes and that parent node should be findable.

**Comment by CyrusNajmabadi** [comment]
> But first GetBoundNodes will need to not return a BoundBadExpression

That's what it returns for the expressoin *inside* the RefExpressionSyntax?

**Comment by 333fred** [comment]
No. It returns the correct BoundLocal for that.

**Comment by CyrusNajmabadi** [comment]
Ok.  So then it's not clear if there' sa problem :)  What i'm saying is:

If you are given a REfExpressionSyntax, get hte bound node for the expression it points at.  Then wrap the result of that in a RefCreationOperation.

**Comment by 333fred** [comment]
@OmarTawfik @VSadov, since this is going to block implementation of IOperation ref I'll take care of the bug. I would like your comments on my proposed solution though: have GetBindableSyntaxNode detect when it's a RefExpressionSyntax, and return GetBindableSyntaxNode of the parent node.

**Comment by OmarTawfik** [comment]
> No. It returns the correct BoundLocal for that.
Sorry, I'm missing the problem here. Do you have a repro test? I can try to look at it locally.

**Comment by VSadov** [comment]
This is where our syntax does not match the semantics. Semantically ref is a part of the assignment - similar to passing an argument by reference. By itself ` ref i `  is not a meaningful expression. - What would be the type of that? Can you get an array or a list of those? What does it convert to? ...
If the goal is to represent semantics of the language, then you should probably add a boolean flag to the assignment specifying that this is a ref assignment.

If you want to match the syntax model, then ReferenceCreationExpression is probably fine. 

Regardless, since standalone `ref <expr>` cannot be bound, it should not be returned as a bindable node and should return the nearest bindable parent node.

Do not forget to check how this works with ref returns, like for example:

```C#
ref int foo() => ref (new int[1])[0];
```

**Comment by 333fred** [comment]
Yep, that was on my list of tests. @VSadov, at some point over the next day or two I'd like to pick your brain for a list of where ref is valid in the language to make sure my test cases are exhaustive.

**Comment by 333fred** [comment]
This issue is now irrelevant for GetOperation, as we now construct IOperation nodes from the top down.
