### ISSUE TITLE
Refactoring: add parameter when an argument is added to the invocation

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#21446]
**Steps to reproduce**:
```cs
void Test(int a, int b, int c) {}

string x = null;
Test(a, b, c);
```
Add an argument to the invocation:
```cs
string x = null;
Test(a, b, c, x); 
```
**Expected Behavior**:

Also، suggest to add parameter "string x" to the existing method "Test".

**Actual Behavior**:

The only option is to add an overload.

![image](https://user-images.githubusercontent.com/3105979/29206956-7106c094-7e99-11e7-8bed-8b5946e18371.png)

**Comment by AdamSpeight2008** [comment]
I'd expect it to add an overload not rewrite existing method.

**Comment by alrz** [comment]
I'm not suggesting that this should replace the current option, it should be a new item on the same invocation.

**Comment by sharwell** [comment]
This makes sense. Broad testing will be important for cases where `Test` is not a private method or local function visible in the current scope.

**Comment by Pilchie** [comment]
@CyrusNajmabadi started this, and we support it for constructors in 15.3, but there was some reason it was harder for other methods...

**Comment by sharwell** [comment]
💭 We could start by limiting it to invocations of private methods and local functions. Then see what people are requesting from there.

**Comment by CyrusNajmabadi** [comment]
If anyone is interesting in implementing this, here is where the code would go:
https://github.com/dotnet/roslyn/blob/master/src/Features/Core/Portable/AddParameter/AbstractAddParameterCodeFixProvider.cs#L77

It has not been implemented yet solely due to the wide gamut of 'interesting' cases that arise here (for example, what should happen when adding something to a generic method).  If anyone does this, i would recommend extracting out a lot of hte logic of 'generate-method' into a common location as it will most likely be relevant here, and we don't want to duplicate it all in a separate location.
