### ISSUE TITLE
Switch case pattern match compile fail for arrays of generic types in VS 15.3

### ISSUE THREAD

**Issue by TylerBrinkley** [dotnet/roslyn#21515]
**Version Used**: VS 15.3

**Steps to Reproduce**:

```c#
using System;
using System.Collections.Generic;

namespace ConsoleApp3
{
    class Program
    {
        static void Main()
        {
            Array array = new KeyValuePair<string, DateTime>[3];
            switch (array)
            {
                case KeyValuePair<string, DateTime>[] pairs:
                    Console.WriteLine("Pairs");
                    break;
            }
        }
    }
}
```

**Expected Behavior**:
This is expected to compile as it used to in VS 15.2

**Actual Behavior**:
I get several syntax errors on the `case KeyValuePair<string, DateTime>[] pairs:` line.

I discovered this after the upgrade to VS 15.3 in my `OrderedDictionary`'s implementation of `ICollection.CopyTo` similar to [Dictionary](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Collections/Generic/Dictionary.cs#L699)'s but with pattern matching.

**Comment by gafter** [comment]
@CyrusNajmabadi This appears to be a bug introduced in your recent parser changes. Can you please have a look?

**Comment by CyrusNajmabadi** [comment]
Looking.

**Comment by CyrusNajmabadi** [comment]
@gafter I get no error (parse or compile) with teh above code when i use master.

**Comment by CyrusNajmabadi** [comment]
I do get a parse error in 15.4 though.  Investigating.

**Comment by CyrusNajmabadi** [comment]
@gafter I actually think this was introduced with:

https://github.com/dotnet/roslyn/pull/16834

Specifically, when we saw ```KeyValuePair<string, DateTime>``` followed by ```[``` we would normally just ```return ScanTypeArgumentListKind.DefiniteTypeArgumentList```:  https://github.com/dotnet/roslyn/commit/3b0e09a8a5105c1b2ae91038d93308ec031b44fe#diff-ac2b4121f27df06f497115cc68277654L5315

However, now we say that we're not "after is", and so we that it's only a "PossibleTypeArgumentList".

ParseSimpleName will then only parse out the type arguments if it's DefinitelyTypeArgumentList or if it is PossibleTypeArgumentList but we're InTypeList.  Neither applies, so we don't think of these as type arguments.
https://github.com/dotnet/roslyn/commit/3b0e09a8a5105c1b2ae91038d93308ec031b44fe#diff-ac2b4121f27df06f497115cc68277654R5231

**Comment by CyrusNajmabadi** [comment]
Note: while my change to generic parsing helped here, it does not solve hte general problem.  Specifically, my change makes it so that if we see something like ```KVP<string, ...>``` that we parse it as generic (as the keyword 'string' makes it unambiguous that this is a type, and not an expression).

However, if you typed  ```KVP<String,``` then we still exhibit the same issue reported by @TylerBrinkley .  @gafter I'm assigning back to you.  I don't think this was due to my change.  And my change doesn't actually address this case, or even attempt to fix it.   I think the core change needs to be revisited to make sure it handles cases like this properly.  It's unclear at which point in the parsing stack this needs to happen, so i'm giving back to you.  Thanks!

**Comment by gafter** [comment]
@CyrusNajmabadi Thank you for such a thorough analysis!
