### ISSUE TITLE
Quick question regarding access to Project object from analyzers

### ISSUE THREAD

**Issue by jonathanbyrne** [dotnet/roslyn#21522]
Is there any way for analyzers to access the related Microsoft.CodeAnalysis.Project object?  As far as I can tell, this is not possible.  In my very limited understanding of Roslyn, it would seem logical to have the project as a property on Microsoft.CodeAnalysis.Compilation.

**Comment by sharwell** [comment]
No, analyzers are not allowed to reference Microsoft.CodeAnalysis.Workspaces. Attempts to use a type from that, or any type which depends on it, will result in an exception at runtime. The easiest way to avoid problems is to make sure your analyzer project does not reference this assembly when you compile your analyzers.

:memo: Implementing this approach requires you move all code fixes to a second assembly, since code fixes do require access to Microsoft.CodeAnalysis.Workspaces.

**Comment by jonathanbyrne** [comment]
That is a big help.  Thanks for the fast response!

**Comment by sharwell** [comment]
No problem. If you were trying to accomplish something in particular and running into challenges, let me know your specific question and I can probably point you to either an example where someone did something similar or to a bug related to the issue. :smile:
