### ISSUE TITLE
How to train your dragon 3!

### ISSUE THREAD

**Issue by richlander** [dotnet/roslyn#2156]
Microsoft teams are _excellent_ at defining contributor guidance. Please help define what the community guidance for Microsoft should be. The conversation has started. What's your take?

Snip from the CoreCLR issue: [How to train your dragon!](https://github.com/dotnet/coreclr/issues/744).

I've written several detailed points below. I think that they all boil down to this advice for MS engineers:

> Invest as little time as possible before creating an issue or pushing code to the community. Sharing is a much higher concern than quality.

- **DO** create issues as soon as possible, even before you fully understand the problem. Self-assign or make up-for-grabs.
- **DO** use public feature branches (personal or central) for work in progress.
- **DO** start work in the open as soon as possible, well before you are done, even before you quite know what you are doing. ```git rebase -i``` and ```git branch -D mybranch``` are your friends.
- **DO** use Issues. **DON'T** use email (as much as possible). Internal technical discussions don't help the community learn and don't enable them to participate. It's like keeping a new hire off of mail threads, for reasons.
- **DO** share snapshots of progress externally on an issue if there is an internal discussion going on. Take a picture of a whiteboard and share it!

**Comment by MgSam** [comment]
As a suggestion specific to the language teams (Roslyn and TypeScript), I think adding some links to the issues list filtered on different tags to the Github project home page would be helpful. For example, 

Design Notes (https://github.com/dotnet/roslyn/labels/Design%20Notes)
Specs (the spec proposals actually need better tags to make this possible- currently they're indistinguishable from your run-of-the-mill community suggestions)

**Comment by JoshVarty** [comment]
I just wanted to say that I think the Roslyn team has been doing a really good job with this since the move to GitHub.

**Comment by AdamSpeight2008** [comment]
* Don't assume that the contributor as the same knowledge or access to the same information as you.
  - Especially performance data, and the JIT code produced.
  - Provide resources / links to resource on how to do such things. 

* Be less focused on the style of code *especially from external contributors*,  and more focused on the substance and intent of the code. 
* Prior to closing an issue / PR, announce your intent to close, for example by adding a tag **(To Be Closed)**. Then curtiously wait, *say 24 hrs* before actually closing it, so that OP an opportunity to respond. As they may not be able to respond or comment after it is closed by a team member.

* @ljw1004 has / had a C# and VB.net grammar exploration resource. I think to a site similar to http://referencesource.microsoft.com  but covers the grammar for the languages versions. 

* Tool to explore the implications of a changes or additions to the grammar Which will help to find ambiguities of proposed additions.

**Comment by davkean** [comment]
Thanks for the great suggestions This issue has long since moved on, please feel free to file individual issues for anything that we've overlooked or you think we're not doing correctly.
