### ISSUE TITLE
Provide change logs for Microsoft.Net.Compilers

### ISSUE THREAD

**Issue by vicancy** [dotnet/roslyn#21574]
Hi there, I noticed that Microsoft.Net.Compilers package has upgraded to v2.3.1, however I am not able to find any documents describing the release. I have questions such as: what it has improved from 2.2.0? Should I upgrade my package to the latest version?

Could you point me to the change logs? Sorry if I missed anything.

**Comment by jcouv** [comment]
Packages versioned 2.3.x include C# 7.1, as documented [here](https://github.com/dotnet/roslyn/wiki/NuGet-packages). It also includes bugs fixed in the [15.3 milestone](https://github.com/dotnet/roslyn/issues?q=is%3Aissue+milestone%3A15.3+is%3Aclosed) in the present repo. The tracking of issues within servicing releases of that milestone (referring to the `.x` portion) is a little tricky.

I'm keeping the present issue open, as such versioning information could be included in the package description itself, to make it easier to find.

**Comment by jcouv** [comment]
Updated the packages to point to https://aka.ms/roslyn-packages for more information, including versioning and compiler features. We should continue to accumulate documentation there to answer such questions.

This fix will affect the next wave of packages that we publish (the 2.6-beta1 packages that we should publish in the next few weeks).
