### ISSUE TITLE
"The specified language version is invalid" warning when using VB LangVersion set to 14.0, 15.0, default, latest

### ISSUE THREAD

**Issue by 0xd4d** [dotnet/roslyn#21628]
**Version Used**: VS2017 15.3.1

**Steps to Reproduce**:

1. Create a VB project
2. Add `<LangVersion>latest</LangVersion>` (or 14.0 or later) to the project file and save it
3. Reload the solution in VS
4. Compile
5. Check the 'Error List' window

**Expected Behavior**:

No warning

**Actual Behavior**:

Warning "Load of property 'LangVersion' failed.  The specified language version is invalid." is present in the `Error List` window.

**Comment by jcouv** [comment]
@0xd4d I was not able to repro this issue. Could you make a zip file with your repro project and attach it to the issue? Thanks

**Comment by jcouv** [comment]
Didn't hear back from you in two weeks. I'll close the issue. 
Feel free to re-open if you can add the details to reproduce this. Thanks

**Comment by memark** [comment]
@jcouv I have the same problem. Please see attached repro.
[Repro.zip](https://github.com/dotnet/roslyn/files/1824663/Repro.zip)

**Comment by memark** [comment]
I'm on VS 15.6.2 btw.

**Comment by gustavsigma** [comment]
I am also experiencing this issue.

The repro @memark attached does successfully recreate the problem for me.

**Comment by jcouv** [comment]
Thanks @memark. The attached solution repros the issue for me too (in 15.7 preview 1), showing the error message in the Error List.
![image](https://user-images.githubusercontent.com/12466233/37669010-0468d39a-2c23-11e8-93de-3973b3399e66.png)

One interesting thing is that the IDE otherwise seems to respond to the LangVersion properly (with "15.0" I get squiggles for using a tuple inferred element name, which go away went set to "latest").

@Pilchie I think this is a project-system issue. Can you confirm and route? Thanks

**Comment by jmarolf** [comment]
@jcouv lets start by moving this to dotnet/project-system

**Comment by jcouv** [comment]
Issue moved to [dotnet/project-system #3411](https://github.com/dotnet/project-system/issues/3411) via [**ZenHub**](https://www.zenhub.com/)
