### ISSUE TITLE
Make-method-async code fix breaks ASP.NET MVC action routing after 'Async' suffix is appended to method name

### ISSUE THREAD

**Issue by jeremymeng** [dotnet/roslyn#21770]
**Version Used**: 

**Steps to Reproduce**:

1. create a ASP.NET Core project
2. select MVC template, create the project, and F5 to make sure the home page is shown
3. open HomeController.cs
4. changing return type of `Index()` to `Task<IActionResult>`
5. Add `await Task.Delay(1);` inside `Index()`
6. Invoke code fix to make the method async

Now the method looks like 

```csharp
        public async Task<IActionResult> IndexAsync()
        {
            await Task.Delay(300);
            return View();
        }
```

7. F5
**Actual Behavior**:
HTTP 404

if rename the method back to `Index()` F5 works again.

**Comment by jeremymeng** [comment]
ASP.NET uses the controller names to locate the views.  If there's an `IndexAsync.cshtml` then `http://localhost:55100/Home/IndexAsync` would work

**Comment by terrajobst** [comment]
It should be added that Roslyn allows project system to fix up identifiers after a rename occurs. However, that doesn't help in this case as routing is rule based. One could argue that the routing engine could handle that, but this could have potential for breaking changes.

So as written, I think this should be moved to https://github.com/aspnet/Mvc/issues. However, one could also argue that the "make this method async" shouldn't also rename the method name, but that seems like the wrong direction.

**Comment by CyrusNajmabadi** [comment]
> However, one could also argue that the "make this method async"-fixer shouldn't also rename the method, but that seems like the wrong direction to me.

I agree.  While things break *in this case*, we do the right thing for the majority of cases.  'Async' suffix is a strong pattern in the framework, and should be something we push code toward.  If we don't do this, it just means that users have to take the extra step of having to rename the method.  If you have to do a lot of this, it's an onerous process.

Here it looks like we have an API that uses stringly typed connections.  If that framework wants to work that way, it should hook into the existing roslyn notifications for when this happens so it can appropriately update things.  Also, it should consider providing an analyzer to tell the user when the names don't match teh routing so that things can be clearer.

Finally, it seems to me like MVC should just support the Async extension.  It's a core .net naming style.

**Comment by jeremymeng** [comment]
Agree on the value of "Async" suffix. It would be great if ASP.NET MVC can handle this.  Can you please help move the issue over to them?

**Comment by terrajobst** [comment]
This issue was moved to aspnet/Mvc#6723

**Comment by terrajobst** [comment]
@jeremymeng 

> Can you please help move the issue over to them?

Just use: https://github-issue-mover.appspot.com/

**Comment by jeremymeng** [comment]
Thanks @terrajobst! Nice tool, will use next time.
