### ISSUE TITLE
Add support for marking analyzers with supported project flavors

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#2180]
DiagnosticAnalyzerAttribute takes arguments for supported languages for which to enable the owning DiagnosticAnalyzer. This allows IDE to selectively load an analyzer assembly only if it has a supported analyzer for current project's language.

This works fine. However, we should add extra functionality to allow marking supported project flavors for analyzers. This will enable writing analyzers target specific project flavors for the supported languages. For example, then one can then write a shared project VSIX analyzer, which is only loaded for shared projects.

**Comment by tmeschter** [comment]
@mavasani Except that shared projects aren't projects at the Roslyn level. All we see are the code files linked in from the shared project.

**Comment by srivatsn** [comment]
I don't think teaching analyzers about a specific project system concept is a good idea. Is there a mechanism for filtering this way for regular MEF components? If not, I don't think we should add it for analyzers either.

**Comment by heejaechang** [comment]
@srivatsn @mavasani I think forcing every diagnostic analyzers to must be host agnostic is dictating on our own decision rather than responding to customer need.

I don't believe every diagnostic analyzer wants to be host agnostic or even care to be run on command line. some of them, just want to provide extra information as diagnostic in IDE and only care about VS. (they probably even require some VS service to function)

for such people, we do have DocumentDiagnosticAnalyzer. (which is currently internal). we can think of exposing it to public. and for DocumentDiagnosticAnalyzer, let author annotate it with more metadata such as project flavor.

**Comment by mavasani** [comment]
Why do we need to tie this metadata just to document analyzers? You can as well have any metadata applied to regular diagnostic analyzers via workspace layer attributes and every host can decide whether or not the metadata applies to it. For example, if we had an attribute which takes strings for supported project file extensions, this would be respected when analyzer is installed as VSIX analyzer for live IDE analysis. If analyzer is being executed for command line builds, such attribute will be ignored (why would you add an analyzer reference to a project file or on command line if you want to never execute it for that compilation?).

If we were to implement this, we should allow host specific metadata on analyzers without forcing the analyzer itself to be tied to a host.

**Comment by mavasani** [comment]
@srivatsn We are not tying up or teaching analyzers about a host. This would add ability to add host specific metadata to analyzers, so it can be configured/filtered in different ways for different hosts. Such workspace specific metadata will be ignored by command line analyzer host, but will be respected for VSIX analyzers in IDE.

**Comment by mavasani** [comment]
@tmeschter shared projects was a bad example, I was referring more generally to different project flavors of C# and VB projects.

**Comment by heejaechang** [comment]
@mavasani sure, we could go that way, but not sure why we would go that way if there is a way to get VS services for IDE only analyzers.

and every host deciding what to do with some random metadata on diagnostic analyzer seems just a way to say behavior will become random...

**Comment by mavasani** [comment]
@heejaechang Not sure how it would be random, the attribute/metadata will clearly be tied to a specific set of hosts. Our 2 primary vehicles to enable analyzers right now are: (a) Project OR compilation specific analyzer reference and (b) Host specific analyzer reference, e.g. VSIX installed analyzers for VS session. This metadata will only apply for the later mode.

Approach you are suggesting seems too restrictive. It will force an analyzer, which is fully capable of being enabled via either (a) OR (b), to become only capable of being enabled via (b). An analyzer shouldn't be forced to become a host only analyzer just so that it can be configured for specific hosts. It seems extremely useful to retain the ability to still allow it to execute in command line builds as a project/compilation specific analyzer, even it wants additional configuration when enabled as a host analyzer.

**Comment by heejaechang** [comment]
@mavasani ya, point was making it restrict to a host the metadata has meaning to. didn't want people to use the metadata as property bag to pass random data that each host interpret it differently.

also, if an analyzer require specific host, I assume they do so since it requires host specific information. and I wanted to guide them to right pattern rather than create its own pattern like our own rename diagnostic.

I bet nuget diagnostic analyzer also require some vs specific info to create diagnostic.

**Comment by mavasani** [comment]
How about I want write a simple symbol analyzer that works for just project-k projects? Are you suggesting that such analyzer can either (a) work only in IDE with project-k specific flavor filtering OR (b) work in IDE + command line, but then can't apply project flavor filtering.

I think this is a too restrictive model. I would want such an analyzer to work in both IDE and command line, so can't be a Document analyzer AND also don't want it to run on non-project k projects when installed as a host (VSIX) analyzer in IDE. This is perfectly legitimate use case and our implementation shouldn't prevent it.

**Comment by heejaechang** [comment]
@mavasani  are you saying in compiler, there is a way to figure out something is project k?

**Comment by mavasani** [comment]
No, but why would you specify a project-k specific analyzer reference on command line/project file for a non project-k project?

**Comment by heejaechang** [comment]
@mavasani ya, that is why I think it would be just simpler for people to use host specific diagnostic analyzer and have metadata there only. then, people who don't care about it doesn't need to see those or know it exist.

if we made it either really visible in common DiagnosticAnalyzer, then someone who doesn't need to know about it need to figure out what that is, or if we hide it, then someone who needs it need to wonder around to figure out how to annotate those.

I think it could be just simpler if we have those quite visible (and make them to think about it since it is relevant to the host they are targeting) and make it available only on the host specific analyzer.

**Comment by mavasani** [comment]
@heejaechang @srivatsn  How about this approach: instead of adding metadata to analyzers for project flavors, we can do so for VSIX analyzer references itself. i.e. the Analyzer asset in the VSIX manifest can take attributes for project flavors, and the IDE host analyzer manager can filter such analyzer references for unsupported project flavors. This way we neither need to make analyzers know anything about project flavors, nor care about adding host specific information to analyzer metadata. Metadata that we care about for IDE host analyzers goes along with the mechanism to enable host analyzers, i.e. in the vsixmanifest file itself.

```
<Asset Type="Microsoft.VisualStudio.Analyzer" Path="MyProjectKAnalyzers.dll" ProjectFlavors=".kproj;.xproj" />
```

**Comment by mavasani** [comment]
Additionally, this way I can also write flavor specific analyzers on top of DiagnosticAnalyzer, instead of DocumentDiagnosticAnalyzer, and have the same analyzer added as a project analyzer reference or installed as a VSIX.

**Comment by heejaechang** [comment]
@mavasani that seems good idea if that is only metadata we need for host specific analyzer.

I think we are talking about slightly two different thing. host specific and host agnostic analyzer and project flavor.

when I say host specific, I assume it would require some host specific service other host doesn't have. so, using it as project analyzer will cause issue since those service will not exist in other host.

that is why I want host specific analyzer to be really explicit. and people can't confused and use it under different host.

**Comment by mavasani** [comment]
Agreed, but the current requirement of filtering based on flavors is when the analyzer executes in IDE host, and is needed for all analyzers, regardless of whether they are host specific or agnostic. So the mechanism we provide should not tie with whether analyzer is DiagnosticAnalyzer or DocumentDiagnosticAnalyzer.

**Comment by heejaechang** [comment]
@mavasani project flavor sounds like very VS host specific though. is there any other host that has project flavor concept?

**Comment by mavasani** [comment]
Yes, project flavor and filtering based on that is host specific, but that shouldn't require the analyzer to be a host specific Document analyzer.
Let's chat offline as we are looping over on the same point :)

**Comment by srivatsn** [comment]
This was discussed and we decided against doing it.
