### ISSUE TITLE
Synthesized name of a method implementing a local function doesn't allow reconstructing the original name of the function

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#21822]
Currently the synthesized name is ```<ContainingMethodName>g__LocalFunctionNameOrdinal#Generation```.
There is no separator in between LocalFunctionName and the Ordinal, so if the function name ends with digits it's ambiguous. 

We need to reconstruct the name for some debugging scenarios, like displaying friendly name in stack trace, or invoking local function from an expression in watch window.

For example, currently the stack trace looks like so:
```
ConsoleApp17.exe!C.Main.__f10_0()
```

where it should rather look like
```
ConsoleApp17.exe!C.Main.f1()
```

Proposal: change the synthesized name to include a separator (e.g. ```|```) that can't use used in a valid identifier and that would allows us to parse the local function name unambiguously.

This would be a trivial change. To reduce the amount of code out there that uses the ambiguous synthesized name I suggest we implement it asap (in 15.4).

**Comment by tmat** [comment]
@jaredpar @agocke FYI

**Comment by jaredpar** [comment]
Not sure what this will solve. Local functions were somewhat deliberately done this way because we can't fully support them in the EE right now. Think of all the places where we do signature rewriting. That takse a bit of work to support. 

Just renaming the func here won't fix that. Only the most trivial cases that don't lift.

**Comment by tmat** [comment]
@jaredpar If this was indeed deliberate then that's sadly very shortsighted approach :(

**Comment by jaredpar** [comment]
@tmat 

Disagree strongly. There was one available to do the work necessary for local functions to work in the EE or ENC. The team, as a whole, decided that we would push off the EE / ENC experience related issues to a future release. Instead of letting them fail terribly we generated them such that they wouldn't be available to the EE until we had the time necessary to support them.
