### ISSUE TITLE
using instruction does not compile when typing to interface not implementing IDisposable

### ISSUE THREAD

**Issue by treziac** [dotnet/roslyn#21845]
**Version Used**: 
Microsoft (R) Visual C# version 2.3.2.61928 (ec1cde8b)

**Steps to Reproduce**:

```csharp
interface IA
{

}

class A : IA, IDisposable
{
    public void Dispose()
    { }
}

class Program
{
    static void Main(string[] args)
    {
        using (IA a = new A())
        {
        }

        IA a = new A();
        try
        {
                
        }
        finally
        {
            if(a != null)
            {
                ((IDisposable)a).Dispose();
            }
        }
    }
}

```
**Expected Behavior**:
Program compile and works

**Actual Behavior**:
using line does not compile : `type used in a using statement must be implicitly convertible to 'System.IDisposable`

The equivalent generated code (given https://docs.microsoft.com/fr-fr/dotnet/csharp/language-reference/keywords/using-statement) works properly

**Comment by svick** [comment]
[The spec](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/statements#the-using-statement) says:

> If the form of *resource_acquisition* is *local_variable_declaration* then the type of the *local_variable_declaration* must be either `dynamic` or a type that can be implicitly converted to `System.IDisposable`.

Since `IA` cannot be implicitly converted to `IDisposable`, the compiler behaves according to the spec.

And I think the spec is correct too: if your code was allowed, then the following code would be also allowed:

```c#
interface IA
{

}

class B : IA
{
}

class Program
{
    static void Main(string[] args)
    {
        using (IA a = new B())
        {
        }

        IA a = new B();
        try
        {
                
        }
        finally
        {
            if(a != null)
            {
                ((IDisposable)a).Dispose();
            }
        }
    }
}
```

But this code would throw an exception on the cast, so clearly incorrect code would be allowed.

Could you explain why you want to write code like that?

**Comment by treziac** [comment]
Didn't found this spec, thanks for pointing me to it.
I was in a case where `IA `was explcitly implemented by `A`, so needed to do a cast to `IA`, and wondered why it wasn't possible in the using (workaround is just to add a line `IA ia = a;` or cast before explicite interface call, but didn't see why it wasn't possible)

Was thinking the check could be done on the concrete type created rather than what it is cast to (in the case where an object is created), but it is not as straight forward as I thought indeed.

**Comment by sharwell** [comment]
@treziac It sounds like @svick explained why the compiler is currently behaving as you observed. Did you have any more questions about how to best proceed given this limitation?

**Comment by treziac** [comment]
No, it's ok - I have workaround, it may just be suggestion change, but would mean change the spec for a small use case. You may close if discarded.

**Comment by sharwell** [comment]
@treziac I did not find an existing feature request in [dotnet/csharplang](https://github.com/dotnet/csharplang) for relaxing the requirements of the `using` statement in this regard. I am not in any position to make a decision regarding such a proposal, so if it's something you would strongly favor then that would be the best place to write a feature request.

I would offer the following as a possible workaround:

```csharp
IA a;
using ((a = new A()) as IDisposable)
{
  // ...
}
```

I have seen a similar situation arise in a project long ago. We had a commonly-used interface (`IA` from your example), where most implementations did not implement `IDisposable` (`B` from @svick's example). However, one of the implementations did end up implementing `IDisposable` (`A` from your example). I don't remember exactly how we handled things in the end, but I remember it was quite problematic because we always had to treat `IA` as "possibly implementing `IDisposable`", yet it wasn't actually communicated as part of the interface. In other words, even if you get it to work, you may find that it's still confusing.
