### ISSUE TITLE
IDE crashes with the specific .editorconfig dotnet_naming_rule

### ISSUE THREAD

**Issue by alexanderkozlenko** [dotnet/roslyn#21893]
**Version Used**: 

VisualStudio.15.Release/15.3.3+26730.12

**Steps to Reproduce**:

1. Create a .NET Standard project using default template, ensure it compiles, close the IDE.
2. Place the specified EditorConfig file into project directory: [editorconfig.zip](https://github.com/dotnet/roslyn/files/1272268/editorconfig.zip).
3. Open the IDE, open the created project.
4. Open class `Class1`, add empty line between 6th and 7th lines.
5. Type `strign ` at the empty line (incorrect keyword and one space).

**Expected Behavior**:

Editor and IDE works as usual.

**Actual Behavior**:

IDE crashes. System EventLog contains the specified stack trace for the internal exception: [eventlog_content.zip](https://github.com/dotnet/roslyn/files/1272267/eventlog_content.zip).

**Comment by davidwengier** [comment]
Ran into this one today, thanks for logging the issue so I didn't have to :)

**Comment by davidwengier** [comment]
The actual bug here is that the naming style specified doesn't have a captialization defined, which causes the naming style to not load, however a `NamingStylePreferences` is still created and hence later a .Single call fails because it seems that a `NamingStylePreferences` must have naming style.

Fixing the naming style itself is trivial, but the crash probably shouldn't happen too.
