### ISSUE TITLE
Add support for InternalImplementationOnly attribute

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#220]
InternalImplementationOnly attribute
====================================

One difficulty that faces API authors is that sometimes an `interface` is the most appropriate type for an API element (because there are multiple unrelated implementations internally). However, once a public API element is exposed as an `interface` it would be a breaking change to add additional methods in a future revision of the interface (clients who implement the interface would be broken because they do not implement the new members).

This issue is mitigated when the API is intended to be implemented only by its authoring assemblies. However, there is no language mechanism to enforce that clients do not implement the interface. API authors resort to documentation suggesting that the interface not be implemented in customer code, but customers can fail to notice the documentation resulting in painful compatibility constraints that are unintended.

The Roslyn APIs have an example of this issue with the [`ISymbol`](http://source.roslyn.io/#Microsoft.CodeAnalysis/Symbols/ISymbol.cs) interface and all of its derived interfaces such as [`IMethodSymbol`](http://source.roslyn.io/#Microsoft.CodeAnalysis/Symbols/IMethodSymbol.cs) and [`INamedTypeSymbol`](http://source.roslyn.io/#Microsoft.CodeAnalysis/Symbols/INamedTypeSymbol.cs). We intend to evolve these interfaces in the future as the language changes, but we may be prevented from doing so because customer code may extend these interfaces.

To mitigate this compatibility constraint we propose to add a compiler-provided error. Interfaces such as `ISymbol` that should only be extended or implemented in assemblies that have internal access are marked with an attribute of the name [`System.Runtime.CompilerServices.InternalImplementationOnlyAttribute`](http://source.roslyn.io/#Microsoft.CodeAnalysis/InternalImplementationOnlyAttribute.cs).

```cs
namespace System.Runtime.CompilerServices
{
    /// <summary>
    /// Indicates that the interface may only appear in the base clause of a type
    /// in the same assembly as the attributed interface or a type in
    /// an assembly that has InternalsVisibleTo the attributed interface's
    /// assembly.
    /// </summary>
    [AttributeUsage(AttributeTargets.Interface, AllowMultiple = false)]
    internal sealed class InternalImplementationOnlyAttribute : Attribute
    {
    }
}
```

This interface may be provided as a public type in a platform assembly, or as an internal type (as above) when the referenced platform does not yet provide direct support for the attribute.

When a compiler sees that such an attributed interface is extended or implemented outside of an assembly that has internal access, a compile-time error is produced.

```cs
namespace Microsoft.CodeAnalysis
{
    /// <summary>
    /// Represents a symbol (namespace, class, method, parameter, etc.)
    /// exposed by the compiler.
    /// </summary>
    [InternalImplementationOnly]
    public interface ISymbol : IEquatable<ISymbol>
    {
```

By adding this attribute to interfaces such as `ISymbol`, an API author can have some confidence that future additions to the interface will not break compatibility with existing clients, as those clients will have been prevented from implementing the interface.

**Comment by apskim** [comment]
It feels like something strongly related to records. In the pattern matching proposal, multiple people have mentioned that it would be great to have automatic verification of `switch`/`match` completeness. With the current design, it requires a similar attribute/keyword applied to the root class of the record hierarchy. This attribute/keyword would enforce that all descendants of the root class are defined in the same assembly, hence the compiler knows all of them ahead of time. In Scala it's called `sealed case class`.

Looks like `[InternalImplementationOnly]` solves the same problem, but for interfaces instead of records. Wouldn't it be better to design the same solution (at least syntactically) for both concepts?

**Comment by gafter** [comment]
This would be done in C# 6, which would be necessary to get the benefits in the type ISymbol.

This does not make the type closed, as the interface can still be extended in assemblies with InternalsVisibleTo access. Furthermore, classes that implement the interface can still be extended wherever they are accessible. So no, this does not address the same set of problems.

**Comment by theoy** [comment]
So exciting! I have a ton of respect for the problem that this proposal is tackling. I share in the concern that our current versioning plans involve evolving the contract for ISymbol in ways that are unusual for other .NET interfaces.

I'm looking forward to the discussion in tomorrow's language design meeting, as well as the review with upper management on whether this is really worth including in the release at this point. We're getting so close to 1.0!

My main concerns with this approach are the following...
* **Prevalence of other tools** (including previous versions of .NET compilers). We're striving had to replace the need for the C# 5/ VB 11 compilers (and earlier), but they were quite successful! Even if we added this to C# 6, it would take a while before compiler adoption in the wild made this effective enough to provide wide-reaching security for API authors. 'dynamic' has the same problem in that earlier tools see it as 'object'. However, in that case it's not that bad since they were generally no worse off. This is a little different because old tools (iincluding previous versions of Visual Studio) would lead people to the wrong path by still easily making it easy for Interface consumers to spin up an implementation (such as the IDE implement interface feature, or Moq's dynamic interface impl features).
* **Other uses for interfaces** Interfaces in .NET also serve double-duty, in scenarios such as Windows Store App development and COM. In those two worlds, the binary contract for the interface is required to be fixed, there are many, many ["equivalent" definitions have direct conversion support in the runtime](https://msdn.microsoft.com/en-us/library/vstudio/dd997297.aspx). We could scope it out, but it would probably end up being a common "gotcha".

**Comment by erik-kallen** [comment]
It might be problematic for test code to not be able to create a mock implementation of an interface. I realize that most likely mock libraries generating dynamic stubs will not be constrained by this, but IMO it's often reasonable to have explicitly created mock types in test projects.

**Comment by sharwell** [comment]
If this was implemented as a library + analyzer with the default severity set to Error, it would be possible to manually set the severity to some other value in cases where code needs to implement the interface for other reasons. The description of the diagnostic would include information about the compatibility problems this could produce as new versions of the interface are released. Individual library authors would be responsible for keeping this in mind before changing the severity.

**Comment by srivatsn** [comment]
@sharwell - we've created [such an analyzer](https://github.com/dotnet/roslyn/blob/master/src/Diagnostics/CodeAnalysis/Core/InternalImplementationOnlyAnalyzer.cs) for the Roslyn nuget package such that folks will be told to not implement ISymbol. However every library author will have to do this if it wasn't in the compiler. The problem with putting the attribute in a separate library with the analyzer is that it's not the library author who need to be warned, it's the library user and there's no way to guarantee that the library user will install this analyzer. The only analyzer that they are guaranteed to run is the compiler.

**Comment by sharwell** [comment]
Why not declare the analyzer package as a dependency of the package which provides `ISymbol`? Then the analyzer is automatically installed by default, and only disabled by explicit action of the user.

**Comment by srivatsn** [comment]
That is what we do for ISymbol. This proposal is a generalization of that analyzer for other library authors.

**Comment by sharwell** [comment]
I assume the intent would be for this to be added as a new warning, and not as an error?

I would be uncomfortable using this feature if it was implemented as an error in the compiler.

**Comment by gafter** [comment]
@theoy Agreed, the "guarantee" provided by this would not be airtight. However, it is tighter than nothing, and far stronger than can be achieved by analyzers. I also agree that it would be silly (though not harmful) to use it with Embedded Interop Types.

@erik-kallen These interfaces are exactly as (or more) hand-mockable as an abstract class with an internal constructor. But they are much more flexible from the point of view of the API author who implements the API.

@sharwell Any users that extend the interface in spite of this diagnostic would place us in the position of breaking them when evolving. The existence of such users would be evidence likely preventing us from making future changes to the API. Unfortunately there are too many ways to "opt out" (or not "opt in") with analyzers. That is why this needs to be an error, not a warning, and implemented by the compiler. I agree, you should probably not use it if it is an uncomfortable fit for your public API, just as you probably already avoid abstract classes with internal constructors for the same reasons.

**Comment by tmat** [comment]
My personal opinion is that we should go further than just reporting compiler error and make it a runtime loader error (in the CLR type loader) as well.

**Comment by gafter** [comment]
@tmat That would work if we were willing to take a CLR version change (i.e. abandon reverse compatibility - running on older platforms) for this. We're not willing to do that though, and existing CLRs do no diagnose this.

**Comment by tmat** [comment]
Why would we need to abandon running on older platforms? Older CLR would just not enforce it. Older compilers won't enforce the attribute either.

**Comment by gafter** [comment]
@tmat We do not generally introduce reverse breaking changes in the CLR without versioning the IL. It would not be OK to have code that runs on one version of the CLR but fails to run on an updated CLR that claims to support the same version.

**Comment by tmat** [comment]
That can by addressed - the CLR knows that the app was built against an older framework that didn't enforce the rule. So it could suppress the check for such apps.

**Comment by gafter** [comment]
I don't know what you mean by "built against an older framework that didn't enforce the rule". One "builds against" APIs, not CLR versions. The way to record the CLR version against which an application was built is the IL version number.

In any case, if we're going to be suppressing the checks, then we are not actually enforcing them.

**Comment by gafter** [comment]
@AlekseyTs You're probably interested in this.
