### ISSUE TITLE
Design decisions made on the way to ref/span features

### ISSUE THREAD

**Issue by VSadov** [dotnet/roslyn#22106]
See the document here:

https://github.com/VSadov/csharplang/blob/RefSpanDesignChoices/proposals/RefReadonlySpanDesignChoices.md

**Comment by VSadov** [comment]
CC: @dotnet/roslyn-compiler @MadsTorgersen

**Comment by svick** [comment]
> `ref readonly` parameters and returns are allowed anywhere where a byval parameters are allowed. This includes […] operators (including conversions) […]
> `ref readonly` returns allowed anywhere where ref returns are allowed. I.E. […] operators (including conversions), […] but not in operators.

I'm confused by this, since it seems to say twice that `ref readonly` returns are allowed in operators and once that they are not.

```c#
void (ref readonly int arg){...};

M1(obj.field);
M1(42);
M1();
```

I think the function was supposed to be named `M1`, but the name is missing. Also, the call `M1();` seems to imply `M1` was supposed to have a default value, but it doesn't.

```c#
true? ref 42, ref 2 + 2
```

Was that supposed to be `:`, not `,`?

---

The document does not mention being able to use `in` instead of `readonly ref`, which is syntax mentioned by [the older proposal](https://github.com/dotnet/csharplang/blob/master/proposals/readonly-ref.md). Is that syntax not going to be allowed?

**Comment by VSadov** [comment]
@swick - thanks! 
the `ref readonly` returns and operators might be fixed already, unless there is another place.   
The other 2 issues need to be corrected.

**Comment by VisualMelon** [comment]
I am distressed to read that calling code will not have to explicitly decorate arguments with `ref readonly` modifiers. Even if the situations where `ref readonly` is applicable are closer to ByVal than `ref`, the semantics are not the same (if generally the same, and not an issue in simple situations).

Without explicit decoration, any code that takes a `ref readonly` return with 'in' parameters becomes terrifying:

```
void DoStuff()
{
    int myInt = 42;
    int myOtherInt = 7;

    readonly ref int result = Process(/*ref readonly ????*/ myInt, ref myOtherInt);

    Console.WriteLine(result);

    myInt = -1;

    Console.WriteLine(result); // I can't have changed this, right?
}
```

_The obvious `ref` param is just for example; the document shows examples where a method returns something that isn't passed in, so the confusion isn't restricted to code that people already complain about because it has `out`/`ref` params_

Decorating the parameters forces the developer to acknowledge that they can create a scenario for themselves that can cause untold confusion. I do not want to read per-method documentation to know whether this piece of code can ruin my day or not. Moreover, I want my code to break when the API I'm using changes because the behaviour could change; this will not occur with the current proposal: This is _really bad_. Requiring the modifiers at the call-site avoids any such uncertainty.

I see little benefit at all from not requiring these modifiers, and no reason not to require them. I can imagine a number of ways in which not requiring them can create misery for new and existing code, and plenty of benefit for forcing a user to acknowledge that they are entering a world where misery and pain are just around the corner: I gather this functionality is being added to enable more performant code, and duly may well be limited to only a handful of applications, so there is no cost what-so-ever in requiring the developer to be acknowledge what they are doing. I can't find any discussion about this particular concern: are there some meeting notes somewhere which explain why this decision has been taken? I presume there is a more serious reason than 'less typing required', but nothing has yet occurred to me.

The overload resolution between `readonly ref` and ByVal is ridiculous: the semantics are different (and duly behaviour may be different), there is no obvious reason to exclude such overloads (e.g. for generics, performance concerns will vary between value and reference types, so they may be of use), and this blatant trap for inexperienced C# programmers can be avoided by following the (existing and prevalent) style of decorating arguments with the appropriate modifiers (which is invaluable for `out` and `ref`, and I would argue the only sensible approach for in-reference semantics).

I would be extremely interested to hear (or be pointed at, if I've just failed to find them) some of the reasons why this uncharacteristic decision has been taken. Some more examples of using the returns from `ref readonly` methods would also be most appreciated.

**Comment by ektrah** [comment]
After prototyping a bit with `in`/`ref readonly` in the last couple of days I find myself wanting "pass an argument by-reference but the reference is read-only" more often than "pass an argument by-value more efficiently by actually passing it by-readonly-reference under the hood".

Would it maybe make sense to have both? `ref readonly` exactly like `ref` (including variables, etc.) but read-only, and `in` for implicit pass-by-readonly-reference?

```csharp
static void Main()
{
    BigStruct bigStruct = new BigStruct();

    ref readonly BigStruct bigStructRef = ref Foo(ref bigStruct);

    Foo(bigStruct);
}

static ref readonly BigStruct Foo(ref readonly BigStruct value)
{
    ref readonly BigStruct temp = ref value;
    // ...
    return ref temp;
}

static void Bar(in BigStruct value)
{
    // ...
}
```

**Comment by VisualMelon** [comment]
That's an interesting idea...

If `in` could only then be passed as `in` internally and can't be returned by reference, then there would indeed be reduced risk at the call-site, mostly relegated to the method itself (which may end up changing the value by side-effect as in [the example given](https://github.com/dotnet/csharplang/blob/master/proposals/readonly-ref.md#aliasing-behavior-in-general)); but it can still go wrong in funky and non-obvious ways, and in ways that may break existing code (e.g. that assumes a copy will take place).

That last point reminds me also that it isn't obvious how you might pass a value ByValue to a `ref readonly` or `in`, which may well be something you'd want to do. I wouldn't be wholly opposed to using copy semantics at the call-site by default (i.e. treat it as an RValue), switching to `ref readonly` when explicitly decorating the method (treat it as an LValue, error if it is an RValue (I like this bit for lots of reasons)). This means that 'quick and easy' code would work as you'd expect, and you could 'opt in' to the performance improvements if you wished. Of course, this means there are 2 ways of passing the parameter now, which is bad (will confuse inexperienced users), but will (by default) prevent any opportunity for unintended side effects and still facilitate performance-hungry code. Less than ideal, but at least the call-site become less ambiguous (there could still be confusion about where myserious `ref readonly` returns are coming from which you don't seem to be passing in, but that's possible already by imaginative means, a probably only a concern for performance-hungry code).

This is going to keep me up at night...

**Comment by ektrah** [comment]
@VSadov Can you share what's the level of maturity of the span spec? Is feedback like the one above helpful or is the design already finalized? https://github.com/dotnet/csharplang/issues/666 is a bit vague on the current status.

**Comment by VSadov** [comment]
This has been discussed in LDM. The actionable changes were logged as separate issues.
