### ISSUE TITLE
API review for IUsingStatement

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#22279]
We should merge the `Declaration` and `Value` into a single field. The OperationKind of this field will tell the user whether it is a variable declaration or an expression.

http://source.roslyn.io/#Microsoft.CodeAnalysis/Operations/IUsingStatement.cs,afcaf33ff8626c1b

**Comment by 333fred** [comment]
As part of this, VB needs to be adjusted. Given the following sample code:
```VB.NET
Module Program
    Class C
        Implements IDisposable
        Public Sub Dispose() Implements IDisposable.Dispose
        End Sub
    End Class
    Sub Main(args As String())
        Using c1 As New C
            Console.WriteLine(c1)
        End Using
    End Sub
End Module
```

Getting the IOperation for the UsingStatementSyntax returns
```
IVariableDeclarationStatement (0 declarations) (OperationKind.VariableDeclarationStatement) (Syntax: 'Using c1 As New C')
```

This is because the ResourceList that we create from in https://github.com/dotnet/roslyn/blob/master/src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory_Methods.vb#L254 is composed of BoundLocalDeclarations, which we don't handle appropriately.
