### ISSUE TITLE
CLI: namespace error on fresh VB project

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#22292]
Repro:

1. `mkdir 22227-cli-vb`
2. `cd 22227-cli-vb`
3. `dotnet new console --language=vb`
4. `dotnet build` produces the namespace error below

```
> dotnet --version
2.0.2-vspre-006949
```

```
> dotnet build
Microsoft (R) Build Engine version 15.3.409.57025 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

vbc : error BC30113: '22227-cli-vb' is not a valid name and cannot be used as the root namespace name. [D:\issues\22227-cli-vb\22227-cli-vb.vbproj]

Build FAILED.

vbc : error BC30113: '22227-cli-vb' is not a valid name and cannot be used as the root namespace name. [D:\issues\22227-cli-vb\22227-cli-vb.vbproj]
    0 Warning(s)
    1 Error(s)
```

Relates to https://github.com/dotnet/roslyn/issues/22227

**Comment by am11** [comment]
Does vb.exe by design considers the directory name to be the root namespace unless we explicitly add normalized name in `<RootNamespace>_22227_cli_vb</RootNamespace>` in vbproj?

csc doesn't seem to rely on dirname, even when there is no namespace in the program, actual dirname has invalid (hyphen) character and `<RootNamespace>` is set to `22227-cli-vb` (with same invalid chars) in csproj.

If it's not a breaking change, would be cool if vb.exe and csc.exe behave the same way.

**Comment by jcouv** [comment]
It looks like the problem is not with `vbc.exe`, but with the arguments it receives. If the `vbproj` file is named A, then there is a `/rootnamespace:A` command-line option.

I'll move the issue to the CLI repo.

**Comment by jcouv** [comment]
Issue moved to [dotnet/cli #7704](https://github.com/dotnet/cli/issues/7704) via [**ZenHub**](https://www.zenhub.com/)
