### ISSUE TITLE
Indent Guides show up between using directives

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#22328]
**Version Used**: 15.3

From: https://developercommunity.visualstudio.com/content/problem/116286/indent-guides-are-misplaced-on-using-directives.html

![image](https://user-images.githubusercontent.com/235241/30829163-f1eb2564-a1f4-11e7-8ed6-a0a25f55dbe9.png)

Notice the indent guide

**Comment by dpoeschl** [comment]
Seems incorrect to me.

**Comment by gundermanc** [comment]
Agreed, I think they do this because the IBlockTag.Type is not set to PredefinedStructureTypes.Nonstructural. IIRC VB using blocks can be indented, so this was done to ensure that they receive indent guides.

**Comment by CyrusNajmabadi** [comment]
it was intentional when i did it.  :)

**Comment by CyrusNajmabadi** [comment]
> IIRC VB using blocks can be indented

VB has to be top level.  But C# can be indented.  But that wasn't really why tey got indent guides.  I gave them indent guides since they're conceptually thought of as being grouped all together and so the dotted line helped convey that.

Of course, if we think this isn't valuable/helpful we can remove.   But it made sense to me at the time.

**Comment by CyrusNajmabadi** [comment]
Has been like this for 5 years, and only gotten one piece of feedback.  Seems fine to keep as is.
