### ISSUE TITLE
Signature info should use named arguments for selection, but not filtering

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#22341]
**Version Used**: 15.4 Preview 2

**Steps to Reproduce**:

Invoke signature info at the `$$` location in the following code:

```csharp
private void Api(int x) => { };
private void Api(string y) => { };

private void Method()
{
  Api($$y: default);
}
```

**Expected Behavior**:

1. Signature info shows two overloads
2. The overload selected by default is `Api(string y)`

**Actual Behavior**:

Signature Info only shows one overload. This has a negative impact on API discoverability for users attempting to learn APIs via Signature Info.

:memo: Note that Quick Info (tool tip when you hover over the call site) *does* indicate that overloads exist. Only Signature Info is failing here.

**Comment by DoctorKrolic** [comment]
@sharwell This seems to be by-design. At least, there are existing tests, that treat this behaviour as expected, e.g.:
https://github.com/dotnet/roslyn/blob/09408ab8a29e03caddfb11f29328c05169ac7cde/src/EditorFeatures/CSharpTest/SignatureHelp/InvocationExpressionSignatureHelpProviderTests.cs#L1865-L1888
And there are lots of them. I found 22 failing tests in total, when tried to tweak the behaviour in order to match the described in the issue.

**Comment by sharwell** [comment]
@DoctorKrolic Yes, this issue is a request for a design change, as this feature is behaving differently from other features.

**Comment by CyrusNajmabadi** [comment]
Clsoing out as speculative.  IF we need to do this we shoudl assign to dev/milestone to get done.
