### ISSUE TITLE
Adopt 15.5 compiler

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#22380]
Because of build-from-source constraints, the branches producing 15.5 compiler should not use a 15.5 toolset. But as soon as we start working on a branch for next version, we should adopt the 15.5 toolset compiler.

**Comment by jasonmalinowski** [comment]
@mavasani, @jinujoseph: weren't you looking at getting us moved over soon for dogfooding reasons?

**Comment by mavasani** [comment]
Yes, that is correct. We plan to move dev15.5.x branch to consume/dogfood 2.5 FXCop analyzer packages, which also require bumping to the latest 2.5 compiler toolset with latest IOperation changes. @jcouv Can you give some more details for this?

**Comment by jcouv** [comment]
I don't have more details, but @jaredpar can fill in. 
My understanding is that RedHat requires that the C# 7.2 compiler be built using an older compiler (such as the C# 7.1 compiler).
This means that moving forward we can only dogfood the compiler in a vNext branch.

**Comment by Pilchie** [comment]
Is the requirement that we *use* a 7.1 compiler, or that we *be able to use* a 7.1 compiler?  In other words, would using the 7.2 compiler with `/langver:7.1` be enough (the source build could then disable analyzers that won't run on the 7.1 compiler).

**Comment by jaredpar** [comment]
> In other words, would using the 7.2 compiler with /langver:7.1 be enough (

No. When doing a source build we must use the same compiler (actual binary) that we previously inserted.

**Comment by jaredpar** [comment]
Note that in the future this draconian restriction should go away. Our velocity here is limited by how often we insert into our source partners. Presently that is only when we ship because the source build operation is still very new to us and just not setup for regular use. 

There is a big effort underway now to fix that. Make source build easy and regular. Once that happens we will be inserting much more regularly (ideally sprintly). That will allow us to adopt a lot faster.

**Comment by jcouv** [comment]
post-dev15.5-contrib branch now uses C# 7.2. Closing.
