### ISSUE TITLE
Discarded stackalloc infers Span<T> type while var does not

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#22434]
**Version Used**: master

**Steps to Reproduce**:

```cs
class C
{
  unsafe void M()
  {
    var _ = stackalloc byte[1]; // infers pointer
    _ = stackalloc byte[1]; // infers Span<> (CS0518 if not imported) but produces CS8183
  }
}
```
**Expected Behavior**: consistent behavior

**Actual Behavior**: inconsistent behavior

**Comment by jcouv** [comment]
Yes, this is inconsistent, but this currently is by design. 
`stackalloc` has a natural type of `Span`, but for backwards compatibility there is one exception: when initializing a local.

Relates to https://github.com/dotnet/roslyn/issues/22411, which proposes an analyzer to warn about such `var` locals. This is also a candidate for a diagnostic with warning waves.
