### ISSUE TITLE
.editorconfig directive dotnet_sort_system_directives_first = false is not regarded

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#22465]
From: https://developercommunity.visualstudio.com/content/problem/45249/editorconfig-directive-dotnet-sort-system-directiv.html

"System namespaces always come first, no matter what the value of this directive is. Other directives work fine."

**Comment by sharwell** [comment]
This sounds like a duplicate of #19089, assuming the user attempted to use a Fix All operation here.

**Comment by poke** [comment]
For what it’s worth, this particular bug was fixed with release 15.3. I believe the original issue was that the .editorconfig was ignored when sorting the usings, e.g. using the “sort and organize usings” functionality. But this was fixed in 15.3 and has been working fine since then. The original poster from the VS community has since accepted my comment that it started working with 15.3 as a solution, so I would assume that this is solved.

For the mentioned Fix All operation, there still is #19089, so I would say this issue can be closed.

**Comment by dpoeschl** [comment]
Great, thanks @poke!

**Comment by Timovzl** [comment]
Is anyone else experiencing this again, on 18.8.0? System usings going first, even if local settings and .editorconfig both attempt to disable that behavior?
