### ISSUE TITLE
Proposal to bring back the "Sort Usings" command

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#22469]
Developer Community: https://developercommunity.visualstudio.com/content/problem/46236/bring-back-sort-usings-command.html

"Please bring back "Sort Usings" command to C# editor context menu.

2017 replaced this command with "Remove and Sort Usings", which is not what I prefer doing: I do not want to remove stock usings from the list, because every time I want to use a feature from those, I have to remember which namespace it's in. Stock usings that New File creates for C# files provides a reasonable list of features available for me, without having me to remember each namespace.

I still want to sort usings, but now the option for doing so, without removing is gone."

**Comment by dpoeschl** [comment]
+2 more comments in agreement on the Developer Community issue

**Comment by dpoeschl** [comment]
@kuhlenh This is a good point. Thoughts?

**Comment by kuhlenh** [comment]
Yeah, we've been hearing this frequently enough that we need to consider bringing it back. I really don't want to add more top-level commands to the Context Menu, so we might have to nest this (though that also doesn't seem ideal). Any other ideas?

**Comment by bladeoflight16** [comment]
I'd like to propose an alternative solution.

The *main* problem with Remove and Sort is that it removes the **default, stock `using`s** that are included in the default class templates. As the original request says, the reason for avoiding the Remove and Sort command is that it removes these.

So instead of bringing back the Sort only command, could Remove and Sort be modified to leave those `using`s alone, even if they're unused? This would make the command vastly more useful and eliminate the need to bring back the old command.

If you want to preserve the existing functionality, a separate Remove All and Sort could be added, and the modified version (that leaves the stock `using`s alone) could replace the one in the context menu.

Also, in the mean time, does the Sort only command still exist at all? I haven't been able to find it yet. If it does, it would be nice to document a work around for accessing it.

**Comment by CyrusNajmabadi** [comment]
> So instead of putting the Sort only command back in the context menu, could Remove and Sort be modified to leave those usings alone, even if they're unused?

I would prefer to not do that.  If htat happens, then we'll just hear people complaining "i said 'remove unused usings' and the usings weren't removed!" :)

> because every time I want to use a feature from those, I have to remember which namespace it's in

This is a very strong reason for us to support intellisense for items outside of hte namespaces in scope :)  

--

That said, i think adding back "sort usings" would be fine.  I would just not put it in the context menu.  Consider the 'Edit | IntelliSense' menu, along with a shortcut.

**Comment by jmarolf** [comment]
> This is a very strong reason for us to support intellisense for items outside of the namespaces in scope :)

I think this is the real answer.  If we suggest items in intellisense irrespective of usings in a file the user no longer misses features if they remove unused usings optimistically.

**Comment by framgeld** [comment]
+1 for reintroduction of "Sort Usings". Not all classes require the "System", "System.Linq", etc namespaces that are added by default and I find myself removing them if they are not required.

**Comment by bladeoflight16** [comment]
@CyrusNajmabadi 
>This is a very strong reason for us to support intellisense for items outside of hte namespaces in scope :)

I'm not sold on this. I could easily see this resulting in a *lot* of clutter in the auto-complete.

**Comment by CyrusNajmabadi** [comment]
> I'm not sold on this. I could easily see this resulting in a lot of clutter in the auto-complete. 

1. We could always expose things through a different gesture.  "Symbols in scope" and "All symbols"
2. We have ways to filter the list already (i.e. filter to classes/properties/locals/etc.)  This could tie into that.
3. FWIW, the auto-complete list is already *OMGHUEG*.  I did some checks of how large the list was in some of my projects when doing some perf tests for completion, and it was *well over 100k* items.  At that point, the actual list isn't relevant.  It's just there to help you speed up typing, and to help you find things *once* you've typed enough to filter effectively.  

IMO, the larger list actually helps you with the last bit.  First, it makes typign better, as you're less likely to type something *not* in the list because you were missing the using.  So other items won't cause mistypes against the item you want.  Second, filtering should still be effective as names don't generally span that many namespaces.  i.e. if i use Xml then that will certainly pull in a few more namespaces with a few elements vs the ones i'm getting already.  But not substantially enough to cause the list to be too cluttered.  

And, if that's a concern, they can be appropriately grouped such that they are there, but down below the list of actual items in scope.

**Comment by kuhlenh** [comment]
My proposal would be to leave Sort Usings out of the Editor Context Menu but add it back as a command so that users can give it a keybinding and use it. (Remove and Sort usings was used by at least an order of magnitude more than Sort Usings, so I can't justify putting Sort Usings back in the menu that we're trying so hard to shorten). 

I agree that when we add unimported types to completion that the Sort Usings issue may vanish. However, I don't want these users to have their productivity stifled until then. @dpoeschl is it hard to add Sort Usings back? Could we get it into the next update?

**Comment by jmatthiesen** [comment]
Reviving an old issue thread here - on the VS for Mac product we received some similar feedback with a use case for Sort Usings: https://developercommunity.visualstudio.com/content/problem/395317/cant-sort-usings-anymore-without-removing-unused-o.html

**Comment by nathanielcook** [comment]
I'm surprised no one has mentioned conditionally compiled code. (i.e. `#if SOME_BUILD_CONFIG`) In my experience with Visual Studio for Mac, the "remove" feature removes usings that are not referenced in the currently selected build configuration. So when you select the other build configuration, the build is broken because you no longer have a using that you need. That's why I usually want to just sort, rather than sort and remove.

**Comment by nathanielcook** [comment]
Just double checked and yep, it still works that way. For mobile development it is quite common to use conditional compilation ifdefs, so the "Remove and Sort Usings" can be pretty unusable for files that have that.

**Comment by CyrusNajmabadi** [comment]
@nathanielcook The appropriate thing to do in that situation is place the right usings if the right `#ifdef`d blocks.  That way all your code is consistent across all your conditional compilation options.

**Comment by nathanielcook** [comment]
> @nathanielcook The appropriate thing to do in that situation is place the right usings if the right `#ifdef`d blocks. That way all your code is consistent across all your conditional compilation options.

I had a feeling someone might suggest that. Putting ifdefs among the using statements breaks sorting! ("Remove and Sort Usings" removes, but no longer sorts.) Not to mention that it is super ugly, hard to read and unnecessarily lengthens the amount of code at the top of the file. We avoid it wherever we can.

**Comment by CyrusNajmabadi** [comment]
> I had a feeling someone might suggest that. Putting ifdefs among the using statements breaks sorting! ("Remove and Sort Usings" removes, but no longer sorts.)

That sounds like something that can be fixed.  If you'd like to contribute a fix here, i'd be happy to help review it.

> Not to mention that it is super ugly, hard to read and unnecessarily lengthens the amount of code at the top of the file.

It doesn't feel unnecessary to me.  It feels like it appropriately explains what hte code is doing.  You are using that `using` in certain configurations, but not using it is in others.

--

Note: this has been the position of the IDE team back since I added this feature in VS 2005 :D  To prevent usings from being removed in conditional scenarios, they shoudl also be placed in an appropriate conditional that matches their usages.

**Comment by CyrusNajmabadi** [comment]
The relevant code is here: https://github.com/dotnet/roslyn/blob/master/src/Workspaces/CSharp/Portable/Utilities/UsingsAndExternAliasesOrganizer.cs#L107

We'd just need a PR to fix things up so that within any section of usings inside a pp-directive block, things can still be sorted.

**Comment by nathanielcook** [comment]
Our team wants to sort using statements without removing unused ones. We do not want ifdefs among the using statements.

I don't disagree with teams that decide to ifdef their usings; it's certainly a valid approach that has some benefits, as well as some downsides. I do disagree with the notion that everyone has to do it that way; it's a decision that will vary per team/repo. Doing things our way used to be easy with Visual Studio for Mac, until "Sort Usings" was removed recently with the switch to Roslyn for that feature.

**Comment by CyrusNajmabadi** [comment]
> I do disagree with the notion that everyone has to do it that way; 

You don't have to do it that way.  It's simply that that's not a scenario that the IDE is going out of its way to support.  

Note: if you sort your usings, the IDE will respect that.  Furture usings that are added will be added in a way that respects sorting.  

If there is a strong desire to have ths feature, i think it's fine if someone else wants to provide it out-of-band.  For now, the decision was made that it was not worth supporting and occupying things like the UI with all these different options.

If you'd like help writing such a feature, i'd be happy to help out with that as well.  It could be delivered as per a nuget package for peopl that want this precise feature for this precise scenario.  Thanks!

**Comment by CyrusNajmabadi** [comment]
PR was here: https://github.com/dotnet/roslyn/pull/12179

**Comment by kendrahavens** [comment]
I got internal feedback expecting "Sort usings" to be offered in a lightbulb as opposed to the right-click menu next to the "Remove usings" refactoring.
![image](https://user-images.githubusercontent.com/8293542/55980965-85954b80-5c4a-11e9-963f-efef384e7561.png)
