### ISSUE TITLE
Could not load file or assembly 'Microsoft.CodeAnalysis.Workspaces, Version=2.3.0.0 in VSIX project

### ISSUE THREAD

**Issue by ranuka2** [dotnet/roslyn#22515]
**Version Used**: 
2.3.2

**Steps to Reproduce**:

1. Create a VSIX (c#) project in Visual Studio 2015 Update 3 with .Net framework 4.6
2. Add latest Microsoft.CodeAnalysis library to VSIX project
3. Add menu command to the VSIX project
4. Add following code in menu command action

```
string projectFilePath = @"C:\ConsoleApp1\ConsoleApp1.csproj";
string outputFilePath = @"C:\ConsoleApp1\ConsoleApp1.dll";
Project project = null;

using (var workspace = MSBuildWorkspace.Create())
{
	project = workspace.OpenProjectAsync(projectFilePath).Result;
	var compilation = project.GetCompilationAsync().Result;
	var compilationStatus = compilation.Emit(outputFilePath);
	bool isSuccess = compilationStatus.Success; 
}
```
**Expected Behavior**:
Roslyn should be able to compile the project and emit output to target location.

**Actual Behavior**:
Following exception occurred when invoking the command.

Could not load file or assembly 'Microsoft.CodeAnalysis.Workspaces, Version=2.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.

**Note**:
Error doesn't occur and command executes successfully when version of the Microsoft.CodeAnalysis is downgraded to 1.3.2

**Comment by RipPer56** [comment]
@Pilchie is this still unresolved?

**Comment by jmarolf** [comment]
Roslyn 2.0 and higher assemblies are not supported on Visual Studio 2015.  You need to use 1.3.2 or lower versions

**Comment by RipPer56** [comment]
@jmarolf No! downgrading is never a solution. Plus i just found out a sort of a resolution.

You must add the references that Studio could not locate as Assets in the source.extension.vsixmanifest :
  - Type : Microsoft.VisualStudio.Assembly
  - Source : File on filesystem
  - Path : the path to the right DLL (since VS by default looks for the DLL in C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\ or whatever installation path you have)

After that you must add the binding redirect of the DLL that Microsoft.CodeAnalysis needs (that are in the app.config by default). But since the "app.config" that the experimental VS uses is [installation path]\Common7\IDE\devenv.exe.config, means we can't change it. So you can instead add this line in the AssemblyInfo.cs:
[assembly: ProvideBindingRedirection(AssemblyName = "AssemblyName", NewVersion = "*.*.*.*", OldVersionLowerBound = "*.*.*.*", OldVersionUpperBound = "*.*.*.*")]
