### ISSUE TITLE
Spurious squiggle sometimes stays in the editor after error is fixed

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#22566]
**Version Used**: 
15.3

**Steps to Reproduce**:

Starting with 15.3 I'm noticing that sometimes in a C# file when I quickly fix an error, a squiggle with the error stays in the editor. Then it keeps tracking with buffer changes and there's no way to remove it. There are no errors in the error list and it compiles fine. Hovering over the squiggle shows the error that used to be there.

I don't remember this before 15.3 or maybe 15.2 so it's a regression.

I'm not sure if it's the Editor or Roslyn. Unfortunately I don't have repro steps (fix errors fast?), but I'm filing this issue mainly for visibility and awareness. Hopefully as others run into this we can brainstorm and narrow it down eventually.

@heejaechang

**Comment by 0xd4d** [comment]
I think it started in 15.3.4, and it's very annoying.

**Comment by heejaechang** [comment]
@jinujoseph looks like we introduced a bug in diagnostic tagger at some point around that time.

**Comment by jinujoseph** [comment]
reported here https://developercommunity.visualstudio.com/content/problem/115131/editorintellisense-is-showing-non-existance-error.html

**Comment by CyrusNajmabadi** [comment]
I've also run into this.  Note: i have pushed for years for their to be a simple API exposed by the diagnostics subsystem for aggregrating and eventing diagnostics for a document.  Currently, there is no such API, and consumers must instead use several *undocumented* APIs and eventing sources to try to figure out what the actual state of the system is.  One such system is the diagnostic tagger.  It has had numerous bugs over the years because there simply is no documentation stating what events it needs to listen to, or how it is supposed to use the diagnostics subsystem properly to keep proper track of what the actual diagnostics are, and how they're changing.

For example, the expectation from the diagnostics subsystem is that the higher layer knows about the complete set of events (like workspace events) that could cause diagnostics to change.  However, the higher layers don't know what the complete set is, making it very possible to miss things and get into a perpetual inconsistent state.

These systems have dragged along for years with these same issues plaguing them.  To me, it's gotten out of hand.  I think it's imperative that the diagnostics subsystem provide a reliable, simple and *documented* API for this sort of purpose.  Only the diagnostics subsystem can provide this, as only it truly understands its own internal data and only it understands all the system events that must be tracked in order to keep this working properly.

**Comment by CyrusNajmabadi** [comment]
Another point to note: we've had barely any issues with all our other taggers (which we have at least a dozen of).  The reason for this is that all our other taggers sit on top of systems that clear supply an authoritative source of data and events to care about.  Because of that, the tagging infrastructure can work reliably for as long as VS stays up.

Diagnostics is the one exception here, and the one with the most problems because of it.  Recently, i've seen complex changes come through to change the tagging system here, when really we should be removing almost all the specialized diagnostics tagging code in the first place.  The diagnostics tagger should be an ultra simple tagger (just like the rest of the ones we have), and it should only have to talk to a very simple 'source' API that does the right thing about aggregating and managing diagnostics for a document.   Instead, we keep making the tagger more and more complicated, which will invariably just lead to more racey bugs appearing over time.

**Comment by CyrusNajmabadi** [comment]
This tagger was changed to an entirely pull model.  I ahven't seen anything like the above since moving to that.  So closing this out for now as the system is entirely different.
