### ISSUE TITLE
Possible ArgHole missing.

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#2267]
[Source:](: https://github.com/dotnet/roslyn/blob/master/src/Tools/Source/CompilerGeneratorTools/Source/VisualBasicSyntaxGenerator/GreenNodes/GreenNodeWriter.vb#L608)

```vb
    Private Sub GenerateNodeStructureConstructorParameters(nodeStructure As ParseNodeStructure, errorParam As String, annotationParam As String, precedingTriviaParam As String, followingTriviaParam As String)
        ' Generate each of the field parameters
        _writer.Write("(kind", NodeKindType())

        _writer.Write(", {0}", errorParam)
        _writer.Write(", {0}", annotationParam)
```

**Possible Resolutions**
I think that the intent of the argument is eithet one to following two possibilities.

1)
```vb
        _writer.Write("({0}", NodeKindType())
```  
2)   
```vb
        _writer.Write("(kind, {0}", NodeKindType())
```

**Comment by pharring** [comment]
@AlekseyTs @gafter [it does look like a slip](http://source.roslyn.io/#VBSyntaxGenerator/GreenNodes/GreenNodeWriter.vb,608), but not a functional bug. VB's casing rules allow "kind" to bind successfully to [VisualBasicSyntaxNode.Kind](http://source.roslyn.io/Microsoft.CodeAnalysis.VisualBasic/Syntax/InternalSyntax/SyntaxNode.vb.html#a107f2aeab2d86fd)

I suspect the fix is to replace the line with
```vb.net
_writer.Write("(Me.Kind")
````
Similarly, [later on](http://source.roslyn.io/#VBSyntaxGenerator/GreenNodes/GreenNodeWriter.vb,615):
```vb.net
_writer.Write(", Me.Text")
````

**Comment by AdamSpeight2008** [comment]
@gafter @paulvanbrenk I'll grab that one as well, since I'm doing String-Interpolation utilisation fix ups.

**Comment by gafter** [comment]
@AdamSpeight2008 Please keep your PRs small if possible. One way is to keep separate changes in separate PRs.

**Comment by AdamSpeight2008** [comment]
Will do. Just doing a branch only for these two issue #2264 and #2267. No extras, just fixes.
