### ISSUE TITLE
git-bisect on Roslyn

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#2269]
How do I do a git-bisect on roslyn?
I would to be able to see which change I made *on my branch* is causing it not to pass. Preferably auto-magically building, then testing.

**Comment by pdelvo** [comment]
The [git docs](http://git-scm.com/docs/git-bisect) are usually a good place to get started.

**Comment by AdamSpeight2008** [comment]
It is the scripting part, to automate it.

**Comment by jmarolf** [comment]
>
Note that the script (my_script in the above example) should exit with code 0 if the current source code is good, and exit with a code between 1 and 127 (inclusive), except 125, if the current source code is bad.
Any other exit code will abort the bisect process. It should be noted that a program that terminates via "exit(-1)" leaves $? = 255, (see the exit(3) manual page), as the value is chopped with "& 0377".
The special exit code 125 should be used when the current source code cannot be tested. If the script exits with this code, the current revision will be skipped (see git bisect skip above). 125 was chosen as the highest sensible value to use for this purpose, because 126 and 127 are used by POSIX shells to signal specific error status (127 is for command not found, 126 is for command found but not executable---these details do not matter, as they are normal errors in the script, as far as "bisect run" is concerned).

So just write .cmd a script that returns 0 for success and 1 for failure and wrap a call to BuildAndTest.proj
