### ISSUE TITLE
handling program that is not syntactically correct is confusing 

### ISSUE THREAD

**Issue by keowang** [dotnet/roslyn#22755]
**Version Used**: 
2.0.0

**Steps to Reproduce**:
Given a program that does not even compile as follows:

    using System;
    using System.IO;

    namespace ModuleTwo 
    { 
        class Program
        {

            public static void Main()
            {
                bool ch     = true;

                if (ch) //Console.Write("X");
                else    Console.Write("O");            
            }
        }
    }

**Expected Behavior**:
Just throw exception or give any kind of indication the program has syntax errors and do not bother to parse

**Actual Behavior**:
Roslyn interpret that if block has a identifier

**Comment by CyrusNajmabadi** [comment]
Sorry, can you be more specific about what issue you see here?  When i try this i get two errors indicating that there is a problem:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1002	; expected	CSharpConsoleApp1	C:\Users\cyrus\source\repos\CSharpConsoleApp1\CSharpConsoleApp1\Program.cs	13	Active
Error	CS1525	Invalid expression term 'else'	CSharpConsoleApp1	C:\Users\cyrus\source\repos\CSharpConsoleApp1\CSharpConsoleApp1\Program.cs	13	Active
```

The IDE also clearly squiggles the problem point:

![image](https://user-images.githubusercontent.com/4564579/31747683-f6ace9d0-b422-11e7-8a8c-6058c5dbfccd.png)

**Comment by CyrusNajmabadi** [comment]
> Just throw exception or give any kind of indication the program has syntax errors and do not bother to parse

This sentence doesn't make much sense.  How can syntax errors be indicated if parsing doesn't happen.  Parsing has to happen to know there are syntax errors in the first place :)

**Comment by keowang** [comment]
when given a program like above. Roslyn thinks there is an identifier in the if body. what I did is (`syntaxNode` is the imaginary if body which should not exist at the first place):

    string name = syntaxNode.GetType().Name;

the value of `name` is `IdentifierNameSyntax` I wonder what's the logic here? Sure you can always parse but clearly when there is a syntax error why not just throw an exception or something to abort? 

I am not sure where is the following coming from. I do not how I can leverage it. Also I don't see how VS squiggles the code helps. Of course I know this is an syntactically invalid program. We are processing millions of programs as strings there is no VS thing involved here. What we want is when a program does not compile Roslyn flags it so we will have special mechanism to deal with it. Instead Roslyn considers it as a valid program which causes trouble down the line because simply it is not a valid program. So would you mind elaborating your answer a bit more. I do not see your point.

    Severity	Code	Description	Project	File	Line	Suppression State
    Error	CS1002	; expected	CSharpConsoleApp1	C:\Users\cyrus\source\repos\CSharpConsoleApp1\CSharpConsoleApp1\Program.cs	13	Active
    Error	CS1525	Invalid expression term 'else'	CSharpConsoleApp1	C:\Users\cyrus\source\repos\CSharpConsoleApp1

**Comment by CyrusNajmabadi** [comment]
> Sure you can always parse but clearly when there is a syntax error why not just throw an exception or something to abort?

Roslyn provides an error tolerant parser.  That's because one of the primary use cases for Roslyn is to be used *inside an IDE* (like VS).  Inside an IDE people expect to be able to use features even when code is in error (indeed, that's the *primary* state that code is in while editing).  If Roslyn were to throw an exception when the code was in error, then we would nto be able to provide features *like intellisense*.

Consider something as simple as:

```c#
class C
{
    void Foo(int )
    {
        x.   //<-- here
    }
}
```

This code is in error.  However, in order to give proper intellisense we need a real parse tree to analyze to figure out what's going on.  We need to see that we're on the right side of a member-access-expression.  We need to be able to determine what is on the left side syntactically.  We then have to figure out semantically what that thing means.  etc. etc.  All of these need a real tree to work with.

--

Now, If you want to fail in the presence of a parse error, that's totally trivial to do.  Just ask the tree if there are any parse errors in it, and throw your own exception.

**Comment by CyrusNajmabadi** [comment]
>  Also I don't see how VS squiggles the code helps.

Squiggling the code tells the user where the error is.  If we don't tell the user where the error is, then it's very hard to fix the error :)

**Comment by CyrusNajmabadi** [comment]
> What we want is when a program does not compile Roslyn flags it so we will have special mechanism to deal with it. Instead Roslyn considers it as a valid program which causes trouble down the line because simply it is not a valid program.

Roslyn does not consider it a valid program.  Roslyn produces several diagnostics to let you know exactly why the program is invalid.  You can get syntactic diagnostics that tell you what went wrong with parsing.  And if parsing was successful, you can get semantic diagnostics to tell you if there were semantic errors.  Roslyn even allows you to get semantic errors, even in the presence of syntax errors.  For example:

![image](https://user-images.githubusercontent.com/4564579/31749133-dd4df6c8-b42c-11e7-956a-00f292af8149.png)

This code is syntactically invalid, but roslyn can still give semantic errors telling me that "Console" isn't something it knows about.

**Comment by CyrusNajmabadi** [comment]
Note: Roslyn's parser is designed to *never* fail on user input.  It always produces a tree, and that tree can always roundtrip *character for character* with the original source it was fed.   As mentioned above, this is important as users may enter arbitrary text into an editor, and we can't have the parser crashing on it.

However, just because roslyn can always produce a tree does *not* mean the code is always syntactically legal.  To find out if the code is syntactically legal or not, you have several facilities at your disposal.  

First, you can just look at the ContainsDiagnostics flag on the root SyntaxNode you have for your tree.  This will tell you if this node (or any nodes transitively underneath it) have any diagnostics.  Note that this will report true for *any* diagnostics (i.e. errors *or* warnings).

We also have SyntaxNode.GetDiagnostics() which will give you all the diagnostics on or under that node.  You can use this to actually see what diagnostics were reported during parsing.  You can see which are errors/warnings/etc.

If you want to see if there are semantic issues, there are mechanisms for that as well.  I can help you figure that out if necessary.  however, right now it seems like you only care about syntax, so i'm going to wait and see if you need it.

--

Remember, Roslyn provides an error tolerant compiler intended to be used in scenarios like IDEs.  It is the *common* and *expected* state that it will be continuously fed invalid user programs.  Programs that use Roslyn expect to be able to get high quality syntactic and semantic information about those programs, even though they're invalid.  As such, Roslyn does not throw when it encounters invalid code.  Instead, it is highly resilient and produces valuable data while *also* informing the client code of what sort of issues there were so that the client can determine the best course of action.  For an IDE, or the command line, that means just displaying that information to the user in some manner.  For you, that may mean throwing/crashing.

**Comment by keowang** [comment]
Hi I really appreciate your effort to answer my question. Looks like the solution is to invoke

    syntaxNode.GetDiagnostics().ToList()

and traverse that list to check the each individual diagnostics. My question is I see a property `DefaultSeverity` assigned `Error` and another property `Severity` assigned `Error` too. So I am not sure 1)are these two properties the indicators of syntax errors, in other words, they will only be assigned to `Error` when there is a syntax error. 2) what's the difference between the two which one shall I use?

**Comment by CyrusNajmabadi** [comment]
> My question is I see a property DefaultSeverity assigned Error and another property Severity assigned Error too

Great observation!  In general, this won't matter for true syntax errors (like missing a semicolon).  These will both be 'Error'.  Where this does differ is in *warnings* (for example, the compiler warns if you use a "lower case L ```l```" in a number, as that could be confused for a ```1```).  The 'DefaultSeverity' for these will be 'Warning' (as that's what the compiler will report these as by *default*.  However, recall that the user can both elevate specific warnings to errors, as well as asking that *all* warnings be reported as error.  If the user has done this, then "DefaultSeverity" will be 'Warning' and "Severity" will be 'Error'.

Does that make sense?

**Comment by keowang** [comment]
Yes which means with no customization `DefaultSeverity` will always be` Error` for syntax error and something else for warnings right?

**Comment by CyrusNajmabadi** [comment]
> Yes which means with no customization DefaultSeverity will always beError for syntax error and something else for warnings right?

Correct.  'Error' for syntax errors, and 'Warning' for syntax warnings.

**Comment by keowang** [comment]
Thanks a lot!

**Comment by CyrusNajmabadi** [comment]
You're welcome! :)
