### ISSUE TITLE
NavigateTo on resource string should also find the RESX entry

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#22801]
Taking the Roslyn solution as an example, `NavigateTo` on [ERR_NoMetadataFile](http://source.roslyn.io/#q=ERR_NoMetadataFile) will find the error code and the resource string in generated file (`CSharpResources.Designer.cs`). But it will not find the entry in `CSharpResources.resx`, which is what you'd need to edit.

Ideally, we'd have some attribute that code generators could sprinkle in generated code to point back to the original definition. But I don't think such an attribute exists.
So I'm thinking of a solution tailored for `resgen` at least.

@sharwell @CyrusNajmabadi If you think this is worthwhile and not too complex, I'd be happy to do it, given some pointers. I'm guessing it would be something like finding the RESX files and adding their entries to an existing index.

**Comment by CyrusNajmabadi** [comment]
Are these resx files currently in the workspace at all?  If so, this is pretty simple.  If not, this is going to take a fair amount of work.

Note: i will also point out that even if you were to have this, the experience on the compiler side would still be pretty poor.  The reason for this is that it's very difficult to go from an actual user facing string to a resource string.  i.e. if we see an error in the error list like "'X' is less accessible than method 'Y'" then tracking that string back to a resource ID is very difficult.  This is unfortunate as finding that resource string then allows you to find the places where the error is reported.

A useful way to handle this (done at the IDE layers, and also in typescript), is to make a strong connection between the resource string content and the resource string name.  For example, the user visible error "Removing projects is not supported" is named, conveniently, Removing_projects_is_not_supported.   You can then nav-to easily given the user visible text:

![image](https://user-images.githubusercontent.com/4564579/31857815-10cc706c-b69c-11e7-91fc-148277256f7f.png)

**Comment by CyrusNajmabadi** [comment]
> If you think this is worthwhile and not too complex,

It's worthwhile-ish.  The weirdness would be that we'd either have to:

1. navigate to the location in the actual resx xml file.  (Odd, since users don't normally edit those files).
2. navigate to the row in the resx GUI editor.  Weird, because why would *we* be navigating to that?

The "right" solution, IMO, is that the resx system should *itself* export a Navigate-To provider.  Then, when the user searched for ERR_XXX Roslyn would find the results in C# code, while the Resx system would find it in the rexfile (and would handle navigation appropriately).    Of course, that said, there's likely 0% chance of that happening (unless you wanted to do it yourself). I can't imagine there being any investment in the resx space by anyone :-/

**Comment by CyrusNajmabadi** [comment]
Closing out.  This is on resx-editor to decide if htey want to support this scenario.  It's not on roslyn here.
