### ISSUE TITLE
Confusing error message for Span stackalloc

### ISSUE THREAD

**Issue by ufcpp** [dotnet/roslyn#22817]
**Version Used**: 

15.5 Preview 2

**Steps to Reproduce**:

Convert `stackalloc T` expression to `Span<T>`.

![image](https://user-images.githubusercontent.com/3760955/31922647-35df7a40-b8b1-11e7-8603-cca084cb4b09.png)

**Expected Behavior**:

Judging from the [test code](https://github.com/dotnet/roslyn/blob/c83671f83929da8bb0674b99f192c894da9146a0/src/Compilers/CSharp/Test/Semantic/Semantics/SpanStackSafetyTests.cs#L1279), this conversion is not allowed because I use non-ref version of `Span<T>` (in System.Memory 4.4.0-preview2-25405-01).

Error message should indicate that.

**Actual Behavior**:

The error message is:

Conversion of a stackalloc expression of type 'byte' to type 'Span<byte>' is not possible.

**Comment by jcouv** [comment]
Tagging @VSadov @OmarTawfik

**Comment by jcouv** [comment]
@VSadov for comment and triage.

**Comment by VSadov** [comment]
Yes, this is because of the use of old Span<byte> that does not have expected shape.

The newest can be obtained at:
https://dotnet.myget.org/feed/dotnet-core/package/nuget/System.Memory

4.5.0-preview1-25906-03 is the latest one

The error basically tells that Span<T> is not as we expect, but does not get into details of what exactly is wrong.

It would be unusual to see errors of this kind going forward. While bug is actionable, working on it would be of much lower priority compared to other bugs.

**Comment by jcouv** [comment]
@ufcpp Please update the package.
I'll go ahead and close the issue.

**Comment by VSadov** [comment]
Also the fix could be fairly involved. There is one place where we decide if a given type is "the special span type" or just some random type named span (which is not an error by itself).

Then there is another place that checks if conversion is possible. Since at this point  "Span" type is just a random type, the conversion is not possible and that is what reported. It would take quite an effort to detect the case where the type is "almost like span, but not really" and the report what exactly makes it to be not a span and therefore not applicable for conversions.

**Comment by Suchiman** [comment]
@VSadov 
```csharp
if (typeName == "Span" && specialType != SpecialTypes.Span)
{
    ReportDiagnostic("Conversion of stackalloc expression to Span<byte> not possible, that's not the Span<T> we were looking for");
}
```
thinking too simple? But its probably still not worth it since this shouldn't happen once `Span<T>` ships as stable

**Comment by jherby2k** [comment]
I don't get it. I get the same error, using the latest nuget package (4.5.0-preview1-26216-02). This is a netstandard2.0 project, if that matters.
