### ISSUE TITLE
Fix All for "Use Expression Body for Properties" fixes nothing

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#22900]
Fixing a single property works, but fixing all does nothing.

I invoke the lightbulb on a single property and get an expected preview. Committing this change behaves as expected too.
![image](https://user-images.githubusercontent.com/12466233/32139365-01dae98a-bbfb-11e7-9865-674251d03cdf.png)

But if I want to fix all occurrences in the document, then there is no effect.
![image](https://user-images.githubusercontent.com/12466233/32139360-f07ca5c0-bbfa-11e7-9738-d260c05d66d8.png)

FYI @jinujoseph for triage.

**Comment by jinujoseph** [comment]
@jcouv related to https://github.com/dotnet/roslyn/issues/19089 ?

**Comment by jcouv** [comment]
It may be, but the symptoms are not exactly that of #19089. 
With #19089, the problem is that fix all only fixes *one*, but the present issue is that fix all fixes *none*.

**Comment by sharwell** [comment]
@jcouv I believe you misread #19089. The bug is that .editorconfig settings are completely ignored for Fix All operations, so it will attempt to apply the Fix All operation using the current Tools &rarr; Options settings. If those settings do not have the same preference for expression-bodied properties, then the Fix All will think there is nothing to fix.

**Comment by jcouv** [comment]
Got it. Thanks for the clarification.
Closing as duplicate
