### ISSUE TITLE
Different refactoring icon shown for me in the same editor

### ISSUE THREAD

**Issue by cartermp** [dotnet/roslyn#22945]
**Version Used**: 15.5 Preview 2

![different-icons](https://user-images.githubusercontent.com/6309070/32253721-a91c3356-be59-11e7-99a0-558b6309f2da.gif)

Is this intentional?

**Comment by CyrusNajmabadi** [comment]
Yes.  You get the 'screwdriver' to indicate that there's "something you can do here just because you might want to".  You get the lightbulb to indicate "this is fixing an issue".  Specifically, in this case, the style preference seems to be "prefer block bodies for methods".  So you get a lightbulb going "you should change this to a block, since it doesn't match your style preference".  But you also get a "screwdriver" saying "well, if you do want this to be an arrow function, i'm happy to help speed that up for you".

**Comment by cartermp** [comment]
Ah, that makes sense.  Interesting that the default is to prefer block bodies for methods.  I hadn't configured this.

**Comment by CyrusNajmabadi** [comment]
Interestingly: if the style is set to 'on:none', it's arguable that perhaps it should be a screwdriver, not a lightbulb.  Tagging @kuhlenh for visibility.

**Comment by CyrusNajmabadi** [comment]
And @sharwell as well.

**Comment by sharwell** [comment]
Yes, hidden (aka none, silent) should show as a refactoring, not a fix.

Limitation here is due to the way severities are assigned to diagnostics reported by the code style analyzers.

**Comment by sharwell** [comment]
@CyrusNajmabadi I filed #23005 to get this fixed

**Comment by CyrusNajmabadi** [comment]
Thanks!
