### ISSUE TITLE
Generation of the GetHashCode method of anonymous types is not deterministic

### ISSUE THREAD

**Issue by Thealexbarney** [dotnet/roslyn#23020]
**Version Used**: 
Commit 72b8f88b0d

**Steps to Reproduce**:

1. Create the following .cs file:
```
class Program
{
    static void Main()
    {
        var a = new { a = 4 };
    }
}
```
2. Compile it with core MSBuild
3. Copy the output .dll elsewhere and compile it again
4. Alternatively, use csc and set the `deterministic` flag:
`dotnet csc.dll Program.cs /target:library /deterministic /noconfig /reference:"C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.netcore.app\2.0.0\ref\netcoreapp2.0\System.Collections.dll" /reference:"C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.netcore.app\2.0.0\ref\netcoreapp2.0\System.Runtime.dll"`

**Expected Behavior**:
The compiler should produce the exact same output both times.

**Actual Behavior**:
The compiler's output differs every time.
If the net46 csc build is used, the compiler produces the same output each time it is run.

**Reason**:
The difference comes from the GetHashCode method of the created anonymous type. Here's the IL from two separate compiles.
```
  .method public hidebysig virtual instance int32 
          GetHashCode() cil managed
  {
    // Code size       29 (0x1d)
    .maxstack  8
    IL_0000:  ldc.i4     0x1af3bd32
    IL_0005:  ldc.i4     0xa5555529
    IL_000a:  mul
```
```
.method public hidebysig virtual instance int32 
          GetHashCode() cil managed
  {
    // Code size       29 (0x1d)
    .maxstack  8
    IL_0000:  ldc.i4     0xc61810dc
    IL_0005:  ldc.i4     0xa5555529
    IL_000a:  mul
```

One of the constants used in the hash method changes every time. This is because Roslyn uses the hash codes of the backing fields of anonymous types to generate the above constant. ([Code here](https://github.com/dotnet/roslyn/blob/72b8f88b0daf42e1a8b1d6687cbfc9ccbb0cc21a/src/Compilers/CSharp/Portable/Compiler/AnonymousTypeMethodBodySynthesizer.cs#L190))

This isn't a problem in .NET Framework because [randomized string hashing](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/runtime/userandomizedstringhashalgorithm-element) is disabled by default. However, it's enabled by default in coreclr, so identical strings will give different hash codes each time the process is run, creating non-deterministic IL code.

**Comment by jcouv** [comment]
Tagging @gafter

**Comment by Joe4evr** [comment]
> However, [randomized string hashing is] enabled by default in coreclr, so identical strings will give different hash codes each time the process is run

Yes, but that's also a security measure. In light of that, should this really be changed without seeing *any* talk of security being considered?

**Comment by svick** [comment]
@Joe4evr 

First, even if randomized hash codes for anonymous types were required for security, I don't think it should cause non-deterministic builds when `/deterministic` is enabled. Instead, some approach that achieves both should be used (e.g. randomization using `new Random().Next()`).

Second, as far as I know, randomized string hash codes are used to defend against this attack:

1. The attacker provides the program with a large set of input strings with colliding hash codes.
2. The program puts the strings into a hash table, degrading its performance from O(1) to O(n) due to all the collisions, which makes this a Denial Of Service attack.

This is exactly what commonly happens with query strings in HTTP servers, which is why those should use randomized string hashing.

But to perform a similar attack here, I think the following would have to happen:

1. The attacker provides the program with a large set of input strings, which are valid C# identifiers, with colliding hash codes.
2. The program generates and compiles C# source code and uses the strings from the input to name fields of distinct anonymous types in it.
3. The program creates instances of those distinct anonymous types with the same values (or values with conflicting hash codes) and puts them into a hash table, resulting in DoS attack.

While this sequence of events could happen, I find it highly unlikely, certainly not something the Roslyn compiler should concerns itself with. Because of that, I think having hash codes for anonymous types that are not randomized is fine, there is no security issue.

Or did I miss something?

**Comment by Thealexbarney** [comment]
From what I see, the possibility of an attack at the runtime of the compiled anonymous type should be the same as it was before. The only difference would be consistent seed values for the generated `GetHashCode` method when compiled multiple times .

On the Roslyn side, the hash is computed on-demand and not cached, and the result used to generate a value that's immediately added to a `BoundExpression`, after which the hash result is disposed of. Because the hash result is not stored, I don't see any likely possibilities of a DoS type of attack.

**Comment by gafter** [comment]
I would like to thank @svick and @Thealexbarney for addressing the issue raised by @Joe4evr by talking about security 😉

**Comment by Joe4evr** [comment]
Yes, thank you. Also, I was incredibly tired when I posted that question, so it didn't occur to me *why* we want string hashes to have a random seed. 😅
