### ISSUE TITLE
PatternMatcher does not match end of string

### ISSUE THREAD

**Issue by Therzok** [dotnet/roslyn#23027]
**Version Used**: 
2.6.0

**Steps to Reproduce**:

1. Have a class named MainClass in the project
2. Use solution explorer and search for "lass"

**Expected Behavior**:
MainClass is shown

**Actual Behavior**:
No results are found

This behaviour is an improvement over the current matcher. We used to have this functionality in VS4M, but switching to the roslyn navigate to search service makes us lose these kind of results.

**Comment by sharwell** [comment]
This is currently by design (substring matches must start at a word boundary), but I'm considering was to expand this in the future. The A/B testing telemetry points to start considering changes to pattern matching behavior will go out in 15.6.

I'm hesitant to implement this directly, preferring instead to focus on the algorithm as a whole having the ability to correctly determine what the user wants to write.

**Comment by CyrusNajmabadi** [comment]
Yup. As Sam said, currently 'by design'.  We used to support arbitrary substring matches in the past, and hte number of false positives was too high.  Furthermore, when we actually discussed things with users, we found that this wasn't something that people really intentionall meant to do.  I mean... who searches for "ocument" instead of "Document" or "Doc" or "D"?  

The only times where this bit people was in words that people felt should be camelcased, but which (due to the funsies of english) were not.  For example, say someone created a method like "GetKeyword" and then searched for "word".  Here, they'd like this member to show up.  However, the vast majority of the time this does not happen.

> I'm hesitant to implement this directly, preferring instead to focus on the algorithm as a whole having the ability to correctly determine what the user wants to write.

@sharwell Would love to be kept in the loop on this. We did a lot of work over the years to both capture patterns people wanted to write, while also trying to avoid/downgrade false positives.  Fortunately, we've also tended to at least capture the former in testing (and at least some of the latter).  So if you can improve things for other patterns we think are valuable, then that would be great.  

One major concern of mine relates to memory usage. I did some investigations in the past with a lot of the current state of the art around matching.  Unfortunately, the majority of algorithms and libraries i could find were designed with the assumption that this was a server architecture, and the spell-checker algorithm had copious (i.e. GB) of memory available for it to basically be able to precompute its indices and operate on them efficiently.  These systems also tended to be good for things like common mispellings (including fascinating understandings around phonemes and fudge-fingers), but weren't good for specific directed lookups like HumpMatching.  Or they'd be really good if you could precompute data, but needing offline computation of indices, etc. etc.   So we ended up with current system which is handwritten, but gives us maximal flexibility to control disk layout and memory layout, as well as the ability to hand tweak the algorithm as necessary.

--

BTW, one thing i was investigating but had to drop, was an index that dramatically lowered the in memory cost over what we have today.  A main problem with the index today is that it actually stores names of things, in full, in memory.  i.e. for a given symbol, not only will it have the name "ThisIsTheSymbolName" stored in memory, but it will also store the full name path to it "The.Path.To.The.Symbol".  Now, for each, it tries to at least be a bit smart.  i.e. "ThisIsTheSymbolName" will use the same string provided by the compiler API, so it's only a pointer (if it has just been generated).  And "The.Path.To.The.Symbol" will be shared for all symbols in a certain container.  We're also smart when we serialize/deserialize, deduping strings at least at a Document level.

However, this is all still pretty wasteful.  Especially as we then need to do an enormous amount of work during matching to operate on those strings.  The approach i was looking into was to actually do the word breaking, but then only store words in a centralized dictionary (either at the document or project level).  So something like "ThisIsTheSymbolName" would get broken into the 5 words, and the entry for it would simply be the 5 concatted numbers representing those name indices.  This would allow a ton of sharing of common words across the corpus.  In my testing at least 80% of words were dupes in all our names.  so many things like "Token" "Provider" "Context" etc. etc. etc.  

This approach was also very amenable to caching strategies.  i.e. when doing matching, you would break the pattern into the word parts as well (which would also get indices).  You could then efficiently cache a tuple of "pattern-word, piece-word, success-bit" very compactly.  

My initial experimentation found something like 75% savings on memory *including adding in the caches*.  i.e. you saved so much in memory usage, that you could spare a few MB for improvements.

Anyways, i'm happy to dive deeper if you want to talk about this more.

**Comment by Therzok** [comment]
Closing as by-design.
