### ISSUE TITLE
Fuzzy matcher does not work with incremental pattern changes

### ISSUE THREAD

**Issue by Therzok** [dotnet/roslyn#23051]
**Version Used**: 
2.6.0-vs-for-mac-62217-03

**Steps to Reproduce**:

1. Have a class named `Test`
2. Write `Tempt` letter by letter in the search bar. `Test` is not matched
3.  Paste in `Tempt` . `Test` is matched.

**Expected Behavior**:
`Test` is matched in case 2.

**Actual Behavior**:
`Test` is not matched.

Possibly a regression in https://github.com/dotnet/roslyn/commit/47b80b58459c5c991c0fbe9b4841b495f55f3db3#commitcomment-25452007

**Comment by CyrusNajmabadi** [comment]
One option here is to break the results into fuzzy/non-fuzzy portions, and cache the results only for the non-fuzzy scan.  :-/

**Comment by slluis** [comment]
Any update on this? this bug is blocking the merge of an important branch in VS for Mac.

**Comment by CyrusNajmabadi** [comment]
I don't think anyone has even started looking at this :)  Why is this blocking a merge of a branch?  While definitely a bug, it seems not major, and something that only affects incremental matches of fuzzy searches.

**Comment by Therzok** [comment]
Well, that means we will never get results for incremental searches as typing into a searchbar _is_ an incremental search

**Comment by Therzok** [comment]
Code that breaks due to this https://github.com/mono/monodevelop/commit/9be2b153d223356457951dafe83f58ee656f949d

**Comment by slluis** [comment]
VS for Mac has a search bar that uses incremental search. We are in the process of replacing several services by what Roslyn provides. The problem is that we have to do it all at once, since otherwise we would duplicate type information in memory (for our services and for Roslyn). This bug breaks global search, which is a core feature of VS for Mac, and this is holding back the integration of several Roslyn services that have to be merged together.

**Comment by Therzok** [comment]
Specifically, AbstractNavigateToSearchService is called with filters that grow: 'p' -> 'pr' -> 'pro' -> etc. -> 'property', so that breaks us. Our searchbar uses fuzzy searching

**Comment by CyrusNajmabadi** [comment]
1. This will only break for the fuzzy searching type of matching.
2. It will only break *if* the previous fuzzy match was more restrictive than the next fuzzy match.  i.e. if you have My, and then type MyProp this will still find all of the items that My would have found.

Where this is a problem is if there is not enough 'strength' in the smaller search string to match something, but typing more gives enough weight to make the match happen.

Note: i'm not saying this shouldn't be fixed.  It should.  I'm just trying to find out why this is such a critical issue that it is blocking an integration.
--

Finally, ironically, this 'optimization' was put in after talking with someone on the VS4Mac side (i don't remember who at this point :)).  They mentioned that VS4Mac sped things up by doing this sort of results caching, and then performing the later queries against the previous results that were returned.  I'm curious how VS4Mac works around this issue themselves in your fuzzy matcher.  Can you give some details as your solution may be something we'd want to take in Roslyn.  Thanks!

**Comment by CyrusNajmabadi** [comment]
> This bug breaks global search, which is a core feature of VS for Mac, and this is holding back the integration of several Roslyn services that have to be merged together.

Why not just postpone this part.  It's going to take time for this to be fixed on the roslyn side anyways.  You could merge in all the rest of the changes, but keep yoru current search system.

**Comment by CyrusNajmabadi** [comment]
I think i've found the problem.  The issue is how the fuzzy matcher works in Roslyn.  Specifically, we have these lines of code:

https://github.com/dotnet/roslyn/blob/715aa4a630246eceda0adf4683ed22cb7be70890/src/Workspaces/Core/Portable/Utilities/SpellChecker.cs#L176-L184

The idea here is that we actually both shut off the fuzzy matching if the user has not typed enough text.  i.e.:
1.  typing 'p' should not be enough to try to fuzzy match anything, since it would match any 1-2 letter identifier.
2. For short strings, we only allow fuzzing matching up to one character.  i.e. if you type Rug, we'd match that to Bug or Run (both a single letter change, but not Bun (a two letter change).  However, if you have typed more than 4 characters, we allow up to two changes total.

--

So, in order for us to cache results, we need to likely cache things as long as the most permissive fuzzy matching algorithm happened.  From the quick glance i took at the code, it sounds like we should basically disable this optimization if the user text is less than 4 letters long.  From 4 and upwards it seems like we can still keep it.

**Comment by CyrusNajmabadi** [comment]
Hrmm.  even that won't be sufficient.  We end up bottoming out on an edit distance calculation.  That edit distance algorithm immediately terminates if it can see the cost will be more than the potential threshold we've set (either 1 or 2 edits).   i.e. Pro will never match CropDuster (since it would take 7 edits to change).  But PropDuster would match.  

Fundamentally, as long as the fuzzy match subsystem completely eliminates candidates (which we want it to do, otherwise we'd have to do so much unnecessary matching), it may have this problem.

To me, the options would be:
1. Always do the fuzzy matching against all candidates.  But mark candidates with a bit saying if they're too poor to show to the user.  This will likely make it so we have a huge set of matched results in memory (i.e. any single character will end up matching eveyrthing in the world).  This seems like a bad idea.
2. Break apart the fuzzy matching results from the non-fuzzy matched results.  The non-fuzzy matched results could be cached and filtered like we do today.  But we'd always have to do a fresh fuzzy match pass against whatever the current user text is.  Pros: best results/perf, cons: complexity.
3. Do no caching at all.  All searches are performed against the entire corbus of potential results.  Pros: correct, simple change to make.  Cons: no perf gain at all.

**Comment by Therzok** [comment]
@CyrusNajmabadi This part is integrated in one go, because we already have a cache of DeclaredSymbolInfo on our side. The incremental analyser for SyntaxTreeIndex would duplicate all that information in memory, which really takes a lot.

I was the one who suggested the optimisation. Our matcher would still match results in that case, I assumed that the roslyn matcher would too, but I made the wrong assumption.

During real-time searches, I'm not sure the searches for single characters (`a`) even get to run for at least half a second due to user typing speed. We also did not cache when the search was cancelled (triggered a new search).

**Comment by CyrusNajmabadi** [comment]
> We also did not cache when the search was cancelled (triggered a new search).

Same for us :)

> During real-time searches, I'm not sure the searches for single characters (a) even get to run for at least half a second due to user typing speed. 

We havne't felt the need for that optimization since the searches are fast, and easily cancelled.  But it's something interesting to consider.

> I was the one who suggested the optimisation.

So it's your fault! :D

> Our matcher would still match results in that case, 

Interesting.  How do you avoid the problem of a single character "matching the world" (and thus consuming tons of memory and excess CPU)?  And if it doesn't "match the world" then i don't see how your fuzzy matching wouldn't also have this issue with overfiltering.

**Comment by CyrusNajmabadi** [comment]
Anyways, it sounds like: 

> Do no caching at all. All searches are performed against the entire corbus of potential results. Pros: correct, simple change to make. Cons: no perf gain at all.

Is the way to go, at least in the short term.  @sharwell, @Pilchie @jinujoseph so this can be appropriately triaged given the integration blocking nature of the issue.

BTW, if something is integration blocking, plz let us know asap.  Otherwise, it will very likely be deprioritized against other critical work.

**Comment by Therzok** [comment]
@CyrusNajmabadi we pay the costs differently. On the initial search, we pull all the document information into memory - keeping a cache of DeclaredSymbolInfos. Then, we pay no cost of allocation for single character, since we only allocate one pattern matcher that does not allocate too much on matching/ranking.

http://source.monodevelop.com/#MonoDevelop.CSharpBinding/MonoDevelop.CSharp/ProjectSearchCategory.cs,377

**Comment by Therzok** [comment]
The bug was actually passing over string.Empty as the initial search query, causing the API to return something other than we expected.

https://github.com/mono/monodevelop/commit/bc9223a1ccfa0063edd49bfe9ae974bb2580006b#diff-36e6735f34513a7e8824fadc7c1a6c84

It's been fixed for a while.

**Comment by CyrusNajmabadi** [comment]
This shoudl probably be reactivated.  It's still an issue.
