### ISSUE TITLE
RegisterPrimarySolution called on UI thread, resulting in UI delays

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#23076]
The following operation blocks the UI thread, resulting in thousands of reported cases of UI delays averaging nearly 4 seconds.

https://github.com/dotnet/roslyn/blob/bc16b0126f340014b39eaa0482f89d74463455dc/src/VisualStudio/Core/Def/Implementation/Remote/ServiceHubRemoteHostClient.WorkspaceHost.cs#L60-L62

:link: Reported internally as [DevDiv 521503](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/521503).

**Comment by CyrusNajmabadi** [comment]
@jasonmalinowski We talked a long time back about WorkspaceHost being async. IIRC, it was an issue even before OOP because we used to use this report events for the codelens system to use (before we took ownership of that).  I seem to recall you thinking it would be very hard to do that (esp. given that so many project/solution/vs apis are synchronous and UI thread bound.  Do you remember any of your thoughts here?

**Comment by jasonmalinowski** [comment]
@CyrusNajmabadi We are already working on fixing this.

**Comment by CyrusNajmabadi** [comment]
Great!  Definitely interested in seeing what the fix will be here.

**Comment by jasonmalinowski** [comment]
This was fixed by #24700.
