### ISSUE TITLE
allow to split LeadingTrivia or TrailingTrivia off of a SyntaxNode

### ISSUE THREAD

**Issue by AdmiralSnyder** [dotnet/roslyn#23072]
**Version Used**: 
VS 2017 15.4.2
**Steps to Reproduce**:
when doing AddMembers for a ClassDeclarationSyntax where there is a closing #endregion before the closing brace, the new members are inserted into the region.

**Expected Behavior**:
the new members should be inserted directly before the closing brace of the classDeclarationSyntax

**Abstraction**:
Find a way to insert a SyntaxNode before another SyntaxNode's LeadingTrivia

**Comment by sharwell** [comment]
💭 I'm not sure I agree with the expected behavior here. Also, for code fixes that need better control over the trivia involved in the fix, it's easier to operate directly on the `SyntaxTree` instead of using one of the generator abstractions. I lean against making a change here for the following reasons:

1. The requested behavior is available through a lower-level API
2. Changing the behavior here will result in code fixes that work differently depending on which version of Roslyn the IDE is using at the time. This increases confusion for users and makes unit testing for code fixes across Roslyn versions particularly difficult.

**Comment by AdmiralSnyder** [comment]
I did not find a suitable way to solve it using the syntaxtre. I can only insertafter or insertbefore tree elements of the same kind, so there seems no way to put a syntaxnode after a trivia. Or am i missing something?

**Comment by AdmiralSnyder** [comment]
@sharwell how do you suggest i do this with SyntaxTree?

**Comment by CyrusNajmabadi** [comment]
> @sharwell how do you suggest i do this with SyntaxTree?

Speaking on behalf of Sam, the SyntaxTree is a fully representative structure that gives you the ability to make any sort of change you want.  In your case, if you have this ClassDeclarationSyntax node, then you can just grab the .CloseBraceToken off of it.  You can then fully access the trivia of that token and make whatever new structure you want.

In your case, you would grab all the leading trivia of the close brace up to and including hte directives, and you would add those trivia as leading trivia to whateer member you were adding.  You would then create a new CloseBraceToken that did not have that stripped trivia.

You would then make a new ClassDeclarationSyntax node using the original one as a starting point and calling 'Update' on it.  You'd pass the new list of members you wanted it to have, and the new CloseBraceToken.

**Comment by AdmiralSnyder** [comment]
oh, i didn't come up with that idea. and didn't find anything like this by googling. is there a roslyn faq or tutorial to write something for?
