### ISSUE TITLE
Migrate Roslyn to Editor’s PatternMatcher and delete its own copy

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#23089]

**Comment by CyrusNajmabadi** [comment]
Hey Jinu, can you clarify what thsi means?  Is this having Roslyn use a platform exposed pattern matcher?  If so, can we ensure that the latest work we did in this area was ported into the platform code. (there was a lot of optimizations that improved performance/allocations).  We shoudl also ensure that all our latest PatternMatcher tests run successfully against a platform pattern matcher.

**Comment by chborl** [comment]
@CyrusNajmabadi , working on this now.  Can you point me to the optimizations you're talking about and I'll make sure it's there.  Thanks!

**Comment by jinujoseph** [comment]
Thats right @CyrusNajmabadi , also adding @olegtk from platform side

**Comment by CyrusNajmabadi** [comment]
@chborl I would recommend just looking at my PRs that went into it for hte last year, and hte PRs that went into the platform, and just spot checking to make sure they're in the platform code.  Importantly, a lot of work went into pooling temporary objects used during matching.  These optimizations were important to keep overall allocations low during pattern matching.

Overall design goal around perf is this:
1. one to two matchers are often created.  During creation, it's ok for these matchers to allocate some amount of memory. Since there will only be a tiny number of these guys.
2. These matchers may then be run over millions of strings.  So it's *super important* to keep the actual match code extremely lean and mean, not allocating anything (that isn't pooled) unless it's because a match was found.

An unnecessary allocation during matching means *millions* of objects of garbage.  Something we want to really avoid.

**Comment by CyrusNajmabadi** [comment]
Here's the history on our side: https://github.com/dotnet/roslyn/commits/master/src/Workspaces/Core/Portable/PatternMatching

Oleg may be able to tell you at which point we were at when they forked from us.

**Comment by jinujoseph** [comment]
it’s currently blocked. This requires editor assemblies to be portable and they are not yet available.
This also needs the perf work tracked via #[533503](https://devdiv.visualstudio.com/DevDiv/NET%20Developer%20Experience%20Productivity/_workitems/edit/533503)

**Comment by olegtk** [comment]
Porting of Roslyn's PatternMatcher optimizations to the editor's fork of PatternMatcher is tracked by the editor's bug https://devdiv.visualstudio.com/DevDiv/NET%20Developer%20Experience%20Productivity/_workitems/edit/533503

**Comment by CyrusNajmabadi** [comment]
@olegtk is the editor pattern matcher exposed anywhere?

**Comment by olegtk** [comment]
Yes, it's public API: https://learn.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.text.patternmatching.ipatternmatcherfactory?view=visualstudiosdk-2022

**Comment by CyrusNajmabadi** [comment]
this wont' work.  we need our own version that can be used in layers under the VS layer, as well as for things like vscode (which have to run on mac/linux).  closing out.
