### ISSUE TITLE
Names used for error 'Source' are confusing

### ISSUE THREAD

**Issue by shyamnamboodiripad** [dotnet/roslyn#2310]
Looks like we call the source for compiler errors 'Intellisense Build'. Other errors that ship in the box have source 'MS.CA.CS.Features [Roslyn Language Services]'. This is confusing - I don't think I would be able to tell the difference between these two strings if I didn't already know what they meant :)

Also, I am not sure whether we should say 'Roslyn' here. Perhaps we should just say -

- 'C# Language Services' and 'VB Language Services' for all errors generated by IDE (i.e. IDE1234*)
- 'C# Compiler - Live Analysis' and 'VB Compiler - Live Analysis' for all errors generated by compiler (i.e. CS1234*)
- And a consistent sounding name ('C# Compiler - Build' and 'VB Compiler - Build') for errors that come from command-line build (I couldn't get one of those to show up below when I was experimenting)

![capture](https://cloud.githubusercontent.com/assets/10579684/7359629/619a5ab8-ecf5-11e4-91d0-9fd240feb691.PNG)

**Comment by srivatsn** [comment]
Is Roslyn coming from the name of the VSIX?

**Comment by heejaechang** [comment]
@srivatsn @shyamnamboodiripad for "IntelliSense Build", I have no preference. used it because it is what other team uses for live errors. and what platform names "live" errors in their API. actually it is only us who calls these kind errors live errors.

for [Roslyn Language Services], it is name of Vsix that generates the errors. we could special case our vsixes (I meant in box roslyn vsix not, install dogfooded vsix). or we could change name of our in box vsix.

**Comment by heejaechang** [comment]
@shyamnamboodiripad @srivatsn so what should we do?

**Comment by shyamnamboodiripad** [comment]
@heejaechang I have indicated my preferences above. @srivatsn thoughts?

**Comment by srivatsn** [comment]
Fixed by #2879

**Comment by natidea** [comment]
The rules list 'Intellisense' as the source
