### ISSUE TITLE
method param ExplicitDefaultValue returns null for negative integer default values

### ISSUE THREAD

**Issue by vvuk** [dotnet/roslyn#23127]
**Version Used**: 2.4.0

**Steps to Reproduce**:

Compile and run this code:

```
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace rtest
{
    internal class Program
    {
        public static void Main(string[] args)
        {
            SyntaxTree tree = CSharpSyntaxTree.ParseText(
@"
using System;
namespace TestNamespace
{
    abstract class TestClass
    {
        public abstract void someMethodA(int a, int b = 42);
        public abstract void someMethodB(int a, int b = -1);
        public abstract void someMethodC(int a, string x = ""hello"");
    }
}
");
            var trees = new List<SyntaxTree>() {tree};
            var compilation = CSharpCompilation.Create("test", trees);
            var model = compilation.GetSemanticModel(tree);

            foreach (var type in tree.GetRoot().DescendantNodes()
                .OfType<MethodDeclarationSyntax>())
            {
                var m = model.GetDeclaredSymbol(type) as IMethodSymbol;
                Console.WriteLine($"Method {m.Name}");
                foreach (var p in m.Parameters)
                {
                    Console.WriteLine($"param {p.Name} type {p.Type}");
                    if (p.HasExplicitDefaultValue)
                    {
                        Console.WriteLine($"   default value '{p.ExplicitDefaultValue}'");
                    }
                }
            }
        }
    }
}
```

The resulting output should have "-1" as the default value for param `b` of `someMethodB`.  Instead, it's null:

```
Method someMethodA
param a type int
param b type int
   default value '42'
Method someMethodB
param a type int
param b type int
   default value ''
Method someMethodC
param a type int
param x type string
   default value 'hello'
```

Any negative value becomes null; values >= 0 work fine.

**Comment by AdamSpeight2008** [comment]
There are only positive literals, the negative is an operator.

**Comment by svick** [comment]
@AdamSpeight2008 At the semantic layer, the syntax used shouldn't matter. The parameter has a default value, so `IParameterSymbol.ExplicitDefaultValue` should return the default value.

---

The problem here is that the compilation does not include a reference to required basic types. If you look at the diagnostics of the compilation, you will get:

> (2,7): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
(5,20): error CS0518: Predefined type 'System.Object' is not defined or imported
(7,42): error CS0518: Predefined type 'System.Int32' is not defined or imported
(7,49): error CS0518: Predefined type 'System.Int32' is not defined or imported
(7,25): error CS0518: Predefined type 'System.Void' is not defined or imported
(8,42): error CS0518: Predefined type 'System.Int32' is not defined or imported
(8,49): error CS0518: Predefined type 'System.Int32' is not defined or imported
(8,25): error CS0518: Predefined type 'System.Void' is not defined or imported
(9,42): error CS0518: Predefined type 'System.Int32' is not defined or imported
(9,49): error CS0518: Predefined type 'System.String' is not defined or imported
(9,25): error CS0518: Predefined type 'System.Void' is not defined or imported
(7,57): error CS0518: Predefined type 'System.Int32' is not defined or imported
(8,58): error CS0518: Predefined type 'System.Int32' is not defined or imported
(8,57): error CS0518: Predefined type 'System.Object' is not defined or imported
(8,53): error CS1750: A value of type 'object' cannot be used as a default parameter because there are no standard conversions to type 'int'
(9,60): error CS0518: Predefined type 'System.String' is not defined or imported
(5,20): error CS1729: 'object' does not contain a constructor that takes 0 arguments
error CS5001: Program does not contain a static 'Main' method suitable for an entry point

I think the CS1750 error is the culprit here, though I'm not sure what exactly causes it. 

But if you include a reference to `mscorlib` in the compilation, it starts working: most of the errors are gone and the output becomes:

```
Method someMethodA
param a type int
param b type int
   default value '42'
Method someMethodB
param a type int
param b type int
   default value '-1'
Method someMethodC
param a type int
param x type string
   default value 'hello'
```

I don't think there is actually a bug here: without a reference to `mscorlib`, the semantic layer is not going to work.

**Comment by AdamSpeight2008** [comment]
@svick It has to be something to do with `IParameterSymbol` has been implement on some node.
```c#
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace rtest
{
    internal class Program
    {
        public static void Main(string[] args)
        {
            SyntaxTree tree = CSharpSyntaxTree.ParseText(
@"
using System;
namespace TestNamespace
{
    abstract class TestClass
    {
        public abstract void someMethodA(int a, int b = 42);
        public abstract void someMethodB(int a, int b = -1);
        public abstract void someMethodC(int a, string x = ""hello"");
    }
}
");
            var trees = new List<SyntaxTree>() { tree };
            var compilation = CSharpCompilation.Create("test", trees);
            var model = compilation.GetSemanticModel(tree);

            foreach (var type in tree.GetRoot().DescendantNodes()
                .OfType<MethodDeclarationSyntax>())
            {
                //var m = type. model.GetDeclaredSymbol(type) as IMethodSymbol;
                Console.WriteLine($"Method {type.Identifier}");
                foreach (var p in type.ParameterList.Parameters)
                {
                    Console.WriteLine($"param {p.Identifier} type {p.Type}");
                    if (p.Default != null)
                    {
                        var cv = p.Default;
                        var value = cv.Value;
                        Console.WriteLine($"   default value '{value}'");
                    }
                }
            }
            Console.ReadKey();
        }
    }
}
```
Works as expected.

**Comment by jcouv** [comment]
I walked through this and the present logic in `BindUnaryOperatorCore` makes sense. The observed behavior is reasonable.

Binding `-1` means binding an unary operator on an expression with an error type. Without `System.Int32`, `1` is an error.
To avoid producing cascading errors (cannot bind the unary operator onto an expression with errors), the binding for `-1` is cut short. So the computation of constant value is also cut short.

I'll go ahead and close the issue. Thanks
