### ISSUE TITLE
Visual Basic methods with nested type constraints can't be used as extension methods

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#23124]
Are extension methods more than just &quot;syntactic sugar&quot;?

Sub exampleMethod(Of T, TList As IList(Of T))(list As TList)
End Sub

compiles just fine.

&lt;Extension&gt;
Sub exampleMethod(Of T, TList As IList(Of T))(list As TList)
End Sub

results in

Extension method 'exampleMethod' has type constraints that can never be satisfied

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/75334/visual-basic-methods-with-nested-type-constraints.html
VSTS ticketId: 459141_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by agocke** [comment]
@AnthonyDGreen Can you take a look at this and tell me if I'm missing something? I can't see why there would be unsatisfiable type constraints.

**Comment by AnthonyDGreen** [comment]
This is a common confusion. Because of VB extension method type parameter reduction. In VB type inference fixes any type arguments on which the first parameter depends such that you can't specify them explicitly. That is to say, once we infer the type of the receiver, no arguments are permitted to change it. When you call that method on, say... `Integer`. `TList` is inferred to be Integer. At that point the signature of the reduced extension method is `exampleMethod(Of T)(list As Integer)`. You can't then go back and specify a `T` that changes what type `TList` had; ergo it has constraints that can never be satisfied.

In C# you don't get this problem because the extension methods aren't reduced. The consequence on the C# side then is that all type arguments must be specified or none of them specified. Take this example:

``` C#
static void Main(string[] args)
{
    var list = new List<string>();
    // Inference fails; doesn't compile.
    list.M();
    // No inference; compiles.
    list.M<object, IEnumerable<object>>();
}

static void M<T, TList>(this TList list) where TList : IEnumerable<T> { }
```

The first line doesn't compile because the compiler can't find an extension method on `List<string>`. It doesn't attempt to re-interpret `TList` as `IEnumerable<string>`. In the second line you explicitly force the type of `TList` to be `IEnumerable<object>` so it can find the extension method. But you still have to specify all arguments even though knowing the type of `TList` _usually_ would imply the type of `T`. I use `IEnumerable<T>` in this example because its variance demonstrates how the inference of `TList` would actually be ambiguous but even without variance nothing stops a type from implementing a generic interface multiple times with different type arguments so the problem would still be there.

Here's an example of the benefit of VBs approach, a sort of "partial type-argument-inference":

``` C#
static void Main(string[] args)
{
    var list = new List<string>();
    // Error! M requires two type-arguments.
    list.M<int>();
}

static void M<T, S>(this IEnumerable<T> list) { }
```

Here an error is reported in C# because the compiler can't infer type-argument `S` and so requires the user to specify both `T` and `S`. Whereas in VB the equivalent code compiles because once type argument inference infers `T` to be `String` it removes that type argument from the equation entirely, producing a new _reduced_ extension method that only has one type argument, `S`.

There are trade-offs of to either approach both for developers, for the compiler itself, for tooling, and the two design teams weighted those trade-offs differently all those years ago. So for this rare case you need to call the extension method like an ordinary `Shared` method or, if possible, change your method definition to break the dependency:

``` VB.NET
<Extension>
Sub M(Of T)(list As IList(Of T))
```
