### ISSUE TITLE
Intellisense suggestion (null check can be simplified) causes incorrect code flow

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#23147]
See code example beflow. The exceptions being (conditionally) thrown are reversed when applying the intellisense suggestion (null check can be simplified).

ORIGINAL CODE
------------------
``` c#
public class Test
{
    private static int? _x;

    private static int? X
    {
        get { return _x; }
        set
        {
            if (value == null)
            {
                throw new Exception("X cannot be updated with value null.");
            }

            if (_x == 1)
            {
                throw new Exception("X cannot be updated when having value 1.");
            }

            _x = value;
        }
    }
}
```

CODE AFTER APPLYING INTELLISENSE SUGGESTION
---------------------------------------------------------
``` c#
public class Test
{
    private static int? _x;

    private static int? X
    {
        get { return _x; }
        set
        {
                if (_x == 1)
            {
                throw new Exception("X cannot be updated when having value 1.");
            }

            _x = value ?? throw new Exception("X cannot be updated with value null.");
        }
    }
}
```

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/148399/intellisense-suggestion-null-check-can-be-simplifi.html
VSTS ticketId: 523373_
_These are the original issue comments:_

Stephan Smetsers on 11/10/2017, 07:27 AM (3 days ago): please ignore the \\{  was caused by copy-paste.... but you smart guys get the picture :-)
_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment]
This is a known 'by design' approach to this feature.  This is a suggestion, allowing you to know a potential simplification.  It does not verify that there will be absolutely no change in semantics.  Indeed, for it to guarantee that, it would effectively be unable to be offered in nearly all the cases it is offered today.

If the potential for semantic change is not acceptable to you, i would recommend disabling the recommendation. This can be done here:

![image](https://user-images.githubusercontent.com/4564579/32745326-3e6b57d6-c867-11e7-9b30-8bcd8417fa75.png)

![image](https://user-images.githubusercontent.com/4564579/32745350-4d045c2a-c867-11e7-8a68-a81c8848eb6b.png)

Tagging @kuhlenh for visibility
