### ISSUE TITLE
Expression-Bodied Throw Statements still use IExpressionStatementOperation

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#23152]
In non-expression-bodied contexts, we don't have IExpressionStatementOperations wrapping IThrowOperations. We do for expression-bodied members however.

```C#
void M()
{
    throw new NotImplementedException();
}
```
Produces
```
IBlockOperation
    Operations:
        IThrowOperation
```

```C#
void M() => throw new NotImplementedException();
```
Produces
```
IBlockOperation
    Operations
        IExpressionStatement
            Operation
                IThrowOperation
```

FYI @AlekseyTs.

**Comment by AlekseyTs** [comment]
@333fred What is the syntax for the ```throw new NotImplementedException()```? If it is an expression, the the shape of the tree looks expected to me.

**Comment by 333fred** [comment]
It is an expression, but I'm thinking that we should fix up the tree here to be a single IThrowOperation in all scenarios. I ran into this when implementing https://github.com/dotnet/roslyn-analyzers/pull/1353, these two things feel like they should be identical from an IOperation perspective.

**Comment by 333fred** [comment]
Also tagging @dotnet/analyzer-ioperation.

**Comment by AlekseyTs** [comment]
We will not be able to get rid of throw expressions completely. Whatever analyzer you are writing, you should be prepared to deal with them and then, I believe, it wouldn't make much difference.

**Comment by mavasani** [comment]
I agree with @333fred that the trees should be identical for both cases mentioned above. Is there a specific reason we have an IExpressionStatementOperation for expression bodied member case but not for regular method body case?

**Comment by AlekseyTs** [comment]
Statements are mapped to statements, expressions are mapped to expressions.

**Comment by bkoelman** [comment]
I noticed that the span for `IExpressionStatement` in the example described does **not** include the trailing `;`. This seems inconsistent with other expression statements that I have seen, which do include the ending semicolon.

**Comment by bkoelman** [comment]
So operations should not expose whether they are statements or expressions because operations are semantic. We (analyzer authors) should not depend on the underlying syntax (or language) too much because it is a different level of abstraction. Or whether the user actually typed the code or that the compiler generated it. Because at this abstraction level such information becomes less irrelevant. 

Yet the operation trees look different, depending on whether it is a statement or expression notation. So we need to write unit tests for all possible syntax forms to ensure implementation works for all of them, and special-case in analyzer code to compensate for inconsistencies in the operation tree. Which leads to [language-agnostic brittle code](https://github.com/dotnet/roslyn-analyzers/blob/17ca5292e32d3463b9e0893d20e1d1f61424da01/src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/ReviewUnusedParameters.cs#L247-L277) in analyzers that is waiting to break in vNext when the tree shape changes for some internal reason. And it will, because we [do not even want to document](https://github.com/dotnet/roslyn/issues/24938#issuecomment-399602307) unusual tree shapes.

How can this be closed as by-design? I am totally lost here.

**Comment by CyrusNajmabadi** [comment]
> We (analyzer authors) should not depend on the underlying syntax (or language) too much because it is a different level of abstraction.

@bkoelman Who said that? :)

I would say it's the opposite.  If you need the actual language-level detail (i.e. syntax), go to the language.
