### ISSUE TITLE
Investigate removing Imaging dependency from EditorFeatures.dll

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#23189]
We currently don't have MS.VS.Imaging.dll and MS.VS.ImageCatalog.dll on VSMac as they don't make any sense in the Mac world.

We see four usages of ImageMonikers by EditorFeatures:
```
Microsoft.CodeAnalysis.EditorFeatures, Version=2.6.0.0
    Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.IconMoniker:ImageMoniker
    Microsoft.CodeAnalysis.Editor.Shared.Extensions.GlyphExtensions.GetImageMoniker(this Glyph glyph):ImageMoniker
    Microsoft.CodeAnalysis.Editor.Tags.DefaultImageMonikerService.TryGetImageMoniker(ImmutableArray<string> tags, out ImageMoniker imageMoniker):bool
    Microsoft.CodeAnalysis.Editor.Tags.IImageMonikerService.TryGetImageMoniker(ImmutableArray<string> tags, out ImageMoniker imageMoniker):bool


```

If it is feasible, we should refactor these out to EditorFeatures.Wpf.dll.

**Comment by AmadeusW** [comment]
* Microsoft.VisualStudio.Imaging is indeed platform specific. 
* ImageCatalog might be useful because it maps user-friendly names to monikers.
* Microsoft.VisualStudio.Imaging.Interop itself is a fairly minimal assembly that can be embedded. 

![image](https://user-images.githubusercontent.com/1673956/32856813-c2908ede-c9fa-11e7-89e1-8e100def47bd.png)

@KirillOsenkov does mono support embedding interop types?

The only issue I found with Imaging.Interop is that it breaks the CLS compliance requirement. In best case scenario this can be fixed with an assembly attribute

We really need to flesh out our cross platform imaging story first. I'll talk to Andrew Sarratori and see what are their plans for xplat images.

**Comment by AmadeusW** [comment]
We could platformize the image catalog, such that all (xplat) language services can use user-friendly names for images (just like KnownMonikers) but internally we would use our own implementation of ImageMoniker. 

Using our own ImageMoniker wouldn't be anything new -i t turns out that the imaging library also uses their own ImageMoniker which is different than the COM-compatible ImageMoniker.

However, this approach would mean that VS:mac would receive guid:id pairs. What would be the best way to consume images in both VS:mac and VS:win in the most performant way?

Can we make our ImageMoniker to have `guid` and `int` for windows client and `string` for mac client? Or just a string that each client translates into internal representation of their image catalogs?

**Comment by KirillOsenkov** [comment]
Let's have that discussion in an appropriate forum with all stakeholders involved. Great idea about properly solving our strategy there.

**Comment by jasonmalinowski** [comment]
So I can pull out ImageCatalog at least, unfortunately ImageMoniker is exposed as a public type out of EditorFeatures:

https://github.com/dotnet/roslyn/blob/master/src/EditorFeatures/Core/Tags/IImageMonikerService.cs

So I can't do much about that right now.

**Comment by KirillOsenkov** [comment]
Ouch, if this is a public API then yeah, it's problematic. In the future we can think about embedding the interop type, not sure if it would be a breaking change.

For now, just removing ImageCatalog would be nice, if possible.
