### ISSUE TITLE
Making DeclaringSyntaxReferences a DeclaringSyntaxReference

### ISSUE THREAD

**Issue by roterdam** [dotnet/roslyn#2318]
Why is DeclaringSyntaxReferences an array of declaration references, could there be more than one declaration syntax reference?

Maybe for partial classes and methods? But why are they declaring references?

**Comment by CyrusNajmabadi** [comment]
>could there be more than one declaration syntax reference?
Yes.  As you guessed, this happens when you have merged declarations that form one symbol.  Examples of this include partial classes, methods, and namespaces.

> But why are they declaring references

The way to read this is "Declaring" + "SyntaxReferences".  They are 'Declaring' in that they are the actual pieces of code that cause the Symbol to be 'Declared'.  And they are 'SyntaxReferences' in that they are a 'Reference to Syntax Element' as opposed to an actual ```SyntaxNode``` itself.  The reason for being a 'Reference to a Syntax Element' is so that they don't actually keep the entire SyntaxTree around.  Instead, they represent a way to *get back to* the syntax element if necessary.
