### ISSUE TITLE
Investigate possible Solution rooting in AbstractDocumentSpanEntry

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#23187]
**Version Used**: 15.4

🔗 [Visual Studio 2017 Constant Crashing](https://developercommunity.visualstudio.com/content/problem/120273/visual-studio-2017-constant-crashing.html) ([Internal feedback ticket](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/500336))

**Steps to Reproduce**:

⚠️ The following is speculation; the situation has proven difficult to pinpoint.

1. Use **Find All References**
1. Press **🔒 Keep Results**
1. Edit a document? (Force the creation of a new `Solution` which differs from the one used in the first step.)
1. Use **Find All References**

**Expected Behavior**:

The two Find All References windows do not hold strong references to two different `Solution` objects. Ideally the windows do not hold strong references to _any_ `Solution` objects.

**Actual Behavior**:

It appears the two windows hold references to `Solution` objects via the following field. It is unclear if/when the references become eligible for garbage collection.

https://github.com/dotnet/roslyn/blob/a604cefecd2cba10803a872c580cfb7a9e0883ad/src/VisualStudio/Core/Def/Implementation/FindReferences/Entries/AbstractDocumentSpanEntry.cs#L26

**Comment by sharwell** [comment]
@CyrusNajmabadi You've done work to eliminate situations like this in the past. Would you like to look at this one?

**Comment by CyrusNajmabadi** [comment]
This is currently by design afaict.  So that we can show things like tooltips for the entries in FAR.  Also, the FAR list is virtualized.  So data is retrieved on demand.  If we don't store the snapshot, we risk someone making an edit, then scrolling the list, and then seeing incorrect data shown.

These are all "solvable" issues.  But are non-trivial and would need a fair amount of work to implement and validate an acceptable experience for.

**Comment by CyrusNajmabadi** [comment]
Actually, i might be wrong about the on-demand data.  I think due to the OOP work, we actually precompute the data we'll need for presenting the FAR rows (not counting the tooltip).  The tooltip could likely just try to retrieve whatever data was current, accepting that it might not be there (i.e. if the file was edited to the point that the loc doesn't exist), or that it might be incorrect (i.e. it points at a position in the file that isn't where the reference actually is).

**Comment by sharwell** [comment]
> I think due to the OOP work, we actually precompute the data we'll need for presenting the FAR rows (not counting the tooltip).

If this is true, we could probably get away with not holding the solution reference. For the case I was looking at, this could result in a substantial reduction in memory load.

**Comment by sharwell** [comment]
@CyrusNajmabadi Is there a way to hold a document independently of the solution? That way we have the document content from the time of the search but not the entire solution containing it.

**Comment by CyrusNajmabadi** [comment]
Well, one could always hold onto the sourcetext.  Then, you could do something like this:

1. Store SourceText and DocId.
2. Get Workspace.CurrentSolution.
3. Get the current document for that DocId.  (or add the document if it's not there anymore).
4. Replace it's text with the text that was captured.

Then, create the preview workspace using that forked solution.  

The only cost then is how many unique source-texts are kept rooted, and prevented from being GCed.

Now, keeping a sourcetext around for an open doc is pretty cheap (since it's going to share so much data, even as the doc is edited).  I'm not sure how efficient sourcetexts are for closed docs.  If we have a nice cheap representation that just is a pointer to the mmf, then i think this would overall be very cheap.

Let me know what you think.

**Comment by CyrusNajmabadi** [comment]
Note: if we did the above, then the tooltip would always show the correct text, though the highlighting might be incorrect.  But that's totally ok IMO.  In most cases things would look great and users would be none the wiser.  If users really did dramatically cahnge their code (i.e. changing the type system), they might be able to observe some small differences, but i doubt anyone would notice or care.

**Comment by sharwell** [comment]
@CyrusNajmabadi Thanks for the feedback here! I think the approach is solid and I'll look into an efficient representation option for closed files.

**Comment by CyrusNajmabadi** [comment]
Tnx!

**Comment by sharwell** [comment]
Solution rooting was eliminated as part of #30733
