### ISSUE TITLE
Disable IDE0032 until it works

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#23217]
**Version Used**: 15.5 Preview 3

🔗 Observed while investigating [this community report](https://developercommunity.visualstudio.com/content/problem/150002/ide0032-performs-less-than-ideal.html).

**Steps to Reproduce**:

1. Attempt to use the Use Auto Property diagnostic and code fix

**Expected Behavior**:

1. Code does not break
2. The code fix works
3. The fix all operation either work or is not provided

**Actual Behavior**:

I was unable to use this feature in any context and have it provide a meaningful result.

* The feature was not even visible without enabling a non-default (and not recommended) feature (#23215, #17857)
* The code was broken when the feature was used (#20855)
* The code fix didn't perform as expected (#23216)

This diagnostic needs to be disabled until it meets a reasonable quality bar.

**Comment by CyrusNajmabadi** [comment]
I use this feature.  :-/  I was even showing someone this feature today as being useful for their own work.

> The feature was not even visible without enabling a non-default (and not recommended) feature 

Sure.  But if you enable that other feature, then this feature does work, and is useful.

> The code was broken when the feature was used (#20855)

This makes it sound as if the feature does not work.  That's not the case.  It sounds like there may be an issue improving how it works with certain type of trivia.  But that's the case for many of our features, and is not a sufficient reason to just turn hte feature off.

> This diagnostic needs to be disabled until it meets a reasonable quality bar.

I disagree.  I think the quality of it is actually ok.  It has a lot of tests already here: https://github.com/dotnet/roslyn/blob/master/src/EditorFeatures/CSharpTest/Diagnostics/UseAutoProperty/UseAutoPropertyTests.cs

It seems like there is an issue with trivia in this case that was missed.  We could just fix that.

--

As for hte fix-all behavior, we could just not offer fix all on this guy.

**Comment by CyrusNajmabadi** [comment]
Note: the issue reported by andrew seems to be something new related to shared projects.  The analyzer/fix runs on a document, but something higher up the stack seems to be upset about hte change made to only that document.  It's unclear to me why this isn't an issue with more fixers that just fixup a single document that happens to be in a shared location.

Regardless, if we were to disable (instead of just fixing the issue), i would only want to disable in teh shared-project case, not in the general case.

**Comment by CyrusNajmabadi** [comment]
Note: i'm a little dismayed to see we're not considering just doing the work necessary to make this appear normally.  We had many discussions with the analyzer team about these sorts of features being very valuable and wanting to make them possible.  Did nothing viable come of that?

**Comment by sharwell** [comment]
@CyrusNajmabadi Disabling the analyzer is only an interim solution. I'm comfortable with it as an interim solution since it's not visible to many users under normal scenarios. Long-term I would love for this to work, however I would place both the .editorconfig work and the analyzer performance validation scenarios above it in priority.

> It sounds like there may be an issue improving how it works when in a shared project, but the common case works fine.

For analyzers that ship in the box, I would expect a near "bug bounty" level of difficulty in finding problems with them. Sure we don't always hit that, but in this case we are very far from it and need to course-correct it.

**Comment by CyrusNajmabadi** [comment]
Note: i'm working on making this no longer a compilation-end-action

**Comment by CyrusNajmabadi** [comment]
I've addressed several of the problems here: https://github.com/dotnet/roslyn/pull/23237

**Comment by CyrusNajmabadi** [comment]
> Sure we don't always hit that, but in this case we are very far from it and need to course-correct.

I don't know how you're coming to that assessment.  Linked files have never been an area with a lot of attention.  Practically none of our analyzers have any tests for that particular case.  Up till now, they've all just assumed that they could make changes to the solution and anything realted to linked-files would be hidden from them.  I don't see why encountering a single issue here with that scenario warrants disabling this feature instead of just figuring out what went wrong in tihs case and addressing it.
