### ISSUE TITLE
Inconsistency in getters that just throw

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#23263]
```C#
int Foo
{
    get { throw new Exception(); }
}
```
```
IBlockOperation
    IThrowOperation
```
```C#
int Foo
{
    get => throw new Foo();
}
```
```
IBlockOperation
    IReturnOperation (IsImplicit)
        IConversionOperation (IsImplicit)
            IThrowOperation
```

These two need to be unified. @dotnet/analyzer-ioperation @AlekseyTs.

**Comment by AlekseyTs** [comment]
> These two need to be unified.

I disagree. Statements should be mapped to statements and expressions should be mapped to expressions.

However, an IExpressionStaement is probably better than a IReturnOperation for an expression bodied case.

**Comment by mavasani** [comment]
Tagging @AnthonyDGreen 

A related issue with similar differences: https://github.com/dotnet/roslyn/issues/23152.
I tend to agree with Fred in both these issues. Both of these are identical semantically, but we have different operation trees, primarily to enable users to map distinct syntax nodes to distinct operations. I really wish we supported different modes for GetOperation where in:
1. Mode 1: we provide operation tree with close mapping to syntax (distinct syntax nodes to distinct operations).
2. Mode 2: we still provide a reasonably high level operation tree but things that differ purely syntactically lead to identical operation trees (this is what @AnthonyDGreen has mentioned in past).
3. Mode 3: lowered operation tree where everything is jumps and conditional branches and simple operations.

**Comment by AlekseyTs** [comment]
> Both of these are identical semantically

Yes, both of them have equivalent run-time result. However, it is not a goal of the current API to provide some kind of unified canonical view on programs written by using different language constructs. The goal is to expose semantics, i.e. the meaning of programs.

**Comment by mavasani** [comment]
> it is not a goal of the current API to provide some kind of unified canonical view on programs 

I agree that we finalized this as the goal of the current API and tree shape and from that viewpoint your stance is correct. I am also not arguing about usefulness of current GetOperation API semantics and tree shapes, these are useful for anyone interested in mapping syntax to semantics and reasoning about it. However, from the view of an analyzer author, I think mode 2 is more useful as I don't need to handle all different tree shapes for semantically identical code and leads to simpler analyzer code.

**Comment by bkoelman** [comment]
So operations should not expose whether they are statements or expressions because operations are semantic. We (analyzer authors) should not depend on the underlying syntax (or language) too much because it is a different level of abstraction. Or whether the user actually typed the code or that the compiler generated it. Because at this abstraction level such information becomes less irrelevant. 

Yet the operation trees look different, depending on whether it is a statement or expression notation. So we need to write unit tests for all possible syntax forms to ensure implementation works for all of them, and special-case in analyzer code to compensate for inconsistencies in the operation tree. Which leads to [language-agnostic brittle code](https://github.com/dotnet/roslyn-analyzers/blob/17ca5292e32d3463b9e0893d20e1d1f61424da01/src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/ReviewUnusedParameters.cs#L247-L277) in analyzers that is waiting to break in vNext when the tree shape changes for some internal reason. And it will, because we [do not even want to document](https://github.com/dotnet/roslyn/issues/24938#issuecomment-399602307) unusual tree shapes.

How can this be closed as by-design? I am totally lost here.
