### ISSUE TITLE
Show captures when hovering over local functions and lambda arrow

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#23307]
Since capture lists are rejected as a language feature I think the next logical step is an IDE feature.

**Comment by CyrusNajmabadi** [comment]
This is a great idea.  Paging @jcouv as he seems to love exposing compiler innards in the IDE.

**Comment by jcouv** [comment]
I love the idea.
@CyrusNajmabadi I don't know how to do those kinds of popups yet. Do you think this would be an extension of QuickInfo, or a new kind of popup?

**Comment by CyrusNajmabadi** [comment]
It would be an extension of quickinfo.  Basically, i think you'd want to modify "ISymbolDisplayService" to support adding this information for the symbol display for a local function or lambda.

Note: this should be easy for local functions, but a little more work will need to be done for lambdas.  that's because AbstractSemanticQuickInfoProvider.BindTokenAsync probably doesn't even work on a => for a lambda.  We'd need to make that work (as well as work for sub/function lambdas in VB).

Nothing about this is very hard.  But it just means touching up a few places.

**Comment by alrz** [comment]
It would nice if we give visual clue if a local function/lambda is capturing anything at all. Heap allocation viewer extension underlines function name/lambda arrow if there is a closure..

Further, this could go hand in hand with https://github.com/dotnet/roslyn/issues/3976 if we also make capture variable distinguishable with a different coloring (bringing this up since it's been three years and it's still open..)

**Comment by CyrusNajmabadi** [comment]
I would add that request to #3976.  Thanks!

**Comment by jcouv** [comment]
I have a PR in progress (https://github.com/dotnet/roslyn/pull/23970) to list captured variables in QuickInfo.

**Comment by sharwell** [comment]
@kuhlenh can we get a design meeting early in January for Quick Info extensions?

**Comment by jcouv** [comment]
Pushed this to 15.7 because underlying compiler API doesn't exist in 15.6 (we just added it to our 15.7 branch, features/compiler).

**Comment by jcouv** [comment]
Feature is merged. Targeting 15.7.
