### ISSUE TITLE
Pattern variable scope doesn't leak out of else if

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#23379]
Is this by design?
```cs
void M(bool o) {
    if (o)
    {
    }
    else if (o is var var)
    {
      return;
    }  
    else var = true; // Remove `else` and this no longer compiles
}
```
Intuitively, `else` here should be insignificant since `if` body's endpoint is unreachable.

Another example:
```cs
void M(bool o) {
    if (o)
    {
        var var = 0;
        return;
    }
    else if (o is var var)
    {
    } 
}
```
IMO the presence of `else` shouldn't affect scope of variables.

**Comment by alrz** [comment]
Imagine an IDE feature for removing redundant `else` keywords, this is a painful edge case to handle.

/cc @controlflow

**Comment by jcouv** [comment]
I think that's by design. 

See option 3 (which was picked) in notes: https://github.com/dotnet/csharplang/blob/master/meetings/2016/LDM-2016-07-15.md
In summary is that expression variables are scoped to the nearest enclosing statement or embedded statement. 


Tagging @gafter @AlekseyTs Do we have any documentation for latest **state** of scopes? It seems like we have many deltas documented.

For instance, the notes on scope in https://github.com/dotnet/roslyn/blob/master/docs/features/patterns.md#scope-of-pattern-variables seem out-of-date.

**Comment by alrz** [comment]
I see, so I think this is the consequence of these two rules

1. variables in `if` condition *only* spill to the `else` block (example 1)
2. every embedded-statement maintains its own scope (example 2)

(1) is desirable but (2) could be more specific. Ideally, non-block embedded-statements should have shared their scope with their parents, then the first example would work with or without `else` and the second example would be an error either way.

**Comment by CyrusNajmabadi** [comment]
```c#
void M(bool o) {
    if (o)
    {
    }
    else if (o is var var)
    {
      return;
    }  
    else var = true; // Remove `else` and this no longer compiles
}
```

is equivalent to:

```c#
void M(bool o) {
    if (o)
    {
    }
    else 
    {
        if (o is var var)
        {
            return;
        }  
        else { var = true; } // Remove `else` and this no longer compiles
    }
}
```

So 'var' is in scope.  But when you remove the final else, you transform it to:

```c#
void M(bool o) {
    if (o)
    {
    }
    else 
    {
        if (o is var var)
        {
            return;
        }  
    }

    var = true;
}
```

And, of course, it isn't.

It was a very intentional decision by the LDM that scoping behave in a consistent way *regardless* of whether or not you included blocks for your embedded statements.  I strongly pushed for this with the argument that *up until now* using a block for an embedded statement was *always* a stylistic preference that could not affect semantics.  That was something people could trust, and we did not want to violate that.    in other words, it shouldn't matter if you used braces here or not:

```c#
if (x) {
    if (int.TryParse(out var s)) { }
}

//vs

if (x)
    if (int.TryParse(out var s)) { }
```

The behavior you see is a consequence of that.

**Comment by CyrusNajmabadi** [comment]
> Imagine an IDE feature for removing redundant else keywords, this is a painful edge case to handle.

Yup.  But the reason is that you're jumping scopes.  previously your else was attached to hte most nested if.  Now it jumps out to the block it is on.  These scopes may have variables in them.  

Sometimes hte language makes some types of refactorings hard.  Too bad, so sad for us :)

**Comment by alrz** [comment]
Yeah, so sad for us.
