### ISSUE TITLE
Ambiguous type reference should suggest adding a using alias

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#23373]
(Following the pattern of reporting my most frequent ReSharper quick actions with the goal of being able to use vanilla VS one day.)

Most times that I have an ambiguous type reference I don't want to resolve it by fully qualifying. It can appear many files in a file. My resolution of choice is to add `using TypeName = The.Namespace.I.Want.TypeName`.

**Comment by CyrusNajmabadi** [comment]
Interesting.  Seems reasonable.  Def would probably need an option to control that. 

PRs welcome.

**Comment by sharwell** [comment]
I agree with PRs welcome. I would recommend the initial implementation not include an option unless it goes through a design meeting an one is deemed necessary. I would certainly be pushing against it.

**Comment by MaStr11** [comment]
I assume we are talking about a code fixer for `Error CS0104 'Ambiguous' is an ambiguous reference between 'System.Text.Ambiguous' and 'System.Threading.Ambiguous'` as in the example below:
File1.cs
```CSharp
namespace System.Text
{
    public class Ambiguous  { }
}
namespace System.Threading
{
    class Ambiguous  { }
}
```
File2.cs

```CSharp
using System.Text;
using System.Threading;
namespace Application1
{
    class Program
    {
        static void Main(string[] args)
        {
            var a = new Ambiguous(); //Error CS0104 'Ambiguous' is an ambiguous reference between 'System.Text.Ambiguous' and 'System.Threading.Ambiguous'
        }
    }
}
```

The fix for File2.cs would be to offer adding 
`using Ambiguous=System.Text.Ambiguous;` or `using Ambiguous=System.Threading.Ambiguous;` to the using block.

```CSharp
using System.Text;
using System.Threading;
using Ambiguous=System.Threading.Ambiguous; // This fixes CS0104 
namespace Application1
{
    class Program
    {
        static void Main(string[] args)
        {
            var a = new Ambiguous();
        }
    }
}
```

Other alternatives are discussed at [this stackoverflow thread](https://stackoverflow.com/questions/20467884/error-cs0104-datatype-is-an-ambiguous-reference-between-system-componentmod) but I think the option given by @jnm2 is the best one.

**Implementing**

The solution should be to implement a new diagnostic code fixer for CS0104 (BC30561 for Visual Basic). Unfortunately the `SimpleDiagnostic` for CS0104 does not carry the information about the conflicting types so the fixer needs to calculate the candidates. This logic is already implemented by the [AbstractFullyQualifyCodeFixProvider](https://github.com/dotnet/roslyn/blob/master/src/Features/Core/Portable/FullyQualify/AbstractFullyQualifyCodeFixProvider.cs#L58-L67). It might be useful to place [GetMatchingTypesAsync](https://github.com/dotnet/roslyn/blob/master/src/Features/Core/Portable/FullyQualify/AbstractFullyQualifyCodeFixProvider.cs#L137) in the `ISyntaxFactsService` to share the code. Another option would be to use [Diagnostic.Properties](https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/Portable/Diagnostic/Diagnostic.cs#L389-L395) to pass the information about the conflicting types to the fixer. The questions are 

1. It seems there is a corresponding solution for VBs BC30561 by using `Imports Ambiguous = System.Text.Ambiguous`. Am I right or are there differences? 
2. Should this be a new code fixer or should the logic be included into AbstractFullyQualifyCodeFixProvider? Likely a new fixer.
3. Is refactoring the common code between the new fixer and AbstractFullyQualifyCodeFixProvider to ISyntaxFactsService the way to go or should there be a common base class for the fixers?
4. Is using `Diagnostic.Properties` to transport the type information from the compiler to the fixer an option?
5. What about the other solutions to solve CS0104 (see e.g. the [stackoverflow thread](https://stackoverflow.com/questions/20467884/error-cs0104-datatype-is-an-ambiguous-reference-between-system-componentmod)).

@CyrusNajmabadi I think you are probably the one how can answer the questions with ease.

**Comment by CyrusNajmabadi** [comment]
> It seems there is a corresponding solution for VBs BC30561 by using Imports Ambiguous = System.Text.Ambiguous. Am I right or are there differences?

Seems reasonable.

> Should this be a new code fixer or should the logic be included into AbstractFullyQualifyCodeFixProvider? Likely a new fixer.

A new fixer.

> Is refactoring the common code between the new fixer and AbstractFullyQualifyCodeFixProvider to ISyntaxFactsService the way to go or should there be a common base class for the fixers?

Don't but in ISyntaxFactsService. its not a fact about syntax :)   instead, use some other mechanism.  You could use a common base class.  or composition.  Or helper utilities.

> Is using Diagnostic.Properties to transport the type information from the compiler to the fixer an option?

Probably not.  We carry almost no information in diagnostics themselves beyond the ID.  The design is that fixers then figure out what's going on using the compiler APIs.  Because this is an ambiguity error, you should be able to call GetSymbolInfo and examine the result of that to figure out what types the compiler thought were in scope at that point that were ambiguous.

**Comment by MaStr11** [comment]
I started working on this [here](https://github.com/MaStr11/roslyn/tree/AmbiguousTypeCodefixProvider), so this isn't up-for-grabs anymore.
