### ISSUE TITLE
VB's anonymous types have a GetHashCode method that doesn't work correctly.

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#23413]
**Version Used**: 

Latest

**Steps to Reproduce**:

1. Compile and run code below

**Expected Behavior**:

Print the same number twice

**Actual Behavior**:

Prints different numbers

``` vb
Imports System

Module Module1

    Sub Main()
        Dim o As Object = Nothing
        Console.WriteLine(New With {.a = o}.GetHashCode())
        Console.WriteLine(New With {.a = o}.GetHashCode())
    End Sub

End Module
```

**Comment by HaloFour** [comment]
This is the expected behavior.  VB.NET's anonymous type members are mutable by default and don't participate in the identity of the type *unless* they are marked with the `Key` keyword.  In your example an implementation of `GetHashCode` isn't even emitted as there are no `Key` members.

However, change your example to this:

```vb
Imports System

Module Module1

    Sub Main()
        Dim o As Object = New Object()
        Console.WriteLine(New With {Key .a = o}.GetHashCode())
        Console.WriteLine(New With {Key .a = o}.GetHashCode())
    End Sub

End Module
```

And it works as expected.

**Comment by gafter** [comment]
@HaloFour Thanks!
