### ISSUE TITLE
WorkspaceRegistration.RaiseEvents is broken

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#23474]
currently we have 2 issues. all of them can lead events to be out of order.

1. RegisterText is Async event, but UnregisterText is synchronous event
(http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Workspace/Workspace_Registration.cs,34)

this can cause WorkspaceChanged event from UnregisterText to be raised before WorkspaceChanged event from RegisterText. causing events to be out of order and make this events hard to be used in state tracking manner.

2. WorkspaceChanged event being called from 2 different Workspace event queues causing events to be out of order.

this event exist to indicate a buffer is moved from one workspace to the other workspace. but it uses each workspace's event queue to raise the WorkspaceChanged event leaving a race where 2 events might be raised in out of order. again, making the event hard to be used in state tracking manner.

...

we either need to make 
1. WorkspaceChanged event synchronous event that only raised in UI thread (using UI thread as queue) 
2. or create its own event queue for WorkspaceRegistration.WorkspaceChanged event so that order is preserved between workspaces and register/unregisterText.

**Comment by heejaechang** [comment]
@jinujoseph @jasonmalinowski @Pilchie

**Comment by jasonmalinowski** [comment]
Yep, this was an oversight I think @CyrusNajmabadi noted awhile back.

As far as 'what to do', this is tricky. Multiple workspaces can choose to have their events raised in different locations -- some could go on the foreground, some could go on the background. Essentially, each workspace has a workspace queue that it can give, and those can be different.

> WorkspaceChanged event synchronous event that only raised in UI thread (using UI thread as queue)

This isn't really feasible, since you could be associating things on background threads -- it'll have to be async no matter what. Hopefully as we get more of the VisualStudioWorkspace background thread safe, and it's entirely reasonable we'll be doing those associations on background threads, so we'll either have to raise the event synchronously on the background thread or asynchronously on the UI thread.

> or create its own event queue for WorkspaceRegistration.WorkspaceChanged event so that order is preserved between workspaces and register/unregisterText.

This seems reasonable to at least put the registrations all on a single queue so you get a consistent order there. Note per my statement earlier you could still have that be a different queue than other workspaces, so beware.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
