### ISSUE TITLE
API inconsistency in ISwitchCaseOperation

### ISSUE THREAD

**Issue by bkoelman** [dotnet/roslyn#23527]
**Version Used**: 
2.6.0-beta3-62329-03

**Steps to Reproduce**:
The `Body` property of `ISwitchCaseOperation` is declared as `ImmutableArray<IOperation>`, while all other statements have their body declared as `IOperation`, which then contains a single other operation or multiple wrapped in a `IBlockOperation`.

**Expected Behavior**:
`ISwitchCaseOperation.Body` is typed as `IOperation`.

**Actual Behavior**:
`ISwitchCaseOperation.Body` is typed as `ImmutableArray<IOperation>`.

**Comment by jcouv** [comment]
Tagging @mavasani @heejaechang

**Comment by mavasani** [comment]
Also tagging @dotnet/analyzer-ioperation 

I think this is by design, but something that can potentially be changed. As our current API is primarily syntax driven, the operation tree shape matches the syntax tree. A switch case can have multiple statements, without requiring braces around it, hence the operation tree shape. We can possibly consider having an implicit IBlockOperation wrapping the statements, the same way as we do for multiple cases in VB for blocks without explicit syntax. Thoughts?

**Comment by heejaechang** [comment]
so user is supposed to figure out whether { } is explicit or not by checking IsImplicit check?

**Comment by mavasani** [comment]
@heejaechang Yes, that is correct.

**Comment by 333fred** [comment]
This makes sense to me. It's consistent with how we decided to treat lambdas. We should also consider if statements with no block; should those have an implicit block as well? They currently do not: https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Test/Semantic/IOperation/IOperationTests_IIfStatement.cs#L194-L213

**Comment by CyrusNajmabadi** [comment]
> We can possibly consider having an implicit IBlockOperation wrapping the statements

This would be pretty odd IMO, especially as it would seem like it would be scoping related (which isn't hte case for switches).

In reality, switches are just really weird.  So it doesn't surprise me that the IOperation form of them would be weird.

**Comment by bkoelman** [comment]
> A switch case can have multiple statements, without requiring braces around it, hence the operation tree shape.

Makes perfect sense, I did not think of that. With this info I'm fine with the current shape.
