### ISSUE TITLE
suggestion : replace property with field

### ISSUE THREAD

**Issue by MkazemAkhgary** [dotnet/roslyn#23543]
**Version Used**: 15.4.5

**Actual Behavior**:

When clicking on property, lightbulb only suggests to replace auto property with a method.

**Expected Behavior**:

add another suggestion to replace auto properties with fields and sort out naming (prefix with `_`), and replace get only auto properties with readonly fields.

**Comment by CyrusNajmabadi** [comment]
that can be done just be changing your field into a property (i.e. removing the accessors), then renaming however you want.  Having a specific feature for this doesn't seem that helpful given that we already have the primitives.

Replace-property-with-method, on the other hand, *is* helpful as you would otherwise have to go fix up a ton of use sites to use method-call syntax instead of variable syntax. i.e.

```Foo++``` gets translated to ```SetFoo(GetFoo() + 1)``` by that refactoring.

**Comment by CyrusNajmabadi** [comment]
Note: if you really want thsi refactoring, feel free to write it and make it available as a nuget package for people to use :)   However, i don't think it meets the value bar to be included as a stock refactoring in the VS package.

**Comment by MkazemAkhgary** [comment]
Oh I see, so I can remove get part and rename variable and problem solved. why I didn't realize that.. nvm thanks for solution 👍
