### ISSUE TITLE
SyntaxKind.VarKeyword is missing

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#23546]
Because of that we always check for "var" string instead of ContextualKind. Is there any reason why is that?

**Comment by CyrusNajmabadi** [comment]
'var' is not a keyword (contextual or otherwise).  It's just a special name that the compiler knows about it a type name does not bind to something.

A contextual-keyword is something that is normally an identifier, but which can be determined to be a keyword *syntactically*.  i.e. 'from'.  if you have "var v = from;" it's clear syntactically that 'from' is just an identifier.  However, if you have "var v = from x in y select x;" then 'from' here is known *syntactically* to be a keyword.  

Contextual keywords are never determined semantically.  They're always syntactically determined.

So 'var' and 'dynamic' are just simple identifiers that the compiler knows about and which it processes specially if the names do not bind to something.

**Comment by alrz** [comment]
So how come we do have NameOfKeyword?

**Comment by CyrusNajmabadi** [comment]
No clue!  @gafter do you remember?

**Comment by gafter** [comment]
`nameof()` get special syntactic treatment in pattern-matching; it is permitted where a method invocation would be forbidden:
``` c#
switch (o) {
    case nameof(x): // OK, looks for the string "x"
    case X(y):           // OK, recursive pattern looks for type `X` with a single-element `Deconstruct` method, whose output value is checked against the constant named `y`.
```

Recursive patterns are being added in C# 8. The special treatment of `nameof` was added early enough to permit it to be used to produce a constant for use in pattern-matching and the switch statement in earlier versions of the language, rather than being a not-yet-supported recursive pattern.

`var` had no effect on the syntax before, but we may need to make it a contextual keyword in C# 8 to support the *var pattern*, which is syntactically different from a recursive pattern:

``` c#
switch (c) {
    case var (x, y): // OK, calls `c.Deconstruct` and saves the output values into new variables `x` and `y`
        break;
    case C(x, y): // OK, calls `c.Deconstruct` and checks the output values against constants `x` and `y`
        break;
```

**Comment by alrz** [comment]
>var had no effect on the syntax before

Doesn't `var (x, y) = p;` count? Anyways, I expected to see a contextual kind for any contextual keyword. `dynamic` included.

**Comment by CyrusNajmabadi** [comment]
> Anyways, I expected to see a contextual kind for any contextual keyword. dynamic included.

That's never been how Roslyn has worked.  It's important to realize that 'var' and 'dynamic' are *not* keywords.  They're names with semantic meaning.

**Comment by gafter** [comment]
> Doesn't `var (x, y) = p;` count?

No. The parser will accept any type there.

**Comment by alrz** [comment]
>That's never been how Roslyn has worked. It's important to realize that 'var' and 'dynamic' are not keywords. They're names with semantic meaning.

>No. The parser will accept any type there.

I think I get how it works now. Thanks.
