### ISSUE TITLE
Visual Basic comment indentation above the ELSE

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#23624]
I now have the release of VS2017.

For a IF THEN ELSE, I cannot put a comment above the ELSE, and make the comment stay above the ELSE, it will always auto indent.
Doesn't matter if in the Tab settings is none, block or smart, the comment will always auto indent.

Even when typing close to one of these comments in an existing file (created with VB in VS2013), it screws up my existing listings.
I also reported this issue with the RC build, and here it still is, nobody said it is an issue or not, if the issue is being looked at/not being looked at, nothing.

Please give me an idea if it is an issue, and if so, if it will be fixed or not, and roughly when.

Thanks.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/24271/visual-basic-comment-indentation-above-the-else.html
VSTS ticketId: 413289_
_These are the original issue comments:_

Chris on 9/16/2017, 11:15 PM (80 days ago): 6 months later and still under investigation... I'm using VS2013. When using VS2017 it is distracting concentrating on not screwing up comments.
_These are the original issue solutions:_

Chris Botha solved on 12/1/2017, 09:35 PM (4 days ago), 0 votes: <p>It's now December, still can't put a comment above an ELSE without it auto indenting, and I'm still using VS2013 even though I bought VS2017 when it was released. I'm wondering if I am the only one using VB...</p>

Chris solved on 12/6/2017, 06:54 AM (6 hours ago), 0 votes: <p>I found something, go to Settings -&gt; Text Editor -&gt; Basic -&gt; Advanced, then turn Pretty Listings off. You lose Pretty Listings, but when un-indenting a comment, it won't auto indent any more.</p>

**Comment by dpoeschl** [comment]
I think this is intentional. We think it's part of the IF block. On our team, we typically put comments pertaining to the ELSE block on the first indented line under the ELSE. Any thoughts, @AnthonyDGreen ?

**Comment by elachlan** [comment]
I either put the comment inside the else block or right next to it. I think not auto indenting this would be very annoying/problematic.

**Comment by AnthonyDGreen** [comment]
This annoys me too! It's intentional but because of technical limitations in differentiating these cases:

``` VB.NET
If condition Then
    ' Do nothing.
Else
    ' Do something
End If
```

Ok, that's a bit contrived but there are situations where people want the comment to be considered part of the `Then` part and other times when it labels the `Else` part. The same problem exists with `Case` blocks. We just didn't have a good heuristic for formatting here at the time. But now I'd like to propose an alternative. Similar to **how whitespace around LINQ queries and implicit line continuation is left undisturbed** if the user manually edits it, perhaps whitespace preceding a comment leasing an `Else`, `ElseIf`, or `Case` statement should be left however the user made it.

* In the normal case of typing the comment will be indented because that's where the cursor was when they started typing.
* If they manually adjust to align with the `Else` statement it'll be preserved.
* If they put a new statement after the comment the statement and comment will both be adjusted to be indented relative to the block.
* If they remove a statement following a comment the comment won't automatically slide over to be indented to the `Else` statement.

I think this balances all the concerns and unblocks the customer. @dpoeschl does this seem doable?

**Comment by paul1956** [comment]
@AnthonyDGreen how about a way to also undo the manual formatting especially around a Linq Query, implicit continuation and here if you decide to implement this change. Maybe a codeFix or as part of the Edit/Advanced/FormatDocument. I find that if I accidently change indenting nothing ever turns auto formatting back on.

**Comment by dpoeschl** [comment]
I believe this should be doable with the formatting engine.

**Comment by CyrusNajmabadi** [comment]
Clsosing out as we are not invessting in this scenario.
