### ISSUE TITLE
OOM while working in Roslyn.sln

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#23628]
**Version Used**: 

15.6.0 P1 27205.0.d15.6

**Crash dump**:

%internal_share%\public\tomat\Bugs\23628

**Comment by tmat** [comment]
@sharwell FYI

**Comment by tmat** [comment]
@sharwell Any progress? My VS crashes a lot while working in Roslyn due to this.

**Comment by Pilchie** [comment]
@sharwell is out for the next week.

**Comment by KevinH-MS** [comment]
I took a quick look at this.  There's a lot going on, but the worst of it is in Test Window:


Name | Inc % | Inc
-- | -- | --
\|+ [static var Microsoft.VisualStudio.CMake.Project.OperationManager.BuildFinishing] | 29.4 | 374,323,648
\|\|+ LIB <<mscorlib!EventHandler>> | 29.4 | 374,323,648
\|\| + Microsoft.VisualStudio.CMake.Package!Microsoft.VisualStudio.CMake.Package.TestExplorer.CTestContainerDiscoverer | 29.4 | 374,320,384
\|\|  + LIB <<mscorlib!EventHandler>> | 29.4 | 374,320,320
\|\|   + Microsoft.VisualStudio.TestWindow.Core!Microsoft.VisualStudio.TestWindow.Controller.TestContainerProvider | 29.4 | 374,317,056
\|\|    + Microsoft.VisualStudio.TestWindow.Core!Microsoft.VisualStudio.TestWindow.Data.InMemory.MergedTestDictionary | 21.3 | 271,266,272
\|\|    \|+ Microsoft.VisualStudio.TestWindow.Core!Microsoft.VisualStudio.TestWindow.Data.InMemory.NamedIDSet | 19.4 | 246,354,224
\|\|    \|+ LIB <<mscorlib!Dictionary>> | 1.9 | 24,285,786
\|\|    + Microsoft.VisualStudio.TestWindow.Core!Microsoft.VisualStudio.TestWindow.VsAdapters.VsProjectOutputContainerDiscoverer | 8.1 | 102,820,640

I believe I have fixed the issue with ```VsProjectOutputContainerDiscoverer``` in the latest d15.6stg builds, so that'll give you a little headroom, but I've not seen ```MergedTestDictionary``` taking this much space before.  @genlu @peterwald have you seen this before when testing on Roslyn.sln?

**Comment by peterwald** [comment]
@KevinH-MS I have been testing somewhat with Roslyn.sln and have not seen an OOM, but that does seem like a lot of memory.

**Comment by tmat** [comment]
I think it might have something to do with the option "Keep test execution engine running" in Test > Test Settings menu. I disabled it and haven't seen oom since -- I have not spent too long in the solution yet, so it might sill happen, but so far so good.

**Comment by KevinH-MS** [comment]
@tmat shared another dump:  [internal share]\public\tomat\Bugs\23628\devenv2.dmp


Name | Inc % | Inc
-- | -- | --
\|+ [static var Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNodeRetriever.ProjectNodeCache] | 34.9 | 427,827,712
\|\|+ LIB <<mscorlib!ConcurrentDictionary>> | 34.9 | 427,827,712

@davkean any thoughts on this?  400MB of ProjectNodes in a dictionary seems a bit excessive (like a leak).

**Comment by peterwald** [comment]
That works out to about 3.2kb per test case.

**Comment by davkean** [comment]
@KevinH-MS Does seem high - but to be honest I have no idea how big ProjectNodes are supposed to be. I'd open a bug against CPS; DevDiv\VS Platform\VS IDE\Project and Telemetry\CPS

**Comment by davkean** [comment]
Oh are you saying that the dictionary itself is 400 MB? Yes, that is excessive.

**Comment by KevinH-MS** [comment]
It's inclusive (so everything the Dictionary points to), but it still feels excessive to me.  A full Roslyn Solution snapshot from the same dump is only ~100MB.  I don't know why the project cache would be 4X of that.

**Comment by peterwald** [comment]
I'm looking at the NamedIDSet memory in the TestWindow. That sounds too high.

**Comment by jviau** [comment]
It is too high for sure, the ConcurrentDictionary should only have 1 project node in it for every open CPS project. On project close it should be removed. Do you have a 32 bit heap dump? I would like to see how many `ProjectNodeRetriever` are in memory un-disposed.

**Comment by peterwald** [comment]
@KevinH-MS I'm curious how PerfView is tallying those numbers. I went through the heap dump and added it up.

There are only two NamedIDSet instances in the entire heap; one of which is empty (as expected). There are 82800 tests that were discovered and they are all discovered from source. There are 74,243 entries in the one NamedIDSet, and it is about 2.7MB exclusive and about 21.5MB inclusive. About 80-90% of that memory is in the form of strings since the NamedIDSet maps strings to GUIDs. 

Since the strings share a lot of the same prefixes, we could use something like a prefix trie to save space, but that doesn't explain why PerfView is reporting 10x higher memory usage than I'm seeing in the dump.

**Comment by jviau** [comment]
I am looking at the 2nd dump. There are 152 `ProjectNode`s alive, which sounds correct, 1 per project and Roslyn.sln is right around that size. So the `ConcurrentDictionary` is not the problem, as it is not the only gcroot to those `ProjectNode`s. 400MB is probably excessive for 152 projects, so I think each individual project is leaking memory and not that dictionary growing out of control.

**Comment by tmat** [comment]
Any progress? Still repro in 
![image](https://user-images.githubusercontent.com/41759/34740672-0c71fffa-f535-11e7-97d7-16b14354b6cc.png)

**Comment by peterwald** [comment]
We have an PR in progress for the Test Window that should reduce the memory pressure from TestData objects. Will let you know when it ships.

**Comment by tmat** [comment]
Is this really a Test Window issue? I do not have it open.

**Comment by peterwald** [comment]
If real-time test discovery is turned on (which it is in 15.6), then test discovery is happening in the background even if the Test Window is not open. The original dump showed a large number of TestData objects in memory (more than there should be).

**Comment by tmat** [comment]
Can I disable it as a workaround?

**Comment by peterwald** [comment]
Yes, if you uncheck the box in Tools | Options, and then restart VS.

![image](https://user-images.githubusercontent.com/5578/34787869-a0318d92-f5ed-11e7-9ef5-15624d853cfd.png)

**Comment by KevinH-MS** [comment]
@jasonmalinowski I cannot assign this to @peterwald any idea why?

**Comment by sharwell** [comment]
@KevinH-MS Assignees either need to be the original issue author, or they need to be in a team within the dotnet organization on GitHub that has explicit read access to the dotnet/roslyn repository.

**Comment by ManishJayaswal** [comment]
@tmat - we have made some fixes that should reduce allocation but are not certain if this issue is completely resolved. We can't repro it. Can you try on latest d15.6 builds ( latest builds from our dogfooding channel) to see if this resolves the issue you were seeing or not?

**Comment by jinujoseph** [comment]
@tmat closing this issue, pls reopen if you notice this again
