### ISSUE TITLE
Control-M Control-O no longer collapses regions

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#23639]
I am using Visual Studio 2017 15.5.0 Preview 1.0.
In Visual Studio 2015, entering control-m control-o while editing c# source code would collapse all regions in the source. 
In Visual Studio 2017, it no longer does this. In collapses methods but no regions.
This is very annoying as I used to use control-m control-o very often

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/131706/control-m-control-o-no-longer-collapses-regions.html
VSTS ticketId: 509521_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by dpoeschl** [comment]
I believe this has come up before but I can't find the existing issue on GitHub, so let's talk about it here. How often do people want one of these behaviors versus the other?

**Comment by CyrusNajmabadi** [comment]
There is an option to control this:

![image](https://user-images.githubusercontent.com/4564579/33735323-d1db6e7c-db43-11e7-9c5b-7612cc15471c.png)

We did this because VB and C# behaved differently and we had people asking that they behave the same... and people asking that things not change...  So we added an option to allow for users to control this.

**Comment by dpoeschl** [comment]
Awesome. Thanks Cyrus!
