### ISSUE TITLE
Instance fields of value types should be allowed to be used inside local functions

### ISSUE THREAD

**Issue by kindermannhubert** [dotnet/roslyn#23670]
**Version Used**: VS 15.5.0

**Steps to Reproduce**:
Following code:
```C#
struct MyStruct
{
    private int value;

    private void Foo()
    {
        FooLocal();

        void FooLocal()
        {
            Console.WriteLine(value);
        }
    }
}
```
does not compile with error:
CS1673	Anonymous methods, lambda expressions, and query expressions inside structs cannot access instance members of 'this'. Consider copying 'this' to a local variable outside the anonymous method, lambda expression or query expression and using the local instead.

Local functions can be (I believe) compiled as instance methods of containing type (same as for reference types - see also #23669) and therefore they can access instance fields.

**Expected Behavior**:
Local functions in value types can access instance fields.

**Actual Behavior**:
Local functions in value types cannot access instance fields.

**Comment by sharwell** [comment]
💭 This is really interesting. Supporting this case would mean some local functions would not be able to be converted to a delegate, while others could.

**Comment by jcouv** [comment]
Tagging @agocke @gafter

**Comment by agocke** [comment]
@sharwell Is correct on the implications here: since `this` is passed by `ref` parameter in value types, it's not possible to capture `this` in a closure. Therefore, it would not be possible to convert these local functions to delegates.

This is contrary to the specification and design of local functions: all local functions can be converted to delegates. Therefore, this is not a bug, it is by design.
