### ISSUE TITLE
Use in-parameter operator from different assembly

### ISSUE THREAD

**Issue by ufcpp** [dotnet/roslyn#23689]
**Version Used**: 

VS 15.5.0

**Steps to Reproduce**:

https://github.com/ufcpp/UfcppSample/tree/master/Demo/2017/InOperatorDifferentAssemly

1. Write a struct with in-parameter operator in an assebmly

```cs
    public struct DifferentAssembly
    {
        ....
        // by-val
        public static DifferentAssembly operator +(DifferentAssembly a, DifferentAssembly b)
        ....

        // by-ref-readonly
        public static DifferentAssembly operator *(in DifferentAssembly a, in DifferentAssembly b)
        ....
    }
```

2. Use it from another assembly

```cs
            var a = new DifferentAssembly(....);
            var b = new DifferentAssembly(....);

            // pass by value. No error.
            Console.WriteLine(a + b);

            // pass by ref readonly.
            // No error in the Visual Studio C# Editor
            // but error on build.
            Console.WriteLine(a * b);
```

**Expected Behavior**:

successfully compiled

**Actual Behavior**:

There is no error in the Visual Studio C# Editor, but error on build.

![image](https://user-images.githubusercontent.com/3760955/33801977-dae86fd8-ddaf-11e7-8dbc-39f5f25b207d.png)

**Comment by jcouv** [comment]
Do you get a different behavior if the struct is declared in the same project/compilation?

@OmarTawfik [recently fixed](https://github.com/dotnet/roslyn/pull/23122) this scenario so that the by-val overload will be preferred in ambiguous situation. This fix is in master and should be available in 15.6 preview 2 (not yet released).
Test `PassingInArgumentsOverloadedOnIn_BinaryOperators` is close to what you describe, but within one compilation.

**Comment by OmarTawfik** [comment]
Yes. 15.5 didn't allow operators from other assemblies to be imported. #23508 fixed that (merged to master).
You can confirm quickly by either declaring your operators in the same assembly (should make the error go away), or trying the latest compiler from master, which should import the operator from the other assembly.

**Comment by VSadov** [comment]
fixed in https://github.com/dotnet/roslyn/pull/23508
