### ISSUE TITLE
How to create CSharpCompilation that has reference to a .vbproj

### ISSUE THREAD

**Issue by GeorgeAlexandria** [dotnet/roslyn#23759]
Hi,

I'm used ***Microsoft.CodeAnalysis.VisualBasic.1.3.2***, ***Microsoft.CodeAnalysis.CSharp.1.3.2*** and they dependents.

I have a *.csproj* that has reference to a *.vbproj*

* I create compilation for the *.vbproj* from it source files
* Then I try to pass it MetadataReference that I get using **Compilation.ToMetadataReference(...)** as a reference to the **CSharpCompilation.Create(...)**. Unfortunately, I give the exception by [this condition](https://github.com/dotnet/roslyn/blob/e2fda399f9bc77b662f9b7f07898fbfd7c6a741e/src/Compilers/Core/Portable/Compilation/Compilation.cs#L504). 

So, how can I pass metadata from the *.vbproj* to the CSharpCompilation as reference?
Any suggestion would be grateful.

P.S. I cannot modified this projects and *.vbproj* can have a compilation time errors, so **Compilation.Emit(...)** cannot solve the problem.

**Comment by jcouv** [comment]
We have some tests that do that. As far as I can remember, `ToMetadataReference()` is the correct way.
I'll dig up an example of test tomorrow.
Can you share more details about the exception you're getting (what's the message?).

**Comment by GeorgeAlexandria** [comment]
@jcouv, `ToMetadataReference()` return to me `VisualBasicCompilationReference` for the `VisualBasicCompilation`(*.vbproj*). And  I get `ArgumentException` when I try to pass `VisualBasicCompilationReference` as `MetadataReference` to `CSharpCompilation.Create()`: 
> Reference of type 'Microsoft.CodeAnalysis.VisualBasic.VisualBasicCompilationReference' is not valid for this compilation.
>Parameter name: references[9]

As I posted above [this validation](https://github.com/dotnet/roslyn/blob/e2fda399f9bc77b662f9b7f07898fbfd7c6a741e/src/Compilers/Core/Portable/Compilation/Compilation.cs#L504) is failed. You can check stack trace for it:
>   at Microsoft.CodeAnalysis.Compilation.ValidateReferences[T](IEnumerable`1 references)
  
>   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.Create(String assemblyName, CSharpCompilationOptions options, IEnumerable\`1 syntaxTrees, IEnumerable\`1 references, CSharpCompilation previousSubmission, Type returnType, Type hostObjectType, Boolean isSubmission)
 
>   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.Create(String assemblyName, IEnumerable\`1 syntaxTrees, IEnumerable\`1 references, CSharpCompilationOptions options)

**Comment by jcouv** [comment]
Checked in the compiler tests (looking for `CreateCSharpCompilation` in the VB test projects). We use `EmitToImageReference()`.
As you pointed out, this can only work when the referenced compilation can successfully compile.

One possible trick though: it is possible to emit the referenced compilation as a ref assembly, instead of a regular assembly. That will not guarantee success, but it can compile in many more cases (since method bodies don't get compiled, the number of possible errors is reduced).

Note that VS itself runs into this problem with cross-language project dependencies. If my understanding is correct, VS will re-use a previous referenced assembly if its compilation now fails.

Also note that I'm working on allowing emitting metadata-only and ref assemblies even in the presence of errors ([TolerateErrors](https://github.com/dotnet/roslyn/issues/20914) flag). I don't know when I'll be able to complete that (maybe in a year or so).

**Comment by GeorgeAlexandria** [comment]
@jcouv, do you mean a using `EmitOptions.MetadataOnly` to emit compilation as a ref assembly, instead of regular? Can you explain this trick with a ref assembly (or give a some example) if my supposition above doesn't right?

**Comment by jcouv** [comment]
@GeorgeAlexandria You need both `MetadataOnly` and `IncludePrivateMembers=false` to produce a ref assembly. The first flag means method bodies aren't emitted. The second flag means that inaccessible/invisible members aren't emitted.
Use `EmitOptions.Default.WithEmitMetadataOnly(true).WithIncludePrivateMembers(false)`.
