### ISSUE TITLE
It's time to create a new awesome programming language

### ISSUE THREAD

**Issue by rxprogrammer** [dotnet/roslyn#23785]
Other platforms has already created their own new programming languages such as Rust, Golang, Swift, Kotlin. On the JVM, Kotlin seems to replace Java with it new modern syntax. People seems to very impressed with Golang by its native support for concurrency. Should we consider to create new programming language?
- More modern and concise syntax, for example no semi-colon, put type after variable's name, put return type after method's name etc. (looking at Swift, Kotlin, or even TypeScript)
- Class / method is open by default (similar to Java). I hate to add the "virtual" keyword when I define new domain class.
- The best of C# is its Generics, LINQ, Lambda => keep it
- Remove all the existing features of C# that are not widely used by developers (look at how Golang's team keep consider carefully when adding any new features)
- Emphasize on support concurrency, multi-core (see how people is impressed with Golang's concurrency support. Yes I know I know Golang's coroutine is just similar to C#'s async/await, but the fact is that not many people know or trust that :) )
- Emphasize on the ability to compile to Web Assembly
- Emphasize on native support for Functional programming (maybe 50-50 support for OOP and Functional)
- Easily to communicate with C#'s code (similar to Kotlin and Java), this is very important
- etc.

**Comment by drozdekl** [comment]
I don't think that method's which are virtual by default is a good idea. I understand "virtual" keyword as a promise to someone who inherits from my class that it I understand all consequences and allow them to override this method. It just seems wrong give this premise by default. 

If I would design new language now I would make classes sealed by default, methods nonvirtual by default and types non-nullable by default. I would also rename interfaces to functional class, allow multiple inheritance and forbid fields in functional class. Multiple inheritance on regular classes would be still forbidden. 

I think that everyone thinks of "ideal language" which would be 100% fulfill their ideal. Currently there is C# , F#, VB and Q#.  I think that these languages are great and there is no need for another language.

**Comment by Emzi0767** [comment]
Kotlin was created to fix Java problems, which are, for the most part, not present in C#. Or put in other words, let JVM catch up to 2017.

Aside from that, creating a language is no easy task. Plus why create one when there's a number of perfectly fine languages available in .NET ecosystem already?

**Comment by HaloFour** [comment]
Microsoft already has more than a half-dozen available and supported languages that target the CLR and can interop with one another.  There is a further ecosystem of many other languages, ranging from general purpose to esoteric.  There are all kinds of languages that meet many (if not all) of your stated goals.

**Comment by CyrusNajmabadi** [comment]
> Remove all the existing features of C# that are not widely used by developers (look at how Golang's team keep consider carefully when adding any new features)

Which are these features?

**Comment by yaakov-h** [comment]
> Emphasize on the ability to compile to Web Assembly

I thought corert is working on this already?

**Comment by Neme12** [comment]
No.

> More modern and concise syntax, for example no semi-colon, put type after variable's name, put return type after method's name etc. (looking at Swift, Kotlin, or even TypeScript)

How is
```c#
var x: string;
```
more consise than
```c#
string x;
```
?

> Class / method is open by default (similar to Java).

No.

> Remove all the existing features of C# that are not widely used

which features?

> Emphasize on the ability to compile to Web Assembly

why does that require a new language?

**Comment by omidkrad** [comment]
I'd like to see some features of F# (like Units of Measure), GoLang (like Coroutines) and EcmaScript (like native JSON support) in C#, but not looking for a new programming language.

**Comment by JeroMiya** [comment]
@Neme12 The variable-name-first-then-type declaration style is not intended to be more concise but to provide other benefits:

- variable and function names are often more important than their types, so placing the name first more closely matches the relative importance of the name vs the type (often left out through type inference).
- Types vary wildly in length, particularly generic types. This style makes it so the variable and function names line up vertically no matter what the return type or variable type is. So even if there's technically more characters, it ends up being more readable, which is more important.
- It helps with type inference - for instance, scala can infer method return types of expression bodied methods. This is only possible syntactically because the return type comes after the method name (unless it can be inferred).
- I'm told it helps eliminate grammar ambiguities in languages that support block/control-flow expressions and optional or no semicolons. Not sure how or if that's true, but it's sometimes said.

All that being said, I'd recommend closing this issue as off topic. I'd rather the Roslyn team focused on the language it was built for rather than refactoring it to be a general purpose language compiler framework. Though, you could always parse your own language and transpile it into

**Comment by sharwell** [comment]
This is the repository for the C# and VB language implementations. A new language which is not C# or VB would by its very nature not be C# or VB, and thus wouldn't belong in this repository. 😄
