### ISSUE TITLE
[Proposal] Tuple pattern matching

### ISSUE THREAD

**Issue by saleyn** [dotnet/roslyn#23791]
I'd like to request a language feature to be able to do pattern matching on tuples.

Example:
```c#
void MyFunction(object t)
{
  switch (t)
  {
    case (string a, _) t when t.a != null:
      HandleStr(t.a);
      break;
    case (int type, _) t when t.type == 10:
      HandleTup(t);
      break;
  }
}
```

**Comment by jcouv** [comment]
I think you're describing positional pattern-matching which is being worked on for C# 8.0.
More details at https://github.com/dotnet/csharplang/issues/1054

I'll go ahead and close this issue since the roslyn repo is for compiler/IDE bugs rather than language design. Feel free to continue the discussion on csharplang.
Thanks
