### ISSUE TITLE
Slow Roslyn solution load time

### ISSUE THREAD

**Issue by VE-2016** [dotnet/roslyn#23823]
Version Used
Most recent master branch from https://github.com/dotnet/roslyn

Running on Windows 10, I am trying to create MSBuild Workspace and load Roslyn.sln.
Loading times are 4 minutes to create Workspace and Solution objects. My question is whether so slow loading is proper?

**Steps to Reproduce**:
The following code execution times is ca. 4 minutes
var solutionName="Roslyn.sln";
MSBuildWorkspace workSpace = MSBuildWorkspace.Create();
Solution solution = workSpace.OpenSolutionAsync(solutionName).Result;

Subsequent execution of CreateCompilation requires next 1 minute.

**Expected Behavior**:
Times in the range of 1-2 minutes.

**Actual Behavior**:
Time 4 minutes

**Comment by jcouv** [comment]
Tagging @davkean

**Comment by VE-2016** [comment]
Issue relates to Performance Area

**Comment by davkean** [comment]
I don't own the workspace, and I'd need traces to make an informed comment but I suspect the majority of this time is doing [design-time builds](https://github.com/dotnet/project-system/blob/master/docs/design-time-builds.md). 

In VS, we use a large number of MSBuild nodes to consume and make use of CPU as efficiently as possible - I wonder if the MSBuild workspace is doing that.

**Comment by Pilchie** [comment]
@DustinCampbell has been the one most recently looking at `MSBuildWorkspace`.  MSBuildWorkspace is currently NOT using multiple nodes AFAIK.

**Comment by DustinCampbell** [comment]
MSBuildWorkspace also does not batch design-time builds. That will cut the time of OpenSolutionAsync roughly in half.

**Comment by Danielku15** [comment]
I also have the feeling that loading projects via `MSBuildWorkspace` is slow. I created a new style csproj class library with 1 file in it and loaded it via 
```csharp
var workspace = MSBuildWorkspace.Create(new Dictionary<string, string>
{
	["Configuration"] = "Debug",
	["Platform"] = "Any CPU"
});
var project == await workspace.OpenProjectAsync("ClassLibrary.csproj");
```
Loading of such a simple project takes ~3seconds on my machine (SSD, Core i7 2.3GHz, 20GB RAM). From a human perspective 3secs might not sound like a lot at the beginning. But from a machine/compiler perspective 3secs just for loading a single project is huge. 

I am writing currently a compiler based on Roslyn which translates my C# code to some other language. As a next step I want to create a `CSharpCompilation`, walk the `SyntaxTrees` and `SemanticModels` to generate some source code. The project loading appears to be a huge bottleneck. 

I understand that the new csprojs have some more 'magic' in place than usual tha require more to be done under the hood via msbuild (implicit references via SDK, package references, wildcard includes,...) but this is too much. 

I digged a bit into the details of this simple project compilation and there seem to be 3 main phases:

## 1. Project File Loading (~37%)
In this phase the MSBuild project is loaded into a `Microsoft.Build.Evaluation.Project`. I think there might not be a lot more optimization here from a Roslyn perspective.  The XML parsing only takes 3-4% of the project file loading and the actual project creation the rest. We would need to ask the guys from the MSBuild team to get this faster.  

## 2. Project Info Loading (~52%)
This code seems to be a big bottleneck. Based on the project file loaded, a project info structure is computed. This info structure should hold then all details about compilation settings, references, compile items etc. 

The big player here is the `BuildAsync`. Roslyn lets MSBuild run the `CoreCompile` target on the project using a custom ITaskHost (ICscHostObject/IVbcHostObject). MSBuild then will call the Roslyn components with all compilation settings and references.

It is somehow understandable why Roslyn is doing this: Mighty MSBuild tasks are running and do a lot of magic that are not Roslyns responsibility. Like nuget package restores, implicit references via SDK definitions and package refernces, manual extensions a developer might do to the compilation process etc. 

There already exists a manual project setting loading from the model, but it is only used in case the `CoreCompile` based execution did not do any initialziation. Creating a Roslyn compilation from those projects are usually failing due to missing metadata references (mscorlib etc.) and no PackageReference support. 

## 3. Mapping into Roslyn Workspace (~11%)
Having all details available from the project info it is mapped into the Roslyn workspaces structure. This consists of command line parsing, reference resolving and simple structure mappings. 

## Conclusion
The slow loading times are mostly caused by the exeuction through MSBuild and not by Roslyn itself. 

The `CoreCompile` target and the `Csc/Vbc` tasks are filled with some evaluated properties and items which are then passed again to the ITaskHost of Roslyn. The CoreCompile targets are provided by Roslyn itself which means we are running in circles here:  Roslyn Library > MSBuild > Installed Roslyn CoreCompile > Back to Roslyn Library. So in order to load a project via Roslyn, I need to start compiling my project using another Roslyn. With all the features on csprojs/vbprojs I guess this is simply needed, but a performance nightmare for devs loading project files via the API. 

Another thing is: Why does Roslyn even start manually loading and evaluating the project files if anyhow the inputs are normally loaded via MSBuild ITaskHost? This part of the code can definitly be removed or at least only executed on demand when initializing the compiler settings based on the data model. 

For those people who want to acquire a `Compilation` from a project/solution only, the Roslyn team could think of a more dedicated API which does this. I think that would allow a way faster solution to this use case by using what `BuildAsync` is currently doing only for loading the compiler inputs:

- Setup a ICscCompileHostObject and call CoreCompile on the input file with some MSBuild properties as input. 
- The host would first setup the compilation options and when Compile is called, the Compilation is generated which can then be loaded via property. 

I personally will try to implement this kind of system for my own project instead of relying on the MSBuildWorkspace.

**Comment by RipPer56** [comment]
@DustinCampbell any update?

**Comment by jinujoseph** [comment]
@jasonmalinowski  can you provide update and dupe/close
