### ISSUE TITLE
Refactoring suggestion: replace if-else with ternary operator

### ISSUE THREAD

**Issue by MkazemAkhgary** [dotnet/roslyn#23822]
like resharper, it would be nice to have suggestion to replace simple if-else assignments with ternary operators. 

    if(cond) x = i;
    else x = j;

would be replaced by 

    x = cond ? i : j;

its a cheap improvement for cheap but quite nice income.

**Comment by BhaaLseN** [comment]
If considered, I'd also like to see the inverse to undo trigger-happy colleagues that apply this to each and every ternary regardless of their length and readability.
Also, perhaps a veto _against_ making it a FixAll provider since this should not be applied blindly to everything. I'm game for simple expressions as shown in the example though.

**Comment by alrz** [comment]
Duplicate of https://github.com/dotnet/roslyn/issues/23306

**Comment by dpoeschl** [comment]
Closing as duplicate.
