### ISSUE TITLE
Cannot obtain symbol for nameof(Method)

### ISSUE THREAD

**Issue by JosefPihrt** [dotnet/roslyn#23902]
**Version Used**: VS 15.5.2

**Steps to Reproduce**:
```csharp
class Foo
{
    void Method()
    {
        string methodName = nameof(Method);
    }
}
```
**Expected Behavior**:
SemanticModel should return symbol for expression 'Method' inside nameof.

**Actual Behavior**:
SemanticModel returns null.

I tested property, field and event inside nameof and they all return a symbol.

**Comment by CyrusNajmabadi** [comment]
It may be because this is a method group.

**Comment by agocke** [comment]
@JosefPihrt Cyrus is right -- this is because `Method` is a method group. The reason why it works this way is because method groups don't have their own symbol, they are instead a group of individual method symbols.

Consider what would happen if you had overloads for your method, e.g.

```csharp
class Foo
{
    void Method()
    {
        string methodName = nameof(Method);
    }
    void Method(string s) { }
    void Method(int i) { }
}
```

Rather than have different behavior when there are no overloads, the compiler provides the same behavior each time: GetSymbolInfo on a method group produces a SymbolInfo where the `Symbol` property returns `null`, but `CandidateSymbols` returns all the methods (overloads) in the method group.

The reason why fields and properties behave differently is that there is no way to overload those members, so there is only ever a single symbol.

The preferred way of dealing with method groups would be to normally look at `Symbol`, but if `Symbol` is null and `CandidateReason` is `MemberGroup`, then you know that the target is a method group and all the method symbols you're interested in will be in `CandidateSymbols`.

**Comment by JosefPihrt** [comment]
That makes sense, thanks for explanation @agocke.
