### ISSUE TITLE
Proposal : Interface declared constructors

### ISSUE THREAD

**Issue by 6opoDuJIo** [dotnet/roslyn#2402]
I'd like to be able to declare needed constructors in interfaces, to provide requirements for constructors, like this: 

``` csharp
interface ISerializable
{
     ISerializable (SerializationInfo information, StreamingContext context);
     void GetObjectData(SerializationInfo info, StreamingContext context);
} 
```

In some cases it would be useful, like above.

**Comment by dsaf** [comment]
It could play nice with #2206.

**Comment by 6opoDuJIo** [comment]
Exactly. I did same proposal today :D

**Comment by HaloFour** [comment]
The problem with adding constructors to interfaces is that constructors are not virtual, and that constructors are not derived from the base class.  That would make it possible for a derived class to break the contract of the interface by simply being defined, which is not otherwise possible.

I think that having constructor constraints for generics is very useful, but I don't think that interfaces are the route to accomplish that.  Maybe if interfaces allowed for static contracts, then a static method could act as the factory instead of the constructor directly.

**Comment by paulomorgado** [comment]
Static factory methods (or even constructors) in interfaces might seem like a good idea.

But would that work for types implementing multiple interfaces?

I guess the implementation of the factory methods would have to account for the different factory implementations.

**Comment by aluanhaddad** [comment]
I think static interface members would definitely be the way to go. They would be much more powerful and general.
