### ISSUE TITLE
VB: Structure guidelines do not show tooltips any more

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#24067]
In Visual Studio 2017 (Enterprise) with code structure guidelines activated, the guidelines show fine. However, since some time, they do not show the tooltips while hovering over them any more. The tooltips used to show the nested statement hierarchy very nicely. Why, and what could I do about it? Thanks very mucht!

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/144528/vb-structure-guidelines-do-not-show-tooltips-any-m.html
VSTS ticketId: 520010_
_These are the original issue comments:_

Jinu Joseph [MSFT] on ‎11‎/‎12‎/‎2017, 06:56 PM (53 days ago): <p>We appreciate you taking the time to report this problem. We are currently prioritizing problems that are impacting a broad set of our customers, so we may not be able to investigate this one immediately. We know this problem is important to you, so we will continue to monitor it.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by sharwell** [comment]
I observe this if I open [AutomaticLineEnderCommandHandler.vb](https://github.com/dotnet/roslyn/blob/master/src/EditorFeatures/VisualBasic/AutomaticCompletion/AutomaticLineEnderCommandHandler.vb). Rather than show *useful* tooltips, all the tool tips just show `Friend`.

**Comment by gundermanc** [comment]
IBlockTags expect both a 'StatementSpan', which should map to the 'block header' (e.g. `if (foo)`) for the block, and a 'Span' which should map to the span of the entire block, except for the header (e.g.: from the ')' to the '}' in a typical if statement).

Since 15.0, Roslyn's been giving us the entire extent of the block as the 'Span' member. To work around it originally, we had a condition in the IBlockTags code that would detect such invalid input and try to do the right thing, but it's tripped up in some cases, causing the guessed 'HeaderSpan' to be zero in length.

I introduced IStructureTags in 15.3 which removes all of the unpredictability and lets the language owner explicitly specify where they want the guides. IBlockTags are now deprecated so I'd recommend moving over to IStructureTags.

This has been a problem in some other places as well, see: #16395.

**Comment by CyrusNajmabadi** [comment]
> I introduced IStructureTags in 15.3 which removes all of the unpredictability and lets the language owner explicitly specify where they want the guides

My recollectoin was that we allowed languages to specify the guide explicitly if they wanted.  But we also had a heuristic htat was good for all the construct cases we could envision across C#/VB (and C-style languages).  Namely, picking the left-most column of either the start/end point.

The reason we wanted this heuristic was because it is *hard* for the language to know this information.  languages don't know about editor columns.  When computing block structure they operate at an abstraction level that just things about lines/**chars**.  But how those chars are represented as columns is ultimately an editor decision.  For example, you might get entirely different guidelines depending on if you had 4 or 8 space tabs and the user had tabs.  That's because those tabs could then greatly affect the relative indentation of the start/end point.

As such, at the editor layer, having a heuristic that took that into account **when** the language didn't specify a guideline was highly desirable.

**Comment by gundermanc** [comment]
There is a heuristic baked into the tags which is currently used by Roslyn for positioning. We could have platformized the left-most-brace heuristic too, but my fear was that it's yet another hard-to-explain behavior in what is already a quite complex API. We've already had a lot of confusion as to what the behavior was for the IBlockTags, so for the IStructureTags I erred on the side of 100% explicit LS driven positioning when the StructureTag is fully specified. To address your concern with formatting, I chose to let LS decide horizontal alignment relative to a character in the document rather than a column. e.g.: If you choose 'e' in else if as the GuideLineHorizontalAnchor, we always align to that character's column, correctly accounting for indentation, tab size, etc.

This unfortunately makes the left-most-brace heuristic you are referring to a little bit more difficult, as your code would have to pick which point to use as the GuideLineHorizontalAnchor based on its indentation. Naively, you can assume the lower the index in the line, the less indented the character is. In reality, this gets less trivial if the document mixes tabs and spaces because you'd have to either 1) be aware of the editor's tab size (which is exposed via the editor options service, which I saw references to in the Roslyn tagger base class) or 2) expect and tolerate the rare cases in which tabs and spaces are mixed and your heuristic chooses the wrong brace. In either case, Roslyn controls the bounds of the block + adornment and is ultimately correct more often than now.

Without the left-most heuristic, if you provide the expected 'HeaderSpan' and 'GuideLineVerticalSpan' and 'GuideLineHorizontalAnchor' members, we draw the block tags as asked in all cases. For Roslyn, this means that if you specify the 'e' in 'else if' as the GuideLineHorizontalAnchor point, the adornment will always be horizontally aligned with the 'e', and will vertically span from the line containing the start of the GuideLineSpan to the line containing the end of the GuideLineSpan.

My understanding is that Roslyn treats an 'else if' as two distinct statements: the 'if/else' and the 'if' that comes just after the else. My recommendation for the Roslyn case would be to try and special-case 'else if' to appropriately populate the HeaderSpan with 'else if'. We can try and bake in heuristics that do the right thing, but ultimately, we don't know as much about the language as the LS does, and in trying to be smart and pick left-most point between the start of the HeaderSpan and the end of the GuideLineSpan, we end up with cases like this in C#:

```
MyLabel:   if (true) {
|
|
|                 }

```

Admittedly the one interesting case that I don't see a good solution for is misaligned guides in Razor embedded C#. The guides are aligning to the 'i' in 'if' instead of the open brace, so the addition of the '@' causes them to be indented one character:

![image](https://user-images.githubusercontent.com/5387680/35883654-cc9d785a-0b3c-11e8-9ca3-8a26d9ff481d.png)

If we do a left-most heuristic implementation, do you have any thoughts on how best to avoid invalid alignment with labels, pragmas, etc?

**Comment by gundermanc** [comment]
I was trying really hard to avoid it but I wonder if ultimately the API will need to have some form of custom projection resolver that can adjust the guidelines in projection scenarios.

**Comment by CyrusNajmabadi** [comment]
> but my fear was that it's yet another hard-to-explain behavior in what is already a quite complex API. 

I really don't think it would be that hard to describe.  It's pretty intuitive, and can be explained easily:

"We have a start point and an endpoint.  We take the column of each and draw whichever is leftmost".

> Naively, you can assume the lower the index in the line, the less indented the character is. In reality, this gets less trivial if the document mixes tabs and spaces because you'd have to either 1) be aware of the editor's tab size (which is exposed via the editor options service, which I saw references to in the Roslyn tagger base class) or 2) expect and tolerate the rare cases in which tabs and spaces are mixed and your heuristic chooses the wrong brace. In either case, Roslyn controls the bounds of the block + adornment and is ultimately correct more often than now.

But again, every language now needs to do this, and they have to get it correct.  It's unclear to me why this isn't a good default thing to do for all languages, allowing languages to opt out if any thought it was necessary (which i'm not even sure any would do).

> If we do a left-most heuristic implementation, do you have any thoughts on how best to avoid invalid alignment with labels, pragmas, etc?

What cases are you concerned about?

**Comment by CyrusNajmabadi** [comment]
> My understanding is that Roslyn treats an 'else if' as two distinct statements: the 'if/else' and the 'if' that comes just after the else. My recommendation for the Roslyn case would be to try and special-case 'else if' to appropriately populate the HeaderSpan with 'else if'.

I don't think that will work for cases like:

```c#
} else if (...) {
}
```

We don't want hte line coming out the 'e', we want the line coming out of whichever guy is leftmost :)

**Comment by CyrusNajmabadi** [comment]
I don't thin i understand this case:

> we don't know as much about the language as the LS does, and in trying to be smart and pick left-most point between the start of the HeaderSpan and the end of the GuideLineSpan, we end up with cases like this in C#:

```c#
MyLabel:   if (true) {
|
|
|                 }
```

Roslyn should be passing the BlockSpan.Span as the span from the end of ```)``` to the start of ```}``` and BlockSpan.StatementSpan should be the span from ```If``` to ```}```.  We should be taking the leftmost of those two points AFAICT.  "MyLabel:" shouldn't play into it at all.

**Comment by CyrusNajmabadi** [comment]
Structure guides look good to me in VB now:

![image](https://user-images.githubusercontent.com/4564579/217629430-b07a8cd6-7ec1-4aca-9fb7-054871017272.png)
