### ISSUE TITLE
"Implement Abstract Class" Shouldn't be Offered as Refactoring for Classes with Internal Abstract Members

### ISSUE THREAD

**Issue by JasonBock** [dotnet/roslyn#2407]
If I write this (VS2015 CTP6):

````
using System.Globalization;

public class x : EastAsianLunisolarCalendar
````

I get the "Implement Abstract Class" option, but since EastAsianLunisolarCalendar has internal members, the code that's generated is messed up:

````
using System;
using System.Globalization;

public class x : EastAsianLunisolarCalendar
{
	public override int[] Eras
	{
		get
		{
			throw new NotImplementedException();
		}
	}

	internal override EraInfo[] CalEraInfo internal override int MaxCalendarYear internal override DateTime MaxDate internal override int MinCalendarYear internal override DateTime MinDate public override int GetEra(DateTime time)
	{
		throw new NotImplementedException();
	}

	internal override int GetGregorianYear(int year, int era)
	{
		throw new NotImplementedException();
	}

	internal override int GetYear(int year, DateTime time)
	{
		throw new NotImplementedException();
	}

	internal override int GetYearInfo(int LunarYear, int Index)
	{
		throw new NotImplementedException();
	}
}
````

I shouldn't get that refactoring option if I really can't implement the members.

**Comment by jmarolf** [comment]
For context, in Visual Studio 2013 we would generate the following
```C#
using System;
using System.Globalization;

public class x : EastAsianLunisolarCalendar
{
    public override int[] Eras
    {
        get { throw new NotImplementedException(); }
    }

    public override int GetEra(DateTime time)
    {
        throw new NotImplementedException();
    }
}
```
Which gives the following compiler errors:

Description                                                                                                                                         | File      | Line | Column | Project
----------------------------------------------------------------------------------------------------------------------------------------------------|-----------|------|--------|---------
'ClassLibrary2.Class1' does not implement inherited abstract member 'System.Globalization.EastAsianLunisolarCalendar.MaxDate.get'                   | Class1.cs | 4    | 14     | ClassLibrary2
'ClassLibrary2.Class1' does not implement inherited abstract member 'System.Globalization.EastAsianLunisolarCalendar.MinDate.get'                   | Class1.cs | 4    | 14     | ClassLibrary2
'ClassLibrary2.Class1' does not implement inherited abstract member 'System.Globalization.EastAsianLunisolarCalendar.CalEraInfo.get'                | Class1.cs | 4    | 14     | ClassLibrary2
'ClassLibrary2.Class1' does not implement inherited abstract member 'System.Globalization.EastAsianLunisolarCalendar.MaxCalendarYear.get'           | Class1.cs | 4    | 14     | ClassLibrary2
'ClassLibrary2.Class1' does not implement inherited abstract member 'System.Globalization.EastAsianLunisolarCalendar.MinCalendarYear.get'           | Class1.cs | 4    | 14     | ClassLibrary2
'ClassLibrary2.Class1' does not implement inherited abstract member 'System.Globalization.EastAsianLunisolarCalendar.GetGregorianYear(int, int)'    | Class1.cs | 4    | 14     | ClassLibrary2
'ClassLibrary2.Class1' does not implement inherited abstract member 'System.Globalization.EastAsianLunisolarCalendar.GetYear(int, System.DateTime)' | Class1.cs | 4    | 14     | ClassLibrary2
'ClassLibrary2.Class1' does not implement inherited abstract member 'System.Globalization.EastAsianLunisolarCalendar.GetYearInfo(int, int)'         | Class1.cs | 4    | 14     | ClassLibrary2


The question here is what is the correcct thing to do for the user?  We could **not** generate an implementation of abstract type members, but there are several cases where this would be useful.

- The user does not have visibility on these members, but has access to the source code and wants to change the abstract type to allow others to implement a concrete type.
- The user does not have visibility on these members due to a configuration error in their build setup, and wants to change their InternalsVisibleTo settings to fix this problem.

In addition to this, the question is how do we tell the user **why** we can't generate the abstract type implementation? In Visual Basic the abstract type implementation is generated when the user hits `enter`.  If we disallowed generating an implementation if we knew their would be errors, VB users would be left with `Error BC30610: Class 'A' must either be declared 'MustInherit' or override the following inherited 'MustOverride' member(s)`.  This error is not sufficient to explain that members where not generated due to accessibility issues.  

Today, we generate members even if we know that they will not compile becasue they are inaccessible.  The hope is that the inaccessibility is a fixable problem.  The general principle we try an stick to with code generation is to always offer to generate something, even in the presence of errors.

I don't think that fixing this issue is going to lead to a better experience.

@Pilchie @DustinCampbell thoughts?

**Comment by Pilchie** [comment]
I'm okay with continuing to offer the refactoring - as you say, I don't generally like to hide things, because the developer might know more about what they are doing and what steps they need to take.

However, in @JasonBock's sample output, look at the `CalEraInfo` member.  It looks like we generate half of it, find the inaccessible type and then just start generating the next method, so we produce extremely strange code.

We should do a better job.

**Comment by jmarolf** [comment]
@dpoeschl could you verify that the bad code gen is fixed?
