### ISSUE TITLE
Diagnostic CodeFix for CS0121: ambiguous extension methods.

### ISSUE THREAD

**Issue by MaStr11** [dotnet/roslyn#24096]
**Version Used**: 

VS 15.5.2

**Steps to Reproduce**:

Method overload resolution for extension methods fails with error `CS0121: The call is ambiguous between the following methods or properties: 'method1' and 'method2'` if two extension methods with the same signature are in scope. A code fix should be provided that transforms the call to the extension method in a call to the static method by fully qualifying the desired method.

**Before the fix**:

```C#
using N1;
using N2;

namespace N1
{
    public static class Ext1
    {
        public static void Ambiguous(this object that) { }
    }
}

namespace N2
{
    public static class Ext2
    {
        public static void Ambiguous(this object that) { }
    }
}

namespace NTest
{
    public class C
    {
        void M()
        {
            new object().Ambiguous(); //CS0121
        }
    }
}
```

**After the fix**:

```C#
using N1;
using N2;

namespace N1
{
    public static class Ext1
    {
        public static void Ambiguous(this object that) { }
    }
}

namespace N2
{
    public static class Ext2
    {
        public static void Ambiguous(this object that) { }
    }
}

namespace NTest
{
    public class C
    {
        void M()
        {
            N1.Ext1.Ambiguous(new object()); 
        }
    }
}
```

Relates to #23326 and #24022.

**Comment by rtybanana** [comment]
I think this is an important problem which needs to be addressed. Migrating framework and language to newer versions often adds functionality that was previously serviced by third party libraries. If some extensions are now provided by the newer framework (with naming conflicts) then it cannot easily coexist with the library because of "ambigous call" compiler errors. The library cannot remove the conflicting extensions because they are still useful for older versions of the framework.

A simple way to disambiguate extension method calls with a namespace would be useful to prevent the need for bandaid solutions, wrapping extensions with new names which may very well create conflicts in future anyway.

My proposal would be for something similar to below. Using the dot syntax to provide a namespace may cause parsing headaches since it already has an existing meaning in this context (class member and extension accesses).

``` cs
using N1;
using N2;

namespace N1
{
    public static class Ext1
    {
        public static void Ambiguous(this object that) { }
    }
}

namespace N2
{
    public static class Ext2
    {
        public static void Ambiguous(this object that) { }
    }
}

namespace NTest
{
    public class C
    {
        void M()
        {
            N1.Ambiguous[Ext1](new object());
        }
    }
}
```

Here the call to the `.Ambiguous()` extension method is disambiguated by hinting the `[Ext1]` namespace.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of broad feedback on this.
