### ISSUE TITLE
QuickInfo always shows fully qualified type names for value tuple variables

### ISSUE THREAD

**Issue by jhinder** [dotnet/roslyn#24130]
**Version Used**: VS 15.5.3; VS 15.6.0 Preview 1.1

**Steps to Reproduce**:

1. Create a new implicitly typed variable of a value tuple type. (See snippets below.)
2. Invoke the QuickInfo tooltip on the `var` (or `Dim`) keyword.

**Expected Behavior**:

The tooltip shows one of the following for the tuple member types:

1. the keyword for tuple elements that are types with associated keywords (`string`, `int`, `object` etc),
2. the non fully qualified type name for types that don't fall in the first category, but are accessible via imported namespaces (e.g. `DateTime` when there's a `using System` directive),
3. the fully qualified type name in all other cases.

This is already the case for QuickInfos on the tuple variable itself (*(local  variable) (int, int) a*) and on the method invocation (*(int, int) Demo.MakeTuple&lt;int&gt;()*).

**Actual Behavior**:

The tooltip always shows the fully qualified type name (e.g. *(System.Int32, System.Int32)* for an `(int, int)` tuple) instead of the shorter variants described above.

**Sample code**:

```c#
public static void Test()
{
    var a = MakeTuple<int>();
    var b = MakeTuple<DateTime>();
}

private static (T, T) MakeTuple<T>() => (default, default);
```

```vb
Sub Test()
    Dim a = MakeTuple(Of Integer)()
    Dim b = MakeTuple(Of DateTime)()
End Sub

Function MakeTuple(Of T)() As (T, T)
    Return (Nothing, Nothing)
End Function
```

**Comment by jcouv** [comment]
The behavior for tuples seems consistent with the behavior for plain types (see below), so I think that is by-design.
I'll let @jinujoseph from IDE team confirm. Thanks

Tuple (hovering over `var`):
![image](https://user-images.githubusercontent.com/12466233/34793142-388dfc2c-f5ff-11e7-9579-d1b940952f7f.png)

Non-tuple (hovering over `var`):
![image](https://user-images.githubusercontent.com/12466233/34793210-6b783166-f5ff-11e7-94da-00faaa00914e.png)

That said, there is a difference between hovering over `var` and hovering over variable name. Hovering over variable name shows a shorter form (`DateTime` instead of `System.DateTime`).

![image](https://user-images.githubusercontent.com/12466233/34793311-c80ad636-f5ff-11e7-8964-9ed58b69c8fd.png)

![image](https://user-images.githubusercontent.com/12466233/34793300-b825a78c-f5ff-11e7-8b1d-d1f72fb7f706.png)

**Comment by jinujoseph** [comment]
That matches my understanding
