### ISSUE TITLE
Double click in editor selects too large an area

### ISSUE THREAD

**Issue by MkazemAkhgary** [dotnet/roslyn#24176]
When i double click inside an string i expect to select contents inside string not outside it. 

Following picture is taken after double click inside string.

I expect text editor to only select contents inside and not parantheses or semicolon.

![1515687373536745397570](https://user-images.githubusercontent.com/15255162/34834811-ea15d500-f6ea-11e7-877e-81a3575d84ee.jpg)

-----

Im not sure if any of this relates to roslyn. Couldnt find better repo for VS text editor.

**Comment by jinujoseph** [comment]
following with editor team

**Comment by sharwell** [comment]
I would *expect* this block to cover the functionality:

https://github.com/dotnet/roslyn/blob/67f2d4338d3889d89c642ae4effebd49751d49d7/src/EditorFeatures/CSharp/TextStructureNavigation/TextStructureNavigatorProvider.cs#L63-L67

I'm not sure if the bug lies in the Roslyn implementation or if the editor is just failing to use `ITextStructureNavigator.GetExtentOfWord` for double click operations.

**Comment by jinujoseph** [comment]
moved over to editor [team](https://devdiv.visualstudio.com/DevDiv/NET%20Developer%20Experience%20Productivity/_queries/edit/559428)
