### ISSUE TITLE
Navigate to decompiled sources: Reference assemblies are not supported

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#24185]
For example, in Roslyn i went to Debug.Assert, and this is what i got:

```c#
		[Conditional("DEBUG")]
		public static void Assert(bool condition)
		{
		}
```

Now, my guess is this is because of reference assemblies.  However, it's hard to tell what's going on.  The top of the file is just:

![image](https://user-images.githubusercontent.com/4564579/34843308-ea760d3a-f6c2-11e7-9168-6d5526838b79.png)

Perhaps a comment could be added that's similar to what we get with normal metadata-as-source:

```c#
#region Assembly System.Collections.Immutable, Version=1.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
// C:\Users\cyrus\.nuget\packages\system.collections.immutable\1.3.1\lib\netstandard1.0\System.Collections.Immutable.dll
#endregion
```

**Comment by MaStr11** [comment]
This is the code that needs to be changed [MetadataAsSourceFileService.cs#L191](https://github.com/dotnet/roslyn/blob/master/src/EditorFeatures/Core/Implementation/MetadataAsSource/MetadataAsSourceFileService.cs#L191) to get the *real* assembly but I have no idea how this could be done. From what I can tell it seems @sharwell added the comment

` // TODO: retrieve path to actual assembly instead of reference assembly`

@sharwell How do you think this could be done?

@CyrusNajmabadi 
> Perhaps a comment could be added that's similar to what we get with normal metadata-as-source

Those comments are produced in [AbstractMetadataAsSourceService.AddAssemblyInfoRegionAsync](
https://github.com/dotnet/roslyn/blob/master/src/Features/Core/Portable/MetadataAsSource/AbstractMetadataAsSourceService.cs#L71) and (if I got that right) needs to be inserted at [this position](https://github.com/dotnet/roslyn/blob/master/src/EditorFeatures/Core/Implementation/MetadataAsSource/MetadataAsSourceFileService.cs#L202). This would require to make `AddAssemblyInfoRegionAsync` available in `MetadataAsSourceFileService` either via copy&paste (this is not as bad as it sounds, because *decompiled source* and *metadata source* might gone have different comments inserted after all) or by refactoring.

@sharwell and @CyrusNajmabadi This issue needs some more advice by you on what needs to be done in detail as I don't see how this is supposed to look like, when it's done. I also wonder whether these are not two issues actually.

**Comment by MaStr11** [comment]
So #24291 addresses the *reference assembly problem* and this issue can be reduced to the *header comment*. Can you describe what the header should look like? In a nutshell: Is the header from *metadata* and *decompiled* exactly the same or not? If you can answer that it is clear whether [ AbstractMetadataAsSourceService.AddAssemblyInfoRegionAsync](https://github.com/dotnet/roslyn/blob/master/src/Features/Core/Portable/MetadataAsSource/AbstractMetadataAsSourceService.cs#L71) should be reused or copied.
