### ISSUE TITLE
Add some dead code analysis

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#24225]
We now fade unreachable code and should be able to start identifying dead code.

To start, it would be nice to fade dead private and internal methods.

**Comment by CyrusNajmabadi** [comment]
Note: these will likely need CompilationEndActions.  I explored this at one point, but gave up because we disable those by default.

Note: internal methods are even harder as you have to analyze across compilations.  

If you did start with private methods, i think it would be great if the compiler could expose this data as it should be able to generate that information very easily when doing the full compilation pass.

**Comment by Neme12** [comment]
This is kind of an annoying feature because when you're writing a new method, nobody is using it yet and everything is faded out.

**Comment by jcouv** [comment]
I just want to point out that code coverage analysis helps catch unused private methods/members, as well as internal ones.

**Comment by mattdkerr** [comment]
@Neme12 I believe some other analysis tools only detect it as dead in that situation if it's not part of an interface or a public method

**Comment by mavasani** [comment]
Re-opening as we still need some follow-up changes from https://github.com/dotnet/roslyn/issues/29519 to enable the added rules by default.

**Comment by mavasani** [comment]
This is now complete.

**Comment by Neme12** [comment]
> This is kind of an annoying feature because every time you're writing a new method, nobody is using it yet and everything is faded out.

I really like the way it turned out, with just the method name being faded out 🎉 It didn't occur to me as an option.
