### ISSUE TITLE
Pdb files for a simple app different with /features:deterministic

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#2422]
While comparing .dll and .pdb compiled with /features:deterministic using the compiler build from 2015/04/30, 6 bytes in the pdbs still differ, unfortunately:

![pdbdifference](https://cloud.githubusercontent.com/assets/679326/7425172/f4230d40-ef60-11e4-8c06-0de1cf1ab350.png)

Subsequent (3rd) compilation only changes the 4 byte group again (2 byte group remains same):
![pdbdifference2](https://cloud.githubusercontent.com/assets/679326/7425195/3cfc4e0a-ef61-11e4-87b7-0cf2877d2451.png)

/cc @gafter @tmat

**Comment by tmat** [comment]
Yes, that's a known issue. We don't know what data is there and won't probably be able to fix it.

**Comment by gafter** [comment]
Our native PDB writing library copies random data from memory into spaces between the PDB sections. We've gone as far as we can without spending a couple of months rewriting it, which we do not plan to do.

I'm keeping this open for now for further comment, but we are more likely to replace the PDB writer with one based on a more compact (deterministic) format rather than try to replace the existing writer.

**Comment by gafter** [comment]
@KirillOsenkov By the way, I am so glad to see that you're giving this stuff a try. Thank you! And thank you for letting us know what you're finding.
