### ISSUE TITLE
SIMD 64 Bit Memory-Alignment Bug

### ISSUE THREAD

**Issue by Gallimathias** [dotnet/roslyn#24233]
**Version Used**: .NET 4.7.1 C# 7.2

**Steps to Reproduce**:

1. Install engenious via nuget or wrote your own packed Vector3 or use a other packed Vector3
2. Cast with pointer to System.Numerics.Vector3 or own unpacked Vector3
3.  Just do the same thing, just put the pointer in a variable before it.
4. Compare the results

**A brief example:**

C#-Code:

````CSharp
        static unsafe void Test()
        {
            var value = new Vector3(0, 0, -41);
            var a = *(Numerics.Vector3*)(&value);
        }

        static unsafe void TestB()
        {
            var value = new Vector3(0, 0, -41);
            var d = &value;
            var a = *(Numerics.Vector3*)d;
        }
````

IL-Code:

````CIL
                 .method private hidebysig static 
			void Test () cil managed 
		{
			// Method begins at RVA 0x2144
			// Code size 33 (0x21)
			.maxstack 4
			.locals init (
				[0] valuetype [engenious]engenious.Vector3 'value',
				[1] valuetype [System.Numerics.Vectors]System.Numerics.Vector3 a
			)

			IL_0000: nop
			IL_0001: ldloca.s 'value'
			IL_0003: ldc.r4 0.0
			IL_0008: ldc.r4 0.0
			IL_000d: ldc.r4 -41
			IL_0012: call instance void [engenious]engenious.Vector3::.ctor(float32, float32, float32)
			IL_0017: ldloca.s 'value'
			IL_0019: conv.u
			IL_001a: ldobj [System.Numerics.Vectors]System.Numerics.Vector3
			IL_001f: stloc.1
			IL_0020: ret
		} // end of method Program::Test

		.method private hidebysig static 
			void TestB () cil managed 
		{
			// Method begins at RVA 0x2174
			// Code size 35 (0x23)
			.maxstack 4
			.locals init (
				[0] valuetype [engenious]engenious.Vector3 'value',
				[1] valuetype [engenious]engenious.Vector3* d,
				[2] valuetype [System.Numerics.Vectors]System.Numerics.Vector3 a
			)

			IL_0000: nop
			IL_0001: ldloca.s 'value'
			IL_0003: ldc.r4 0.0
			IL_0008: ldc.r4 0.0
			IL_000d: ldc.r4 -41
			IL_0012: call instance void [engenious]engenious.Vector3::.ctor(float32, float32, float32)
			IL_0017: ldloca.s 'value'
			IL_0019: conv.u
			IL_001a: stloc.1
			IL_001b: ldloc.1
			IL_001c: ldobj [System.Numerics.Vectors]System.Numerics.Vector3
			IL_0021: stloc.2
			IL_0022: ret
		} // end of method Program::TestB
````

**Expected Behavior**: Both methods should produce the same result on all systems.

Method Test: a should be <0. 0. -41>
Method TestB: a should be <0. 0. -41>

**Actual Behavior**: When you cast a packed vector into an unpacked vector, the result will always be a zero vector on some computers with 64 Bit and the use of a direct assignment.

Method TestB works on all systems no matter if 32 Bit or 64 Bit.
Method Test does not work as 64 bit version on some systems. Could this be related to the CPU used?

My Results compiled as 64 Bit:

Method Test: a is <0. 0. 0>
Metod TestB: a is <0. 0. -41>

On my PC, Method Test doesn't work. My CPU is Intel i7-5960X.

The only difference in CIL are the following lines:

IL_001a: stloc.1
IL_001b: ldloc.1

**Comment by mikedn** [comment]
This looks more like a JIT bug so it probably belongs in the coreclr repository.

Also, it's not clear how did you figure out that the result is sometimes <0, 0, 0>. Your example code does not do anything with `a`, it does not display it, it does not return it etc.

**Comment by jvbsl** [comment]
It was tested with the results shown by the debugger. As well as in another Project where these values where used for further calculation of forces. Which on some systems(all 64 Bit) worked perfectly fine and on other systems there wasn't any movement at all(no movement is the same as no forces and as zero vectors).

**Comment by mikedn** [comment]
Can you post the assembly code generated for method Test()? You should be able to get it from the VS debugger by using "go to disassembly". On my system everything I tried seems to be working fine.

On a side note - I'm not sure if what you're trying to do in that project makes sense. There's a good chance that the `USE_SIMD` code is not as fast as you may expect it to be. Especially in the case of `Vector3`.

**Comment by jvbsl** [comment]
You mean you aren't sure that it makes sense because it could be slower than the original Code?
That's true if the system doesn't support SIMD, because unfortunately C# jitter doesn't seem to be able to optimize readonly boolean variables like I would want to(of course you could change it with Reflection -> Undefined behaviour please^^) so it get's a lot slower than using my own actual code if SIMD is not supported. Otherwise it gets a lot faster though, so it does exactly what I want.

If you mean it does not make sense to pack my Vectors. It does at first memory Usage, and secondly I need it packed for OpenGL, otherwise I would need to make a transform method on which I would lose a lot of performance as well.

**Comment by mikedn** [comment]
> You mean you aren't sure that it makes sense because it could be slower than the original Code?

Yes. Taking the address of the value basically ensures that the value will be forced into memory (if it was in register). Then it has to be loaded back as `System.Numerics.Vector3` and that's not very cheap either because there's no such thing as a "SIMD vector with 3 components" in SSE/AVX so you basically get 2 separate loads than are then stitched together into a SSE register.

I'm not sure what readonly, reflection and packing have to do with this. To be clear, I'm referring to this type of code:
```asm
Fast.Vector3 res= (*(Fast.Vector3*)&value1 + *(Fast.Vector3*)&value2); 
```

**Comment by jvbsl** [comment]
I can assure you that the code still is faster than not using SIMD. Of course I'm clear on the part, that all the casting isn't that nice, but I can't use System.Numerics. Vector directly, and I'm not able to directly use SIMD in C# either. So in theory I could always create the new value explicitly, but is that really faster? I know that in C++ it wouldn't be. But yeah C# isn't that good at optimizing of course.

What i was referring to with readonly and reflection is that:
https://github.com/dotnet/corefx/blob/master/src/System.Numerics.Vectors/src/System/Numerics/Vector3.cs#L116
https://github.com/dotnet/corefx/blob/76dd41773b0ac79f6cde2bd681eaa8b1aeb91298/src/System.Numerics.Vectors/src/System/Numerics/Vector_Operations.cs#L528
So the jitter doesn't seem to be able to optimize the path of the if, even if the returned value is constant. So the code if there isn't any SIMD is always gonna be slower as it would normally, because of additional value checks and jumps. Even if it was possible to change the value at runtime in my opinion the jitter should be able to optimize it to compile it as a constant path(so no value check and no jump, cause the value never changes anyway). It is possible to change these values with reflection though and if someone would change normally unchangeable values, the jitter should just have undefined behavior in my opinion, because the benefits of the optimization are more important than behavior of stuff, with shouldn't even be possible anyway^^

And I exactly knew which code you was referring to, but it seems that you don't understand what I'm talking about. The cycle count of the division itself should for a Vector3 still be a lot less, even combined with the needed cycles for the casts. As I said before I already measured the difference of time needed.

Apart from that, thats not even the Point the issue is making. It's not about if the code makes sense or it could be done better. But about the determinability of the IL/C#-code which should theoretically be the same on all platforms, and which it definitely is not.
The thing is that the two different codes shown above should(at least in my opinion) logically result in the same outcome, which it does not, and that is actually what the whole issue is about. What MS wants to do about it is on there part. And it is quite possible that my whole casting won't be possible platform-independant anymore, by what I still would be completely fine, as long as it is deterministic.

**Comment by mikedn** [comment]
> So the jitter doesn't seem to be able to optimize the path of the if, even if the returned value is constant.

As far as I can see it does that. If I add 2 `System.Numerics.Vector3` in .NET 4.7.1 x86 I don't see any trace of that `if` in the generate code.

> Apart from that, thats not even the Point the issue is making.

I know, that's why I said "On a side note - I'm not sure if what you're trying to do ...". If you measured it and it's faster, good.

>  But about the determinability of the IL/C#-code which should theoretically be the same on all platforms, and which it definitely is not.

I said in my first post - this looks like a JIT bug. It's very unlikely that it has anything to do with IL, C# and Roslyn. I can't reproduce it myself and you haven't posted the assembly code so I can only guess. AFAIR, the JIT did have some issues with Vector3 in the past.

**Comment by jvbsl** [comment]
> As far as I can see it does that. If I add 2 System.Numerics.Vector3 in .NET 4.7.1 x86 I don't see any trace of that if in the generate code.
And it does make sense that it works with x86, because the alignment should be on full register size(32-bit == sizeof(float)) anyway, so there wouldn't be any alignment in both structs, so the memory layout of both structs should be the same anywhere with x86. It's about x64, where the jitter produces different Code on different platforms(or same Code and different results, will need to look into that, need to ask a friend for his assembly results again).
than it's possibly the casts that cost the additional time, but there are other cases in which it couldn't do it(on older .Net versions at least).
The difference we saw on one platform was that it uses AVX to move while using the temporary variable. But why isn't it done with the other code, that's what I'm still curious about.
Actually we hoped for an answer of a Microsoft developer before opening another issue, but you where persistent enough to do it now, and we will link the issues together ;)

**Comment by mikedn** [comment]
> And it does make sense that it works with x86,

The reason why it works on x86 is that the x86 JIT used by the .NET Framework doesn't support hardware acceleration. Anyway, my comment about x86 was related to the `if (IsHardwareAccelerated)` line you pointed to.

> The difference we saw on one platform was that it uses AVX to move while using the temporary variable. But why isn't it done with the other code, that's what I'm still curious about.

Well, it uses AVX if it's available. Otherwise it uses SSE2.

**Comment by gafter** [comment]
Issue moved to [dotnet/coreclr #16068](https://github.com/dotnet/coreclr/issues/16068) via [**ZenHub**](https://www.zenhub.com/)
