### ISSUE TITLE
.editorconfig some values aren't recognizable/supported by VS

### ISSUE THREAD

**Issue by eyalsk** [dotnet/roslyn#24248]
**Version Used**: Visual Studio Community 2017 v15.5.3

1. `flush_left` is documented [here](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/editorconfig-code-style-settings-reference.md) but [here](https://gist.github.com/jmarolf/0e165b27a498b49e3b3512004ea9d8b8) it's documented as `left_most` and yet VS doesn't recognize either of these values.

2. `type_parameter` and `namespace` they are documented [here](https://gist.github.com/jmarolf/0e165b27a498b49e3b3512004ea9d8b8) but are not documented anywhere else. @jmarolf does VS really support these values?

3. <s>`when_on_single_line` is documented [here](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/editorconfig-code-style-settings-reference.md) but it's not mentioned [here](https://gist.github.com/jmarolf/0e165b27a498b49e3b3512004ea9d8b8) and VS doesn't recognize it.</s> Resolved.

It can be really confusing because you don't know whether VS supports these values or they are just aren't recognizable by the IDE and these values are important to my style of coding, probably to others too.

**Comment by jmarolf** [comment]
> `flush_left` is documented here but here it's documented as `left_most` and yet VS doesn't recognize either of these values.

That is part of the core VS editorconfig support, which I didn't implement.  @olegtk Do you know what the story is here?

>` type_parameter` and `namespace`  they are documented here but are not documented anywhere else. @jmarolf does VS really support these values?

they are not currently supported due to how the analysis engine works.  We wanted to add support but ran out of time. As soon as support is added we can add the equivalent support in editorconfig.

> `when_on_single_line` is documented here but it's not mentioned here and VS doesn't recognize it.

This should work or its a bug, see [here](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp.Workspaces/CodeStyle/CSharpCodeStyleOptions.cs,123)

Here is the official documentation of what is supported.  If something on here doesn't work its a bug we need to fix.
- [.NET coding convention settings for EditorConfig](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference)
- [Naming Conventions for EditorConfig](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-naming-conventions)

**Comment by eyalsk** [comment]
@jmarolf Thank you, I'll create a new issue for `when_on_single_line`.
