### ISSUE TITLE
Code run in OOP host doesn't respect VS' culture settings

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/roslyn#24317]
**Version Used**: 
VS 15.6-preview2

**Steps to Reproduce**:

1. Install Spanish VS language pack
2. Start devenv.exe in Spanish local: devenv.exe /LCID 3082
3. File => new Web App
4. Run culture sensitive code in OOP host

**Expected Behavior**:
- Culture sensitive code returns Spanish based information

**Actual Behavior**:
- English based information is returned

**Notes**:
This seems to be caused by the OOP host not having its current culture set to what VS has its language settings set to.

/cc @heejaechang

**Comment by heejaechang** [comment]
@Pilchie @jasonmalinowski @AArnott @dotnet/roslyn-ide does anyone know where VS gets culture setting? apparently user can set VS culture different than host (OS). getting current culture from VS process would be enough?

**Comment by AdamSpeight2008** [comment]
@NTaylorMullen Is it US English? or UK English? If it US then I've experience it with UK English.

**Comment by AArnott** [comment]
ServiceHub uses the system default culture. To override it you'd need to set `CultureInfo` thread-static properties within your service (on any and all threads you run on that need to format or look up localized resources). Given I'd set it on that type, my inclination would be to look up those values from the VS process from the same type, then send them over via JSON-RPC to the service. 

Our fix for https://github.com/Microsoft/vs-streamjsonrpc/issues/86 is likely to give OOP servers the ability to pass in a `SynchronizationContext`, which could help make it easier to effectively apply `CultureInfo` on any thread your work gets scheduled on.

If there is a process-wide setting you can set, within the Roslyn OOP server process you might set that instead as a simpler solution.

**Comment by NTaylorMullen** [comment]
> @NTaylorMullen Is it US English? or UK English? If it US then I've experience it with UK English.

US english.

**Comment by heejaechang** [comment]
@AArnott thank you. do you know where in VS it sets culture for VS process when it is explicitly given which is different than system culture?

**Comment by heejaechang** [comment]
@AArnott I think I found where VS does this.

http://index/?leftProject=Microsoft.VisualStudio.Platform.AppDomainManager&leftSymbol=wok83tw8yxy7&file=VsAppDomainManager.cs&line=108

but reading through, it feels like it would be best if it gets set when appdomain for us is created by service hub. like devenv.exe.config, can servicesub service.json file has config for culture as well? so that one can either specify which culture its app domain wants or specify its wants same default culture as its host.

https://msdn.microsoft.com/en-us/library/system.globalization.cultureinfo.defaultthreadcurrentuiculture(v=vs.110).aspx
https://msdn.microsoft.com/en-us/library/system.globalization.cultureinfo.currentculture(v=vs.110).aspx

otherwise, every service needs to set the culture on every single call.

**Comment by AArnott** [comment]
Ah! I didn't know about the `DefaultThreadCurrentUICulture` property. Cool. At least that means you don't have to set it on every thread yourself.

A given service's AppDomain serves _n_ clients, and those clients might be node, .NET, python, etc. The client may not even have a CultureInfo-like setting, and even if it did, there are _n_ of them, and only one could win if we were to do it at an AppDomain level. We could try to do a 'best effort' where the first client wins (even if that client has no culture to prescribe) and when the appdomain is created, the client has passed the culture to the controller, which passed it to the host process so it can be fed into the AppDomain. 
Alternatively (and IMO far more simply) you can simply add a SetCulture method on your service, and make sure that your client calls it at least once. Since it would set static properties, you'd only need to call it once -- not from every single one of your methods.
