### ISSUE TITLE
Verify unused strings are eventually removed from the SQLite string table

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#24645]
**Version Used**: 15.5.1

:link: https://developercommunity.visualstudio.com/content/problem/164554/cpu-at-20-constantly-in-debug.html

In the performance trace included with the feedback ticket, more than 2GB is allocated in `TryFetchStringTable`, with more than 700MB allocated just for the `byte[]` buffers used to hold the raw database string contents. This indicates one of the following is occurring:

1. `TryFetchStringTable` is called too many times
2. The database contains far more strings than are actually needed by the IDE
3. The string table is simply gigantic for this project

**Comment by CyrusNajmabadi** [comment]
Good lord.  The string table just holds project filepath, name, and document filepaths and names, as well as generating a key per document in the project.  To have that allocate that much is insane :)

> TryFetchStringTable is called too many times

That's possible.  It's intended to only be called once.  Namely when the provider starts up.  However, there are potential issues that may cause us to fail to get the table and to try over and over again.  namely:

```c#
            catch (SqlException e) when (e.Result == Result.BUSY || e.Result == Result.LOCKED)
            {
                // Couldn't get access to sql database to fetch the string table.  
                // Try again later.
                return false;
            }
```

Note: the major problem here is that if we fail to get the string table once for the solution, we may attempt to get it for *every* project we then load.  We don't keep any sort of data around to indicate that we loaded it completely, and this should not try to load it for the next project.

SPecifically: if 'BulkPopulateIds' is passed 'fetchStringTable: true', it should attempt to load each project, and for each project it should try to load the string table . But once it succeeds, it shouldn't keep loading the table.  in otehr words, the code should become more like:

```c#
            foreach (var project in solution.Projects)
            {
                fetchStringTable = BulkPopulateProjectIds(connection, project, fetchStringTable);
            }
```

**Comment by CyrusNajmabadi** [comment]
This system was changed heavily since 15.5.1.  We used to use string-concatenation to produce unique 'keys' to do key/value lookup in the DB.  This meant a ton of additional allocs of special strings representing important combinations of keys.  Importantly, this meant concatting things like ProjectFileFolder/ProjectFilePath/DocumentFolder/DocumentPath/ProjectFlavor/FeatureId.  This led to LOTS of string combinations and LOTS of allocs.

We've since changed this to be entirely different.  Now, we simply map from a string (like ProjectFileFolder) to an integral ID.  And we use a tuple (at the DB level, not the runtime level) of integral IDs to key our values.   This dropped hte memory needs here massively.

We also put all these strings into different tables.  So we're not reading the old tables in the DB.  So we shouldn't be impacted by those large string permutations placed in the DB from previous instances of VS.
