### ISSUE TITLE
Roslyn version mismatch between VS2015RC and NuGet 1.0.0-rc2

### ISSUE THREAD

**Issue by dzeitlin** [dotnet/roslyn#2465]
Roslyn shipped with **VS2015** is **1.0.0.50411** (AssemblyFileVersion)
Roslyn **1.0.0-rc2** from NuGet is **1.0.0.50417** (AssemblyFileVersion)

All VS2015 CTPs releases before RC had the same Roslyn versions shipped and in NuGet, actually assemblies were identical.
It's very important to have these assemblies synchronized, our team develop compiler C#->JS (http://duoco.de/) for Visual Studio and of course use and test using NuGet assemblies.
Now we are considering to use Visual Studio 2015RC assemblies instead.
Thanks

**Comment by sharwell** [comment]
The assembly file version isn't used for the assembly binding process, so it doesn't sound like you are describing a binary compatibility problem here (e.g. with strong names). Would it be sufficient to simply identify the commit hash of the commit used for 1.0.0.50411, and the commit hash used for 1.0.0.50417, so you could compare the source and see if any internal changes exist that would affect your work?

**Comment by jmarolf** [comment]
The version numbers are different, but there are no differences in the binary contents.  The numbers are different because I triggered an additional build of the [Microsoft.CodeAnalysis.CSharp.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.CSharp.FxCopAnalyzers/) nuget package so that we could get the bugfix from pull request #2084 into RC.

**Comment by hmemcpy** [comment]
How is Roslyn going to handle (semantic) versioning from now on? The version has been 1.0.0 for a while now. Is Roslyn going to adhere to semver rules from now on, with respect to changes in the public API?

**Comment by dhusemann** [comment]
Any way by rtm to just use Simver on the assemblies??

**Comment by sharwell** [comment]
@hmemcpy Your comment is misleading, because it implies a stable version of the library has been released.

I'm assuming steps will be taken to ensure strong-named libraries built against the stable 1.0.0 release use the correct assembly at runtime. For example, this could have one of the following forms:

1. The stable releases of Roslyn use a different strong name key than pre-release builds. This is the strategy I use for most of my libraries now.
2. Visual Studio or some other installer places the stable binaries in the GAC, which I believe has the highest precedence during the binding process.

**Comment by Pilchie** [comment]
@sharwell We plan to do neither of those things :)  I expect that once we fork for the 1.0 release, we will increment the version numbers (NuGet and Assembly) in master.  Thus, you'll be able able to use the new binaries by adding binding redirects if you want to, but they won't automatically resolve.
