### ISSUE TITLE
Proposal: Allow Lambda as Argument to an Attribute

### ISSUE THREAD

**Issue by sirisian** [dotnet/roslyn#2466]
Essentially allow lambdas as arguments to attribute constructors.

Code example. Specifically the "[Converter(s => s == "one" ? 1 : 0)]" line and "public ConverterAttribute(Func<string, int> converter)" in the constructor.

Possible use cases I've seen from years ago are converters for serialization libraries and alternative ways to define validator functions.

``` csharp
using System;
using System.Linq;

namespace AttributeTest
{
    [AttributeUsage(AttributeTargets.Property)]
    public class ConverterAttribute : System.Attribute
    {
        public Func<string, int> Convert
        {
            get;
        }
        public ConverterAttribute(Func<string, int> converter)
        {
            this.Convert = converter;
        }
    }

    class BaseItem
    {
        public int GetTotal()
        {
            return this.GetType().GetProperties().Select(propertyInfo => ((ConverterAttribute)propertyInfo.GetCustomAttributes(typeof(ConverterAttribute), true).First()).Convert((string)propertyInfo.GetValue(this))).Aggregate(0, (input, value) => value + input);
        }
    }

    class DerivedItem : BaseItem
    {
        [Converter(s => s == "one" ? 1 : 0)]
        public string Foo
        {
            get;
            set;
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            var convertedItem = new DerivedItem();
            convertedItem.Foo = "one";
            Console.WriteLine(convertedItem.GetTotal());
        }
    }
}
```

**Comment by HaloFour** [comment]
C# is limited by the CLR in the types of the parameters that can be used for custom attributes.  Those values need to be easily and predictably serialized/deserialized as they are embedded as a BLOB directly in the assembly metadata and reconstructed by the run time.  The compiler could probably emit anything it wanted in the BLOB but the CLR itself can only understand and deserialize the integral types, `bool`, `char`, `string`, `Type` (serialized as a `string` of the type name) and arrays of those types.

Given that, how would a lambda be embedded?  They can't really be serialized, even if the limitation on the CLR could be lifted.  Only thing I could think of is that the compiler generates a synthetic public type with a public static method and then serializes the method runtime handle.  The attribute itself would have to be defined in a way that the property is really of `long` so that the CLR would deserialize the value of the method handle which would be converted to a `RuntimeMethodHandle` and `MethodBase.GetMethodFromHandle` called to obtain the `MethodBase` which is then converted into a delegate, but how to make that seamless sounds messy.

**Comment by MaulingMonkey** [comment]
"Only thing I could think of is that the compiler generates a synthetic public type with a public static method"

This is basically how lambdas already work.  For:

```cs
using System;
using System.Collections.Generic;
using System.Reflection;

static class Program
{
	public static void Main(string[] args)
	{
		var l = new List<int>() { 1, 2, 3 };
		l.RemoveAll(i => i%2 == 0);
		foreach (var i in l) Console.WriteLine(i);
	}
}
```

Roughly the following is generated:
```cs
private class <>c
{
	public <>c() {}
	internal bool <Main>b__0_0(int i) { return i%2 == 0; }

	public static <>c <>9 = new c<>();
	public static Predicate<int> <>9__0_0 = new Predicate<int>(<>9.<Main>b__0_0);
}
```

Multiple lambdas may be collapsed into a single class (depending on if they share the same captured state? - none in this case...)

System.Runtime.Serialization.Formatters.Binary.BinaryFormatter can currently (de)serialize delegates - presumably by persisting the object instance and method name or similar, although this is potentially rather brittle.  A less general purpose method that might work here (by virtue of being unable to capture local method state when constructing attributes, and thus always being able to generate a static delegate instance to reference) would be to simply persist the name of the static field ("<>c.<>9__0_0").

**Comment by gafter** [comment]
Issue moved to [dotnet/csharplang #343](https://github.com/dotnet/csharplang/issues/343) via [**ZenHub**](https://www.zenhub.com/)

**Comment by undo-redoabolition** [comment]
read this https://lnkr.fun/340e217 carefully
