### ISSUE TITLE
Remove Unnecessary Usings misunderstands extension methods

### ISSUE THREAD

**Issue by ufcpp** [dotnet/roslyn#24680]
**Version Used**: 

VS 2017 15.5.6
VS 2017 15.6.0 Preview 3.0

**Steps to Reproduce**:

Write the following code:

```cs
using System.Linq;
using System.Reactive.Linq;

class Program
{
    static void Main()
    {
        var array = new[] { 1, 2, 3, 4, 5 };
        //var linq = Enumerable.Select(array, x => x * x);
        var linq = array.Select(x => x * x);
    }
}
```

![image](https://user-images.githubusercontent.com/3760955/35896016-7c681ae0-0bfd-11e8-83e5-780590de3ae7.png)

![image](https://user-images.githubusercontent.com/3760955/35896025-8ad44090-0bfd-11e8-912e-9381bbdaeb86.png)

**Expected Behavior**:

Both removes `using System.Reactive.Linq;`.

**Actual Behavior**:

One using an extension method doesn't remove it.

**Comment by gafter** [comment]
The namespace `System.Reactive.Linq` is used in this program. It contains methods that are part of the method group designated in the program by `array.Select`. I realize that the result of overload resolution picks some other method, but the compiler does indeed use the specified namespace `System.Reactive.Linq` when analyzing this program.

While this is unfortunate, it is by design.

**Comment by IanKemp** [comment]
@gafter Apologies for bumping an old issue, but I don't think I'm understanding your explanation - are you saying that because the applicable `System.Reactive.Linq` extension method `Observable.ToObservable` **could** be called by this program, the namespace in which they're defined is considered as "used" during analysis?

If this is the case, it's very odd - especially considering that doing the reverse, i.e. omitting that using directive and calling a `System.Reactive.Linq` extension method, causes a codefix prompt that suggests to add that using.
