### ISSUE TITLE
Please make IDocumentTrackingService public

### ISSUE THREAD

**Issue by SLaks** [dotnet/roslyn#2475]
To make VSEmbed report errors as the user types, I need to force background diagnostic analysis to run in the high priority processor (currently, I have a noticeable and frustrating delay from the normal processor)

To do this, I need to export [`IDocumentTrackingService`](http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/SolutionCrawler/IDocumentTrackingService.cs,b328e370914849e6,references) and implement `GetActiveDocument`.  

Can you please make this interface public?

**Comment by heejaechang** [comment]
@srivatsn @Pilchie is supporting people to use Roslyn to their own host (up to Editor layer) one of scenarios we want to support? I know we are trying to support case where people use Roslyn as service (up to Feature layer) but how about people who want to use up to Editor layer? is that "no" since it require editor component that belong to VS and not open sourced?

**Comment by SLaks** [comment]
Just because it's not open-source doesn't mean people can't use it...

**Comment by heejaechang** [comment]
@SLaks I shouldn't say Open Source, but issue with license. I don't think those VS components (even though they are host independent) are allowed to be used out side of VS or Microsoft product (not 100% sure though)

**Comment by SLaks** [comment]
I checked this when I first wrote VSEmbed, and I didn't see anything in the license terms about using DLLs.  (IANAL)

**Comment by Pilchie** [comment]
This seems like something we want in VSCode as well, even if we don't have the editor layer.

**Comment by CyrusNajmabadi** [comment]
This would need to go through an API proposal.  in general, the reason we don't just make things public is because it increases maintenance costs and locks down our ability to change things in teh future.  We can open things up, but we have a process that requests need to go through to make sure the appropriate people weigh in and the right API shape is determined and shipped.  Importantly, any extension points need strong evidence that they can be provided in ways that do not impact scalability, and can have good debugging/editing experiences around them.

This API is unlikely for us to expose as we want to move away from roslyn itself having awareness of thigns like "is a document open".  that is for a host to know.  Roslyn itself should act as a pure data service independent of that knowledge.
