### ISSUE TITLE
Prevent duplicate invocations of per-compilation actions for a given symbol/syntax node in IDE

### ISSUE THREAD

**Issue by srivatsn** [dotnet/roslyn#248]
Ported from TFS WorkItem: <b>1113197</b>

------------------------------

<p><b>Repro Steps:</b></p>
<P>1) Create a compilation analyzer (has a compilation start action which registers an end action + additional symbol/syntax node action)</P>
<P>2) Add the analyzer to a project and open the project in VS.</P>
<P>3) Add code to project to ensure symbol/syntax node fires</P>
<P>&nbsp;</P>
<P>Expected: Symbol/syntax node action are never called multiple times for a given symbol/syntax node in a compilation</P>
<P>Actual: Multiple invocation can intermittently happen in IDE, current design doesn't guard against it.</P>

**Comment by heejaechang** [comment]
I think this bug is misleading.

we don't need to guard only one execution. we just need to guard only one execution per same state.

and we should have its own state per diagnostic execution path (solution crawler path, light bulb path, error list path and etc)

how they internally cache some information (not diagnostic state but engine's state) is implementation detail, and should not leak to diagnostic analyzer.

**Comment by mavasani** [comment]
Heejae, I am not sure I understand your comment fully. What do you mean by "one execution per state"? Are you suggesting each diagnostic execution path have a cloned compilation? The bug is primarily about trying to separate out the compilations used by these execution paths, so that none of these paths end up using same compilation, because if they do, then we cannot avoid duplicate callbacks.

**Comment by heejaechang** [comment]
@mavasani I think we are going back and forth on this. in v1, it doesn't care on compilation being cloned or not.

for "one execution per same diagnostic analyzer state", basically, I am asking we need to make sure we don't call same callback twice for same diagnostic analyzer state which can only be created by StartXXXAction.

**Comment by mavasani** [comment]
@srivatsn do we want to do anything about this bug for v1 engine?

**Comment by srivatsn** [comment]
No I think we should just wait for v2 to solve this problem.

**Comment by mavasani** [comment]
@ManishJayaswal @srivatsn @JohnHamby I just attempted to write a compilation end analyzer with a nested syntax node action and hit this particular issue in the IDE, causing my analyzer to either crash or report duplicate diagnostics due to duplicate callbacks.
IDE invokes the syntax node actions which computing diagnostics for active document, and then when computing compilation end diagnostics, is required to force complete analysis for project's all documents, which causes the duplicate callback for nodes in the active document. I can workaround this in the analyzer by adding checks about this scenario in the analyzer, but we probably want to consider fixing this one for v1 OR explicitly documenting it, otherwise lot of stateful analyzers will end up running into this.

**Comment by mavasani** [comment]
Moving to reconsider for 1.0. If it doesn't meet the bar, we should at least document this.

**Comment by JohnHamby** [comment]
If it is possible to fix this for RTM, we should take a shot at it. Manish is correct--this issue will cause trouble.

**Comment by ManishJayaswal** [comment]
@mavasani  Let's take a stab at a fix for this and see how risky the change is.

**Comment by mavasani** [comment]
Fixed with https://github.com/dotnet/roslyn/commit/0154c37128a115c9433849978ac4d1256e6d024a

**Comment by mavasani** [comment]
@JohnHamby you may want to verify this or ask Sri/Manish to assign it to someone else to verify and close.
