### ISSUE TITLE
Is pattern matching not supposed to be used like this?

### ISSUE THREAD

**Issue by taori** [dotnet/roslyn#24879]
**Version Used**: 
C# 7.1

**Steps to Reproduce**:

![grafik](https://user-images.githubusercontent.com/5545184/36285095-9770926e-12aa-11e8-9419-cff6171f0ef5.png)

**Expected Behavior**:
no initializer error
**Actual Behavior**:
initializer error

A workaround is to rename variables on the end of it with another pattern matching expression, which is obviously rather ugly. Could pattern matching be modified so the null check resolves this issue?

**Comment by gafter** [comment]
No, it is not supposed to be used like this.

A pattern variable is only _definitely assigned_ when the pattern matches. Since you're using the pattern variable `activateFeedbackPage` outside of the `if` statement where the pattern-matching operation occurs, it might not be definitely assigned where you use it.

**Comment by gafter** [comment]
> Could pattern matching be modified so the null check resolves this issue?

Moving to csharplang to be considered there.

**Comment by gafter** [comment]
Issue moved to [dotnet/csharplang #1326](https://github.com/dotnet/csharplang/issues/1326) via [**ZenHub**](https://www.zenhub.com/)
