### ISSUE TITLE
Categorize References by Read/Write

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#24877]
The C++ team has this in their Find All References, where users can filter to see only read/write usages.

Relates to https://github.com/dotnet/roslyn/issues/903.

**Comment by aluanhaddad** [comment]
This would be great to have.

**Comment by MaStr11** [comment]
Also  related #22545

**Comment by jcouv** [comment]
Also related to https://github.com/dotnet/roslyn/issues/17684 (Find-Refs on a setter should only find write-references to that property)
Note: I had taken a stab at implementing this, but ended up closing the PR because I took a wrong approach. But Cyrus had provided a number of [useful directions](https://github.com/dotnet/roslyn/pull/23276#issuecomment-345561655) for implementing it.

**Comment by jnm2** [comment]
@jcouv Didn't know about this issue when I started working on it at https://github.com/dotnet/roslyn/issues/22545#issuecomment-366847223.

First I did it in the UI adapter layer. The end result is what we need, but I wasn't sure if that was the ideal approach. https://github.com/dotnet/roslyn/compare/master...jnm2:accessor_specific_search(UI_only)

The other option seemed to be making changes to SymbolFinder. After asking @CyrusNajmabadi, he suggested a new SymbolFinderOptions type which could have Cascade = false.
I ran out of time before I did anything with this. https://github.com/dotnet/roslyn/compare/master...jnm2:accessor_specific_search

**Comment by jcouv** [comment]
@jnm2 nice. I hadn't realized you were already working on this. Go for it! 
As for design considerations in IDE layer, I'll defer to IDE team :-)

**Comment by jnm2** [comment]
Here are two completely-working implementations. The simpler one does the filtering in the UI adapter but that seems to be a dead end: https://github.com/dotnet/roslyn/compare/master...jnm2:accessor_specific_search(UI_only)

`IsWrittenTo` is a hack since it can't distinguish between:
  - `nameof(Property)`: no accessor—mistakenly included from getter search
  - `_ = Property`: getter
  - `Property++`: getter *and* setter—mistakenly excluded from getter search

And `IsWrittenTo` will be useless for event accessors. We need the proposed `SemanticModel.GetAccessors` at https://github.com/dotnet/roslyn/issues/25057#issuecomment-368659777.

This is the direction @CyrusNajmabadi and I want to go: https://github.com/dotnet/roslyn/compare/master...jnm2:accessor_specific_search

I need feedback on the direction and implementation. Should I start a review-only PR for comments?

**Comment by MaStr11** [comment]
I like your SymbolFinderOptions type. As mentioned by @CyrusNajmabadi in [comment](https://github.com/dotnet/roslyn/pull/22314#discussion_r170164131) it could be extended to support all kinds of other scenarios too. I would also like to see this feature shipped without waiting for semanticModel.GetAccessor as it is FAR better than what we have today even with the mentioned  limitations.

**Comment by jnm2** [comment]
Cyrus suggested I direct these questions to @jinujoseph and @sharwell rather than him.

**Comment by CyrusNajmabadi** [comment]
> Cyrus suggested I direct these questions to @jinujoseph and @sharwell rather than him.

I did?

**Comment by CyrusNajmabadi** [comment]
> Here are two completely-working implementations. The simpler one does the filtering in the UI adapter but that seems to be a dead end: master...jnm2:accessor_specific_search(UI_only)

Note: this is dead-end *only* if you keep the API as IsWrittenTo only.  We can certainly expand on that to have a full ReferenceType concept exposed here.  i.e. if this discussion bears fruit: https://github.com/dotnet/roslyn/issues/25057

**Comment by CyrusNajmabadi** [comment]
>  Should I start a review-only PR for comments?

Yes please.

**Comment by jnm2** [comment]
@CyrusNajmabadi My mistake, that was about a different issue number.

**Comment by CyrusNajmabadi** [comment]
ok :)

**Comment by jnm2** [comment]
RFC: https://github.com/dotnet/roslyn/pull/25561

**Comment by AngelElx** [comment]
i need it :(

**Comment by Neme12** [comment]
@mavasani I don't think 3. is a design issue, it seems to me like it is a correctness issue. If the design meeting concludes that there should be any changes for that that deviate from the language spec, I would hope that that those changes are added to the FAR code together with consuming ValueUsageInfo rather than ValueUsageInfo itself.

**Comment by Neme12** [comment]
All other features that depend on ValueUsageInfo definitely need the correct language interpretation. For example, converting a variable to readonly can happen if all references are read or readable ref, and it is important that method calls on structs are marked as read/write ref, because the variable cannot be readonly (would change semantics), and method calls on readonly structs are readable ref, therefore it's OK to make the var readonly.
