### ISSUE TITLE
Provide spell checker on comments/identifiers

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#24963]
A spell-checker is important because of the accessibility aspects (dyslexia, ESL) as well as the FXCop parity. We want to offer spell-checking support for:
- Identifiers (FXCop parity with public identifiers)
- XML doc comments
- Comments
- Strings

**Comment by kendrahavens** [comment]
+1 Internal feedback

**Comment by genlu** [comment]
related to https://github.com/dotnet/roslyn-analyzers/pull/1111

**Comment by CyrusNajmabadi** [comment]
As per one of our last design meetings, i think we stated this as fully served by an existing popular extension.  Specifally: https://marketplace.visualstudio.com/items?itemName=EWoodruff.VisualStudioSpellCheckerVS2017andLater.  This also has the benefit of working across all languages in a unified way.  Closing as out of scope for Roslyn.

**Comment by CyrusNajmabadi** [comment]
Reopening.  Request includes 'identifiers' which is outside the scope of some of the solutions out there.

**Comment by jasonmalinowski** [comment]
Conclusion from the design meeting: we should go ahead and accept the contribution we have to add an analyzer to check **API names and identifiers**. and merge that into dotnet/roslyn-analyzers. We'll ship it as a separate package for now. We'll ensure the fixer has the same IDs as FxCop did so the transition there is smooth. We won't ship this inbox in the SDK for now, but we'll continue to listen to feedback.

For **comments and strings**, we'll reach out to the editor team to ask if they have a planned feature for this, because that's something that should work for other languages as well.

We'll also reach out to our globalization teams, to see if this brings up any GB 18030 compliance issues. @jmarolf you were voluntold to perhaps do this, did you actually want to? :smile:

**Comment by jasonmalinowski** [comment]
@mavasani @sharwell Who is taking the next steps as far as the analyzer contribution?

**Comment by mavasani** [comment]
I can drive it

**Comment by CyrusNajmabadi** [comment]
Added in https://github.com/dotnet/roslyn/pull/59693
