### ISSUE TITLE
C# 7.1 Build failing on Build Server.

### ISSUE THREAD

**Issue by vivekkjain** [dotnet/roslyn#24982]
**Version Used**: 
Visual Studio 2017 15.5.4

Used C# 7.1 feature. Building fine on local machine using Visual Studio 2017 15.5.4

I have set language version to 7.1 explicitly still its failing .

**error CS8314: An expression of type 'Employee<T>' cannot be handled by a pattern of type 'Company' in C# 7.0. Please use language version 7.1 or greater. [D:\BuildAgent\work\936e0f87a6\MyShop\Events.csproj]**

**Expected Behavior**:
It should build fine on the agent server. I have visual studio 15.5.7 on build server.

**Actual Behavior**:
Failing on build agent with above message.
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\bin\Roslyn

**Comment by jcouv** [comment]
I'm not familiar with build server, but from the compiler error this is a C# compiler that supports C# 7.1 (at least), but it got passed a language version that is `7.0` or `default`.

So the question is why did the compiler get passed this language version, instead of the one you expect. 
If you're using msbuild for your build, then you can collect a log (I'd suggest a structured/binary log, using option `/bl`) and then troubleshoot your build process to understand how the language version is determined and passed to the compiler.

**Comment by markalanevans** [comment]
Did this get resolved?

**Comment by markalanevans** [comment]
I'm experiencing the same issue.

**Comment by jcouv** [comment]
To verify what version of the compiler and the language are being used in CI, please include `#error version` in that source file and collect the resulting message. I suspect the language version is 7.0, not 7.1 as you expect.
