### ISSUE TITLE
Terrible code completion suggestion for implementing interface explicitly.

### ISSUE THREAD

**Issue by MkazemAkhgary** [dotnet/roslyn#24993]
**Version Used**: 15.5.5

**Steps to Reproduce**:

Suppose I have a class and an interface. this class has implemented all interface members except one (or a few).

    public interface IInterface
    {
        void DoFoo();
        void DoBar();
    }

    public class MyClass : IInterface
    {
        public void DoFoo()
        {
        }
    }

This class is missing a member. Quick action works fine if I choose `Implement interface`. I get what is expected. a method that throws `NotImplementedException`.

How ever if I choose `Implement interface explicitly` this is what I get.

![wrong suggestion 2](https://user-images.githubusercontent.com/15255162/36542597-81cc6d10-17f6-11e8-95cc-a871ce87f447.JPG)

**Actual Behavior**:

It will try to implement **all** interfaces explicitly and it will, you can try it your self. after this completion ill have 3 methods and I have to remove `DoFoo` manually.

This kind of completion is not practical, when interface contains more than 3 members, it just makes bunch of trouble.

**Expected Behavior**:

only the missing member should be implemented explicitly without affecting any other members.

**Comment by MkazemAkhgary** [comment]
@sharwell please check this out. looks like this can be fixed very easily. maybe as simple as filtering a list.

**Comment by CyrusNajmabadi** [comment]
this is very much by design.  We used to have "implement explicitly" do what you wanted, but we got a lot of feedback that that's exactly *not* what people wanted.  They wanted "implement explicitly to make sure there was an explicit impl for all members".  

"implement interface" is thus the: do the minimal work to make sure i'm implementing things.  "Implement interface explicitly" is the: make sure i have an explicit member for all interface members.

There is no concept of "find whatever is missing, but make *explicit* members for those".  up till now, no one has ever asked for that.

**Comment by MkazemAkhgary** [comment]
@CyrusNajmabadi 

When I get error, this lightbulb comes _in regard to that error_. so I do expect that to solve the related problem, not to solve another problem.

![inkedwrong suggestion 3_li](https://user-images.githubusercontent.com/15255162/36627737-9756a102-195c-11e8-9a07-cec19b398dfc.jpg)

>"implement explicitly to make sure there was an explicit impl for all members".

_if that's the case_, then you should show us a lightbulb always when clicking on the interface not when there is error in regard to not implementing _an_ interface.

the description is also wrong. `implement interface explicitly` is singular form. _if that's the case_ it should be plural form.

>We used to have "implement explicitly" do what you wanted, but we got a lot of feedback that that's exactly not what people wanted.

I see, what a pity but you could add an option instead of replacing existing one. 

some people don't waste their time bothering to explain the problems here, or ask for features. some people don't even know such place exist to come here and explain, or they may not have this problem in the first place. for many other reasons I don't think you are getting feedback from majority of users.

In either way, please fix the description and availability of the lightbulb and also add the old option. best regards.

**Comment by CyrusNajmabadi** [comment]
> When I get error, this lightbulb comes in regard to that error. so I do expect that to solve the related problem, not to solve another problem.

The problem is that you're not implementing the interface.  The decision on the part of the fix is how to address that.  It's not just to add the method that the diagnostic says is missing.  If it did only that, you'd still have a problem the moment you're missing any more than one member.

> I see, what a pity but you could add an option instead of replacing existing one.

up till now, you're the first person to have asked for this.  We made the options in roslyn match what we saw people actually doing and the features that people asked for.  

We also believe in a lot in "more is less".  i.e. having a dozen different "implement interface" choices is not good.  So we've opted for a few amount of fixes per problem, but we've worked hard to make those fixes appropriate for the broadest classes of users and cases.

> some people don't waste their time bothering to explain the problems here, or ask for features. some people don't even know such place exist to come here and explain, or they may not have this problem in the first place. for many other reasons I don't think you are getting feedback from majority of users.

I'm referring to all the feedback we've gotten from all channels over 15 years.  

>  I don't think you are getting feedback from majority of users.

When i was working on this stuff there was continuous feedback from a variety of different sources.  We can't just guess at what some unknown people want when we have tons more people actually willing to tell us waht they want :)

> In either way, please fix the description

The description is correct.  It's the diagnostic that triggered the lightbulb.  The compiler simply picks one member that is missing and reports it.

>  and availability of the lightbulb 

I don't know what this means.  The lightbulb *is* available.  Should it not be available?

> and also add the old option. best regards.

I'm sure the team will consider it.  Note though: you haven't actually made an argument as to why that option would be preferred.

--

Let's walk through the three current options that exist, and what purposes they serve:

1. "Implement interface".  The broadest and most general option (and also the option most likely to be picked).  It simply says "make it so that i have a member that properly implements every member in the interface's hierarchy".  This means that it will find any unimplemented interface members and then will try to make a real member for it.  That member will be implicit by default, but can also be explicit if an implicit member would conflict with an existing member.  By far this choice is picked the most.
2. "Implement interface explicitly".  This is much narrower case that exists, but does have some people who use it all the time.  In this case, the user does *not* want to expose the interface through the type directly.  Instead, they expect all consumers to cast this type to the interface (or get this type as an instance of the interface).  And they specifically do not want to accidently use this interface directly from *within* the type.  in this case, they absolutely want every member to be explicitly implemented, and they only want to be able to get to those members through the interface.
3. "Implement interface through member '...'".  The even more narrow case, but one that is helpful when doing composition patterns.  Here, you are composing an object as a field/prop htat implements an interface, and you also want to expose that interface yourself.  This feature allows you to get all the boilerplate that generates all the interface members on you, forwarding them to the underlying field/prop.

Each of these three patterns has a clear development reason for them, and a set of users that follows those patterns and benefits from these behaviors.  So far, no reason or use case has been provided that demonstrates why it would be appropriate to *partially* implement an interface explicitly into an existing type.

**Comment by CyrusNajmabadi** [comment]
> old option could be labeled as Implement "DoBar" explicitly so it wont be confusing.

1. why would you want this?  That still hasn't been explained.
2. It is *hugely* unlikely that we would add an option that just implements a single member from an interface.  It's such a marginal case that isn't worth cluttering up the UI to offer.

**Comment by MkazemAkhgary** [comment]
1. Because im lazy :)
2. Ok :(

**Comment by CyrusNajmabadi** [comment]
> Because im lazy :)

Not a good reason :)    If you want one-off features that help your specific use cases, then def invest in writing code-analyzers.  They're great for this purpose :)

**Comment by sharwell** [comment]
@MkazemAkhgary I tend to agree with the conclusion, but I'm not quite ready to simply dismiss the idea. I'm going to reopen it so a couple more eyes are on the issue and see if there's anything here to tweak as an improvement.

**Comment by sharwell** [comment]
@dpoeschl I'm thinking there may be a way to include interface names in member completion so it's easier to add an explicitly implemented member, similar to how `override` assists with other members.
