### ISSUE TITLE
[Completion] Need a way to add to override completion

### ISSUE THREAD

**Issue by mkrueger** [dotnet/roslyn#25017]
The override completion provider is exclusive howver that exclusive model prevents adding to the override completion list.

However our users are used to a feature where they could virtually override members that are not virtual. 
See the VSTS issue https://devdiv.visualstudio.com/DevDiv/_workitems/edit/564610

**Comment by CyrusNajmabadi** [comment]
@mkrueger Can you not supply your own completion provider here?

**Comment by CyrusNajmabadi** [comment]
NOte: this would be the preferred way as what you are talking about seems veyr weird.  i.e. ` virtually override members that are not virtual.`.  Since that problem space seems domain specific to whatever you are doing, it would make sense to have your own domain-specific completion provider to support that.

**Comment by CyrusNajmabadi** [comment]
This would need to go through an API proposal.  in general, the reason we don't just make things public is because it increases maintenance costs and locks down our ability to change things in teh future.  We can open things up, but we have a process that requests need to go through to make sure the appropriate people weigh in and the right API shape is determined and shipped.
