### ISSUE TITLE
Hidden analyzer not reported during builds

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#2512]
If an analyzer has a default severity of Hidden, then diagnostics produced by it are not reported for closed files in Visual Studio, even if "Show diagnostics for closed files" is checked. This applies even if the ruleset configured for the project overrides the severity to Warning or Error.

Note that for rules with a default severity of Warning are shown as errors when the ruleset file overrides them to be Error, suggesting that the ruleset file should take precedence when determining whether or not a rule is evaluated.

**Comment by mavasani** [comment]
This seems be done explicitly here: http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/Diagnostics/EngineV1/DiagnosticIncrementalAnalyzer.cs,450

@heejaechang more context, I can't remember why this was done.

**Comment by heejaechang** [comment]
@sharwell @mavasani ah, yes this is a bug. Hidden doesn't run for closed file since it has no meaning (there is no visible representation for the diagnostics and code fix only works for opened file).

but, it checking default severity not effective severity is a bug. I will assign the bug to me and fix it.
