### ISSUE TITLE
VB: CandidateSymbols is missing some candidates

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#25135]
Reported in https://github.com/dotnet/roslyn/pull/22314#pullrequestreview-100251540.

We'd expect to candidate symbols for invocation of `M`, as the semantic model does for similar code in C#.
Tagging @AlekseyTs @gafter to confirm expected behavior. Thanks

```VB
        <Fact>
        Public Sub TestCandidateSymbols()

            Dim comp = CreateCompilationWithMscorlibAndVBRuntime(
<compilation>
    <file name="a.vb">
Module Module1
    Public Sub M(i1 As String, i2 As String)
    End Sub

    Public Sub M(ex As System.Exception)
    End Sub

    Sub Main()
        M(new System.Exception(), 2)
    End Sub
End Module
    </file>
</compilation>, options:=TestOptions.DebugExe)

            comp.AssertTheseDiagnostics(<errors>
BC30311: Value of type 'Exception' cannot be converted to 'String'.
        M(new System.Exception(), 2)
          ~~~~~~~~~~~~~~~~~~~~~~
                                        </errors>)

            Dim tree = comp.SyntaxTrees(0)

            Dim model = comp.GetSemanticModel(tree)
            Dim nodes = tree.GetCompilationUnitRoot().DescendantNodes()
            Dim node = nodes.OfType(Of InvocationExpressionSyntax)().Single()

            Assert.Equal("M(new System.Exception(), 2)", node.ToString())
            Dim symbol = model.GetSymbolInfo(node)
            AssertEx.Equal({"Sub Module1.M(i1 As System.String, i2 As System.String)"},
                symbol.CandidateSymbols.Select(Function(s) s.ToTestDisplayString()))
        End Sub
```

**Comment by MaStr11** [comment]
It should be noted that there are other diagnostic ids (related to conversion errors) that are also affected by this. Another test case hit by this is [TestInvocation_LambdaExpressionParameter](https://github.com/MaStr11/roslyn/blob/7a95e228a104078b5a170b387985d7ccf2b8c805/src/EditorFeatures/VisualBasicTest/AddParameter/AddParameterTests.vb#L826-L843) for diagnostic error `BC36625: Lambda expression cannot be converted to 'Integer' because 'Integer' is not a delegate type.`.

I can confirm that at least these diagnostics are affected:
* BC30311: Value of type 'Exception' cannot be converted to 'String'.
* BC36625: Lambda expression cannot be converted to 'Integer' because 'Integer' is not a delegate type.

and these are probably affected also:

* BC30512: Option Strict On disallows implicit conversions from 'Object' to 'Integer'.
* BC32006: 'Char' values cannot be converted to 'Integer'.

**Comment by AlekseyTs** [comment]
Candidates is not necessarily the same set as a member group. It is a set of best candidates among all, i.e. dismissed due to the same reason, but the reason is the "best" one, comparing with reasons for others. For example, ```M(i1 As String, i2 As String)``` is dismissed because conversion doesn't exist, ```M(ex As System.Exception)``` is dismissed because it doesn't have required number of parameters, which is a worse reason. If one needs complete list of candidates, I suggest to look at member group.

**Comment by jcouv** [comment]
Thanks for the clarification.
