### ISSUE TITLE
Testplan for new constraints.

### ISSUE THREAD

**Issue by VSadov** [dotnet/roslyn#25139]
## Enum constraint ##

The feature removes restrictions on use of `System.Enum` in constraints. 

- [x] langver test.
- [x] constraint is enforced - rejects types that do not derive from `System.Enum`
- [x] constraint can be satisfied - allows enums, `System.Enum` itself and type parameters with `System.Enum` constraint.
- [x] can combine with `class` constraint. Only `System.Enum` satisfies.
(try also an enum, string, int, T:System.Enum)
- [x] can combine with `struct` constraint. Only actual enums and `T:struct, System.Enum` can satisfy. 
(try also an enum, string, int, System.Enum)
- [x] can combine with `new()` constraint. Same result as with `struct` since `System.Enum` has protected ctor.
- [x] test above scenarios via metadata. Not a new scenario, basically a check for metadata emit.
- [x] test constraints on a type parameter symbol (API)
- [x] symbol display test (another indirect test of symbol API) 
- [x] what is `System.Enum` is not available
- [x] bunch of OHI tests 
- [x] test VB

## Delegate/MulticastDelegate constraint ##

The feature removes restrictions on use of `System.Enum` in constraints.
 
- [x] langver test.
- [x] same as above really. Except the [Multicast]Delegate are regular classes and cannot be combined with `class`/`struct`.
- [x] Delegate does not satisfy MulticastDelegate. (just falls out from the inheritance, no new code here).

## `unmanaged` constraint ##

A "pseudo-constraint". It has meaning only in the C# typesystem. (CLR has no idea about it). 
Encapsulates the meaning of `unmanaged type` in the language with all it's quirks and possible future changes.

"unnmanaged" in C# is basically a quality of a type that allows it to be an element of a pointer type. The constraint simply propagates the notion through generics.

Currently type is unmanaged if 
- it is a regular (not generic/constructed) struct
- it has only unmanaged fields
- valuetype primitives and empty structs are unmanaged

We are adding a `T:unmanaged` to this set.

Note: `unmanaged` implies `struct.
Note: `unmanaged` is contextual - like `var`. If may bind to a type `unmanaged`, if such is in scope. 

The greatest risk is metadata representation since we are using some undocumented bits in the metadata. The purpose is that those who do not understand the constraint should not simply ignore it.  
We are using a `System.ValueType` constraint with `modreq(System.Runtime.InteropServices.UnmanagedType)`. 

### Testplan ###

- [x] langver
- [x] metadata tests
	- [x] "standard" set of synthesised/embedded attribute tests for `IsUnmanagedAttribute` 
	(used in addition to `modreq` to ease metadata parsing by 3rd party tools)
	- [x] errors when modreq type is missing or duplicated.
	(we do not synthesize `UnmanagedType`)
	- [x] `modreq` is copied to overrides (compilation/metadata references)
		- [x] virtual
		- [x] abstract
		- [x] interfaces
		- [x] lambdas
	- [x] metadata import 
		- [x] wellformed `unmanaged` form IL is accepted 
		- [x] `IsUnmanagdAttribute` is required 
		- [x] `IsUnmanagdAttribute` without modreq is also invalid (type is not supported error).
		- [x] `modopt` is not accepted
		- [x] unexpected `modreq` types are not accepted
		- [x] unmanaged + `new()`      
		- [x] unmanaged + `SomeType`  
		- [x] unmanaged + `class`  
		- [x] unmanaged without `struct`
	- [x] constraint on a type parameter of a type.    
- [x] lanaguage tests
	- [x] test that constraint is enforced on a method instantiation 
		(construct with managed/unmanaged structs, classes, int, unmanaged/ordinary generic typeparam)  
	- [x] test that constraint is enforced on a type instantiation 
		(construct with managed/unmanaged structs, classes, int, unmanaged/ordinary generic typeparam)
	- [x] test that constraint is enforced on a delegate instantiation 
		(construct with managed/unmanaged structs, classes, int, unmanaged/ordinary generic typeparam)
	- [x] not supported on local functions
	- [x] cannot be mixed with any other constraints (`class`, `struct`, `new`, `SomeType` before/after)
	- [x] pointer operations work with `unmanaged` constrained type params
	- [x] `sizeof` works with `unmanaged` constrained type params (primitives, structs)
	- [x] presence of a type named "unmanaged" - in scope/out of scope. 
	- [x] unmanaged implies `struct`
		- [x] can be passed to `T:struct` 
		- [x] to `T:SomeInterface`
		- [x] to `T:System.Enum`
		- [x] to `T:new()`
		- [x] not to `T:class` 
		- [x] not to `T:SomeClass` 
		- [x] cannot itself be used as a constraint
- [x] missing required types
	- [x] 'System.Runtime.InteropServices.UnmanagedType'
	- [x] 'System.ValueType'
-[x] validate symbol API  (`HasUnmanagedTypeConstraint`)
	- [x] on a method type param
	- [x] on a type type param
- [x] bunch of OHI tests 
- [x] validate our metadata encoding scheme with various languages/tools/runtimes. 
(C++ fixed a crash, otherwise ok)
- [x] test with best betternes when features are combined. - Since we can resolve overloading on constraints now. 
 
### Extra test scenarios that came from testplan review. ###
- [x] check `IsReferenceType` on `T` when constrained to `System.Enum` or `unmanaged`
- [x] check `IsValueType` on `T` when constrained to `System.Enum` or `unmanaged`
- [x] inherit from `System.Enum` in code (which would be an error of some sort). Check if it satisfies `System.Enum` constraint, or not - should not just crash.
- [x] check that code consuming `System.Enum` and `System.Delegate` constraints from metadata correctly still does so even if langver < 7.3
- [x] check that the metadata emitted for `Enum`/`Delegate` constraints is consumable by legacy csc (metadata compat, ok to check manually once)
- [x] `System.Enum` can be combined with `unmanaged` constraint
- [x] `unmanaged` can be combined with Interfaces
- [x] `System.Enum` can be combined with Interfaces (did I miss a test?)
- [x] struct with pointer fields satisfies `unmanaged` 
- [x] enum defined in a generic type should not be considered `unmanaged` (per existing rules), but will satisfy  `System.Enum`/`struct`/`new()`

**Comment by Joe4evr** [comment]
> A "pseudo-constraint". It has meaning only in the C# typesystem. (CLR has no idea about it).

This does worry me a tiny bit. Completely understandable, but is there really nothing that can be done to find out if a type passed to `T : unmanaged` has had a reference type field added by e.g. IL rewrite?

**Comment by VSadov** [comment]
@Joe4ever - it is possible to dig through the type using reflection and check for reference types - like in https://github.com/dotnet/corefx/blob/945eed42a2db5b002716af78dc5d60b6c771aad4/src/System.Memory/src/System/SpanHelpers.cs#L131

But, no, the "unmanaged" here is a completely C# concept around pointer types. CLR does not know or enforce it.

**Comment by kindermannhubert** [comment]
Do I understand correctly that definition of unmanaged type wouldn't allow to any nullable type to be unmanaged? 

In our project we already use notion of unmanaged types (call it something else though) and we define them very similarly as in https://github.com/dotnet/corefx/blob/945eed42a2db5b002716af78dc5d60b6c771aad4/src/System.Memory/src/System/SpanHelpers.cs#L131
(with the difference we also allow pointer types, which I believe are also types you can take pointer to).

We have a framework that uses generic pointers to these types and we test validity of used types (=if they are unmanaged) at runtime. That means our generic methods don't have any compile time constraints and we check if passed generic types are correct at runtime.
To get generic pointers we use following methods:
```
.method public hidebysig static !!TBlittable* GetReferenceForBlittableType<TBlittable>(!!TBlittable& 'value') cil managed 
{
	.maxstack 8
	ldarg.0
	ret
} 

.method public hidebysig static !!TBlittable* CastToGenericPointer<TBlittable>(void* 'value') cil managed
{
	.maxstack  8
	ldarg.0
	ret
}
```

Funny thing (but it's great it is possible, because we use it a lot) is following code does not compile:
``` C#
T* p = CastToGenericPointer(...);
```
but following code compiles fine
``` C#
var p = CastToGenericPointer(...);
```
and 'var' in second snippet is 'T*'. Pointer arithmetic and everything works correctly with generic pointer ```p```.

When I saw new unmanaged constraint I hoped it would be possible for us to use it instead of runtime type checking and usage of extra MSIL methods. But nullable (or more generally generic unmanaged) types is a must.

Few more questions:
Will syntax ```T* p = ...;``` be valid with unmanaged constraint on T?
Will it be possible to get pointer to value of type unmanaged T like this: ```T* p = &value;```?
----> Now we get pointers to value like this: ```var p = GetReferenceForBlittableType(ref value)```.

Would it be please possible to extend the set of unmanaged types to the set of types given by method ```IsReferenceOrContainsReferencesCore``` in SpanHelpers (or extended version of this method which also allow pointer types)?

**Comment by VSadov** [comment]
@kindermannhubert - `unmanaged` set does not include generic types and nullable is generic.

The restriction can be relaxed in the future to actually look into fields of generic structs. That change would be of a more general nature than this feature. 

Here we are just propagating the notion of `unmanaged` through generics, whatever it is. 

You may enter an issue at https://github.com/dotnet/csharplang/ about generic structs vs. `unmanaged`. If it gets enough interest, it will be considered.

**Comment by VSadov** [comment]
@kindermannhubert - yes   `T* p = &value;` will work assuming `T:unmanaged`. That is basically the point of the feature. 

Note: `value` will have to be not movable (i.e. not possibly on the heap) for direct `&` to work, otherwise you will need `fixed` to pin it. Nothing changes here.

Your `GetReferenceForBlittableType` could be quite dangerous around heap variables. I assume you are being careful with those.

**Comment by VSadov** [comment]
@dotnet/roslyn-compiler - FYI. "Constraints" testplan has been updated to contain scenarios from the review.

**Comment by jkotas** [comment]
> > A "pseudo-constraint". It has meaning only in the C# typesystem. (CLR has no idea about it).

> This does worry me a tiny bit.

I am worried about this too. This feature does not really guarantee a type safety, even though it makes it look like that it does. It suffers from security issues discussed in https://github.com/dotnet/corefx/issues/27094 .

I understand that this feature was done because of a lot of people asked for it and it was not hard to do, but I do not think it is a particularly good feature - it is both too dangerous and too limited at the same time.

My alternative rejected proposal in offline discussion was to allow taking `fixed` pointers of anything and emit on-by-default warning if the value is not unmanaged type. It would make it clear that there are no type safety guarantees, and it would provide full flexibility for unmanaged pointer operations, without using `System.Runtime.CompilerServices.Unsafe`.
