### ISSUE TITLE
[Quick Action] Push members up

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#25145]
From several customers:

"_I use this daily. In test driven development, we use interfaces for everything. I prefer to write the implementation first, and promote the method to the interface when I’m happy with it. “Extract Interface” isn’t the same, because I’m trying to append an existing interface.

This is the main use case, especially relevant to developers who prefer a “bottom up” style of coding. On the other hand, Visual Studio has had the opposite operation forever, where you write the interface signature first, and then have it create a method body in the derived class._"

"_I’ve seen a few different versions:
- ReSharper, “Pull Members Up” https://www.jetbrains.com/help/resharper/Refactorings__Pull_Members_Up.html
- Roslynator, “Add member to interface” (https://github.com/JosefPihrt/Roslynator/blob/master/docs/refactorings/RR0195.md)
- Standalone Extension, “Add to interface” (https://marketplace.visualstudio.com/items?itemName=LeonGitis.Addtointerface)_"

"_This ties in with my request for a “change modifiers” quick action/refactoring – I’m promoting and demoting visibility or abstract/virtual-ity frequently_."

**Comment by jinujoseph** [comment]
This should be a platform capability that other languages could plug into

**Comment by alrz** [comment]
linking to https://github.com/dotnet/roslyn/issues/15796

**Comment by Cosifne** [comment]
A common situation when pushing member up/down, user may want push something wrong up/down.
Here are some possible situation I can figure out.
1. Push a private method/Event/Property to an interface. (ReSharper gives user a warning, if user want, it changes the modifier )
2. Push a static private method/Event/Property to an interface (ReSharper does nothing, just copy the static method declaration to interface)
3. Push an abstract method/Event/Property to non-abstract class. (ReSharper change the base change to abstract)
4. Push an abstract method/Event/Property to interface. (ReSharper remove the abstract keyword)
5. Push an explicitly declared method to interface, like
`public class SomeClass: inteface1, interface2
{
    interface1.Test()
    {
        // Do something
    }
}`
Should we provide the option to push to interface2? (ReSharper let user to push to everything and just copy the 'interface1.Test()' without doing anything)

It would be nice if you can figure out more interesting situation.

**Comment by Cosifne** [comment]
![image](https://user-images.githubusercontent.com/24360909/45578792-8d1d7f00-b838-11e8-989f-efbf2abb5be3.png)
The original design

**Comment by CyrusNajmabadi** [comment]
If anyone here is interested in tryin to create this feature, i'd be happy to help them with guidance on how to do so in Roslyn.

**Comment by CyrusNajmabadi** [comment]
@Cosifne Yes.  Several features already make use of this.  It's the "NestedActions" part of a CodeAction.

**Comment by CyrusNajmabadi** [comment]
Note: certain things that would be a concern:

1. Push some method down to sub class.

There is no general, fast enough, facility to find out the subclasses of a class in Roslyn.  There are asynchronous facilities that depend on being able to search the entire solution.  However, they are unbounded in time, and may take a lot of time to both build the indices required for this and to find the results.

If this was offered, we'd likely either need to cap the amount of time it would take to compute this.  Or we would need a general facility to bring up lightbulbs while still figuring out if certain items should appear in them.

To put this in perspective.  Open roslyn, then go do some public abstract member in the Compilation layer and ask to find all implementations.  It may take tens of seconds (or more).  This would effectively block the lightbulb from appearing for the same amount of time if we did that for a refactoring.

**Comment by CyrusNajmabadi** [comment]
> Here are some possible situations I can figure out.

In general, we've gone with teh approach of making sane and reasonable default decisions, without onerously bogging people down with having to make lots of choices to get out of it.  So, if someone wants to push a private method into an interface, by all means let them do it.  If they push an abstract method into a non-abstract type, i would say just push it in and keep it abstract.  The user will get a error about that, but then if that's an issue we should then have a fixer taht helps them fix **that** problem (i.e. by making the member non-abstract, or by making the containing type abstract).

We prefer lots of small little fixes versus big heavyweight changes that have lots of downstream effects in general.

**Comment by CyrusNajmabadi** [comment]
> Push a static private method/Event/Property to an interface

I probably would not even offer to move a static method to an interface.  It seems *highly* unlikely as something someone would want to do.  Instead, i would offer "make static method into instance method", and then allow the person to push up/down from that point.

**Comment by heejaechang** [comment]
we don't need to find all base types before showing LB. so we can show LB or entry but showing nested sub menu shows waiting circles and slow.

but that being said. not sure dialog box is that bad. we have signature change dialog box and I use them a lot and I don't have much complain about it. do we don't like it because we have data that resharper users don't like it? 

otherwise, we could do something like push down to derived types or interface implementation to show dialog box like signature change. if there are a lot of derived or implementation, user might need to search among those and multi select and etc? and if it can, preselect types the method is called off in source code ?

**Comment by CyrusNajmabadi** [comment]
The general issue with UI is... well... we have to create UI :)  And then people have to learn how each piece of UI needs to work.  In general, it's been something we have tried heavily to avoid (though we're not always succesful), as we want to guide people through a lean and mean text-driven development process.

It's somewhat like a language feature.  Things like UI start at negative 1000 points.  If they can show they're valuable enough, or we can show we just can't develop a streamlined way to interact with them through existing mechanisms, then we can certain provide custom UI.  But it's generally a last resort instead of something embraced up front.

**Comment by CyrusNajmabadi** [comment]
>we don't need to find all base types before showing LB. so we can show LB or entry but showing nested sub menu shows waiting circles and slow.

Right.  But we never want any part of a menuing system (even a submenu) to potentially take dozens of seconds to show up.  The only time it's ok is if it's a totally optional part of the flow (for example, seeing the preview).  If yuo need to wait that long to even *get* the option in the first place, then the user will have canceled out long before because it will just seem like the system is broken :)

**Comment by CyrusNajmabadi** [comment]
> we have signature change dialog box and I use them a lot and I don't have much complain about it. 

Right.  Signature change exists with UI because the entire metaphor of what's going on isn't something that fits into a general "choose an option from a set"-oriented interaction model.  Because the number of options combinatorially increases, it's not suitable for a normal choice-oriented menu.  i.e. you can reorder parameters however you want, and you can remove whatever you want, etc. etc.  There's no good way we can think of to offer this, so UI it is.

But that's definitely one of the very special cases.  It may be that this feature becomes such a special case.  But we'd have to be very certain of that before going down that route.

**Comment by CyrusNajmabadi** [comment]
>otherwise, we could do something like push down to derived types or interface implementation to show dialog box like signature change. if there are a lot of derived or implementation, user might need to search among those and multi select and etc? and if it can, preselect types the method is called off in source code ?

Yes.  Such an approach could potentially work out.  i.e. the lightbulb menu would be ```Push down to derived type...```.  The ```...``` being our signal that this will end up causing more work to happen (including potentially UI) once selected.  

Note: i wasn't saying there were no solutions here.  Just that this was a general area of concern as we don't want to accidently check in something that runs in unbounded time, in an code location that has tight time constraints.

**Comment by heejaechang** [comment]
sure. that's one opinion. so don't need to keep push your opinion.
…
whether it requires UI or not seems just work thing. not user experience. if we need to make one, then we will make one.
...
now, about user experience. for me, user experience wise, having dialogbox or not didn't make my experience worse or better. at the same time, having stream line way doesn't make the experience better or worse. I use one when appropriate and the other when the other is appropriate. 

for example, I sometime uses rename LB to apply rename, sometime use command to do rename.
...
I just didn't want to just push off dialogbox route. if we want to not go that route, we probably need concrete data rather than some people's preferences.
…
also, menu. not sure why sub menu is bad and preview is okay. both are bad. but if one is allowed, no reason the other is not allowed.

**Comment by CyrusNajmabadi** [comment]
>sure. that's one opinion. so don't need to keep push your opinion.

You keep saying this across many conversations.  These are explicit team decisions that have been made and strongly reinforced over the lifetime of Roslyn.  THey were not made haphazardly and they are the result of deep consideration and design around these systems.  Please stop being dismissive of this sort of thing.  The purpose of these conversations and issues and PRs is to deeply discuss the core values of these features and how they can best mesh with the core principles Roslyn (and C#/VB IDE) have been baking for decades now.

> whether it requires UI or not seems just work thing. not user experience. if we need to make one, then we will make one.

I'm sorry, that's not true.  UI **is** user experience.  Please do not be dismissive of reasoned and principled decision making that long predates things here.  We did not reach this point haphazardly.  It was intentional and it is important to consider and understand when working on any new features.  

If you disagree or think otherwise, that's fine.  We can feel free to go back and reconsider these decisions.  But, the default position shoudl be for new things to follow them *unless* there is a strong reason for exception.  The default position should not be to disregard them.

> now, about user experience. for me, user experience wise, having dialogbox or not didn't make my experience worse or better. 

This is not the position that the Roslyn IDE team has made.  And the place we've landed WRT to UI was intentional and specific.  This has been the case from the beginning.   

> at the same time, having stream line way doesn't make the experience better or worse.

The actual design decisions that were made disagree.  that's *precisely* why we implemented so many features in the way we did.  The team design decision here was that it *did* make the experience better and that we would strongly push toward this sort of model unless there was *very strong* reason otherwise.

We did not land here haphazardly.  We did not just do this on a whim.  These were very explicit decisions from very early on in the IDE days and we've used the same decision making methodology on all subsequent features.

--

As an aside, i don't know why this has to come up on each and every single feature that is being worked on.  It feels like every single discussion has to descend into the same repeated conversation about the decisions made in the past, and how we should not be deviating from them without good reason.  We've even had to go back and pull in the stakeholders and have design meetings again, just to reinforce the idea of "yes, this is intentional. yes, please do not do things differently without good reason".

The IDE codebase and feature-set has had a tremendous amount of thought and effort put into the design.  If you think that there are ideas that shoudl supercede that, that's fine.  BUt please go through a design process that establishes that rather than using individual PRs or issues to push for that sort of thing.  On individual PRs/issues, we should stick with the designs that have guided us so far, and not use them as the place to go try to re-litigate everything from the start.

**Comment by CyrusNajmabadi** [comment]
>  also,  menu. not sure why sub menu is bad and preview is okay. both are bad.  but if one is allowed, no reason the other is not allowed.


I don't know anyone who said submenus are bad.

**Comment by heejaechang** [comment]
you probably need to link the design doc saying that is the decision then.

for me, streamlined or not, best user experience for the feature wins.

**Comment by heejaechang** [comment]
bring up the context is fine. but I don't still agree that because of that we should not discuss having an UI. I believe for push down, due to a potential of there might be a lot of derived types or implementations, having UI has a merit.

sure we can have something like pushed method down to all derived types or etc. but I don't get why even discussing about it has to shutdown.

**Comment by CyrusNajmabadi** [comment]
> bring up the context is fine. but I don't still agree that because of that we should not discuss having an UI.

I never said we shouldn't.  I feel like you have misread my posts and then are arguing against something different entirely.

In fact, i even agreed that UI *could* be appropriate for this feature:

> Yes. Such an approach could potentially work out. i.e. the lightbulb menu would be Push down to derived type.... The ... being our signal that this will end up causing more work to happen (including potentially UI) once selected.

You are misreading what I am saying and interpreting it to mean something else.  What i *was* very explicitly trying to address was this *different* point you were explicitly making:

> whether it requires UI or not seems just work thing. not user experience. if we need to make one, then we will make one.

It is *not* "just [a] work thing".  And it is very much *not* "not user experience".   A piece of UI is absolutely tied into the user experience around a feature, and the Roslyn IDE team has taken a principled and consistent stand on our feelings around those sorts of UIs since the inception of the team.  The stand is *not*, and has *never* been "we will *not* have UI".  The stand has been "this is part of the user experience, and we should be conscientious about using it, and especially about not using is unnecessarily."

This is the position i was taking, and i was only specifically addressing points of yours that were actually contradictory to the actual positions and conclusions the IDE team has made in these areas int eh past.

--

Now, at this point, i think this should be tabled.  If you think the IDEs past decisions here should be reconsidered.  That's fine.  But please don't re-litigate it here.  Please just take it to a design meeting.  I'll accept whatever outcome comes of that.  But it does not help to have that back and forth happening here.  It just masks being able to talk about the actual feature itself.

**Comment by heejaechang** [comment]
so, let me say my opinion? I am not sure what you are trying to keep picking up for? 

this was my post
> we could do something like push down to derived types or interface implementation to show dialog box like signature change. if there are a lot of derived or implementation, user might need to search among those and multi select and etc? and if it can, preselect types the method is called off in source code ?

and we could stict to it. and discuss whether UI will help or not.

**Comment by CyrusNajmabadi** [comment]
@heejaechang I think this may be a bit of a communication problem.  The only thing i started saying about UI was this:

> It's somewhat like a language feature. Things like UI start at negative 1000 points. If they can show they're valuable enough, or we can show we just can't develop a streamlined way to interact with them through existing mechanisms, then we can certain provide custom UI. But it's generally a last resort instead of something embraced up front.

in no way does that imply that we should not do UI.  But what it states is that if we are to do UI, it should be in a reasoned manner where the UI justifies its existence against the other potential approaches we normally take.  This has long been the IDE's position on UI, and i think it's an accurate state to put forth.

I feel like you read the above as a statement disallowing UI, and indicating that it was not the right choice for this feature.  On the contrary, as i pointed out *explicitly* it may very well be that UI *is* the right choice here.  However, we'd want to be totally sure of that, and we'd need to appropriately measure it against the alternatives available.

I regret if anything in my choice of words has led you to read things in a different manner.  But i please ask that you work with me to get a good understanding of the position if there's any doubt in your mind.  For example, when saying something is "generally a last resort", that is not at all an absolute, but is (as stated) a *general* approach we take.  It means that it's how things are *commonly* done, but by no means means that they must *always* be done that way.  I definitely get the sense that this doesn't come across clearly enough.  So i'd like to work with you if possible to help out here.

**Comment by heejaechang** [comment]
I usually don't come to PR to argue with you. I just write my opinion and you jump over. I don't get what you are trying to do.

**Comment by CyrusNajmabadi** [comment]
>we could do something like push down to derived types or interface implementation to show dialog box like signature change. if there are a lot of derived or implementation, user might need to search among those and multi select and etc? and if it can, preselect types the method is called off in source code ?

I literally agreed with that position.  My very post quoting that position said *exactly* that:

> Yes. Such an approach could potentially work out. i.e. the lightbulb menu would be Push down to derived type.... The ... being our signal that this will end up causing more work to happen (including potentially UI) once selected.

> Note: i wasn't saying there were no solutions here. Just that this was a general area of concern as we don't want to accidently check in something that runs in unbounded time, in an code location that has tight time constraints.

Not only did i agree with your position, i took the time to try to clarify my own to make sure tehre was no confusion about the concerns i was bringing up.

--

This is the second time i've stated agreement with you on a topic, only to have to have a dozen additional messages fly back and forth because that agreement doesn't seem to have been understood.

please let me know what i can do to be clearer here.  If it means explicitly stating "yes, i agree that that seems like a viable strategy to investigate" i'm willing to state that.  It's just not clear to me what i need to do to make my positions clearly understood here.

**Comment by CyrusNajmabadi** [comment]
> I just write my opinion and you jump over.

I'm at a loss.  I just stated what i was trying to do.  Which was to specifically address points of yours that i believe contradicted intentional design choices and decisions made by the IDE team over the last decade+.  

I said it literally right here: https://github.com/dotnet/roslyn/issues/25145#issuecomment-421517316

I really don't know what to do.  I've tried to be as explicit as possible about my agreements with you.  I've tried to be as explicit as possible about when i'm bringing in important historical context and understanding htat contradicts positions you've taken.  

I've tried to be as explicit as possible about what i think shudl be the right course of action if there is disagreement on those historical positions.    And i've laid out, with specific examples, of how i think the conversation goes off the rails (commonly because there seems to be a deep misunderstanding about what was actually said and how it was interpreted).  I literally do not know how to help this situation at all, and i'm dismayed that once again a conversation has drifted so far off topic.

**Comment by heejaechang** [comment]
@Cosifne sorry for making your issue so messy. that was not my intention. 

I just wanted to say my opinion.

> we could do something like push down to derived types or interface implementation to show dialog box like signature change. if there are a lot of derived or implementation, user might need to search among those and multi select and etc? and if it can, preselect types the method is called off in source code ?

github allows you to hide posts you feels like it is not giving value to your issue. feel free to hide any posts.

**Comment by heejaechang** [comment]
@CyrusNajmabadi just came home. and sure more posts. I am sorry as well if you think I misunderstood or not read what you wrote. I read them. just I wasn't looking for your agreement.

the post I wrote was not even to you or asking your opinion. I wrote it for @Cosifne since I didn't want him to shut down the idea of having dialogbox.

also, about jumping over. just look any issues or PRs. and count number of comments you wrote. it is all over the places. so I don't even need to tag one. just go to any one of them.

for example, right before this, I wrote on joey's PR that having the feature in the code clean up will be nice. again, I am not asking your approval or agreement or anything. I was talking to joey. yet. you wrote I dont know over 20-30 posts saying that's wrong or bad or I dont know. if that's not jumping over, I dont know what it is. you don't need to agree with my opinion. if you don't, just ignore. as much as I dont need to agree with your opinion.

there are bunch more, but gonna spend time with family now. if you want, sure we can keep going on and on. but I really want to say that I am not the one who started this long posts. and I dont have any intention to stop writing my opinion whether you like it or not.

**Comment by CyrusNajmabadi** [comment]
> you wrote I dont know over 20-30 posts saying that's wrong or bad or I dont know.

I'm really sorry that that's your takeaway from my posts.

**Comment by Cosifne** [comment]
A general quick summary about the design review.
1. UI or Light bulb
Use light bulb to do quick and clear refactoring. And show a "..." option at the bottom, which can pop up a dialog to provide the user some complex push up operations. (like change the modifiers)

2. Problem about the cost of push down.
First just focus on pushing up function, because people mainly use this. If the push down is really needed by the user in the future, then consider to do it.

**Comment by Cosifne** [comment]
> 
> 
> If anyone here is interested in tryin to create this feature, i'd be happy to help them with guidance on how to do so in Roslyn.

Hello Cyrus, do you know how to create a dialog using Rolsyn's API? It should be similar to the one when user want extract interface. I see the code there it implements ILanguage Interface but it is an empty interface. Could you explain its logic more clearly?

**Comment by CyrusNajmabadi** [comment]
@Cosifne Sorry, i'm unfamiliar with any interface called "ILanguage".  Can you point me at an example on github/dotnet/roslyn?  

> Hello Cyrus, do you know how to create a dialog using Rolsyn's API? 

My recommendation would be to start with an existing dialog and try to go from there.  That will help give you a sense of how you need to structure the xaml/code-behind/resources, and other things involved in a dialog.  

As an example, you could use the [PickMembers](https://github.com/dotnet/roslyn/tree/master/src/VisualStudio/Core/Def/Implementation/PickMembers) code as a starting point just to get something up and running.  Once there, you can then work toward modifying this dialog to the form you'd like for your feature.

**Comment by Cosifne** [comment]
> 
> 
> @Cosifne Sorry, i'm unfamiliar with any interface called "ILanguage". Can you point me at an example on github/dotnet/roslyn?
> 
> > Hello Cyrus, do you know how to create a dialog using Rolsyn's API?
> 
> My recommendation would be to start with an existing dialog and try to go from there. That will help give you a sense of how you need to structure the xaml/code-behind/resources, and other things involved in a dialog.
> 
> As an example, you could use the [PickMembers](https://github.com/dotnet/roslyn/tree/master/src/VisualStudio/Core/Def/Implementation/PickMembers) code as a starting point just to get something up and running. Once there, you can then work toward modifying this dialog to the form you'd like for your feature.

My bad, it is called ILanguageService. Sample is here [https://github.com/dotnet/roslyn/blob/master/src/Features/Core/Portable/ExtractInterface/AbstractExtractInterfaceService.cs](AbstractExtractInterfaceService)

**Comment by CyrusNajmabadi** [comment]
Hi @Cosifne ILanguageService is a *very* important part of how Roslyn internally works.  You can think of Roslyn as being a *mostly* language neutral framework for languages to plug into and light up (i.e. we currently support C#/VB/F#/TypeScript/JavaScript, and even some bits of xaml).  Because of this, the core parts of Roslny can't really depend on how those individual languages work (because they don't really share anything in common).

So, when there are times when Roslyn wants to provide some feature, but it needs to involve the languages to decide *how* to provide that feature, then it uses the ILanguageService to go talk to the right language depending on the feature/context.

Let's look at a concrete example: Outlining.

Outlining for every language is going to be language specific (i.e. C# will will want to collapse `{}` blocks, VB will want to collapse begin/end blocks, etc.).  So Roslyn defines this specific "ILanguageService" for the general act of producing outlining spans:

https://github.com/dotnet/roslyn/blob/master/src/Features/Core/Portable/Structure/BlockStructureService.cs

You'll note that there is not language specific here.  it just says "if you want to outline, just implement htis class, and give back BlockStructure values asynchronously for a given document".

Roslyn then hooks that all up.  When you open a Document it sees what language it belongs to.  It hten goes and loads the right ILanguageServices for that specific document, it can hten do things like properly outline the document, even though it may know nothing about that language.  

--

On the other side, individual languages provide implementations of these services, which then allows them to be found and used by the core Roslyn feature set.

--

Does that help clarify things?

**Comment by CyrusNajmabadi** [comment]
ALso, i'm routinely on gitter.  You might want to reach me over there as it will be easier to chat back and forth quickly, isntead of requiring lots of time to pass between each message.  Up to you if you want to do that :)

**Comment by Cosifne** [comment]
> 
> 
> ALso, i'm routinely on gitter. You might want to reach me over there as it will be easier to chat back and forth quickly, isntead of requiring lots of time to pass between each message. Up to you if you want to do that :)

Thanks, I will first read the code first and reach you out on gitter when I am feel confused

**Comment by jinujoseph** [comment]
Available via  https://github.com/dotnet/roslyn/pull/31211
thanks @Cosifne
