### ISSUE TITLE
C# Intellisense does not completely handle null conditionals

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#25221]
class A
{
public bool Foo(){return true;}
}

A a = null;
if(a?.Foo()) // does not compile, as expected, IntelliSense complains about not being able to cast bool? to bool, as expected

if(a?.Foo() == true) // Compiles as expected, however IntelliSense treats &quot;a?.Foo()&quot; as if it was bool, tooltip for == shows bool operator==(bool,bool), etc.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/182696/c-intellisense-does-not-completely-handle-null-con.html
VSTS ticketId: 552073_
_These are the original issue comments:_

**Comment by CyrusNajmabadi** [comment]
> however IntelliSense treats "a?.Foo()" as if it was bool, tooltip for == shows bool operator==(bool,bool), etc.

That is correct, and this is by design.  The == operator written there is the "operator ==(bool, bool)" from the perspective of hte compiler.

This is esp true if you have your own custom struct, with its own custom operator.  Similarly "Foo" is a reference to the method that returns "bool". Now, it's the case that because you have ?.  the compiler will only call that Foo method in teh case that 'a' is non-null.   But it's still correct that .Foo() returns bool.

--

Note that intellisense understand this fine if you type different things.  For example, if you write:  ```(a?.Foo()).```  then intellisense will rightly understand that *here* you have a nullable-bool, and thus should see the entries of 'nullable'.  But if you write ```a?.Foo().``` then here you have a boolean, and should see its members.

**Comment by lcsondes** [comment]
> The == operator written there is the "operator ==(bool, bool)" from the perspective of hte compiler.

Even if this is technically correct and there's a layer of nullable hacks on top, it's still immensely misleading from a code writer's perspective, because the == that's there is comparing bool? to bool-promoted-to-bool?.

If `== true` was removed, this code would (correctly) not compile, because `a?.Foo()` is a `bool?`. The `.` and `?.` also have way higher operator precedence than `==`, which should always be evaluated even if `a` is null (otherwise you could get `if(null)`). It's my understanding that property setters don't work with `?.` due to a similar line of reasoning (the assignment operator in that case being unaffected). Even if you add brackets around `(a?.Foo())` or use a `bool?` temporary variable for the RHS it still treats it as a regular `bool` even though at runtime you'll get the expected null-aware comparison.

In a different scenario, if you change `==` to `|` you'll get a compiler error about no implicit conversion from `bool?` to `bool`, it will get a squiggly red underline in VS, yet it will still say it's `bool operator|(bool,bool)` despite it actually being the expected ternary OR (that in the case of `|false` could be `null` so it can't possibly be static typed to `bool`).

**Comment by CyrusNajmabadi** [comment]
Given that this is how the language defines things, and how the compiler actually models things (both internally and through the public API), I think it's reasonable for the IDE to be honest and have quick-info exactly show the truth here.

I don't think there's much value in showing something different.  Esp. as you might then have a customer say: wait... why is it doing X when the language says it should be Y?
