### ISSUE TITLE
Introduce local for awaited result not working

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#25312]
- Install VS 15.6.0
- Create an async method in which you await another Task-returning method (using the following code: &quot;await AsyncMethod()&quot;)
- Select the &quot;await AsyncMethod()&quot; code and open IntelliSense. I expect to be able to introduce a local variable for the result, but I can't.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/209470/introduce-local-for-awaited-result-not-working.html
VSTS ticketId: 577883_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by Neme12** [comment]
It seems that the refactoring is not offered if the expression is in an expression statement.
The refactoring doesn't show up here:
```c#
static async Task M()
{
    await AsyncFunction();

    Task<int> AsyncFunction() => default;
}
```
but it is offered here:
```c#
static async Task M()
{
    var result = await AsyncFunction();

    Task<int> AsyncFunction() => default;
}
```

**Comment by Neme12** [comment]
In fact it doesn't have to involve async.
Similarly, no refactoring here around Function():
```c#
static void M()
{
    Function();

    int Function() => default;
}
```
but there is here:
```c#
static void M()
{
    var result = Function();

    int Function() => default;
}
```

**Comment by Neme12** [comment]
Can you please tell us what you'd expect the result to look like?

**Comment by CyrusNajmabadi** [comment]
> It seems that the refactoring is not offered if the expression is in an expression statement.

Yes.  This was intentional.  In such a case the refactoring doesn't seem to add value.  You can just define the variable right there :)   Similar to if you have ```var v = some_expr;```  we don't offer introduce-variable around some_expr because you already have a variable.

The primary purpose of introduce-variable is to take a sub-portion of some expression and 'extract' it out to its own variable, wit hthat variable now referenced where the original sub-portion was.

**Comment by CyrusNajmabadi** [comment]
This works fine if you're actually using the feature on an await-expression inside some larger expression:

![image](https://user-images.githubusercontent.com/4564579/37114765-1a2c4f60-21fe-11e8-87f0-8ed0f2531bca.png)

**Comment by Neme12** [comment]
@CyrusNajmabadi 
> we don't offer introduce-variable around some_expr because you already have a variable

Actually it is offered:
![image](https://user-images.githubusercontent.com/11444821/37116965-1710df60-2250-11e8-99e9-1f36c6d0c125.png)

**Comment by CyrusNajmabadi** [comment]
Interesting.  I wonder when that cahnged.  That was not part of the original design there :)

**Comment by CyrusNajmabadi** [comment]
>  If you do that, you probably do want to see a refactoring there.

Just because you want to see a refactoring, doesn't mean that *all* refactorings should be shown.  refactorings should be smart as to their likelihood so as to not overwhelm the lightbulb with too many unnecessary options.  Here, it is very wonky to allow introducing a variable, when literally right in the code *you have a variable* :)

It's like being on an interface and saying "i want to extract this interface into an interface" just on the off chance someone wants to duplicate the interface :)

That said, going back to the original issue (with expression statements), the primary problem is simply: what would we generate?  Intro-local creates a new local and then subs it back intot eh original location.  so if you have:

```Foo();```

And you do intro-local, do you get:

```c#
var v = Foo();
v;
```

?

Clearly, that would be bad.  So we'd end up not doing the substitution and just generating:

```c#
var v = Foo();
```

but at that point, why did you need "intro local"?  You're literally *right there*, so you can just define the local yourself.  It seems like jumping through more hoops to try to get the refactoring to do it for you.

--

The one exception i can envision is using this for "introduce local - for *all*".  In that case, you might have:

```c#
Foo();
Console.WriteLine(Foo() + Foo());
```

Maybe you see that and you want to transform that into:

```c#
var v = Foo();
Console.WriteLine(v + v);
```

**Comment by Neme12** [comment]
> Interesting. I wonder when that cahnged. That was not part of the original design there :)

Are you sure you're not confusing this with the case where the expression you're selecting is a variable? (as opposed to an expression that's assigned to a variable)
```c#
var v = 0;
Console.WriteLine(v);
```
Here if you select 'v', the refactoring is not offered, which definitely seems reasonable to me.

**Comment by CyrusNajmabadi** [comment]
> Are you sure you're not confusing this with the case where the expression you're selecting is a variable? (as opposed to an expression that's assigned to a variable)

Possible.  As this code goes way back, it's hard to tell (and i'm not really interesting in doing the spelunking) :)

**Comment by CyrusNajmabadi** [comment]
Closing out.  Not likely to do this.
