### ISSUE TITLE
Make IAddImportsService public?

### ISSUE THREAD

**Issue by JohanLarsson** [dotnet/roslyn#25343]
The need for adding using directives comes up every now and then in code fixes.

**Comment by CyrusNajmabadi** [comment]
Can you be more specific about your general scenario?  What are you trying to accomplish?  I ask because SyntaxGenerator already has a mechanism for adding imports.  Namely, if you use it to generate types you can say ```generator.TypeExpression(type, addImport: true)```

And then in any code-fix, the proper import will be added (if not there) to make it so that the type does not have to be fully qualified.  Can you give your scenario so that we can understand why that existing mechanism is not sufficient?  Thanks!

**Comment by JohanLarsson** [comment]
That sounds like what I was after, asked in chat as it felt like there should be something for it.
I wrote [this](https://github.com/DotNetAnalyzers/PropertyChangedAnalyzers/blob/master/PropertyChangedAnalyzers.CodeFixes/Helpers/DocumentEditorExt.cs#L87) today for adding using directives.

It adds the using sorted like stylecop wants it and figures out if it should add the first directive inside or outside the namespace by walking the syntaxtrees in the compilation.

**Comment by CyrusNajmabadi** [comment]
Closing out.  Question was answer and solution was provided.
