### ISSUE TITLE
Crash when opening Code style

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#25393]
When I am trying to open
Tools-&gt;Options...-&gt;Text Editor-&gt;C#-&gt;Code style
visual studio is crashing. It is very disappointing =(

It was three time. But when I was tried to create screenshot for this report all started works fine. It's magic support I suppose.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/200791/crash-when-opening-code-style.html
VSTS ticketId: 569480_
_These are the original issue comments:_

Ariel Yang - MSFT on 2/23/2018, 07:01 PM (13 days ago): <p>Thank you for your feedback. In order to investigate your issue further, would you be able to send us crash dumps for Visual Studio process? These process dumps files would help us to root cause the issue.</p><p>1) Enable user-mode dump collection by running the following command in an administrator command prompt: reg add &quot;HKLM\Software\Microsoft\Windows\Windows Error Reporting\LocalDumps\devenv.exe&quot; /v DumpType /d 2 /t REG_DWORD</p><p>2) This command will enable Windows to automatically collect a crash dump and store it under %LOCALAPPDATA%\CrashDumps</p><p>3) Use Visual Studio normally to reproduce the crash, once crash occurs let all Windows crash dialogs finish processing.</p><p>4) Go to %LOCALAPPDATA%\CrashDumps and locate the latest dump file for devenv.exe process.</p><p>5) You can run the following command to revert back dump collection to its original state:</p><p>reg delete &quot;HKLM\Software\Microsoft\Windows\Windows Error Reporting\LocalDumps&quot; /f</p><p>We look forward to hearing from you.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by jinujoseph** [comment]
stack 

Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at Microsoft.VisualStudio.LanguageServices.Implementation.Options.OptionPreviewControl.LoadSettings()
   at Microsoft.VisualStudio.LanguageServices.Implementation.Options.AbstractOptionPage.OnActivate(System.ComponentModel.CancelEventArgs)
   at Microsoft.VisualStudio.Shell.DialogPage+DialogSubclass.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr, Int32, IntPtr, IntPtr)

**Comment by poid** [comment]
I'm having the exact same issue in Version 15.7.6. It crashes each and every time I click C# -> Code Style. 
Quite discouraging to know this issue has been around since March and is still an issue in August.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of prism hits.
