### ISSUE TITLE
Make DecodeAttributeUsageAttribute() public

### ISSUE THREAD

**Issue by Inspyro** [dotnet/roslyn#2548]
Hi, 
We need to read the _AttributeUsageInfo_ from the  _AttributeData_ , in the roslyn source code i found the static method:
_static internal AttributeUsageInfo DecodeAttributeUsageAttribute()_
which apparently does exactly what we want. 

**Could you make this method (and class) public**? Or a way to check wether an attributedata is applicable to a certain symbol (Property, Class)

**Comment by CyrusNajmabadi** [comment]
This would need to go through an API proposal.  in general, the reason we don't just make things public is because it increases maintenance costs and locks down our ability to change things in teh future.  We can open things up, but we have a process that requests need to go through to make sure the appropriate people weigh in and the right API shape is determined and shipped.  Importantly, any extension points need strong evidence that they can be provided in ways that do not impact scalability, and can have good debugging/editing experiences around them.
