### ISSUE TITLE
[Go To All] Extend Go To All to search for text

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#25498]
Several customers have asked for the ability to allow text search from the Go To All dialog. They find the performance of Find in Files suboptimal and want one place to search for everything in their solution.

I'm thinking we would need to have this as another 'category filter'...

**Comment by CyrusNajmabadi** [comment]
This feels like this belongs to the editor, not to Roslyn.  @olegtk Do you agree?

**Comment by olegtk** [comment]
totally. @jinujoseph please route it to the editor.

**Comment by CyrusNajmabadi** [comment]
> They find the performance of Find in Files suboptimal

Can you expand on this.  If 'Find in Files' is suboptimal,how does 'allow[ing] text search from the Go To All dialog' help?  Go-to-all would just run the same code that Find-in-Files runs today.  So it would be the same speed (unless i'm missing something).

Also, FindInFiles seems blazingly fast for me (it actually uses all my cores!), except for when it actually has to go and read all the data off disk right after an OS reboot.  It's unclear how things would be fast *unless* this is about the editor investing in some sort of indexing system that could be queried instead of actually reading all the contents from disk.  But i have no idea how that would work given all the types of strings people can search for.

**Comment by jinujoseph** [comment]
moved to editor team [link](https://devdiv.visualstudio.com/DevDiv/NET%20Developer%20Experience%20Productivity/_queries/edit/584195)
