### ISSUE TITLE
SolutionSizeTracker is a singleton incremental analyzer instance

### ISSUE THREAD

**Issue by Therzok** [dotnet/roslyn#25599]
**Version Used**: 
dev15.7.x

Although PersistentStorage was properly moved to a workspace service, this should be done too. Otherwise all solutions from workspaces other than the main solution will end up clearing the incremental analyzer cache.

**Expected Behavior**:

SolutionSizeTracker should be able to track more than one solution.

**Actual Behavior**:
SolutionSizeTracker does not to track more than one solution.

**Comment by Therzok** [comment]
cc @jasonmalinowski

**Comment by jasonmalinowski** [comment]
FYI to @heejaechang too. @Therzok for our triage purposes, this is blocking for you or just an annoyance?

**Comment by Therzok** [comment]
@jasonmalinowski There's 2 things which I consider might have a big impact:
a) SolutionSizeTracker cache will be broken, and it'll recompute everything on every solution snapshot
b) Checks for persistent storage will be broken until a new solution snapshot is done. The tracker needs to exceed a threshold (we set it to 0), but it returns -1 on solution id mismatch. (I suppose setting the application level threshold to -1 might surface new bugs)

**Comment by CyrusNajmabadi** [comment]
Another option: just remove this tracker entirely.  It's not clear that it actually solves a valuable purpose.

**Comment by heejaechang** [comment]
I think I dont have full context.

not sure what it means by "Although PersistentStorage was properly moved to a workspace service,"

currently, "SolutionSizeTracker" only runs over solution from Workspace.Kind == Host and Workspace.CurrentSolution. SolutionCrawler guarantee that.

IPersistentStorageService used to return NoOp service except for Workspace.Kind == Host & solution from Workspace.CurrentSolution from the workspace service factory.

looks like it doesn't care anymore. no idea what's current behavior of it is if Workspace is not Host (VSWorkspace or RemoteWorkspace)

the service as I know use same db location and use documentId,ProjectId,SolutionId as key where they are unique only inside of same Workspace. so 2 workspace (ex, PreviewWorkspace, VSWorkspace) might share same documentId and step over each other.

**Comment by heejaechang** [comment]
I suggest put that check back in the PersistentService and return only Sqlite service if given workspace is workspace host. otherwise return NoOp service.

otherwise, the service should either create new db files per workspace, or db schema should contains workspace id (we need to define what it is first) in it. not just document/project/solutionid.

once we have workspace id in it, we need to define when to delete those data since workspace (and data in it) can be temporary.

or we can force people who uses IPersistenService to only uses Checksum and remove it being used with Versions.

also, once we go there, we need to remove all features that uses the persistent service for states not caches, since checksum and multiple workspace basically means state can't be saved there anymore.

**Comment by jasonmalinowski** [comment]
> IPersistentStorageService used to return NoOp service except for Workspace.Kind == Host & solution from Workspace.CurrentSolution from the workspace service factory. looks like it doesn't care anymore. no idea what's current behavior of it is if Workspace is not Host (VSWorkspace or RemoteWorkspace)

This is correct: both run, but they have a different IPersistentStorageLocationService that specifies where each will serialize. So for other workspaces, it's "running" but since nobody provides that it'll no-op.

What IPersistentStorageService was doing that was really strange before (and what @Therzok is referring to) is it was a workspace service, but would also accept Solutions from other workspaces, and then go ask *that* workspace for it's IPersistentStorageLocationService and use it kinda somewhat. Now it's for each workspace, there's an IPersistentStorageService and IPersistentStorageLocationService. It might so happen that they are the same code (but separate instances), but that's just coincidence.

**Comment by heejaechang** [comment]
I see. then, we can make either ISolutionSizeTracker workspace service or merge it with IPersistentStorageLocationService.

**Comment by heejaechang** [comment]
where this happen?
> all solutions from workspaces other than the main solution will end up clearing the incremental analyzer cache.

cache is built by solution crawler and it is marked to run only for Workspace.Host

**Comment by Therzok** [comment]
We can hold multiple host workspaces alive at a time. Each with their own MEF composition. Having the solutionTracker return a singleton effectively [here]9https://github.com/dotnet/roslyn/blob/master/src/Workspaces/Core/Desktop/Workspace/SolutionSize/SolutionSizeTracker.cs#L21) breaks multiple workspace support.

**Comment by heejaechang** [comment]
I see, so you are saying, it could happen, not it happens currently. 

...

basically this code is wrong
https://github.com/dotnet/roslyn/blob/master/src/Workspaces/Core/Desktop/Workspace/SolutionSize/SolutionSizeTracker.cs#L33

since, SolutionCrawler is the one what is supported not IPersistentStorageLocationService.

**Comment by heejaechang** [comment]
by the way, not sure we support having multiple Workspace.Kind == Host in one process since assumption is there is only 1 host (main workspace) in process.

**Comment by heejaechang** [comment]
looked our WorkspaceService provider implementation. 

having WorkspaceServices doesn't make service to be different between different workspace. same workspace kind will get same workspace services if the service is exported as WorkspaceService.

different workspace kind get different workspaceservices. but instance.

if one exports workspace service as WorkspaceServiceFactory, implementation can choose to return different workspaceservice between different workspace even though workspace.kind is same.

so, contract looks like quite tightly coupled with how IPersistentStorageservice is Implemented. 

but, that seems really bit weird since IPersistentStorageService is exported as WorkspaceServiceFactory which it doesn't need to, since it is the IPersistentStorageLocationService that need to return different service per workspace, but the IPersistentStorageLocationService itself is NOT exported as IWorkspaceServiceFactory but IWorkspaceService. 

meaning it will be shared between same Workspace.Kind but different only between different Kind.

so, 
> We can hold multiple host workspaces alive at a time. Each with their own MEF composition. Having the solutionTracker return a singleton effectively [here]9https://github.com/dotnet/roslyn/blob/master/src/Workspaces/Core/Desktop/Workspace/SolutionSize/SolutionSizeTracker.cs#L21) breaks multiple workspace support

this doesn't work for IPersistentStorageLocationService either. 

sounds like, all this service (ISolutionSizeTracking, IPersistentStorageLocationSerivce, IPersistentStorageService) should be implemented by 1 type that implementation is tightly coupled each other. 

since they have very specific assumption each other in current implementation.

**Comment by heejaechang** [comment]
right now, the way things are implemented, all seems should work since IPersistentStorageLocationService should be shared between same workspace.Kind. making SolutionSizeTracker to behave same.

that being said, it feels like we should merge all these 3 to 1 type so that contracts are shared.

...

looking more of our code, having mutliple workspaces with same Kind (Host) will break bunch of things. so I dont think that is supported scenario. if we want to support that scenario, we probably need to change more than just persistent service.

**Comment by Therzok** [comment]
IPersistentStorageLocationService takes a solutionId parameter which allows us to return different paths.

**Comment by Therzok** [comment]
SolutionSizeTracker also takes a SolutionId parameter, but it returns a cached result for only one solutionId, and invalidates on new snapshot. The proper thing to do would probably be to have a cache per solutionId in a CWT.

**Comment by Therzok** [comment]
I fixed the PR title. I was referring to the incremental analyzer being a singleton, not the tracker itself. It looks like other incremental analyzer providers support multiple workspaces:
http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures/Implementation/TodoComment/TodoCommentIncrementalAnalyzerProvider.cs,21
http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/Diagnostics/DiagnosticAnalyzerService_IncrementalAnalyzer.cs,17

**Comment by heejaechang** [comment]
> IPersistentStorageLocationService takes a solutionId parameter which allows us to return different paths.

you shouldn't do that. solutinId/projectId/documentId is only unique within same workspace. 2 different workspaces are completely fine to have 2 completely different contents with same id.

so you can't pivot by solutionId for 2 different workspaces.

proper way will be you returning different different location per workspace. otherwise, if you have 2 workspace with same solutionId, all will get messed up.

...

I think proper fix is what I said above. we should move those 3 related thing together. and set expectation to be same.

right now, assumption is that persistent service only support 1 workspace (Host kind) per process and there can be only 1 workspace.Kind == host per process.

**Comment by Therzok** [comment]
Oh, I see why and yes, not using solution id makes sense.

In the end, it seems that supporting multiple host workspaces has more implications than I initially thought.

Maybe this issue should fit under an umbrella which tracks multiple host workspace support?

In VSMac, we create a Workspace per Solution we have open and can support multiple solutions open at the same time.

**Comment by heejaechang** [comment]
> n VSMac, we create a Workspace per Solution we have open and can support multiple solutions open at the same time.

I see. that is the fundamental difference to VS. since we assume there is only 1 Host type workspace, I believe we have some bulletin assumption on those. including PrimaryWorkspace thingy.

 > this issue should fit under an umbrella which tracks multiple host workspace support?
that sounds like the actual work we need to do.

**Comment by heejaechang** [comment]
I am not sure how things will currently react for opened files, linked files and etc...when there is multiple workspaces with host kind...

**Comment by CyrusNajmabadi** [comment]
SolutionSizeTracker has been removed.
