### ISSUE TITLE
Create a refactoring service for keeping user code style

### ISSUE THREAD

**Issue by ivanbasov** [dotnet/roslyn#25694]
We should have refactoring service that return document that changes code following code style options like

`Document = ICodeStyleService.ApplyCodeStyle(Document, Options)`

So that each refactoring, code fix doesn't need to care about those code style at all, and all features can follow all code styles as we add more of them

**Comment by ivanbasov** [comment]
FYI: @heejaechang

**Comment by CyrusNajmabadi** [comment]
Note: we already have an annotation for that.  The simplification annotation.  This would be able ensuring that places where we put the simplification annotation are properly respected by teh simplifier service.  

For example, the simplifier service should take qualified-annotated-type-names and change them to "var" if it fits the user's setting.  Similarly, if "default(T)" is generated and annotated, it should become "default" if the user has that setting. On so on and so forth.

Note: this will require the user use things like SyntaxGenerator so that our later passes know what is *new* code as opposed (and thus should be mutated) vs what is *existing* code (and thus shoudl not be touched).  After all, even if a person prefers 'var', an unrelated code-action shouldn't cause us to make all the TypeNames in a file 'var' just because the file was passed through this 'apply code style' pass.

**Comment by CyrusNajmabadi** [comment]
This would need to go through some sort of api review that fleshed out what api we're asking for and how it would work.
