### ISSUE TITLE
"Generate Equals" refactorings should not include set-only properties

### ISSUE THREAD

**Issue by jhinder** [dotnet/roslyn#25707]
**Version Used**: VS 15.7 Preview 2 (Roslyn 2.8.0.62716)

**Steps to Reproduce**:

1. Copy the class below into a C# source file.
2. Invoke the Quick Fix menu at the marked location and select either "Generate Equals" or "Generate Equals and GetHashCode".
3. Make sure SetOnly is marked in the list and press "OK".

```c#
class Repro
{
	int SetOnly { set { } }
	$$
}
```

**Expected Behavior**: The property is not included in the list, and thus doesn't appear in the generated code.

**Actual Behavior**: The generated code looks something like this:

```c#
public override bool Equals(object obj)
{
	var repro = obj as Repro;
	return repro != null &&
		   this.SetOnly == repro.SetOnly; // Emits two CS0154 errors
}

public override int GetHashCode()
{
	return 257811045 + this.SetOnly.GetHashCode(); // Emits one CS0154 error
}
```

**Comment by CyrusNajmabadi** [comment]
I personally think it's fine to have this behavior.  This is a refactoring, and we want to allow the user to do things like generate equals/gethashcode even if they're in the middle of writing everything up.  It may be that they intend to make this readable as well as writable shortly therafter.

> Make sure SetOnly is marked in the list and press "OK".

And, the current behavior is that we just put the item in the list.  If the user sees that and still chooses to keep that member part of their equality/hashing member... i'm not sure what the problem is :)

--

that said, i don't feel strongly about this.  Setter only props are pretty uncommon, and it's probably fine to filter them out here.
