### ISSUE TITLE
No suggested usings when initializing fields

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#25705]
**Version Used**: 15.7 Preview 2

**Steps to Reproduce**:

```C#
using System;

namespace WPFConsoleApplication2
{
    class Program
    {
        static byte[] Data = Encoding|

        [STAThread]
        static void Main(string[] args)
        {
        }
    }
}
```

**Expected Behavior**: Add "using System.Text;" suggested. 

**Actual Behavior**: Only encapsulate field and add accessibility modifiers are suggested. Note also that encapsulate field adds the property in between `[STAThread]` and the `Main` method.

**Comment by CyrusNajmabadi** [comment]
This is likely due to the parser thinking this is:

```c#
static byte[] Data = Encoding[StaThread]
```

There are a few things that can help out here, including (but not limited to): 

1. attempting to improve the parser here.  Though this will be an uphill battle due to how complex attributes can be.
2. Improving add-using here to understand that Encoding can actually be a reference to a type, and is not necessarily a value that is being indexed by ```[StaThread]```

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
