### ISSUE TITLE
Pattern cast matching with dynamic object causes CS0165

### ISSUE THREAD

**Issue by mikasoukhov** [dotnet/roslyn#25718]
**Version Used**: 
C# 7.0 (VS 2017)

**Steps to Reproduce**:

```
static void TestIssue()
{
	dynamic obj = new { status = "error" };

	if (obj is JObject o && obj.status == "error")
		throw new InvalidOperationException((string)o.Property("err-msg")?.Value);
}
```

**Expected Behavior**:
Successful compilation

**Actual Behavior**:
error CS0165: Use of unassigned local variable 'o'

**Comment by gafter** [comment]
Although it is counterintuitive, the compiler might be correct. The `&&` operation is [not a compile-time boolean short-circuiting operation](https://github.com/dotnet/csharplang/blob/master/spec/expressions.md#conditional-logical-operators) because its right-hand operand is of type `dynamic`:

> If an operand of a conditional logical operator has the compile-time type `dynamic`, then the expression is dynamically bound (Dynamic binding). In this case the compile-time type of the expression is `dynamic`, and the resolution described below will take place at run-time using the run-time type of those operands that have the compile-time type `dynamic`.

Because of that you cannot expect the compile-time definite assignment rules to apply.

**Comment by svick** [comment]
@gafter Does that mean that the most reasonable way to work around this problem is to cast away the `dynamic`-ness? E.g.:

```c#
if (obj is JObject o && obj.status as string == "error")
```

Or:

```c#
if (obj is JObject o && (bool)(obj.status == "error"))
```

Though it seems to me that definite assignment rules *could* apply, even if the spec currently says they don't. (But I guess that would be an issue for dotnet/csharplang, not dotnet/roslyn.)

**Comment by mikasoukhov** [comment]
I think in my example o will be initialized every time in any case. So if the C# spec is not cover it.... so let enforce C# spec at the first =)

**Comment by gafter** [comment]
Reported as a spec issue https://github.com/dotnet/csharplang/issues/1414
