### ISSUE TITLE
Intellisense does not work in nameof expressions

### ISSUE THREAD

**Issue by ilkayilknur** [dotnet/roslyn#2596]
``` csharp
class Program
{
    static void Main(string[] args)
    {
        Foo foo = new Foo();
        Console.WriteLine(nameof(foo));
    }
}

class Foo
{
    public int Bar { get; set; }
}
```
When I type dot after foo in nameof expression, intellisense doesn't show any suggestions. Intellisense should suggest `Bar` property.

**Comment by FunctionalFirst** [comment]
I think this is by design. Quoting from the [C# FAQ blog](http://blogs.msdn.com/b/csharpfaq/archive/2014/11/20/new-features-in-c-6.aspx):

>`WriteLine(nameof(person.Address.ZipCode)); // prints "ZipCode"`
*Note: there are small design changes to nameof since the Preview was built. In the preview, dotted expressions like in the last example, where person is a variable in scope, are not allowed. Instead you have to dot in through the type.*

**Comment by Pilchie** [comment]
This is the same issue as https://github.com/dotnet/roslyn/issues/1663.

It's true that this doesn't work in the RC build of VS2015, but it has been fixed for the next release.
