### ISSUE TITLE
When keyword recommender failure with recursive patterns

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#25998]
Some keyword recommender tests are skipped in the branch `features/recursive-patterns` because the implementation does not handle recursive patterns. This is a specific line skipped in `WhenKeywordRecommenderTests.cs`:

``` c#
        [InlineData("(1 + )")]
```

**Comment by Neme12** [comment]
If `(1 + 1) w` is now a deconstruction pattern, then it's probably the right thing to not offer `when` so that we don't interfere with the declaration. It might be OK if it is just in suggestion mode, but it would still be a little distracting to see `when` every time you're typing a variable name for a deconstruction. It might be fine if there was also completion for suggested names and `when` was just one additional item in the list, but I don't see how that could be work in a deconstruction (I might be wrong, I still don't understand this in detail).

**Comment by jcouv** [comment]
Fixed in https://github.com/dotnet/roslyn/pull/30243
