### ISSUE TITLE
QuickInfo shows type for `default` literal, but not `null` literal

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#26027]
Both `default` and `null` get an inferred type, which the compiler exposes via semantic model.
I think QuickInfo should show the type in both cases.

![image](https://user-images.githubusercontent.com/12466233/38472834-b55a7318-3b3a-11e8-8bc1-96452c1f90d9.png)

![image](https://user-images.githubusercontent.com/12466233/38472847-d4489eee-3b3a-11e8-8c8e-eab895c38c0b.png)

**Comment by Neme12** [comment]
> Both default and null get an inferred type, which the compiler exposes via semantic model.

I just checked and GetTypeInfo().Type returns a type for `default` but null for `null`. Is this expected?

**Comment by jcouv** [comment]
@Neme12 Thanks. That seems unexpected. Signing to compiler to take a look.

**Comment by Neme12** [comment]
With a null literal, `Type` is null but `ConvertedType` is not. This actually makes sense to me because the type is only acquired after the conversion. Should that be the same for default? I think `Type` should be null as well since the target type is only acquired through the conversion which is classified as `ConversionKind.DefaultOrNullLiteral`. This is similar to how lambda expressions work.

**Comment by Neme12** [comment]
I debugged through the code and it seems `Type` is artificially added to the default literal here:
https://github.com/dotnet/roslyn/blob/216993f315119fe855fe452827ab2832593475e0/src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs#L114-L118
by recreating the bound node to add the constant value. The original `source` indeed does not have a `Type`.

**Comment by jcouv** [comment]
Yes, there is a discrepancy between null and default, but that may be OK. The idea is for 'default' to behave just like 'default(T)' with inferred 'T'.
Then maybe the problem is in IDE after all. Maybe QuickInfo should show converted type of no type.

**Comment by Neme12** [comment]
Great,  I just couldn't find anything about default literals in the spec.

Should IDE show always show converted type if type is null or only in case of null/default? I'm not sure what other tokens this might affect, if any.

**Comment by Neme12** [comment]
I only found this from the proposal (might be outdated):
> A new expression is introduced, the default literal. An expression with this classification can be implicitly converted to any type, by a default-or-null literal conversion.
>
>The inference of the type for the default literal works the same as that for the null literal, except that any type is allowed (not just reference types).
>
>This conversion produces the default value of the inferred type.

**Comment by Neme12** [comment]
This snippet from a design meeting makes it even clearer, but might be even more outdated:
>In essence, default is like null: an **inherently typeless expression**, that can acquire a type through implicit or explicit conversion. Unlike null, default can be converted to any type T, including non-nullable value types, and is equivalent to default(T) for that T. For types where both null and default are allowed, they both have the same value, namely null.

**Comment by Neme12** [comment]
This comment also suggests it should be null:
https://github.com/dotnet/roslyn/blob/88801fa234db8f1bd16b30c04971311915a04cd7/src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml#L550-L554

I find it a little weird that there's a conversion of `ConversionKind.DefaultOrNullLiteral` which converts from and to the same type.

**Comment by Neme12** [comment]
It seems there was a discussion about this here: https://github.com/dotnet/roslyn/pull/17205#discussion_r102340554 and some disagreement between @AlekseyTs and @gafter

**Comment by Neme12** [comment]
I was actually bitten by this oddity here: #26140

**Comment by gafter** [comment]
I think both the spec and design notes are clear about the language intent: `default` is typeless and gets a type on conversion.

**Comment by Neme12** [comment]
@jcouv @gafter Can you please relabel this as Area-IDE instead of Area-Compilers, and if you feel the default literal should have a null type, please make a separate issue?

The original issue says
> I think QuickInfo should show the type in both cases.

and I'd like to consider that fixes as part of #30364. The compiler issue here is mostly unrelated because if it was fixed, there would be QuickInfo for neither the default or a null literal, not both as the issue requests. The IDE fix would still be necessary, and it's completely independent of any compiler fix (if there will be any).
