### ISSUE TITLE
Microsoft.NETCore.Compilers v2.7.0 package is broken

### ISSUE THREAD

**Issue by tannergooding** [dotnet/roslyn#26033]
Currently attempting to use the v2.7.0 package for Microsoft.NETCore.Compilers results in a failure because of an unmatched quote.

This was already fixed here: https://github.com/dotnet/roslyn/pull/25220, but it was not included in the RTM release.

Ideally, the fix should be backported and a v2.7.1 package should be released with the fix.

**Comment by agocke** [comment]
These are the same binaries as were shipped in .NET Core SDK 2.1.10x, so as an alternative, the user can download that SDK and ignore the NuGet package entirely.

**Comment by jaredpar** [comment]
Fixing the package itself does not meet the bar as there are no direct consumers of the broken code today. Should a case come up where we need to fix 2.7 + deliver a hot fix to customer of that package then the bug will be fixed in the 2.7 train. Outside that customers can use the 2.8 train to get the correct package.
