### ISSUE TITLE
Lightbulb suggests renaming a type to "var"

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn#2605]
Screen shot says it all:

![rename type to var](https://cloud.githubusercontent.com/assets/11762653/7544397/86498a3e-f581-11e4-88a3-fc26889eb8c9.png)

**Comment by pharring** [comment]
@lgolding Is this with VS 2015 RC? If not, what version of VS and Roslyn are you using?

**Comment by lgolding** [comment]
Yes, 2015 RC. 22822.1 IIRC, although I don't have it in front of me here on the bus :)

Sorry, I included that information when I originally filed the bug in TFS, but forgot to mention it when I re-filed it in GitHub.

Larry

Sent from my Windows Phone
________________________________

**Comment by dpoeschl** [comment]
@lgolding Did you manually replace the type name with "var" by typing "var" (or pasting it or making some other edit), or did you run an automated fix that reduced the type name to "var" automatically?

Some background: When a reference is tracked for rename, we usually show the dotted border around the identifier. But, once the identifier binds to something again (whether a different symbol or, in this case, the same symbol), the dotted border goes away because you're probably done with your edit. But, we continue to allow the rename to be executed just in case the user really wants to rename the original underlying symbol to a name already used by another symbol (probably introducing an ambiguity at the current reference, but that's their decision), or they really want to rename the underlying symbol to "var" in this case, since it would be a legal rename.

There's a few things we could do here:
1. Don't offer RenameTracking fixes when the new name binds to the same symbol as the old name (this wouldn't help if the ```var``` in your example were previously some base type or interface of ResultCollection, but it would fix cases where the ```var``` is the same type as the one replaced).
2. Special case "var" in RenameTracking and disallow renames to it.
3. Disallow RenameTracking after any type of "programmatic edit" -- If you replaced the "ResultCollection" with "var" by invoking a code fix that converted it to "var", then we would have to detect that the edit was caused by a programmatic edit rather than a user edit and reset the Rename Tracking state. This has been discussed before but it quickly gets tricky and error prone, so we haven't implemented it.
4. Do nothing. We've removed the dotted outline in this case to indicate that Rename Tracking doesn't think you *need* to do anything, and renaming to "var" would indeed be valid.

For now, I'd vote for either 4 (do nothing because it would be a legal rename) or 2 (special case "var" in Rename Tracking).

**Comment by lgolding** [comment]
Hi David,

I manually edited the type name to var.

This bug report is a false positive. I did not realize that “var” is a legal type name<https://msdn.microsoft.com/en-us/library/bb384061(v=vs.140).aspx>: “If a type named var is in scope, then the var keyword will resolve to that type name and will not be treated as part of an implicitly typed local variable declaration.”

That said, I would still vote for #2 (“special case var”) because I think it would be extremely that somebody who makes that particular edit really intended to rename their type to “var”, so almost always the user would see a lightbulb that does not help them.

Thanks,
Larry

**Comment by Pilchie** [comment]
I'm also in favor of just special casing `var` (and `dynamic`).

**Comment by lgolding** [comment]
Thanks David!

Sent from my Windows Phone
________________________________

**Comment by dpoeschl** [comment]
@lgolding No problem, thanks for reporting it! Can you take a look and verify that it works as expected in this case now and add the Verified label if so? I can find someone else to take a look if needed -- just assign the issue back to me if that's the case.

**Comment by dpoeschl** [comment]
Actually, I can't assign it to you for some reason, @lgolding. Do you know why? /cc: @srivatsn

**Comment by lgolding** [comment]
@dpoescl Taking you up on your offer to find someone else to verify this, thanks.

**Comment by lgolding** [comment]
@dpoeschl  Taking you up on your offer to find someone else to verify this, thanks.

**Comment by dpoeschl** [comment]
Simple enough bug, verified myself.
