### ISSUE TITLE
Overload resolution for method groups and Action/Func<Task> overloads

### ISSUE THREAD

**Issue by gkonterman** [dotnet/roslyn#26077]
**Version Used**: 
Latest

**Steps to Reproduce**:

```C#
    void LocalFunction(Action action) // this doesn't work
    {
        var capture = "Captured";
        void closure()
        {
            var local = capture;
            
            action();
        }
        
        Task.Run(closure); // error CS0121: The call is ambiguous between the following methods or properties: 'Task.Run(Action)' and 'Task.Run(Func<Task>)'
    }
    
    void ActionDelegate(Action action) // this works
    {
        var capture = "Captured";
        Action closure = () =>
        {
            var local = capture;
            
            action();
        };
        
        Task.Run(closure);
    } 
```

See:
https://sharplab.io/#v2:CYLg1APgAgDABFAjAbgLAChYMQVjZgZgQCY4BhODAbwwEgM5GEAWOAGQHsBjAQwBsoOAC4BLDgDsAFElI8uoiQEoGTGuiYa4ANx4AnOLwAOQgK66ApnAC8cAERkexs+eC38mplFZc+HAM7OksrqHnBqoZo6+r68fNYGjqYW7hFMKqlwcgpSiikeAL7pmkUaAPSlUABsAHQASiZSPv7OuXDlcA1cHAC23ebiQnBCABYifkWFIYxFXtjEACLmfOYA5jxC5tKIsvJi4sEa4aFRCU4W8faJzq55mjIGvgHnNkHWAHwlqp8eJzH88UYkuZbhFvposnsgiCmPlodMpncavVGo8Wrd8pQERh8kA

**Expected Behavior**:
I would expect that the two examples are identical and both should compile

**Actual Behavior**:
  `error CS0121: The call is ambiguous between the following methods or properties: 'Task.Run(Action)' and 'Task.Run(Func<Task>)' `

What I am not getting is that the compiler says that is has to choose between `Task.Run(Action)` and `Task.Run(Func<Task>)` but my closure clearly has the same signature as an Action right? (no param, no return)

Edit: the fun thing is that Visual Studio (analyzer + fix) hints for using a local function, which results in a compiler error @kuhlenh

**Comment by CyrusNajmabadi** [comment]
tagging @agocke .  IT does seem weird to have ambiguity, given that one of the overloads expect ``Func<Task>```, and i don't see how ```void closure()``` would ever be considered for that...

**Comment by gkonterman** [comment]
@CyrusNajmabadi  Yes, Im not getting the ambiguity part of the error message

**Comment by agocke** [comment]
Doesn't look like this has anything to do with local functions:

```C#
using System.Threading.Tasks;
public class C 
{
    public void M() 
    {
        Task.Run(M2);
    }
    
    void M2()
    {

    }
}
```

Output: `error CS0121: The call is ambiguous between the following methods or properties: 'Task.Run(Action)' and 'Task.Run(Func<Task>)'`

Plain old overload resolution.

**Comment by agocke** [comment]
cc @gafter

**Comment by gkonterman** [comment]
@agocke Thanks, so is this considered as a bug or more an design (known) issue?

**Comment by agocke** [comment]
This appears to be a bug, since I don't think there's a conversion from `void M()` to `Func<Task>` but maybe I'm missing something in the spec. @gafter, what do you think?

**Comment by alrz** [comment]
Doesn't repro on master. worth to add a test maybe

**Comment by agocke** [comment]
It looks like this was part of the "bestest betterness" feature implemented for C# 7.3 (which is why it does not repro in master).

See https://github.com/dotnet/csharplang/blob/master/proposals/csharp-7.3/improved-overload-candidates.md for the specification, specifically number (3), which addresses this scenario.

**Comment by veler** [comment]
Hi,

I'm posting my problem here because I think it's related but I would like to double check.
I have a similar issue than described above, but in my case, it builds correctly. The issue I get is at runtime.

**Version used** 
2.7.0

**Step to reproduce**

    internal static void Main()
    {
        // MyVoid is a void. Implictly, this lambda should be an Action.
        // But with Microsoft.CodeAnalysis.CSharp 2.7.0, it is considered as a Func at runtime.
        Run(() => MyVoid());
    }    
    
    internal static void MyVoid()
    {
    }
	
    internal static dynamic Run(System.Action action)
    {
        action(); // It doesn't go here, while in VS with .Net 4.7.1 it goes here.
        return null;
    } 
    
    internal static dynamic Run(System.Func<dynamic> func)
    {
        return func(); // Here I get "Cannot implicitly convert type 'void' to 'object'" at RUNTIME.
    } 

**See** [https://sharplab.io/#v2:CYLg1APgAgDABFAjAbgLAChYMQVjZgZgQCY4BhODAbwzjrgEsA7AFwFMAnJgQwBtsAbAgAs2ABwAKAJS16NdPUVwA9MrgBZAJ4A1APYNgjAM5xuIgHRwAkgFsADrwYBjFr00AaOCwAWDE724bACNgMyNvXQBXXkMgtlMmbGJzWSUVNQAhSJY4AHcGHw1nDl0jXQAzFnMyXWA2AEEeNyM/aoBlb24OOzhkgHZzGE8C4zgnXSYWuo42Q24TMygcUxyOSNYGGzYUhTS4ACV1iWk4AF4APg0dfWBpKXxFAF9FVMpdumZ2Lj5BESu9AzSV7yJ4YACQr0+nCav2Amh4NmcByOSHMSFI3BcDAmMnecBBe0xLGxTGkyHS1hywF0bCMTAA5DkAOa6ODeThsTy5Xy8eLMODaNp5AreODmABybBywnMA0QjGZNJM7JmOz2CD6cCY0V4D3oz1ekNY0J+SCEcIRSMOpNRSwAPBbAs5LuV1k5cYoCWkoJrXUwnGSKQAJDnWOBMqVwABEZG4TCYuhymwczgKbjGEwAbpwcixNHZ4vSoMJ6V5WfTdEEAFZsFz0qMrA4AVXFABUrOoAKJq/VvF7oR5AA=](url)

**Expected behavior**
1. It should build.
2. At runtime, the lambda should be considered as an Action and it should go in the FIRST "Run" method.

**Actual result**
1. It builds fine (at least there is no error).
2. At runtime, the lambda is considered as a Func<object> and it goes in the SECOND "Run" Method.
3. On the line "return func()", an Exception is throw with the message "Cannot implicitly convert type 'void' to 'object'".

Please note that I can't reproduce the same result with a Console project in VS.
Does this issue has been fixed with the changes you did with the problem of @gkonterman or is it another problem to fix ?

Thanks

**Comment by las-nsc** [comment]
Sorry to resurrect an old issue, but why was nothing done about this? 

I've just encountered this because one project in our solution was compiling with 7.3 and another with 8.0, and the newer project build failed because it's missing this improved overload candidate resolution, which was confusing until I found this issue. 

I ended up forcing the project back to using 7.3, but we will want to upgrade everything to .Net 5 soon, and this will break.
