### ISSUE TITLE
No CS0618 warning when using an extension method on a class marked with Obsolete attribute

### ISSUE THREAD

**Issue by eroller** [dotnet/roslyn#26083]
**15.5.2**: 

**Steps to Reproduce**:

Compile this:

```cs
    [Obsolete("Don't use this")]
    public static class MyExtensions
    {
        public static void MyExtension(this string dir)
        {
        }
    }

    public static class UseMyExtensions
    {
        public static void UseMyExtension()
        {
            string myString = null;
            myString.MyExtension();
        }
    }
```

**Expected Behavior**:
CS0618 Warning: MyExtensions.MyExtension(string) is obsolete 

**Actual Behavior**:
No warning. 

**Notes**:
Placing an Obsolete attribute on `MyExtension` method produces the expected behavior. Also, invoking the `MyExtension` as a static method directly (i.e. `MyExtensions.MyExtension(myString)`) produces the expected behavior.

**Comment by eroller** [comment]
Fair enough, perhaps just unexpected/undesirable behavior. I do see the behavior is consistent with non-static classes marked as Obsolete. If the instance methods are not marked obsolete only the constructor which refers to the class name will generate the warning. 

I do think it would be useful (eliminate some copy/pasting) if the class-level Obsolete attribute propagated to all fields/methods etc. of the class. From the documentation 

>Marking an element as obsolete informs users that the element will be removed in future versions of the product.

Since there is no way to remove a class without also removing all fields/methods etc. inside that class, this propagation behavior would make sense.

Documentation for reference: 
https://docs.microsoft.com/en-us/dotnet/api/system.obsoleteattribute?view=netstandard-2.0

**Comment by CodeAngry** [comment]
This is the laziest close that has ever existed. There's no by design here. Anyone sitting 5 minutes and thinking about this would understand that this is BAD design.

The Obsolete on a static class should trickle down to all Extension Methods and Static Methods of said class. Imagine having a lot of Extension Methods and not being able to Obsolete them all (via the containing static class) so you can diligently go and fix each of them, aided by the compiler.

**Comment by CyrusNajmabadi** [comment]
> This is the laziest close that has ever existed. There's no by design here. Anyone sitting 5 minutes and thinking about this would understand that this is BAD design.

Seems fine to me.  There's a trivial workaround as well. 

> 
> The Obsolete on a static class should trickle down to all Extension Methods and Static Methods of said class. 

Feel free to propose such a language suggestion. We could consider it.  But this issue is closed as this is not a bug in Roslyn. 

Language changes go at dotnet/roslyn

> Imagine having a lot of Extension Methods and not being able to Obsolete them all (via the containing static class) so you can diligently go and fix each of them, aided by the compiler.

Again. Seems fine.

Regardless, this is Roslyn, the repo for the compiler. The compiler just implements the lang spec. 

If you want the lang spec changed, make a discussion at dotnet/csharplang.  It may get picked up.
