### ISSUE TITLE
Provide an API to notify the language service of pending code generation work 

### ISSUE THREAD

**Issue by rynowak** [dotnet/roslyn#26125]
**This issue is part of a larger plan to enable the Find-All-References and Refactoring for the .NET Core Razor editor in Visual Studio.** 

You can find the tracking project for the entire feature here:  https://github.com/aspnet/Razor/projects/13
You can find more context about what's required here: https://gist.github.com/rynowak/ac48949e76e08ce7fdc533ada17c8d16#roslyn

----- 

As part of the larger feature set for enabling more IDE features for Razor, there will be times when we know that Razor's generated C# code is out of date and is in the process of updating.

This issue tracks the work on the Roslyn IDE to define a new API that Razor can implement or call to notify the language service that it has pending work. Roslyn will be be responsible for integrating this new concern into appropriate features.

This issue is not a design doc for the API, we still need to drill into that once this work is committed.

/cc @jinujoseph @jasonmalinowski

**Comment by Joe4evr** [comment]
Just a spitball, but would it be convenient to have this proposed API also be used as part of the Legendary general-purpose Source Generator feature? (dotnet/csharplang#107, [feature branch](https://github.com/dotnet/roslyn/tree/features/source-generators))

**Comment by CyrusNajmabadi** [comment]
Note: i don't think features should need to know about this.  Instead, features already work by getting access to the solution or objects of of hte solution.  So, the way i would like to see that is if there is pending work, these features simply asynchronously block on the acquisition of those resources.  That most closely indicates what's actually happening, namely that the solution is not actually available because razor is still doing work.

**Comment by rynowak** [comment]
@CyrusNajmabadi - @jasonmalinowski and I discussed and approach like this a while back. As I understand it,  the combination of Razor changing *the generated C# source code* in response to changes in *other assemblies/files* would cause perf problems with that approach.

I'll explain in a bit more detail what I proposed, and maybe you will have some bright ideas that we didn't see 👍 

------------

The main idea was that we would implement a *Language* a long with a corresponding and `ISyntaxTreeFactoryService` and `ICompilationFactoryService`. These could be wrappers around the C# implementations, except the `ISyntaxTreeFactoryService` would run the Razor code generator and then hand off the generated source code to the underlying implementation. We would create a project in the workspace and fill it up with the `.cshtml` files.


This seemed to me like a pretty natural fit when I thought about it at first.  Then come the problems. 

There's not a 1:1 mapping between input files and output files. Razor has `_ViewImports` files, which are like includes (you can globally include a `using MyNamespace`) for instance. Changes in a `_ViewImports` will change the generated code of all of the files that are within it's directory tree. 

We also generate different C# code depending on what is in your C# code. You can write classes (tag helpers) in your C# code in your project that metaprogram the HTML and change the meaning of the code you wrote *and* the code we generate. To figure out what code we need to generate we create a compilation and inspect the symbols of a project's dependencies. So a change to a .NET type in the solution could cause us to reparse and regenerate *all* of the generated code. The cost of us no-op'ing in this case could be significant.

These two things break the model where you only need to get syntax trees for the documents that have changes, or that you don't need to update syntax trees when a referenced project changes. But, these things would be necessary every time the Razor project needs to produce a compilation.


The conclusion from @jasonmalinowski last time we talked about this was that our feature set is very similar to source generators in a few key ways.  The concern coming from him was that we would be put in the perf firing fine for a number of solution-wide events, since atomically producing a solution would require us to do a lot of work in some cases.

It was I that proposed the model described here, because the pull model is much simpler to reason about, but I did so with a naive understanding of some of the details work (and maybe I still have a naive understanding).

The other approach, where we generate code in the background means that producing a set of compilations from a solution is not always atomic, but it allows a little more fine-grained control over when the IDE chooses to wait for Razor. 

-------

Additionally, the code generation in Razor is extensible. MVC and Blazor rely heavily on extending and customizing the code generation. I think this is a smaller concern. We do care about making the perf good of the code generators that we ship, but that hasn't been relevant for us at the level of *impacting all IDE perf*.

---- 

Is this what you were thinking about? Has anything like this been tried before?

**Comment by CyrusNajmabadi** [comment]
> The main idea was that we would implement a Language a long with a corresponding and ISyntaxTreeFactoryService and ICompilationFactoryService. These could be wrappers around the C# implementations, except the ISyntaxTreeFactoryService would run the Razor code generator and then hand off the generated source code to the underlying implementation. We would create a project in the workspace and fill it up with the .cshtml files.

I like this idea.  :)

> This seemed to me like a pretty natural fit when I thought about it at first. Then come the problems.

> There's not a 1:1 mapping between input files and output files. Razor has _ViewImports files, which are like includes (you can globally include a using MyNamespace) for instance. Changes in a _ViewImports will change the generated code of all of the files that are within it's directory tree.

This seems very similar to how roslyn already handles certain events.  For example, if you change a project 'define', then all files in that project may need reparsing because they could be affected.  Couldn't we just treat teh _viewImports files in the same manner?  If you edit them, then it invalidates all other files.  Perhaps you can be somewhat smarter depending on the sort of edit, but at least this model would fit in with how things work already for us today.

> We also generate different C# code depending on what is in your C# code. You can write classes (tag helpers) in your C# code in your project that metaprogram the HTML and change the meaning of the code you wrote and the code we generate. 

Can you expand on this sort of thing?  I'm not sure i get it.

> But, these things would be necessary every time the Razor project needs to produce a compilation.

I'm not understanding why that would be a problem.  Indeed, it sounds like that would be *necessary* for correctness.  If a change can have a dramatic reaching impact on the compilation... then you're going to have to pay htat cost at some point.  Fortunately, features like FindAllReferences are already async and can just spin a bit while that work is done and can analyze the correct results.

Do you have an idea on how such work could be avoided, given that (from waht i can tell from the above), it is necessary to how your system works?

**Comment by CyrusNajmabadi** [comment]
> Additionally, the code generation in Razor is extensible. MVC and Blazor rely heavily on extending and customizing the code generation. I think this is a smaller concern. We do care about making the perf good of the code generators that we ship, but that hasn't been relevant for us at the level of impacting all IDE perf.

So, i'm curious how we could expect this to work with good perf.   The title here is "Provide an API to notify the language service of pending code generation work", but i'm not sure how that actually addresses performance.  Say razor says: "i have pending code gen work", so the roslyn LS (or a feature) says "ok... i'll wait for that work, then i'll do my thing".  That can provide a correct experience, but we'll certainly be gated on the cost of that perf that has to happen.  If that perf involves "extending/customizing code generation" (and does that include arbitrary 3rd party code running?), then i'm not sure what ideas there are for making things fast.

**Comment by CyrusNajmabadi** [comment]
> The conclusion from @jasonmalinowski last time we talked about this was that our feature set is very similar to source generators in a few key ways. The concern coming from him was that we would be put in the perf firing fine for a number of solution-wide events, since atomically producing a solution would require us to do a lot of work in some cases.

Yes.  I see the concern.  Note that one of hte reasons SourceGenerators were tabled was because, without scoping things, perf is really hard since so many points in the system can now take arbitrarily long, and **so** many of our features are heavily dependent on the existing roslyn perf characteristics.  i.e. "getting a solution is free", "getting a compilation is relatively cheap", "getting a syntax tree after an edit is almost always cheap", etc. etc.  If these characteristics change, then that can be a substantive problem for features.

**Comment by CyrusNajmabadi** [comment]
> Is this what you were thinking about? Has anything like this been tried before?

Here's a potential idea.  Could we take everything complex/code-gen-y about the system you're describing, and end up making it just run asynchronously, with mutation operations happening once they finish?  i.e. as far as roslyn's workspace/solution model is concerned, we can always get things fast, but they may not always be accurate because you may not have updated it with the *accurate* results of all your code-gen/__viewImports/etc. work.  

This would have the impact that if a user made an edit, and then quickly did some operation, they might get inaccurate results.  This is because they'd be operating on the last applied snapshot, along with whatever edits had happened (but without all the downstream effects of those edits having been applied).  However, once your background work had been done, and had updated the roslyn workspace, then any operations would see that.

That would have the benefit of having fast features, while making that interim period observable by lower quality results.  Note that this is similar to how thigns already work today during async solution loading.  If you do a find-refs while the solution is asynchronously loading in the BG, you can get incomplete and inaccurate results.  However, once fully loaded, then things will be fine.   With the model i suggest, you would always be at risk of data being slightly wrong if you performed operations right after an edit.  We would just have to decide how bad an experience it would be to have periods of time when results might be stale.

We could also find ways to potentially surface that information in the IDE.  For example, i believe NavigateTo does (or used to) warn if you use it while async solution load is happening.  We could do something similar for features like FindRefs/NavTo/etc.  Have some small UI affordance that says something like "Results may not be completely accurate because razor is currently regenerating blah blah blah".  

What do you think?

**Comment by jasonmalinowski** [comment]
@CyrusNajmabadi That's what we were planning on. Things can be temporarily out of sync, and some higher-level API can be used for "wait until the current snapshot is up to date".

**Comment by CyrusNajmabadi** [comment]
@jasonmalinowski is that so certain features can take the perf hit and be accurate, but other features (like completion, etc.) can ensure they have a non-perf-impacted (but less accurate) path so they don't degrade the user experience wrt perf?

**Comment by rynowak** [comment]
I'm responding to your comments in order, and trying to keep up.

----------

re: ViewImports

> This seems very similar to how roslyn already handles certain events. For example, if you change a project 'define', then all files in that project may need reparsing because they could be affected. Couldn't we just treat teh _viewImports files in the same manner? 

Assuming I wanted to prototype this, where should I look? Is that [this](https://github.com/dotnet/roslyn/blob/175c1605927859bc3cfcd4a84b720b27c4054ba9/src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationTranslationAction.Actions.cs#L62)?

---------

re: Tag Helpers

> Can you expand on this sort of thing? I'm not sure i get it.

Example time! Taken from [here](https://github.com/aspnet/Blazor/blob/dev/test/Microsoft.AspNetCore.Blazor.Build.Test/ComponentRenderingRazorIntegrationTest.cs#L94) and tweaked to demonstrate my point.

```
// in MyComponent.cs
public class MyComponent : BlazorComponent
{
    public string StringProperty { get; set; }

    ... rendering code omitted
}

// in MyPage.cshtml
@addTagHelper *, TestAssembly
<MyComponent StringProperty="42" NotAComponentProperty="43" />
```

When we see the definition of `MyComponent`, that can replace the `<MyComponent>` tag at runtime with a call to the rendering code of the `MyComponent` class. There can be more complicated rules for how classes map to tags, this is an example of a simple one.

How this effects design time is that the text inside the quotes in `StringProperty="42"` maps to an assignment to the C# property defined by `MyComponent.StringProperty`. 

And since it's a `string` it specifically maps to the region delimited by pipes in a statement like:
```
builder.AddAttributte(1, "StringProperty", "|42|");
```
It's actually messier than that really because of our friend `#line`, but we can ignore that for now. 

So anything you type in there, you're in the context of a C# string. This is a parser feature for us. We need to know the set of tag helpers in scope for a project to be able to parse correctly.


If you changed the `StringProperty` property to an `int`, the code we'd generate would look like:
```
builder.AddAttributte(1, "StringProperty", 42);
```

You could also change the code to have something more better than just a literal:
```
<MyComponent StringProperty="MyClass.GetMyValue()" NotAComponentProperty="43" />
```
```
builder.AddAttributte(1, "StringProperty", |MyClass.GetMyValue()|);
```

If you remove this property, then the attribute is now just plain HTML, and it doesn't map to in the generated C# (for design time).

Hopefully this makes the picture clearer. Changes to the .NET types you reference can cause us to **parse** the document in a different way, and can cause us to generate different code.

[More examples of how these features are used in case you are curious](https://github.com/aspnet/samples/blob/master/samples/aspnetcore/blazor/FlightFinder/FlightFinder.Client/Main.cshtml)

Modern Razor has much more metaprogramming of HTML than it does templating.

-----

> I'm not understanding why that would be a problem. Indeed, it sounds like that would be necessary for correctness. If a change can have a dramatic reaching impact on the compilation... then you're going to have to pay htat cost at some point. Fortunately, features like FindAllReferences are already async and can just spin a bit while that work is done and can analyze the correct results.

> Do you have an idea on how such work could be avoided, given that (from waht i can tell from the above), it is necessary to how your system works?

Let's continue down the rabbit hole. We implement tag helpers by creating a compilation and walking it with a symbol visitor looking for public types that implement a certain interface or pattern. This feature comes from runtime people with roots designing IOC web frameworks, remember 😉 

Well, if we know what 'version' of tag helpers we had last time we generated the code, we only need to reparse/regenerate if the tag helpers or `ViewImports` or .`cshtml `source code have changed since last time.

So we can avoid the regeneration operation if either we:
- use a push model rather than pull model for tag helper changes
- or if we do look for tag helpers and find there were no changes

------

>  That can provide a correct experience, but we'll certainly be gated on the cost of that perf that has to happen. 

Yes, ultimately. I think as the owner of the LS, the Roslyn team wants to be in control of that experience *somehow*.

------

> If that perf involves "extending/customizing code generation" (and does that include arbitrary 3rd party code running?), then i'm not sure what ideas there are for making things fast.

3rd party extensibility is something we've had in the incubator for a very long time, but may never ship. Given a choice, we would choose feature parity with the C# editing experience for our primary scenarios 100% of the way.

------

> Here's a potential idea. Could we take everything complex/code-gen-y about the system you're describing, and end up making it just run asynchronously, with mutation operations happening once they finish? i.e. as far as roslyn's workspace/solution model is concerned, we can always get things fast, but they may not always be accurate because you may not have updated it with the accurate results of all your code-gen/__viewImports/etc. work.

This is basically what I'm planning to implement, but what you're describing is much more fundamentally integrated with Roslyn's abstractions. 

We would be notified when we **might need to do codegen** by a file watcher or some other notification, and then mark the relevant files dirty. Then we would update the code and push out those changes to the generated documents. While we know we're in a dirty state, we would flag the ourselves as having pending work. It's up to the LS if they want to wait for us to update or not.

It would save us a lot of time if we don't have to duplicate concepts like like the Workspace. It's really their call if they want us to be integrated at that level.

**Comment by rynowak** [comment]
> It would save us a lot of time if we don't have to duplicate concepts like like the Workspace. It's really their call if they want us to be integrated at that level.

That said, @jasonmalinowski I'm interested to know if this will help us solve the contained language hookup if the `.cshtml` is is in a project in the workspace already.

**Comment by jasonmalinowski** [comment]
The .cshtml/closed file interaction is 100% something you're going to have to sync up with for project system. I cannot stress that enough. Trying to get Roslyn in the middle is likely going to result in sadness.

**Comment by CyrusNajmabadi** [comment]
> likely going to result in sadness

![image](https://user-images.githubusercontent.com/4564579/38750669-874224de-3f0a-11e8-8230-a010b4f8313d.png)

**Comment by CyrusNajmabadi** [comment]
Closing out as this all refers to a razor architecture far from what we are actually tryin gto ship with LSP.
