### ISSUE TITLE
"Make field readonly" introduces error with deconstruction assignment

### ISSUE THREAD

**Issue by Neme12** [dotnet/roslyn#26264]
```c#
class C
{
    int i;
    int j;

    void M()
    {
        (i, j) = (1, 2);
    }
}
```
Add readonly modifier should *not* be offered here.

**Comment by CyrusNajmabadi** [comment]
@jcouv Currently, the IDE does analysis to determine if a variable is written to or not.  In general this has not been too complex.  However, tuples definitely make this a bit thorny.  After all, the above would be considered a write of 'i' and 'j', but if ```(i, j)``` were on the right of the assignment, and not hte left, there would be no issue.

based on your deep knowledge of the syntax of the language, can you let me know what i should look for in order to tell if this is an identifier used for assignment?  I can see there's an internal helper called GetContainingDeconstruction which looks like it does what i want it to do.  Can you weigh in and let me know if that logic is sufficient for all the sorts of odd deconstruction cases i might run into?

Thanks!

**Comment by jcouv** [comment]
@CyrusNajmabadi Yes, `GetContainingDeconstruction` is what I was going to suggest. Basically, if you are in a tuple that is on the left of an assignment, then you are being assigned to.

In terms of related/weird scenarios:
- Deconstruction-declarations and deconstruction-foreach aren't an issue, since they declare variables.
- The language doesn't allow mixing declarations and assignments. But it's still probably good to test a scenario like `(i, var y) = (1, 2);`
- Aside from that, there are nested deconstructions to worry about (`(i, (j, k)) == (1, (2, 3))`), but `GetContainingDeconstruction` handles that.

**Comment by CyrusNajmabadi** [comment]
Great, thanks much.  I'll do a bunch of tests in those areas (including the invalid ones).  Thanks!
