### ISSUE TITLE
Implement a better fix for when completion runs in the debugger before it runs in the normal editor

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#26394]
This tracks fixing https://github.com/dotnet/roslyn/pull/26361 the better way. We should ensure that the CompletionService used to trigger completion in the debugger is the same CompletionService used to show the description and perform the commit.

**Comment by CyrusNajmabadi** [comment]
Could a little more data be provided here?  It's not clear to me why the "right fix" is particularly hard or problematic to just do as hte initial fix.  Could that be clarified?  Thanks!

**Comment by CyrusNajmabadi** [comment]
Could this be answered?  I don't think ti's healthy to put in hacks, with followup issues (which, from my experience rarely get addressed, and then just get closed) without at least giving a good explanation as to why these decisions are being made.

@jinujoseph

**Comment by ivanbasov** [comment]
#26361 was fixed long ago and tons of other changes were applied to the area. since then. I could not get information from the issue description correlating with Roslyn design for async completion.

Switching between the normal editor and the debugger is on the Editor side now.
Resolving the issue.
Tagging @AmadeusW if he is interested to review Roslyn completion issues related with the debugger.
