### ISSUE TITLE
(Proposal) VB namespace local imports

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#264]
This is will bring VB.net into line with C#, that can specify imports that are in scope within the body of a namespace.
**C#**
```c#
using GlobalLibrary

namespace Foo
{
  using FooLibray;

  namespace Bar
  {
    using BarLibrary;
  }
}
```

**Proposed VB**
```vb
Imports GlobalLibrary

Namespace Foo
  Imports FooLibrary

  Namespace Bar
    Imports BarLibrary

  End Namespace
End Namespace
```

**Comment by AnthonyDGreen** [comment]
Hey Adam,

Is the primary motivation for this feature simple parity between VB and C#?

**Comment by paulomorgado** [comment]
For C#, the lookup rules favor using directives inside the namespace declaration over the ones outside.

Would this be motivation enough?

**Comment by AnthonyDGreen** [comment]
While that's how the feature works it's not necessarily motivation enough. For example, if C# never had this feature would it still be something worth adding to VB on its own right? If the answer is "no" then it's probably not worth putting in anyway. I don't see this feature used very heavily in C# because I don't often see multiple namespace declarations in a single file in C#. VB file templates, by default, don't even include a namespace declaration so I would expect the feature to be used even less in VB. It does add significant complexity to the IDE because the lookup rules become that much more complicated. In general, we don't just add features to the languages because we can. We add them to enable new scenarios (LINQ), or round out some existing experiences (implicit line continuation, NoPIA, binary literals, readonly auto props), or vastly improve productivity (Await), etc. I don't see how this fits into those buckets.

**-ADG**

**Comment by paulomorgado** [comment]
@AnthonyDGreen 

Probably not the best of usages, but I've done something like this in the past:

    using System.Windows.Forms;
    
    namespace PauloMorgado.SomeApplication
    {
        using PauloMorgado.Windows.Forms;

        ...
    }

I like to have my utility namespaces with the same structure as the extended ones (framework, some vendor, some library, etc.).

I remember reading (a long time ago) that there were performance benefeits for the compiler to have the namespace imports inside the namespace declaration. **StyleCop** favors that usage. But I never tested it myself.

**Comment by gafter** [comment]
If the only motivation is parity, then I don't see it worth putting any effort into making this change.

**Comment by AnthonyDGreen** [comment]
From chatting it up with the IDE team this feature in C# is a bit of a tooling nightmare. Because aliases introduced at the file level can impact the meaning of names in using directives inside the namespace blocks it significantly complicates refactorings. While we have done the work to overcome this in C# in general it's been a pain with very little benefit. Considering the cost here we're going to pass on this. We can revisit if some new _incredibly valuable_ scenario comes to light.
