### ISSUE TITLE
Some refactoring doesn't respect naming rules

### ISSUE THREAD

**Issue by zaytsev-victor** [dotnet/roslyn#26417]
**Version Used**: 
VS2017 15.7 Preivew 4.0

**Refactorings that doesn't respect naming rules**:

1. ```Encapsulate field```
2. ```Generate constructor```
3. ```Extract interface```
4. ```Generate constructor```
5. ```Generate type```
6. ```Initialize member from parameter```
7. ```Replace property with methods```
8. ```Convert auto property to full property```

Maybe I missed something.

I've already implement the fix. But I'm waiting https://github.com/dotnet/roslyn/pull/26165 and https://github.com/dotnet/roslyn/pull/26336 for some tests infrastructure and additional cases

**Comment by CyrusNajmabadi** [comment]
@zaytsev-victor I would be happy to start reviewing the fix now.  You can also just base your PR off of @Neme12 's PRs so you can pull in his test  infrastructure work.

**Comment by zaytsev-victor** [comment]
@CyrusNajmabadi I'll prepare PR tomorrow, thanks.

**Comment by Neme12** [comment]
Thanks. I'm just curious what test infrastructure from my PR do you find useful? I think I only added 1 test helper to test the order in a completion list. I would probably be causious about merging my PRs into your work right now because they might still change based on feedback, so I hope I don't make it worse for you if you had to handle merge conficts later because of that.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
