### ISSUE TITLE
RegisterCodeFixesAsync does not indicate which diagnostics are in the context

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#2643]
The [documentation for `CodeFixProvider.RegisterCodeFixesAsync`](https://github.com/dotnet/roslyn/blob/9e392f1cf230ae6af3d560150097a7c40681b197/src/Workspaces/Core/Portable/CodeFixes/CodeFixProvider.cs#L19-L22) does not indicate whether or not the `CodeFixContext.Diagnostics` property is allowed to contain diagnostics which are not present in the result of `FixableDiagnostics` for the same `CodeFixProvider`.

Unfortunately, if this precondition is not documented, we cannot use it as a [simplifying assumption in our code fixes](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/acb3ffb8be59448a8cbcf963c36195186e4676bc/StyleCop.Analyzers/StyleCop.Analyzers/OrderingRules/SA1205CodeFixProvider.cs#L36).

**Comment by mavasani** [comment]
@sharwell @shyamnamboodiripad @Srivatsn @heejaechang I think this one seems to be by design, unless we decide to change `CodeFixContext` constructor API parameters.

`CodeFixProvider.RegisterCodeFixesAsync` method invocation from the IDE code fixer service guarantees that none of the diagnostics in the `CodeFixContext` are outside the fixer's `FixableDiagnosticIds`. However, given that the constructor of `CodeFixContext` is public, and has no association to the underlying fixer (see here: http://source.roslyn.io/Microsoft.CodeAnalysis.Workspaces/R/571cdf75a90d323d.html), some other fixer host (such as a command line tool) is free to create a context with random diagnostics and invoke `RegisterCodeFixesAsync` API.

I think current implementation of Sam's fixer, which explicitly walks all the provided diagnostics in CodeFixContext and filters out non-fixable diagnostics is correct. The right fix on our side would be to change CodeFixContext constructor to take a `CodeFixProvider` argument, and throw/filter any diagnostic provided to the constructor that is not fixable by the given fixer. This is going to be a public API change though. Should we make this for 1.0?

**Comment by sharwell** [comment]
Not worth the breaking change at this point. Besides, you could just as easily make the mistake of using one `CodeFixProvider` in the constructor of `CodeFixContext`, and then passing the constructed instance to a different `CodeFixProvider`. As long as the requirement that a `CodeFixContext` not contain any diagnostics that aren't declared to be supported by a `CodeFixProvider` is documented for both the `CodeFixContext` constructor and the `CodeFixProvider.RegisterCodeFixesAsync` method, it should be fine.

**Comment by mavasani** [comment]
@sharwell The documentation would just a guideline rather then an enforcement on API consumers. @srivatsn Does that seem reasonable?

**Comment by sharwell** [comment]
@mavasani The "guideline" can be strong though:

> The behavior of `CodeFixProvider.RegisterCodeFixesAsync` is undefined if the `CodeFixContext` contains diagnostics which are not supported by the code fix provider, as indicated by `CodeFixProvider.FixableDiagnosticIds`.

**Comment by sharwell** [comment]
@mavasani Thinking about it some more, even if this is in place it probably wouldn't eliminate the check from our code. We'd probably just replace the filtering with throwing an `ArgumentException` if an unsupported diagnostic was included in the request.

**Comment by srivatsn** [comment]
Agreed. Documentation sounds sufficient.
