### ISSUE TITLE
Make InsertFinalNewLine public

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#26483]
Unlike the other options in this types InsertFinalNewLine  is internal, making it impossible for API consumers to check this option.

https://github.com/dotnet/roslyn/blob/8095c609a2a9fc2f00a51d7c1f43ea27b4a01d71/src/Workspaces/Core/Portable/Formatting/FormattingOptions.cs#L32

**Comment by CyrusNajmabadi** [comment]
This would need to go through an API proposal.  in general, the reason we don't just make things public is because it increases maintenance costs and locks down our ability to change things in teh future.  We can open things up, but we have a process that requests need to go through to make sure the appropriate people weigh in and the right API shape is determined and shipped.
