### ISSUE TITLE
Linq: Cast throws while explict cast into Select does not

### ISSUE THREAD

**Issue by leandromoh** [dotnet/roslyn#26515]
**Version Used**: 

- VS 2015 Entreprise Update 3
- .Net Framework 4.6.1

Why `Enumerable.Range(2, 10).Cast<double>().ToArray()` throws a `InvalidOperationException` while `Enumerable.Range(2, 10) .Select(x => (double) x).ToArray()` does not?

**Comment by CyrusNajmabadi** [comment]
Yes.  By design.  .Cast is written as: 

https://github.com/dotnet/corefx/blob/master/src/System.Linq/src/System/Linq/Cast.cs#L48-L55

This is an actual cast which at runtime will be trying to do a .net cast from 'int' to 'double' (something which is not legal).

However, ```.Select(x => (double) x)``` is not hte same.  in this case, this is not a .net cast, but is instead a *conversion*.  C# sees *at this location* that 'x' is an int, and it knows how to *convert* ints to doubles.

You can see the difference with the IL generated for both if that helps clear things up.

**Comment by CyrusNajmabadi** [comment]
```int -> double``` is ok from the perspective of *C#* which places a **conversion** in teh code to actually convert things.

```int -> double``` is *not* ok from teh perspective of the runtime which does not allow a **cast** to be used to go between those different representations.

```object``` doesn't really come into play at all here.  What is relevant is what sort of 'cast' this is.  even though they both look like ```(XXX)``` (which is unfortunate).  One is an actual cast, and one is a conversion.
