### ISSUE TITLE
IAssemblySymbol equality across languages

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#26542]
@AlekseyTs believes that an `IAssemblySymbol` created by one language for a given assembly will not satisfy `object.Equals(...)` with an `IAssemblySymbol` created by another language for the same assembly. This bug could result in an incorrect result from the extension method [`ISymbolExtensions.IsAccessibleWithin`](https://github.com/dotnet/roslyn/pull/26367).

**Comment by AlekseyTs** [comment]
This is by design. We explicitly put a stake in the ground that equality is not guaranteed to work across compilations, not just languages. I general one should assume that it works only when symbols are obtained through the same compilation.

**Comment by AlekseyTs** [comment]
This is true for all kinds of symbols, not just for assemblies

**Comment by CyrusNajmabadi** [comment]
I can understand and accept equality not working for all symbols across all languages.  However, we could certainly define equality to have a sensible meaning for *some* symbols, right?  In that case, we could simply doc this as part of the contract for these specific symbols, while not stating that this applied to anything else beyond htat.  

IAssemblySymbol certainly *intuitively* feels like it could have well defined equality semantics across languages.  Though i'm not an expert here and would certainly understand if reasons could be given why that would not be possible.

However, absent actual reasons, i feel like it would be fine and appropriate to take the extra step and define equality for these *specific* symbols.

**Comment by CyrusNajmabadi** [comment]
> That is why IDE layer has SymbolKey concept.

Note: SymbolKey exists for a couple of reasons.  The first is the lack of these defined semantics at the ISymbol layer.  If some semantics *were* defined, i would def be ok with removing code from SymbolKey that was no longer necessary.  The second is that SymbolKey also wants to work *across* different snapshots of the compiler, and wants a general 'matching' heuristic about what someone might intuit is the 'same' symbol across snapshot.

In that latter regard, i can see there being a bit of an oddity defining any equality semantics here.  Specifically, it has always been the case (i believe) that across two independent compilations (even from the same language), you would never get symbol equality.  This would be relaxed with @gafter's proposal, whereas you could now get two IAssembly symbols from two snapshots (from the same language) being equal.

This is actually a bit weird to me as i would assume that *equal* symbols were indistinguishable.  However, that's def not the case here.  For example, if you get the 'GlobalNamespace' of two 'Equals' IAssemblySymbols, they might not be Equal themselves.

Perhaps instead of .Equals, we have a separate question that can be asked that better reflects that hte IAssemblySymbols *represent* the 'same' assembly, without all the strict concepts that .Equals tends to convey.

**Comment by CyrusNajmabadi** [comment]
For example, this might be more of a CLR-assembly-equality question, with a name that reflects that fact.  This woudl then be clearer that this wasn't .Equals in the Roslyn symbol model sense, but more 'same-ness' in terms of how the runtime views things.

**Comment by AlekseyTs** [comment]
There is simply no reliable way for us to tell if two distinct assembly symbols represent the same actual assembly. We don't have any information for that, even identity cannot be used for that. All assembly symbols are distinct by design.

**Comment by CyrusNajmabadi** [comment]
>There is simply no reliable way for us to tell if two distinct assembly symbols represent the same actual assembly

This doesn't provide enough information for me to actually understand if this was hte case or not.  Imagine if one person said hte above, and another person said "there is enough information to reliably tell, and this is how to do it".  I'm at an impasse because neither position has actually clarified *why* their statement is correct.

> We don't have any information for that,

What information are we lacking?

> even identity cannot be used for that. 

Why is identity insufficient for this?

I think you could be 100% correct on this.  However, these statements of fact, without backing explanations leave a lot to be desired.  They do not help explain why they are correct, and i'm left simply taking you at your word.

--

Or, in other words, if someone came and asked me "why is aleksey correct?" i would find myself unable to actually explain. The best i could do would be to simply state "he seems quite sure".  The best thing here would be if you could help me (and anyone else interested in tihs space) understand the *why* of all this.   That would not only help avoid a lot of this back and forth, but could also likely be invaluable toward a constructive discussion about what an actually sufficient solution could look like.

Thanks!

**Comment by AlekseyTs** [comment]
> Why is identity insufficient for this?

Because I can have to distinct assemblies with the same identity

**Comment by gafter** [comment]
The accessibility API that this relates to is attempting to determine whether one symbol has access to another. The assumption when asking that question is that both symbols will be loaded together at runtime (if they are not loaded into the same program then of course there is no possibility of access). Since the compilers and the runtime will, by spec and design, never load more than one assembly with the same identity, we can use assembly identity as a proxy for the identity of the assembly to correctly answer access questions. I will therefore avoid using `IAssemblySymbol.Equals` and instead use `IAssemblySymbol.Identity.Equals`.
