### ISSUE TITLE
Consolidate recursive patterns to a single syntax node

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#26540]
Consider revising the syntax nodes for recursive patterns so that there is a single syntax node.

**Comment by jcouv** [comment]
@CyrusNajmabadi Here's what I'm proposing:

Currently, we have (1) a `DeconstructionPattern` with a optional type, positional pattern (parens and list of patterns), an optional property sub-pattern and a designation, and (2) a `PropertyPattern` with a optional type, a property sub-pattern and a designation, and  (3) a `DeclarationPattern` with a type and a designation. 

The proposal is to merge those three nodes into one that has an optional type, optional positional sub-pattern and optional property sub-pattern, and a designation.
This means that we need good conventions so that no such nodes is ever created with all three parts missing, or to handle such nodes if they occurred. We would no longer rely on the types of the syntax nodes to encode the contract.

**Comment by CyrusNajmabadi** [comment]
> This means that we need good conventions so that no such nodes is ever created with all three parts missing,

Agreed. 

What is the contract?  Any permutation of these three properties can be there (but a designation will always be there)?  Or will there be some rules about what can/can't happen?

**Comment by jcouv** [comment]
The contract is that you must have at least one of the parts (type, positional sub-pattern or property sub-pattern).
Designation is optional (only used if you want to capture what was matched).

**Comment by CyrusNajmabadi** [comment]
Ok.  While a bunch of work, actually enumerating this finite set of constructs would be *very* appreciated.  It will act as a good starting point for writing appropraite tests for all features that are impacted by patterns.  @jcouv, can you write them up?  It looks like it would only be 16 cases max (and it should be less since several forms are not allowed).  Thanks!

**Comment by jcouv** [comment]
Here's a representation of those rules. Designations are optional, except where specified.

| Type | Positional | Property | Notes |
| ----- | ----------- | --------- | ------- |
| | |  | Disallowed |
| Set | | | Designation required |
|  | Set | | Only allowed if more than 1 position |
| Set  | Set | | |
| | | Set | |
| Set | | Set | |
| | Set | Set |Only allowed if more than 1 position |
| Set | Set | Set | |

**Comment by CyrusNajmabadi** [comment]
Ok.  i was going to ask for a small example of each.  but i think it should be relatively clear.  So does that mean we'll allow single, or empty positional deconstruction if 'Type' is provided?

**Comment by jcouv** [comment]
Note: while doing this, it's probably good to make the casing on "SubPattern"/"Subpattern" uniform.

**Comment by jcouv** [comment]
Regarding @CyrusNajmabadi's question on 0-deconstruction, it seems to be [work without type](https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLRIMaOQSwG4SoAOsMECAdsgDQAmIA1AD4ACADAAQsCMA3ALAAoFgGYuAJg4BhDgG8hHRVzEsALBwCyACgCUchUsMB9DgF4OMABY5kHGx10DBhgL4HForuoAiEDAHsqGAQ4DBhdMwA+C0sEfwB3Dgo4ABsUp0NPNQ5fAKCQsK1/OBg7ClKADz1TaKs4xOS0pxcgA==).

@gafter Can you confirm this is expected?
My guess is that the 1-deconstruction case is ambiguous (with a parenthesized constant), whereas the 0-deconstruction case isn't.

**Comment by gafter** [comment]
Yes, this is expected.

**Comment by gafter** [comment]
Interesting that the compiler elides the invocation of `Deconstruct()` because it produces no output that the compiler needs to resolve the pattern-matching operation.

**Comment by gafter** [comment]
@jcouv We already have `DeclarationPatternSyntax` in the public API. I can't remove that, though I could make its properties optional and add new properties. But the name seems wrong for recursive patterns.

**Comment by jcouv** [comment]
Up to you. I'm fine if we consolidated `DeconstructionPatternSyntax` and `PropertyPatternSyntax` (into `RecursivePatternSyntax`?). That'd be much better already.

**Comment by gafter** [comment]
Fixed in https://github.com/dotnet/roslyn/pull/26784

**Comment by alrz** [comment]
>Here's a representation of those rules.

We can validate those rules with this switch:
```cs
switch (type, decon, prop, designation)
{
    case ({},	null,	null,	{}):
    case (null,	{},	null,	_):
    case ({},	{},	null,	_):
    case (null,	null,	{},	_):
    case ({},	null,	{},	_):
    case (null,	{},	{},	_):
    case ({},	{},	{},	_):
        break;
    default:
        throw new ArgumentException();
}
```
what a world.

**Comment by gafter** [comment]
Fixed in https://github.com/dotnet/roslyn/pull/26782
