### ISSUE TITLE
Microsoft.CodeAnalysis fails to load on `dotnet build` in a custom MSBuild task

### ISSUE THREAD

**Issue by pbalaga** [dotnet/roslyn#26569]
**Version Used**: 
[Microsoft.CodeAnalysis 2.8.0](https://www.nuget.org/packages/Microsoft.CodeAnalysis/)

`dotnet --info`:
```
.NET Command Line Tools (2.1.105)

Product Information:
 Version:            2.1.105
 Commit SHA-1 hash:  141cc8d976

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.105\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.7
  Build    : 2d61d0b043915bc948ebf98836fefe9ba942be11
```

**Steps to Reproduce**:

1. `git clone https://github.com/pbalaga/TaskWithCodeAnalysisFailure.git`
2. `cd TaskWithCodeAnalysisFailure\TaskConsumerProject`
3. `dotnet build`

Important points about how the above repro repository was built:
- TaskLibrary.csproj
  * define a custom MsBuild task: `SampleTask`
  * `<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>` in order to copy NuGet references to bin folder
- TaskConsumerProject.csproj
  * invoke SampleTask from TaskLibrary's bin folder:

```
<UsingTask TaskName="TaskLibrary.SampleTask" AssemblyFile="..\TaskLibrary\bin\Debug\netstandard2.0\TaskLibrary.dll" />
<Target Name="SampleTaskInvocation" BeforeTargets="Build">
    <SampleTask></SampleTask>
</Target>
```

**Expected Behavior**:
Project should build without errors.

**Actual Behavior**:
Build fails with the below error:
>TaskConsumerProject\TaskConsumerProject.csproj(11,5): error MSB4018: System.IO.FileLoadException: Could not load file or assembly 'Microsoft.CodeAnalysis, Version=2.8.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621)

**Remarks**:
- the same project builds without errors in Visual Studio 2017 and via MsBuild CLI
- commenting out [the line](https://github.com/pbalaga/TaskWithCodeAnalysisFailure/blob/1f440e36f2ca0648d3b7624fefb03a173ea947d0/TaskLibrary/Task.cs#L11) containing Microsoft.CodeAnalysis usage makes the problem disappear
- all projects are targeting netstandard2.0, no multi-targeting (so not the same issue as https://github.com/dotnet/cli/issues/7510)
- I managed to attach a debugger to `SampleTask` before it throws an exception, but there is no more detail presented than in console output
- two additional dependencies were added to `SampleTask`: a project dependency and a NuGet dependency on a package different than Microsoft.CodeAnalysis to rule out possibility that this is a more general `dotnet`'s problem with dependency resolution. Only using Microsoft.CodeAnalysis causes the build to fail
- I tried other versions of Microsoft.CodeAnalysis, specifically: `2.8.0-beta4` and `2.7.0`, both of which produce exactly the same results

**Comment by pbalaga** [comment]
Can I provide any more information about this problem? 

Let me know if whether this is related to Roslyn.

**Comment by jmarolf** [comment]
@pbalaga `dotnet build` also uses `Microsoft.CodeAnalysis` and it runs and loads assemblies before your build task.   When MSBuild attempts to load your task, your task asks for version `2.8` to be loaded but since `Microsoft.CodeAnalysis` is already loaded and it is an older version you get a `System.IO.FileLoadException:`

If you change `TaskLibrary.csproj` to reference `2.0.0` of `Microsoft.CodeAnalysis` like so:
```XML
<PackageReference Include="Microsoft.CodeAnalysis" Version="2.0.0" />
```

You task will load successfully

**Comment by pbalaga** [comment]
@jmarolf As of now, there is no such specific API, so using the newest version is possibly overzealous. My assumption was to support new C# `7.x` language features.

I don't have a clear vision how the version of `Microsoft.CodeAnalysis` used by `dotnet build` corresponds to allowed C# language versions. I can easily `dotnet build` a C# `7.2` project without issues when specifying `<LangVersion>7.2</LangVersion>` in the `.csproj`.

Do [these notes ](https://github.com/dotnet/roslyn/wiki/NuGet-packages)refer to language versions supported by  `Microsoft.CodeAnalysis` as well?

**Comment by jmarolf** [comment]
>As of now, there is no such specific API,

Ok thanks, just wanted to make sure I understood the problem.  As it stands now, this seems like an issue that [MSBuild](https://github.com/Microsoft/MSBuild) will need to solve for tasks that reference the same dependencies as MSBuild itself.  Do you have any objection to me moving this over to the MSBuild repo?

>Do these notes refer to language versions supported by Microsoft.CodeAnalysis as well?

The note on nuget packages are correct.  However, `Microsoft.CodeAnalysis.dll` is not the same as `Microsoft.CodeAnalysis` the nuget package.  The version of `Microsoft.CodeAnalysis.CSharp.dll` determines which version of C# you will be able to analyze.  You task probably just wants to use whatever version of `Microsoft.CodeAnalysis.CSharp` that comes with MSBuild since that is the version that the user is compiling their code with.  By targeting `2.0.0` you should just get whatever version of the compiler is present on the machine.

**Comment by jmarolf** [comment]
moved to https://github.com/Microsoft/msbuild/issues/3290
