### ISSUE TITLE
QuickInfo displays non-generic XML comments when highlighting completion item is a generic type

### ISSUE THREAD

**Issue by mazhou-msft** [dotnet/roslyn#26610]
**Version Used**: 
Visual Studio 2017 (27702.1.d15.8)

**Steps to Reproduce**:

1. Create a C# project
2. In the Main method, type `ImmutableArray`, or any identifier that has both non-generic and generic types (for example, `ValueTuple`)
3. Use the Down Arrow or mouse click to select the generic type in the IntelliSense items
4. A tooltip with type definition and XML comments (if any) will be displayed

**Expected Behavior**:
When non-generic type is highlighted, it should display XML comments from non-generic type declaration, when generic type is highlighted, it should display XML comments from generic type declaration.

**Actual Behavior**:
It displays non-generic type XML comments (the first match with the identifier,) for both non-generic and generic type definitions. See screenshot below.

![image](https://user-images.githubusercontent.com/12908526/39605873-7081f188-4ee7-11e8-8653-be47fca2a062.png)

**Comment by sharwell** [comment]
@mazhou-msft This is wonderful bug report. Great attention to detail! ❤️

**Comment by mikkelbu** [comment]
I've just looked into this, and I think that the problem is here, where we get two elements in `bestSymbols`
https://github.com/dotnet/roslyn/blob/990fbbbf1e29eca1b7e73aa755c446ce2858446d/src/Features/Core/Portable/Completion/Providers/AbstractRecommendationServiceBasedCompletionProvider.cs#L119-L120
and then when we extract the description we just take the first element
https://github.com/dotnet/roslyn/blob/990fbbbf1e29eca1b7e73aa755c446ce2858446d/src/Features/Core/Portable/Completion/CommonCompletionUtilities.cs#L103

I've a PR ready that also filters on the arity in `AbstractRecommendationServiceBasedCompletionProvider.cs`, but this only solve part of the problem. In the dropdown we currently show one entry for the non-generic variant and _one_ entry for the generic variants (even if there are more). So the question is what should be the description for the entry representing the generic variants? Currently with my change it shows the description for the variant with arity 1 (as the dropdown entry has arity 1) which seems wrong.

Current behaviour
![image](https://user-images.githubusercontent.com/1007631/39667410-f93f36a0-50b5-11e8-8f34-7e4c71e775c5.png)

If we take arity into account
![image](https://user-images.githubusercontent.com/1007631/39667396-c6f08cc6-50b5-11e8-91fd-174ac5e3ad17.png)

**Comment by sharwell** [comment]
@mikkelbu Thank you for the update with screenshots and everything!

@kuhlenh We'll need to review this design

**Comment by CyrusNajmabadi** [comment]
@mazhou-msft I dont' think there's been any movement on this issue.  but PRs certainly welcome!

**Comment by sharwell** [comment]
@mikkelbu During a design review yesterday, we concluding that the following behavior is preferable. Can you review this conclusion and let us know if it is reasonable in light of your proposal?

1. The completion help for non-generic types would not show any overloads, even if a generic type with the same name exists.
2. The completion help for generic types would show the following:

    1. The name of the *first* generic overload (when unambiguous, this would be the one with the lowest arity)
    2. When applicable, the number of *generic* overloads
    3. The summary text for the item shown in (i)


Here are some examples:

* class System.Windows.Documents.Span
* struct System.Span&lt;T&gt;  
  (summary for Span&lt;T&gt;)
* class System.Tuple ~~(+ 8 overloads)~~  
  Provides static overloads ...
* class System.Tuple<T1> (+ ~~8~~ 7 overloads)
  (Summary for Tuple&lt;T1&gt;)

**Comment by mazhou-msft** [comment]
Ping. Is anyone working on this?

**Comment by mazhou-msft** [comment]
Ping from the year 2020 -- anyone working on this? if not, I would like to pick this up.

**Comment by sharwell** [comment]
@mazhou-msft Please feel free to take this up! 👏

**Comment by mazhou-msft** [comment]
@sharwell Sure! any permission I need for contribution?

**Comment by sharwell** [comment]
@mazhou-msft You shouldn't need anything specific. Our main contributor guide is in [CONTRIBUTING.md](https://github.com/dotnet/roslyn/blob/master/CONTRIBUTING.md). After committing your changes to a branch locally, you can push those changes to your fork of dotnet/roslyn and then submit a pull request so we can review it for inclusion.

**Comment by mazhou-msft** [comment]
Nice!

**Comment by mazhou-msft** [comment]
@sharwell The PR is approved, when do I expect a merge?

**Comment by sharwell** [comment]
@CyrusNajmabadi can you review the PR compared to the above, and either merge if they match or get a second reviewer if we overlooked something that needs to be confirmed?
