### ISSUE TITLE
Inlining a ref variable

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#26668]
VS2017 suggests I inline the temporary variable &quot;value&quot; in the following code:

```csharp
ushort value = 0;
int stat = L43_SubFrmWordRd(ref value, sf, word, A717Chan, m_handle);
return (short)(stat == 0 ? value : -1);
```

By replacing it with this:

```csharp
ushort value = 0;
int stat = L43_SubFrmWordRd(ref value, sf, word, A717Chan, m_handle);
return (short)(stat == 0 ? 0 : -1);
```

VS appears to be completely oblivious to the fact that &quot;value&quot; is being passed by reference and its value could change.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/243165/inlining-a-ref-variable.html
VSTS ticketId: 609147_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Can you provide more information?  This is what i see when i try your code:

![image](https://user-images.githubusercontent.com/4564579/39684043-f868f28a-516d-11e8-87de-d00f69ee25d6.png)

As you can see VS is simply offering you the tool for you to use *if* you want it.  It also calls out that there's a conflict present with this code because you're inlining a variable that is written to across some codepaths.

--

A core issue we want to avoid is reasonable features not being present for reasons that aren't clear.  When features are just missing people often view that as meaning the product is broken and they don't understand what's going on.  So, instead, we try to err toward allowing you to still use these features (since they still might be useful to you), but we also let you know there can be a problem with what you're doing.

This is important because code is often *broken* when people want to perform quick code changes on it.  So if the features were to not be offered, the experience would quickly become useless.  Instead, the features are offered so that teh user can still depend on them, but with the caveat that running them may not always lead to correct code.

**Comment by v-rodudi** [comment]
I think that my repro is related to this. 

1. Add following code to any method:
`var name = "username";`
`name = name.ToUpper();`
`Console.WriteLine("Hello " + name);`
2. Put cursor to `var name`
3. Open Quick Actions
4. Look on suggestion for "Inline temporary variable"

**Actual:** 
`var name = "username";`
`name = "username".ToUpper();`
`Console.WriteLine("Hello " + "username");`
suggested. 

**Note:** the same behavior for VB

[Repro Gif](https://microsoft-my.sharepoint.com/:i:/p/v-rodudi/ES9lJ0tE8sJEgnHPf4ZRwmgBq7tHusjuOYyt2ygug73YPg?e=2vIoWN)

**Comment by CyrusNajmabadi** [comment]
I don't repro this.  The behavior we have seems to be correct/expected.
