### ISSUE TITLE
Use multiple workspace cache files

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#26664]
From discussion with @CyrusNajmabadi and @jmarolf: currently cache files are reset aggressively, which means that if you switch back and forth between two git branches, the cache is frequently erased.
I suspect there is a similar situation when switch between two solutions.
Not having a proper cache file means much longer load time, for those scenarios.

We should investigate archiving a cache file, rather than just resetting it, since there is a good chance it could be later re-used.
~~A possible design would be to move the cache file into a sub-folder named after the git branch. We may want to have a sub-sub-folder for the solution name as well.~~ (There is already a sub-folder per solution)

Then to avoid a glut of such folders, we'd probably want some cleanup mechanism to remove cache files that have not been updated in a while (maybe top N or time-based expiration).

**Comment by CyrusNajmabadi** [comment]
I was thinking that a fairly easy way to do this would be to just augment the workspace to internally have an option that keeps track of the current git branch (which would update as the user change branches).  Then just update the IPersistentStorageService so that when you call GetStorage it with a solution it returns the IPersistentStorage instance associated with that branch.  

This would make things happen fairly transparent to the services now that need the persistence caches.

> I suspect there is a similar situation when switch between two solutions.

I don't think this is the case.  Teh caches *should* already be isolated to individual solutions.  So opening a new solution should point to the cache for that solutoin and should not affect the other cache.

--

Note: this is all about our persistent caches.  I have absolutely no idea how our *in-memory* caches work and what sort of issues we face there when doing these sorts of operations.

**Comment by sharwell** [comment]
I'm concerned that branch switching isn't necessarily an appropriate time to clear the cache. I'm also concerned that all the changes that can occur during branch switching can also occur without a branch switch, so the invalidation strategy needs to make sense in both scenarios.

My instinct is to simply remove the force invalidation during branch switches and allow the cache to be preserved across branch switches. Most of the information in the cache is likely to remain correct, and events for changed files will allow selective invalidation to make sure the cache becomes up-to-date over time and/or as the data is requested.

**Comment by CyrusNajmabadi** [comment]
Can we get some clarity on which specific caches we're talking about?  It's a little vague to me currently.

> My instinct is to simply remove the force invalidation during branch switches and allow the cache to be preserved across branch switches. Most of the information in the cache is likely to remain correct, and events for changed files will allow selective invalidation to make sure the cache becomes up-to-date over time and/or as the data is requested.

Note: this should already be the case for persistence-service-caches.  They are doc-based, and will give you the same data as loc as the document's checksum is the same.  The checksum will of course stay the same if the file has not changed.

**Comment by CyrusNajmabadi** [comment]
Closing out as we haven't seen anything that actually indicates a problem here.  Practically, branch switches seem to keep most things the same, with large switches being rare.  Having those rare cases have some cost associated with them seems fine.
