### ISSUE TITLE
Unable to call C# 7.3 method with `unmanaged` type parameter

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#26751]
Porting this issue over from the VB language forum. ([issue](https://github.com/dotnet/vblang/issues/300))

> @Berrysoft 
> I wrote a C# function like this:
> 
> ```c#
> int SizeOf<T>() 
>     where T : unmanaged
> {
>     return sizeof(T);
> }
> ```
> But when I tried to call this function in a VB project, the compiler threw a BC30649 exception said:
> ` is an unsupported type`
> What should I do to call this function?

**Comment by AlekseyTs** [comment]
If I remember correctly this is expected. VB doesn't understand the ```unmanaged``` constraint and is unable to verify it at the call site.

**Comment by stakx** [comment]
> If I remember correctly this is expected. VB doesn't understand the unmanaged constraint and is unable to verify it at the call site.

CLS compliance comes to mind. I guess that these days, CLS compliance is no longer deemed as important as it was in ye olden times. (Perhaps because it is increasingly seen as a hindrance for rapid language innovation?)

`[assembly: CLSCompliant(true)]` used to be an easy way of getting warnings about code with potential cross-language issues. I'm pretty sure that CLS compliance rules haven't been updated much in the last few years (if ever)... perhaps they should be updated?

**Comment by OmarTawfik** [comment]
Yes. VB does not support `unmanaged` constraints (not yet, at least) because it does not know how to enforce these rules. This is by design, until such a feature is championed for VB.

**Comment by fitdev** [comment]
Supporting `unmanaged` constraint is _critical_ to be able to consume (in VB) the C# APIs that have unmanaged constraints on them! This is really important in migration scenarios and general VB-C# interop! We are now blocked in some cases, as we simply cannot call C# APIs from VB because of this. ANd yet, we cannot remove the `unmanaged` constraint from C# code either as it is needed there due to how the code is implemented.
