### ISSUE TITLE
Making incremental parsing cancellable to improve perf for large files.

### ISSUE THREAD

**Issue by OmarTawfik** [dotnet/roslyn#26766]
The IDE calls into APIs like `SyntaxTree.WithChanges()` to incrementally parse changes as the user is typing. These APIs should accent a `CancellationToken` so that ongoing parsing requests can be cancelled if the user typed something else.

**Comment by CyrusNajmabadi** [comment]
Incremental parsing is normally quite fast.  And it's usually a good idea to let previous changes actually produce the new tree that can be fed into the next incremental update. 

We played with this idea in typescript, but it didn't turn out to be beneficial.  Is there data that indicates differently here for c#?

> These APIs should accent a CancellationToken so that ongoing parsing requests can be cancelled if the user typed something else.

Note: there is no good way to do this in teh IDE today.  This is because as typign happens, many features will want the intermediate syntax tree.  So we can't 'cancel' getting that tree bcause all those features *will* want it because they definitely can and *do* work on 'out of date' trees.

For example, all our tagging features (classification, outlining, squiggles, etc.) all work on stale trees and then map those reuslts *forward* to the present document *until* the new results come in and replace them.  So we can't actually cancel in this case.

**Comment by CyrusNajmabadi** [comment]
here's a *really* good example of how things would break.  Take completoin.  The way completion works is to get 'kicked off' by something the user types (often 'dot', but also teh start of any word).  Completion then grabs the document snapshot at that point, and uses *that snapshot* for all work it does.  Completion starts by kicking off BG work that *will not cancel*.  i.e. the intent of completion is that as you type it *continues* to use the original tree that we kicked off the work again.  And, then, as the user types, waht they typed is then used to augment the results we get computing completion against that *original* tree.  

So, for example, if you have ```Console``` and you type ```.Write```, the ```.``` will kick of completion which will start aggressively computing things in the BG.  This is a *lot* of work it does.  It needs the tree, semantic model, and many other services that it computes with.  Then, as those new letters come in (i.e. ```W```, ```r```, etc.) it very *intentionally* does not cancel the work it is doing.  Instead, it really wants all that work to complete so that it can then say "ok, i need to filter what i computed down to things that match the pattern 'W', and now hte pattern 'Wr' and now the pattern 'Wri', etc. etc).  

There would be no opportunity to cancel, because the way our features are designed is to use these trees *even when they are old* to compute their results.  It's entirely woven into our design of grabbing snapshot of time (including the past) and then computing in the BG, and then using those results in a sensible way against whatever is relevant in the present.  

If "ongoing parsing requests can be cancelled if the user typed something else" then that breaks the design of all these features entirely, and goes against the actual design we had in Roslyn from the beginning of it being *desirable* to get snapshots and work on them in the BG even if the user ended up continuing to edit in the IDE.

**Comment by gafter** [comment]
It looks like this is something we aren't planning to do for the reasons discussed.  If this changes, please reopen.
