### ISSUE TITLE
Allow ternary operator with same-signature method groups

### ISSUE THREAD

**Issue by wiz0u** [dotnet/roslyn#26795]
This kind of code

    int result = list.Max(condition ? MethodA : MethodB);

result in the following error:
> Type of conditional expression cannot be determined because there is no implicit conversion between 'method group' and 'method group'

even though MethodA and MethodB both have the same correct signature `int Method(ListItem)`

It would be nice if future versions of C# would allow this kind of expression to be valid.

_(Sorry if it's a duplicate.. I searched if the suggestion was already raised but couldn't find it)_

**Comment by alrz** [comment]
This will work with https://github.com/dotnet/csharplang/issues/877.

The target type is a delegate that both method groups can be converted to, but a ternary only tries to convert one operator that has a type to another which is not the case here. (both operands are typeless).

I recently hit this in VB, but since VB casts are more verbose, it becomes a disaster when you shove DirectCasts there just to satisfy the compiler.

```vb
       Protected Overrides Function GetIfStatement(token As SyntaxToken) As SyntaxNode
            Return If(DirectCast(token.GetAncestor(Of SingleLineIfStatementSyntax), SyntaxNode),
                      DirectCast(token.GetAncestor(Of MultiLineIfBlockSyntax), SyntaxNode))
        End Function

        Protected Overrides Function GetAnalyzer(ifStatement As SyntaxNode) As IAnalyzer
            Return If(TypeOf ifStatement Is SingleLineIfStatementSyntax,
                      DirectCast(New SingleLineIfStatementAnalyzer, IAnalyzer),
                      DirectCast(New MultiLineIfStatementAnalyzer, IAnalyzer))
        End Function
```

**Comment by alrz** [comment]
Note: this has been brought up before: https://github.com/dotnet/csharplang/issues/1257

**Comment by CyrusNajmabadi** [comment]
This is legal now.  Closing out.
