### ISSUE TITLE
Fix VS IDE live analysis to replicate analyzer behavior with no explicit dependencies

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#2684]
Git commit #2502 changed VBCSCompiler.exe to reject builds where an analyzer dependency is not explicitly specified. The fallback for this is to use the standalone csc.exe/vbc.exe which runs in a separate process and uses `Assembly.LoadFrom` to load analyzer assemblies. So, if the analyzer dependency is actually packaged with the analyzer and present in the same folder, the fallback path successfully loads and executes the analyzer.

However, our `VisualStudioAnalyzer` type for executing analyzers in IDE live analysis fails for this scenario as it uses the `ShadowCopyAnalyzerAssemblyLoader` : http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices/Implementation/ProjectSystem/MetadataReferences/VisualStudioAnalyzerAssemblyLoaderService.cs,ee9d36e9927f4be7.

This causes a bad IDE experience where the live analysis generates analyzer exception diagnostics such as below:

```
Severity	Code	Description	Project	File	Line
Warning	CS8032	An instance of analyzer Analyzer5.Analyzer5Analyzer cannot be created from C:\Users\mavasani\Documents\Visual Studio 2015\Projects\Analyzer5\Analyzer5\Analyzer5\bin\Debug\Analyzer5.dll: Exception has been thrown by the target of an invocation..	ClassLibrary1		1
```

While the command line build succeeds, reporting actual analyzer diagnostics, and the error list ends up with both analyzer load failure diagnostics from live analysis + analyzer reported diagnostics from build:

![analyzer_ide_inconsistency](https://cloud.githubusercontent.com/assets/10605811/7597448/73bd6190-f8a8-11e4-94c5-29780698a118.png)

@tmeschter is aware about this issue, and plans to fix it soon. This issue tracks this work.

**Comment by tmeschter** [comment]
Note that the "fix" here will be for VS to be very explicit about what is missing. It will not be as lenient as csc.exe and vbc.exe are about loading the missing dependencies.

**Comment by mavasani** [comment]
@tmeschter We still need to make sure that the behavior is consistent to a reasonable extent. The current behavior is probably ok if it were for a very corner case scenario, but otherwise the current IDE behavior is going to be extremely confusing.

Can you expand on this _"Note that the "fix" here will be for VS to be very explicit about what is missing"_? How do you plan to fix this?

**Comment by mavasani** [comment]
Also note that the ruleset editor will not show any rules from this analyzer assembly if the missing dependency is required for creating descriptors.

**Comment by tmeschter** [comment]
@mavasani in order to explain the design decisions that have been made, it's probably worth reviewing the relevant requirements and a realistic scenario.

Principles:

1. If the build inputs are consistent, the build outputs must be consistent as well. "Outputs" include the generated .dll/.pdb/.xml/etc. files, of course, but also the overall success or failure, and the errors/warnings/messages generated by the compiler and the analyzers.
2. In order to uphold principle 1., we need to know all of the build inputs. This means that all analyzer assemblies and their dependencies must be specified with the `/analyzer` switch (with the exception of a small number of well-known assemblies that are supplied by the host).
3. We should still attempt to build when it is not possible for the user to supply all the analyzer dependencies, so long as we don't sacrifice consistency.

Scenario:

Suppose you have an analyzer assembly, MyAnalyzers.dll. It contains a number of analyzers, and a number of related code fixes. Some of those code fixes take a dependency on VS functionality in RandomVSLibrary.dll.

MyAnalyzers.dll is going to have a number of dependencies, including RandomVSLibrary.dll. The analyzer author can't redistribute it because it's a VS library, and so can't specify it as a dependency to the compiler. And anyway it's only needed for the code fix, not the analyzers. So now what?

* VS can be more forgiving than the compilers. It will see that MyAnalyzers.dll depends on RandomVSLibrary.dll but the latter isn't specified as an analyzer. If RandomVSLibrary.dll is already loaded in VS then all is well. If it is not, then a warning will be created letting the user know that their project is missing an analyzer dependency. VS will still try to run the analyzers, but it will not attempt to go looking for RandomVSLibrary.dll if it is not loaded. This helps uphold principle 2.
* VBCSCompiler.exe will see that RandomVSLibrary.dll was not specified as an analyzer dependency and will reject the compilation request, which will subsequently fall back to csc.exe/vbc.exe. This is because we do not want the output of the build to be dependent on whether or not some previous submission *just happened* to load RandomVSLibrary.dll. That would violate principle 1.
* csc.exe and vbc.exe do nothing to check that all analyzer dependencies have been specified. Since all the loaded assemblies will come from one build, either the set of assemblies specified with `/analyzer` plus the set loaded through standard CLR mechanisms will be sufficient for the analyzers to run, or they won't. In the latter case, of course, you will get an error. This helps uphold principle 3.

The result of all of this is that VS and the build are intentionally inconsistent in how they handle analyzer dependencies.

**Comment by mavasani** [comment]
@tmeschter Thanks for the detailed explanation. I agree with almost all of what you have said. However, I don't think VS and build inconsistency are acceptable for the following scenario:

1. I have multiple analyzer assemblies, say "Analyzer1.dll", "Analyzer2.dll", etc. and a shared assembly for resource strings for their descriptors, say "AnalyzerResourcesCore.dll". 

2. I add all the "AnalyzerXXX.dll" assemblies as analyzers for my project, but not the core resources dll. 

3. I build the project on command line and I see all analyzers run fine and generate correct analyzer diagnostics.

4. Now I open the project in VS and I see a whole bunch of analyzer exception diagnostics in the error list saying none of the analyzers could be instantiated. Live analysis is broken for these analyzers.

5. I build the project in IDE and I see all analyzers run fine and generate correct analyzer diagnostics in output window and these are also added to the error list along with existing exception diagnostics.

6. Intermittent behavior: If I infact had multiple projects in my solution, where one of them had "AnalyzerResourcesCore.dll" as an analyzer reference, so VS loaded it, all of sudden the analyzers for other projects that didn't have it as an analyzer also start working. 

Are you suggesting the scenario I described in steps 1 and 2 is not important enough for VS/build consistency?

**Comment by tmeschter** [comment]
@mavasani Regardless of anything else, VS needs to give you a warning like  "`Analyzer1` depends on `AnalyzerResourcesCore, Version=1.0.0,0, Culture=null, PublicKey=...` but it was not found in the list of analyzers; did you mean to include `C:\Foo\AnalyzerResourcesCore.dll`?". That explains the problem and guides the user to do the right thing.

What I'm suggesting is that we don't need to go further than that. As we expect most people will get analyzers from NuGet packages, this should be a rare problem. Also, attempting to find and load the unspecified dependency has other problems. It would require VS to have its own analyzer assembly loader, where right now it shares one with vbcscompiler.exe. We would have to guess about where to find the unspecified dependencies, and in some circumstances we would guess wrong and lead to a different set of much more subtle inconsistencies between the build and the IDE.

If the behavior I've proposed turns out to be insufficient for our users we can always revisit this decision.

**Comment by mavasani** [comment]
@tmeschter I agree with you. As long as we generate the diagnostic about missing dependency, the behavior difference is acceptable, especially given that the nuget package mode isn't affected by this.

A related question though: How will we deal with analyzers that have separate resource assemblies for localized resources, rather than embedded resources? I am presuming we cannot add all the resource dlls as analyzers, so we would need to shadow copy the resource assemblies over and try to load them from there? I remember your fix did indeed do that, but just wanted your confirmation before I go ahead testing this scenario.

Thanks!

**Comment by tmeschter** [comment]
@mavasani Resource assemblies do not need to be (and should not be) specified as analyzers. Instead we rely on the fact that the CLR only looks for resource assemblies in a small set of well-known locations relative to the primary assembly. In the situations where we shadow copy the primary assembly, we also look for and copy resources assemblies to the same relative locations. The CLR then finds and loads them from the shadow copy location as needed.

**Comment by mavasani** [comment]
Great thanks!

**Comment by tmeschter** [comment]
@mavasani Assigning back to you for verification.

**Comment by mavasani** [comment]
Verified fix.
