### ISSUE TITLE
IDE0007 when enum name is the same as variable name

### ISSUE THREAD

**Issue by MSeifert04** [dotnet/roslyn#26894]
**Version Used**: 

Not sure what version is meant but I'm using Visual Studio 15.7.1, I hope that helps.

**Steps to Reproduce**:

Config:

```
csharp_style_var_for_built_in_types = true:suggestion
csharp_style_var_when_type_is_apparent = true:suggestion
csharp_style_var_elsewhere = true:suggestion
```

Code:

```c#
enum A { B, C };

public void Fun()
{
    A A = A.B;
}
```

**Expected Behavior**:

No IDE0007 and no suggested "code fix".

**Actual Behavior**:

It suggests to replace `A` with `var` but that would lead to code that won't compile (Cannot use local variable before it's declared).

After code fix:

```c#
enum A { B, C };

public void Fun()
{
    var A = A.B;
}
```

**Comment by Neme12** [comment]
Fascinating.

**Comment by Neme12** [comment]
This is of course the Color Color scenario: https://github.com/dotnet/csharplang/blob/master/spec/expressions.md#identical-simple-names-and-type-names
The interpretation of `A.B` depends on what the type of the variable `A` is, but its type depends on the type of `A.B`.

Is the spec clear about this at all? I didn't find a clarification but maybe it's in some other part.

A slightly more interesting case would be:
```c#
enum A { B, C };

class C
{
    void Fun()
    {
        var A = GetA(A.B);
    }

    A GetA(object o) => default;
}
```
Here, the type of A can in theory be determined... but it's not known at the time of binding `A.B`. What is the expected behavior in this case?

**Comment by Neme12** [comment]
Forget all I said. The only relevant part is this:
> The initializer expression cannot refer to the declared variable itself

(https://github.com/dotnet/csharplang/blob/master/spec/statements.md#local-variable-declarations)

Since C# doesn't allow shadowing locals, the fix should be relaively easy. If the initializer mentions the name of the variable, we cannot offer var.

**Comment by wachulski** [comment]
I'm on it. Seems like `Microsoft.CodeAnalysis.CSharp.Utilities.CSharpUseImplicitTypeHelper.AssignmentSupportsStylePreference` doesn't catch it in:

```csharp
// variables declared using var cannot be used further in the same initialization expression.
if (initializer.DescendantNodesAndSelf()
        .Where(n => (n as IdentifierNameSyntax)?.Identifier.ValueText.Equals(identifier.ValueText) == true)
        .Any(n => semanticModel.GetSymbolInfo(n, cancellationToken).Symbol?.IsKind(SymbolKind.Local) == true))
{
    return false;
}
```

**Comment by wachulski** [comment]
I'm adding a few interesting scenarios:

```csharp
namespace N
{
    class C { public static C Instance; }
}

enum E { E1 }

class P
{
    // compiling error
    void M1() { var E = E.E1; }
    void M2() { var N = N.C.Instance; }

    // ok
    void M3() { var E = global::E.E1; }
    void M4() { var N = global::N.C.Instance; }
    void M5() { var C = N.C.Instance; }
}
```

Any suggestions, clues?
