### ISSUE TITLE
Incorrect "use var" suggestion in a foreach loop

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#26923]
**Version Used**: 2.9.0-beta4-62911-02. Commit Hash: db5486576d92f24a62cf86406753d259ff148d83

**Steps to Reproduce**:

1. Create a new console app.
1. Add the following to an .editorconfig:

```
[*.cs]

csharp_style_var_for_built_in_types = true:suggestion
csharp_style_var_when_type_is_apparent = true:suggestion
csharp_style_var_elsewhere = true:suggestion
```

2. Write this in the console app's Main method:
```
            foreach (string arg in args)
            {

            }
```

3.  Trigger light bulb.

**Expected Behavior**: nothing is wrong here.

**Actual Behavior**:

![image](https://user-images.githubusercontent.com/201340/40148893-3e5f28e0-5925-11e8-9fd0-29d71cf2a53a.png)

**Comment by Pilchie** [comment]
Just hit this in `project-system`

**Comment by sharwell** [comment]
We should definitely figure out how this was introduced.

**Comment by CyrusNajmabadi** [comment]
I made a bunch of changes to UseImplicit/ExplicitType to unify codepaths and to make it part of the simplifier pass.  I could have def unintentionally broken this as specialized 'foreach' code was absolutely impacted by the change.  Potentially relevant PRs here:

https://github.com/dotnet/roslyn/pull/25865
https://github.com/dotnet/roslyn/pull/26288

**Comment by CyrusNajmabadi** [comment]
This is highly likely to be the buggy code in question: 

https://github.com/dotnet/roslyn/blob/3fe9e5e3e2990fb5b3a44701ab7c444c72e063e6/src/Workspaces/CSharp/Portable/Utilities/CSharpUseImplicitTypeHelper.cs#L153-L160

Oddly enough, i didn't change this code (afaik).  But this likely means some other codepath was likely blocking things from making it here.

**Comment by CyrusNajmabadi** [comment]
I think i found it.  Looks like there was one more check for this in a different location:

https://github.com/dotnet/roslyn/pull/25865/files#diff-a419a7e5e40e4a95b7469c2a47229a56L2332

I didn't realize that that was important for actually blocking the code above from thinking the change should be allowed.

**Comment by jasonmalinowski** [comment]
@CyrusNajmabadi Are you sending a PR or should one of us take it from here?

**Comment by heejaechang** [comment]
so, from now on, should I block all this kind of subsystem changes regardless how beneficial it is if it is not directly fixing bug until it is proven to be not breaking anything at all?

**Comment by CyrusNajmabadi** [comment]
@jasonmalinowski I would not be able to get to this until tomorrow (and then i'm on a flight that day too).  So in this case i think it would be better if someone else took this given the severity.  My posts were intended to at least help narrow down both how this happened, and where the likely fix would need to go for it.

**Comment by CyrusNajmabadi** [comment]
> so, from now on, should I block all this kind of subsystem changes regardless how beneficial it is if it is not directly fixing bug until it is proven to be not breaking anything at all?

In general, the primary issue for me is hte subtlety of the impact on the user.  For example, things that affect muscle memory are pretty difficult issues because not only do you have to try to replicate hte original behavior, but you also not have *two* behaviors that could be considered 'correct' depending on the user and which version they became most accustomed to.

Such a situatoin does not exist here.  This is a not a muscle-memory issue.  This is a pure: this is a bug issue, with a very clear 'right' behavior and 'wrong' behavior.  Fixing the issue would be appropriate, without necessarily restricting ourselves too much toward improvements with clear benefits.  For example, in this case, the clear benefit was providing a simpler system so that our features would properly respect user settings.  IMO that was worth it.  Though it's a pity this issue crept in.

**Comment by heejaechang** [comment]
but one can argue I have muscle memory to hit ctrl+. and apply right away since I learned to do it for explicit<->var LB without actually looking at preview. in that sense, I broke the muscle memory.

**Comment by heejaechang** [comment]
I have same thing for how we changed BatchFixer to SyntaxEditor based fix all fixer. since that is quite significant change, and we didn't do extensive check whether that changed any behavior on fix all for that fixer.

**Comment by CyrusNajmabadi** [comment]
> Such a situatoin does not exist here. This is a not a muscle-memory issue. This is a pure: "this is a bug" issue, with a very clear 'right' behavior and 'wrong' behavior.

**Comment by CyrusNajmabadi** [comment]
As an example, i think it would be a good idea for people (including myself) to be extra vigilent about code that considers nodes in the context of their parents.  People writing hte PR as well as reviewers should likely focus some extra energy on asking questions like "are we sure we're operating on the right not?  are we sure this is hte only parent this could have?  what happens if tree changes come in the future that might violated some implicit assumptions this seems to have?  Are we sure we're going to eb finding the right node?  What about if the tree has this sort of error in it?" etc. etc.

In general we do try to do this with PRs, but it's clear things can slip through.  Extra attention may be valuable considering how tightly tied our features are to the tree, and how 'interesting' the tree can be in practice.

**Comment by CyrusNajmabadi** [comment]
If you'd like, i'd be happy to brainstorm more on this on gitter if that would be useful!

**Comment by sharwell** [comment]
Git bisect found the cause in commit 06393e4e4a9f23150aa4ec984b97f0af4e95bd94, which narrows it down to #25865.

**Comment by CyrusNajmabadi** [comment]
I felt bad that i introduced.  This.  Have made a fix.  Sorry about this guys.

**Comment by akashkc** [comment]
@CyrusNajmabadi  : What do you mean by  muscle-memory issue in this context? I've never heard about this term earlier.

**Comment by CyrusNajmabadi** [comment]
Muscle-memory isn't really a factor in this particular bug.  So it's a bit of a non-sequitor right here.

In general though, it refers to how people tend to remember behaviors in an unconscious manner which they they repeat without thinking.  In the context of Roslyn and the IDE, we talk about it a lot in terms of how people get used to typing.  For example, without thinking i'll often do something like ```List<int>ctrl-space,enter,list=new,tab``` knowing i'll end up with the right set of code despite not necessarily thinking about each and every step and what it is doing.  People get very used to these patterns and if you accidently make them do things that are subtly different, people will end up with different code than what all that 'muscle memory' led them to expect.

in general we try to avoid unnecessarily doing things that would impact the user in this way.

**Comment by akashkc** [comment]
Awesome. Now, it makes sense to me about muscle memory and it's beauty of VS encouraging muscle memory day by day. Thanks for great explanation.
