### ISSUE TITLE
Generate Method Fixer picks up wrong containing method

### ISSUE THREAD

**Issue by OmarTawfik** [dotnet/roslyn#26957]
It seems when called in a lambda, the fixer picks up the name of the containing method, instead of the actual non-existing method:

![image](https://user-images.githubusercontent.com/15987992/40210683-2afabba8-59fb-11e8-8118-2c39b658150a.png)

Code:

```csharp
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace ConsoleApp13
{
    class Program
    {
        static void Test(Action<string> action)
        {
        }

        static void Main(string[] args)
        {
            Test(arg =>
            {
                Console.WriteLine(arg.NotFound());
            });
        }
    }
}
```

**Comment by CyrusNajmabadi** [comment]
Note: this seems to be a confluence of issues.  First, we correctly run the gen method code and see that 'NotFound' is not defined.  We then look to see if we could generate such a method.  However, because 'arg' is of type 'string', and 'string' is from metadata, we say 'no'.  All that is correct.

However, the gen method code then bizarrely walks upwards and upwards looking for other potential methods it can generate.  it hits 'Test' and thinks that what it shoudl be working on.

The best i can tell all this is happening because the code is registered to work on some diagnostics, but then doesn't know when/where those diagnostics will appear.  So it just blindly walks upwards looking for *any* node it can fix.

--

There are a couple of ways i could see this being fixed.  First, and simplest, would be to limit the upward walk.  i.e. if we hit something we should obviously stop on (like a lambda), we just bail.  The second, and more complicated would be to not do the walk at all.  We should just take the syntax and the actual diagnostic and have explicit code that handles all the cases of interest.

However, the latter is also difficult because this code has been augmented over the years to handle more and more cases which would be better handled through other fixers.  For example, generating a conversion operator is handled through the same codepath.  So It's extremely difficult to have a common and consistent set of checks given all the different sorts of nodes that may flow through things.  So i will likely just go with the simpelr former approach and just feel unhappy that the code got to this state :-/
