### ISSUE TITLE
[ASK] F12 "Go to definition" to a nullable struct such as int? always go to the definition of the struct.

### ISSUE THREAD

**Issue by eriawan** [dotnet/roslyn#27005]
**Version Used**: 
VS 2017 15.6.5 and 15.7.1
**Steps to Reproduce**:

1. Write a code that has declaration of any nullable struct such as `int`:
`int? anynum = 5;`
2. Place the cursor on int?, right click and choose Go to definition
3. 

**Expected Behavior**:
The resulting definition should show Nullable<T>
**Actual Behavior**:
The resulting behavior shows definition of Int32

Is this behavior by design, or if it's not, what should be the correct behavior?

**Comment by CyrusNajmabadi** [comment]
This is the expected behavior.  Same as if you had:  ```List<int>``` and you goto-def on the ```int```.  If you want to go to Nullable, you can write it out as ```Nullable<int>``` and goto-def on the Nullable part.

The reasoning is that it's much more important to tell you about the type inside the nullable.  That's the shape that you most likely care about.  That it is nullable or not doesn't really affect "going to definition" on it as the definition is Nullable is well known and idiomatic and less valuable than the actual definition of the underlying type.

**Comment by eriawan** [comment]
@CyrusNajmabadi 

Make sense to me. 

> Same as if you had: List<int> and you goto-def on the int.

Hmm.. Currently it's not like that, even in VS 2017 since 15.1x until 15.7.x. 
If I try goto-def on List<int>, Visual Studio will show me the definition of List<T> instead of int. I also get the same behavior of goto-def on List<Int32>.

So is this intentional? I mean, based on your last comment, imho the behavior expected against the actual behavior isn't quite consistent between int? and List<int> then.

**Comment by jmarolf** [comment]
@eriawan it depends on where your cursor is

```C#
List<int> a = new List<int>();
//                 ▲
// Got-to-Def here shows List
```
![image](https://user-images.githubusercontent.com/9797472/40358890-b52534de-5d75-11e8-8c97-896d107a21df.png)


```C#
List<int> a = new List<int>();
//                      ▲
// Got-to-Def here shows int
```
![image](https://user-images.githubusercontent.com/9797472/40358923-d03b44a2-5d75-11e8-8fe6-33330319c2f0.png)

**Comment by eriawan** [comment]
@CyrusNajmabadi 
Thanks! ok, I understand now. I'm closing this issue.

**Comment by CyrusNajmabadi** [comment]
> Should cursor on the ? itself navigate to Nullable?

I thinkk that would be totally reasonable.  But, at the same time, not having support for that is fine with me as well :D
