### ISSUE TITLE
Go To All does not filter results to current document

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#27137]
Steps to reproduce:

1. Bring up "Go To All"
2. Select the option to search only for symbols in the current document

Expected: Just symbols in the current document are returned

Actual: All scopes are searched

Note:
- see video [here](https://www.dropbox.com/s/prp4bhfwybg45kt/2018-01-26_17-16-33.mp4?dl=0)

copied from [here](https://devdiv.visualstudio.com/DevDiv/NET%20Developer%20Experience%20Productivity/_workitems/edit/558453)

**Comment by karaziox** [comment]
I took a look at this issue since I've filed a pretty similar one on the developper community:
https://developercommunity.visualstudio.com/content/problem/215048/gotoall-doesnt-respect-current-document-with-c-pro.html

From the linked video this seems to be exactly the same issue: C++ symbols get pulled into the suggestions even when limiting search to current document. From what I saw after a bit of debugging, roslyn doesn't seem to be handling searching the C++ files, I feel like it's some other provider inside Visual Studio that misbehave when asked to search the current document with a document it doesn't support and fills the search with its own results.

If I'm correct, then the bug might not be in the right repo (I don't think the C++ part for VS is open sourced?)

**Comment by jinujoseph** [comment]
thanks guys , moved to C++ team [link](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/558453)
