### ISSUE TITLE
Code editor jumps to previous focused line after applying intellisense suggestions

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#27141]
Scrolling thru my code and applying some intellisense suggestions (like inline variable declarations) causes the code editor to jump to the last focused line in the editor. To avoid this annoying behaviour I first need to set focus to the line which I intent to improve before accually applying the suggestion.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/148377/code-editor-jumps-to-previous-focused-line-after-a.html
VSTS ticketId: 523367_
_These are the original issue comments:_

Cytheria Ji (MSFT) on 11/13/2017, 05:06 PM (192 days ago): <p>Thank you for your feedback! Could you please provide a repro video using your own software to us for further investigation?  We look forward to hearing from you!</p>

Stephan Smetsers on 11/14/2017, 09:07 AM (191 days ago): <p>as requested</p><p><a target='_blank' href="https://developercommunity.visualstudio.com/storage/temp/16856-feedback.mp4">feedback.mp4</a></p>

Darrell Tunnell on 3/5/2018, 07:12 AM (80 days ago): Experiencing same issue.
_These are the original issue solutions:_
(no solutions)

**Comment by sharwell** [comment]
Here is a set of repro steps derived from the video:

1. Write some code which has a suggestion available (light bulb)
2. Write some other code in a different method
3. Make sure the caret is placed in the code from step 2
4. *Using the mouse only*, scroll if necessary to find the code from step 1 and use the light bulb to apply a code fix

Actual behavior:

After applying the code fix, the code from step 2 still has the caret and the editor scrolls to this location.

Expected behavior:

The editor window should not scroll if the caret is not being repositioned.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
