### ISSUE TITLE
Consider having the compiler find .editorconfig files instead of build task

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#27172]
Right now, the proposal is that a build task will find editorconfig files and pass them off to the compiler. It could be more efficient to have the compiler do this itself.

The primary change here would be a change to the command line, since instead of passing files, there would be a boolean flag to indicate the compiler would look for editorconfig files.

**Comment by tmat** [comment]
The performance benefit would stem from not having to call Path.GetFullPath(Path.Combine(projectDir, filePath)) twice on each `@(Compile)` item. These paths are relative to the project directory and not normalized. The compiler task already normalizes them. If we implement finding editorconfig files as a separate task that precedes csc it would need to also normalize the paths in the same way the compiler does it. 

This is a more general problem though. The SourceLink package also needs to do the same normalization if `EmbedUntrackedSources` is true. So perhaps the work that's needed is actually in msbuild to provide cache for the full normalized paths.

Note that we do not have data that would prove that path normalization cost is significant. Just being careful since it can in some cases incur additional IO.

**Comment by tmat** [comment]
@sharwell @nguerrera FYI

**Comment by tmat** [comment]
@jasonmalinowski Pointed out that we need to include the .editorconfig files in the list of files that csc tasks depends on, otherwise incremental build would be broken. That means we need to have a separate task that does it. He has already implemented it somewhere (@jasonmalinowski please share a link) and done some perf measurements as well.

**Comment by agocke** [comment]
I've decided this is not a path I'll go down for these reasons and two more:

1. This is supposedly done for perf reasons, but we have no data to validate that this is a real perf problem. Moreover, we don't know that this is the only way it could be addressed.

2. This creates a fragility in csc that is not currently common. Right now, when you have a csc command line you generally know the inputs and dependencies of the compilation, so a log of the command line is an accurate view of the compilation inputs. This will no longer be true if the compiler searches for extra input files. We currently have this problem with related features like AssemblyKeyFileAttribute and it has been a pain before. Luckily, that is not an often used feature so the problem is not that bad. This feature will complicate things even worse.

Unless compelling information is brought that 1) this is problem and 2) this cannot be addressed in other ways (e.g., not hitting the file system to do basic path normalization until we actually read the file) I'm not going to reopen this issue.

**Comment by tmat** [comment]
Agreed. If we need to avoid normalizing paths multiple times we can move it to an external task that all tasks that need normalized paths depend on and the csc task can then skip normalization.

**Comment by jasonmalinowski** [comment]
This is what we had at the time: https://github.com/dotnet/roslyn/pull/18590
