### ISSUE TITLE
[Proposal] Operator |> to return this after method

### ISSUE THREAD

**Issue by KalitaAlexey** [dotnet/roslyn#2718]
There are proposals whose suggest to allow mark method as returning this.
I suggest operator |>, which write classes without thought about returning this.

```
public class MyClass
{
    public void SomeVoidFunc() {}
    public bool SomeBoolFunc() {}
    public CustomType SomeCustomTypeFunc() {}
    public void SomeVoidFuncWithArgs(int arg) {}
}
```

And using of operator |>

```
...
MyClass myClassInstance = ...;
myClassInstance.SomeVoidFunc() |> .SomeBoolFunc() |> SomeCustomTypeFunc() |> SomeVoidFuncWithArgs(5)
...
```

All real returned values must be suppressed.
This expression cannot be assigned to
It will be helpful when target object path is long

```
Configuration.SharedConfiguration.CustomSettings
```

**Comment by dharmatech** [comment]
Dart accomplished something similar with [method cascades](http://news.dartlang.org/2012/02/method-cascades-in-dart-posted-by-gilad.html). There's a [user voice](https://visualstudio.uservoice.com/forums/121579-visual-studio/suggestions/5182443-add-method-cascades-to-c) for adding method cascades to C#.

**Comment by KalitaAlexey** [comment]
Yeah. Method cascades are good.

**Comment by Przemyslaw-W** [comment]
It's a bit like With statement in VB, which I think is not planned for c#
at all

2015-05-14 5:12 GMT+02:00 Alexey <notifications@github.com>:

**Comment by bondsbw** [comment]
I prefer Dart's ```..``` syntax over ```|>```, which is used for a different purpose in F# (forward pipe).  I think ```|>``` would be more confusing for people using both languages.

Also I think this can have a problem with ambiguity.  How would the following be interpreted?
``` c#
A.B.C() |> D() |> E();
```
would it be the same as:
``` c#
A.B.C();
A.B.D();
A.B.E();
```
or the same as:
``` c#
A.B.C();
A.D();
A.E();
```

Dart's syntax fixes this I believe, because the operator "discards the result, and returns the original receiver instead" (quote taken from @dharmatech's link above).  So instead of 
``` c#
A.B.C() 
  ..D() 
  ..E();
```
you would write (notice the two dots before ```C()```):
``` c#
A.B
  ..C() 
  ..D() 
  ..E();
```
so that it is clear that all operations are performed on the result of the expression ```A.B```.

**Comment by gafter** [comment]
We are now taking language feature discussion on https://github.com/dotnet/csharplang for C# specific issues, https://github.com/dotnet/vblang for VB-specific features, and https://github.com/dotnet/csharplang for features that affect both languages.
