### ISSUE TITLE
Crash message not reported, only error code

### ISSUE THREAD

**Issue by yao-bin** [dotnet/roslyn#27248]
**Version Used**: 
dotnet --version  2.1.200
macOS  10.13.4

**Steps to Reproduce**:

1. dotnet restore
2. dotnet build

.csproj
    TargetFramework = netcoreapp1.1
    PreserveCompilationContext = true
    OutputType = Exe
    RuntimeFrameworkVersion = 1.1.0
    PackageTargetFallback = $(PackageTargetFallback);dotnet5.6;portable-net45+win8

**Expected Behavior**:
Build SUCCESS.

**Actual Behavior**:
Build FAILED.

/usr/local/share/dotnet/sdk/2.1.200/Roslyn/Microsoft.CSharp.Core.targets(52,5): error MSB6006: "csc.dll" exited with code 134. [/Users/xyz/Documents/Github/xyz/src/xyz/xyz.csproj]
    0 Warning(s)
    1 Error(s)

**Comment by yao-bin** [comment]
@jcouv  Thanks for your reply.   I found the stackoverflowexception in msbuild.binlog
![csc error](https://user-images.githubusercontent.com/13148142/40823752-2115dad2-65a4-11e8-8acb-28fa52d4d57b.png)

When repro, it said 
![csc error 2](https://user-images.githubusercontent.com/13148142/40823916-bc656c0a-65a4-11e8-8571-cdbb4a3d6be4.png)
though I set /out: in the tail of CommandLineArguments

Btw, the project can be compiled and run success on Windows 8.1.   The issue just happen on my MacOS.

**Comment by jcouv** [comment]
Thanks for the update.
I would love to see the stacktrace for the stack overflow. But I don't know how to capture a crash dump on MacOS.

@jaredpar Do you have an idea how to get more details for a crash on MacOS?

@yao-bin If you repro project is relatively small and if it is possible to share it, could you provide some instructions so that I try to repro?

I'm assuming you're using the same SDK and compiler on MacOS and Windows. 
Are you doing anything unusual in your code, such as extremely long expression (`x.Method().Method()... .Method()`), class with a great number of methods/properties/etc, very large file, ...?

**Comment by yao-bin** [comment]
@jcouv 
Thanks!
Actually you are right.  I reviewed the history and found the weird code.

It works for generating a database structure template, and has StringBuilder Obj.Method().Method()... .Method().
![csc error 3](https://user-images.githubusercontent.com/13148142/40834746-3c148e80-65c4-11e8-9f4e-8512ed505582.png)
It works find if the piece of code commented.

I think we have to update the piece of code.  But, anyhow, I can continue the work on my MacBook.

Thanks again!

**Comment by Neme12** [comment]
Side note: It's extremely puzzling to me that StringBuilder.Replace returns a StringBuilder since it mutates the original one. Does it always return the original one? (If so, what's the point in that? This API is terribly misleading.)

@yao-bin Can you rewrite these as separate statements as a workaround? ie.:
```c#
sb.Replace("a", "b");
sb.Replace("a", "b");
...
```

**Comment by svick** [comment]
@Neme12 

> Side note: It's extremely puzzling to me that StringBuilder.Replace returns a StringBuilder since it mutates the original one. Does it always return the original one? (If so, what's the point in that? This API is terribly misleading and makes it seem like the original SB would be unchanged.)

That's just how [fluent interface](https://en.wikipedia.org/wiki/Fluent_interface) works for mutable objects. It's done that way so that you can chain the method calls and don't have to repeatedly specify the object that you're modifying.

And yes, it is [documented](https://docs.microsoft.com/en-us/dotnet/api/system.text.stringbuilder.replace?view=netframework-4.7.2#System_Text_StringBuilder_Replace_System_String_System_String_) as returning "A reference to this instance".

**Comment by jaredpar** [comment]
> Do you have an idea how to get more details for a crash on MacOS?

No. The binary log is still the best way to get a sense of what the crash is.

**Comment by jcouv** [comment]
Seems like the core issue was identified (the stackoverflow is the result of a very deep expression chain), so we don't need to capture a crash dump.

I will move this issue over the CLI repo because the compiler error text should be reported, not just the error code.

**Comment by jcouv** [comment]
Issue moved to [dotnet/cli #9401](https://github.com/dotnet/cli/issues/9401) via [**ZenHub**](https://www.zenhub.com/)

**Comment by nguerrera** [comment]
Reopening. As the issue is that the Csc task is not logging to msbuild correctly. See comments below from moved issue.

@nguerrera commented 4 minutes ago

> Without looking deeper, my guess is that the Csc task isn't logging these crash details with a high enough message level to msbuild. I will dig in to be sure. I don't think there's anything the CLI could do here, we simply execute msbuild. Our default verbosity is minimal, but I don't think anything in the system should assume minimal is too low to show crash details.

@rainersigwald commented a minute ago
This is a bug in the Csc task, as I explained in Microsoft/msbuild#3054 (comment). I think it should be fixed in Roslyn.

**Comment by svick** [comment]
@jcouv Shouldn't the compiler avoid the stack overflow by using a trampoline? I believe it already does that in other cases.

**Comment by jcouv** [comment]
@svick Yes, and that is tracked in separate issue. 
That's why I'm focusing this issue on the reporting problem (if an overflow occurs, it should be clearly reported).

@nguerrera Thanks for the clarification.

**Comment by svick** [comment]
@jcouv 

> Yes, and that is tracked in separate issue.

Can you provide a link to that issue? I believe in such cases, linking to the related issue is important.

**Comment by nguerrera** [comment]
> That's why I'm focusing this issue on the reporting problem

@jcouv Consider changing the title of this issue. I could swear there was another one about fixing the logging, but I can't find it now. There are a bunch of "exited with code X" bugs and it may be buried in one of them.

**Comment by jcouv** [comment]
@nguerrera Updated the title.
Yes, there are a [number of issues](https://github.com/dotnet/roslyn/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+%22csc.dll%22+exited+with+code+) with details not being reported via CLI. 
I thought it was a problem on CLI side, since I've not encountered such problem in desktop build, and all reports related to CLI.

If I make a fix to the Csc task, as suggested by Rainer, how do I test it in CLI?

**Comment by yao-bin** [comment]
@Neme12 

Sorry for late.   It works fine using separate statements instead.
