### ISSUE TITLE
Single-element var patterns are not permitted

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#27385]
**Version Used**: `recursive-patterns`

**Steps to Reproduce**:

```cs
class C {
    extern public void Deconstruct(out int i);
    void M() {
        if (this is var (x)) { }
    }
}
```

**Expected Behavior**: Should call `Deconstruct(out int)`

**Actual Behavior**: Syntax error

**Comment by alrz** [comment]
Deconstruction of `var (x)` doesn't work either. So perhaps this is intentional?

**Comment by gafter** [comment]
This is not a compiler bug. It is by design. Admittedly the design probably isn't great. Added the following to #1054 (open LDM issues in pattern matching)

### var pattern for 0 and 1 elements

The var pattern currently requires 2 or more elements because it inherits the grammar for *variable_designation*. However, both 0-element and 1-element var patterns would make sense and are syntactically unambiguous.

``` c#
public class C {
    public void Deconstruct() => throw null;
    public void Deconstruct(out int i) => throw null;
    public void Deconstruct(out int i, out int j) => throw null;
    void M() {
        if (this is var ()) { }          // error
        if (this is var (x1)) { }        // error
        if (this is var (x2, y2)) { }    // ok
    }
}
```

I propose we relax the grammar to permit 0-element and 1-element var patterns.

We could do the same for deconstruction.
