### ISSUE TITLE
Editor Completion: Allow empty string or null descriptions of suggestion mode items

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#27419]
// TODO

**Version Used**: 

**Steps to Reproduce**:

1. 
2. 
3. 

**Expected Behavior**:

**Actual Behavior**:

**Comment by ivanbasov** [comment]
@AmadeusW , currently sending an empty description leads to a failure like

`at Microsoft.VisualStudio.Language.Intellisense.AsyncCompletion.Data.SuggestionItemOptions..ctor(String displayTextWhenEmpty, String toolTipText)\r\n at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.EditorImplementation.CompletionItemSource.<GetCompletionContextAsync>d__5.MoveNext() in C:\\git\\ivanbasov\\roslyn\\src\\EditorFeatures\\Core\\Implementation\\IntelliSense\\EditorCompletionImplementation\\CompletionItemSource.cs:line 69\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.<CallExtensionPointAsync>d__331.MoveNext()`

Please help with a solution or a workaround.

**Comment by AmadeusW** [comment]
The tool tip provides user with context on why the feature behaves different than normal. 
If the language service enters the builder mode, it should explain in one sentence what’s going on.

As an example, currently Roslyn tells the user that they're building a lambda.

**Comment by CyrusNajmabadi** [comment]
Note: teh builder text is mostly useless.  That's because, in practice, all you ever see is this:

![image](https://user-images.githubusercontent.com/4564579/43179062-a27ec11e-8f85-11e8-8d40-90178c24fa2d.png)

In other words, you need the builder because completion comes up on typing (and you don't want to interfere with typing a new name with a completion item).  However, the name you're typing ends up going in the builder.  So, effectively, the explanation text serves no purpose.  You would only see that text if you brought up completion manually:

![image](https://user-images.githubusercontent.com/4564579/43179088-c5610188-8f85-11e8-926b-b8f2969d0d05.png)

However, if you bring up the completion list explicitly, then you don't need the builder.

**Comment by AmadeusW** [comment]
@ivanbasov  The constructor for SuggestionItemOptions takes two parameters: display text and tooltip text.

Display text is what is visible when user hasn't typed anything - for example, `<lambda expression>`. It is OK when display text is empty, since (as @CyrusNajmabadi said) we don't want to interfere with user typing the name.

Tooltip text is the tooltip that explains each item. The tooltip explains the selected item. From the UX tenet, every item needs to have a tooltip. You should say something along lines of "here type your lambda expression" or "type the variable name".

**Comment by ivanbasov** [comment]
@AmadeusW Here is the scenario when we do not need the tooltip (for <Name>):
![image](https://user-images.githubusercontent.com/5455484/43349446-a9e1989c-91b4-11e8-8a85-eb815c2bc796.png)

**Comment by dpoeschl** [comment]
I'm fine with providing a string for this particular case and letting @AmadeusW take the API leniency request and figure out what they want there (for example, _we_ want tooltips in this case, but third parties don't _necessarily_ care to adhere to our strict internal guidelines).

**Comment by CyrusNajmabadi** [comment]
@dpoeschl Is this still relevant?

**Comment by CyrusNajmabadi** [comment]
This doesn't seem relevant.  The experience is working as expected.
