### ISSUE TITLE
Editor Completion Test Failures: Test*IncompleteParenthesizedDeconstruction* [Possible Race / Test Infra Problem] [Only Partially Fixed!]

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#27454]
**Version Used**: 

**Steps to Reproduce**:

1. 
2. 
3. 

**Expected Behavior**:

**Actual Behavior**:

**Comment by ivanbasov** [comment]
@AmadeusW , we have the following scenario that works properly in VS but fails as a unit test (TestParenthesizedDeconstructionDeclarationWithSymbol):

1. Code


```
class Variable
{
    public void Goo()
    {
       ($$) = (1, 2);
    }
}
```

2. state.SendTypeChars("vari")
3. Await state.AssertSelectedCompletionItem(displayText:="Variable", isHardSelected:=True)
4. state.SendTypeChars(" ")
5. Assert.Contains("(Variable ", state.GetLineTextFromCaretPosition(), StringComparison.Ordinal)
6. Await state.AssertNoCompletionSession()
7. state.SendTypeChars("x, vari")
8.  Await state.AssertSelectedCompletionItem(displayText:="Variable", isHardSelected:=True)

Please note that AssertSelectedCompletionItem awaits for WaitForAsynchronousOperationsAsync to complete.

**Expected behavior**
There is an active completion session on step 8.

**Actual behavior**
There is no active completion session on step 8.

However, if we replace step 7 with 
7. a.            state.SendTypeChars("x, ")
7.b.              Await state.AssertNoCompletionSession()
7.c                 state.SendTypeChars("vari")
Then, step 8 works properly. It seems that an extra call of WaitForAsynchronousOperationsAsync from AssertNoCompletionSession helps us to execute the test. If so, our approach for calling SendTypeChars and WaitForAsynchronousOperationsAsync seems to be wrong. Please advise.

**Comment by dpoeschl** [comment]
> we have the following scenario that works properly in VS but fails as a unit test
When typed at the speed of a human. There could be a product race here. Or something wrong with our SendTypeChars like Ivan mentions (though we use that infrastructure lots of places already), or something wrong with the way your synchronous blocking test-only (basically) method on the session is implemented and interacts with your async infrastructure.

**Comment by AmadeusW** [comment]
I'm trying to picture the state of the buffer and various completion during the test.
During 7, when you type `x, vari`, does the buffer contain `Variable $$ = (1, 2)`? 
Is the desired outcome to have typed `Variable x, vari$$ = (1, 2)`? with `Variable` being a selected item?
Is `,` supposed to commit the session applicable to `x`?

When you set a breakpoint in your implementation of IAsyncCompletionCommitManager, do you see it being probed after typing `,` in the first case, or only in 7a?

**Comment by AmadeusW** [comment]
This works fine on my machine. I'm typing faster than completion, such that this UI appears after couple seconds: 
![image](https://user-images.githubusercontent.com/1673956/43350926-63fb3c78-91c0-11e8-86b2-455d682a744d.png)
Initial state is as of step 6 (Variable committed, there is no current completion)

**Comment by dpoeschl** [comment]
Let's fix this as part of https://github.com/dotnet/roslyn/issues/27439
