### ISSUE TITLE
Make SymbolKey API public

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/roslyn#27527]
SymbolKey is a very useful API for creating an opaque identifier for a symbol that can be resolved back to an `ISymbol` in a `Compilation`. There a various scenarios in which this is needed:

1. Resolving symbols across `Compilation` modifications. This can be necessary for code actions that need to perform multiple edits where semantic information is needed. For example, a code action that adds a method to an `INamedTypeSymbol` and then retrieves the `IMethodSymbol` that it just added. By using a `SymbolKey`, the code action can resolve the `INamedTypeSymbol` in the `Compilation` after adding the method to retrieve the `IMethodSymbol`.
2. Resolving symbols across isolation boundaries. For example, when synchronizing features with the remote workspace in Visual Studio. Or, to handle the various 'provide'/'resolve' APIs in the [Language Server Protocol](https://microsoft.github.io/language-server-protocol/specification).

@CyrusNajmabadi: Do you have any concerns or areas I should look out for as I work on making this API public?

**Comment by CyrusNajmabadi** [comment]
> @CyrusNajmabadi: Do you have any concerns or areas I should look out for as I work on making this API public?

If we make this public, all i would ask is that we document the behavior completely.  With that, i'm fine :)

**Comment by PathogenDavid** [comment]
I can create a separate issue for this, but since this issue also concerns enhancing the documentation on `SymbolKey`, I figured I'd point it out here.

The [main documentation for `SymbolKey`](https://github.com/DustinCampbell/roslyn/blob/d1359e701e4b6388ad43b31a732ac019569f7ca2/src/Workspaces/Core/Portable/SymbolKey/SymbolKey.cs#L46-L48) states the following:

```csharp
///     If the <see cref="INamespaceSymbol"/> is the global namespace for a
///     compilation (and thus does not have a containing symbol) then it will only match another
///     global namespace of another compilation.</item>
```

This statement is incorrect:

1. Global namespaces do have a containing symbol - a module. (As far as I am aware, an assembly is the only symbol that can't have a containing symbol.)
2. This isn't even correct from a `SymbolKey` perspective since the containing module is considered for symbol same-ness.

-----------------

For reference, here is the chain of containing symbols for `System.Single`:

```
NamedType float
  Namespace System
    Namespace <global namespace>
      NetModule CommonLanguageRuntimeLibrary
        Assembly mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
```

And here's the encoded `SymbolKey` data, showing that both the module (`U`) and assembly (`S`) are considered:

```
(D "Single" (N "System" 0 (N "" 0 (U (S "mscorlib" 4) 3) 2) 1) 0 10 0 ! 0)
```

**Comment by CyrusNajmabadi** [comment]
This would need to go through an API proposal.
