### ISSUE TITLE
Light bulb code fix doesn't work on generated files

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#2753]
![lightbulb_bug1](https://cloud.githubusercontent.com/assets/12449387/7639651/5e98f60e-fa32-11e4-9e58-e29b1dcbd4a9.png)

On autogenerated file (AssemblyInfo.cs) When I click on the “Fix all occurances in : Document “ nothing happens , if I preview and apply it does.

**Comment by shyamnamboodiripad** [comment]
Per @mavasani this is happening because the batch fixer is skipping generated files.

If generated files are not supported for fix all should we consider disabling light bulb entirely in such files? (The fix in project / solution links may still be useful - but I guess they can also be invoked from non-generated files.)

**Comment by sharwell** [comment]
It should not be the job of the `FixAllProvider` to separate generated files from non-generated files. The `DiagnosticAnalyzer` and/or `CodeFixProvider` should bear the responsibility for suppressing messages in generated files. By placing this code in the `FixAllProvider`, the UI indicates a problem was found and an automatic solution is available, but then fails to apply the automatic solution.

**Comment by mavasani** [comment]
@sharwell I don't think that we want every fixer/analyzer to understand whether it is being invoked within a generated or non-generated file. I believe the correct approach is to categorize generated files into:

1. One time generated files (such as AssemblyInfo.cs).
2. Temporary generated files, which get regenerated based on the contents on another project item on user actions such as build, editing and saving the .resx file, etc.

One time generated file should be treated like ordinary source files by both lightbulb and fix all. For temporary generated files, we should suppress the lightbulb and retain the current fix all behavior.

Also note that the current fix all implementation skips processing the generated files at first step itself, i.e. it won't even compute diagnostics in those files. So, it will not compute or show a fix within them in the preview dialog.

**Comment by mavasani** [comment]
We probably want to update the APIs in [GeneratedCodeRecognitionService](http://source.roslyn.io/Microsoft.CodeAnalysis.Workspaces/R/f6a02beb3e2a98de.html) to take an additional flag about whether the callee wants a specific category of generated files or all of them.

**Comment by sharwell** [comment]
> For temporary generated files, we should suppress the lightbulb and retain the current fix all behavior.

It's very important that if a diagnostic is reported and a code fix is available for that diagnostic, it works regardless of the location. If you are not suppressing *diagnostics* in these files, then you should also not suppress either the light bulb or the code fixes.

In the StyleCopAnalyzers project, we provide complete coverage for diagnostics and code fixes using a specific set of rules for which files are excluded from analysis. If the code fix fails to correct any instance of a reported diagnostic, then that is something we need to correct.

**Comment by sharwell** [comment]
@mavasani The missing 0.6% in [this tweet](https://twitter.com/samharwell/status/625440315688652800) was entirely due to this issue. Now that we implemented our own `CustomBatchFixAllProvider` which does not attempt to distinguish generated code from other code (DotNetAnalyzers/StyleCopAnalyzers#1122), we can now fix all violations.

**Comment by mavasani** [comment]
@sharwell You are right, I think we should just skip analyzing temporary generated files in the IDE diagnostic service, and then change FixAll to not bother about whether a file is generated or not. @heejaechang what do you think?

**Comment by sharwell** [comment]
The problem with that approach is diagnostic analyzers are able to cause a build to fail. It is conceivable that a project would use diagnostic analyzers to prevent a build from succeeding if any compilation unit met certain conditions, regardless of the source of this file.

I believe the solution is to simply change the fix all provider to not distinguish between generated and other code. If a user applies a code fix within the generated code, that change will be reversed anyway the next time the generator runs.

**Comment by heejaechang** [comment]
@sharwell @mavasani I think if there are too many corner cases that require human decision, I think it might be just better we don't implicitly make those decision in a way user can't control.

basically what I am saying is. default FixAllProvider doesn't distinguish it, but fixer engine distinguish those and make it easier for users to make decision.

for example, when user click fix all document, project, solution, and if fix involves changes in the generated file, in the preview, it shows info bar/warning somewhere that indicates it contains changes in generated files, and group them in one place so that it can be easily selected/deselected with one click. and default can be saved from last time it was changed.

**Comment by sharwell** [comment]
@heejaechang That sounds like it could work. :+1:

**Comment by twsouthwick** [comment]
I'm hitting this for some codefixers I'm authoring - the diagnostics are raised fine, but I don't see a way to apply the code fix. Is there a way that the built in batch processor could at least expose a way to decide whether or not to apply to a generated file similar to how analyzers can opt in/out of it?

**Comment by sharwell** [comment]
I didn't realize this wasn't fixed already. I'm testing a fix for it now.

**Comment by CyrusNajmabadi** [comment]
Subsumed by https://github.com/dotnet/roslyn/pull/33515
