### ISSUE TITLE
Destructor code snippet inserted by one Tab

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#27885]
copied from internal [link](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/625459)
Affected Branch: [27729.1.d15.8]
Affected Build: 15.8.0 Preview 2.0
Affected Product Language: C#

Steps to reproduce:

1. Open any C# project
2. Print ~
3. Press Tab twice

Expected: snippet for destructor inserted
Actual: snippet for destructor inserted after first Tab and second Tab added to destructor's body
Note: other snippets inserted by twice Tab

[Repro Gif](https://microsoft-my.sharepoint.com/:i:/p/v-rodudi/EUE2ISyarsxMpqMDkHp5rzgB5CGeGv8PmpCOUkCDivD2Aw?e=gWJkqB)

**Comment by sharwell** [comment]
When inserting a snippet, the first <kbd>Tab</kbd> isn't ignored - it clears the completion list. You could also press any other sequence that clears out the completion list, such as <kbd>Esc</kbd>-<kbd>Tab</kbd> or <kbd>Enter</kbd>-<kbd>Tab</kbd>. The unique characteristic about `~` isn't the fact that only one <kbd>Tab</kbd> is required, but rather the fact that typing `~` doesn't trigger the completion list to appear.

Marked as **Need Design Review** since it's not clear how this should proceed.

**Comment by sharwell** [comment]
Design review conclusion: This behavior is strange, but it's a low-impact situation that shouldn't need to change. In addition, since the behavior has not changed in a long time, we believe there are likely users who have muscle memory that typing <kbd>~</kbd>, <kbd>Tab</kbd> will insert a finalizer. The specific behavior detail that led to the current state was already described in https://github.com/dotnet/roslyn/issues/27885#issuecomment-397500804. Marking as **Won't Fix**.
