### ISSUE TITLE
"Enter key behavior" option and other options don't have a default

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#27896]
The following options don't have "defaults" when they clearly do:

C#:
![image](https://user-images.githubusercontent.com/1103906/41456573-3a12f08a-70c4-11e8-9cda-284aa7b2c1d3.png)

VB:
![image](https://user-images.githubusercontent.com/1103906/41456643-746d903c-70c4-11e8-93ae-4887e3364100.png)

**Comment by vritant24** [comment]
Hi,
I'd like to try and fix this issue. Since this is my first issue, I would appreciate some help.

I found the files where to code fixes would need to be:
`\src\VisualStudio\CSharp\Impl\Options\IntelliSenseOptionPageControl.xaml`, `line: 39` for C#. (I also see that the `Snippets Behavior` option doesn't have a default for C# and assume that needs one too.)
`\src\VisualStudio\VisualBasic\Impl\Options\IntelliSenseOptionPageControl.xaml`, `line: 36` for VB

Which options would need to be set as the default?
Are there any resources/examples I could look at to learn to implement the fix?

**Comment by sharwell** [comment]
@vritant24 The issue here is _one_ of the three options under **Enter key behavior** should be selected, but in a fresh install none is. It looks like the **Snippets behavior** section in C# is working, so maybe see if you can find a difference between the way that's handled and the way enter key behavior is handled?

**Comment by CyrusNajmabadi** [comment]
Closing out as this has been fixed.
