### ISSUE TITLE
Numerous instances of VBCSCompiler.exe slowing down Roslyn.sln build

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#2790]
I am noticing extremely slow build times for Roslyn.sln (> 15 mins), with when self-building Roslyn.sln with locally built compiler bits. The primary reason seems to be lots and lots of VBCSCompiler.exe processes being spawned by msbuild (see screenshot). When I build with our current toolset compiler, I don’t see this issue and build seems to be pretty fast (~2-3 mins).

It is likely that this was caused by https://github.com/dotnet/roslyn/pull/2229#issuecomment-101695803

![vbcscompiler_multiple](https://cloud.githubusercontent.com/assets/10605811/7657437/a90b1938-fae6-11e4-9efd-ed8cffcb82d4.png)

/cc @agocke

**Comment by pharring** [comment]
Could this be at the root of our perf machine issues?

**Comment by pharring** [comment]
Answering my own question: Yes. I just cracked open a profile from the 6-core machine and we see multiple compiler server processes there.

**Comment by agocke** [comment]
Shouldn’t quite explain failures… but it definitely would explain slowness.

**Comment by pharring** [comment]
Verified by looking at the latest performance traces. I see exactly one instance of the compiler server process as expected.

**Comment by jrussell865** [comment]
This is probably not the right place for this type of question/comment, but I'm seeing this exact issue with what I think is an official release of Visual Studio Professional 2015 (14.0.23107.0). I've not knowingly installed any beta versions. This is a relatively small .NET 4.0 C# solution (~20 projects). Randomly the number of VBCSCompiler instances will multiply and bring my box to a crawl. No one else has reported this issue. This is the only place that I can find something similar... What causes this issue?? How can it be corrected? Any help would be appreciated. Let me know if you need more information. Or you can email me directly.

**Comment by pharring** [comment]
@jrussell865 no worries; you did the right thing. Thanks for tracking down this issue.
@jaredpar FYI
@angocke What can we do to diagnose this on @jrussell865's machine? Verify build number; attach a debugger to the compiler server? Perhaps an ETW trace with PerfView (or the VS feedback tool) might capture exception information.

**Comment by jaredpar** [comment]
@jrussell865 would you be able to grab a dump of a couple of the VBCSCompiler processes?  I think that's the best way to start looking into this.

Also curious: when this occurs, if you stop using VS for 15 minutes do the instances shut themselves down or do they stay active?

**Comment by jrussell865** [comment]
I will capture the dumps as soon as it happens again. I can't predict when it occurs, so it may be a bit. As far as whether the instances shut themselves down automatically, I'm not really sure. I've not waited 15 minutes to see - but I will leave them be next time. I usually kill them off via task manager. Thanks!!

**Comment by jrussell865** [comment]
Sorry for the delay. Took a bit to reproduce the issue. The following links will take you to the dump files from a couple of the VBCSCompiler.exe processes:

https://vimtechnologies-my.sharepoint.com/personal/john_russell_vimtechnologies_com/_layouts/15/guestaccess.aspx?guestaccesstoken=O71MLYFnVN%2bXOc9M%2fohjktsEVoEdExglLB1WmVFd9Iw%3d&docid=0ff8e04b8f9c64b33b02924844d7acd1c

https://vimtechnologies-my.sharepoint.com/personal/john_russell_vimtechnologies_com/_layouts/15/guestaccess.aspx?guestaccesstoken=9LpyLSrV9nktxAjVwXX5EjBYD4qiNROZWGPE15hPngM%3d&docid=0f796181bb8444b9c90c893e34f858d5e

Also, here's a screen shot of my task manager with the arguments being passed:

![untitled](https://cloud.githubusercontent.com/assets/13695873/9173001/317df11c-3f45-11e5-9292-9ccb1b7348cc.png)

Let me know if there's anything else I can provide.

Thanks again!!

**Comment by Montago** [comment]
This issue hasn't been solved...

We are 4-5 people in a team of 15 that struggle with this issue daily :(

ever since we added the Roslyn compiler, some of us are seeing ultiple VBCSCompiler instances that we have to kill to regain control over our computer !!

**Comment by jaredpar** [comment]
@Montago what version of Visual Studio are you running?  There were a few bugs in RTM but most of them have been fixed as of Update 1.

**Comment by Montago** [comment]
We are running VS 2015 SP1 -- all fully upgraded / updated. 

All PC's are Windows 7 Enterprise / Professional (also fully updated)

**Comment by jaredpar** [comment]
@Montago hmm.  That shouldn't be happening.  In update 1 the server uses a mutex to ensure only one instance can be running per user on the machine.  There should only be multiple instances running if ...

1. There are multiple users on the machine compiling.  
2. A single user issues a compilation from an admin and non-admin account.  In that case there will be two servers created. 

If neither of those are happening could you grab a dump of the processes and post it somewhere for us to take a look at?

**Comment by Montago** [comment]
sorry for asking but how do i make those dump files ?

**Comment by jaredpar** [comment]
@Montago this article describes the process:

> http://blogs.msdn.com/b/debugger/archive/2009/12/30/what-is-a-dump-and-how-do-i-create-one.aspx

In general procdump would be best here.  Make sure to use the `-ma` option.  Without it the dumps are rarely useful for us to look at .

**Comment by dviljoen** [comment]
I'm experiencing this issue intermittently.  This issue is closed.  Does that mean it was fixed?
My environment: 
Microsoft Visual Studio Professional 2015
Version 14.0.25431.01 Update 3
Microsoft .NET Framework
Version 4.6.01055

Installed Version: Professional

Microsoft Visual Studio Tools for Applications 2015   00322-50051-00059-AA251
Microsoft Visual Studio Tools for Applications 2015

Visual Basic 2015   00322-50051-00059-AA251
Microsoft Visual Basic 2015

Visual C# 2015   00322-50051-00059-AA251
Microsoft Visual C# 2015

Visual C++ 2015   00322-50051-00059-AA251
Microsoft Visual C++ 2015

Application Insights Tools for Visual Studio Package   7.18.00214.2
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2015.1   14.1.21111.0
ASP.NET and Web Tools 2015.1

ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.40314.0
For additional information, visit http://www.asp.net/

Azure App Service Tools v2.8.1   14.0.11123.0
Azure App Service Tools v2.8.1

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.0.6000.0
Microsoft Azure Data Lake Tools for Visual Studio

Common Azure Tools   1.8
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

GhostDoc   5.4.16325.0
GhostDoc automatically generates XML documentation comments.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

Microsoft .NET Core Tools (Preview 2)   14.1.21111.0
Microsoft .NET Core Tools (Preview 2)

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2015 - v2.9.40701.9

Microsoft Azure Tools   2.7
Microsoft Azure Tools for Microsoft Visual Studio 2015 - v2.7.30818.1601

NuGet Package Manager   3.5.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

Python Tools for Visual Studio   2.2.50113.00
Python Tools for Visual Studio provides IntelliSense, projects, templates, Interactive windows, and other support for Python developers.

Python Tools for Visual Studio - Django Integration   2.2.50113.00
Provides templates and integration for the Django web framework.

Python Tools for Visual Studio - Profiling Support   2.2.50113.00
Profiling support for Python projects.

SQL Server Analysis Services   13.0.1701.8
Microsoft SQL Server Analysis Services Designer 
Version 13.0.1701.8

SQL Server Data Tools   14.0.61021.0
Microsoft SQL Server Data Tools

SQL Server Integration Services   
Microsoft SQL Server Integration Services Designer
Version 13.0.1601.5

SQL Server Reporting Services   13.0.1701.8
Microsoft SQL Server Reporting Services Designers 
Version 13.0.1701.8

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript   1.8.36.0
TypeScript tools for Visual Studio
