### ISSUE TITLE
Add a code fix for going from "expression-body member" to "auto-property initializer" and vice versa

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#27948]
I can never remember the syntax for going from "expression-body member" to "auto-property initializer":

``` C#
public static ImageMoniker ApplicationPrivate => new ImageMoniker { Guid = s_manifestGuid, Id = ApplicationPrivateId };
```

to:

``` C#
public static ImageMoniker ApplicationPrivate { get; } = new ImageMoniker { Guid = s_manifestGuid, Id = ApplicationPrivateId };
```

It would be great if we had a code fix to automatically do this.

**Comment by sharwell** [comment]
Design review conclusion: there is some concern that this will be too noisy, and possibly confusing since it will likely trigger in the same scenarios as "Use block body", which is a behavior-preserving code style refactoring. To reduce confusion, this should have a title which clearly indicates that the refactoring will result in the initialized value of the property being cached.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of broader feedback on this.
