### ISSUE TITLE
Duplicate diagnostic reports in unit tests

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#28]
We are observing multiple cases in the StyleCopAnalyzers project where the unit tests are producing multiple reports for the same diagnostic. The behavior is reproducible (100% observed consistency for Beta 1 and Beta 2), but we have diagnostics where only *particular* inputs result in the behavior, suggesting that the problem is not within the diagnostic implementation itself. We believe the problem lies either in the unit test framework or in Roslyn itself.

This behavior is currently affecting the following diagnostics:

* [SA1121 Use built-in type alias](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/9d1d078dafef149fa3f578ffcd589b585f2dd775/StyleCop.Analyzers/StyleCop.Analyzers.Test/ReadabilityRules/SA1121UnitTests.cs#L949-L960)
* [SA1304 Non-private readonly fields must begin with upper-case letter](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/9d1d078dafef149fa3f578ffcd589b585f2dd775/StyleCop.Analyzers/StyleCop.Analyzers.Test/NamingRules/SA1304UnitTests.cs#L45-L56)
* [SA1600 Elements must be documented](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/9d1d078dafef149fa3f578ffcd589b585f2dd775/StyleCop.Analyzers/StyleCop.Analyzers.Test/DocumentationRules/SA1600UnitTests.cs#L368-L379)

The unit test framework we use is the one provided with a new Roslyn diagnostic project (created with Visual Studio 2015 Preview), converted to use `async` methods instead of synchronous methods.

It would be enormously helpful if someone could help track down the cause of this issue.

**Comment by jmarolf** [comment]
The issue is that the AnalyzerDriver used to call syntax node analysis for both symbols (it would look at the declaration syntax node) and syntax causing certain types of analysis, such as identifier name, to get called twice.  There was a significant re-factoring of the AnalyzerDriver to remove this.  I've updated the StyleCopAnalyzers project to use the new AnalyzerDriver on my fork and verified that this issue is fixed. 

![Test run with distinct disabled](http://i.imgur.com/wlhokAz.png)

You can take a look at the changes in my fork [here](https://github.com/jmarolf/StyleCopAnalyzers/commit/6608d33324e85c18ab25267051c0db20ef742201).  

I'll reply back here when we've released nuget packages that have this fix.
