### ISSUE TITLE
ValueTuple does not work properly when using the dynamic parameter in function

### ISSUE THREAD

**Issue by pedoc** [dotnet/roslyn#28112]
**Version Used**: 
Framework:netcore2.0
LanguageVersion:C#latest(7.3)

**Steps to Reproduce**:
1. create console project
2. test code:
```
 class Program
    {
        static void Main(string[] args)
        {
            dynamic input = new object();
            var output = TestTuple(input);
            Console.WriteLine(output.result1);
            Console.WriteLine(output.result2);
            Console.ReadKey();
        }

        private static (bool result1, bool result2) TestTuple(object input)
        {
            return (true, false);
        }
    }
```

**Expected Behavior**:
print True,False in console

**Actual Behavior**:
throw a Exception:
`Microsoft.CSharp.RuntimeBinder.RuntimeBinderException:“'System.ValueTuple<bool,bool>' does not contain a definition for 'result1'”`

when `TestTuple` argument Type is `dynamic`，`TestTuple` return value from ValueTuple chanded to `dynamic`.
if the argument type is cast, it works,code example:
` var output = TestTuple((object)input);`

any help?
thanks

**Comment by HaloFour** [comment]
When you use a `dynamic` in any expression the entire expression becomes `dynamic` and evaluated at runtime.  So when you pass `input` to `TestTuple` as a `dynamic` the compiler skips compile-time checking of the entire expression and `output` is also of type `dynamic`.

Add to that the fact that tuple names don't existing at runtime and you get this confusion.  The `result1` and `result2` pseudo-members which the compiler would normally resolve and replace with the actual member names are lost and since `output` is dynamic and the property access not attempted until runtime that's why that expression throws.

**Comment by pedoc** [comment]
@HaloFour hi，thanks for reply 😄 

in the sample code，`input` not any reference in function `TestTuple`,at this time,compiler shouldn’t skip this directly，so as to avoid the return value becoming `dynamic`?

**Comment by svick** [comment]
@pedoc `dynamic` does not consider whatever is inside the called method and I don't think it should. The rule is that when an expression contains a `dynamic` sub-expression, the whole expression is `dynamic` (with the exception of casting).

**Comment by HaloFour** [comment]
@pedoc 

> at this time,compiler shouldn’t skip this directly，so as to avoid the return value becoming `dynamic`?

The fact that you pass `input` to `TestTuple` is what causes the entire expression to be evaluated at runtime.  The compiler at that point will do some rudimentary checks to ensure that the method exists, that it has the correct arity and that any non-dynamic arguments are of the appropriate type.  But the invocation of the method is emitted and bound at run time, instead of trying to cast the dynamic argument to the type of the parameter, and the return value is dynamic.

What's unfortunate here is that the tuple element names are lost so the C# binder can't resolve them.  I don't know if that's something that could be fixed.

**Comment by pedoc** [comment]
@svick @HaloFour ok,thanks a lot of

**Comment by ufcpp** [comment]
```cs
dynamic input = new object();
var output = TestTuple(input);
Console.WriteLine(output.Item1);
Console.WriteLine(output.Item2);
Console.ReadKey();
```

**Comment by pedoc** [comment]
@ufcpp 
yes,it's work but loses grammar advantage.
this is not the expected effect
