### ISSUE TITLE
Visual Studio crashed when type { object = ref

### ISSUE THREAD

**Issue by NoofSaeidh** [dotnet/roslyn#28238]
**Version Used**: 
15.7.4

**Steps to Reproduce**:
open any method, or C# interactive and start writing:
var temp = new { object = ref

**Expected Behavior**:
Error that "object" appears.

**Actual Behavior**:
Visual Studio crashed

**Comment by NoofSaeidh** [comment]
I found this because in generated class there are property: "@object", but intellisense autocorrects it to "object" (and my variable's name started from ref)

**Comment by jinujoseph** [comment]
cc @ivanbasov  to triage

**Comment by jhinder** [comment]
I can reproduce this, but only in 15.7.4 and 15.8-pre3, not on the current `master` revision.

Analyzing a dump with WinDbg showed that there was an `InvalidOperationException` coming from `Microsoft.CodeAnalysis.CSharp.BoundExpressionExtensions.GetRefKind()`. This exception was thrown because the switch fell through to the default case (`node.Kind` is `TypeExpression`), which used to throw the exception generated by `ExceptionUtilities.UnexpectedValue()`, which is an `InvalidOperationException`.

The code was changed in PR #27030, now it returns `RefKind.None` instead of throwing. The revision before the merge (42b41179cb) will crash.

**Comment by tmat** [comment]
@OmarTawfik Please, confirm that this case was intentionally fixed.
