### ISSUE TITLE
Go To support for decompiled types/members

### ISSUE THREAD

**Issue by gundermanc** [dotnet/roslyn#28275]
The experimental decompilation feature in VS 2017 15.8 Preview 3 has proven to be quite nifty for enabling use of code in place of documentation in large projects that share code as binaries (like VS).

![image](https://user-images.githubusercontent.com/5387680/42249019-abdf74a0-7edd-11e8-906e-73aec7eb9048.png)

A missing nice-to-have would be to be able to use 'Go To' to navigate to the decompilation of types referenced by the project. These could be surfaced the same as any type present in the project but ordered low in the list.

**Comment by CyrusNajmabadi** [comment]
This would be nice.  Note that there are challenges here due to creating the right 'context' in which to do the decompilation.  For example, your type may be found in metadata in many different projects.  Those projects all may have different settings and differents sets of referenced metadata.  This will impact you as you do further things like goto-def on symbols in the decompiled code.

This is def solvable, but subtle.
