### ISSUE TITLE
Intermittently unable to modify IsEnabledByDefault through an AdditionalFiles passed to analyzer

### ISSUE THREAD

**Issue by msbasanth** [dotnet/roslyn#28370]
**Version Used**: 
Roslyn v2.6.0

**Steps to Reproduce**:

1. In the our analyzer constructor/class level we are setting the IsEnabledByDefault value of the analyzer to true.

DiagnosticDescriptor = new DiagnosticDescriptor(DiagnosticId, Title, MessageFormat, AnalyzerCategory.SpecialRules, DiagnosticSeverity.Warning, true, Description, HelpLink);

2. We have need to change the IsEnabledByDefault according to a configuration(XML). For this we have a settings file(as AdditionalFile) with global and analyzer specific settings for our analyzer package.

public override void Initialize(AnalysisContext analysisContext)
{
	analysisContext.RegisterCompilationStartAction(compilationStartContext =>
    {
	    ImmutableArray<AdditionalText> additionalFiles = compilationStartContext.Options.AdditionalFiles;
        AdditionalText settingsFile = additionalFiles.FirstOrDefault(file => Path.GetFileName(file.Path).Equals(CodeAnalysisSettingsProvider.SettingsFileName));
        bool isEnabledByDefault = ... // read from settingsFile.
        DiagnosticDescriptor = DiagnosticDescriptor.WithIsEnabledByDefault(isEnabledByDefault);
    }
}

2. This way we could modify the IsEnabledByDefault value at runtime by reading the settings from the XML.
   This works fine when we run the code analysis in VisualStudio menu. The same analysis when we run in the build machine we could see analyzer enabled by default. i.e. the setting is not taken from AdditionalFile inputted.

**Expected Behavior**:
I expected we will get the modified DiagnosticDescriptor instance will make the changes in the Aanalyzer instance and won't be enabled by default if we have IsEnabledByDefault = false in the settings file.

**Actual Behavior**:
Now intermittently seeing analyzer not picking the latest value from the settings file.

It looks like by the time RegisterCompilationStartAction is triggered descriptor is used by the msbuild task. Whether DiagnosticDescriptor is used by compilation before RegisterCompilationStartAction is triggered?

Let me know if there a better approach to modify IsEnabledByDefault using a setting from outside.

Thanks
Basanth

**Comment by mavasani** [comment]
This is by design. `IsEnabledByDefault` is for the *default* analyzer configuration, which is tied only to an instance of an analyzer, not context entities such as additional file text or compilation. The value remains the same for the entire lifetime of the analyzer instance.

You can potentially implement a filtering logic at every diagnostic report site in the analyzer code to get your desired behavior, but this is only possible for analyzer rules which are _enabled_ by default, not the _disabled_ ones.
An analyzer which is disabled by default can only be enabled by explicit user settings passed to the compiler (not analyzer), such as ruleset entry to enable the analyzer or `/warnaserror:<RuleId>`.

**Comment by msbasanth** [comment]
Thanks for the quick response. I will recheck our implementation.
