### ISSUE TITLE
Error taking address of fixed sized member

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#28476]
Consider the following code:

``` csharp
using System;
using System.Runtime.InteropServices;

public unsafe class C
{
    public void M() { }

    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    unsafe struct NativeDkmString
    {
        public IntPtr VTable;
        public int m_ReferenceCount;
        public int m_Length;
        public fixed char m_Value[1]; // this is a variable-length array

        public static extern int ProcDkmString0(IntPtr /*const DkmSourceString&*/ pInputString, out IntPtr /*DkmString**/ pCreatedObject);
    }
    
    public static void StringToManaged(IntPtr pvNativeString)
    {
        NativeDkmString* pNativeString = (NativeDkmString*)pvNativeString;
        char* ptr = &pNativeString->m_Value[0];
    }
    
}
```

This code should compile. Instead it incorrectly emits the following error:

> error CS0212: You can only take the address of an unfixed expression inside of a fixed statement initializer

**Comment by agocke** [comment]
I've been trying to gather context on this bug, the previous bugs, and the feature design all the way back to what we did for C# 7.3. I'd like to record some of what I've found.

First, a reminder of what a pointer is in C#. A pointer is an unmanaged reference, so if a pointer is pointing into a managed object, the GC can move the underlying memory or free it if there isn't something preventing it from doing so. Pointers in C# are unsafe, so there are no guarantees from the compiler that they're being used correctly, but the language does have substantial guardrails in place to make it less likely certain things will happen, especially getting a pointer to a managed object that may be moved by the GC.

This notion is formalized in the language by a notion of ["moveable" and "fixed" variables](https://github.com/dotnet/csharplang/blob/master/spec/unsafe-code.md#fixed-and-moveable-variables). A moveable variable may be moved by the GC, so the language provides the `fixed` statement to provide a scoped region where the variable may not be moved by the GC. This leads to the single most important pointer safety principle in the language: **you cannot get a pointer to a moveable variable unless it is inside a `fixed` statement initializer**. Once you have one, that's where the guard rails end. The language won't prevent you from stashing away the pointer for longer than the lifetime of the `fixed` statement, but it will provide the base level of security of requiring moveable variables to be fixed before you can retrieve a pointer. This also means that subsequent safety guardrails of the language are dependent on the assumption that, if you have a pointer, its target must be fixed.

Now that we know the principle, we can track down the rules that enforce it. The most obvious is around the "address-of" (`&`) operator. This is one of the only ways to get a pointer in pure C# code. The spec says this about address-of and moveable variables:

> the address of a moveable variable can only be obtained using a fixed statement

So the principle is safe.

The only other way I can find to get a pointer in pure C# code is a [fixed size buffer](https://github.com/dotnet/csharplang/blob/master/spec/unsafe-code.md#fixed-size-buffers). In this case, the native type of a fixed size buffer is *already a pointer*, so the address-of operator rule cannot help. The only way this can be guaranteed to be safe is if (1) fixed size buffers are always non-moveable variables or (2) there is another rule about fixed size buffer usage. (1) is not true, but (2) is. The spec has this to say about [accessing fixed size buffers](https://github.com/dotnet/csharplang/blob/master/spec/unsafe-code.md#fixed-size-buffers-in-expressions):

>In a member access of the form `E.I` ...  if `E` is a moveable variable... and the expression `E.I` is not a _fixed_pointer_initializer_, a compile-time error occurs.

And so C# 6 is safe.

Now, enter C# 7.3. A feature is [proposed](https://github.com/dotnet/csharplang/blob/master/proposals/csharp-7.3/indexing-movable-fixed-fields.md) to allow a _pointer_member_access_ to a moveable fixed size buffer outside a fixed statement. This can be seen as essentially sugar for turning `T x = fixed_buf[0]` into

```C#
T x;
fixed (T* ptr = &fixed_buf)
{
    x = ptr[0];
}
```

However, this absolutely breaks the C# 6 safety principle: you can now get a pointer to a moveable variable outside the fixed statement. Luckily, the result of the expression must be a primitive type, so there are no complex questions about the result type, but there's still the concern that we could get back to the original pointer without a fixed statement. To prove that is not possible, we can use the assumption from before: there are only two ways to get a pointer in pure C#: address-of and fixed size buffers. Since the resulting type is a primitive type, there is no way to get a fixed size buffer off of it. Thus, the only way is address-of. If the value resulting from `moveable_fixed_buf[0]` is moveable, then we know this is safe from the previous lemma.

Unfortunately, that is not true. The spec says:

> a fixed variable is... a variable resulting from a... _pointer_element_access_ of the form `P[E]`

Our new expression is a _pointer_element_access_ of that form. Note that the rule does not consider whether or not `P` is moveable -- it is assumed that all pointers are fixed because of the application of the previous safety rules.

Thus, we have a safety hole. The expression `&moveable_fixed_buf[0]` appears to result in a non-moveable variable, even though the resulting pointer is to moveable memory.

To repair this hole, I propose a modification to the existing rule for _pointer_element_access_, namely:

> a variable resulting from a... _pointer_element_access_ of the form `P[E]` [is fixed] if `P` is not a fixed size buffer expression, or if the expression is a fixed size buffer _member_access_ of the form `E.I` and `E` is a fixed variable

This effectively means that a _pointer_element_access_ off a moveable fixed sized buffer will result in a moveable variable, instead of a fixed one. We should now be able to apply the earlier lemma and consider safety proved.
