### ISSUE TITLE
Structure guidelines is wierd C#

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#28551]
The structure guidelines is wierd in C#

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/45549/structure-guidelines-is-wierd-c.html
VSTS ticketId: 422050_
_These are the original issue comments:_

![image](https://user-images.githubusercontent.com/12449387/42732023-f4e9bb4e-87cd-11e8-9edf-e596143062c1.png)

[File example](https://developercommunity.visualstudio.com/storage/attachments/4960-flashbangactor.zip)

**Comment by CyrusNajmabadi** [comment]
@gundermanc Another user issue here.  Has the editor been able to budget any time to adopt the "align the guideline to the left-most of the two points" approach we talked about previously?

**Comment by CyrusNajmabadi** [comment]
@olegtk can you move to editor/platform?  this is not on the roslyn side IMO.

**Comment by olegtk** [comment]
@gundermanc, do you have a context about ""align the guideline to the left-most of the two points" approach" ?

**Comment by gundermanc** [comment]
> @gundermanc, do you have a context about ""align the guideline to the left-most of the two points" approach" ?

This is not a change I committed to on the Editor side because it can absolutely be implemented with the primitives exposed by the current API.

The LSP implementation of this feature implements this heuristic already. I expect this to be a non-issue once Roslyn switches over to textDocument/foldingRange for structure guides.
