### ISSUE TITLE
Roslyn analyzers generate warnings for projects where they weren't installed as a nuget package

### ISSUE THREAD

**Issue by JarLob** [dotnet/roslyn#28757]
**15.7.5**: 

**Steps to Reproduce**:

1. Open some solution with projects and tests. You can use Nancy for example: `git clone https://github.com/NancyFx/Nancy.git`
2. Click manage nuget packaged for solution and add some roslyn analyzers nuget package, for example https://www.nuget.org/packages/Microsoft.CodeQuality.Analyzers to a single project in the solution - `Nancy`
3. Build the solution.

**Expected Behavior**:
Code quality warnings just from a single project in the solution.

**Actual Behavior**:
Warnings from test projects too. Microsoft.CodeQuality.Analyzers listed as a dependency under projects, that were not selected when installing the nuget package (nuget manager still shows only one project installed).
![image](https://user-images.githubusercontent.com/26652396/43036242-49ed3b56-8d06-11e8-8781-19a616c4f9f0.png)

Notice, that Microsoft.CodeQuality.Analyzers has `<developmentDependency>true</developmentDependency>` in nuspec.

Do I miss something? Does it work as expected? How to use roslyn analyzers just for selected subset of projects?

**Comment by JarLob** [comment]
Tried the same with a solution that doesn't have netstandard projects and it works as expected - no analyzers appeared in dependent projects.

**Comment by mavasani** [comment]
This is by design. See the "NOTE" at the end of https://docs.microsoft.com/en-us/visualstudio/code-quality/use-roslyn-analyzers for clarification and `PrivateAssets` workaround.

@gewarren Thanks a lot for documenting this. @JarLob Did you try to search the documentation or google your specific issue? Wonder if we can highlight the documentation better in searches as this is quite a common issue that people seem to be facing.

**Comment by mavasani** [comment]
@sharwell pointed out that @JarLob has correct expectations for his scenario and `<developmentDependency>true</developmentDependency>` should automatically imply `<PrivateAssets >all</PrivateAssets>`. This is NuGet bug https://github.com/NuGet/Home/issues/4125, which should be fixed with https://github.com/NuGet/NuGet.Client/pull/2182

**Comment by JarLob** [comment]
Actually I didn't try to web search for that, but I did search issues. Now hopefully if we'll be even easier to find. I also put the information on my [analyzer site](https://security-code-scan.github.io/)
