### ISSUE TITLE
Intellisense lambda backspace issue

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#28921]
There's an issue regarding intellisense activation when writing and rewriting a lambda expression in C#.

If I in an empty line write &quot;Func&lt;int, int&gt; f = a =&gt; [...]&quot; intellisense will not suggest anything on inputting &quot;a&quot;, leaving me to easily move on to writing the lambda body.

If I however somewhere in said lambda body decide to change the input variable name, say from &quot;a&quot; to &quot;b&quot;, and do this by backspacing back before &quot;a&quot; after which I enter &quot;b&quot;, intellisense will popup with a suggestion making my next whitespace tap autocomplete some random type starting with &quot;b&quot;.
In my case it's usually BadImageFormatException, which I'm really starting to hate.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/297360/intellisense-lambda-backspace-issue.html
VSTS ticketId: 652005_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by Dunkhan** [comment]
This is part of a larger issue. Backspace changes the behaviour of intellisense completely.
I use suggestion mode and after backspace is pressed it switches to standard mode for the current suggestion list.

This means if you are in suggestion mode type asd  on a new line, then space, then backspace twice, then space again you get the keyword 'async' automatically inserted instead of 'as' which is what was typed. Suggestion mode should never autocomplete on space.

Some internal switch is being changed in intellisense when it is activated by backspace, that makes it behave differently than when it is activated by any other keypress.

**Comment by Dunkhan** [comment]
The variation I mentioned was fixed in VS 15.8.0
The original lambda variant is not fixed however. It seems these were two different issues.

**Comment by CyrusNajmabadi** [comment]
Closing this out as this does not repro.  If i backspace over 'a' and try to type something else, i remain in suggestion mode.  If there are other cases where this arised, please add repro steps that show what they are.  Thanks!
