### ISSUE TITLE
Cannot override /features value cleanly

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/roslyn#28935]
**Version Used**: 
2.8.0.62811 (9081e399)

**Steps to Reproduce**:

It appears to be not possible to override `/feature:strict` later in the command line. As a general rule it is helpful for command line parsers to allow flags to be overridable. Scenarios include overriding response file entries, or (in an MSBuild project) overriding inherited property values.

For example imagine I have a .props file that globally sets this in my source tree
```xml
    <Features>strict</Features>
```
Now in one .csproj I want to not apply strict. In order to not wipe out whatever is in `<Features>` I would like to do something like one of these 
```xml
    <Features>$(Features);strict=false</Features>
    <Features>$(Features);strict-</Features>
```
These do not work currently and I have to be a bit hacky:
```xml
    <Features>$(Features.Replace('strict', '')</Features>
```
Looking at the code here, it looked like `/feature:strict=false` might work:
https://github.com/dotnet/roslyn/blob/f60facc9f40ddc40f85411372f5b8dde9dd5e3b4/src/Compilers/Core/Portable/InternalUtilities/CompilerOptionParseUtilities.cs#L35-L50

however the internal flag is set only by the presence of `strict` in the features dictionary, without regard to its value:
https://github.com/dotnet/roslyn/blob/8e22089fbb59f2d68c4a7b6b09f20fdd8de0e36e/src/Compilers/CSharp/Portable/Compilation/CSharpCompilation.cs#L164

**Expected Behavior**:

Allow features to be negated like ` /features:strict=false` or ` /features:strict-` or equivalent in MSBuild properties.

BTW `/features` is not documented in the output of `/?`

**Comment by gafter** [comment]
The `features` flag is unsupported, and anything it enables is also unsupported.

**Comment by danmosemsft** [comment]
Is it then unwise for corefx to use it? We have been bitten by shipping accidental comparison of an intptr with null.

**Comment by gafter** [comment]
@danmosemsft No, I believe it is a good idea to use it. It enables warnings that we cannot ship due to them being, technically, breaking changes. We expect to keep the `strict` flag, and even if we remove it there will not be an error when you use it (unrecognized features are ignored). When we add support for warning waves, I expect we will make the `strict` feature flag turn it on.

However, I do not expect that we will do anything to enhance the usability of the command-line flag or the project file for the feature flags, as requested in this issue.
