### ISSUE TITLE
[Feature Request]Metadata as Source: Turn AsyncStateMachine attribute into async keyword

### ISSUE THREAD

**Issue by diryboy** [dotnet/roslyn#28958]
**Version Used**: 
VS 15.7.5

**Steps to Reproduce**:

1. Create empty asp.net core app project
2. F12 for `Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware`

**Expected Behavior**:

The `Invoke` method uses `async` keyword and hide `AsyncStateMachine` attribute

**Actual Behavior**:
```C#
        [AsyncStateMachine(typeof(<Invoke>d__9))]
        public Task Invoke(HttpContext httpContext);
```

**Comment by CyrusNajmabadi** [comment]
> The Invoke method uses async keyword and hide AsyncStateMachine attribute

Note: hiding the attribute is reasonable.

However, we should not show the 'async' keyword.  It would improperly imply that 'async' somehow is part of the API signature for a method.  When really, it's just a construct used to allow you to use 'await' inside the body (which is of course not relevant here since this is Metadata-as-source and has no bodies).

From an API perspective, all that matters (or that you should be able to tell) is that this is 'Task' returning.  We shouldn't show one Task returning method as different from another just because of an implementation detail of how the original code was authored.

**Comment by diryboy** [comment]
Depends on how you interpret metadata-as-source, if you think it should be more loyal to the metadata, then hiding this attribute does not make sense. I've seen request about hiding interfaces not visible to the current project, it did not got pass.

The goal of this request was to make the generated code better looking but not miss out any useful information. My thought was, if we have language feature that compiles into some kind of metadata like that, why not use when decompiling. And, isn't that the exception behavior is different when you use the async keyword?

But I get your point, the dll might be produced by other compilers. I think the current behavior is good enough, so I'm closing this request.

**Comment by CyrusNajmabadi** [comment]
> The goal of this request was to make the generated code better looking but not miss out any useful information

Well, i'm all for removing information not actually relevant.  i.e. compiler synthesized attributes that don't reflect anything relevant to the user.  So i would still leave this issue open for that part :)
