### ISSUE TITLE
INavigateToSearchService filters wrong items

### ISSUE THREAD

**Issue by Therzok** [dotnet/roslyn#29031]
**Version Used**: 
2.9.0-beta8-63130-02

**Steps to Reproduce**:

have any kind of project with just this type defined:
```
class MyClass
{
    public MyClass() {}
}
```

Then use search service as follows:
```
// get a project

var searchService = proj.LanguageServices.GetService<INavigateToSearchService_RemoveInterfaceAboveAndRenameThisAfterInternalsVisibleToUsersUpdate> ();
if (searchService == null)
	return ImmutableArray<INavigateToSearchResult>.Empty;
var results1 =  await searchService.SearchProjectAsync (proj, "M", ImmutableHashSet.Create (NavigateToItemKind.Class), CancellationToken.None).ConfigureAwait (false);

var results2 = await searchService.SearchProjectAsync (proj, "My", searchService.KindsProvided, CancellationToken.None).ConfigureAwait (false);

// look at the results
``` 

**Expected Behavior**:
Results1 contains: MyClass - class
Results2 contains: MyClass - class, MyClass - constructor

**Actual Behavior**:
Results1 contains: MyClass - class
Results2 contains: MyClass - class

Seems that the previous cached results are filtered regardless of kinds change

**Comment by Therzok** [comment]
cc @KirillOsenkov @sharwell @CyrusNajmabadi @jinujoseph found via dogfooding new roslyn version in VSMac, it breaks our test suite and scenarios where you paste filters into the search box, for us being: `m:M` -> `My`

**Comment by sharwell** [comment]
The bug is in this cache:

https://github.com/dotnet/roslyn/blob/e2af9bfec5b4491223ae68140bdbbe15352331b2/src/Features/Core/Portable/NavigateTo/AbstractNavigateToSearchService.InProcess.cs#L23-L24

**Comment by Therzok** [comment]
One of the problems with _not_ having the cache is that searching in huge projects becomes _horrendously_ slow, up to the point it takes 6-8 seconds to get the first results in (last I checked). We did not having the IProjectHostCacheService in place back then, so that might've been a cause, but still.

Maybe the pattern matcher is being too quick to discard some results if fuzzy matching will actually yield more with more keypresses?

**Comment by CyrusNajmabadi** [comment]
> One of the problems with not having the cache is that searching in huge projects becomes horrendously slow, up to the point it takes 6-8 seconds to get the first results in (last I checked). We did not having the IProjectHostCacheService in place back then, so that might've been a cause, but still.

Why don't we just fix the perf... ? :)   Do you have a trace specifying what the problem is?

Adding a cache is fine if it doesn't violate correctness.  That isn't hte case here.  So i think the cache should go up until we can provide a correct one.

> Maybe the pattern matcher is being too quick to discard some results if fuzzy matching will actually yield more with more keypresses?

I don't know what that means.  :)    If we don't discard, then you will get non relevant matches.  With fuzzy matching, there just simply isn't a principle that a prefix of a pattern will produce a superset of the pattern's matches.

**Comment by CyrusNajmabadi** [comment]
> up to the point it takes 6-8 seconds to get the first results in (last I checked)

FYI, the cache would never help here.  Your first set of results should always effectively take the same amount of time.  The only thing the cache helps with is once hte results are there and you then continue typing.  In that case, you could still show the same results in place up until the new results came in.  

Those new results should stream in when found.  

--

Note: we could also use the cache to *augment* the results. IN other words, we would use the cache to quickly filter things down, but we would still do the full search to find the true results.

**Comment by Therzok** [comment]
I'll try to get a trace and we can discuss what's going on hands-on.

One of the things we used to have is a rank+match matcher. What that entailed is that a given fuzzy search pattern "abc" would always match words with "abc" in the name, but [ranking was also taken into account for a given match](https://github.com/mono/monodevelop/blob/c7b8957162b960b786d3c4cbb01371589ad725f0/main/src/core/MonoDevelop.Core/MonoDevelop.Core.Text/LaneStringMatcher.cs#L54-L76). So that means we could always reuse the previous fuzzy match, but we'd have different ranking on every keypress.

That way we could keep the results returned by the previous result and only stream back N results, depending on how many the API user actually wanted, sorted by the match rank.

**Comment by Therzok** [comment]
The optimization here is that fluent search patterns could reuse previous search results and trim the set of items passed for a match, and then ranking would be done on the current matched set.

**Comment by CyrusNajmabadi** [comment]
> The optimization here is that fluent search patterns 

What is a 'fluent search pattern'

> could reuse previous search results and trim the set of items passed for a match, and then ranking would be done on the current matched set.

So that's how the current system *does* work.  Except, as i mentioned above, such an algorithm isn't legal.  It presumes that you can take the previous search results and trim them down to get the current search results.  That isn't a valid thing that can be done because not all results of a larger search pattern will have been returned from the search of the prefix of that pattern.

**Comment by CyrusNajmabadi** [comment]
> One of the things we used to have is a rank+match matcher. What that entailed is that a given fuzzy search pattern "abc" would always match words with "abc" in the name, but ranking was also taken into account for a given match. So that means we could always reuse the previous fuzzy match, but we'd have different ranking on every keypress.

That's how the system already works.  but tha'ts not a *fuzzy* match.That's just a general "exact/prefix/substring match".  We *can* reuse those matches.   :)  

 But that doesn't work for *actually fuzzy* matches.  A fuzzy match is when the match happens, taking into account things like edit-distances.  this means characters can be missing, transposed, replaced, or deleted.  When you have a short search string, and a large string to match against, the edit distance is simply so large that these items will not be included.  Or, if they were included, you'd effectively have to return the entire search space because there could be a chance that those strings would later on be viable matches once the user had entered more of a search term.

**Comment by CyrusNajmabadi** [comment]
Note: to reiterate, this is why the cache effectively becomes ineffective:

>  Or, if they were included, you'd effectively have to return the entire search space because there could be a chance that those strings would later on be viable matches once the user had entered more of a search term.

If you're returning the entire search space, just because it might later result in a match... then you might as well just do the entire search all over again.  Because you're always searching everything.

--

Note: as i mentioned before, caching the results and trimming them *does* work for exact/prefix/substring matches.  We could consider caching those values and performing that optimization.  The fuzzy match portion though woudl always have to be done across the entire search space.  The only way we could potentially avoid that is if someone found some way to find a correspondance between the previous search with the previous pattern and the current search and the current pattern.  If such a correspondence could be found, then we could try to optimize around that.  However, i'm unaware of any such correspondences.  (but that is just general ignorance on my part.  one may be staring me in the face, i'm just not aware of it).

**Comment by Therzok** [comment]
The problem was passing over an empty filter for the service, and that made the results not come in properly. Fixed on our side.
