### ISSUE TITLE
Re-use SourceText and SyntaxTree for files in multiple projects when possible

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#29062]
Source files can be included in multiple projects:

* Through multi-targeting in SDK-Style projects
* By being in a Shared Project referenced by multiple projects
* By being linked into multiple projects

Today in Roslyn, these files share the same `SourceText` if and only if the file is open in the editor.  If not, we'll read the file from disk multiple times, store it in temporary storage multiple times etc.

Additionally, we'll create a distinct `SyntaxTree` object for each context, even though that's often not necessary.
 
We should:
1. Re-use the same `TextLoader` in the closed file case.
2. Re-use the same `SyntaxTree` if:
2.1. The `Project`s have identical `ParseOptions`, *or*
2.2. The `ParseOptions` differ only in the set of preprocessor defines, and the file doesn't contain any `#if` or `Conditional` methods (heuristically based on a simple text check).

**Comment by Pilchie** [comment]
FYI @sharwell @jasonmalinowski @jinujoseph

**Comment by jasonmalinowski** [comment]
2 is interesting, because of this API:

https://github.com/dotnet/roslyn/blob/ab82586f39106934edd95e71b703f1fad6e92b07/src/Workspaces/Core/Portable/Workspace/Solution/Solution.cs#L135

Because there's a bunch of places where we get a syntax tree (say walking around Compilations) and we need to go back to the document. Astute observers will note we also have an API for finding a syntax tree _in a project_ which nobody actually uses (and seems oddly implemented.)

**Comment by CyrusNajmabadi** [comment]
Closing out as not actionable for now.  It's unclear if htere's a scenario this will help with, and there are problematic api issues here.
