### ISSUE TITLE
Developer mode design document

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#29123]
🚧 This is a work-in-progress design document for the "developer mode" feature.

## Summary

The "developer mode" feature involves the addition of three distinct modes to the IDE (names subject to change):

1. **Focus mode:** Intended for writing new code
2. **Developer mode:** Intended for day-to-day development
3. **Review mode:** Intended for reviewing code as part of team development

|  | Focus | Developer | Review |
| --- | --- | --- | --- |
| Compiler errors | ✔️ | ✔️ | ✔️ |
| Compiler warnings | | ✔️ | ✔️ |
| Follow "treat warnings as errors" | | | ✔️ |
| Run analyzers | Forced Hidden ("refactoring only") | ✔️ | ✔️ |
| Scroll bar indicators | Errors only | Warnings and Errors only | ✔️ |

## Changing modes

I do not have a specific proposal for changing modes. However, it's important to keep in mind that some users will prefer to always work in one specific mode.

**Comment by mikadumont** [comment]
The platform team recently created a prototype to display a streamlined UI that maximizes the files that the user is working in and minimizes distractions. The feature will be available as a command in the View Menu near Full Screen or via the **Shift + Alt + f** keyboard shortcut. 

**The default values for Focus Mode’s options are**:

•	Error, Warning, Suggestion underlines suppressed 
•	QuickInfo suppressed 
•	Quick Actions margin suppressed 
•	Completion List suppressed 
•	Focused debugging will be disabled 
•	All of the panels besides the editor will be hidden

![image](https://user-images.githubusercontent.com/46729679/93801622-1d94b400-fbf7-11ea-8324-49866ed2baa0.png)

**Customization**:

![image](https://user-images.githubusercontent.com/46729679/93801645-26858580-fbf7-11ea-9a70-f43fac632797.png)

![image](https://user-images.githubusercontent.com/46729679/93801656-2be2d000-fbf7-11ea-85c2-5e908e7a549b.png)

**Comment by CyrusNajmabadi** [comment]
I don't like the terminology "and boost productivity".  That feels very biased towards a certain type of development mentality.

**Comment by CyrusNajmabadi** [comment]
I'm ok with most of hte things that will be hidden.  However, i do want clarification on if every single one of those things will have a way to enable if that's what works best for a particular user.  

A few more thoughts:

![image](https://user-images.githubusercontent.com/4564579/93803849-4cf8f000-fbfa-11ea-944f-aa8c161d0441.png)

This seems odd.  I feel like if users take an explicit action (like hovering over something), then showing them information is appropriate.  

Having the error list *and* squiggles not be shown seems like a very strong direction to go in.  Do we have indications that customers want things suppressed to that extent?

**Comment by mikadumont** [comment]
> I don't like the terminology "and boost productivity". That feels very biased towards a certain type of development mentality. It also is effectively flat out stating that our featureset negatively hampers productivity. I would just phrase this in terms of allowing users to pick the set of features they prefer to have as part of their default workflow.

I agree and can create a ticket for platform team to change.

**Comment by mikadumont** [comment]
> 1. I'm ok with most of hte things that will be hidden.  However, i do want clarification on if every single one of those things will have a way to enable if that's what works best for a particular user.

Currently there isnt a way to configure some of these while other editors such as VS Code allows you to and think we should offer that option to as well. 

We should provide the option to configure the following: 

- activity bar
- status bars
- tabs
- notifications
- toolbars
- tool window bars
- navigation bar
- main menu 

> 2. ![image](https://user-images.githubusercontent.com/4564579/93803849-4cf8f000-fbfa-11ea-944f-aa8c161d0441.png)
> 
> This seems odd. I feel like if users take an explicit action (like hovering over something), then showing them information is appropriate.

There is an option to enable this if you select QuickInfo tooltips then tooltips will be shown during focus mode.

> 1. Having the error list _and_ squiggles not be shown seems like a very strong direction to go in.  Do we have indications that customers want things suppressed to that extent?

We can change that and use Sam's proposal to show compiler errors at the very least. The indicator drop down lets you customize the diagnostics being shown. There is data from the platform team on the customization story to determine the default state of their feature. I have received feedback on Quick Info Tool Tips, Signature Help, Lightbulbs, and Screwdriver being distractions but not for compiler errors. 

> 2. Should code-lens be here as somethign easy to disable?

That would be a good option even though they have their own settings option.

> 3. What is 'focused debugging'?

Not sure what focused debugging is either.

**Comment by CyrusNajmabadi** [comment]
> There is an option to enable this if you select QuickInfo tooltips then tooltips will be shown during focus mode.

I guess my point is: this is already a feature you do not see by default.  so why does it need to be 'disabled'.  I think the only things that should be disable-able would be things that present UI to the users as part of the default editing experience.

**Comment by CyrusNajmabadi** [comment]
> Configurable options:

That sounds good.  The UI doesn't seem to reflect that, but i'm glad to have the clarification.

**Comment by CyrusNajmabadi** [comment]
Note: this feels worthwhile to have a dedicated status bar button to trivially enable focus mode and/or these sub options.  Specifically i do *not* feel like this shoudl go into tools|options, but should rather be a flyout on the status bar you can click to *really* quickly enable/disable any of these options with just two-clicks (one to open the flyout, one to enable/disable the feature).

Having to jump to/from these different contexts if the very poster child of focus-disrupting :)

**Comment by CyrusNajmabadi** [comment]
> Currently there isnt a way to configure some of these

IMO, that's just broken.  Focus-mode shoudl not be someone else telling me: here's how you focus.  It should be me telling teh product "here is what i find relevant enough to my effectiveness to be visible by default".

**Comment by CyrusNajmabadi** [comment]
> We can change that and use Sam's proposal to show compiler errors at the very least. 

I think that's sensible.  It can always be someone can turn the knob one dial further on if they don't even want squiggles.

**Comment by mikadumont** [comment]
> Note: this feels worthwhile to have a dedicated status bar button to trivially enable focus mode and/or these sub options. Specifically i do _not_ feel like this shoudl go into tools|options, but should rather be a flyout on the status bar you can click to _really_ quickly enable/disable any of these options with just two-clicks (one to open the flyout, one to enable/disable the feature).
> 
> Having to jump to/from these different contexts if the very poster child of focus-disrupting :)

There is a keyboard shortcut to enable/disable focus mode and you can enable it by searching for focus mode in Ctrl+Q search and select focus mode. If we create a status bar option it can have a flyout to enable/disable and to configure. 

![image](https://user-images.githubusercontent.com/46729679/93810704-e1b41b80-fc03-11ea-98c7-69dbfe9dfce1.png)

**Comment by mikadumont** [comment]
> > Currently there isnt a way to configure some of these
> 
> IMO, that's just broken. Focus-mode shoudl not be someone else telling me: here's how you focus. It should be me telling teh product "here is what i find relevant enough to my effectiveness to be visible by default".

I agree!

**Comment by mikadumont** [comment]
@CyrusNajmabadi Below are updates to the configuration page and the default behavior should show compiler errors:

![image](https://user-images.githubusercontent.com/46729679/93812410-6acc5200-fc06-11ea-8baa-1cac10a7ea9e.png)

Also, shouldnt the behavior be the opposite and what ever I check off I would like to get applied to my customized focus mode settings and not vice versa?

**Comment by gundermanc** [comment]
FWIW, I think the concepts outlined in the 'Developer Mode(s)' proposal above offer quite a bit more value and nuance than the existing Focus Mode prototype. Instead of tailoring to just minimizing distractions, you have fit-to-purpose modes that emphasize certain important features while de-emphasizing others.

Before settling on anything that's already built I'd like to see us iterate a bit more on the Developer Mode(s).

At least from my perspective as a VS user, they seem particularly compelling

**Comment by CyrusNajmabadi** [comment]
> If we create a status bar option it can have a flyout to enable/disable and to configure.

👍 

I think whatever we have in `tools|options` should just show up in the flyout.   :)

**Comment by CyrusNajmabadi** [comment]
> Also, shouldnt the behavior be the opposite? so whatever I check off I would expect it to be hidden and not vice versa?

Sure :)  we should probably wordsmith things then so it would be like:

- [ ] Hide quickinfo tooltips
- [ ] Hide codelens

That way you know if it's checked that the thing is hidden.

**Comment by CyrusNajmabadi** [comment]
> I'd like to see us iterate a bit more on the Developer Mode(s) concept.

What are "developer modes"?

**Comment by gundermanc** [comment]
>What are "developer modes"?

It's in the description of the issue :)

> Focus | Developer | Review

The idea is there's a bigger set of problems to solve here than just Focus Mode.

**Comment by mikadumont** [comment]
We currently have a prototype for Focus Mode for code analysis: 

![FocusModeDemo](https://user-images.githubusercontent.com/46729679/180345229-b2cdcf02-01b7-460e-9215-f93afd17e75f.gif)

We plan to create a Tools Options page which allows the user to check off the options that they would like to hide when they are in Focus Mode. The keyboard shortcut to toggle Focus Mode will be Ctrl+K+Z (same shortcut as VS Code): 

![image](https://user-images.githubusercontent.com/46729679/180345550-f7245c09-5eef-49e8-b6cf-1de129564b96.png)

As an MVP we would like to ship the first 6 options with the following defaults:
- Hide Diagnostic Errors (unchecked by default)
- Hide Diagnostic Warnings (checked by default)
- Hide Diagnostic Suggestions (checked by default) 
- Hide Quick Info (checked by default)
- Hide Quick Actions LightBulb (checked by default)
- Hide Inheritance Margin (checked by default)

Eventually we should see about adding an option to easily access/configure Focus Mode from the status bar to help with discoverability:
![image](https://user-images.githubusercontent.com/46729679/180347506-950cbd37-328c-4c97-8535-32c76dfee67f.png)

**Comment by mavasani** [comment]
@mikadumont I have couple of open issues that we should discuss at the design meeting:

1. **Lightbulb experience**: I think we all have clarity for this, but I just wanted to restate my understanding and confirm the desired experience:
    
   1. _When Focus mode is enabled, `Show Quick Actions LightBulb` checkbox only determines whether or not the lightbulb/screwdriver will automatically show via background analysis (both in the gutter and right under the cursor). However, when user presses Ctrl + Dot, lightbulb menu still shows up with exactly the same quick actions as would show up when Focus menu is disabled, regardless of whether `Show Quick Actions LightBulb` is checked or unchecked._

   2. _Additionally, even if any of the `Show Diagnostic Errors`, `Show Diagnostic Warnings` or `Show Diagnostic Suggestions` checkboxes are unchecked, we will still show all potential code fixes for all errors, warnings and suggestions that exist on that line, even if there are no squiggles or three dots. Basically, unchecking any of the diagnostic related checkboxes in Focus mode has no effect on lightbulb experience, it just forces the effective severity of those diagnostics to be `Hidden`, so we can still continue showing all the corresponding code fixes._

   Can we please confirm if this matches the desired experience?

2. **Error list experience for Build diagnostics**: In the experience originally proposed by Mika, error list contents would match the squiggles/three dots experience, i.e. by default only errors show up and warnings and suggestions are not displayed in the error list. However, this poses an experience concern when user invokes a build that reports errors and warnings. Users would expect that the Error list's content after build matches the Output window, but if Focus mode is enabled and `Show Diagnostic Errors` OR `Show Diagnostic Warnings` is unchecked, we would be filtering those out from error list in live analysis. This would confuse the users into thinking their build is clean when it is not. I can think of couple of options here to address this, but would like to get more opinions and feedback:
   1. Keep the desired design so the Error list respects Focus mode diagnostics related checkboxes and matches the editor squiggles, i.e. only shows errors by default. When the user does an explicit Build/Rebuild and Focus mode is enabled, such that either `Show Diagnostic Errors` or `Show Diagnostic Warnings` is unchecked, show a dialog box stating that as Focus mode is enabled, some errors/warnings from Build will not show in the Error list in `Build + IntelliSense` and `IntelliSense Only` modes. Users would need to explicitly switch to `Build Only` mode to view errors and warnings from the last build. IMO, dialog box should have a `Configure Focus Mode here` with a hyperlink that opens up the Focus mode options page and also a checkbox `Do not show this message again`.

   2. Do not alter the Error list experience with Focus mode, and instead just hide the Error list when user enables Focus mode to avoid distractions. Error list will always show all errors, warnings and suggestions in Focus mode, and the existing build/live diagnostics de-duping logic and user experience will be retained. We already have severity based filters in Error list so users can toggle whether or not they want to see Errors, Warnings and Messages:
       ![MicrosoftTeams-image](https://user-images.githubusercontent.com/10605811/180698642-20709056-f5c9-41d2-935a-a5704e7f9550.png)
       This way we allow the users to view their Build errors and warnings, and also keep the Editor squiggles and Error list in sync while typing in Focus mode.

   Note that it won't be a good experience to show errors/warnings from Build in the Error list, while hiding errors/warnings from intellisense in `Build + IntelliSense` and `IntelliSense Only` modes, because as soon as user starts typing in the file with errors/warnings from the build, these diagnostics will go stale as we don't update them from intellisense.

**Comment by Bosch-Eli-Black** [comment]
Excited to see movement on this 🙂

I know it's off topic, but I think one of the top things that would let me focus better in VS is if this were fixed: https://developercommunity.visualstudio.com/t/Cannot-permanently-disable-outlining/408289?space=8&scope=follow&stateGroup=active 😄

**Comment by jmarolf** [comment]
## Discussion

- Will this be a Visual Studio platform feature?
  - Yes eventually, but we want to have something that works end-to-end before we work on shipping an API
- Will there be a public extensibility point that anyone can plug into?
  - likely not when we first ship, though folks will undoubtedly ask for it and we'll want it eventually. We should design as though that is going to be the case.
  - If this is expected to be an extensibility point then we need to involve other language teams to ensure it meets their needs.
- What should the initial set of features be?
  - It's likely that everyone will have their own opinions on this. We may want to dogfood this feature internally to ensure we are happy with it first. It's likely that whatever we do, the design will change once going into public preview.
- Lightbulb and error list behavior
  - Agree with @mavasani's details, we don't want to modify the set in the error list or change what appears when the lightbulb is invoked.
- Public API
  - Should be able to register a set of options that appear in Tools -> Options 
  - The editor should call into whomever registered their options when we switch to "focus mode"
  - It is the responsibility of the feature to determine how to enable/disable itself based on the given options

## Next Steps

- Work to ship an api from the Visual Studio platform and consume it in the roslyn repository.
- Engage partner teams to ensure the api also meets their needs.
- Consider internal dogfooding to see which set of options we want to ship with initially.

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of movement.  If this is something we want to invest in, we should ensure we have partners lined up and a proper schedules we will do this in.
