### ISSUE TITLE
Debugging unhandled exceptions does not work well with async Main

### ISSUE THREAD

**Issue by svick** [dotnet/roslyn#29143]
**Version Used**: VS 15.7.6

When I have an unhandled exception in a regular `void Main` method, everything works as it should: I can see the call stack, the code is stopped at a reasonable point, etc.:

![](https://user-images.githubusercontent.com/287848/43793692-9a27db84-9a7c-11e8-83d1-83bcea28892a.png)

But when the same thing happens with `async Task Main`, it's much worse: call stack offers no useful information, the code isn't stopped in my code, etc.:

![](https://user-images.githubusercontent.com/287848/43793794-db025292-9a7c-11e8-8260-a562bcc20e91.png)

The code I used is:

```c#
using System;
using System.Threading.Tasks;

class Program
{
    static async Task Main()
    {
        throw new Exception();
    }
}
```

Note that I'm specifically talking about what happens with unhandled exceptions. If "Break When Thrown" is set, it works well in both cases.

There's a good chance this is not the right repo for this issue. If that's the case, feel free to move it as appropriate.

**Comment by tmat** [comment]
The exception is caught in compiler-generated catch within the async method body and stored on the Task object. The generated `<Main>` method then calls `Task.GetResult()`, which re-throws the exception. At this point the stack does not have any user method on it, so the debugger shows no source code.

@chuckries @gregg-miskelly Any ideas how can we improve the experience?

**Comment by gregg-miskelly** [comment]
This is a general problem with any user method which is `async Task` (as opposed to `async void`) -- the debugger doesn't know that the exception is logically user-unhandled and therefore it should stop on it by default.

In the case of 'Main' this seems like something that could be fixed by checking if the method token is the entry point token in the PDB. If the compiler knows of other methods where we would want to stop by default, we would probably need to invent a new custom attribute to communicate this. 

Thoughts?

In terms of improving the experience when the debugger doesn't stopped until the exception is unhandled -- we do have some things being considered in this area for Dev16.

**Comment by gregg-miskelly** [comment]
To fix this problem, we need the compiler to emit catch block offset debug info for 'main' in addition to `async void` methods. 

Relevant code: http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/Compiler/MethodCompiler.cs,1411

**Comment by jcouv** [comment]
I'll take a look when I get back. I think I understand what's needed. Thanks for the details

**Comment by jcouv** [comment]
Fix merged for dev16.2p1
