### ISSUE TITLE
Revert "latest" and "default" and add "beta" tag

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#29150]
- [x] We need to have "default" = 7.0 (~~or 7.3?~~) and "latest" = 7.3.
- [ ] ~~We should still allow an explicit selection of "8.0-beta".~~ (we stuck with "8.0")
- [x] project-system change to display "8.0" and "beta" https://github.com/dotnet/project-system/pull/4091

Note the project-system change (https://github.com/dotnet/project-system/issues/3569) will also need to include a beta label.

**Comment by gafter** [comment]
Unfortunately, this change will prevent us from being able to try new features in https://sharplab.io/

**Comment by jcouv** [comment]
This can be solved by making a feature branch (`features/compiler` for instance) where the default is 8.0.

**Comment by gafter** [comment]
In what branch are you proposing to make the change that is the subject of this issue?

**Comment by jcouv** [comment]
I'm not sure yet. It will likely be `master`, or maybe `features/compiler` depending on the timing.

**Comment by svick** [comment]
As far as I can tell, [the code SharpLab uses to select `LanguageVersion`](https://github.com/ashmind/SharpLab/blob/ba53ad15d1a203e514e26036c2dcd127255d4cff/source/Server/Common/Languages/CSharpAdapter.cs#L24-L27) is: `Enum.GetValues(typeof (LanguageVersion)).Cast<LanguageVersion>().Max()`. That will always select `Latest`, since its value is `int.MaxValue`.

I assume it wouldn't be an issue for @ashmind to change that logic to e.g. `Enum.GetValues(typeof (LanguageVersion)).Cast<LanguageVersion>().Where(v => v != LanguageVersion.Latest).Max()`, or any other code required to get `LanguageVersion` of the latest beta version for the current branch, if there is one.

(Note that it's possible I don't fully understand what this issue is about.)

**Comment by jcouv** [comment]
The PR for project-system is in review. I'll go ahead and close this tracking issue.
