### ISSUE TITLE
Have to select an entire property/field body before you can generate a constructor from it

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#29195]
You have to be too precise to generate a constructor, you need to select all of a properties/fields body before you are offered to ability to generate a constructor that initializes it.

I ran into this while doing a talk, and so did Allison from the platform team: https://youtu.be/6ozHCNVmrcw?t=3766.

1. Place cursor anywhere within Foo

``` C#
        public int Foo
        {
            get;
        }
```

Expected: To be offered to create a constructor

Actual:
Not offered.

To be offered to create a constructor, you need to select the entire property as indicated by the $:

``` C#
        $public int Foo
        {
            get;
        }$
```

**Comment by CyrusNajmabadi** [comment]
Note: while i agree you shouldn't have to select the entire property... i'm wary of offering to generate a constructor just because you're anywhere *on* a property.  I think it's acceptable to have zones of non-offering.  These zones should generally be picked both to prevent offering too much all of the time, and also to not overload the user in areas where it's unlikely for them to want that feature.

For a feature like Generate-Constructor, i could see offering the feature if you're on a field/prop name.  This helps clearly indicate that you're choosing "the symbol" to generate from.  However, it's less clear to me that offering this is sensible if you're *inside* the accessor list.  For example, say you had:

```c#
public int Foo
{
    [$$SomeAttribute]get;
}
```
Does the user go to that location thinking: "i have chosen the property, and would like to generate an initializing constructor from here."?

IMO, more often than not (with the above example), the answer would be 'no'.  

--

So, i woudl start by relaxing 'generate constructor' to work when the user was on (or had selected) just a field/prop name.

**Comment by chborl** [comment]
Fixed by https://github.com/dotnet/roslyn/pull/33606
