### ISSUE TITLE
Don't get offered to generate a constructor if a property has only a getter

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#29198]
Ran into this doing a talk.

While this is "correct", it was unexpected - I'd prefer you to generate invalid code with a squiggle in the constructor due to the missing setter:

1. Highlight the following:

``` C#
    class Program
    {
        private int _value;

        $public int Foo
        {
            get { return _value; }
        }$
    }
```

Expected: 
To get offered to generate a constructor
![image](https://user-images.githubusercontent.com/1103906/43941356-2402dc0a-9cb7-11e8-8950-2f79fbabc4cb.png)

Actual:
Am not offerred
![image](https://user-images.githubusercontent.com/1103906/43941374-3d46ad2c-9cb7-11e8-983b-90b27c47b10f.png)

**Comment by CyrusNajmabadi** [comment]
Interesting.  This is one of those hard to decide areas.  In general, many features have a *lot* of of checks they do to limit when they will be shown.  This is both to prevent overloading people with a ton of options showing up all the time, and also because people often complain when a feature is offered that doesn't smartly recognize when things would be broken.

I'm on the fence with this one.  I think the behavior is pretty reasonable here.  But i can see the perspective of someone saying: 

> this is just hte current state of my class.  These fields/prop define the general shape of it.  And i want to generate a constructor from that shape.   I'll figure out later how to actually make this property properly work for that.

**Comment by sharwell** [comment]
I might expect to see this constructor:

```csharp
public Program(int foo)
{
  _value = foo;
}
```

**Comment by dpoeschl** [comment]
Design Meeting Notes:

Let's recognize this pattern and use @sharwell's suggestion when we encounter it.
