### ISSUE TITLE
[Regression] Completion window does not show until you stop typing

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#29265]
This has regressed between 15.7 -> 15.8.

In 15.8, you now need to stop typing in certain circumstances before the completion window shows. This slows down my typing because previously I only needed type the prefix of the symbol and press TAB to enter the entire symbol. Now I have stop typing, wait for the completion window to show and then press TAB. I have no idea when or when I can stop typing because I don't know how many characters I need to disambiguate the symbol I'm interested in from the other symbols.

**15.7:**
![completion2](https://user-images.githubusercontent.com/1103906/44070888-a34152de-9fc9-11e8-87e2-e06bfb955134.gif)

**15.8:**
![completion](https://user-images.githubusercontent.com/1103906/44070887-a12c5fac-9fc9-11e8-9ea7-3d4123258c56.gif)

If this is by design, please an option to bring back previous behavior.

**Comment by dpoeschl** [comment]
@davkean This shouldn't be happening _at all_, but it could be caused by one of the new completion experiences if you're using/dogfooding them. E.g.:

1. The new Async Completion experience? An easy way to be sure is the filter icons at the bottom -- in new completion, they'll gray out as you type and the set of kinds available in the list decreases (your gifs cut off such that I can't check).
2. IntelliCode, which determines ★ items and puts them at the top of the list (but only after `.`, like `double x = Math.$$`)

If it's one of those, we can talk to the teams involved and do some targeted investigations. If not, I don't know of anything that changed here in 15.7 --> 15.8 and would have to investigate further.

**Comment by davkean** [comment]
Don't have IntelliCode installed, this is what my completion window looks like:

![image](https://user-images.githubusercontent.com/1103906/44121527-bf826380-a063-11e8-9b84-e97a4b45b5ef.png)

**Comment by jinujoseph** [comment]
@ivanbasov  can you test this with latest build

**Comment by ivanbasov** [comment]
Checked this scenario with both existing and new completions: both work fine. Completion window shows during typing. No stop is required.
