### ISSUE TITLE
Show the quick action to implement an interface explicitly even if already implemented implicitly

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/roslyn#29348]
One of the reasons to implement an interface explicitly is to have a different implementation for member with the same signature from another implemented interface.

For members shared with other interfaces the refactoring should generate new explicit implementing members. Members that are not shared should be converted to explicit implementations.

```C#
public interface IA
{
    void Shared();
    void AMethod();
}

public interface IB
{
    void Shared();
    void BMethod();
}

public class AB : IA, IB
{
    public void AMethod()
    {
    }

    public void BMethod()
    {
    }

    public void Shared()
    {
    }
}
```

Running the refactoring on IB would result in
```C#
public class AB : IA, IB
{
    public void AMethod()
    {
    }

    void IB.BMethod()
    {
    }

    public void Shared()
    {
    }

    void IB.Shared()
    {
        throw new System.NotImplementedException();
    }
}
```

**Comment by CyrusNajmabadi** [comment]
I'm wary about this.  It feels like it could lead to confusion because people would see the lightbulb light, see this option, and go "well... i guess i didn't actually implement it....".  

If we did this, i think i'd want the feature to have some way of indicating that your code was fine, but this was just if you happened to eb in this rarer state where you had properly implemented the interface, but still wanted to do things explicitly.

--

Note: one of things we did more than a decade ago (based on strong user feedback) was to make 'implement explicitly' much smarter.  Specifically, it does not reeimplement any members that are already implemented in some form (including implicitly).  So this would essentially be a feature request for the feature to have some way to *stop* doing that so that reimplementation happened.

**Comment by AndriySvyryd** [comment]
@CyrusNajmabadi I don't think there would be confusion as there would be no squiggles or other indicators that something might be wrong, the lightbulb would only appear when caret is placed on the interface identifier.

> Specifically, it does not reeimplement any members that are already implemented in some form (including implicitly)

This behavior changed at some point. Doing it on
```C#
public class AB : IA, IB
{
    public void AMethod()
    {
    }

    public void Shared()
    {
    }
}
```
results in
```C#
public class AB : IA, IB
{
    public void AMethod()
    {
    }

    public void Shared()
    {
    }

    void IB.BMethod()
    {
        throw new System.NotImplementedException();
    }

    void IB.Shared()
    {
        throw new System.NotImplementedException();
    }
}
```

**Comment by CyrusNajmabadi** [comment]
> @CyrusNajmabadi I don't think there would be confusion as there would be no squiggles or other indicators that something might be wrong, the lightbulb would only appear when caret is placed on the interface identifier.

Right. But we've seen people go: oh.... the thingy on the left has appeared, i guess it's telling me to do something :)

Just something we need to be careful of.  In general, when we have offered somethign, it's been clear that's it's been an optional transformation.  Now, we're effectively providing a code-gen feature, which has only ever been offered to fix a problem.  There is the potential for confusion.

> This behavior changed at some point.

Well that does make things easier then :)

**Comment by CyrusNajmabadi** [comment]
it may be as simple as having the text say: "Re-implement explicitly".

**Comment by CyrusNajmabadi** [comment]
@jinujoseph @sharwell would like to bring this to review.  I don't think this is worthwhile.  It's a single request, and it's not a common enough scenario to 'win' space in lightbulb.

**Comment by kendrahavens** [comment]
Design meeting update:
We'd like more data (votes or comments) to verify this should be the default behavior. 
**Please note:** Since we aren't sure most users would want this instead of making a PR to this repo we would encourage users to create a refactoring extension (vsix) that would ship separately from the analyzers included in the compiler by default.

**Comment by sharwell** [comment]
As an addition to https://github.com/dotnet/roslyn/issues/29348#issuecomment-598484159, if you are a user that would find this feature helpful, it would be helpful to include detailed descriptions of the scenario(s)/workflow(s) (with code to demonstrate) that would be improved by this.

**Comment by CyrusNajmabadi** [comment]
Closing out as won't-fix.
