### ISSUE TITLE
Dynamics disabling Deterministic behavior of generics return type

### ISSUE THREAD

**Issue by Jlalond** [dotnet/roslyn#29342]
So I have an interesting scenario below that I found by pure curiosity.

~~~~~
    public class Program
    {
        public static void Main(string[] args)
        {
            dynamic thing = new List<Exception>();
            SqlCompareOptions otherVariable = ConvertTo<IEnumerable<Exception>>(thing);

            Console.WriteLine(otherVariable.GetType());
        }

        private static T ConvertTo<T>(object thing)
        {
            return (T) thing;
        }
    }
~~~~~

In the above program, we declare a variable as a dynamic. I understand this should turn off static type analysis for said variable by the compiler. Yet where I believe there might be a problem is the fact that the return type of a generic method isn't evaluated. I recall that generics are deterministic in their return type, and are some of the cornerstone features of a strong typed language. Thus suddenly not evaluating the variable declaration compared to the return type of the generic seems off to me.

This might be exactly what the compiler is supposed to do, and if so, I apologize for not researching hard enough, but I haven't found any reference material on the above scenario. So I wanted to get the Roslyn's teams thoughts.

One final point of clarity, the above does throw a run time exception of cannot implicitly convert.

First Issue! This is cool stuff.

**Comment by gafter** [comment]
When an argument to a method call is `dynamic`, you're performing a dynamic invocation. In that case the return type of the invocation is `dynamic`. In your code, you are therefore assigning a `dynamic` to `SqlCompareOptions`. Since the type of the thing being converted is, at runtime, a `List<Exception>`, that will fail at runtime.

See https://github.com/dotnet/csharplang/blob/master/spec/expressions.md#static-and-dynamic-binding for more.
