### ISSUE TITLE
Wrong null check suggestion

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#29372]
The new refactoring system suggests to use an *is null* check here:

      var size = (AStruct)obj;
      if ((object)size == null)
        return false;

However, if I accept the suggestion, the code will have an error: &quot;Cannot convert null to AStruct because it is a non-nullable value type&quot;.

The suggestion is wrong here.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/312582/wrong-null-check-suggestion.html
VSTS ticketId: 664998_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by jinujoseph** [comment]
cc @CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
Interesting.  It's worth noting that this is actually helping identify a problem in the user's code.  They are doing a check that will effectively always be false.  It's just that the compiler can't tell given the form they used.  Once we simplify to the clearer form `size is null`, it's clear that something is very wrong, and you get the error.

So i'm someone amenable to the idea of not touching this and having this be a virtue of the system :)

**Comment by deakjahn** [comment]
Fair enough. However, this snippet came from the standard pattern of implementing an `IEqualityComparer`. Yes, in an `Equals()` override this simply means an extra conditional that's never active. Still, I'd be a bit afraid of suggesting to people that it should always be removed because if you happen to need to change the struct to a class later, well, you'll be hosed.

So, while you're technically right, I feel this particular snippet, being in an actively used pattern, is common enough to warrant some solution.

**Comment by CyrusNajmabadi** [comment]
> Fair enough. However, this snippet came from the standard pattern of implementing an IEqualityComparer. 

What standard pattern is that?  For structs, i wouldn't expect to ever see that.

> Still, I'd be a bit afraid of suggesting to people that it should always be removed because if you happen to need to change the struct to a class later, well, you'll be hosed.

This is always true for any sort of code change.  You need to make sure that your code is correct :)

>  being part of an actively used pattern,

I'm really not sure what pattern that would be though?  What pattern out there suggests that you cast your struct to object, then check it for null?  That's very much an anti-pattern, and I'm struggling to think who would be recommending that...

**Comment by deakjahn** [comment]
No, I didn't want to imply that there is a specific pattern for these structs. You just have the usual way of how you set up an `Equals()` in the general case: check for nullity of the operands first and only comparing the insides in the null checks pass. Without this specific suggestion, there is no harm at all if you leave the null checks in place even for structs because they don't do any harm, so I guess, many people will do it, anyway. So, in a sense, it would be more elegant to warn about that in the first place with a regular compiler warning than popping up an error after a transformation that's supposed to leave your code equivalent to what is was before. I don't think any code refactoring suggestion should be exposing errors that weren't there in the first place. If it does, it's not an equivalent transformation.

**Comment by CyrusNajmabadi** [comment]
> Without this specific suggestion, there is no harm at all if you leave the null checks in place even for structs because they don't do any harm

There is one harm. You are now boxing up your structs, leading to unnecessary allocations that pressure the GC :)

>  so I guess, many people will do it, anyway.

Definitely skeptical of that :)

> So, it would be more appropriate to warn about that in the first place with a regular compiler warning

That sounds like a great idea.  You might want to suggest that over at https://github.com/dotnet/roslyn-analyzers/ :)

>  I don't think any code refactoring suggestion should be creating errors that weren't there in the first place. If it does, it's not an equivalent transformation.

In general, i'm sympathetic to that view.  However, with code that is fairly broken, but the compiler was lenient about, i don't actually have a problem with things getting clearer and actually pointing out the problem.

**Comment by deakjahn** [comment]
You convinced me about the bulk of the issue but I still wonder whether you will need to adjust this approach slightly now that all these transformations can be done in bulk. Until now, when you did one at a time, you could count on any errors popping up to get immediate attention of the user. But if a single Format Document will now potentially perform hundreds of modifications and the result might be lots of new errors, suddenly appearing out of the blue, well, I don't know. I could argue both for and against. :-)

**Comment by CyrusNajmabadi** [comment]
@deakjahn Very good point! :)

**Comment by CyrusNajmabadi** [comment]
Closing out as we haven't heard about this from anywhere else, and the change does reveal a very real bug in the user's code.
