### ISSUE TITLE
VB: "Introduce local" refactoring should NOT add the 'Call' keyword to method calls.

### ISSUE THREAD

**Issue by ericmutta** [dotnet/roslyn#29485]
**Version Used**: 

Visual Studio Community 2017 v15.5.6

**Steps to Reproduce**:

Paste the following code into a VB console project:

```vb
Public Module Module1
  Public Class CBlah
    Public Sub Foo(ArgBleh As Integer)
    End Sub

    Public Sub Bar()
    End Sub
  End Class

  Public Sub Main()
    Dim lambda =
        Sub()
          Dim blah As New CBlah

          With blah
            .Foo(1 + 2 + 3)
            .Bar()
          End With
        End Sub
  End Sub
End Module
```

Highlight the expression `1 + 2 + 3` so you can invoke the "Introduce local" refactoring on it:

![vs_introduce_local_1](https://user-images.githubusercontent.com/20465797/44562296-a6636c00-a761-11e8-92b7-ec82339d3c25.png)

When you proceed with the refactoring, it does introduce the local, but for some reason, it also adds the `Call` keyword before the `.Foo(...)` and `.Bar()` method calls:

![vs_introduce_local_2](https://user-images.githubusercontent.com/20465797/44562505-913b0d00-a762-11e8-9c34-eef1d42fa5c8.png)

**Expected Behavior**:

The `Call` keyword is legacy VB and is completely optional (I haven't touched that keyword for over 18 years). The documentation even [recommends AGAINST it's use](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/statements/call-statement#remarks), so the "Introduce local refactoring" should NOT inject it.

This bug is particularly strange because it only triggers for code inside a `With` block which is inside a lambda. If you try "Introduce local" with this code:

```vb
  Public Sub NoProblemHere()
    Dim blah As New CBlah

    With blah
      .Foo(1 + 2 + 3)
      .Bar()
    End With
  End Sub
```

...the refactoring works WITHOUT trying to add the `Call` keyword before the `.Foo(...)` and `.Bar()` method calls:

![vs_introduce_local_3](https://user-images.githubusercontent.com/20465797/44562919-749fd480-a764-11e8-9d63-6cc91d7f2250.png)

**Comment by CyrusNajmabadi** [comment]
IN general, the reason this is added is because of a subsystem we call "expand/simplify".   We use this to help ensure that the meaning of code does not change when we refactor.  First we 'expand' which makes the statement ultra-explicit and does things to remove ambiguities and to make all type meaning clear.  Then, we simplify at the end, which causes us to try to remove as much of the expansion as we can (ideally all of it).  In this case something is causing us to think we can't/shouldn't remove the `call`s.  My *guess* is that it's the `.XXX` bits.  Our logic is probably concerned that if we remove the `call`s that there will be some sort of ambiguity and things like the `.Foo` will now get attached as a continuation to the `1 + 2 + 3` part.

Note: i'm not saying this behavior is correct, just that this is probably what's going on.

**Comment by CyrusNajmabadi** [comment]
Closing out as we are not changing these vb experiences.
