### ISSUE TITLE
Prefer braces does not support removing unnecessary braces

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#29606]
Gee, very welcome changes, it was really a pain to always change foreign code to my code style half-manually. Most of it seems to work all right but not removing extra braces around one-liners. I have the attached settings and neither suggestion nor refactoring seems to happen in simple cases like:

```csharp
if (args.MarginSizeChanged) {
  page.MarginSize = args.MarginSize;
}
```

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/311544/prefer-braces-not-working.html
VSTS ticketId: 664398_
_These are the original issue comments:_

Gábor Deák Jahn on 8/15/2018, 05:24 AM (15 days ago): <p><img src="https://developercommunity.visualstudio.com/storage/temp/37350-untitled-1.png"></p><p>I did attach a screenshot... Well, here it is again.</p>

Gábor Deák Jahn on 8/15/2018, 05:30 AM (15 days ago): <p>Addendum, this might be relevant: in other cases, changing the Preference mostly (but not always) changes the illustrative example below. In the case of Prefer braces, the example always stays the same, preferring braces, no matter whether I set it to Yes or No.</p>

Gábor Deák Jahn on 8/15/2018, 05:48 AM (15 days ago): <p>Just one more thing, Lieutenant. Could just as well be linked. If I ask for an Invert If, the branches are swapped all right but I get braces around the *then* branch. With Prefer braces still set to No.</p>

Alexander Seeck on 8/29/2018, 06:09 AM (35 hours ago): I just wanted to report the same issue. Glad someone did that already
_These are the original issue solutions:_
(no solutions)

**Comment by Alexees** [comment]
@jinujoseph just wanted to know how this is a feature request instead of a bug now?

**Comment by CyrusNajmabadi** [comment]
@Alexees It is a feature request because the product is currently working as intended.  There is no feature today that allows one to say "disallow braces around single-line if-statements".  So, it's not a bug.  It's a request that the Roslyn IDE add such a feature.

The team will have to decide.

1. if such a feature *should* be provided. And, if so:
2. when such a feature would then be worked on.

--

The linked issue helps explain things more: https://github.com/dotnet/roslyn/issues/29621

The primary problem here is that the name of the existing feature seems to imply that this is a preference which switched between either:

1.  forcing braces around single-line constructs 
2. forbidding braces around single-line constructs

However, that's not what the feature is.  The existing feature is not intended to ever 'forbid' braces.  Merely to state if it's ok for them to be absent or not.

**Comment by deakjahn** [comment]
However, VS now has a Configure Code Cleanup (Ctrl+K+Q is the default). And it has an *Add/remove braces for single-line control statements* item. Only that it doesn't seem to work.

**Comment by Alexees** [comment]
16.0, 16.1, backlog... nobody likes this guy XD

**Comment by deakjahn** [comment]
Nope, that's something different, I guess. Not the Code Style tip but a definitive promise from the Code Cleanup system. While we could argue about the first, I don't think the second can be considered anything but a bug if it doesn't work. I think I'll report it as such, especially if you can confirm you see it, too.

**Comment by Alexees** [comment]
if you mean me, I have not tried it, but considering everybody uses the same install of VS, it's hard to believe it would turn out differently for me in such a trivial case.

**Comment by deakjahn** [comment]
Anyway, I reported it and they seem to pick up the bug, so here's hoping.

https://developercommunity.visualstudio.com/content/problem/573444/code-cleanup-addremove-braces-fixer-not-working.html

**Comment by deakjahn** [comment]
The bug report linked above was closed but referring to this as the original thread (it happened the other way around, actually, but it doesn't matter).

**Comment by bengi83** [comment]
Why is this closed? #43299 is closed and I don't see how #34707 is relevant. Version 16.9.1 and still when I set prefer braces to "When on multiple lines" and code formatting to "Add/**remove** braces for single-line control statements" it still doesn't remove braces for single line control statements.

**Comment by CyrusNajmabadi** [comment]
> Why is this closed? 

This is not closed.

**Comment by bengi83** [comment]
> > Why is this closed?
> 
> This is not closed.

Oh yes, it is open. Sorry, I got ahead of myself. Normally when I finally find tickets related to an issue and scroll to the bottom to find someone has related it to closed or irrelevant tickets it has been shamefully closed. I'm glad this one is still open because this issue is really annoying, I almost contemplated changed team coding standards to requiring braces for single line control statements!

**Comment by deakjahn** [comment]
Don't change standards. :-) Long life to he who considers the widespread misbelief of "there should be braces everywhere" null and void and woe betide he who never fixes it for us in two years or more.
