### ISSUE TITLE
Microsoft.VisualStudio.LanguageServices.Implementation.Options.LanguageSettingsPersister loads settings eagerly (88ms) 

### ISSUE THREAD

**Issue by JieCarolHu** [dotnet/roslyn#29602]
copied from https://devdiv.visualstudio.com/DevDiv/Default/_workitems/edit/639090

**Comment by JieCarolHu** [comment]
The idea of fixing this perf issue is to preload the dependent services via GetServiceAsync(), so the serviceProvider.GetService() will get back the service instance fast without creating a new instance. 
In this particular LanguageSettingsPersister constructor, it needs SVsTextManager service instance, which is already added to GetServiceAsync() in https://github.com/dotnet/roslyn/pull/29560

**Comment by JieCarolHu** [comment]
It currently took 3ms to get the dependent service, so this fix probably won't reduce the a lot of the 88ms. We currently don't have other ways to improve the solution load perf besides pre-load the dependent services

**Comment by jasonmalinowski** [comment]
Reactivating this one because although the service load time is a nice small improvement, the real win really needs to come from not doing the preloading of options. We could do this via:

1. Getting the shell/editor to provide a free-threaded API to read these, and we can avoid the preload entirely.
2. Reading the options directly from the underlying option store to bypass the shell/editor API, if they can't fix it.
3. Just understand why the shell/editor code is consuming this long to read options.

etc. I'm not particularly partial on implementation approach (although the first is always my preferred option, of course), but we do still have work to do here.

**Comment by davkean** [comment]
Note, this issue is pointed to from https://github.com/dotnet/roslyn/blob/main/src/EditorFeatures/Core/Implementation/LanguageServer/AbstractInProcLanguageClient.cs#L126 and that hack was just blamed in a UI delay: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1468258.

**Comment by tmat** [comment]
Will be addressed once https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1307188 is implemented by the editor.

**Comment by davkean** [comment]
We only need the mef construction to be done off the UI thread to resolve the UI delay. It's the DLL load that is causing it. You can switch back to call that API.
