### ISSUE TITLE
[C# Feature] Support more feature for LINQ query

### ISSUE THREAD

**Issue by rexxiang** [dotnet/roslyn#2970]
In some complex situation, the LINQ query will be loss the readability and hard to maintain.
so it would be better if the LINQ query syntax improved like below.

allow more condition expression in the join clause. the **equals** expression is the only choice nowdays.
```csharp
from l in EntityList
join r in EntityList on l.ParentId == r.ParentId && l.Id > r.Id
select r
```

allow left join clause in LINQ to let the query more simplify .
```csharp
from l in EntityList
left join r in EntityList on l.ParentId == r.ParentId && l.Id > r.Id
select r
```

--
I'm not good at English, but hope you guys understand what I'm saying. :smile:

**Comment by aluanhaddad** [comment]
For the first example proposed:
In terms of LINQ to Objects the current semantics of the join clause are that it does not enumerate the right sequence for each item in the left sequence. Instead it produces the keys used in the equals clause a single time for each sequence and correlates items accordingly. This has two nice properties:
1. It improves performance when items only need to be correlated thusly.
2. It may improve readability in these cases by highlighting the simplicity of the correlation. This can be especially true for scenarios which perform ad hoc correlations (subjective).
Continuing with LINQ to Objects, the first example proposed
```C#
from l in EntityList
join r in EntityList on l.ParentId == r.ParentId && l.Id > r.Id
select r
```
Would currently quite clearly written as either:
```C#
from l in EntityList
from r in EntityList 
where l.ParentId == r.ParentId && l.Id > r.Id
select r
```
or, if we want potentially better performance*:
```C#
from l in EntityList
join r in EntityList on l.ParentId equals r.ParentId 
where l.Id > r.Id
select r
```
Either option is very readable in my opinion.

My reason for the above statements is to clarify the nature of the first part of the feature request. 
Is it because that you find ```join on x == y && a > b``` more readable than the currently available options?


In the second example: 
```C#
from l in EntityList
left join r in EntityList on l.ParentId == r.ParentId && l.Id > r.Id
select r
```
What semantics do you propose for ```left``` join modifier?

**note that ```equals``` and ```==``` can behave differently for some types*
