### ISSUE TITLE
Make NavigationAnnotation public

### ISSUE THREAD

**Issue by MaStr11** [dotnet/roslyn#29797]
The [`NavigationAnnotation`](
http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/CodeActions/Annotations/NavigationAnnotation.cs,18) is used to place the cursor after a CodeFix was applied. While other Annotations (Rename, Formatter, ...) are public, this one is internal. It would be nice if it could be made public.

**Comment by CyrusNajmabadi** [comment]
I would do this.  However, for the design review, there are a couple of tweaks i would make.  Right now this annotation is placed on a piece of Syntax (hence SyntaxAnnotation).  However, it is ambiguous about what it means wrt to that syntax.  For example, should the user navigate to the start of that syntax?  to the end?  should the entire piece of syntax be selected?  

Basically, along with this annotation should be an enum specifying the desired behavior here about what it means to navigate to syntax.

**Comment by CyrusNajmabadi** [comment]
This would need to go through an API proposal.  in general, the reason we don't just make things public is because it increases maintenance costs and locks down our ability to change things in teh future.  We can open things up, but we have a process that requests need to go through to make sure the appropriate people weigh in and the right API shape is determined and shipped.
