### ISSUE TITLE
Completion Suggestion Mode doesn't work as expected in collection initializers

### ISSUE THREAD

**Issue by mkrueger** [dotnet/roslyn#29830]
See

https://github.com/mono/monodevelop/issues/5816

1. Open a C# file with `using System.Collections.Generic;`
2. Inside a method body, type `var list = new List<string> {`
3. Make sure the closing `}` is auto-inserted and the caret is between the curlies: `new List<string> { |}`
4. Note that at this time completion list is showing, String is soft-selected
5. Press ENTER

**Expected:**
ENTER to insert a line break between the curlies, because String is not hard-selected

**Actual:** 
String is inserted into the buffer, line break is not inserted.

![image](https://user-images.githubusercontent.com/679326/44884249-81925b80-ac6f-11e8-9120-eaff20992934.png)

**Comment by sharwell** [comment]
> Note that at this time completion list is showing

This does not occur in Visual Studio.

> Press <kbd>Enter</kbd>

When suggestion mode is enabled and completion appears inside a collection initializer (e.g. by typing `S`), the expected behavior occurs.

I can't find a way to reproduce the "Actual" behavior, which suggests this is a bug in the way monodevelop is triggering completion in this scenario.

**Comment by KirillOsenkov** [comment]
Apologies for the confusion, this is a MonoDevelop specific bug and doesn't reproduce on Windows. Closing.

**Comment by sharwell** [comment]
@KirillOsenkov no problem 👍
