### ISSUE TITLE
VS Wrongly Suggests Name Simplify Refactoring on C# String

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#29923]
VS2017 suggests name simplify refactoring on all C# String types, when they are written as String (with capital S). It suggests to replace it with string. There is no real simplification in this refactoring. As a matter of fact, String vs string is personal developer style as these are the synonims in C#. I prefer to use String with capital &quot;S&quot; , so I am tired to see all these suggestions in all my code files.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/328393/vs-wrongly-suggests-name-simplify-refactoring-on-c.html
VSTS ticketId: 677559_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment]
`string` is considered the simple form of the name because it always, unambiguously, means the correct `String` type.  This is not hte case with `String` as it may bind to some other type, and also needs an appropriate `using` in scope in order to be understood.

This behavior is definitely expected as per the design here.

> , so I am tired to see all these suggestions in all my code files.

You can disable this suggestion here:

![image](https://user-images.githubusercontent.com/4564579/45593716-17510a80-b941-11e8-8d43-863f6a6040dc.png)

If you prefer the framework type over the simpler, predefined type, then just specify that as your preference, and these suggestions will go away.

**Comment by CyrusNajmabadi** [comment]
General location for these options is:

![image](https://user-images.githubusercontent.com/4564579/45593776-4b78fb00-b942-11e8-8892-6b455d073aa2.png)

**Comment by busyscout** [comment]
There should be an option "Disable" or "None" in Severity to skip this check. Take a look how it's done e.g. in Jet Brains Resharper.

**Comment by CyrusNajmabadi** [comment]
Closing out as the option already exists for this.
