### ISSUE TITLE
Cached analyzer is applied instead of updated one

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#29939]
_From @taori on September 17, 2018 12:24_

I've got a project which references a local nuget repo analyzer.

After updating the analyzer the build process works fine and uses the updated analyzer - Visual Studio still reports diagnostics of the previous analyzer version however in the error window, as well as the code window.

I think some cache needs to be invalidated here after nuget updates.

_Copied from original issue: dotnet/project-system#4031_

**Comment by Pilchie** [comment]
Tagging @mavasani and @tmeschter.

There is *supposed* to be a warning in this case, but it may happen only if the analyzer assembly is strong name signed.  Unfortunately, it's not possible to load a new version of an analyzer if it's not, as the CLR treats the assemblies as the same.

**Comment by sharwell** [comment]
We should strive for one of the following two outcomes for any arbitrary package change:

1. We start using the new analyzer assembly, and stop reporting diagnostics from the old one
2. We cannot perform (1) due to assembly version limitations (no strong name and/or no *unique* strong name and/or no unique assembly load context), so we report an error that the analyzer changed and needs to be reloaded

**Comment by thomasclaudiushuber** [comment]
Same issue for source generators: #48083

**Comment by jasonmalinowski** [comment]
Going to close this in favor of #48083 since that one is actually what most folks are following these days.
