### ISSUE TITLE
NullableAttribute constructor parameter should be stored in a field

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#30143]

**Comment by jcouv** [comment]
Re-purposed this issue for NullableAttribute instead of NonNullTypesAttribute (which is being removed)

**Comment by roji** [comment]
And although this seems pretty obvious, the value(s) should be exposed via a public property :)

My scenario is modifying Entity Framework Core to detect nullable vs. non-nullable properties and set up the database model accordingly (so that non-nullable properties cause non-nullable database columns to be created). So the nullability information recorded in the attribute must be accessible to us via reflection.

Would it be possible to prioritize this somewhat (especially as it seems simple)? We'd like to make sure this works early, allow users to test etc.
