### ISSUE TITLE
[Idea] Async Properties

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#3015]
AFAIK it is currently not possible to have async properties in vb.net (and C#?), as result it isn't possible to implement asynchronous indexes. Some times I like to have indexers the are used for index position lookup of data, maybe from a file. It been used common in code that to keep the code concise I'll implement it as an Indexer. 

Async on `Read Write` properties would be I think a little comples (if not close to impossible), but I think at would be relatively simple to allow `async readonly ` properties.

**Comment by GeirGrusom** [comment]
I think you can already achieve this. Use an internal async function and just return that task in the property or indexer. You can even have an async setter if you like.

You can't mark a property as async, but you don't really have to.

**Comment by OzieGamma** [comment]
Properties should **only** be used for:
- Values that can immediately be retrieved from memory
- Values that can easily be computed in a short time

Exception can be made (Eg. cashed data, which can be slow the first time it is accessed).
Those are of course only guidelines.
Here is Microsoft's opinion on it;

### Properties vs. Methods

Class library designers often must decide between implementing a class member as a property or a method. In general, methods represent actions and properties represent data. Use the following guidelines to help you choose between these options. 
- Use a property when the member is a logical data member. In the following member declarations, Name is a property because it is a logical member of the class. 
- Use a method when: 
    - The operation is a conversion, such as Object.ToString.
    - The operation is expensive enough that you want to communicate to the user that they should consider caching the result.
    - Obtaining a property value using the get accessor would have an observable side effect.
    - Calling the member twice in succession produces different results.
    - The order of execution is important. Note that a type's properties should be able to be set and retrieved in any order.
    - The member is static but returns a value that can be changed.
    - The member returns an array. Properties that return arrays can be very misleading. Usually it is necessary to return a copy of the internal array so that the user cannot change internal state. This, coupled with the fact that a user can easily assume it is an indexed property, leads to inefficient code. In the following code example, each call to the Methods property creates a copy of the array. As a result, 2n+1 copies of the array will be created in the following loop. 

https://msdn.microsoft.com/en-us/library/bzwdh01d(v=vs.71).aspx

**Comment by dsaf** [comment]
@OzieGamma To be fair that guidance was created long time ago. Probably even before ```Lazy<T>``` was introduced. If I will see an ```async``` property it will communicate to me that the operation is probably expensive. So it's not misleading. That being said, I don't see myself using async properties.

**Comment by whoisj** [comment]
@OzzieGamma in theory that makes sense. In practice it is nonsense. Objects can have read only values which make perfect, logical sense but need to use IO to get the data. Imagine software like Git implemented in C#, a Commit object could have  Tree property, but it would require IO to lazy load the object, so instead developers would implement a GetTree() method. Syntactically ugly for no reason than historical silliness around implied meanings of properties.

**Comment by OzieGamma** [comment]
@whoisj I mentioned cachable data as an exception to the guidelines.

How would you use async properties ?

I don't see myself writing:
```csharp
class Foo {
    public async List<string> Bar { get {...} }

    public static void Main(string[] args) {
        var f = new Foo();
        Console.WriteLine((await f.Bar).Count);
    }
}
```
The user shouldn't be able to make the distinction between a property and a variable. It just feels weird to me. Eg:
```csharp
class Foo {
    public async int Count { get {...} }

    public static void Main(string[] args) {
        var f = new Foo();
        
        for(var i = 0; i < await f.Count; i += 1) { ... }
    }
}
```

What's that supposed to mean ? Is count retrieved each time ? As I user, I expect properties to be cheap: I expect to be able to call them n times at the same cost of calling them once. Ie I don't have to cache the values myself.

**Comment by dazerdude** [comment]
It would be a little weird, especially in the set case, but you could do it. I'm not sure it justifies itself as a language feature as it adds a fair bit of complexity to properties, while not providing much benefit beyond the syntactic niceness of properties on async functions.

The case I really see for it is the async lazy load case.

This code:
```c#
class Foo {
  private int count = -1;
  public async Task<int> GetCount() {
    if(count == -1) 
      count = await LoadCount();
    return count;
  }

  public async Task SetCount(int value) {
    count = value;
    await SaveCount(value);
  }
}
```

could become

```c#
class Foo {
  private int count = -1;
  public async int Count {
    get { 
      if(count == -1) 
        count = await LoadCount();
      return count;
    }
    set {
      count = value;
      await SaveCount(value);
    }
  }
}
```

Most of the time the getter just returns the cached value, but you have to call it with await everytime because you can't know whether the getter has already cached the value.

The weird parts are that the setter function doesn't take the same type that the getter returns, and the setter returns a Task. This breaks pretty hard from the way properties work right now. I don't really see the work being justified to support only getters though. I expect it'd be nontrivial work to implement to support only a few cases that can already be easily implemented in the current language (without even much extra code).

```c#
class Foo {
  public Task<int> Count { get { return GetCount(); } }
  private async Task<int> GetCount { await DoAsyncWork(); }
}
```

**Comment by HaloFour** [comment]
@dazerdude The problem with async setters is that they would be entirely fire-and-forget.  The caller could never know that it failed (or even that it completed).  `async void` was included to allow for async event handlers but I think it was largely a mistake.

**Comment by dazerdude** [comment]
I understand that. If I'm not mistaken setters now return the value (so you can chain them). You'd have to have the setters return a Task or Task<T> which would create some really weird expressions. 

However, without support for setters I don't see the work justifying itself. To be honest though, I don't really see the work justifying itself with setters for that matter. It's just too complex and weird.

**Comment by HaloFour** [comment]
Quite sure they can't return a value.  Chaining property setters wouldn't
syntactically make sense.

**Comment by gafter** [comment]
The consensus on this issue is that this is not something we'd want to do.
