### ISSUE TITLE
Will nulllable reference type optimize away null reference checks?

### ISSUE THREAD

**Issue by vectorix** [dotnet/roslyn#30237]
This is a question, not a request. With the new C# feature for nullable reference, if a reference is not nullable, will the compiler/JIT optimize away null reference checks when accessing it (to improve performance)?

Thanks

**Comment by svick** [comment]
As I understand it, no, it will not, because it's a compiler-only feature. From the point of view of the runtime, all reference types are still nullable, so it will still have to perform null reference checks.

Also non-nullable reference types are not 100 % guaranteed to be not null. If you use `null` where it's not allowed, [you only get a warning, not an error](https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLQDk4BstWFiAJQkiQDsBjCAFQE8AHFAGhhADcIEBLMWgHwDaAAQCMAOkJwyMLgFsIYgMIB7WfS4EEAZU5suVZGPTKymHHUbIAugFgAUEIBMAAkXOA3veffnogAzOALIAFACUHl4+UUIA7M5k2FgA3JHeAL72aUA==). [And there's even syntax to get rid of that warning.](https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLQDk4BstWFiAJQkiQDsBjCAFQE8AHFAGhhADcIEBLMWgHwDaAAQCMAOkJwyMLgFsIYgMIB7WfS4EEAZU5suVZGPTKymHHUbIAugFgAUEIBMAAkXOA3veffnogAzOALIAFACUHl4+UUIA7M5k2FgAhADckd4AvvYZQA===) This means that removing those checks would not be safe.

**Comment by jaredpar** [comment]
@svick is correct. This will not optimize away null checks.
