### ISSUE TITLE
Object Browser displays incorrect objects/members, and is painfully slow

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#30371]
_From @verelpode on October 4, 2018 16:24_

Hello, the Object Browser window is very useful -- I love it and I thank everyone who ever worked on it, because I use it multiple times every day I work.  However, some reliability and speed improvements would be very much appreciated.  Sometimes it displays incorrect objects/members (see screenshot).  It replaces the correct object/member with some other random object/member, seemingly chosen at random, as if the internal data structures are corrupted.  VS 15.8.5.

Furthermore, it is unfortunately slow to the point of being frustrating to use/wait.  Searching is slow, and expanding "Desired Types" is extremely slow.  When I change "Browse:" to "Universal Windows" then search etc, it seems even slower than when I have it set to browse ".NET Framework 4.7.2".  Unsurprisingly, the speed is worsened even further when you search "All Components".   I suggest using indexing and caching techniques to improve the speed.  Maybe even pre-load all of the data into an SQLite database, then search the database instead of searching the original assemblies.

See also [Dev Community #76369](https://developercommunity.visualstudio.com/content/problem/76369/object-browser-blocking.html) -- another person who described the painful slowness of Object Browser.

![object browser bug](https://user-images.githubusercontent.com/32857007/46488173-3df8b780-c802-11e8-8725-4c799a4df25e.png)

_Copied from original issue: dotnet/project-system#4083_

**Comment by Pilchie** [comment]
_From @verelpode on October 4, 2018 17:2_

Example of the speed problem:  I chose `Browse: All Components` then I searched for the word "**updated**".  When the search completed, I immediately clicked the button to clear the search, which caused another delay.  The total time was **21 seconds**!  During these 21 seconds, Visual Studio was totally unresponsive to mouse clicks etc (the search is not async).

Next I searched for "**visual**" and it again took around 20 seconds, but when I searched for "**xaml**", it took half the time -- around 10 seconds (including time to also clear the search).

Next I tried opening "**Derived Types**" for `Windows.UI.Xaml.UIElement` and it took a shocking 1 minute and 38 seconds!

**Comment by Pilchie** [comment]
No problem - there are definitely a lot of repos, and you shouldn't *have* to know how everything is split up :)

**Comment by verelpode** [comment]
Currently I'm writing this message while I'm waiting for Visual Studio to unfreeze, because I accidentally clicked on the expand-triangle for "Derived Types", and VS freezes (**totally locks up!**) for a couple of minutes while it searches for the derived types.  This happens at least a few times every week.  It's frustrating.  Of course I try not to accidentally open "Derived Types", but if I always click very carefully in the "Object Browser" window, then I'm constantly slowed down anyway as a result of precaution.  Basically, the point is, the "Object Browser" window/pane is very useful but frustratingly slow, and this slowness is made worse by the fact that the Object Browser window is not async.   It would be less bad if I could work in other parts of VS while waiting for the Object Browser window, but unfortunately the entire VS freezes while the Object Browser is working.

**Comment by verelpode** [comment]
Here's another bug in the Object Browser:   Every so often, when I type into the Search box and hit the Enter key, it displays a message box saying:
> "Enter a symbol name, or a portion of a symbol name, to search."

Thus it sometimes reacts as if the Search box is empty when I press the Enter key after typing into the Search box.  Then I dismiss the message box, re-type the text and hit Enter again, and then it works.   I suspect this bug occurs more often after using "Browse:" to switch to a different collection, but actually I don't know what triggers this bug.

Here is another bug with the Search box:   I type "test" then press the Enter key and it searches for "testing" instead of "test".  I can explain why it does that.  In my opinion, this is a bug or incorrect design, although some people may disagree with me.  The reason why it searches for "testing" instead of "test" is because I previously searched for "testing", and thus "testing" is auto-filled into the Search textbox as soon as I type the first "t" in "test".

Thus to search for "test", I am forced to type "test", then press the Backspace/Delete key, then press the Enter key.  In my opinion, this behavior is undesirable.   The reason why I'm forced to press the Backspace key because when I type "test", it auto-fills "testing", and the Backspace key deletes the auto-selected text (deletes "ing") leaving me with the text I actually typed, that is "test".

**Comment by verelpode** [comment]
Today and yesterday, when I look at the `System.Windows.Window.Activated` event in the Object Browser, instead of displaying the delegate for this event, it displays the class `System.Windows.MessageBox` -- see attached screenshot.  The event `System.Windows.Window.Closed` is also incorrectly mapped to `System.Windows.MessageBox`.  I also do dev for UWP and I'll try to remember to save a screenshot when I next see Object Browser malfunctions when browsing the UWP collections.
![object browser bug wrong delegate displayed](https://user-images.githubusercontent.com/32857007/48852692-325f5100-edae-11e8-9fb6-cb2dbfa1f5bb.png)

**Comment by CyrusNajmabadi** [comment]
Object browser is in maintenance mode and is getting no further work.  Any changes here would need to come through some new system (which would effectively be a rewrite).
