### ISSUE TITLE
Consider reordering Extract-Method and Introduce-Variable

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#30475]
Right now, when you select some code, you will get up to 4 actions to 'introduce variable', and up to one action to 'extract method'.  i.e.:

![image](https://user-images.githubusercontent.com/4564579/46884184-152b8000-ce09-11e8-8634-74e7395061e0.png)

If you want to actually extract a method, you then need to skip over up to 4 other actions to make the selection.

I think it would make sense to reorder these.  First, i personally believe extract-method is used more than introduce-variable.  Second, it just makes selection more pleasant since, at worse, you only need to skip over one action you don't want, instead of up to four.

--

Note: i think this decision should also be telemetry driven.  If Introduce-Variable is more heavily used thatn Extract-Method, then we can leave this alone.  However, if it's not (as my hunch indicates), then flipping this makes a lot of sense.

Previously Kasey could figure this out.  But i'm not sure who is now reviewing this data.

**Comment by jinujoseph** [comment]
@kendrahavens for telemetry

**Comment by kendrahavens** [comment]
Hey @CyrusNajmabadi, your prediction was correct. Extract-Method appears more frequently used than the Introduce-Constant. I recommend changing the priority to list Extract-Method first.

**Comment by kendrahavens** [comment]
*Correction* _In menus were there is more than 1 option_, Introduce Constant is much more popular than Extract Method. My perception was skewed before because I was including all the usages where Extract Method is the only menu option. (Sorry!) If you have any more ideas on how to cut the data let me know!

Based on this, I think we should keep the current ordering.
