### ISSUE TITLE
Extract Interface is not an option on a class that extends an abstract / generic class

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#30514]
I'm not sure the exact cause, but I have the following class:

public abstract class UsageHelper&lt;T&gt; where T : ISharedContentUsage {}

And one that implements it:

public class AttachmentSectionRuleUsageHelper : UsageHelper&lt;AttachmentSectionRuleUsage&gt; {}

And when I open Quick Actions and Refactoring, &quot;Extract interface...&quot; is not an option.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/348444/extract-interface-is-not-an-option-on-a-class-that.html
VSTS ticketId: 695628_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment]
IN that code provided, extract interface is not available since the class has no members.  If you add just a single member, then we do offer to extract out an interface for the type.

This seems like intended design barring some strong reason we would have to offer 'extract interface' which would then just extract out an empty interface.
