### ISSUE TITLE
Inline temporary variable doesn't inline and creates invalid code instead

### ISSUE THREAD

**Issue by Tragetaschen** [dotnet/roslyn#30558]
**Version Used**: 
15.8.7

**Steps to Reproduce**:
```csharp
public static IObservable<object> Create()
{
    object build(string a, double b) => null;

    IObservable<string> first = null;
    IObservable<double> second = null;

    var observable = first.CombineLatest(second, build); // run here
    return observable;
}
```
Run the "Inline temporary variable" code fix on the marked line

**Expected Behavior**:
The return statement should just be moved and `observable` should be removed.

**Actual Behavior**:
The code fix generates invalid code:
![image](https://user-images.githubusercontent.com/1947968/47089409-17367a00-d221-11e8-9523-639c8e6b7975.png)

**Comment by CyrusNajmabadi** [comment]
Looks like broken expansion/reduction.  Likely because the local functions 'build' was expanded out to an invalid 'fully qualified form'.  We'll have to update expansion to not fully qualify local functions.

At the same time, whoever does this should ensure that 'expansion' does cast the local function to the right delegate type when passed as an argument to something.

**Comment by Tragetaschen** [comment]
Does not reproduce in 16.6.2

![image](https://user-images.githubusercontent.com/1947968/84683696-e350b200-af37-11ea-8345-0757621cb051.png)
