### ISSUE TITLE
Symbol equality

### ISSUE THREAD

**Issue by YaakovDavis** [dotnet/roslyn#3058]
It seems like 2 logically equivalent symbols from 2 different compilations are considered "unequal" in the current API.

This makes it hard to rewrite existing code, since you don't have a reliable way of comparing symbols.

Say I have syntax tree T1, containg a class C1.
I calculated S1, the symbol for C1.

Now I modified T1 to get T2, and I want to check all references to C1.
I can't use S1 anymore, and would have to recalculate it.

Why doesn't the IEquatible implementation of ISymbol consider logical equivalence?

**Comment by mattwar** [comment]
While its not the same thing as SymbolEquivalenceComparer, there is a few API's that could help.  

In Microsoft.CodeAnalysis.Editing there is a type SymbolEditor with the API GetCurrentSymbolAsync that will find you the current symbol in the latest solution that corresponds to a symbol from a previous solution.

If aren't working with solutions, you could also try the API that the SymbolEditor uses; DocumentationCommentId.  (It was made public recently.)  It uses this value to identify a symbol across solutions. You can use it to find the equivalent symbol in a new compilation, as long as names and distinguishing types have not been changed.

**Comment by Jake456** [comment]
Thanks, I'll check out the mentioned APIs.

**Comment by Jake456** [comment]
The types in the .Editing namespace do seem to help with tree editing.

What's missing IMO is a ProjectEditor, that allows you to get the current Compilation after an edit.

Or is there something like this already available? Is there an easy way to get a fresh compilation after editing a node in a single tree?

**Comment by mattwar** [comment]
You can use the DocumentEditor to get the changed document, and then do doc.Project to get the project from it, or manually do it with doc.WithSyntaxRoot. Every time you update a document with new tree nodes, you get a new project and solution too.  From a new project you can always get the updated compilation with project.GetCompilationAsync.  Note, you can also bypass the doc & project altogether if you just want a new compilation, since you can call compilation.ReplaceSyntaxTree.

**Comment by Jake456** [comment]
Sure, but if I rely on docEditor.GetChangedDocument().Project I lose the ability to centralize the changes.

Say I modified doc1, and then made another modification to doc2.
Calling the above from both docs will yield 2 different projects.

I thought the whole point of the *Editor classes is to "fake" a mutable wrapper on top on immutable objects.

SolutionEditor provides a nice solution (hmm..) at the solution level, where you can make unrelated changes to the doc, and them get a commutative updated solution.

The same approach would be much beneficial at the project level as well.

I have in fact implemented one myself meanwhile, but the framework can better control the internals, providing a more complete solution. (For example, I don't want anyone changing a doc, without the ProjectEditor being aware of that, but my implementation can't achieve that).

FWIW, Immutability seems be a non-trivial barrier for modifying existing code.
It's not clear (to a novice user) what actions are expensive, what can be cached, and how to keep different parts of the data in sync.

**Comment by CyrusNajmabadi** [comment]
This would need to go through an API proposal.  in general, the reason we don't just make things public is because it increases maintenance costs and locks down our ability to change things in teh future.  We can open things up, but we have a process that requests need to go through to make sure the appropriate people weigh in and the right API shape is determined and shipped.
