### ISSUE TITLE
Cannot retrieve symbols under a type alias

### ISSUE THREAD

**Issue by GeorgeAlexandria** [dotnet/roslyn#30631]
Hi,

I'm used **Microsoft.CodeAnalysis.CSharp.2.8.2** and they dependents.

I cannot retrieve `ISymbol` and `ITypeSymbol` (they are just nothing in the relevant `Info` structures) using `SemantciModel.GetSymbolInfo` and `SemantciModel.GetTypeInfo` for the type alias identifier (`KNFE`) in the code below:

```c#
using KNFE = System.Collections.Generic.KeyNotFoundException;
```

At first, I tried append before these using a something that will be used this alias:

```c#
/// <see cref="KNFE"/>
using KNFE = System.Collections.Generic.KeyNotFoundException;
```
and I still cannot receive symbols for `KNFE` identifier under `NameEqualsSyntax`, but can for the identifier under the `NameMemberCrefSyntax`. I checked that the boths `IdentifierNameSyntax` have the same kind.

At second, I assumed it can be due that using was determined as unused, so I added reference on it:

```c#
/// <see cref="KNFE"/>
using KNFE = System.Collections.Generic.KeyNotFoundException;

class Some
{
    KNFE field;
}
```
but I still cannot receive symbols.

As workaround I can receive symbols from the right hand of equals in the using directive

**Comment by mavasani** [comment]
@GeorgeAlexandria You need to invoke `SemanticModel.GetDeclaredSymbol` API on the `UsingDirectiveSyntax` to fetch the declared alias symbol.

**Comment by GeorgeAlexandria** [comment]
@mavasani, I actually wrote that I know a way to retrieve the corresponding symbol from `UsingDirectiveSyntax.Name` or just from `UsingDirectiveSyntax`, but my question was why `ISymbol` cannot be retrieved from identifier under the alias node: `UsingDirectiveSyntax.Alias.Name`.

**Comment by mavasani** [comment]
Tagging @dotnet/roslyn-compiler - semantic model API question.

**Comment by CyrusNajmabadi** [comment]
> @mavasani, I actually wrote that I know a way to retrieve the corresponding symbol from UsingDirectiveSyntax.Name or just from UsingDirectiveSyntax, but my question was why ISymbol cannot be retrieved from identifier under the alias node: UsingDirectiveSyntax.Alias.Name.

Because that's the design of the semantic model :)  At a declaration, we basically only have a single node that we consider 'the declaration'.  The same holds true for all our other declarations.  If you have a 'class declaration' you can use GetDeclaredSymbol on it to get the INamedTypeSymbol.  However, you can't call anything on hte 'Name' of the class.  

This was intentional to avoid ambiguity and open questions about "which subnodes should we support GetDeclaredSymbol on?"  The answer is always pretty simple: it's on the topmost node that is still specific to that symbol.

**Comment by CyrusNajmabadi** [comment]
> why do SemanticModel.GetSymbolInfo return nothing (doesn't return any symbols) for 

Because GetSymbolInfo is for figuring out what something means at  *referencing* location.  THis is not a referencing location.  It is the *declaration point*.  As such, only GetDeclaredSymbol is defined to work there.  This is how things work for all our nodes.  At the declaration point you use GetDeclaredSymbol and at a reference point you use GetSymbolInfo.  These APIs are behaving consistently with that design.

> but returns symbols for the other IdentifierNameSyntax nodes from the my original post?

Your other Identifiers are at reference location, they're not the actual declaration location itself.

**Comment by GeorgeAlexandria** [comment]
> Because GetSymbolInfo is for figuring out what something means at *referencing* location

@CyrusNajmabadi, It's explaining why it doesn't work for `IdentifierNameSyntax` as `UsingDirectiveSyntax.Alias.Name`. 

Thanks for answer.
