### ISSUE TITLE
Remove namespace

### ISSUE THREAD

**Issue by VinothIndian** [dotnet/roslyn#3071]
New feature : Add Project wise namespace no need add namespace in each file.

**Comment by dimaaan** [comment]
Bad idea :-1:

**Comment by VinothIndian** [comment]
Hello dimaaan , 

Please let me know why this is bad idea ?

Regards,
Vinoth.

**Comment by SolalPirelli** [comment]
Duplicate of #2044, which already has a discussion about this.

**Comment by whoisj** [comment]
@VinothIndian bad idea because you are assuming the use of Visual Studio and therefore the existence of a csproj file. Not all code is compiled this way. At the enterprise level, where you have tens of thousands of C# files to be build, having a project per isn't always feasible. If the namespace is removed, what namespace would you assign objects to when no .csproj is present?

**Comment by gafter** [comment]
Duplicate of #2044
