### ISSUE TITLE
Overall discoverability/quality issues with the /shared switch

### ISSUE THREAD

**Issue by kg** [dotnet/roslyn#30722]
Right now if you want to use the compiler server support, you have to dig through the csc source code to find out the name of the switch, and then guess what argument it takes. This is unclear and I'm still not sure I'm using it correctly. It should appear in the help with all the other switches.

Additionally, as pointed out in https://github.com/dotnet/roslyn/issues/28559 there is no diagnostic feedback telling you if you're using the switch wrong, or have omitted a required argument, or otherwise. In my case I'm trying to get /shared working in Mono and it's impossible to debug any of this, because all csc does is (sometimes) hang for a while and then quietly compile in-process, usually after having spawned a hung worker in the background. It's reasonable to want to suppress an error message in common cases, but if something unexpected has happened (and there appear to be like a dozen different failure modes in the source code for the relevant components) it really needs to be printed somewhere. If I have to pass another flag like /debugshared for diagnostic messages then so be it, but the current state of things is bad. If a user is trying to take advantage of /shared for performance reasons and has made a mistake, they have no way to know other than timing their builds.

**Comment by jmarolf** [comment]
@agocke

**Comment by jaredpar** [comment]
> Right now if you want to use the compiler server support, you have to dig through the csc source code to find out the name of the switch, and then guess what argument it take

This is not documented because it wasn't intended to be shipped at all. The core compilation path in MSBuild doesn't even use this switch. It uses the implementation inside the build task to do the communication. The `/shared` switch got shipped mostly due to an accident of history which is partyl why it's not documented.

The way to manually set this up is to do the following: 

- launch `csc -shared some_string`
- launch `vbcscompiler -pipename:some_string`

The secret passed to each instance just needs to be the same then they should link up properly.

> If a user is trying to take advantage of /shared for performance reasons and has made a mistake, they have no way to know other than timing their builds.

That is somewhat by design here. The core problem here is that shared **will** fail even in the best of circumstances. This is due to flakiness of named pipes, timing issues on startup, analyzer conflicts, etc ... 

The server is an optimization. Issuing a warning every time this failed would make normal, 100% correct builds have a warning. That's not acceptable to the user base. They did nothing wrong, the underlying optimization just couldn't take affect for that build. Worst of all their build completed successfully. We ended up giving them a warning they can't take action on for a build that completed successfully. 

That being said we do have a diagnostic mode here for debugging issues. To enable it setup the following environment variable before launching the server or csc:

```
export RoslynCommandLineLogFile=/path/to/log.txt
```

Detailed information from both the client and server will be written to that log file. Please shoot me an email if you have issues interpreting the output.

**Comment by agocke** [comment]
Technically, we did mean to ship it, but since all our users use MSBuild it was never meant for wide consumption. If you are using MSBuild, using `/shared` is materially worse because it requires spinning up the client for each invocation and waiting on CLR startup.

That said, I've put off writing documentation for this for too long and I should just write up a compiler design doc on how it works.

Jared's correct that there's no way we can make all compiler server indications produce warnings on server failure, but we could special case `/shared` since it's clear what the user wanted if they passed it explicitly and it's in use by such a small subset of users that there's not a huge risk of a breaking change.

**Comment by kg** [comment]
I see, if it's not intended to be used by anyone it's probably not necessary to make any changes to csc's list of switches/inline help. If the command line log contains relevant info then there probably isn't a need for it to talk every time it fails to talk to the compiler server. It might be good to expose command line logging as a switch to csc instead?

Diagnostic messages on /shared failure will certainly be welcome if it can happen - in the short term mono is not going to be using msbuild, so it'll be csc /shared for us if we manage to get it working.

Thanks for the information on how to use it, much appreciated.

**Comment by kg** [comment]
FYI, I tried using RoslynCommandLineLogFile and while it worked for VBCSCompiler it does not appear to work for csc.exe. It didn't even create the file.

```
kate@reeir-debian:~/Projects$ RoslynCommandLineLogFile=~/csc-log.txt ~/.mono/bin/mono --debug roslyn/Binaries/Debug/Exes/csc/net46/csc.exe mono/modreqtest/Program.cs /shared:1024
Microsoft (R) Visual C# Compiler version 42.42.42.42424 (<developer build>)
Copyright (C) Microsoft Corporation. All rights reserved.

kate@reeir-debian:~/Projects$ cat ~/csc-log.txt
cat: /home/kate/csc-log.txt: No such file or directory
```

**Comment by agocke** [comment]
Looks like there's a bug in the `~` expansion -- when I use a full path it works for me on Mac. I've also created some documentation here: https://github.com/dotnet/roslyn/pull/30816.

This is just a first step -- there's a lot to write down 😅
