### ISSUE TITLE
Using default() with ref struct in expression causes CS7038: Failed to emit module

### ISSUE THREAD

**Issue by csyszf** [dotnet/roslyn#30776]
**Version Used**: 
Tested with sdk 2.1.402 and 2.1.500-preview-009335
**Steps to Reproduce**:

1. Create a project
2. 
``` csharp
using System;
using System.Linq.Expressions;
public class Class1
{
    public void Method1()
    {
        Method((Class1 c) => c.Method2(default(Struct1)));
    }

    public void Method2(Struct1 s1) { }

    public static void Method<T>(Expression<Action<T>> expression) { }
}

public ref struct Struct1 { }
```
3. Build project

**Expected Behavior**:
Build succeeds
**Actual Behavior**:
error CS7038: Failed to emit module '_'.

**Comment by RikkiGibson** [comment]
Changing `default(Struct1)` to `new Struct1()` makes the program compile successfully. However, it seems like it shouldn't compile due to the restrictions around ref structs.

The `Method((Class1 c) => c.Method2(default(Struct1)))` will be lowered approximately like so:

```cs
public void Method1()
{
    ParameterExpression parameterExpression = Expression.Parameter(typeof(Class1), "c");
    MethodInfo method = typeof(Class1).GetMethod("Method2");
    Expression[] obj = new Expression[1];
    obj[0] = Expression.Constant(default(Struct1), typeof(Struct1));
    MethodCallExpression body = Expression.Call(parameterExpression, method, obj);
    ParameterExpression[] obj2 = new ParameterExpression[1];
    obj2[0] = parameterExpression;
    Method(Expression.Lambda<Action<Class1>>(body, obj2));
}
```

However the `Expression.Constant(object, Type)` requires the `default(Struct1)` to be boxed into `object`, which ref structs don't support. The compiler hits an assert in debug mode because no conversion exists-- in release mode the compiler probably crashes when it finds there's no way to emit the conversion.

We may need to perform additional checks to ensure that values of `ref struct` types are never used in expression trees.
