### ISSUE TITLE
Smart indent should handle braces when brace completion and formatting are disabled

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#30787]
**Version Used**: 15.8.8

**Steps to Reproduce**:

1. Set indentation mode to **Smart**
2. Disable Automatic Brace Completion
3. Disable formatting while typing
4. Type `if (true)`
5. Press <kbd>Enter</kbd>
6. Type <kbd>{</kbd>

**Expected Behavior**:

```csharp
if (true)
{
```

**Actual Behavior**:

```csharp
if (true)
    {
```

**Notes**:

The tests for this feature should also cover the case where the steps above are followed by:

7. Press <kbd>Enter</kbd>
8. Press <kbd>}</kbd>

:link: Derived from information in https://developercommunity.visualstudio.com/content/problem/49738/c-braces-indent-incorrectly-if-brace-completion-is.html

**Comment by pushqrdx** [comment]
This is so annoying, so either we use the semi retarded brace completion or live with that weird indentation issue once it's disabled. I hope this gets fixed soon.

**Comment by CyrusNajmabadi** [comment]
@pushqrdx This is marked 'help wanted'.  It would be great if you were interested in this if you could help out with a fix.  Thanks!

**Comment by CyrusNajmabadi** [comment]
Note: from looking at teh above, this seems by-design.  Smart indent indents properly when you press 'enter'.  it puts you here:

```c#
if (whatever)
    $
```

You also asked to disable 'format when typing'.  So, when you type `{` formatting is definitely *not* going and formatting that item, as per the intent.

--

One thing i can think about here would be to have a 'automatically format on `{`' so that you can turn off most formatting, but have the formatter place `{` in the right location when you typed it.  Otherwise, it's unclear to me how this would be expected to work since hte option to actually format code as you type is was explicitly disabled.
