### ISSUE TITLE
Per job GitHub badges

### ISSUE THREAD

**Issue by chcosta** [dotnet/roslyn#30827]
Azure DevOps now provides per job GitHub badges.

See https://raw.githubusercontent.com/Microsoft/azure-pipelines-agent/master/README.md as an example.

This means the Roslyn readme.md can provide status at the same granularity as the Jenkins badges are reporting.

side note: I don't think the Localization badge for Roslyn has been updated yet.

FYI @jaredpar

**Comment by jaredpar** [comment]
@chcosta how can I figure out the appropriate job name to put into the query for an executed job? Many of our jobs don't have hard coded names because they're a part of a matrix operation. I tried using the visual job name but it didn't work. 

Example:  https://gist.githubusercontent.com/jaredpar/b209df328b570a274c007a8eed6d9b72/raw/aabc74cc35247dcd5d114c2788a538422bc9ef1e/blamh.md

**Comment by dagood** [comment]
Here's where we're using it, for an example: https://github.com/dotnet/source-build/blob/release/2.1/README.md.

**Comment by jaredpar** [comment]
@chcosta, @dagood this support appears to be broken for branches that have a dot in the name 

https://gist.github.com/jaredpar/22a998980916fddc2a818f500f9c1b18
