### ISSUE TITLE
Simplifier prematurely removes "this" qualifiers in code containing compilation errors

### ISSUE THREAD

**Issue by Inspyro** [dotnet/roslyn#3085]
In the following example ...
```C#
internal class Program
{
  private static void Main (string[] args)
  {
    var syntaxTree = CSharpSyntaxTree.ParseText (s_text, options: new CSharpParseOptions());

    using (var workspace = new AdhocWorkspace())
    {
      var project = workspace.AddProject ("Test", LanguageNames.CSharp)
          .AddMetadataReference (MetadataReference.CreateFromAssembly (typeof (string).Assembly));

      var document = project.AddDocument ("Test.cs", syntaxTree.GetRoot());
        
      var errors = document.GetSemanticModelAsync().Result.GetDiagnostics().Where (d => d.Severity == DiagnosticSeverity.Error);
      Console.WriteLine ("Errors: " + Environment.NewLine + string.Join (Environment.NewLine, errors));

      var annotatedSyntaxTree = document.GetSyntaxRootAsync().Result.WithAdditionalAnnotations (Simplifier.Annotation);
      var simplifiableDocument = document.WithSyntaxRoot (annotatedSyntaxTree);

      var simplifiedDocument = Simplifier.ReduceAsync (simplifiableDocument).Result;

      Console.WriteLine (simplifiedDocument.GetTextAsync().Result.ToString());
    }
  }

  private static readonly string s_text = @"
public class C 
{
  static void StaticMethod()
  {
  }

  public void CallingCode()
  {
    this.StaticMethod();
  }
}
";
}
```

the simplifier **incorrectly** removes the `this` qualifier on the invalid static method invocation, which in the end makes the code valid again. This is unexpected behavior, as the code is semantically changed - An explicit instance call is changed to a static call.

**Comment by srivatsn** [comment]
The simplifier itself needs to be able to work on code with errors since in VS, code is mostly broken as users are typing. In this case the simplification being offered wouldn't be so suprising if you look at it in VS, because you will also see a squiggle saying you are calling a static method with this.

In your app, before calling the Simpifier.Reduce method, you could check to see if there are any errors at all in the code and bail out and not call the simplifier so that you don't have the simplifier running on broken code.
