### ISSUE TITLE
Sytem.Private.CorLib assembly referenced when building through Roslyn

### ISSUE THREAD

**Issue by adrianoc** [dotnet/roslyn#30893]
Hi. I am trying to compile a C# source into an executable using Roslyn but when I try to run the generated executable (dotnet core version **2.1.403**) it fails to run with an exception stating **System.Private.CorLib** assembly could not be loaded. Not completely sure whether this is a bug or if I am misunderstood something. 

**Version Used**:  2.9.0

**Steps to Reproduce**:

1. Unzip attached project
2. Build & run
3. Run the output of the step above

**Expected Behavior**:
Built application run with no exceptions.

**Actual Behavior**:
Exception:

> Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e' or one of its dependencies. The system cannot find the file specified.

[Test.zip](https://github.com/dotnet/roslyn/files/2536934/Test.zip)
![failtoloadsystem private corlib](https://user-images.githubusercontent.com/61679/47828085-dc236300-dd57-11e8-8b7a-34a8d3bbe186.PNG)

**Comment by jaredpar** [comment]
The approach you're taking here is not going to work:

```
var references = ((string) AppContext.GetData("TRUSTED_PLATFORM_ASSEMBLIES")).Split(Path.PathSeparator).ToList();
```

This is going to create references based on the runtime / implementation assemblies rather than the reference assemblies. That can work in certain cases but overall is not supported by the runtime or the compiler. This needs to change to pass the compiler the reference assemblies instead.

Also it's unclear how you're trying to exec the resulting assembly. A .NET Core assembly can't necessarily just be executed by invoking the assembly. Instead you need to use the CoreCLR host. Essentially `dotnet run` the output. 

Stepping back ... what are you trying to accomplish here? Compiling dynamically for coreclr is trickier than desktop. It's impossible to avoid expliicitly using the runtime in some way. 

@nguerrera

**Comment by adrianoc** [comment]
Thanks for the response @jaredpar 

> The approach you're taking here is not going to work
I've found some posts suggesting that and at least I was able to get Roslyn to compile my code.

I've also tried to add **typeof(object).Assembly.Location** (instead of using the the *TRUSTED_PLATFORM_ASSEMBLIES* approach) but in that case Roslyn failed to compile (complaining that references to some assemblies were missing)

>This is going to create references based on the runtime / implementation assemblies rather than the reference assemblies. 

Is there a way to programatically figure the folder that contains such assemblies ? (I would like to avoid hardcoding paths)

> Also it's unclear how you're trying to exec the resulting assembly. A .NET Core assembly can't necessarily just be executed by invoking the assembly. Instead you need to use the CoreCLR host. Essentially dotnet run the output.

IIRIC I've tried that but it produced a different error; something like project could not be found (sorry it was late night). I'll try that again today; I don't have access to that machine now.

To give some more context, in one of my projects I do some code generation; in my (integration) tests I build that code and execute the resulting assembly to compare the output with some expectations.

> Stepping back ... what are you trying to accomplish here? Compiling dynamically for coreclr is trickier than desktop. It's impossible to avoid expliicitly using the runtime in some way.

I was using CodeDom to build the C# code inside the tests (on Windows) but I want this to also work on Linux. AFAIK dotnet core (or Mono) are the only options on *nix OS (or am I wrong?)  so I decided to switch to dotnet core.

Adriano

**Comment by nguerrera** [comment]
>> A .NET Core assembly can't necessarily just be executed by invoking the assembly. Instead you need to use the CoreCLR host. Essentially dotnet run the output.

> I've tried that but it produced a different error; something like project could not be found 

`dotnet run` operates on projects. To run a managed assembly,  use `dotnet <assembly path>`. The assembly path must end in .exe or .dll.

Another issue, you will encounter is that the program needs a runtimeconfig.json.

I am able to get your repro to work by applying the following patch that:

1. Changes the output file extension to .dll
2. Copies the compiling program's runtime config to the compiled program's runtime config

**DISCLAIMER: This is still unsupported due to compiling against runtime assemblies.**

``` diff
@@ -12,7 +12,7 @@
         static void Main(string[] args)
         {

-            var outputFilePath = Path.GetTempFileName();
+            var outputFilePath = Path.GetTempFileName() + ".dll";
             Console.WriteLine($"Building into {outputFilePath}");

             var source = @"
@@ -55,6 +55,13 @@

             using (var outputAssembly = File.Create(outputFilePath))
                 compilation.Emit(outputAssembly);
+
+            var outputRuntimeConfigPath = Path.ChangeExtension(outputFilePath, "runtimeconfig.json");
+            var currentRuntimeConfigPath = Path.ChangeExtension(typeof(Program).Assembly.Location, "runtimeconfig.json");
+
+            Console.WriteLine($"Copying current {currentRuntimeConfigPath} to {outputRuntimeConfigPath}");
+
+            File.Copy(currentRuntimeConfigPath, outputRuntimeConfigPath);
         }
     }
 }
```

```
> dotnet run
Building into C:\Users\nicholg\AppData\Local\Temp\tmpE7.tmp.dll
Copying current D:\Temp\testcomp\bin\Debug\netcoreapp2.1\ConsoleApp1.runtimeconfig.json to C:\Users\nicholg\AppData\Local\Temp\tmpE7.tmp.runtimeconfig.json

> dotnet C:\Users\nicholg\AppData\Local\Temp\tmpE7.tmp.dll
Hello World
```

> Is there a way to programatically figure the folder that contains such assemblies ? (I would like to avoid hardcoding paths)

It's complicated as the reference assemblies in .NET Core come from nuget. 

There is feature that [Razor](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/) uses to allow it to compile at runtime. It would be rather involved to replicate fully, but the basis of it is `<PreserveCompilationContext>true</PreserveCompilationContext>` in the .csproj, which then copies references to a refs/ folder when you `dotnet publish`.  

In the .NET Core 3.0 SDK, we expect to put reference assemblies for the matching framework in a well-known location. This is not implemented yet.

**Comment by adrianoc** [comment]
Thanks for the response @nguerrera 

> dotnet run operates on projects. To run a managed assembly, use dotnet <assembly path>. The assembly path must end in .exe or .dll.

My bad. Actually I've tried both. I guess I've misread the error when running *dotnet <assembly path>*  (with the temp file name without **.dll** extension)

> I am able to get your repro to work by applying the following patch
> DISCLAIMER: This is still unsupported due to compiling against runtime assemblies.

I'll try later today.
This is a *toy* project so even though this approach is not supported it is ok for now :) (in the worst case I guess that, somehow, I can ask nuget the dotnet core installation path and derive the reference assembly path, i.e, I'd have to hardcode a relative path which should be ok)

> In the .NET Core 3.0 SDK, we expect to put reference assemblies for the matching framework in a well-known location. This is not implemented yet.

That would be nice

Thanks again

**Comment by adrianoc** [comment]
@nguerrera 

I manage to get it to work (with the caveats you mentioned) so I am closing this issue.

Thanks again.

**Comment by wilmerbarriosvilla** [comment]
En el SDK de .NET Core 3.0, esperamos colocar ensamblados de referencia para el marco de coincidencia en una ubicación conocida. Esto aún no se ha implementado.

en  net 7.0 ya esta esta caracteristica ?

**Comment by wilmerbarriosvilla** [comment]
esto funciona en maui net 7.0?
sample?
<PreserveCompilationContext>true</PreserveCompilationContext>
