### ISSUE TITLE
Is there a way to see the resulting 'green' tree right before the codegen?

### ISSUE THREAD

**Issue by d-dizhevsky** [dotnet/roslyn#30907]
Is there a way to see the results of lowerings and other syntax optimizations via public api's? 
They can be observed in generated IL **but** it would be handy to access an updated tree from code before that.

// I know that this is a sensitive topic and that green tree is not public for solid reasons, just asking

**Comment by CyrusNajmabadi** [comment]
> Is there a way to see the results of lowerings and other syntax optimizations via public api's?

SyntaxTree aren't themselves 'lowered' or 'optimized'.  I'm fairly certain that's what you're referring to since you've mentioned 'green' and 'syntax tree' several times :)

The way the compiler works internally is that the SyntaxTree is translated into a form we call "Bound Nodes".  This is a *separate tree* that is then operated on (i.e. Lowering/Optimizing/etc.).  It is definitely *not* a Syntax-Tree (or 'green').  Now, we currently expose these 'Bound Nodes' through the 'IOperation' API that was recently added.  However, you're getting only the original unlowered/unoptimized tree.

Returning the final lowered bound-nodes through IOperation was something that was always on the list to consider.  I'm tagging @mavasani @jinujoseph so this request can be tracked. 

--

Could you give examples of what you would use thsi for?  i.e.:

> it would be handy to access an updated tree from code before that.

Why would it be handy?  Thanks!

**Comment by d-dizhevsky** [comment]
> Why would it be handy?

Because right now for me, as a consumer, it is a black-box area and I would like to be able see how my code goes from A to Z all in one place (for whatever reasons). 

Now sure how these things (lowering and other optimizations) which happen behind the scenes actually tested but an open API would help to test them directly case-by-case? 

And also I would be able to try these kind of things (lots of edge cases) and see them in action all in one place without even having to leave the IDE
![image](https://user-images.githubusercontent.com/25821724/47880934-5eca2200-de2d-11e8-9172-3deccfcd90ca.png)

That said, for me it is just an option to explore the compiler's internals in the way I used to.

**Comment by CyrusNajmabadi** [comment]
> That said, for me it is just an option to explore the compiler's internals in the way I used to.

if you're working with Roslyn directly, why does it need to be a public API?  you can write whatever sort of APIs you want to just work with the BoundExpressions yourself... :)

**Comment by d-dizhevsky** [comment]
It is gonna be quite challengeable for someone less involved in roslyn's codebase to write a tool which would work with its internal API's since this set of things is hundred times larger than the set of public ones. If you google "roslyn get syntax tree" you will get 100% hit for a code snippet of ~5 lines of code but if you want to go deeper the time spent on that is gonna be hundred times bigger than profit. 

That's why I said 'handy', I even think it would be easier to generate the nodes based on the lowered/optimized IL than trying to hook into the compilation pipeline directly to see what they are 😄

**Comment by CyrusNajmabadi** [comment]
> It is gonna be quite challengeable for someone less involved in roslyn's codebase to write a tool which would work with its internal API's since this set of things is hundred times larger than the set of public ones. 

Sorry, how were you envisioning this woudl work otherwise? :)   If the 'lowered tree' is exposed... well, it would be that huge :)    So you have to deal with the hugeness no matter what.

>  I even think it would be easier to generate the nodes based on the lowered/optimized IL than trying to hook into the compilation pipeline directly to see what they are

I believe @nguerrera may have done that or looked into it.  Nick, am i misremembering?  Or did you have some sort of API that wrapped IL in IOperations?  Thanks!

**Comment by d-dizhevsky** [comment]
>  If the 'lowered tree' is exposed... well, it would be that huge :) So you have to deal with the hugeness no matter what.

That's the thing. If these "optimized" trees are exposed the end-user then would just consume them as a result of optimization in an "input-output" manner with some sort of determinism.
Otherwise, other than the "hugeness" of the trees themselves, he would have had to learn which roslyn's code invokes the optimization, when lowering happens and all that kind of things.

@CyrusNajmabadi 
But again, I might be wrong. And I also appreciate the time you've spent to discuss that :)

If @nguerrera has that sort of thing it would be great and save me some time :) otherwise I will probably try to write that by myself which is also not worst :))

**Comment by nguerrera** [comment]
> I believe @nguerrera may have done that or looked into it. Nick, am i misremembering? Or did you have some sort of API that wrapped IL in IOperations? Thanks!

I looked into it.  The *prototype* code can still be seen at https://github.com/Microsoft/binskim/pull/10

**Comment by gafter** [comment]
The answer to the question is: no, we do not have any API to expose the compiler's internal data structures representing executable code after lowering.
