### ISSUE TITLE
consider using HostDocumentServices like HostLanguageServices or HostWorkspaceServices rather than using IDocumentServiceProvider

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#30937]
we have concept of HostLanguageServices and HostWorkspaceServices that packages how these services are delived to us from Host.

consider using IDocumentServiceProvider same pattern.

**Comment by heejaechang** [comment]
I will tell in next design meeting you think it is not needed. we already had a design meeting for this and people involved all agree that it is needed and let's try this way. so, please don't repeat that you don't think it is needed since like I said, I hear that and I will tell people that you think it is not needed.

**Comment by CyrusNajmabadi** [comment]
> I will tell in next design meeting you think it is not needed

It's not that i think ti's not needed.  My questions stemmed entirely from: i'm not understand the use case, and it would be helpful to get clarity on that to help inform the need for this type.

AFAICT now, this exists because of a desire to go a more injection route instead of a query route.  I'm not actually hugely opposed to this idea.  I can see some benefits in it.  However, it does seem a bit 'wonky' given how we've done most of the rest of Roslyn.  We generally have gone the "mef import + query" route, but we seem to be going a different way entirely here.

I'm not against it per-se.  I'm just not necessarily for it either given that it seems somewhat unnecessary given existing patterns and practices.

**Comment by CyrusNajmabadi** [comment]
Anotehr way of stating is:  If we started going this route, i would expect to see the same things for things like project-level services, or workspace level services.  Namely that instead of discovery/lookup, we went more with direct injection.  I would prefer the mechanism be more consistent across the board.  But if people feel there really are strong reasons to go this different way for this one case, i'm open to hearing the reasoning :)

**Comment by heejaechang** [comment]
I dont get it. but you already said, you think it is not needed and unnecessary. if you are not understanding usage case, then why saying it is not needed?

**Comment by CyrusNajmabadi** [comment]
> I dont get it. but you already said, you think it is not needed and unnecessary. if you are not understanding usage case, then why saying it is not needed?

I'm said: based on everything i could pick up *so far*, it didn't *appear* to be necessary.  As such i *asked* for more information so i could make a more *informed* decision on things.

You then added more information explaining some of the decision making going on.  Based on that, i reiterated that while i didn't think this approach was truly necessary, i was also not actually against it.  

Right now i'm landing on the position of:
1. this seems odd, and feels out of place given how we've currently done workspace work.
2. i'm amenable to this design being hte one going forward.  But, if that were to happen, i would want to see a similar effort made toward our other 'Service-Factory' systems to bring them in line here.

Overall, my preference would be to stick with the existing patterns. But, i'm always ok with moving to new patterns, as long we do so in a *cohesive* manner.  What i'm generally *strongly against* are introducing ad-hoc one-off patterns for things.  IMO, it makes the Workspace and Roslyn IDE layers less understandable and makes it harder to maintain and move things forward.  The smaller number of concepts we have, and the more consistently they all work, the healthier the codebase. 

Thanks! :)

**Comment by CyrusNajmabadi** [comment]
Closing out as not actionable.
