### ISSUE TITLE
MapMarkuSpans in test utility can't distinguish {|P1:|}{|P2:|} and {|P2:{|P1:|}|}

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#30975]
this http://source.roslyn.io/#Roslyn.Services.Test.Utilities/Workspaces/TestWorkspace.cs,542 currently treat these 2 cases same
{|Projection1:|}{|Markup1:|} and {|Markup1:{|Projection1:|}|} 

it always treat Markup1 as the later.

**Comment by CyrusNajmabadi** [comment]
Both of those are 0-length spans.  How would you have wanted them to be treated? Thanks!

**Comment by heejaechang** [comment]
markup1 not include projection expansion in one case and include in the other case as the markup is written?

**Comment by CyrusNajmabadi** [comment]
Ah, interesting.  So you'd want there to be semantics around knowing that they were somehow nested.  I think you would have to customize the output of MarkupTestFile somewhat as `{|X:|}` is only represented as as a named position wherever that was found.  i.e. there's no info provided about how the original was written, and how it might have related to other named-spans.  

Seems like a nifty idea though! :)

**Comment by CyrusNajmabadi** [comment]
Note: MarkupTestFiles were never meant to really convey such richly structured information.  Primarily because at some point the markup becomes so intense that you can't really make out the code it is trying to present.  That's why, for example, we use Xml for Workspace/Project/Document literals.  IMO, xml is far better suited for hierarchical representation of relationships, and would like produce a much cleaner and easier to understand representation for things like projections.

Conversely, when you have large chunks of text, and you just wanted to way to delineate a small handful of things within it, that's where markup files shine.  Having an easy way to use `$$` to be the caret, or `[|...|]` to be a span, works really well.  IT means the test code is easy to read and understand, and you don't need to do something lke insert an actual `/*...*/` comment in your code which might then mean the code doesn't match the textual scenario you're trying to test.  

So, looking at this use case, Xml would likely be a much better choice.  Cheers!

**Comment by heejaechang** [comment]
actually, not following what you are saying.

I don't care much whether we keep our existing projection buffer test framework as it is and fix this issue or rewrite from the scratch to use xml.

but it should be able to distinguish these 2 cases so that people can write projection buffer test better.

**Comment by CyrusNajmabadi** [comment]
> actually, not following what you are saying.

Sorry, i'll try to be more clear:

1.  The Markup-test-format was never intended for complex scenarios like this.  It really was borne out of a need to just delineate spans in an extremely simple manner.  Most importantly, because it was an inline-markup format, it was essential that the syntax and use of it be very lightweight so that people could no lose track of what the actual code being marked-up was.  i.e. if i have:

```
@"class C
{
    void Foo($$int i)
    {
    }
}"
```

Then it's very clear what the intent of that is.  If that starts being cluttered with the need to distinguish things like `{|Markup1:{|Projection1:|}|}` then that starts making intent far less clear, and makes the test file too cryptic to warrant the use of the markup in the first place.

In other words: the point of markup is to serve *clarity* first and foremost.  If that starts going away, then other systems should be used.  That is why, for example, we don't use markup to represent things like workspace/projects/doc structure itself.  In a scenario where you need a richer, hierarchical system, using another technology is a far better choice.  

I was bringing this up because it seems like a *not good* idea for me initially to see that any part of the system would need to distinguish between `{|Projection1:|}{|Markup1:|}` and `{|Markup1:{|Projection1:|}|}`.  As i mentioned initially, from the markup test specification, these are identical.  And i mean 'literally identical'.  There is no sort of 'containment relationship' between named positions.  Indeed, it's not even clear what this would represent.  In the first case, `Projection1` is a named position (let's say `5`).  And `Markup1` is a named position also at `5`.  There's no real way in the markup system to indicate that `Markup` abuts `Projection1` isntead of being contained within it.  After all, they're just positions.  In both cases all four spans are at position '5'.  It was very intentional in the original design of hte test-format that it simply be spans, and anything like hierarchy was not part of it.

I hope that helps clear things up! :)

**Comment by heejaechang** [comment]
@CyrusNajmabadi sure that is how it works. that doesn't mean we shouldn't fix it.

also, nested markup works completely fine {|Markup1:xxx{|Markup2:xxx|}xxxx|} and I believe there are many usages of this form in the tests. also, nested and adjuscent marker also works completely fine.

it is just how the code is written on projection buffer expansion. and how markup span calculation is written around projection buffer expansion.

...

I am not going to go over how markup should be used or what you think it is clear and etc. I will just say sure, you do that way if that's what you want as long as you don't force whatever your definition of how it should be used or what is clear to other people.

**Comment by CyrusNajmabadi** [comment]
Tagging @jasonmalinowski

**Comment by CyrusNajmabadi** [comment]
Tagging @jasonmalinowski I've provided my thoughts on the matter as well as my suggestions on the paths forward i think would be the most successful.  Please accept the advice in the spirit with which it was given.  Thanks!

**Comment by jasonmalinowski** [comment]
Yeah, I don't see why we shouldn't just make this work. :smile:

**Comment by CyrusNajmabadi** [comment]
Closing out.  The specific test harness that benefits from this would be able to write helpers if necessary to ask if there was any nesting here.  It would not affect any of the existing helpers which find the above code identical.
