### ISSUE TITLE
give DynamicFileInfo in to RemoveDynamicFile

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#30974]
Task RemoveDynamicFileInfoAsync(ProjectId projectId, string projectFilePath, string filePath, CancellationToken cancellationToken);

**Comment by heejaechang** [comment]
also, see whether we can just ask them to return new DynamicFileInfo in event EventHandler<string> Updated;

**Comment by CyrusNajmabadi** [comment]
Is there are a concern about just having an appropriate API up front?  The reason is that at least now we can specify what it shoudl be.  however, if we ship this now, it will be super difficult in the future to change.  We know that that's how things normally land, and we just end up with technical debt because no one wants to touch it once it has shipped.  

Since we're adding this code right now... why not just factor the surface well and have our consumers adapt simply to it when they get the first drop that contains this?

**Comment by CyrusNajmabadi** [comment]
Closing out as not actionable.
