### ISSUE TITLE
Please provide the C# Specification in PDF instead of DOCX

### ISSUE THREAD

**Issue by nvivo** [dotnet/roslyn#31]
When going to the [C# spec download page](https://www.microsoft.com/en-us/download/confirmation.aspx?id=7029), the file provided is a docx. I don't have office, so I need to upload that to google drive and convert to something else to read.

It is really not a big deal, but it would be nice of you to just published the file in PDF instead, which everyone can open anywhere.

**Comment by dsaf** [comment]
Docx is an open standard and there is a free viewer available:


http://en.wikipedia.org/wiki/Office_Open_XML

http://www.microsoft.com/en-us/download/details.aspx?id=4

http://superuser.com/questions/141435/is-there-anything-to-open-docx-documents-on-linux-ubuntu

**Comment by paulomorgado** [comment]
I'd which there was a website we could link to.

**Comment by am11** [comment]
Why not simply [embed the docx](http://windows.microsoft.com/en-us/onedrive/embed-files-website-blog) via onedrive in GitHub [repo's wiki](https://github.com/dotnet/roslyn/wiki)? 

Something like:

```html
<iframe
  src="https://onedrive.live.com/embed?cid=..."
  width="100%" height="100%" frameborder="0"
  scrolling="yes"
></iframe>
```

I have seen this practice used on http://isocpp.org/ (for excel files) and some WordPress blogs.

**Comment by nvivo** [comment]
@dsaf this has nothing to do with open formats, it has to do with how easily I can look at it, and PDF is much more common than DOCX.

A website would also be great. Most modern languages have them instead of a document, and would be even easier to read than a PDF.

**Comment by JoergWMittag** [comment]
Scala has moved its spec into a set of LaTeX-enhanced Markdown files right into the compiler repository: https://github.com/scala/scala/tree/2.12.x/spec The website generated from this looks nice: http://scala-lang.org/files/archive/spec/2.11/

Converting the existing spec would probably be a week's worth of admittedly tedious and very boring work for an intern.

Some benefits other than availability in an easy-to-convert format (Markdown can be converted to pretty much anything these days, the embedded LaTeX makes it slightly harder, but a quick skimming of the existing C# spec seems to indicate that LaTeX might not even be needed) are that spec changes can be submitted and reviewed as pull requests just like code, and they can be taken directly from proposals, because those are already written in Markdown anyway.

**Comment by MadsTorgersen** [comment]
Long term we are merging the Microsoft C# spec with the ECMA Standard, which is provided in PDF.
