### ISSUE TITLE
`GetTypeInfo().Type` should return `null` for `default` literal

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#31029]
From Neal (in https://github.com/dotnet/roslyn/issues/26027):
> I think both the spec and design notes are clear about the language intent: default is typeless and gets a type on conversion.

```C#
        [Fact]
        public void AssignmentToInt()
        {
            string source = @"
class C
{
    static void Main()
    {
        int x = default;
        System.Console.Write(x);
    }
}
";
            var comp = CreateCompilation(source, parseOptions: TestOptions.Regular7_1, options: TestOptions.DebugExe);
...

            var tree = comp.SyntaxTrees.First();
            var model = comp.GetSemanticModel(tree);
            var nodes = tree.GetCompilationUnitRoot().DescendantNodes();

            var def = nodes.OfType<LiteralExpressionSyntax>().Single();
            Assert.Equal("System.Int32", model.GetTypeInfo(def).Type.ToTestDisplayString()); // should be null
            Assert.Equal("System.Int32", model.GetTypeInfo(def).ConvertedType.ToTestDisplayString());
...
        }
```

**Comment by Neme12** [comment]
I like this but I just wanted to point out that this seems to have been an intentional decision after @AlekseyTs  stated his concerns here: https://github.com/dotnet/roslyn/pull/17205#discussion_r102340554 arguing that the GetTypeInfo().Type should match the type of the constant value. I think an ideal scenario would be that the Type was null and constant value didn't exist, however there would be another API for ConvertedConstantValue (or something like GetConstantValueInfo().ConvertedValue) which would match the ConvertedType and would be present on default literals.

Such an API could be useful on its own because it seems this functionality is currently missing. For example someone might want to know that the converted constant value of `'A'` in `'A' + 1` is 65.

The only concern with this is that removing the constant value from a default literal could be a huge breaking change. However removing the type will be a breaking change too, breaking a lot of IDE code I imagine. (Actually, now that I'm thinking about it, removing the type will be a much larger break, I can't think of a scenario where IDE uses the constant value).

also tagging @gafter for thoughts

**Comment by Neme12** [comment]
@gafter @AlekseyTs What do you think about my proposal for either `GetConstantValueInfo().ConvertedValue` or `GetConvertedConstantValue()`?

**Comment by jcouv** [comment]
I have a PR revising conversions on `default` literal. As part  of that work, I tried changing the behavior of `GetTypeInfo(...).Type` for `default`, but saw that had significant impact on the IDE code. To minimize pain for API consumers, I'll keep the current public behavior (`.Type` returns the target-type instead of the `null` natural type), maintaining compatibility.
