### ISSUE TITLE
Binary Name Conflict with Chicken Scheme

### ISSUE THREAD

**Issue by octonion** [dotnet/roslyn#31058]
Chicken Scheme and the C# compiler have the binary name conflict "csc". I'm not quite sure how to report this as an issue, so I'm filing an issue with both Rosyln and Chicken Scheme. It could be argued this is an issue with the particular Linux packages, but I believe they're simply copying the existing binaries or making symbolic links within /usr/bin.

**Comment by jaredpar** [comment]
Can you elaborate a bit on what the conflict is and what errors it is causing? There really shouldn't be any binaries named `csc` in the .NET SDK at the moment. It's possible one will be showing up at some point in the future but right now the actual shipped component should be `csc.dll`.

**Comment by octonion** [comment]
I'm running Ubuntu 18.04, and the apt package manager indicates the conflict is "/usr/bin/csc" between the packages "mono-rosyln" and "chicken-bin" (Chicken Scheme).

I have:

/usr/bin/csc: Microsoft (R) Visual C# Compiler version 2.8.2.62916 (2ad4aabc)
mono-roslyn: 5.16.0.179-0xamarin1+ubuntu1804b1

**Comment by jaredpar** [comment]
Thanks for the extra info. This looks like it's a Mono issue then in how they re-package and re-distribute the compiler at the moment. CC @marek-safar 

This may become a problem for us in the future at some point though. For instance if we ever decide to make `csc` a first class command instead of letting it be primarily driven via `dotnet build`.

**Comment by marek-safar** [comment]
@jaredpar we are aware of the problem, the issue is tracked on our side as https://github.com/mono/mono/issues/9056
