### ISSUE TITLE
async completion. re-consider changes TestNavigationBeforeCompletedComputation 

### ISSUE THREAD

**Issue by ivanbasov** [dotnet/roslyn#31131]

**Comment by CyrusNajmabadi** [comment]
Note: this is a *super* critical scenario.  And we should not check in the new completion without this.  Languages may take quite a while to produce completions.  For example, TS has to remote requests over to another process (which may be rescanning the filesystem).  F# may be executing type-providers which are calling over to the network.  If the user types something that has kicked off completion, but then moves, it's critical that their navigation be respected, and not captured by the completion session.

**Comment by ivanbasov** [comment]
@CyrusNajmabadi , I have re-reviewed the test scenario (https://github.com/dotnet/roslyn/blob/master-vs-deps/src/EditorFeatures/Test2/IntelliSense/VisualBasicCompletionCommandHandlerTests.vb#L487). 
I'd consider the new behavior as an improvement.

**Scenario**
```
Class Program
    Shared Sub Main(args As String())
        Program$$
    End Sub
End Class
```
User types `.Ma` and move the caret to the left by one position.

1. With a fast provider, we expect that a completion appears and it is still displayed while moving the caret by one position.
2. With a slow provider, the existing completion considers that moving character while making calculations should dismiss the completion even if the caret is inside the applicable span.
3. The new completion puts commands in a queue, then when the slow provider responds, the new completion moves and character by one position and keep the completion.

I could not understand what is the reason to dismiss the completion for users: if you press the left arrow key fast enough, the completion is dismissed; if you do the same faster, the completion is still displayed.
Why should we dismiss the completion?

**Comment by CyrusNajmabadi** [comment]
Note: the 'dismissal' behavior was very much intentional, and was justified to be better behavior.  Here's why:

The critical thing is to consider this from the perspective of the user.  For the user, completion is either visible or it isn't.  If it's not visible, then, effectively, navigation operations intuitively feel like they should affect the caret on the buffer and should have no effect on something that is invisible that we *may* decide to show in the future.

However, if completion is visible, then the user can see it and can see it has focus.  in that world, the movement of the caret is understood to be affecting the visible completion box.


So, the behavior we had was: if navigation happens, but completion is not visible, respect that hte user is trying to nav the document, and do not capture just because we may be showing completion in the future.

If you do capture the nav gesture, then that puts the user in the perspective of having to understand when we've kicked of async completion, as well as understanding if that async completion ends up computing something (in which case nav will affect completion), or ends up computing nothing, in which case nav goes into this document.  This means users have to understand our completion model *and* know if it's going to produce results.  Both of these are onerous, and go against the intuition that navigation should happen *immediately* based on what the user can actually see.

--

On top of this, we actually had the above model for a short while and it was unpleasant.  Users often do the following:

1. jump to a location in the code
2. quickly make edits
3. navigate somewhere quickly with the caret.

This would end up always capturing their movement, forcing them to dismiss completion manually.  It actually felt bad, and is one of hte reasons we made this design change explicitly.

--


Does that help clear htings up?  It's a *strong* belief i have that we should never capture nav keystrokes *before* completion is visible.  It just doesn't fit any sort of sensible user intuition about what's goign on in their code.  If the text buffer has focus, and completion is not visible, then navigation should respect that and just navigate.

**Comment by CyrusNajmabadi** [comment]
I like that conclusion.  However, i would prefer this bug not be closed.  otherwise, it's too easy to lose track of this.  We should close this when the dependent editor bug is closed.

**Comment by ivanbasov** [comment]
Thank you, @CyrusNajmabadi ! OK. Let us reopen it and keep active until the dependent VSO issue is not resolved.

**Comment by ivanbasov** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/33621
