### ISSUE TITLE
async completion: DebuggerTextView should not save topBuffer for the editor

### ISSUE THREAD

**Issue by ivanbasov** [dotnet/roslyn#31189]
This new code in DebuggerTextView looks suspicious:
 ```
     // The editor requires the current top buffer.
            _innerTextView.Properties.AddProperty(CompletionRoot, bufferGraph.TopBuffer);
```

Here is how Editor consumes it:
// In certain scenarios, TextView.TextSnapshot is not the appropriate snapshot to use.
// For example, in the watch window (C# debugger), TextView.TextSnapshot corresponds to the single line for the expression.
// Roslyn uses the property bag to indicate the correct snapshot to use.

@AmadeusW responded:

> Correct, weird projection things are happening. To recap meetings we had about this issue:
> Roslyn overrides implements DebuggerTextView which is not a standard text view (built using Editor APIs). In Roslyn’s implementation, the top snapshot is the single line visible in the debugger UI. If Editor built this TextView, the top snapshot would contain the entirety of other buffers, including the front matter (usings), the line visible in the UI, extra semicolon and the rest of the document. We would then use projection to display just the single line. Logic that finds appropriate buffers would be simplified, such that we’d simply map down from this top buffer.
> Roslyn is not refactoring the way DebuggerTextView works, so we need to work around this arguably bad design.
>

**Comment by CyrusNajmabadi** [comment]
@jasonmalinowski do you remember why we did hte projections here in this way?

**Comment by jasonmalinowski** [comment]
@CyrusNajmabadi, yeah, it's a mess and chatting with @ivanbasov we didn't have a better answer. The screwy situation is the immediate window, which unlike the interactive window, isn't a well behaved projection. Basically, we're supposed to do completion/everything on the last line of the immediate window, but instead of it being the case where the last line is a subject buffer being projected in...it's just a really big buffer. So we create an elision buffer for that last line and then have a fake ITextView that pretends there's just the last line, and we set this to redirect.

I don't have a better answer for that, other than to make the immediate window a proper projection buffer design like the interactive window.

**Comment by CyrusNajmabadi** [comment]
Yikes...

That sounds like a lot of work.  While icky, i would be ok with an interim hack to get things up and running.  Up to you guys!

        -- Cyrus

**Comment by tmat** [comment]
> I don't have a better answer for that, other than to make the immediate window a proper projection buffer design like the interactive window.

Immediate Window UI needs to die and be replaced by Interactive Window UI.

**Comment by AmadeusW** [comment]
The Editor team is here to help when you have any questions about buffer graph etc.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
