### ISSUE TITLE
"using" alias directive adds assembly reference even if the aliased type is not used. 

### ISSUE THREAD

**Issue by jechter** [dotnet/roslyn#31192]
**Version Used**: 

Microsoft (R) Visual C# Compiler version 2.6.0.62309 (d3f6b8e7)

**Steps to Reproduce**:

1.  Build this `HelloWorld.cs` file using `csc HelloWorld.cs`:

```
using System;
using sxn = System.Xml.XmlNode;
namespace HelloWorld
{
    class Hello 
    {
        static void Main() 
        {
            Console.WriteLine("Hello World!");
        }
    }
}
```

2. Inspect the assembly references in the resulting `HelloWorld.exe` using ILSpy or similar tools.

**Expected Behavior**:

`HelloWorld.exe` should not reference `System.Xml`, because nothing from `System.Xml` is _actually_ being used (even though we have declared this alias: `using sxn = System.Xml.XmlNode;`).

**Actual Behavior**:

`HelloWorld.exe` contains an assembly reference to `System.Xml`.

**Comments**

It is not clear to me if this should be considered a bug, as I don't know if this behavior is specified anywhere. But:

1. This is a regression in behavior from Xamarin's `mcs` compiler, which will not emit such a reference in this case.

2. This is causing issues for us (Unity) further down the line, as we use Mono's IL Linker (or our fork of it) to remove unused code to optimize build sizes. In a case like this, it will detect that the referenced assembly is not actually being used, and remove it. Now we end up with a reference to a missing assembly, which causes issues in other tooling. We can work around these issues, but at the core, I feel that this may be incorrect behavior in roslyn.

**Comment by jechter** [comment]
To clarify, if I remove this (unneeded) line 
```
using sxn = System.Xml.XmlNode;
```

from `HelloWorld.cs`, then the `System.Xml` reference is not emitted, and everything works, so this problem is easy to work around for our users. Still, we'd like to have our pipeline work with any code  built with it.

**Comment by tmat** [comment]
This behavior is by design as the reference is used by the PDB. The PDB includes all usings so that the they are available when evaluating expressions during debugging.

>  In a case like this, it will detect that the referenced assembly is not actually being used, and remove it.

Sounds correct as long as it also eliminates the debugging information. It'd be a bug in the IL Linker if it keeps the debugging information but eliminates the reference.

> Now we end up with a reference to a missing assembly

I'm not sure what you mean by this. Isn't the presumption of the issue that there is no reference to this assembly in the DLL?

**Comment by tmat** [comment]
@marek-safar You mean when not writing out PDB? We don't want the binary to differ based on whether we write PDB or not.

**Comment by tmat** [comment]
@sharwell It's similar to removing an unused method but leaving debugging information for it in the PDB. The PDB would then reference token that does not exist in the DLL. 

There is no point in removing the AssemblyRef from the DLL. AssemblyRef itself doesn't have any effect on runtime. It just assigns a number (token) to an assembly reference specification. Until that token is used in method body IL (thru TypeRef) the assembly is not gonna be loaded.

**Comment by marek-safar** [comment]
@tmat no I meant when I do `/debug- /optimize+`, in this case, I don't see any reason why the assembly reference has to be there (btw, if you use `/refonly` it's not there).

**Comment by tmat** [comment]
The compiler produces 3 flavors of DLLs: fully optimized (`/optimize+`), optimized as long as it doesn't affect debuggability (`/debug+ /optimize+`), unoptimized (`/optimize-`).

`/debug-` means without writing out PDB - that was what I was talking about. The compiler emits the same DLL for `/debug-`, `/debug:full` and `/debug:portable`.

`/optimize+` does not mean without debugging info - we still emit debugging info for stepping and evaluation as long as it does not affect perf. We want optimized code to be debuggable as well. Adding an assembly reference does not affect performance, while removing it reduces debuggability.

It's not there for `/refonly` since there are no method bodies emitted to the reference assembly. So no code to debug.

**Comment by tmat** [comment]
@gafter Yes.
