### ISSUE TITLE
Proposal: Namespace resolution could be improved

### ISSUE THREAD

**Issue by MatthieuMEZIL** [dotnet/roslyn#3123]
This code does not compile

``` c#
namespace N1.N2
{
}

namespace N2
{
    public class C1 { }
}

namespace N1
{
    class C2 : N2.C1
    {
    }
}
```
Error	CS0234	The type or namespace name 'C1' does not exist in the namespace 'N1.N2' (are you missing an assembly reference?)

We can use `class C2 : global::N2.C1` to fix the error.

However, I think that because the type C1 does not exist in N1.N2 namespace, the compiler should be able to determine that it should use N2.C1 instead (which can be done without breaking backward compatibility).

I think we have an similar behavior with extension methods. If the compiler cannot find the method in the instance type, it tries with extension methods using namespace prioritization.

**Comment by gafter** [comment]
When resolving a type name `X.Y`, the language specifies that first the name `X` is resolved, and then `Y` is resolved as a member of `X`. That works well for extension methods; the type of the left-hand-side is first determined, and then the meaning of the method name may look in more than one place, but we never reconsider the meaning of the left-hand-side.

However, this requests that we reconsider the meaning of the left-hand-side. In the example, the base class of `C2` is written `N2.C1`. The name `N2` unambiguously refers to the nested namespace `N1.N2`, because we are inside of `N1`, and `N1.N2` therefore *hides* the name `N2` from the enclosing namespace. Once that name is resolved, the language (and compiler) can see that there is no type `C2` that is a member of that. So it is simply an error.

A language specification to "fix" this would necessarily be quite messy. I don't see it happening.

**Comment by gafter** [comment]
@MadsTorgersen Please reopen if you disagree.

**Comment by paulomorgado** [comment]
I don't think this kind of backtracking would be hard to do.

But de compile time cost of the compiled code would be potentially higher than the cost of implementing it in the compiler.

The example hides the complexity and memory needs by providing a use case of a depth of just 2. What if it as 3? Or 4? Or 10?

**Comment by MatthieuMEZIL** [comment]
@paulomorgado : I'm not sure that the namespace depth changes a lot the complexity but I completely agree with the fact that it won't be hard to implement but it could make the compiler really slower which is not good.
However, I think that we could imagine an analyzer with code fix (adding global::) for this.

**Comment by paulomorgado** [comment]
@MatthieuMEZIL, in order for this to work, you have to treat every namespace segment as a unit. And the same for nested classes and nested members, or it would be confusing for the user.

Although it would not be the hardest thing to code in Roslyn, it would definitely make it considerably slower depending on the source code.
