### ISSUE TITLE
Re-use existing functionality in my code fix provider?

### ISSUE THREAD

**Issue by emilefokkema** [dotnet/roslyn#31285]
I apologize in advance if this is the wrong place for my question.

I wrote a `DiagnosticAnalyzer` that generates a certain diagnostic. Now I would like to write a `CodeFixProvider` that reacts to this diagnostic by offering neither more nor less than the existing "Introduce local". So my question is: can I re-use the existing functionality of, say, an `IIntroduceVariableService` in my `CodeFixProvider`?

**Comment by CyrusNajmabadi** [comment]
@emilefokkema Nothing to apologize for :)

1. you cannot reuse IIntroduceVariableService currently.  However, there may be other services that can help out.
2. There is a channel over at gitter.im/dotnet/roslyn that can be useful for asking questions and getting help.  You'll almost always get responses in a short time (or within a day at hte worst).  However, Thanksgiving is coming up, so that may not be the case for the next few days.

**Comment by CyrusNajmabadi** [comment]
Closing out as answered.
