### ISSUE TITLE
Standardize on refactoring location code

### ISSUE THREAD

**Issue by ryzngard** [dotnet/roslyn#31286]
Per discussion in #31183 , we have similar capabilities across a few refactorings. We should think about how we can reuse code to always enable new code generation, when it makes sense, to target the same locations.

**Comment by heejaechang** [comment]
we have these 2 UIs

one from extract interface
https://user-images.githubusercontent.com/475144/48518028-1e02dd80-e81d-11e8-8b39-286414173c15.png

and this

one from generate new type
https://user-images.githubusercontent.com/1333179/48660001-6681ed00-ea0f-11e8-86bb-303c251a7703.png

we should merge these 2 to 1 and share code for UI/Model and file handling.

**Comment by heejaechang** [comment]
one from generate new type lets one to choose

1. projects to generate new file (regardless of what content is in the file)
2. in the project selected, folders the new file should be in with a file name user wants to + suggestion on the default file name.
or 3. in the project selected, existing files the content should be inserted including current file.

...

new code added to the extract interface, just do 1 thing. adding the content to existing file. by sharing the code in generate new types, we can get

1. same UI for all refactoring/fix so that user can get used to.
2. same abilitis for all refactoring/fix. and adding new ability improve all existing ones. (all the benefit ones get by sharing)
3. no need to worry about the file handling in new code generation by just utilizing this helper.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
