### ISSUE TITLE
SyntaxNodeAnalysisContext.ContainingSymbol points to wrong Symbol

### ISSUE THREAD

**Issue by pamidur** [dotnet/roslyn#31292]
**Version Used**: 
Microsoft.CodeAnalysis.Analyzers 2.6.2
Microsoft.CodeAnalysis.CSharp.Workspaces 2.10.0

**Steps to Reproduce**:
1.  Code like 
``` c#
   public class MyAttribute : Attribute{}

   public class TestClass{
       public void Do( [MyAttribute] string data) {}
   }
```
2. Define DiagnosticAnalyzer like
```c#
    public override void Initialize(AnalysisContext context)
    {
        context.RegisterSyntaxNodeAction(AnalyzeAttribute, SyntaxKind.Attribute);
    }
    private static void AnalyzeAttribute(SyntaxNodeAnalysisContext context)
    {
        var symbol = context.ContainingSymbol;
    }
```

**Expected Behavior**:
symbol is `IParameterSymbol` which points to parameter `data`
**Actual Behavior**:
symbol is `IMethodSymbol` which points to method `Do`

**Comment by CyrusNajmabadi** [comment]
Parameters are never containing-symbols.  This is by design.

**Comment by pamidur** [comment]
This is very confusing. IParameterSymbol is ISymbol, the same as IMethodSymbol. And containing symbol for the attribute is the parameter and not the method.
Anyway, could you please suggest a workaround for this? I need somehow get the real owner of the attribute.

**Comment by CyrusNajmabadi** [comment]
> Anyway, could you please suggest a workaround for this? I need somehow get the real owner of the attribute.

The method symbol, walk the parameters for the one whose syntax contains the attribute syntax you have.

**Comment by CyrusNajmabadi** [comment]
Alternatively, simply get the parent of hte attribute, and call `semanticModel.GetDeclaredSymbol` on it.

**Comment by pamidur** [comment]
So loop through parameters. I got it.

Still this sounds like very bad design, how come looking for an attribute in types I got a type, looking for an attribute in methods I dot a method, looking for an attribute in parameter I got method again?

**Comment by CyrusNajmabadi** [comment]
>  I got method again?

Because that's how the Roslyn semantic model works.  The container gives you something that can contain symbols.  These are things like Methods (whch can contain parameters), Types (which can contain members), Namespaces (which can contain namespace or types), etc.

> Still this sounds like very bad design

This has been the design since V1.  Even if it were a problem, there's nothing that can be changed about it now given that lots of code depends on this behavior.

**Comment by pamidur** [comment]
> 
> 
> Alternatively, simply get the parent of hte attribute, and call `semanticModel.GetDeclaredSymbol` on it.
```c#
context.SemanticModel.GetDeclaredSymbol(context.Node.Parent);
```
returns `null`

**Comment by CyrusNajmabadi** [comment]
by parent, i meant the ParameterSyntax

**Comment by pamidur** [comment]
Thanks, it works.

**Comment by mavasani** [comment]
@CyrusNajmabadi is correct - this is by design. Ideally, once we implement https://github.com/dotnet/roslyn/issues/18198, which should expose the symbol to which attribute is applied, you can get a uniform semantic view for attributes. Until then, you should take the approach that Cyrus recommended.
