### ISSUE TITLE
Suggestion: Replace GetType with typeof for structs

### ISSUE THREAD

**Issue by YairHalberstadt** [dotnet/roslyn#31318]
When `T` is a struct, and `inst` is an instance of `T`,

Then `inst.GetType()` will always return the same value as `typeof(T)`.

However `inst.GetType` requires boxing the struct, and so has a performance impact compared to the `typeof` operator.

I would suggest that therefore roslyn could statically replace calls to  `inst.GetType()`  with `typeof(T)`.

This does have a (minor) performance advantage. For example compare the results of this benchmark:

```csharp
private Type result;

[Benchmark]
public void GetType()
{
	for (int i = 0; i < 1000; i++)
		result = i.GetType();
}

[Benchmark]
public void TypeOf()
{
	for (int i = 0; i < 1000; i++)
		result = typeof(int);
}

  Method |     Mean |     Error |    StdDev |  Gen 0 | Allocated |
-------- |---------:|----------:|----------:|-------:|----------:|
 GetType | 5.829 us | 0.0864 us | 0.0722 us | 5.7144 |   24000 B |
  typeof | 1.903 us | 0.0426 us | 0.0356 us |      - |       0 B |
```

**Comment by YairHalberstadt** [comment]
@CyrusNajmabadi
On the other hand, I'm guessing this is almost trivial to add in at the Roslyn level, but probably significantly more risky at the runtime level.

An advantage of doing this at the runtime level though is that you can than do this for generic types which are not constrained to a struct as well.

**Comment by CyrusNajmabadi** [comment]
> On the other hand, I'm guessing this is almost trivial to add in at the Roslyn level, 

It's not clear to me that it would be.  Is it guaranteed anywhere that this is a safe optimization to make when you don't know the final runtime your code will run on?  Is it specified that .GetType and typeof must return the same System.Type instance?

> but probably significantly more risky at the runtime level.

That seems highly unlikely to me.  The jit certainly is already setting up things where it knows the receiver is a struct, and it knows that this is a call to this specific .GetType method.  At that point, it can literally just replace that entirely with teh result.  This sort of optimization is a common sort of thing that jits do (chakra/v8/etc. are chock full of this sort of thing).  Being able to remove an actual runtime computation with the result is something Jits are good at doing in a low-risk fashion, especially when the check you need to make is simple.

Is there a reason you think this would be risky for the runtime?  You might want to run it by them to see how they feel.  My guess is that they'd take a PR from you if you even coded this up yourself.

> An advantage of doing this at the runtime level though is that you can than do this for generic types which are not constrained to a struct as well.

Indeed. And for things like sealed types (though perhaps that isn't safe due to potential reflection shenanigans).

**Comment by YairHalberstadt** [comment]
@CyrusNajmabadi
Thanks for your advice. I'll suggest it there then.
I tested it for sealed types, and it was no faster.

**Comment by CyrusNajmabadi** [comment]
These look relevant: 
https://github.com/dotnet/coreclr/issues/14304
https://github.com/dotnet/coreclr/pull/14381

**Comment by CyrusNajmabadi** [comment]
> However inst.GetType requires boxing the struct, and so has a performance impact compared to the typeof operator.

It looks like this code is there to try to prevent that:
https://github.com/dotnet/coreclr/pull/14381/files#diff-edc46b80f57431489a82311948a8234dR3606

Maybe that only works for generic T's though?  If it's not working just for primitive types, it might be worth asking coreclr if it can be expanded out to that case.

**Comment by CyrusNajmabadi** [comment]
Hrmm... I feel like this code should be doing what you're asking for:

>https://github.com/dotnet/coreclr/blob/5e4e286ea2bffa4a5cb2467721ed89f27959d253/src/jit/importer.cpp#L3673-L3698

**Comment by YairHalberstadt** [comment]
Closed in favour of making this a runtime feature

**Comment by YairHalberstadt** [comment]
I just tested this on .Net Core 2.1 and the struct isn't boxed, so this is already done.

**Comment by CyrusNajmabadi** [comment]
Hooray! :)
