### ISSUE TITLE
don't create partial solution when it is not actually needed

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#31547]
currently, we have this
http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Workspace/Solution/SolutionState.cs,1645

that does some wire up to make a partial solution.

by digging through a bit, it looks like most of the time, except certain obvious cases such as solution load, solution reload, configuration changes, branch switch, source control synching and etc that happen rarely compared to more common cases such as typing, the solution is just missing last char typed by a user. so actually no point of doing all those forking except those rare cases mentioned above.

we should refactor this code so that we only do partial solution work if there is truly a lot of pending work for the solution.

**Comment by CyrusNajmabadi** [comment]
Could you clarify this bit:

> we should refactor this code so that we only do partial solution work if there is truly a lot of pending work for the solution.

So we would still do the partial-work during solution load?  If so, what benefit would we be getting?  Thanks!

**Comment by heejaechang** [comment]
not creating partial solution unnecessarily.

**Comment by heejaechang** [comment]
first we dont need to create partial solution. second, since it is now used less often, we can see whether we can completely remove it.

**Comment by CyrusNajmabadi** [comment]
>  since it is now used less often, we can see whether we can completely remove it.

Would we be able to tell that without needing to make this change?  We could simply have the telemetry about how often it is used during solution load.  That would be enough right?

> first we dont need to create partial solution

I'm not seeing how that benefits us since we already have the code to do this.  I'd actually prefer as much code as possible go through teh same paths to get good coverage.  Otherwise we risk having things slip through because we do things differently.   Uniformity helps with preventing that sort of thing :)

**Comment by heejaechang** [comment]
> Would we be able to tell that without needing to make this change
no, we will need to make the change to see how often we get into truly partial mode. 

..

sure, you can have your opinion. so, noted and team will consider that when we discuss this. I opened the issue as I believe what should happen.

**Comment by CyrusNajmabadi** [comment]
Could you clarify why we would need to make changes in order to determine this?  It doesn't seem clear to me.  

> sure, you can have your opinion. 

I'm not really stating it as an opinion.  I'm literally just saying: we could figure out X without doing Y, so why do we need to do Y first?  That's all :)  If htere is a reason, i'm totally ok with it, i'm just trying to understand what that reason is.  If there isn't such a reason, then it seems like it would be more effective to just figure out X right now without a potentially problematic change.

Thanks :D

**Comment by CyrusNajmabadi** [comment]
Also, i'm available to chat over gitter if that would help brainstorm in this area faster :)

**Comment by CyrusNajmabadi** [comment]
closing out as not planned.
