### ISSUE TITLE
API to retrieve symbol naming preferences is not public

### ISSUE THREAD

**Issue by IanKemp** [dotnet/roslyn#31655]
Please refer to https://github.com/dotnet/roslyn/issues/22884#issuecomment-445173009 and https://github.com/JosefPihrt/Roslynator/issues/473#issuecomment-445164565 for my current investigations on this.

tl;dr people who write refactoring tools need access to user-specified options that control names of identifiers, and the API for this (which, as far as I can tell, is `Microsoft.CodeAnalysis.Simplification.SimplificationOptions.NamingPreferences`) is internal. @CyrusNajmabadi commented "Maybe something can be made available once .editorconfig support is moved down the compiler layer" but I'm not entirely sure why that is necessary and would entail, so I guess all I'm asking for is a spitball estimate on when we can expect this (or another) API to expose that information.

**Comment by CyrusNajmabadi** [comment]
This would need to go through an API proposal.  in general, the reason we don't just make things public is because it increases maintenance costs and locks down our ability to change things in teh future.  We can open things up, but we have a process that requests need to go through to make sure the appropriate people weigh in and the right API shape is determined and shipped.
