### ISSUE TITLE
Add Grammars To Documentation

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#3169]
Would it be possible to add the language grammars for C# and VB.net to the available documentation?

**Comment by AdamSpeight2008** [comment]
Asking because I can only seem to find VB11 and C#5

**Comment by gafter** [comment]
We're still investigating how best to ship the language specifications.

**Comment by AdamSpeight2008** [comment]
@gafter 
I working on creating text file of just the grammars as based on the two `*.doc` that ship with VS2015RC. If I were to make the publicly available I think it is only appropriate to the include copyright / license and attribution within them. I don't know what license etc (will cover it).

Another option is to have another Git Repo `dotnet/roslyn grammars/` to which I could submit a PR to.
Or should I do PR to this repo with them in documentation section?

**Comment by gafter** [comment]
@AdamSpeight2008 You'll have to consult with your own lawyer for legal advice on what part of the VS2015RC documentation you can copy, make derivative works of, and publish. I am not aware of any permission grant in those documents that would allow you to do what you're suggesting, but even if I were, I am not a lawyer (and even if I were, I'm not *your* lawyer).

However we are investigating re-releasing the specifications in the open.

**Comment by AdamSpeight2008** [comment]
My goal is to have the language grammar itself accessible via api  
```
<grammar("hh ::= ( ('0'|'1') '0'-'9' ) | ('2' '0'-'2')">
<grammar("mm ::= ('0'-'5')('0'-'9')>
<grammar("ss ::= ('0'-'5')('0'-'9')>
<grammar("time ::= hh ':' mm (':' ss)?>
<grammer("literal-time ::= '#' time '#'">
```

**Comment by AdamSpeight2008** [comment]
I've started a [repo](http://www.github.com/AdamSpeight2008/Grammars).

**Comment by niemyjski** [comment]
+1 please release the grammars

**Comment by BillHenning** [comment]
Guys the formal specs/grammars were requested for the new C#/VB versions back in May here and VS 2015 RTM still ships with outdated old version specs.  When and where can we get the updated specs/grammar?  We really need this for our products so that we can accurately make changes to our C#/VB parsers.

**Comment by gafter** [comment]
@mads @ljw1004 Do either of you have any insight on when or how our customers will have access to the formal grammars for C# and VB?

**Comment by BillHenning** [comment]
Guys, any word on this?  We have customers asking for us to update our C#/VB parsers to understand the latest syntax and really need the formal grammar updates.  Otherwise we have no reliable specs to go on.

**Comment by niemyjski** [comment]
+1

    _____________________________

**Comment by gafter** [comment]
@MadsTorgersen The natives are restless.

**Comment by niemyjski** [comment]
As a born native I take offense to that, a quick resolve would make me happy again.

**Comment by ejsmith** [comment]
Yes, I don't understand why the entire language has gone open source, but the spec hasn't been updated. Seems kind of ridiculous.

**Comment by gafter** [comment]
@ejsmith Yes, I also hate it when people don't give me enough stuff for free.

**Comment by niemyjski** [comment]
@gafter pretty uncalled for and rude comments from a .NET Foundation member... 

**Just found out what I was looking for [Contributor Code of Conduct](http://www.dotnetfoundation.org/code-of-conduct) sub item #4**

> Public or private harassment

**Comment by ejsmith** [comment]
Yeah, I'm not trying to start trouble, but C# 6 has been out for quite a while now. And C# is an open ECMA standard. Seems like the spec should be available.

**Comment by gafter** [comment]
@niemyjski How can agreement be construed as harassment?

**Comment by BillHenning** [comment]
@gafter Thank you for reopening the issue.  For anyone like my company that is developing third-party tooling for the C# and VB languages, it's really important to have the official specs and grammar up-to-date so that we can properly support all the great work you guys are doing in language enhancements.

**Comment by nickjudson** [comment]
+1: For products which use .NET languages within a scripting environment, this is important!

**Comment by ljw1004** [comment]
While waiting for an official C#6 spec, I put up this temporary unofficial copy: https://github.com/ljw1004/csharpspec/blob/gh-pages/README.md

It incorporates this hyperlinked version of the grammar: http://ljw1004.github.io/csharpspec/csharp.html

And this version in ANTLR format: https://github.com/ljw1004/csharpspec/blob/gh-pages/csharp.g4?raw=true

**Comment by BillHenning** [comment]
Hi @ljw1004, thanks for the unofficial copy.  We need to be able to "diff" the updates for 6.0 as compared to 5.0, so that we can update our custom C# parser appropriately.  In the past, we would take the Word document spec for a version and the next version and would diff the grammar portion of the Word document.  It doesn't look like your unofficial Word document spec contains the grammar though, so it's difficult to know what is new/changed.  Do you happen to have any sort of "diff" that we could examine that would compare 6.0 to 5.0?

**Comment by ljw1004** [comment]
@BillHenning here's the diff from C#5 to C#6: https://github.com/ljw1004/csharpspec/pull/1

You can look at just the .g4 file to see the grammar changes.


NOTE: the C#5 grammar I use here denotes the same language as the official C#5 spec, but I modified some of the production rules to make better use of ANTLR primitives such as kleene-star * (zero or more of) and plus + (one or more of). The official C#5 spec only used ? (zero or one of).

**Comment by BillHenning** [comment]
Thanks @ljw1004, you rock.  I know I'm totally pushing my luck, but you don't happen to have similar for VB 14, do you?

**Comment by ljw1004** [comment]
@BillHenning No sorry no VB yet. That's my job and I'm a bit behind. I'll see what I can bang out this week. You can follow progress at
https://github.com/ljw1004/vbspec/blob/gh-pages/README.md

**Comment by nickjudson** [comment]
@ljw1004 Any update on the VB version? Thanks.

**Comment by danipen** [comment]
@ljw1004 Could you tell us something about the release date of the official C#6 grammar? Thanks!!

**Comment by AnthonyDGreen** [comment]
@nickjudson the VB spec has been uploaded to a new repo @ https://github.com/dotnet/vblang/
@danipen the C# spec has been uploaded to a new repo @ https://github.com/dotnet/csharplang/

**Comment by zspitz** [comment]
@ljw1004 @AnthonyDGreen Would there be any value in making an ANTLR4 compliant grammar for VB.NET? Since (presumably) the Roslyn compiler wouldn't make use of such a grammar, the only benefit would be to make the rules written into the spec verifiably unambiguous.

While the [current version](http://ljw1004.github.io/vbspec/vb.g4?raw=true) linked to from the [VB.NET spec README](https://github.com/dotnet/vblang/tree/master/spec) has the `.g4` extension, it bears only a vaguely superficial resemblance to a valid ANTLR4 grammar. It causes [errors and warnings when passed through ANTLR4](https://github.com/dotnet/vblang/issues/281).

In addition, character ranges are denoted like so:
```antlr
AlphaCharacter
    : '<Unicode classes Lu,Ll,Lt,Lm,Lo,Nl>'
    ;
```
which ANTLR interprets as the literal text `<Unicode classes Lu,Ll,Lt,Lm,Lo,Nl>`. The actual notation should be something like:
```antlr
AlphaCharacter
    : [\p{Lu}\p{Ll}\p{Lt}\p{Lm}\p{Lo}\p{Nl}]
    ;
```

Also, presumably XML literals should be defined using [different lexical modes](https://github.com/antlr/antlr4/blob/master/doc/lexer-rules.md#lexical-modes).

NB. I haven't looked at the C# ANTLR grammar; does it also have similar problems?

**Comment by AdamSpeight2008** [comment]
I initially opened this issue, because of the lack of an up to date specification / grammar accessible to external members. The lang repos didn't exist at the time, the situation is a little better today. The contents of the specification still need bring in sync with released version of the languages.

**Comment by zspitz** [comment]
@AdamSpeight2008 Since the point of the grammar is not [to generate a fully realized parser from the grammar](https://github.com/dotnet/vblang/issues/281#issuecomment-372505835), perhaps the grammar could be generated by running some script over the specification and extracting the ANTLR code blocks into a separate file?

**Comment by BillHenning** [comment]
It's unfortunate this was closed.  At the time I write this, the grammar specifications here are now multiple release iterations behind production C#/VB.

**Comment by CyrusNajmabadi** [comment]
@BillHenning you are welcome to open an issue to ask for this.  Adam closed out all his issues.
