### ISSUE TITLE
Nullability: Arrays of null objects can be created even though non-null was specified

### ISSUE THREAD

**Issue by praeclarum** [dotnet/roslyn#31873]
From: https://twitter.com/R2D221/status/1074765608359608320

This code compiles:

```csharp
string[] lines = new string[100];
```

even though `lines` was declared as non-nullable.

This also comes up with `var` since it assumes the type is `string[]`.

It would be nice if the compiler raised an error letting you know the `lines` is going to be full of nulls and should be redeclared as `string?[] lines`.

**Version Used**: .NET Core 3.0.100-preview-009812

**Expected Behavior**: Error

**Actual Behavior**: No error, runtime crash with NRE

**Comment by jcouv** [comment]
That's currently by design. Relevant LDM notes: https://github.com/dotnet/csharplang/blob/master/meetings/2017/LDM-2017-10-04.md#null-warnings

The rationale is that we don't want to be annoying for the common pattern of creating an array and immediately populating it with a loop.

That said, we discussed the alternative in LDM as recently as today. The alternative is that you must put a `!` in `string[] lines = new string[100] !;`. 
We don't think forcing users to put this `!` really helps much, and it could easily be annoying...

**Comment by praeclarum** [comment]
Call be a hobgoblin but I think the inconsistency is more annoying than generating errors. But I won't push the point if it's already been argued ad nauseam.

I'm trying to avoid `!` in my code :-)
