### ISSUE TITLE
Roslyn needs a way to disable completion for LiveShare sessions on the guest side.

### ISSUE THREAD

**Issue by tinaschrepfer** [dotnet/roslyn#31965]
By switching over to async completion, Roslyn's IAsyncCompletionSourceProvider exports based on "Roslyn Languages" content type.  However, this results in duplicate completion items and completion filters showing up in the async completion API UI in LiveShare guest session when LiveShare uses LSP to display completion.  The reason is that in LiveShare guest session, all buffers have a content type which derive from both "Roslyn Languages" and "code-languageserver-preview".  Because of this, both LSP and Roslyns's async completion source providers get picked up by the Editor and used to provide completion.

We need a way to disable Roslyn from participating in LiveShare guest sessions when LSP is used.  Couple of suggestions which floated around are:
* Feature service so LiveShare can disable as needed.
* Change the content type to be more specific so LiveShare doesn't use that content type.

**Comment by AmadeusW** [comment]
A possible solution for this problem is to use `IFeatureService` (available through `Microsoft.VisualStudio.Utilities.IFeatureServiceFactory` MEF part)

LiveShare may call `IFeatureService.Disable("RoslynCompletion"...)` to get a disposable token. 
Once the token is disposed, feature will be enabled again.
Roslyn should call `IFeatureServce.IsEnabled("RoslynCompletion")`

The feature service is per-view and also global. It updates immediately and you may subscribe to update events.

**Comment by daytonellwanger** [comment]
We could use the `IFeatureService`, but we'd (Live Share) prefer for the dependency to go in the other direction; that is, rather than Live Share disabling Roslyn, Roslyn should disable itself if it detects it's in a Live Share session. This can be detected either by checking the content types of the files, the workspace they belong to, or by consuming our public APIs.

**Comment by daytonellwanger** [comment]
> I mostly don't like this because it seems to place a new requirement on all language service authors. 

It does. But the alternative is that Live Share needs to know about every language it supports and how to interact with those languages. This
- makes Live Share very fragile because it's easy for language teams to make breaking changes without noticing they're breaking us
- doesn't scale well

But I agree that you can probably make the same points in the other direction.

The ideal solution is that Live Share doesn't need to do anything special to work with Roslyn and vice versa. If the buffers didn't have "Roslyn Languages" as a base type, that would solve this problem? We intentionally leave it as a base type to get local language services for some features. I'd need to do a more in-depth audit to see if there's a better way we could achieve this/how much value we get from it.

**Comment by tinaschrepfer** [comment]
Is it possible to add an additional content type to Roslyn languages that's only used for completion?  For example, instead of exporting IAsyncCompletionSourceProvider using "Roslyn Languages" as the content type, it would use "Rolsyn Languages Completion".  This would mean the following:

1. Roslyn would have to add this "Roslyn Languages Completion" to all its buffers.
1. LiveShare would only derive from "Roslyn Languages" when it wants to use LSP to handle completion on the guest side.

**Comment by ivanbasov** [comment]
Discussed with LiveShare team. Agreed that the fix should be done on LiveShare side by telling the Editor that LiveShare will participate in completion exclusively. Editor already provides an option for the purpose.
