### ISSUE TITLE
No nullability warning for a FirstOrDefault() method

### ISSUE THREAD

**Issue by savahmel** [dotnet/roslyn#31997]
Visual Studio 2019 Preview 1.1

The following code produces no warnings and results in a null reference exception. 

```C#
using System.Linq;
#nullable enable
class Program
{
    static void Main(string[] args)
    {
        System.Console.WriteLine(new string[0].FirstOrDefault().Length);
    }
}
```
Expected: IMHO, since FirstOrDefault is a library method that might or might not be aware of nullability, 
might or might not support this concept it should be treated as returning a nullable value. 
Unless there is an indication of nullability on the CLR level, probably any library public method, field or property should be assumed to return and accept nullable references. 

I would also expect the compiler to give me a warning if I expose a public library method with non-nullable reference arguments or return types.

**Comment by jaredpar** [comment]
This behavior is "By Design". The framework libraries in this case have not been annotated with nullability warnings. This means all of their exposed types are oblivious. Hence they don't get subjected to nullability warnings. This will warn once the libraries are updated. You can verify this by typing out the `FirstOrDefault` signature in the same project where nullability is enabled.
