### ISSUE TITLE
Possible bug in Batch Fixer merge algorithm

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#320]
We have a code fix that uses the batch fixer to provide support for correcting all instances of a particular style problem in a document/project/solution. Even though each correction is made to a distinct `ExpressionSyntax` node in the source tree, the batch fixer fails to properly merge two changes in a particular scenario.

The problem is described (with example input/output) in the following issue:
https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/466

**Comment by mavasani** [comment]
Fix merging logic in BatchFixer is based on text differencing algorithm between syntax trees (SyntaxTree.GetChanges(SyntaxTree)). So theoretically, just adding a "this." qualification to a SimpleNameSyntax should classify as a single TextChange with an add operation.
However, it seems that for the reported test case, this API behaves doesn't behave such. For certain edits to expressions, it correctly classifies tree changes as having a single add operation. For some it returns each edit as 2 changes: First change is an add of length 14 instead of 5 (for "this.") and second one is a delete of bunch of character. This is causing isolated fixes to ExpressionSyntax nodes to appear as conflicting edits and hence the BatchFixer doesn't do the expected merging.

@sharwell For now, you are better off writing your own FixAllProvider, probably on same lines as BatchSimplificationFixAllProvider used by our simplification fixes. I'll open a separate issue to track the bug in SyntaxTree.GetChanges(SyntaxTree).

**Comment by mavasani** [comment]
@theoy @AnthonyDGreen  So, this basically looks like an issue in SyntaxTree.GetChanges(SyntaxTree) API not behaving consistently. I have added a skipped test "TestQualifyWithThis" to CSharpCompilerSyntaxTest project. Once fixed, kindly re-assign to me to verify that the BatchFixer scenario affected by this bug is also fixed.

**Comment by theoy** [comment]
@mavasani - opened bug #463 to track the Syntax API bug, so that we don't have to do the confusing "we fix our bug, verify, then reassign back to you" to verify the impact on your scenario. I added you as cc to that bug so you should get a notification when it's fixed.

Cheers, --Theo

**Comment by heejaechang** [comment]
I believe syntaxTree.GetChanges are there for fast diffing. and the one Enc used is for more accuracy. 
we might think of switching using the one Enc use for accuracy rather than speed for batch fixer.

@tmat 
Tomas. do you think tree differ Enc uses can handle this case better? basically the bug is about SyntaxTree.GetChanges doesnt return changes as optimal as it can give.

ex) for adding "this." to Blah -> this.Blah, it gives 2 changes as diff 
Add: "this.Blah" and Delete "Blah" 

rather than giving one change as diff
Add: "this."

**Comment by mavasani** [comment]
@heejaechang The diffs returned are actually worse, as in:

Add: "this.Blah + some code"
Delete: "Blah + some code"

and if 'some code' has another expression 'Blah' where FixAll is applicable, these 2 fixes are incorrectly deemed as conflicting due to overlapping diff spans.

**Comment by heejaechang** [comment]
@mavasani  yep. probably, it has been long time since I looked at that code, but I believe that differ is not for accuracy but for speed with reasonable gradularity. also it heavily depends on green node for speed.

@tmat Tomas one might be better one to use for BatchFixer.

**Comment by heejaechang** [comment]
@mavasani so I just talked with @tmat . it sounds like the differ he wrote is what we want for batch fix all provider.

http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp.Features/EditAndContinue/StatementSyntaxComparer.cs,4b9a60cb63d5c08c

we probably want the fast one to find portion that has changed fast, and then use this to get more accurate changes. it can get changes at the token level. and can detect replace, exchange and etc.

this differ is certainly more complex and more work to do. but since batch fix all will be most common fix all provider, it probably be nice for us to provide very good differ for users. let me open a bug for the work.

**Comment by srivatsn** [comment]
@mattwar has fixed this in #609

**Comment by sharwell** [comment]
We're getting a slew of bug reports due to the batch fixer failing to merge "dense" changes, and it's causing a problem because we have no way to detect the presence of conflicts in the result to alert the user or selectively not perform those fixes.

DotNetAnalyzers/StyleCopAnalyzers#727
DotNetAnalyzers/StyleCopAnalyzers#723
(I saw additional cases when I was working on DotNetAnalyzers/StyleCopAnalyzers#711)

**Comment by mavasani** [comment]
@sharwell I'll take a look at this again, it is pretty likely that the compiler's differ is not handling lot of these cases. We may have to move to a more accurate syntax differ in the generic batch fix all provider.

**Comment by mavasani** [comment]
Re-opening to track the new reports.

**Comment by mavasani** [comment]
@sharwell I just tried the repro that you suggested in the original issue, and it doesn't repro for me with the latest Roslyn bits. I see all the SA1101 fixed in the document after invoking the fix all, including the line 233 in NumberSignSpacingTestBase.cs which was in your original repro:

```
To reproduce, clone this repository and open the file NumberSignSpacingTestBase.cs. Do a Replace All in the file to replace  this.  with the empty string. A warning will appear (from the analyzer which is installed in the project) requesting each of these instances be changed back to  this. . If you use the Fix All provider to correct all instances in the document, you'll find the document is restored to the state in which you cloned it, with the exception of the specific expression which I reported in dotnet/roslyn#320.
```

Can you please re-try the repro? I will try the repros from other issues that you cited above.

**Comment by mavasani** [comment]
@sharwell The corruption issue should be fixed for *real* now. Thanks again for reporting the issues!

**Comment by mavasani** [comment]
@srivatsn Probably want to someone to thoroughly test our batch fixer's merge algorithm.

**Comment by heejaechang** [comment]
talked with @mavasani it looks like @mavasani already added unit test for this issue. but we decide to create another issue to add bunch of tests after RTM.
