### ISSUE TITLE
FeatureRequest: Support XML Comments on local methods

### ISSUE THREAD

**Issue by YairHalberstadt** [dotnet/roslyn#32061]
I find it useful to document behavior of local methods, and having a fixed specification as to how to do so would be useful, rather than an ad-hoc comment system. As such I like to use XML comments. I will document information relating to contracts, usages of the parameters, return type, etc.

However currently XML comments are invalid on local methods. As a result, if you add XML comments to local methods, they don't show up in intellisense. Also, tooling can not auto-generate empty XML comments for the user to fill in.

Whilst these can't be used for Documentation (as local methods are private) the same is true for private methods, which do allow XML comments.

(This issue has been moved from https://github.com/dotnet/csharplang/issues/2110)

**Comment by CyrusNajmabadi** [comment]
Note: i think this would be fine to support as a pure tooling-only feature (i.e. without changing the language).  It would just be about connecting the codepaths in the compiler/IDE so that doc-comments (which are already parsed) on locals/local-functions properly light-up.

**Comment by jnm2** [comment]
> markdown support

/cc @sharwell

**Comment by sharwell** [comment]
@alrz See https://gist.github.com/sharwell/ab7a6ccab745c7e0a5b8662104e79735

**Comment by CyrusNajmabadi** [comment]
@alrz I think any discussion of stripped/trimmed down doc comments should be another issue.  For example, we already have https://github.com/dotnet/csharplang/issues/878 tracking something similar.  

This issue is purely about expanding the allowed set of doc-comment locations to include locals as well.

**Comment by alrz** [comment]
That's not the only thread about this stuff. It was the first time I heard that the team is actually interested to invest in this area. perhaps we should have a "champion" issue for the feature so the discussion takes place on a single GitHub thread.

**Comment by CyrusNajmabadi** [comment]
@alrz They're entirely different features.  For example, this PR (imo) is simply about tooling updates, without any language changes at all.  it would just be about the IDE registering these comments and displaying them, instead of dropping them on the floor.  It would be entirely a dotnet/roslyn issue.  On the other hand, expanding/changing what can go *in* a doc-comment is very much a language change belonging in dotnet/csharplang, and would require a vastly different process and effort to even bring that to the table.

Note that while these are complimentary activities, they're also orthogonal.  Lighting up doc-comments for locals can happen independently.  If/when the language ever decides that markdown/etc. are supported, then that would just naturally come to locals as well.

**Comment by alrz** [comment]
>They're entirely different features. For example, this PR (imo) is simply about tooling updates, without any language changes at all.

doc comments are a part of language specification and the compiler is responsible to parse code segments. So I'd argue that this rather belongs to csharplang repo.

**Comment by CyrusNajmabadi** [comment]
>and the compiler is responsible to parse code segments. So I'd argue that this rather belongs to csharplang repo.

Compiler is this repo :) .  And the compiler *is* parsing these code-segments afaict.  So nothing needs to change there.  What needs to change is simply updating the roslyn API to just expose this info, instead of dropping it on the floor.  But i could be wrong about that since i haven't debugged through.

**Comment by CyrusNajmabadi** [comment]
Oh... i do suppose on issue woudl be that if hte language doesn't specifically allow doc-comments here, that hte parser might err/warn.  So you'd need that to stop happening.  Which might be a language change.  Objection withdrawn.

**Comment by YairHalberstadt** [comment]
In conclusion, where does this issue belong?

**Comment by sharwell** [comment]
@gafter @jaredpar We would like to provide editor support for XML documentation comments on local functions. These comments would not be included in the XML file produced during a build. Can you provide an interpretation of the C# language per https://github.com/dotnet/roslyn/issues/32061#issuecomment-451683423 to determine whether this is allowed?

**Comment by AlekseyTs** [comment]
CC @agocke

**Comment by agocke** [comment]
The language does not allow doc-comments on local functions.

**Comment by gafter** [comment]
Reopening https://github.com/dotnet/csharplang/issues/2110 and championing it.  We would not make this compiler change without a corresponding language change.
