### ISSUE TITLE
CS8625 and CS8603 for Enum constraints in nullable ref type project

### ISSUE THREAD

**Issue by Tornhoof** [dotnet/roslyn#32064]
Warnings
Warning	CS8625	Cannot convert null literal to non-nullable reference or unconstrained type parameter.	
Warning	CS8603	Possible null reference return.
are shown for an Enum constraint.

**Version Used**: 
VS 2019 Preview 1.1
.NET SDK Version:   3.0.100-preview-009844
**Steps to Reproduce**:
1. Create project and set:
```xml
    <LangVersion>8.0</LangVersion>
    <NullableReferenceTypes>true</NullableReferenceTypes>
```
2. Copy following source code into the project:
```csharp
namespace ConsoleApp8
{
    public interface ISerializer<T>
    {
        T Serialize();
    }

    public class EnumSerializer<TEnum> : ISerializer<TEnum> where TEnum : /*struct,*/ Enum
    {
        public TEnum Serialize()
        {
            return default; // CS8625 and CS8603
        }
    }
}
```
3. Look at the warnings.

**Expected Behavior**:
`` return default`` is valid
**Actual Behavior**:
CS8625 and CS8603
**Workaround**
Constraint the type further with ``struct``

**Comment by HaloFour** [comment]
This is expected behavior.  To the CLR the `System.Enum` constraint allows the generic type arguement to be `System.Enun`, which is a reference type, and has a default value of `null`.  By also including the `struct` constraint you force the generic type arguement to be an actual enum type which is a value type and thus not nullable.

**Comment by Tornhoof** [comment]
Thank you for your explanation. I think we can close this.
