### ISSUE TITLE
Consider making EffectiveTypeNoUseSiteDiagnostics public 

### ISSUE THREAD

**Issue by pgrefviau** [dotnet/roslyn#3207]
The [EffectiveTypeNoUseSiteDiagnostics](http://source.roslyn.codeplex.com/#Microsoft.CodeAnalysis.CSharp/Symbols/TypeSymbol.cs,246) property on the [TypeSymbol](http://source.roslyn.codeplex.com/#Microsoft.CodeAnalysis.CSharp/Symbols/TypeSymbol.cs#21) class seems like an incredibly useful, powerful and already existing thing to have when dealing with type parameters, since there is no real other non-internal way to obtain the effective/constrained underlying type of a symbol. I know that I found myself more that once in need of having that information, especially when dealing with generic methods. It just looks to me like there would be only benefits to exposing this property publicly.

**Comment by CyrusNajmabadi** [comment]
This would need to go through an API proposal.  in general, the reason we don't just make things public is because it increases maintenance costs and locks down our ability to change things in teh future.  We can open things up, but we have a process that requests need to go through to make sure the appropriate people weigh in and the right API shape is determined and shipped.
