### ISSUE TITLE
Selecting a named parameter from intelisense list not inserting the colon

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#32204]
<p>When adding a method’s parameters and using named parameters, I’ll see the parameters in the list twice, one with a colon and one without.  When you scroll down in the list and select the parameter with the colon and press tab/enter to select/insert the parameter, the named parameters are always without the necessary colon as expected.</p>

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/394019/selecting-a-named-parameter-from-intelisense-line.html
VSTS ticketId: 736597_
_These are the original issue comments:_

Cytheria Ji [MSFT] on 11/29/2018, 05:08 PM (37 days ago): <p>Thank you for your feedback! For us to investigate this further, could you please provide your project type and language?  We look forward to hearing from you!</p>

Daniel Doris on 11/30/2018, 08:43 AM (36 days ago): <p>Thanks for following up.  </p><p>Version: VS 2017 15.8.8<br>Project type: C# old .Net (not Core) solution contains a mix of DLLs and a console app.<br>Environment Settings: (General/C#/VB/Web)  i'm using C# Development Settings.<br><br>Can't think of anything else that will impact the behavior but will provide if you need anything else.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment]
This is by design.  The punctuation on these items acts just as marker in the list to help indicate what sort of item this is.  It's the same reason that we have `Dictionary<>` in the completion-list, but selecting it doesn't actually insert the `<>` chars.

**Comment by ZooDoo4U** [comment]
Sorry this doesn't make sense.  Can you provided another example where you select in item from the intelisense list you see "ItemWanted" and selecting it in it list to insert/commit it  you get "ItemWante"  with the trailing character removed?   Or for that matter why if this is by design does the same text show up twice, if so they it seems there an another bug.  Sorry from a user's experience does make for a poor and unexpected experience, "Where or why did the last character for the item selected disappear?"   My first thought once i noticed it,  I can't think of any other program where if you had Item1, Item2, Item3 in a list a and you select "Item3" you get item, ooops which one?  The issue if one selects and highlights the one desired, explain how the editor fixing up my choice from the list is helpful or intuitive, please suggest another program that has this buggy behavior,  I can't think of one.

**Comment by CyrusNajmabadi** [comment]
> Can you provided another example where you select in item from the intelisense list you see "ItemWanted" and selecting it in it list to insert/commit it you get "ItemWante" with the trailing character removed?

Yes.  As i mentioned, this is done with generics.  Similarly, the Regex completion work operates in this fashion.  You'll see the following in the list:

![image](https://user-images.githubusercontent.com/4564579/50843129-f90e8080-131c-11e9-8713-0010e3c063f5.png)

This is to help both show the general structure of the regex-operator, as well as have names to give things to explain in the comments.  However, if you actually select/insert these guys, you'll get:

![image](https://user-images.githubusercontent.com/4564579/50843155-03307f00-131d-11e9-82e4-5bf8c0b68723.png)

So that you can then insert all the relevant parts yourself, without having to get rid of unnecessary cruft that we may have added.

**Comment by CyrusNajmabadi** [comment]
> explain how the editor fixing up my choice from the list is helpful or intuitive

This has been the behavior of the IDE for nearly 15 years now.  Up until now, it hasn't been reported as an issue or a problem.  I get that the behavior is surprising and unintuitive for you, but that doesn't mean it is bad or not helpful.

For example, here's an extremely common coding pattern i employ (simplified for brevity).  I'll write a call to a method like so:

![image](https://user-images.githubusercontent.com/4564579/50843850-5d7e0f80-131e-11e9-9649-308e015d1eb6.png)

I'll then bring up completion:

![image](https://user-images.githubusercontent.com/4564579/50843877-68d13b00-131e-11e9-91b3-083027477808.png)

I'll now hit `tab` to complete this item **without** the colon:

![image](https://user-images.githubusercontent.com/4564579/50843897-75ee2a00-131e-11e9-8eae-d2dc3ae90c81.png)

Once i have this, i can bring up the lightbulb to help me generate this variable:

![image](https://user-images.githubusercontent.com/4564579/50843932-87cfcd00-131e-11e9-942d-56b5d05a114e.png)

**Comment by ZooDoo4U** [comment]
Lets be consistent, in the example when you the Regex for the different capture behavior say i select "(?=" from the list but changes what you selected to be "(?<Name>".     

As for the IDE working this way for the last 15 years, possibly 10, as named parameters have only been out this long,  but either way because the IDE works this way doesn't justify perpetuating buggy behavior. Honestly use to look at named parameters more for Office interop where you have 30+ parameters it seems for for some calls where 20 will most likely be null...   But started noticing the behavior i'm reporting because i'm using name parameter more and more, seems to make code must more readable if the parameter names are useful. 

While your example you are showing with the Cancellation token example.  Your argument here really is a bit flawed and contrived.  Because as is the highlighted item in the in the list, the only way you would get the item selected with the ":" for the named arg, the user had to arrow down and explicitly set it.  Would think the user has now clearly indicated their intention and which item to select.   Not sure why you need to use a contrived false example as you are to same i'm expecting something other than what a user would expect.   My two office mates, when i explained it to them find what i'm saying to be what they would expect, especially after i've arrowed down to explicitly select the item.  The normal behavior/experience in VS would be the first item in the list will be selected as it will be sorted before the item with the ":", so the only way the item with the ":" is selected is the user took an explicit action, or possibly from their historical usage, but then again would assert if that is what they selected the last time, good chance they would want the same item again, if not arrow up and select the one desired and all is good.   The point is the user has made the explicit item, and VS is going against the users selection.  How is this a user case only interesting to me.  Really do find it hard to see a program second guessing a user's explicit choice is ever good..  Would disagree your example with the Regex fits this unless the user really wanted "(?=" after selectiong "(?<".  Sorry don't see it...

**Comment by CyrusNajmabadi** [comment]
> As for the IDE working this way for the last 15 years, possibly 10, as named parameters have only been out this long

We've had the behavior of completion showing one thing, but inserting something else since at least the preview build of VS2005 :)  So pretty much 15 years.

> Lets be consistent, in the example when you the Regex for the different capture behavior say i select "(?=" from the list but changes what you selected to be "(?".

As i said, you select one thing, but something else is inserted.  This is what we have in many different cases, including the `colon` case you identified.

> but either way because the IDE works this way doesn't justify perpetuating buggy behavior. 

It's not a bug in my opinion.  It may be behavior you don't like.  But it's behavior that was intentionally chosen to work this way, and has become part of the muscle memory for many users.  Changing things that affect muscle memory is not done lightly, and would likely not ever be done here given the reasons we had to do this and hte size of the user base that has grown up around this.

> While your example you are showing with the Cancellation token example. Your argument here really is a bit flawed and contrived. Because as is the highlighted item in the in the list, the only way you would get the item selected with the ":" for the named arg, the user had to arrow down and explicitly set it. 

That's not true.  I didn't use arrows at all.  This is the exact behavior you get when typing things out.  I can include a gif if you don't believe me :)  

--

Note: this discussion has really run its course here.  If you want to discuss things more, feel free to go over to gitter.com/dotnet/roslyn.  Cheers!

**Comment by CyrusNajmabadi** [comment]
> My two office mates, when i explained it to them find what i'm saying to be what they would expect, 

This is not a compelling argument.  The behavior and decisions here have a lot of history behind them and are based on working with many thousands of users over the decades.  Not all decisions will be what all users desire.  And that's ok.  There are certainly many parts of VS/C#/Roslyn that aren't the best fit for me (and i wrote tons of them myself).  I'm simply including information to help you understand things better.  My goal isn't to make you like it.  It's to simply help with understanding/documenting this for the future.

Thanks!

**Comment by ZooDoo4U** [comment]
The point is the user explicitly made the choice what to insert.  Just curious to provide one example of a program that over rides the user's explicit selection where it isn't a bug.

**Comment by CyrusNajmabadi** [comment]
> The point is the user explicitly made the choice what to insert. Just curious to provide one example of a program that over rides the user's explicit selection where it isn't a bug.

Feel free to come to gitter.im/dotnet/roslyn, and we can discuss it more.  I can def think of examples, but it's not relevant here. :)

**Comment by Neme12** [comment]
I agree that inserting the parameter name in order to generate a variable is sometimes useful, but let's consider the two scenarios:
1. I'm trying to insert `parameter:` but completion only inserts `parameter`. It takes one more key press (or 2 really) to insert the `:`.
2. With the alternative design: I'm trying insert `parameter` but completion actually inserts `parameter:`. It takes one key press to remove the `:`.

Which of these is more common? Selecting `parameter:` in the completion list in order to actually type a named parameter or just use its name? At least in my experience it's the first of the two.

**Comment by Neme12** [comment]
I'd expect that to be the case for most users too because the completion item literally says `parameter:` as opposed to `parameter`.

**Comment by CyrusNajmabadi** [comment]
The common problem there, which was one of the many motivations for the current design was someone writing:

```Foo(bar<space/comma/dot/etc.>``` with the intent of writing a variable that doesn't exist yet.  It is common for people to want to create a variable with teh same name as the parameter they're going to pass to.  When we added named-items into the list (because we did want to speed up typing those), we also regressed the muscle memory of people who wrote that sort of thing and ended up having `bar:` inserted in an unwanted manner.  

Note that this is not a hypothetical concern.  This was actual fallout from such an initial approach, and it's part of the reason we went to the "this is just a name" system.  I don't think we can change the behavior because it's detrimental to how people expect to be able to type after years of C# behavior.

I am sympathetic to the complaint that this can be confusing since the item literally says `whatever:` in the list.  My solution **if** we even felt this warranted any change, would just be to say: take the `colon` off the item in the list.

That said, i'm loathe to change things here without strong need.  This doesn't seem to be a large issue for users.  So the default position shuld be to stick with the status quo unless there is strong reason otherwise.  Completion is a core and critical part of the experience, and we only change things when very necessary and when the benefits you get are large enough to outweigh any potential changes taht can trip up, confuse, or otherwise cause problems for users.

**Comment by ZooDoo4U** [comment]
I hear you, change always tends to sucks (my opinion) some like change.  While i've see in the last couple updates that are more prevalent and annoying, if we are use the standard as you did that it has been that way for 15 years.   Intellisense i thought in one of the last updates went from great to good.   Something changed and i didn't like it much.  Use to be no matter what you had after an object say a SqlCommand cmd"

If you had cmd.op%$#*$(   where obliviously the "%$#*$(" is complete garbage.  The difference it seems, in the older version of VS when positioning  the cursor after the dot "cmd.|op%$#*$("  (so my cursor is where the '|' is)  Press "completion" ctrl-space or tab,  use to insert "Open" can't remember if it removed the garbage or left it.  Currently these days you get nothing.  Seemed the old behavior was doing a listbox.FindString() on the items in the suggested completion list up to the point where there was  common substring for the object members and text in the editor.  The change seems to be the old would remember the listbox item index up to the point the last common character was found and selected that item.   Now these days today if it can't find the entire string after the dot and simply provides no suggestion is provided.

So i hear you about making changes with no regard to behavior and user's habits of getting use to it, i get that,  but the question i would have would be first off why are there two entries, surely you saw that in your example with the "CancelationToken", i would ask why two?  And what is the difference if the are actually both going to do the same thing?  While as a user i would thin if selecting the one with the ":" on the parameter name...   Then it should be added as the item in the list, really no surprises to the user, as the default selected will be the first/sorted one with no ":" so no change for the habitual coder :)

**Comment by CyrusNajmabadi** [comment]
>  Something changed and i didn't like it much. Use to be no matter what you had after an object say a SqlCommand cmd"

If you can make a minimal repro of what you're talking about, please file it.

**Comment by CyrusNajmabadi** [comment]
>  i would have would be first off why are there two entries, surely you saw that in your example with the "CancelationToken", i would ask why two? 

I don't know what this means.  What two entries are you talking about?

**Comment by ZooDoo4U** [comment]
Sorry in one of your previous responses,  with the screen shots showing the intellisense list the item you were showing in which got inserted was on the "CancelationToken" 2nd image in the post on the 8 Jan, should be clear now.

**Comment by CyrusNajmabadi** [comment]
> Sorry in one of your previous responses, with the screen shots showing the intellisense list the item you were showing in which got inserted was on the "CancelationToken" 2nd image in the post on the 8 Jan, should be clear now.

Still not clear.  Are you talking about this image:

![image](https://user-images.githubusercontent.com/4564579/50999090-3cfcb380-14de-11e9-8bc4-fce41fb8fe68.png)

If so... i'm not sure what you're referring to.  Can you be more explicit?

**Comment by ZooDoo4U** [comment]
Ah one final thought, and for name parameters i think it makes sense to put in the ":"...   I just put in a call to a method  "TestMethod( string s1, string s2, string s3)" For example.  Upon my first selection i put in 

TestMethod(

At this point i press ctrl-space and see a list of the named parameters (sweet this i like)   now i select the named parameter, only thing in the context that really makes sense, but selecting say "s3:"  i get s3, so rather counter intuitive here.  So the tools out thought me and gave me what wasn't expected, thus my point why if i select an item explicitly i get something different?   Have not seen another program ever do this where it wasn't a bug.  If i wanted the parameter without i didn't need to explicitly select it, would be just as bad to select the one without the ":" and get the ":" inserted...

**Comment by ZooDoo4U** [comment]
My comment about was to get the cancellationtoken with the ":" the user needed to explicitly set it, but upon selecting it the editor fixes up and knows better what i wanted (not...).

**Comment by CyrusNajmabadi** [comment]
> So the tools out thought me and gave me what wasn't expected, thus my point why if i select an item explicitly i get something different?

The reasons for this have all been listed and explained.  Your questions is understood, but there are strong reasons they are overruled.

>  Have not seen another program ever do this where it wasn't a bug.

There are other programs that do this.  But it's out of scope to discuss htat here.  I'm happy to take it offline with you on gitter.  I'm off to dinner now, but would be happy to chat later.

**Comment by GF-Huang** [comment]
Was this proposal rejected?

**Comment by ZooDoo4U** [comment]
Yep believe it was rejected.  Interesting eh?  From what it seems intelisense is broken in a few different ways from what it seems how it use to work.

**Comment by GF-Huang** [comment]
> Yep believe it was rejected. Interesting eh? From what it seems intelisense is broken in a few different ways from what it seems how it use to work.

Let's use notepad.exe for coding. :)

**Comment by GF-Huang** [comment]
I think the default value can be kept the same, but a setting option is provided for people to choose whether to automatically insert a colon.

**Comment by ZooDoo4U** [comment]
It is interesting 2019 makes it a lot harder.   In 2017, if you start off the first parameter with a named parameter, once you enter a ',' and get the intelisense list you get only named parameters, as i'd expect.   VS 2019 after the first named parameter, you get nearly everything in the intelisense list.   I should have the same settings in vs 2017 && vs 2019 i always export my setting with Tool::Import Export Settings  and then import them again into the new version of VS, so not sure why there is such a difference :(

**Comment by CyrusNajmabadi** [comment]
> VS 2019 after the first named parameter, you get nearly everything in the intelisense list. 

Yes.  Because the language changed, and this is now legal.  i.e. you can write ths:

```c#
Foo(a, name: "bar", b, c)
```

When you're typing the arguments after the named parameter, you need to still be able to get help.  note: we use this a *ton* in roslyn.  

> so not sure why there is such a difference :(

Language changes necessitate behavioral differences.   :)

**Comment by ZooDoo4U** [comment]
Okay, fair enough if the language updates, but all the more for the editor to stand up and provide some support here.  I'd suggest some kind of inteliParams or something along those lines. Given i'd know better then the editor what i'm entering,  the InteliParams would be a setting in VS that allow one to specify how arguments are entered by users,  options should be (No Filtering, Limit To Method Parameters)  and the limit to Method Params be the default.   Would assert the user can is users more often if they are using named parameters will more often desire named parameters over positional.   And i'd really questions mixing named and positional parameters in the first place.  If positional, why even name the parameter at all, or if that is the case why limit everyone else for such a bizarre non standard behavior.   Besides if their code is that messed up, then could select the "No Filtering", or after completing the line of code for invoking the method, go back and fix up the statement to mess it up with a mix if named and positional args...

**Comment by CyrusNajmabadi** [comment]
>  and the limit to Method Params be the default

This would completely break people writing totally legal code.

> Would assert the user can is users more often if they are using named parameters will more often desire named parameters over positional. 

I don't have any basis to believe that that's true :)   For example, in roslny itself that's definitely *not* true. 

> if they are using named parameters will more often desire named parameters over positional. 

This is not hte case.  A core reason for named-parameters is to provide clarity about particular parameters.  i.e. we do things like:

`new User(id: null, "Cyrus", "Najmabadi")`

Without hte named arg, it's very unclear what `null` is meant to be.  We suggest this all the time in PRs to provide clarity about args that need it.

>  If positional, why even name the parameter at all,

See above.  It's very common, and a core reason we did the feature in the first place.  it makes a very clear, in-code place to document what's going on.

>  Besides if their code is that messed up,

There code is not messed up.

> go back and fix up the statement to mess it up with a mix if named and positional args...

The problem here is that you're coming from a position of presuming that people who are doing things differently from you are doing things wrong or in a messy fashion :)
