### ISSUE TITLE
C# code generated for "Implement Interface" adds in using statements that I clearly didn't want

### ISSUE THREAD

**Issue by ljw1004** [dotnet/roslyn#3239]
Look at this codespit for "Implement Interface" in C#:
![cs-codespit](https://cloud.githubusercontent.com/assets/3316258/7924849/a246ed4e-0873-11e5-9a8e-b647ac3fcb4c.png)

I wrote out `System.IFormattable`. From this, the IDE should understand that I _wanted_ to explicitly qualify this type.

But the IDE chooses to add a "using" clause so that the parameters of the "ToString" method it spits out don't need to be explicitly qualified. This results in my own explicit qualification becoming greyed out.

(1) I _NEVER_ like it when an unrelated action causes my own deliberately-written-out code to become greyed out.

(2) Please respect my coding convention, inasmuch as you can detect it. In this case please detect that my coding convention is an explicitly qualified type, and follow that convention.

**Comment by Pilchie** [comment]
There are a couple of places where we do this (overrides completion being another).  We should think about a better design here.

**Comment by CyrusNajmabadi** [comment]
Note: this was a deliberate decision made by far more people saying: hey... whne i'm going to implement this, i really want the usings because i don't want things fully qualified in this manner.

Given the large amount of feedback there, and the only one piece of feedback here, i believe our current behavior is the most desirable, and that there's not enough justification here to handle the much rarer case when someone really doesn't want usings to help not having to fully qualify their types.

**Comment by sharwell** [comment]
Reopening to bring to design review with a proposed resolution of **By Design**.

**Comment by CyrusNajmabadi** [comment]
Design review conclusion: this is by design.  The current behavior is desirable for most users, and the case raised here (while valid for this user) doesn't warrant adding an option.
