### ISSUE TITLE
[Question] Why the output is CS0165 when using a Null-Conditional Operator.

### ISSUE THREAD

**Issue by deloorc** [dotnet/roslyn#32572]
**Steps to Reproduce**:

1. https://sharplab.io/#v2:D4AQDABCCMAsDcBYAUCkBmKAmCAxA9vhCgN4TnHIUQAOATgJYBuAhgC4CmEdHLAJvgB2AGwCeEACIMAxmwZCWdUQB4YYADRRoYAHwQA+gCNFEALwRBHAO6SZchUtXbNanQAoAlEioUU1DFqQAOIcbG5qEADWHKIeZnpGigD8AHQAKkohbABqLMIArhxu0aKa+PlsEKx0VXmFcabmbHSFlNTUSbUFXH7t5ABcEHwcAGYs+cJs3gC+QA==

Given the following C# example:

```cs
using System.Collections.Generic;

public class Foo 
{    
    private readonly Dictionary<string, string> _bar = new Dictionary<string, string>();
    
    public string Get(string key) => _bar?.TryGetValue(key, out var value) == true 
        ? value 
        : default;
}
```

The following result is returned:

-  CS0165: Use of unassigned local variable 'value'

When I adjust the C# example without the Null-Conditional Operator:

```cs
using System.Collections.Generic;

public class Foo 
{
    
    private readonly Dictionary<string, string> _bar = new Dictionary<string, string>();
    
    public string Get(string key) => _bar != null && _bar.TryGetValue(key, out var value) 
        ? value 
        : default;
}
```
this will compile without any error(s). So my question is, aren't these essentially the same? If not could you elaborate on why the output result is CS0165?

**Comment by gafter** [comment]
> When I adjust the C# example without the Null-Conditional Operator

Try modifying your adjustment to include the `== true`.

**Comment by gafter** [comment]
This is by design.  Definite assignment tracks *assigned-when-true* and *assigned-when-false* per the specification for values of type `bool`.  But the return value of the invocation is `Nullable<bool>`.  Moreover, we do not track *assigned-when-true* and *assigned-when-false* results for the `==` operator per the specification.

I think your expectation is reasonable, but what you expect is not what the C# specification requires.  If you'd like the specification changed, please provide a detailed proposal in the `csharplang` repository.

**Comment by SylwesterZarebski** [comment]
Proposal for expected assignment with `==` and `!=` operators is https://github.com/dotnet/csharplang/issues/801.
