### ISSUE TITLE
GetLocation and FindNode are not always reliable

### ISSUE THREAD

**Issue by ryzngard** [dotnet/roslyn#32753]
Context: 

[PR Discussion](https://github.com/dotnet/roslyn/pull/32685#discussion_r250021980)
#29793 from the original bug

Our messaging for roundtrip nodes for analyzers has been

>if you want to find a node between analysis and fixing, then use AdditionalLocaitons, and just add someNode.GetLocation() to it. You can then find that later with someLocation.FindNode().

This doesn't always hold true if there is ignored trivia contained in a span. Currently [GetLocation](http://source.roslyn.io/#Microsoft.CodeAnalysis/Syntax/SyntaxNode.cs,111ac3d15ffccc76) uses the `Span` property, while  [FindNode](http://source.roslyn.io/#Microsoft.CodeAnalysis/Syntax/SyntaxNode.cs,1973a2affa06beb8) uses `FullWidth` and `FullSpan` properties to evaluate spans and break ties. 

A proposed change is to add a `SourceFullSpan` property to [Location](http://source.roslyn.io/#Microsoft.CodeAnalysis/Diagnostic/Location.cs,ad289cd0d5b2b950) 

```C#
public virtual TextSpan SourceFullSpan => SourceSpan;
``` 

The above would be the change to the abstract base, where implementations can use whatever they see fit. For `SourceLocation` that would mean storing the `FullSpan` property. 

Then the implementation for `Location.FindNode` can use the `SourceFullSpan` property

**Comment by AlekseyTs** [comment]
I do not think adding SourceFullSpan property to location is appropriate. Location is a span of characters in some source code, it has no direct relation to syntax nodes. Yes, a syntax node has a location, but not the other way around. A location doesn't have to map a complete syntax node, it can span multiple nodes, or start in the middle of one node and end in the middle of another node. So, the concept of "full" span is foreign to location. If API is not able to produce correct result based on one location and needs two locations, it should take two locations.

**Comment by ryzngard** [comment]
> I do not think adding SourceFullSpan property to location is appropriate

That would indicate we need different guidance for how analyzers round trip information right? For an analyzer/codefix pair I expect them to reliably find and change the right nodes. 

> If API is not able to produce correct result based on one location and needs two locations, it should take two locations. 

Maybe. That's a different change that adds more complexity to `FindNode`.

**Comment by CyrusNajmabadi** [comment]
I do get @AlekseyTs's point.  However, for a lot of cases, Location very much *is* gotten from a node.  And, it's unfortunate that node.GetLocation in a sense returns something which then isn't really the *actual* 'unambiguous span' of the node as far as the Roslyn apis are generally concerned.  We chose to give 'span' in the past, and now we're stuck with that since many might have taken a dependency on that.

So, the options now are a bit muddy.  I personally think it's acceptable to have two spans in Location.  however, it might be relevant to name them more like: 

`Span`
`RoundTrippableSpan`

Or something to indicate the different purposes of things. 

--

Alternatively, we could have syntax elements expose a GetFullSpanLocation, and then update all our own code (and guidance to users) to use GetFullSpanLocation instead of GetLocation as the former would roundtrip trivially without concerns, while hte latter can be tricky to properly do that.

--

Finally, @ryzngard , have you investigated what it would take to make FindNode just support working properly with a 'Span' vs a FullSpan?  is the main concern that you can have multiple nodes of differing types have the same Span in error conditions?

**Comment by Neme12** [comment]
Why don't we just use syntax references instead of locations? Locations are unreliable anyway because 2 syntax nodes can have the same locations. Each feature then has to think about whether to use `getInnermostNodeForTie` or not based on what scenario can happen and there have been many bugs around that.

**Comment by CyrusNajmabadi** [comment]
> Why don't we just use syntax references instead of locations

1. no place to store those on diagnostics (but that's potentially solvable).
2. a reference represents dynamic code that can run.  diagnostics need to be serializable.  Locations, being raw data, are easy to support that.  References are not.

**Comment by Neme12** [comment]
Why does a syntax reference represent dynamic code? If it does then maybe there needs to be another concept of a tree location that could uniquely identify a node. Maybe something like the position + depth or node index.

**Comment by CyrusNajmabadi** [comment]
> Is depth enough to make this work correctly?

Back in the native-IDE days we used to do it by storing a list of kinds so we could distinguish between nodes of different kind, but same span.  that was primarily because we had scenarios where we were trying to track over edits.  Given that this is much simpler (we only really support the case of recovering the node from teh same snapshot), depth might be enough.  :)

**Comment by Neme12** [comment]
Regarding the original suggestion, I agree with @AlekseyTs's point - location just represents a single location. Adding some sort of `SourceFullSpan` property to `Location` and thus having `Location` actually store 2 different spans, is weird and not what `Location` should represent. I think a better fix would be to add `public Location GetFullLocation()` to `SyntaxNode` (in addition to the existing `GetLocation()`).

**Comment by Neme12** [comment]
But really, as I said earlier, as opposed to using the location, it would be much more reliable to add some sort of serializable "syntax location" or "syntax reference" type, which would also store the depth. Even if we fixed this span/full span discrepancy, using `FindNode` only based on `Location` still won't reliably return the original node, because multiple nodes can have the same span if there's a simple wrapper node involved.

**Comment by CyrusNajmabadi** [comment]
@Neme12 if you have an approach here, can you open an API request?

**Comment by Neme12** [comment]
@Neme12 I didn't think about what the API would look like, just throwing ideas, because I don't think solving the full span discrepancy is sufficient to be able to find the same node reliably - depth is also important.

**Comment by CyrusNajmabadi** [comment]
At this point, i'm not sure  there's any value in a new API on this.  The existing APIs are sufficient, with 'getInnermost' being usable for the two cases where you might have nodes at different depths.  I'm ok closing this out as we havn't seen any external feedback on a problem here, and we've got a pattern that works well.

Any effort to introduce and use the new pattern can be spent on just using the existing pattern properly.

**Comment by Neme12** [comment]
I don't think it works well. There have been so many bugs around this because `getInnermost` isn't straightforward at all. Consumers have to think about what sorts of wrapper nodes or nested nodes there could be and which one they need to use to get the correct original syntax node they're interested. And `getInnermost` isn't a reliable solution because what if in some cases there could be a wrapper node and in other cases a nested node with the same span? It feels like a hack and it's not obvious at all. Even code fixes in the IDE have gotten this wrong many times. There should be a way to get an actual round-trippable tree location that is reliable for all cases.

**Comment by CyrusNajmabadi** [comment]
> I don't think it works well. There have been so many bugs around this because getInnermost isn't straightforward at all.

I think it's very straightforward.  Given two nodes with teh same span (a parent/child case) it gets you the child vs the parent.

But, as per above: Any effort to introduce and use the new pattern can be spent on just using the existing pattern properly.

You'd still have to get people to know and use the new API.  At which point, you can just get them to know and use this API properly.

**Comment by CyrusNajmabadi** [comment]
> And getInnermost isn't a reliable solution because what if in some cases there could be a wrapper node and in other cases a nested node with the same span?

What cases are these?  

> It feels like a hack 

I don't think it's a hack.  It's precisely the reason that parameter exists.  

> There should be a way to get an actual round-trippable tree location that is reliable for all cases.

Ok.  But you'd still have to call all the right APIs to get that to work.  You can't change teh existing behavior on the existing APIs because that could break existing code.  so you'd need to get all the features and customers to use this pattern and use it properly.

> Even code fixes in the IDE have gotten this wrong many times. 

I don't see why that would cahnge.  You'd still have IDE feature that didn't use thsi new API properly, or didn't use it at all.  IF their own PRs missed using the existing APIs properly, what woudl change in the future?

**Comment by Neme12** [comment]
> But, as per above: Any effort to introduce and use the new pattern can be spent on just using the existing pattern properly.

But my point is, there's no reliable way to do this properly. Let's say you have a syntax node B, its parent node A, which has the same span, and a child node C, which also has the same span. If you get the location of `B` and then call `FindNode` and want to get the same node back, there's no reliable way to do that. You have to work around this everywhere this has happened and everywhere that bugs appeared because of this.

I'm not sure if there's a scenario where 2 nested nodes have the same span, but it's more likely you could have a scenario where node A *sometimes* has the same span as B, and sometimes it doesn't but node C has the same span. There's simply no way to get the same syntax node back *reliably*.

**Comment by CyrusNajmabadi** [comment]
> But my point is, there's no reliable way to do this properly. Let's say you have a syntax node B, its parent node A, which has the same span, and a child node C, which also has the same span

When does this happen?  I know of no cases at all where this exists.

**Comment by CyrusNajmabadi** [comment]
> There's simply no way to get the same syntax node back reliably.

We've had like 10 years now of features and customers and so far i haven't heard of this happening to anyone (internal or external) ever.  Can you please be specific about when you've encountered this?

If you have, then i think discussing what, if anything, we may need to do about it.  If you haven't, then it sounds like designing an entirely new api for a case that has never been hit by anyone.  In which case, that seems like a wildly disproportionate approach to this.  Why *this* case for doing that?  Making these apis (at the design an impl level) is not cheap.  So i'd really want to be able to point at actual cases that we are unable to be reliable on today, where it is already causing problems (for us or 3rd parties) that this now fixes.

**Comment by ryzngard** [comment]
> > But my point is, there's no reliable way to do this properly. Let's say you have a syntax node B, its parent node A, which has the same span, and a child node C, which also has the same span
> 
> When does this happen? I know of no cases at all where this exists.

https://github.com/dotnet/roslyn/pull/32685#discussion_r250327450 is where this initially came from. It was a legitimate bug caused by this behavior.

**Comment by sharwell** [comment]
There is not always an unambiguous span difference. Here's a simple example:

```csharp
Method(x);
```

Is this code, the span `x` is both the `Span` and `FullSpan` of both a `ArgumentSyntax` and an `IdentifierNameSyntax`.

**Comment by CyrusNajmabadi** [comment]
Yes.  THere are intentionally defined cases where there's a parent/child with the same span.  Specifically ArgumentSyntax/ExpressionSyntax and StatementSyntax/GlobalStatementSyntax.  The question is if there are cases with 3 level in the tree with the same span.  That wasn't supposed to be something that shouldn't happen with correct syntax.

**Comment by sharwell** [comment]
I'm not sure we need to make any change here. The other behavior is available by calling `node.SyntaxTree.GetLocation(node.FullSpan)` instead of just `node.GetLocation()`.

**Comment by CyrusNajmabadi** [comment]
Closing out as non actionable.
