### ISSUE TITLE
make Sqlite to handle error better

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#32819]
we have bunch of NFW on SqlException such as 

..

Microsoft.CodeAnalysis.SQLite.Interop.SqlException: disk I/O error
disk I/O error
   in Microsoft.CodeAnalysis.SQLite.Interop.SqlConnection.Throw(sqlite3 handle, Result result)
   in Microsoft.CodeAnalysis.SQLite.Interop.SqlConnection.ExecuteCommand(String command, Boolean throwOnError)
   in Microsoft.CodeAnalysis.SQLite.SQLitePersistentStorage.Initialize(Solution solution)
   in Microsoft.CodeAnalysis.Storage.AbstractPersistentStorageService.TryCreatePersistentStorage(Solution solution, String workingFolderPath, AbstractPersistentStorage& persistentStora

…

looks like when this kind exception is thrown on write, we just leak the exception out rather than handling it by returning "false"

didn't dig in through so not 100% sure how it is handled, but opening issue since SqlException is top 1 NFW issue we have.

**Comment by heejaechang** [comment]
link to NFW - https://watson/Bucket?iEventType=666&OrderBy=1&MaxRows=100&P3=vs.ide.vbcs.nonfatalwatson

**Comment by CyrusNajmabadi** [comment]
> looks like when this kind exception is thrown on write, we just leak the exception out rather than handling it by returning "false"

Can you provide more data on what the exceptions are?  I do not have access to `https://watson`.  

IOException seems like something necessary to handle, since we can't know when there are transient IO errors outside of our control.  

```
in Microsoft.CodeAnalysis.SQLite.Interop.SqlConnection.Throw(sqlite3 handle, Result result)
in Microsoft.CodeAnalysis.SQLite.Interop.SqlConnection.ExecuteCommand(String command, Boolean throwOnError)
```

These are critical to know more about.  This indicates a logic bug somewhere. If we are throwing, it means something handled that we didn't expect.  And it's necessary to investigate to figure out what it was we didn't expect and fix it either by:

1. figuring out what previous mistake we made that got us here.
2. figuring out if this is something that can happen even if everything up to that point was fine, and we just need to handle it (i.e. like sqlite_busy)

**Comment by CyrusNajmabadi** [comment]
This was handled.
