### ISSUE TITLE
VB intellisense fails to show dot-completion-list after array literal

### ISSUE THREAD

**Issue by ljw1004** [dotnet/roslyn#3290]
```vb
Module Module1
    Sub Main()
        Dim x = {1}|
    End Sub
End Module
```

Repro: position your cursor where the caret is, and press "dot"

WHAT I EXPECT: It should show a load of members in the intellisense drop-down list, e.g. .Concat, .Length, .CopyTo, .ToList.

WHAT I GET: no intellisense completion list at all.

**Comment by rchande** [comment]
@AnthonyDGreen `{1}` in this case gets parsed as a CollectionInitializer and SemanticModel.GetTypeInfo returns a TypeInfo whose type is null and whose ConvertedType is Array(Int). Why does it return only a ConvertedType?

**Comment by AnthonyDGreen** [comment]
Because per the spec array literals (which just consist of a collection initializer) are typeless expressions like lambdas, AddressOf, and the Nothing literal. These expressions don't have an intrinsic type but are reclassified/converted to a type. So, for instance given the statement:

```VB.NET
Dim arr As Integer() = {"1", "2", "3"}
```

It is not the case that this is a string array that's converted to an integer array - that's impossible. It an array literal expression that's reclassified as an Integer array. That's only possible because the expression isn't realized with an intrinsic type first.
