### ISSUE TITLE
Does this method just return false?

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#32964]
I'm not a VB expert, but it seems this method just returns false?

https://github.com/dotnet/roslyn/blob/6296ea1dc694724335a9310266eacfa6e1931245/src/Workspaces/VisualBasic/Portable/Formatting/DefaultOperationProvider.vb#L103-L116

**Comment by AdamSpeight2008** [comment]
`Continue For ` jumps to next loop iteration ignoring code between where it stated to the corrisponding `Next`

If the condition in the if statement is true it can return true, otherwise it will return false. 

A colon is used in labels eg. `StartOfLoop:`
StatementSeparator eg `Statement1 : Statement2`

I think that condition is the second possiblity.  To splitting statements over multiple lines. 

eg 
IF condition THEN Statement1 : _
Statement2

Theree should be unittest in the parser that will cover it.

**Comment by jmarolf** [comment]
Looks like it, this is the equivalent C# code.
```C#
private bool ColonTriviaFollowedByLineContinuation(IEnumerable<SyntaxTrivia> triviaList)
{
	SyntaxTrivia  previousTrivia = default;
	foreach (SyntaxTrivia trivia in triviaList)
	{
		if (previousTrivia.RawKind == SyntaxKind.None ||
            trivia.RawKind == SyntaxKind.None)
		{
			continue;
		}

		if (previousTrivia.RawKind == SyntaxKind.ColonTrivia && 
            trivia.RawKind == SyntaxKind.LineContinuationTrivia)
		{
			return true;
		}
	}
	
	return false;
}
```

I assume it should be this:
```VB
Private Function ColonTriviaFollowedByLineContinuation(triviaList As IEnumerable(Of SyntaxTrivia)) As Boolean
    Dim previousTrivia As SyntaxTrivia = Nothing
    For Each trivia In triviaList
        If previousTrivia.RawKind = SyntaxKind.None OrElse trivia.RawKind = SyntaxKind.None Then
            Continue For
        End If

        If previousTrivia.RawKind = SyntaxKind.ColonTrivia AndAlso trivia.RawKind = SyntaxKind.LineContinuationTrivia Then
            Return True
        End If
        
        previousTrivia = trivia
    Next

    Return False
End Function
```
