### ISSUE TITLE
Regex: Error message incorrect for empty character set

### ISSUE THREAD

**Issue by chborl** [dotnet/roslyn#32996]
```csharp
using System.Text.RegularExpressions;

namespace ConsoleApp27
{
    class Program
    {
        static void Main(string[] args)
        {
            //language=regex
            string s = @"foo[]bar";

            var MyRegex = new Regex(@"folder[]name");
    }
}
```

Expected: Warning "Empty [] set"

Actual: Warning "Unterminated [] set"

**Comment by CyrusNajmabadi** [comment]
The way regex works, `[]x]` is legal.  the first `]` is actually part of the character set.

**Comment by CyrusNajmabadi** [comment]
This is what happens if you actually run this regex:

![image](https://user-images.githubusercontent.com/4564579/52037245-50021280-24e3-11e9-8529-99f517b46eaf.png)

A core goal of the Roslyn regex-integration is to match the behavior of the underlying engine.  We don't want one set of errors in the IDE and one at runtime.  Since we are properly following the underlying engine, this behavior is by design.

If you want a different error here, please file a CoreFx bug.  If/when they change things, we can then update Roslyn accordingly.
