### ISSUE TITLE
Regex string not colorized until completed

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#32992]
**Version Used**: 
![image](https://user-images.githubusercontent.com/41759/52027129-1e775000-24bf-11e9-8bcf-6c47889e1c9a.png)

**Steps to Reproduce**:
Start typing regex string without the string being completed:

**Actual Behavior**:
![image](https://user-images.githubusercontent.com/41759/52027141-27682180-24bf-11e9-85d1-becf388e93f8.png)

Notice the parentheses are not colorized.

**Expected Behavior** (without the right quote):
![image](https://user-images.githubusercontent.com/41759/52027173-3fd83c00-24bf-11e9-9039-959658dee5cc.png)

**Comment by CyrusNajmabadi** [comment]
Yes.  This is intentional.  Otherwise we don't know what invariants about the individual chars might be broken.  As hte compiler does not expose an error tolerant API here, and we don't want to reimplement all the rules, we just bail.  Note: this is less of an issue due to brace-completoin spitting out the close quote when you write the open quote.

**Comment by CyrusNajmabadi** [comment]
Going to close out as "wont' fix".  This would add a lot of complexity in the impl (which already has a lot of code :) ).  The default behavior of the IDE is to pair quotes anyways, and getting into a 'good' state here is just the addition of a single quote character.    So the cost does't seem worth it IMO.
