### ISSUE TITLE
Completion appears for null-conditional operator against actual types

### ISSUE THREAD

**Issue by tenor** [dotnet/roslyn#33]
In VS 2015 CTP 5, typing:

Console?.      (Will cause member completion to appear)
String?.Join(      (Parameter completion appears)
String?.Split(      (Parameter completion appears even though Split is not a static method)

In these two examples, the null conditional operator is used on actual types (not instances).
Completion shouldn't pop up in these cases so the developer knows something is wrong.

**Comment by rchande** [comment]
I don't think we should change this. The error messages make it fairly clear that you need an instance or to not use ?. .

**Comment by Pilchie** [comment]
Even if there are clear errors, what is the motivation for not fixing?  Seems like it's still better to not guide users down the wrong path.

**Comment by rchande** [comment]
I suppose I would rather finish typing my current thought and then go fix the error, instead of typing "?.", wondering why completion didn't come up, and then fixing the error and continuing.

**Comment by Pilchie** [comment]
That's a valid argument in some cases, but I don't think all.  I'm not sure how to express the principle, but this feels to clearly wrong to me.  Using that argument, should we also always show static/instance methods regardless of context?  What about inaccessible things?

**Comment by rchande** [comment]
What stands out to me is where you’d have to go to correct the error. If you use instance members in a static member, you have to leave the thing you just typed to either make the static instance or find the instance members and make them static. Similarly, correcting the use an of inaccessible thing  requires you to do something else entirely, or go tweak accessibility somewhere. I agree that we wouldn’t want to guide the user down the wrong path in these cases, because whatever they do will be completely wrong and will have a non-obvious fix. In the ?. case, you simply have to realize that ?. doesn’t operate on types and delete the “?”.

Maybe that’s too subtle and we should just fix this, though ☺.

**Comment by Pilchie** [comment]
Let’s just fix it ☺
