### ISSUE TITLE
CodeLens does not show test running status on expression-bodied test method in VS2019

### ISSUE THREAD

**Issue by huoyaoyuan** [dotnet/roslyn#33044]
##### 2017:
![image](https://user-images.githubusercontent.com/5644458/52135819-a3aa6280-2681-11e9-8088-90acc5246084.png)

##### 2019:
![image](https://user-images.githubusercontent.com/5644458/52136032-187d9c80-2682-11e9-97e8-e6fe10e90c5d.png)

**Comment by jinujoseph** [comment]
cc @shyamnamboodiripad

**Comment by shyamnamboodiripad** [comment]
I am able to see the glyphs on such methods in latest internal builds -
![image](https://user-images.githubusercontent.com/10579684/52620041-44560a80-2e58-11e9-88ce-fc58d4faad59.png)

However, currently the glyphs only appear if -
1. I have explicitly built the project at least once after adding tests. This is known issue that we are tracking internally and plan to address in an upcoming update.
2. The Test Explorer window has been opened at least once previously during the session. cc @drognanar to confirm whether this is by design. (I seem to recall past discussions that opening a file containing tests will cause the test explorer package to be loaded even if the test explorer pane is not open because the glyphs have to be displayed. However, the glyphs don't seem to be displayed until I open the test window pane.)

**Comment by sharwell** [comment]
> I have explicitly built the project at least once after adding tests.

This was the key for me. Every time a new test is added, the glyph will not appear until the project is built again. This applies even if I have already built the project one or more times after opening the IDE.
