### ISSUE TITLE
IntelliSense isn't simplifying optional parameter defaults

### ISSUE THREAD

**Issue by stephentoub** [dotnet/roslyn#33049]
**Version Used**: 
Version 16.0.0 Preview 3.0 28531.182.d16.0

**Steps to Reproduce**:
Paste this code into VS:
```C#
class Program
{
    static void Main()
    {
        Foo();
    }

    static void Foo(MyStruct s = default) { }
}

struct MyStruct { }
```
then get IntelliSense for the `Foo` method:
![image](https://user-images.githubusercontent.com/2642209/52147778-bc8d2680-2635-11e9-87de-e88414f66193.png)
It shows `MyStruct s = default(MyStruct)` rather than `MyStruct s = default`, even though a) the method is defined with just `default` and b) my editorconfig settings are set to simplify, e.g. if I instead have the parameter declared as `MyStruct s = default(MyStruct)`, VS dutifully tells me I should simplify it:
![image](https://user-images.githubusercontent.com/2642209/52147842-f3633c80-2635-11e9-9010-9cba2a6333d2.png)

**Comment by CyrusNajmabadi** [comment]
Specifically, this is just QuickInfo.  But i totally agree it should be fixed up to just use the simpler form (and should likely use that form regardless of the .editorconfig setting).  It's possible this would potentially be different depending on your language version.  But i would also be ok with this always being the form used regardless of the language version as it is:

1. Far more compact and clean.
2. Completely understandable, even if you're on a previous version of the language.

i.e. since this is just 'display' code, we can just pick this as our reasonable way of always showing default struct values.
