### ISSUE TITLE
The Document.Folders property is empty for ClassLibrary (C#, VB) .Net Framework in VS2019 16.0.0 Preview 2.2

### ISSUE THREAD

**Issue by Droni** [dotnet/roslyn#33171]
**Version Used**: 
Visual Studio 2019 16.0.0 Preview 2.2
**Steps to Reproduce**:

1. Create a new ClassLibrary (C# or VB) .Net Framework project
2. Add a new folder with some name
3. Add a new class to this folder 

**Expected Behavior**:
The Document.Folders property should contain a folder name when the class is declared
**Actual Behavior**:
The Document.Folders property is empty

**Comment by heejaechang** [comment]
@Droni what do you mean by "Document.Folders"? are you referring this? http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Workspace/Solution/TextDocument.cs,53

**Comment by jasonmalinowski** [comment]
Yeah, indeed this is empty.

@tmeschter this appears to be broken due to 5b250f67. Now we're getting the call to AddFile that takes the link metadata, but the metadata is empty. I think the implicit contract here would be if it's _not_ a linked file, we should be using the relative path of the project file. Is that something that needs to be fixed on the project system side or on our side?

**Comment by Droni** [comment]
@heejaechang Yes, that is what I meant.
The problem manifests itself only on .Net Framework projects. For .Net Core and .Net Standard the behavior does not change.

**Comment by tmeschter** [comment]
@jasonmalinowski I'd prefer to just have the project system provide the path and the link metadata (if any) as-is, and leave the interpretation to the language service.
