### ISSUE TITLE
Auto completion for goto and goto case

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#33215]
When typing after a ```goto``` keyword in Visual Studio, the IntelliSense drop-down list now shows all code snippets and existing labels. It would be good to enhance this feature by including '```case xxx```' in the list if ```goto``` is in a ```switch``` block (or show all ```case``` labels after typing ```goto case```) and make the list appear once a space after the ```goto``` keyword is typed (instead of when starting typing the label name). Furthermore, code snippets can be removed from the list as a ```goto``` proceeding any reserving keywords (generated by the snippets) other than ```case``` makes no sense in the language. 

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/441435/auto-completion-for-goto-and-goto-case.html
VSTS ticketId: 782010_
_These are the original issue comments:_

Hafnia Vasilyevna on 1/30/2019, 08:55 PM (7 days ago): <p>*The last sentence should be "... preceding any reserved keywords...", sorry for the typo :)</p>

Jane Wu [MSFT] on 1/31/2019, 01:52 AM (7 days ago): <p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;We'll provide an update once the issue has been triaged by the product team.</p>
Kendra Havens [MSFT] on 2/1/2019, 03:41 PM (5 days ago): <p>Thanks for filing this feedback! Just to check, is it safe to assume you are specifically referring to 'goto' statements in Visual Basic? (Not C++?)</p>

Hafnia Vasilyevna on 2/1/2019, 08:01 PM (5 days ago): <p>I'm using C# currently, not sure about the situation in other languages. </p>

**Comment by sharwell** [comment]
Design review conclusion:

1. After typing `goto` in a switch case, the `case` keyword *should* be offered in completion (and it is)
2. After typing `goto` in a switch case, the `default` keyword *should* be offered in completion (and it is)
3. After typing `goto case` in a switch case, completion *may* offer to complete one of the existing cases in the same switch statement, similar to how enum member completion works

Since the first two items are already correctly implemented, this issue remains a feature request and moves to **help wanted**.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
