### ISSUE TITLE
C# smart indenting after single-line comment and a newline

### ISSUE THREAD

**Issue by pharring** [dotnet/roslyn#3321]
Type the following into a new C# class library:

``` C#
class Repro
{
    // comment$
    private int _field;
}
```

Place the caret at the end of the single-line comment (where the $ is).
Press Enter twice

Result:
After the first enter, auto-indent aligns the caret with the comment and private field. After the 2nd Enter, it indents another 4 chars.

Expect:
The indent should stay at 4 chars

This feels like a recent regression.

**Comment by pharring** [comment]
This is with InstallDogfood bits from 20150603.2

**Comment by pharring** [comment]
It's a regression from Dev12, but apparently it's been there for a while. It repros in ETA as far back as 20150205.1

**Comment by Pilchie** [comment]
@mattwar didn't you look at something similar near RTM?

**Comment by mattwar** [comment]
It sounds familiar.

**Comment by leppie** [comment]
sub

**Comment by leppie** [comment]
Is there an issue for properties for the following:
```
class F {
  public string B {get;set;}
  // now type a property here (when D is defined), and it gets formatted as
  public string C 
  {
    get;
    set;
  }
  public string D {get;set;}
  // do the same, it is fine here
  public string E {get;set;}
}
```

**Comment by verelpode** [comment]
For reference, this bug persists in VS 2019 16.0.0.  I don't know whether another example code snippet would be helpful to have, but here it is -- I hope this helps.  The following snippet reproduces the bug.  I experience this bug frequently.

```
namespace TestNamespace1
{
    class TestClass1
    {
    }

    // Test comment.





    class TestClass2
    {
    }
}
```

Put the above code in a .cs file and then try clicking in each blank line after `// Test comment.`  When you click in each blank line, don't click too close to the left side.  Click sufficiently far right in each blank line, in order to see the bug.  

In the following, the "|" character marks the positions where the text insertion bar/caret appears when you click in each blank line.  (I mean, don't copy the following into a .cs file, rather the following is intended to be a diagram.)

```
namespace TestNamespace1
{
    class TestClass1
    {
    }

    // Test comment.
    |
        |
        |
        |
        |
    class TestClass2
    {
    }
}
```

Although I have the C# tabs option set to "Keep tabs", I also tried it with "Insert spaces" and the bug occurred regardless of whether I set it to tabs versus spaces.  My other settings are:  Tab size = 4.  Indent size = 4.  Indenting = Smart.

**Comment by CyrusNajmabadi** [comment]
Not repro.  I get the expected behavior:

![image](https://user-images.githubusercontent.com/4564579/217118807-9063155a-9cb8-432c-90dc-fecdc80cc8a8.png)
