### ISSUE TITLE
Better support for InvalidTypeCast  Warning

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#33286]
Reported by internal customer Sudhanshu Gupta  

Code snippet looks like: 
```
foreach (MimeRecipient recipin headerNew)
       { … }
```
 
Where enumerator for headerNew returned base type IEnumerable<MimeNode> while I casted it to MimeRecipient : MimeNode
This led to a Typecast exception in a corner scenario where object was another derived type of MimeNode. 
Is there a way to provide warning for such scenarios.

**Comment by mavasani** [comment]
I feel providing an IDE analyzer/fix for the scenario might actually be discouraging use of a C# language feature, specifically ability to perform an upcast on the elements being enumerated in a foreach loop by specifying an explicit type for the loop variable.

Let me add some more context before giving my stance on this feature. Consider the below example with simple type hierarchy and possible ways that someone might write foreach loops:

```csharp
using System.Collections.Generic;

class Base { }
class Derived : Base { }
class C
{
    void M(List<Base> listOfBase, List<Derived> listOfDerived)
    {
        // 1.
        foreach (var b in listOfBase) { }
        // 2.
        foreach (var d in listOfDerived) { }
        // 3.
        foreach (Base b in listOfBase) { }
        // 4.
        foreach (Derived d in listOfDerived) { }
        // 5.
        foreach (Base b in listOfDerived) { }
        // 6.
        foreach (Derived d in listOfBase) { }
    }
}
```

1. Cases 1 and 2 are the most common forms of the loop.

2. Cases 3 and 4 are used when either when developer prefers explicit types over ‘var’ OR when the type of the loop variable is not apparent, for example if the collection being iterated is coming from a method call.

3. Case 5 is generally used when the loop variable is only used to access members off the base type.

4. Case 6 – This is the scenario brought up in this email thread. It is also the only case amongst the above cases where an explicit conversion/upcast is performed and hence can lead to an invalid cast exception. Resharper outright flags this as an unsafe way to write your code, but it is indeed a C# language feature that you can provide a supertype as loop variable type to force this upcast when you are sure that listOfBase contains all Derived instances.

I personally agree with Resharper here – given how common forms 3, 4 and 5 are in a code base, it is extremely likely that a user might end up with form 6 by accident rather than on intent. I wish the C# language would have required a different syntax for form 6 to avoid accidental use of this form, say a parenthesized type syntax such as:  ‘foreach ((Derived) d in listOfBase)’. This way form 6 above would have been a semantic compiler error as it would require an implicit conversion from Base to Derived, which doesn’t exist.

Coming back to the feature being requested here – if we decide to implement this analyzer/fixer, there are likely couple of issues:
1. We are explicitly flagging every use of a particular C# language feature in the IDE and recommending developers to not use it – I don’t think any other IDE analyzer/fixer does this.
2. The viable code fixes to offer when this analyzer fires would be:
   1.	```foreach (var d in listOfBase.Cast<Derived>()) { }```
Use Linq to clarify intent on using an upcast. Might be unpopular with anti-Linq folks – why is the IDE recommending Linq over compiler syntax to do the same thing?
   2. ```foreach (Base b in listOfBase) { var d = (Derived)b; }```
This form seems reasonable but the immutability of ‘d’ is now lost as it is not the loop variable anymore.

**Comment by mavasani** [comment]
Actually thought of another viable code fix that we can offer here, which might solve Sudhanshu’s case and also majority of accidental usages of case 6.
If we analyze all references of loop variable `Derived d` and find that it only accesses `Base` type members, then we can offer a code fix to convert it to form 3. This would be a non-controversial analyzer/fix, which could be a good first step to address this specific feature request. 

Confirmed with @jinujoseph that we should take this as the initial approach.

**Comment by CyrusNajmabadi** [comment]
We do recommend you cast here:

![Image](https://github.com/user-attachments/assets/9f94312f-e2b5-4d5d-89b1-5ca22ff0a3de)
