### ISSUE TITLE
Block comment / uncomment

### ISSUE THREAD

**Issue by dibarbet** [dotnet/roslyn#33298]
## Feature
Similar to other IDEs and languages, support for block comment / uncomment functionality would be useful.
Some examples:
https://www.jetbrains.com/help/ruby/commenting-and-uncommenting-blocks-of-code.html 
https://www.jetbrains.com/help/resharper/Coding_Assistance__Comment_Uncomment_Code.html 
https://www.jetbrains.com/help/idea/using-code-editor.html
https://code.visualstudio.com/shortcuts/keyboard-shortcuts-windows.pdf

## Proposal
In general, we are proposing a new 'toggle block comment' command.  This command will be mapped to a single shortcut and will only act on block comments (not single line comments).

### Command
The block commenting command will be a *toggle* based command.  If the span selected contains a block comment it will be removed; otherwise, a block comment will be added.  Details on the exact functionality will be explained below.  

It will be accessible through a keyboard shortcut which by default would be mapped to `Cntrl + Shift + /`.  This mapping is currently unused in a default visual studio installation.  

#### Notes
1.  Toggle behavior is almost universal across editors that have block comment functionality.  
2.  `Cntrl + Shift + /` happens to be the same command used by resharper for the same functionality.  We considered alternatives such as `Shift + Alt + A` (the VS Code block comment command) but it was unfortunately already in use by **Project.AddExistingItem**

### Functionality
The same command will both add and remove block comments depending on the context that the user has selected (highlighted).

#### Removing block comments
1.  The selection contains a block comment section (plus whitespace).  _Matches current uncomment behavior._  <img width="767" alt="remove_entirely_within" src="https://user-images.githubusercontent.com/5749229/52743719-89c92380-2f8f-11e9-991b-647538774fba.png">
2.  The selection is contained entirely inside a block comment section.  _Matches current uncomment behavior.  Other toggle block comment features usually do nothing._  <img width="748" alt="remove_comment_around" src="https://user-images.githubusercontent.com/5749229/52743837-cb59ce80-2f8f-11e9-9d08-d1f43f7aa5ed.png">
3.  The caret is inside a block comment section.  _Matches current uncomment behavior._  <img width="755" alt="caret_inside_remove" src="https://user-images.githubusercontent.com/5749229/52743887-e9273380-2f8f-11e9-95fb-3045b5cd7b80.png">
4.  The caret is before the block comment open marker or after the block comment close marker on the same line with only whitespace.

#### Adding block comments
1.  The selection contains no block comments.  <img width="742" alt="add_selection" src="https://user-images.githubusercontent.com/5749229/52743938-0d831000-2f90-11e9-8132-ff47bfe95b12.png">
2.  The caret is not inside a block comment.  A block comment will be added after the caret at the next whitespace.  _Similar to R#._  <img width="748" alt="add_caret" src="https://user-images.githubusercontent.com/5749229/52744141-b3367f00-2f90-11e9-9114-b71413820c8d.png">
3.  The selection contains all of a block comment plus other code.  <img width="746" alt="code_plus_block" src="https://user-images.githubusercontent.com/5749229/52747954-f77a4d00-2f99-11e9-8d53-b8d5b417bdcc.png">  In this case, the comment will be *extended* to cover the newly selected pieces with multiple comments blocks.  <img width="741" alt="code_plus_block_result" src="https://user-images.githubusercontent.com/5749229/52747989-1e388380-2f9a-11e9-8864-918769cccff1.png">  _This is similar to how intellij functions._
4.  The selection contains part of a block comment plus other code.  <img width="749" alt="partial_code" src="https://user-images.githubusercontent.com/5749229/52748193-ba628a80-2f9a-11e9-9b5a-68491bf18ebf.png">  When this case happens, we will add additional comments to cover the extra code being selected.  <img width="751" alt="partial_code_result" src="https://user-images.githubusercontent.com/5749229/52748236-d9f9b300-2f9a-11e9-8117-90bbd4430c11.png">
5.  The caret is before (or after) the block comment open (or close) marker with only whitespace in between but on a different line.

#### Highlight
The comment section being added or removed will be selected once the command completes.  *Matches current behavior.*

### Changes to UI
No icon will be introduced for this command for the following reasons.
1.  Introducing a toggle block comment icon would not make sense unless the current comment / uncomment icons were made into a single toggle button.
2.  Adding two new icons to block comment or block uncomment would not work with a toggle command.  The preference is for toggle over add / remove.
3.  The existing icons and UI is rather unhelpful already.
4.  We guess that these icons are rarely ever used over the keyboard shortcuts (TBD is that data available?)

### Changes to existing comment / uncomment commands.
The existing comment / uncomment commands will be left as-is.  We want to avoid breaking users' existing workflows that they may be used to.  This means that
1.  The single line comment command can create a block comment when the selection is inside a single line.  <img width="752" alt="within_line" src="https://user-images.githubusercontent.com/5749229/52744601-02c97a80-2f92-11e9-95e7-8af8903827db.png">
2.  The uncomment line comment command can uncomment block comments with similar functionality to block uncomment.

### Current VS Functionality
VS currently has separate comment and uncomment commands (comment: `Cntrl+K,Cntrl+C`, uncomment: `Cntrl+K,Cntrl+U`).  These commands also have representation in the UI.

![comment_selection](https://user-images.githubusercontent.com/5749229/52589534-ea235e00-2df3-11e9-82c0-61999b9346d2.png)

Commenting a selection will comment all lines that the selection spans with a single line comment.  If the selection is inside one line, it will use a block comment on the selection.  
Uncommenting a selection tries the following steps in order.
1.  Uncomment a block comment span if the selected span exactly matches the block comment span.
2.  Uncomment any single line comment (or multiple single line comments) on the selected span's lines.
3.  Uncomment any block comment that surrounds the selected span.

### Resharper Functionality
Resharper has separate command *toggles* for dealing with single line comments and block comments.
`Cntrl+Alt+/` will comment and uncomment single line comments.  `Cntrl+Shift+/` will comment and uncomment block comments.  If there is a selection, it will add a block comment around the selection.  If the selection exactly matches a block comment, it will uncomment the selection.  If the selection is within a block comment it will do nothing.  If the *caret* is inside a block comment, it will uncomment the block.

### Intellij
Block comments are toggled in intellij with `Cntrl+Shift+/`.  It functions the same as resharper.

### VS Code
`Shift+Alt+A` toggles block comments in VS code.  This toggle looks at the *lines* of code to determine whether or not to comment or uncomment the block.  If the first and last line of the selection contain block comment characters, it will uncomment them.  Otherwise, it will add a comment (even inside an existing block).

**Comment by CyrusNajmabadi** [comment]
From a conversation on the implementation over at: https://github.com/dotnet/roslyn/pull/34066#pullrequestreview-213718283

I don't see any need for this to be block-comment specific.  A general 'toggle comment' feature seems like it would handle a superset of these cases and woudl generally work for both sorts of comments in C# and would work for line-comments in VB.  That seems more desirable than overly specializing on block comments.

**Comment by heejaechang** [comment]
I am on the side where we finish block comment first and then refactor it to merge with others rather than making things complicated by merging this work with other things before block comment work itself didn't get finalized.

@dotnet/roslyn-ide @jinujoseph 

for those, supporting other languages and consolidating it with other related features, i would open tracking issue. it can be work item containing multiple steps with this being the first step and others being next steps. or just plain separate issues.

since the feature will be in with feature flags (off by default), it won't be exposed to public anyway.

**Comment by jasonmalinowski** [comment]
Isn't the only "shared" work defining the commands? The problem with doing this "on our own" first is it makes the transition process a lot trickier, especially if we have to redefine the commands and move then in a VSCT. Since that implicitly includes the package GUID, I'm not sure what might all break.

**Comment by dibarbet** [comment]
The commands are going to be defined by the editor team.  In this case the shared work being referred to is the implementation of the actual toggle.

For example, the current [comment, uncomment handlers](http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures/Implementation/CommentSelection/CommentUncommentSelectionCommandHandler.cs,674a07aad4f49bae) are implemented using text based parsing and are re-used by F# / typescript etc.  It abstracts the retrieval of the comment info (characters, if block comments are supported) out to a service that other languages can implement.

I believe the question for this one is if we want to do the same for toggle block comment.  I believe we have roughly 3ish options.
1.  Use only text based of comments, F#/Typescript can re-use the same implementation as-is.  Note that we would run into issues with things like ```string s = "*/"```.  Also note that there would not be any variations in functionality for this feature across the languages this way.
2.  Abstract part of the functionality out, like retrieving commented spans or the next caret location after a token, into a service.  This would allow us to use the syntax tree for c# (to avoid the above issue) when we need it, but leave most of the implementation of adding and removing comments the same for both.
3.  Abstract the entire functionality out to a service (send in a document, service returns the document).  This would allow us and F#,typescript ,etc. to implement the feature in whatever manner they wish, but we wouldn't be sharing much else other than an almost empty command handler.

**Comment by CyrusNajmabadi** [comment]
I would start with '1'.  It was totally sufficient for the current comment/uncomment handler (i know, i wrote it and implemented for all these languages) :D   So i think it would likely be sufficient for 'toggle comment'.  It's also the quickest and cheapest IMO.

**Comment by CyrusNajmabadi** [comment]
> for those, supporting other languages and consolidating it with other related features, i would open tracking issue. it can be work item containing multiple steps with this being the first step and others being next steps. or just plain separate issues.

This seems more complicated and costly than just doing the right thing from the start and implementing in a fashion taht works for all these languages.  I did the original comment/uncomment work, and it was exceptionally cheap to do.

If the team isn't willing or interested in making this feature work from the start in a multi-language fashion, i'd be happy to have it reassigned to me and i can use my time to do that.  I'd much rather just add features that are good, and work for the entire roslyn ecosystem myself, than have us do one offs for C# and only then do right for the rest of the community after endless meetings and needing customers to have to ask for this sort of thing.

**Comment by CyrusNajmabadi** [comment]
Note: i was the person who did the original service here and got it working for C#/VB.  I wanted to make sure something so basic was trivial for JS/TS/F# to implement.  That's why the entire F# impl can be seen here:

```f#

20 lines (16 sloc) 941 Bytes
namespace Microsoft.VisualStudio.FSharp.Editor

open Microsoft.CodeAnalysis.CommentSelection
open Microsoft.CodeAnalysis.Host.Mef
open System.Composition
open System.Threading.Tasks

[<Shared>]
[<ExportLanguageService(typeof<ICommentSelectionService>, FSharpConstants.FSharpLanguageName)>]
type CommentSelectionService() =
    interface ICommentSelectionService with
        member this.GetInfoAsync(_document, _textSpan, _cancellationToken) =
            Task.FromResult(CommentSelectionInfo(supportsSingleLineComment=true,
                                                 supportsBlockComment=true,
                                                 singleLineCommentString="//",
                                                 blockCommentStartString="(*",
                                                 blockCommentEndString="*)"))

member this.FormatAsync(document, _changes, _cancellationToken) = Task.FromResult(document)
```

And the entire TS/JS impl is similarly small.  We should be striving to deliver a great and consistent experience to our customers across all these languages.  That's one of the core deliverables of the Roslyn project.  Finally, we have found time and time again that we produce *better* software, with higher-quality-designs, and cleaner implementations, when we consider and implement the cross-language solution up front.  We better separate out responsibilities.  We better factor the different layers needed.  We are able to share more code because we don't just have a single file that is just "everything" all gooped together.  

In fact, the "single file with everything gooped together" is how roslyn started, and it meant we paid the price over and over again just for the *two* languages we were supporting.  But thinking about things in a cross-language fashion we would make thigns cheaper by being forced to properly separate and reuse.

**Comment by dibarbet** [comment]
Some good news :), I have consensus from the other languages that they're fine with our experience, so we'll be going with 1 or 2.

They said they could provide the information needed for 2 as well.
Putting this in the design review queue to review the points brought up on 1 vs 2.

**Comment by jasonmalinowski** [comment]
I'm going to give one small nitpick here to @CyrusNajmabadi's otherwise correct statements:

> Finally, we should be striving to deliver a great and consistent experience to our customers across all these languages. That's one of the core deliverables of the Roslyn project.

That's actually the motto of the Platform team. 😉  Given that C++ and "non-Roslyn" languages will want this too, we should really push to make sure this isn't Roslyn specific. Roslyn being the "better IDE APIs" was a workaround the platform not producing good APIs, but now that they're both pushing hard for that _and_ we're One Microsoft we should just make sure that happens properly at the editor layer.

**Comment by CyrusNajmabadi** [comment]
I'm fine with this happening at the editor layor.  I also have no issue with someone doing the legwork and then migrating as necessary. Roslyn is well positioned here because of the huge investment in this area. So, to me, it makes sense to cheaply do this for many languages at the Roslyn layer. Then, if editor wants to move over to their sure, hooray.  

What o would like to avoid though is hoping editor will do it, only to find 10 years has passed and we're no closer.  That happened way too often in the past. And if we have done the work wed done in Roslyn, projects like TS would have been 10x more expensive

**Comment by CyrusNajmabadi** [comment]
>and "non-Roslyn" languages will want this too, 

Note: I long held that Roslyn should be the base.  Editor is the great platform for representing text and the presentation of features into it. Roslyn is the great platform for orchestration of features and representing *languages*. My goal was always that we would 'prove out' this with 4-5 languages.  Then open up to all languages once we had confidence.  Alas, the best laid plans

**Comment by jasonmalinowski** [comment]
At this point we're working very closely with the editor team on other things (say, the async completion) so this just fits in that way. I'm just sensitive that right now Roslyn acting as a in-between for the editor and their code is a large tax on our development right now.

> My goal was always that we would 'prove out' this with 4-5 languages. Then open up to all languages once we had confidence. Alas, the best laid plans

Indeed, alas. And maybe that's still the direction we should go. (If it is, we sure need more resources!) Just our middle ground is right now has already gone past the breaking point right now and I don't want to stoke the fire further.

**Comment by CyrusNajmabadi** [comment]
This feels like shipping the org chart though.  Roslyn powers all these facilities. If management thinks they're important enough to focus on, why does it not feel like it's worth investing in in terms of team resources.  

> is a large tax on our development right now.

Sure. But id prefer a focus on the user. We go: oh, will just do it got c#.  And we slowly slide back to the time when customers would bounce between languages and continually report the deficiencies between them.   I know it's a fallacy, but we literally have sunk man centuries into this, and all of a sudden it seems like we rather just not give users a consistent experience, rather than just ramping up. 

Does management not factor in costs here for you sort of thing?  I.e. the 2% extra time spent here saves whole other teams the cost of having to implement this...  Why is it that were always willing to try to do less work to vastly increase external costs?

It feels like the continued behavior of shipping and rewarding the org chart. Imagine, for example that js/TS actually reported through Rosslyn, and this people got rewarded for this.  Do you imagine we'd do things differently?

**Comment by jasonmalinowski** [comment]
We're working to make sure all the teams get the experience. That's a distinct statement than "Roslyn must implement APIs for them". I recognize you want Roslyn to be the platform for everything, but practically we've been focusing on making sure the platform provides good enough APIs that Roslyn doesn't have to be in the middle as well. And there are plenty of cases where the platform absolutely doesn't meet that, but we hope that there are some too where it's fine.

**Comment by dibarbet** [comment]
Design review outcome - 
1.  We will implement the command handler as C# content type.  We can use the syntax tree as needed.  Consensus was that we would rather do this than use text parsing to offer a better c# experience.
2.  We will not expose any more service API(s) to avoid more IVT dependencies.  There are already issues with external partners depending on these kinds of interfaces, so we want to avoid adding more where we can.

Tagging @jasonmalinowski / @sharwell / @heejaechang to make sure I haven't misspoke :)

**Comment by jasonmalinowski** [comment]
What was the plan for the F#/TypeScript case? Since we didn't want to leave them out, right?

**Comment by dibarbet** [comment]
@sharwell suggested we provide assistance / documentation on our solution.

**Comment by CyrusNajmabadi** [comment]
That seems really unfortunate.  Looking at your PR, there's a lot of custom code it seems like these teams would need to start owning.  When a bug is found in one, it would then need to be ported to every other team that copies us.  This is exactly the direction we moved away from due to how high this cost was on individual teams.

> We will not expose any more service API(s) to avoid more IVT dependencies. There are already issues with external partners depending on these kinds of interfaces, so we want to avoid adding more where we can.

This seems like a small price to pay.  Esp. versus each team having to just reinvent hte wheel.  I wasn't joking that 90% of the effort and code in TS was originally just trying to have copies of Roslyn that were then maintained.  It seems utterly backward to me that our take would be to move back to that?

Also, why do you need another service API?  Why is ICommentSelectionService insufficient?

> Consensus was that we would rather do this than use text parsing to offer a better c# experience.

That seems like a strange consensus given that such an approach has worked without a single reported issue across all these languages for comment/uncomment.  Basically, the design outcome is that we will speculate that tehre is an issue, and because of that we will force all teams to have to replicate the work going on here.

This is not only extremely illogical afaict, it's also super inefficient.  I honestly can't tell who wins here.  Other language customer do not win, since those teams will likely not have the man power for a while to meet these features.  We don't win since we're not actually saving on IVT (since we already have ICommentSelectionService), and our partner *definitely* do not win since the pressure is now on them to both implement these features, but also match the behavior here properly.  Finally, there's a great loss here in that any bug is now tripled in cost across the teams.  

Totally bizarre to me, and extremely not "one microsoft" from my perspective.  This is the epitome of shipping the org chart.

**Comment by jasonmalinowski** [comment]
> This seems like a small price to pay.

We've discovered that sometimes it's a small price relative to the other code sharing costs, and sometimes it's vastly more expensive than the code sharing costs. There are definitely service sharing that we've done that was a net negative, and we're trying to learn from those experiences.

@dibarbet My expectation from the design meeting was we'd still be doing better than that and making sure F# and TypeScript had the support too? I was assuming we'd have a simple default implementation for those languages and yes, if you wanted something fancy then go ahead but that's your own risk/reward.

**Comment by dibarbet** [comment]
@jasonmalinowski That was not the outcome I understood (and is also not the outcome listed in the design meeting notes).  

I'm not opposed to that - I think it would be relatively easy to make a regular command handler for everything, and override specific pieces for c#?  I'm not opposed to that, but it is not what was agreed upon earlier.

**Comment by jasonmalinowski** [comment]
I guess I took that to mean that Roslyn won't be responsible for implementing command handlers for the other languages, but they still wouldn't be expected to implement this from scratch.

If we squint at the Roslyn handler, what are the different pieces? Can we give some reusable helpers that other languages could use too?

**Comment by dibarbet** [comment]
We can give them pretty much the whole thing I'm various forms, e.g. finding commented spans at selection, adding commented spans at selection, or going even lower to just deleting commented spans.

There are exactly two pieces that I use csharp specifics for - retrieving commented spans, and finding caret locations after the token.

I'm not really sure how you are thinking of exposing these and we probably won't get very far here.  I'll setup some time with you tomorrow to go through this more in depth.

**Comment by heejaechang** [comment]
once platform team adds blockcommenttogglecommand, F# and typescript team is free to add their own handler using new editor command handler API.

if there is any code that can be shared with F# or typescript or any other language such as C++/xaml and etc team, editor team or platform should have common utility all can reuse rather than Roslyn.

that's my understanding from the design meeting we had.

also, we talked about looking at those codes we provide to share some platform functionality with certain languages such as F#/typescript or xaml, whether we can get rid of those so that each team provides their own implementation, and code sharing is done by editor or platform rather than roslyn.

**Comment by CyrusNajmabadi** [comment]
Can't basically all the code be shared here?  That was the idea behind comment/uncomment.  It feels natural that it would be the same for 'toggle comment'. 

>if there is any code that can be shared with F# or typescript or any other language such as C++/xaml and etc team, editor team or platform should have common utility all can reuse rather than Roslyn.

This would basically be all the code. Would it not make sense to consider the work item the work to make today shared component and show that it can work for all these languages?

**Comment by CyrusNajmabadi** [comment]
It seems like there's two viable strategies we can take here.

1. platform/editor handles all of this.  Languages can plug in simply (like we've demonstrated with comment/uncommnet/icommentselectionservice).  This is the best case for all languages plugging into VS.  platform/editor could start by taking the code that roslyn already pioneered here.

2. if platform/editor isn't willing to do this, then next best option is for Roslyn to take this on.  That way we at least get toggle-comment working for the Rosly languages trivially.  

My preference is for '1'.  It's the best solution for the broadest set of languages.  However, if they can't manage this in a reasonable timeframe, Roslyn can figure this out easily for a broad enough set of languages.  Then, when editor/platform is available, we can work together with them to move this code over.

**Comment by jmarolf** [comment]
@TIHan 	@cartermp regarding the discussion about F# support

**Comment by sharwell** [comment]
The design meeting concluded the maintenance overhead for additional IVT entry points from F# and TypeScript were not worth the benefits provided for this feature. We will share our design with them, including links to our command handler, feature implementation, and tests, but the feature would only be provided in those languages if independently implemented. Code sharing could be provided by the editor libraries, but that would be a separate feature request with no clear date at which it would become available. The feature implementation in dotnet/roslyn will be restricted to languages implemented in dotnet/roslyn, which means C# only (Visual Basic does not have block comments).

**Comment by CyrusNajmabadi** [comment]
> The design meeting concluded the maintenance overhead for additional IVT entry points from F# and TypeScript

What additional entry points?  This feature can be written entirely on the existing ICommentSelectionService.

**Comment by cartermp** [comment]
What API do we need to implement for F# in light of the decisions made here?

**Comment by CyrusNajmabadi** [comment]
@cartermp I *may* be wrong, but unless some new information comes to light, i don't think you'd have to implement *any* new APIs.  You already have this implementation here: https://github.com/Microsoft/visualfsharp/blob/master/vsintegration/src/FSharp.Editor/BlockComment/CommentSelectionService.fs

Based on having that *alone* i think you are already in a place where Toggle-Block-Comment could be written once by Roslyn and have the impl work automatically for you without any effort on your side.

Note: i say i *may* be wrong because i didn't actually do the work to validate that the above is definitely true.  It's possible we may discover in the process of doing this that that API is insufficient.  I *personally* doubt it, but the proof will have to be in the pudding.  

If it turns out there is a need for more APIs, that will def change teh equation.  However, i would very much like to see us to see how far we can get with what we already have before conservatively assuming it would not work out.  Thanks!

**Comment by sharwell** [comment]
@cartermp If you want the toggle comment command to work for F#, you will need to implement the command handler *and* the implementation of the command. @dibarbet will be filing an issue on the F# editor repository once we have our feature ready to merge explaining the feature behavior design, and linking to our command handler, implementation, and tests as examples you can reference should you choose to provide the feature.

**Comment by dibarbet** [comment]
@sharwell Jason and I had a discussion today and we may have a simple way to implement this w/out IVT and use the C# syntax tree and have a good implementation for other roslyn languages.  I'm currently seeing if it will work out.

**Comment by CyrusNajmabadi** [comment]
Thanks @dibarbet, i really look forward to seeing how it turns out.  One nice thing from this should be that any specialized logic we have in our impl for strange cases should just light up for the ohter languages.  So, we can localize all that code to one place, and only have to fix issues in it there instead of having to coordinate across everyone :)

**Comment by dibarbet** [comment]
@cartermp the current version of the PR should work for F# without any additional work required from you guys.  Will keep you updated in case it changes.

**Comment by dibarbet** [comment]
Resolved in https://github.com/dotnet/roslyn/pull/34066
