### ISSUE TITLE
Compile fails in server mode on OSX involving defines

### ISSUE THREAD

**Issue by mrvoorhe** [dotnet/roslyn#33320]
This is an intermittent bug that I am only seeing on OSX with roslyn server mode enabled.  I have *not* experienced this bug a single time on Windows.

Unity is hitting this bug in our UnityLinker test suite.  The UnityLinker test framework follows the same structure as https://github.com/mono/linker.  The scenario that seems to trigger this bug is compiling the same and/or similar files in the same location with almost identical command line arguments.  The difference that seems to be key in triggering the bug is specifying a define.

In case these clues are of any use, here are things I've done that make the bug go away
* Don't use server mode
* Use `mcs`
* Change `Run2` to use different output assembly file names than `Run1`

**Version Used**: 
```
Microsoft (R) Visual C# Compiler version 2.9.1.65535 (4d10ef64)
Copyright (C) Microsoft Corporation. All rights reserved.
```

**Steps to Reproduce**:

1. Open the attached solution
2. Open `Program.cs`
3. Implement the property `YourRoslynPathOnOSX`
4. Implement the property `PathToAnMscorlibOnOSX`  (You could probably cut out the /nostdlib and get rid of this part if you wanted to)
5. Compile the solution
6. Open a terminal and cd `RoslynDefineBug/bin/Debug`
7. Run `mono RoslynDefineBug.exe` (Mono has nothing to do with the bug, you could adjust the project to compile for .NET Core and use that if you wanted)

**Expected Behavior**:

No compile errors should occur

**Actual Behavior**:

The following errors will appear one or more times
```
Failed to compile assembly with csc:
common/Executable.cs(3,7): error CS0246: The type or namespace name 'ONE' could not be found (are you missing a using directive or an assembly reference?)
common/Executable.cs(22,47): error CS0246: The type or namespace name 'IntegratedSubsystemDescriptor<>' could not be found (are you missing a using directive or an assembly reference?)
common/Executable.cs(32,37): error CS0246: The type or namespace name 'IntegratedSubsystem<>' could not be found (are you missing a using directive or an assembly reference?)

Failed to compile assembly with csc:
common/Executable.cs(3,7): error CS0246: The type or namespace name 'ONE' could not be found (are you missing a using directive or an assembly reference?)
common/Executable.cs(22,47): error CS0246: The type or namespace name 'IntegratedSubsystemDescriptor<>' could not be found (are you missing a using directive or an assembly reference?)
common/Executable.cs(32,37): error CS0246: The type or namespace name 'IntegratedSubsystem<>' could not be found (are you missing a using directive or an assembly reference?)
```

[RoslynDefineBug.zip](https://github.com/dotnet/roslyn/files/2856022/RoslynDefineBug.zip)

**Comment by jaredpar** [comment]
Thanks for filing this issue. 

Curious why do you believe this is an issue in the compiler server itself? The .NET ecosystem makes heavy use of both the server and conditional compilation today and we haven't seen this issue pop up. That's because every project which is multi-targeted has conditional compilation attached to it and implicitly uses the compiler server.  

A multi-targeted project would seemingly have all the qualities in the repro you've provided here. If there were a fundamental issue in how we process conditional compilation symbols it seems very likely we would have run into this already. 

Certainly there could be a latent bug here. But given how frequently we exercise this capability across all of our own repositories and customer code it seems somewhat unlikely. 

I believe Unity uses a custom hosting of the compiler server (please correct me if I'm wrong).  If so I'd like to take a look at that as I believe it's more likely to be an issue on that end.

**Comment by agocke** [comment]
@mrvoohe I just ran this sample 100 times and didn't see a failure. One thing I noticed: I had to fix up the code to call `dotnet` instead of the exe path and pass `csc.dll` as a parameter. How are you hosting the compiler in your build process?

**Comment by mrvoorhe** [comment]
Thanks for taking a look.

You are right that we use a fork of Roslyn, however, to my knowledge I don't believe we customize much.

I adjusted the repro to use `dotnet` and `csc.dll` from the latest .NET Core 2.1 sdk.  When I ran the repro project, there were no errors.  This likely explains what you saw.  Again, we don't customize our Roslyn fork much so I was a little surprised by this.  Our fork is older though, so I thought I would try using the .NET Core 2.0 sdk.  Sure enough, the errors came back.

here is the output of the repro on my machine using the Roslyn from the .NET Core 2.0 sdk and .NET Core 2.1 sdk.

https://gist.github.com/mrvoorhe/e3091c059d9c8fd2656f5e4078da2c0c

So it seems like somehow this issue is fixed in newer versions of Roslyn.

Thanks for taking a look.  We'll update our fork and that should resolve the issue.

**Comment by khyperia** [comment]
So turns out we (unity) are hitting this again, so I started to look into this a bit more. The repro _does not work_ with the latest .net core sdk, you need 2.0, on a mac. I believe that in Unity, we're hitting this with the above-mentioned updated sdk (`2.2.107`), but, I think getting to the root of this issue may help. I think what would be really nice is to figure out what changed from 2.0 to 3.1, if any bugs were filed on this, tests added, etc. - looking at any PRs to specifically something addressing this would be really nice! Alternatively, if the issue is that we're just invoking the compiler incorrectly (not flushing the server's metadata cache or something like that?), do let us know <3

I minimized the repro project quite a bit, it's far easier to analyze now.

[RoslynDefineBug.zip](https://github.com/dotnet/roslyn/files/3967332/RoslynDefineBug.zip)

But for the lazy:

test-src/Library.cs:
```cs
#if ONE
namespace ONE
#else
namespace TWO
#endif
{
    public class LibraryClass { }
}
```

test-src/Executable.cs
```cs
#if ONE
using ONE;
#else
using TWO;
#endif

namespace TestExe
{
    public class Program
    {
        public static void Main()
        {
            var tmp = new LibraryClass();
        }
    }
}
```

commandline, run this in a loop:
```bash
/Users/ashley.hauck/Downloads/dotnet-sdk-2.1.202-osx-x64/dotnet /Users/ashley.hauck/Downloads/dotnet-sdk-2.1.202-osx-x64/sdk/2.1.202/Roslyn/bincore/csc.dll /shared /platform:anycpu /nologo /debug- /optimize- /define:DEBUG /noconfig /nostdlib /r:/usr/local/share/dotnet/packs/Microsoft.NETCore.App.Ref/3.1.0/ref/netcoreapp3.1/System.Runtime.dll /target:library /out:/Users/ashley.hauck/tmp/build/library.dll /Users/ashley.hauck/tmp/test-src/Library.cs /define:ONE
/Users/ashley.hauck/Downloads/dotnet-sdk-2.1.202-osx-x64/dotnet /Users/ashley.hauck/Downloads/dotnet-sdk-2.1.202-osx-x64/sdk/2.1.202/Roslyn/bincore/csc.dll /shared /platform:anycpu /nologo /debug- /optimize- /define:DEBUG /noconfig /nostdlib /r:/usr/local/share/dotnet/packs/Microsoft.NETCore.App.Ref/3.1.0/ref/netcoreapp3.1/System.Runtime.dll /target:exe /out:/Users/ashley.hauck/tmp/build/test.exe /r:/Users/ashley.hauck/tmp/build/library.dll /Users/ashley.hauck/tmp/test-src/Executable.cs /define:ONE
/Users/ashley.hauck/Downloads/dotnet-sdk-2.1.202-osx-x64/dotnet /Users/ashley.hauck/Downloads/dotnet-sdk-2.1.202-osx-x64/sdk/2.1.202/Roslyn/bincore/csc.dll /shared /platform:anycpu /nologo /debug- /optimize- /define:DEBUG /noconfig /nostdlib /r:/usr/local/share/dotnet/packs/Microsoft.NETCore.App.Ref/3.1.0/ref/netcoreapp3.1/System.Runtime.dll /target:library /out:/Users/ashley.hauck/tmp/build/library.dll /Users/ashley.hauck/tmp/test-src/Library.cs
/Users/ashley.hauck/Downloads/dotnet-sdk-2.1.202-osx-x64/dotnet /Users/ashley.hauck/Downloads/dotnet-sdk-2.1.202-osx-x64/sdk/2.1.202/Roslyn/bincore/csc.dll /shared /platform:anycpu /nologo /debug- /optimize- /define:DEBUG /noconfig /nostdlib /r:/usr/local/share/dotnet/packs/Microsoft.NETCore.App.Ref/3.1.0/ref/netcoreapp3.1/System.Runtime.dll /target:exe /out:/Users/ashley.hauck/tmp/build/test.exe /r:/Users/ashley.hauck/tmp/build/library.dll /Users/ashley.hauck/tmp/test-src/Executable.cs
```

Obviously you'll need to modify the commandline a bit to reference wherever you downloaded the dotnet sdk, where System.Runtime.dll is (I couldn't find what to reference in 2.1.202, but referencing the 3.1 one still repros, I guess... or uh, I actually have no idea what the right dll to reference is), and where you placed the source files. (The project handles all that, except for the location of dotnet and System.Runtime.dll)

**Comment by khyperia** [comment]
Actually, I think I may have just figured it out, possibly:

Metadata is cached on a `(file, timestamp)` bool. https://github.com/dotnet/roslyn/blob/fab7134296816fc80019c60b0f5bef7400cf23ea/src/Compilers/Server/VBCSCompiler/MetadataCache.cs#L57

Timestamp boils down to `File.GetLastWriteTimeUtc`: https://github.com/dotnet/roslyn/blob/8b154a48f7e867747599a04f5e2481f4956011c8/src/Compilers/Core/Portable/FileSystem/FileUtilities.cs#L367

aaand... `stat` on a macbook may only have 1-second precision. So if the second compile hits in the same unix second, it might re-use the same metadata cache entry.

Unfortunately though, my mac debugging skills aren't great, not sure if this is actually the case. It fits the intermittent failure mode, though!
