### ISSUE TITLE
Check expression for null

### ISSUE THREAD

**Issue by kendrahavens** [dotnet/roslyn#33335]
Customer request copying here.

**Version Used**: Visual Studio 2017

**Steps to Reproduce**:

> 1. Have a potential nullreferenceexception 
![image](https://user-images.githubusercontent.com/8293542/52672308-5a081600-2ed2-11e9-9ef9-6d792c343f15.png)

> 2. The variable attrib can be null and attrib.Value throws NullReferenceException. Resharper prompts an option to add null check or use ?. to avoid this exception.
![image](https://user-images.githubusercontent.com/8293542/52672333-68eec880-2ed2-11e9-81c6-cc41e13da191.png)

**Expected Behavior**:
Receive warning on potential null reference exception.

**Actual Behavior**:
No warning is given.

**Comment by gafter** [comment]
I believe this is a compiler issue.  We intend to support nullable value types in the nullable prototype.

**Comment by jaredpar** [comment]
Strictly speaking the current behavior is "By Design". The `XElement` code here is oblivious hence we don't issue a warning when we are dereferencing the value. Longer term though we want this scenario to warn by having a side car representation for nullable state of existing libraries. This is one of the cases that we will be hitting.

Side car tracking is in #31632
