### ISSUE TITLE
Can roslyn compile ios and android apps?

### ISSUE THREAD

**Issue by ygc369** [dotnet/roslyn#3334]
I hope roslyn itself has the ability to compile ios and android apps written by C# without Xamarin which is too expensive. If we can develop ios and android apps using C# and free version of Visual Studio under Windows OS, it would be very good. If Microsoft can't buy Xamarin and make it free, it should consider developing a similar software which is free to use.

**Comment by GeirGrusom** [comment]
It can compile binaries that can be used by Xamarin, but that is not enough. For Android Xamarin also builds Java libraries for .NET, and for iOS it compiles the Mono binary into native code for the iOS platform (as generating code in runtime is forbidden on iOS by the developer license).

So no, you can't build iOS or Android applications with Roslyn, because a C# compiler is not all you need.

**Comment by ygc369** [comment]
@GeirGrusom 
Can Roslyn include all libraries needed by Android and IOS?

**Comment by ygc369** [comment]
Sine Xamarin has been free, close this issue.
