### ISSUE TITLE
C# XML comments displayed incorrectly when they contain a < symbol

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#33381]
In the IDE when a C# file is loaded that contains an XMLComment and the comment contains a &lt; within the comment text the line is incorrectly formated  Text before the &lt; is Green by default the XMLDocument color. Everything the the &lt; to the &gt; is display as grey, then the text is again Green. I belive this is related to Roslyn Classifier or SyntaxWalker. I have attached a file from CorFX that displays the issue the best.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/442614/c-xml-comments-displayed-incorrectly-when-they-con.html
VSTS ticketId: 783216_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by sharwell** [comment]
Literal `<` characters are required to be escaped as `&lt;` in XML content. For example, instead of writing the following:

#### Invalid example

```csharp
/// <summary>
/// The value <= 2.
/// </summary>
```

#### Valid example

```csharp
/// <summary>
/// The value &lt;= 2.
/// </summary>
```

We have an ongoing feature request to improve the experience in this space by not requiring all documentation to be written as XML content, but it's still in the earliest design stages. See https://github.com/dotnet/csharplang/issues/891.
