### ISSUE TITLE
Incorrect implicit casting with ternary operator

### ISSUE THREAD

**Issue by silarmani** [dotnet/roslyn#33472]
**Rosylin 7.3**: 

When using the ternary operator ?: in order to assign either an int? or decimal? into an object variable, the int? value gets implicitly casted into decimal?

```
var defaultValueDecimal = (decimal?)10.0;
var defaultValueInt = (int?)defaultValueDecimal;
object defaultValue = defaultValueDecimal == defaultValueInt ? defaultValueInt : defaultValueDecimal;
Console.WriteLine(defaultValue?.GetType().Name)
```
**Expected Behavior**:
It should print Int32

**Actual Behavior**:
It prints Decimal

If I explicitly cast both results to object then it works
```
var defaultValueDecimal = (decimal?)10.0;
var defaultValueInt = (int?)defaultValueDecimal;
object defaultValue = defaultValueDecimal == defaultValueInt ? (object)defaultValueInt : (object)defaultValueDecimal;
Console.WriteLine(defaultValue?.GetType().Name)
```

**Expected Behavior**:
It should print Int32 and it does! however the compiler emits an warning saying "Cast is redundant"

I believe that the warning is correct and the implicit casting is incorrect.

**Comment by gafter** [comment]
The compiler is correct.  There is an implicit conversion from `int` to `decimal`, but not vice versa.  See https://github.com/dotnet/csharplang/blob/master/spec/conversions.md#implicit-numeric-conversions .  For the conditional expression, the target type makes no difference.  Either the second operand has to be convertible to the type of the third, or vice versa.  See also https://github.com/dotnet/csharplang/blob/master/spec/expressions.md#conditional-operator

Also, the IDE is correct to report that the cast is unnecessary.  You only have to cast one of the operand to `object`.  Since you have two casts, either of them can be removed.
