### ISSUE TITLE
FAR missing occurrences in Shared Project Files

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#3351]
1. Sync to https://github.com/amcasey/roslyn/commit/abbca4925361489c1418a25102372f330e537081
1. Open roslyn.sln
1. Open ExpressionEvaluator\Core\Source\ResultProvider\Formatter.TypeNames.cs in the ResultProviderTestUtilities head
1. On line 305 (```sawInvalidIdentifier = !IsIdentifier(identifier);```), Find All References of ```IsIdentifier```.

Expected: 3 defs, each with 4 refs
Actual: 3 defs, two with 4 refs each, one with 0 refs

**Comment by amcasey** [comment]
FYI @dpoeschl

**Comment by dpoeschl** [comment]
This repros without a special commit on members like ```GetTypeName``` from the same type.

**Comment by dpoeschl** [comment]
The scope of this problem is limited to documents linked into projects with the same assembly name. In the given example, ```ResultProvider.Portable``` and ```ResultProvider.NetFX20``` both have assembly name ```Microsoft.CodeAnalysis.ExpressionEvaluator.ResultProvider```. Changing either to ```...ResultProvider2``` allows the Find Symbol Results to show the correct information.

The actual results from AbstractFindReferencesService.FindReferencedSymbolsAsync are incorrect:

![image](https://cloud.githubusercontent.com/assets/235241/8026510/eba48abe-0d2d-11e5-87dd-71a6fc753d80.png)

The first three lines show the projects containing the three definitions, and things look good there. The next three lines show the projects containing the first reference to each of these symbols, and you can see the ```NetFX20``` definition has a reference in ```Portable```. This probably points to a problem under SymbolFinder.FindReferencesAsync somewhere in this situation.

**Comment by Pilchie** [comment]
IIRC, there are numerous cases where we unify projects based on assembly name.

**Comment by balajikris** [comment]
Note: Please also verify and test #3352 when resolving this bug.

**Comment by balajikris** [comment]
Note: Added one more customer scenario to the related bug mentioned above (Asp.Net vNext Applications).

**Comment by Pilchie** [comment]
Tagging @jasonmalinowski. We should consider doing something here to support the Asp.NET 5.0 cases)

**Comment by jasonmalinowski** [comment]
@Pilchie: hah, somebody testing my csproj -> xproj prototype immediately hit this bug. Already debugged it a bit yesterday, will fix today.

**Comment by dpoeschl** [comment]
Verify internal bug 162818 when verifying this fix.

**Comment by jasonmalinowski** [comment]
I've verified internal bug 162818.

**Comment by jasonmalinowski** [comment]
Fixed by #8096.
