### ISSUE TITLE
Change method signature should allow adding additional parameters to the method

### ISSUE THREAD

**Issue by vatsalyaagrawal** [dotnet/roslyn#33534]
While 15.8 provides a way to add a method parameter by modifying the invocation of a method, this breaks any other invocations of the method (which will continue to pass the old argument list). It would be good to have a dialog (or some other way) that lets you modify a method signature. You could provide default arguments for new parameters, including using a variable in scope at the invocation if it was the only one of the type. VS has a similar dialog, but it only allows reordering and removing parameters.

**Comment by vatsalyaagrawal** [comment]
related to #25144

**Comment by kendrahavens** [comment]
Additional design note: The 'Change Method Signature' dialog is not available if the method has no parameters. It's generally expected to be offered regardless or else users assume we don't have this dialog at all. 

Making the 'Change Method Signature' option appear on any (Ctrl +.) menu when the cursor/selection is a method signature would make more sense once the user can actually add a parameter.

**Comment by jcgknudson** [comment]
Can we prioritize this? We moved off of resharper since similar productivity tools were promised natively back in VS2017. Moreover, the existing functionality does not work in the general case. And this previous feature suggestion was incorrectly marked as included in VS2017:

https://developercommunity.visualstudio.com/content/idea/351698/refactoring-to-add-a-parameter-to-existing-method.html

The steps provided here:
https://docs.microsoft.com/en-us/visualstudio/ide/reference/add-parameter?view=vs-2019
are not applicable generally.

I have

- An interface defining a code contract with a particular method
- Several classes implementing this method

The add parameter mentioned in the above public doc does not appear in my case (in VS 2019).

**Comment by CyrusNajmabadi** [comment]
@jcgknudson PRs welcome :)

**Comment by alrz** [comment]
Is it too much work to *detect* signature change inplace and suggest to apply and update usages? something similar to rename.

**Comment by allisonchou** [comment]
Closing this issue as add parameter is now part of the Change Signature dialog.
