### ISSUE TITLE
CS1061 'Task' does not contain a definition for 'Result' and no accessible extension method 'Result' accepting a first argument of type 'Task' could be found

### ISSUE THREAD

**Issue by lmcarreiro** [dotnet/roslyn#33596]
**Version Used**:

C# 7.3
C# Compiler version 2.10.0.0 (b9fb1610)

**Steps to Reproduce**:

```cs
using System;
using System.Linq;
using System.Threading.Tasks;

namespace N
{
    class C { public string Id { get; set; } }

    class P
    {
        private static Task<C[]> GetArrayOfC() => throw new NotImplementedException();

        private static void M()
        {
            GetArrayOfC().ContinueWith(task => {
                var a = task.Result.FirstOrDefault(x => x.Id = "");
            });
        }

    }
}
```

**Expected Behavior**:
See just the error
> CS0029	Cannot implicitly convert type 'string' to 'bool'

**Actual Behavior**:
> CS1061	'Task' does not contain a definition for 'Result' and no accessible extension method 'Result' accepting a first argument of type 'Task' could be found (are you missing a using directive or an assembly reference?)

![image](https://user-images.githubusercontent.com/13019179/53240451-7f88e280-367d-11e9-973f-6321bc926254.png)

If I fix the lambda (`==` instead of `=`) everything works fine, and it recognizes that my `task` parameter is of type `Task<C[]>` and not just `Task`):

![image](https://user-images.githubusercontent.com/13019179/53240478-8fa0c200-367d-11e9-9142-1a53e2b7a801.png)

**Comment by YairHalberstadt** [comment]
The explanation for this issue is as follows:

Task<T> inherits from Task
Task<T> defines a method ContinueWith(Action<Task<T>>)
Task defines a method ContinueWith(Action<Task>)

You have called a method Task<T>.ContinueWith(x => expression)

The compiler has to resolve which overload you meant. Note that even without errors this is a hard problem -it can in a pathological case be NP Complete.

In order to do so, essentially the compiler first tries all the options, then discards those that would result in errors.

In your case, all options result in errors. As such the compiler has no idea which overload to pick. It essentially pick randomly, and assumes you picked the overload Task.ContinueWith(Action<Task>). Since Task does not have a result property, it reports an error.

I think a solution to this problem could be that when deciding which overload to pick in such a case, pick the one with the fewest errors.

**Comment by YairHalberstadt** [comment]
The relevant Method is UnboundLambda.GenerateSummaryErrors

It has an interesting comment:

> It is highly likely that "the same" error will be given for two different
> bindings of the same lambda but with different values for the parameters
> of the error. For example, if we have x=>x.Blah() where x could be int
> or string, then the two errors will be "int does not have member Blah" and 
> "string does not have member Blah", but the locations and errors numbers
> will be the same.
> 
> We should first see if there is a set of errors that are "the same" by
> this definition that occur in every lambda binding; if there are then
> those are the errors we should report.
> 
> If there are no errors that are common to *every* binding then we
> can report the complete set of errors produced by every binding. However,
> we still wish to avoid duplicates, so we will use the same logic for
> building the union as the intersection; two errors with the same code
> and location are to be treated as the same error and only reported once,
> regardless of how that error is parameterized.
> 
> The question then rears its head: when given two of "the same" error
> to report that are nevertheless different in their arguments, which one
> do we choose? To the user it hardly matters; either one points to the
> right location in source code. But it surely matters to our testing team;
> we do not want to be in a position where some small change to our internal
> representation of lambdas causes tests to break because errors are reported
> differently.
> 
> What we need to do is find a *repeatable* arbitrary way to choose between
> two errors; we can for example simply take the one that is lower in alphabetical
> order when converted to a string.

Now i'm not sure of the logic of reporting the union of all errors. I would suggest that we want to report the minimum possible number of errors. A valid option would be all the errors for the option that had the least errors, and if there are multiple, arbitrarily picking one of those.

**Comment by YairHalberstadt** [comment]
Note that here we're actually reporting an inconsistent set of errors, since if Result cannot be found, we wouldn't know the signature of FirstOrDefault, so we wouldn't know that it didn't accept a lambda returning a string.

I think that showing the union is therefore probably useful. Without knowing the authors intentions it is impossible to know which one of the lambdas was the one he intended, and if we only show the errors for the wrong lambda it would be really confusing for him to work out where he went wrong.

For example what if we arbitrarily decided to only show the errors assuming that the lambda took a parameter of Task?

Then the only error would be about Result not existing, which would be really confusing to you who knows that Result does exist on Task<T>.

Or what if it was the other way round, and you misspelt Result, and actually meant something which existed on Task, and which had a FirstOrDefault method which accepted a Func<T, string>? Then if the only message shown was about not being able to convert string to bool, that would be extremely confusing.

**Comment by lmcarreiro** [comment]
Understood. It's good to know some internal details about the compiler.

Thank you @YairHalberstadt.

**Comment by YairHalberstadt** [comment]
No Problem 🙂

**Comment by CyrusNajmabadi** [comment]
I'm fairly certain this is a dupe of some existing bug.  It's a known issue that we would lke to make better, but don't have any easy solutions for.  Tagging @jcouv @gafter in case they know the existing bug to dupe against.

**Comment by DamengRandom** [comment]
using Task<T> instead of using normal types, like string, bool when you define your http API call helper function

**Comment by DamengRandom** [comment]
coz HttpClient is tailored for `asynchronous` API request calls, so it must be using `async` `await` keywords in your http helper function
