### ISSUE TITLE
Autocompletion missing arguments

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#33630]
**Version Used**: VisualStudio.16.Preview/16.0.0-pre.3.0+28608.199

**Steps to Reproduce**:
```C#
static void Main(int x, int y)
{
    int m = | x * y;
    int s =  x + y;
}
```
Imagine you want to prepend the formula, e.g. make it `int m = y + x * y`. However, when you type `y` in front of `x * y`, i.e. `y| x * y`, it is not offered in autocomplete and random entry with `y` will be committed when pressing space.

All other cases work:
1. Type `x` in front of `x + y` , i.e. `x| x + y`. `x` is in autocomplete.
2. Type `y` instead, i.e. `y| x + y`. `y` is in autocomplete.
3. Type `x` in front of `x * y`, i.e. `x| x * y`. `x` is in autocomplete.

**Comment by CyrusNajmabadi** [comment]
it's possible that hte invalid code is causing the compiler to parse `x* y` as a the declaration of a variable called 'y' of type `x*` (i.e. `pointer to x type`).  This makes it seem as if `y` is declared after teh caret point, so `y` is filtered out of the completion list.

**Comment by miloush** [comment]
My real scenario was actually `int value = b| a.Value * b.Value;` Does it mean it treats `a.Value` as a nested type declaring pointer to `b` and throwing away `.Value` as error?

**Comment by CyrusNajmabadi** [comment]
> Does it mean it treats `a.Value` as a nested type declaring pointer to `b` and throwing away `.Value` as error?

Quite possibly.

**Comment by CyrusNajmabadi** [comment]
This is almost certainly what's going on.  Observe the compiler error here:

![image](https://user-images.githubusercontent.com/4564579/53292566-8137d080-3779-11e9-8ba2-09bad38a78b9.png)

It believes there is a definition of 'y' after the point it is being written.  Effectively, the parser has 'gone off the rails' and has produced a tree that has confused the compiler.  Due to this, the IDE is just respecting what the compiler is telling it.

The best fix here would be to improve the parser to have a better sense of what is going on here.  Note: this may be non-trivial.

**Comment by miloush** [comment]
Presumably the tree before the error is fine and the `y` has already been declared as a method parameter, could that make it not be filtered out of the completion list?

Looks like if the same problem occurs in code when a local variable is declared twice, the autocompletion still offers the variable name before the last declaration.

**Comment by CyrusNajmabadi** [comment]
> Presumably the tree before the error is fine

Not at all. The parser routinely looks ahead to make decisions.  Invalid code can easily break code far before that point.

>  and the `y` has already been declared as a method parameter, could that make it not be filtered out of the completion list?

No.  Because if 'y' is also declared *legitimately* later in the method, it should not show up in the list, as 'y' both hides the parameter *and* is invalid to reference from prior to itself in the list.

**Comment by miloush** [comment]
Thanks for the insights. Doesn't seem to be worth the effort to fix unless there is more compelling issues than this one.

**Comment by CyrusNajmabadi** [comment]
@miloush It would def be lower on my list.  It's def pretty specialized as it requires a fairly particular patter on the right of what you're typing.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
