### ISSUE TITLE
SyntaxFactory.SwitchStatement without parentheses in VS 2019 Preview 3

### ISSUE THREAD

**Issue by Droni** [dotnet/roslyn#33685]
**Version Used**: 
Visual Studio 2019 Preview 3
**Steps to Reproduce**:

1. Use SyntaxFactory.SwitchStatement(ExpressionSyntax) (C#)

**Expected Behavior**:
The switch statement should surround the expression with parentheses

**Actual Behavior**:
The expression inserts without parentheses

Inside the Visual Studio 2017 (15.9.7) the expression correctly inserts with parentheses but in VS 2019 Preview 3 not. If we manually add parentheses, then in VS 2017, double parentheses will be inserted.

**Comment by CyrusNajmabadi** [comment]
this is a known change due to the fact that the language allows `switch some_tuple_expr`.  i.e. `switch (a, b, c)`.  That kind of node is created by passing in a tuple expr to SwitchStatement and having it not add parens around.

> Inside the Visual Studio 2017 (15.9.7) the expression correctly inserts with parentheses but in VS 2019 Preview 3 not. If we manually add parentheses, then in VS 2017, double parentheses will be inserte

The only way around this is to always call the version of SwitchStatement that takes the open and close parens.

**Comment by CyrusNajmabadi** [comment]
Tagging @gafter for visibility.  An outcome of a known change in behavior.  Should we have some mechanism for documenting this and giving clear instructions on how users can write code that will work properly for both prior vesions of the API and future versions?

**Comment by Droni** [comment]
@CyrusNajmabadi thank you for the clarification. We will correct this on our side.

**Comment by CyrusNajmabadi** [comment]
@Droni Glad to help!

**Comment by gafter** [comment]
@CyrusNajmabadi Thank you. We will look at where best to document this.

**Comment by CyrusNajmabadi** [comment]
@gafter Awesome!  Let me know if/when you do.  if will affect the work (which i hopefully can get back to soon) to support `if !(...)`.

**Comment by GrahamTheCoder** [comment]
What I'm about to say is only worth saying because you've done an absolutely excellent job with the design and implementation of Roslyn, and to me, this shows up as a weak spot in API consistency and design. Please consider reversing this change before it gets out of preview.

### This specific case
As far as I understand, the documentation required will say "only call this convenience overload if `expression` is of type `TupleExpressionSyntax`. But there's a better way of indicating that than documentation, change the type:
```csharp
    public static SwitchStatementSyntax SwitchStatement(TupleExpressionSyntax expression, SyntaxList<SwitchSectionSyntax> sections)
```
This would pass `Token`s of `SyntaxKind.None` for the parentheses as it does in the latest beta.

But of course, you wouldn't want to change your public API so you can keep the old method with the old logic (passing parentheses) and add this alternative as a new overload.

<sub>Personally I'm not convinced an overload is even needed for such a special case, and especially not at the expense of covering the general case, I'm just providing a way to achieve the best of both worlds.</sub>

### If you aren't convinced yet, the general case

As a consumer I need to have an expectation of what will come out of the `SyntaxFactory` when I call it. 
My expectation used to be very simple: "If there is an overload omitting parameters, some defaults that creates a valid syntax tree in the general case will be added"

I'd say this change violates that expectation, and makes it very hard to know what to expect when omitting parameters. What you seem to say is that in the general case (for an expression of unknown type), I should be explicitly passing all the tokens, and that what appears to be a convenience overload is only actually a convenience overload for some very special cases.

Since more syntax structures will have tuples in the future, and this will change over time, this means that to be future proof I should never use the convenience overload if I have hold of a general expression since it will (in general) risk producing invalid code.

**Comment by CyrusNajmabadi** [comment]
> As far as I understand, the documentation required will say "only call this convenience overload if expression is of type TupleExpressionSyntax. But there's a better way of indicating that than documentation, change the type:

We can't change teh type.  It would be a binary breaking change.

**Comment by CyrusNajmabadi** [comment]
> Since more syntax structures will have tuples in the future, and this will change over time, this means that to be future proof I should never use the convenience overload if I have hold of a general expression since it will (in general) risk producing invalid code.

This is a decent policy.

**Comment by GrahamTheCoder** [comment]
Thanks, I appreciate the swift reply

> We can't change teh type. It would be a binary breaking change.

I understand - to reiterate my suggestion: 
* Leave the old method as it was in the last stable release.
* New method with the `TupleExpression` type signature (if you feel it's necessary)

Someone in the special tuple case can just pass `SyntaxKind.None` to the full method call when they specifically don't want parentheses. Presumably you'd recommend that as decent policy anyway?

Current behaviour in preview breaks *all* current callers, just to introduce some special tuple behaviour with the wrong type signature that you don't want people to use anyway.

**Comment by CyrusNajmabadi** [comment]
> Current behaviour in preview breaks all current callers, just to introduce some special tuple behaviour with the wrong type signature that you don't want people to use anyway.

I'm not sure i agree with this statement.  

This method follows the same behavior as all roslyn factory methods have with unspecified args, and optional syntax concepts.  I would feel very strange having this method not behave consistency with the rest.

--

Note: consistency in the syntax-model (i.e. all the syntax methods are just generated, and behave in a common way versus the actual syntax definitions), is very important to roslyn.  It means people don't have to guess at the behavior.

For example, say someone called this method and it added parens (even though they didn't specify it). There would now be confusion around "why is this synthesizing syntax for optional tokens, when no other methods do that?"

--

NOte: i'm very sympathetic to the issue here.  It's a challenging problem.  When something was previously required, and now becomes optional, it can have wide reaching impact.  However, the impact extends beyond just things like the factory methods.  For example, if you do `switchExpression.OpenParenToken` you could get `SyntaxKind.None` (something never possible before).  

I think just trying to patch/plug the holes will likely just make things messy and will never fully succeed.  As such, i think it's better we just make things optional, and downstream clients should rewrite teh code as if that's the case.

**Comment by GrahamTheCoder** [comment]
Sounds like I need to understand more about how these are generated since my current understanding  is just wrong. Is this the right place to start? https://github.com/dotnet/roslyn/blob/master/eng/generate-compiler-code.ps1

I agree trying to hack individual cases would be the wrong thing to do. 

It seems from the caller's point of view the current consistency kinda relies on knowing what the current draft language spec is. That's not the *most* useful kind of consistency in my opinion, but I agree finding a better one that can be easily implemented/maintained and doesn't break binary compatibility doesn't sound hugely likely and goes way beyond the scope of this issue. So it sounds like a problem to solve in my own project. I could try to generate my own SyntaxFactory, but I think if I just pay attention to changes in syntax.xml I'll at least have a heads up when changes are about to hit.

Thanks for the explanation!

**Comment by CyrusNajmabadi** [comment]
> but I think if I just pay attention to changes in syntax.xml I'll at least have a heads up when changes are about to hit.

Yup.  And i think there is a large onus on hte Roslyn team to make these changes clear.  @jcouv Is this something you might be able to help out with in terms of future changes in behavior?  Thanks!

 > Thanks for the explanation!

Definitely.  Sorry for the pain!

**Comment by jcouv** [comment]
@gafter I'm assuming we're keeping this for 16.3 since regression. Let's prioritize this issue. It should be possible to get it in post-snap although I'm not sure which branch will be targeted. Thanks
