### ISSUE TITLE
In parameters could be in type parameters?

### ISSUE THREAD

**Issue by dzmitry-lahoda** [dotnet/roslyn#33718]
**Version Used**: 

[master (28 October 2018)](https://sharplab.io/)

**Steps to Reproduce**:

```
interface DoesNotCompile<in T>
{
    void Do(in T value);
}
```
`error CS1961: Invalid variance: The type parameter 'T' must be invariantly valid on 'DoesNotCompiles<T>.Do(in T)'. 'T' is contravariant.`

**Expected Behavior**:
- if it is not sound or valid to pass by `in` mean than may be improve error message to avoid such question (or close issue, it will be still searchable)
- if it sound, just was not implemented, than allow to contravariance for `in` parameters

**Actual Behavior**:
- error with not clear text

**Notes**
Failed to do reasonable discussion on [SO](https://stackoverflow.com/questions/54907452/contrvariant-in-type-parameter-to-be-in-parameter)

#17140 I have found is about `ref`, not `in`

**Comment by ericlippert** [comment]
The error message is correct, but you are right to note that it is particularly confusing in this case. It is not clear from the error message why an "in" parameter is the same as a "ref" parameter as far as its variance validity is concerned.

I wrote that error message over ten years ago; I struggled for a long time to find a way to phrase the  error so that it would be both accurate and understandable. I believe I failed; the error message is accurate, but not very understandable:

* It uses the jargon of the C# specification's rules; this means that you can look up the rules in the specification easily, but if you don't have a copy of the spec handy, that's not much help.
* The error message is diagnostic, but not prescriptive: it doesn't tell you where you went wrong or how to fix it.

That last point is the difficult part. It is easy to criticize the message. It is much, much harder to come up with a compiler that reads the user's mind, figures out their mental state, and crafts an error message that educates the user about why a program that they think should work does not work.  If you have suggestions for an algorithm that does so, I would love to hear about it.

**Comment by dzmitry-lahoda** [comment]
[ref out SO was updated by in](https://stackoverflow.com/posts/2877515/revisions).

Considerations:
- Decompile C# code with `in` type parameter, modify IL to have `in` parameter, compile, CLR runs that code, not sure about C#, if yes - than I can do what I want without language support, fody plugin?
- `<in ..>` and `(in ..)` kind of `in`, if CLR runs that `IL`, and if C# eats custom modified `in` than considering `in` to be valid for contrvariance, but not `CLSCompliant`, so solution should mark that with  `CLSCompliant false`, 
- F# seems have not variance and will work fine
- error now is searchable on github and SO, so less reason to change message, error could reference spec directly, so error to have number + spec reference.
- Second time I get that CLR possible, but C# precludes to compile https://github.com/dotnet/csharplang/issues/1631#issuecomment-456176924 , in both cases seems I can provide workaround which will be eaten by C# as it should
