### ISSUE TITLE
.editorconfig settings being ignored in AspNetCore repo.

### ISSUE THREAD

**Issue by adrianwright109** [dotnet/roslyn#33715]
**Development environment**:
Visual Studio 2019 Preview 3.0
Resharper 2018.3.3

**Steps to Reproduce**:
Clone the AspNetCore repo `https://github.com/aspnet/AspNetCore.git`
Open the `.\src\Components\Components.sln` in Visual Studio 2019 Preview 3
Right-click on the solution node in the `Solution Explorer` and `Add > Existing Item...`
Add the following file `..\..\.editorconfig` - this is the root `.editorconfig` in the main AspNetCore repo.
Open the `ElementRef.cs` class from the `Components.csproj` project
Format the opened class using `Format Document Ctrl+K, Ctrl+D`

**Expected Behavior**:
`usings` are sorted with system directives first and therefore change from:
```
using Microsoft.JSInterop.Internal;
using System;
using System.Collections.Generic;
using System.Threading;
```

to:
```
using System;
using System.Collections.Generic;
using System.Threading;
using Microsoft.JSInterop.Internal;
```
**Actual Behavior**:
Nothing changes

The `.editorconfig` rule `dotnet_sort_system_directives_first = true:warning` is not being enforced for some reason.

As I have ReSharper installed I have used the `Resharper > Windows > File Formatting Info` menu to show me details of what rules are being applied from the `.editorconfig` file; it shows that:
`[*]`
`indent_style = space`
~~`charset = utf-8`~~
~~`trim_trailing_whitespace = true`~~
`insert_final_newline = true`

`[*.cs]`
`indent_size = 4`
~~`dotnet_sort_system_directives_first = true:warning`~~

strike-through rules are not being applied.

Is this a bug or am I not understanding how the `.editorconfig` file should work?

FYI:
![image](https://user-images.githubusercontent.com/47532258/53488948-aaad7080-3a87-11e9-8aae-1f000e3cbc4a.png)

**Comment by rynowak** [comment]
I think the issue here is the `:warning` - which I can't find in examples of `dotnet_sort_system_directives_first`.

It would be really nice if something in the experience told us that we made a mistake because it's an easy one to make. 

If you read and digest the official docs, it's [explained](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference?view=vs-2017) that there are *code style rules* and *formatting rules* - and some of each are prefixed with *dotnet* and some of each are prefixed with *<language_name>*.

So you really **have to** understand if the specific rule is a formatting rule or code style rule to apply it - the docs is the only place I can find that info.

**Comment by jinujoseph** [comment]
@rynowak  is correct about the cause here.
We are also tracking a priority feature to validate the .editorconfig file for users #19055

**Comment by rynowak** [comment]
Great!

**Comment by jmarolf** [comment]
@rynowak 	in the meantime there is this extension by Mads that at least provides support in VS for identifying errors: https://marketplace.visualstudio.com/items?itemName=MadsKristensen.EditorConfig
