### ISSUE TITLE
Nullable analysis of lifted binary operator likely wrong for `&` or `|`

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#33771]
@333fred pointed out this issue in reviewing PR https://github.com/dotnet/roslyn/pull/33648. This is a follow-up issue. 

Relevant portion of the spec: https://github.com/dotnet/csharplang/blob/master/spec/expressions.md#boolean-logical-operators

```C#
        private TypeWithState InferResultNullability(BinaryOperatorKind operatorKind, MethodSymbol methodOpt, TypeSymbol resultType, TypeWithState leftType, TypeWithState rightType)
        {
...
            if (operatorKind.IsLifted())
            {
                resultState = leftType.State.JoinForFlowAnalysisBranches(rightType.State);
            }

            return new TypeWithState(resultType, resultState);
        }

```

**Comment by gafter** [comment]
We can only do better when the operands are constants.  But there are no constants of type `bool?`.  Which means that in order to do better we'd have to peek below the conversions to see if there is an underlying constant value.

It is hard to imagine a circumstance in which this would help some user.  It is also hard to imagine that we'd specify any better than what is implemented.  So I'm going to declare success and leave it as is.
