### ISSUE TITLE
Need to document breaking change described in #2909

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#3379]

**Comment by gafter** [comment]
@AlekseyTs Please review this doc:

Clashing Enum Members
=====================

As reported in #2909, it is possible to reference an enumeration type from VB that contains more than one enumeration member with the same name. For example, a library author might release version 1 of his API in C# with this type

```cs
enum Something
{
	Something,
    Datetime,
	SomethingElse,
}
```

and then realize later that the name Datetime is misspelled (it should be camel-case, with `Time` capitalized). So in version 2 the type is changed

```cs
enum SomeEnum
{
	Something,
    DateTime,
    [Obsolete] Datetime = DateTime,
	SomethingElse,
}
```

A C# client that used the old name of the enumeration member would receive an obsolete warning from the compiler encouraging the use of the new name instead of the old one, but would otherwise be able to compile and run the code unchanged.

A VB client that used `SomeEnum.Datetime` would have received no warning from previous versions of the VB compiler.

```vb
    Dim v = SomeEnum.Datetime
```

The Dev12 VB compiler would select the *lexically first* enumeration constant of a given (case-insensitive) name when looking up an enumeration constant within an enumeration type. Since that member does not have the Obsolete attribute in this example, the VB code would continue to compile and run without a problem.

**The Roslyn version of the VB compiler reports an ambiguity error for this case.** Since there is more than one member of the given (case-insensitive) name `Datetime` in the type `SomeEnum`, the symbol being referred to is ambiguous.

If you run into this problem, you can work around it by explicitly using the numeric value corresponding to the enum constant:

```vb
    Dim v = CType(1, SomeEnum)
```

This particular issue may affect you if you use the MySql APIs for .net.

**Comment by gafter** [comment]
Fixed in fdeaea451c46cf99c482626be23115281a29f7db on the stabilization branch

**Comment by gafter** [comment]
@AlekseyTs Please verify.

**Comment by gafter** [comment]
@AlekseyTs I've clarified the documentation. Please verify.

**Comment by AlekseyTs** [comment]
Verified.
