### ISSUE TITLE
Renamer.RenameSymbolAsync should not rename the use of a delegate with a different number of type parameters.

### ISSUE THREAD

**Issue by gabirx** [dotnet/roslyn#33845]
**Version Used**: 
2.10.0
**Steps to Reproduce**:

```csharp
       string originalCode = @"
         delegate void Action<T1, T2>(T1 t1, T2 t2);
    class Class1<T> 
    { 
        public static readonly Action<Exception> Throw = delegate(Exception ex) { throw ex; };
        private Action<T> _onNext;
        Class1(Action<T> onNext, Action<Exception> onError)
        {
            this._onNext = onNext;
        }
    }
        ";
            var expectedCode = @"
         delegate void Action2<T1, T2>(T1 t1, T2 t2);
    class Class1<T> 
    { 
        public static readonly Action<Exception> Throw = delegate(Exception ex) { throw ex; };
        private Action<T> _onNext;
        Class1(Action<T> onNext, Action<Exception> onError)
        {
            this._onNext = onNext;
        }
    }
        ";
            var workspace = new AdhocWorkspace();
            string projName = "NewProject";
            var projectId = ProjectId.CreateNewId();
            var versionStamp = VersionStamp.Create();
            var projectInfo = ProjectInfo.Create(projectId, versionStamp, projName, projName, LanguageNames.CSharp);
            var newProject = workspace.AddProject(projectInfo);
            var sourceText = SourceText.From(originalCode);

            var newDocument = workspace.AddDocument(newProject.Id, "NewFile.cs", sourceText);
            
            Document doc = newDocument;

            DelegateDeclarationSyntax decl = doc.GetSyntaxRootAsync().Result.
                DescendantNodes().
                OfType<DelegateDeclarationSyntax>().First(x => x.Identifier.Text == "Action");
            var semanticModel = doc.GetSemanticModelAsync().Result;
            var typeSymbol = semanticModel.GetDeclaredSymbol(decl);

            string oldName = typeSymbol.Name;
            string newName = oldName + "2";


            var newSolution = Renamer.RenameSymbolAsync(doc.Project.Solution, typeSymbol, newName, null).Result;
            var modifiedDoc = newSolution.Projects.First().Documents.First();

            ;
            Assert.Equal(expectedCode, modifiedDoc.GetTextAsync().Result.ToString());
        }
```

**Expected Behavior**:
To rename only the definition of the delegate `delegate void Action<T1, T2>(T1 t1, T2 t2);` . The use of the `action<T>` delegate remains unchanged.
**Actual Behavior**:
The delegate definition is renamed to `Action2<T1, T2>`. And the references to the `action<T>` delegate to `Action2<T>` are renamed

**Comment by CyrusNajmabadi** [comment]
Your code contains errors.  Namely, this code is not legal:

```c#
delegate void Action<T1, T2>(T1 t1, T2 t2);
class Class1
{
  public static readonly Action Throw = delegate(Exception ex) { throw ex; };
  private Action _onNext;
  Class1(Action onNext, Action onError)
  {
  this._onNext = onNext;
  }
}
```

That's because 'Action' doesn't bind successfully.  Roslyn is error tolerant and thus guesses as to what you most likely meant.  In this case, it thinks that your usages of `Action` are usages of `Action<T1, T2>` just with missing type params.  As such, they get renamed as well.

The presence of `Rename` in code that has errors is that it renames on a `best effort` basis.  As such, this is currently operating within the scope of how it is intended to behave.  THe behavior here is also reasonable to me.

If you do not want this behavior:

1. add a `using Sytem;` in your file.
2. prevent renames when there are errors in teh code.

**Comment by gabirx** [comment]
In original case when i found this issue used this case:
`  var properties = new Dictionary<string, string>
            {
                { "Configuration", "NET20"}
            };
            Workspace = MSBuildWorkspace.Create(properties);`

class1.cs
`namespace NameSpace1
{
#if NET20
    delegate void Action();
    delegate void Action<T1, T2>(T1 t1, T2 t2);
    delegate void Action<T1, T2, T3>(T1 t1, T2 t2, T3 t3);
    delegate void Action<T1, T2, T3, T4>(T1 t1, T2 t2, T3 t3, T4 t4);
#endif
}`
class2.cs
`using System;
namespace NameSpace1
{
    class Class1<T>
    {
        public static readonly Action<Exception> Throw = delegate (Exception ex) { throw ex; };
        private Action<T> _onNext;
        Class1(Action<T> onNext, Action<Exception> onError)
        {
            this._onNext = onNext;
        }
    }
}`

**Comment by CyrusNajmabadi** [comment]
@gabirx Can you format your code properly?  Thanks.

Also, are you saying you still believe there is an issue?  If so, can you be specific about what issue it is you think you're encountering?

**Comment by gabirx** [comment]
> @gabirx Can you format your code properly (including in the original post)? Thanks.
> 
> Also, are you saying you still believe there is an issue? If so, can you be specific about what issue it is you think you're encountering?
Yes, the problem persists. 
When rename NameSpace1.Action<T1,T2> to  NameSpace.Action2<T1,T2>, renamed links System.Action<T> on NameSpace1.Action2<T>. 
NameSpace.Action2<T1,T2> references were renamed correctly in other files

**Comment by CyrusNajmabadi** [comment]
Sorry, i'm not quite sure what you're seeing.  What result did you see?  Can you post the code for hte resultant file?

**Comment by CyrusNajmabadi** [comment]
Note: i don't repro this myself when i try this manually in VS.  Is it possible there is something wrong with your project configuration?  For example, if mscorlib isn't properly being added, then the compiler will not know that `Action<T>` binds to `System.Action<T>` and will instead think it binds to one of your delegates.

Are you sure the code you've loaded compiles without errors?

For example, just looking at your original post code (which you still haven't reformatted).  I don't see any place where you add references.  So I don't see how this would work for you.

**Comment by sharwell** [comment]
@gabirx Here's some short code to reproduce this issue:

⚠️ Note that the following file _intentionally_ omits `using` directives for the purpose of demonstrating this behavior.

```csharp
class TestClass
{
    delegate void Action<T1, T2>(T1 t1, T2 t2);

    void Method(Action<int> action) { }
}
```

Since the code references `Action<T>` but there is no type with that name in scope, the compiler reports error CS0305 and binds the reference to the type most closely matching the name, which is `Action<T1, T2>`. When you rename the delegate, the reference to it is also updated. This behavior is by design.

The scenario highlights which the new analyzer testing library ([Microsoft.CodeAnalysis.Testing](https://github.com/dotnet/roslyn-sdk/blob/master/src/Tools/Microsoft.CodeAnalysis.Testing/README.md)) validates by default that the input code does not contain any compiler errors that have not been explicitly declared. It's very easy to miss these errors in testing, leading to misinterpreted test results:

* Compiler errors can cause tests to incorrectly pass, e.g. cases where you are asserting that an error does not appear, but the error only does not appear because the compiler error is masking it
* Compiler errors can cause tests to incorrectly fail, e.g. cases like this issue

**Comment by gabirx** [comment]
> Note: i don't repro this myself when i try this manually in VS. Is it possible there is something wrong with your project configuration? For example, if mscorlib isn't properly being added, then the compiler will not know that `Action<T>` binds to `System.Action<T>` and will instead think it binds to one of your delegates.
> 
> Are you sure the code you've loaded compiles without errors?
> 
> For example, just looking at your original post code (which you still haven't reformatted). I don't see any place where you add references. So I don't see how this would work for you.

The problem did not reproduce on the other computer. After you recreate the solution and use the packages from the "Stand alone code analysis tool" template, the problem also does not reproduce. Thank you!
