### ISSUE TITLE
Move wrap/unwrap parameter to a sub-menu in the context menu

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#33858]
**Version Used**: 
![image](https://user-images.githubusercontent.com/41759/53774177-4ed95200-3ea2-11e9-9bc3-fdc843540b3f.png)

I don't think these fixes are important enough to be the ordered first in the context menu.

![image](https://user-images.githubusercontent.com/41759/53774157-4254f980-3ea2-11e9-9359-65c349a91ae2.png)

I'd rather see them moved to `Change formatting` sub-menu, which should itself be the last item of the context menu.

**Comment by sharwell** [comment]
These were de-prioritized in #33631 and ported to 16.0 in #33790

**Comment by tmat** [comment]
Do you think it'd be worth creating a `Change formatting` sub-menu for all formatting fixes?

**Comment by CyrusNajmabadi** [comment]
> Do you think it'd be worth creating a Change formatting sub-menu for all formatting fixes?

I'd be personally against that unless very necessary.  Such a change will necessitate users navigating to the bottom, then diving through two lists of child menus.  That's a pretty unpleasant experience for the user.

**Comment by miloush** [comment]
I might prefer a submenu for formatting changes too, happy with all the options inlined in it. If the list of formatting actions is going to grow in the future, separating it seems inevitable at some point...

**Comment by tmat** [comment]
> However, i believe you can get up to 8 or 9 different wrapping changes (representing the top wrapping patterns i found in Roslyn and other C# repos). So that would be a lot. 

Having them all in the main menu clutters the menu. 

> I wouldn't be opposed to someone investing this. If you're interested @tmat i'd def love to see the results you get.

The thing is I do not care at all about these kind of refactorings and personally would be fine just removing them. It would make space for refactorings that are actually useful.

**Comment by tmat** [comment]
Another idea - I'm not sure why do we need to give the choice of multiple different wrapping styles for each method. I think it would make more sense to allow customers to specify preferred parameter wrapping style in their .editorconfig and then have a _single_ "(un)wrap parameters" fix in the context menu that wraps the parameters according to the style. The fix would detect whether the parameters are already wrapped - if they are it would display "Unwrap parameters", otherwise it would display "Wrap parameters". Formatting would do the same - if the parameters look wrapped then it would just format them according to the preferred style, possibly correcting the indentation.

**Comment by miloush** [comment]
Formatting has been discussed for a while... #9702 (and all referenced ones #779 #8269 #12156 #16927 #21192). The formatting could be done simply by splitting the line anywhere and invoking the autoformat.

I am also leaning towards "do not care about these", however I did eventually use it once (although none of the predefined styles were the one I wanted). If it was a code style option, it could be treated as error/warning/suggestion/refactoring only according to user's choice.

**Comment by CyrusNajmabadi** [comment]
> Having them all in the main menu clutters the menu.

And having them all be nested several levels deep makes it painful to reach these items.

> The thing is I do not care at all about these kind of refactorings and personally would be fine just removing them. It would make space for refactorings that are actually useful.

And others would like these refactorings.  Currently, the lists are not overly large and strike a reasonable balance between usefulness and usability.

**Comment by CyrusNajmabadi** [comment]
> Another idea - I'm not sure why do we need to give the choice of multiple different wrapping styles for each method. I think it would make more sense to allow customers to specify preferred parameter wrapping style in their .editorconfig and then have a single "(un)wrap parameters" fix in the context menu that wraps the parameters according to the style.

The problem is: This is not a style

i.e. if you even look at roslyn *in many files* you'll find a *mix* of wrapping forms.  The reason these 9 forms were picked, was because they had a sensible shape *and* they were found in use in many parts of the Roslyn and CoreFx codebases.  Effectively, these are refactorings because the entire point is to allow someone to quickly switch between forms they like depending on *context* (the very def of a refactoring for the IDE).

We could consider, in the future, if someone only wants to allow certain forms.  however, it defeats the purpose to have that be hte main design as it prevents someone from going to a section of wrapped args and being able to say "you know... now in this code, i would like to wrap it differently".

**Comment by CyrusNajmabadi** [comment]
>  am also leaning towards "do not care about these", however I did eventually use it once (although none of the predefined styles were the one I wanted)

Which style would you have liked to see instead @miloush ?

> it could be treated as error/warning/suggestion/refactoring only according to user's choice.

See above.  I found it difficult to even find a single codebase of any reasonable size where there was a definitive choice on the part of hte user as to the formatting style they wanted.  Even just scanning through several dozen popular C# github repos should a wide variety of forms used *in each repo*.  

Again, i'm not against hte idea of people being able to *optionally* restrict formatting wrapping.  However, that's an complimentary feature to being able to just go to one part of your code, say "i really want to rewrap this quickly" and do that (something which I've done in several parts of our codebase with htis feature quite rapidly now).

**Comment by CyrusNajmabadi** [comment]
>  am also leaning towards "do not care about these"

I'm very wary of that.  I would much prefer we drive this with telemetry.  For example, i have never once run "encapsulate field", but it's always there for me when i'm on a field.  Even though i don't care about it, it doesn't mean i don't think it should be there and available as a useful refactoring for people.

**Comment by tmat** [comment]
@CyrusNajmabadi Sure, repos are using various styles. The reason is likely that there is no setting that would allow to specify what the preferred style should be. You can make the same argument about any style that is set in .editorconfig. Until the rule is in place and can be enforced or at least suggested, you won't see any consistency.

Yet, we do not offer code fixes that e.g. change the indentation of `{` to all possible cases.

**Comment by miloush** [comment]
> Which style would you have liked to see instead @miloush ?

If I remember correctly, I wanted the same formatting traditional `if`/`for` blocks have, i.e.
```C#
MyMethod(
   1,
   2,
   3
);
```
or even what I imagine would be more controversial
```C#
MyMethod
(
   1,
   2,
   3
);
```
However, the "Indent all arguments" option does most of the hard work, and I can wiggle the rest a bit.

> i have never once run "encapsulate field", but it's always there for me when i'm on a field. 

+1 on that one

> I'm very wary of that. I would much prefer we drive this with telemetry.

I generally agree (unless I am on the bad side of telemetry, which seems to be happening a lot recently :)). It seems to be more tricky in these cases though, because the refactorings have not shipped right? So there is no telemetry to begin with and once there is telemetry data, it is already potentially a breaking change for someone.

> I found it difficult to even find a single codebase of any reasonable size where there was a definitive choice on the part of hte user as to the formatting style they wanted.

Here is an [example](https://github.com/NETMF/netmf-interpreter/wiki/Coding%20Standards#naming-conventions) of a repo that uses argument wrapping as a coding style. But yeah, it will be different for different repos - me personally would consider wrapping only at isolated places with a lot of excessively long arguments.

**Comment by CyrusNajmabadi** [comment]
> If I remember correctly, I wanted the same formatting traditional if/for blocks have, i.e.

Ah, i see.  Definitely interesting and worth consdiering.  Can you open issues on that?

**Comment by CyrusNajmabadi** [comment]
>So there is no telemetry to begin with and once there is telemetry data, it is already potentially a breaking change for someone.

We're ok with that if the usage is too limited to matter.  We've done it before.

**Comment by CyrusNajmabadi** [comment]
> @CyrusNajmabadi Sure, repos are using various styles. The reason is likely because there is no setting that would allow to specify what the preferred style should be. You can make the same argument about any style that is set in .editorconfig. Until the rule is in place and can be enforced or at least suggested, you won't see any consistency.

And if we make this a style feature, we will nto see it used.  Because some codebases will not want to mandate a style (like Roslyn).  

As i said, your suggestion is complimentary to the feature as it has shipped, it is not a replacement for it.  I'm totally fine with there being an enforceable part of this, but it needs to be optional, and people need to be able to access the refactoring in the meantime.  This is actually the design for IDE style (though unfortunately we have lots of cases that violate this). I have attempted to rectify that with this PR which actually codifies things: https://github.com/dotnet/roslyn/pull/28770

The basic idea is this:
1. you can have code-styles specified.  You can have vary level of severity for them.   You can fix-all to make everything match your preferred style.
2. regardless of severity, you can always access the feature as a refactoring.  i.e. even if the codebase has a preference to use expression-bodies for methods, you can always say in a specific case "refactor this one guy to have a block body".

--

That's how things are supposed to work in the IDE today. UNfortunately, because this isn't codified deep into the system, every feature has to try to implement the above logic, and they all almost always do it badly.  I'd like to introduce core base types that take this out of hte hands of individual features so that you just get the right consistent behavior across the board.

**Comment by CyrusNajmabadi** [comment]
Note: started looking into the code change here.  Def not hard.  But there's a bit of design complexity in how we name all the strings.  Right now because of hte existing bucketing there's a clean way to name everything without getting too verbose.  When it's one item per wrapping style, it gets much more cluttered in terms of how you name things.  Going to table for now and come back to this later.

**Comment by tmat** [comment]
I like the basic idea, but then I don't think we should pollute the context menu with dozens of style formatting refactorings especially when you have them already reported via suggestions based on .editorconfig style. That's why I suggested them all to be in a sub-menu. These refactorings are easy to do by hand for a single method or code block. I can see their value when you want to apply them to the entire document or project.

**Comment by CyrusNajmabadi** [comment]
> I like the basic idea, but then I don't think we should pollute the context menu with dozens of style formatting refactorings 

We haven't done that. 

> These refactorings are easy to do by hand for a single method or code block. 

Many refactorings are easy to do by hand.  We still offer them so people can still easily do it in an automated fashion.  Right now, if i want to wrap/unwrap a  N-line/N-node construct, that will take N steps.  We think there's enough value to make it 1 step.

>  In that case they don't add much value.

To *you*.   Encapsulate-field has zero value for *me*.  But it's something we still offer.

> I can see them having more value when you want to apply them to the entire document or project.

Again, that's a complimentary feature.  The purpose here is *precisely* to allow people to quickly make a single change when appropriate.  i.e. if they feel like a particular method is getting a little to cluttered on a single line.  Or they feel it would better wrapped one-param-per-line, instead of having wrapping, but having several items on each line.  

--

Note that this has *already* moved to the end of the list.  So it's taking up normally 1-2 items at the bottom of the list.  This is not a lot of space to be used for these feautres, and it is absolutely *not* dozens-of-style-refactorings.

**Comment by tmat** [comment]
Every feature has some value for somebody. That doesn't mean we need to add all features. Quite contrary, we should add minimal amount of features that make the greatest difference in customer productivity. Not make this just a kitchen sink of features. That has negative value for everyone. Adding a code fix that saves someone hitting enter a few of times is not worth it.

> This is not a lot of space to be used for these feautres, and it is absolutely not dozens-of-style-refactorings.

Yes, now there are two items. But you suggested that style features that you can specify in editorconfig should be designed in the way that you can invoke them manually on particular piece of code in addition to having them reported as suggestions. There is dozens of style refactorings in editorconfig. 

If you wanna be consistent then either 1) all style formatting fixes will be listed directly in the context menu or 2) none of them will be. I am saying that we should do the latter.

**Comment by CyrusNajmabadi** [comment]
> Adding a code fix that saves someone hitting enter a few of times is not worth it.

Sorry, this is not the case.  Many of our refactorings fit into this category.  Things like being able to go quickly to a type and say "use var" is only marginally quicker than selecting the type and replacing it with 'var'.  similarly, expr-bodies are just a matter of cleaning up a few tokens.  

Furthermore, this isn't just saving that.  it's also saving on things like having to go wrap a line, then see how long that line is and then find the next suitable point to wrap, and so on and so forth.  it also saves if you want to cycle through a few options to find one that best fits your needs.

> That has negative value for everyone.

This feature has already provided a lot of positive value to me and another team member.  

> we should add minimal amount of features that make the greatest difference in customer productivity.

Most IDE features would be cut under such an approach.

> But you suggested that style features that you can specify in editorconfig should be designed in the way that you can invoke them manually on particular piece of code in addition to having them reported as suggestions. There are dozens of style rules in editorconfig.

And?  There wouldn't be dozens of style options in the list.  Heck, we've already *shipped* this way for most of our style rules.  And you don't end up with dozens of options in the list.  I'm really not understanding how you're even coming to that conclusion.  can you even show a single time when we show even a *single dozen* options to the user in the list, let alone "dozens"?

> If you wanna be consistent then either 1) all style formatting fixes will be listed directly in the context menu or 2) none of them will be. I am saying that we should do the latter.

Why should we do the latter?  Style fixes/refactorings are useful, and they are things we have data that people *do* apply (for all the existing style stuff we've shipped so far).  

This whole conversation branched off of a reasonable issue (namely the priority of things) into a long discussion about a need to 'fix' something that doesn't seem to actually be 'broken'.

**Comment by miloush** [comment]
Getting back on the topic, if the way arguments are laid out was a matter of code style and set to "refactoring only", how would the experience be different from the current one?

**Comment by CyrusNajmabadi** [comment]
> Getting back on the topic, if the way arguments are laid out was a matter of code style and set to "refactoring only", how would the experience be different from the current one?

@miloush Currently there would be no difference.

**Comment by tmat** [comment]
@CyrusNajmabadi I think you are missing my point, or I misunderstood what you meant by: 

> regardless of severity, you can always access the feature as a refactoring. i.e. even if the codebase has a preference to use expression-bodies for methods, you can always say in a specific case "refactor this one guy to have a block body".
> That's how things are supposed to work in the IDE today. 

I understand this as follows: there are many style rules enforced by .editorconfig. You suggest that each of these should be manually tweakable in the right context via a code fix listed in the context menu. Is that not the case?

**Comment by CyrusNajmabadi** [comment]
> You suggest that each of these should be manually tweakable in the right context via a code fix listed in the context menu

Correct

> Is that not the case?

Right now, it's completely dependent on teh feature.  Many many many features do this incorrectly and don't properly handle the matrix of different scenarios properly.  This is why i want to codify things in a manner that you can't actually screw this up.  I've submitted PRs to help this along, but it's somewhat stalled since there are several open discussions about how we want to change the APIs for codefixes/refactorigns in the future.

**Comment by tmat** [comment]
Right, so once we fix all the features and offer all the fixes I'm worried about having too many of them listed in the top-level context menu. Then those menu items will be useless clutter in those 95% of code where you follow the style.

**Comment by CyrusNajmabadi** [comment]
> Right, so once we fix all the features and offer all the fixes I'm worried about having too many of them listed in the top-level context menu. 

This is unlikely to be the case.  The menus are contextual.  It is unlikely you'll be on such a context.  It's not like the context menu brings up every potential refactoring for everything in the file.  Rather, it gives the contextually relevant refactorings based on where you are.

> Then those menu items will be useless clutter in 95% of code where you follow the style.

All but one option in the list is already almost always unnecessary clutter.  Most of the time people are bringing up the list to invoke a single thing.  It's completely acceptable to have a set of available options for people to invoke for the time that they *do* want such an option though.

I honestly don't know what to say at this point.  These sorts of features are things we've been hearing about for *decades* from users.  The feedback about the desire to be as rich and full featured as resharper has been a continual drum people have been beating for years.  We are conscientiously and carefully adding features to give people access to the features they want (though you may not want), and we're paying attention to the experience to make sure it keeps a good balance around utility, clarity and whatnot.

**Comment by CyrusNajmabadi** [comment]
I also get teh sense that it is missed that the lightbulb experience is carefully tracked by the IDE.  We address the experience there *all the time*.  From appropriate prioritization of items.  To ensuring that items do not show up when innapropriate (and vice versa).  It's not a strange aggregation of cruft shown the user.  It's *the* entrypoint into the features we feel are contextually relevant to them based very specifically on what code they have and what they're currently doing.  

Working with code (including wrapping/unwrapping etc.) fits entirely in that purview, and is something that both our competitors have offered for ages, and which users have asked about for a long time.  It fits into the IDE goals of speeding things up and preventing people from having to manually perform the same set of steps over and over again.  

Furthermore, i'm baffled how the conversation has gone on this long.  This issue was opened, about a bug we already identified and addressed.  Since there, there has been a lot of exaggeration and hyperbole about the fact that people occasionally have a couple of formatting options available to them.  

At this point, if you want something to change, i would recommend you just go and make a PR so we can examine if the change is an improvement or not.  As i mentioned in several posts, i would be interested in seeing what the experience might be like moving from a couple of menus down to one single menu.  Maybe it will be better, and we can easily move to it.  Maybe it makes things slightly worse, btu the improvement to the top level menu is worth it.   But intead of just going on and on about this, i'd much rather the effort be focused on actually just demonstrating an improvement.
