### ISSUE TITLE
Regex Completion + Async Completion = Failure to trigger on `[` in VB

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#33852]
**Version Used**: Visual Studio 2019 Preview 4

**Steps to Reproduce**:

1. Paste VB code:

```VB
Imports System.Text.RegularExpressions
Class C
    Sub M()
        Dim r = New Regex("$$")
    End Sub
End Class
```

2. Remove the `$$` and type `[` at that location

**Expected Behavior**: Completion should show
**Actual Behavior**: Completion does not show

**Notes**:

This is related to a couple test failures for VB, including `TestCaretPlacement` and `OnlyClasses`.

Completion does work, but just not when triggered on `[`. For example, try triggering with `\` instead. In Old Completion, it correctly triggers on `[`.

I commented out the following line, and completion started triggering on `[` (but I don't know what else would go wrong as a result):
https://github.com/dotnet/roslyn/blob/6752c0f7c544b36ff574603d43d04a8c4b217cf2/src/Features/Core/Portable/EmbeddedLanguages/RegularExpressions/RegexEmbeddedCompletionProvider.cs#L32

**Comment by CyrusNajmabadi** [comment]
Can you keep me roped in on the issue here.

Note: Regex completion is using our public completion model.  Meaning, if this regresses here for async-completion, then we may be regressing things for third party completion providers.

Please don't revert regex-completion as an appropriate solution here.  We need to understand hte issue before shipping async-completion as this indicates a potential problem that 3rd party integrators may have to deal with.

Tagging @jinujoseph @ivanbasov .  To reiterate, this is not a problem with regex-completion.  rather, this indicates a change in behavior with normal completion and async completion, with regex-completion just being the canary that caught things early.

**Comment by dpoeschl** [comment]
@CyrusNajmabadi @ivanbasov I added some more notes to this issue's original post.

**Comment by dpoeschl** [comment]
I've skipped the related failing tests as part of the `master-vs-deps` merge at https://github.com/dotnet/roslyn/pull/33815.

**Comment by ivanbasov** [comment]
We do not have `RegexEmbeddedCompletionProvider.cs` in vs-deps code we use for shipping VS. @jinujoseph, are we going to mere master into master-vs-deps and then investigate the issue?

**Comment by dpoeschl** [comment]
@ivanbasov If you wanted to investigate immediately, you can checkout the `merges/master-to-master-vs-deps` branch while it still exists (this is how I've been looking at it this morning).

Otherwise, the plan is to proceed with [the merge](https://github.com/dotnet/roslyn/pull/33815) to `master-vs-deps` as soon as possible, at which point everything will live there and can be investigated that way.

**Comment by jinujoseph** [comment]
ya , i think it's important to unblock the merge. Lets investigate separately and bring the fix in

**Comment by CyrusNajmabadi** [comment]
I have no problem with merging here.  I'm glad regex completion may have helped discover a regression before it makes it into the wild!

**Comment by dpoeschl** [comment]
I had to disable a C# Regex Completion test too to get the merge in, seemingly around `[`. So maybe the VB-only-ness wasn't real. I haven't had a chance to really investigate it.

**Comment by dpoeschl** [comment]
Reopening with the merge of https://github.com/dotnet/roslyn/pull/34883
