### ISSUE TITLE
Constrained type parameter not treated as a value type for "in" extension method

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#33867]
A method declared like this
``` c#
        static void Test<T>(this in T o) where T : struct {}
```
is given the error message
``` none
CS8338 The first parameter of an 'in' extension method 'Test' must be a value type.
```
This is inexplicable, given that it *is* a value type.

**Comment by gafter** [comment]
Similarly, this method gives an error
``` c#
    static int M(this in E e) => 0;
```
where
``` c#
enum E { }
```

**Comment by VSadov** [comment]
Technically, the error is correct - `T` is a generic type parameter. It can only be substituted for structs, but it is not itself a struct :-).

Yes, the error is confusing. 

As I remember the error is intentional. We wanted only actual structs in this case, ignoring the generic type params regardless of constraints. There were reasons. I do not remember exactly.
Either it would always result in a copy with generics and as such pointless, or it would cause issues with things like null-conditional calls (like `myConstrainedInst?.Test()` <- do I get a ref to a copy? ). It must be explained in the design docs.

At very least - the error message could be better indeed.

**Comment by YairHalberstadt** [comment]
The error could be:
CS8338 The first parameter of an 'in' extension method 'Test' must be a concrete (non - generic) value type.

**Comment by gafter** [comment]
Fixed in https://github.com/dotnet/roslyn/pull/33931
