### ISSUE TITLE
ConstructorArguments and NamedArguments fail to return arguments for attributes

### ISSUE THREAD

**Issue by Grafu** [dotnet/roslyn#33901]
**Version Used**:  2.10.0

**Steps to Reproduce**:

1. Compile and run the following code: https://pastebin.com/X4aThZpA

**Expected Behavior**:

```
[Route(""api/[controller]"")]
[ApiController]
public class ValuesController : ControllerBase
{
}
```
attribute.ConstructorArguments for Route attribute should return a list with 1 argument.

```
[HttpGet(""{id}"", Name = ""Get"")]
public ActionResult<string> Get(int id)
{
    return ""value"";
}
```
attribute.ConstructorArguments for HttpGet attribute should return a list with 1 argument and
attribute.NamedArguments should also return a dictionary of 1 argument.

**Actual Behavior**:

attribute.ConstructorArguments for both cases return empty list even though attributes in the code contain arguments.
attribute.NamedArguments also returns an empty list when it should return 1 entry.

![image](https://user-images.githubusercontent.com/11540828/53906188-eda4b080-4052-11e9-95c4-2d6397da8232.png)

**Comment by CyrusNajmabadi** [comment]
It's possible that because you are not actually passing any references by which `RouteAttribute` (or your other attributes) can resolve, that the compiler is simply producing errors and doesn't have any symbols to give you.

If you get diagnostics from your compilation instance, do you see any errors reported?

**Comment by Grafu** [comment]
You are right. It is due to missing correct references.
