### ISSUE TITLE
A C# POD struct is not compiled into a runtime POD struct correctly

### ISSUE THREAD

**Issue by vlomshakov** [dotnet/roslyn#3392]
There is problem with code generation for that:
```csharp
[StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
  public unsafe struct WIN32_FIND_DATA
  {
    public uint dwFileAttributes;
    public FILE_TIME ftCreationTime;
    public FILE_TIME ftLastAccessTime;
    public FILE_TIME ftLastWriteTime;
    public uint nFileSizeHigh;
    public uint nFileSizeLow;
    public uint dwReserved0;
    public uint dwReserved1;
    public fixed char cFileName [260];
    public fixed char cAlternateFileName [14];
  }
```

If you compile project with BuildToolVersion 12 (using C# compiler), all it works.
If you compile project with BuildToolVersion 14 (using Roslyn compiler), we get runtime exception `"Cannot marshal 'parameter #2': Pointers cannot reference marshaled structures.  Use ByRef instead."` when we call P/Invoke.

repro:
https://github.com/vlomshakov/RoslynReproSolution
MsBuild version: 14.0.22609.0

**Comment by whoisj** [comment]
[StructLayout(LayoutKind.Sequential, CharSet=CharSet.Auto)]
 struct WIN32_FIND_DATA
 {
     public uint dwFileAttributes;
     public System.Runtime.InteropServices.ComTypes.FILETIME ftCreationTime;
     public System.Runtime.InteropServices.ComTypes.FILETIME ftLastAccessTime;
     public System.Runtime.InteropServices.ComTypes.FILETIME ftLastWriteTime;
     public uint nFileSizeHigh;
     public uint nFileSizeLow;
     public uint dwReserved0;
     public uint dwReserved1;
     [MarshalAs(**UnmanagedType.ByValTStr, SizeConst=260**)]
     public string cFileName;
     [MarshalAs(UnmanagedType.ByValTStr, SizeConst=14)]
     public string cAlternateFileName;
 }

**Comment by vlomshakov** [comment]
Why doesn't c# compiler(msbuild 12) have any problem with it? 
It looks like bug.

**Comment by hypersw** [comment]
@whoisj: your declaration won't even compile in the given example, because it's not a POD and you can't pass it as `WIN32_FIND_DATA* lpFindFileData` to the funciton.

The point is that the declaration is intended to produce a POD (i.e. a named group of bytes) to be passed to Windows as a pointer. From C# point of view, it's a POD, and you can have pointers to it. 
I expect the compiler to produce CIL for it which also is a POD.

But from the error that reads "Pointers cannot reference marshaled structures." I assume that Roslyn-compiled version of this struct does not look like a POD to the runtime, while CSC makes a POD out of it.

So, the error is: "A C# POD struct is not compiled into a runtime POD struct correctly".

**Comment by hypersw** [comment]
Now, to the difference.
Both compilers emit helper nested value types to back the fixed buffers.

CSC:
```
  .class sequential unicode sealed nested public beforefieldinit '<cFileName>e__FixedBuffer0'
         extends [mscorlib]System.ValueType
```

Roslyn:
```
  .class sequential ansi sealed nested public beforefieldinit '<cFileName>e__FixedBuffer'
         extends [mscorlib]System.ValueType
```

(other lines look equivalent, but for the names)

The only percieved difference is that CSC places the `unicode` attribute, and Roslyn does not pull `unicode` from the outer class and marks them as `ansi`.

I guess the runtime problem is that you can't pass what you think is ANSI chars as a buffer to the UTF-16 OS API.

-----

Outline: Roslyn does not pull the `unicode` attribute from the outer value type to the generated nested value types which support fixed buffers.

**Comment by whoisj** [comment]
@hypersw I copied the code from the CoreFX source code, I really hope that it compiles!

**Comment by hypersw** [comment]
@whoisj: if you paste the struct declaration into the repro code at https://github.com/vlomshakov/RoslynReproSolution, you'd see it actually does not.

But anyways the point is not in trying to look up the code that works around the compiler issue (the simplest workaround would be to use a `UInt16` buffer instead of a `Char` buffer), but to make the compiler not worse than CSC.

**Comment by AlekseyTs** [comment]
@gafter Please verify.
