### ISSUE TITLE
Add Indent to format multi-line strings

### ISSUE THREAD

**Issue by VBAndCs** [dotnet/roslyn#34006]
when we right multi-line string, it looks like this:
```C#
            var code = @"
public class MyClass
{
    public void MyMethod()
    { 
    }
}";
```

we can't add spaces in each line to format the string, because they will be added to the string itself, 
Can VS editor add some auto indent to multi-line strings, so it is not considered as spaces (indent in word is not a white space)?
I can workaround this using something like:
```C#
            var code = @"
___________________public class MyClass
___________________{
___________________    public void MyMethod()
___________________   {
___________________   }
___________________}"
                .Replace("___________________", "");
```

but it still looks ugly!

**Comment by jrmoreno1** [comment]
I added this as a comment on developer community just the other day.

https://developercommunity.visualstudio.com/idea/482286/tabs-in-multi-line-interpolated-strings-should-be.html

**Comment by VBAndCs** [comment]
@jrmoreno1
Nice, but tabs can be treated as part of the string, besides, we can edit them which will confuse the editor. 
The editor can have a left indent for each of these lines,  where no one can write or delete.
RitchTextBox has such indent, and I think VB editor is more advanced than RitchTextBox.

**Comment by CyrusNajmabadi** [comment]
@VBAndCs 

> Can VS editor add some auto indent to multi-line strings, so it is not considered as spaces (indent in word is not a white space)?

Sure.  This could likely be done.  Would you be interested in contributing such a change?  I have some ideas on how you might do it, and i would be happy to suggest them to you.

**Comment by CyrusNajmabadi** [comment]
> but it still looks ugly!

Your indented code looks worse to me.

**Comment by VBAndCs** [comment]
> > but it still looks ugly!
> 
> Your indented code looks worse to me.

I can use spaces instead of underscores. It will work in this sample but can not be granted in others.

**Comment by VBAndCs** [comment]
> @VBAndCs
> 
> > Can VS editor add some auto indent to multi-line strings, so it is not considered as spaces (indent in word is not a white space)?
> 
> Sure. This could likely be done. Would you be interested in contributing such a change? I have some ideas on how you might do it, and i would be happy to suggest them to you.

I can try. Where to start or what project to fork?

**Comment by sharwell** [comment]
@VBAndCs The best place to start would be a detailed description of the precise behavior of this feature, especially in relation to other impacted features:

* What happens when a user clicks in the indentation area?
* What happens when the user has a rectangular selection?
* What happens if the verbatim string literal is broken up?

    ```csharp
    _ = @"
    text" + 0 + @"
    more text";
    ```

* What happens if the user manually indents the string by selecting it and pressing <kbd>Tab</kbd>?
* What happens if the user manually unindents the string by selecting it and pressing <kbd>Shift</kbd>+<kbd>Tab</kbd>?
* Will users with Show Whitespace disabled be able to make sense of the new behaviors? What about when Show Whitespace is enabled?

**Comment by VBAndCs** [comment]
> How is the desired indentation amount determined?

Using same roles uses when a normal code line is broken after `,` for example.

>What happens when a user clicks in the indentation area?

1 click: put cursor before the first char in line.
2 clicka: select the line.
3 clicks: select the whole string.


>What happens when the user has a rectangular selection?

Indent is not selectable, delectable nor editable (as in word and RichText). So, select only text in the rectangle.

>What happens if the verbatim string literal is broken up?

Add indent before broken text. If the line starts with var name or a language symbol don't add indent, but add regular with spaces.

>What happens if the user manually indents the string by selecting it and pressing Tab?

Increase the indent to all lines. he can us `\t` to insert tab in the string.

•What happens if the user manually unindents the string by selecting it and pressing Shift+Tab?
Decrease the indent to all lines.


>Will users with Show Whitespace disabled be able to make sense of the new behaviors? What about when Show Whitespace is enabled?

Indent is not a white space and shouldn't be affected with this option. I appears as a blank area in all cases. 

Note: The indent can have a back color other than white. Maybe light grey.

**Comment by CyrusNajmabadi** [comment]
Could you mock up a picture of what this would actually look like?

**Comment by VBAndCs** [comment]
This is how the indent looks in MS Word:
![2](https://user-images.githubusercontent.com/48354902/54143557-be1aed00-4432-11e9-95a2-2a376025f604.jpg)

It is not selectable, or editable. 
I don't know what type of controls the editor is, but it seems more advanced than RichTextBox which can add different indents to each line..

**Comment by CyrusNajmabadi** [comment]
Sorry, i'm asking for mockups what this would look like in a normal VS environment.  I'd like to see the mockups for this in both the light and dark theme, and with things like 'view-whitespace' on.  Also, it would be good to get a mockup with other adornments on the line.  For example teh debugger breakpoint. 

Can you go make those (with a normal font btw).

**Comment by VBAndCs** [comment]
Sorry, I don't know what the mockups is, nor how can view this in visual studio while it is not there yet.
Again, the question is: Does the editor have an indentation capability with some built-in properties? If it does, the implementation should be easy. Otherwise, I don't know how you can workaround this.

**Comment by sharwell** [comment]
@VBAndCs I think we have enough information to have an initial design discussion and see if this is something we want to pursue in dotnet/roslyn. We should know more after that.

**Comment by CyrusNajmabadi** [comment]
> Sorry, I don't know what the mockups is, nor how can view this in visual studio while it is not there yet.

Use mspaint, or whichever image editor you would like.  I can walk you through how you can do that over on gitter.im if you want to discuss things further.

**Comment by VBAndCs** [comment]
![Untitled](https://user-images.githubusercontent.com/48354902/54157262-a4889e00-4450-11e9-84a0-d761bcd64b8f.png)

**Comment by CyrusNajmabadi** [comment]
@vbandcs

> Sorry, i'm asking for mockups what this would look like in a normal VS environment. I'd like to see the mockups for this in both the light and dark theme, and with things like 'view-whitespace' on. Also, it would be good to get a mockup with other adornments on the line. For example teh debugger breakpoint.

> Can you go make those (with a normal font btw).

Feel free to come to gitter.im and we can discuss this further.  It would likely be a lot faster and passing information along to you.

**Comment by MarkusAmshove** [comment]
There was a csharplang proposal to have this as a language feature and I did a writeup on how this looks in other languages:

https://github.com/dotnet/csharplang/issues/2216#issuecomment-463411783

This might help for an idea.
I don't mean this comment to implement this as a language feature, as an editor feature proposed by @VBAndCS would be cool enough  :-)
The linked posts contain some screenshots

**Comment by jrmoreno1** [comment]
> @VBAndCs The best place to start would be a detailed description of the precise behavior of this feature, especially in relation to other impacted features:

Not @VBAndCs, but since my dev community request has been closed as a duplicate, I will take a shot at this..

> * How is the desired indentation amount determined?

From the position of the first “ character in the assignment of a multi line assignment expression (it wouldn’t hurt elsewhere but if it makes it easier, assignment is the only place I see this happening).

> * What happens when a user clicks in the indentation area?

Cursor moves to immediately before the first actual character on that line.  The indentation area is virtual and does not actually exist.

> * What happens when the user has a rectangular selection?

Characters are selected based upon virtual/displayed position, not the actual position as would be shown in notepad or some other editor.  The indentation itself can not be copied or deleted.

> * What happens if the verbatim string literal is broken up?
>   ```cs
>   _ = @"
>   text" + 0 + @"
>   more text";
>   ```

I believe it should ideally use the first “ as the indent position, but it wouldn’t be a horrible experience either way.  It is better done with string interpolation, where it would always be the first because it would be inside the same string.

> * What happens if the user manually indents the string by selecting it and pressing Tab?
> * What happens if the user manually unindents the string by selecting it and pressing Shift+Tab?

Indentation starts at the line position immediately following the “. On subsequent lines the indentation should be virtual and not actually exist: that space on the screen can not be copied or deleted, everything happens after the indentation.

> * Will users with Show Whitespace disabled be able to make sense of the new behaviors? What about when Show Whitespace is enabled?

I would suggest a new symbol for show white space (no idea what).  I don’t think it’s likely to cause confusion.   @VBAndCs used Word as his example, and the behavior is similar enough to that for people to easily mentally map it to the same kind of behavior.

**Comment by CyrusNajmabadi** [comment]
This is what raw-strings are for.  If you just switch to them, you'll get this behavior for free.  We are unlikely to do anything with our other strings given this.

**Comment by VBAndCs** [comment]
Are raw-strings available in VB.NET?
