### ISSUE TITLE
Consider removing IDocumentOperationsService.CanApplyChange

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#34011]
> dumb question.  why do we need this guy?  it even says you should be able to ask `"Workspace.CanApplyChange(ApplyChangesKind)"`

_Originally posted by @CyrusNajmabadi in https://github.com/dotnet/roslyn/pull/34009#discussion_r264343085_

**Comment by heejaechang** [comment]
we have multiple ways to ask about feature/API supports for different dimensions.

1. we can ask whether a workspace host supports certain kind of changes.
2. we can ask whether a document support certain kind of features.
3. we can ask whether a certain document is generated files.
4. we can ask whether a certain document supports diagnostics and etc.

I am pretty sure there are even more than what I wrote the above. 

each one has a different view and who decides what.

1), it is workspace claiming what kind of changes it supports
2), it is workspace claiming what kind of feature document in the workspace supports.
3) it is language service (aka, project) claiming, what document is a generated code. it is used by feature author to decide whether they want to offer their feature or not on whatever context they want to.
4) it is a document provider claiming, it wants to have diagnostics on its document.

there are all one-off code that have these SupportXXX in our code. I guess at some point we need to make sense of all those ones. it would be nice those are documented to show what they are for. and had design discussion before those are added.

anyway, I guess this issue is about why we added 4) rather than using any other APIs.

we didn't see a way to use any other APIs without changing existing code since this is added after meeting with people involved with razor work.

so rather than messing with those APIs that seems just doing one of thing, this is added specifically for the work as other seems added with same way.

but that doesn't mean it should left this way. as we move to more final phase with razor, we can merge those.

for example, we can have engine to consume SupportDiagnostics of DocumentService so that we don't need this each code fix (or some random on checking and other doesnt) checking for isGeneratedFiles for one that opt in. 

or we could change IsGeneratedCode to support razor case and fix every diagnostics and others to make sure they check IsGeneratedCode and pass this info to compilation from IDE layer.

any suggestion is welcome.

I hope suggestion is a bit better than, I dont know this so it must be not needed. or I wasn't involved in the meeting so it must be bad, or convince me it is needed otherwise, this is not needed.

all code is there. if you want to contribute, please spend some time to read code like everyone else does, and provide how this can be changed better.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.  If we want to remove this, we should just remove this.  The tracking issue doesn't change things.
