### ISSUE TITLE
`SetRemoteHostBitness()` uses invalid feature flag

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#34047]
https://github.com/dotnet/roslyn/blob/bd1e0c6cb23e552d390c1b3c14cdb6ec8434883e/src/VisualStudio/Core/Def/Implementation/Remote/RemoteHostClientServiceFactory.RemoteHostClientService.cs#L166-L167

This api requires a `word.word` feature flag, which we are not providing. This causes an exception that is silently swallowed by our experimentation service wrapper, and causes a resources dll load in RPS.

**Comment by heejaechang** [comment]
thank you @333fred 

so the root cause is that we use same IExperiementationService for 3 different VS services. 1. feature flags and 2. A/B testing and 3. experiment service.

3 are different services in VS side for 3 different purposes. 1 is to create specific ring to test new feature, 2. is to make multiple experiences on a feature to find out which one give us better result, 3 is exposing new feature to small group of random people to test stability and etc.

but in roslyn side, we don't care those 3 being 3 different services (portal to set up flight_, we treat them as under same service.

problem is that requirement for flight name is different for all 3 services. and newly added feature flag service is rejecting flight name for other 2 services and causing resource file to loaded.

linked PR should fix that.

**Comment by CyrusNajmabadi** [comment]
@333fred

> This causes an exception that is silently swallowed by our experimentation service wrapper,

Where does this this silent swallowing occur?  Thanks!

**Comment by heejaechang** [comment]
it has nothing to do with we swallowing the exception since it is known exception we have. what we didn't know is it will bring in resource file.

**Comment by 333fred** [comment]
@CyrusNajmabadi https://github.com/dotnet/roslyn/blob/0196c9d5fcdbe589418d5781bd1aa935972dd4be/src/VisualStudio/Core/Def/Experimentation/VisualStudioExperimentationService.cs#L53.

**Comment by CyrusNajmabadi** [comment]
@333fred is it the 'catch-all's in that method that are causing the silent swallowing?

**Comment by 333fred** [comment]
Yeah. The underlying API was doing a regex match on `(\w\.)+\w`, and throwing an invalid flag exception.
