### ISSUE TITLE
Collection initializer code fix should recognize assignments into an array

### ISSUE THREAD

**Issue by neven10** [dotnet/roslyn#34131]
Visual Studio Community 2017 v15.9.6
".NETFramework,Version=v4.7.2"

**Steps to Reproduce**:

```
        private async Task SomethingAsync()
        {
            Task[] tasks = new Task[2];
            tasks[0] = this.SomeTaskOne();
            tasks[1] = this.SomeTaskTwo();
            await Task.WhenAny(tasks);
        } 
```

**Expected Behavior**

Something like this:

`   await Task.WhenAny(new Task[] { this.SomeTaskOne(), this.SomeTaskTwo() });`

**Actual Behavior**:    
     
    (new Task[2])[0] = this.SomeTaskOne();
    (new Task[2])[1] = this.SomeTaskTwo();
    await Task.WhenAny(new Task[2]);

     Naturally it also breaks function completely.

Not a big deal ofc. I just stumbled across this. 
I usually auto refactor just basic stuff like properties.

**Comment by jasonmalinowski** [comment]
We discussed this and decided that we're best off leaving the behavior as is, but with an investigation into something else too.

The challenge here is we know _as humans_ this is somewhat preposterous but it's hard to turn this into something that seems useful. We don't want to block inlining of all object creations, because sometimes people do indeed want to say new Foo().SomeMethod(). You might do further editing after that, but in those cases this is a useful tool that gets you closer to where you are going. We could try adding more specific smarts around "block inlining of array creations" or "block inlining of array creations followed by assignments into specific indexes", but it felt like at that point we were perhaps blocking individual scenarios that are sufficiently rare it doesn't warrant extra overhead of maintaining the code.

The one thing we *did* wonder though is if our use collection initializer refactoring should have picked this up which would have done the transformation that was wanted here. We didn't have a good answer why that didn't work, so I'm going to update this bug accordingly.

**Comment by CyrusNajmabadi** [comment]
Adding 'help wanted'.  We would likely take an update which adds support for converting:

```
            Task[] tasks = new Task[2];
            tasks[0] = this.SomeTaskOne();
            tasks[1] = this.SomeTaskTwo();
```

Into

```
            Task[] tasks = new Task[]
            {
                this.SomeTaskOne(),
                this.SomeTaskTwo(),
            }
````

Or, even better in this case, either:

```
            var tasks = new []
            {
                this.SomeTaskOne(),
                this.SomeTaskTwo(),
            }
```

(if the user likes var), or:

```
            Task[] tasks =
            {
                this.SomeTaskOne(),
                this.SomeTaskTwo(),
            }
```

If the user does not.

**Comment by CyrusNajmabadi** [comment]
This does not repro for me:

![Image](https://github.com/user-attachments/assets/8081f23c-5855-45d4-878b-90267589d452)
