### ISSUE TITLE
Closing brace after single line if / while

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#34181]
<p>Please provide automatic transformation which applies for control statements (while, if) in block type containing only one statement. This transformation would apply iff user removes closing or opening brace. This would automatically remove matching brace and effectivelly transform if / while from block type to single line type.<br><br>When I am refactoring I often remove one or more statements from if or while block and suddenly want to make it single line without braces. Suggested feature would make my life much easier because all I would have to do is removing opening / closing brace. </p><pre>if (a == 1) 
{
  DoSomething();
  /* When refactoring this method is suddenly no longer needed. I want to be able to delete it and after removing } make if only single line without braces */&lt;br&gt;  DoSomethingElse();
}</pre>

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/459346/closing-brace-after-single-line-if-while.html
VSTS ticketId: 795120_
_These are the original issue comments:_

Jane Wu [MSFT] on 2/18/2019, 02:28 AM (25 days ago): <p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;We'll provide an update once the issue has been triaged by the product team.</p>

**Comment by sharwell** [comment]
This went to a design review 6 May 2019.

* Roslyn's extensibility mechanism already allows this refactoring to be implemented as a 3rd-party extension, either inside Visual Studio or installed as a code fix for a specific project.
* The feature itself could have many forms. For example, some users would want the child statement moved up to the same line as the `if` keyword, while others would not. Some users will want exclusions to apply for comments, while others will not. Some users will want exclusions to apply for multi-line statements, while others will not. Some users will want this enforced as a code style, while others will only want it to be an optional refactoring.

Rather than try to implement all of the variants of this feature for all the users who might want it, we felt it makes more sense to allow simpler and more desirable features be implemented as extensions for users who would like to automate this.
