### ISSUE TITLE
Problem with temporary object lifetime

### ISSUE THREAD

**Issue by josetr** [dotnet/roslyn#34313]
**Version Used**: 
VS 2019 Preview 4.2

**Expected Behavior**:

Test should output `not equal`. The first temporary object should not be destroyed and its underlying storage shouldn't be available for reuse till the full expression is evaluated. 

**Actual Behavior**:

Test outputs `equal` because it receives 2 references pointing to the same location.

**Steps to Reproduce**:

```
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

struct Num
{
    byte n;

    public Num(byte n)
    {
        this.n = n;
    }

    public Span<byte> Span => MemoryMarshal.CreateSpan(ref n, 1);
}

static void Test(Span<byte> a, Span<byte> b)
{
    Console.WriteLine(a.SequenceEqual(b) ? "equal" : "not equal");
}

static void Main()
{
    Test(new Num(1).Span, new Num(2).Span);
}
```

**IL** seems to make things more obvious:
```
// Method begins at RVA 0x2688
// Code size 38 (0x26)
.maxstack 2
.entrypoint
.locals init(
    [0] valuetype ConsoleApp1.Program/Num

)

// (no C# code)
    IL_0000: nop
// Num num = new Num(1);
IL_0001: ldc.i4.1
IL_0002: newobj instance void ConsoleApp1.Program/Num::.ctor(uint8)
IL_0007: stloc.0
// Span<byte> span = num.Span;
IL_0008: ldloca.s 0

IL_000a: call instance valuetype[System.Runtime] System.Span`1<uint8> ConsoleApp1.Program/Num::get_Span()
// num = new Num(2);
IL_000f: ldc.i4.2

IL_0010: newobj instance void ConsoleApp1.Program/Num::.ctor(uint8)
IL_0015: stloc.0
// Test(span, num.Span);
IL_0016: ldloca.s 0

IL_0018: call instance valuetype[System.Runtime] System.Span`1<uint8> ConsoleApp1.Program/Num::get_Span()
IL_001d: call void ConsoleApp1.Program::Test(valuetype[System.Runtime] System.Span`1<uint8>, valuetype[System.Runtime] System.Span`1<uint8>)
// (no C# code)
    IL_0022: nop
IL_0023: br.s IL_0025


IL_0025: ret
} // end of method Program::Main
```

**Comment by gafter** [comment]
I think this may be a bug in escape safety analysis.  I think there should be an error on
``` c#
    public Span<byte> Span => MemoryMarshal.CreateSpan(ref n, 1);
```

**Comment by josetr** [comment]
@gafter It would be nice if someone could clarify what is going on and what is safe to do since the issue has not been fixed.

> I think this may be a bug in escape safety analysis. I think there should be an error on
> 
> ```cs
>     public Span<byte> Span => MemoryMarshal.CreateSpan(ref n, 1);
> ```

Is it safe if the object is not a temporary one or if the object is a reference type?

Asking because doing either one seems to work just like in [this](https://stackoverflow.com/a/54334142) stackoverflow answer. Returning spans from fixed buffers seems useful but I need someone to clarify if it's safe to do so.

**Comment by gafter** [comment]
@jaredpar FYI

**Comment by jaredpar** [comment]
@gafter thanks for the ping. 

The compiler is operating correctly here. The `ref` escape rules are written with the [explicit assumption](https://github.com/dotnet/csharplang/blob/master/proposals/csharp-7.2/span-safety.md#span-constructor) that there is no usable constructor on `Span<T>` that takes and stores a `ref T`. Essentially the `ref` escape rules do not believe in the existence of `ref` fields. That means the compiler believes there is no way for the returned `Span<T>` to contain a reference to `ref n` because it's explicitly disallowed by the rules.

That constructor does exist though, it's just private to the .NET runtime. The `MemoryMarshal` class is one of the types that indirectly exposes that constructor and hence any uses of this method are not properly lifetime checked. This is noted directly in the documentation comment for this type:

> The lifetime of the returned span will not be validated for safety by span-aware languages.

Essentially the compiler is operating by the rules here but the API is not. In general the InteropServices namespace does contain types, including `MemoryMarshal`, which can do unsafe memory operations that don't fully comply with the C# language safety rules for `unsafe` or `ref` escape safety. Those APIs need to be used with caution.

**Comment by josetr** [comment]
@jaredpar Thanks for the detailed answer. Its clear that what I've reported is not a bug but I'm still unsure what this means for the example provided in [this](https://stackoverflow.com/a/54334142) stackoverflow answer. Returning a `Span<T>` to an object's field that was allocated in the heap (due to boxing or because it was a reference type) seems to work consistently. The Span internal pointer is updated after compacting the heap and the object seems to be kept alive.

I just would like to know if that is an example of "using the API with caution" assuming I will only use .NET Core.

Here is another example that seems to work:

```cs
struct SmallIntList {
    fixed int buffer[10];
    public Span<int > Span => new MemoryMarshal.CreateSpan(ref buffer[0], 10);
}

class Class {
    public SmallIntList list;
}

var span = obj.list.Span;
```

**Comment by jaredpar** [comment]
>  Its clear that what I've reported is not a bug but I'm still unsure what this means for the example provided in this stackoverflow answer.

One problem with that stackoverflow example is that it operates on the _assumption_ that the value is moving in memory but it does not verify that it does. I think that sample is more instructive when the explicit check for watching the underlying heap object move is added. I did add that locally though and yes it does indeed move. 

> The Span internal pointer is updated after compacting the heap and the object seems to be kept alive.

There are two claims being made here that I will address separately: internal pointer is updated and object is kept alive. 

At it's core `Span<T>` on is really just a tuple of `(ref T data, int length)` and it's a `struct` hence both of these exist effectively on the stack. The GC is responsible for updating the `ref T` portion as objects in the heap move just as it would be responsible for updating any other `ref` local variable. 

The code in question here is indeed using `unsafe` but it is returning a valid `ref` into to the interior of a heap allocated object. The fact that `unsafe` was used to create it is somewhat immaterial. The end result is a `ref` to the interior of a heap allocated object. If the GC moves the object, it needs to update all `ref` on the stack that refer to it. That is why the value properly tracks during compaction. 

This also follows though that the object is kept alive. That is because the `Span<T>` here has a `ref` to the interior of an object hence just like a `ref` local this is a strong reference to the entire containing object. 

Now I must caveat here that my answers are only valid when this sample is run on .NET Core. In that environment `Span<T>` is intrinsic to the runtime and it fits into the `(ref T data, int length)` mental model. On .NET Framework though this is not the case because `Span<T>` is not an intrinsic. Instead it uses a three word storage strategy of essentially `(object container, IntPtr offset, int length)`. In the cases where `container == null` the resulting `Span<T>` is no longer a strong pointer on .NET Framework where it would be on .NET Core. The code in the stackoverflow sample is one such example. If you change that to multi-target `netcoreapp3.1` and `net5.0` you'll see that the behavior is different for this reason. 

In the majority case this distinction does not matter. Straight line C# code won't ever see this difference. It requires _clever_ unsafe code to produce samples which differ between .NET Core and .NET Framework. But this sample does fit squarely into that hence it's worth discussing.
