### ISSUE TITLE
Cannot find path 'D:\roslyn\System.Windows.Forms.dll' because it does not exist.

### ISSUE THREAD

**Issue by jdm7dv** [dotnet/roslyn#34347]
**Version Used**: 
 Windows 8.1
**Steps to Reproduce**:

1. build a release version of the powershell rc set PATH in the Control Panel replace old system powershell env variable. sign out sign back in to set variable not using a sandbox.
2. open Visual 2017 CMD prompt
3. runt the restore.cmd batch file.

**Expected Behavior**:
restore.cmd to complete 
**Actual Behavior**:
Cannot find path 'D:\roslyn\System.Windows.Forms.dll' because it does not exist.

**Comment by jmarolf** [comment]
@jdm7dv are you trying to build roslyn or some other project? If you are trying to build the master branch of roslyn it requires a preview installation of VS 2019 now

**Comment by 333fred** [comment]
This happened because the version of pwsh you compiled does not have a reference to Windows Forms, which some of the integration tests scripts need. This was fixed a while ago, we only import those things if the integration tests are being run. For that scenario, you will need to use a version of powershell that has a reference to WindowsForms.
