### ISSUE TITLE
Cannot read preview for IDE0059 code fix

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#34445]
**Version Used**: Visual Studio 2019 RC

**Steps to Reproduce**:

Apply the suggested IDE0059 code fix for this line:
https://github.com/dotnet/roslyn/blob/b28ec8a8fff49553516e6af0123ff0c2dac08f82/src/Features/Core/Portable/QuickInfo/IndentationHelper.cs#L36

**Expected Behavior**:

Preview is clear.

**Actual Behavior**:

![image](https://user-images.githubusercontent.com/1408396/55010885-0b5e9900-4fb3-11e9-80dd-acf87edf1556.png)

**Comment by JoeRobich** [comment]
At least this isn't a problem I introduced.

**Version Used:** Visual Studio 2017

![image](https://user-images.githubusercontent.com/611219/55034274-5cca5080-4fd2-11e9-988f-571145be6798.png)

**Comment by JoeRobich** [comment]
**Version Used:** Visual Studio 2017

![image](https://user-images.githubusercontent.com/611219/55034410-a87cfa00-4fd2-11e9-9346-227432e28e88.png)

**Comment by JoeRobich** [comment]
This statement is colored yellow in the diff view because the node has a WarningAnnotation added. Preview Warning classification controls this color.
![image](https://user-images.githubusercontent.com/611219/55036905-4378d280-4fd9-11e9-8948-10810b7f98c3.png)

Here is the same diff with a more reasonable warning color
![image](https://user-images.githubusercontent.com/611219/55037014-90f53f80-4fd9-11e9-9155-6dc351799fdf.png)

**Comment by sharwell** [comment]
@JoeRobich I literally did not realize there was a warning in this dialog until you commented on it there. We should improve visibility on it, e.g. by placing ⚠️ icon at the start.

**Comment by JoeRobich** [comment]
This is where the marker definition is defined.
https://github.com/dotnet/roslyn/blob/88d1bd10fa5ee14d3199ed94b2a04834e6421449/src/EditorFeatures/Core.Wpf/PreviewWarningTagDefinition.cs#L15-L24

One solution would be to remove the BackgroundColor and uncomment the border.
![image](https://user-images.githubusercontent.com/611219/55037865-54771300-4fdc-11e9-916d-10beaab6b40c.png)

**Comment by JoeRobich** [comment]
Here it is with a textual ⚠️ symbol:
![image](https://user-images.githubusercontent.com/611219/55038342-b6844800-4fdd-11e9-8711-86c0e4101785.png)

Since this is a marker setting foreground color has no effect and choosing a single background color that can work with both dark and light editor themes while providing good contrast is not possible.

**Comment by JoeRobich** [comment]
@sharwell We could replace these lines in the PreviewFactoryService to get textual emoji

https://github.com/dotnet/roslyn/blob/23c08dd017f93c05e62e132f2515bc3cceec31df/src/EditorFeatures/Core.Wpf/Preview/PreviewFactoryService.cs#L396-L406

replace with something like
```csharp
                var conflictNodes = newRoot.GetAnnotatedNodesAndTokens(ConflictAnnotation.Kind);
                var conflictSpans = conflictNodes.Select(n => n.Span.ToSpan()).ToList();
                var conflictDescriptions = conflictNodes.SelectMany(n => n.GetAnnotations(ConflictAnnotation.Kind))
                                                        .Select(a => $"❌ {ConflictAnnotation.GetDescription(a)}")
                                                        .Distinct();

                var warningNodes = newRoot.GetAnnotatedNodesAndTokens(WarningAnnotation.Kind);
                var warningSpans = warningNodes.Select(n => n.Span.ToSpan()).ToList();
                var warningDescriptions = warningNodes.SelectMany(n => n.GetAnnotations(WarningAnnotation.Kind))
                                                        .Select(a => $"⚠ {WarningAnnotation.GetDescription(a)}")
                                                        .Distinct();
```
