### ISSUE TITLE
MSBuildWorkspace unable to load compiler task

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#3454]
Now that we removed `Microsoft.Build.Tasks.CodeAnalysis.dll` from the GAC, standalone apps that try to use `MSBuildWorkspace` need a way to find and load it.

**Comment by agocke** [comment]
@Pilchie @jasonmalinowski Does the workspaces require a full reference or only a design-time reference to the build task?

**Comment by Pilchie** [comment]
A full reference.  It actually isn't required for build time, but the app has to be able to load it.

**Comment by agocke** [comment]
Fixed in CS 1486756

**Comment by agocke** [comment]
There's an alternate fix proposed for this currently in review.

**Comment by agocke** [comment]
Customer scenario -- If a customer uses the MSBuild APIs to execute a build (real or otherwise), they may be surprised that they have to bundle the Roslyn build task with their application, *even if VS 2015 is installed on the machine.* This is because we currently use a regular `Load` in MSBuild to load a task named `Microsoft.Build.Tasks.CodeAnalysis`. Since it's unlikely that the MSBuild 15 install directory is on their binding path, unless they include the build task or alter their binding resolution they will not find the build task.

Fix description -- Use relative path resolution to load the assembly file rather than assembly name resolution. This finds the build task at a relative path to the installed tasks file, which should be installed as long as VS 2014 is correctly installed.

Testing done -- Manual, by patching the tasks file with this fix in a D14Rel install and then

1) Building a C# and VB console application
2) Opening files that are a part of the projects and verifying that they are recognized as part of the projects and not misc files (i.e., design-time build succeeded)
3) Creating errors in the projects and verifying that the correct error is shown in the Error List and in the output window during build.

**Comment by MattGertz** [comment]
Approved 6/16 by ML Shiproom. @jaredpar Add testing.

**Comment by agocke** [comment]
Workspaces.Common NuGet change committed as 1489119. D14Rel change will go in later today.

**Comment by agocke** [comment]
Insertion completed with 1489492.
