### ISSUE TITLE
Suggest using of types in referenced Assembly

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#34642]
**Repro Steps** 
1. Create a class library (any kind) 
2. Add a reference to the binary by browsing to file path C:\Program Files\dotnet\sdk\NuGetFallbackFolder\newtonsoft.json\11.0.2\lib\netstandard2.0\Newtonsoft.json.dll 
3. Add a console Application to the same sln 
4. In your console application use the type from Newtonsoft.json 

You will get a suggestion 
![image](https://user-images.githubusercontent.com/12449387/55348801-ea8fbb00-546c-11e9-852e-9d13bc9a4ff5.png)

Another example 
![image](https://user-images.githubusercontent.com/12449387/55348895-1c088680-546d-11e9-8593-74df6d709346.png)

Also reported here 
We have a report of what looks like the same or similar bug, where a user reports that the quick fix added a reference to “..\..\..\..\..\..\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Collections.Immutable.dl”: https://developercommunity.visualstudio.com/content/problem/458599/warning-about-conflicts-between-system-libraries-a.html?childToView=503859#comment-503859

**Question** 
Is this by design and doesn't seem to be controlled by this option 
![image](https://user-images.githubusercontent.com/12449387/55349053-8de0d000-546d-11e9-8d88-291450aba3d4.png)

**Comment by sharwell** [comment]
Design review summary:

1. The current option is unclear. We should change the text for the option to the following to better reflect its current (and still intended) behavior:

    > Suggest usings for types in .NET Framework assemblies

1. The current implementation generally follows the process we want to use for presenting this code fix. However, one final step is missing: after locating an assembly which will be presented in this list, we should attempt to resolve its location on disk to a NuGet package, and if one is found from context, present it as a NuGet package reference instead of an assembly reference. For the example images above, the assemblies would have been resolved to Newtonsoft.Json:11.0.2 and Microsoft.NETCore.App:2.1.0, respectively.

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.
