### ISSUE TITLE
StackOverflow in the compiler

### ISSUE THREAD

**Issue by tannergooding** [dotnet/roslyn#34693]
**Repro:**
Compile the following program using the latest compiler bits:
```csharp
using System;
using System.Runtime.InteropServices;

namespace Interop
{
    public unsafe struct PROPVARIANT
    {
        public CAPROPVARIANT ca;
    }

    public unsafe struct CAPROPVARIANT
    {
        public uint cElems;
        public PROPVARIANT* pElems;
    }
}
```

StackTrace: 
[StackTrace.txt](https://github.com/dotnet/roslyn/files/3036089/StackTrace.txt)

**Comment by tannergooding** [comment]
This does not repro against the 3.0.0 bits released with VS 2019 today, but does against the latest 3.1.0 bits

**Comment by tannergooding** [comment]
CC. @jaredpar

**Comment by chsienki** [comment]
Possibly related to: https://github.com/dotnet/roslyn/issues/24978 ?

**Comment by RikkiGibson** [comment]
I think I introduced this somehow in the implementation of unmanaged constructed types. Looking now.

**Comment by RikkiGibson** [comment]
The situation we're in looks a bit like:
```
- bind field types
  - bind pointer type
    - check if pointed-at type is unmanaged
      - bind pointed-at type
        - bind field types
          - bind pointer type
            - check if pointed-at type is unmanaged...
```

As part of the unmanaged constructed types feature, we had to push generic constraint checks until after fields were bound. In a sense, pointer types are a special case of generic constraints-- a pointer has a type parameter constrained to `unmanaged`, and for similar reasons we probably need to push the unmanaged check until after fields types are bound.

I've done this in an ad-hoc way without too much difficulty and it fixes the case in the issue description, but it introduces a weird edge case behavior due to a small oversight in how after-binding constraint checks works. Basically, the following case will no longer report an error:

```cs
public class A {
    public class B {}
}

public class C<T> : A {
    // Once we bind this, we just see it as an A.B (and emit it that way)
    // Therefore if we check the type after binding we don't see anything wrong
    public C<string*[]>.B field;
}
```

This code will report an error *today* because `string*` is not legal (pointer to a managed type). However, checking the field type constraints after binding winds up hiding this.

Here's a similar case, but with generic type constraints instead of pointers. This will correctly report an error in 2.9.0, but it won't in `master`: https://sharplab.io/#v2:EYLgtghgzgLgpgJwD4AEDMACFAmDBBAWACgBvYjCrTHDASQDt7EMSBfY9o49LXAIQA8AFQB8GEPgwB3ABaI4GIeIwBXepHoQA5nAAmxMkU7dquAMIHylQSgCMABhEA6BkwQYAZgEs4AG10A3BxAA
