### ISSUE TITLE
VB wpfdpro snippet emits wrong code

### ISSUE THREAD

**Issue by ljw1004** [dotnet/roslyn#3469]
Repro:
(1) File>New>VB>Windows>Desktop>WPF application
(2) open up MainPage.xaml.vb and inside the class type `wpfdpro` and press TAB.

What I get: there are two errors because it's failing to pick up the name of the enclosing type. It emits `GetValue(.Prop1Property)` without the classname in front of the dot. And it emits `GetType()` because without the classname inside parentheses.

Also, stylistically, it should be using NameOf now instead of the string literal `"Prop1"`.

![wpfdpro](https://cloud.githubusercontent.com/assets/3316258/8133149/44b48cf2-10db-11e5-8bca-78b0531ca908.png)

**Comment by AdamSpeight2008** [comment]
@ljw1004  Could you provide an example of how it should look?

**Comment by ljw1004** [comment]
In this case it should look like this:

```vb
    Public ReadOnly Property Prop1 As String
        Get
            Return CType(GetValue(MainWindow.Prop1Property), String)
        End Get
    End Property

    Private Shared ReadOnly Prop1PropertyKey As DependencyPropertyKey =
                            DependencyProperty.RegisterReadOnly("Prop1",
                            GetType(String), GetType(MainWindow),
                            New PropertyMetadata(Nothing))

    Public Shared ReadOnly Prop1Property As DependencyProperty =
                           Prop1PropertyKey.DependencyProperty
```

CHANGES I EXPECT:

(1) Change `GetValue(.Prop1Property)` into either `GetValue(MainWindow.Prop1Property)` or `GetValue(Prop1Property)`. The latter would be nicer.

(2) Change `GetType()` into `GetType(MainWindow)`.

(3) Add the necessary `CStr` or `CType` to the property getter.

**Comment by dpoeschl** [comment]
Some notes:

> It emits GetValue(.Prop1Property) without the classname in front of the dot.

This is because the current authoring has the literal defined as ```ownertype``` but the references are listed as ```ownerType```. This casing difference probably didn't matter in the old VB snippets implementation, but the merged implementation (the same one used by C# pre-VS2015) takes casing into account. 

However, even then, it will just default to Window1 instead of your actual surrounding class, because it wasn't using the ```ClassName()``` snippet function.

> Also, stylistically, it should be using NameOf now instead of the string literal "Prop1".

For things like that, I think we should go through and update all of the existing snippets, rather than just updating individuals as they are noticed.

**Comment by CyrusNajmabadi** [comment]
CLosing out as we are not investing in these legacy snippets.
