### ISSUE TITLE
PVS-Studio: Checking the Roslyn Source Code

### ISSUE THREAD

**Issue by AndreyKarpov** [dotnet/roslyn#34725]
Once in a while we go back to the projects that we have previously checked using PVS-Studio, which results in their descriptions in various articles. Two reasons make these comebacks exciting for us. Firstly, the opportunity to assess the progress of our analyzer. Secondly, monitoring the feedback of the project's authors to our article and the report of errors, which we usually provide them with. Of course, errors can be corrected without our participation. However, it is always nice when our efforts help to make a project better. Roslyn was no exception. The previous article about this project check dates back to December 23, 2015. It's quite a long time, in the view of the progress that our analyzer has made since that time. Since the C# core of the PVS-Studio analyzer is based on Roslyn, it gives us additional interest in this project. As a result, we're as keen as mustard about the code quality of this project. Now let's test it once again and find out some new and interesting issues (but let's hope that nothing significant) that PVS-Studio will be able to find. Link: https://www.viva64.com/en/b/0622/

**Comment by jaredpar** [comment]
@AndreyKarpov is the intent to update this issue with the problems PVS-Studio found as you have done in the past? If so that would be quite welcome. Some of those were quite interesting and we moved to fix them. 

As it stands though this looks like using an Issue to plug a blog post. Probably not appropriate as an issue on our repository.

**Comment by AndreyKarpov** [comment]
Hello, @jaredpar . We check projects in order to demonstrate the benefit that static code analysis methodology can bring. We don't claim that we provide fullness of the analysis and, unfortunately, we don't have enough forces to separately suggest edits for every bug. By this moment we've found more than 10000 [errors](https://www.viva64.com/en/examples/) in open source projects and we don't have the opportunity to make so many pull requests :). I understand that my description of the problem is rather out of place, but I have nothing to do except this. People comment our article: "did you tell developers about found bugs?". I cannot answer these people "No way, let bugs stay at their place!" :).  The best solution is to close this issue and independently check the project more thoroughly using PVS-Studio. We're ready to provide with a temporary license. In addition, we've got several options of [free licensing](https://www.viva64.com/en/b/0614/).

**Comment by jaredpar** [comment]
Blog posts are not issues. They are not a good way to communicate specific product issues, nor are they friendly to the community since the specific concerns are not on GitHub but on your blog. We welcome you to open issues for the top findings in your tool, or open a single issue with a log of those same issues. Otherwise, we’ll close this issue
