### ISSUE TITLE
Regex HighLighting fails with verbatim interpolated string

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#34748]
![image](https://user-images.githubusercontent.com/12449387/55541522-04521d80-567a-11e9-8381-17bfa05690b3.png)

In the image above, when you use $@&quot;  &quot; the syntax highlighting for RegEx stops working. 

Normally it looks like this: 
![image](https://user-images.githubusercontent.com/12449387/55541589-1d5ace80-567a-11e9-9684-bb278f3c4e19.png)

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/503671/regex-highlighting-fails-with-verbatim-interpolate.html

**Comment by jinujoseph** [comment]
cc @CyrusNajmabadi

**Comment by santoshyadav198613** [comment]
Hi @jinujoseph ,

Can i take this up.

**Comment by CyrusNajmabadi** [comment]
This is by design and was called out in the original pr.  The problem is that the 'holes' in the interpolated string would affect how the regex is parsed. I.e. the hole might contain `\`, causing everything to followup to change. We don't know what's in the hole, so we just don't do regex highlighting here.

**Comment by GoldenCrystal** [comment]
I just stumbled on this inconvenience today, and while I understand the highlighting not working in the general case, there is at least one exception where it could be supported safely.

If we have the following code:
````csharp
var someRegex = new Regex($"{Regex.Escape(x)}[0-9]");
````

The call to `Regex.Escape` should make this expression perfectly safe from a regex parser's perspective (it introduces no "holes" in the final regex), however, it will not be colored.

It could theoretically be possible to at least accept coloring interpolated strings when either:
- No interpolated parameters are used (Admittedly, this could be improved very easily by the developer himself)
- All interpolated parameters can be easily traced to calls to `Regex.Escape`, or to constant strings/integers introducing no "holes"

@CyrusNajmabadi Would you agree with such a feature, provided it's possible to implement easily enough ?

**Comment by CyrusNajmabadi** [comment]
I'd have no problem with that.  It feels rather niche.  But if someone wanted to contribute it, that's fine with me.

**Comment by Layarion** [comment]
Actually, `$""` wouldn't be needed as much if .Net Regex supported Pre-Defined subroutines, 

example being: https://www.rexegg.com/regex-disambiguation.html#define
at the "Pre-Defined Subroutines" section.

**Comment by CyrusNajmabadi** [comment]
@Layarion That seems offtopic for this issue.  If you would like .net regex to support this, please raise the issue at dotnet/runtime, thanks.

**Comment by CyrusNajmabadi** [comment]
@ygoe That is not related, but is a different bug in it's own right.  Thank you for bringing htat to our attention!

**Comment by CyrusNajmabadi** [comment]
@ygoe filed https://github.com/dotnet/roslyn/issues/47079 to track that issue.  Thanks!

**Comment by ygoe** [comment]
There's another exception that's probably more common and would help me a lot now: constants. Look at this:

```cs
private const string Time = @"[0-9-]{10} [0-9:]{8}";
private const string QueueId = @"[0-9A-Za-z]{6}-[0-9A-Za-z]{6}-[0-9A-Za-z]{2}";
private static readonly Regex mainLogMessageArrivalRegex = new Regex(
	$@"^({Time}) ({QueueId}) (<=|\(=) (<>|[^ @]+@[^ @]+) (.+?) for(?: ([^ @]+@[^ @]+|""[^""]*""@[^ @]+))+$",
	RegexOptions.Compiled);
```

This defines a regex that parses certain types of log lines of the Exim mail server. These include repeated subpatterns that I'd like to define only once and then include by a more readable name. I see no reason why the syntax parser should be unclear about the complete resulting string. It's probably (hopefully!) already resolved at compile time (didn't check, I'm not sure how compiled regexes really work).

**Comment by CyrusNajmabadi** [comment]
@ygoe see https://github.com/dotnet/roslyn/issues/34748#issuecomment-479933250:

>  The problem is that the 'holes' in the interpolated string would affect how the regex is parsed. I.e. the hole might contain \, causing everything to followup to change. We don't know what's in the hole, so we just don't do regex highlighting here.

>  I see no reason why the syntax parser should be unclear about the complete resulting string. 

First, 'Time' and 'complexity of implementation' are both core reasons here. :)

Second, by doing this we need to actually understand more than just the lexical/syntactic structure of the file.  now we need semantics to go find what the holes bind to.  We also then need to be able ot make our regex-parser restartable at any point.  i.e. if `QueueId` ended with `\` we'd have to consider how that impacted teh outer regex parsing for what comes after it when doing the main parsing.

That all said, i mentioned before:

>  But if someone wanted to contribute it, that's fine with me.

So, if you want to look into a contribution here, it's something i would support.  Note: or the contribution to be accepted, it would have to reign in the complexity so that things did not get out of control

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback and high complexity of design here.
