### ISSUE TITLE
Implement `where T: class` and `where T: struct` for overrides and implementations

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#34798]
See https://github.com/dotnet/csharplang/issues/2378#issuecomment-479634969

The LDM has specified that an override method or an explicit implementation method may specify the `struct` or `class` constraint on type parameters, and that such constraints are checked that they are implied by the constraints on the method being implemented or overridden.

When the `class` constraint is used, a nullable annotation on that type parameter `T?` does not mean `Nullable<T>` but rather it is a nullable reference type.

This needs to be implemented.

**Comment by gafter** [comment]
See also test that are skipped with a skip reason `"https://github.com/dotnet/csharplang/issues/2378#issuecomment-479634969"`.

**Comment by YairHalberstadt** [comment]
I'm happy to finish what I started, and give this a go.

**Comment by YairHalberstadt** [comment]
@gafter
`SourceMethodSymbol` currently has an abstract method `GetTypeParameterConstraintClauses(bool early)`
I think the correct thing to do here is to add another method called `GetDeclaredTypeParameterConstraintClauses()`
This will contain the constraint clauses that are declared directly by an explicit interface implementation or method override, rather than the overridden/implemented method.
Does that make sense?

**Comment by gafter** [comment]
@AlekseyTs What do you think about @YairHalberstadt 's suggestion on how to address this?

**Comment by AlekseyTs** [comment]
I am not sure if we need to add any special API around that. Where we need the information about the presence of constraints, we can "bind" them in a special and very restrictive way. Essentially just recording the fact that ```struct``` or ```class``` constraints are present and reporting errors for anything else, without even attempting to bind type syntax involved, etc. In error recovery situation, when the overriden/implemented method isn't found, we might want to flow that information into the HasReferenceTypeConstraint/HasValueTypeConstraint on the corresponding type parameter symbols in order to suppress cascading diagnostics on ```?``` marks applied to them.

**Comment by YairHalberstadt** [comment]
Now that #34584 is merged, this can be worked on.
I have a branch which is almost complete for this.
I should have a PR ready by tomorrow.

**Comment by AlekseyTs** [comment]
@YairHalberstadt We would like to expedite completion of this work item and, in order to achieve that, we would prefer the work to be done by a member of the compiler team. If you've made significant progress on this work item, consider publishing what you have (in a single commit) and we continue from that point. This way your valuable contribution will be recorded. Thanks!

**Comment by YairHalberstadt** [comment]
@alekseyTS
I'm pretty much done. I'm just finishing off the last few tests. I'll create a WIP PR tonight (English time) if I get a chance, or tomorrow morning otherwise.

**Comment by YairHalberstadt** [comment]
https://github.com/dotnet/roslyn/pull/34989

**Comment by YairHalberstadt** [comment]
Still to do:
Fix broken tests.
_declaredConstraints in SourceOrdinaryMethodSymbol can be a local, not a field.
