### ISSUE TITLE
Error MSB6006

### ISSUE THREAD

**Issue by biqas** [dotnet/roslyn#3487]
Hi,

in one of my project i removed the assembly "Microsoft.CSharp" and later used some futures which requiring this assembly, and when tried to compile I got the error: "MSB6006" without any information's until i guessed that i an assembly is missing.

Hope this will be fixed in a kind of additional error message(s) and also the code editor is highlighting it some where.

**Comment by vaualbus** [comment]
Nope Microsoft.CSharp is present,  also I have done a compltly new install of windows and vs and the error remain. So please somebody help me!

**Comment by gafter** [comment]
MSB6006 is an msbuild error.

**Comment by vaualbus** [comment]
Ya, thanks.
Though If you change the line that cause the error to var script2 = ScriptRepository.Scripts[scriptDataFormAttribute.Value.ScriptName]; 
instead of calling TryGetScriptGameObject function inside the ScriptRepository class, now it compile.
I really cannot get what the problem could be.
Thanks for the help.

**Comment by jaredpar** [comment]
Thanks for taking the time to file this issue.  Resolving as this is an MSBuild error, not a Roslyn issue.  The MSBuild team tracks their issues on the following repo:

> https://github.com/Microsoft/msbuild
