### ISSUE TITLE
Open EmbeddedLanguages for public consumption

### ISSUE THREAD

**Issue by cartermp** [dotnet/roslyn#34979]
I'd like to hook into the Regex language service to support colors and brace matching (and completion if possible). However, all the types and interfaces are marked `internal`, so even though we have IVTs with F#, we can't access these things.

**Comment by YairHalberstadt** [comment]
@cyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
> However, all the types and interfaces are marked internal, so even though we have IVTs with F#, we can't access these things.

if you have IVT, then why can't you access them?

**Comment by cartermp** [comment]
We have access to things marked as `public`, but not `internal` unless we have IVT to that specific thing. For example, we can't access `ISymbolSearchService` because it's `internal` and we don't have an IVT.

**Comment by CyrusNajmabadi** [comment]
Sorry, i didn't understand when you said "so even though we have IVTs with F#, we can't access these things."  It sounded like you have IVT.  

In terms of the regex support.  It would not be hard to expose.  That said, i would like it to bake a bit more.  For example, just a few weeks ago i completely changed one of the core interfaces here for performance reasons.  If this was publicly available, that woudl have been much harder to do.  

If you guys do want to use this, and are willing to be available to make changes as appropriate, then i'm sure something could be made to happen.  Tagging @sharwell since he has lots of ideas on how internals can be shared with other teams without it being as much of a maintenance concern.

**Comment by cartermp** [comment]
If it's not ready to expose, that's totally fine. I'd eventually want to plug into it but not if it's going to undergo a lot of change.

Re: IVTs - we have IVTs to a few things, but not everything. For example, we can access `IClassificationService` despite it being `internal`, but not `ISymbolSearchService`. We'd need an IVT to access the latter, but we don't want to pile onto the IVT problem. EmbeddedLanguages is in a similar boat.

To address the IVT problem, we are moving towards an F# shim that we'll have an IVT to here: #34945

So perhaps the appropriate reference could be made in the shim, but I don't know.

**Comment by CyrusNajmabadi** [comment]
Yes.  I believe this could bedone through shims :)

**Comment by cartermp** [comment]
Great! I'll circle back with @TIHan once the shim is in place to see how we want to extend it moving forward.

**Comment by CyrusNajmabadi** [comment]
@cartermp keep me looped in.  This won't be trivial to support, but i don't htink it will be hard either.  The pieces we'll need are:

1. a way for F# to produce VirtualCharSequences (https://github.com/dotnet/roslyn/blob/master/src/Workspaces/Core/Portable/EmbeddedLanguages/VirtualChars/VirtualCharSequence.cs).  This is how we abstract over a string-literal to figure out the actual characters within.  This is necessary so that we know that `"\\"` is actually a single `\` to the regex engine.
2. You'll then have to create a RegexTree from the virtualchar-sequence.  you can use https://github.com/dotnet/roslyn/blob/master/src/Workspaces/Core/Portable/EmbeddedLanguages/RegularExpressions/RegexParser.cs for that.
3. you'll then have to hook up to your classifier.  The way roslyn does this today is in https://github.com/dotnet/roslyn/blob/master/src/Workspaces/Core/Portable/EmbeddedLanguages/RegularExpressions/LanguageServices/RegexSyntaxClassifier.cs . Unfortunately, this depends on C#/VBisms (like SyntaxTokens).  We could see if we could extract out the portions of this that only deal with the regex-tree and classifying it.  You could then use that from F#.

It's all possible, but it will take some legwork.  I'm happy to assist here :)

**Comment by cartermp** [comment]
@CyrusNajmabadi  the F# shims are now in and we're no longer poking into 80+ different places 🙂 

We could definitely make a change to expose this in a safer way now, but since you had mentioned wanting to make more changes, would it be better for us to hold off on that?

**Comment by CyrusNajmabadi** [comment]
@cartermp Nope!  I made the changes i wanted to make.  So it would def be possible for you to start plugging into this now.  I'm happy to help walk you through how this would be done.

Note: it's *likely* you'll run into some issue where assume something specific to VB/C#.  But it should be minor and we should be able to refactor to remove that assumption.
