### ISSUE TITLE
Collapse section hotkey collapses entire region if method signature has newlines

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#35000]
VSF_TYPE_MARKDOWNUsing the &quot;Ctrl+M, M&quot; Hotkey, if the caret is on method Foo it will correctly collapse the selection. But with the caret on method Bar it will collapse the entire region.
```
# region MyRegion
public void Foo(int param1, int param2) 
{
    string foo = &quot;foo&quot;;
}

public void Bar(
    int param1,
    int param2)
{
    string bar = &quot;bar&quot;;
} 

#endregion
```

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/532398/collapse-section-hotkey-collapses-entire-region-if.html
VSTS ticketId: 847516_
_These are the original issue comments:_

Visual Studio Feedback System on 4/15/2019, 02:44 AM (15 hours ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment]
This is because the region for the methods starts on the close-paren and goes to the end of the method.  So when on 'Bar', the innermost region found is the `#region` region.  This is entirely controlled by the editor/platform afaict.  So leaving to @olegtk  to reroute and decide if they want to do anything here about this behavior. (given only one user ask, i'm guessing no).
