### ISSUE TITLE
"Replace method with property" replaces non-invoked method with property

### ISSUE THREAD

**Issue by vatsalyaagrawal** [dotnet/roslyn#35002]
16.0.1

Original code:

```
delegate int Mdelegate();

class C
{
    int GetP() => 0;

    void M()
    {
        Mdelegate del = new Mdelegate(GetP);
    }
}
```

Use Replace 'GetP' with property refactoring.

Refactored Code:

```
delegate int Mdelegate();

class C
{
    int P => 0;

    void M()
    {
        Mdelegate del = new Mdelegate(P);
    }
}
```

Note that refactored code will not compile as a property can not be used in place of a method in the delegate.

**Comment by CyrusNajmabadi** [comment]
Yes.  This is by design.  You asked us to replace the method with a property.  We did the best we could here, you'll have to fixup any remaining problems.  

Note: i even wrote the feature to detect this and give a message in the preview to this effect:

![image](https://user-images.githubusercontent.com/4564579/56186590-bec81580-5fd4-11e9-92c5-fe68b34363be.png)
