### ISSUE TITLE
Cross assembly analysis support

### ISSUE THREAD

**Issue by xmarshal** [dotnet/roslyn#35104]
its important for null check helpers for example 
https://github.com/dotnet/roslyn-analyzers/issues/2215

**Comment by vatsalyaagrawal** [comment]
@mavasani is this a duplicate?

**Comment by mavasani** [comment]
No, this is not a duplicate. This is a request to allow whole program analysis in Roslyn, where a method invokes methods from different projects and/or reference assemblies. Our current analysis support in analyzers is limited to the same compilation.

**Comment by JeffStong** [comment]
I definitely would upvote this request.  We have a code with many assemblies and the classes make use of a helper class to validate arguments.  The current behavior of the analyzer means that we can't enable this rule to find the places we need to add the argument validation because of the large number of false positives.

**Comment by ggreig** [comment]
Another upvote from me, for exactly the same reasons as @JeffStong. The old, pre-Roslyn FxCop was perfectly happy with an argument checker implemented in another assembly - as we switch to the Roslyn analyzers, we're finding that we unwillingly have to disable a really useful rule because Roslyn can't do that cross assembly analysis.

**Comment by mavasani** [comment]
See documentation for the option: https://github.com/dotnet/roslyn-analyzers/blob/master/docs/Analyzer%20Configuration.md#null-check-validation-methods
