### ISSUE TITLE
New refactoring: Make local function static

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#35135]
This refactoring would add the `static` modifier to a local function, and automatically add parameters to the local function for each item previously captured by the function.

**Comment by genlu** [comment]
Assigned to @lavanyaguru

**Comment by lavanyaguru** [comment]
Feature is in the works

**Comment by lavanyaguru** [comment]
### Current Situation
As of now, local functions using local variables are not suggested to use static, but the refactoring would be triggered when the use of a local function is detected. 


With the addition of the static modifier being suggested, the refactoring would also capture the use of any local variables and pass them as parameters and arguments for the method declaration and method call respectively. 


<img width="257" alt="Old" src="https://user-images.githubusercontent.com/20705008/60553432-29d9dc00-9ce8-11e9-9e58-e45a64953ac0.png">

Current Situation: using the  static  modifier isn't suggested since it would cause an error and hinder the use of the variables of firstName and lastName in this scenario


### Refactoring Plan
The user is given a suggestion of adding static and the suggestion would include the parameters being passed. The preview would show the parameters being passed in

1. <img width="291" alt="Capture1 (2)" src="https://user-images.githubusercontent.com/20705008/60621553-d40e3e00-9d92-11e9-8a93-7bfbafc81d62.PNG">

2. <img width="305" alt="Capture2 (2)" src="https://user-images.githubusercontent.com/20705008/60621483-a0cbaf00-9d92-11e9-979b-e4d96174c9f7.PNG">




### After Refactoring 

<img width="356" alt="NewRefactoring" src="https://user-images.githubusercontent.com/20705008/60621614-f43dfd00-9d92-11e9-90a1-44fc2d93a2c3.png">
After the Refactoring: The static  modifier is added while the local variables are passed in as arguments and parameters

**Comment by CyrusNajmabadi** [comment]
Note: we should detect and give a warning/error annotation in the code if this would break things (i.e. because the local function is now passed to something and the signature is no longer compatible).
