### ISSUE TITLE
pre-selection should favor in-scope symbols

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn#35163]
From [feedback](https://github.com/dotnet/roslyn/issues/7053#issuecomment-484907098)

> For some reason it tends to pre-select import completions over regular ones.
>
>![image](https://user-images.githubusercontent.com/788783/56449194-262edf80-62cb-11e9-9115-7fd6026db92c.png)

It seems the reason unimport one is favored in this case is because it's considered a better match based on current algorithm (which takes suffix "<>" in to account as well)

**Comment by 333fred** [comment]
I've hit this a lot working with the roslyn APIs, especially in unit tests in the compiler layer where there are 4 different `InvocationExpressionSyntax` classes in differing namespaces.

**Comment by AmadeusW** [comment]
I've also ran into this issue. I'd like the local `LastReturnedResults` to be selected:
![image](https://user-images.githubusercontent.com/1673956/60299072-b0557e80-98e0-11e9-821f-a0e9160f0615.png)

**Comment by genlu** [comment]
feedback from @AmadeusW 

> I would always favor the exact match. In my case, I would like the imperfect match of local variables to be favored over imperfect match of external items.

**Comment by CyrusNajmabadi** [comment]
> however, we have two imperfect matches. One of them is a substring match, and another is a camel case match. I would like locally available variables to have priority over external items who also have imperfect match kind.

say i have a prefix match with an existing symbol, and an exact match with an import-symbol, which should win?

The 'exact match' seems better (it's exact after all), but a user could have easily just wanted to write a quick prefix that would normally hit the existing symbol.

I think we shoudl basically *always* defer to non-import matches.  Because that's the behavior the user would have gotten prior to import-matches being an option.  So import matches (similar to extension methods for the compiler) are always 'second tier' results.  They're to solve a problem if no existing symbols solve the problem.  This also forces users to be more explicit about selecting them, indicating awareness and acceptance of the addition of the import.

**Comment by AmadeusW** [comment]
> I think we shoudl basically always defer to non-import matches

I like the predictability of this approach. 
After all, user can use arrow keys to select desired item, or keep typing until local variable gets filtered out.
