### ISSUE TITLE
Nullable reference types + Anonymous objects ... a couple rough edges

### ISSUE THREAD

**Issue by joshlang** [dotnet/roslyn#35168]
Check this out:

    string x = "";

    // This creates no warnings, but intellisense shows "a" as type "string?"
    x = new { a = "x" }.a;

    // This creates a warning
    x = new[] { new { a = "x" } }[0].a;

    // This creates a warning (the cast doesn't work)
    x = new[] { new { a = (string)"x" } }[0].a;

There's a few similar open issues, but I'm not expert enough to know if there's a complete overlap.  If so, sorry :)

This does seem to be a bug since the docs say the nullability of the arguments are inferred from the initializing expression:  https://github.com/dotnet/roslyn/blob/master/docs/features/nullable-reference-types.md#anonymous-types

I came across this when accessing properties downline from a Select projection in a LINQ expression.

**Comment by jcouv** [comment]
This was fixed by implementation of nullability analysis of anonymous types (https://github.com/dotnet/roslyn/pull/33562)

I'm not sure which release the fix went in, but I verified that it doesn't [repro](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxASwDZICYgNQA+AAgAwAERAjANwCwAUAMQB2ArhhhMBnGXM1x4MGRAMwUATGQDCZAN4MySiuKIAWMgFkAFAEp5i5UarkAHmQC8ZAETW69BgHpHZACoALNFDIBjBHAh4b2YAezIAdwgEZjRmAHMoJDJgVhgyWPgOL34oXih3EPDvawhrMmgyGABPAAdeaxMAfmsGcytmOHD5cssbUzKAXwA6CHsnFw8vX39AuG8ICKiY+NbejvCAbQBdbvXuhatrfrIBk42SLZGx+mc3T28/AKCeyOjYuLJtGHdeH2g07AhObMADkaXCIQQAGtdKt2p1trtOvtetoTLojoMzhcroYlAMGAMgA==) with current bits.

**Comment by jcouv** [comment]
I'll go ahead and close this issue since this was fixed already. Thanks
