### ISSUE TITLE
Naming of naming styles should reflect their casing

### ISSUE THREAD

**Issue by terrajobst** [dotnet/roslyn#35243]
**Version Used**: 

Microsoft Visual Studio Enterprise 2019 Int Preview
Version 16.1.0 Preview 3.0 [28823.117.d16.1]
VisualStudio.16.IntPreview/16.1.0-pre.3.0+28823.117.d16.1
Microsoft .NET Framework
Version 4.8.03752

**Steps to Reproduce**:

1. Ctrl Q
2. Type 'C# naming'
3. Enter
4. Open the drop down "Required Style" for any entry

**Expected Behavior**:

Finding the following entries:

* `PascalCase`
* `camelCase`

**Actual Behavior**:

These entries:

* `Pascal Case`
* `Camel Case`

[Was raised here](https://twitter.com/gotheap/status/1121118929097637888).

**Comment by mkrtich-m** [comment]
Will there be support for `snake_case` ?

**Comment by terrajobst** [comment]
> Will there be support for `snake_case` ?

I think this might violate good taste :-)

**Comment by benaadams** [comment]
Alas `kebab-case` isn't valid C#

**Comment by mkrtich-m** [comment]
> > Will there be support for `snake_case` ?
> 
> I think this might violate good taste :-)

To be honest lot of public APIs are using `snake_case` in their JSON objects and it's much easier to maintain C# POCO in `snake_case` for those APIs.

**Comment by terrajobst** [comment]
That's fair, although I'd rather configure a JSON.NET casing strategy than making my C# POCOs look weird.

Hypothetically, if you had that casing option, how would you configure the system thought? There are no namespace / attribute filters. Presumably, you don't want to apply this convention everywhere.

**Comment by mkrtich-m** [comment]
I was thinking that naming can be tied to particular project. Not sure though if it's possible at the moment.
Anyway I was able to create custom `snake_case` :)

![image](https://user-images.githubusercontent.com/4062518/56689555-5c90a400-66a9-11e9-83e2-3f569edb68b4.png)

**Comment by poke** [comment]
Alternative to the original suggestion, I think adding an example after the name would also work very well:

- “Pascal case (`HttpClient`)”
- “Camel case (`httpClient`)”

This would probably be a bit more in line with the other option there.

**Comment by mkrtich-m** [comment]
The main dropdown called `Capitalization` which is responsible for styling already has correct styling or its values. The issue is with the titles of default naming styles which come with Visual Studio installation.

![image](https://user-images.githubusercontent.com/4062518/56690067-957d4880-66aa-11e9-9855-db4182896986.png)

**Comment by poke** [comment]
Mentioning that drop down, it does appear a bit inconsistent that the first two options refer to the general style names (pascal case and camel case), while the lower three options are descriptions of what they do.

We could have the first two be “All words capitalized” and “All words except first capitalized” respectively to match with the others; although I do think that it is useful to keep the pascal/camel case in there somewhere (maybe in parentheses). Or we come up with names for the other three (the name for the third is actually “Title case”).

That being said, the third option should actually be ”First word capitalized” instead of “First word upper”, otherwise it should probably be `HTTPclient` or `SERVICEprovider`.

**Comment by terrajobst** [comment]
Looks like this was addressed at some point: 

![image](https://user-images.githubusercontent.com/5169960/117941056-9350ab80-b2be-11eb-8d86-4243d981e9bf.png)
