### ISSUE TITLE
Various non-deterministic empty symbol compiler errors

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/roslyn#35290]
1. error CS0648: '' is a type not supported by the language
https://github.com/dotnet/corefx/pull/37141#issuecomment-486340227

2. error CS4001: Cannot await ''
https://dnceng.visualstudio.com/internal/_build/results?buildId=170149&view=logs&jobId=7b614801-ed38-51b7-97d8-b2f3e799aa24&taskId=82d75caa-41ea-59a8-35f3-0486fa4f1cf4&lineStart=1551&lineEnd=1552&colStart=1&colEnd=1

3. System\Collections\Immutable\ImmutableDictionary_2.cs(785,52): error CS1503: Argument 1: cannot convert from '' to 'object' [F:\workspace\_work\1\s\src\System.Collections.Immutable\src\System.Collections.Immutable.csproj]
https://dnceng.visualstudio.com/internal/_build/results?buildId=163632

4. BasicEventSourceTest/Harness/Listeners.cs(285,43): error CS0023: Operator '?' cannot be applied to operand of type ''
https://dnceng.visualstudio.com/internal/_build/results?buildId=166101

Talked with @stephentoub and his guess is that this could be a threading related compiler bug.

Happens with `Microsoft.Net.Compilers.Toolset` 3.1.0-beta3-19217-05.

**Comment by sandreenko** [comment]
I saw this error in CoreCLR ci: [link](https://dev.azure.com/dnceng/public/_build/results?buildId=171047)->Test Pri1 Linux x64 checked Job->Build tests->scroll down:
[RoundCurrentDirectionScalar.Double.cs(217,26): error CS1503: Argument 1: cannot convert from '' to 'void*' [/__w/1/s/tests/src/JIT/HardwareIntrinsics/X86/Sse41/Sse41_ro.csproj]](url)

The test last update was 24 days ago and it has not failed before, so this is some flakiness.

**Comment by davidsh** [comment]
I was an error during my PR: https://github.com/dotnet/corefx/pull/37238
https://dev.azure.com/dnceng/public/_build/results?buildId=171147
![image](https://user-images.githubusercontent.com/7684835/56843495-73282e00-6856-11e9-88a0-b3784752125e.png)

**Comment by stephentoub** [comment]
@jaredpar, @agocke, @jcouv, any idea what's going on here? This just recently started plaguing corefx.

**Comment by jcouv** [comment]
Some basic observations:
The various diagnostics have one thing in common: they are reporting empty type names. 
The code in this last error is `var set = new HashSet<Color>(ColorTable.Colors.Values);` ([ColorConverter.cs](https://github.com/dotnet/corefx/blob/master/src/System.ComponentModel.TypeConverter/src/System/Drawing/ColorConverter.cs)) and here is [ColorTable.cs](https://github.com/dotnet/corefx/blob/master/src/Common/src/System/Drawing/ColorTable.cs).

Some ideas so far in terms of investigating:
- do we have some idea of the faulty version range? I'm wondering if this is a new compiler issue (which MacOS somehow hits more often) or whether some timing changes in MacOS revealed a longstanding compiler issue.
- let's try to setup a non-CI repro and get a sense of frequency. That'll help to determine how to investigate, and will tell us if we can narrow the faulty version range with a delta search.
- we could make a version of the compiler that saves a stack trace or crash dump when an error diagnostic is produced.

**Comment by jaredpar** [comment]
Do we have a binary log of any of the failures? That would help differentiate if the compiler is giving different output for same input or if there is a tool further up the chain which is giving us different input

**Comment by ViktorHofer** [comment]
Yes, please find the binary logs in the results tab of each build. Just make sure to pick the right leg.

**Comment by jaredpar** [comment]
@ViktorHofer 

Looked into these and here are my findings:

1. The binary logs are available but they don't capture the build error. Made sure to have attempt set to 1 but the binary file has a successful compilation for attempt 1. Wonder if they just have only logs from the latest attempt which is why I can't see the error here. Buidl error by itself isn't enough to make progress here. 
2. The binary log captures the error here and it's fairly straight forward. Oddly the same code which fails to compile at line 20 basically exists at line 35 as well. Hence one fails, one succeeds. Very odd. This does suggest some sort of race in the compiler. 
3. Similar to 2 above. Hitting a bad type, attempting to output `node.Display` and getting an empty string. 
4. FYI this is RedHat not MacOS. The binary log also indicates that compilation succeeded here ... The binary log captures stdout from the compiler and the error is not present in the log file. 

These findings are ... weird. I'm not really sure what is going on here in 1 and 4. Definitely seeing output that is from the compiler suggesting there is an error but it's not showing up in our binary logs. That doesn't make sense unless there are other compilations going on here that don't end up in the log file (unlikeyly). Also the compiler only writes to the console in one place and it's the same place as other stdout that is in the log.  @tannergooding 

As for 2 and 3 it's the same pattern of an error with an empty string. 2 can be tracked down to a single in our source code: https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Portable/Binder/Binder_Await.cs#L272

Appears that we're binding `null` for `BoundExpression.Type` but failing to emit an error as to why.

**Comment by stephentoub** [comment]
FYI, just happened again here:
https://dev.azure.com/dnceng/public/_build/results?buildId=172881&view=logs&jobId=2d8d410d-ec68-5b66-b034-32972d3a2938
```
ExistsTests.cs(15,50): error CS0648: '' is a type not supported by the language [/__w/1/s/src/System.Diagnostics.Contracts/tests/System.Diagnostics.Contracts.Tests.csproj]
```
This was on Linux.

**Comment by jcouv** [comment]
Thinking about this over the weekend, there is one area that changed in Roslyn 3.0 and feels suspicious in light of this issue. 

Considering an example: before Roslyn 3.0, a `FieldSymbol` used to have a `TypeSymbol lazyType` field (with `TypeSymbol` being a reference type). We would do:
```C#
if ((object)lazyType != null) { return lazyType; } 
... compute the type
Interlocked.CompareExchange(ref lazyType, computedType, null);
return lazyType;
```

With the introduction of nullability annotations, this pattern changed. `FieldSymbol` now has a `TypeWithAnnotation.Builder lazyType` (that's a struct) ([source](https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberFieldSymbol.cs#L405)). We use the following initialization pattern:
```C#
if (!lazyType.IsDefault) { return lazyType; }
... compute the type
lazyType.InterlockedInitialize(computedType));
return lazyType;
```

Here's the [logic](https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Portable/Symbols/TypeWithAnnotations.cs#L38) for `TypeWithAnnotation.Builder.IsDefault` and `InterlockedInitialize`.
@jaredpar and @agocke confirmed this is suspicious and that we're probably doing our struct initialization wrong, but we've not exactly nailed how this new initialization pattern could cause your symptoms.

@stephentoub Could you take a look and let us know what you think?

**Comment by stephentoub** [comment]
> Could you take a look and let us know what you think?

It's definitely suspicious.  I don't know the codebase, but I just browsed around a little.  Notice that in InterlockedInitialize, _nullableAnnotation is being set prior to the interlockeds and prior to _defaultType being set.  Further. IsDefault will then start returning false if _nullableAnnotation was set to non-zero, and that'll happen prior to _defaultType being set.  Then code like:
http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/Symbols/Metadata/PE/PEFieldSymbol.cs,206
(just the first caller I looked at) appears to be using IsDefault to determine whether to perform initialization, but you could have a race condition here where one thread sets _nullableAnnotation, another thread then sees IsDefault as false, but the original thread hasn't yet initialized _defaultType.  Then the caller proceeds to do:
http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/Symbols/TypeWithAnnotations.cs,65
sees IsDefault is false, and reads _defaultType, even though it may not have been initialized yet.

I don't know if that's the issue or a pattern of the issue or completely unrelated, but it doesn't look right to my eyes.

**Comment by ViktorHofer** [comment]
> FYI this is RedHat not MacOS

Right the title was misleading, this is not MacOS/RedHat specific.
