### ISSUE TITLE
brace matching wrong

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#35346]
brace matching is not always working correctly.
if I click next to the opening brace it highlights the correct closing one.
If I click on the closing brace, it might highlight a wrong opening one. I get that behaviour if I click in between two adjacent closing brackets

for example, I get the wrong opening brace highlighted if I click between the two closing braces
b(())

or between the )) here:
os.path.join(os.path.dirname(os.path.abspath(__file__)),'dsp')

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/331171/brace-matching-wrong.html
VSTS ticketId: 679504_
_These are the original issue comments:_

Ariel Yang - MSFT [MSFT] on 9/10/2018, 02:43 AM (231 days ago): <p>Thanks for taking the time to report this issue to us. We’ve created a bug for this issue as internal tracking. The status on this Developer Community item will be updated as that bug is resolved. Thanks again for your feedback.</p><p><strong></strong><u></u><sub></sub><sup></sup></p>

_These are the original issue solutions:_
(no solutions)

**Comment by jinujoseph** [comment]
Notes from @chborl 
I couldn't repro this issue by placing a zero width caret in various places on the line of code, but I did see it when selecting a brace character.

If you select a single brace character either from the beginning to the end of the character's span, or from the end to the beginning (basically selecting it backwards) you get a different matching brace highlighted.  This is because the active brace used for brace matching is determined by the caret position.

I propose having brace matching behave differently if a single brace character is selected by using the end of the span instead of the caret position.  

In cases where no characters or multiple characters are selected, continue to use the caret position.

**Comment by CyrusNajmabadi** [comment]
> I propose having brace matching behave differently if a single brace character is selected by using the end of the span instead of the caret position.

It should probably not use the start/end, but just use that character.  i.e. if i select a `(` in some large expression, then we would want ot use the *start* of that guy.  But if you select `)` then we shoudl use the end.
