### ISSUE TITLE
Intellisense for the Is pattern match

### ISSUE THREAD

**Issue by xwlantian** [dotnet/roslyn#35387]
Using `is` pattern matching expression is a convenient way to check not null and define a new local variable:
```csharp
List<int> list = new List<int>();
if (list is List<int> notnullList)
{

}
```
It would be nice if there is a intellisense for the type `List<int>` after typing the space after `is` since the type of the variable `list` is already known. In the case of left side of `is` is a expression, the intellisense could be even more helpful to infer the return type of the expression.

**Comment by CyrusNajmabadi** [comment]
> Using is pattern matching expression is a convenient way to check not null and define a new local variable:

it's much nicer and simpler to just write that as:

```c#
var list = ...
if (list is {} notNullList)
```

Now you can do the null check without having to repeat the type name redundantly.

I bring this up because my expectation is that the vast majority of cases, the type after the 'is' will not be the type of the expression, it will be some other subtype/interface.  And for the one case you wrote, the recommendation woudl be to not use that pattern either in the future but instead use the more simple and idiomatic `is {} foo` form.

**Comment by xwlantian** [comment]
Thanks, I didn't know `{}` expression and it looks like only in vs2019. Since `is` doesn't have any intellisense right now, maybe `{}` or the left expression type can be a good candidate for that.

**Comment by CyrusNajmabadi** [comment]
Closing out.  The current behavior is desirable.  We would want to encourage usages of `{}` (or `not null` once available) versus having the user have to specify the full type again.
