### ISSUE TITLE
The Deconstruct method should optionally return Boolean

### ISSUE THREAD

**Issue by igor-tkachev** [dotnet/roslyn#35458]
Fir example:

```c#
public static bool Deconstruct<T>(this T[] arr, out T item0, out T item1)
{
    if (arr.Length != 2)
    {
        item0 = item1 = default; // ref parameters would be useful here, no need to initialize out parameters
        return false;
    }

    item0 = arr[0];
    item1 = arr[1];

    return true;
}
```

Actually, it can be more then just Boolean. It be can some IDeconstructionResult, but at least Boolean can be really useful.

**Comment by CyrusNajmabadi** [comment]
This is what's know as an [active pattern](https://github.com/dotnet/csharplang/issues/277).  It's already been proposed and closed.

**Comment by jcouv** [comment]
Please bring this discussion to the csharplang repro, where language changes are discussed (as opposed to implementation bugs of the compiler with regards to the current language design).
I'll go ahead and close this issue.

Tagging @gafter as FYI, since he's the driver for various patterns features.

**Comment by igor-tkachev** [comment]
Ok
