### ISSUE TITLE
Local functions has problem with callie resolving

### ISSUE THREAD

**Issue by JiriCepelkaFirstLineSoftware** [dotnet/roslyn#35490]
Using VS ’17 E I got badly resolved callee from withing local function if local function has same name as method called.

1. [Image](http://software919.sweb.cz/Local%20Method%20Error.png)
2. Example

    void MethodX()
    {
      void WriteData() { WriteData(3); }
    }
    void WriteData(int number)  {   }

**Comment by svick** [comment]
I believe this is the expected behavior. The local function here behaves similarly to a local variable, in that it shadows members with the same name from the outer scope. There is no overload resolution in that case: the compiler finds a local function with the right name and stops there.

Unfortunately, there is currently no spec for C# 7.0, but you can look at the history: [These meeting notes](https://github.com/dotnet/csharplang/blob/e7ef269/meetings/2015/LDM-2015-05-20.md#scope-and-overloading) describe that local functions should behave like local variables. [The final  proposal](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-7.0/local-functions) changes that a bit, but it does not change the shadowing behavior.

If you're looking for a workaround, [you can use `this.WriteData(3);` to call the outer method](https://sharplab.io/#v2:C4LgbgpgTglgZgTwDQBMQGoA+ABATAAgGEBYAKAG8z9r9sAWfAWQmAAsB7FADQAoBKKjUqka+AJD18AdVjAIAEQCGwRf3zl8bGAGcAdDJhylKngGY+AbnwBfQdVsiad2gwNHlqmADtg+LwFcAWwAjaD51GzJrIA=).

**Comment by JiriCepelkaFirstLineSoftware** [comment]
Aha, I got it. Great. I didn’t know about this spec. Thank you for info. I am closing the issue.
