### ISSUE TITLE
'Is' operator casts Int32 to null within constructor of generic type

### ISSUE THREAD

**Issue by ojhall** [dotnet/roslyn#35584]
**Version Used**: Unsure - let me know how to determine, or if you need further information. Using VS2019 Enterprise, targeting .NET Framework 4.6.1, LangVersion 7.3, Microsoft.Net.Compilers 3.0.0.

**Steps to Reproduce**:

```
[Test]
public void UnexpectedlyCastToNull_ViaIsOperator_WhenGeneric()
{
    var nonGenericfoo = new NonGenericFoo(0);  // no problem

    var genericFoo = new GenericFoo<int>(0); // Kaboom exception thrown
}

private class NonGenericFoo
{
    public NonGenericFoo(int value)
    {
        if (value is object obj && obj == null)
        {
            throw new Exception("Kaboom!");
        }
    }
}

private class GenericFoo<T>
{
    public GenericFoo(T value)
    {
        if (value is object obj && obj == null)
        {
            throw new Exception("Kaboom!");
        }
    }
}
```

**Expected Behavior**:

I believe that if the expression `value is object obj` evaluates to `true`, then `obj` should be a non-null object. As such, the subsequent `obj == null` expression in the `GenericFoo` constructor should evaluate to false, and not throw the exception.

**Actual Behavior**:

The `is` operator in the `GenericFoo` constructor casts `value` to a null object, which then throws the "Kaboom!" exception.

Also relevant: if the value `1` is passed into the constructor instead of `0`, the test passes without any exception being thrown.

**Comment by mazhou-msft** [comment]
Looks like an interesting bug.

```c#
void M<T>(T value)
{
    if (value is object o && o == null)
    {
        Console.WriteLine("value is null. {0}", value);
    }
    else
    {
        Console.WriteLine("Value is not null. {0}", value);
    }
}
```
If you test the following:

```c#
M(0)
M(1)
M(false)
M(true)
```

You get:
```
Value is null. 0
Value is not null. 1
Value is null. False
Value is not null. True
```

**Comment by svick** [comment]
I looks like this is a regression caused by generating incorrect IL.

The relevant part of [IL for the working case (2.9.0)](https://sharplab.io/#v2:C4LglgNgPgAgDAAhgRgNwFgBQWYCYEDiApgHZEBOYAxgGID2dAPACoB8WA3lgj0gMyFSFavToAKZggBuAQwgBXIgEpuvLpl6aEYAGYIxshUW0BnBHQBGAKyJVg56wgBkTh1YQBeDwhLyIEFQ0tHnVg4OAAC3I6AHcfIjiAUQAPKiIAB2AwOhIxACIAaRkLBgBbAEI8pQwg4IBfVR4GzDqgA=) is:

```il
.locals init (
    [0] object
)

IL_0006: ldarg.1
IL_0007: box !T
IL_000c: dup
IL_000d: stloc.0
IL_000e: brfalse.s IL_001e

IL_0010: ldloc.0
IL_0011: brtrue.s IL_001e

IL_0013: ldstr "Kaboom!"
IL_0018: newobj instance void [mscorlib]System.Exception::.ctor(string)
IL_001d: throw
```

For [the non working case (master)](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxASwDYB8ACAGAAhwEYBuAWACgqcAmAgcTgDtE0BjAMQHtuAeACoA+KgG8qBSUQDMjFmy68AFAIIA3CBgCucAJQSp4ylJME0AMwJKN2uGagFuwAFZx2MRy4IAyb5+cEALyBBMxaGBj6xqaSRjExMAAWCNwA7qFw6QCiAB7scAAOMGjczEoARADSEMC8YACE5boU0TEAvgaSHZRtQA==), it's:

```il
.locals init (
    [0] object
)

IL_0006: ldarg.1
IL_0007: box !T
IL_000c: brfalse.s IL_001e

IL_000e: ldarg.1
IL_000f: stloc.0
IL_0010: ldloc.0
IL_0011: brtrue.s IL_001e

IL_0013: ldstr "Kaboom!"
IL_0018: newobj instance void [mscorlib]System.Exception::.ctor(string)
IL_001d: throw
```

Notice how this is saving a value of type `T` directly to a variable of type `object`, which is not verifiable:

> [GenericFoo`1[T]::.ctor][offset 0x0000000F][found (unboxed) 'T'][expected ref 'System.Object'] Unexpected type on the stack.
