### ISSUE TITLE
WithAttributeList() adds attributes before documentation comment trivia

### ISSUE THREAD

**Issue by WenningQiu** [dotnet/roslyn#35707]
**Version Used**: 
Microsoft.CodeAnalysis.FxCopAnalyzers 2.9.1. 2.9.2 may have the same issue.

**Steps to Reproduce**:

1. Find a  FieldDeclarationSyntax, PropertyDeclatationSyntax, or TypeDeclarationSyntax node that has no attribute but has documentation comment.
2. Call WithAttributeList() to add attributes

**Expected Behavior**:
New attributes appears after the documentation comment.

**Actual Behavior**:
New attributes are added before the documentation comment trivia and results in compile error. WithAttributeList() works fine when the node already has attributes after documentation comment in which case new attributes are added right by the existing attributes.

Developers have to take steps to position new attributes:

https://codereview.stackexchange.com/questions/145231/adding-an-attribute-to-a-class-after-the-documentation-comment-trivia

**Comment by CyrusNajmabadi** [comment]
This would be by-design.  These methods are very specifically and intentionally designed to do no interpretation and to just do exactly what was asked for.  

To deal with thsi sort of thing, use `SyntaxGenerator.WithAttributeLists`.  SyntaxGenerator (unlike SyntaxFactory, or the raw SyntaxNode methods), does try to add heuristics and smarts to better match your intuition on how things should behave.

@jcouv for confirmation/closing.

**Comment by CyrusNajmabadi** [comment]
Also, this behavior (which is definitely intentional) could not be changed due to the massive break.  

--

History: prior to roslyn we had our own internal API for doing syntax/compiler stuff.  We tried to bake these tyeps of smarts into it.  It turned out to be a big mistake as it meant no one had any idea what behavior any particular method would have.  We also would try to change things, but that would break a swath of consumres that then had to workaround this change in behavior that they might not want.

When we did Roslyn we designed the syntax-model would be based on completely consistent invariants and behavior.  So, for example, every "WithXXX" method behaves the same.  It means to exactly *and only* take that existing node and swap in the subnode as appropriate.  It doesn't touch any other parts of the node, leaving that entirely up to the caller to handle.

**Comment by sharwell** [comment]
Yes, @CyrusNajmabadi is correct here. Trivia manipulation in scenarios like this is manual when using the low-level factory APIs, or you can use a higher level API like `SyntaxGenerator` which does more automatic manipulation but loses some control over the exact form of the final output.
