### ISSUE TITLE
IDE0051 on private json constructors

### ISSUE THREAD

**Issue by JranZu** [dotnet/roslyn#35767]
After moving to VS 2019 I started seeing IDE0051 showing up on all of my private JSON constructors.  This should not be shown or there should be an easy way to disable this.

**Comment by mavasani** [comment]
This is by design. If there is no use of the constructor in source code, IDE0051 will fire. You have following choices:
1. Add pragma suppressions or suppress message attribute suppressions
2. Disable IDE0051 for your project or solution using ruleset files
3. Author a diagnostic suppressor to programmatically suppress IDE0051 on private json constructors. See https://github.com/dotnet/roslyn/pull/36067
