### ISSUE TITLE
NullContextOptions weird out when using nullable reference type and value tuple deconstruction

### ISSUE THREAD

**Issue by pranavkm** [dotnet/roslyn#35801]
Consider:

```C#
static void Main(string[] args)
{
    foreach (var (a, b) in GetCollection())
    {
        Console.WriteLine(a);
    }
}

static ICollection<(int a, string? b)> GetCollection()
{
    return new[]
    {
        (1, "A"),
        (2, null),
    };
}
```

This results in the compiler complaining about the nullability at the site of deconstruction:

![image](https://user-images.githubusercontent.com/174281/57974769-69d04400-7972-11e9-907a-20bf9c1bc911.png)

Reproduced using `SDK v3.0.100-preview6-011875`

**Comment by Pzixel** [comment]
Same here. But since I'm using treat warning as errors it's a hard blocker to me.

Any progress on that?

**Comment by jcouv** [comment]
This scenario no longer produces warnings ([sharplab](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxASwDYB8ACAGAAhwEYAWAbgFgAoHAJmJpoGIA7AVwwwmAzgLisefGvQIBhGgG9RxAGxFSBALIQ0rABQk8AbQC6BCAgDmUAJTSaBawQBmAewRwIAYwAWBDQDcjniEgJgMwJ1AgBxOBhxey44Fxg0e00zC2obAhk09JsSAE4NCDMqLOsAXxpy6lkFAElo2PjE1gAeDXUYQwDtAH5AswA+cMj6vkakjVTM9JwAdgJWOAB3fSsbKezrDWIAgCIAQR2zJFWNjToAji4jk4JS4srSoA=)).
I think this was fixed by https://github.com/dotnet/roslyn/pull/35445

I'll go ahead and close. Thanks
