### ISSUE TITLE
Class name namespace error

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#35893]
Class name is considering as namespace

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/490101/class-name-namespace-error.html
VSTS ticketId: 820709_
_These are the original issue comments:_

Visual Studio Feedback System on 3/15/2019, 00:26 AM (68 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by vatsalyaagrawal** [comment]
Reproducible in 15.9.12

Repro:
namespace Mini.Models
{
    public class Auto
    {
        // code and stuff
    }
}

namespace Mini.Models
{
    public class Airplane
    {
        // code and stuff
    }
}

namespace Mini.Auto
{
    public class OtherAirplane
    {
        // code and stuff
    }
}

namespace Mini
{
    using Mini.Models;
    using namespaceAuto = Auto ;

    class NamespaceIssue
    {
        void execute()
        {
            var autoObject = new Auto();   // notice how it references Models folder
            var planeObject = new Airplane();  // Same folder but not referencing Models in front of it      
            // other code
        }
    }
}

**Comment by gafter** [comment]
According to the language specification, during name lookup we look for members of the current namespace before looking at the usings appearing in the namespace scope.  The current namespace is `Mini`, and it contains a namespace named `Auto`.  Since we find that, we do not look in the using declarations.  See https://github.com/dotnet/csharplang/blob/master/spec/basic-concepts.md#namespace-and-type-names
