### ISSUE TITLE
Use camelCase for local functions in Roslyn code base

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#35944]
Using camelCase for local functions makes it much more obvious that we are working with local functions and not methods. It also is more consistent to use the same casing for all local declarations - variables and functions.

**Comment by sharwell** [comment]
Related to #29019

**Comment by CyrusNajmabadi** [comment]
I'm in the same boat as @sharwell .  It's very different to me if this is just a real local/param (where then my expectation is that someone else passed this in as an *indirection* mechanism), versus having this just be a normal ref to a method, albeit one that was dclared in an inner scope to keep the class clean.  The IDE almost always uses these as separate types of patterns, so having the naming be distinct is actually valuable for clarity.

**Comment by jaredpar** [comment]
I don't think we should necessarily be having this debate here. Roslyn largely follows the coding style guidelines for the .NET organization vs. inventing our own. This has been true pretty much from the day we went OSS. 

Rather than debate here I suggest we move to CoreFX, have them establish the baseline and then adjust to that decision. 

Having the debate here first is how we approached tuples. CoreFX took up the debate later, came to a different conclusion and now we're left with a different style than we're telling our customers to use (oops). To get us back in line we'll need to make an update to our code (once CoreFX makes the recommendations official). Would rather avoid repeating that process again with local function names. 

Remember the goals for style in our code bases:

1. Keep in consistent across the dotnet organization. This makes it easier for customers to transition from one repository to the next. 
1. Use the style we advocate to customers. 
1. Debate, decide, move on 😄 

@terrajobst

**Comment by CyrusNajmabadi** [comment]
Note: i believe roslyn-ide had an additional goal of: be able to dogfood the scenario of having different projects have different codestyles.  This has been pretty critical over the years to validate and vet this scenario.  We're in a slightly special space of actually being the team that need to provide the tools that enforce style.  So it's more incumbent on us to be able to dogfood the experiences here directly.  When we haven't in the past, we've simply shipped things that haven't worked since we weren't directly encountering the problems.

Thanks!

**Comment by CyrusNajmabadi** [comment]
> Having the debate here first is how we approached tuples. CoreFX took up the debate later, came to a different conclusion and now we're left with a different style than we're telling our customers to use (oops). 

I do think we should front load these conversations earlier.  Esp. when designing the lang feature.  The Tuple debate was particularly surprising given that the LDM has effectively settled on a pattern that was used in all our docs, and was how we were messaging this to customers in talks and conferences and whatnot.  There was a very explicit design there (i.e. `tuples are like a bundled group of parameters`) that was motivating a lot of things, and which many wanted the naming to follow.  By separating out the discussion of the language feature and the eventual naming guidelines, there was a lot of friction.   Ideally that can be avoided in the future for any sort of top-level naming-impacting features.

**Comment by tmat** [comment]
>  There was a very explicit design there (i.e. tuples are like a bundled group of parameters) that was motivating a lot of things

I think in this case the LDM did not consider all use cases in real code - as tuples can be used in collections where they have nothing to do with method parameters.

**Comment by CyrusNajmabadi** [comment]
> I think in this case the LDM did not consider all use cases in real code - as tuples can be used in collections where they have nothing to do with method parameters.

This was 100% considered :)   Even in that case, it was felt to be a collection of pieces of data that you would think about as individual components, not as an aggregated whole.  i.e. you don't think about the ValueTuple itself, or that this is some struct with props.  it's just an aggregation of data that are very similar to how parameters are aggregated and passed around.  

It was def known and understood (and examples and talks even covered this).

> e.g. `Dictionary<string, (int A, bool B)>`

Yup.  Thse cases were totally expected, and still written up always as `...(int whatever, bool andSoForth)...`.  

--

*Regardless*, my point isn't that the LDM was right.  My point is that by separating out these discussions, much *friction* was introduced since the naming thoughts that went in at one part of the process didn't align with the naming thoughts produced elsewhere.  That's not healthy and we should do a better job around this precisely because naming *is* something that goes into LDM thinking, and it often goes unstated, not realizing the possible negative results that can produce later.

**Comment by tmat** [comment]
Just to argue a bit on that dictionary case: so you're saying the LDM said this looks good? `dict["key"].a.X`

**Comment by sharwell** [comment]
Not sure about the LDM, but I think it looks good.

**Comment by CyrusNajmabadi** [comment]
Yes.   Certainly.

**Comment by tmat** [comment]
I think it's terrible

**Comment by CyrusNajmabadi** [comment]
Note: i'm not interested in relitigating the actual views of the LDM.  That's not waht' relevant to me.  My point is the friction between the different views, and the lack of communication.  that's what caused the majority of the problem here.

**Comment by tmat** [comment]
@CyrusNajmabadi I get that and I agree with you. You wanted to ask what's the opinion on the dotting thru casing inconsistency.

**Comment by CyrusNajmabadi** [comment]
> @CyrusNajmabadi I get that and I agree with you. Just wanted to ask what's the opinion on the dotting thru casing inconsistency.

I don't see anything inconsistent.  if you have a field, you might see:  `foo.a.b.c.D`.  If you have parameters, you might see `a.b.D`.  There are lots of times when casing goes lower/upper/etc.  None of that is particular bothersome.

**Comment by CyrusNajmabadi** [comment]
Bringing this back to local-functions.  I don't think i can speak for any particular views from the part of the LDM (i'm not sure anyone had any).  I do know that i felt that a core part of local functions was that, in particular, they were *not* local delegates. i.e. they weren't just a convenient shorthand for writing `Action a = () => { ... }`.  Instead, they were a way to actually just have methods, just scoped more narrowly to hide them from the rest of the class.

Regardless of my views here, what i woudl like is for the topic to at least be considered by anyone responsible for making .net naming decisions, and that it's not just given a haphazard thought, but is discussed with the differing views on this represented to make an informed choice.

**Comment by CyrusNajmabadi** [comment]
> "I think it's terrible"

And i think that's totally fair.  TBH, there's a distinct difference here between tuple-members and local-functions as well.  Tuple-members *are* part of your public contract.  And i can see there being extremely strong feelings about what these should mimic.  I also think it's 100% reasonable to think they should be like public fields (after all, that's what they are!! :-) ).

With local-functions though i adopt a "allow people to decide what's best" view as i think both the "this is a local" and "this is a method" views are both valid.  Since it's not part of your public API, i think it's highly less pressing or of a concern that we must force a naming style here.   If people want to think of them as locals, they can name as such.  If they like them as methods, name them appropriately.  However, since they are an internal detail, and since both views seem to have proponents, and reasonable arguments for each, perhaps allow this to just be an area where there is no strong .net position.

**Comment by tmat** [comment]
> I also think it's 100% reasonable to think they should be like public fields (after all, that's what they are!! :-) ).

I think the problem with tuples is essentially the lack of records :). If we had both then we could say that tuples are just group of parameters and should be used just to return mutliple values from methods. Everywhere else records would be preferred. Then it would make sense to use camelCase for tuple element names and PascalCase for record element names. Right now tuples are used for both. So I don't think there is a single rule that should be applied to both scenarios. I think the right approach is to use a more nuanced rule that distinguishes between these cases.

> However, since they are an internal detail, and since both views seem to have proponents, and reasonable arguments for each, perhaps allow this to just be an area where there is no strong .net position.

True, they are not public APIs, but seems like there is a desire to unify the style across code base. I actually find local functions to be easily overused. I think it makes the code often less readable when methods that implement a piece of logic that's well isolated are nested into a method just because they are only called from that method. Now if in addition, PascalCase is used for naming them and the containing method is large it's visually hard to distinguish the boundaries of the containing method. So it easily happens that I'm reading some code that I think it's a method, but it's actually a local function that captures some local variables of a containing method.

**Comment by CyrusNajmabadi** [comment]
> I think the right approach is to use a more nuanced rule that distinguishes between these cases.

Sure!  I also think that's somewhat why naming on tuples was punted and why there was discussion about if tuples are even appropriate for public apis (not sure where that ever landed).

> True, they are not public APIs, but seems like there is a desire to unify the style across code base. I actually find local functions to be easily overused. I think it makes the code often less readable when methods that implement a piece of logic that's well isolated are nested into a method just because they are only called from that method.

Note: this is why i push heavily for two things in the IDE:

1. local functions go after the *last* return point in your method.  i.e. they're not intermixed with the rest of the main method's logic.
2. local functions should try to be static as much as possible (though this is new, and we need to conver a lot over to this).  When data is passed explicitly, it's really easy to understand what's oging on and how it flows.  When it's implicitly captured, it gets super confusing.

With this style, it's not too bad to have a bunch of a local functions.  In effect, all that happened was the **last** `}` of the method simply reached out a bit and gobbled up some slibing methods :)  

I do think local functions can be abused, so i def go for a "use these responsibly, and make sure to keep code clarity high" approach.  Note that the naming that we like on the IDE helps support this *IMO*.

**Comment by CyrusNajmabadi** [comment]
>  So it easily happens that I'm reading some code that I think it's a method, but it's actually a local function that captures some local variables of a containing method.

I totally see your concern there.  I push heavily to not have local functions capture state (and to use 'static' now to enforce that).  I can't tell you the number of times i saw something like this:

```c#
string something;

// .. code ..

// .. loops ..

return something;
```

and i was super confused since 'something' wasn't touched in all that code (instead, it was local functions that was mutating it).  By moving to static-local functions for most code, this is avoided as the data flow must be much more explicit (as it would have to be sibling methods).

Anyways, i don't think there's a lot of disagreement between you and me :)   I think we both care the most about making code readable and having patterns that try to maximize clarity and maintainability.

**Comment by tmat** [comment]
Yeah, so perhaps we should not enforce any specific style for naming local functions. Let the author of the function decide what's most appropriate for the particular method.

**Comment by jmarolf** [comment]
CC:  @heejaechang

**Comment by jmarolf** [comment]
@ryzngard 	maybe we should have an editorconfig option for this?

**Comment by sharwell** [comment]
@jmarolf we do have editorconfig for this and it's already configured for Roslyn

**Comment by jaredpar** [comment]
@tmat 

> Yeah, so perhaps we should not enforce any specific style for naming local functions.

Disagree. This is an enforceable style element that people obviously have strong opinions about (as evidenced by this thread). The compiler and IDE team have already started doing this. Like other style decisions we should just push CoreFX to take the lead here and shift debate over to it.

**Comment by CyrusNajmabadi** [comment]
If this shifts to CoreFx, can you include me?  I want to make sure all the requisite points/counterpoints for the different positions are represented.  Thanks!

**Comment by tmat** [comment]
@jaredpar Fine with me to delegate to CoreFX, though the style does not affect public surface.

**Comment by CyrusNajmabadi** [comment]
> Fine with me to delegate to CoreFX, though the style does not affect public surface.

Yeah, my bar is def different because of that.  However, i think CoreFx does have rules for all sorts of things that aren't public.  For example, isn't the rule about `_foo` naming for private fields something from them?

**Comment by jaredpar** [comment]
@tmat 

> Fine with me to delegate to CoreFX, though the style does not affect public surface.

Neither do `private` fields or methods yet CoreFX still has style guidelines for those 😄 

@CyrusNajmabadi 

> If this shifts to CoreFx, can you include me? 

Will do.

**Comment by tmat** [comment]
@jaredpar As I said, i'm happy to defer to CoreFX design guidelines if there are any. I was just not sure if they care about owning all style decisions for C# and VB (and F#?).

**Comment by tmat** [comment]
> If this shifts to CoreFx, can you include me?

Me too please :)

**Comment by CyrusNajmabadi** [comment]
Closing out as we've stuck with the 'PascalCased' for local functions and camelCased for local delegates in the IDE.

**Comment by jaredpar** [comment]
We still use camelCased in the compiler layer but it's something I want to talk with the team about in the future. Seemingly every code base has chosen PascalCased including the .NET framework recommendations. Similar for tuples
