### ISSUE TITLE
Null propagation should prohibit CS8602 

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/roslyn#36014]
**Version Used**: VS 16.2.0-pre.1.0+28917.182

**Steps to Reproduce**:

In the final line of this code, `s` is provably non-null yet CS8602 is issued.

```c#
string? t = s?.ToUpper();

if (t == null)
    return;

Console.WriteLine(s.ToString());

//                ^ dereference of possibly null reference
```

**Expected Behavior**:

No warning.

**Actual Behavior**:

Warning.

**Comment by 333fred** [comment]
I don't think this is something that we're planning on supporting. This requires another level of flow analysis, namely remembering that `s` fed into the value in `t` and that when `t` is not null we can flow that information back to `s`.

**Comment by jaredpar** [comment]
Agree with @333fred here. This is essentially asking for nullable to support alias tracking. That is a feature we've explicitly decided to not do in 8.0 due to the complexity. I have some doubts we'd ever be able to do it because of the inherent complexity of alias tracking in C#.

Primary bug tracking this is #34644. Yes that is about indexers but it's the same fundamental problem: alias / value tracking.
