### ISSUE TITLE
[Discuss] Performance Checks / Unit Tests

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#3602]
I think it be beneficial to some (open) way of checking the performance, contributions changes have on the code of Roslyn. Do a compilation with the (old / current ) compiler and the newer compiler.

Whilst differences in the testing environment would produce different result. It does give ballpark figures. To see if the change is worth it. 

We would also require a de-facto standards to use
- code to against which to compile.
- compiler to use as the base

Would a separate set of Unit Test suffice? or is a separate Tool required? 

Discuss

**Comment by AdamSpeight2008** [comment]
This would be especially useful for changes that affect the scanner / parser.

**Comment by VSadov** [comment]
The minimum functionality here would be ability to tun some tests before and after given change and compare numbers. 
In theory that could be a separate set of XUnit tests which run and time some pieces of code so that such set could serve as a benchmarking tool. I wonder, however, if XUnit is the right tool for doing this kind of work and if there are better alternatives.

**Comment by AdamSpeight2008** [comment]
A Trace Build flag?

**Comment by Pilchie** [comment]
Tagging @pharring

**Comment by agocke** [comment]
This is a bit of a dup of #3567. That's what we do must of our perf testing with.

**Comment by chrisaut** [comment]
See also #670
