### ISSUE TITLE
Add documentation and sample links in our template Analyzer + Fix project

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#3619]
We have recently added some documentation and samples on analyzers and fixers. We may want to consider adding comments with hyperlinks to documents under https://github.com/dotnet/roslyn/tree/master/docs/analyzers at appropriate places in the template project.

**Comment by paul1956** [comment]
The issue is not mostly with analyzing it is with fixing and refactoring. 

The VB walkthroughs  turn off Option Strict and Explicit which makes understanding them more difficult.

The two refactoring examples (codeRefactoringVSIX and ImplementPropertyChanged) both use PropertyBlock and have little help around what they are doing with respect to this issue.

**Comment by jmarolf** [comment]
@mavasani could you verify that this is fixed please?
