### ISSUE TITLE
Include analyzer that warns users ignoring results of .WithRoot(), .ReplaceNode() etc.

### ISSUE THREAD

**Issue by JoshVarty** [dotnet/roslyn#3620]
A lot of users are running into issues with immutability in Roslyn. They're ignoring the results of methods such as `.WithRoot()` and `.ReplaceNode()` and are unsure why their code doesn't work.

For example: http://stackoverflow.com/questions/30986360/order-constructor-parameters-with-roslyn

I think an analyzer would be the perfect solution to this issue. Whenever users ignore the results of these methods, we could warn them about it. I don't have much experience with analyzers but I'd build it if you think it's a good idea.

**Comment by paul1956** [comment]
Sorry replied to wrong thread. 

The issue is not mostly with analyzing it is with fixing and refactoring. 

The VB walkthroughs  turn off Option Strict and Explicit which makes understanding them more difficult.

The two refactoring examples (codeRefactoringVSIX and ImplementPropertyChanged) both use PropertyBlock and have little help around what they are doing with respect to immutability.

**Comment by srivatsn** [comment]
Moved this issue to the roslyn-analyzers repo where these analyzers now live
