### ISSUE TITLE
C# - make readonly field refactoring ignores MEF Import attributes

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#36266]
When Managed Extensibility Framework (MEF) is used with its [Import] attribute on private field which is not assigned elsewhere, &quot;Add readonly modifier&quot; refactoring is suggested. When realized, readonly modifier makes the code to fail at runtime when MEF tries to inject the imported object.

When this refactoring is auto applied during document formatting, it is error prone to check it untill runtime.

See the attached picture.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/343070/c-make-readonly-field-refactoring-ignores-mef-impo.html
VSTS ticketId: 691047_
_These are the original issue comments:_

Jinu Joseph [MSFT] on 10/14/2018, 08:59 PM (237 days ago): <p>We appreciate you taking the time to report this problem. We are currently prioritizing problems that are impacting a broad set of our customers, so we may not be able to investigate this one immediately. We know this problem is important to you, so we will continue to monitor it.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by sharwell** [comment]
I submitted https://github.com/dotnet/roslyn-analyzers/pull/2534 to address this for Roslyn.sln.

**Comment by jinujoseph** [comment]
**Design Meeting Notes**
We won't want to fix the analyzer since the analyzer will need to have special knowledge of library. We will end up teaching two different import attributes which are in different namespace etc We should probably take the suppressor API approach here. If we know who owns the MEF analyzer package then they should take a suppressor API approach and suppress this warning going forward
