### ISSUE TITLE
Add editor format classifications for member declarations vs member usage

### ISSUE THREAD

**Issue by abock** [dotnet/roslyn#36327]
When VS Mac switched from TextMate to Roslyn classification. One of the things that TextMate did was classify member/method declarations and usages/references differently.

#3976 was recently closed as fixed due to #31231, but this did not actually seem to implement support for the usage vs declaration classification. So while Roslyn does now have richer classification, it's still missing this this particular case which many users found useful in VS Mac.

See also https://github.com/mono/monodevelop/issues/4506, which was filed originally when VS Mac moved to Roslyn classification.

**Comment by jinujoseph** [comment]
Need to have conversation with Editor team to see if they can support compond classification

**Comment by JoeRobich** [comment]
This is prohibitive because it would greatly increase the number of ClassificationFormatDefinitions that we export, since it would require exporting all identifier types in combination with new Identifier Declaration and Identifier Usage classifications.

Compound Classification would simplify this since we would not have to export the combination of classifications, we could simply report a combination of classifications per span. Take for instance the code `Console.WriteLine()`. Ideally we could return to the editor that the span `WriteLine` was a Method Name, a Static Symbol, and an Identifier Usage.

**Comment by jinujoseph** [comment]
looping in @olegtk for thoughts from editor side

**Comment by olegtk** [comment]
What's Compound Classification? @AmadeusW (as this looks related to fonts&colors).

**Comment by sharwell** [comment]
Design review conclusion: with the APIs available today, this would add more classification formats to the Fonts and Colors dialog than we are comfortable adding at this time. Before working to address this, we would need a better system in place for defining "compound classifications", which is essentially cases where identifiers have multiple classifications at the same time which are then configured and eventually presented in an intuitive manner.
