### ISSUE TITLE
Generate ctor does not include parameters for base class ctor

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#36333]
VSF_TYPE_MARKDOWNWhen you generate a ctor for a class using Ctrl-. a dialog is shown to allow you to pick which properties to initialize. However, there is no ability to choose which base class ctor should be invoked, and thus no parameters will be added for this.

To be useful in this scenario, the dialog should allow you to also choose which base class ctor to invoke, and include the required fields in the generated ctor.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/508491/generate-ctor-does-not-include-parameters-for-base.html
VSTS ticketId: 830580_
_These are the original issue comments:_

Visual Studio Feedback System on 3/28/2019, 11:56 PM (74 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

Cytheria Ji [MSFT] on 3/31/2019, 07:28 PM (71 days ago): <p>Thank you for submitting feedback on Visual Studio.</p><p>Could you please provide your project language and screenshot to us for further investigation?</p>

Visual Studio Feedback System on 4/2/2019, 00:08 AM (70 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

Visual Studio Feedback System on 4/3/2019, 00:43 AM (69 days ago): <p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

_These are the original issue solutions:_

Morten Mertner solved on 4/1/2019, 09:40 AM (71 days ago), 0 votes: <p>I am using C#. Currently on iPad so no screenshot, but there is only one dialog displayed for Generate Constructor, so don’t see much value in me posting a copy of it here.</p>

**Comment by vatsalyaagrawal** [comment]
@chborl : Is this something we can incorporate with your recent constructor work?

**Comment by chborl** [comment]
@vatsalyaagrawal , it's not clear what the best design for this would be so I think we should talk about it in design meeting.

**Comment by AlessandroMartinelli** [comment]
I feel this should be important too: automatic constructor generator is a great feature, but if a given class inherits from a base class having its own attributes, the constructor generator feature does not take into account fields of the base class, that need to be handled manually. 
As a result, in case of a class inheriting from a base class with its own attributes, the automatic constructor generator feature become useless. And it's really a shame because it is a feature that increases productivity but it cannot be used in the above-mentioned scenarios.

From the developers productivity perspective it would be a **great** improvement to complete such features.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of broad feedback on this topic.
