### ISSUE TITLE
How to compile scripts efficiently?

### ISSUE THREAD

**Issue by NMSAzulX** [dotnet/roslyn#36499]
When compiling dynamically, are there any optimization options, such as ScriptString with Inline-Attribute, configuration with Release-Options, and so on?

I hope to be able to compile high-performance code.

Here is the code:
https://github.com/dotnetcore/Natasha/blob/master/Natasha/Engine/ComplieModule/ScriptComplieEngine.cs#L148-L159

In addition, although my needs have been met now, I would like to ask if there will be any significant improvements in the future for CSharpCompilation.

**Comment by jcouv** [comment]
Can you clarify what you mean by performance? Specifically, do you mean time from script to execution, or speed of execution?
Do you have indications of a lack of performance? Have you done any benchmarking comparing scripting to regular C# to identify bottlenecks? Being specific will help us assess the situation better.

The speed of execution in scripting should be very similar to that of regular (non-scripting) C#, with one caveat on top of my head: instead of locals, scripting uses fields, which I expect would cause some overhead. You can avoid this by using types for most of code, as opposed to top-level variables.
More generally, scripting scenarios prioritize convenience (ability to put things together quickly) over performance. 

@tmat may be able to share some thoughts.

**Comment by NMSAzulX** [comment]
> Can you clarify what you mean by performance? Specifically, do you mean time from script to execution, or speed of execution?

Emmmm, I mean, execution speed. Because there are some optimizations of Dup instructions in handwritten Emit, will this occur in roslyn compilation?
  
  

> Do you have indications of a lack of performance?  

The BechmarkDotNet official team says the next version will support benchmarking for roslyn compilation. I've written the benchmark, and I'm waiting for this moment. https://github.com/dotnet/BenchmarkDotNet/issues/1152  

Does the roslyn feature allow developers to focus on scripts instead of Emit?This feature really makes sense, and I personally think it will be an important pillar of the widespread use of. Net. And It would be better if AOP joined.  : )

**Comment by NMSAzulX** [comment]
I have fixed the link to the above code.  https://github.com/dotnetcore/Natasha/blob/master/Natasha/Engine/ComplieModule/ScriptComplieEngine.cs#L148-L159
