### ISSUE TITLE
VS 16.1.3 - For To Foreach Bug CS1656

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#36506]
VSF_TYPE_MARKDOWNVS 16.1.3 converts this for:
```
void M(System.Collections.Generic.List&lt;(string s1, string s2)&gt; list)
{
    for (int i = 0; i &lt; list. Count; i++)
    {
        list[i] = (&quot;a&quot;, &quot;b&quot;);
    }
}
```

To this foreach:
```
void M(System.Collections.Generic.List&lt;(string s1, string s2)&gt; list)
{
    foreach ((string s1, string s2) v in list)
    {
        v = (&quot;a&quot;, &quot;b&quot;);
    }
}
```

Which fails to compile with CS1656.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/608684/vs-1613-for-to-foreach-bug-cs1656.html
VSTS ticketId: 919078_
_These are the original issue comments:_

Visual Studio Feedback System on 6/17/2019, 01:46 AM (7 hours ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by jinujoseph** [comment]
cc @CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
@jinujoseph was this to just give me awareness of the issue?  Or did you ping me for some other purpose?  Thanks!

**Comment by jinujoseph** [comment]
@CyrusNajmabadi for your info only, also to highlight if you are aware of any limitation since I believe you added this feature.

**Comment by CyrusNajmabadi** [comment]
I did not add the feature :)  ForToForeach (and the reverse) were possibly Heejae/Ivan.  Cheers! :)

**Comment by CyrusNajmabadi** [comment]
Apperantly, i added this feature :D

**Comment by CyrusNajmabadi** [comment]
The feature properly reports a warning that thsi will cause a problem:

![image](https://user-images.githubusercontent.com/4564579/59715850-97a2e580-91c9-11e9-8604-ae0a3f9377ab.png)

I think this behavior is appropriate and was by design originally.  I don't think we need to change things here.  As this is a refactoring, we want it to be generally applicable to help people along.  As long as we're informing them of the problem, i think that's ok.  

Tagging @jinujoseph @ivanbasov as i think we can just resolve this.

**Comment by ivanbasov** [comment]
@CyrusNajmabadi , @jinujoseph there is an actually a bug at least for non-direct scenarios, for example, for deconstruction:

![image](https://user-images.githubusercontent.com/5455484/59717234-742d6a00-91cc-11e9-8bc5-546431249b49.png)

We can either do not provide a conversion or should extend warnings for those scenarios.

**Comment by CyrusNajmabadi** [comment]
> We can either do not provide a conversion or should extend warnings for those scenarios.

Yeah, i woud just extend the warnings to handle this (and any other usage of 'list' that might be a write).

**Comment by CyrusNajmabadi** [comment]
I'm actually a little confused why you don't see the warning, but i do...

**Comment by ivanbasov** [comment]
Oh.. I see @CyrusNajmabadi . Thank you for pointing this! I haven't notice the warning in preview. It seems that the customer hadn't noticed it as well. Hm... we had an offline design discussion. @sharwell  suggested to add `ref` in those cases in the iterator. It should resolve the issue. We would add `ref` only in case of an assignment.

**Comment by CyrusNajmabadi** [comment]
> @sharwell suggested to add ref in those cases in the iterator. It should resolve the issue. We would add ref only in case of an assignment.

That works for me as well :)

**Comment by ivanbasov** [comment]
@sharwell , @CyrusNajmabadi 
I tried `ref` with some examples. Using `ref` requires some types of collections, otherwise it produces code which cannot be compiled. `ref` in `For...Each` is not supported in VB.

1. Warnings are generated. The only reasonable update for the _for to foreach_ refactoring I see is to add more test cases. Maybe there are some corner cases. But in general the refactoring seems to work fine. Sorry for the false alert, @CyrusNajmabadi ! 

2. User didn't notice the warning. I didn't notice it as well. In both color schemes, the warning is displayed with basic _black on white_ or _white on black_ colors. There are elements in the preview highlighted with more evident red color. @kendrahavens , could you please consider an UX design review for this?

**Comment by mikadumont** [comment]
The warning is hard to notice and therefore don't think this particular scenario should be an option if it will break code.

**Comment by CyrusNajmabadi** [comment]
@mikadumont Many (most?  all?) refactorings can break code.  The idea of a refactoring though is to help speed up changes that would take many more steps manually.  We want to always have the feature available so that people can trust that it's available, instead of being in the position of wondering why it's not showing up and thinking the product is broken.

We strike a balance here of not wanting to be so rigid that the tools become unreliable and unhelpful.  We understand this means users can make changes that will need additional fixup steps.

**Comment by nnpcYvIVl** [comment]
@CyrusNajmabadi

> We want to always have the feature available so that people can trust that it's available, instead of being in the position of wondering why it's not showing up and thinking the product is broken.

That doesn't seem to be the case universally. IDE0044 'Make field readonly' isn't offered if it detects that it will generate bad code (e.g. mark a mutable field as readonly). In my opinion developers would prefer that the codefix not be shown rather than be shown and generate broken code.

**Comment by CyrusNajmabadi** [comment]
> IDE0044 'Make field readonly' isn't offered

That's an analyzer/fix.  You can tell because it has the `IDEXXXX` bit.  It's not a refactoring.

>  In my opinion developers would prefer that the codefix not be shown rather than be shown and generate broken code.

We've received consistent feedback over the years of hte opposite.  People want to use the refactoring and are confused when it's not available when they expect it to be.  It's possible there are different customer segments, but i've seen no data indicating that we should now start erring toward this other group versus the one we've intentionally erred toward all these years.

**Comment by ivanbasov** [comment]
@mikadumont @CyrusNajmabadi @jinujoseph  @mavasani  maybe we should have an option if user accepts that refactoring will break their code or if refactorings should be provided only in safe scenarios. I think we may have users preferring each of these options.

Moreover, sometimes we bail out from refactoring assuming we would break something important for a user. Having such option, we may action braver in case if user accepts code breaks.
