### ISSUE TITLE
Nullable analysis should learn from calls to well-known Equals methods

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#36591]
From @jcouv:

Update the null-state at the end of an invocation of a recognized method
https://github.com/dotnet/csharplang/blob/master/meetings/2019/LDM-2019-05-15.md#equality-postconditions

Comparison with null literal (or null constant): `object.Equals(x, null)`
- learn that `x` is null in when-true branch
- learn that `x` is not-null in when-false branch

Comparison with a not-null expression: `object.Equals(x, notNull)`
- learn that `x` is not-null in when-true branch
- for `object.Equals(x?.y, notNull)`, learn that x was not-null (the same as `x?.y == notNull`)

`object.Equals(x, maybeNull)`
- learn nothing about x

Open question: what are all the methods we recognize? So far:

- `Object.ReferenceEquals`
- `Object.Equals` 
- `IEqualityComparer<T>.Equals` 
- `EqualityComparer<T>.Equals` 
- `IEquatable<T>.Equals`

Also add some tests around user-defined `==` (we learn the same thing regardless of if it's builtin or user-defined)

**Comment by RikkiGibson** [comment]
Wondering about some of the scenarios related to instance Equals methods:

This one seems clear:
```cs
void M(string? s) {
    string s1 = "hello";
    if (s1.Equals(s)) {
        _ = s.ToString(); // no warning
    }
}
```

This one is less clear to me:
```cs
void M(string? s) {
    if (s.Equals(null)) {
        s.ToString(); // is this unreachable code?
    }
}
```

**Comment by jcouv** [comment]
I suspect you meant to declare the parameter as non-nullable in the second example:
```C#
void M(string s) { // type is not annotated
    if (s.Equals(null)) {
        s.ToString(); // is this unreachable code?
    }
}
```
If you wrote `if (s == null) s.ToString();` we would treat the branch of the `if` as reachable, but then we'd warn on the dereference. That's because `s == null` is considered a pure null test; it tells the compiler that the expression may be null after all.
This raises a question: should `s.Equals(null)` be considered a pure null test.
I think it should, but it would be good to confirm (maybe see what Chuck or Neal think on this one).

**Comment by RikkiGibson** [comment]
I think for now we are going to treat all the known Equals methods as pure null tests, even if they are virtual.
