### ISSUE TITLE
Import completion should timeout if computing items takes too long

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn#36624]
It should keep the computation going to populate the cache, so the next time completion is triggered the data will be available.

This is to avoid blocking completion for the very first time it's triggered. Telemetry shows that for most people it might take at least 6s for the import completion to return (30s in the most extreme case). 

An alternative would be pre-calculate the data and warm up the cache before completion is triggered.

**Comment by Dreamescaper** [comment]
IMHO, alternative approach is much better. IntelliSense behavior should be consistent. Having it stuck for several second is irritating, but having it missing items I'm expecting is much worse.

P.S. I'd say the best behavior would be to should IntelliSense immediately with available items and some loading indicator, and add computed items when they are available. I suppose that's _much_ harder though...

P.P.S. I suppose delay is caused by roslyn's types cache, not by CompletionItems cache? Had same issue with IntelliSense Extender extension, and I didn't use cache there.

**Comment by CyrusNajmabadi** [comment]
> Having it stuck for several second is irritating, but having it missing items I'm expecting is much worse.

i don't see how that can be the case.  Even having a delay of a few hundred milliseconds makes typing feel awful.  Having it takes seconds is not an irritant, it's literally not usable for an editor.

**Comment by Dreamescaper** [comment]
> Having it takes seconds is not an irritant, it's literally not usable for an editor.
True, but it happens only for the first time. And it's not blocking for actual typing. So for me it simply makes an impression that it's loading, just like the whole VS is slow right after VS is opened.

If not all usual items are present, and least it should indicate that somehow (e.g. using suggestion mode). Otherwise it could be confusing, and breaking muscle memory.

OTOH, again, we're talking only about first time. Probably not that important.

**Comment by CyrusNajmabadi** [comment]
> If not all usual items are present, and least it should indicate that somehow (e.g. using suggestion mode). Otherwise it could be confusing, and breaking muscle memory.

We've already shipped this way for around 20 years :)  I don't think it's a problem that needs solving.  During first trigger/initial-load, the list may be incomplete.  It's been a non-issue to have to solve :)

> OTOH, again, we're talking only about first time. Probably not that important.

Indeed :)

**Comment by genlu** [comment]
Closed. Timebox (of 1s) is implemented in #36936. I will further explore the possibility of saving the cache to disk and pre-calculation.
