### ISSUE TITLE
Expose IHierarchyItemToProjectIdMap functionality publicly (feature request)

### ISSUE THREAD

**Issue by aodl** [dotnet/roslyn#36710]
**Feature Request**:

Expose functionality for easy mapping between `IVSHierarchy` and `ProjectId` - [functionality that already exists but is internal](https://github.com/dotnet/roslyn/blob/master/src/VisualStudio/Core/Def/Implementation/HierarchyItemToProjectIdMap.cs#L24).

**Use Case**:

In my VSIX extension I have a `EnvDTE.Project` object, but I'd like to convert this to a `Microsoft.CodeAnalysis.Project`. It looks like I need to first get the `ProjectId`, so that I can call `workspace.CurrentSolution.GetProject(projectId)`, but I can't find how to get the `projectId`.

**Context**

I'm wanting to display a custom tree in the solution explore underneath projects of a particular capability. The tree displays some dependencies of the project, and certain types that are exposed by those dependencies. I'm hooking the `_dispReferencesEvents_ReferenceAddedEventHandler` event, getting the `Reference.SourceProject`, and from that I'm trying to get it's `projectId` to bring the project into the roslyn code analysis world (for discovering type information etc.)

tagging @jasonmalinowski, as suggested by @CyrusNajmabadi on dotnet/roslyn

**Comment by CyrusNajmabadi** [comment]
@jasonmalinowski perhaps an extension method can be provided on EnvDTE.Project? and/or IVsHierarchyItem?  Similar to how we have an extension on ITextSnapshot to get a Document?

**Comment by tmat** [comment]
We shouldn't expose an API that couples VS UI type (`IVsHierarchy`) with Roslyn workspaces layer type (`ProjectId`). 
Instead, the right API to provide is one that maps from project GUID, which can be retrieved from `IVsHierarchy`, to `ProjectId`.

**Comment by CyrusNajmabadi** [comment]
> We shouldn't expose an API that couples VS UI type 

At the VS layer, i'm not certain why that would be an issue.  Esp. with an EnvDTE.Project.  We tied a VS UI type before (ITextSnapshot) with the Roslyn workspaces layer.  It's not clear to me why we wouldn't want that for other sensible VS types.

**Comment by tmat** [comment]
@CyrusNajmabadi Because for VS SaaS scenarios we are working on separating Roslyn from the VS UI. In past it might have been ok, but not anymore. We don't want any Roslyn types to be coupled with VS UI types like `IVsHierarchy`. `ITextSnapshot` is not a UI type in this context. The editor separates the rendering of the buffer content from the model that represents the text in the buffer. `IWpfTextView` would be a UI type.

**Comment by CyrusNajmabadi** [comment]
This would need to go through an API proposal.  in general, the reason we don't just make things public is because it increases maintenance costs and locks down our ability to change things in teh future.  We can open things up, but we have a process that requests need to go through to make sure the appropriate people weigh in and the right API shape is determined and shipped.
