### ISSUE TITLE
Choosing "Use defaults" in Fonts and Colors, loses the "defaults" for the new syntax colors

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#36897]
Make sure you've never set the new syntax coloring colors.

**Steps to Reproduce**:

1.  Tools -> Options -> Fonts and Colors 
2. Scroll down to `User Members - Methods`
3. Click  Use Defaults

**Expected Behavior**:
For the color to not change for `User Members - Methods`

**Actual Behavior**:
The color changes by to "Default" (black) which is different default to what it was originally set to.

Looks like there's a concept of "Default" colors that we're not making user of for this?

**Comment by davkean** [comment]
I cannot figure out how to reset the default back to what it was originally at all.

**Comment by JoeRobich** [comment]
I agree. With the enhanced colors not being the in-box default colors, it makes things unnecessarily difficult for users. 

Perhaps the things to do at this point would be:
- Bake the enhanced colors into VS as defaults
- Change the Tools > Options > Text Editor > C# | Basic > Advanced page Classification section to be an "Apply classic colors" button (If the user later clicked `Use defaults` from Fonts and Colors, they would need to re-apply classic colors)
- Change the on-startup enhanced color code to do a one-time application of classic colors if the user had previously unchecked the "Use enhanced colors" option

@dpoeschl Since you ran into the same problem (https://github.com/dotnet/roslyn/issues/33708), what are your thoughts on my proposal?

**Comment by JoeRobich** [comment]
This issue is resolved by https://github.com/dotnet/roslyn/pull/39792
