### ISSUE TITLE
"Indexing can be simplified" has changed behavior

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#36909]
It used to be that the compiler had intrinsic knowledge of strings/arrays for indexing/slicing operations.  As such, we could offer to convert to use those new features in projects that didn't hve a reference to System.Index or System.Range.  

This behavior seems to have regressed and the compiler seems to now require those types to be avialable.  This breaks our feature which offers to convert to this form (even if those types aren't available) for strings or arrays.

**Comment by CyrusNajmabadi** [comment]
Tagging @agocke for the regression.

**Comment by agocke** [comment]
Yeah, that was a hack for compat. This is intentional.

**Comment by CyrusNajmabadi** [comment]
1. Sorry, can you explain which behavior you mean is "intentional"?
2. If you mean that it is "intentional" that we require Range/Index, that's fine.  However, we should still keep this issue open as teh IDE *feature* is broken.  i.e. we suggest people use these operators, even though it immediately breaks.

**Comment by agocke** [comment]
Ah my mistake, I thought it was a compiler bug. Yeah, the feature requires the types. Some emit choices may mean that the types never get created, but for user simplicity it's easier to require them. Otherwise you can end up in the situation where the user changes a small thing and unexplainable errors appear.

**Comment by CyrusNajmabadi** [comment]
Gotcha.  I'll fixup the feature soon.
