### ISSUE TITLE
Roslyn does not check nullability of `MoveNextAsync` in await foreach pattern

### ISSUE THREAD

**Issue by TessenR** [dotnet/roslyn#37002]
**Version Used**: 

```
Branch master (21 Jun 2019)
Latest commit 898bed by Heejae Chang:
added NFW to get some data on incremental parsing bug where source si� (#36620)

* added NFW to get some data on incremental parsing bug where source size and tree size is different

* more comments
```

**Steps to Reproduce**:

```cs
#nullable enable
using System.Threading.Tasks;

public class C {
    public C GetAsyncEnumerator() => this;
    public int Current => 0;
    public Task<bool>? MoveNextAsync() => null;
}

class D
{
    static void Main()
    {
        M(new C());
    }

    static async void M(C c)
    {
        await foreach (var x in c) { }
    }
}
```

**Expected Behavior**:
`warning CS8602: Dereference of a possibly null reference.` reported for `c` in `await foreach (var x in c) { }`

**Actual Behavior**:
No warnings. The program crashes at runtime with a `NullReferenceException`

**Notes**
Roslyn seems to be aware of nullability annotations of `GetAsyncEnumerator` methods but fails to check `MoveNextAsync`'s nullability. If you annotated `GetAsyncEnumerator` as returning `C?` you'll get the warning.

**Comment by jaredpar** [comment]
Thanks for reporting this. Confirmed this issue is fixed now 

https://sharplab.io/#v2:EYLgtghgzgLgpgJwD4GIB2BXANliwtwAEcaeBAsAFAACADIdQIwCsA3FVdQMwMBMhAYUIBvKoXEMeQgOJwYAQSgBPNAGMAopjCIIMAPYIAFAEpCAXgB8hGAAsAllHaUJkwnbQxBGBAhKfLhLROLtwMAGwAPMB6elgWAPyEALJ6AG5wAHJwAB4Kymom5laYOE4Avhw0/AAiVKLOEkxhDAAsyRDuJmIS9S4uSYZocADugibGwRIVlN3iTQwAHK3JhkKqxrMimyEAnIQAZgZwEKo2hIapEAiE2W5ohOsihNMu02VAA=
