### ISSUE TITLE
Passing extension method as method group causes invalid CS8622

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/roslyn#37040]
**Version Used**: 3.3.0-beta1-19327-04

**Steps to Reproduce**:

```c#
class C
{
    IEnumerable<string> M(IEnumerable<C> source)
    {
        var d = new D();

        return source.Select(d.Ext);
        //                   ^^^^^
        // CS8622 Nullability of reference types in type of parameter 'd' of
        // 'string Extensions.Ext(D d, C item)' doesn't match the target
        // delegate 'Func<C, string>'.
    }
}

class D { }

static class Extensions
{
    public static string Ext(this D d, C item) => "";
}
```

**Expected Behavior**:

No diagnostic.

**Actual Behavior**:

CS8622.

**Comment by jcouv** [comment]
Thanks for filing numerous and detailed issues, @drewnoakes 
I tried to repro this ([sharplab](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQBMQGoA+BiAdgVwBtCJhC4ACOXU8gWACgABABgqYEYAWAbkdfYcAdABkAlrgCOfBvwBMFAMKMA3owobBAZgA8nFgD4KAWQAUnXYqNQA9vgQBjOAEp1mtQ01eKANwgIKFAoAXgpcOAB3CgARU2cZN292AHYKW3snIQBlOHIHGFMUIQBRAA8YeMTvAHpqpPqkgD1m5qqvWqUsgA4ANjkFADkiEmAxQjEYAE8KGwAzCgQ4WcRqJwopgAc4KAoJdcmtmfmN/wgwOHgAgHIUK6O2zQ6r/Qoy+FwoMRsPkvLTaMCSCUu3gYGcdxQNm2uCuMAokBgDgAFuskZQYP4AOYXB4aDooXJwTEQeAUZ4AVh0iiB+gMVyEVQAvoxmbJmAoASoKKz+BweuwFG9qJ9vlBVFUmFpBPyXm9TDAkWIdgCUEDFCC4GCQkYAEQ6mSMoA)) and couldn't, so it may have been fixed already.

It may be even better to try and repro without dependency on Linq library, and using an explicitly implemented `Select` method instead, so that the repro is more self-contained. Thanks

**Comment by drewnoakes** [comment]
@jcouv I can no longer reproduce this in the project system repo 👍
