### ISSUE TITLE
Errors loading analyzers are not shown to the user

### ISSUE THREAD

**Issue by tmeschter** [dotnet/roslyn#3707]
I ran into this while investigating issue #3706.

If there is an error loading an analyzer in the compiler we create an instance of diagnostic AD0001, which has a `DiagnosticSeverity` of `Info`. Unlike errors and warnings MSBuild effectively ignores info messages, which means the user will never see AD0001 unless they notice an analyzer is not working , and know to check their build log for details.

I suggest we change this to be a warning.

**Comment by tmeschter** [comment]
@srivatsn @heejaechang @mavasani @shyamnamboodiripad @jmarolf Was there a reason we decided that a failure to load an analyzer should only produce an info-level diagnostic?

**Comment by mavasani** [comment]
This was specifically requested by an internal team, when an analyzer load failure was causing their builds to break. Note that the info diagnostics are produced by msbuild if the verbosity level is increased. I think we need to be cautious in breaking builds when third party components fail due to any reason.

Additionally, I think the right fix here is to change our msbuild tasks to not ignore info diagnostics. Historically, compiler diagnostics have been errors or warnings, and our Csc/Vbc msbuild tasks ignore anything not prefixed with an 'error' or 'warning', for non-verbose logging mode. Now that we can have analyzers generating info diagnostics (even for non-exception case), we should fix the tasks to always display info diagnostics.

**Comment by tmeschter** [comment]
@mavasani Couldn't the internal team have simply removed the problematic analyzer? Or fixed it, if they owned it?

I disagree with classifying a broken analyzer as merely informational. The user wanted the analyzer to be part of their build process, and it didn't work. That should at least be a warning.

**Comment by mavasani** [comment]
Hmm.. I can see both sides to it. Some might want a strict requirement on having functional analyzers, while some might want analyzer failures to be informational (as long the info diagnostics are always shown) so that it can be diagnosed, but not severe enough to break the build completely.

I am fine with either way. However, I think the more severe issue might be that we currently don't allow configuring the effective severity of exception diagnostics through compilation options (I am not sure about this, you may need to check). If we turn this into a warning, we should at least ensure it's severity could be configured.

Additionally, the msbuild task bug ought to be fixed. We must display info diagnostics from analyzers as part of build. Can you open a separate issue to track that work?

**Comment by srivatsn** [comment]
Making this diagnostic a warning now would be a breaking change for projects that have analyzers that are not loading. Let's see if more people run into this and ask for this to be a warning. 

I agree with @mavasani that we should fix the MSBuild issue. @tmeschter  can you please log an issue for that?

**Comment by srivatsn** [comment]
We've run into more instances of this causing problems and decided to take the break and increase the severity of AD0001 to warning.
