### ISSUE TITLE
"Time to all errors" much slower with VS versus rider/resharper

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#37205]
Repro steps:

Clone https://github.com/DotNetAnalyzers/ReflectionAnalyzers
`dotnet restore` the solution
open in a recent VS.
turn on FSA.
make a change to: C:\github\ReflectionAnalyzers\ReflectionAnalyzers\Helpers\Reflection\BindingFlags.cs

For example, edit `internal enum BindingFlags` to `internal enum BindingFlags1`

Wait for all errors to be reported.

This takes roughly 50 seconds on my machine.   For comparison, resharper does it in around 5 seconds (see the spinning icon in hte lower right):

![image](https://user-images.githubusercontent.com/4564579/61176439-ce281200-a575-11e9-9cde-df798428dc39.png)

That's an order of magnitude difference and greatly impacts the experience around being able to introduce issues then efficiently find and fix them.

**Comment by CyrusNajmabadi** [comment]
Tagging @kendrahavens @jinujoseph @heejaechang @mavasani .  This was reported by a customer.  I'm able to repro this myself.

It's unclear to me what's taking so long on the VS side TBH.  Perhaps it is trying to do things like figure out "suggestions" instead of prioritizing just getting and reporting compiler issues first?

**Comment by CyrusNajmabadi** [comment]
Note: this is not a large project (maybe around 20k tops).  Also, what's extremely strange is that just building only takes around 10 seconds on my machine.  So live errors (where we don't actually have to produce and emit IL) takes 5x longer than a real build.

**Comment by mavasani** [comment]
I will investigate and pull in @heejaechang as and when needed.

**Comment by mavasani** [comment]
Tagging @heejaechang as he is the expert on IDE analyzer execution algorith,

Just verified that this still repros on latest build even after CodeLens has been turned off. I believe this is due to the fact that we even though we prioritize the compiler analyzer amongst all the analyzers in the compilation, our IDE analyzer execution model still goes file by file and executes all analyzers on each file before moving to next file. We would need to change this to be a 2 pass model - first pass runs compiler analyzer on all pending files to analyze and second pass runs remaining analyzers on all pending files to analyze. Does that sounds correct Heejae?

**Comment by CyrusNajmabadi** [comment]
We've rewritten this.
