### ISSUE TITLE
"Generate GetHashCode()" is using System.HashCode when it's not available

### ISSUE THREAD

**Issue by MikiraSora** [dotnet/roslyn#37297]
**Version Used**: 
VisualStudio Community 2019
VisualStudio.16.Release/16.1.2+29001.49
[VS Info Detail](https://pastebin.com/9ziznmL4)
Project Target framework: .net framework 4.7.2

**Steps to Reproduce**:

In my [class](https://github.com/MikiraSora/sb2cssa/blob/master/sb2cssa/CSS/Property.cs) , auto generate Equals()/GetHashCode() and Implmenet IEquatable<>. [Pic](https://puu.sh/DTR7a/9e04e2b7c9.png)

**Expected Behavior**:

get error `"HashCode"无法访问,因为它具有一定的保护级别` [Pic](https://puu.sh/DTR8J/4dcad6d07a.png)

**Actual Behavior**:
Hope it work.

**Comment by huoyaoyuan** [comment]
**Better title:** "Generate GetHashCode()" is using System.HashCode when it's not available

#### Version Used:
VisualStudio Community 2019
VisualStudio.16.Release/16.1.2+29001.49
Target framework: .Net Framework 4.7.2

#### Steps to Reproduce:
Use quick action "Generate Equals() and GetHashCode()" on a class like:
```csharp
class C
{
    public int A { get; set; }
    public string B { get; set; }
}
```

#### Expected Behavior:
Some code does not use `System.HashCode`:
```csharp
public override int GetHashCode()
{
    var hashCode = -1817952719;
    hashCode = hashCode * -1521134295 + A.GetHashCode();
    hashCode = hashCode * -1521134295 + EqualityComparer<string>.Default.GetHashCode(B);
    return hashCode;
}
```

#### Actual Behavior
Some code uses `System.HashCode`:
```csharp
public override int GetHashCode()
{
    return System.HashCode.Combine(Name, Value);
}
```

#### Note
I cannot reproduce this on my machine with simple code.
I'm using 16.1.6

**Comment by CyrusNajmabadi** [comment]
We use System.HsahCode only if we were able to bind it to a symbol in their current project.  Not sure why it would be an error for them.  We need more details from teh user.

**Comment by canton7** [comment]
Google thinks that the message translates as "Unable to access because it has a certain level of protection".

I cloned the user's repo and it targets .NET Framework 4.7.2, so `System.HashCode` shouldn't be available. When I try that refactoring I get the old code that doesn't use `System.HashCode` (VS 16.2.0 Preview 3.0).

**Comment by MikiraSora** [comment]
I have tried upgrading my VS to latest version even VS preview and also reference dependence .dlls (not reference .csproj)，it's still same situation.
But it's work (use magic number) when I directly create new solution and .net framework Console project. So I think there are something in my solution/projects.

And I dont know what detail information I have to provide  , and I have create [new branch](https://github.com/MikiraSora/sb2cssa/tree/test) and you could clone and build directly.
