### ISSUE TITLE
IDE0060 false positive for Main(string[] args)

### ISSUE THREAD

**Issue by Twoleeland** [dotnet/roslyn#37329]
**Version Used**: 
MS VS Community 2019 v16.1.6

**Steps to Reproduce**:
namespace S0201___HelloWorld
{
	internal static class Program
	{
		private static void Main(string[] args)
		{
			Console.WriteLine("Hello World");
			Console.ReadLine();
		}
	}
}

**Expected Behavior**:
No message (-> blue bang).

**Actual Behavior**:
Message	IDE0060	Remove unused parameter 'args'	S0201 - HelloWorld	C:\SourceCode\Learning\Complete ASP.NET MVC Web Dev - Newbie to Ninja!\S0201 - HelloWorld\Program.cs	11	Active

![image](https://user-images.githubusercontent.com/1656150/61477185-f907d100-a98e-11e9-8d84-fe45dc847a66.png)

**Comment by CyrusNajmabadi** [comment]
That message seems correct to me.  You're not using hte args array.  So you can remove it from Main.  THe suggestion is appropriate.

**Comment by mavasani** [comment]
Yes, this is by design. The suggestion will not appear as soon as you start using `args` parameter in the Main method.

**Comment by Twoleeland** [comment]
Many project templates and settings use „Main(string[] args)“ for ages, regardless if used or not. And now, it‘s considered as warning/message and filling the warning/message box for nothing. For me, it looks like the whole thing is not so rigorously thought through... ;-)

**Comment by CyrusNajmabadi** [comment]
> it‘s considered as warning/message

It's not a warning.  It's just a simpel message letting you know that you're not using the args, and thus they can be removed.  This can be helpful both to let you either cleanup your code, or to bring your attention to something possibly unintended.  i.e. "oh... yeah!  i probably should read in the args and do something with them".

> For me, it looks like the whole thing is not so rigorously thought through... ;-)

It was.  The templates are designed to be the most helpful since it is likely that you will start wanting to use these.  However the messages are still there just to help you as you're coding for things that are relevant to bring to your attention.
