### ISSUE TITLE
Jump to reference when only one reference exists

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#37346]
<p>When you are selecting a variable or function you can use the shortcut 'shift + f12' to open the 'references-window'.</p> <p>It would be great to just skip this window if only one reference exists, and jump immediately to the reference itself.</p> <p>That way it would work the same as a the default behavior of 'f12' (jump into). If there are multiple references it shows the 'references-window'. If not it goes immediately to the reference itself.</p>

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/556260/jump-to-reference-when-only-one-reference-exists.html
VSTS ticketId: 866911_
_These are the original issue comments:_

Jane Wu [MSFT] on 5/5/2019, 03:09 AM (74 days ago): <p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;We'll provide an update once the issue has been triaged by the product team.</p>

**Comment by CyrusNajmabadi** [comment]
The problem here is that we have no idea how many references there actually are. So we're actually searchin for them and populating the list as we find them in an **asynchronous** manner.  

I experimented with this, but it turns out to be complex, especially in the interaction model.  i.e. what if the user starts the search, but then starts navigating around or editing themselves.  Once we're sure there's a single item, is it ok to just yank them away from what they're doing?  What aobut the symbol list?  Should we dismiss it because there was only one item?  etc. etc.

**Comment by CyrusNajmabadi** [comment]
We now do this.  If we get a single result fast enough, we jump to it.  Otherwise, we bring up FAR window and asynchronously load results into it as they are found.
