### ISSUE TITLE
IOptionPersister should be async

### ISSUE THREAD

**Issue by dibarbet** [dotnet/roslyn#37377]
Some IOptionPersister implementations are required to be initialized on the UI thread (e.g. [LanguageSettingsPersister](http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices/Implementation/Options/LanguageSettingsPersister.cs,6fa3bca20b86523a), [RoamingVisualStudioProfileOptionPersister](http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices/Implementation/Options/RoamingVisualStudioProfileOptionPersister.cs,28)

We should attempt to remove the initialize dependency on the UI thread / make IOptionPersister async.

See
https://github.com/dotnet/roslyn/pull/37360#discussion_r305378427
And
https://github.com/dotnet/roslyn/pull/37360#discussion_r305483079

Related - https://github.com/dotnet/roslyn/issues/27677 , https://github.com/dotnet/roslyn/issues/27678

**Comment by heejaechang** [comment]
it doesn't need to be IOpertionPersister being Async the conclusion. it is my opinion. but the solution for this problem should be made by team so that we don't get different opinion from different people.

this area (UI/JTF) it seems everyone has different opinions.

**Comment by CyrusNajmabadi** [comment]
Yeah.  I would just make these free threaded.  I'm not getting at all what about them requires UI thread access.  I would actually block work until this happens because we shouldn't be pushing more stuff to the UI thread (since it undoes all the work we've done to get off it).  Instead, if some other feature needs the UI thread, we should push on that feature having to move off.  Otherwise, this likely will *never* get done and this issue will just sit here for years, serving no real purpose :-/

**Comment by jasonmalinowski** [comment]
The agreement on this one from the design meeting is we should just ensure everything is free threaded. In this case, the setting service for roaming settings is free-threaded; if fetching the service also is then that solves that. For the LanguageSettingsPersister, the plan is just to bypass the shell API and read the settings directly, so that'd remove that complexity.

**Comment by sharwell** [comment]
The original issue above stands as filed by @dibarbet. Failure to adhere to the MEF requirement that _constructors_ of exported types be free-threaded has produced a high-hitting performance bug in Visual Studio (AB#761238). There is no known value in further complicating this issue by attempting to eliminate UI dependencies from the method implementations.
