### ISSUE TITLE
CSharpSyncNamespaceCodeRefactoringProvider crashes when refactoring class reference have a reference in g.cshtml.cs

### ISSUE THREAD

**Issue by imranbaloch** [dotnet/roslyn#37521]
In VS 2019 (community edition), When I try to move a class from namespace1 to namespace2, the Roslyn refactoring crashing by saying that `CSharpSyncNamespaceCodeRefactoringProvider changing document g.cshtml.cs file is not supported`. It looks like the refactoring of the razor generated file is not working(my file was at obj\Debug\netcoreapp2.2\Razor\Views\**\**.g.cshtml.cs).

**Comment by genlu** [comment]
@imranbaloch Thanks for reporting the issue. Is it possible for you to provide a sample project and steps to repro this crash? I don't know much about razor pages so those would be very helpful for my investigation.

**Comment by imranbaloch** [comment]
![Break](https://user-images.githubusercontent.com/667961/62300552-1311db00-b488-11e9-9075-8f66a7991846.gif)
[WebApplication2.zip](https://github.com/dotnet/roslyn/files/3457131/WebApplication2.zip)
A Gif and sample repro attached.

**Comment by genlu** [comment]
@imranbaloch Great! I will take a look. Thanks a lot!

**Comment by genlu** [comment]
While fixing this crash, I've found another bug using the repro project (#37891). No idea how I missed such a glaring bug 🤦‍♂️

**Comment by genlu** [comment]
Please note that the fix I made merely avoid the crash, it doesn't actually do the rename in the cshtml file. This is because we currently don't have a way to communicate the change back to razor, so we have to drop those changes. As a work around, you can try a find all reference on the entity to be renamed, and make sure all the references in cshtml files are opened in VS, then do a rename.
