### ISSUE TITLE
TypeLoaderExceptions using MsBuild 14 and VS2015 RC from MsBuild Task

### ISSUE THREAD

**Issue by hvanbakel** [dotnet/roslyn#3753]
I'm trying to write some code analysis rules in VS2015 RC and I'm having trouble getting it to run in VS2015RC. It works in VS2013, but in VS2015 I'm getting `TypeLoaderExceptions` trying to create an instance of `AdhocWorkspace`. I'm getting a number of exceptions, please see the attached test project for all of them.

The first excpetion is (if that might help diagnosing):
Method 'ResolveReference' in type 'Microsoft.CodeAnalysis.AssemblyReferenceResolver' from assembly 'Microsoft.CodeAnalysis.Workspaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.

The test project can be downloaded here:
https://drive.google.com/file/d/0B9ePsBgnLgh6WTFDUTRLazM1Y2M/view?usp=sharing

In order to test it, use the targets file to toggle the task on/off. Build it with the task off, then enable the task (by uncommenting) and start the debugger. This should run MsBuild 14 for this project and get you in the debugger with the exception raised pretty quickly.

I'm trying to get reassurance this is something that's known and will be addressed in the RTM.

**Comment by sharwell** [comment]
I believe the problem is you are building against the Roslyn RC3 release, and then trying to run your analyzers within Visual Studio 2015 RC. Visual Studio 2015 RC comes with the Roslyn RC2 release, which causes the failure. You should be able to use the Visual Studio 2015 NuGet Package Manager to explicitly downgrade your dependencies from the RC3 release to the RC2 release to get you moving again.

:memo: The RC3 packages should still work for testing on the command line, but the resulting analyzers won't load properly within Visual Studio.

**Comment by hvanbakel** [comment]
It was, changing all the references to the RC2 package fixed this!
