### ISSUE TITLE
Include namespaces with cut, copy, & paste

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#37562]
I'd like an option I can turn on that affects all cutting, copying, and pasting of C# code.  So when I cut or copy code from one C# code file, and then paste it into another C# file, using directives for the referenced namespaces will, upon paste, be added to the destination file.  It may also be nice, upon the cut, if namespaces that become unnecessary due to the cut are, upon the cut, removed from the source file.

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/648723/include-namespaces-with-cut-copy-paste.html
VSTS ticketId: 948171_
_These are the original issue comments:_

Jane Wu [MSFT] on 7/17/2019, 02:34 AM (12 days ago): <markdown><p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We’ll provide an update once the issue has been triaged by the product team.</p>
</markdown>

**Comment by jinujoseph** [comment]
@JoeRobich can you provide guidance on 'Add using' and see if that helps here

**Comment by ChainReactive** [comment]
Hi, I'm the original poster. @JoeRobich I like most know to hit Ctrl+. and then Enter to add a `using`.  But that becomes a pain with a copy & paste code that involves a ton of newly imported namespaces.

I think that adding using directives upon paste would be a small but useful productivity boost.  The latter part of my suggestion that "upon the cut, if namespaces that become unnecessary due to the cut are, upon the cut, removed", may be unnecessary.  One already can eliminate all unused namespaces in one fell swoop with _Remove and Sort Usings_.  Plus it's sometimes useful during refactoring to see which namespaces a code file no longer needs, before removing them.

**Comment by CyrusNajmabadi** [comment]
hi @ChainReactive .  When you cut/paste into a file, you should get an option to add all the usings for the section you just pasted if you bring up the smarttag/lightbulb using `ctrl-<dot>`.  Does that not work for you?

**Comment by JoeRobich** [comment]
Hi @ChainReactive, 

We support adding missing usings from pasted code in VS 2019. As @CyrusNajmabadi pointed out, we will show a lightbulb after paste if we detect missing using that we can fix for you. Making edits (including inserting newlines) following pasting will dismiss the lightbulb, which may be why you aren't seeing it. 

The other caveat is that we will add imports to namespaces that exist in the assemblies that your project currently references. If the namespace exists in a nuget package or require an added project reference, then those will not be fixed by this refactoring. For those from un-referenced assemblies you can visit them individually and decide how you want them fixed in the Quick Actions menu.

As for removing unnecessary namespaces following a cut, you can "Remove and Sort Usings" from Edit > Intellisense (or Ctrl+R,Ctrl+G).

-Joey

**Comment by ChainReactive** [comment]
Sounds cool.  I didn't notice that improvement since my VS 2019 upgrade, but I'll try it out next time the situation arises.  You can close this in the meantime.
