### ISSUE TITLE
Auto-complete for #region and #endregion in C# code

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#37563]
I consistently organize my C# code into common regions.  When I type #region and then a space, I'd like auto-complete suggestions consisting of the most common region names I use in my codebase.  Either that, or I'd like someplace in Options where I can manage this list.  I also label the end of my regions.  After typing #endregion and then space, I'd like the auto-complete suggestion to simply be the same label as appears after the closest above #region.

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/648964/auto-complete-for-region-and-endregion-in-c-code.html
VSTS ticketId: 948202_
_These are the original issue comments:_

Jane Wu [MSFT] on 7/17/2019, 02:34 AM (12 days ago): <markdown><p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We’ll provide an update once the issue has been triaged by the product team.</p>
</markdown>

**Comment by ChainReactive** [comment]
Hi, I'm the original poster.  I'd just like to add a few points.

The whole `#endregion MyLabel` could be an autocomplete item rather than the multiple steps of completing `#endregion`, typing a space, and another autocomplete for `MyLabel`.

I'd like to note the `#region` code snippet in case it comes up.  Although I organize nearly all my C# files into regions,  I _never_ use that code snippet.  That's because I don't organize code into regions until there's code to organize.  As for the _Surround With_ menu item, it's way to cumbersome to bother with.  It requires multiple steps that take me out of my code writing flow.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
