### ISSUE TITLE
Bad C# code formatting: using-statement without curly braces

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#37581]
```
// original code
using (var v = BeginScope())
using (A a = new A())
using (A a = new A(), b = new A())
using (BeginScope())
return;

// after VS2019 Format Selection (Ctrl+k, Ctrl+f)
using (var v = BeginScope())
using (A a = new A())
using (A a = new A(), b = new A())
using (BeginScope())
͏͏͏ ͏͏͏ ͏͏͏ ͏͏͏ return;

// suggested formatting:
using (var v = BeginScope())
͏͏͏ ͏͏͏ ͏͏͏ ͏͏͏ using (A a = new A())
͏͏͏ ͏͏͏ ͏͏͏ ͏͏͏ ͏͏͏ ͏͏͏ ͏͏͏ ͏͏͏ using (A a = new A(), b = new A())
͏͏͏ ͏͏͏ ͏͏͏ ͏͏͏ ͏͏͏ ͏͏͏ ͏͏͏ ͏͏͏ ͏͏͏ ͏͏͏ ͏͏͏ ͏͏͏ using (BeginScope())
͏͏͏ ͏͏͏ ͏͏͏ ͏͏͏ ͏͏͏ ͏͏͏ ͏͏͏ ͏͏͏ ͏͏͏ ͏͏͏ ͏͏͏ ͏͏͏ ͏͏͏ ͏͏͏ ͏͏͏ ͏͏͏ return;
```

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/664154/bad-c-code-formatting-using-statement-without-curl.html
VSTS ticketId: 956517_
_These are the original issue comments:_

Visual Studio Feedback System on 7/29/2019, 03:10 AM (31 hours ago): <markdown><p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>
</markdown>
_These are the original issue solutions:_
(no solutions)

**Comment by vatsalyaagrawal** [comment]
Repro in 16.3

**Comment by sharwell** [comment]
This behavior is definitely intentional, but I'm having trouble finding the tests for it.

**Comment by RobEin** [comment]
You can [here](https://github.com/antlr/grammars-v4/tree/master/csharp/examples) the test (you too have something to do with it :)

And a more realistic sample:
Similar to this formatting ...
`
using (StreamReader sr = File.OpenText("from.txt"))
{
 ͏͏͏ ͏͏͏ ͏͏͏ using (StreamWriter sw = File.CreateText("into.txt"))
 ͏͏͏ ͏͏͏ ͏͏͏ {
 ͏͏͏ ͏͏͏ ͏͏͏  ͏͏͏ ͏͏͏ ͏͏͏ sw.WriteLine(sr.ReadLine());
 ͏͏͏ ͏͏͏ ͏͏͏ }
}
`


I think the same code without curly braces should also be formatted in the same way:
`
using (StreamReader sr = File.OpenText("from.txt"))
 ͏͏͏ ͏͏͏ ͏͏͏ using (StreamWriter sw = File.CreateText("into.txt"))
 ͏͏͏ ͏͏͏ ͏͏͏  ͏͏͏ ͏͏͏ ͏͏͏ sw.WriteLine(sr.ReadLine());
`


The current formatting is less expressive for the statement order and does not fit with the syntax of the other block statements (if, for, while, ...) without curly braces:
`
using (StreamReader sr = File.OpenText("from.txt"))
using (StreamWriter sw = File.CreateText("into.txt"))
 ͏͏͏ ͏͏͏ ͏͏͏ sw.WriteLine(sr.ReadLine());
`

**Comment by CyrusNajmabadi** [comment]
@sharwell is correct.  This is *intentional* and has been since C# 1.0.  All our examples, docs, formatting rules, IDE features, etc. are designed around the idea that nested usings should not be indented.

> @CyrusNajmabadi do you happen to know where this is tested?

NoIndentForNestedUsingWithoutBraces perfectly checks for this case :)

We also have typing tests somewhere that validate that we will push it into this form.  I can look it up if you want, but i think the above just proves the point perfectly.

**Comment by CyrusNajmabadi** [comment]
> // I think the same code without curly braces should also be formatted in the same way:
> // the current formatting is less expressive for the statement order and does not fit with the syntax of 

This would be a massive regression and would likely upset a massive amount of the user base.  The reason for this formatting is that it's *hugely* common for some code bases to need to have a lot of usings in a row.  Upwards of 5+.  Having these now indent 5 more levels deep would make the code much less pleasant to work with and read.  It doesn't add any benefits as all teh scoping is effectively the same.  Namely, all the 'using' variables are in scope in the nest usings, and in the interior final block.  

Furthermore, it would *not* add any additional clarity.  The non-nested using has been a common and consistent style in the language since 1.0.  It's recognizable and immediately clear to the ecosystem.  It allows a reasonable amount of indentation, while being clear on what the scoping is.

**Comment by sharwell** [comment]
Yep, this is the corresponding test:

https://github.com/dotnet/roslyn/blob/b552a02360dd2f635b95bd0bf9eb8711f130b354/src/Workspaces/CSharpTest/Formatting/FormattingTests.cs#L5880-L5909

**Comment by RobEin** [comment]
>  The reason for this formatting is that it's _hugely_ common for some code bases to need to have a lot of usings in a row. Upwards of 5+. Having these now indent 5 more levels deep would make the code much less pleasant to work with and read.

Most codes don't have that depth.
Maybe a new formatting option?
VS menu:
Tools -> Options... -> Text Editor -> C# -> Code Style -> Formatting -> Indentation

**Comment by sharwell** [comment]
> Maybe a new formatting option?

Yes, we marked this Feature Request since it's a request for a new option. It will likely fall into the same category that other bugs linked to #31691 fall into: it's an uncommon formatting preference but impacted users can create a custom formatting extension that modifies the formatter to follow the rule in the project or projects where it's desired.

**Comment by ryzngard** [comment]
Design Review: Current style follows most frequent formatting for sequence of using statements. #31691 should consider this as a validation scenario.
