### ISSUE TITLE
IDE0017 (Use Object Initializer) should not be offered on using declarations

### ISSUE THREAD

**Issue by KrisVandermotten** [dotnet/roslyn#37675]
**Version Used**: Visual Studio 2019 Version 16.2.0

**Steps to Reproduce**:

Consider the following code:

    using System;

    internal sealed class Disposable : IDisposable
    {
        public string Property { get; set; }
        public void Dispose() { }
    }

    internal static class Program
    {
        private static void Main(string[] args)
        {
            using var disposable = new Disposable();

            disposable.Property = args[2];
        }
    }

Compile the code using

    <Project Sdk="Microsoft.NET.Sdk">

      <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>netcoreapp2.2</TargetFramework>
        <LangVersion>8.0</LangVersion>
      </PropertyGroup>

    </Project>

**Expected Behavior**:

IDE0017 should not be reported and the associated code fix should not be available.

**Actual Behavior**:

IDE0017 is reported on the using declaration. When the associated code fix is applied, it generates the following code:

    private static void Main(string[] args)
    {
        using var disposable = new Disposable
        {
            Property = args[2]
        };
    }

The behavior of this code is substantially different from the behavior of the original code. This may not be a problem, or even desired, when simply assigning to a variable. It would never be a problem when initializing a newly declared local variable, as the difference in behavior is not observable in that case (AFAIK).

However, a using declaration is more than simply a declaration, and the difference in behavior is certainly observable! The intent of the original code clearly was to construct an object, making sure that constructed object would be disposed at the end of the current scope, even if exceptions are raised in subsequent statements. By moving the assignments in those subsequent statements into an object initializer, that intent is violated. Indeed, in the above example, if `args[2]` throws, the Dispose method will not be called on the newly created Disposable.

IDE0017 should not be offered on using declarations.

PS: We discovered a real bug in a real application under development, that was introduced as a result of a developer applying the IDE0017 code fix on a using declaration.

**Comment by CyrusNajmabadi** [comment]
Note: this behavior was never intentional.  The "use object initializer" code was only written to handle local-decl intializers.  However, when local-decl initializers were updated to add support for the `using` keyword, this new behavior fell out.  This seems to have been missed during the testing of that new feature (unsurprising since it is subtle).  However, we should def be checking for this and disabling in this case due to the fair different semantics this now causes.

Tagging @dpoeschl for ensuring that the IDE test pass doc is updated to ensure this feature is checked when new language features come online.
