### ISSUE TITLE
Provide a compiler level API to list used (or the opposite unused) references per compilation

### ISSUE THREAD

**Issue by ivanbasov** [dotnet/roslyn#37768]
Required for https://github.com/dotnet/roslyn/issues/6763

**Comment by ivanbasov** [comment]
Tagging @gafter and @jaredpar

**Comment by gafter** [comment]
This is not possible (too complex for the bar) in 16.3.

**Comment by jaredpar** [comment]
This is a significant work item for the compiler team: both in design and implementation. It's not going to meet our bar for 16.3 and almost certainly won't meet the bar for 16.4 either.

**Comment by AlekseyTs** [comment]
The following aspects should be taken into consideration:
- If an assembly reference is removed, it might still be possible to compile successfully, but with different result (a different extension method is used, etc.). 
- Speculative binding triggered by SemanticModel should have no effect, shouldn't "pollute" the result.
- A linked (NoPia) assembly is never added to the AssemblyRefs in the resulting assembly, however it should be referenced by the compilation if any types are used.
- A references to a constant (constant fields/enum member) in source is replaced with underlying constant value in the resulting assembly and, by itself, doesn't add defining assembly to the set of AssemblyRefs. However, the build is going to fail if the defining assembly is not referenced by the compilation. 
- Intermediate assemblies in the type forwarding chain are not added to the set of AssemblyRefs, but they should be among compilation references in order to compile successfully when the forwarding chain is used.
- Some types are used by compiler implicitly without an explicit reference in source (runtime helpers, attributes, etc.). It is quite possible that compiler can silently change output when a certain API becomes available (no longer ambiguous if reference is removed) or becomes unavailable. 
- Compiler can embed or stop embedding some types (for example, attribute types for C# features) without resulting in a compilation error when the set of compilation references is changed.

**Comment by jcouv** [comment]
@AlekseyTs Can we close this?
