### ISSUE TITLE
Question: How do I use the "refs" tag?

### ISSUE THREAD

**Issue by NMSAzulX** [dotnet/roslyn#37760]
> Alternatively, projects that use .NET SDK can set PreserveCompilationContext build property to true. Publishing such project will copy reference assemblies for the framework the project targets to a refs sub-directory of the publish directory.

I used `< PreserveCompilationContext > true < / PreserveCompilationContext >` and published the WEB application, but I didn't see the refs subfolder. How do I use the refs tag?

![image](https://user-images.githubusercontent.com/16236903/62554702-2a93fe00-b8a4-11e9-9503-2d368bb83a26.png)

**Comment by KevinCathcart** [comment]
A quick trace though the code indicates that you also need to add:
```
<MvcRazorExcludeRefAssembliesFromPublish>False</MvcRazorExcludeRefAssembliesFromPublish>
```
By default the web sdk disables the refs folder, because it would otherwise always be generated due to internal details of how razor view pre-compilation works.

Adding that property tells the web that you really do want the refs folder.

**Comment by NMSAzulX** [comment]
@KevinCathcart  Thanks, It works .It's so Cool!
