### ISSUE TITLE
Typing #if causes outlining to expand

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#37910]
This is copied from https://github.com/OmniSharp/omnisharp-vscode/issues/3217

Put the following in an empty C# file:
```
namespace ConsoleApp3
{

    class Program
    {
    }
}
```

Use the "outlining" feature to collapse the definition of `Program`.
![image](https://user-images.githubusercontent.com/3751401/62883783-c29d4780-bce9-11e9-88d1-1674722849fe.png)

Now type `#if` above the class definition. Observe that `Program` expands.

![image](https://user-images.githubusercontent.com/3751401/62883836-e6608d80-bce9-11e9-87ee-d98533e10fa3.png)

**Comment by CyrusNajmabadi** [comment]
Probably tough to fix this.  It's akin to typing `/*` above code.  It fundamentally changes the meaning of the code, which affects what is collapsible or not.

**Comment by rchande** [comment]
@CyrusNajmabadi My guess is that error recovery puts the missing #endif trivia at the end of the file. Would it be possible instead to put it on the line immediately following #if?

**Comment by CyrusNajmabadi** [comment]
@rchande it would def be challenging (similar to if we did the same for an unterminated `/*`).  The basic problem then is that now you'd have to know that any edits *anywhere* after this should restart lexing at this point to see if the pp-directive/comment is now complete.  i.e.  imagine if you had an unterminated `/*` and we now just had the rest of the file be lexed/parsed normally.  Now, say later on you have `* /`  and you delete the space there.  The lexer/parser has to know it can't start incrementally parsing right there.  Instead, it has to restart from the earliest unterminated comment. 

It could totally be done.  But it would also be high risk due to the potential bugs in incremental scenarios this could introduce.

Def something that oculd be considered though!

**Comment by rchande** [comment]
@CyrusNajmabadi That makes sense. Thanks for the explanation :)

**Comment by CyrusNajmabadi** [comment]
Closing out.

**Comment by sharwell** [comment]
This is showing up in a few other cases involving syntax errors. In my experience, the solution is not nearly as complicated as presented above. When an edit to a document results in a syntax error being introduced, there are two options for handling it:

1. Ignore all previous outlining regions, and calculate the new ones to the best of the ability from the new syntax tree
2. Construct the new outlining regions by merging the current computed regions with information from the previous known good state

I've found that (2) is relatively easy to use in the presence of mismatched tokens (e.g. `{` without `}`, or `#if` without `#endif`), and the state is reset to "known" the next time all tokens are matched.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.  If we want to take the appraoch specified, we should assign to a dev/milestone and do it.
