### ISSUE TITLE
Include suffix in inserted text when completion item is committed

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn#37960]
We have a few completion providers that provide items with suffix. For example:

1.  `:` and ` =` for `AttributeNamedParameterCompletionProvider`
2.  `:` for `NamedParameterCompletionProvider`
3.  `:` for `PropertySubpatternCompletionProvider`
4.  `:` for `TupleNameCompletionProvider`

For those, the suffix will be shown as part of the item in the completion list, but will not be parted of inserted text when committed. Should we make the suffix as part of the inserted text in these cases?

![image](https://user-images.githubusercontent.com/788783/62970510-812d9a80-bdc4-11e9-9291-c385bc6dfd20.png)

Was originally suggested in #33250.

**Comment by CyrusNajmabadi** [comment]
These should become part of what is inserted into the document based on what the user types.  For example, in your cases, if the user types `<space>` we would likely want the colon added.  However, if they type `:` we would not as it would be redundant.

This is case by case dependent though.  For example, with named-args to an invocation we do not necessarily want the colon inserted if a comma is typed.  This is because sometimes people use the named-arg to then insert the name that will then be used to generate something.  So it depends on if this is strictly a place where you might be declaring something (like the name of a property) or if you could also hae references to other things.

**Comment by ryzngard** [comment]
Design Review: Vast changes in behavior would be bad in this area. We agree that typing `:` should result in insertion of `:` when shown in the completion list as long as we use this behavior consistently.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
