### ISSUE TITLE
diagnostic reported at the beginning of a file doesnt get updated when rule severity is updated.

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#3796]
![image](https://cloud.githubusercontent.com/assets/1333179/8466044/8d9eddd2-2003-11e5-9997-752d92d16fef.png)

add stylecop nuget package or create one yourself.

**Comment by mavasani** [comment]
@heejaechang The issue here is that SA1517 is implemented as a syntax diagnostic (SyntaxTreeAction) and the solution crawler deems compilation options changed as [ProjectConfigurationChanged](http://source.roslyn.io/Microsoft.CodeAnalysis.Features/R/81fe0b6d34d709b1.html) which doesn't include [SyntaxChanged](http://source.roslyn.io/Microsoft.CodeAnalysis.Features/R/728044ab0fc0361d.html), and hence causes only semantic analysis to be rerun. I'll fix ProjectConfigurationChanged to include SyntaxChanged, seems correct to you?

**Comment by heejaechang** [comment]
yep. seems correct.
