### ISSUE TITLE
Debug.Assert() causes wrong nullability in analysis when targeting older TFMs

### ISSUE THREAD

**Issue by roji** [dotnet/roslyn#37979]
With the following source code:

```c#
class Foo
{
    public void Bar()
    {
        string s = "";
        Debug.Assert(s != null, "No connector");
        Console.WriteLine(s.Length);
    }
}
```

The preview8 compiler generates `warning CS8602: Dereference of a possibly null reference.` on `s.Length`. If the assertion is removed the warning disappears.

This only happens when targeting netstandard2.0 (and possible other older TFMs) - with netstandard2.1 and netcoreapp3.0 the warning is not generated. I know C# 8 is officially supported only on the new TFMs, but this seems like quite an odd bug that's probably worth investigating.

csproj:

```xml
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <Nullable>enable</Nullable>
        <LangVersion>8.0</LangVersion>
    </PropertyGroup>
</Project>
```

**Comment by sharwell** [comment]
This bug makes `Debug.Assert` all but useless for me. I've already hit it on several occasions.

**Comment by 0xd4d** [comment]
Another common method is `string.IsNullOrEmpty()` which also doesn't have any nullable attributes if tfm is net4x/netstandard2.0.

My workaround I created Debug2/string2 classes with nullable attributes. It's ugly but it gets rid of all the warnings.

**Comment by roji** [comment]
FWIW it's not surprising that `string.IsNullOrEmpty()` isn't recognized by the compiler, as there's no intention (or possibility) of going back and annotating the BCL APIs in older TFMs. However, in the example above it's odd that Debug.Assert *invalidates* the non-nullability of s, which is typed as non-nullable.

**Comment by YohDeadfall** [comment]
Faced the problem with `IsNullOrEmpty` too. A workaround is to replace it by `value?.Length > 0`.

**Comment by 0xd4d** [comment]
> FWIW it's not surprising that `string.IsNullOrEmpty()` isn't recognized by the compiler, as there's no intention (or possibility) of going back and annotating the BCL APIs in older TFMs. However, in the example above it's odd that Debug.Assert _invalidates_ the non-nullability of s, which is typed as non-nullable.

You added a null check in your code, so you're telling the compiler that it can be null. Since Debug.Assert() doesn't have any nullable attributes in older tfm ref assemblies, the compiler can't know that it won't return if it's null. The C# compiler that was shipped in preview 7 seems to have special support for Debug.Assert()/string.IsNullOrEmpty(), but this support was removed in preview 8 so you're now getting warnings.

**Comment by YohDeadfall** [comment]
Opened #37995 to track `IsNullOrEmpty`.

**Comment by roji** [comment]
> You added a null check to your code, so you're telling the compiler that it can be null

How is a `Debug.Assert(s != null)` telling the compiler that s can be null? The point is that the type of s is `string`, not `string?`.

> the compiler can't know that it won't return if it's null

It's not a matter of what Debug.Assert returns (it returns void), but that it shouldn't be modifying the nullability of s in its analysis.

**Comment by sharwell** [comment]
@roji it may be possible to generate annotated reference assemblies for local builds by looking up each exposed API in the reference assembly, applying the annotations found in the most current release, and then emitting a new reference assembly that contains annotations.

**Comment by sharwell** [comment]
> How is a `Debug.Assert(s != null)` telling the compiler that s can be null?

I assume the expression `s != null` indicates to flow analysis that `s` might be null on the 'false' path. Otherwise you could have cases like this:

```csharp
public void Method(string value) {
  if (value is null) {
    // According to the static type of `value`, we don't have a warning here:
    Console.WriteLine(value.ToString());
    return;
  }
}
```

**Comment by roji** [comment]
> s != null is telling the compiler that it can be null. If you know that it can't be null, why do you add null checks?

Could be. In my mind, the variable in question has a type with a specific nullability, tracked by the compiler (non-nullable). At the point where the Debug.Assert() is executed, the compiler knows that `s` is non-nullable, and there's no reason for that to change because I perform a (silly) check.

In any case, we can wait for someone from the compiler team to provide the answer here.

**Comment by JamesNK** [comment]
I also get this.

![image](https://user-images.githubusercontent.com/303201/63240620-94e56f00-c2a4-11e9-8bd1-54a41672eabf.png)

```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview9-013927
 Commit:    e1f793b16d
```

**Comment by jcouv** [comment]
I think that's by design. `Debug.Assert` is not annotated in that implementation.

The same warning occurs if you write `_ = x != null;`. That's a pure null test, which implies that the value may be `null` (from a public API for example). If you do an explicit comparison with `null`, we take it seriously.

**Comment by jcouv** [comment]
Will discuss further. From discussion with @cston, it is tempting to give the compiler special knowledge of this API.

**Comment by roji** [comment]
> That's a pure null test, which implies that the value may be null (from a public API for example). If you do an explicit comparison with null, we take it seriously.

I guess I understand the logic, but in this case the variable is known to be type-wise non-nullable - it's not oblivious - so it's odd. Anyway thanks for looking at this.

**Comment by JamesNK** [comment]
> I think that's by design. `Debug.Assert` is not annotated in that implementation.

I know that is the simple, pure answer, but I'd urged you to consider how OSS .NET libraries are going to use nullable types and their experience when turning them on. Almost every library on NuGet today is targeting netstandard2.0, net4xx, netcoreapp2.0, etc. None of these targets have nullable type annotations.

Not providing a good story OSS .NET library developers to turn on nullable type annotations will hinder the feature's adoption. Asking OSS libraries to move to netstandard2.1 isn't a solution, because only netcoreapp3.0 supports 2.1. For platform compatibility libraries should continue targeting netstandard2.0.

**Comment by jaredpar** [comment]
Thanks for the feedback. We do understand this presents challenges to customers currently targeting netstandard2.0, and that we're in a bit of a weird place right now where new features are only for .NET Core. Since this feature heavily involves the platform, and the platform evolves for .NET Core moving forward, the decision was to focus on that and not back port the annotations to older target frameworks
