### ISSUE TITLE
Grammar issue in SourceTextContainer exception message

### ISSUE THREAD

**Issue by SLaks** [dotnet/roslyn#38]
`TextEditorResources.TextcontainerIsNotAnSource` in EditorFeatures.Text reads

 > textContainer is not an SourceTextContainer that was created from an ITextBuffer.

That should be `a`, not `an`.  (I assume it used to be an interface)

**Comment by Giftednewt** [comment]
@theoy @Pilchie I'd like to take this on.

I notice that the name of the resource along with the casing also appears to be incorrect. I think the same is also true for the resource ```TextEditorResources.TextIsNotAnSourcetextThat``` and it's corresponding value is 
> text is not an SourceText that was created from an ITextSnapshot
Which should probably also be changed to ```a``` not ```an```

**Comment by Pilchie** [comment]
@Giftednewt sounds great!  I agree with the other changes you suggest too.  We're not *quite* ready to start hitting the merge button on PRs yet, but hopefully it will be very soon.

That shouldn't start you from preparing and submitting one though - we just won't be able to merge it for a bit.  Another thing you can do in the meantime is sign a Contributor License Agreement at https://cla.dotnetfoundation.org/

Thanks!

**Comment by Giftednewt** [comment]
@Pilchie Thanks. I'll get on and make the changes. Pretty sure I'd signed a CLA previously as I made a contribution when you were hosted on Codeplex. If it has changed and needs to be re-signed I'll get on and do it.

**Comment by Pilchie** [comment]
Now that we're part of the .NET Foundation instead of MS OpenTech there is a new CLA :frowning:.

**Comment by Giftednewt** [comment]
Ok. Done.

**Comment by Giftednewt** [comment]
@Pilchie On further inspection it appears as though ```TextEditorResources.TextIsNotAnSourcetextThat``` does not appear to be referenced from anywhere in the codebase. If this is not used anywhere in the codebase, even in parts that have not been opened up to the community it would seem that it could be removed instead of fixing the typos.

With regards to the other typo fix I can't see any unit test that would currently cover the scenario where this is thrown from the argument exception in TextEditorFeatures -> Extensions.cs.

I'm intending to add a unit test class into EditorServicesTest -> Extensions as this would seem to be the correct place for this. If you're happy with that then I'll go ahead and add the unit test before submitting a pull request?

**Comment by JoshVarty** [comment]
@Giftednewt I suspect it may be used it parts of the code base that are not yet open source.

**Comment by Pilchie** [comment]
All that sounds great.  Also, in response to @JoshVarty's comment (that I don't see anymore), `TextEditorResources.TextIsNotAnSourcetextThat` doesn't seem to be used internally either.
