### ISSUE TITLE
Problems with BC42376

### ISSUE THREAD

**Issue by shyamnamboodiripad** [dotnet/roslyn#3804]
A few of issues here -
1. Why is BC42376 a warning and AD0001 an info? Both are complaining about exceptions encountered by the compiler when it is processing analyzers and both should arguably have the same severity.

2. AD0001 is a lot nicer since it embeds the exception stack trace in the expanding portion of the error list entry making it easier for analyzer authors to debug the problem / for end users to share the problem details with analyzer authors. Perhaps we should do the same for BC42376 and include more details about the exception in the expanding section.

3. Minor issue - The error message for BC42376 ends with two periods. We should remove the redundant period.

![capture](https://cloud.githubusercontent.com/assets/10579684/8467691/925ef72c-2016-11e5-8d0a-257db68c972f.PNG)

**Comment by mavasani** [comment]
I think the issue here is by design.

1. AD0001 is the diagnostic generated for an exception thrown during analyzer callback. Even though for the screenshot, it seems to be related to analyzer loading but not from analyzer code itself  (TypeInitializationException), we have no way to know that from the driver. For the driver, a specific instance of an analyzer from the analyzer assembly threw some exception on one particular callback. We need to have this diagnostic as an info to avoid a single analyzer to break builds when /warnaserror is true.

2. BC42376 or diagnostics reported in [ResolveAnalyzersFromArguments](http://source.roslyn.io/Microsoft.CodeAnalysis/R/c8d1cea9dc9db656.html) are exceptions when trying to load analyzer assembly or instantiate analyzer types. These issues are related directly to the analyzer assembly and are hence more severe, warranting a fix. Probably, the severity of these should be consistent with AD0001, but I don't see a lot of value add in changing this now.

The exception stack trace is also more helpful for exceptions from analyzer code itself (i.e. AD0001). For BC42376, the exception stack trace will not be too useful as we are not executing any user code.

@shyamnamboodiripad Let me know if you disagree :)
