### ISSUE TITLE
Undo stack title is incorrect when fix all occurences is invoked

### ISSUE THREAD

**Issue by shyamnamboodiripad** [dotnet/roslyn#3806]
1. Create a new project with some unused namespace imports at the top of code files
2. Open one such code file
3. Ctrl + . on a line containing unused usings

If I apply the fix by hitting enter, the fix is correctly applied and I see the following text at the top of the undo stack.

![capture](https://cloud.githubusercontent.com/assets/10579684/8467882/06c2d686-2019-11e5-8e26-4b5d307bc51e.PNG)

However, if I select "Fix All Occurences: Project" instead, the undo stack title is updated to 'Project'. This is confusing. The title should still probably read 'Remove Unnecessary Imports' just like the above case.

![capture2](https://cloud.githubusercontent.com/assets/10579684/8467908/610c16ac-2019-11e5-84db-b38f96750911.PNG)

**Comment by dpoeschl** [comment]
This also applies to the "Preview changes" flavored action, and the nested warning suppression actions (anything that isn't a top-level item in the lightbulb menu).

**Comment by dpoeschl** [comment]
@mavasani Can you explain what a FixMultipleCodeAction is, and how they might want their Titles & UndoTexts set up? I went back to bug recently and it looks like this type was introduced recently.

**Comment by mavasani** [comment]
@dpoeschl FixMultipleCodeAction is basically a different flavor of FixAll where the diagnostic source for the fix is a prior known set of diagnostics that can belong to any document in the solution, and hence has a FixAllScope.Custom. For example, right now it used to trigger Suppression fixer on issues selected in error list - you know beforehand what needs to be fixed. Additionally, this means the suggested code action might not have any source subject buffer on which the fix is triggered. Each host triggering such a fix (say error list for example) will need to provide an appropriate title for such a fix.

There are quite a few open issues around the design of the scenario, and should go through a thorough design review before anything is made public for this scenario.

**Comment by CyrusNajmabadi** [comment]
I don't repro this anymore.
