### ISSUE TITLE
Local functions not available in intellisense/autocomplete

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#38074]
**Version Used**: 16..3.0 Preview 2.0

**Steps to Reproduce**:
```C#
namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            Loca|

            void Local() { }
        }
    }
}

```

**Expected Behavior**: Local function offered in autocomplete list and provided with intellisense support when typing arguments.

**Actual Behavior**: Local function not in the list and gets colorized only after arguments match the signature.

**Comment by gafter** [comment]
I'm not sure that the parser would recognize that there is a local function in your example, preceded as it is by a garbage token.

**Comment by miloush** [comment]
```C#
static void Main()
{
    Loca

    switch (Console.BackgroundColor)
    {
        default:
            break;
    }

    Main();
            
    void Local() { }
}
```

This does not help either. 

Even in code with no syntax errors,
```C#
static void Main()
{
    Local(4, 2);

    void Local(int a, int b) { }
}
```
The _Display parameter info_ command does not show any intellisense at the callsite.

**Comment by gafter** [comment]
Hey IDE folks, is there some API not behaving as expected here, or is this just not implemented in the IDE?

**Comment by sharwell** [comment]
Regression in 16.3 Preview 2 relative to 15.9.

**Comment by svick** [comment]
As far as I can tell, this regression was introduced by https://github.com/dotnet/roslyn/pull/35822, which probably explains why the issue happens in `static` methods, but not in instance methods.

**Comment by ivanbasov** [comment]
@gafter the issue is totally on the compiler side. The semantic model does not return local functions defined inside static members. I debugged it and found that local functions are filtered out inside static scopes if is no static modifier provided for it.

I would consider this line: https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Portable/Binder/Binder_Lookup.cs#L1468

Maybe it is worth to change it to 
`                    return symbol.RequiresInstanceReceiver();`

**Comment by svick** [comment]
I have submitted https://github.com/dotnet/roslyn/pull/38117, which fixes the completion issue using the approach suggested by @ivanbasov.

But that still leaves the *Display parameter info* issue. In other words, the following test will still fail, even if that PR is merged:

https://github.com/dotnet/roslyn/blob/62918fc39895da53eb4ce76b4a83a949746220e8/src/EditorFeatures/CSharpTest/SignatureHelp/InvocationExpressionSignatureHelpProviderTests.cs#L2421-L2437

I suspect the problem is here:

https://github.com/dotnet/roslyn/blob/5551fad9651b91dcc64a965cfd93e1da4f386273/src/Features/CSharp/Portable/SignatureHelp/InvocationExpressionSignatureHelpProvider_MethodGroup.cs#L56-L60

I think this could be resolved by using `RequiresInstanceReceiver` too, except that `RequiresInstanceReceiver` is internal, so it can't be used here. What would be the right fix here? Would it make sense to add `RequiresInstanceReceiver` to `ISymbol`? (It's currently only defined for C# `Symbol`.)

**Comment by gafter** [comment]
@333fred What do you think is the right approach to address this?

**Comment by ivanbasov** [comment]
Thank you for your help, @svick ! The change to InvocationExpressionSignatureHelpProvider_MethodGroup.cs seems to be reasonable for me. If the compiler team is OK with the approach in general (@333fred to review), please go ahead and add it to #38117 as well

**Comment by 333fred** [comment]
I like the idea of adding the API, though I'm not sure of the naming. `RequiresInstanceReceiver` was fine when it was an internal API, but it doesn't fit with the rest of the properties on `ISymbol` as a public API. Perhaps `IsInstanceMember`?

**Comment by 333fred** [comment]
Additionally, the docs will need to be clear where the potential differences between these two properties lies, as a naive first glance makes these properties appear identical.

**Comment by 333fred** [comment]
@svick @ivanbasov, is there a reason that the IDE can't just additionally filter based on `IMethodSymbol.MethodKind`? The filter could be `Where(m => m.IsStatic || m is IMethodSymbol { MethodKind: MethodKind.LocalFunction })`, right? Am I missing something here that warrants adding a new API here?

**Comment by ivanbasov** [comment]
@333fred not sure I understand you. Do you mean that you want to keep the binder code as is and correct IDE only by explicit adding items with `|| m is IMethodSymbol { MethodKind: MethodKind.LocalFunction }` to the list? If so, is the binder code correct in the place for other scenarios?

**Comment by 333fred** [comment]
That's correct.

**Comment by CyrusNajmabadi** [comment]
@333fred @ivanbasov  i'm a little confused.  It appears as if the issue is:

>  I debugged it and found that local functions are filtered out inside static scopes if is no static modifier provided for it.

Could you be explicit about where that filtering is happening?  Is it in IDE or code or in compiler code?

If it's in IDE code, we could certainly fixup teh filtering.  If it's compiler code, it's unclear to me what IDE could do as the filtering is happening before we ever see the symbol.

**Comment by 333fred** [comment]
@CyrusNajmabadi https://github.com/dotnet/roslyn/issues/38074#issuecomment-522800766. This is in the IDE layer, not the compiler. I'm not sure what RequiresInstanceReceiver would even do for you here. The IDE just needs to include all local functions that are in scope.

**Comment by CyrusNajmabadi** [comment]
>The IDE just needs to include all local functions that are in scope.

Ok...  :)  But the IDE doesn't have logic for that.  All we call is `LookupNames` to ask for the "all [...] that are in scope".  

I think the problem is that the compiler is considering this *not* in scope, when we really want it to be for intellisense purposes in this scenario.

IDE def doesn't want to reimpleemnt the "include all XXX in scope" logic.  That's basically reimplementing the complex compiler rules that exist here and one of the reason we don't do that and instead use LookupNames instead.

Does that help clear things up?

**Comment by CyrusNajmabadi** [comment]
I misunderstood the repro.  A simpler repro is:

```c#
    static void Foo()
    {
        void Bar()
        {

        }

        Bar$$ // Bar should appear here but doesn't.
    }
```

**Comment by CyrusNajmabadi** [comment]
Ok.  So i grossly misunderstood things.  I think there are two feasible solutions.  HOwever, i personally think it's totally ok to just do the expeditious thing here.  i.e. we should just update https://github.com/dotnet/roslyn/blob/5551fad9651b91dcc64a965cfd93e1da4f386273/src/Features/CSharp/Portable/SignatureHelp/InvocationExpressionSignatureHelpProvider_MethodGroup.cs#L59 so that it checks:

`m.IsStatic || m is IMethodSymbol { MethodKind: MethodKind.LocalFunction }`

I'm totally amenable to the idea that `.RequiresInstanceReceiver` is "more right".  But i think the value is so narrow, and the cost of hte public APi so high, that we should just take the expeditious route.

**Comment by vatsalyaagrawal** [comment]
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/985838

**Comment by ivanbasov** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/38117 (16.4 P1) and https://github.com/dotnet/roslyn/pull/38811 (16.4 P2). I do not see open issues with this. Please let me know if there are.
