### ISSUE TITLE
`static` Local Functions are not being emitted as static

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#38143]
```cs
using System;
public class C {
	static void M()
	{
  		static void localFunction() { }
        Action a = localFunction;
	}
}
```
Capturing the local function in an `Action` is causing it to be emitted as an instance function on an inner class, instead of being a static method.
https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxASwDZICYgNQA+AAgEwCMAsAFBEDMABKfQML0De1AkEWQGyMAWegFkAFAEouHKvXqdufQfQwB7AMYQMRAKww0KgHYT29AL7VZlyzxL0I9ALzL1mnXsMBuLuaqmgA==

**Comment by gafter** [comment]
@333fred I can see that this would be unexpected, but it implements a tradeoff (the inner class must be created, but invocations are faster).  Why do you classify it as a bug?

**Comment by ZacharyPatten** [comment]
I was asking about this code (C# 8.0; .NET Core preview 8), and @333fred concluded there was a bug:

```csharp
static void Main(string[] args)
{
  static void localFunction() { }
  Action action = localFunction;
  Console.WriteLine(action.Method.IsStatic);
  // Output: False
}
```

I wasn't sure if that output was intended or not. If that output is intended, that is going to confuse people, and maybe "static" wasn't a very appropriate keyword. :P

Question (since @gafter implied this might not be a bug): _If it is intended that "static" local functions be compiled to instance methods instead of a static methods,_ would the MethodInfo.IsStatic property ever be altered for "static" local functions?

**Comment by gafter** [comment]
The C# language won't say anything about the `MethodInfo`'s `IsStatic` behavior for a delegate created from a local function.  Nor when it is created from a lambda.  Local functions are not methods.  It is possible that this is a bug but it is also likely it is intentional.

**Comment by 333fred** [comment]
@gafter it's a bug because future work intends to allow static local functions to be used for native interop. This would break that scenario, and at least mine and @agocke's understanding was that static local functions would be emitted as static members.

**Comment by agocke** [comment]
@gafter This behavior is a bug. The proposal has a mention of the intent here: https://github.com/dotnet/csharplang/issues/1565#issuecomment-409288581

**Comment by tannergooding** [comment]
This was also hit for some interop code being contributed to a personal project of mine. Currently validating delegates don't have a `Target` so that code can be cleanly converted to use function pointers once they are out.
