### ISSUE TITLE
IDE0067 fires for IHttpClientFactory.CreateClient(), but not IHttpClientFactory.CreateClient("foo")

### ISSUE THREAD

**Issue by olivermue** [dotnet/roslyn#38204]
**Version Used**: 
Visual Studio Enterprise 16.2.3

**Steps to Reproduce**:
Add the following method in your project:
```csharp
public void DoSomething(IHttpClientFactory clientFactory)
{
    var clientWithWarning = clientFactory.CreateClient();
    clientWithWarning.BaseAddress = new Uri("https://localhost");

    var clientWithoutWarning = clientFactory.CreateClient("Foo");
    clientWithoutWarning.BaseAddress = new Uri("https://localhost");
}
```

**Expected Behavior**:
Get either an IDE0067 warning for both methods or none.

**Actual Behavior**:
The first method without parameters produces a warning message IDE0067, the second doesn't.

**Comment by vatsalyaagrawal** [comment]
Manish for initial investigation.

**Comment by mavasani** [comment]
Minimal repro:
```csharp
using System;

class C
{
    public void DoSomething(IHttpClientFactory clientFactory, Uri uri)
    {
        var c1 = clientFactory.CreateClient();
        var c2 = clientFactory.CreateClient("Foo");
    }
}

public interface IHttpClientFactory
{
    HttpClient CreateClient();
}

public static class Extensions
{
    public static HttpClient CreateClient(this IHttpClientFactory clientFactory, string v) => new HttpClient();
}

public sealed class HttpClient : IDisposable
{
    public Uri BaseAddress { get; internal set; }

    public void Dispose()
    {
    }
}
```

**Comment by mavasani** [comment]
Couple of points to note:

1. The difference in IDE0067 violations between `c1` and `c2` is due to the fact that one of them is an interface method invocation while the other is a static extension method invocation.
2. IDE0067 rule implementation has a heuristic that treats static methods whose name starts with "Create" as factory methods that create new instances. This heuristic matches the implementation of [CA2000](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2000-dispose-objects-before-losing-scope?view=vs-2019), which is the FxCop original rule from which this rule was ported over. This causes the rule to treat `c2` as a newly created disposable instance, such that the caller has dispose ownership, while the interface method invocation is treated as merely a query to get an existing disposable instance, hence dispose ownership is assumed to be with callee. Note that a heuristic that considers the interface method invocation as a creation is likely to be very noisy.

We can consider making the heuristic about static extension methods much tighter - instead of considering all static methods whose name starts with Create as factory methods, we can only do so for known methods/types where we are sure they are factory methods.

@olivermue it is safe for you to add a suppression for this case until the heuristic is modified.

**Comment by olivermue** [comment]
I already added a suppression in my case. I just wondered why both methods are behaved differently and simply didn't recognized that one is an extension method. So which of your two proposals (make tighter or wider) finally wins doesn't matter, as long as both are treated equally.
