### ISSUE TITLE
'Object initialization can be simplified' attempts to initialize read-only properties.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#38216]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/704045/object-initialization-can-be-simplified-attempts-t.html)._

---
Accidentally I think I may have found a bug.
Visual studio suggests me to initialize read only properties if I try to initialize them below (Refer to screenshots).

I was just refactoring old code that had Point exposed to set, so this glitch occured naturally.

My simplified version of `Point`

```
public struct Point 
{
	public int X { get; }
	public int Y { get; }

public Point(int x, int y) 
        {
		X = x;
		Y = y;
	}
}
```

---
#### ltlion on 8/21/2019, 03:55 PM: 

url version of the [screenshot](https://cdn.discordapp.com/attachments/202046273052868608/613868559109455882/unknown.png)
#### Visual Studio Feedback System on 8/22/2019, 03:40 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by LtLi0n** [comment]
I made it over! o/

Probably indexing it with labels:
`IDE-Formatter` or `IDE-IntelliSense` would be helpful for a proper team to fix this.

**Comment by CyrusNajmabadi** [comment]
This seems by design.  The new code is no less correct then the code it's offering to replace.  The idea here is to just let you be able to easily swap between forms.  Any sort of offerings of changes in code that has errors in it are simply in a best effort basis to allow people to keep functioning even in the presence of problems.

**Comment by LtLi0n** [comment]
I agree with your view, but it just seems slightly odd for a tool that is supposed to hint what's correct, to try to initialize read-only properties.

I would consider having a setting for that, just to have an option to
> easily swap between forms

as you mentioned.

But if a setting was available, by default it should hint the way you should be doing things, as guidance so initializing read-only look weird.

**Comment by CyrusNajmabadi** [comment]
Code is most often in error.  When in error you have the choice of being more restrictive and possibly causing things to be less useful to the user.  Or, you have the choice of being more encompassing, and allowing someone to still proceed.  In this case, given that there were assignments to those properties, the feature effectively says "ah, perhaps the user intends to make these mutable.  i don't want to force them to have to do that first, i'll let them go to the obj-initializer form, and then they can fix up the properties next, instead of needing it to be the reverse direction".
