### ISSUE TITLE
Spikes in CPU usage when resolving references to methods implementing System.IDisposable

### ISSUE THREAD

**Issue by SirIntruder** [dotnet/roslyn#38223]
Finding references to a method that implement System.IDisposable in any non-trivially sized project takes a long time and causes a big spike in CPU usage. I replicated this behaviour in VS2019, VS2017 and VSCode with omnisharp. It's impossible to avoid this issue if you want to use Code Lens.

After making a cpu profile, it seems that core issue is here:
https://github.com/dotnet/roslyn/blob/d570d6cc2e0d12a1c587bd2cd83d6fe3215d51e2/src/Workspaces/Core/Portable/FindSymbols/FindReferences/DependentProjectsFinder.cs#L442-L464

Namely, to find references to MyClass.Dispose(), Roslyn first tries to find all classes that implement System.IDisposable, with first step being filtering all projects in solution to those which have access to assembly containing System.IDisposable. Checking whether a project has access to the said assembly involves creating a whole new compilation object, and this is what seems to be taking most of the cpu cycles.

![DisposeProfile](https://user-images.githubusercontent.com/5102661/63548614-e3a63980-c52e-11e9-861d-a1de7deddcb3.png)

I assume what @CyrusNajmabadi remarked in the TODO would resolve/help with this issue?

**Comment by jmarolf** [comment]
In past we had optimizations here to not do full FAR on `IDisposeable` and `object` members (like `ToString`) since there are likely going to be tens of thousands of those in large project and finding every location of `ToString` is not worth the electricity. We should add a filter in front of our Call to `SymbolFind.FindRefernces` to exclude these types or do a more targeted type search.

**Comment by CyrusNajmabadi** [comment]
Can a repro/trace be supplied here?
