### ISSUE TITLE
SemanticModel.GetSymbolInfo or GetDeclaredSymbol for ObjectCreationExpressionSyntax returns null

### ISSUE THREAD

**Issue by zhaoyingju** [dotnet/roslyn#3825]
I am trying to get symbol info from ObjectCreationExpressionSyntax object but failed.

Here is example that reproduce the problem:

```
public IEnumerator<KeyValuePair<TKey, TValue>> GetEnumerator()
        {
            foreach (var kvp in _hm.Where(x => x.Key.IsAlive))
            {
                yield return new KeyValuePair<TKey, TValue>(kvp.Key.Target, kvp.Value);
            }
        }
```

find new KeyValuePair<TKey, TValue>(kvp.Key.Target, kvp.Value) symbol failed

**Comment by ygra** [comment]
Why would `GetDeclaredSymbol` even work here? My understanding was that it will return a corresponding symbol from a *declaration* syntax node. An object creation expression isn't exactly the declaration of something.

**Comment by jaredpar** [comment]
Thanks for taking the time to report this issue.  Unfortunately this behavior is by design.  From the documentation 

```
        /// A syntax node that is a declaration. This can be any type
        /// derived from MemberDeclarationSyntax, TypeDeclarationSyntax, EnumDeclarationSyntax,
        /// NamespaceDeclarationSyntax, ParameterSyntax, TypeParameterSyntax, or the alias part of a
        /// UsingDirectiveSyntax
```

The type `ObjectCreationExpressionSyntax` is not one of the supported types.

**Comment by Pilchie** [comment]
@jaredpar The title mentions `GetSymbolInfo` as well, which should work.

**Comment by jaredpar** [comment]
@Pilchie ah okay.  Missed that.

**Comment by AlekseyTs** [comment]
It is hard to say definitively whether the behavior of GetSymbolInfo is expected in the scenario or not, because the repro is incomplete. We don't know if the binding of ObjectCreationExpressionSyntax succeeds or fails, but that is important. If it succeeds, GetSymbolInfor should return a symbol for the constructor used. If it fails, then the symbol should be null and CandidateSymbols should not be empty. The current behavior matches these expectations.
