### ISSUE TITLE
Should the constant value propagate to ICoversionOperation?

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#38272]
Consider this code:
```cs
void M(int? x) {
    if (x == 1) {
    }
}
```
Currently `IOperation.ConstantValue` returns null for the literal `1` because it's wrapped in a `IConversionOperation`.

I think this behavior is unintuitive because we need to fallback to use `SemanticModel.GetConstantValue` which works as expected.

**Comment by alrz** [comment]
This is a passing test for the scenario above
```cs
        public void Test()
        {
            string source = @"
class C
{
    public void F(int? i)
    {
        var a = /*<bind>*/i == 1/*</bind>*/;
    }
}
";
            string expectedOperationTree = @"
IBinaryOperation (BinaryOperatorKind.Equals, IsLifted) (OperationKind.Binary, Type: System.Boolean) (Syntax: 'i == 1')
  Left:
    IParameterReferenceOperation: i (OperationKind.ParameterReference, Type: System.Int32?) (Syntax: 'i')
  Right:
    IConversionOperation (TryCast: False, Unchecked) (OperationKind.Conversion, Type: System.Int32?, IsImplicit) (Syntax: '1')
      Conversion: CommonConversion (Exists: True, IsIdentity: False, IsNumeric: False, IsReference: False, IsUserDefined: False) (MethodSymbol: null)
      Operand:
        ILiteralOperation (OperationKind.Literal, Type: System.Int32, Constant: 1) (Syntax: '1')";
            var expectedDiagnostics = DiagnosticDescription.None;

            VerifyOperationTreeAndDiagnosticsForTest<BinaryExpressionSyntax>(source, expectedOperationTree, expectedDiagnostics);
        }
```
Notice that the `IConversionOperation` node does not have a constant.

While it's true that expression of nullable types can't have a constant value, but I think CosntantValue should just propagate to parent nodes, otherwise it's is less useful in actual IDE scenarios.

that being said, I don't undrestand on what basis `SemanticModel.GetCosntantValue` does return a value for the same node?

**Comment by AlekseyTs** [comment]
> Notice that the IConversionOperation node does not have a constant.

That is expected, because according to C# language rules a conversion like that is not a constant expression and therefore doesn't have a constant value. Only nodes representing valid constant expression per C# rules should have a ConstantValue associated with them.

>  I don't undrestand on what basis SemanticModel.GetCosntantValue does return a value for the same node?

SemanticModel returns a value for syntax node representing the literal (without any implicit conversions applied), in IOperation tree that corresponds to the ILiteralOperation node (the one that is not marked as IsImplicit, and the one that you should get from SemanticModel.GetIOperation API for the syntax node). Note that the ILiteralOperation node has ConstantValue.

**Comment by 333fred** [comment]
Agreed with Aleksey. The semantic model walks through the implicit conversion for you because you cannot do so yourself from syntax. If you instead have this code, calling GetConstantValue on the explicit conversion returns nothing:
```cs
void M(int? x) {
    if (x == (int?)1) {
    }
}
```

In IOperation, you can walk through implicit conversions, so you need to in order to get to the actual constant value.
