### ISSUE TITLE
Provide spelling suggestions for command line build

### ISSUE THREAD

**Issue by svick** [dotnet/roslyn#38280]
Roslyn can already help with fixing typos in code when used from a proper editor through [a code fix](https://github.com/dotnet/roslyn/blob/master/src/Features/CSharp/Portable/SpellCheck/CSharpSpellcheckCodeFixProvider.cs). But I believe C# is also increasingly being used in less traditional environments, especially by beginners, so I think it would be very helpful if the same spelling suggestions could be also provided in a command line build.

For this request, things that don't matter:

1. If the suggestion is provided as part of the existing error message, or as a separate message.
2. If the suggestion is provided by the core compiler itself, by an analyzer, or in some other way.

The thing that does matter is that this feature is on by default when building from the command line. In other words, if I run `dotnet new`, edit my code and then run `dotnet build`, I should be notified of typos. I shouldn't have to install any extra analyzer packages, or anything like that.

**Comment by jmarolf** [comment]
@cartermp I believe F# has this feature correct?

**Comment by cartermp** [comment]
Yep.

**Comment by YairHalberstadt** [comment]
I like the way the rust compiler works. Underneath errors, they provide extra information, like suggestions. For example:

```
error[E0507]: cannot move out of borrowed content
 --> src/main.rs:4:9
  |
4 |     for &item in list.iter() {
  |         ^----
  |         ||
  |         |hint: to prevent move, use `ref item` or `ref mut item`
```
 But I think that has two issues for Roslyn:

1. It requires mixing up the IDE and compiler layers, since the compiler layer generates errors, and the IDE code fixes.
2.  It requires a pretty significant redesign of the entire diagnostics system.

For a really nice blog post about the potential of compilers and error messages as learning tools, see https://manishearth.github.io/blog/2017/05/19/teaching-programming-proactive-vs-reactive/

**Comment by CyrusNajmabadi** [comment]
Spelling suggestions are provided both by the platform and by roslyn.
