### ISSUE TITLE
[Regression] ServiceHub.RoslynCodeAnalysisService32.exe is OOMing multiple times a day

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#38330]
**Version Used**: 
Version 16.3.0 Preview 3.0 [29221.207.master]

This is a regresssion, either because we've opt'd into more analyzers when we moved over to .editorconfig enforcement of analyzer levels, or because we're running on newer builds of VS.

**Steps to Reproduce**:

1. `git clone http://github.com/dotnet/project-system`
2. `cd project-system`
3. `git checkout 369551a45088071ec37673d11cfca67658c5ba25`
4. `ProjectSystem.sln`
5. Work for a couple of hours.

This occurs 3 or 4 times a day, and I've also experienced it in other codebases. I had a look at the watsons and every time this crashes its getting into a unique bucket due to the random nature of what frame the OOM is being thrown.

[internalshare]\\public\davkean\Roslyn\38330.zip

**Comment by mavasani** [comment]
Re-opening the issue as we need to update to a newer flow analysis package with the change to ensure a similar leak is fixed for the IDE Dispose analyzers.

**Comment by mavasani** [comment]
@vatsalyaagrawal We need to take the fix for this bug through Dev16.3 ask mode. I will create a PR targeting 16.3 release branch very soon.

**Comment by mavasani** [comment]
@davkean Identified 3 issues here:

1. Memory leak in the flow analysis assembly in roslyn-analyzers repo. Fixed with https://github.com/dotnet/roslyn-analyzers/pull/2795. Verified this leak is resolved with https://dotnet.myget.org/feed/roslyn-analyzers/package/nuget/Microsoft.CodeAnalysis.FxCopAnalyzers/2.9.5-beta1.19451.1+20d91a42.
2. The flow analysis assembly is packaged as `Microsoft.CodeAnalysis.FlowAnalysis.Utilities` and consumed in Roslyn, so https://github.com/dotnet/roslyn/pull/38441 needs to fix the issue 16.3 for IDE analyzers. Verified this leak is resolved after installing the locally built Roslyn VSIX with this fix. @vatsalyaagrawal is driving that PR through 16.3 ask mode.
3. Memory leak in VS Threading analyzers: https://github.com/microsoft/vs-threading/issues/508. Tagging @AArnott for fixing this. @sharwell we may also want to move Roslyn.sln to consume newer VS Threading analyzers package after this gets fixed.

**Comment by mavasani** [comment]
Verified that there is no memory leak after the following changes:
1. Moved to https://dotnet.myget.org/feed/roslyn-analyzers/package/nuget/Microsoft.CodeAnalysis.FxCopAnalyzers/2.9.5-beta1.19451.1+20d91a42. We will publish a 2.9.5-beta1 and/or a 2.9.5 stable release very soon.
2. Installed the latest Roslyn VSIX from release/dev16.3 branch that includes https://github.com/dotnet/roslyn/commit/db910a7f4a057151dae1c9b30efabe5c5ec005a9. This fix should be in Dev16.3.
3. Moved to VS Threading analyzers package from [here](https://dev.azure.com/devdiv/_apis/resources/Containers/4361728/deployables?itemPath=deployables%2FMicrosoft.VisualStudio.Threading.Analyzers.16.3.26.nupkg), which has the fix for https://github.com/microsoft/vs-threading/issues/508

**Comment by mavasani** [comment]
FYI: https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers/2.9.5-beta1.final has been released, which has this fix.

@AArnott Does https://www.nuget.org/packages/Microsoft.VisualStudio.Threading/16.3.52 have the fix for https://github.com/microsoft/vs-threading/issues/508?

**Comment by AArnott** [comment]
Yes
