### ISSUE TITLE
Covariance does not consider type parameter constraints

### ISSUE THREAD

**Issue by Naine** [dotnet/roslyn#38363]
Minimal reproduction:

```csharp
interface IFoo<out T> { }
class Foo<T> : IFoo<T>
{
    static void Bar<U>() where U : T
    {
        U x1 = default;
        T y1 = x1; // works, thanks to constraint

        IFoo<string> x2 = new Foo<string>();
        IFoo<object> y2 = x2; // works, thanks to covariance

        IFoo<U> x3 = new Foo<U>();
        IFoo<T> y3 = x3; // error CS0266
    }
}
```

I would expect `IFoo<U>` to be implicitly convertible to `IFoo<T>` due to the covariance rule, since U is a subclass of T according to the constraint.

Instead I get:
```
Error CS0266 Cannot implicitly convert type 'IFoo<U>' to 'IFoo<T>'. An explicit conversion exists (are you missing a cast?)
```

`Foo<U>` is also not implicitly convertible to `IFoo<T>`, but casts do succeed at runtime for any U and T that satisfy the type parameter constraint.

**Comment by svick** [comment]
> `Foo<U>` is also not implicitly convertible to `IFoo<T>`, but casts do succeed at runtime for any U and T that satisfy the type parameter constraint.

They won't. Consider `Foo<object>.Bar<int>()`: this combination satisfies the constraint, but the cast from `Foo<int>` to `IFoo<object>` fails at runtime, because the conversion from `int` to `object` is not an implicit reference conversion (which is what's required by [the spec](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/interfaces#variance-conversion)).

This also means this behavior is correct and points to a way to fix your code: you have to ensure the conversion from `U` to `T` is an implicit reference conversion and you can do that by constraining `U` to be a reference type:

```c#
where U : class, T
```

**Comment by Naine** [comment]
Yes, you're correct. I'd neglected to consider value types and `object`.

I'll close the issue.
