### ISSUE TITLE
Using with alias in suggestions

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#38539]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/711223/using-with-alias-in-suggestions.html)._

---
Add the option to automatically add a using statement with an alias instead. I have a class that I need a using, but I don't want to include everything in that namespace so I need something like this : 
`using MyClass = Namespace.Something.MyClass`

It would be nice if it was in the suggestions instead of the more common `using Namespace.Something`

---
#### Jane Wu [MSFT] on 8/26/2019, 00:55 AM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We’ll provide an update once the issue has been triaged by the product team.</p>

**Comment by kendrahavens** [comment]
Design Meeting Notes
* Won't fix: we need clear guidance from the C# language design on what approach to recommend before encouraging this pattern. https://github.com/dotnet/csharplang/issues/3712
* ‘Add using’ is also one of the most popular codefixes used. This option should not appear as commonly as the regular ‘add using.’ It could be limited to only appear if a certain code style is set. (It would be great if we could only offer it if we detect conflicts would occur if the normal ‘Add using’ is applied, but we expect the detection of conflicts is a prohibitively expensive operation to add in this context.)
* Note: If a team wanted to suppress this by writing an analyzer they would be blocked since this is a codefix of a compiler error until https://github.com/dotnet/roslyn/issues/4032 is implemented.
