### ISSUE TITLE
VBCS Compiler takes almost 70 % of cpu on every page run on first time in ASP .Net MVC project

### ISSUE THREAD

**Issue by kcdhaker1987** [dotnet/roslyn#38578]
![vbcs complier1](https://user-images.githubusercontent.com/25609223/64483779-39186100-d226-11e9-805f-424f50efcaab.png)
**Version Used**:  2.0.1

**Steps to Reproduce**:

1. 
2. 
3. 

**Expected Behavior**: Should not use that much of CPU and it takes almost 30 seconds on each page every deployment

**Actual Behavior**: Taking too much time and too much CPU

**Comment by jaredpar** [comment]
> Should not use that much of CPU and it takes almost 30 seconds on each page every deployment

The VBCSCompiler will aggressively use CPU in order to produce a compilation as fast as possible. Ideally it would use 100% of the CPU when possible. 

The 30 seconds though is not expected. Generally when we see times that high it's because an extremely high number of references are being passed to the compiler or the code exposed a perf bug in the compiler. 

Can you provide some more info here:

1. How many references are you passing to the compiler?
1. Do you have a repro that we could run locally? If not could you grab a trace of the application that we can look at?

**Comment by agocke** [comment]
@kcdhaker1987 Do you have a sample that you could share with us to reproduce the problem?

**Comment by kcdhaker1987** [comment]
This issue is occurring on the client's server and he has already moved  to another server so can't you provide the sample, on the new server, it is not that much slower as the previous one
