### ISSUE TITLE
Why does compiler generate a br instruction?

### ISSUE THREAD

**Issue by CreateAndInject** [dotnet/roslyn#38579]
```
        static string GetString()
        {
            return "Test";
        }
```

Compile it, view IL

**Expected Behavior**:
```
ldstr     "Test"
ret
```

**Actual Behavior**:
```
IL_0000: nop
IL_0001: ldstr     "Test"
IL_0006: stloc.0
IL_0007: br.s      IL_0009
IL_0009: ldloc.0
IL_000A: ret
```

Why does compiler generate so many IL instructions?  Especially, why does compiler generate a br instruction?

**Comment by HaloFour** [comment]
Is this debug or release build?

**Comment by CreateAndInject** [comment]
I test it just now.
Release generates only 2 instructions : ldstr ret
Why does debug generate a br instruction?

**Comment by Joe4evr** [comment]
So there's places where the debugger can break execution.

**Comment by CreateAndInject** [comment]
Why does compiler use `br` rather than `nop`?

**Comment by jaredpar** [comment]
@tmat can best explain why this is done.

**Comment by gafter** [comment]
The designed debugging behavior for a method is that when you set a breakpoint on the close curly brace, you get stopped at that breakpoint when any return statement is executed.  Moreover, there are circumstances in which the debugger arranges to display the returned value.  In order to arrange those, when in debug mode the compiler places the returned value into a temp and jumps to the end of the method, where the value is loaded and returned.  You are seeing that code sequence.
