### ISSUE TITLE
.editorconfig warning/error support

### ISSUE THREAD

**Issue by MarkPflug** [dotnet/roslyn#38684]
Hello,
I [asked a question in the .NET community standup yesterday](https://youtu.be/FDDZzxxERFI?t=1847) about the .editorconfig warnings work that was demoed. My question was whether it was considered how this feature would interact with warnings/errors configured in MSBuild (csproj). I believe the response was that using .editorconfig allowed the configuration to be more easily shared between projects than a csproj implementation, since .editorconfig applies in a "cascading" manner and thus common settings can be applied to multiple projects. That makes total sense, and I completely agree with the design goal. 

Have you considered using [Directory.Build.props](https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build?view=vs-2019) instead? Directory.Build.props would allow the settings to cascade/inherit in the same way that .editorconfig does, and already integrates with MSBuild, so wouldn't require any extra work to integrate.

.editorconfig is a wonderful thing, but it seems that up to this point it is focused on code style, with which warnings/errors don't totally align. This feature will be duplicating functionality that has historically been managed through the MSBuild (csproj). I would expect a command line build to be producing the same warnings/errors as the IDE, so an .editorconfig implementation would require adding some smarts to the existing MSBuild scripts to understand .editorconfig.

It's hard for me to find documentation on some of the MSBuild properties, but some of the ones I can find/remember are:
- **NoWarn** (error list) suppress listed warnings. These warnings will simply not be emitted by the compiler.
- **WarningsAsErrors** (error list) a list of specific warnings to treat as errors.
- **TreatWarningsAsErrors** (true/false) treats all warnings as errors. Defaults to false.
- **WarningsNotAsErrors** (error list) can be used with TreatWarningsAsErrors to not elevate certain warnings to errors. This is a lesser-known property, because the VS properties UI didn't expose it, which is unfortunately because it is very useful.
- **WarningLevel** (0-4) Not really sure how this works, but I think the default is 4 which enables all warnings.

The way I like to setup projects is to turn on TreatWarningsAsErrors, then exclude certain errors `<WarningsNotAsErrors>CS1591,CS0612,CS1030`. Those 3 are a few that I actually care about, but the community could probably provide a more complete set. These will continue to surface as warnings, so won't "break the build".

CS1591 : missing doc comments on public members. I turn this on because too many team members will provide empty comments to suppress the error, which is harder to detect and fix than a warning. There are a lot of related warnings (like [CS1573](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs1573)) that might also be reasonable to exclude.

CS0612: warnings about obsolete usage. Debatable if this should be an error, but I find that sometimes I "Obsolete" something, but continue to use it internally. I think CS0618 is similar

CS1030: explicit warning pragmas (#warning). I like to use these as more aggressive "TODO". Elevating them doesn't make sense when #error also exists.

**Comment by MarkPflug** [comment]
Additionally, MSBuild already integrates with nuget packages. It would be possible to create a "targets only" (no runtime lib) nuget package that contains best practices for warnings configuration. This package could then be consumed by many projects, and could be evolved by the community over time as more warnings are added to the language.
This would be much harder to do with a .editorconfig implementation.

**Comment by jasonmalinowski** [comment]
> Have you considered using Directory.Build.props instead? Directory.Build.props would allow the settings to cascade/inherit in the same way that .editorconfig does, and already integrates with MSBuild, so wouldn't require any extra work to integrate.

People could definitely use Directory.Build.props for some of the scenarios, but there's a few notable differences:

1. You can apply a .editorconfig to a directory within a project and that will only apply to the source within that project. Directory.Build.props still is project-at-a-time, so you can't do more specific stuff. It's not uncommon that a team might have some folder which is "legacy" or needs different naming styles or certain rules to not apply, and being able to apply to certain folders or even certain files is valuable.
2. It doesn't mean manual editing of MSBuild files; not everybody is comfortable with this and it's easy to get things wrong. As far as cascading: Directory.Build.props doesn't behave the same as .editorconfig: MSBuild only loads the "closest" one and then it's up to that Directory.Build.props to explicitly choose to continue cascading higher up. Not to say you can't make it work, but for somebody who is unfamiliar with MSBuild it's a pretty high learning curve.
3. As a niche scenario, if you have a large solution and at some point you use linked files, .editorconfig means it's unambigious which styles apply to those linked files. A project-based configuration potentially means you have two projects "fighting".

If using Directory.Build.props is something that works for you and you're happy with it, we're not taking that away. But for some that's not the experience they're looking for, and we hope .editorconfig works better for them. We also very much imagine .editorconfig as more being a replacement for ruleset files, since trying to manage a solution sharing a ruleset file was a very error-prone task.

**Comment by MarkPflug** [comment]
> You can apply a .editorconfig to a directory within a project and that will only apply to the source within that project. 

I didn't realize that .editorconfig allowed that. I have to admit that use case sounds somewhat questionable to me, but if it's something that has been determined to be useful, so be it. 
I still fail to see how this is going to integrate with a command line build without a lot of additional work within MSBuild or the compiler. Is the intent that diagnostics would match between a build within the IDE and a command line build? If they didn't match, that would be a pretty bad experience, in my opinion. Can you explain how you envision this working? An MSbuild task that reads .editorconfig, transforms it into a ruleset file that it passes to the compiler? That wouldn't support the scoping you are talking about, though. A new compiler argument, which would duplicate the existing concept of rulesets? Let the compiler emit all warnings and an MSBuild task would suppress/elevate based on error code and source location?

> It doesn't mean manual editing of MSBuild files

Maybe I misunderstood what I was seeing in the demo, but thought the tooling (which wasn't quite there yet) was going to take care of this for you, so you wouldn't have to manually edit the .editorconfig either? Tooling has always been there to prevent people from needing to dig into their csproj files (project properties), why would this be any different?

> large solution and at some point you use linked files

As someone who has used linked files between projects, I don't know that the "fighting" is of concern  to me. I wouldn't expect two projects withing a solution to be using wildly different style or diagnostics configuration. I work in a solution with over 100 projects, that have been authored over 20 years (yes, longer than .NET has existed), and we use a single .editorconfig for all of it. We do use different warning configurations for some of the projects, but I can't envision using an .editorconfig to manage a sub-tree within a project.

This feature may not be *for* me, and that's fine. I just wanted to make sure that this alternative had at least been considered. Thanks for taking the time to respond.

**Comment by jmarolf** [comment]
A lot of the motivation for using editorconfig was to try and have just a single file where everything was managed. We also wanted to decouple this file from other technologies, where possible, so that people could have an easy drop-in way to have things work (what about people that use Make or Fake to build instead of MSBuild? Would they need to change all their build infra just to configure code style?).

> This feature will be duplicating functionality that has historically been managed through the MSBuild (csproj).

You can change warnings in MSBuild for the compiler but that never applied to code analysis.  You needed ruleset files for that. There has always been a variety of different file formats you needed to modify (VS Settings XML, ruleset files, MSBuild files) to get things configured correctly. There has never been a single file format that could do it all till now. Yes, this duplicates the configuration for warnings from the compiler but only because we want a singular place for people to look when they need to understand what effects their code style settings.

>I still fail to see how this is going to integrate with a command line build without a lot of additional work within MSBuild or the compiler

The C# compiler was updated to understand editorconfig files so this scenario would work. The IDE and the compiler will read the same file and do the same thing.

> Maybe I misunderstood what I was seeing in the demo, but thought the tooling (which wasn't quite there yet) was going to take care of this for you, so you wouldn't have to manually edit the .editorconfig either? 

Yes, but doing the same thing for MSBuild is significantly harder.  MSBuild is a turing complete scripting language that needs to be evaluated in totality to know if something is safe to do or not. editorconfig is just a simple declarative file. We could tool MSBuild better (and we are working on that too!) but its going to take longer than just using a simple declarative file.

>As someone who has used linked files between projects, I don't know that the "fighting" is of concern to me. 

If two different projects have different code-style configurations and both include the same linked file which one should apply? This may seem like a problem that doesn't ever come up but we encountered this in the roslyn project itself.

**Comment by MarkPflug** [comment]
> Would they need to change all their build infra just to configure code style?

I wouldn't think so, because presumably Make and Fake have features similar to MSBuild's NoWarn, WarningsAsErrors, etc. Do people that use Make and Fake even use VS? Honest question.

To me, diagnostics aren't about "style", they are about correctness. Tabs vs spaces, or the position of curly braces, doesn't affect the compiler output. Warning and error configuration do. That's why it feels weird to me that diagnostics would be configured in .editorconfig.

> The C# compiler was updated to understand editorconfig files so this scenario would work.

So, all the .editorconfig files will be passed to the compiler as a new command line option? I'm assuming rulesets will continue to exist? Will the compiler also be able to emit output when the source file style doesn't match the .editorconfig spec? So, now there will be (at least) three avenues to configure warnings from the compiler: -warn/nowarn/warnaserror, -ruleset, and a new -editorconfig option?

Honestly, this feels a bit like the project.json move back in the early days of dotnet core. I'm happy that effort happened, because without it we probably wouldn't have the Sdk-style MSBuild projects that we have now. It just feels like this is happening because MSBuild has lacked decent tooling for so long.

**Comment by jmarolf** [comment]
>Do people that use Make and Fake even use VS?

Sure they do and we don't want to require build infra changes for people.

>To me, diagnostics aren't about "style", they are about correctness.

What is 'correct' is a deeply personal thing for a project. We don't want to tell people that they can't fail the build because someone used tabs instead of spaces even if that is a perfectly fine thing to do from the C# language spec perspective. StyleCop and its usage in the wild told us that there is a very large distribution of what people consider 'correct' for their project.

>all the .editorconfig files will be passed to the compiler as a new command line option?

Yep

>I'm assuming rulesets will continue to exist?

We don't want to break existing people so they will continue to work but we aren't going to be suggesting people create rule-set files in the tooling. Instead we will suggest editorconfig

>Will the compiler also be able to emit output when the source file style doesn't match the .editorconfig spec

Yes.  It is important that commandline builds and the IDE experience are exactly the same. I shouldn't be able to build in VS but have something fail on a CI machine.

>So, now there will be (at least) three avenues to configure warnings from the compiler: -warn/nowarn/warnaserror, -ruleset, and a new -editorconfig option?

Yes but editorconfig will always be the way that has the most tooling support and the most features.

>Honestly, this feels a bit like the project.json move back in the early days of dotnet core.

.editorconfig files are things that will exist regardless in most projects because nearly all editors (not just Visual Studio) respect the base set of rules for them such as tabs, spaces etc. What originally led us to look at supporting editorconfig was that most opensource .NET projects already had an editorconfig file. So instead of having two files where you configured this stuff, we wanted there to be just one. There are also engineering reasons that MSBuild was harder to do, and most people find modifying their build too high a cost just to get style enforcement. For all these reasons I don't think we will move back to having property-based enforcement mechanism that is evaluated by MSBuild though you never know what the future holds :)

**Comment by MarkPflug** [comment]
> Yes. It is important that commandline builds and the IDE experience are exactly the same. I shouldn't be able to build in VS but have something fail on a CI machine.

Okay, I think that addresses my main concern.

The only other thing that I'd like to request is that it will be easy to use .editorconfig to do "all warnings as errors" then exclude specific warnings so they don't elevate to errors. If it handles that elegantly, meaning I don't need to explicitly list every single warning code, then I think I'm happy. :)

Thanks for taking the time to discuss this with me. I know it consumes valuable time to interact with the community, so please know that we appreciate it!
