### ISSUE TITLE
Confirm required CancellationToken for Formatter.OrganizeImportsAsync

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#38758]
#38593 adds this method with a required cancellation token, which aligns with asynchronous usage analyzers that require cancellation tokens be passed to methods that take them. The new API deviates from existing patterns, so it should be confirmed in design review.

**Comment by CyrusNajmabadi** [comment]
Note: IMO we should not do this.  I personally write a bunch of tools that do not pass cancellation tokens along.  It's very much appreciated that the public surface area of Roslyn doesn't require this.  For production-ready IDE code, cancellation tokens should be explicitly passed in.  However, our public surface area shouldn't require this to make the experience more pleasant for these other use cases.

Note: this API is also inconsistent with every other public API we have.  Since there is already an analyzer to catch mistake using this by us, we don't need to make this required.  This doesn't help us, and only serves to make things more unpleasant for a consumer that doesn't care about this scenario.

**Comment by jasonmalinowski** [comment]
It was decided in the design meeting to synchronize this API with the rest of the Roslyn surface area. Independently we will discuss with the framework team if it's worth revisiting that pattern going forward but that's a longer-term question than this.
