### ISSUE TITLE
Signature help in collection inializers

### ISSUE THREAD

**Issue by terrajobst** [dotnet/roslyn#38850]
Collection initializers are just a syntactic sugar for calling an `Add()` method. When calling the `Add()` method explicitly, I get signature help:

<img width="487" alt="ci1" src="https://user-images.githubusercontent.com/5169960/65613389-cc61ce00-df6a-11e9-949d-4f60050a5537.png">

However, when using the collection initializer syntax, I don't:

<img width="237" alt="ci2" src="https://user-images.githubusercontent.com/5169960/65613387-cc61ce00-df6a-11e9-90b4-f904ed4c5b3e.png">

**Version Used**: 

Microsoft Visual Studio Enterprise 2019 Int Preview
Version 16.4.0 Preview 2.0 [29322.22.master]
VisualStudio.16.IntPreview/16.4.0-pre.2.0+29322.22.master

**Comment by M-Zuber** [comment]
I'd like to try and give this a shot
Where would I need to start?

**Comment by terrajobst** [comment]
> I'd like to try and give this a shot
> Where would I need to start?

@jasonmalinowski can probably point you somewhere. I suspect you can start by looking at the types derived from [`AbstractCSharpSignatureHelpProvider`](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp.Features/SignatureHelp/AbstractCSharpSignatureHelpProvider.cs,cd93403e316c15c9,references).

**Comment by jasonmalinowski** [comment]
Indeed, a few steps for this:

1. Make a new type in https://github.com/dotnet/roslyn/tree/master/src/Features/CSharp/Portable/SignatureHelp that derives from AbstractCSharpSignatureHelpProvider. There are some methods to override, you may find looking at the other implementations helpful to see what they do (there's a certain number of utility functions that make it easier.)
2. When you recognize you're in this context you'll have to go up, call SemanticModel.GetTypeInfo() on the overall initializer which will give you the type of the underlying thing (the "JObject" in the case of @terrajobst's screenshot).
3. [This API exists](https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.csharp.csharpextensions.getcollectioninitializersymbolinfo?view=roslyn-dotnet) which will let you know which Add method is being used. I'm not sure if there's a good way to get all of the methods, since you would need them all at once to list overloads. You'd have to mess with that, I don't actually remember any of the details...

**Comment by CyrusNajmabadi** [comment]
Oh... fyi, i heard about this last night and already started a PR on hte matter :-/

**Comment by terrajobst** [comment]
> Oh... fyi, i heard about this last night and already started a PR on hte matter :-/

Of course you did :-)

**Comment by M-Zuber** [comment]
@CyrusNajmabadi for what it's worth, I'd rather see the feature get in than be the one to do it ☺

**Comment by peteraritchie** [comment]
+1 if only for consistency and completeness.

**Comment by RikkiGibson** [comment]
Would it make sense to do any of the following:

- include element initializers in Find All References results for Add methods
- go to the appropriate Add method on F12 of the curly brace for the element initializer

**Comment by CyrusNajmabadi** [comment]
@RikkiGibson sure.  it's just a question of motivation.

**Comment by terrajobst** [comment]
> * include element initializers in Find All References results for Add methods

Yes.

> * go to the appropriate Add method on F12 of the curly brace for the element initializer

Maybe? I think this would never occur to me.

**Comment by CyrusNajmabadi** [comment]
Here's the location we would need to update for find-refs: https://github.com/dotnet/roslyn/blob/6dab121ff512e2bcc5028149d7705d3ba2d51a72/src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/OrdinaryMethodReferenceFinder.cs#L94-L105

We already have the concept of being able to find special methods.  It would just be a matter of adding support for this additional special method and putting the right information in our indices to determine which documents to search.  

The index to update would be: https://github.com/dotnet/roslyn/blob/master/src/Workspaces/Core/Portable/FindSymbols/SyntaxTree/SyntaxTreeIndex_Forwarders.cs

**Comment by terrajobst** [comment]
@RikkiGibson, would you mind filing suggestions for your comments?

**Comment by RikkiGibson** [comment]
One issue already existed, and I filed another issue to follow up on these.
