### ISSUE TITLE
Convert to conditional expression refactoring disgards null-forgiving operator

### ISSUE THREAD

**Issue by nxtn** [dotnet/roslyn#38879]
**Version Used**: Visual Studio 2019 Version 16.4

**Steps to Reproduce**:

```cs
#nullable enable

class Program
{
    public static string Method(bool empty)
    {
        if (empty)
        {
            return string.Empty;
        }

        return null!;
    }
}
```

```diff
+Expected Behavior
-Actual Behavior
```

```diff
#nullable enable

class Program
{
    public static string Method(bool empty)
    {
+        return empty ? string.Empty : null!;
-        return empty ? string.Empty : null;
    }
}
```

**Comment by jcouv** [comment]
Tagging @ryzngard

**Comment by CyrusNajmabadi** [comment]
Debugged through.  This looks to be a bug with the IOperation API.  The shape of the API is that we have a `return operation` that points at a `conversion operation` of the `null constant` to the `string` type.  

There is nothing in the IOp tree to represent the suppression operation.  As such, when we then sya that we want the "syntax" for what is returned, IOp gives us just `null` and not `null!`.

This seems busted to me.  There is syntax that has very specific semantics, and the IOp tree doesn't seem to represent this at all.  i.e. it represents both `return null;` and `return null!;` the same.  

We could certainly work around this on the IDE side.  But it would mean that we basically could never trust the IOp tree to represent or tell us about suppressions or use the nodes it points to.

**Comment by CyrusNajmabadi** [comment]
@333fred is there an expectation/design around how suppression is encoded into IOp tree?

**Comment by 333fred** [comment]
The short answer is that no, there is no current design for how this info is encoded into IOperation.

**Comment by CyrusNajmabadi** [comment]
Ok.  We def should do that :)

**Comment by CyrusNajmabadi** [comment]
@333fred has there been any work to supply this information to IOp?  It's really unclear to me how we want to take all our IOp features (which includes pretty much where we want all our features to be) to work properly with NRT.

Suppression is an operator.  Should we not have an ISuppressionOperator to indicate that in the op tree?

**Comment by 333fred** [comment]
Nothing has been done yet. @AlekseyTs and I have talked a bit in the past about putting a `IsSuppressed` flag on `IOperation` itself, like `Type`. I'd be resistant to making an `ISuppressionOperator` because I don't want to make a `ParenthesizedExpressionSyntax`-type node for `IOperation`. A suppression could appear on _any_ expression, including in places were we've today specified that only a single or small set of nodes can appear today. So walking the tree would become an exercise in "Alright, and now let's skip past any possible suppressions here", much like walking the syntax tree is often an exercise in "Let's skip past any parenthesized expressions here.".
