### ISSUE TITLE
mbox shortcut changes in WPF

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#38919]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/554389/mbox-shortcut-changes-in-wpf.html)._

---
<p>In WPF/C#, I used mbox shortcut. At that time, this code was inputed.</p><pre>System.Windows.Forms.MessageBox.Show(&quot;Test&quot;);
</pre><p>But I want to enter the code below in WPF.</p><pre>System.Windows.MessageBox.Show(&quot;Test&quot;);</pre><p>or</p><pre>using System.Windows;
// Some Code
MessageBox.Show(&quot;Test&quot;);  // Where I used shortcut</pre><p></p>

---
#### Jane Wu [MSFT] on 5/5/2019, 03:20 AM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;We'll provide an update once the issue has been triaged by the product team.</p>
#### Kendra Havens [MSFT] on 9/27/2019, 11:03 AM: 

<p>Thank you for filing this feedback! I'm going to move this to our open source repository on GitHub for further discussion with the community.</p>

**Comment by miloush** [comment]
Since both `System.Windows` and `System.Windows.Forms` are both included by default in the respective project, perhaps just inserting unqualified `MessageBox.Show` would do the trick. And if used elsewhere, the add using quick fix can fix it easily.

Otherwise, I think this is easy enough to solve by users themselves (i.e. editing the snippet or creating your own).

**Comment by sharwell** [comment]
Blocked on #31879

**Comment by CyrusNajmabadi** [comment]
Closing out as we are not investing in these legacy snippet scenarios.
