### ISSUE TITLE
Broken Nuget package Microsoft.VisualStudio.Shell.15.0

### ISSUE THREAD

**Issue by NextTurn** [dotnet/roslyn#38939]
The first dependency of the latest version of package [`Microsoft.VisualStudio.Shell.15.0`](https://www.nuget.org/packages/Microsoft.VisualStudio.Shell.15.0/), [`Microsoft.ServiceHub.Framework`](https://www.nuget.org/packages/Microsoft.ServiceHub.Framework/), is broken. Can someone please forward this issue to the SDK team?

**Comment by NextTurn** [comment]
Closing as fixed.

**Comment by LeroyK** [comment]
This issue is back for [Microsoft.VisualStudio.Shell.15.0 version 16.4.29519.181](https://www.nuget.org/packages/Microsoft.VisualStudio.Shell.15.0/16.4.29519.181). It depends on [Microsoft.ServiceHub.Framework](https://www.nuget.org/packages/Microsoft.ServiceHub.Framework/) >= 2.1.20, which isn't published on nuget.org.

**Comment by BrienKing** [comment]
Anyone have a resolution to this?
