### ISSUE TITLE
Cannot apply null-conditional operator for Nullable<T> returned by null-conditional operator (CS0023)

### ISSUE THREAD

**Issue by VillSnow** [dotnet/roslyn#38975]
**Version Used**: 
Visual Studio Community 2019 Version 16.2.5

**Steps to Reproduce**:

```C#
class Foo {
	public ClassType ClassMember { get; }
	public StructType StructMember { get; }
	public int PrimitiveMember { get; }
}

class ClassType {
	public int Value { get; }
}

struct StructType {
	public int Value { get; }
}

static void Main(string[] args) {
	Foo foo = null;
	int? a = foo?.ClassMember?.Value;             // ok
	int? b1 = foo?.StructMember?.Value;           // CS0023
	int? b2 = (foo?.StructMember)?.Value;         // ok
	string c = foo?.PrimitiveMember?.ToString();  // CS0023
}
```

I think there is no difference between b1 and b2, but cannot build b1.

**Comment by gafter** [comment]
The null-conditional operators are effectively right-associative, not left-associative.  That is why the parens are required.

**Comment by VillSnow** [comment]
I'm confused about eight-associative member access.
Is `foo?.ClassMember?.Value` same as `foo?.(ClassMember?.Value)`? What is the `ClassMember` in the paren? Something like pointer to member in C++?

Are usual member access operators (.) right-associative too?

**Comment by gafter** [comment]
When you write `something?.somethingElse`, the `somethingElse` is skipped when `something` is `null`.  The `somethingElse` can include further`.` and `?.` operators which are also skipped.  That's why you don't need to `?.` after a field of a non-nullable struct type.

You cannot parenthesize the "right-hand-side" of a conditional member access as you show, because it isn't an expression.  And you don't need to.  But you can parenthesize the left-hand-side.  A similar comment applies to `a.b.c`.  You can't rewrite it `a.(b.c)`, but you can write it `(a.b).c` as long as `b` is an expression (i.e. not a type or namespace).

**Comment by VillSnow** [comment]
I haven't know `foo?.StructMember.Value` yields `int?` and never throw `NullReferenceException`.
I'm interested in why is it possible. Left-associative `a?.b?.c` seems enough.

These need fixing
https://docs.microsoft.com/en-US/dotnet/csharp/language-reference/operators/member-access-operators#null-conditional-operators--and-
https://docs.microsoft.com/en-US/dotnet/csharp/language-reference/operators/#operator-associativity
Is there any official and original C# reference?

**Comment by gafter** [comment]
The language reference for this is at https://github.com/dotnet/csharplang/blob/master/spec/expressions.md#null-conditional-operator

**Comment by VillSnow** [comment]
Thank you. I got.
So `a?.b?.b` or `a?.b.c` is a single expression and cannot deconstruct into an expression tree.
