### ISSUE TITLE
ArrayBuilderExtensions.FreeAll is wrapped with nullable disable

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#39052]
https://github.com/dotnet/roslyn/blob/7bf43667a1658911e4091d9e60695fe15b3bd2e0/src/Compilers/Core/Portable/Collections/ArrayBuilderExtensions.cs#L191-L200

According to https://github.com/dotnet/roslyn/pull/38882#discussion_r328916521, this is related to #38195.

/cc @333fred

**Comment by 333fred** [comment]
The main issue is that the nested `.FreeAll(getNested)` call is a `SourceMethodSymbol` in the original bound tree, but after reinferrence in the nullable walker it's a `SubstitutedMethodSymbol`, with the `T` from the method substituted in. Because equality isn't handling substituted method symbols correctly right now, these do not compare equivalently and an assert fails on the bootstrap build.

**Comment by gafter** [comment]
Reinference in the nullable walker should never infer a type that is not equivalent (identity convertible with) the type from the initial binder.  If it is different, then there is a bug.
