### ISSUE TITLE
'Go to all' can't find local functions

### ISSUE THREAD

**Issue by 0xd4d** [dotnet/roslyn#39083]
**Version Used**: VS 16.3

**Steps to Reproduce**:

1. `Ctrl+,`
2. Search for `LocalFunction`

```C#
using System;

namespace ConsoleApp9
{
    class Program
    {
        static void Main(string[] args)
        {
            static void LocalFunction() { }

            Console.WriteLine("Hello World!");
        }
    }
}
```

**Expected Behavior**:

The local function is found

**Actual Behavior**:

The local function is not found

**Comment by CyrusNajmabadi** [comment]
In general, we don't index local members at all.  Likely because they're viewed as temps, and likely have far too many hits across tons of members.  That said, local functions seems somewhat reasonable as something we could index.  

I do envision some difficulties putting this into the nav-to index.  Specifically:

1. indexing will be slightly more expensive as we'll have to navigate into method bodies (right now we can avoid that entirely).  Given how large method bodies can be, this could be impactful.
2. indexes will get slightly larger.  This is likely not a big deal.
3. returning results will get more expensive.  With go-to, we have to realize information about the results.  currently, this is all only for top-level symbols, which never need things like SemanticModels.  This woudl change with local functions, potentially making result retrieval more expensive if we had to create semantic models to recover the original symbol.  This is potentially avoidable by increasing indexing time by adding more info to the index.
