### ISSUE TITLE
Refactor object from different directives

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39117]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/741362/refactor-object-from-different-directives.html)._

---
can we do refactoring of same object name from different setup in directives especially if the object inside #if(DEBUG) ?

```
#if (DEBUG)
	public static ConnectionString CurrentConnectionString = new ConnectionString(&quot;DEVELOPEMENTsqlserver&quot;,&quot;db&quot;,&quot;mgmguardiana&quot;,&quot;password&quot;,false);
#else
        public static ConnectionString CurrentConnectionString = new ConnectionString(&quot;PRODUCTIONsqlserver&quot;,&quot;db&quot;,&quot;mgmguardiana&quot;,&quot;password&quot;,false);;
#endif
    }
```

In this example, if I use ctrl+R+R in `CurrentConnectionString` assume that I'm in debug mode, any reference will be updated only under the current directive(DEBUG), and when switching to release mode, the codes may go broke and need to rename it again.

Current steps of refactoring
1. From screenshot in example at DEBUG mode, press CTRL+R+R to show rename the object of `CurrentConnectionString` into `RenamedConnection` and press ENTER
2. Run or build in debug mode, no errors will be raise.
3. Now switch to release assume that you are now ready to deploy the application
4. Run or build in release mode, errors will be made that all references of `RenamedConnection` are invalid
5. Refactor the `CurrentConnectionString` into `RenamedConnection` while still in release mode.
6. Run or build to test

---
#### Jane Wu [MSFT] on 9/22/2019, 11:30 PM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We’ll provide an update once the issue has been triaged by the product team.</p>

**Comment by mgmguardiana** [comment]
thanks. waiting for further feedback for this.

**Comment by CyrusNajmabadi** [comment]
This has been a longstanding request.  The basic answer we have is:

1. it's really hard.
2. we don't have any sort of design presented that we think can actually solve this.

**Comment by jmarolf** [comment]
I think a _possible_ solution (though not necessarily reasonable) is to have the project system treat more things like they are "mulit-targeted".  The most common case is that users are using pre-processor symbols that are defined in an existing configuration (i.e. `DEBUG`).  If the project system notified the language service of two "project" (Debug and Release) then the language service could begin try and make this better.  There would still need to be a lot of work to de-dupe things but we already need to do that for linked files/projects and multi-targeting.

**Comment by CyrusNajmabadi** [comment]
So here's the significant problem:

if we do that, then we already incur a 2*n cost on things like our indices (or worse if there's anything combinatorial here).  i.e. all these features are driven off of indexes that are stored for the project.  If we now have separate projects because this effectively forks a project P into Debug-P and Release-P, then that's a high cost on things like:

1. extra time to produce indices
2. extra space for indices
3. extra cost to search them.

And this doesn't cover how we even update our features to be aware of this.  For example, with rename, we'd have ot say "if you're renaming X, try to find that X in all the other 'targetted' versions of this project".  

It's complex at an "every feature" level, and it's definitely non obvious how to do it efficiently.  Even the simplest case (i.e debug/release, with no other target config) already makes it much more expensive :-/

**Comment by CyrusNajmabadi** [comment]
Note: I'm not at all against this.  Just that our previously explorations in the past yielded nothing 'easy/cheap'.  Which was greatly concerning because the impact on mainline scenarios could be quite large.

**Comment by jmarolf** [comment]
@CyrusNajmabadi 	yes that is exactly the problem.  This problem exists for multi-targeted projects and linked files today (You will see FAR results listed twice for example). I think this would need to exist as an option that is off be default until we resolve the difficult memory issues.

**Comment by CyrusNajmabadi** [comment]
> @CyrusNajmabadi yes that is exactly the problem. This problem exists for multi-targeted projects and linked files today (You will see FAR results listed twice for example).

Right.  And those cases are even *easier* because we don't deal with this sort of case (i believe):

```
#if (DEBUG)
	public static ConnectionString CurrentConnectionString = new ConnectionString(&quot;DEVELOPEMENTsqlserver&quot;,&quot;db&quot;,&quot;mgmguardiana&quot;,&quot;password&quot;,false);
#else
        public static ConnectionString CurrentConnectionString = new ConnectionString(&quot;PRODUCTIONsqlserver&quot;,&quot;db&quot;,&quot;mgmguardiana&quot;,&quot;password&quot;,false);;
#endif
```

i.e. we don't go into the other targets to look for *other* declarations we might have to rename as well as the original symbol.  We do look in other targets for references though.  The multi-symbol-declaration is definitely somethin that feels entirely new (i believe).

**Comment by CyrusNajmabadi** [comment]
Anotehr fun example.  Say you have:  

```
#if debug && win32

#elif debug && !win32

#endif
```

Now, latter in code like `#win32` or `#debug` you have all sorts of fun things to have to flow and consider between all those cases.... 

I think if we were ever to do something here we might limit it *solely* to the debug/release view of the world just to hit hte 90% case.

**Comment by jmarolf** [comment]
> I think if we were ever to do something here we might limit it solely to the debug/release view of the world just to hit hte 90% case.

That was my opinion too. The user could define any set of directives and pass them via msbuild.  I think if we should limit ourselves to what Visual Studio has configured for the solution.

**Comment by CyrusNajmabadi** [comment]
Closing out as we are unlikely to make any changes here due to the enormous cost and complexity of the impl.
