### ISSUE TITLE
Optional Parameter without static constant - allow static properties

### ISSUE THREAD

**Issue by furesoft** [dotnet/roslyn#3914]
make an optional parameter without having a constand but like this:

public void Draw(Color c = Color.White) {

}

**Comment by HaloFour** [comment]
That is effectively a limitation inherited by the CLR.  The default value must be encoded into the metadata of the parameter at compile time and available to allow any compiler to use that value in place of omitted arguments at the call site.  There is no way to encode an expression that would be understood by the CLR or universally understood by CLR languages.

The argument could be made that for `private` or `internal` methods that the C# compiler could relax that restriction since the optional parameter metadata would never be a part of the public surface of the assembly.  In those cases the compiler could contain a dictionary of the expressions and then replace the omitted arguments.

**Comment by dsaf** [comment]
This is already requested (in a way): #263 (closed, but could be re-opened if requirements are met), #2401.

**Comment by gafter** [comment]
We are now taking language feature discussion on https://github.com/dotnet/csharplang for C# specific issues, https://github.com/dotnet/vblang for VB-specific features, and https://github.com/dotnet/csharplang for features that affect both languages.

Part of the proposal https://github.com/dotnet/csharplang/issues/39 would address the use case for this issue.
