### ISSUE TITLE
Live Code Analyzer Methods Without Parameters Should Become Properties

### ISSUE THREAD

**Issue by SetTrend** [dotnet/roslyn#3917]
Watching the Channel9 video "ImproveCodeQualityUsingLiveCodeAnalyzers" I noticed that many property-like accessors have been implemented as methods.

Even the presenter himself, Anthony D. Green, stubled over this weird implementation style a few times while creating some examples.

Can we hope that this implementation style of preferring parameterless methods over property getters is only present in the Beta but not in the final version?

![methodsoverproperties](https://cloud.githubusercontent.com/assets/9283914/8639145/dd8e3c90-28d0-11e5-81a3-5cd6f99ace10.png)

**Comment by AnthonyDGreen** [comment]
Hi SetTrend,

Good catch on the video. It didn't help that I'm used to coding in VB and just dropping empty argument lists. Muscle memory fail. You make a good observation that these methods don't take any parameters and therefore could be made properties. But another factor to be considered when deciding between methods and properties is how much computation is being done. Generally, properties should be very fast to access and shouldn't require their callers to cache the result. Because of lazy evaluation and other behind the scenes optimizations we do in our immutable syntax trees innocuous looking method calls can be surprisingly expensive. For instance, in order for a token to compute it's own location it needs file wide context. Normally a token only stores its own kind, text, and trivia. In order to determine location a token needs to ask it's containing tree. One reason is because the compiler/parser operates in terms of spans--offsets in a file steam--but the editor and users work in lines and columns. The tree needs to translate between these systems and has the necessary knowledge when hosted in the IDE to take into account things like your tab spacing width. Finding the tree may involve traversing the tokens parent and parent's parent etc to the root of the tree, then computing offsets all the way back down. We don't always cache such answers because they may only be asked once or twice and the storage space on the tree for every node and token would be costly and we're constantly reevaluating what to precompute, what to lazily compute, and what to cache based on usage and performance profiling. So there may be methods which used to be expensive and are no longer or methods which are more cheap which may become more expensive later. DescendantNodes by virtue of doing a tree traversal has nontrivial performance implications. Owing to its convenience we've seen many suboptimal analyzer implementations perform poorly due to its overuse. Other reasons for preferring methods might be the need to use extension methods or genericity or overloading.

Having said all that, the shape of the API is locked down at this point. So even if we did observe some low hanging fruit we'd be unable to change it now without breaking consumers so they may be worts we have to live with. But on the whole Roslyn is a huge API with tons of value in its design so I don't think such blemishes will matter much in the long run.

Regards,

-ADG

Sent from my Windows Phone
