### ISSUE TITLE
Intellisense provides wrong enum suggestions with overloads when different enums can be on the same position

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39193]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/736970/wrong-suggestion-in-messageboxshow-method.html)._

Type System.Windows.Forms.MessageBox.Show and begin to fill parameters like "string text, string caption, MessageBoxButtons buttons, MessageBoxIcon icon". When you reach the last parameter VS suggests you to enter an enum object belongs to MessageBoxButtons type instead of MessageBoxIcon type.

**Comment by ivanbasov** [comment]
I was able to reproduce the issue. The root cause that the analysis we perform for the intellisense takes into account just the number of available parameters. There are many overloads in the case considered. In one of them, MessageBoxButtons can be the fourth argument of the method. Please see the image attached:
![image](https://user-images.githubusercontent.com/5455484/66532400-25317a80-eac4-11e9-9983-70bbdf891cfe.png)



We realize we could involve an analysis of method parameters already added for the method. In this case, we would exclude MessageBoxButtons from the list.

**Comment by ivanbasov** [comment]
The problem could be somewhere here https://github.com/dotnet/roslyn/blob/7bc44488c661fd6bbb6c53f39512a6fe0cc5ef84/src/Workspaces/CSharp/Portable/LanguageServices/CSharpTypeInferenceService.TypeInferrer.cs#L441 or in some its recent callers. The type selection takes into account just the parameter index and ignores types of parameters already typed.

**Comment by MulleDK19** [comment]
At the very least it should consider the currently selected overload. It also shows MessageBoxButton when the overload taking a MessageBoxImage is selected (even when selected before IntelliSense pops up).

![image](https://user-images.githubusercontent.com/3169809/76794195-c5ec3a80-67c6-11ea-909e-3369da0ff453.png)
