### ISSUE TITLE
Suggestion: VB should codespit getter for a readonly property

### ISSUE THREAD

**Issue by ljw1004** [dotnet/roslyn#3921]
When I type this line and hit return
```vb
Public ReadOnly Property P As Integer
```
then there are three possible things I want to do next:
1. Cursor up to the end of the line and stick in an initializer
2. Create a constructor for my class, and initialize the readonly autoprop in there
3. Explicitly write a "getter"

I think that case [3] is sufficiently typical that you should codespit based on that case, as happened in VS2013, with the empty "getter" body.

More specifically:
* If the user writes a readonly property *with* an initializer and hits return, then assume it's intended to be a readonly autoprop, and do nothing else
* If the user writes a readonly property *without* an initializer and hits return, then assume it's intended to be a computed readonly property, and insert the getter

**Comment by Bill-McC** [comment]
I think I'd prefer to have the suggestion to complete the getter appear as soon as I start typing "G" or "Get" and then press tab to complete.  Generally I prefer it if the IDE errs on the side of caution or uses prompts rather than have me have to delete things.
Along similar lines, I'd like to be able to easily expand autoprops with a simple keystroke combination, such as shift or ctrl + enter or ctrl + > etc.

**Comment by Pilchie** [comment]
We implemented @Bill-McC's suggestion.  If you type "G<Enter>" on the next line we will add the Get/End Get/End Propeprty and put the caret in the middle, so it's pretty easy to convert to a property with a getter.

**Comment by Bill-McC** [comment]
Thanks 😊
