### ISSUE TITLE
Loading Microsoft/CodeContracts with MsBuildWorkspace will hit assertion

### ISSUE THREAD

**Issue by pdelvo** [dotnet/roslyn#3926]
Repro:
- Clone https://github.com/Microsoft/CodeContracts
- Build roslyn from source. Create a debug build
- Write an application that uses MsBuildWorkspace to load CodeContracts.sln.
- The assertion at [RetargetingModuleSymbol.cs](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/Symbols/Retargeting/RetargetingModuleSymbol.cs,206) will fail.

I think the reson is that in line 206 a AssemblyIdentity is created without setting the version.

**Comment by Pilchie** [comment]
RetargetingModuleSymbol is the compiler.  Please let us know if something is not right about the references passed in, but I do not expect this is an IDE issue.

**Comment by jaredpar** [comment]
@pdelvo does this cause any errors when loading code contracts from the IDE?  Or is it just when loading via the MSBuildWorkspaces API?

**Comment by pdelvo** [comment]
Loading it in MsBuildWorkspace works fine in an release build. I used a debug version because I was investigating a different issue when I saw this.

**Comment by jcouv** [comment]
Seems related to VSO 290337

**Comment by jaredpar** [comment]
Adding another repo:

1. Create a UWP application.
2. Add a UWP class library project.
3. Add a reference from the UWP application to the UWP class library project.
4. Collapse the navigation in the Solution Explorer so that the individual files of each project cannot be seen. Close all tabs.
5. Go to Tools -> Options -> Projects and Solutions and check Lightweight solution load.
6. Close and reopen solution.
7. Expand the Class Library in the Solution Explorer.
8. Open a file in the Class library project.
9. Expand the UWP application in the Solution Explorer.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback that people are hitting this.
