### ISSUE TITLE
Incorrect CS0165: Use of unassigned local variable

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39489]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/792064/incorrect-cs0165-use-of-unassigned-local-variable.html)._

---
The following code incorrectly produces an &quot;Use of unassigned local variable&quot;

```
using System;
using System.Dynamic;

namespace TestDynamic
{
    class Program
    {
        private class TestDynamicObject : DynamicObject { }
        private interface ITest
        {
            string StringValue { get; }
        }
        private class Test : ITest
        {
            public dynamic DynamicValue =&gt; new TestDynamicObject();
            public string StringValue =&gt; &quot;&quot;;
        }

static void Main(string[] args)
        {
            var test = new Test();
            if (test. DynamicValue != null &amp;&amp;
                test is ITest testInterface)
            {
                // Use of unassigned local variable 'testInterface'
                Console.WriteLine(testInterface.StringValue);
            }
            // This does compile
            if (test. DynamicValue != null)
            {
                if (test is ITest testInterface2)
                {
                    Console.WriteLine(testInterface2.StringValue);
                }
            }
        }
    }
}

```

---
#### Visual Studio Feedback System on 9/19/2019, 01:00 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by controlflow** [comment]
Unfortunately, this is not a bug, this is is caused by the existence of `true`/`false` operators in C#.
Basically, you can define a type that would evaluate to `true` under `&&` expression without evaluating the right operand of `&&`, something like this:
```
class C {
  public static U operator==(C c, C d) => null;
  public static U operator!=(C c, C d) => null;
}

class U {
  public static U operator &(U c, U d) => null;
  public static implicit operator U(bool b) => null;
  public static bool operator true(U c) => false;
  public static bool operator false(U c) => false;
    
  public void M(C c, object o) {
    if (c != null && o is string s) {
      s.ToString();
    }
  }
}
```
When working with values of type `dynamic`, C# has no static information about the type and it's overloaded operators, so it assumes the "worse" - type like `U` in example above.

**Comment by pasauter** [comment]
@controlflow Thank you for your response! I was unaware of the ability to override true/false. I had to tweak your example to get it to short circuit - the overload of the true operator needs to return true.

Relevant section of [documentation](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/expressions#user-defined-conditional-logical-operators)

**Comment by Ghostbird** [comment]
I ran into this issue too, it took me a while to figure out where this went wrong. It turns out that because `foo.CustomData` is `dynamic`, the type of `&&` is `dynamic`.
```csharp
if (outerEx is MyException foo && foo.CustomData != null)
{
    var customData = foo.CustomData; // CS0165: Use of unassigned local variable 'foo'
}
```
I read the documentations and understand that it is possible to override the `false` and `&` operator so that the right hand side is evaluated even though `outerEx` is not of `MyException`, and foo was not assigned.

**I'm quite baffled by one thing though**: _Why is `&& foo.CustomData` allowed in the first place?_ Given this behaviour, there is no guarantee that `foo` is assigned at all in the right-hand side of the `&&` operation.

If I understand correctly, the compiler should throw this error on the first use of `foo.CustomData` already!
