### ISSUE TITLE
Switch Expression Crash

### ISSUE THREAD

**Issue by supertx2** [dotnet/roslyn#39522]
https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLRIMaOQSwG4SoAOsMECAdsgDQwg4A21AJiANQA+AAgEwCMAWABQwrgGYABLwkBlABZQiECQG8AvqMnSAwjgQYGykLIVLVUyWAYB7WBIBKUZjjjIA3BI1DxUng4gYMFAUAOaGEsbyisoqFhJWtjASAOo4zDByHj4JdgASEDghcjAeXpq+EtrCKsISdXFcACwSALIAFFFmyKYQAJS19TVC9SMSAPoSALwSbdbAAFYBML1t3dESyADuODAYcgOjqgeH9br64RhTAHwzvdeqatTHJ+P3GQjWmxIUEF8AkhRmBAAB4AeTgMFBYEcoQgAFFgRgIEQYDhrBQ2v1hic1L03McvGogA===

```
using System;

public class Shape {}
public class Circle : Shape { public float Radius; }
public class Rectangle : Shape { public float Width; public float Height; }

public class C
{
    public void M(Shape shape)
    {
        _ = (object)(shape switch
        {
            Circle c => () => {},
            _ => throw new IndexOutOfRangeException()
        });
    }
}
```

This causes a crash in Visual Studio every time it opens

**Comment by 333fred** [comment]
@gafter please take a look.

**Comment by gafter** [comment]
This [bug in 3.3.1](https://sharplab.io/#v2:C4LglgNgNAJiDUAfAAgJgIwFgBQPkGYACNQgZQAsBDABwFNCBvAXzyJIGEwAnAYwnpBkqdRsSIAzCAHtKwQgCVKMMAFcAzgG5CLbAWKoFtHsEoA7AOb9CgijXoMxhSTLkB1MDGDkte57MIAErRg5uTAWjqs+oTsOAw4hImOyAAshACyABS2ImrCtACUCUnx2EnlhAD6hAC8hJlSAEYAVkbABZl5doRqAO5gwDzkxRWMI6NJnLxWPLUAfPUF84xMUOMTVcteXFK9hKa0ewCSpjC0AB4A8irAl+KKFrQAouc8tNTAYFKmmUVlE0wChpxjomEA=) appears to be [fixed in master](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxASwDZICYgNQA+AAgEwCMAsAFDVEDMABKQwMoAWEADnAwN4C+tRswDCaBAGMMPEKw7c+TRgDMMAewgwGAJQjY0AVygBuBoKr0mJHXAkwIAOwDm0hrPZcevJQ1UatAOpo2DBsppZ+mgwAEnBoTmwwpuZCVgwi1LzUDDk+RAAsDACyABQeClDycACU2blZVLlNDAD6DAC8DCVqwABWtjDVJZWeDFAA7mgwEmx1zXxz87likq4SHQB8XdWbfPxIi0utu6EIauMMDnAXAJIO2HAAHgDyBjDPyrrOcACijxJwTgwNBqBwlWqNJb8arGRbmfhAA=).  I believe it was fixed in https://github.com/dotnet/roslyn/pull/39104.
