### ISSUE TITLE
IntelliSense does not use pattern matcher when capital letters are present

### ISSUE THREAD

**Issue by AmadeusW** [dotnet/roslyn#39671]
**Version Used**: 16.5.0 preview 1.0 [29429.30.master]

**Steps to Reproduce**:

1. Create class PooledStringBuilder which has two methods: `ToString` and `ToStringAndFree`
2. Write code which calls `ToString` on the instance
3. I want to make this `ToStringAndFree`. I will type place caret after `ToString`, type `af` and hit Ctrl+Space.

**Expected Behavior**:
`ToStringAndFree` is selected and inserted
**Actual Behavior**:
IntelliSense has `no items` 
![image](https://user-images.githubusercontent.com/1673956/68146388-ba216b00-feec-11e9-9359-dc8fc8dfad42.png)

Let's take a closer look at what's going on.

4. Place caret at `ToString$$()` and hit Ctrl+Space to see what's happening inside IntelliSense:
5. Type `a` and observe correct intellisense selection
![image](https://user-images.githubusercontent.com/1673956/68146311-952cf800-feec-11e9-8e75-0fd0bcaa3dc6.png)

6. Type `f` and see that IntelliSense did not select the desired item
![image](https://user-images.githubusercontent.com/1673956/68146116-22238180-feec-11e9-8b03-863772a9b099.png)

**Comment by AmadeusW** [comment]
IntelliSense matches my desired method if I type "tostringaf" or "ToStringAF", and I can see how someone thought this might be a perf or ux improvement.
However, in my case, the code already had `ToString` and I want to switch it by typing `af` and not `AF`

**Comment by CyrusNajmabadi** [comment]
This is by (perf) design.  The issue is the enormous cost of pattern/word matching.  With teh appraoch you want, we would have to consider *every* lowercase letter the potential start of a string, and it explodes the computation complexity.  As such, we very explicitly state: we use yoru capital letters as the ones we consider for word-break points, and we will compare those against the actual word breaks in the words we're comparing against.

We have to balance the desire to have this powerful matching system with the goal to have it running in < 1ms *across all your potential strings*.  It was *very very very* hard to get to that point and it involved a whole lot of custom algorithms along with very specific work to try to be as alloc-free as possible.

this has also been really difficult as the change ot highlight in the completion UI means we have to write the algorithm such that it can be alloc free (for matching) and then product the spans later when the UI requests them.  This was only doable because teh design is supposed to be (though this has regressed several times) that the UI only asks for the actual spans for hte items *that are visible*.

**Comment by AmadeusW** [comment]
Thanks for the explanation. This makes sense!
