### ISSUE TITLE
Completion sugests items that do not satisfy generic constraint

### ISSUE THREAD

**Issue by pakrym** [dotnet/roslyn#39689]
**Version Used**: Version 16.5.0 Preview 1.0 [29501.166.master]

**Steps to Reproduce**:

1. Create Console app
2. Add `Azure.Storage.Blobs` Nuget package
3. Open intellisense on `args.`

**Expected Behavior**:

Extension methods that don't satisfy the generic constraint are not shown.

**Actual Behavior**:

AddBlobServiceClient is shown

![image](https://user-images.githubusercontent.com/1697911/68171664-8dd80f80-ff29-11e9-8e3c-b32ce11ed795.png)

``` C#

        /// <summary>
        /// Registers a <see cref="BlobServiceClient"/> instance with connection options loaded from the provided <paramref name="configuration"/> instance.
        /// </summary>
        public static IAzureClientBuilder<BlobServiceClient, BlobClientOptions> AddBlobServiceClient<TBuilder, TConfiguration>(this TBuilder builder, TConfiguration configuration)
            where TBuilder : IAzureClientFactoryBuilderWithConfiguration<TConfiguration>
        {
            return builder.RegisterClientFactory<BlobServiceClient, BlobClientOptions>(configuration);
        }
```

**Comment by Dreamescaper** [comment]
That does not look like native VS IntelliSense. Is that Resharper?

**Comment by pakrym** [comment]
My bad, reproes with R# disabled:

![image](https://user-images.githubusercontent.com/1697911/68223423-9cfaa400-ffa1-11e9-9717-7364b64e5e42.png)

**Comment by sharwell** [comment]
@ivanbasov This sounds like #37780 but was reported on 16.5 internal preview.

**Comment by ivanbasov** [comment]
@gafter this maybe related with https://github.com/dotnet/roslyn/pull/38109 . Maybe more work should be done on the compiler side. Please take a look.

**Comment by KirillOsenkov** [comment]
@jinujoseph this has been a reoccurring issue and would be nice to fix.

We first saw this in 16.3, then it seemed like it was fixed, now it's reoccurring again in 16.5.

**Comment by KirillOsenkov** [comment]
![image](https://user-images.githubusercontent.com/679326/80154824-33814880-8575-11ea-9ee1-26a0f83bc056.png)

**Comment by CyrusNajmabadi** [comment]
@genlu ptal.

**Comment by genlu** [comment]
This seems to be a compiler issue. [`ReduceExtensionMethod`](http://sourceroslyn.io/#Microsoft.CodeAnalysis.CSharp/Compilation/CSharpSemanticModel.cs,1666) is unable to filter out the the symbol that doesn't fulfill the constraint like this

```cs
    public interface ISomeInterface<T>
    { }

    public static class Ext
    {       
        public static bool SomeExtMethod<T1, T2>(this T1 builder, T2 x)
            where T1 : ISomeInterface<T2>
        {
            return true;
        }
    }
    public class Bar
    {
        void M(string[] s)
        {
            s.$$
        }
    }
```

FYI @dotnet/roslyn-compiler

**Comment by AlekseyTs** [comment]
This is by design. We cannot check constraints that depend on type parameters that cannot be inferred from ```this``` argument.

**Comment by jaredpar** [comment]
Adding in a bit of history to issue. The idea of how to handle extension methods and dependent type parameters first came up in #11166. This was based on user feedback and the decision was to ignore dependent constraints when considering extension methods. The motivating scenario is very similar to the one laid out here but with `class` constraints instead of `interface` ones:

```
public static class Extensions {
  public static BC SetMember<BC, TMember>(this BC This, TMember NewValue) 
     where BC : BaseClass<TMember> { }
}
```

The behavior of including these methods got reverted during the C# 7.3 development as a part of implementing the `unmanaged` constraint. That resulted in issue #37780 asking us to restore this behavior which was done in PR #37022. 

Note: the scenarios are all a bit different in the specific details but they are all essentially oscillating on the idea of how we should handle constraints in extension method reduction. Particularly when they are not fully inferable when dotting off the receiver. 

Overall though this is a case where the compiler is being asked to operate with imperfect information. Hence we end up with a heuristic vs. more definitive behavior. There were some discussions about how we could tune this to make this case better without breaking the existing cases by special casing interfaces to a degree. This is not a trivial fix though and it's unclear how grokable this is going to be for end users where as the behavior today is fairly easy to explain. Reactivating the issue for the purpose of exploring that idea though and seeing where we end up.

Note: readers should note that overall this API pattern is decidedly unfriendly for VB users as they must resort to explicit type parameters here.
