### ISSUE TITLE
Reopen intellisense after break in typing

### ISSUE THREAD

**Issue by kendrahavens** [dotnet/roslyn#39784]
[Customer feedback]

> I start typing the name of something and for whatever reason don’t complete typing it, it would be nice if the editor would realize that I am typing again and prompt me with choices. As it is I have to delete the entire variable name and hit the first letter again. 
Or remember to type Ctrl+space to reopen intellisense.

![7C7CFB15-25A2-46A8-B157-7BB169583690](https://user-images.githubusercontent.com/8293542/68707743-31877800-0547-11ea-836f-d82adf9af2ff.GIF)

**Comment by CyrusNajmabadi** [comment]
That seems really dangerous as it will capture the caret and prevent further movement.  At some point i think it's acceptable to say: we've had a keystroke to invoke intellisense for 20+ years.  It's worthwhile to learn some basics about the tool and work within those boundaries.

**Comment by mavasani** [comment]
Design meeting review: 

1. Likely a risky change 
2. Difficult for users to discover and remember any special keys to trigger completion 
3. Potentially can include a new option to show completion when a character is typed after an identifier 

**Conclusion:** Follow-up with Dustin, KevinPi and/or Cyrus to understand if we have a specific reason why we cannot turn on completion after a character is typed after an identifier. If we have no known reason, we can turn this on by default.

**Comment by CyrusNajmabadi** [comment]
> Conclusion: Follow-up with Dustin, KevinPi and/or Cyrus to understand if we have a specific reason why we cannot turn on completion after a character is typed after an identifier.

This stems back to how we tried to implement intellisense back in the VS2005 days.  We actually had the above model and it was *viciously* hated by people.  i.e. people got the new intellisense experience and tore into us about how much they disliked this.  

Our compromise was to take this back a bit and make it so that it isn't typing any character that launches intellisense, but just typing the start of the word.  And, even this was something that had a lot of psh-back from people.

I think the experience we have now is a suitable balance of being helpful, while not being too invasive.  I would be *extraordinarily* hesitant about the above approach before every moving forward with it.  I'll also point out that i don't think we see that behavior *anywhere* despite being something that i know other products have tried.  Strongly indicating that it's just not a good experience to have a focus-capturing UI element be so aggressive in coming up when typing.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedbck.
