### ISSUE TITLE
Perf optimization for DesignerCategoryAttributeIncrementalAnalyzer

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#39782]
See comments at https://github.com/dotnet/roslyn/pull/39699#issuecomment-553060127. We can potentially fast track the analyzer to skip all projects that do not have `DesignerCategoryAttribute` defined in the compilation, instead of doing so for each document.

**Comment by mavasani** [comment]
Another suggestion from @CyrusNajmabadi 

> Does the incremental-analyzer subsystem have a similar 'RegisterStart' characteristic like the diagnostic-analyzer subsystem? It would be great if it could just say "should i bother to even run on this project?" and then avoid all work if it doesn't need to.

This system does not have a Start notification, as unlike the analyzer driver, the solution crawler does not retain any state about what parts of the solution/project have been analyzed or not.

**Comment by CyrusNajmabadi** [comment]
Really dumb question... why do we have these separate systems, as opposed to a unified system across both of these? It really seems like the Diagnostic-Analyzer subsystem is effectively a *finer grained* versions of what we want the Incremental-Analyzer subsystem to be.

i.e. the Incremental-Analyzer system is about analyzing solutions/projects/docs in the bg in an efficient manner.  THe Diagnostic-Analyzer is the same, just about being able to register specific things to operate on. 

It seems like we would benefit from having the IncrementalAnlayzer system just expand on what we already have.  We could then potentially make it public as well if users would find it valuable.

**Comment by mavasani** [comment]
Yes, I like that proposal. In fact, I have been thinking for quite a while about solution/workspace level analyzer API, something that users can possibly execute on demand in the IDE and also potentially enforce in CI (that part might be tricky), and we can then move the incremental analyzer system to the same API.

**Comment by CyrusNajmabadi** [comment]
Anotehr optimization i'd like to see (esp. now that editorconfig is part of the compiler):

Many analyzers are pointless to run on nodes/etc. because their option is simply disabled for the files they're operating on.  It would be nice to either:

1. have specific analyzer registration apis where you can pass in an option and only have teh feature run if the option is on.
2. update our analyzers to actually register start actions where they check the option and avoid all the node checks if they're not even going to bother running.

we really don't do a great job of features basically having a way to say, or saying, "i don't need to run because i couldn't impact the user experience".  It would be great to get there from both a design and impl level.

**Comment by mavasani** [comment]
+1. I recently added a similar performance optimization in the analyzer driver to skip callbacks on files if end user has suppressed all possible diagnostics from the analyzer via editorconfig based configuration (https://github.com/dotnet/roslyn/pull/38793). Your request would build on that to do something similar for option based suppression.

**Comment by jinujoseph** [comment]
@mavasani whats the amount of perf gain we are looking at + the cost of getting there.
Currently marked for 16.5 but we can move based on the above

**Comment by CyrusNajmabadi** [comment]
We did optimize here.
