### ISSUE TITLE
Incorrect suggestion from code helper (Inline temporary variable)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39820]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/792359/incorrect-suggestion-from-code-helper.html)._

---
See screenshot.

The suggested code ignores the `out` keyword in the method signature, incorrectly suggesting null in place of the variable in future calls.

![100575-screenshot-3](https://user-images.githubusercontent.com/10605811/68884153-6c181e80-06c7-11ea-8884-24f54a64f568.png)

---
#### david.c.day on 10/24/2019, 03:14 AM: 

(private comment, text removed)
#### Visual Studio Feedback System on 10/25/2019, 00:11 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 10/31/2019, 03:47 PM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
This is working as designed (and even provides notification in this case):

![image](https://user-images.githubusercontent.com/4564579/76376698-28949080-6306-11ea-8114-004723a74099.png)

Specifically, we inline the value into all the places we can, and we give an error about the places we cannot.  Because we cannot inline into all locations we do not remove the declaration so that the code can continue to work.
