### ISSUE TITLE
Simplify using fix messes with formatting

### ISSUE THREAD

**Issue by JohanLarsson** [dotnet/roslyn#39864]
![Animation](https://user-images.githubusercontent.com/1640096/69036644-9ed35700-09e6-11ea-9b9e-f1e59b526daa.gif)

Probably a good idea to add some tests with trivia.

**Comment by CyrusNajmabadi** [comment]
Tagging @heejaechang

**Comment by sharwell** [comment]
> Each statement is marked with a formatted annotation

This should not be occurring. The statements should be outdented, but no other formatting should change.

**Comment by CyrusNajmabadi** [comment]
that's precisely what the formatting annotation should do.  That was a core part of the design originally.  Features aren't supposed to have to mess with trivia unless they are doing something *feature specific*.  They are supposed to simply state which items the formatter should fix back up.

**Comment by heejaechang** [comment]
what is repro code?

**Comment by heejaechang** [comment]
by the way, if formatting is bad, just rewrite one :)

**Comment by heejaechang** [comment]
ah, I think I know what is going on. so. outer block is removed, so if statement is un-indended once, making all its associated node to move along if "if statement" (called Anchor operation), and I think there is some conflicting rule over the pattern expression used above.

one way to test it will be, just do regular formatting on same code with wrong indentation

```
          void method()
          {
// wrong indentation
if (c is { Parameters: ... 
    parameters.Count ...

           }
```

and see whether parameters.Count move along with it. if it doesn't there is some bad rule overriding "if"'s anchor operation. 

we used to have formatting rule visualizer in Kirill's editor app, if someone still has it, people can see what rules are applying to the if statement, if not, probably need some digging to figure out rules applying to "if" statement.

**Comment by CyrusNajmabadi** [comment]
note: it reproes with any expression, it doesn't need to be a pattern.  For example, i was able to repro it with:

```c#
            using (IDisposable v = null)
            {
                if (items[0] ==
                    null)
                {

                }
            }
```

Any multi-line expression seems to lose its indentation

**Comment by heejaechang** [comment]
actually, I should not say it is something around pattern, since capture doesn't show right side of the code. but regardless anchor operation seems broken.

my guess is v = null); has only elastic trivia until "if" token, so formatter doesn't know whether between ";" and "if", it should count it as 1 lines or 0.

probably adding new line after ";" explicitly will fix the issue.

if that fix the issue, then fixing engine to use new line operation to find out whether "new line" will be inserted between ";" and "if", so anchor operation should be applied is I guess root fix for this kind of situation.

but, that will make a lot more cost on anchor operation, since it needs to check every time whether there will be new line added between anchor token and its previous token.

I will say just add "new line" trivia after ";" to help formatter that there to see context.

**Comment by heejaechang** [comment]
thinking a bit more. I think what happen is

formatter sees it as
```
                   blah blah; if (blah blah ==
                          whola blah) ...
```
due to the elastic trivia, and elastric rule on ";" make "if" to move down, which make anchor operation to maintain delta "if" and "whola", making it unindented.

again, my guess is adding "new line" trivia after ";" explicitly will fix the issue.

**Comment by JohanLarsson** [comment]
![Animation](https://user-images.githubusercontent.com/1640096/69330690-af3c3980-0c53-11ea-8361-1bb190d986d9.gif)

Another case that is not well handled.

**Comment by JohanLarsson** [comment]
![Animation](https://user-images.githubusercontent.com/1640096/69330836-00e4c400-0c54-11ea-83c5-6de9131a6054.gif)

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/42311
