### ISSUE TITLE
Move introduce local to the top of the list

### ISSUE THREAD

**Issue by JohanLarsson** [dotnet/roslyn#39977]
![indroduce_local](https://user-images.githubusercontent.com/1640096/69460061-75faeb00-0d73-11ea-8bad-1a332b0836c7.gif)

I'm thinking discard should be rare.

**Comment by CyrusNajmabadi** [comment]
I'm not sure i agree with htis.  One is a squiggle and is "in your face", the other is a refactoring.  I'ts not clear to me why I, as a user, would think that i would be doing a random refactoring versus fixing the thing that is directly showing up for me in the UI with squiggles.

**Comment by JohanLarsson** [comment]
In this case the random refactoring happens to fix the warning. It could be offered as an alternate fix. Reason I prefer it first is that as a long time r# user I'm used to typing the expression and have r# generate the declaration.

**Comment by ryzngard** [comment]
I agree, both of these provide a valid solution to the squiggle. Why is a discard more desirable than a named variable? 

Maybe the value is that you won't introduce any other problems, like an unused reference.

**Comment by dpoeschl** [comment]
Design Meeting Notes

We will investigate the telemetry of which option is chosen more _when both options are present in the lightbulb_, and make a decision based on that data.

**Comment by BhaaLseN** [comment]
Some food for thought: CodeRush has an option to their refactorings/code providers by frequency of use*; so over time the more frequently used ones are on top (even if they started towards the bottom).
So instead of just deciding on the ordering for an upcoming release of VS, just learn straight from the users behavior.

The only caveat would be that two equally likely options like the ones mentioned here (use discard vs. introduce local) might cause them to end up in a different order every other time if the user ends up picking the not-first one because it makes more sense in a given situation (but at least from my experience with CodeRush, this only affects a very small number of refactorings and may not matter at all for most users).

*) that is, aside from commands provided by VS itself (which appear in the order determined by VS). They always appear on top of ones provided by CodeRush (which appear in the order of most frequent use)

**Comment by CyrusNajmabadi** [comment]
Ping @jmarolf .  Do we have telemetry here?  If not, how can we get it?

**Comment by jmarolf** [comment]
@CyrusNajmabadi thanks for assigning to me, makes it easier to keep track of. I'll dig into stuff today and post what I find.

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of response.  We are tracking this holistically by looking at code action telemetry, and adjsuting accordingly.
