### ISSUE TITLE
Use multiplex stream from StreamJsonRpc

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#40146]
This will allow us to use a single stream over a single remote connection for all remote calls.

**Comment by heejaechang** [comment]
this is the library 
https://github.com/AArnott/Nerdbank.Streams/blob/master/doc/MultiplexingStream.md

StreamJsonRpc already use it so, it won't be new dll in RPC
...

to use it, one needs to create ServiceHub service asynchronously. so instead of using ctor like (http://sourceroslyn.io/#Microsoft.CodeAnalysis.Remote.ServiceHub/Services/SnapshotService.cs,17) use static method with same signature
public static Task<IDisposable> CreateAsync(Stream stream, IServiceProvider provider)

...

once we have it, we can make 

http://sourceroslyn.io/#Microsoft.VisualStudio.LanguageServices/Implementation/Remote/ServiceHubRemoteHostClient.ConnectionManager.cs,15

to pool all connections per service regardless whether there is callback object or not and remove any special case on RemotableDataJsonRpc and don't share it between multiple connections.

instead, from the main stream we get from servicehub, create 2 sub streams, one for service and one for remotable data as in here (http://sourceroslyn.io/#Microsoft.VisualStudio.LanguageServices/Implementation/Remote/ServiceHubRemoteHostClient.ConnectionManager.cs,126)

basically get rid of _remotableDataRpc field.
...

another benefit is we no longer needs this (ServerDirectStream, ClientDirectStream - http://sourceroslyn.io/#Microsoft.VisualStudio.LanguageServices/Shared/ServerDirectStream.cs,295e8f9b6d37ecc3,references) since we can just create new substream from servicehub stream rather than we create our own named pipe for one off stream.
...

and get rid of snapshot service which is counter-part of remotable data rpc stream (http://sourceroslyn.io/#Microsoft.CodeAnalysis.Remote.ServiceHub/Services/SnapshotService.cs,13)

it was there to workaround the service hub limitation where stream can be only created from VS side, now since we can create a substream as we want, we can use the remotable data substream we just created and connect it directly to JsonRpcAssetSrouce (http://sourceroslyn.io/#Microsoft.CodeAnalysis.Remote.ServiceHub/Services/SnapshotService.JsonRpcAssetSource.cs,28)

...

sure needs to be some refactoring and tweak. but that's the work to adapt multiplex stream for us.

**Comment by tmat** [comment]
Superseded by https://github.com/dotnet/roslyn/issues/40512.
