### ISSUE TITLE
VB Curious CodeFix suggestion with forgotten Extension Attribute

### ISSUE THREAD

**Issue by vbspoony** [dotnet/roslyn#403]
Hey all,
 
I have this, and the compiler cannot find the method ToNormalDateInfoString because I forgot to put the Extension-Attribute above it.
But – the CodeFix I got presented I do not understand. 
I think the CodeFix doesn’t make any sense, but maybe I just fail to understand what’s leading to this:

![codefixerror](https://cloud.githubusercontent.com/assets/9663150/6143483/c7cae9fe-b1c9-11e4-81e6-c84d45cfc21a.png)

Thanks,
 
Klaus

**Comment by shyamnamboodiripad** [comment]
This looks like a bug - since property with same name already exists, it shouldn't be offering to create the method ShortPeriod(). If at all, it should be offering to create the ToNormalDateInfoString(). The issue here may be that we don't process the case where the property is of a nullable type (i.e. DateTimeOffset?)

**Comment by jmarolf** [comment]
This does not have to do with nullable types. I believe this is fixed in the next public release after CTP 6. I cannot repro this on the most recent (internal) build of roslyn..
