### ISSUE TITLE
IntelliSense in multi-targeted projects shouldn't show warnings when APIs are merely hidden

### ISSUE THREAD

**Issue by terrajobst** [dotnet/roslyn#40370]
> The "this is only available on one side" logic is implemented by computing the list for both targets; it merges all the times together and if it didn't appear on one side or the other then the warning is given.

That's what I thought. I don't think the current behavior is desirable. You show a warning in IntelliSense that never materializes as a diagnostic when building. As this issue demonstrates, this is confusing because IntelliSense claims an API to be unavailable when in fact it is available but hidden. If the API is marked as `EditorBrowsable.Never` across all configured TFMs, then hiding the API entirely in the merged IntelliSense makes sense to me. But even in that case, the completion window wouldn't show a warning icon.

> 1. EditorBrowsableState.Never is the IDE's ultimate back compat nightmare: any time we change this, somebody else will complain instead. At this point, we don't touch it unless we have a really good reason to. This is something we'd have to consider carefully, and I could imagine somebody else might come up with a reason we simply can't change this.

That's why I'd like to avoid having to change the API declarations.

> 2. The IDE behavior looks like a feature here for other scenarios.

I don't buy the described scenario. If the person obsoletes the API for one TFM, then the consumer will get a warning when building for that TFM. Keep in mind that when people use multi-targeting they often do so because they need to support multiple versions of the same TFM. In that scenario you're often forced to call API that was obsoleted/hidden in a later TFM because the replacement isn't available in the earlier TFM. In that scenario, not showing me the API is the opposite of being helpful.

_Originally posted by @terrajobst in https://github.com/dotnet/runtime/issues/720#issuecomment-564329609_

**Comment by CyrusNajmabadi** [comment]
I'm a bit confused reading through this myself.  It looks to be behaving *exactly* as i would expect.  

Here's my reasoning:

![image](https://user-images.githubusercontent.com/4564579/70843044-77eb2380-1de0-11ea-8a28-634dc0adb4ef.png)

1. You are calling something called `.InterfaceIsDual` from a piece of code that will be compiled in two scenarios (net472 and netcorapp3).  
2. `.InterfaceIsDual` was marked as something that users should not use in netcoreapp.  The author explicitly marked the member that way.  
3. Intellisense is telling you: hey... yes you can use this... but it's not a good idea, because in netcoreapp3 this api is something that you shouldn't be using.

This seems lke a *good* warning.  If i was writing code i would *want* to know this.  The alert makes me aware that htere's something wonky here that i definitely need to look into because one of my targets doesn't want me to use this member.

**Comment by terrajobst** [comment]
The popup says “not available” which simply isn’t true. The warning implies there will a compilation error which isn’t going to be the case.

If the experience for the warning would be keyed of the ObsoleteAttribute this behavior would make sense. Keying it off of EditorBrowsableAttribute seems broken to me.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by CyrusNajmabadi** [comment]
The purpose of EB(never) is for API designers to let users know that they should think of the api as being not available. I.e. it's a mistake that can't be undone, or it's there just as a detail only for use internally. The intent really is to say: this doesn't exist, don't use it. 

So this behavior makes sense to be. The user should think of this API this way.

**Comment by terrajobst** [comment]
I don’t agree with that but I also don’t feel strongly enough to push for this more.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by CyrusNajmabadi** [comment]
I think this ties into what jason was saying: if we change EB in any way, it's always something bad.  If we change this to not hide here, we will lkely get someone coming along saying: but we used EB to hide these members so that people would be warned in multi-targetting.  That doesn't work now.  Bug! :(

**Comment by terrajobst** [comment]
This come up today in @dotnet/fxdc. We'd like to have a conversation about this behavior b/c an editor browsable never API isn't meant to indicate "won't work".

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of movement in many years.
