### ISSUE TITLE
TFS doesn't auto checkout files in VB Winforms Project

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#4039]
Filed on behalf of LMKz from comment on [this blog post](http://blogs.msdn.com/b/somasegar/archive/2015/07/20/visual-studio-2015-and-net-4-6-available-for-download.aspx#10629520).

**Repro Steps:**
In a Visual Basic windows forms project connected to TFS, open a form in the designer, then press F7 to switch to code. Start typing. The file is not auto checked out, and you cannot edit without manually checking out.

**Comment by davkean** [comment]
Was able to repro this with C# and VB, here's what I found:

1) This also affects C#, the code behind (Form.cs) and the designer file (Form.Designer.cs)
2) If I drag a control onto a checked-in Form, I get the below error [1], but then both the Form.cs and Form.Designer.cs files are checked out.
3) This only seems to affect WinForms. I tried WPF and it correctly checked out the items at the appropriate time.

[1] 
---------------------------
Microsoft Visual Studio
---------------------------
Failed to create component 'Button'.  The error message follows:

 'The file c:\users\davkean\documents\visual studio 2015\Projects\WindowsApplication2\WindowsFormsApplication1\Form1.Designer.cs cannot be modified at this time.'
---------------------------
OK   
---------------------------

**Comment by davkean** [comment]
This is worse than above, if appears that if the project is connected to source control, you cannot drag any control onto WinForms designer regardless of whether the underlying form (and designer.cs) is checked out.

**Comment by davkean** [comment]
Found the issue, it's a bug in AbstractEditorFactory and occurs whenever we create an editor for an existing doc data (another repro would be to open a C# file, choose Window -> New Window and see that both have turned read-only).

In this particular this piece of code is incorrect:

``` C#
            // If the text buffer is marked as read-only, ensure that the padlock icon is displayed
            // next the new window's title and that [Read Only] is appended to title.
            READONLYSTATUS readOnlyStatus = READONLYSTATUS.ROSTATUS_NotReadOnly;
            uint textBufferFlags;
            if (ErrorHandler.Succeeded(textBuffer.GetStateFlags(out textBufferFlags)) &&
                0 != (textBufferFlags & ((uint)BUFFERSTATEFLAGS.BSF_FILESYS_READONLY | (uint)BUFFERSTATEFLAGS.BSF_USER_READONLY)))
            {
                ((IVsPersistDocData2)textBuffer).SetDocDataReadOnly(1);
                readOnlyStatus = READONLYSTATUS.ROSTATUS_ReadOnly;
            }
```
We're attempting set read-only flag so that the padlock shows up, but it's broken for a few reasons:

1) This only actually runs on the creation of a second editor over an existing doc data. On the first creation, the doc data that we're looking at is effectively empty with zero state set or data. That's filled in later by the editor manager in VS Core.

2) On second editor case, what we're effectively doing is reading the state flags, and then if includes any read-only state forcing the state flags to include user read-only (SetDocDataReadOnly means  "set state flags to include BSF_USER_READONLY).

We don't ever actually need to call SetDocDataReadOnly, we don't own loading the buffers that we create - those that do, already set this correctly.

**Comment by winklerp** [comment]
Any Hotfix planned for correcting this issue?

**Comment by davkean** [comment]
There are no current plans to ship a hotfix for this, there are a couple of workarounds:

1. If you are using TFS, convert your workspace into a local workspace (https://msdn.microsoft.com/en-us/library/bb892960.aspx. You are likely using a server workspace currently, which leaves the files as read-only, making it more likely to hit the problem. Added benefit to local workspaces is that tend to be a lot faster for small to medium sized workspaces and there’s less communication with the server.

2. Check-out the form before opening it in the designer/code editor.

If you would like request a hotfix because the above workarounds do not work for you, please contact our support team http://support.microsoft.com.

**Comment by MeaningOfLights** [comment]
Other solutions: http://stackoverflow.com/questions/37715212/the-file-c-tfs-form1-cs-cannot-be-modified-at-this-time
