### ISSUE TITLE
[Proposal] Ability to prevent call some methods if some method was called

### ISSUE THREAD

**Issue by KalitaAlexey** [dotnet/roslyn#4048]
Example
```
class List
{
    [Enables(RemoveAllElements)]
    [Enables(PopFirst)]
    [Enables(PopLast)]
    public void AddElement(int element) { /* Implementation */ }

    [DisabledByDefault]
    [Disables(PopFirst)]
    [Disables(PopLast)]
    public void RemoveAllElements() { /* Implementation */ }

    [DisabledByDefault]
    public int PopFirst() { /* Implementation */ }
    [DisabledByDefault]
    public int PopLast() { /* Implementation */ }
}
```

**Comment by whoisj** [comment]
Isn't this just a state of your object kind of thing?

Do you have an example of this being implemented in another language?

Do you have an example of you see this being used in actual code?

Do you expect this to be thread-safe?

**Comment by KalitaAlexey** [comment]
@whoisj 
1) It is just a state of object, but it is good to prevent invalid method call sequence at compile-time than at run-time.
2) No, none of languages implements this feature. C# will be revolutionary
3) Yes, of course
```
public class Service
{
    public void Initialize() { /* Implementation */ }
    public void SetIdentifier(int identifier) { /* Implementation */ }
    public void SetAdditionalInformation(string additionalInformation) { /* Implementation */ }
    public void Start() { /* Implementation */ }
    public ServiceData ReceiveData() { /* Implementation */ }
}
```
Could you use this class?
Do you know in which sequence methods must be called?
I think the following example more clear
```
public class Service
{
    [Enables(SetIdentifier)]
    [Enables(SetAdditionalInformation)]
    [DisablesItself]
    public void Initialize() { /* Implementation */ }
    [DisabledByDefault]
    [DisablesItself]
    public void SetIdentifier(int identifier) { /* Implementation */ }
    [DisabledByDefault]
    [DisablesItself]
    public void SetAdditionalInformation(string additionalInformation) { /* Implementation */ }
    /* I don't know how hard to implement this attribute */
    [DisabledByDefault]
    [DisablesItself]
    [EnabledAfter(SetIdentifier, SetAdditionalInformation)]
    [Enables(ReceiveData)]
    public void Start() { /* Implementation */ }
    [DisabledByDefault]
    public ServiceData ReceiveData() { /* Implementation */ }
}
```
Now you should not have a documentation that describes algorithm of initialization because compiler will check correct order.
It is verbose, but it is error-free

**Comment by dsaf** [comment]
Sounds like something that potentially could fit into #119, but it might be too specific to be a part of language. Could it not be implemented as a custom analyzer though? Simply checking the order of calls and/or executing a state machine validator.

**Comment by HaloFour** [comment]
[Microsoft Research's Axum](http://download.microsoft.com/download/B/D/5/BD51FFB2-C777-43B0-AC24-BDE3C88E231F/Axum%20Programmers%20Guide.pdf) language had something very similar to this called protocols which applied state change transition rules to channels.  However this was managed by the channel implementation itself so it could traverse between method/message boundaries.

As implemented above you're looking at little more than metadata to drive flow analysis.  The actual state of the object would be lost between method calls since the object could be passed to/from anywhere.  So unless you put all of the logic affecting the instance into giant methods I don't see how this would provide any real value in being able determine and enforce proper state management.

To do this correctly in C# you'd probably need new syntax to define and manage state transitions which would be handled internally within the class itself.  This would prevent invalid state changes at runtime but would still suffer from the inability to really be able to enforce the logic during compilation.

**Comment by whoisj** [comment]
As meta data for static analysis, I think this is great. As hints to API adopters, it is likely useful as well (especially when coupled with static analysis).

As a compiler (somehow, magic?) or run-time enforced construct, I do not think this would work. Costs in overhead and complexity, extra pain when versioning, etc.

**Comment by gafter** [comment]
This proposal does not contain enough of a description of the semantics for us to evaluate it. However, if the intent is that the presence or absence of attributes should affect name lookup or the methods that are invoked at runtime due to elements of the source statements, I would like to point out that we try to avoid giving attributes that kind of semantic meaning.

I'll leave this open for a couple of weeks to give you a chance to fill out the proposal.
