### ISSUE TITLE
VBCSCompiler using 4+GB of Ram

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/roslyn#40576]
The screen shot only shows it at 2GB but it was all the way up to 4GB.
Is this normal?

![image](https://user-images.githubusercontent.com/13609558/71410517-40178380-260b-11ea-9c4e-b3a39b5a2f34.png)

What would I do to find out why this is happening?

**Comment by gafter** [comment]
The compiler retains in memory (caches) imported assemblies "compiled" into the symbol table data usable by the compiler. Since it is very common for a few used assemblies to be used over and over again when compiling (even different programs), this results in a significant speedup.  This is common.

If you want to "recover" that memory, you can simply kill that process.  It will be restarted with a clean slate next time you compile something.
