### ISSUE TITLE
Introduce parameter refactoring

### ISSUE THREAD

**Issue by vatsalyaagrawal** [dotnet/roslyn#40600]
Given a local variable/literal, change the containing method to include that variable/literal as a parameter, updating existing calls to the method to include the existing value as an argument.

**Comment by CyrusNajmabadi** [comment]
We had this feature.  It was never ever used by any customer ever.  (Telemetry showed *zero* usages of it ever).  So we removed it.

**Comment by sharwell** [comment]
@dpoeschl how hard would it be to reuse the new Change Signature helper services to provide a 'Promote local to parameter' refactoring?

**Comment by mikadumont** [comment]
We did receive 4 user asks for this in the past year. Also, this issue seems to be a duplicate of this: https://github.com/dotnet/roslyn/issues/22051

**Comment by CyrusNajmabadi** [comment]
Note: we actually used to ahve this feature.  Telemetry indicated taht it was our least used refactoring *across the board*.  So we cut it because it was jsut too much code/complexity versus how much usage it was getting.  If it's cheap now with teh new sig-change code i'd be more amenable to having it.  but i'm wary again of an investment here if we don't think usage will warrant it.

**Comment by dibarbet** [comment]
Design meeting notes
We would take a PR that adds a new refactoring on a local variable assigned to a constant value.  This refactoring would launch change signature to add the parameter.

**Comment by allisonchou** [comment]
Closing as a dupe of #22051.
