### ISSUE TITLE
object.Equals(null) triggers CS8602 C# Dereference of a possibly null reference.

### ISSUE THREAD

**Issue by ChrisTorng** [dotnet/roslyn#40665]
**Version Used**: 
.NET Core 3.1

**Steps to Reproduce**:
1. Set `<Nullable>enable</Nullable>` to Class Library csproj.
2. Put code in `Class1`:
```
public void Test()
{
    var a = "a";
    a.Equals(a);
    a.Equals(null);
    a.Equals(a); // CS8602
}
```

**Expected Behavior**:
No warning.

**Actual Behavior**:
`CS8602 C# Dereference of a possibly null reference.` on the second `a.Equals(a);` line.

**Note**
I found this issue in the following test:
```
Assert.IsFalse(a.Equals(null));
Assert.IsFalse(a.Equals(b)); // CS8602
```
Variable `a`'s value never been changed, why it think it's value may be null after `a.Equals(null)`?

**Comment by Joe4evr** [comment]
I think this is because of the use of `var`, which has the compiler update its beliefs about the value's nullability as it proceeds to be used. Once it encounters a comparison to `null`, it starts to believe that the value is nullable and responds accordingly at the next use-site.

**Comment by jaredpar** [comment]
This behavior is "By Design". 

The problem is indeed the line `a.Equals(null)`. This qualifies as a pure null check and informs the compiler that at this point in the program the developer believes the value `a` can be `null`. Hence going forward the compiler will consider this value potentially null (because the developer has specifically told us that is a possibility). 

Note that the compiler will only do this on branches which where the return value of `a.Equals(null)` is `true`. If you did the following it would not warn. 

```c#
if (!a.Equals(null)) {
  a.Equals(b); // no warning
}
```

**Comment by CyrusNajmabadi** [comment]
> The problem is indeed the line a.Equals(null). This qualifies as a pure null check

This feels weird to me.  If `a` were null here, then you'd get an exception and not even get to the next line.  So either `a` is null and hte nxt line is unreachable, or it's non-null and it's reachable. This pattern should help inform the compiler that `a` is *not* null on hte next line.

Right @jaredpar ?

**Comment by jaredpar** [comment]
Correct in this case you have essentially two competing pieces of data:

1. Invocation of an instance member
1. Pure null check on the member 

In this case the compiler prefers the pure null check over the instance member.

I do agree in this case the instance member invocation is the better indicator but I also don't find this example very compelling. It's invoking a pure null check, ideally side effect free, and ignoring the results.

**Comment by CyrusNajmabadi** [comment]
That makes sense to me. Thanks!

**Comment by NN---** [comment]
@jaredpar I have encountered this behavior while writing a test.
It makes unobvious that this code warns:

```cs
Assert.IsFalse(obj.Equals(null)); // Continues if 'obj' is not null
Assert.IsTrue(obj.Equals("a")); // Possible null 'obj'.
```

**Comment by jaredpar** [comment]
@NN--- 

I understand but that is the expected behavior here. The code `obj.Equals(null)` is a declaration that the developer thinks `obj` can be `null` at this line and the compiler responds accordingly. The xUnit team can help with this scenario by marking the API as `[DoesNotReturnWhen(true)]` and that would allow the compiler to respond appropriately here. But as written the code is behaving as expected.
