### ISSUE TITLE
System.AccessViolationException when invoking extension method on ValueTuple

### ISSUE THREAD

**Issue by anpaz-msft** [dotnet/roslyn#40690]
# Issue Title

With .NET Core 3.1.100 we're getting a:
`Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.` 
when invoking an extension method on a field of a `ValueTuple`.

This was fine with .NET Core 3.0.100

# General

We're trying to update the Quantum Development Kit runtime from `3.0.100` to `3.1.100` and one of our tests is failing and crashing execution with the exception mentioned above. 

I have pinpoint the problem, it happens when we're trying to call an extension method (an extension for `object`) of a field of a ValueTuple if the field is a generic Type Parameter, for example:

```C#
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;

namespace bug
{
    public static class Extension
    {
        public static String GetValue(this object value) => value?.ToString();
    }

    public partial class BGen<__T__>
    {
        public (Int64, __T__) Data { get; }

        public BGen((Int64, __T__) data)
        {
            this.Data = data;
        }

        internal String Value
        {
            get
            {
                /// This works fine:
                //var i2 = Data.Item2;
                //var q2 = i2?.GetValue();

                // This causes the AccessViolation:
                var q2 = Data.Item2?.GetValue();
                return q2;
            }
        }
    }
    
    class Program
    {
        static void Main(string[] args)
        {
            var i = new BGen<string>((0, "foo"));
            var r = i.Value;

            Console.WriteLine($"Hello World: {string.Join(',', r)}");
        }
    }
}
```

This happens on windows with version `3.1.100`. Works fine if downgrading to `3.0.100`.

**Comment by RikkiGibson** [comment]
Ref types may not be used as type arguments or in tuple fields. Could you show us where `__Canon` is being provided as a type argument? @anpaz-msft @AndyAyersMS

**Comment by AndyAyersMS** [comment]
Here `T` is actually `string`.

We informally use "ref type" to mean IL type `O` or a reference to a heap object (ref class or boxed value class).

The coreclr runtime shares generic instantiations across ref class types, since the values of that type all have the same size and ABI behavior. So in the runtime, `string` gets mapped to a special shared placeholder type `__Canon` and that's what the jit sees. But it is really `string`.

**Comment by RikkiGibson** [comment]
Thanks, that makes a lot of things click. Will investigate.

**Comment by RikkiGibson** [comment]
This bug appears to be introduced by #35979

**Comment by cston** [comment]
@RikkiGibson, thanks for investigating.

With this repro it looks like the value of `receiverTemp` at https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Portable/CodeGen/EmitExpression.cs#L406 is the tuple `(Int64, __T__)` rather than `__T__ Item2`, so the optimization in #35979 is using the wrong value.

We should consider reverting the optimization for simplicity. And we probably need to revert the corresponding change to VB as well.

**Comment by YairHalberstadt** [comment]
Fix (as opposed to revert at https://github.com/dotnet/roslyn/pull/40878)
