### ISSUE TITLE
Double clicking error in error list with file it is referencing closed does not open the file

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#40721]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/576868/double-clicking-error-in-error-list-with-file-it-i.html)._

---
Compilation error in C# project shows CS0103 and CS7036 errors, but when i double click them, it doesn't open the file even if the file is open but not in focus.

---
#### Visual Studio Feedback System on 5/22/2019, 00:33 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 5/22/2019, 01:45 PM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

#### Visual Studio Feedback System on 12/31/2019, 00:26 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
I can't repro this at all.

**Comment by hpropsner** [comment]
I have this problem too (VS 2019) and when I looked closely at the file path in the Error List, the paths were subtly wrong on the offending rows. (Part of the path showed duplicated "\Views\Views\" instead of just "\Views\". It's an MVC project). When you double click the Error List row with an invalid path, nothing happens. For errors shown with the correct path, you can double-click those rows and it opens the file. So it definitely seems path-related.

For example, and actual physical path might be:       c:/users/xxxx/Projects/ThisMvcProject/Views/CRM/Entity/Show.cshtml
However the path in the Error List shows:       c:/users/xxxx/Projects/ThisMvcProject/Views/Views/CRM/Entity/Show.cshtml

In this case I would have to manually navigate to the file to fix the error, and the project builds and functions as expected. It's just the navigation from the Error List pane that is the problem. 

I spent time updating VS and trying various things like deleting the .vs and obj folders, examining .csproj file, etc. None of that helped. 

It's worth noting this doesn't happen on every file shown in the Error List. The most frequently affected are .cshtml/Razor files, at least in my experience. Happens to old files and newly added files alike, seems to be random.

I don't know where the Error List is getting the "Path" column from but this might be a clue to this longstanding issue.
