### ISSUE TITLE
Question - about lifetime & potential leakage

### ISSUE THREAD

**Issue by sujayvsarma** [dotnet/roslyn#40842]
Observe the following code-block:

```csharp
var handler = foo.SomeDelegateEventHandler;
foo.SomeDelegateEventHandler = async context => 
{
     /* do something... */

     // call the handler that we grabbed and saved earlier
     await handler(context);
};
```

What is the lifetime of the reference stored in `handler` ? What is the potential that it leaks from there?

Now, observe this code-block where this sort of thing gets nested in:

```csharp
var blah = something;
services.Configure<FooOptions>(options => 
{
      blah.UseBlahHereSomehow();

    var handler = foo.SomeDelegateEventHandler;
    foo.SomeDelegateEventHandler = async context => 
    {
        /* do something... */

        // call the handler that we grabbed and saved earlier
        await handler(context);
    };
));
```

Now you have both `blah` and `handler` …

I find this sort of thing frequently being done, especially in MVC apps, in Startup.cs. I wanted to understand the potential pitfalls and gotchas of doing this. 

What do you think?

**Comment by sujayvsarma** [comment]
Ping?

**Comment by jmarolf** [comment]
Based on the limited example you give this looks like a live-leak. These objects will be held onto forever unless someone unsubscribes them from the event handler.

Also, calling the event handler you are subscribed to feels like a code smell to me. What is the justification for doing this?

**Comment by sujayvsarma** [comment]
Almost everyone seems to be wiring up stuff in their `Startup.cs` files in aspnet mvc projects this way. Including in official Microsoft projects & samples & examples.

I find this odd, which is what prompted the question.

**Comment by jmarolf** [comment]
Can you point me to a sample in the Microsoft documentation?

**Comment by sujayvsarma** [comment]
Check this out then (this is the code block I had "anonymized" in my OP above):

https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/81afe541b69487102d8845360cf8e1fbe8041ec0/Microsoft.Identity.Web/WebAppServiceCollectionExtensions.cs#L147

**Comment by jmarolf** [comment]
ah, I see. Its not an event its just a delegate.  For some reason I read it as an async event even though this is its signature.

```csharp
// Summary:
//     Invoked after security token validation if an authorization code is present in
//     the protocol message.
static Func<AuthorizationCodeReceivedContext, Task> OnAuthorizationCodeReceived;
```

They appear to be using the chain of responsibility pattern here. Wrapping other callers by grabbing the original delegate and calling it. Depending on your scenario it is very possible that this will hold on to a large chain of objects in scope and never release them. This might be ok because perhaps all of the objects it holds onto are singletons that are supposed to be alive for the entire lifetime of the application. 

As I read the code [here](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/81afe541b69487102d8845360cf8e1fbe8041ec0/Microsoft.Identity.Web) this is intended to be called in Startup.cs and used throughout the applications lifetime to authenticate requests. In this scenario I don't know what it would mean to un-register events. Your application would cease to work without authentication. I similarly wouldn't expect parts of your application to register with this service many times. It should only happen once at startup.

**Comment by sujayvsarma** [comment]
So, would that mean that in _this_ scenario, it is okay, but it may not be appropriate somewhere else? 

My basic confusion is regarding the lifetime of an object captured at some form of a `local` scope and is then that captured reference is used inside something [typically within an anonymous function] that would execute asynchronously [on some other thread? and at a distant point in time?] -- like those Startup.cs events fire.

**Comment by jmarolf** [comment]
In  this case, all of the capture is happening inside of a static method inside a static class. Unless your static method has an enormous amount of local variables this should always be safe to do.

**Comment by sujayvsarma** [comment]
Thank you @jmarolf 

Also, thank you for teaching me about triple ` csharp. Didn't know that one 😜
