### ISSUE TITLE
InlineRenameSession should eagerly cancel unnecessary work

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#40891]
Currently InlineRenameSession only cancels certain work when the session is committed or canceled. In cases where the work is invalidated by options changes and/or typing, the work should be canceled eagerly.

See https://github.com/dotnet/roslyn/pull/34254/files#r365025055

**Comment by jasonmalinowski** [comment]
To clarify: the work that doesn't seem to be getting cancelled is the initial search for the spans that need updating. If you start a rename session and then change an option like rename overloads or something, the initial search should be getting cancelled. Instead we queue the new computation _after_ the first one, which means the first one will still run, we'll ignore the result, and then compute the real results again.

I suspect what happened here was originally we didn't support the option changing at all in the early versions of the feature, which meant the CancellationToken was readonly since there was no reason to cancel and restart. But then we added that and rather than fixing that we instead hacked around it.

**Comment by CyrusNajmabadi** [comment]
We should just do this work if necessary.  If so, it shoudl be assigned to an actual milestone.  Having a tracking issue here taht we never get to doesn't benefit us.
