### ISSUE TITLE
GetTypeInfo returns inconsistent nullability on type syntax

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#40925]
I would expect `NotAnnotated` in all cases, instead of `None` in some cases.
```
        [Fact]
        public void GetTypeInfoOnNullableType()
        {
            var source =
@"#nullable enable
#nullable enable
class Program2 { }
class Program
{
    void Method(Program x)
    {
        (global::Program y1, global::Program? y2) = (x, x);
        global::Program y3 = x;
        global::Program? y4 = x;
    }
}
";
            var comp = CreateCompilation(source);
            comp.VerifyDiagnostics();

            var tree = comp.SyntaxTrees.Single();
            var model = comp.GetSemanticModel(tree, ignoreAccessibility: false);
            var identifiers = tree.GetRoot().DescendantNodes().Where(n => n.ToString() == "global::Program").ToArray();
            Assert.Equal(CodeAnalysis.NullableAnnotation.NotAnnotated, model.GetTypeInfo(identifiers[0]).Nullability.Annotation);
            Assert.Equal(CodeAnalysis.NullableAnnotation.None, model.GetTypeInfo(identifiers[1]).Nullability.Annotation);
            Assert.Equal(CodeAnalysis.NullableAnnotation.NotAnnotated, model.GetTypeInfo(identifiers[2]).Nullability.Annotation);
            Assert.Equal(CodeAnalysis.NullableAnnotation.None, model.GetTypeInfo(identifiers[3]).Nullability.Annotation);
            // Note: this discrepancy causes some issues with type simplification in the IDE layer
        }

```

**Comment by jcouv** [comment]
I suspect this is related to https://github.com/dotnet/roslyn/issues/40750 (refactoring produces ugly namespaces)

**Comment by jasonmalinowski** [comment]
Is the problem here that some are calling GetTypeInfo() on a fragment of a type syntax? In all the cases where you got "None" would passing the node _with_ a ? give you Annotated?

**Comment by jcouv** [comment]
I think the answer should be `NotAnnotated` in both cases, because:
1. the annotation on `Program` as a whole type syntax by itself is obvious (`!`)
2. the annotation on `Program` syntax taken from `Program?` needs to match that from (1) (this condition is important for the IDE to understand what simplifications affect semantics)

**Comment by jcouv** [comment]
Tagging @333fred as FYI.
I think we should look at this issue soon (16.5p3?) because I suspect it causes problems with other refactorings (simplification is busted in nullable-enabled code).

**Comment by 333fred** [comment]
Alright, so this is one of those scenarios where it's kinda weird that `GetTypeInfo` returns anything at all. That being said, what we should return here is the type that is actually written, not any inference from the actual state. To explain why you're getting the `None`s here: you're passing the `AliasQualifiedSyntax` to `GetTypeInfo`, which does not have a corresponding `BoundNode`. Rather, the `BoundNode` we have for it is the _parent_ `NullableType` node. We then create a `BoundNode` out of nowhere for it, and we give it the default state of `None` because we can't run analysis on it. We should be noticing that the syntax is parented by a `NullableType` syntax and appropriately getting the parent instead.

Also, @jcouv, I'm not sure that this is what's causing the issue you're seeing. The only missing simplification in the test code that you shared is the `global::` on the first tuple deconstruction, which should be entirely unrelated to the what the annotation for the second part returns. I could see this being a problem with nullable, but tuple support in general is tracked by https://github.com/dotnet/roslyn/issues/35010 and is a larger piece of work.

**Comment by jcouv** [comment]
@333fred I took another look at the IDE issue I encountered, and I suspect you are right. My repro above may not be related. Sorry about that :( 
I'll let you decide whether to close this issue then (may not be a desirable scenario or worthwhile to fix after all).

Here's more details on the IDE scenario I encountered:
In `ReplacementBreaksTypeResolution` (copied below), we have:
- `newType` is `Program` in `        (Program y1, global::Program2 y2) = (x, x2);`
- `type` is `global::Program` in
```
#nullable enable
class Program2 { }
class Program
{
    void Method(Program? x, Program2 x2)
    {
        (global::Program y1, global::Program2 y2) = (x, x2);
    }
}
```
- `symbol` is `Program` with `NotAnnotated` annotation
- `newSymbol` is `Program` with `None` annotation
- therefore `SymbolsAreCompatible` returns `false` and the simplifier doesn't perform the simplification from `global::Program` to `Program`

```
        private bool ReplacementBreaksTypeResolution(TTypeSyntax type, TTypeSyntax newType, bool useSpeculativeModel = true)
        {
            var symbol = this.OriginalSemanticModel.GetSymbolInfo(type).Symbol;

            ISymbol newSymbol;
            if (useSpeculativeModel)
            {
                newSymbol = this.SpeculativeSemanticModel.GetSymbolInfo(newType, _cancellationToken).Symbol;
            }
            else
            {
                var bindingOption = IsInNamespaceOrTypeContext(type) ? SpeculativeBindingOption.BindAsTypeOrNamespace : SpeculativeBindingOption.BindAsExpression;
                newSymbol = this.OriginalSemanticModel.GetSpeculativeSymbolInfo(type.SpanStart, newType, bindingOption).Symbol;
            }

            return symbol != null && !SymbolsAreCompatible(symbol, newSymbol);
        }
```

**Comment by 333fred** [comment]
@jcouv I don't believe this bug is relevant anymore. Closing it out.
