### ISSUE TITLE
This extension is already installed to all applicable products

### ISSUE THREAD

**Issue by hickford** [dotnet/roslyn#4096]
When I try to install `Roslyn SDK.vsix` I get the error 

> This extension is already installed to all applicable products

Yet it doesn't show up in Visual Studio 2015.

I previously installed the extension on a Visual Studio 2015 beta, perhaps that's why the extension thinks  it's already installed.

**Comment by hickford** [comment]
Is there some file I can delete that will let me install again? Or a 'force install' mode for vsixinstaller.exe ?

**Comment by davkean** [comment]
Sorry for the late reply, and thanks for the feedback. This does not work today because Roslyn is considered part of Visual Studio product.

We're working on a solution that will be enabled when we release Visual Studio 2015 Update 1 RTM that will enable you to install private builds of Roslyn locally that will override what's installed on the product. You'll also be able to F5 from Roslyn solution and have it deploy and run.

We'll update the wiki with the instructions, when Update 1 RTM has been released.

**Comment by nolisj** [comment]
This is still happening for Visual Studio 2015 Update 3: the Roslyn templates are not showing up after installing the Update 3 and selecting the Extensions checkbox, and when you try to install the Roslyn SDK, the error message mentioned above is still showing?

**Comment by jmarolf** [comment]
To clarify, if you go to Tools -> Extensions and Updates...
![image](https://cloud.githubusercontent.com/assets/9797472/16793922/711c70de-4889-11e6-8e6c-c0a5191c7806.png)
 
And search for .NET Compiler Platform SDK
![image](https://cloud.githubusercontent.com/assets/9797472/16793930/7c8ac740-4889-11e6-945c-c2823419e29b.png)

Does it say that the extension is installed?

And if it says that the SDK is installed, do you see any templates under extensibility when the framework dropdown is set to .NET Framework 4.6

![image](https://cloud.githubusercontent.com/assets/9797472/16793943/8be34802-4889-11e6-998b-dbfe25d561af.png)

**Comment by hickford** [comment]
@jmarolf I think Visual Studio should hide the "Download the .NET Compiler Platform SDK" link (third screenshot) if the SDK is already installed (second screenshot)

**Comment by jmarolf** [comment]
@hickford it does not

**Comment by nolisj** [comment]
For my issues, what was not clear was you have to enable the .NET Compiler Platform SDK at the Extensions and Updates screen since it was Disabled by default. Strange that that's the default behavior of the extension after installing Update 3. Or was it the behavior if you installed the VSIX right after the Update 3?

**Comment by payelh** [comment]
Still having this issue.

**Comment by ryanseghers** [comment]
I had a lot of trouble finding the "Code Refactoring (VSIX)" template, until I noticed the "when the framework dropdown is set to .NET Framework 4.6" above. By default for me it is set to 4.5.2 and so I didn't see that template until I changed to 4.6.
