### ISSUE TITLE
Retail mode without compiler optimizations

### ISSUE THREAD

**Issue by jacdavis** [dotnet/roslyn#4103]
Tomas Matousek asked me to file this based on a conversation we were having. For dynamic diagnostic scenarios, having a compiler flag to create a pre-Roslyn style Release binary would be very nice. (sequence points removed but relying on the jit compiler / ngen to perform optimizations). This would allow us to deoptimize a method by simply requesting a rejit with jit optimizations off and injecting sequence points.

**Comment by gafter** [comment]
What kinds of optimizations does Roslyn perform in Release scenarios that you'd like to avoid?

**Comment by VSadov** [comment]
Current proposal is to use combination of
```
   /optimize+ /debug+       
```
to designate this mode.
The combination is currently unused since we only consider /optimize[+|-]

The philosophy for this combination will be - "perform optimizations except those that reduce debuggability"

At the end we will have 4 combinations:
* /optimize+ /debug-           :: optimizations are performed and if they conflict with debuggability, optimizations win
* /optimize- /debug+           :: code will be intentionally generated with additional instrumentation or different emit strategies to make it more debuggable, very likely to the detriment of performance
* /optimize+ /debug+          :: optimizations are performed, but only if they do not conflict with debuggability. There is no intentional instrumentation/deoptimizing. (I.E. locals are not elided, but no nops are emitted either)
* /optimize- /debug-           :: same as /optimize- /debug+   since we are not optimizing anyways, debug flag does not have any effect

**Comment by VSadov** [comment]
CC @jaredpar @tmat

**Comment by tmat** [comment]
I think this proposal has two issues:
1) It changes the current meaning of the command line options /debug+. Until now /debug+, /debug:full, /debug:pdbonly were all equivalent and interpreted as _emit pdb file_.
2) it conflates level of optimization with format/availability of debug information. 

I suggest an alternative: introduce a new value /optimize:debug (or /optimize:partial, etc.), so that OptimizationLevel has 3 values: Release, Debug, OptimizedDebug.
