### ISSUE TITLE
Add host provided analyzers to solution snapshot

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#41127]
Currently the solution snapshot includes analyzers specified in PackageReferences of projects contained in the solution. It does not, however, include analyzers provided by the host (e.g. via a VSIX extension). These analyzers apply to all projects, so it would make sense if the Solution itself held on these and the host would create a new solution snapshot when analyzers are discovered from VSIXes.
The host would control what workspaces receive these analyzers.

**Comment by tmat** [comment]
@heejaechang @mavasani

**Comment by heejaechang** [comment]
sounds good. if we do, these should be changed

http://sourceroslyn.io/#Microsoft.VisualStudio.LanguageServices/Implementation/Remote/RemoteHostClientServiceFactory.RemoteHostClientService.cs,235 
http://sourceroslyn.io/#Microsoft.CodeAnalysis.Features/Diagnostics/HostAnalyzerManager.cs,435

and these should be part of solution?
http://sourceroslyn.io/#Microsoft.CodeAnalysis.Features/Diagnostics/DiagnosticAnalyzerService.cs,73

and add it to solution state checksum
http://sourceroslyn.io/#Microsoft.CodeAnalysis.Workspaces/Workspace/Solution/StateChecksums.cs,13

one thing is host analyzer reference is currently handled differently than normal analyzer reference since host analyzer reference doesn't need to be shadow copied. but probably can be merged. 

http://sourceroslyn.io/#Microsoft.CodeAnalysis.Workspaces/Execution/CustomAssetBuilder.cs,34
