### ISSUE TITLE
Apparent compiler issue with differing NRT settings across project boundaries

### ISSUE THREAD

**Issue by roji** [dotnet/roslyn#41179]
Minimal repro: https://github.com/roji/EFCoreNullableIssue

Building the above produces the error: 

```
D.cs(10,34): error CS0229: Ambiguity between 'I1<string>.Foo' and 'I1<string>.Foo' [/home/roji/repros/EFCoreNullableIssue/Top/Top.csproj]
```

I've narrowed it down to a point where tweaking pretty much anything makes the error go away.

Thanks to @MNie for submitting [the original issue](https://github.com/dotnet/efcore/issues/19470) and [the initial repro](https://github.com/MNie/EFCoreNullableIssue)

Note that this repros with Microsoft.Net.Compilers.Toolset 3.6.0-beta1-20071-02 (in Directory.Build.props).

**Comment by RikkiGibson** [comment]
Is this related to #40360?

**Comment by jcouv** [comment]
Note: PR https://github.com/dotnet/roslyn/pull/40360 was merged into 16.5p3. It fixes an issue that looks very similar (same diagnostic). Let's retry the repro once 16.5p3 is publicly available.

**Comment by jcouv** [comment]
@roji I think this issue was fixed. We now try to minimize ambiguity errors in presence of nullability differences (when one interface has oblivious but this other has a not-nullable annotation `!`). The relevant fix was https://github.com/dotnet/roslyn/pull/49338 in 16.9p3.
I'll go ahead and close the issue as fixed, but feel free to re-open if the problem still occurs after this fix. Thanks

**Comment by roji** [comment]
Thanks @jcouv!
