### ISSUE TITLE
MSBuildWorkspace.Create().OpenSolutionAsync() throws NullReferenceException when run in wpf app

### ISSUE THREAD

**Issue by GaryStonerock** [dotnet/roslyn#4127]
The following line works in a console app but not if run in a wpf or win form app.  Using VS 2015, .NET 4.6 and 1.0.0 of the roslyn apis.

        private void Test()
        {
            var solution = MSBuildWorkspace.Create().OpenSolutionAsync("...").Result;
        }

Using in a window loaded event in wpf:

        private void MainWindow_Loaded(object sender, RoutedEventArgs e)
        {
            var solution = MSBuildWorkspace.Create().OpenSolutionAsync("...").Result;
        }

Stack trace:
{System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.CSharp.CSharpProjectFileLoader.CSharpProjectFile.GetReferences(CSharpCompilerInputs compilerInputs, ProjectInstance executedProject, IEnumerable`1& metadataReferences, IEnumerable`1& analyzerReferences)
   at Microsoft.CodeAnalysis.CSharp.CSharpProjectFileLoader.CSharpProjectFile.CreateProjectFileInfo(CSharpCompilerInputs compilerInputs, ProjectInstance executedProject)
   at Microsoft.CodeAnalysis.CSharp.CSharpProjectFileLoader.CSharpProjectFile.<GetProjectFileInfoAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.CodeAnalysis.MSBuild.MSBuildWorkspace.<LoadProjectAsync>d__40.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.MSBuild.MSBuildWorkspace.<GetOrLoadProjectAsync>d__39.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.MSBuild.MSBuildWorkspace.<OpenSolutionAsync>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

**Comment by paulirwin** [comment]
+1 I receive this same error from a unit test project when trying to load either a solution via OpenSolutionAsync or a class library project via OpenProjectAsync.

**Comment by Pilchie** [comment]
@mattwar can you take a look?

**Comment by mattwar** [comment]
The code that threw the exception has changed considerably recently, but I cannot repro with 1.0 bits either.

**Comment by mattwar** [comment]
Is there more information, like a specific project type that always fails?  Does it only fail inside a WPF app, but succeeds from a Console app?

**Comment by lmeyer2** [comment]
I've tried to use it in a console application and getting the same error. 

Just created a new Console Application in VS2015. Added Microsoft.CodeAnalysis.CSharp.Workspaces and Microsoft.CodeAnalysis.CSharp to the project and just added this few lines of code

```
            var workspace = MSBuildWorkspace.Create();
            var sourceProject = await workspace.OpenProjectAsync(_sourceProject).ConfigureAwait(false);
```

Can Repo with every new console application. But a WinForm Application does work

**Comment by mattwar** [comment]
@Imeyer2  when you say "added Microsoft.CodeAnalysis.CSharp.Workspaces and Microsoft.CodeAnalysis.CSharp" are you referring to those specific libraries (and not some nuget packages that indirectly reference more), and if so, are you saying you only added those two to the project?

**Comment by lmeyer2** [comment]
I've added the NuGet Packages - sorry for the confusion

**Comment by mattwar** [comment]
@lmeyer2 What kind of csharp project is being opened by the workspace?

**Comment by mattwar** [comment]
There is a scenario I know will throw null-ref exception in RTM.  If you don't have the Microsoft.CodeAnalsys.CSharp.Workspaces dll in the same directory as your exe at runtime then a bug introduced by merging the c# and vb project loading code into the workspaces.desktop dll will bypass an check that would have told you about the missing language library (via a different exception) and lead to a null-ref in the project loading code at approximately the place where the exception is being thrown for this issue.  This could be caused by not actually using the csharp workspaces nuget, or a nuget setup problem or possibly the properties on the library reference not being set to copy-to-output-directly.

**Comment by sharpdevel** [comment]
I can confirm that adding the CodeAnlysis-Nuget-Package (1.0.0) to the console application solves the issue.

**Comment by paulirwin** [comment]
@sharpdevel What is "CodeAnalysis-Nuget-Package" or what is the actual NuGet package ID for that? And is that being added to the application that is opening of the csproj via Roslyn, or the application that is being opened by Roslyn, or both?

**Comment by sharpdevel** [comment]
I have a console application and and a class library. The class library references this package: https://www.nuget.org/packages/Microsoft.CodeAnalysis/1.0.0. The console application did not reference it. The console application called a method in the class library which itself called OpenSolutionAsync. The call failed with a NullReferenceException. After adding the nuget package to the console application everything worked fine.

**Comment by Pilchie** [comment]
Thanks for the confirmation.

**Comment by vikash-gupta** [comment]
Solution given by @sharpdevel worked for me as well. However if Microsoft.CodeAnalysis is required, then can you please add it as a NuGet dependency so that the code doesn't blow up at runtime.

**Comment by Pilchie** [comment]
@vikash-gupta: the dependency already exists.  The issue here (if I understand correctly), is that the call was in a library that had the NuGet package, but that library was used from an exe that *didn't*, so the exe didn't deploy the dependency properly.

**Comment by vikash-gupta** [comment]
Hello @Pilchie, in my case I didn't have a library. Steps to reproduce:
1. Create new console app on.NET 4.5.2 in VS2015
2. in package manger console
```powershell
Install-package Microsoft.CodeAnalysis.Workspaces.Common -version 1.0.0
```
After that package.config looks like:
```xml
  <package id="Microsoft.CodeAnalysis.Analyzers" version="1.0.0" targetFramework="net452" />
  <package id="Microsoft.CodeAnalysis.Common" version="1.0.0" targetFramework="net452" />
  <package id="Microsoft.CodeAnalysis.Workspaces.Common" version="1.0.0" targetFramework="net452" />
  <package id="Microsoft.Composition" version="1.0.27" targetFramework="net452" />
  <package id="System.Collections.Immutable" version="1.1.36" targetFramework="net452" />
  <package id="System.Reflection.Metadata" version="1.0.21" targetFramework="net452" />
```
3. Code below compiles without any error or warning
```c#
var solution = MSBuildWorkspace.Create().OpenSolutionAsync("...").Result;
```
4. Run time exception message
```c#
Object reference not set to an instance of an object.
```
Stack trace-
```c#
   at Microsoft.CodeAnalysis.CSharp.CSharpProjectFileLoader.CSharpProjectFile.GetReferences(CSharpCompilerInputs compilerInputs, ProjectInstance executedProject, IEnumerable`1& metadataReferences, IEnumerable`1& analyzerReferences)
   at Microsoft.CodeAnalysis.CSharp.CSharpProjectFileLoader.CSharpProjectFile.CreateProjectFileInfo(CSharpCompilerInputs compilerInputs, ProjectInstance executedProject)
   at Microsoft.CodeAnalysis.CSharp.CSharpProjectFileLoader.CSharpProjectFile.<GetProjectFileInfoAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.CodeAnalysis.MSBuild.MSBuildWorkspace.<LoadProjectAsync>d__40.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.MSBuild.MSBuildWorkspace.<GetOrLoadProjectAsync>d__39.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.MSBuild.MSBuildWorkspace.<OpenSolutionAsync>d__34.MoveNext()

```
Now comes the workaround fix
1. In package manger console:
```powershell
Install-package Microsoft.CodeAnalysis -version 1.0.0
```
2. At this stage, packages.config looks like
```xml
  <package id="Microsoft.CodeAnalysis" version="1.0.0" targetFramework="net452" />
  <package id="Microsoft.CodeAnalysis.Analyzers" version="1.0.0" targetFramework="net452" />
  <package id="Microsoft.CodeAnalysis.Common" version="1.0.0" targetFramework="net452" />
  <package id="Microsoft.CodeAnalysis.CSharp" version="1.0.0" targetFramework="net452" />
  <package id="Microsoft.CodeAnalysis.CSharp.Workspaces" version="1.0.0" targetFramework="net452" />
  <package id="Microsoft.CodeAnalysis.VisualBasic" version="1.0.0" targetFramework="net452" />
  <package id="Microsoft.CodeAnalysis.VisualBasic.Workspaces" version="1.0.0" targetFramework="net452" />
  <package id="Microsoft.CodeAnalysis.Workspaces.Common" version="1.0.0" targetFramework="net452" />
  <package id="Microsoft.Composition" version="1.0.27" targetFramework="net452" />
  <package id="System.Collections.Immutable" version="1.1.36" targetFramework="net452" />
  <package id="System.Reflection.Metadata" version="1.0.21" targetFramework="net452" />
```
3. App runs without any exceptions

**Comment by Pilchie** [comment]
Ah - got it. The packages are structured that way because we don't want to force you to have VB support if you only care about opening C# projects or vice versa.  You have to pick what languages you want support for if you just install the language agnostic Microsoft.CodeAnalysis.Workspaces.Common package.

**Comment by StanBPublic** [comment]
That was exactly my problem - code in class library ran fine under unit test (because the unit test project had Roslyn nugget package), but was failing under console app which didn't have that package and adding Roslyn package to the console project solved the problem.. I didn't realize that Roslyn is dynamic dependency..

**Comment by daveaglick** [comment]
I just hit this problem. In my scenario, I'm running a console app which brings in a library assembly via reflection that references the Roslyn libraries via NuGet packages. The library is in the same solution and itself is referenced by the console app, so everything ends up in the same directory after build.

I had initially referenced just the Microsoft.CodeAnalysis.CSharp.Workspaces package (with dependencies). Then I tried the suggestion here and brought in the omnibus Microsoft.CodeAnalysis package. Same result. The relevant stack trace is below (though it looks just like the ones above).

```
Error while executing module ReadSolution: System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.CSharp.CSharpProjectFileLoader.CSharpProjectFile.GetReferences(CSharpCompilerInputs compilerInputs, ProjectInstance executedProject, IEnumerable`1& metadataReferences, IEnumerable`1& analyzerReferences)
   at Microsoft.CodeAnalysis.CSharp.CSharpProjectFileLoader.CSharpProjectFile.CreateProjectFileInfo(CSharpCompilerInputs compilerInputs, ProjectInstance executedProject)
   at Microsoft.CodeAnalysis.CSharp.CSharpProjectFileLoader.CSharpProjectFile.<GetProjectFileInfoAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.CodeAnalysis.MSBuild.MSBuildWorkspace.<LoadProjectAsync>d__40.MoveNext()
...
```

I did some additional research and found it was throwing on this line (this is decompiled source, so not quite the same as what's in the repo):
![2015-10-15_12h16_17](https://cloud.githubusercontent.com/assets/1020407/10520305/8536e0ea-7337-11e5-9c71-e3cc9b7e58d7.png)

More specifically, it looks like `this._commandLineArgumentsFactoryService` is null. I see that it gets populated in the `CSharpProjectFile` constructor via a property on a `CSharpProjectFileLoader` parameter. I also noticed that `this._msbuildHost` was also null, though the other fields that get set by the `CSharpProjectFileLoader` were not.

One more tiny bit of information: I do have all the MSBuild stuff installed, and this exact code works find from LINQPad.

**Comment by daveaglick** [comment]
A little more information...

If I break in the `CSharpProjectFile` constructor to see what's going on, I discover I'm getting an error under the hood while trying to get the `ICommandLineArgumentsFactoryService` from the `CSharpProjectFileLoader` in the call to `GetLanguageServices(this.Language)`:

![2015-10-15_12h41_44](https://cloud.githubusercontent.com/assets/1020407/10520782/2505fe74-733a-11e5-8d52-6e6bc329d99d.png)

```
error CS1703: Multiple assemblies with equivalent identity have been imported: 'Microsoft.Build.Framework.dll' and 'Microsoft.Build.Framework.dll'. Remove one of the duplicate references.
```

I also wonder if this issue is related to (or even the same as) #2904. Both this one and that one are currently closed, and it looks like this bit of code is now totally different, so maybe this whole problem is a moot point...

**Comment by daveaglick** [comment]
Also, #2779 looks possibly related/same.

**Comment by daveaglick** [comment]
Just one more note: As @JoshVarty mentioned in #2779, the CS1703 error I was seeing looks like it was just masking the real problem and was only present because of the debugger. Adding the binding redirects referenced in that issue allowed me to take a closer look at what was really going on.

It turns out the root of the issue appears to be that there is no `ICommandLineArgumentsFactoryService` registered with MEF. I went through all 18 services that the `MefWorkspaceServices` instance knows about, and couldn't find it (I looked at the `Metadata.ServiceType` property to make sure I would see it, even if it hadn't been instantiated yet).

Is there any way to troubleshoot the MEF registrations? Any guesses as to why there's no registration for `ICommandLineArgumentsFactoryService` (as implemented by `CSharpCommandLineParserFactory` in Microsoft.CodeAnalysis.CSharp.Workspaces)?

**Comment by Pilchie** [comment]
Did you deploy Microsoft.CodeAnalysis.CSharp.Workspaces to the directory where you run your console application from?  There isn't a hard dependency on it from the language neutral workspace code, but it should be loaded if it is present.

**Comment by daveaglick** [comment]
Okay, pretty sure I've found the problem. Apparently if Project Foo references project Bar, and project Bar has an assembly reference Baz, Baz will not be copied to the output folder for Foo, even if both the reference from Foo to Bar and the reference from Bar to Baz both have Copy Local. Bar has to actually *use* a type from Baz for it to be copied over to the output directory for Foo. I didn't know this and as a result was missing the language-specific workspace libraries in my main output directory. What a nightmare for addin style project setups with dynamically loaded composition systems.

I suspect this may be the underlying cause of the problems for many of the other participants in this issue. That would explain why adding the omnibus Microsoft.CodeAnalysis package to all of their projects resolved the problem: even though they didn't need the extra dependent packages, and may not have needed the Roslyn packages at all in the "master" project, it forced inclusion of the required language-specific Roslyn assemblies that otherwise weren't being copied to the build folder.

Is there an appropriate place to add a note about this so it doesn't trip anyone else up?

**Comment by mattwar** [comment]
Yes, this is the root cause.  The null ref exception has been fixed with the code changes you noted.  But the actual problem is due to the language specific workspace library not being loaded dynamically at runtime because it is missing from the deployment directory.   If the null ref problem wasn’t happening, you’d have gotten a different exception that would have told you that the language was missing.
