### ISSUE TITLE
C#, Editor, 'Split string literals on enter' not honoring EOL convention.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#41322]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/889591/c-editor-split-string-literals-on-enter-not-honori.html)._

---
Repro:
Create or modify .editorconfig for a Solution with
```
[*.cs]
end_of_line = lf
```

Make sure the option 'Split string literals on enter' is enabled.

From a project in the Solution, Open a C# source file containing a string.

At the very bottom-right of the editor view for that file, the area displaying EOL sequence, make sure it reads "LF". If not, click it and select LF.

Place cursor in the middle of a string in the C# source file.

Hit return.

Actual:
Note that EOL sequence now, in error, reads "MIXED". The operation has unconditionally introduced CRLF.

Expected:
Honor the .editorconfig setting, and the current source file's line endings (which if consistent, i.e. not MIXED, should take precedence for this operation).

---
#### Visual Studio Feedback System on 1/19/2020, 00:31 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by tamlin-mike** [comment]
Hypothesis: Mixed EOL sequences in a file is generally an unwanted condition.

Scenario: You have a source file with at least one EOL. The EOL sequence indicator at the bottom-right of the editor view displays a consistent sequence (i.e. not `MIXED`).

When editing such a file, would it perhaps make sense to give preference to that existing EOL sequence in the file, only falling back to `.editorconfig` setting if file EOL's are already messed up (i.e. `MIXED`) or doesn't contain any EOL?

The idea is basically that you follow existing conventions, rather than blindly following orders. Much like you would strive to follow existing code style in a source file when modifying it.

Comments?

 cc @06needhamt

**Comment by 06needhamt** [comment]
@tamlin-mike I see where your coming from with this, but shouldn't all the files in a given project follow the `.editorconfig` rather than what's in the file? Because I could copy a file from a project with LF line endings to a project with CRLF endings and by following the rules of the file instead of the `.editorconfig`, the copied file would diverge from the rest of the project, which in my opinion is not the correct behaviour.

**Comment by tamlin-mike** [comment]
> shouldn't all the files in a given project follow the `.editorconfig`

@06needhamt Ehhh, kindasorta. You can have _different_ `.editorconfig` files in a single project. One `root`ed, with overrides in specific subdirectories where you might need to have e.g. specific charset for some files. Let's say 99.9% of the files use latin1, so you set that in the `root`  `.editorconfig`, but some files in some subdirs might need UTF-8 or even specific codepages (usually due to historical reasons), so you could add `.editorconfig` files with overrides in such directories.

Another option could be you have checked out some project from SVN as part of your project tree. Subversion and EOL sequences can be ... let's be polite and call it a "massive pain in the behind". :-)

A third scenario could be you inherit code developed by a wide variety of people over many years, and you are now tasked with cleaning it up. Adding an `.editorconfig` with LF could possibly be one of the first steps you did, but you might want to hold off on creating one (or worse, many) commit(s) with _massive_ diff's (if using an SCM where EOL matters).

I'm not touching the subject of sanity with such project setups, just pointing out that there are ... different ways to do project management. :-)

I understand and sympathise with your reasoning, but I believe following existing EOL convention (if it's consistent) for an existing file should take precedence over `.editorconfig` setting for this specific scenario. If not, you'd end up with a source file containing mixed EOL sequences, which I hope we can agree would be the less preferrable outcome.

If the file already contains mixed EOL sequences, closest applicable `.editorconfig` setting (in the scenario there are multiple) should be used.

**Comment by CyrusNajmabadi** [comment]
> The idea is basically that you follow existing conventions, rather than blindly following orders. Much like you would strive to follow existing code style in a source file when modifying it.

Tagging @sharwell for IDE design review of this idea.  It's big enough to need to be agreed on by the team before adpoting it for particular features.

**Comment by CyrusNajmabadi** [comment]
Note: my understanding is that there may be an effort somewhere for VS to expose an "when in rome" service that does this sort of detection.  But i don't know the status of it.
