### ISSUE TITLE
"Find All References"/"Go to implementation" blocks editing for a significant amount of time

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#41374]
1. Go to src\Compilers\Core\Portable\MetadataReader\TypeNameDecoder.cs in Roslyn solution
2. Right click,  "Go to implementation" on the "TypeNameDecoder" type name.

Observed:
VS is blocked by an "Please wait for an editor command to finish ..." dialog. The dialog sits there for a significant amount of time, blocking user from any work in VS. There is a "Cancel" button,  but clicking it (even multiple times) has no immediate effect.

Expected:
"Find All References"/"Go to implementation" should execute in the background, should not block editing and any other operations in VS, even for a second.

**Comment by sharwell** [comment]
> "Find All References"/"Go to implementation" should execute in the background, should not block editing and any other operations in VS, even for a second.

This is true for Find All References, but not for Go To Implementation. The latter is a synchronous navigation command. With that said, it should still be fast and respond to cancellation requests.

**Comment by AlekseyTs** [comment]
> This is true for Find All References, but not for Go To Implementation. The latter is a synchronous navigation command.

I am not sure why this would be the case. For me, as a user, the "Go to implementation" command is just a filtered version of "Find All References" command. IDE puts results into the separate window and it doesn't navigate anywhere, despite the "Go To" words in the name. I expect the command to be asynchronous.

**Comment by CyrusNajmabadi** [comment]
Without derailing things:

1. the IDE will only put 'go to' results in a separate window if there are multiple results.  Otherwise, it will just navigate to the item.
2. `go to` should be operating in a fashion that is effectively always free.  i.e. it's designed to not do anything that any layer considers expensive.  If that's not the case we def need to investigate.

Find-Refs def should not ever block, and if you're seeing any blocks we need to investigate.

Regardless, teh behavior you're describing is not acceptable. This sentence is on point:

> should not block editing and any other operations in VS, even for a second.

If we're seeing blocks, those need to be driven down and quashed.

**Comment by AlekseyTs** [comment]
At this point I am not sure if I've seen this issue with "Find All References", I just assumed both commands are flavors of the same thing. I definitely experienced the issue with "Go to implementation". I also experienced it on multiple occasions, again I do not remember if any of them were with "Find All References".
