### ISSUE TITLE
"Implement Interface Explicitly" adds implementation for member already implemented

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#41558]
In this code `C` fails to implement `I2.M2()`.  When I ask the IDE to "implement interface explicitly", it adds an implementation for `I2.M2()` and *also* an unnecessary implementation for `I2.M()` which is already implemented.  I only wanted the IDE to add an implementation for the method that was not already implemented.

``` csharp
interface I1
{
    void M();
}
interface I2 : I1
{
    void M();
    void M2();
}

class C : I2
{
    public void M() { }
    void I1.M() => M();
}
```

**Comment by CyrusNajmabadi** [comment]
>  I only wanted the IDE to add an implementation for the method that was not already implemented.

Note: this is explicitly (no pun intended) by design.  `implement explicitly` was asked by many customer to fully implement the interface explicitly.  Indeed, the behavior you're asking for was what we used to have and which people asked to not have.

the normal `implement` case will implement as much as it can implicitly, and the rest explicitly.

We don't have any feature *currently* to do what you ask `implement remaining members explicitly`.  It could def be something added though, but it should be with a new code-action for implement-interface instead of changing how the existing one works.

**Comment by YairHalberstadt** [comment]
I'll try and add a new feature to do this.
