### ISSUE TITLE
Update Dialog for Pull Members Up, Extract Interface, and Extract SuperClass

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#41576]
The dialog for Pull Members Up, Extract Interface, and Extract Superclass should be updated to look the same for all 3 options but have different titles and entry points. 

Draft of new dialog UI:
![image](https://user-images.githubusercontent.com/46729679/74257978-6f14b200-4caa-11ea-8a43-c84ef2d83f97.png)

Related to extract superclass work item: #40601

**Comment by ryzngard** [comment]
Some clarifying points to make for design: 

1. The UI should have defaults based on entry point. I.E: extract interface should have an interface selected by default. 

2. New file should be the default for all applicable things (new types).

3. Make abstract is the only entry point for pull members up today. We should consider make virtual in a later request, but keep it "Make abstract" for now for new and existing ancestor types. 

4. Extract to new class should only be applicable if no ancestor classes are present. Interfaces are okay. 

5. Name default for base class is "Base{ExistingName}"

6. Members should be disabled from change if not applicable to the base type. A meaningful warning should be available via hover over or screen reader tabbing. 

7. What should the title be?

**Comment by sharwell** [comment]
Also related to #40293

**Comment by jasonmalinowski** [comment]
The takeaways we had from our design meeting on this one:

1. We should try to make the UI more dynamic so things don't appear that don't apply. For example, pulling members into an existing type probably don't need the "pick a file" part of the UI.
2. We should try to expand symbol selection in solution explorer since that might give people a more direct way to mess with symbols than having to build more UI.
3. We might want to dig into telemetry to figure out what percent of time people are using dialogs versus invoking code fixes that don't need dialogs.
4. We probably still need to improve our selection logic more for code fixes.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of movement and costs here.  If this is critical, we should assign to a dev/milestone.
