### ISSUE TITLE
nameof does not offer instance members without closing parenthesis

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#41615]
**Version Used**: VisualStudio.16.Preview/16.5.0-pre.2.0+29721.120

**Steps to Reproduce**:

Automatic brace completion off.

```C#
class Program
{
    public string Property { get; }

    static void Main()
    {
        string s = nameof(Program.|
        Main();
    }
}
```

Note that this reproduces even when there are no errors in the class to be named:

```C#
class Test { public string Property { get; } }

class Program
{
    static void Main()
    {
        string s = nameof(Test.|
        Main();
    }
}
```

**Expected Behavior**: Autocompletion to offer `Property` property in the `nameof` context.

**Actual Behavior**: Only static members are shown. Works as expected with closing parenthesis present.

**Comment by CyrusNajmabadi** [comment]
This is likely because the following parses as:

```string s = nameof(Program.Main()```

So every check we have seems to indicate that this is not a usage of `nameof` but rather a call to something called `nameof` with a normal expression arg.

Note: by default we should spit out the `()` so this should be a rarer occurrence in general.

--

If we wanted to fix ths, we'd have to do some detection of this potential case.  It would likely have to take newlines into account here.  i.e. if the user literally had:

```nameof(Program.$$Main()``` then we likely should keep it only as static members.

**Comment by miloush** [comment]
> every check we have seems to indicate that this is not a usage of `nameof` but rather a call to something called `nameof` with a normal expression arg.

Why is the `nameof` colored as a keyword then? Wouldn't it make more sense when there are syntax errors to assume it's a `nameof` context than a call at this point?

> Note: by default we should spit out the () so this should be a rarer occurrence in general.

To be fair that was not the default before, so while it may by rare for new users, it is a reasonable to expect some of the more senior users to revert to the previous default (rather than it being a random setting you accidentally try out).

> `nameof(Program.$$Main()` then we likely should keep it only as static members.

Why?

**Comment by CyrusNajmabadi** [comment]
> Why is the nameof colored as a keyword then? 

Likely because it's moret aggressive here. 

> Wouldn't it make more sense when there are syntax errors to assume it's a nameof context than a call at this point?

Yes. That's what I'm suggesting we do.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
