### ISSUE TITLE
SyntaxGenerator.Merge is not merging abstract and partial correctly

### ISSUE THREAD

**Issue by Evangelink** [dotnet/roslyn#41654]
The `SyntaxGenerator.Merge` method returns `public abstract` when merging `public partial` and `public abstract`. IMO it should return `public partial abstract`.

_Originally posted by @Evangelink in https://github.com/dotnet/roslyn/pull/40448_

**Comment by Evangelink** [comment]
You are all pretty busy so I am happy to help with this resolving this issue but it seems that there is some discussion that needs to happen on your side.

**Comment by davidwengier** [comment]
Going to close this out. The test skipped because of this issue is fixed in https://github.com/dotnet/roslyn/pull/54905 and I had a look at the merge method and it looks like it does the right thing. I think this issue was created due to a misunderstanding of what `SyntaxGenerator.WithModifiers` does - it preserves accessibility, but overwrites modifiers. I admit this is confusing, but it would break too many things to change it now.

**Comment by Evangelink** [comment]
@davidwengier Sorry for the bump. You are talking about the behavior of `SyntaxGenerator.WithModifiers` but my issue is referring to `SyntaxGenerator.Merge`, is it a mistake on your comment or is the issue not meant to be fixed?

As you can see the code wasn't using the `Merge` at the end because of this, that's why I was doing a manual merge.

**Comment by davidwengier** [comment]
I certainly won't rule out that I'm completely misunderstanding, but I assumed this issue came out of [this comment](https://github.com/dotnet/roslyn/pull/40448/files#r359788105) as `WithModifiers` uses `Merge`, it just doesn't pass in the existing modifiers (see [here](https://github.com/dotnet/roslyn/blob/main/src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs#L1557-L1558) where `tmp` holds the existing modifiers but is thrown away).

> As you can see the code wasn't using the Merge at the end because of this, that's why I was doing a manual merge.

It's not clear to me which code you mean specifically. Can you link to a commit, or line of code?

I'm more than happy to reopen this if I'm mistaken, though there won't be any link to the issue in case any longer so we should definitely expand the detail here to include an example of the issue.

**Comment by Evangelink** [comment]
I may have written too fast. Honestly I don't remember the details and as you pointed out the issue is not of a good quality so it's probably safer to assume that the code is fixed and if not we will reopen a proper issue.

Sorry for the trouble :)
