### ISSUE TITLE
Setting .editorconfig trim_trailing_whitespace option to false is ignored

### ISSUE THREAD

**Issue by stopiccot** [dotnet/roslyn#41666]
I've configured trim_trailing_whitespace to false in my .editorconfig file but running dotnet-format still removes trailing whitespace characters.

dotnet-format version: 3.2.107702+3ecea99de4bb82b724bf11134279b5aaf8dd1f2f

**Comment by JoeRobich** [comment]
@sharwell Since the Formatter does support the indenting .editorconfig options it would be nice to support trim_trailing_whitespace as well.

**Comment by sharwell** [comment]
@JoeRobich The formatter removes all _insignificant_ trailing whitespace. This is a safe subset of what .editorconfig will do for `trim_trailing_whitespace` set to true.

trim_trailing_whitespace should never be set to true. Doing so can silently change the behavior of applications.

**Comment by JoeRobich** [comment]
I think the expectation was not to trim insignificant whitespace based on `trim_trailing_whitespace`.

**Comment by sharwell** [comment]
`trim_trailing_whitespace` has very different semantics. We _must not_ require this option be set in order to trim insignificant whitespace. Doing so would be a breaking change for C# applications.

**Comment by JoeRobich** [comment]
What if we default the option to 'true', but if it is set to 'false' we respect the users choice?

**Comment by JoeRobich** [comment]
Opened dotnet-format PR to update the documentation about `trim_trailing_whitespace` - https://github.com/dotnet/format/pull/544/files#diff-b326c72431c6ea02ccbc113464bafecdR11

**Comment by stopiccot** [comment]
Ok if `trim_trailing_whitespace` is not really supported is there any other option to ask formatter not to touch whitespace characters?

**Comment by sharwell** [comment]
@stopiccot Not currently. Fixing whitespace is the primary reason users run this tool. Normally the approach taken is running the tool once to fix the current issues, and submitting it as a single code change separate from any others. After that point all future corrections are small/manageable.

**Comment by jessetrinity** [comment]
Any updates on this? We probably want to do the same for TypeScript in VS. Same for `end_of_line`.

**Comment by ivan-prodanov** [comment]
@JoeRobich please give us an update. We shouldn't expect every code editor leveraging Roslyn to support virtual spaces. A simple boolean option opens the door to every editor out there. I'm specifically talking about VScode/monaco and my main concern is the Formatter removing whitespaces from empty lines (more info here: [issue 3585](https://github.com/OmniSharp/omnisharp-vscode/issues/3585)). 

We need to optionally disable this.

**Comment by CyrusNajmabadi** [comment]
As far as i can tell, the formatter is working as designed and as intended.  It's purpose is to fixup whitespace, and this sort of whitespace is absolutely a case of that.

>  I'm specifically talking about VScode/monaco 

i don't see why those editors can't workaround this.  Specifically, they can format, then ask what the indentation of that line should be.  If the indentation says that it should be into virtual space, tehn just reinsert the whitespace for that specific line.  This sounds like something that whatever plugin is formatting C# in VSCode should be doing, which would be out of scope for roslyn.

> We need to optionally disable this.

We are very hesitant to touch the formatter at all.  It carries high risk and is very difficult to get right due to the complex nature of it.  I'm uncertain if it would even be possible to add such an option and validate that it was working correctly for all cases.

**Comment by eatdrinksleepcode** [comment]
> Normally the approach taken is running the tool once to fix the current issues, and submitting it as a single code change separate from any others. After that point all future corrections are small/manageable.

Even automatically generated changesets need to be reviewed. Tools can make mistakes; changes which are supposed to be benign can have unintended consequences. The current all-or-nothing behavior of the formatter creates unacceptably large and difficult-to-review changesets when introduced to an existing unformatted codebase.

> As far as i can tell, the formatter is working as designed and as intended. It's purpose is to fixup whitespace, and this sort of whitespace is absolutely a case of that.

That several different types of changes can all be described as "whitespace" changes doesn't mean they are all of the same risk or complexity. There absolutely needs to be a way to perform specific kinds of formatting corrections without lumping them all together.

**Comment by CyrusNajmabadi** [comment]
> That several different types of changes can all be described as "whitespace" changes doesn't mean they are all of the same risk or complexity.

It's unclear why this case needs config. Can you give an example if where it's a problem?  Currently it seems to be a complaint about vscode, so I would recommend asking them for a solution here.

**Comment by eatdrinksleepcode** [comment]
@CyrusNajmabadi The original issue had nothing to do with VSCode, nor does mine. The problem is simply that the developer may want to apply some types of whitespace reformatting and not others, and the tool doesn't allow that. Virtually every other kind of change can be applied at a granular level, but not whitespace changes; and there is no obvious reason why that should be the case.

I am currently working around this problem using regex find/replace to make targeted fixes, which is error prone since it doesn't have semantic information. This really needs to be built in.

**Comment by CyrusNajmabadi** [comment]
> and there is no obvious reason why that should be the case.

Because we'd need some technical solution to make thsi possible, and that is non-trivial.  We're also not really in support of the idea of partial application of formatting, or making things very complex with knobs and whatnot.

It's still unclear where this is a problem, regardless of what host (vs/vscode) you might be in.  The general idea here is that this is just a formatter that formats based on its rules.  It's not a goal to provide extensibility and config for all possible needs of all customers.

**Comment by tilkinsc** [comment]
I dont see whats so hard about not touching already existing whitespace. If its there hands off.

**Comment by sharwell** [comment]
I believe this issue has already been answered. The current behavior is certainly By Design. The Roslyn formatter adjusts the whitespace of a document in order to format the text of the document.

**Comment by koen-lee** [comment]
Not to raise the dead here, but the formatter usually inserts newlines as well besides fixing whitespace (and in the context of trimming trailing whitespace, let's agree newlines are _not_ considered whitespace...)

Use case: an existing legacy repo with incidental trailing whitespace that requires some small fixes/PRs to be made.
As a contributor I don't want to start a discussion about a global cleanup with the repo owner when I just want a focused PR without friction.
Since perfect is the enemy of done, I want the formatter to help me be consistent in bracing style (= follow my settings), but keep trailing whitespace intact (= follow my settings).

And from the viewpoint of consistency and Principle of Least Surprise... I think the resolution by @sharwell was set in https://github.com/dotnet/roslyn/issues/41666#issuecomment-585957425 on a wrong understanding of the issue - the issue is about behavior on `false` not `true` or unset.
As I understand it, the current interpretation of `true` is _possibly break my code_ and of `false` it is _trim anyway, though the user explicitly doesn't want it_. You sure that's by design?

**Comment by CyrusNajmabadi** [comment]
@koen-lee we are not planning on doing that.
