### ISSUE TITLE
Warning Level 3 breaks Remove Unused Usings and Simplify Type Name

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#41784]
**Version Used**: 16.5 Preview 2

**Steps to Reproduce**:

Regression of #20377

**Comment by JoeRobich** [comment]
cc @AlekseyTs

**Comment by AlekseyTs** [comment]
It looks like the behavior was introduced by https://github.com/dotnet/roslyn/commit/db859fcc. The description doesn't mention hidden diagnostics at all, therefore, it is likely that the effect on the hidden diagnostics was not intentional. That diagnostics is already hidden from a user. I think hidden diagnostics should be unsuppressible (at least those produced by compiler), otherwise analyzers cannot work reliably. For example, we were planning to use Unused Using diagnostics in the analyzer that removes unused references, it should also remove unused usings.

CC @mavasani, @jaredpar, @agocke

**Comment by JoeRobich** [comment]
This is a related dev community ticket https://devdiv.visualstudio.com/DevDiv/_workitems/edit/990801
