### ISSUE TITLE
IntelliSense suggestion "IDE0030 Use coalesce expression" clashes with string interpolation when used with nullable types

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#41827]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/919168/intellisense-suggestion-ide0030-use-coalesce-expre.html)._

---
If I have an enum

```
	public enum VCSubjectType {
		User = 1,
	}
```

and a class has a nullable property of this type

```
public VCSubjectType? VersionSubjectType { get; set; }
```

and I use this with string interpolation

```
$"Unexpected version control subject type {VersionSubjectType}"
```

I get a compile error 

>CS0029	Cannot implicitly convert type 'ETR. DAL. Models.VCSubjectType?' to 'object'

I can fix this using a ternary to check for null

```
$"Unexpected version control subject type {(VersionSubjectType.HasValue ? VersionSubjectType.Value : "null")}"
```

but then I get IntelliSense suggestion

>IDE0030 Use coalesce expression

and if I accept the suggestion it changes the code to

```
$"Unexpected version control subject type {(VersionSubjectType ?? "null")}"
```

which has the compiler error

>CS0019	Operator '??' cannot be applied to operands of type 'VCSubjectType?' and 'string'

---
#### Visual Studio Feedback System on 2/16/2020, 02:54 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jinujoseph** [comment]
cc @CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
I don't see an issue here.  Note that the user code is in error.  i.e. this code is already *not* legal:

```
VersionSubjectType.HasValue ? VersionSubjectType.Value : "null"
```

The compiler gives the error:

```
Type of conditional expression cannot be determined because there is no implicit conversion between 'VCSubjectType' and 'string'	ConsoleApp1	C:\Users\cyrus\source\repos\ConsoleApp1\ConsoleApp1\Program.cs	12	Active
```

So the refactoring simply offers to simplify code that is already illegal to a simpler form that remains just as illegal :)

In general, we don't suppress our suggestions with code that is in error.  This is because code is constantly 'in error' and people still want to be able to manipulate it in expected ways *while on the way* to getting to a good state.
