### ISSUE TITLE
Go To Interface From Implementation By F12

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#41870]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/918638/go-to-interface-from-implementation-by-f12.html)._

---
Visual Studio has 2 very popular navigation features:
F12 - Go To Definition
Ctrl + F12 - Go To Implentation

If we are in interface and press Ctrl+F12 then we go to implementation.

But backwards navigation (F12) does not work! If we do not use code lens then there is no way to go to interface from its implementation. If we put cursor on method name and press F12 - nothing happens.

---
#### Visual Studio Feedback System on 2/16/2020, 05:37 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by tamlin-mike** [comment]
+1

This deficiency has been a source of frustration for as long as it has been missing. :-)

**Comment by CyrusNajmabadi** [comment]
@sharwell @jinujoseph Let's discuss this at next meeting.  I think it woudl be reasonable to update goto-def on an existing public class/struct method/prop/event to attempt to find and goto implemented interface methods.  Note: we could restrict this to only work for known declared implemented interfaces on the current type (or base types).  This would ensure the operation was always fast, as we wouldn't be looking for cases like the following:

```
class C
{
    public void $$Foo() { }   // goto def here
}

interface IFoo { void Foo(); }

class D : C, IFoo { }
```

If we ignore this one case, i think we can hit the 99% case for users with high perf.  THe other case is still possible throught eh slower, but globally searching, 'find all references'.

**Comment by tamlin-mike** [comment]
@CyrusNajmabadi Considering that edge-case example is really a mixin, that could in theory implement _any_ interface with a matching method signature, it would not only be impractical but could even be impossible to GoToInterface (assuming it's to match a single interface method), since the set of interfaces it implements could be infinite.

I don't think anyone would enjoy seeing a measurable slowdown in navigation for something like that.

I'd be willing to bet only considering parent interface(s) methods will cover not only 99%, but more likely 100% of use cases.

**Comment by kendrahavens** [comment]
Design meeting notes:
This feature is essentially Go To Base. We should remap F12 to trigger Go To Base when already on the member.

**Comment by tamlin-mike** [comment]
Design/implementation question: Would this remapping/redirection occur (hard-coded) within the existing `Edit.GoToDefintion` handler code, or would it add a separate named `Edit` action, introduce the concept of not only different editors having different keymappings but also different mappings within a single editor depending on context, and then have logic added to select (in this case `Edit`) handler depending on context (that it it has to query the editor for)?

Not considering the design and implementation efforts of such a redesign; more of a philosophical/semantical thought.

(Syntax-)context sensitive key mappings within a component (in this case Text Editor) could have merit, not only for this case but other actions (f.ex. editor selection widening, candidate selection of some refactorings). Feel free to bounce the idea to see if it could stick at the tail-end of some `StuffToInvestigate.txt`. :-)


Semantically `GoToDefintion` could mean either "Go to the code implementing (defining) this method" or "Go to the definition of this methods signature (the interface)", so that ambiguity for once works in favor of leaving everything as-is and simply do the redirect within the existing `Edit.GoToDefintion` handler.

**Comment by CyrusNajmabadi** [comment]
We would do this in our existing impl.  :)
