### ISSUE TITLE
XmlDoc On Default Constructor in C #

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#41880]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/920301/xmldoc-on-default-constructor-in-c.html)._

---
In C# we usually have xmldoc comments on classes. But if we do not specify constructor for class or do not annotate the constructor with it's own xmldoc then VS doesn't show the doc when we hover mouse over class constructor usage.

Example

```
/// <summary>
/// This is class A
/// </summary>
class A 
{

} 
```

When we use it like var a = new A(); then we don't see any documentation on mouse hover A.
It would be nice to see class xmldoc in this case.

---
#### Visual Studio Feedback System on 2/17/2020, 04:03 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by sharwell** [comment]
Design review conclusion: Add the _containing type_ as a fallback `inheritdoc` target for constructors. The rest of the proposal will work automatically from this.

**Comment by sharwell** [comment]
### Items that will need updating

Support constructors and update documentation:

https://github.com/dotnet/roslyn/blob/cf55f3a58e47298426fa971d3bd9d8857c746c65/src/Workspaces/Core/Portable/Shared/Extensions/ISymbolExtensions.cs#L279

Redirect from constructor to containing type:

https://github.com/dotnet/roslyn/blob/cf55f3a58e47298426fa971d3bd9d8857c746c65/src/Workspaces/Core/Portable/Shared/Extensions/ISymbolExtensions.cs#L460

**Comment by sharwell** [comment]
I'm tentatively marking this one as blocked. During my update, I encountered a concerning scenario which was not discussed in the design review, so we should discuss it before proceeding. 

Many default constructors are documented with this message:

> Initializes a new instance of the A class.

Types with these constructors would not be able to benefit from the added Quick Info. In addition, documentation rendering tools may have trouble separating the documentation for types and constructors. Therefore, I'm proposing we consider the following approach instead:

1. Instead of defaulting to `<inheritdoc/>`, we default to the standard constructor message quoted here
2. If the standard message is deemed insufficient, modify the _Quick Info_ subsystem to render the documentation for both the constructor and the containing type

**Comment by kendrahavens** [comment]
Design Meeting Notes

* We should show the default message  "Initializes a new instance of the A class," in addition to the inherited comments.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback and movement.
