### ISSUE TITLE
Do not show "Gathering Suggestions" during rename tracking

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#42050]
Ctrl+. in a rename session shouldn't run *all* code actions. It would be a lot faster if we just show "Rename" code action since a renaming is in progress and that's what most likely the user intends to do.

**Comment by jinujoseph** [comment]
@alrz not able to understand why would you want to do ctrl+. in rename session.
Do you mind providing full set of steps for repro pls.

**Comment by alrz** [comment]
Steps to reproduce:

1. Rename an identifier (renaming annotation shows up)
2. Press Ctrl+. (to select "Rename 'identitfier' to 'newIdentifier'")


![Untitled](https://user-images.githubusercontent.com/3105979/75989709-fa2f4380-5f08-11ea-9479-9e103c437acc.png)

At this point all code actions are computed and listed, this may take a while while I would only interested in the first code action "Rename".

When the renaming annotation is active it's wasteful to try to list all available code actions here.

**Comment by CyrusNajmabadi** [comment]
> When the renaming annotation is active it's wasteful to try to list all available code actions here.

There are a lot of cases for me when this is not true.  i.e. i may edit the identifier for a variable and then want to perform *other* refactorings on it.  

For me, far more often than not, i do *not* want to rename.

**Comment by alrz** [comment]
Hit Escape? All I'm saying is that this significantly degrades renaming experience, especially if you have a few analyzers installed, you should literally wait for the list to show up to select rename.

**Comment by CyrusNajmabadi** [comment]
I'm amenable to that.  This may also may fall out given some work I intend to do to split out how rename works wrt analyzing/fixing.  Assigning to myself to see what i can do here.

**Comment by jasonmalinowski** [comment]
So there were two thoughts from the design meeting today:

1. Normally we block on all code actions being computed because we don't want to show an updating list to the user. Our rename tracking quick fix is special in that it is always first, so if we had the ability to show just the rename first and fill in the rest of the list second in one go, that would work here. Unfortunately, we don't believe the editor APIs support that, so we'd have to build that.
2. It'd be nice if Ctrl+. and then an immediate enter key was special cased to just invoke the rename one, since somebody doing that clearly is expecting that item to be first and just wants to invoke it. There's no reason to compute the rest of a list they won't see.

**Comment by alrz** [comment]
I usually use Alt-Enter for quick actions, so it will be Alt+Enter, Enter. That would be awesome! thanks.
