### ISSUE TITLE
Create a single file watcher for a folder

### ISSUE THREAD

**Issue by Michael-Eng** [dotnet/roslyn#42095]
In our out of memory investigations for VS, we see that Roslyn ends up creating VS file watchers for each individual file. Instead it should create a single file watcher for each folder. 

The large number of file watchers is contributing significantly to the memory that's consumed when opening a large .NET Core solution, and impacts the overall ability to load large solutions.

**Comment by jinujoseph** [comment]
cc @jasonmalinowski not sure if there was another bug for it , could not find it.

**Comment by CyrusNajmabadi** [comment]
@Michael-Eng @jasonmalinowski I thought the platform was supposed to automatically do this for us.  That way the individual languages/services don't need to know about this sort of optimization, but instead all the batching is done at the platform level.

**Comment by jasonmalinowski** [comment]
So they do the consolidation, but we wanted to add an optimization to avoid consolidating thousands of source file paths if not necessary. The change is just here:

https://github.com/dotnet/roslyn/blob/4be125cab1f70b6af4ba7b476ee647eca975f3a3/src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioProject.cs#L130-L132

Uncomment the commented line, delete the other one, and run an RPS test. We just couldn't merge this because it exposed an unrelated bug so had to roll it back at the time.

**Comment by Michael-Eng** [comment]
I think the request in this bug is to do what's outlined on line 130
