### ISSUE TITLE
Proposal: Invariant arrays

### ISSUE THREAD

**Issue by Wazner** [dotnet/roslyn#4211]
In C# arrays are covariant, this means that they can be casted to an array of the element's base type. For example `string[]` can be casted to an `object[]`. This feature increases array write times by up to 30% in some cases as explained in [an article](http://codeblog.jonskeet.uk/2013/06/22/array-covariance-not-just-ugly-but-slow-too/) by Jon Skeet.

Yes, developers could make a wrapper struct themselves like Mr. Skeet did, but it would make array code very verbose and read unfriendly. I've seen multiple implementations of `Element` structures containing only a single field in the Roslyn codebase, just to circumvent array covariance.

My proposal is to introduce a syntactic sugar that removes covariance from arrays. Either internally in the CLR, or by using a structure wrapper in the background (something like `ArrayElement<T>`).

For example:

``` C#
invariant string[] array = new invariant string[5];

string myValue = array[5];
array[6] = myValue;
```

Would get translated to:

``` C#
ArrayElement<string>[] array = new ArrayElement<string>[5];

string myValue = array[5].Value;
array[6].Value = myValue;
```

Where `ArrayElement<T>` looks something like

``` C#
struct ArrayElement<T> {
    public T Value;
}
```

**Comment by jveselka** [comment]
It always felt like arrays should have been invariant from the beggining although I understand the reasoning behind covariance. I would welcome if this was implemented. That being said, lets point out few things why not to implement it:
* New keyword
* Existing workaround (altghough it is by no means well known and easily understod)
* Only relevant in performance critical scenarios
* It feels like the new default (because array covariance is rarely useful). So everyone who knows about it will use it everywhere (because the perf it brings), while beginners will be confused by it (why is it there when it behaves equaly)

**Comment by AqlaSolutions** [comment]
I vote for this! Array covariance is used very rarely and is a source of possible errors. Please let me turn it off. 

30% write speed improvement is a lot for arrays. I understand that it's too late to make them invariant by default but at least let developers decide...

**Comment by ilmax** [comment]
+1 on this

**Comment by HaloFour** [comment]
Wouldn't an array of a struct wrapper still be a covariant array?

Seems that short of CLR support you can't really implement this feature in any meaningful way.  And even then with CLR support you effectively have to define another array type that would be incompatible with those that already exist.  The developer wouldn't be capable of passing an `invariant string[]` to any methods that accept `string[]` because those methods could cast to `object[]` and the array would lack the internal type checking.

**Comment by Wazner** [comment]
@HaloFour 
No, structs are not covariant. 
An example demonstrating this:
```C#
int[] array1 = new int[1];
object[] array1obj = array1; // Compilation error CS0029

string[] array2 = new string[1];
object[] array2obj = array2; // No compilation error, works fine.
```

**Comment by HaloFour** [comment]
@Wazner 

Oh ok.  I did not know that.  I can't honestly say I've ever made use of array covariance, at least not intentionally.  It's funny, a mistake copied from Java where it is also largely regarded as a mistake.

So that leaves the issue that even without CLR support your creating a new incompatible array "type", specifically because `invariant string[]` cannot be passed to any existing methods that accepts `string[]`.  Implemented as a keyword that seems like it would be confusing.  That may be just a minor issue if this is intended only for new performance-sensitive development.

**Comment by Wazner** [comment]
@HaloFour 

Yes, the two types would be incompatible.

Another possible solution when CLR support is possible, is to keep the Array type but add a IsInvariant property to it. And when the array is casted to a derived type when IsInvariant is `true` an `ArrayIsInvariantException` is thrown. This would keep an invariant array compatible with existing methods (as long as it isn't casted).

**Comment by gafter** [comment]
We are now taking language feature discussion on https://github.com/dotnet/csharplang for C# specific issues, https://github.com/dotnet/vblang for VB-specific features, and https://github.com/dotnet/csharplang for features that affect both languages.
