### ISSUE TITLE
Move DesignerAttributeIncrementalAnalyzer OOP

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#42186]
1) Enable this analyzer in RemoteWorkspace (attribute on the provider).

Replace `WorkspaceKind.Host` with `WorkspaceKind.RemoteWrkspace`:

```C#
 [ExportIncrementalAnalyzerProvider(Name, new[] { WorkspaceKind.Host }), Shared]
```

2) Split the code into analyzer part (remote) and notification part (in devenv). 
3) Serialize the analysis results in OOP and send them over to devenv. 
4) Forward the notification to the project system.

The analyzer and PS notification need to be independent (producer/consumer queue), so that ServiceHub doesn't block on UI thread as the project system API requires UI thread.

**Comment by tmat** [comment]
@CyrusNajmabadi Something you could pick up.

**Comment by CyrusNajmabadi** [comment]
Will do.

**Comment by CyrusNajmabadi** [comment]
Ok.  So here's the plan as i understand it.  It follows a similar model to how unit testing works OOP.

1. We have the normal VSWorkspace.  After it loads, and some delayed point in the future, we start up a local service that will act as the 'sink' for designer-notifications.
2. This local service will call over to OOP telling it to start analyzing the solutoin for designer attributes.  It will pass over itself as the 'callback' for OOP to pass back information with.
3. On the OOP side we have an IncrementalAnalyzerProvider/IncrementalAnalyzer.  Importantly, these are *not* MEF exported.  We don't want them getting loaded up and running automatically.
4. Instead, when VS calls over to the OOP side we will use that time for our Analyzer/Provider to call into the ISolutionCrawlerRegistrationService and now register ourselves as an analyzer to run.  
5. The oop runner will always tell the SolutionCrawler it needs to reanalyze the entire workspace for this analyzer.  We need this so that we actually process everything and nothing is missed.
6. at this point OOP will start analyzing the solution and determining new info about designable files.  It will call back into the callback (VS) with that info.
7.  On the VS side we will buffer these notifications and eventually notify the designer-subsystem with this info at regular intervals (so as not to overload hte UI thread).

**Comment by tmat** [comment]
Sounds a bit more complicated than I'd expect. 
It's not clear to me why we need the extra handshake. Couldn't the local service be created and ready to receive data immediately as Roslyn loads (via MEF composition)?
The OOP incremental analyzers can't run before the solution is loaded in the ServiceHub process. . A that point we know the VS side is ready to receive data.

**Comment by CyrusNajmabadi** [comment]
@tmat I agree with your assessment, however i'm still hesitant.  I've lost track of the number of times we've presumed an *implicit* ordering dependency between components.  It's led to a massive number of bugs over the years.  Because of this, i've strongly moved to a model where there are no implicit orderings and all handshakes must be explicit to ensure things always work.

Note: this really ends up mattering as the core parts of our system get refactored.  i.e. as we change packages/workspaces/oop models, it's  *really* easy for this stuff to change and have things break without it being noticed.  The explicit handshake approach ensures that simply doesn't happen.

**Comment by CyrusNajmabadi** [comment]
Note: in terms of complexity, it's not actually that complex from a code perspective.  Just a small number of lines to have the VS side kick the OOP side to actually start working.  So i think it's well worth it for the future safety this buys us.

**Comment by CyrusNajmabadi** [comment]
Note: we have a slight correctness concern if we go with:

> The analyzer and PS notification need to be independent (producer/consumer queue), so that ServiceHub doesn't block on UI thread as the project system API requires UI thread.

Specifically, the OOP side needs to be able to know what the VS side has received *and persisted* through the project-system APIs.  i.e. the OOP side would like to be able to quickly say "the designer attribute didn't change between the last time i notified VS about it and this time, so i can skip notifying VS".  However, this is only valid if it really knows that the project system truly did receive and persist the last notification.

There are a few things we can do here:

1. we can have oop *presume* that any notifications are received by the project system.  This requires the least coupling, but opens ourselves up to narrow races where OOP and VS can get out of sync over time.
2. we can have OOP notify VS, and VS doesn't return to OOP until the information was successfully sent to the project system.  However, this means (even though we're async) the OOP side is waiting on the VS side.
3. we can have the OOP side notify VS and have that return immediately.  We can then have VS notify the project system on its own.  Once this happens, VS can call back into OOP to state which values were persisted.  OOP can then use that in the future when making determinations about which values it needs to send back.

To be honest, i'm really mostly leaning toward '1'.  Yes, it opens a small window for things to be incorrect**.  However, a simple edit in the file will clear it up.  It's extremely simple and means no coupling between all the messages going back and forth.

--

** The window is effectively: OOP is reanalyzing.  It computes new data for some doc.  It then persists this new data and sends message over to VS notifying it of the new value (or vice versa).  Before VS actually tells the project system though, it closes (or crashes).  So OOP has persisted information about what VS knows that isn't actually true.  

This seems narrow enough, and easy enough to work around (just edit the file) that i don't think it's a big deal IMO.  

Thoughts @tmat ?  If you want something more like '3', we can def do it, just at higher complexity and cost around ensuring correctness.

**Comment by tmat** [comment]
I'd definitely go with [1]. Keep in mind that we are dealing with legacy system here. Ideally, we would provide a service and the Project System, or rather WinForms/XAML designer would ask it for information about the designer attributes (Project System polling). We should follow up on that and find out what this information is actually used for, which component needs it and change that. But for now we just need to move the analysis OOP.

I don't think it's necessary to persist in OOP whether Project System has been notified about a particular type or not. I'd assume that if we send the message over to in-proc it will be delivered to the Project System.

We can persist the set of attributes in the given snapshot, so that we don't need to recalculate everything when the same solution is loaded.

**Comment by CyrusNajmabadi** [comment]
Yup.  I'm going to go with '1' for now.  I'll just doc the limitation in the impl of this choice.  Working on this now.

**Comment by tmat** [comment]
@CyrusNajmabadi 
> @tmat I agree with your assessment, however i'm still hesitant. I've lost track of the number of times we've presumed an implicit ordering dependency between components. It's led to a massive number of bugs over the years. Because of this, i've strongly moved to a model where there are no implicit orderings and all handshakes must be explicit to ensure things always work.

I understand that. However, we should also not over-engineer everything to account for many different potential future changes that might never happen. If we make an assumption I'd think about what kinds of changes might break it and how likely it is that these changes occur in code that's unrelated to the component that makes the assumption. 
Let's say we initialize the service and document the assumption that the service is expected to receive messages before solution is loaded and analyzers are started on it.
What can break that? Moving the initialization to later point would. But that is a change local to the code that makes the assumption and presumably one would not do it when they read the comment. Moving solution load before RoslynPackage load is impossible. Anything else?

**Comment by CyrusNajmabadi** [comment]
So... i'm really really really feeling oogy about that.  With how our components load, and with how much 'delay loading' and 'async bg loading' and whatnot, i feel really wary about having that actually work out.  It's really 1-2 lines to just have the dependency order clear in code.  That feels like something we should not  be trying to get around :-/

**Comment by tmat** [comment]
I don't feel strongly about this one. Just a bit worried about treating some analyzers differently than others in the solution crawler.
