### ISSUE TITLE
Warn when using uninitialised field in constructor

### ISSUE THREAD

**Issue by YairHalberstadt** [dotnet/roslyn#42217]
**Version Used**: master as of 5th march 2020

**Steps to Reproduce**:

Compile the following

```csharp
using System;

#nullable enable
public class C {
    string _s;
    public C(string s)
    {
        Console.WriteLine(_s.ToString());
        _s = s;
    }
}
```

**Expected Behavior**: Warning: possible null dereference `_s.ToString()`

**Actual Behavior**: No warning and NRE at runtime

The compiler does not track the null state of fields in the constructor. I think that if the constructor does not call another constructor, all fields should start off with a maybe null state.

**Comment by jcouv** [comment]
This was fixed by @RikkiGibson. We now enter the body of constructors assuming that fields are maybe-null. Verified that we produce a warning on [sharplab](https://sharplab.io/#v2:CYLg1APgAgTAjAWAFDIMQDsCuAbbBDAI2wFMACY9Qk5KAZlNlIGFSBvZUzhuABlIH0AzgG4OXOswAUUXqUEBKMZ3ZIua7gE5JQgHQAVAPYBlAC4AnAJboA5pPnzhpAPRPSAdzxn0V68yMAOADYeGBBSABFiM2IAMyiKAGMyAxjSPFIABwNBQQsiAE9SLFxSaLjo9CSdJXUhUgBeOVFVLgBfZFagA).
I'll go ahead and close this issue as fixed. Thanks
