### ISSUE TITLE
Roslyn OOP repeatedly crashing

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#42365]
I don't have a specific repro, but it often seems to be Find References doing this:

```
Application: ServiceHub.RoslynCodeAnalysisService32.exe
Framework Version: v4.0.30319
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: System.InvalidOperationException: SqlConnection was not properly closed
Stack:
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.CodeAnalysis.FailFast.OnFatalException(System.Exception)
   at Microsoft.CodeAnalysis.ErrorReporting.WatsonReporter.ReportFatal(System.Exception)
   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception, System.Action`1<System.Exception>)
   at Microsoft.CodeAnalysis.SQLite.Interop.SqlConnection.Finalize()
```

**Comment by CyrusNajmabadi** [comment]
Watson buckets: https://watsonportal.microsoft.com/BucketDetails?BucketIdentifier=b7d22fce-5dc3-2322-ba37-274f899cf487

**Comment by mavasani** [comment]
@jasonmalinowski @CyrusNajmabadi - do we know the root cause for this? I am hitting this extremely often on latest dogfood builds on doing a FAR query and it renders VS unusable.

**Comment by sharwell** [comment]
@mavasani Can you attach the heap dump from **ServiceHub.RoslynCodeAnalysisService32.exe** to a feedback ticket? A performance trace that captures the situation would be slightly better.

My guess is the is running out of memory and throwing an OOM exception (because you haven't manually configured it to use a 64-bit process), and the exception is thrown on a path that leads to `SqlException` not getting disposed on the exceptional path.

**Comment by sharwell** [comment]
Duplicate of #22302
