### ISSUE TITLE
Roslyn fails to process conditional flow annotations if there's explicit true / false comparison

### ISSUE THREAD

**Issue by TessenR** [dotnet/roslyn#42398]
**Version Used**: 
```
Branch master (10 Mar 2020)
Latest commit 441c154 by msftbot[bot]:
Merge pull request #42303 from CyrusNajmabadi/useCompoundParens

Support parenthesized expressions in use-compound-operator.
```

**Steps to Reproduce**:

Compile the following code
```cs
#nullable enable
using System.Diagnostics.CodeAnalysis;

class C
{
  void M(C c)
  {
    string? s = null;
    if (c?.GetS(out s) == true)
    {
      s.ToString(); // false CS8602
    }
  }

  extern bool GetS([NotNullWhen(true)] out string? y);
}
```

**Expected Behavior**:
No warnings, the condition explicitly checks that `GetS(out s)` returned true

**Actual Behavior**:
CS8602 reported for `s.ToString()`

**Notes**
Note that this behavior does not require conditional access in the if statement's condition, i.e. the warning is still present even if the condition is `if (c.GetS(out s) == true)`, however conditional access makes it impossible to omit explicit true / false comparison and thus renders flow annotations completely useless.

**Comment by jcouv** [comment]
For the scenario with `?.`, that is a known issue: https://github.com/dotnet/roslyn/issues/41107
I'll go ahead and resolve as duplicate.

>  the warning is still present even if the condition is if (c.GetS(out s) == true),

I don't see that behavior (was fixed by PR https://github.com/dotnet/roslyn/pull/41349)
([sharplab](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQBMQGoA+BiAdgVwBtCJhC4ACOXU8gWACgABABgqYEYA6AEQEsIAc1wB7WHwDGULgGERKOAEEahAJ5Q+UANyNGTAEwUZjAN6MK7ACwUAsgAoZFCQEpzFMwwsXOLAPwUoCgBeCgJiHU8vPgAzCjsJLgBxOBgAZTsRfBgA52CQmAR8OFdIiw8vL2kAFRFUgr5cQTtnLQoAejaKaIhCKEoZVIAOADYWfTcLAF83aYY3YBERQgpktLsAbQA5ERhNokIAdQALajsCoucAXQpM7J9/VVyggD4KGCOEEQB3UP2AQgikyAA=))

**Comment by jcouv** [comment]
From discussion with @RikkiGibson we think that being able to fully analyze such scenario would require more expensive tracking of state. 
Currently, we return from analyzing `c?.GetS(out s)` with an unconditional state. When we realize the comparison is `== true`, we go back and find a few slots that can be marked as not-null (`c` in this scenario).
To analyze this scenario better without re-analyzing the expression, we'd have to devise a more complex conditional state of some sort (WhenTrue+WhenFalse+WhenNull triplet maybe?). It's something that we've brainstormed a few times, but we suspect would be very expensive to design and possibly to implement/test as well... :-/

**Comment by jaredpar** [comment]
Had a side discussion. Going to re-evaluate once @RikkiGibson finishes the definite assignment work for C# 10.

**Comment by RikkiGibson** [comment]
Fixed by the "improved definite assignment" feature. #51463
