### ISSUE TITLE
Visual Studio 2017 (Roslyn 2.X) produce warning for analyzer assembly that targets roslyn 3.X

### ISSUE THREAD

**Issue by cezarypiatek** [dotnet/roslyn#42538]
**Version**:
Visual Studio 2017 (15.9.21)

**Steps to Reproduce**:

1. Create or open existing project with Visual Studio 2017
2. Install nuget packge with analyzer that uses Roslyn 3.X, for example https://www.nuget.org/packages/SmartAnalyzers.CSharpExtensions.Annotations/

**Expected Behavior**:
Assembly that references Roslyn 3.X should be ignored in Visual Studio 2017.

**Actual Behavior**:
![image](https://user-images.githubusercontent.com/7759991/76979594-70d03600-6938-11ea-9c01-1401e47ca41b.png)

**Comment by sharwell** [comment]
@mavasani An analyzer package needs to be able to include two or more assemblies, where at one of the assemblies works with the current compiler version and one of them targets a more recent compiler. In this scenario, the analyzer targeting a more recent compiler is intended to "light up" in that environment, but today it's not possible to use it because the fallback behavior produces a warning in the driver.

**Comment by mavasani** [comment]
Closing out old issue - we are unlikely to add this feature.
