### ISSUE TITLE
Nullability attribute warnings reported for oblivious types

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#42552]
**Version Used**: 3.6.0-1.20127.6 (572b1f0e)

**Steps to Reproduce**:

1. Target **netstandard2.0**
1. Implement `IDictionary<TKey, TValue>.TryGetValue` in nullable-aware code
1. Add `[MaybeNullWhen(false)]` to `out TValue value`

**Expected Behavior**:

No warnings. `IDictionary<TKey, TValue>` in **netstandard2.0** is an oblivious type.

**Actual Behavior**:

> CS8767: Nullability of reference types in type of parameter 'value' of 'bool DictionaryAnalysisData<TKey, TValue>.TryGetValue(TKey key, out TValue value)' doesn't match implicitly implemented member 'bool IDictionary<TKey, TValue>.TryGetValue(TKey key, out TValue value)' because of nullability attributes.

[jcouv:] when this issue is fixed, the `roslyn-analyzer` repo should be updated (currently suppressed such an issue, in https://github.com/dotnet/roslyn-analyzers/pull/3400/files)

**Comment by jcouv** [comment]
This is a result of the type substitution design. If you have an oblivious API, but substitute an null-aware type, you get a null-aware type.

The API that is being implemented in this example is `bool IDictionary<TKey2, TValue2>.TryGetValue(TKey2! key, out TValue2! value)` because those type parameters come from your type `DictionaryAnalysisData<TKey2, TValue2>` which is fully annotated. (I renamed the type parameters and added `!` for clarity)

I do not remember the reason for this substitution behavior. The alternative would be that substituting `TValue2!` into `TValue~` would produce an oblivious (instead of a `!`). 
@AlekseyTs @gafter may remember the reason for this design.

**Comment by AlekseyTs** [comment]
That is how type substitution is supposed to work. You substitute with a type that has annotations, you get them in result.

**Comment by sharwell** [comment]
@AlekseyTs This is not a call site, but rather an OHI site. If the original definition was not annotated, it doesn't make sense assume that the annotations it contains are correct.

**Comment by AlekseyTs** [comment]
> This is not a call site, but rather an OHI site. If the original definition was not annotated, it doesn't make sense assume that the annotations it contains are correct.

Call-site or use-site, makes no difference for this discussion. Annotations come from substitution, we can and should trust annotations given for generic type arguments. That is one of the fundamental principles of the feature - annotations flow through generic substitution. Sometimes that requires annotations to be combined at specific "locations". For example, when ```T``` is substituted with ```string!```, ```T?``` becomes ```string?```. However, when ```T``` in the signature isn't annotated (i.e. oblivious), effectively there is nothing to combine with and ```T~``` becomes ```string!```.

**Comment by AlekseyTs** [comment]
Perhaps the fact that the lack of a ```?``` in nullable enabled context is actually considered as a "not nullable" annotation is confusing you. But this is what it means, even though syntactically there is no token to indicate that.

**Comment by sharwell** [comment]
It looks like this is just fallout from the change to treat `[MaybeNull]` the same way that `?` is treated. I would consider this a candidate for a diagnostic suppressor since it's an API-specific problem and not a language-specific one.
