### ISSUE TITLE
LiveShare tests are crashing and causing build flakiness

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#42587]
Failing builds: 
- https://dev.azure.com/dnceng/public/_build/results/buildId=564945&view=artifacts&type=publishedArtifacts
- https://dev.azure.com/dnceng/public/_build/results?buildId=563985&view=artifacts&type=publishedArtifacts

The crash appears to occur on xunit shutdown. The actual log file for the tests indicates that everything succeeded. But xunit is exiting with a failure code and no output.

**Comment by dibarbet** [comment]
Interesting, going off of the test run logs, all of the liveshare tests are "Finished".  So it must be crashing after the test completes?

**Comment by sharwell** [comment]
FatalExecutionEngineError. We need a heap dump to investigate. Could be an exception getting thrown within a `when` handler.

**Comment by dibarbet** [comment]
pretty much all of the liveshare tests have been removed (due to migration off liveshare APIs)
Last remaining one is https://github.com/dotnet/roslyn/blob/master/src/VisualStudio/LiveShare/Test/ProjectsHandlerTests.cs which as far as I can tell from the almost-unusable ADO dashboard history hasn't failed in at least the past 100 runs.  Resolving this issue.
