### ISSUE TITLE
The refactoring 'Use explicit type' should conserve the ref-ness of the variable.

### ISSUE THREAD

**Issue by HobbsCode** [dotnet/roslyn#42880]
**Version Used**: 
netcoreapp3.1 
VS 16.5.1

**Steps to Reproduce**:

```
static void Main()
{
     string str = "hello";

     ref var rStr1 = ref str; // Codefix wants to replace 'ref var' with 'string'

     ref readonly var rStr2 = ref str; // Codefix wants to replace 'ref readonly var' with 'string'

     Console.WriteLine($"{rStr1} {rStr2}");
}
```

**Expected Behavior**:
The codefix should conserve the ref-ness of the variable.
In this case, 'ref var' should be replaced with 'ref string'.

**Actual Behavior**:
The codefix discards the ref-ness of the variable, producing unexpected and invalid code.

**Comment by YairHalberstadt** [comment]
I cannot reproduce. I get:

```csharp
    static void Main()
    {
        string str = "hello";

        ref string rStr1 = ref str; // Codefix wants to replace 'ref var' with 'string'

        ref readonly string rStr2 = ref str; // Codefix wants to replace 'ref readonly var' with 'string'

        Console.WriteLine($"{rStr1} {rStr2}");
    }
```

**Comment by YairHalberstadt** [comment]
Perhaps you could record a gif of what you're doing?

**Comment by HobbsCode** [comment]
![UseExplicitType](https://user-images.githubusercontent.com/22330191/77917975-3f753580-7269-11ea-9636-0cc45d0a8908.gif)

**Comment by YairHalberstadt** [comment]
Thanks for the gif
I think that's the refactoring rather than the code fix.
If your settings are "prefer explicit type" and you select `var` and press ctrl . and select the "use explicit type" code fix then it works as expected.

I'm guessing a little bit of work could be done to combine the common parts of the refactoring and the code fix.

Also I'm not sure why the code fix triggers on `var` and the refactoring on `str`

**Comment by HobbsCode** [comment]
I get the expected behavior if I remove my .editorconfig.
