### ISSUE TITLE
How to change node location for diagnostic messages (not only line)?

### ISSUE THREAD

**Issue by nikitaodnorob** [dotnet/roslyn#42956]
Hello!

I want to create simple programming language for my diploma and compile it via Roslyn. I made translating code in my language to `CSharpSyntaxTree` object and now I can compile this syntax tree using Roslyn. But I have a problem with diagnostic messages because tokens' positions in program in my language don't match with positions in CSharpSyntaxTree. For example, program in my language
```
print a;
```
matches with this C# program (it was gotten by `SyntaxTree.ToString()` method)
```
usingSystem;namespaceApp{publicclassProgram{staticvoidMain(){Console.WriteLine(a);}}}
```
For example, in my code the `a` identifier has position `(1;7)` (or just **7**) but in showed C# code a position of identifier's node is **80**.

I want that source positions in my language will be contained in `Diagnostic` objects after compilation.

I read that Roslyn keep offset of nodes instead of position `(row;column)` and I shouldn't change it manually because it depends from values of other nodes. So, I added `LexLocation` property to `SyntaxNode` class, the structure which contains `lineStart`, `lineEnd`, `colStart`, `colEnd`. But I couldn't change diagnostic's logic for showing my `LexLocation` in diagnostic's messages. 

Can you get me advice, how to do this?

**Comment by CyrusNajmabadi** [comment]
Hi Nikita,

In general, questions like this should be taken to gitter.im/dotnet/roslyn, or discord.gg/csharp (#roslyn channel).

I'm going to close this out.  however, as a general idea, the way you'd want to do this is to keep track of the original location that your generated code spans map to.  Since you're hte one generating the new code, it should be easy for you to keep an auxiliary structure to store that mapping info.

Then, when you get diagnostics, you can translate those positoins backward from teh the roslyn tree location to your own original location.
