### ISSUE TITLE
Consider exposing public ProjectId.DebugName

### ISSUE THREAD

**Issue by JoshVarty** [dotnet/roslyn#4296]
So I'm in a weird situation here that would be made easier by either:

 - Exposing a public `ProjectId.DebugName` (Maybe rename to `ProjectId.Path`?)
 - Making `ProjectId.Id` deterministic for `.csproj` projects.

Here's a summary of what I'm doing:

I'm building a workspace that emulates the `VisualStudioWorkspace` but in Visual Studio 2013. (I know it's definitely not a supported scenario). I've created a workspace called `TrackingWorkspace` that tracks the current state of a C# solution using EnvDte events and the `MSBuildWorkspace`.

When the solution loads for the first time, I create a temporary `MSBuildWorkspace`, load the solution and then use [`Workspace.SetCurrentSolution()`](http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Workspace/Workspace.cs,9f508d251920fb0d) to load the solution into my `TrackingWorkspace`.

I listen to [`EnvDte.SolutionEvents`](https://msdn.microsoft.com/en-us/library/envdte.solutionevents.aspx) to add and remove projects and documents. Right now I'm having an issue handling the addition of projects with existing `ProjectReferences`.

When a project is added, I use the following:

```CSharp
using (var msBuildWs = MSBuildWorkspace.Create(msBuildProperties))
{
	var msBuildProject = msBuildWs.OpenProjectAsync(projectPath).Result;
	var projInfo = ProjectInfo.Create(msBuildProject.Id, msBuildProject.Version, msBuildProject.Name, msBuildProject.AssemblyName, msBuildProject.Language, msBuildProject.FilePath,
		compilationOptions: msBuildProject.CompilationOptions,
		projectReferences: msBuildProject.ProjectReferences, //<- This is a problem
		metadataReferences: msBuildProject.MetadataReferences);
		
	base.OnProjectAdded(projInfo);
	
	//And then I add the documents
	//...
}
```

The problem I'm having here is that the project references are not correctly applied to the project that is added to my `TrackingWorkspace`. The compilation options, metadata references and other properties work fine.

I've glanced through the source and I believe this is likely because the `ProjectId` for the `msBuildProject.ProjectReferences` are random Guids. So it can't correctly resolve the project references to a project in my project.

That's understandable and I don't mind building the references myself. The issue here is that [`ProjectReference`](http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Workspace/Solution/ProjectReference.cs,944b5173649705e4) type and the [`ProjectId`](http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Workspace/Solution/ProjectId.cs,d57a45799bc4a52e) type don't give me a lot to go on. The only public info they really expose is the random Guid in `ProjectId.Id`. 

However, I notice that there's a private `_debugName` field that contains the project path and (I think, but correct me if I'm wrong) I can use that path to build the project reference manually. Unfortunately right now I'll have to parse that path out of a string like:

```
(ProjectId, #904f7f02-8332-4e64-93a6-2de9d93f29f4 - C:\Users\Josh\Documents\GitHub\Orange\test\TestSolution\TestSolution.Legacy\TestSolution.Legacy.csproj)
```

So I have a couple questions:

1. Do you think I'll have problems with using the path to build the references? Are there project types (excluding DNX/project.json) that have multiple projects with the same path?
2. Would it make sense to expose `_debugName` on `ProjectId` somehow?
3. Would it make sense to create `ProjectId.Id` using the `<ProjectGuid>` property for `.csproj` files? I see there's a [`ProjectId.CreateFromSerialized()`](http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Workspace/Solution/ProjectId.cs,d57a45799bc4a52e) that might allow for this.

**Comment by jasonmalinowski** [comment]
> 3. Would it make sense to create `ProjectId.Id` using the `<ProjectGuid>` property for `.csproj` files? I see there's a [`ProjectId.CreateFromSerialized()`](http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Workspace/Solution/ProjectId.cs,d57a45799bc4a52e) that might allow for this.

We can't do this safely. ProjectGuid is a great idea in theory until you see how people break it. People regularly copy/paste project contents creating duplicate ProjectGuids in source files, and sometimes simply delete the ProjectGuid. I believe this is why we ultimately didn't populate the ProjectId.Id property from the project file, because it's too unreliable in practice.

> 2. Would it make sense to expose `_debugName` on `ProjectId` somehow?

I would argue no: the point of the debug name is to simply be the name shown in the debugger. It is not contractually guaranteed to be anything useful, or even anything not useful. The fact the name is a file path from MSBuildWorkspace is currently happenstance; we could change that at any time.

> 1. [...] Are there project types (excluding DNX/project.json) that have multiple projects with the same path?

Not that you'll get from `MSBuildWorkspace`. Weird things can happen with web projects inside Visual Studio but I don't think that's a problem here.

Let me suggest something else if you haven't tried it already: when you load a project with MSBuildWorkspace, rather than using the ProjectReferences list *directly*, use the ProjectIds to fetch the Projects themselves (Solution.GetProject), and then just look at the FilePath property from there. This should let you work just fine on our public API today. It also happens that it means we don't have to add APIs I don't like, so that's a plus.

**Comment by jasonmalinowski** [comment]
And an unrelated thought:

> I'm building a workspace that emulates the `VisualStudioWorkspace` but in Visual Studio 2013

So creating your own workspaces inside Visual Studio is totally supported, and since the core Workspaces layer and lower doesn't depend on Visual Studio 2015, there's nothing really unsupported. I suspect you're maintaining a custom build of MSBuildWorkspace but that's your own problem.

If there's something that is "unsupported" at least it's using DTE to populate Workspaces in the first place. The DTE APIs do not provide sufficient information needed to get compiler information, so you're going to have effectively unfixable bugs if you try this. Some third-party plugins that were watching DTE to get file information in 2013 prior to Roslyn actually moved to using Roslyn in 2015 just because we can provide better information there through the Workspaces API. You'll definitely be able to get close, but it won't be perfect.

I suspect you're already aware of this, just wanted to highlight it for anybody else watching this conversation.

**Comment by JoshVarty** [comment]
>Let me suggest something else if you haven't tried it already: when you load a project with MSBuildWorkspace, rather than using the ProjectReferences list directly, use the ProjectIds to fetch the Projects themselves (Solution.GetProject), and then just look at the FilePath property from there.

That makes a lot more sense than what I had originally planned on doing. I'll go with this approach, thanks for the help. :)
