### ISSUE TITLE
Recognize references for `nint` and `nuint`

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#42988]
- FindAllReferences/GoToDefinition treats nint and IntPtr as a single type. I assume that's okay (similar behavior for tuples).
![image](https://user-images.githubusercontent.com/12466233/78170128-58b3e880-7407-11ea-8874-2a7fda8318b4.png)
- We're currently not highlighting correctly when placing cursor on `nint` (should highlight other `nint` syntax, but only highlights `IntPtr` syntax).
- QuickInfo on type shows xml doc from underlying type, which seems incorrect, although minor.

Relates to https://github.com/dotnet/roslyn/issues/38821

**Comment by jcouv** [comment]
@jasonmalinowski @cston What do you think of this design question:
If you place your cursor on `nint`, I expect other instances of `nint` should be highlighted. But should that also highlight `IntPtr` or not?

**Comment by cston** [comment]
> But should that also highlight IntPtr or not?

I wouldn't expect `IntPtr` to be highlighted when selecting `nint`.

**Comment by CyrusNajmabadi** [comment]
I agree with chuck.  i would not expect them to be highlighted.  That said, i don't mind if they're highlighted.  i.e. if it's expensive to make this work, punt.  if it's cheap, do it.  :)

**Comment by jasonmalinowski** [comment]
I wouldn't expect them to be highlighted either. I would investigate this bug not because the scenario is perhaps critical, but I would have expected this to fall out automatically: if it's not that might mean some symbol equality check is doing something "funky" and who knows what downstream issues might be happening that are worse than that.
