### ISSUE TITLE
Compiler generates empty cctor for static fields initialized to `null!`

### ISSUE THREAD

**Issue by stephentoub** [dotnet/roslyn#42985]
**Version Used**: 
3.6.0-2.20173.3+2242fa4fb945b97680bdd49eb5dd58285e4abb1c

**Steps to Reproduce**:
```C#
#nullable enable
using System;

public class C0 {
    private static readonly String S1;
}

public class C1 {
    private static readonly String S1 = null!;
}
```

**Expected Behavior**:
No cctor should be generated for either type, as in both cases S1 is null.

**Actual Behavior**:
An empty cctor is generated for C1:
```
    .method private hidebysig specialname rtspecialname static 
        void .cctor () cil managed 
    {
        // Method begins at RVA 0x2087
        // Code size 1 (0x1)
        .maxstack 8

        IL_0000: ret
    } // end of method C1::.cctor
```

**Comment by RikkiGibson** [comment]
This is a tricky one to solve. We add a synthesized static constructor to the members list based on the presence of a static non-const field initializer. We avoid binding any of the initializers in order to reduce the overhead of determining the member list. It seems like we should keep doing that.

I have tried an approach where we do not include a synthesized static constructor in the member list, and only decide whether to include one at emit. I'm concerned about the potential public API behavior break, and it also took somewhat hacky intervention to get flow analysis to still run on static initializers when doing this.

I have also tried keeping the synthesized static constructor in the members list, but deciding not to emit it if it is empty. This causes us to [throw in ReferenceIndexer](https://github.com/dotnet/roslyn/blob/91571a3bb038e05e7bf2ab87510273a1017faed0/src/Compilers/Core/Portable/PEWriter/ReferenceIndexer.cs#L124), and so far I can't think of any workaround that is not extremely hacky.

There might be a better place to do what I'm trying to do but I just haven't found it.

Tagging @AlekseyTs in case you have thoughts on how this should work.

**Comment by RikkiGibson** [comment]
It feels like #37975 is an alternative to this that we should consider

**Comment by AlekseyTs** [comment]
I think it should be fine to not emit an empty synthesized static constructor even when there is one in symbol. No one can refer to it in source anyway. I hope things would just work if it is excluded from the set returned by GetMethodsToEmit API. Might want to also check what VB does and whether the same issue is applicable.

**Comment by RikkiGibson** [comment]
in VB, a .cctor is always synthesized when a non-const, Shared field has an initializer, and initializers which assign the default value are included in the implementation instead of being optimized out like they are in C#.

**Comment by stephentoub** [comment]
Thanks, @RikkiGibson.
