### ISSUE TITLE
GetDeclaredSymbol's return type is not annotated as a nullable symbol

### ISSUE THREAD

**Issue by allisonchou** [dotnet/roslyn#42992]
Per this [comment](https://github.com/dotnet/roslyn/pull/42971#discussion_r401300134), GetDeclaredSymbol is in a file that is nullable enabled and the method's comments indicate that it can return null, however the return type is not annotated as a nullable symbol.

**Comment by CyrusNajmabadi** [comment]
I'm curious if this is actually a bug.  We have one of two scenarios:

1. we should get back some sort of param for an __arglist parameter.  This is then an issue on the compiler. (my preference)
2. we really want 'null' to represent this. (not my preference).  In which case, we have to mark this as `ISymbol?` or `IParameterSymbol?`, but we then will likely have to go and audit everything that breaks here.  Those audits are likely necessary because we likely do have __arglist bugs everywhere

**Comment by Youssef1313** [comment]
Looks like this was already fixed in #47209?

**Comment by jcouv** [comment]
Indeed, this was fixed (thanks @Youssef1313). Closing
