### ISSUE TITLE
Move to namespace UI behavior change 

### ISSUE THREAD

**Issue by tamlin-mike** [dotnet/roslyn#43086]
Experienced in VS16.5.1.

Referring to the combobox "Target Namespace" you get when you engage "Move to namespace...".

While pre-filling the combobox with project (or maybe it's even solution?) existing namespaces was a nice addition, it had a possibly unforseen consequence.

Previously, if you moved a type to a namespace you manually entered, that namespace remained as the first entry in the list (possibly because there were no other namespaces in the list?). That made it easy to continue to move types into the same namespace. You selected the type, "Move to...", hit down arrow, and return. For me that became so common it unfortunately runs on automatic. "Unfortunately", since I have now found myself moving types into the wrong namespace.

With the recent (recent as in "shipping VS 16.5.1" at least) change in behavior of this combobox, the "last moved to namespace" can now end up tens, or even hundreds of entries down in a list filled with all existing namespaces.

While I certainly wouldn't want the pre-filling to be removed, would it make sense to do one of the following?

- move (or copy) last-moved-to namespace to the top of the list.

- copying the behaviour of auto-completion, where it moves (or copies?) context-sensitive entries to the top of the list and mark them with a star.

If such a change is deemed good, and the latter of these two choices seems OK, it could even become a user-setting: "Star last N". For many scenarios N=1 would probably be a good choice, but I can also see larger code restructurings benefit from e.g. N=3.

Comments?

**Comment by ryzngard** [comment]
@tamlin-mike  Thanks for the feedback! 

There was no intentional change in this behavior, so I'll dig into what possibly regressed. That said, there's no special logic in the code that keeps the last used around. Instead, it's likely a result of the combobox being reused so the UI element maintains state. 

As far as the second part, favoriting namespaces could be a good idea but I imagine keeping state in the combobox would be sufficient. We should separate that concern out and determine it's usefulness after this bug is fixed.
