### ISSUE TITLE
Null dereference check is not performed when creating tuples

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/roslyn#43140]
_From @EgorManevich on Tuesday, April 7, 2020 9:34:26 AM_

### Steps to reproduce
When creating tuples using properties of nullable reference type, no null dereference checks are performed

```csharp
class Program {
	static void Main(string[] args) {
		M1(null);
	}
	static void M1(C? c) {
		var a = (c.I, c.I); //no warnings or errors on build
		Console.WriteLine(a);
	}
}
class C {
	public int? I { get; set; }
}
```

### Expected behavior
 Warning generated
`Dereference of a possibly null reference.`

### Actual behavior
No warnings are generated 

### Environment data
Build Engine version 16.5.0+d4cbfca49 for .NET Core

OS info:
Tried on MacOS, Windows

_Copied from original issue: microsoft/msbuild#5243_

**Comment by jcouv** [comment]
That was fixed in [16.6p1](https://github.com/dotnet/roslyn/pull/41690). I'll go ahead and close.
Thanks

([sharplab](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxASwDYB8ACAmARgFgAoAYgDsBXDDCYDOAAjgvsdNPyZwIHYmAb1IBIXgDYeAFiYBZCGgoAKXgAYA2gF0mEBAHMoASiGiRsgkuq1DAblEBfUROlyLAYQD8TAMbHhJEREAN10dJgBeJiVvADoASSQfeNsmAHpUigB7JgB3XQpFAyZMhBYEBBKoYoomYCpMABNTXgBOJQhbB1JHEm43EwCcAGYmRRgvOKEmPTgYGyYoWfme+yA===))
