### ISSUE TITLE
Support LSP hover outside of LiveShare

### ISSUE THREAD

**Issue by ajaybhargavb** [dotnet/roslyn#43274]
Roslyn already contains the support for LSP hover but was explicitly disabled on non-liveshare scenarios (https://github.com/dotnet/roslyn/pull/40937) due to classifications not being supported in LSP hover.

But we need the C# language server to support hover in order to make C# hovers work in Razor files (even though we might be missing classifications until it is supported).

cc @dibarbet

**Comment by NTaylorMullen** [comment]
@jinujoseph assuming the work here is minimal (since I believe you used to have this) would it be possible to land this for 16.7-preview1? We currently support hover for many of our Blazor components/TagHelpers and we'd love to make things consistent. 

As a side note we've also reached out to the CoreEditor folks to prioritize colorization for hovers so there doesn't have to be the discrepancy in remote scenarios.

/cc @mkArtakMSFT

**Comment by dibarbet** [comment]
this was resolved in https://github.com/dotnet/roslyn/commit/3d614b9eb89ed678ba7ade5e5859815853b44cc6
