### ISSUE TITLE
Workspace change events fire before IVsTypeScriptTodoCommentService is prepared to receive calls to ReportTodoComments 

### ISSUE THREAD

**Issue by rachelgshaffer** [dotnet/roslyn#43320]
**Version Used**: 3.6.0-3.20209.3

**Steps to Reproduce**:

1. JS/TS VS extension imports `IVsTypeScriptTodoCommentService` in order to call `ReportTodoComments`. On `DocumentAdded` and `DocumentChanged` workspace events we call into `ReportTodoComments`. 
See PR: https://devdiv.visualstudio.com/DevDiv/_git/TypeScript-VS/pullrequest/240324

**Expected Behavior**:
Calls to `ReportTodoComments` work and the comments appear in the Task List

**Actual Behavior**:
The calls fail because Roslyn has not finished loading

Ideally, one of the following would be true:
1. The service to be available by the time any workspace change events are fired
2. Some way to check if the service is available so that we can buffer any requests and wait to send them only when the service is available

**Comment by mavasani** [comment]
@jinujoseph maybe should be assigned to someone with more knowledge on interaction between core workspace events and our services...

**Comment by uniqueiniquity** [comment]
@CyrusNajmabadi It seems like this issue is still reproing and is causing our integration tests to fail.

I've added some telemetry (not inserted yet, hopefully will be soon) that shows the interleaving of events.

When the test passes, we see that `servicehubremotehostclient/createasync` happens before we finish reporting todo comments:
![image](https://user-images.githubusercontent.com/9092011/101411135-4ee75c80-3895-11eb-84f7-89268da64d25.png)

When it fails, we report, then that event happens:
![image](https://user-images.githubusercontent.com/9092011/101411173-61619600-3895-11eb-907f-1f0c8c969110.png)

Therefore, it seems to me that #43410 wasn't able to fix the issue.

**Comment by uniqueiniquity** [comment]
Sorry, forgot a key detail - the test waits for 5 seconds before failing, so it's unlikely that I'm not waiting long enough for the entries to be processed.

**Comment by uniqueiniquity** [comment]
Repro steps:
1. Create a JS file with `// TODO: blah` in it.
2. Open that JS file in VS (just thru Open -> File is fine).
3. Observe that no entries are added to the task list.

The timing is very sensitive, so attaching a debugger may cause the issue to stop reproing.
