### ISSUE TITLE
Cannot switch on nullable struct implicitly converable to string

### ISSUE THREAD

**Issue by yaakov-h** [dotnet/roslyn#4344]
Code:

	using System;

	namespace Repro
	{
		struct MyStringWrapper
		{
			public string str;

			public static implicit operator string (MyStringWrapper wrap)
			{
				return wrap.str;
			}
		}

		class Program
		{
			static void Main(string[] args)
			{
				MyStringWrapper? a = new MyStringWrapper { str = "c" };
				switch (a)
				{
					case "a":
						Console.WriteLine("a");
						break;

					case "b":
						Console.WriteLine("b");
						break;

					default:
						Console.WriteLine("default");
						break;
				}
			}
		}
	}

This works in VS2013, but breaks in VS2015.

If I switch on a `MyStringWrapper` (non-nullable), it compiles in VS2013 and VS2015.

If I switch on a `MyStringWrapper?`  as above, it compiles in VS2013 but outputs the following error in VS2015:

    Program.cs(20,12,20,13): error CS0151: A switch expression or case label must be a bool, char, string, integral, enum, or corresponding nullable type

**Comment by gafter** [comment]
According to the language spec, the conversion operator

```cs
        public static implicit operator string (MyStringWrapper wrap)
        {
            return wrap.str;
        }
```

doesn't have a lifted form, because

> ### 6.4.2 Lifted conversion operators
Given a user-defined conversion operator that converts from a non-nullable value type S to a non-nullable **value type T**, a lifted conversion operator exists that converts from S? to T?. This lifted conversion operator performs an unwrapping from S? to S followed by the user-defined conversion from S to T followed by a wrapping from T to T?, except that a null valued S? converts directly to a null valued T?.
>
A lifted conversion operator has the same implicit or explicit classification as its underlying user-defined conversion operator. The term “user-defined conversion” applies to the use of both user-defined and lifted conversion operators.

my emphasis. Of course this is a bug in the spec, but it is related to the bug in the implementation.

/cc @MadsTorgersen

**Comment by yaakov-h** [comment]
Does that mean that regarding the snippet above (from a non-nullable value type S to a **reference type T**) the old compiler's behaviour S? -> T (or S? -> S -> T) was actually undefined behaviour?

**Comment by gafter** [comment]
@yaakov-h No, it wasn't undefined. It was well defined as requiring a compile-time error.

We're going to change the language specification and the Roslyn compiler to make this behave as before.
