### ISSUE TITLE
IDE0046 code profiling not taken in account

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#43503]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/943257/ide0046-code-profiling-not-taken-in-account.html)._

---
[EN] The IDE0046 `true` configuration seems to not be taken in account when code refactoring (Ctrl+K/E).

Here is a code sample :
```
namespace Namespace1
{
	public class Class1
	{
		public override bool Equals(object obj)
		{
			if (obj is Class1 class1)
				return Equals(class1);
			return false;
		}
		public bool Equals(Class1 class1) => true; //actual comparison goes here
		public override int GetHashCode() => base. GetHashCode();
	}
}
```

And the associated `.editorconfig` file (French environment) :

```
[*.cs]

# IDE0046: Convertir en expression conditionnelle
dotnet_style_prefer_conditional_expression_over_return = true:suggestion

# IDE0011: Ajouter des accolades
csharp_prefer_braces = when_multiline:silent

# IDE0003: Supprimer une qualification
dotnet_style_qualification_for_method = false:silent

# IDE0022: Utiliser un corps de bloc pour les méthodes
csharp_style_expression_bodied_methods = true:silent
```

What I was waiting for is what the editor itself manually suggests ("Convertir en expression conditionnelle") :
`return obj is Class1 class1 ? Equals(class1) : false;`, that is then gracefully refactored (Ctrl+K/E) as
```
namespace Namespace1
{
	public class Class1
	{
		public override bool Equals(object obj) => obj is Class1 class1 ? Equals(class1) : false;
		public bool Equals(Class1 class1) => true; //actual comparison goes here
		public override int GetHashCode() => base. GetHashCode();
	}
}
```

Do you need more informations ?

[FR] La configuration de IDE0046 `true` semble ignorée lors de l'exécution du nettoyage de code. Voir cas d'usage ci-avant. Je reste à disposition si vous avez besoin d'informations complémentaires.

---
#### Visual Studio Feedback System on 3/9/2020, 08:24 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 3/12/2020, 08:48 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
This seems to be a request to automatically apply the expression-bodied methods preference when a refactoring simplifies the body of a method down to a single return statement.

**Comment by Daynvheur** [comment]
Hello, some precisions to avoid misinterpretations.

The specific `IDE0046` rule can be manually triggered, as in the following screenshot:
![image](https://user-images.githubusercontent.com/4216815/97292962-3cb4e000-184c-11eb-81f0-14b0290d1fe7.png)
The code block
```cs
if (obj is Class1 class1)
	return Equals(class1);
return false;
```
then becomes `return obj is Class1 class1 ? Equals(class1) : false;`.

**The problem is that this rule is not automatically applied when set to `true` in the `.editorconfig` file.**
Before Ctrl+K/E:
![image](https://user-images.githubusercontent.com/4216815/97294051-cd3ff000-184d-11eb-9a6c-c31ada853341.png)
After Ctrl+K/E:
![image](https://user-images.githubusercontent.com/4216815/97294235-0710f680-184e-11eb-8f35-5e4ec0ab65ae.png)
Note the lightbulb still indicating that `IDE0046` may apply:
![image](https://user-images.githubusercontent.com/4216815/97294372-30318700-184e-11eb-9218-4084df3a3418.png)

The only effect `IDE0046` has is to disable the lightbulb proposition when set to `false`.

Is it possible to have this rule be applied when code refactoring?
