### ISSUE TITLE
Roslyn Outlining regression from VS 2012

### ISSUE THREAD

**Issue by Jes28** [dotnet/roslyn#4353]
![2015-08-05_1516](https://cloud.githubusercontent.com/assets/3026249/9085405/2cf360b4-3b85-11e5-97ea-6d39fc83806b.png)

New otlining breaks formatting of all code in all projects.
Now code is hard to read and hard to fast find exact method or property in calss.
And that is the coolest class many others looks more ugly now.

Need setting to use VS2012 outlining style

**Comment by CyrusNajmabadi** [comment]
@Jes28 Can you provide a sample of the code you were using before?

**Comment by Jes28** [comment]
``` csharp
using System;

namespace Saber
{
	public class SomeClass
	{
		private		Int32		_someFiled;
		private		Single		_someFiled2;
		
		private		Int32		SomeFiled		
		{
			get	
			{
				return _someFiled;
			}
			set	
			{
				_someFiled = value;
			}
		}
		private		Single		SomeFiled2		
		{
			get	
			{
				return _someFiled2;
			}
			set	
			{
				_someFiled2 = value;
			}
		}

		private		void		Method	( )		
		{

		}
	}
}
```

**Comment by Jes28** [comment]
There are tabs in code not spaces.
May be this helps

**Comment by Jes28** [comment]
![summarycollapse](https://cloud.githubusercontent.com/assets/3026249/9686824/77042e34-532e-11e5-993f-6bb37cf16fe4.png)

The similar regression on summary collapse.
May be the best solution is to allow to collapse lines entirely so they dont interfere coding.
We can collape comments and symmary in that way

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/4995#issuecomment-137636299

Thanks for bringing this to our attention.  

Note: i'm only fixing the collapsed span location for the whitespace issue you called out.  I'm not changing the behavior for collapsed comments.  The collapsed comment form is very intentional.  And it's so that you can still glean useful information from comments even when they're collapsed.  

Cheers!

**Comment by Jes28** [comment]
Can you create toggle in settings to collapse comments entirely?
