### ISSUE TITLE
Semantics of ClosedFileDiagnostics solution crawler option

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#4364]
[ClosedFileDiagnostics](http://source.roslyn.io/Microsoft.CodeAnalysis.Features/R/bee6dce813e27221.html) is used in the IDE diagnostic service to determine whether running certain kind analyzer actions on closed files should be skipped. There are certain unclear aspects around what category of actions should be skipped and whether or not the reported diagnostics should be filtered:

1. Should the flag only apply to our own [IBuiltInAnalyzer](http://source.roslyn.io/Microsoft.CodeAnalysis.Features/R/e0e40b5b8006db68.html) analyzers, i.e. first party analyzers? Theoretically, 3rd party analyzers can have any action report a diagnostic on any file within a project, and we probably can't skip any of their actions based on this flag.

2. We cannot skip running compilation actions and compilation end actions based on this flag, as these actions can report diagnostics on open files. https://github.com/dotnet/roslyn/pull/4363 fixes this issue in the IDE diagnostic service.

3. Given that we can have some actions report diagnostics with location on closed files, should we filter out all diagnostics reported with locations in closed files if this flag is turned off. Basically this boils down to what semantics we want for this flag:
    1. Performance only: Avoid running certain set of actions to improve performance, but show me even diagnostics reported on closed files, if they got reported while computing open file diagnostics.
    2. Functional: I only want to see diagnostics reported on all open files in my VS instance.

**Comment by srivatsn** [comment]
We should filter out diagnostics on closed files that would have been produced by analyzing open files but we shouldn't try to report all diagnostics in open files that would have been produced by analyzing closed files.

**Comment by heejaechang** [comment]
I think there used to be only 2 cases.

1. user explicitly turned off running close file analysis (probably due to perf)
2. diagnostic analyzer can only produce hidden (or trigger) diagnostics which have no meaning for closed files. (no visible indication of the diagnostics except on view)

by the way, closed file analysis check should only apply to solution crawler code path. all other code path where analysis is requested explicitly (LB, fix all, error list and etc), closed file analysis check shouldn't affect anything. if the caller asked for closed file analysis, the service should provide them regardless of options or flags.

**Comment by heejaechang** [comment]
forgot to add @mavasani @srivatsn

**Comment by mavasani** [comment]
@heejaechang do you want to take this one and implement what Sri suggested for solution crawler path?

**Comment by heejaechang** [comment]
@mavasani @srivatsn this option is to make VS act like VS2013. so I think we either take this option out or just do what VS2013 does. basically show diagnostic only for opened file and that's it. we might even turn off all user diagnostic when this option is on. is there any person who think this option is important that require complex logic behind it? otherwise, I think we should just do really basic thing and done with it. or just remove this option

**Comment by heejaechang** [comment]
@mavasani @srivatsn by the way, what is the reason we had the Project Analysis to even run on this option off? I made it not run with this option off and did we ever hear anyone complaining about it? if we simply don't run project analysis when this option is off, there is no need for any complex thing we need to do since all the complexity comes from the Project

**Comment by heejaechang** [comment]
clicked wrong button.

**Comment by heejaechang** [comment]
moving to 1.2

**Comment by heejaechang** [comment]
we need to discuss what to do with this option.
