### ISSUE TITLE
[PDB] incorrect PDB document associated with hidden sequence points of MoveNext method

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#4370]
Compile the following code with

```
c:\Temp> csc /target:library /debug+ /optimize- Async.cs
```

```C#
#line 1 "C:\Async.cs"
#pragma checksum "C:\Async.cs" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "DBEB2A067B2F0E0D678A002C587A2806056C3DCE"

using System.Threading.Tasks;

public class C
{
	public async Task<int> M1() 
	{
		await Task.FromResult(0); 
		await Task.FromResult(1); 
		await Task.FromResult(2); 
		
		return 1;
    }
    
    public async void M2() 
	{
		await Task.FromResult(0); 
    }
}
```

The generated PDB contains 2 documents, but it should only contain a single document ```C:\Async.cs```.

```
<files>
    <file id="1" name="C:\Temp\Async.cs"  />
    <file id="2" name="C:\Async.cs"  />
</files>
...
<method containingType="C+&lt;M1&gt;d__0" name="MoveNext">
      ...
      <sequencePoints>
        <entry offset="0x0" hidden="true" document="1" />
        <entry offset="0x7" hidden="true" document="1" />
 <entry offset="0x27" startLine="8" startColumn="2" endLine="8" endColumn="3" document="2" />
        <entry offset="0x28" startLine="9" startColumn="3" endLine="9" endColumn="28" document="2" />
        <entry offset="0x34" hidden="true" document="2" />
        <entry offset="0x90" startLine="10" startColumn="3" endLine="10" endColumn="28" document="2" />
        <entry offset="0x9d" hidden="true" document="2" />
        <entry offset="0xfb" startLine="11" startColumn="3" endLine="11" endColumn="28" document="2" />
        <entry offset="0x108" hidden="true" document="2" />
        <entry offset="0x163" startLine="13" startColumn="3" endLine="13" endColumn="12" document="2" />
        <entry offset="0x167" hidden="true" document="2" />
        <entry offset="0x181" startLine="14" startColumn="5" endLine="14" endColumn="6" document="2" />
        <entry offset="0x189" hidden="true" document="2" />
      </sequencePoints>
```

**Comment by gafter** [comment]
@tmat Is it reasonable to assign this to you?

**Comment by tmat** [comment]
@gafter Yes.

**Comment by jcouv** [comment]
After investigation, my recommendation is WON'T FIX.

Both possible solutions to fix how hidden sequence points reference documents works:
1) Having the heading hidden sequence points find the document at position 0,0
2) Having the heading hidden sequence points look for the next real sequence point

Approach (1) doesn't give the expected behavior (the sequence point will still refer to the actual file name, rather than the one specified in the pragma).

Approach (2) solves the problem described in the bug, but introduces bad side effects. This is illustrated by the `NormalizedPath_ExternalSource` unittest, where the heading hidden sequence point would reference the wrong document (the one from a later pragma, rather than the actual file name).

**Comment by tmat** [comment]
@jcouv and I discussed this offline and we discovered bugs in VB sequence points that need to be fixed first. Then we can reevaluate. I still believe this bug should be fixed as well.

**Comment by jcouv** [comment]
Two changes committed in #8961:
1. heading hidden sequence points get positioned within document according to the first real sequence point (this saves from including un-necessary document reference)
2. methods with only hidden sequence points emit no sequence point to the PDBs
