### ISSUE TITLE
Tool - text editor - s- code style, cannot be modified, tool-text editor-s-s-s-code style, modified point ok can't be saved

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#43812]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1007571/tool-text-editor-c-code-style-cannot-be-modified工具.html)._

---
**Tool -> text editor ->C#-> code style, cannot be modified,工具->文本编辑器->C#->代码样式,修改后点确定无法保存**

---
#### Visual Studio Feedback System on 4/26/2020, 06:36 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 4/29/2020, 09:40 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by mavasani** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/43815 for VS2019 16.7 Preview1. Unfortunately, the bar for 16.6 is very high at this point to take this into 16.6 RTW. As a workaround on 16.6, you can define an .editorconfig at the root of your repo or drive and update the code style options in this file. See https://docs.microsoft.com/en-us/visualstudio/ide/code-styles-and-code-cleanup?view=vs-2019#code-styles-in-editorconfig-files
