### ISSUE TITLE
New keyboard key(physical) to hide async keyword, so that i can read/understand rest of the business code in editor.

### ISSUE THREAD

**Issue by dvbava** [dotnet/roslyn#43977]
**Version Used**: 

**Steps to Reproduce**:

1. create one async method
2. call it from different class
3. iterate using IAsyncEnumerator

**Expected Behavior**: I should be able to read and understand code/business.

**Actual Behavior**: I only can see its ocean of async words.

**Comment by sharwell** [comment]
The `async` keyword is only 5 characters, and was chosen partly for its brevity. We can't hide the keyword outright, since it would make it very difficult to read code (synchronous and asynchronous code do not behave the same way, so it's critical readers can tell them apart). I'm going to go ahead and close this specific issue as "won't fix", but if you are interested I can try to get you a meeting with one of our PMs to better understand the larger issues that led to this request.
