### ISSUE TITLE
Rename: Invoking rename when there is an active session should commit

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#44]

**Comment by DustinCampbell** [comment]
Yes it should. :-)

**Comment by balajikris** [comment]
Looks like it our current design sets the focus to the dashboard in such a scenario.

the command handler has a comment and a piece of code to do this:
// If there is already an active session, focus its dashboard;

**Comment by DustinCampbell** [comment]
I remember now. We changed F2 to focus the dashboard to provide keyboard access to various checkboxes. Now that I try that experience, I think that might not be the right behavior. In order to keep users fluid productive, I think F2 should probably commit the active session and start a new one. @Pilchie, what do you think?

If we change this back, are users still able to use the options on the dashboard with the keyword? Using accelerator keys should still work, right?

**Comment by Pilchie** [comment]
@rchande - do you know the state of accelerators and F2?

**Comment by rchande** [comment]
Accelerators should work even if you focus the editor. We changed F2 to refocus the dashboard in order to allow users of screen readers to have the dashboard read to them. How could we implement that if we made F2 commit?

**Comment by DustinCampbell** [comment]
What if we had a separate accelerator key that could provide focus without invoking something (Alt+F2). Is that possible?

**Comment by rchande** [comment]
Sure, that sounds reasonable.

**Comment by rchande** [comment]
The new plan here is:

The dashboard isn't focused by default. F2 within a rename field focuses it, F2 outside a rename field commits and tries to start a new session.

**Comment by rchande** [comment]
Merged into stabilization with #3186.

**Comment by rchande** [comment]
@Pilchie Can you verify this?
