### ISSUE TITLE
[VB][Auto-complete bug] Auto replace parallel keywords

### ISSUE THREAD

**Issue by NaxAlpha** [dotnet/roslyn#4406]
Hi,
Let say we have a function like
![image](https://cloud.githubusercontent.com/assets/11090613/9130636/fc08d16c-3cfd-11e5-86cf-909de5e84669.png)
If we replace word function with sub as
![image](https://cloud.githubusercontent.com/assets/11090613/9130649/20bccd24-3cfe-11e5-9df5-ed3cda7bad89.png)
It automatically replaces word End Function with End Sub e.g.
![image](https://cloud.githubusercontent.com/assets/11090613/9130663/3ee6075c-3cfe-11e5-8b6a-fa2de9877ce1.png)
but if i press space in following situation
![image](https://cloud.githubusercontent.com/assets/11090613/9130711/9213feac-3cfe-11e5-8c84-83371dbf5897.png)
it should have replaced End Sub with End Function but it does not work
![image](https://cloud.githubusercontent.com/assets/11090613/9130736/be0ef20a-3cfe-11e5-8fb2-e03ba8af2e82.png)
This happens because i didn't wrote Function whole instead i used auto-complete by space key.
if i would had written whole word Function like
![image](https://cloud.githubusercontent.com/assets/11090613/9130780/2701db7e-3cff-11e5-80fc-377b127c2fee.png)
It works

**Comment by Pilchie** [comment]
I don't seem to be able to repro this - even when I complete the item from the completion list, the End Sub is updated.  Any more detail you can provide about what might be going wrong here?

**Comment by NaxAlpha** [comment]
Auto complete is not selecting 1st element in list by default at this case, which can be selected by pressing down arrow key and then 1st element in list is selected and then pressing space or tab does not change parallel token

**Comment by Pilchie** [comment]
Ah.  That happens on purpose, because you might be typing a field:
```VB
Public field as Integer
```

When you type `f`, there is no way to know if you are going to type function or field, so we have the extra element in the list to allow you to declare a new field.

**Comment by NaxAlpha** [comment]
Problem is not with this list,
it is with replacing paired keyword

**Comment by Pilchie** [comment]
I understand, but I'm unable to see any problem here.  If I choose the item and commit with tab, it is updated appropriately.  If I type it out all the way, it is similarly updated appropriately.

**Comment by NaxAlpha** [comment]
Thanx for help i think in next update of visual studio i ll also be able to do that but in current version i cant

**Comment by Pilchie** [comment]
What version of VS are you seeing this with?  I've been looking at VS2015 RTM.

**Comment by NaxAlpha** [comment]
I am using vs2015 rtm

**Comment by Pilchie** [comment]
Then there is still something missing, because I am not able to reproduce the issue you are seeing.  Any chance you could record a screen capture or something to help narrow down exactly what you are doing?

**Comment by NaxAlpha** [comment]
[Here](http://1drv.ms/1hw37gb) is sample video

**Comment by dpoeschl** [comment]
@Pilchie @NaxAlpha It repros for me on VS2015 RTM with these steps:

1. Paste this code:
    ```VB
    Class C
        Public Sub Test()
        End Sub
    End Class
    ```

2. Select/highlight the first ```Sub``` and type ```fun<tab>``` (with a *lowercase* f), 

**Expected**: The end construct should be updated to ```End Function```. 
**Actual**: The end construct is not updated. (Note: If you type ```Fun<tab>``` instead, then the end construct is correctly updated)

*Comments*: When the <tab> completion switches the text from ```fun``` to ```Function```, that change is interpreted as TWO changes, { f => F, ε => ction }, with the middle “un” unchanged.  This causes [LinkedEditsTracker.TryGetTextChanged](http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures/Shared/Utilities/LinkedEditsTracker.cs,84) to return false, which then makes the [AutomaticEndConstructCorrector bail](http://source.roslyn.io/#Microsoft.CodeAnalysis.VisualBasic.EditorFeatures/AutomaticEndConstructCorrection/AutomaticEndConstructCorrector.Session.vb,51) instead of fix the end construct.

**Comment by dpoeschl** [comment]
@Pilchie I meant to mention this earlier, but I think this should be easy to fix. While the intersection in TryGetTextChanged contains multiple spans, those multiple spans are contained by a *single* tracking span, so you should still be able to calculate ```singleTrackingSpanTouched``` in this case (and only bail if multiple *tracking spans* are touched).
