### ISSUE TITLE
XAML: Provide access to project properties and capabilities

### ISSUE THREAD

**Issue by mgoertz-msft** [dotnet/roslyn#44133]
**Problem**
Project does not currently provide access to project properties and capabilities making it harder to develop project-specific features.

**Justification**
XAML semantics are different for each platform (WPF, UWP, Xamarin, etc.). The platform usually depends on the type of project and is generally determined by a variety of project properties, such as:
- TargetFrameworkMoniker
- TargetPlatformIdentifier
- TargetPlatformVersion
- TargetPlatformMinVersion
- etc.

Or capabilities, such as:
- WindowsXAML
- SharedAssetsProject
- etc.

**Ask**
Please provide access to project properties and capabilities through `Project`.

**Comment by tmat** [comment]
@jasonmalinowski What do you think would be the best approach here? I believe we are making some msbuild properties available for source generators, correct?

**Comment by jasonmalinowski** [comment]
Yes, we are making some properties available. @chsienki would be able to give a pointer to more information.

**Comment by chsienki** [comment]
We're currently working on a mechanism that allows you to select properties to be provided via analyzer config using the mechanism added here: #43617 (We can't just pass every property through, as the amount of data is way too large, and most of it wouldn't be used).

Note that the compiler doesn't really have a concept of `TargetFramework` etc, all it sees is a set of references. We encourage people to do feature detection rather than relying on these properties to decide how to do project specific things, which makes them both resilient to change and future proof as new features get light up (think of JS feature detection vs agent string matching).  It's also possible that someone could call the compiler without invoking MSBuild at all, so there wouldn't even _be_ a `TargetFramework` to read.

We don't have a perfect answer yet, but we're thinking about how we can make feature detection easier to do https://github.com/dotnet/roslyn/projects/54#card-37390778

**Comment by mrlacey** [comment]
This is great for projects within Microsoft/VS but without proper extensibility support for XAML, there is limited benefit to this.

**Comment by mgoertz-msft** [comment]
This request is not necessarily XAML specific. C# analyzers could benefit from this as well.

XAML extensibility is really orthogonal to this. While that is on our roadmap it is highly unlikely to happen in the near term.

**Comment by mavasani** [comment]
This is done - https://github.com/dotnet/roslyn/blob/master/docs/features/source-generators.cookbook.md#consume-msbuild-properties-and-metadata
