### ISSUE TITLE
BatchFixAllProvider is not deterministic

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#4416]
Currently the order in which code fixes are attempted by the `BatchFixAllProvider` is not deterministic. When conflicts exist between two or more fixes, the fix which gets applied is not always the same fix. This is especially problematic for unit tests which apply batch fixes (see DotNetAnalyzers/StyleCopAnalyzers#1126 for our automated `FixAllProvider` testing).

I believe we have now corrected this problem via DotNetAnalyzers/StyleCopAnalyzers@da4452e1d229dd11afd59e6ba89569aa043da7c1. Note that `CustomBatchFixAllProvider` is a copy of `BatchFixAllProvider` which is modified in the following ways:
- Uses of internal logging APIs were removed.
- The deterministic application issue was fixed.
- Generated code is not treated in a special manner (#2753).

**Comment by balajikris** [comment]
I believe this is outside the scope of the default BatchFixer. From speaking to various team members who originally designed and implemented the `BatchFixAllProvider`, it appears that the default batchfixer assumes that individual fixes can be applied independently and resulting changes can be merged without conflicts. 

From the [Documentation](https://github.com/dotnet/roslyn/blob/e39a3aeb1185ef0b349cad96a105969423065eac/src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/WellKnownFixAllProviders.cs#L13-L15) of the default batchfixer : 

---

Default batch fix all provider.
This provider batches all the individual diagnostic fixes across the scope of fix all action, computes fixes in parallel and then merges all the **non-conflicting fixes** into a single fix all code action.

---

So, I guess the non-determinism that Sam is encountering happens because of using the default batchfixer for something it wasn't designed for. Sam's solution to this (writing a custom batch fixer) is indeed the correct approach. Given that, we'll leave the default batchfixer untouched. 

**Thoughts?** @sharwell, @Pilchie , @srivatsn , @mavasani , @shyamnamboodiripad , @DustinCampbell

**Comment by mavasani** [comment]
I synced with Balaji on this, and we still do need to fix this. Even though the batch fixer only applies non-conflicting fixes (which is a subset of batch of all fixes), we want this subset to be deterministic. The current implementation of the batch fixer doesn't guarantee this determinism.

You can either use Sam's proposed fix or some other alternative that allows you to deterministically order the registered code actions for merge operation (which is sequential). One option is to change the ConcurrentBag<CodeAction> [here](http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/CodeFixes/FixAllOccurrences/BatchFixAllProvider.cs,54) to a ConcurrentBag<Tuple<CodeAction, Diagnostic>>, and then finally order the code actions based on the diagnostic's tree and span [here](http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/CodeFixes/FixAllOccurrences/BatchFixAllProvider.cs,70) before passing them down to TryGetMergedFixAsync.

**Comment by sharwell** [comment]
> I believe this is outside the scope of the default BatchFixer.

The current implementation of the batch fixer cannot be reliably or comprehensively unit tested due to this issue. Either the current tests are not actually producing conflicting changes (and thus not testing a critical piece of functionality), or the tests are going to fail sporadically.

It sounds like we are all on the same page now regarding the need for a fix. :+1:

**Comment by mavasani** [comment]
> Either the current tests are not actually producing conflicting changes (and thus not testing a critical piece of functionality), or the tests are going to fail sporadically.

Yes, we don't have too many tests to test the batch fixer in presence of conflicting fixes (probably just 1-2). #3404 tracks adding more unit tests for the batch fixer.

**Comment by balajikris** [comment]
We still need to fix this, but currently it does not meet our bar for 1.2 milestone. Moving it to 1.3 for now.

**Comment by Pilchie** [comment]
@CyrusNajmabadi you've been looking at the batch fixer stuff lately.
