### ISSUE TITLE
Covariant returns when the platform lacks `PreserveBaseOverridesAttribute`

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#44208]
We need to decide how the compiler should behave when the underlying platform advertises support for covariant returns but lacks an accessible declaration for `System.Runtime.CompilerServices.PreserveBaseOverridesAttribute` or its default constructor. Some choices are:
1. Simply do not produce the attribute
2. Produce an error at compile-time
3. Produce a warning at compile-time
4. Generate an attribute definition in the source module.

The current behavior in the feature branch is (1).

**Comment by AlekseyTs** [comment]
I believe we should treat this attribute as required. In cases like that we report an error if the type or constructor is missing. Also, since the attribute is so "intimate" to runtime, we should not generate its definition, instead the runtime that claims to support the feature should include the attribute into the core library.

**Comment by gafter** [comment]
@AlekseyTs Also suggests in the review of https://github.com/dotnet/roslyn/pull/44025
1. I think we should limit lookup of this attribute to the core library, therefore, should move it to the set of SpecialTypes. 
2. Similarly to the type, I think this (the constructor) should be a special member.
