### ISSUE TITLE
Inconsistent verb tense in name for internal symbol types

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#44294]
We use past tense for most modified symbol classes (e.g. `SubstitutedMethodSymbol`). However, for one category we use a different tense ("Retargeting"). The difference is gratuitous. We should settle on one convention and rename for consistency. I prefer the past tense.

**Comment by gafter** [comment]
@AlekseyTs and I discussed this and he explained the reason for the difference. I'll let him explain here and close the issue.

**Comment by AlekseyTs** [comment]
The term "retargeting" reflects the fact that the symbols perform retargeting of types that they use (in signatures, etc) rather than to reflect the fact that they are themselves are retargeted. For example, when a type symbol is retargeted it can change, but the result isn't necessary a "retargeting" type symbol, though it could be in some cases.
