### ISSUE TITLE
Compiler API for getting semantic information about an attribute syntax

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#44340]
Currently, there is no IOperation API for attributes (#18198). Additionally, there is no API on semantic model that given an attribute syntax node returns the corresponding `AttributeData` which has all the required semantic information about the attribute, i.e. all the resolved constructor and named arguments for the attribute. It would be nice if we can provide either or both of the following APIs:

1. IOperation API for attributes (#18198)
2. Semantic model API to get `AttributeData` for a given attribute syntax node, say `public AttributeData SemanticModel.GetAttributeInfo(SyntaxNode attributeSyntax)`

**Comment by mavasani** [comment]
Tagging @AlekseyTs @333fred

**Comment by AlekseyTs** [comment]
@mavasani The issue makes it sound like there is absolutely no information provide by IOperation and SemanticModel. I believe this is not accurate. I believe we do have support in SemanticModel for attribute applications and it is likely possible to examine symbols for constructors, get information about arguments, etc. Given that we have SemanticModel for attributes, it is alo likely that there is IOperation support for constituent pieces of an attribute application. So, I think it would be good to have a clear picture what is exposed and what isn't exposed in order to have a better understanding of the feature gap.

**Comment by mavasani** [comment]
@AlekseyTs Yes, sorry for not being clear. We do expose the operation tree with an OperationKind.None node. Also semantic model APIs allow you to get semantic information about constituent parts of the attribute node. So, this is not a blocking issue for attribute analysis.

The request here is an enhancement to expose a strongly typed IAttributeOperation with rich properties like Arguments, NamedArguments etc. Additionally, it might be good to expose some API that provides AttributeData given an attribute syntax node, currently you can only get that from ISymbol.GetAttributes() API. Latter might not be required if we implement the IOperation API.

**Comment by RikkiGibson** [comment]
Closing in favor of #53618
