### ISSUE TITLE
TypedConstant.get_Type() can cause NullReferenceException

### ISSUE THREAD

**Issue by JosefPihrt** [dotnet/roslyn#44377]
**Version Used**: 3.5.0

Prior to [this commit](https://github.com/dotnet/roslyn/commit/0b3b6d5a28c7b5e10dd312d339b210b1b5c9cef0) code for `TypedConstant.Type` looks like this:
```cs
public ITypeSymbol Type
{
    get { return _type; }
}
```
Now it looks like this:
```cs
public ITypeSymbol Type
{
    get { return _type.GetITypeSymbol(); }
}
``` 
which can cause NullReferenceException if the `_type` is null.

**Comment by jinujoseph** [comment]
cc @333fred

**Comment by 333fred** [comment]
@JosefPihrt are you seeing a crash? `TypedConstant._type` should never be null, if there's a crash because that is `null` there's a bug somewhere else.

**Comment by JosefPihrt** [comment]
If `var x = default(TypedConstant)` then I'm seeing a crash for `x.Type`.

**Comment by 333fred** [comment]
Unfortunately, there's not a lot we can do about that. You're not meant to be creating `TypedConstant` instances, and we annotate and code for expected use cases. This is why the constructors for this type are all `internal`: you shouldn't be constructing them. If you need to have a non-initialized copy, I'd suggest using a `TypedConstant?` to represent the difference. There are a number of struct types in the compiler like this that we do not expect to be defaulted, and as such we don't guard the implementations against `default`. While the language team has considered non-`default`able structs a few times to try and help scenarios like this, they haven't made a decision on them yet.

**Comment by JosefPihrt** [comment]
@333fred I do not create instance of TypedConstant. I have existing code that start to crash after update from 3.0.0 to 3.5.0.

Related commit: https://github.com/JosefPihrt/Roslynator/commit/e7a79b2a45ccefdad2c8b5e6d61de2b195fb406d

**Comment by 333fred** [comment]
FirstOrDefault creates a default of TypedConstant. Again, this is not valid.

This type is nullable annotated. If we were to put a null test in there, it would have to return null or just throw an InvalidOperationException. The former is a penalty for all consumers that use valid TypedConstants, because they never need to worry about null. The latter is just a different exception. I would not be opposed to adding an IsDefault property to TypedConstant to allow testing for this if that would help. But changing the implementation of the type doesn't solve the real problem.
