### ISSUE TITLE
Proposal: Enable assigning functions with less number of arguments to events/delegates with more

### ISSUE THREAD

**Issue by tpetrina** [dotnet/roslyn#4446]
This is common when registering events, consider this:
```
event1 += (s, o) => { /* */ };
event2 += (s, o) => { /* */ };
```

Since I am not using neither of these parameters, it would be wonderful if compiler could handle the following syntax:
```
event1 += () => { /* */ };
event2 += (s) => { /* */ };
```

Current workaround for registering functions that ignore arguments:
```
private void foo() {}
event1 += (s, e) => foo();
```
Which is messy because you have to name those arguments. And you cannot unregister foo from event since it is actually not bound to it.

**Comment by HaloFour** [comment]
It's the CLR that imposes the signature limitation on delegate targets.  How exactly might C# overcome that issue?

The only real way I can think of this happening is if the compiler were to emit a helper method which would marshal the call:

```cs
private void foo() { }

event1 += foo;
```

would become:

```cs
private void foo() { }
private void foo_event1_helper(object sender, EventArgs e) { foo(); }

event1 += foo_event_helper;
```

But this still seems like it would be messy when it comes to unsubscribing.  For example, let's make the foo method `public`.  You have one class which subscribes the event, so the compiler emits a helper method to make that happen.  Then in another class, which happens to have a reference to the same instance on which the event is subscribed, wishes to unsubscribe.  The compiler would have to emit a separate helper method, and because the target is different the CLR wouldn't remove the original subscription.

**Comment by tpetrina** [comment]
Well, compiler already did ton of magic in async code without touching CLR so I am sure there could be a way to handle this as well. But yes, you are on the right track with that helper method, something like that would work.

**Comment by mburbea** [comment]
C# already supports assigning 0 parameter functions via the `delegate` form so it's not an unprecedented ask. At least for parity with the anonymous delegate syntax it could be useful to add support for 
```csharp
SomeEventHandler current_allowed= delegate{};
SomeEventHandler parity_form=()=>{};
```

**Comment by HaloFour** [comment]
That's not assigning 0 parameter functions, that's assigning arbitrary parameter delegates.  The compiler emits a closure that matches the function of the signature which has the exact same problem as using a lambda to wrap the subscription.

**Comment by gafter** [comment]
Changing the lambda conversion like this would be a breaking change, so unlikely to be taken.
