### ISSUE TITLE
Unexpected CS8762 

### ISSUE THREAD

**Issue by zspitz** [dotnet/roslyn#44494]
**Version Used**: 
16.6.0

**Steps to Reproduce**:
```
public static bool Test([NotNullWhen(true)] out object? value) {
    bool isAfternoon = DateTime.Now.Hour > 12;
    value = isAfternoon ? new Random() : null;
    return isAfternoon;
}
```

**Expected Behavior**:
No warning

**Actual Behavior**:
CS8762: Parameter 'value' must have a non-null value when exiting with 'true'.

**Additional info**:
Expanding the ternary if doesn't seem to make a difference:
```
public static bool Test([NotNullWhen(true)] out object? value) {
    bool isAfternoon = DateTime.Now.Hour > 12;
    if (isAfternoon) {
        value = new Random();
    } else {
        value = null;
    }
    return isAfternoon;
}
```

**Comment by RikkiGibson** [comment]
Unfortunately you've hit upon a fundamental limit of C#'s nullability analysis. By the time we hit the 'return' statement, the information we learned about what happens when 'isAfternoon' is true is lost.

This comment explains the fundamental issue, though in the context of a different scenario: https://github.com/dotnet/roslyn/issues/36927#issuecomment-508595947

The simplest fix is probably to return a literal 'true' or 'false' inside the respective branches of the if statement:

```cs
    public static bool Test([NotNullWhen(true)] out object? value) {
    bool isAfternoon = DateTime.Now.Hour > 12;
    if (isAfternoon) {
        value = new Random();
        return true;
    } else {
        value = null;
        return false;
    }
```

**Comment by zspitz** [comment]
@RikkiGibson Is this the same as #44285?

**Comment by RikkiGibson** [comment]
No. The reason that other situation works is that the returned expression itself tells the compiler that the 'out' parameter is "not null when returning true". Unfortunately some forms of indirection do not work, as in the following examples:

```cs
class C
{
    bool M([NotNullWhen(true)] out string? p)
    {
        p = null;
        return p != null; // ok, no warning
    }
}

```


```cs
class C
{
    bool M([NotNullWhen(true)] out string? p)
    {
        p = null;
        bool flag = p != null;
        // we get a warning because the information that
        // flag "implies" p != null is lost after visiting the statement.
        return flag;
    }
}

```
