### ISSUE TITLE
Struct names sometimes shown using the class name color after updating to 16.7-p1

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#44506]
**Version Used**: 16.7-p1

**Steps to Reproduce**: After running the VS installer to update first 16.5.5 to 16.6.0 and then the latest 16.6 preview to 16.7-p1, the 16.7 installation showed struct names in the same color as class names. I'm pretty sure this persisted across a couple of VS restarts. I lost the repro when I opened 16.6 to see if it also had the issue. It did not, and when I reopened 16.7, it did not either.

@Joe4evr had a different experience. ~~After updating to 16.7, both his 16.7 and 16.6 installations started exhibiting the bug.~~ My bad, he has only 16.6 and is seeing the bug there.
I believe his repro hasn't gone away, but I think he also plans to reset the color by hand.

![image](https://user-images.githubusercontent.com/8040367/82616111-5285f100-9b9a-11ea-837b-787fa50c9500.png)

/cc @JoeRobich, @CyrusNajmabadi

**Comment by JoeRobich** [comment]
In VS 16.6 could you check Tools > Options > Text Editor > C# > Advanced and let me know if the Editor Scheme is showing "Visual Studio 2017" or "Visual Studio 2019". Since the struct color was introduced in 2019, if the migration to 16.6 determined you should be started on VS2017 (possibly because other custom colors) then you can just flip it to VS 2019 and be good to go.

**Comment by jnm2** [comment]
Mine says 2019, but I lost the repro when I opened 16.6. @Joe4evr?

**Comment by Joe4evr** [comment]
> @Joe4evr had a different experience. After updating to 16.7,

I'd like to point out, I actually *haven't* installed 16.7. I was purely using 16.6 and at some point the struct name color switched to the 2017 style.
> In VS 16.6 could you check Tools > Options > Text Editor > C# > Advanced and let me know if the Editor Scheme is showing "Visual Studio 2017" or "Visual Studio 2019".

@JoeRobich Yep, looks like it got set to 2017 for some reason for me.

**Comment by JoeRobich** [comment]
Merged this change (https://github.com/dotnet/roslyn/pull/45118) to how we handle the migration from the old "Use enhanced color" experience to the new "Editor color scheme" experience. Unfortunately this cannot correct migrations that have already reset colors to the VS 2017 scheme. It will however allow those who are skipping VS 16.6 avoid this when they upgraded. 

For users who have already had a failed migration when upgrading to 16.6 or 16.7 preview the fix is to manually update the "Editor Colors Scheme" option from the Text Editor > C# | Basic > Advanced page.
