### ISSUE TITLE
Some SyntaxTreeRootTests are commented out

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#4453]
Validation for some of the tests are commented out:
```
#ifdef false
...
#endif
```.

**Comment by jaredpar** [comment]
Can we get a link to the tests?

**Comment by jaredpar** [comment]
Can we get a link to the tests?

**Comment by tmat** [comment]
```src\Compilers\CSharp\Test\Semantic\Semantics\SyntaxTreeRootTests.cs```

**Comment by TyOverby** [comment]
@jaredpar 

I don't think that these tests have *ever* been run.  

[SyntaxTreeRootTests lines 126 and 129](http://source.roslyn.io/#Roslyn.Compilers.CSharp.Semantic.UnitTests/Semantics/SyntaxTreeRootTests.cs,126) is an obvious bug that immediately throws a `System.ArgumentException : An item with the same key has already been added.`  Due to this, I suspect that this code has never been tested.

**Comment by jaredpar** [comment]
@TyOverby it's very possible these have been disabled since ... who knows when.  Let's go through them all and enable them if they make sense, delete them if they are just non-sense code.

**Comment by TyOverby** [comment]
Well they've certainly been disables since Roslyn was open sourced.  Git blame shows the initial git commit as the source.

The code for [SpeculativeSemanticModelTestsBase](http://source.roslyn.io/#Roslyn.Test.Utilities.Desktop/SpeculativeSemanticModelTestsBase.cs,751524ac69073b4b) looks like it's using reflection to access members on the SyntaxTree, and asserting that calling them yields the right exceptions. 

Seems like something that is made more confusing by automating it.
