### ISSUE TITLE
CancellationToken is not correctly propagated downstream

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#447]
Ported from TFS WorkItem: **1118674**

------------------------------

**Repro Steps:**

**Repro:**

1. create new TypeScript project (in Dev14)

2. open .ts file, hit ctrl+s many times (this will invoke compile-on-save), make a few edits (add spaces) then keep saving the file. Eventually VS crashes.

&nbsp;

**Reason:**

Gist of current implementation of CompileOnSave in TypeScript 

var cancellationToken = cts.Token;

try {

&nbsp;&nbsp;&nbsp; await CompileAndSave(cancellationToken)

}

catch(OperationCancelledException e) {

&nbsp;&nbsp;&nbsp; if (e.CancellationToken == cancellationToken) {

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; return;

&nbsp;&nbsp;&nbsp; }

&nbsp;&nbsp;&nbsp; throw;

}

&nbsp;

For some reason TaskCancelledException that crashes VS contains cancellation token that is equal to CancellationToken.None and&nbsp;at glance it is thrown from inside the AsyncLazy&lt;T&gt; code in Roslyn

**Comment by jasonmalinowski** [comment]
@stephentoub, the problem here is that the Task that gets returned out of AsyncLazy is a task from a TaskCompletionSource that we have canceled with TrySetCanceled(). I see there's now an overload TrySetCancelled(CancellationTokenSource) that's available in 4.6 but we're still on 4.5. It's also not portable. Do I have alternatives here?

**Comment by stephentoub** [comment]
No great options, which is why the method was added for 4.6.  The only way I can think of right now pre-4.6 would be to use an AsyncTaskMethodBuilder instead of a TaskCompletionSource.  It exposes SetResult and SetException, and if you call SetException with an OperationCanceledException that wraps the token you care about, that'll cancel the task and put that token into it.  The primary complication here is that AsyncTaskMethodBuilder treats any OperationCanceledException as an indication that it should cancel the Task (there's no separate SetCanceled method), so if your API requires being able to store arbitrary exceptions into this and you don't want OperationCanceledExceptions to be treated as cancellation, you can't use this approach, or you'd need to wrap the OCE with a non-OCE to fool the AsyncTaskMethodBuilder.

**Comment by tmat** [comment]
TaskCompletionSource<TResult>.TrysetCanceled(CancellationToken) is in Project K profile, so we can actually use it once we move to Core CLR.

**Comment by tmat** [comment]
@Pilchie any reason why not to require 4.6 for Workspaces right now?

**Comment by jasonmalinowski** [comment]
There's no code we have that relies on the distinction of Faulted w/ OCE vs. Canceled. We do use Faulted w/ OCE as an indication that somebody might have done something bad with a cancellation token (like passed the wrong one around) so we might be hiding bugs but that seems preferable than this issue which is going to be observable to consumers of Roslyn.

One downside of AsyncTaskMethodBuilder it appears is it doesn't have Try* methods so I get to do that myself at the cost of additional memory when it looks like the Task already knows internally what is going on. Any recommendations there?

**Comment by stephentoub** [comment]
I'm not clear on the memory costs you're concerned about.  Can you elaborate?  If it's possible that someone else may have already completed the task, then you can check builder.Task.IsCompleted prior to trying to SetResult/Exception on it.  Which means that the only time you run the risk of exception getting thrown that you have to then catch and handle/ignore is if there's a race where the task is completed between the time you check IsCompleted and call Set*; that's a pretty small window to be concerned about the exceptional perf overheads.  Or did I misunderstand?

**Comment by stephentoub** [comment]
(Additionally, AsyncTaskMethodBuilder is a struct, so you're actually saving an allocation by switching to it.  You just need to make sure to access its Task property before any asynchronous code is scheduled that could possibly race to access Task.  Remember that this type is what underlies async methods, and its design is specific to that scenario.)

**Comment by jasonmalinowski** [comment]
The code that we have that deals with TaskCompletionSources does things like inherit from it vs. have a separate object containing it to avoid the extra pointer in memory. So it's somewhat sensitive. But you're right since AsyncTaskMethodBuilder is a struct embedding that into a class is no worse than anything else.

> that's a pretty small window to be concerned about the exceptional perf overheads

I'd be worried less about the perf in that approach than the evils of the first-chance exception and the potential noise it makes for other people debugging VS.

**Comment by stephentoub** [comment]
If your worst problem is that in an extremely small window, while debugging, with parallel execution of specific code paths, there may be an extra first-chance exception, I think you've got a winner.

**Comment by jasonmalinowski** [comment]
:-)

**Comment by jasonmalinowski** [comment]
To follow up on the memory concerns after chatting with @pharring:

Our current Request object that holds onto the state needed for an asynchronous request for the value *derives* (!!) from TaskCompletionSource to save an allocation and through that has the other pointer to the Task object itself. Switching to AsyncTaskMethodBuilder doesn't change the allocation count, but does mean that in addition to the Task reference we're also bringing along two additional fields which aren't necessary for our scenario. Our allocation count is still the same, but our type grows by a few fields. It's something we'd like to avoid but don't have a better option we think.

We discussed using reflection, but then to invoke it requires boxing the CancellationToken in the MethodInfo.Invoke() so it doesn't buy us anything. So we'll take the hit and look forward to moving to .NET 4.6.

**Comment by stephentoub** [comment]
> We discussed using reflection, but then to invoke it requires boxing the CancellationToken in the MethodInfo.Invoke() so it doesn't buy us anything.

Is cancellation the common case? You'd only be invoking this in the case of cancellation.

**Comment by jasonmalinowski** [comment]
It's fairly common. For Roslyn we're regularly starting tasks which then get cancelled when the next keypress comes in. I don't have exact numbers but it's not rare.

**Comment by stephentoub** [comment]
If we're concerned about the impact of two fields vs an allocation sometimes vs whatever other option, seems like some numbers would be useful to help make a decision?

**Comment by jasonmalinowski** [comment]
Fair enough, let me get some numbers. The other argument for AsyncTaskMethodBuilder is it's actually safe to use versus randomly changing our behavior. :smile:

**Comment by jasonmalinowski** [comment]
This is fixed.

**Comment by MattGertz** [comment]
Agree appears fixed -- can't repro it.
