### ISSUE TITLE
Add WithChanges to Solution, Project, Document.

### ISSUE THREAD

**Issue by malylemire1** [dotnet/roslyn#44747]
**Version Used**: Latest

**Steps to Reproduce**:
```

Solution oldSolution = workspace.CurrentSolution;

Document document = oldSolution.Projects.FirstOrDefault().Documents.FirstOrDefault();

Solution newSolution = oldSolution.WithDocumentName(document.Id, "Test");

//Update workspace using dte or manually.
//workspace.TryApplyChanges(newSolution) will fail since solution is modified.

//Be able to set changes to current solution.
newSolution = workspace.CurrentSolution.WithChanges(newSolution.GetChanges(workspace.CurrentSolution));

workspace.TryApplyChanges(newSolution);
```

**Expected Behavior**:

I should be able to apply changes to a modified solution.

**Actual Behavior**:

Cannot apply changes to a modified solution.

**Comment by CyrusNajmabadi** [comment]
This would need to go through an API proposal.  in general, the reason we don't just make things public is because it increases maintenance costs and locks down our ability to change things in teh future.  We can open things up, but we have a process that requests need to go through to make sure the appropriate people weigh in and the right API shape is determined and shipped.
