### ISSUE TITLE
Unexpected behaviour of static initializers. Should be at least compiler warning

### ISSUE THREAD

**Issue by ivankarpey** [dotnet/roslyn#44749]
**Version Used**: 
.NET Core 2.2
**Steps to Reproduce**:
```
    public class ContentItemConstants
    {
        public static ContentItem Item1 = _constantsCache[(int)FeedContentTypeEnum.Key1];

        public static ContentItem Item2 = _constantsCache[(int)FeedContentTypeEnum.Key2];

        private static readonly ContentItem[] _constantsCache = InitCache();

        private static ContentItem[] InitCache()
        {
            ContentItem[] cache = new ContentItem[Enum.GetValues(typeof(FeedContentTypeEnum)).Cast<int>().Max()];
           --- initialization ---
            return cache;
        }
    }
```
**Expected Behavior**:
`ContentItemConstants.Item1` return correct item from `_constantsCache` or at least compiler warning
**Actual Behavior**:
Failed with null reference exception

------

So I actually believe that the initialization of static fields happen consecutive. So I would expect to see a compiler warning for trying to use an uninitialized field.

**Comment by RikkiGibson** [comment]
This is by design in the language, but it feels like nullability analysis could catch this if we made a change to constructor analysis: instead of starting analysis using the declared type for all fields, give every reference type field a maybe-null initial state. Is this something that was considered and ruled out? @jcouv @agocke
