### ISSUE TITLE
Need to default to C# 9 when targeting net50

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#44756]
Need to change our language version defaults for C# based on the current target framework:

- `net5.0` and [all the variants](https://github.com/dotnet/designs/blob/master/accepted/2020/net5/net5.md#design) should map to 9.0
` net3.*` should map to 8.0 
- everything else should be 7.3

Relevant code section: https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/MSBuildTask/Microsoft.CSharp.Core.targets#L6

As a part of this change we should also add 9.0 into the supported C# language numbers.

**Comment by jcouv** [comment]
@chsienki I assume there is some work left aside from your compiler PR https://github.com/dotnet/roslyn/pull/44911. It may be good to keep track here.
For instance:
- update tests to use specific version instead of "preview"
- verify end-to-end, including IDE LangVer drop-down (not sure how it works nowadays, maybe project-system needs updating)

**Comment by chsienki** [comment]
Thanks @jcouv I already opened https://github.com/dotnet/roslyn/issues/44962 to track that info.
