### ISSUE TITLE
Build time > 10 minutes for a simple project when code analysis is on.

### ISSUE THREAD

**Issue by himalpatel81** [dotnet/roslyn#44777]
**Version Used**: 
Visual Studio Enterprise 2019
Version 16.4.5

**Steps to Reproduce**:

1. Clone the repository from following URL
[Code Analysis Build Issue Repro](https://github.com/himalpatel81/CodeAnalysisIssue)
2. Open the solution in Visual Studio and Compile.
3. Notice the build time. It will be more than 10 minutes. 

Change to the branch "withoutcodeanalysis" and compile. It would compile in couple of seconds. 

**Expected Behavior**:
It should compile the project in appropriate time. 
**Actual Behavior**:
It takes more than 10 minutes to build a single project with a single class and a single method.

**Comment by himalpatel81** [comment]
any updates on this issue please ?

**Comment by nbalakin** [comment]
I've done some measurements and the root cause of the issue is not the compiler but the analysers themselves. The data flow analysis takes all the time ([this method](https://github.com/dotnet/roslyn-analyzers/blob/master/src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/DataFlowAnalysis.cs#L35) with all its recursive paths).

You may try to create issue in [roslyn-analyzers](https://github.com/dotnet/roslyn-analyzers) repo.

**Comment by himalpatel81** [comment]
@nbalakin  Thank you!
Moved to [reslyn-analyzers](https://github.com/dotnet/roslyn-analyzers/issues/3738) repo.
