### ISSUE TITLE
Type alias intellisense incorrect when using multiple aliases for same type

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#44829]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1052892/type-alias-intellisense-incorrect-when-using-multi.html)._

---
With the following code:

```
using x = System.Int32;
using y = System.Int32;

namespace ClassLibrary1
{
    public class D 
    {
        public x GetX { get; set; }

public y GetY { get; set; }
    }
}

```

When hovering over the Property 'GetY' it displays 'x' as the return type in the intellisense popup. 

It should display 'y'.

---
#### Visual Studio Feedback System on 5/27/2020, 10:47 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Yes.  This has long been the design of the IDE, and a limitation/complexity of the compiler.  They expose the real type of the member, nothing about the alias.  We've held that if you have an alias, that's yoru way of saying "in the context of the file, this is the name we'd prefer to use rather than teh real type name."  We haven't found it to be a reasonable scenario to have multiple aliases to the same type, as that would seem to make things more confusing, so we made a design decision to just pick one of them and use that consistently.
