### ISSUE TITLE
"Change Signature" dialog forbids void as type but allows System.Void

### ISSUE THREAD

**Issue by jhinder** [dotnet/roslyn#44959]
**Version Used**: VS 16.7 P2

**Steps to Reproduce**:

1. Open the Change Signature dialog.
2. Try to add a parameter of type `void`. (This will fail: "Type name has a syntax error".)
3. Add a parameter of type `System.Void`.

**Expected Behavior**: System.Void is rejected and the parameter can't be added.

**Actual Behavior**: The parameter is accepted (and simplified to `void` in the main dialog), leading to syntax errors when the change is committed.

**Comment by CyrusNajmabadi** [comment]
It's unlikely this is causing a "syntax error" rather than a binding error.  It's likely not something really worth blocking though (just like we wouldn't block many other types that might lead to an eventual error).  If a user chooses this, we can just go ahead with teh change and the user can deal with the simple fallout
