### ISSUE TITLE
Change to definitive assignment in LINQ queries

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#4509]
The following code compiles on VS 2013 but fails in VS 2015 

```csharp
static void Main(string[] args)
{
    decimal a, b;
    IEnumerable<dynamic> array = new string[] { "10", "20", "30" };
    var result = (from v in array
                  where decimal.TryParse(v, out a) && decimal.TryParse("15", out b) && a <= b // Error here
                  orderby decimal.Parse(v)
                  select v).ToArray();
}
```

The resulting error is:

> Error CS0165 Use of unassigned local variable 'b'

This appears to be a bug in the definite assignment logic of the compiler.  

Original source: http://stackoverflow.com/questions/31961411/roslyn-failed-to-compile-code

**Comment by gafter** [comment]
The use of dynamic obscures what is going on. What is happening is that the compiler doesn’t know the semantics of && because it may be a user-defined operator. It is possible that the user-defined operators are defined in a way that b is not actually definitely assigned in a<=b.

The following program demonstrates how b could be “not definitely assigned” in an expression of that form. That suggests this might be a bug in the C# 5 compiler.

On the other hand, when dynamic is used both operands of && are evaluated (the compiler does not know to short-circuit until it knows that both operands are of type X). That suggests this might be a bug in the C# 6 compiler.

I'll have to investigate the specification for the evaluation of dynamic expressions in the presence of overloading very carefully to sort this out.

```cs
using System;

namespace ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            int a;
            int b = 100; // if you delete "= 100" the program will not compile
            if (X.M(1, out a) && X.M(2, out b) && Nop(a <= b)) { }
        }

        public static bool Nop(bool b)
        {
            Console.WriteLine($"Nop({b})");
            return b;
        }
    }
}

public class X
{
    public static X M(int x, out int y) {
        Console.WriteLine(x);
        y = x;
        return new X();
    }

    public static bool operator false(X x) { return true; }
    public static bool operator true(X x) { return true; }
    public static X operator &(X a, X b) { return new X(); }
    public static implicit operator bool(X x) { return true; }
}
```

**Comment by rawling** [comment]
Given that `int.TryParse` can only return `bool` even when called with a `dynamic` argument, *should* the compiler worry about `&&` being something other than the `bool` version?

**Comment by jskeet** [comment]
I don't understand why that code doesn't compile without the initial assignment, to be honest.

From 5.3.3.24 (C# 5 spec; I assume this hasn't changed in the C# 6 spec)

> Otherwise, if the state of v after expr-second is definitely assigned or “definitely assigned after true expression”, then the state of v after expr is “definitely assigned after true expression”.

So considering the first expression (`X.M(1, out a) && X.M(2, out b)`), the state of `b` after `X.M(2, out b)` is definitely assigned, therefore the state of `b` after `expr` should be "definitely assigned after true expression". (I don't *think* the earlier rules in the list match.)

Now if we think about `expr1 && Nop(a <= b)` - where `expr1` is the first expression, we then use an earlier rule:

> The definite assignment state of v before expr-second is definitely assigned if the state of v after expr-first is either definitely assigned or “definitely assigned after true expression”. Otherwise, it is not definitely assigned.

By the earlier logic, the definite assignment state of `b` after `expr1` is definitely assigned after true expression, therefore the definite assignment state of `b` before `Nop(a <= b)` is definitely assigned.

This clause doesn't say anything about the types involved, so I don't currently see how your example using custom types and operator overloads change things.

I suspect I'm missing something though, and I'll look forward to being schooled :)

**Comment by rawling** [comment]
Jon, I was about to post the same thing. I believe the `X` example is another bug in the C#6 compiler, this time not involving `dynamic`.

I also disagree with *when dynamic is used both operands of && are evaluated (the compiler does not know to short-circuit until it knows that both operands are of type X)* - `&&` *always* short circuits if the first argument is falsy, no?

**Comment by gafter** [comment]
@jskeet If we followed those rules we would indeed allow reading of an unassigned variable `b` in the above code. Section 5.3.3.24 should only apply to the *built-in* operator &&. The user-defined versions should be treated according to the translation scheme they are defined by. When `dynamic` is used, the compiler cannot know which it is and must be pessimistic.

The spec could be more clear about all this.

**Comment by rawling** [comment]
In the `X` example, were it to compile with `b` unassigned:

- `X.M(1, out a)`  returns a `new X`
- `X.false(new X())` is `true`, so `new X() && X.M(2, out b)` evaluates as the `new X()` without evaluating the `X.M(...)`
- `X.false(new X())` is `true`, so `new X() && Nop(a <= b)` evaluates as the `new X()` without evaluating `b`

I don't see the unassigned variable reading here.

**Comment by gafter** [comment]
@rawling Re your comment

> `&&` always short circuits, and just returns the first argument, if the first argument is falsy, no?

It would be useful to find that in the specification somewhere, but that doesn't appear to be the way the runtime behaves. As you can see by this example, the concept of being *falsy* would need to be nailed down very carefully; my type `X` below is both *falsy* and *truey* :wink: 

```cs
using System;
using System.Threading.Tasks;

namespace ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            int a, b = 100;
            dynamic one = 1;
            dynamic two = 2;
            if (X.M(one, out a) && X.M(two, out b) && Nop(a < b)) { }
        }

        public static bool Nop(bool b)
        {
            Console.WriteLine($"Nop({b})");
            return b;
        }
    }
}

public class X
{
    public static X M(int x, out int y) {
        Console.WriteLine($"M({x})");
        y = x;
        return new X();
    }

    public static bool operator false(X x)
    {
        Console.WriteLine($"operator false(X)");
        return true;
    }

    public static bool operator true(X x)
    {
        Console.WriteLine($"operator true(X)");
        return true;
    }

    public static X operator &(X a, X b)
    {
        Console.WriteLine($"operator &(X, X)");
        return new X();
    }

    public static implicit operator bool (X x)
    {
        Console.WriteLine($"implicit operator bool(X)");
        return true;
    }
}
```

**Comment by gafter** [comment]
> In the `X` example, were it to compile with `b` unassigned:
> 
> - `X.M(1, out a)`  returns a `new X`
- `X.false(new X())` is `true`, so `new X() && X.M(2, out b)` evaluates as the `new X()` without evaluating the `X.M(...)`
- `X.false(new X())` is `true`, so `new X() && Nop(a <= b)` evaluates as the `new X()` without evaluating `b`
> 
> I don't see the unassigned variable reading here.

You don't use `X.false` to evaluate the second `&&`. That is an ordinary `bool &&` So we convert its left-hand-side to `bool` using the implicit conversion. That  returns `true`, not `false`.

**Comment by jskeet** [comment]
Ah, I see. (I was slightly confused by user error in not actually running your code properly first time - I didn't see Nop being executed.)

@rawling: The *second* `&&` is a normal `&&` between two `bool` expressions - because `Nop` returns `bool`, and there's no `&(X, bool)` operator... but there *is* a conversion from `X` to `bool`.

**Comment by rawling** [comment]
Thanks guys, I take your points.

I dislike that that the dynamic binder has to evaluate the second argument before it can decide whether it needs to evaluate the second argument... :+1:

**Comment by jskeet** [comment]
@rawling: That's already a Stack Overflow question in its own right... see http://stackoverflow.com/questions/27508991

**Comment by rawling** [comment]
@jskeet Cheers Jon, that's exactly the issue I was wrestling with. And I think it's about to raise another SO question, since I don't want to pull this thread any more off-topic :)

**Comment by gafter** [comment]
See also http://stackoverflow.com/a/16307237

**Comment by gafter** [comment]
OK, since the dynamic binder has to evaluate the second argument (even if it then discovers that it didn't need to do so), the definite assignment rules can be adjusted to assume the second argument was evaluated. Preparing a PR.

**Comment by rawling** [comment]
@gafter Apologies if I'm being dense again, but from my experimenting with the dynamic binder last night it doesn't evaluate the second argument just to see whether there's a user-defined operation to use - if the first argument is implicitly convertible to `bool` and the value is `false` (for `&&`), it just returns the first argument.

**Comment by gafter** [comment]
@rawling Indeed, I am just running into that myself. Given that, I believe the current behavior may be correct (and the Roslyn compiler should continue producing the diagnostic reported in this issue). When the left-hand operand of a `&&` expression is `dynamic`, the compiler cannot know whether or not the right-hand operand will be evaluated; even when the second operand isn't evaluated the resulting value can waffle between being *truey* and *falsey* -- the third operand of a `&&` might be evaluated even if the second isn't.

Admittedly it would take a twisted example to make that happen, but the definite assignment rules need to protect against the strangest of circumstances.

**Comment by gafter** [comment]
@jaredpar I think this incompatibility is unavoidable. The compiler-reported diagnostic represents a possible (twisted and unlikely) circumstance in which the variable is actually not assigned. I propose to document the incompatibility and close the issue.

**Comment by jaredpar** [comment]
@gafter can we produce such a twisted sample to hold up as why we need to make this compat change?  :smile_cat:

**Comment by gafter** [comment]
Sure.

**Comment by gafter** [comment]
The following program, written in honor of @VladimirReshetnikov, demonstrates that fixing this issue would introduce a situation in which the compiler would allow reading an uninitialized variable.

```cs
using System;

namespace ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            string val = "unassigned";
            if (Api1() && Api2(out val) && UseVal(val))
            {
                Console.WriteLine(val);
            }
        }

        static dynamic Api1()
        {
            return new Waffle();
        }

        static bool Api2(out string val)
        {
            Console.WriteLine("Assigning to val");
            val = "assigned";
            return true;
        }

        static dynamic UseVal(string val)
        {
            Console.WriteLine($"Using val == {val}");
            return true;
        }
    }

    class Waffle
    {
        int count = 0;
        public static implicit operator bool(Waffle w)
        {
            try
            {
                return w.count != 0;
            }
            finally
            {
                w.count++;
            }
        }
    }
}
```

The output of this program is

```none
Using val == unassigned
unassigned
```

Because of this possibility the compiler must not allow this program to be compiled if `val` has no initial value.

**Comment by jaredpar** [comment]
@gafter thank you.  That is indeed twisted :smile:

**Comment by rawling** [comment]
Sorry to dredge this up again.

Is there not (also?) an issue with the dynamic runtime here?

Having decided that as the reuslt of `Api1()` is implicitly convertible to `false` there is no need to evaluate `Api2()` in order to evaluate the first `&&`, should the result not be `false` rather than a `Waffle` instance?

In the static binder, the first `&&` is known to be a `bool&&` and so the result is a `bool`. Having decided that the first `&&` is a `bool&&`, should the dynamic runtime not pass a `bool` result onwards?

**Comment by gafter** [comment]
@rawling The dynamic runtime needs the arguments to decide what kind of operator is being used (it might be an error, not binding to any built-in or user-defined operator), and the only way to get them is to evaluate them.

**Comment by rawling** [comment]
@gafter Sorry, I'm referring to your Waffles example above where the second argument (call to Api2) is not dynamically typed and, according to the sample output, is not called.

But I'm not concerned about whether the second argument is evaluated or not; once the dynamic runtime has established that the && being called is the bool one, shouldn't it produce a bool result rather than what appears to be a Waffle that goes on to be reevaluated?

**Comment by gafter** [comment]
@rawling No, that is not the way that `&&` works in the presence of user-defined operator overloading. See 7.12.2:

> 7.12.2 User-defined conditional logical operators
When the operands of && or || are of types that declare an applicable user-defined operator & or operator |, both of the following must be true, where T is the type in which the selected operator is declared:
•	The return type and the type of each parameter of the selected operator must be T. In other words, the operator must compute the logical AND or the logical OR of two operands of type T, and must return a result of type T.
•	T must contain declarations of operator true and operator false.
A binding-time error occurs if either of these requirements is not satisfied. Otherwise, the && or || operation is evaluated by combining the user-defined operator true or operator false with the selected user-defined operator:
•	The operation x && y is evaluated as T.false(x) ? x : T.&(x, y), where T.false(x) is an invocation of the operator false declared in T, and T.&(x, y) is an invocation of the selected operator &. In other words, x is first evaluated and operator false is invoked on the result to determine if x is definitely false. Then, if x is definitely false, the result of the operation is the value previously computed for x. Otherwise, y is evaluated, and the selected operator & is invoked on the value previously computed for x and the value computed for y to produce the result of the operation.

**Comment by rawling** [comment]
@gafter I'm referring to [the `Waffle` example above](https://github.com/dotnet/roslyn/issues/4509#issuecomment-130872713) which only has a `bool` conversion, not a user-defined `&&`.

**Comment by gafter** [comment]
@rawling Are you interested in working on a specification (and perhaps reimplementation) of the dynamic binder for operator overloading? I think the dynamic binder is now open-source. If you are interested perhaps you can propose to change it to behave as you prefer.

**Comment by rawling** [comment]
@gafter Oh fair enough, I assumed Roslyn included the dynamic binder but if not I'll stop bothering you with dynamic binder questions!
