### ISSUE TITLE
Expose SyntaxFactory.AreEquivalent from SyntaxTree

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#45196]
We already have `SyntaxTree.IsEquivalentTo` but it only works for syntax trees themselves.

With an API such as `SyntaxTree.AreEquivalent(SyntaxNode, SyntaxNode)`, given an `IOperation` we can perform language-agnostic syntax operations as well.

**Comment by jinujoseph** [comment]
cc @333fred @mavasani

**Comment by CyrusNajmabadi** [comment]
This would need to go through an API proposal.  in general, the reason we don't just make things public is because it increases maintenance costs and locks down our ability to change things in teh future.  We can open things up, but we have a process that requests need to go through to make sure the appropriate people weigh in and the right API shape is determined and shipped.
