### ISSUE TITLE
InvocationExpressionSyntax.WithArgumentList adds list after TrailingTrivia

### ISSUE THREAD

**Issue by NiKiZe** [dotnet/roslyn#45221]
Only other maybe related mention of this is in #41923, but that is just a guess
This might also be totally correct, just odd to me

**Version Used**: 
.NET 4.7.1

**Steps to Reproduce**:

1. Get a `InvocationExpressionSyntax` instance for `SubName` from this VB code
```VB.NET
Public Sub SubName()
    SubName  ' recursive call
End Sub
```
2. This should have a `.GetText()` of: `"        SubName  ' recursive call\r\n"`
3. Àdd an empty ArgumentList: `invocationNode.WithArgumentList(SyntaxFactory.ArgumentList());`
4. Check resulting `.GetText()`

ArgumentList ends up after TrailingTrivia, (and there is no TrailingTrivia in the resulting node)

**Expected Behavior**:
`"        SubName()  ' recursive call\r\n"`
Expected TrailingTrivia to be on InvocationExpressionSyntax
**Actual Behavior**:
`"        SubName  ' recursive call\r\n()"`
InvocationExpressionSyntax.Expression has TrailingTrivia, and ArgumentList is added after that trivia

Trying to use this in a codefix gives incorrect code, but maybe there is other issues in this function.

**Comment by CyrusNajmabadi** [comment]
This is by design.  The 'With' methods do exactly one thing, they update the existing child node with the node you specified.  SO, in this case, the existing invocation points at an expression `SubName ' recursive call` and no arg list.  When you add the arg list, it only updates the arglist portion of the node, it doesn't touch anything else.

If you want trivia to move, that's something to take care of in your own code.

**Comment by NiKiZe** [comment]
I havily dissagre, but ok thanks.

**Comment by NiKiZe** [comment]
You are saying that everyone needs to handle trivia on their own, and you do realize that very few will actually create testcases that has trivia in them, and that will cause a number of bugs when fixes are applied to code with trivia.

Also I have not seen any documentation, or examples where this is done, you need to work on that part.

**Comment by CyrusNajmabadi** [comment]
> You are saying that everyone needs to handle trivia on their own,

I'm saying that the syntax API does no processing of this sort.  It is outside of its domain.  It is similar to a low-level data structure API.  If you have a list and you say you want to add a value to it, it adds it at the end always.  It doesn't attempt to look at the items in the list to decide that sometimes it will, in fact, not add it at the end :)

Our syntax is a raw, *concrete*, tree.  It does not convey anything beyond a structured model of code that represents every character in a completely consistent manner.  We don't put in 'smarts' in this layer because it means that any higher level layer now has to understand all those smarts and not get thrown off by how all the different parts might behave differently.  We actually had a model at one point that *did* try to be smart, and it turned out to be almost impossible to use effectively because no one was ever sure what any particular manipulation of it would do.  Similarly, any tweak or revision in behavior could potentially break vast swaths of consumers.

Based on this, we went ot a model that is completely simple and consistent.  Specifically, all this is a simple concrete-syntax-tree model with no interpretation around any sort of behavior.  When you ask to do something, *precisely* that single thing is done.  No more, no less.  This means clients can always trust that given a particular input tree , they will know exactly what output tree they should expect based on their calls.

This has already borne itself out over the lifetime of Roslyn as producing *far* less confusion and difficulty for clients than our previous 'smart' system had.

**Comment by CyrusNajmabadi** [comment]
> Also I have not seen any documentation, or examples where this is done, you need to work on that part.

Effectively, the tree is just a tree.  We describe Nodes/Tokens/Trivia in several documents.  You can then manipulate those producing new trees however you want.  i.e. we leave it to you to decide what you would think is best in a particular scenario.  For some domains this would be taking trivia like that and keeping it where it it.  For others it might be moving it *after* the node that was added.  For others it might be removing the trivia and placing *before* the statement containing the node being updated.   etc. etc.  

In general, the recommendatation is simply:

Take the 'before' code and look at it in some sort of syntax visualizer.   Then take your desired 'after' code and do the same. You will easily be able to see the structure of both trees, and can then fairly trivially (no pun intended) figure out what operations to perform on the former to transform it to the latter.

Cheers!

--

Also: if you need any help with this, we have several community channels that are useful for asking questions and engaging with other roslyn devs and team members.  I recommend gitter.im/dotnet/roslyn and discord.gg/csharp (#roslyn channel).  Good luck! :)
