### ISSUE TITLE
Casts between integral types that can change values shouldn't be marked as redundant

### ISSUE THREAD

**Issue by NN---** [dotnet/roslyn#4531]
```cs
using System.Net;

namespace ConsoleApplication124
{
	class Program
	{
		static void Main(string[] args)
		{
			int addr=1;
			int port=2;
			var ep = new IPEndPoint(addr, (ushort)IPAddress.NetworkToHostOrder((short)port));
		}
	}
}
```

In this simple code the (ushort) cast is a must.
Otherwise it is possible to get a negative port number which is incorrect port number.

Visual Studio 2015 suggests removing this (ushort) cast.

**Comment by Pilchie** [comment]
Unfortunately, given the way those APIs are designed, there is no way for the IDE to know that the cast is redundant.  The `IPEndPoint` constructor says that it accepts all integers.  The IDE has no concept of ports, or what their valid values are.

**Comment by dpoeschl** [comment]
@Pilchie Right, but we *do* know that casting a ```short``` to a ```ushort``` can change its value (in a way that casting a ```short``` to an ```int``` cannot), regardless of the larger context (in this case, that it's eventually interpreted as an ```int``` by the receiving method). Maybe building in this understanding of the relationships between primitive types would be worthwhile. Marking this cast as redundant feels wrong, since we *definitely* know that the cast can change the value on some set of legal values.

**Comment by Pilchie** [comment]
Good point.

**Comment by dpoeschl** [comment]
(Removed milestone to ensure this gets re-triaged and an assignee)

**Comment by DustinCampbell** [comment]
Hmmm... I remember doing this at one point. Maybe something was missed?

**Comment by DustinCampbell** [comment]
It looks like we used to be more conservative and leave all explicit numeric casts. However, the check was loosened some point to only leave explicit numeric casts in checked/unchecked contexts. This isn't right.

**Comment by DustinCampbell** [comment]
PR #4643 is now open to address this.
