### ISSUE TITLE
Visual C# Compiler Should Not Fail with /keycontainer Option If Key Container Is User Based

### ISSUE THREAD

**Issue by Petr-Alexeev** [dotnet/roslyn#4533]
Visual C# Compiler 1.0.0.50618 is not able to fetch key pair from strong name key container with /keycontainer option if the key container is user based. Steps to reproduce (using Developer Command Prompt for VS2015).

<ol>
<li>Configure key containers to be user based. Run the following command with administrative privileges:
<pre>sn -m n</pre>
</li>
<li>Create a key pair and install it to a container as follows:<br/>
<pre>sn -k KeyPair.snk
sn -i KeyPair.snk Container123</pre>
</li>
<li>Create a conapp.cs file for dummy compilation with the following content:
<pre>
using System;
class ConsoleApp
{
  public static void Main(string[] args)
  {
    Console.WriteLine("Hello world!");
  }
}
</pre>
</li>
<li>Create strong named assembly from the file using the /keycontainer compiler option:
<pre>
csc conapp.cs /keycontainer:Container123
</pre>
</li>
</ol>

Expected result: The assembly created without errors.
Actual result: Compiler fails to create an assembly with the following error message:
```
error CS7028: Error signing output with public key from container 'Container123'
 -- Keyset does not exist (Exception from HRESULT: 0x80090016)
```
Using of csc 12.0.31101.0 (using Developer Command Prompt for VS2013) with the same option for the same file of source code is successful.

It seems like Visual C# Compiler 1.0.0.50618 always tries to fetch key pair from a machine container even if key containers are configured to be user based. For example, if command ```sn -m n``` at the first step will be replaced with ```sn -m y``` (to configure key containers to be machine based), than the described problem does not reproduce.

**Comment by VSadov** [comment]
This is ByDesign. 

New compilers are built for neutral platform and typically run as 64bit processes on 64bit capable OS. That is really depends on how they are launched, but typically it is 64bit.

There are 32bit and 64bit flavors of sn.exe. The default VS command prompt will use 32bit one, and 64bit command prompt will use 64bit one. 

On my machine they are:
Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\sn.exe
Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\x64\sn.exe

If you expect running compiler in 64bit, you need to use 64bit sn.
I'd just run the same command through both to be sure.

Note that 64bit flavor of the the native compiler also exists. It is just not often used. Otherwise it will be affected by the same issue.
That is just because 32bit and 64bit subsystems can be configured separately.
