### ISSUE TITLE
AD0001 in CSharpRemoveUnnecessarySuppressionsDiagnosticAnalyzer

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#45465]
> Starting with Visual Studio 2019 version 16.7 Preview 2, a new analyzer ([dotnet/roslyn#44287](https://github.com/dotnet/roslyn/pull/44287)) will report cases where the target of a global suppression cannot be found. The first thing I would try is opening the solution in this version and looking for reports of IDE0076 in GlobalSuppressions.cs.

That helps. I can see 13 warnings raised by `IDE0076` analyzer when I opened the solution in VS 2019 Int Preview (16.7 Preview 4). I found around 35 additional errors from `AD0001` analyzer. please see attachment for errors with stack trace. Looks like an issue in `IDE0076 and IDE0077` analyzers.
[AD0001 errors.txt](https://github.com/dotnet/roslyn-analyzers/files/4833849/AD0001.errors.txt)

_Originally posted by @kartheekp-ms in https://github.com/dotnet/roslyn-analyzers/issues/3587#issuecomment-649823987_

**Comment by VitaliySmolyakov** [comment]
Thanks for fixing that. But why it's still not released?! Who is deciding in which version to release it? So frustrating...

**Comment by mavasani** [comment]
This should be available in latest 16.8 Preview builds and soon in 16.8 release build, when released.

**Comment by CyrusNajmabadi** [comment]
> But why it's still not released?! 

After we fix an issue, the code flows into the next release of VS.

> Who is deciding in which version to release it? So frustrating...

Only super critical issues get preemptive patches to address this.  These have to be issues like "vs crashes on start" where the product is literally fully non-functional.  In this case the product is functional, albeit with an annoying bug.  So that will be provided on the normal release cadence for VS.  Thanks!
