### ISSUE TITLE
Type assigned to var should not be nullable when expression ends in !

### ISSUE THREAD

**Issue by lostmsu** [dotnet/roslyn#45462]
I am unsure if this is a bug in Roslyn, or an issue with the spec. See sample:

```csharp
Type? TryGet() => ... ;

var type = TryGet()!; // note exclamation mark
Trace.Assert(type != null); // this line is necessary
Console.WriteLine(type.Name); // <- ⚠ CS8602: Dereference of a possibly null reference.

var noNullCheckLater = TryGet()!; // no warnings
Console.WriteLine(explicitType.Name); // no warnings
```

**Comment by lostmsu** [comment]
@HaloFour I am using .NET SDK 3.1.301.

Actually, updated the repro in the report. With my SDK `Debug.Assert(type != null);` is enough to generate the warning. In SharpLab I had to replace it with `bool v = type != null;`

**Comment by theunrepentantgeek** [comment]
In C#9, **var** is [always nullable](https://github.com/dotnet/csharplang/issues/3591#issuecomment-647062087):

> the language team has decided to always treat var as nullable and to rely on flow analysis to determine when to warn. 

See also [C# Language Design Meeting for Dec. 18, 2019](https://github.com/dotnet/csharplang/blob/master/meetings/2019/LDM-2019-12-18.md#var)

In your example, `Trace.Assert()` is annotated with `[Conditional("TRACE")]` which I believe means that nullability analysis won't use it to conclude that the value cannot be null because the method won't always be there.

**Comment by lostmsu** [comment]
@theunrepentantgeek you don't have to `Trace.Assert`, it can be replaced with `bool notNull = type != null;` for the same effect.

What I don't understand is: there is only 1 assignment, and using bang the value should be treated as non-null. Why the subsequent access thinks it might be, but only if there's a comparison to `null` before it?

**Comment by gafter** [comment]
If you explicitly compare a value to null, we take that to mean that you think the value might have been null, and we use that information in inference. That is by design.
