### ISSUE TITLE
Design: Should previous evaluations be able to continue to write output to the console

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#4554]
Right now, our design allows for a submission that kicks off a background thread that continues to write output to the console after the next prompt has appeared.  This functionality seems unconventional (in the sense that I've never seen a REPL behave that way), it has a non-trivial implementation cost, and it is untested, so I thought we should discuss what experience we would like to have before we invest further.

**Comment by amcasey** [comment]
FYI @ManishJayaswal @kuhlenh @tmat

**Comment by tmat** [comment]
+@DinoV 
I believe we should keep the functionality. A lot of functionality is not completely tested. And our REPL certainly goes beyond what other REPLs do - like supporting the full editor experience, for example. That's what makes it the best :)

**Comment by MgSam** [comment]
> This functionality seems unconventional (in the sense that I've never seen a REPL behave that way)

Open the JavaScript console in any browser (tested in IE and Chrome) and type
``` JavaScript
var i = 0; setInterval(function(){console.log(i++)}, 1000);
```

To me it seems pretty normal to have something asynchronous write to the console.

**Comment by ManishJayaswal** [comment]
@tmat  what is the user scenario where this would be useful?

**Comment by DinoV** [comment]
MgSam gave one example of this being standard, here's a couple more.  Python is of course multi-threaded, so I can have writes that are coming out of some asynchronous code.  I think an interesting example is what happens when I have an unhandled exception on a background thread, I don't want that to just be swallowed, I want to see that in some manner:

```
>>> def f():
...     raise Exception()
...
>>> import thread
>>> thread.start_new_thread(f, ())
23052
Unhandled exception in thread started by <>>>
>>>
```

You can also imagine the same thing in Node.js:

```
> fs.readFile('C:\\foo.txt', function() { throw 'something went wrong!'; })
undefined
> something went wrong!
>
```

The big difference between our support for this and a traditional REPL is that we actually write the output before the prompt to maintain a nice output stream, which IMO is a nice improvement.  Beyond these rather critical error cases I also think people just generally expect to see the output that their program produced, even if it's happening on the background.  If you completely suppress the output then people are just going to file bugs and say it's broken.

But I'd like to reframe the question here...  Currently it's "Should previous evaluations" be able to do this...  My immediate response is how do you suppress only previous evaluations?  I think the real question might be "Should we allow writes while waiting for an input?"  Otherwise you need to somehow understand the context of asynchronous operations which were triggered by a previous evaluation.  If you don't do this then you're going to end up with a really wonky model as far as the user is concerned.  They'll see outputs which occur while their code is executing, including asynchronous outputs, but they won't see them when sitting at the prompt.  Swallowing some output but not others is going get confusing.

Maybe an argument exists that we should just buffer the output instead of swallowing.  But that's going to lead to users needing to write no-op statements to check if things happened, or seeing a stream of unrelated output when they do their next execution.

Also, I think it's worth pointing out that with our implementation consumers of the REPL can get whatever behavior they want.  If they want to support background outputs they basically do nothing.  If they want to buffer the outputs until the next execution they hold onto them and display them before the next time they execute text.  And if they want to suppress them they just don't do any writes when they're not actively executing code.  Removing this feature means that consumers of the REPL window may find it inadequate for their purposes, and there's no workaround other then re-implementing the entire thing.

**Comment by amcasey** [comment]
I'm sold.  I just wanted to make sure we'd built it intentionally and with a customer scenario in mind, rather than because we could.

If we're going to make this a first class scenario, we'll definitely need to increase our test coverage and audit our thread safety (#4044).

**Comment by amcasey** [comment]
We've audited (and fixed) the threading behavior, but we'll definitely want to add some test coverage when we add standard input support to our host.
