### ISSUE TITLE
Consider hiding nullability differences in PEModuleBuilder.Translate() 

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#45758]
A couple of recent PRs have changed `MetadataWriter` to accommodate type references that differ only by nullability: https://github.com/dotnet/roslyn/pull/38249 and https://github.com/dotnet/roslyn/pull/45714.

Since nullability is not persisted as part of the type reference, an alternative suggested by @AlekseyTs to changing `MetadataWriter` might be to hide nullability differences in `PEModuleBuilder.Translate()`.

For instance, the following change to `PEModuleBuilder.Translate()` seems to work as an alternative to https://github.com/dotnet/roslyn/pull/45714.

```C#
internal Cci.INamedTypeReference Translate(
    NamedTypeSymbol namedTypeSymbol,
    SyntaxNode syntaxNodeOpt,
    DiagnosticBag diagnostics,
    bool fromImplements = false,
    bool needDeclaration = false)
{
    Debug.Assert(namedTypeSymbol.IsDefinitionOrDistinct());
    Debug.Assert(diagnostics != null);

    // If the only differences between the type and OriginalDefinition is nullability, use
    // OriginalDefinition because nullability is not persisted as part of the type reference.
    if (!namedTypeSymbol.IsDefinition)
    {
        var definition = namedTypeSymbol.OriginalDefinition;
        if (namedTypeSymbol.Equals(definition, TypeCompareKind.AllNullableIgnoreOptions))
        {
            namedTypeSymbol = definition;
        }
    }

    // ...
```

See also related issue https://github.com/dotnet/roslyn/pull/40271 translating [native integers](https://github.com/dotnet/roslyn/commit/f22ad6e4b43b0c0495989e74d6f764cb456727dc#diff-3e769ab816ce69b4ac1b52b10107fb26).

**Comment by AlekseyTs** [comment]
After some additional investigation, I am thinking that metadata generation layer shouldn't be using Object.Equals method on instances of Cci interfaces provided by compilers. Whether it does that explicitly or implicitly by using collections , etc. Often we are simply passing symbols as is, but equality of symbols (whatever TypeCompareKind is used by default) isn't really suitable for metadata generation purposes. We simply never considered that as a requirement for equality implementation, especially that hierarchies aren't aligned. For example, a reference to a generic type and a generic type definition are represented by the same symbol in compiler layer, but should be represented by separate, unequal Cci entities in order for metadata generation to work properly. That is exactly where nullability is causing problems. If ignored (which is done by default equality), a constructed type symbol (i.e. a reference) can be equal to a type definition symbol.
It looks like majority of components involved would work just fine if reference equality is used instead of Object.Equals. For example, https://github.com/dotnet/roslyn/pull/48106 is a PR that uses reference equality approach as an alternative to fixes applied in the two PRs mentioned above. It passed all existing compiler tests. Alternatively, we could add a special interface, or, perhaps, implement ```IEquatable<IReference>``` and make sure that that implementation is used for equality purposes by metadata generation layer. With either approach, I think that for debug build we should create wrappers around all symbols (i.e. never pass symbols directly to metadata generation layer, and not implement Cci interfaces directly on symbols) and throw from overrides of Object.Equals for the wrappers. That will make sure that default equality is never used and, as an additional benefit, ensure that all symbols go through proper translation process.
