### ISSUE TITLE
auto completion issue

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#45782]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1047062/auto-completion-issue.html)._

---
[regression] [worked-in:upgrading to 16.6.0]
The proposed label and the orderlist of the auto completion is most of the time wrong.
The auto completion does not take into account the type to assign.
For example (this is only one example the auto completion was doing corerctly and is not doing correctly anymore)

```csharp
DateTime MessagePosted = DateTime.MaxValue;

private System.Windows.Forms.ToolStripStatusLabel dateTimeLabel;

private void OnEverySecond( object sender , EventArgs e )
{
	if( DateTime.Now.Second == 0 )
		dateTimeLabel.Text = $"{DateTime.Now:dddd dd MMMM yyyy @ HH:mm}";

	lock( statusLabel )
	if( MessagePosted >= DateTime.Now )
	{
		statusLabel.Text = "Ready";
		statusLabel.ForeColor = SystemColors.ControlText;
		MessagePosted = <try auto completion here expecting  DateTime after enterring 'dat' will wrongly propose dateTimeLabel
	}
}
```
Assign object proparties when cloning... most of the proposed values are wrong.

Hope this helps,

Regards,

C. Hannosset

---
#### Feedback Bot on 5/25/2020, 02:42 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 5/26/2020, 01:44 PM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by genlu** [comment]
We made an attempt to address this issue in https://github.com/dotnet/roslyn/pull/55562. However, based on the user feedbacks we received, that behavior caused other problems and was reverted as a part of https://github.com/dotnet/roslyn/pull/63985. Now we believe case sensitivity should be preferred over type. 

The issue described in the example above could be easily avoided by typing "D" instead of "d", as we would choose items of matching type when they have similar text match (i.e. case-sensitive prefix). Additionally, we also have a "target-type match" filter you can use (shortcut ALT-j, see the bottom right filter button in screenshot below, the support for enums shown is added in https://github.com/dotnet/roslyn/pull/64477)

![image](https://user-images.githubusercontent.com/788783/193912384-c90b479d-6450-4971-8e74-dd245ab0e8c5.png)
