### ISSUE TITLE
Build fails with CS0263 when a partial class derived from a generic type is defined across different nullable contexts

### ISSUE THREAD

**Issue by hamzasood** [dotnet/roslyn#45960]
Related to #38560

**Version Used**: 
version 3.8.0-dev (\<developer build\>)
(Built from master a few minutes ago)

**Steps to Reproduce**:

Compile the following code:

    class Base<T> { }

    #nullable enable
    partial class Derived : Base<object> { }
    #nullable disable
    partial class Derived : Base<object> { }

**Expected Behavior**:

The build should probably succeed. I've ran into this issue in a WPF project with nullable enabled (although the above code shows that this isn't a WPF issue). Code generated from xaml files is marked as `auto-generated` and is therefore has nullable disabled, which means that you can't use xaml for classes with a generic base class (which unfortunately is quite common with `ReactiveUI`, e.g. `ReactiveWindow<ViewModel>`).

**Actual Behavior**:

`<file>(4,15): error CS0263: Partial declarations of 'Derived' must not specify different base classes`

I've also tried changing the base declaration to `Base<object?>` in the nullable enable block, but that still gives the same error.

**Comment by captainsafia** [comment]
@jinujoseph Has this issue been triaged already?

It's showing up in https://github.com/dotnet/aspnetcore/issues/30531 and other issues in Razor.

**Comment by CyrusNajmabadi** [comment]
this is not an IDE issue.  Tagging @jaredpar  instead.

**Comment by RikkiGibson** [comment]
If the base type differs across partial declarations, the compiler needs to determine a single type to actually use for the partial type symbol's base type. We seem to have some prior art with interfaces in partial declarations: [SharpLab](https://sharplab.io/#v2:CYLg1APgxAdgrgGwQQwEYIKYAIMzZgWAChiA3ZAJywGMsBeLGDAdywGEAKASgG5iBJADwABAIwAGAPwA+LAEt6NPiSLCAzPJgAXDBQBmyatiEAVWQG8sAX2LF1WAA6Utc5AizCATOywgsQsXELa1siWEQUdGxgOQBnfAxQ+ycKFzcPbzZiLBzffxEJWQB6IpoAewBbCtwtLC0ACzisMrharTKsAHMMWuRGFixmShg5GE7s3MsbIiA===)

```cs
#nullable enable

var c = new C();
I<string?> i = c; // no warning

public interface I<T> { }

public partial class C : I<string> { }

#nullable disable

public partial class C
    : I<string> // comment this out to get a new warning
    { }
```

Also note that a "non-oblivious" difference such as `I<string>` and `I<string?>` in `#nullable enable` context results in a warning.
Essentially, the presence of a nullable disabled "version" of the interface clause causes the oblivious types to "win" over the nullable aware types. I don't know whether this was part of a deliberate design or if it occurred incidentally to solving a different bug. @jcouv in case he is able to weigh in.

It seems like code generators can reasonably sidestep this problem by avoiding specifying base classes or interfaces that another declaration has already specified. It also sounds like Razor team has a workaround for the time being, so I will put this bug in a post-17.0 milestone.

**Comment by AlgorithmsAreCool** [comment]
I just ran into this but with a twist.

My project has some WCF generated models and interfaces. We extend some of those in a separate file with human written partials with some hooks and other logging.

The declared signatures or the partial implementations are identical. When we enabled nullable in this project today, the build broke with CS0263. It didn't make any sense because the declarations were identical, there are no `#nullable` directives anywhere.

I think it is due to this:

https://github.com/dotnet/roslyn/blob/ba75cb8c43275d935110cb4138f7bc68a75c2957/src/Compilers/CSharp/Portable/Compilation/CSharpSemanticModel.cs#L5284-L5286 

If your code has a `GeneratedCodeAttribute` attribute, Roslyn will treat it is as `#nullable disable` even if it is in a otherwise nullable project.

We have worked around it by placing `#nullable disable` in the human files and the error went away. 

Posting this incase anyone else trips on this headscratcher.

P.S. What a wonderful thing open source is, there is ZERO chance I could have produced any theory on what was happening without the compiler source. Instead I had a fix in 30 mins.

**Comment by RikkiGibson** [comment]
It looks like the docs do a decent job of calling this out: https://docs.microsoft.com/en-us/dotnet/csharp/nullable-references#nullable-contexts

However, I am sympathetic that the existence of this doesn't make it instantly easy to figure out why the heck it's behaving this way :)

**Comment by RikkiGibson** [comment]
The below comment is a bit long and disorganized, so I apologize. I've spent some time digging into the issue and the compiler's current behavior in similar scenarios.

First, let's look closely at the behavior when the nullable context is changed in the middle of an interface in the base interfaces list.

```cs
        [Fact]
        public void PartialInterfaceHijinks()
        {
            var source0 = @"
#nullable enable

public interface Interface<T, U, V> { }
";

            var source1 = @"
#nullable enable

public partial class Derived1<T, U, V> : Interface<
#nullable disable
    T,
#nullable enable
    U,
#nullable enable
    V> { }
";

            var source2 = @"
#nullable enable

public partial class Derived1<T, U, V> : Interface<
#nullable enable
    T,
#nullable disable
    U,
#nullable enable
    V
    > { }
";
            var verifier = CompileAndVerify(new[] { source0, source1 }, symbolValidator: validate0);
            verifier.VerifyDiagnostics();
            void validate0(ModuleSymbol module)
            {
                var derived = module.GlobalNamespace.GetMember<NamedTypeSymbol>("Derived1");
                Assert.Equal(1, derived.Interfaces().Length);
                var typeArgs = derived.Interfaces()[0].TypeArgumentsWithAnnotationsNoUseSiteDiagnostics;
                Assert.Equal(NullableAnnotation.Oblivious, typeArgs[0].NullableAnnotation);
                Assert.Equal(NullableAnnotation.NotAnnotated, typeArgs[1].NullableAnnotation);
                Assert.Equal(NullableAnnotation.NotAnnotated, typeArgs[2].NullableAnnotation);
            }

            verifier = CompileAndVerify(new[] { source0, source2 }, symbolValidator: validate1);
            verifier.VerifyDiagnostics();
            void validate1(ModuleSymbol module)
            {
                var derived = module.GlobalNamespace.GetMember<NamedTypeSymbol>("Derived1");
                Assert.Equal(1, derived.Interfaces().Length);
                var typeArgs = derived.Interfaces()[0].TypeArgumentsWithAnnotationsNoUseSiteDiagnostics;
                Assert.Equal(NullableAnnotation.NotAnnotated, typeArgs[0].NullableAnnotation);
                Assert.Equal(NullableAnnotation.Oblivious, typeArgs[1].NullableAnnotation);
                Assert.Equal(NullableAnnotation.NotAnnotated, typeArgs[2].NullableAnnotation);
            }

            verifier = CompileAndVerify(new[] { source0, source1, source2 }, symbolValidator: validate0);
            verifier.VerifyDiagnostics();

            verifier = CompileAndVerify(new[] { source0, source2, source1 }, symbolValidator: validate1);
            verifier.VerifyDiagnostics();
        }
```

It appears that when the same interface is used in multiple partial declarations, where the interfaces only differ by nullable-obliviousness, we just choose the first interface syntactically. In practice we don't lose nullability diagnostics or anything on implicit implementations, for example, because we end up including both interfaces in the source symbol's interface list and check the members of each against the implementation methods. This could mean, though, that when a type like this is used from metadata and converted to the interface type, we may miss warnings.

There's also an issue when a type like this is *converted to* an interface type because the symbol has multiple copies of the "same" interface in its interface list. Feels like I'm pulling on the thread and the thing is unraveling..

Now consider a similar situation involving a base class difference:

```cs
        [Fact]
        public void BaseClassHijinks()
        {
            var source0 = @"
#nullable enable

public class Base<T, U, V> { }
";

            var source1 = @"
#nullable enable

public partial class Derived1<T, U, V> : Base<
#nullable disable
    T,
#nullable enable
    U,
#nullable enable
    V> { }
";

            var source2 = @"
#nullable enable

public partial class Derived1<T, U, V> : Base<
#nullable enable
    T,
#nullable disable
    U,
#nullable enable
    V
    > { }
";
            var comp = CreateCompilation(new[] { source0, source1 });
            comp.VerifyDiagnostics();
            var derived = comp.GetMember<NamedTypeSymbol>("Derived1");
            var typeArgs = derived.BaseTypeNoUseSiteDiagnostics.TypeArgumentsWithAnnotationsNoUseSiteDiagnostics;
            Assert.Equal(NullableAnnotation.Oblivious, typeArgs[0].NullableAnnotation);
            Assert.Equal(NullableAnnotation.NotAnnotated, typeArgs[1].NullableAnnotation);
            Assert.Equal(NullableAnnotation.NotAnnotated, typeArgs[2].NullableAnnotation);

            comp = CreateCompilation(new[] { source0, source2 });
            comp.VerifyDiagnostics();
            derived = comp.GetMember<NamedTypeSymbol>("Derived1");
            typeArgs = derived.BaseTypeNoUseSiteDiagnostics.TypeArgumentsWithAnnotationsNoUseSiteDiagnostics;
            Assert.Equal(NullableAnnotation.NotAnnotated, typeArgs[0].NullableAnnotation);
            Assert.Equal(NullableAnnotation.Oblivious, typeArgs[1].NullableAnnotation);
            Assert.Equal(NullableAnnotation.NotAnnotated, typeArgs[2].NullableAnnotation);

            comp = CreateCompilation(new[] { source0, source1, source2 });
            comp.VerifyDiagnostics(
                // (4,22): error CS0263: Partial declarations of 'Derived1<T, U, V>' must not specify different base classes
                // public partial class Derived1<T, U, V> : Base<
                Diagnostic(ErrorCode.ERR_PartialMultipleBases, "Derived1").WithArguments("Derived1<T, U, V>").WithLocation(4, 22)
                );
            derived = comp.GetMember<NamedTypeSymbol>("Derived1");
            typeArgs = derived.BaseTypeNoUseSiteDiagnostics.TypeArgumentsWithAnnotationsNoUseSiteDiagnostics;
            Assert.Equal(NullableAnnotation.Oblivious, typeArgs[0].NullableAnnotation);
            Assert.Equal(NullableAnnotation.Oblivious, typeArgs[1].NullableAnnotation);
            Assert.Equal(NullableAnnotation.Oblivious, typeArgs[2].NullableAnnotation);
        }
```

Base classes are a bit different because the type arguments *do* affect the signatures of accessible members, and we can only use one symbol for the base type, rather than simply being able to add all of them to a list. It feels like there are a few possible options:

1. Pick one of the base classes that appeared in syntax as the base type for the symbol, based on some criteria.
    - For example, we could simply pick the first base type which has non-oblivious top-level nullability, or if all of them have oblivious top-level nullability, pick the first one in syntax. This would result in `Base<T, U!, V!>!`, for example (using the test symbol display style).
2. Create a "composite" base class by combining all the base types that appeared on all the declarations.
    - For example, we could visit the N base types simultaneously and produce a new type where we prefer a type in a `#nullable enable annotations` context over the opposite in every position. This would result in `Base<T!, U!, V!>!`.

It feels like the situations where (2) would result in a different type than (1) are so esoteric that we shouldn't spend engineering effort making them work. But it does feel like we should be conscious/aware of the scenarios that could behave strangely as a consequence.

There is a separate question of when to give errors. It has been suggested to allow any kind of oblivious differences between base classes on different partial class declarations. It has also been suggested by @jcouv that we give a diagnostic for any difference *if* both of the types are non-oblivious or contain non-oblivious types. We would then make it so that a "completely oblivious" type would be ignored in favor of a type which is non-oblivious in any way, and multiple types which differ in the extent of their non-obliviousness would be considered incompatible and result in at least a warning (and if we emit in that scenario, we probably just emit the first one in lexical order.)

**Comment by RikkiGibson** [comment]
I wrote up the following document for the purpose of LDM discussion. https://github.com/RikkiGibson/csharplang/blob/partial-base-nullable/proposals/partial-base-nullable.md
