### ISSUE TITLE
CS4034: "async" CodeFix does not fix all errors it points out

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#4598]
1. Paste code below: 
2. Press Ctrl+. when you click within that delegate
3. The preview shows `delegate [space] () { }` instead of `delegate async () { }`.  It shows the first fix correctly though.

```C#
using System;
using System.Threading.Tasks;

class Program
{
    private async void method()
    {
        string content = await Task<String>.Run(
             delegate ()
             {
                 await Task.Delay(1000);
                 return "Test";
             });
    }
}
```

**Comment by Semyntax** [comment]
There is at least one additional manifestation to this issue.
The suggested fix for duplicate async keyword is to add another async-keyword instead of removing it or pointing out that the keyword is duplicate.
`private async async void method()` will suggest  `private async async async
duplicate void method()` instead of `private async void method()`

**Comment by jmarolf** [comment]
@Semyntax Fixed the duplicate keyword issue by only offering the fix on code that doesn't have the async keyword.  Take a look [here](https://github.com/dotnet/roslyn/pull/4621/files#diff-efb115ee06371772cdbdff35aca8a49fR73)
