### ISSUE TITLE
LocalInputEntityStruct is considered unmanaged in source but not from metadata

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/roslyn#46003]
---
**Issue moved from microsoft/msbuild#5512**
- Please respond to @sebas77.

---

_From @sebas77 on Tuesday, July 14, 2020 5:27:21 PM_

Hi,

The only way to report this issue is to upload the project, as the structure of the project, and not just the code, affects the outcome. However, I would like to show you what leads me to think it's a compiler bug before to proceed further. 

![image](https://user-images.githubusercontent.com/945379/87456739-45680a00-c5ff-11ea-91f4-bc318d4f40ec.png)
![image](https://user-images.githubusercontent.com/945379/87456755-4ac55480-c5ff-11ea-84e7-783b471f350f.png)

If my assumptions about how the compiler works are right, this looks to me like a paradox.  QuickSaveEngine.cs cannot be compiled if LocalInputEntityStruct is not compiled first and LocalInputEntityStruct cannot be compiled if it's nullable, right? The struct itself is 100% unmanaged and doesn't have nullable fields, but since it's a complex struct, the implementation of the interface with unmanaged constraint is my way to prove it. If you agree that there is something fishy, please let me know if and how I should proceed. Note: the same code compiles if I don't use separate assemblies.

OS info:

Windows 10, MSBuild 2017 (c# 7.3)

**Comment by sebas77** [comment]
@rainersigwald thank you for the first clarification I needed (move it here). Since I have been already downvoted on StackOverflow for the way I wrote the question, I am going to rewrite it here as well:

All of a sudden, I have a compilation bug, that I cannot figure out, on code that has been working for a long time. This is reproducible with C# 7.3. The following structure never changed:

     public interface ILocalInputEntityStruct<T> where T : unmanaged
    {
        //wouldn't the implementation of this interface prove 
        //that the struct doesn't have nullable fields (so it's unmanaged for c# 7.3)?
    }
    
    public struct LocalInputEntityStruct:ILocalInputEntityStruct<LocalInputEntityStruct>, IEntityComponent, INeedEGID
    {
        public float2      cameraAngles; 
        public float       cameraZoomFactor; 
        public float       roll;
        public ActionInput actionMask;
        public GuiInput    guiMask;
    }

while in the following code, found in a different assembly than the one of the declaration, the **QueryEntity** expects T to be unmanaged, but the compiler thinks the struct is instead nullable:

      ref var localInput = ref entitiesDB.QueryEntity<LocalInputEntityStruct>(
                    playerId, InputExclusiveGroups.LocalPlayers);

compiling this line results in the error

      VisualCameraInputEngine.cs(60, 53): [CS8377] The type 'LocalInputEntityStruct' must be a non-nullable value type, along with all fields at any level of nesting, in order to use it as parameter 'T' in the generic type or method 'EntityDBExtensions.QueryEntity<T>(EntitiesDB, uint, ExclusiveGroupStruct)'

Now, I cannot be sure that the problem was just hidden before as the constraint may work differently in the new code, but if my assumptions about how the compiler works are right, this looks to me like a paradox. **VisualCameraInputEngine.cs** shouldn't compile before **LocalInputEntityStruct** and **LocalInputEntityStruct** cannot compile if it's nullable, right? The struct itself is 100% unmanaged and doesn't have nullable fields, but since it's a complex struct, the implementation of the interface with unmanaged constraint is my way to prove it. 

Edit: **QueryEntity** declaration:

     public static class EntityDBExtensions
    {
       [MethodImpl(MethodImplOptions.AggressiveInlining)]
       public static ref T QueryEntity<T>(this EntitiesDB entitiesDb, uint id, ExclusiveGroupStruct group) where T : unmanaged, IEntityComponent
       {
           throw new Exception("keeping this code simple for the purpose of the stack overflow question");
       }
    }

    public static class EntityDBExtensionsB
    {
       [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ref T QueryEntity<T>(this EntitiesDB entitiesDb, uint id, ExclusiveGroupStruct group) where T : struct, IEntityViewComponent
        {
            throw new Exception("keeping this code simple for the purpose of the stack overflow question");
        }
    }

Note: the same code compiles if I don't use separate assemblies.

OS info:

Windows 10, MSBuild 2017 (c# 7.3)

I am writing here because I am looking for expert people that can explain me why this could happen (I would be extremely grateful for that) or think this may be a Roslyn bug (which in this case I will report on the Roslyn github).

I do not exclude that I am missing something about how assemblies work and I don't know about it.

**Comment by sebas77** [comment]
Just to be clear, the first step of this investigation and reason I wrote here is to have someone confirming that, if LocalInputEntityStruct is indeed the same reported here, this is a compiler paradox.

**Comment by RikkiGibson** [comment]
> Note: the same code compiles if I don't use separate assemblies.

this is a very interesting clue. Could you please share the compiler versions from before and after this broke? An easy way to do this is to add `#error version` to your code.

**Comment by sebas77** [comment]
Thanks for the reply. I am available to give you all the info you need, but I am not sure why you are asking about the compiler version from before and after this broke. Sorry, I may not have explained myself properly. The compiler is the same, the difference between the two versions is that "QueryEntity" has been modified to the extension methods I listed in the second post. Before it was just one "normal" method and it didn't have the "unmanaged" constraint. Adding the extension triggered the bug, but I don't think it's the reason of the bug itself. The code is supposed to pickup the unmanaged extension method, and it does, but then it thinks that the struct is not unmanaged. Static analyzer do not pick up this btw.

**Comment by sebas77** [comment]
Get the same error on these two compiler versions: 

error CS8304: Compiler version: '2.9.1.65535 (9d34608e)'. Language version: latest.

  TextBlockMessageReceiveClientEngine.cs(56, 8): [CS8304] Compiler version: '2.10.0.0 (b9fb1610)'. Language version: latest.

**Comment by RikkiGibson** [comment]
Sorry for the misunderstanding. To clear up what is happening:

1. Originally you had an unmanaged struct `LocalInputEntityStruct`. You passed the struct as a type argument for a method `QueryEntity<T> where T : unmanaged`.

2. Then you moved the call to `QueryEntity<LocalInputEntityStruct(...)` to a different assembly. Now it complains that type parameter constraints are not met.

 It would be useful to know if the bad behavior is still present in a more recent compiler (e.g. by installing [VS Preview](https://visualstudio.microsoft.com/vs/preview/) and trying to build your project). If this is not feasible for you, I may have enough information at this point to try and create a reproducer.

**Comment by sebas77** [comment]
I can share with you the project to repro the bug, it's the complete codebase of our game, but it's not a problem for us as the code is easily decompilable anyway. I would just need a way to send you a link privately. 

The bug is not reproducible with MSBuild 2019 compiler, but I cannot be sure as I think c# 8 may be hiding it (as nullable struct are considered unmanaged). Unluckily, due to the number of assemblies in the project, I cannot easily move from "latest" to "7.3" in the projects.

**Comment by sebas77** [comment]
OK I mass find and replace worked and I was able to repro the bug with the MSBuild 2019

  TextBlockLocalTweakNotificationEngine.cs(40, 25): [CS8304] Compiler version: '3.6.0-4.20251.5 (910223b6)'. Language version: 7.3.

let me know if you want me to test an even newer version.

**Comment by RikkiGibson** [comment]
You are welcome to send a link or attachment containing your project to rigibson@microsoft.com.

**Comment by sebas77** [comment]
The project is sent, please let me know if you have any problem with it (including if you can repro the problem of course :) )

**Comment by RikkiGibson** [comment]
Thanks for sending the project @sebas77. It really helped clear up the problem.

Good news: you can work around this in your project. In the assembly containing `TextBlockLocalTweakNotificationEngine.cs` in your project, you need to add references to assemblies containing all the types used in the struct which triggers the CS8377 error.

The problem is that some of the struct field types are defined in assemblies which are not referenced. The ErrorType symbol which gets used for the field's type is considered "managed", thus the containing struct is also considered "managed". What we should do in the compiler is issue use-site diagnostics where these unmanaged checks are performed to tell the user that they need to add additional assembly references.

**Comment by sebas77** [comment]
Hi Rikki

Thank you very much for your time and help. I have just one problem with
your workaround, the projects are automatically created by unity using
asmdefs. I will see if I can fix it with unity, otherwise do you think it's
a unity issue?

**Comment by RikkiGibson** [comment]
It sounds like you can modify your asmdef files to make them reference the appropriate projects. Hopefully that works for your use case.

**Comment by sebas77** [comment]
I managed to fix my problem with your advice @RikkiGibson 
Technically those extra references I added were not needed as I wasn't using any of the code from those assemblies, so even with the compiler telling me that something is wrong, I wouldn't understand why I should add references to assemblies that I don't use directly in the project.
However, I am very grateful you unblocked me ;)

**Comment by RikkiGibson** [comment]
Thanks again for reporting @sebas77. It definitely will help future developers resolve the problem you encountered.
