### ISSUE TITLE
Exception When Opening Document With Workspace

### ISSUE THREAD

**Issue by shortspider** [dotnet/roslyn#4613]
I am trying to register a refactoring action that will navigate to a particular document, however whenever I try and open the document I get an InvalidOperationException (see screenshot).

![image](https://cloud.githubusercontent.com/assets/5712543/9321946/db59cbfc-453a-11e5-89d9-6e3ed884ac7c.png)

This exception is thrown when calling Workspace.OpenDocument or WorkspaceOpenAditionalDocument. It occures in both methods regardless of weather activate is true or false.

The document exists and is a part of the solution. Is this a bug or am I missing something?

**Comment by Pilchie** [comment]
I believe that Extract Interface opens the document - can you point out the right way to do it?

**Comment by shortspider** [comment]
Hey is there any update on this?

**Comment by CyrusNajmabadi** [comment]
Do you hi @shortspider Do you have a sample project that repros this?  Thanks!

**Comment by shortspider** [comment]
@CyrusNajmabadi I have created a [test project](https://github.com/shortspider/TestRefactor).

If you debug this extension in Visual Studio you will be prompted to open another project. Open the TestRefactor project again and go to the TestClass.cs file. This class is used in AnotherClass.cs. If you click on the class deceleration syntax and initiate a refactor my code will attempt to open AnotherClass.cs but fail with the error I posted above.

Does that make sense?

**Comment by shortspider** [comment]
@CyrusNajmabadi hey did you get a chance to try out the project?

**Comment by Pilchie** [comment]
@shortspider - sorry, @CyrusNajmabadi had to take a little bit of time off, but he should be back online later this week.  Sorry for the delay.

**Comment by shortspider** [comment]
@Pilchie no worries, hope it was just a vacation and not something serious. Thanks for letting me know.

**Comment by CyrusNajmabadi** [comment]
Hey @shortspider here's the problem.  You're attempting to open a document while you're being executed on a background thread.  This is not a supported thing to do.

What you probably want to do instead is write your own CodeAction that returns a different type of CodeActionOperation.  Instead of using CodeAction.Create (which returns an ApplyChangesOperation), an option is to instead return a subclass of ApplyChangesOperation.  You could then override:

```c#
        public override void Apply(Workspace workspace, CancellationToken cancellationToken)
        {
            workspace.TryApplyChanges(_changedSolution);
        }
```

You'd call base.Apply to make the actual change to teh workspace.

The benefit here is that ```.Apply``` is guaranteed to be called on the UI thread.  So it would be possible for you to then open documents in your overridden method.

I'm going to make some changes here to make it so we provide a useful exception here to make it clear what the problem is.  Once i make that change, i'll resolve this back to you.

**Comment by CyrusNajmabadi** [comment]
Actually, as @jasonmalinowski pointed out to me, you can just use OpenDocumentOperation for this operation.  Cheers!

**Comment by jasonmalinowski** [comment]
@CyrusNajmabadi: yep, that's what should be used. We should still make the exception better. :smile:

**Comment by shortspider** [comment]
@CyrusNajmabadi @jasonmalinowski thank you both so much, worked like a charm!
