### ISSUE TITLE
Remove ConditionalFact(typeof(x86))

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#462]
PR #453 enabled the running of our tests in 64 bit by adding the `/p:Test64=true` option to BuildAndTest.proj

> msbuild /v:m /m BuildAndTest.proj /p:Test64=true

In order to do this a number of tests were disabled by adding a `Fact` annotation that disabled the test in 64 bit runs.  

``` csharp
// C#
[ConditionalFact(typeof(x86))]
```

``` vb
' Visual Basic
<ConditionalFact(GetType(x86))>
```

These attributes all represent bugs in our test environment, and potentially production code, that need to be fixed up.  This bug tracks removing all of these and getting the tests working on 64 bit.  

Note: This does not include the uses of the above attributes in the Visual Studio directory.

**Comment by DustinCampbell** [comment]
Note that it *might* be possible to remove the <ConditionalFact(GetType(x86))> from the Visual Studio directory. This was originally added because we had a native binary to handle COM aggregation. However, now we do that in some very... ummm... disorienting managed code that implements VTable and COM Aggregation logic. So, the dependency on x86 may no longer be necessary.

**Comment by ManishJayaswal** [comment]
Let's get this fixed area by area. Kevin once you are done with debugger area, assign this to someone in another feature team who have fix up work to do and update the label.

**Comment by davkean** [comment]
Removing infrastructure, these are test bugs against product areas.

**Comment by Youssef1313** [comment]
Related to: https://github.com/dotnet/roslyn/issues/28639
