### ISSUE TITLE
Sort implementer class methods in order they defined in interface

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#46273]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1112712/sort-implementer-class-methods-in-order-they-defin.html)._

---
<p>In Visual Studio when I use Quick Actions(ctrl+.) and select implement interface it imports the methods in an alphabetical sort. But I want them to be imported in order that they defined in interface. please provide this option, thanks</p>

---
#### Feedback Bot on 7/15/2020, 00:58 AM: 

Thank you for taking the time to provide your suggestion.&nbsp; We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.

**Comment by genlu** [comment]
Design meeting notes:
	
- Should this be in Tools-> options?

Proposal:
- Change to order to use declaration order
  - If there's no implemented members already: yes
  - If some member already implemented? Stick to what we are doing today. i.e. Add new ones to the end of type, but in declaration order
	
Follow up:
Can we get APIs in order consistently from metadata with current compiler API?

**Comment by reclaimer-zz** [comment]
+1 on the request here, specifically using declaration order instead of alphabetical by default.  Can I also add that when inserting the new members, you should preserve any lines of whitespace that have been defined between them in the originating abstract class?  If methods were grouped a certain way in the abstract base class (e.g. due to having related function), the implementing class likely will want the same grouping.

That additional suggestion aside, I ended up here today because my issue is that I have the following abstract class:
```
abstract class Manager{
    public abstract void Startup();
    public abstract void Shutdown();
}
```
And every time I use "Quick Actions" to have a new concrete class implement it, the <code>Shutdown()</code> method gets created before the <code>Startup()</code> method.  And then I have to waste time changing the order.

**Comment by CyrusNajmabadi** [comment]
I'm fine with this idea in principle. However, from an implementation pov this would actually be somewhat challenging due to how disparate apis take to each other here.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
