### ISSUE TITLE
Clarification on ControlFlowAnalysis.EndPointIsReachable 

### ISSUE THREAD

**Issue by JoshVarty** [dotnet/roslyn#4630]
Consider the following code:

```CSharp
static int TestMethod()
{
    return 0;
}
```

When I perform control flow analysis on it, [`EndPointIsReachable`](http://source.roslyn.io/#Microsoft.CodeAnalysis/Compilation/ControlFlowAnalysis.cs,593df28d26c785c2) is false.

The documentation says:

>Indicates whether a region completes normally. Return true if and only if the end of the last statement in a region is reachable or the region contains no statements.

In the above case, the last statement in the method's body is `return 0;` which is reachable. Why is `EndPointIsReachable` false?

To repro:

```CSharp
var tree = CSharpSyntaxTree.ParseText(@"
class C
{
	static int TestMethod ()
	{
		return 0;
	}
}");

var Mscorlib = PortableExecutableReference.CreateFromAssembly(typeof(object).Assembly);
var compilation = CSharpCompilation.Create("MyCompilation",
	syntaxTrees: new[] { tree }, references: new[] { Mscorlib });
var model = compilation.GetSemanticModel(tree);

var method = tree.GetRoot().DescendantNodes().OfType<MethodDeclarationSyntax>().Single();
ControlFlowAnalysis result = model.AnalyzeControlFlow(method.Body);

var lastStatement = method.Body.Statements.Last();
Console.WriteLine(lastStatement);               //return 0;
Console.WriteLine(result.EndPointIsReachable);  //False
```

**Comment by gafter** [comment]
The *end of* the return statement is not reachable because the return statement has returned from the method. See also the following excerpts from the language specification:

> 8.1 End points and reachability
>
Every statement has an end point. In intuitive terms, the end point of a statement is the location that immediately follows the statement. The execution rules for composite statements (statements that contain embedded statements) specify the action that is taken when control reaches the end point of an embedded statement. For example, when control reaches the end point of a statement in a block, control is transferred to the next statement in the block.
>
If a statement can possibly be reached by execution, the statement is said to be reachable. Conversely, if there is no possibility that a statement will be executed, the statement is said to be unreachable.

> 8.9.4 The return statement
>
The return statement returns control to the current caller of the function in which the return statement appears.
```none
return-statement:
return   expressionopt   ;
```
>
A return statement with no expression can be used only in a function member that does not compute a value, that is, a method with the result type (§10.6.10) void, the set accessor of a property or indexer, the add and remove accessors of an event, an instance constructor, a static constructor, or a destructor.
>
A return statement with an expression can only be used in a function member that computes a value, that is, a method with a non-void result type, the get accessor of a property or indexer, or a user-defined operator. An implicit conversion (§6.1) must exist from the type of the expression to the return type of the containing function member.
>
Return statements can also be used in the body of anonymous function expressions (§7.15), and participate in determining which conversions exist for those functions.
>
It is a compile-time error for a return statement to appear in a finally block (§8.10).
>
A return statement is executed as follows:
•	If the return statement specifies an expression, the expression is evaluated and the resulting value is converted to the return type of the containing function by an implicit conversion. The result of the conversion becomes the result value produced by the function.
•	If the return statement is enclosed by one or more try or catch blocks with associated finally blocks, control is initially transferred to the finally block of the innermost try statement. When and if control reaches the end point of a finally block, control is transferred to the finally block of the next enclosing try statement. This process is repeated until the finally blocks of all enclosing try statements have been executed.
•	If the containing function is not an async function, control is returned to the caller of the containing function along with the result value, if any.
•	If the containing function is an async function, control is returned to the current caller, and the result value, if any, is recorded in the return task as described in (§10.14.1).
>
Because a return statement unconditionally transfers control elsewhere, **the end point of a return statement is never reachable.**

(my emphasis)

**Comment by JoshVarty** [comment]
:+1: Thanks @gafter
