### ISSUE TITLE
Release timeline and versioning story for IDE CodeStyle NuGet packages

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#46516]
We now have C# and VB CodeStyle NuGet packages with majority of IDExxxx rules ported over. The NuGet packages are being dogfooded on both roslyn-analyzers and roslyn repo for couple of months, with no major issues. Any known issues are specific to individual analyzers, and should not affect the release of the package. We have received large number of internal and external customer requests to publish these packages on NuGet.

## Proposal
1. Release beta1 CodeStyle NuGet packages on nuget.org along with VS2019 16.8. Ensure that release notes mention these packages.
2. The packages would be based on Microsoft.CodeAnalysis 3.7.0 - users would need to be on at least VS2019 16.7 to use these packages in their projects.
3. Versioning story: We can take 2 possible approaches for how we move forward the versions of CodeStyle packages and underlying `Microsoft.CodeAnalysis` version reference.
   1. Report better diagnostics on `Microsoft.CodeAnalysis` reference mismatch: We ensure that we give good diagnostics to users when they try to use CodeStyle packages on earlier versions of VS/compiler then required by the package. In fact, this functionality is required by all analyzer packages and would be good to implement in Roslyn. We can enhance `AnalyzerFileReference` analyzer loading so that if the analyzer assembly is built against a version of `Microsoft.CodeAnalysis` that is later then the current executing version of assembly, we report a special analyzer reference load failure diagnostic recommending users to either upgrade their VS/compiler toolset OR downgrade the referenced analyzer package. This will allow us to continually bump up the CodeStyle package's `Microsoft.CodeAnalysis` version reference to latest version.
   2. Keep `Microsoft.CodeAnalysis` version reference as low as possible, and use reflection/light up to enable consuming new Roslyn APIs. This has the advantage that newer CodeStyle packages will keep working on older VS/compiler versions, but makes for a nightmare maintenance scenario for our code base.

**Comment by mavasani** [comment]
@mikadumont @vatsalyaagrawal @sharwell I would like to bring up this issue for today's design meeting.

**Comment by huoyaoyuan** [comment]
Question: what's the relationship between this analyzer and `dotnet format`?
Can it replace `dotnet format --dry-run --check` in CI?

**Comment by jmarolf** [comment]
I see `dotnet format` evolve into being about _applying_ fixes and the regular compiler + analyzers becomes more and more capable

**Comment by mavasani** [comment]
@jmarolf Can you please update this issue with our final plan of action for CodeStyle package in SDK/NuGet package?

**Comment by jmarolf** [comment]
Items 1 and 2 are non-controversial and we are going to do them. Here are the addendums:

## Defaults
- CodeStyle analysis will ship in the .NET 5 SDK but be off by default
  - can be turned on by setting the property `<EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>` in the project file
  - can also be turned on by checking the checkbox in the code analysis property page
- CodeStyle analysis will ship in the .NET 5 SDK but be _on_ by default
  - can be turned off by setting the property `<EnforceCodeStyleInBuild>false</EnforceCodeStyleInBuild>` in the project file
  - can also be turned off by un-checking the checkbox in the code analysis property page

## Versioning
- CodeStyle analysis in .NET 5 will be 3.8.0-3.20425.2
- CodeStyle analysis for .NET 6 will be updated with compiler updates until it ships next year at which point it will be frozen like .NET 5
- If a code style analysis rule ships in both Visual Studio and the .NET 5 SDK the rule from the SDK will be preferred
- If the user installs the codeStyle nuget packages and they are older what comes from the SDK we will issue a warning to uninstall them. Otherwise we will use the nuget packages over the SDK packages.

@mavasani let me know if I have mis-stated anything.

**Comment by mavasani** [comment]
Thanks @jmarolf. That sounds good. Few things to add

1. We have official documentation for enabling code style in build with .NET5 SDK at https://docs.microsoft.com/dotnet/fundamentals/productivity/code-analysis#code-style-analysis
2. We need to ensure that we ship CodeStyle packages on nuget.org along with other Roslyn packages, such as `Microsoft.CodeAnalysis`, as they are tightly coupled with the compiler and workspace packages. Who should be informed about doing adding these packages to the list of packages we publish on nuget.org? @JoeRobich would you know?
> user installs the codeStyle nuget packages and they are older what comes from the SDK we will issue a warning to uninstall them
3. @jmarolf above is only implemented for Microsoft.CodeAnalysis.NetAnalyzers package. Can we open an issue for doing similar work for CodeStyle packages?

**Comment by jmarolf** [comment]
created https://github.com/dotnet/roslyn/issues/47753
