### ISSUE TITLE
UnitTests don't clean up modified SynchronizationContext

### ISSUE THREAD

**Issue by tannergooding** [dotnet/roslyn#4654]
There are multiple unit tests (https://github.com/dotnet/roslyn/search?utf8=%E2%9C%93&q=SynchronizationContext) which modify the SynchronizationContext and don't restore it when completed.

**Comment by tannergooding** [comment]
FYI. @brettfo, @Pilchie

**Comment by Pilchie** [comment]
Hmm, @brettfo, could you take a look at the ones in the IDE codebase, and then move along to interactive and compiler?

**Comment by brettfo** [comment]
In short, since the work to properly update these tests is co-dependent on @tannergooding's work to move to another version of xUnit which is currently in progress, we decided that he (Tanner) would make the appropriate test changes along with his xUnit stuff and that I'd be pulled in near the end if he needs extra help and during the review.

The current plan is to add a `[WpfFact]` attribute inheriting from Tanner's `[StaFact]` which will handle the SynchronizationContext issues and all affected tests will get that new attribute.  So for a long-winded answer to your request, yes I'll make sure that when it's all done and over the affected IDE, interactive, and compiler tests are given the appropriate attribute.

**Comment by davkean** [comment]
What was the resolution to that? Looks like we added WpfFact, was this completed?

**Comment by tannergooding** [comment]
@davkean, I believe this was fixed now. @brettfo, could you confirm?

**Comment by brettfo** [comment]
Reviewing IDE tests it appears that the appropriate ones have the `[WpfFact]` attribute set and the [`WpfTestCase`](http://source.roslyn.io/#Roslyn.Services.Test.Utilities/Threading/WpfTestCase.cs,26763f49e4a5e475) class appropriately handles the threading issues.
