### ISSUE TITLE
[Feture Request] Auto Cast

### ISSUE THREAD

**Issue by Jes28** [dotnet/roslyn#4670]
Add ability to call to concreate type if I know that object is of that type:

if( someObj is IGraphics )
    someObj.Render(); //Bo beed to additionally write cast operation because we already check someObj for IGraphick interface.

**Comment by khellang** [comment]
This sounds an awful lot like the `is` operator proposed as part of the "pattern matching and record types" proposal (#206).

That would allow you to do

```csharp
if (someObj is IGraphics g)
{
    // Do something with g
}
```

**Comment by whoisj** [comment]
Is there something wrong with:

```
    Type2 casted;
    if ((casted = original as Type2) != null)
    {
        // do work with casted
    }
```

Though I could see the value of allowing a declaration there as well:

```
    if ((var casted = original as Type2) != null)
    {
        // do work with casted
    }
```

**Comment by Jes28** [comment]
I think 
```csharp
if (someObj is IGraphics g)
{
    // Do something with g
}
```

is definitely better way :)

**Comment by whoisj** [comment]
I personally do not think `(someObj is IGraphics g)` and a declaration of `IGraphics g` is clear at all.

Can't we do better?

Maybe add a new operator `when` or something? Perhaps `when (someobj as IGraphics) { /* use someObj as IGraphic now /* }` or something?

**Comment by Jes28** [comment]
There we think different. :)

For me declaration of ``` IGraphics g ``` is absolutely clear as soon as I saw it.
Buy your ```when (someobj as IGraphics)``` suggestion is not clear at all event when I read it few times :)

**Comment by Eyas** [comment]
This exact feature seems to be a subset of pattern matching (#206) as @khellang stated. This exact proposal:

    if (expr is Type v) { // code using v }

is in section 5.1 "Type Pattern".

**Comment by HaloFour** [comment]
I think that this is an interesting idea but it is also a breaking change from the existing logic in some cases.  For example:

```cs
public class Foo {
    public string Say() { return "Foo!"; }
}

public class Bar : Foo {
    public new string Say() { return "Bar!"; } 
}

Foo foo = new Bar();
if (foo is Bar) {
    Console.WriteLine(foo.Say());
}
```

In C# 1.0 through C# 6.0 "Foo!" would be written to the console, but with this proposal if the compiler were to consider `foo` to be a `Bar` within the `if` block it would write "Bar!".  Even if the compiler would take that into consideration and try to call `Foo.Say` that would also be a source of confusion.

The pattern matching version does require you to assign a new identifier but at least it makes you have to be explicit about their use.

**Comment by whoisj** [comment]
@HaloFour I'm confused as to which post you're replying to. I do not think anyone is suggesting that `if (a is type_b)` invoke a cast from `type_a` to `type_b` as that would be unexpected and breaking.

**Comment by AnthonyDGreen** [comment]
We get this proposal a lot. The main issue is that it only works for the simple cases of local variables/parameters and maybe simple fields. For example, if instead of the simple identifier someObj the expression were complex like Collection[0].Property.SomeObj then would it be reasonable to implicitly convert future property accesses to SomeObj to IGraphics? SomeObj could be recomputed every time it's evaluated and the value might not always implicit IGraphics? Do we cache the initial result or re-perform the cast on each access. One leads to code that might blow up and the other to code which doesn't do what you say. Both are bad options :( So we could do it for local variables because we know they won't change. But even for something as simple as a field in theory its value could be changed on another thread so we can't promise this.SomeObj will always be an IGraphics.

That's why the pattern matching proposal introduces a new local identifier which we can know is safe to access without redundant cast. But we'd all be excited to hear any proposals the community comes up with for how to resolve these problems with the elegance of the proposed syntax. We agree that it would be really cool.

**Comment by gafter** [comment]
We're planning to do pattern matching per #206 to address this issue.
