### ISSUE TITLE
Possible optimization in interpolated string: inline interpolated constants

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#4678]
if an expression hole has a constant string value and no alignment or format, treat it as a literal instead of an expression. This would erase string.Format calls for scenarios like "throw new ArgumentException($"{nameof(argument)} should be something else".

Migrated from TFS/DevDiv 1097932

**Comment by AdamSpeight2008** [comment]
That should optimise down to just a string constant, not a Interpolation String. 
`NameOf( argument ) `
What about  the case of multiple expression holes, one constant one not?
You can also extend it to any constant, not just strings. as well as including `, alignment`. As it is just padding the string with spaces. Since we are using constants, it could be worked out a compile-time. 

Should this be more of an Analyser and Code-Fix? *(Eg String-Format Diagnostics. Doesn't offer code-fixes yet))*

**Comment by khellang** [comment]
@gafter Do you know if there's an existing issue on optimizing interpolated strings where you're basically just doing concatenation? (I couldn't find one)

So that `var result = $"{a}{b}";` becomes `var result = string.Concat(a, b);` instead of `var result = string.Format("{0}{1}", a, b);`, at least for a certain amount of parameters.

See https://github.com/aspnet/HttpAbstractions/pull/460#issuecomment-153474801 for reference.

**Comment by benaadams** [comment]
@khellang @gafter Additionally automatically calling `.ToString()` on valuetype params; currently:

```csharp
public static string InterpolatedBox(int i)
{
	return $"? {i}";
}
```
boxes as 
```
.method public hidebysig static string  InterpolatedBox(int32 i) cil managed
{
  // Code size       17 (0x11)
  .maxstack  8
  IL_0000:  ldstr      "\? {0}"
  IL_0005:  ldarg.0
  IL_0006:  box        [System.Runtime]System.Int32
  IL_000b:  call       string [System.Runtime]System.String::Format(string,
                                                                    object)
  IL_0010:  ret
} // end of method
```
vs adding `ToString` like
```
public static string InterpolatedToString(int i)
{
	return $"? {i.ToString()}";
}
```
which doesn't box
```
.method public hidebysig static string  InterpolatedToString(int32 i) cil managed
{
  // Code size       18 (0x12)
  .maxstack  8
  IL_0000:  ldstr      "\? {0}"
  IL_0005:  ldarga.s   i
  IL_0007:  call       instance string [System.Runtime]System.Int32::ToString()
  IL_000c:  call       string [System.Runtime]System.String::Format(string,
                                                                    object)
  IL_0011:  ret
} // end of method
```
As its known at compile time what is happening

**Comment by gafter** [comment]
@khellang I don't know if there is an issue for it.

**Comment by gafter** [comment]
See https://github.com/dotnet/roslyn/pull/6738#issuecomment-156257037 for why this is likely to never happen.
