### ISSUE TITLE
Enabling a rule that's off by default makes it ignore general diagnostic options

### ISSUE THREAD

**Issue by srivatsn** [dotnet/roslyn#468]
When a rule that has isEnabledByDefault set to false needs to be turned on, currently the way to do it is by having an entry in the ruleset file to set it's severity to something specific. However when that happens general options like warnaserror is ignored because specific options always win over general ones. We need to instead set the severity of the rule to Default. There is no way to do this from the ruleset editor. We decided that we should tweak the ruleset editor to put a new Default option in the drop down for actions and remove the None action and make the checkbox really mean enabled\disabled.

We should test the commandline and solution explorer behavior as well when this is fixed.

**Comment by tmeschter** [comment]
We're actually going in a different direction to fix this. The rule set schema does not allow for an action of Default, and there are many problems with adding it (notably, the need to update FxCop to do something reasonably with that action). Instead, I'm going to update the compilers and language services so that the general diagnostic options from the command line (e.g. `/WarnAsError`, `/NoWarn`) properly update settings from the rule set (turning warnings to errors, or suppressing them, respectively) and specific diagnostic options from the command line trump both of them.

**Comment by tmeschter** [comment]
Re-assigning to @srivatsn for verification.
