### ISSUE TITLE
Compiler exception messages do not use the "preferred UI lang" for localization

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#4683]
Every place that Microsoft.CodeAnalysis.CSharp.CSharpResources is used in the C# compiler we skip localization according to Compiler.Culture, which reflects the command-line setting from /preferreduilang. Similarly for VBResources. Virtually all of them are exception messages.
 
In short, exception messages are formatted in the "current UI culture" instead of according to the setting of /preferreduilang.
 
It isn't clear that any action is required to "address" this. Perhaps we could document it in the compiler spec.

Migrated from TFS/DevDiv 1080516

**Comment by jaredpar** [comment]
This resource file seems to control the error messages generated from our APIs vs. compiler error output correct?  

If so, at least in my opinion, that seems to be "by design".  The `/preferreduilang` switch should control the warnings / errors produced by the compiler analysis.  It shouldn't control the errors produced because APIs were passed invalid parameters.  

I agree that we don't need to address this.

**Comment by gafter** [comment]
Closing because "we don't need to address this"
