### ISSUE TITLE
API Proposal: OptionSet handling

### ISSUE THREAD

**Issue by mkrueger** [dotnet/roslyn#47]
- Currently OptionSets are handled at Workspace level. Moving them to the Project level would allow more fine grained option scenarios.

-Why it's not possible to create own option sets or provide option services ?

In general the option API seems to be tailored for a 'read only' use.

**Comment by paulvanbrenk** [comment]
+1 for making the OptionSet more useful. 

**Use case**
In the codeformatter project [https://github.com/dotnet/codeformatter], the code in the project is formatted using the standard Roslyn formatter. This formatter however uses the default formatting options, e.g. "Open Brace on New Line for types", unless you supply an OptionSet, however there is currently no way to instantiate that class since the constructor is internal and the class is sealed.

**Comment by Pilchie** [comment]
Pulling into 1.2, as this is something that we're looking at related to #7071 (like #7058 and #7059).

**Comment by Pilchie** [comment]
Let's actually use #7058 to track this.
