### ISSUE TITLE
make BatchFixAllProvider to use differ that EnC uses

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#470]
we have 2 syntax tree differ. 

one is SyntaxDiffer that is exposed as SyntaxTree.GetChanges and etc from compiler layer.
http://source.roslyn.io/#Microsoft.CodeAnalysis/Syntax/SyntaxDiffer.cs,8c0e0f3e0fb0271f

and the other is TreeComparer<TNode> in workspace layer.
http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Differencing/TreeComparer.cs,02b876372b38cf58

the one in the compiler layer takes advantage of green node so in case of incremental changes, it is very fast. and most of time return good enough result. but not as optimal as it can be. a lot of IDE features take advantage of this differ since it is fast (since most of features work on top of changes of the same tree which can take advantage of green nodes) and very simple to use and result is good enough for most of cases.

but there is one IDE feature that demands better accuracy. and requires accuracy over speed which is Enc. so EnC uses the second differ. the benefit of the second differ is its accuracy and customizability. disadvantage of it is speed and complexity.

but for BatchFixAllProvider, I think we would want to use the EnC differ since speed is not as important as accuracy. or it can first try compiler one, and then if that results in conflict, it tries the EnC one.

another drawback is we need to create our own differ on top of EnC one (EnC has heavily customized version of differ on top of generic tree differ). but according to @tmat , we should be able to use most of them, cut out customization made for EnC and make it generic syntax tree differ.
http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp.Features/EditAndContinue/StatementSyntaxComparer.cs,11

since BatchFixAllProvider will be most common fix all provider people will use, it will benefit a lot of people if we can make it as better as we can.

**Comment by CyrusNajmabadi** [comment]
I don't think we can make this change.  Despite all it's faults, the BatchFixer has a very specific behavior that we cannot necessarily change.  Any changes here may end up *breaking* users that depend on how this diffs.  For example, another differ might end up producing edits that 'conflict' while the batch fixer does not because of how it sees text edits.

Recommendation should be that if you need different diffing behavior that you provide your own fix all provider.  We do this ourselves in several cases without much difficulty or complexity.  It's even better normally because most batch fixers *don't* even need to do any diffing.  They can just apply their changes directly in a way that doesn't cause any conflicts.
