### ISSUE TITLE
Bad code for int? switch

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#4701]
Steps to reproduce:

1. Copy Code below and run it.

Expected: It prints "In DEFAULT case"
Actual: It prints "in Null case", even though i is assigned. This works in VS2013

```cs
using System;

namespace ConsoleApplication1
{
    class Program
    {
        private void SwtchTest()
        {
            int? i;

            i = 1;
            switch (i)
            {
                case null:
                    Console.WriteLine("In Null case");
                    i = 1;
                    break;
                default:
                    Console.WriteLine("In DEFAULT case");
                    i = i + 2;
                    break;
            }
        }

        static void Main(string[] args)
        {
            var p = new Program();
            p.SwtchTest();
         }
    }
}
```

Migrated from TFS/DevDiv 1208142

**Comment by gafter** [comment]
@VSadov Could you please have a look at this?

**Comment by MrJul** [comment]
It happens with any nullable integral value (int, enum, boolean, etc.) as long as `null` is the only case label present.

I think the offending line is [SwitchIntegralJumpTableEmitter.cs:118](https://github.com/dotnet/roslyn/blob/051ad4381100859442af93e16d8d8edbb681b05f/src/Compilers/Core/Portable/CodeGen/SwitchIntegralJumpTableEmitter.cs#L118)

Since there are no cases other than `null`, the switch isn't generated at all. Note that this bug doesn't affect a switch statement with only a default branch since it's specially handled at [EmitStatement.cs:1019](https://github.com/dotnet/roslyn/blob/4d34be60cf9cb2633f8120780c01af8822bff806/src/Compilers/CSharp/Portable/CodeGen/EmitStatement.cs#L1019)
