### ISSUE TITLE
INegatedPatternOperation and IRelationalPatternOperation should not be present in the CFG

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#47068]
Adding new operations in CFG has couple of disadvantages:
1. Existing CFG based analyzers are broken as they encounter unknown operations in the tree and are forced to pessimistically bail out from analysis of such cases.
2. Fixing this forces the analyzer package to move to a newer API and add logic to handle new operation kinds.

It is understandable that we will have new OperationKinds pop up in the CFG now and then, but they should only be done when absolutely essential and the new operation cannot be lowered into existing operation kinds that already occur in the CFG.

For the newly added patterns, we should instead consider lowering these as follows:

1. `INegatedPatternOperation`. For the below example, INegatedPatternOperation can be completely elimated if the conditional branch jump sense is changed from false to true in the CFG builder:
https://github.com/dotnet/roslyn/blob/85967eb19b20dd86edc5e12446b2e5731429f115/src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_ISwitchOperation.cs#L3674-L3683
2. `IRelationalPatternOperation` can be lowered into an `IBinaryOperation` with the flow capture as the left operand and the relational pattern's value as the right operand.

**Comment by mavasani** [comment]
Seems like there are two additional patterns introduced in the CFG: `IBinaryPatternOperation` and `ITypePatternOperation`. I believe leaving all these different high level pattern constructs in the lowered CFG is against the spirit of a simplified CFG.

**Comment by gafter** [comment]
Since patterns do not have an order of operation specified, there is no single correct lowering. If we wanted to eliminate these operations, we would presumably want to eliminate all pattern-matching constructs altogether from the CFG and simply choose some order of operation when producing the CFG.

**Comment by mavasani** [comment]
Thanks. The operations that are the most complex to handle for each CFG client are `IBinaryPatternOperation` as they have conditional logic within them. No other operation in CFG has any conditional construct, all of these have been lowered into explicit conditional branches between basic blocks. If we could atleast do the same for the `or` and `and` binary pattern operations, that would be tremendous help.

**Comment by gafter** [comment]
They cannot be lowered into conditional branches, for example when placed as nested patterns.

Property patterns and positional patterns also contain implicit "and" operations... for example, in property patterns each (all) of the properties named must match the corresponding pattern. Why are the binary patterns a problem but the property and positional patterns are not a problem?

**Comment by mavasani** [comment]
> Why are the binary patterns a problem but the property and positional patterns are not a problem?

Sorry, I meant any operation that has implicit conditional logic should be converted into lowered/simpler operations without implicit conditional logic. All conditional code should be part of control flow branch condition, not within any operation in the basic block itself.

**Comment by gafter** [comment]
Property patterns imply that each of the named properties must match its corresponding pattern. You could consider that an implicit conditional logical "and" just as much as the new explicit "and" keyword.  So why is one a problem and the other is not a problem?

Since there is no order of operations defined for these patterns, how do you suggest it be lowered? How do you suggest it be lowered when in a nested context (e.g. the pattern inside a property pattern)?

**Comment by mavasani** [comment]
> Property patterns imply that each of the named properties must match its corresponding pattern. You could consider that an implicit conditional logical "and" just as much as the new explicit "and" keyword. So why is one a problem and the other is not a problem?

In that case, even that is a problem for CFG clients. Basically, the contract for CFG is no operations inside basic block with implicit conditional logic. Having such operations makes it impossible for CFG clients to do regular dataflow analysis where operations such as merge only happen at the start of basic blocks with multiple predecessors.

> Since there is no order of operations defined for these patterns, how do you suggest it be lowered? How do you suggest it be lowered when in a nested context (e.g. the pattern inside a property pattern)?

We should follow the approach used by @AlekseyTs when he originally wrote the CFG builder. The order of operations in CFG should match the order of instructions in MSIL when the language does not define the order. We should take a flow capture of the value operation being tested for switch/is pattern operation, then break down complex patterns into simple binary operations with the flow capture reference of the tested value as the left operand and operation to compare as right operand, removing any implicit conditional logic. Personally, I am fine even if order of lowered operations within patterns does not match the MSIL, but I believe this is something @AlekseyTs strongly strived for during the initial feature work.

**Comment by gafter** [comment]
@AlekseyTs Would you please work with @333fred and @mavasani to decide whether pattern-matching should be lowered in the CFG or not?

**Comment by AlekseyTs** [comment]
I think we assume that pattern operations do not have side-effects and arbitrary APIs (methods, etc.) cannot be called directly within a pattern operation. At the same time, the exact order of evaluation is not specified. It feels like an analyzer could be able to treat a pattern as an atomic operation, i.e. branches inside are not that important. If an analyzer needs to track the "state" of the checked object depending on result of the top-level pattern, perhaps specially analyzing patter operations wouldn't be over complicated.
Alternatively, I guess, we could try lower pattern operations into basic blocks using simplified direct translation that doesn't have to match the exact order of evaluation at runtime. However, this mismatch in order of evaluation makes me feel uncomfortable.

**Comment by mavasani** [comment]
>  If an analyzer needs to track the "state" of the checked object depending on result of the top-level pattern, perhaps specially analyzing patter operations wouldn't be over complicated

Thanks @AlekseyTs. That can potentially be done for most complex pattern operations. My primary concern is for complex `IBinaryPatternOperation` trees such as below: https://github.com/dotnet/roslyn/blob/85967eb19b20dd86edc5e12446b2e5731429f115/src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_ISwitchOperation.cs#L3711-L3793

A simple flow based analysis would also need to attach state to each left and right child of the `or` and `and` binary pattern operations and apply all complex state merge and intersect logic for these branches - currently these operations only happen at actual basic block control flow branches, and the analyses also doesn't need to deal with `||` and `&&` logic as these operators never appear in the CFG. It would be great if we could lower out the `IBinaryPatternOperation` and `INegatedPatternOperations`, in the same fashion as `||`, `&&` and `~` operators. I think rest of the pattern operations can be dealt with relative ease by flow based analyzers. Does that sound reasable?

**Comment by AlekseyTs** [comment]
There is an important difference between ```||```/```&&``` operators and patterns. The operators are short-circuiting and have specified order of evaluation, the patterns are not. The primary goal of CFG (Control Flow Graph) is to reflect **the order of evaluation**. With patterns, the order of evaluation is unspecified. What is specified is what conditions should be met for a pattern to be true. In that sense, the tree from the test is accurate, it reflects semantics of the language and order of evaluation. I think, patterns can be considered somewhat similar to non-short-circuiting operators ```&```/```I```. For these operators, both sides are always evaluated and we are not breaking them up into basic blocks. If an analyzer needs to track state across these operators, it cannot rely on basic blocks for that. If we assume that everything in a pattern is always evaluated, this should be a "safe" assumption since we do not expect side-effects, then there is really no difference between ```and```/```or``` patterns and ```&```/```I``` operators. If an analyzer needs to track state within a ```and```/```or``` patterns, then I would expect it to track state within ```&```/```I``` operators as well. And if it knows how to do that, patterns shouldn't be a problem. If state transitions are not tracked within ```&```/```I``` operators, then why does it have to be tracked within ```and```/```or``` patterns?

**Comment by mavasani** [comment]
> I think, patterns can be considered somewhat similar to non-short-circuiting operators &/|. For these operators, both sides are always evaluated and we are not breaking them up into basic blocks. 

Ah, thanks. That makes sense. I will give that a try.

**Comment by mavasani** [comment]
@AlekseyTs Do we want to keep this issue open to track removing `INegatedPatternOperation` from the CFG? For the below example, INegatedPatternOperation in the original issue description can be eliminated if the conditional branch jump sense is changed from false to true in the CFG builder.

**Comment by AlekseyTs** [comment]
> Do we want to keep this issue open to track removing INegatedPatternOperation from the CFG? For the example in the original issue description, it can be eliminated if the conditional branch jump sense is changed from false to true in the CFG builder.

I do not believe we want to do this. It can be inlined into a more complicated pattern and we are not going to try to eliminate it then. I do not believe it is worth special casing this particular case because consumer have to be able to deal with this node anyway.
