### ISSUE TITLE
#if preprocessor directive incorrectly handles enclosed C# verbatim string

### ISSUE THREAD

**Issue by gdivis** [dotnet/roslyn#4726]
To reproduce, just use this code and make sure that DEBUG is set:

    #if !DEBUG
        [Description(@"
        # text")]
        class Test
        {
        }
    #endif

Actually, this produces a CS1024 error because the compiler seems to interpret the "# text" portion of the string as a preprocessor directive.

**Comment by CyrusNajmabadi** [comment]
I'm pretty sure this is by design.  Once the compiler sees the ```#if !DEBUG``` it's going to be in an inactive region.  Once in that state it will continue scanning through the inactive region handling other preprocessor directives, until it finally ends that region (with the ```#endif```).  Inside that region, the compiler has no concept of things a multi-line string literal.

**Comment by gafter** [comment]
We should investigate whether this is a bug or per spec.

**Comment by CyrusNajmabadi** [comment]
From my reading, this is 'per spec'.  The relevant sections are:

```pp-if-section:
    whitespaceopt   #   whitespaceopt   if   whitespace   pp-expression   pp-new-line   conditional-sectionopt

conditional-section:
    input-section
    skipped-section
```

Because 'DEBUG' is defined, then the pp-expression evaluates to ```false```, meaning we'll be in a ```skipped-section```.

The spec then says:

> The remaining conditional-sections, if any, are processed as skipped-sections: except for pre-processing directives, the source code in the section need not adhere to the lexical grammar; no tokens are generated from the source code in the section; and pre-processing directives in the section must be lexically correct but are not otherwise processed. Within a conditional-section that is being processed as a skipped-section, any nested conditional-sections (contained in nested #if...#endif and #region...#endregion constructs) are also processed as skipped-sections.

As such, it is 'per spec' that an error is produced as the compiler is checking that the ```#text``` "pre-processing directives in the section must be lexically correct".  As ```#text``` is not a legal pp-directive, the error is appropriate.

**Comment by gdivis** [comment]
Fair enough; per the spec I agree that this can't be considered a bug. Nonetheless it is rather unintuitive behavior - requiring pre-processing directives to be "lexically correct" while declaring that they are unprocessed goes contrary to what one would expect - that everything is skipped until the #endif directive is encountered at the beginning of a line. Sounds like my problem is actually with the spec and not the implementation :)

All that being said, this was a rather odd scenario that popped up and was easy to work around. Thanks for looking into it.

**Comment by gafter** [comment]
When commenting out a block of code, I recommend using line-ending comments. In VS, select the code to be commented out and hit control-K control-C. To uncomment a block of code select it and hit control-K control-U.

I acknowledge that this doesn't help in your scenario, where you want the code commented or not depending on a PP-symbol.

**Comment by gdivis** [comment]
Agreed on the line-ending comments; I'm a big fan of ctrl-K,C. This was literally a case of production code having a C# verbatim string inside a skipped block with a line that happened to begin with #. I can't imagine that this is a very common use case, but I wanted to at least report this behavior in case it wasn't intended. Again, thanks for taking the time to check this out and explain it to me.

**Comment by CyrusNajmabadi** [comment]
I think it's so you don't end up accident writing something like:

#els

in the middle of your skipped section. With the current spec approach, you'll get a nice error here and you can fix the directive.

    -- Cyrus
________________________________

**Comment by diryboy** [comment]
This is similar to
```C#
/*
var s = "*/"
*/
```
Ops

**Comment by NickCraver** [comment]
Can we open this back up to see if it *should* be "by-design" (on the spec side)? This bit us when building Stack Overflow when a debug section had some markdown inside a string. I don't really think markdown in a string is *insanely* uncommon - I'd imagine quite a few people will hit this over time for that and other use cases...and it's not at all intuitive as to why Roslyn suddenly breaks here.

**Comment by CyrusNajmabadi** [comment]
@NickCraver 

> and it's not at all intuitive as to why Roslyn suddenly breaks here.

Could you explain what you mean by this?  It sounds like you're saying one of two things here:

1. It's not intuitive why Roslyn breaks *versus* the pre-Roslyn compiler.
2. It's not intuitive why C# has this behavior at all.

If the former, this should not be the case.  We should have the same behavior as the pre-Roslyn compiler.

If the latter... well, it's in the eye of the beholder.  It's intuitive for me.  The compiler is in preprocessor-translation mode.  And it sees an invalid preprocessor directive.  So it dies.  Makes sense to me :)

**Comment by svick** [comment]
@CyrusNajmabadi I'm not sure "is intuitive to compiler implementer" is the right goal. I think that normal developers are not going to think like that.

To me the intuitive behavior is "surrounding any piece of code with `#if` will just work". Maybe it's not possible to reach that (e.g. what if there's `#endif` inside the string literal?), but getting closer sounds like a worthwhile goal to me.

**Comment by NickCraver** [comment]
Sorry, busy days here lately :) It's definitely the latter - surrounding a chunk of code with `#if <directive>`/`#endif` for example should *just work*. Most developers won't understand why this broke without digging a little. 

This gets further complicated in our case because we do compile-time replacement of strings for localization. That wasn't the case hit here (it was simple markdown), but the fact that a string our translators give us can just break builds one day is a little scary. I simply think we can do better here.

**Comment by CyrusNajmabadi** [comment]
It would be unintuitive to me to try to understand why a ```#elseif``` was not working.  Today the compiler will helpfully tell me that ```#elseif```` is wrong (and I should use ```#elif``` instead).  

Either way has pros and cons.  The current approach has the benefit of telling when I do things wrong, but impeding you if you use pp directives in multi-line string literals.  The approach you suggest allows for multi-line string literals, but means I don't get good feedback about when i'm doing things wrong.

**Comment by gafter** [comment]
@NickCraver Do you have a specific proposal for changes to the language specification? Absent a proposed alternative, I don't see what the value would be in reopening the issue. The current spec and all implementations agree, and we would not be likely to take a change that could break existing programs.

**Comment by NickCraver** [comment]
@CyrusNajmabadi Indeed, that's not the error we're talking about here though. Any multi-line string that has a line starting with `#` will result in this:
> error CS1024: Preprocessor directive expected

That's *far* less intuitive than information errors from actually using a directive incorrectly. The surface area for hitting such a thing is much larger. In our case it's markdown, for others it may be a PowerShell comment, etc. I'm not sure how excluding multi-line strings (which admittedly may be *very* non-trivial) would prevent your case of good informational errors with misused directives. I think the problem here is identifying what *is* a directive, a step before that.

**Comment by diryboy** [comment]
If verbatim strings are accounted for, what about normal and interpolated strings? What about multiline comments?

**Comment by agocke** [comment]
@NickCraver @diryboy Let's be clear here -- there is no source code inside inactive `#if` directives. Nothing is parsed, compiled, analyzed -- *anything*. Excluding strings inside directives has no meaning because there's no such thing as a string, just a block of text that may or may not contain preprocessor directives.

I think any proposal needs to start from there and any assumptions it implies, including that people could have entire files containing inactive `#if` blocks consisting of nothing but kilobytes of line noise.

**Comment by paul1956** [comment]
VB seems to require the # start in the first column (at least by default it auto formats it that way removing all the whitespace), but then as @agocke says the false clause is just a blob of text. What seems confusing to me is if I change True to False then the error appears at the #Else instead of the #End If. Since you are forced to have the # as the first character of the line why not change the grammar to require it and then most/all of the issues with # appearing in strings goes away except when the # is the first character. Alternatively there should be some kind of escape for # that allows it to be ignored when on the false side and treated as a # when on the true side. If I have to edit one side or the other every time the condition changes the preprocessor directive is less useful. There could then be a Analyzer and Fix to detect and fix these corner cases.
```
#If TRUE Then
        Dim x As String = "
         #End If"
#Else
        Dim x As String = "
#End If"
#End If ' Error here because previous part of line is taken as a Preprocessor string 
```

**Comment by gafter** [comment]
If the `#` were "ignored" in the false side, how would the false side ever end?

**Comment by agocke** [comment]
> Since you are forced to have the # as the first character of the line

C# Spec Section 2.5:

> `White space may occur before the # character and between the # character and the directive name.`

**Comment by paul1956** [comment]
@gagter I was proposing the use of an escape character before the # so that it could be ignored in the cases sited.

@agocke I was talking about VB which has the same issues and Visual Studio removes any leading white space so it ignored the spec assuming it shares that grammar with C#.

**Comment by agocke** [comment]
@paul1956 Pick any escape character you want that's not whitespace. As long as there is a non-whitespace character before `#` it isn't regarded as the start of a directive.

**Comment by paul1956** [comment]
@agocke how does that help. The compiler doesn't understand it. I would have to remove it every time the condition changed.
In the True clause I need # and in the False clause I need escape# for everything to work correctly in both clauses. When the condition changes I need to move the Escape so it is always in the False clause only.

**Comment by agocke** [comment]
@paul1956 In the True case no escape could possibly help because the example given is nested inside a verbatim string literal.

**Comment by paul1956** [comment]
@agocke I am not trying to engineer a solution just saying the is a real issue that should not be so easily dismissed.

**Comment by AraHaan** [comment]
I got this issue on the C# Compiler in VS2017 when debug is not set too.

**Comment by gafter** [comment]
Issue moved to [dotnet/csharplang #1230](https://github.com/dotnet/csharplang/issues/1230) via [**ZenHub**](https://www.zenhub.com/)
