### ISSUE TITLE
Introduce local mangles formatting

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/roslyn#47277]
**Version Used**: 3.6.0-beta1-20111-10

**Steps to Reproduce**:

Seen in the CPS solution

1. Code:

    ```c#
    new List<Action>
    {
        () =>
        {
            Array.Empty<string>().Count();
        }
    };
    ```
2. Select `Array.Empty<string>()`
3. Invoke "Introduce local"

**Expected Behavior**:

Code formatted correctly:

```c#
new List<Action>
{
    () =>
    {
        string[] vs = Array.Empty<string>();
        vs.Count();
    }
};
```

**Actual Behavior**:

Generated code has strange formatting.

```c#
new List<Action>
{
    () =>
    { string[] vs = Array.Empty<string>(); vs.Count();
    }
};
```

**Comment by BaileyFirman** [comment]
Hi there @sharwell , I haven't contributed before but I'd like to give this one a go is that okay?

**Comment by CyrusNajmabadi** [comment]
@BaileyFirman yup. Go ahead!

**Comment by BaileyFirman** [comment]
Hi @CyrusNajmabadi I did manage to work out a fix but it's to much of a hack right now to make a PR I feel.
[My Fix so far](https://github.com/dotnet/roslyn/compare/master...BaileyFirman:baileyfirman/47277).
I think the issue is in `CSharpIntroduceVariableService_IntroduceLocal.cs` around the check to see if the block {}'s are on the same line (L56). If they aren't on the same line a newLineCarrageReturn is added to the **declarationStatement's** trailing trivia, I think further down in the processing of the block the presence of the .Count() prevents this trivia from working correctly.

If I add some trailing trivia to the **finalInnerMostBlock** (L349) when the {}'s are on different lines, and when the parent is a lambda it fixes the issue. Ideally I would like to check if anything else is called after the array declaration and add the newLineCarrageReturn to the replacement node if something is present.

I could be looking at this all wrong however 😅 I'll keep trying some other things but if you or anyone else has some suggestions please do let me know.
