### ISSUE TITLE
Nullable warning isn't emitted when passing default to a struct parameter

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#47346]
Repro:

```csharp
using System;
#nullable enable

public class Person
{
    public string Name { get; }
    
    public Person(string name) =>
        Name = name ?? throw new ArgumentNullException(nameof(name));
}

public struct MyStruct
{
    public Person person;
}

public static class Program
{
    public static void Foo(MyStruct s)
    {
        Console.WriteLine(s.person.Name);
    }
    
    public static void Main() => Foo(default); // Expected warning here. Because MyStruct contains a non-nullable reference type.
}
```

The previous example throws NullReferenceException.

I think any struct containing a non-nullable reference type should have a warning when it takes the value "default".

**Comment by sharwell** [comment]
This is blocked on the concept of non-defaultable value types being part of the language.

**Comment by Youssef1313** [comment]
@sharwell Can you provide more info on that please?

**Comment by sharwell** [comment]
https://github.com/dotnet/csharplang/issues/99#issuecomment-601792573

**Comment by Youssef1313** [comment]
> 
> 
> [dotnet/csharplang#99 (comment)](https://github.com/dotnet/csharplang/issues/99#issuecomment-601792573)

Is that feature planned to be in C# 10? or no plans on it yet?

**Comment by Youssef1313** [comment]
@jaredpar @sharwell Should this be closed as by-design like https://github.com/dotnet/roslyn/issues/48546? or marked as blocked based on https://github.com/dotnet/roslyn/issues/47346#issuecomment-685149700?

**Comment by jaredpar** [comment]
The current behavior is "By Design". 

I wouldn't classify this as "blocked" because generally I associate that with bug fixes or design decisions. Essentially I internalize "blocked" as "yes this is a bug but we can't make progress due to a related work item or decision from LDM". 

In this particular case though the language is operating as designed. The use of `default` with `struct` is a known hole in the C# nullable analysis, similar to `null` in array elements. The referenced [csharplang issue](https://github.com/dotnet/csharplang/issues/99) isn't a proposal to change this design. Rather it's a proposal to add a new feature which users could then take advantage of to *potentially* work around this hole.

**Comment by Youssef1313** [comment]
> The current behavior is "By Design".
> 
> I wouldn't classify this as "blocked" because generally I associate that with bug fixes or design decisions. Essentially I internalize "blocked" as "yes this is a bug but we can't make progress due to a related work item or decision from LDM".
> 
> In this particular case though the language is operating as designed. The use of `default` with `struct` is a known hole in the C# nullable analysis, similar to `null` in array elements. The referenced [csharplang issue](https://github.com/dotnet/csharplang/issues/99) isn't a proposal to change this design. Rather it's a proposal to add a new feature which users could then take advantage of to _potentially_ work around this hole.

That's clear enough. Let me close.
