### ISSUE TITLE
Internal code comments are put in triple-slash doc comments

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#47366]
https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.syntaxnode.findnode?view=roslyn-dotnet

> Remarks
> TODO: This should probably be reimplemented with ChildThatContainsPosition(Int32)

I don't believe such a comment should be a doc comment.

There will probably be more occurrences of this. At least, I'd search with `///.+?TODO` regex in the repo to detect some of these issues.

**Comment by sharwell** [comment]
The documentation comment allows the comment to be validated for `cref` accuracy, and also work with features like Find All References. You can use a `<devdoc>` element instead of `<remarks>` if you don't want the documentation to appear in public API documentation, but non-public APIs can use `<remarks>` for anything that might be useful from Quick Info.
