### ISSUE TITLE
Operator overloading of concrete IDictionary, IReadOnlyDictionary and both is inconsistent depending on whether the type arguments of the interfaces are concrete

### ISSUE THREAD

**Issue by Happypig375** [dotnet/roslyn#47378]
**Version Used**: latest master (e7bad77)

**Steps to Reproduce**:
https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxAgrgOwD4AEAMABLgIwAsA3ALABQuAzMQEyEDChA3rYT8Y6QDZiZQgFkAFAEkAIgEsAxjFkB7TBAQBPADyl8SYiXwA+QgA8AlIQC8J0gDpSATnEAiEi/PUavPgaG4RCUkAJTgIABMAeUwAGw05RRU1TR1DfV0TC2tbEgcSZxcmDy8fBj9hMS0AFSNxKrNLAHcAC0Q4QnqQQhkFJVV1bV10wyN9ELCo2PjepIHUvQNjbIM8gvpi7l4ywQrRJmqAaTgNfSqANQgY9DhansT+lKqjk46Lq5uG5fsnV3dPTZ42xI/kC+yex1Ob2ut1CEWicQSfWS2nBL3Ol2hnxsKx+hQ23i2/GBuzBp2ekIxNzqnxabQ6hC6dyRc1RFPeo26sMmCJmDxR5NelJM2O++Vc63+BMBTBY2IkmDgjUIiNmKSGi1q5klAF8gA=

Change the call in `Main` from `M` to `M2`.

**Expected Behavior**: The output stays the same: `3` regardless of `M` and `M2`.

**Actual Behavior**: `3` is outputted when calling `M`, and `error CS0121: The call is ambiguous between the following methods or properties: 'C.M2<TKey, TValue>(IDictionary<TKey, TValue>)' and 'C.M2<TKey, TValue>(IReadOnlyDictionary<TKey, TValue>)'` when calling `M2`.

**Comment by svick** [comment]
The output can't be 3, [if you comment out the first two `M2`s](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxAgrgOwD4AEAMABLgIwAsA3ALABQuAzMQEyEDChA3rYT8Y6QDZiZQgFkAFAEkAIgEsAxjFkB7TBAQBPADyl8SYiXwA+QgA8AlIQC8J0gDpSATnEAiEi/PUavPgaG4RCUkAJTgIABMAeUwAGw05RRU1TR1DfV0TC2tbEgcSZxcmDy8fBj9hMS0AFSNxKrNLAHcAC0Q4QnqQQhkFJVV1bV10wyN9ELCo2PjepIHUvQNjbIM8gvpi7l4Aei2ywQrRJmqAaTgNfSqANQgY9DhansT+lKrT847r2/uG5fsnV3cnk2PB2exI/kCR1eZwunzuD1CEWicQSfWS2mh7yuN3hPxsK3+hQ23l4YIhYihFzesJx9zqPxabQ6hC6jzRc0xNK+o26iMmKJmzwx1I+tJM+L++Vc6yBJJ4uCYLHxh3EmDgjUIqNmKSGi1q5llAF8gA), you get:

> error CS0411: The type arguments for method 'C.M2<T, TKey, TValue>(T)' cannot be inferred from the usage. Try specifying the type arguments explicitly.

And since it can't be the third overload, what remains is an ambiguity between the first two overloads.

**Comment by jaredpar** [comment]
This behavior is by design. The issue here is that C# doesn't support this type of inference. Here is a more concise sample that shows the problem:

```cs
using System.Collections.Generic;
public class InferenceExample {
    void M<T, TElement>(T t) where T : IEnumerable<TElement> { }
    public void Go() {
        M(new List<int>()); // Fails to infer TElement
    }
}
```

The language rules don't allow the inference of `TElement` here through the relationship defined in the constraint. Hence the method `M` is essentially uncallable without explicitly specifying the generic arguments. The same is the case with the last overload of `M2` that you defined.

```cs
public static void M2<T, TKey, TValue>(T x) where T : IDictionary<TKey, TValue>, IReadOnlyDictionary<TKey, TValue> => System.Console.WriteLine("3");
```

Given that this method isn't an option, the language is left with the other two overloads of `M2` which are ambiguous.
