### ISSUE TITLE
(CSharpScript + linq + await) will compile errors!

### ISSUE THREAD

**Issue by Dogwei** [dotnet/roslyn#47411]
**Version Used**: 

Rolsyn: 3.7.0
.NET Core: 3.1

**Steps to Reproduce**:

```C#
public static class Helper
{
    public static async ValueTask<List<T>> ToListAsync<T>(this IEnumerable<T> enumerable)
    {
        var list = new List<T>();

        if (enumerable is IAsyncEnumerable<T> asyncEnumerable)
        {
            await foreach (var item in asyncEnumerable)
            {
                list.Add(item);
            }
        }
        else
        {
            foreach (var item in enumerable)
            {
                list.Add(item);
            }
        }

        return list;
    }
}

public class Program
{
    public int[] Area { get; set; } = new int[] { 1, 2, 3, 4, 5 };

    public static void Main()
    {
        var result = CSharpScript.RunAsync(@"

using System.Linq;

/* This sentence will be wrong when compiling! */
return await (from a in Area select a).ToListAsync();

/* And this sentence will not. */
//var linq = from a in Area select a;
//return await linq.ToListAsync();

",
            ScriptOptions.Default.AddReferences(typeof(Program).Assembly),
            new Program()).Result;

        if (result.Exception is Exception exception)
        {
            throw exception;
        }

        Console.WriteLine($"ReturnValue : {result.ReturnValue}");
    }
}
```

**Expected Behavior**:

Compile normally!

**Actual Behavior**:

Compile error!

**Comment by Dogwei** [comment]
![微信截图_20200903124553](https://user-images.githubusercontent.com/14845492/92072268-71c02b80-ede3-11ea-957b-43956c0fbe0a.png)

**Comment by svick** [comment]
As far as I can tell, the problem is that in a script, the compiler assumes you're not in an `async` function and so it prefers to treat `await` as a regular name, if possible.

And `return some_name (from a in Area select a).ToListAsync();` could be valid code, so `await` is treated as a regular name there.  
But `return some_name linq.ToListAsync();` can't possibly be valid, so `await` is treated as a keyword.

I'm not sure if this is the expected behavior and if it isn't, how to fix it.

**Comment by svick** [comment]
@Dogwei @tmat Since this is marked as a bug, I think it should stay open.

**Comment by Dogwei** [comment]
Sorry, I thought this bug was fixed and I forgot to close this issue.🤣
