### ISSUE TITLE
CSharpSyntaxTree.ParseText not returning MethodDeclarationSyntax

### ISSUE THREAD

**Issue by parxal** [dotnet/roslyn#47449]
**3.7.0**: 

**Steps to Reproduce**:

```
string method = @"
                 public void test()
                 {{
                 	Console.WriteLine(""Hello World"");
                 }}
                 ";
SyntaxTree syntaxTree = CSharpSyntaxTree.ParseText(method);
IEnumerable<SyntaxNode> syntaxNodes = syntaxTree.GetRoot().DescendantNodes();
MethodDeclarationSyntax methodDeclarationSyntax = syntaxNodes.OfType<MethodDeclarationSyntax>().FirstOrDefault();

```
**Expected Behavior**:
methodDeclarationSyntax should have a value. It works on 3.6.0 and older versions.
**Actual Behavior**:
methodDeclarationSyntax is null.

**Comment by Youssef1313** [comment]
This behavioral change could be very related to the new top-level statements feature.
You need to have a class wrapping the method to get MethodDeclarationSyntax as a child of ClassDeclarationSyntax.

**Comment by CyrusNajmabadi** [comment]
This is by design.  when you call ParseText, you are parsing the input the same way the parser would parse a complete file.  IN that case, this is not a method declaration (which can only exist inside a type).

To parse just a method decl, without needing to surround with anything, call SyntaxFactory.ParseMemberDeclaration.
