### ISSUE TITLE
VS incorrectly handles Checked name in if statement

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#47460]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1173359/vs-incorrectly-handles-checked-name-in-if-statemen.html)._

---
If you have C# class Foo with Checked property and you type

```
var f = new Foo();
if(f.Checked)

```
and press Tab key after you selected Checked from suggestion list then VS incorrectly changes this fragment to 
```
if (f.checked
    {

})
```
Expected behavior is cursor going after closing brace.

---
#### Feedback Bot on 9/4/2020, 01:40 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
This occurs because snippet matching is currently case-insensitive. It should be updated to use the casing rules of the language (e.g. case-sensitive for C#, but still case-insensitive for VB).

**Comment by sharwell** [comment]
After further review, we have decided to mark this as **Won't Fix** due to the difficulty of ensuring that proposed changes do not negatively impact the experience for other users. The recommended workaround is to type over the `)` character by pressing <kbd>)</kbd> or using the **Edit.SmartBreakLine** command (<kbd>Shift</kbd>+<kbd>Enter</kbd>).
