### ISSUE TITLE
Outdated/incorrect XML doc on private method

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#47496]
https://github.com/dotnet/roslyn/blob/e43555357f58252dc623b285aa62a1894d09afe8/src/Compilers/CSharp/Portable/Parser/LanguageParser.cs#L4683-L4700

The comment says it returns "true if not contextual". However, it returns "true" for nint and nuint which are contextual.

Changing the behavior to match documentation breaks tests (https://github.com/dotnet/roslyn/pull/47495).

**Comment by CyrusNajmabadi** [comment]
`nint` and `nuint` are not contextual.  They are semantic identifiers.  A 'contextual keyword' is an identifier that is reiterpretted as a keyword purely based on the syntax surround it.  i.e. `from x in y`.  `from` and `in` are known to be keywords there because syntactically, that's the only legal interpretation.  however, with something like `var x = ...`, then `var` is simply an identifier, and it's up to semantic analysis to decide if what that identifier should mean.

**Comment by Youssef1313** [comment]
@CyrusNajmabadi That cleared it!
