### ISSUE TITLE
Improvement for Display inline parameter name hints

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#47597]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1173604/improvement-for-display-inline-parameter-name-hint.html)._

---
<p>While this feature is great, I think it needs some tweaks to make it better. There are many places where the parameter name is not useful:</p>
<ul>
<li><code>Console.WriteLine(value: &quot;&quot;)</code></li>
<li><code>object.Equals(objA: &quot;&quot;, objB: &quot;&quot;)</code></li>
<li><code>object.ReferenceEquals(objA: &quot;&quot;, objB: &quot;&quot;)</code></li>
<li><code>TimeSpan.FromSeconds(value: 1)</code></li>
<li><code>Task.FromResult(result: 12)</code></li>
<li><code>TaskCompletionSource.SetResult() / TrySetResult()</code></li>
<li><code>ConfigureAwait(false)</code> I’m pretty sure people knows what the value is, and the name of the parameter is very long.</li>
<li><code>int.TryParse(s: &quot;42&quot;, out _)</code> Any single-ascii-character parameter name</li>
<li><code>EnableXXX(bool)</code> The parameter is for enabling or disabling something, but it’s name is already part of the method name or named “value”</li><li>Math.Max(val1: 1, val2: 2) from the doc <a href="https://docs.microsoft.com/en-us/visualstudio/ide/reference/options-text-editor-csharp-advanced?view=vs-2019#editor-help">https://docs.microsoft.com/en-us/visualstudio/ide/reference/options-text-editor-csharp-advanced?view=vs-2019#editor-help</a></li>
</ul>
<p>That’s just the ones I can see in my code right now. Maybe you could allow disabling per method/parameter using a configuration file (.editorconfig?) as there will always be project specific cases that you may not support.</p>
<p>Another idea: make the parameter name easily convertible to an actual named parameter in the source code. Maybe clicking on it could open the suggested actions menu where you can already add the parameter name.</p>

---
#### Feedback Bot on 9/4/2020, 02:50 AM: 

Thank you for taking the time to provide your suggestion.&nbsp; We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.

**Comment by CyrusNajmabadi** [comment]
Taking for next meeting for us to discuss what sort of heuristics might help out here.  @akhera99 If you're interested, we can try to find a way to let you attend :)

**Comment by jinujoseph** [comment]
cc @jasonmalinowski

**Comment by mavasani** [comment]
# Design Meeting Notes

- Other IDEs has a fully configurable way for end users
- Need to find a balance between adding user configurable actions versus adding some default exclusions if it makes sense for all users
	○ Should we identify these exclusions at each API level OR try to define rules based on signatures that identify these exclusions
- Toggle mode: Add a binding key so the adornments toggle on/off with the key press
	○ Will the toggle mode turn the feature off by default? If so, concerned about feature cut back
	○ Toggle doesn't help for cases where we know for sure we have certain cases that should be excluded, e.g. ConfigureAwait
- We can potentially do all things - toggles + options + default exclusions
- Touch base with @jcouv  who implemented an analyzer for this to gauge the noisy APIs - https://github.com/dotnet/roslyn/issues/43988 and discussion on https://github.com/dotnet/roslyn/pull/22010 for context.
- Don't shoot for 100% case, it is fine if our heuristics are good enough for 98% of users
	
**Conclusion:**
- @CyrusNajmabadi will champion the work to come up with an appropriate heuristic for default exclusions for parameter name hints feature.
- Toggle functionality is tracked with a separate feature request: https://github.com/dotnet/roslyn/issues/47765
- If required in future, @mavasani can champion the work to add end user option to exclude custom symbols from this feature

**Comment by CyrusNajmabadi** [comment]
Tagging @jcouv .  Julien, in teh past you tried to create a rule to enforce named parameters for method calls.  Do you recall teh set of rules you had to come up with to not make it too noisy?

**Comment by jcouv** [comment]
We ended up not using such enforcement. But the rule that seemed the most acceptable: require named parameter for literals, disable the enforcement in test files (too many APIs using `null` literals but not needing to be named).

**Comment by CyrusNajmabadi** [comment]
We did a few of these here:

![image](https://user-images.githubusercontent.com/4564579/96505864-9180a700-120b-11eb-835c-7ccf24740f42.png)

So i'm going to close this out.  If we find other areas where we can improve things, i think we cna open individual bugs on those.

**Comment by jameslear** [comment]
I'm not sure what the protocol is for commenting on closed issues, but I had a simple suggestion that might help in a few circumstances: suppress hints when there is only one parameter.

Please let me know if I need to create a separate feature request.

**Comment by Jehoel** [comment]
@jameslear as a counter-example, having the name-hints is useful for single-parameter methods when the parameter name indicates the overload being used.

My main request is for `ConfigureAwait` to be exempted, because seeing `continueOnCapturedContext:` really doesn't add any value here:

![image](https://user-images.githubusercontent.com/1693078/121459131-8bd4fe80-c95f-11eb-94be-e6959b5c7736.png)

----

As a quick workaround, I might see if I can add a toolbar button to VS that would toggle this (genuinely useful!) feature on-and-off - [like the "Just My Code" button extension](https://marketplace.visualstudio.com/items?itemName=SamHarwell.JustMyCodeToggle) - which is maddening it's not built-in to VS.

**Comment by Jehoel** [comment]
@CyrusNajmabadi I just noticed the `Alt+F1` keyboard shortcut in the Options window now - unfortunately it doesn't seem to work at all for me (VS2019 16.10.1). It also differs from your screenshot from last year where it says it's `Ctrl+Alt`.

I checked my VS Keyboard shortcuts listing and `Alt+F1` isn't mapped to anything. I also searched the entire commands list for "hints" and "parameters" and nothing relevant came up, so is that a bug then?

------

![image](https://user-images.githubusercontent.com/1693078/121459735-a5c31100-c960-11eb-9f7b-bc47d1b9eef8.png)

Observe:

* Searching for "hint" doesn't return any relevant commands.
* The `Alt+F1` shortcut's "Currently used by" combobox is empty, indicating it's not currently bound to anything.
* Also, if you look at my screenshot at 1:1 zoom you'll notice graphics corruption (weird white borders and ghosted text - this is something I've been experiencing since mid-2020 in VS2019 when some unrelated changes were made to the VS Options window - is this a known issue? It happens if I unfocus the Options window, mouse-hover it and then give it focus back, it's really weird, but it happens across machines with completely different graphics stacks, so I guess it's a glitch in VS's WinForms-in-WPF code?
