### ISSUE TITLE
Add C# refactoring for invert boolean

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#47602]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1167350/add-c-refactoring-for-invert-boolean.html)._

---
For boolean variables there should be a refactoring option which inverts all usages of it. (i.e. add `!` in front of all usages of it / assignments to it and then simplifying any `!! ` or `!false`/`!true`... I might be forgetting some other cases.) Also, it should trigger a rename refactoring.

For example, maybe you have a variable named something like `isEmpty` and then after writing some code decide it makes more sense to write `hasAny`.

(This refactoring is available in ReSharper.)

---
#### Feedback Bot on 8/31/2020, 03:07 AM: 

Thank you for taking the time to provide your suggestion.&nbsp; We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.

**Comment by dibarbet** [comment]
Design review:
We would take a feature that operates in the following manner
1.  The refactoring is offered on the boolean declaring identifier.
2.  We invert all usages of the boolean (reads and writes).
3.  Uses existing helpers to simplify conditional logic in usages where necessary.
4.  Add a rename annotation to the usages so that it can be renamed.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
