### ISSUE TITLE
MemberNotNullWhen null tracking not working with generics

### ISSUE THREAD

**Issue by kofifus** [dotnet/roslyn#47667]
**Version Used**: 16.8.0 Preview 2.1 `<TargetFramework>net5.0</TargetFramework><LangVersion>preview</LangVersion> <Nullable>enable</Nullable>`

**Steps to Reproduce**:

Consider first the non generic example that works correctly:
```cs
class GetResult {
    [MemberNotNullWhen(true, "Value")]
    public bool OK { get; set; }
    public Manager? Value { get; set; }
}

record Manager(int Age); 

class Archive {
  readonly Dictionary<string, Manager> Dict = new Dictionary<string, Manager>();

  public GetResult this[string key] 
    => Dict.TryGetValue(key, out var value)
          ? new GetResult {OK = true, Value = value}
          : new GetResult {OK = false, Value = null};
}

public class C {
    public void M() {
        Archive archive = new Archive();
        
        GetResult result = archive["John"];
        if (!result.OK) return;
        int age1 = result.Value.Age; // NO WARNING HERE - CORRECT
    }
}
```
Now almost the same code with generics:
```cs
class GetResult<T> {
    [MemberNotNullWhen(true, "Value")]
    public bool OK { get; set; }
    public T? Value { get; init; }
}

record Manager(int Age); 

class Archive {
  readonly Dictionary<string, Manager> Dict = new Dictionary<string, Manager>();

  public GetResult<Manager> this[string key] 
    => Dict.TryGetValue(key, out var value)
          ? new GetResult<Manager> {OK = true, Value = value}
          : new GetResult<Manager> {OK = false, Value = null};
}

public class C {
    public void M() {
        Archive archive = new Archive();
        
        var result = archive["John"];
        if (!result.OK) return;
        int age1 = result.Value.Age; // WARNING HERE - Dereference of a possibly null reference
    }
}
```

**Expected Behavior**:

The second generic version do not give a warning when accessing result.Value (in the same way as first non generic version)

**Actual Behavior**:

The second generic version gives a "Dereference of a possibly null reference" warning when accessing result.Value

**Comment by kofifus** [comment]
Thanks! the code no longer compiles on the main branch

see: [sharplab](https://sharplab.io/#v2:EYLgtghgzgLgpgJwD4AEAMACFBGALAbgFgAodLbAOgBEBLCAcwDsB7WGgYygoGFmATOAEFGEADYBPKDShFiJEgGJGAV1GiIwUXAxwRmuPOIiwcKAAcI7bTgoAlZYxg0TPZmDM0tCAMqIAbhymJADeJBjhWADMWABMGACSUACiAB7wCCKi8Yw0MMEAviSFciUocQDicDC2pqowADwAKgB8GKHEERgA2gCycGDAiAByzDBDqqIA6gAWugAUMAjKcAA0GABEAGpiy+sAlAC6YREo0cDMzKIYAPIA0m0Y9FX4GFDPGMWdpxiNAPwY21EyweTxgLxoOTBHyKhgQcHYzAQfAwPQgIieCDmEJgGEETz2L0MZVxCHY0xofm07XCcIgfGYjAkGFo7CcDIgCHE9RwaDWqPRiFaLJxAF4MIw4AB3ZkcNkiTnc7C8lFohiCuYEwzhb6Vaq1UQNflqhCtGDkqBdHkYADWcHEBwwx3CIqFsoojU5usByzmtvEa2Yyhxfg5GBDQLgeydnQi/wl0t1NSgdXqRoxrWCdwwYsWyzW3u0YvDy0+Mc6IHFUowif1htV6baWbFADMxG98ztC+KJvlZMUSN9idw2tHB7gURqRx0yySyRTtBy55Ts5XpYJSeTKRrZDPHdOyyGEBg4cmDSvF5u4F11gApZjTRjrA47mc0ZsYOYAQhPdQodz2WAAOwvmW2IYGq2Arj+BoUAWFB4nALwAPRIRgkyCLYQzxEM5QYAAEkkthJBgAC0zKIHAzYUYwVgYMw74QBgZisFImjiN2ajHpR1FWNGxT5EAA)

I get:

> error CS0122: 'MemberNotNullWhenAttribute' is inaccessible due to its protection level

Any help ?

**Comment by RikkiGibson** [comment]
Seems like maybe an issue with sharplab and the SDK it's consuming (possibly out of date)? It works when the attribute is explicitly declared [(link)](https://sharplab.io/#v2:EYLgtghgzgLgpgJwD4AEAMACFBGALAbgFgAodLbAOgBEBLCAcwDsB7WGgYygoGFmATOAEFGEADYBPKDShFiJEgGJGAV1GiIwUXAxwRmuPOIiwcKAAcI7bTgoAlZYxg0TPZmDM0tCAMqIAbhymJADeJBjhWADMWABMGACSUACiAB7wCCKi8Yw0MMEAviSFckYQJuaW1pS0DCxsnK4CwmKS0iFhESjRKHEAsnBgwIgAcswww6qiAOoAFrqCMDAINMDK8BggGAtLK2sGxBEYoQeHndH9gyNjE2qz84vLq/AAFMDMzKIYULrfADTkmBMlwQwzKcAAlEcMMVDsViiQehgAOJwGC2UyqGAAHgAKgA+I4dcIAbQuQxB10md0YzyWyjg/wARAA1MT0xnggC6RKiGDeHwwAHkANJQ+io/BfCXQnldDA4gD8GFZonpYulNByMElcMMCDg7GYCD4GF6EBE4oQz01MC24vBksMiMECHYMxofm0x3C+ogfGYjAkGFo7CcAYgCHEWJwaH+ZotiAJIdtAF4MIw4AB3YMcMMiSPR7Cx03mhiJ54OwzhOUotEY0TY+NlhAEmDuqDEmMYADWcHEnIwPJTSdzFBxkdrKvpz174n+zDWGD8EaXbIhPNOGCVGeztfRUExWKbloJwRFGDTdIZyrXF9XqrgMM3EU2O+RqP3h+PiaO57TADMxD+G8HzvFQ1HyWR4VIbo4m4QkTmrbpcFNCsEOfLZXXdT0MAjN0PW0NM3xdfDPQrWQMI3CJlwQDB9QPBs7zw7C4GJRkAClmBmRhGU5Cjnxof8MGeABCejMQoEVIRQAB2fjNxtXDxWwO9xIbCgpzgChBHFSUAHo9IwKZBFsYZ4mGJEMAACSSWwkgwABaYNEDgf8XMYKwMGYISIAwMxWCkTRxHTSY6Nc9yrB5OEgA==)

Note that the fix is not yet present in SharpLab--it takes some time after merging a change for it to get picked up.
