### ISSUE TITLE
C# Interactive fails to load a netstandard2.1 assembly - System.IO.FileNotFoundException: Could not load file or assembly netstandard, Version=2.1.0.0

### ISSUE THREAD

**Issue by maartenba** [dotnet/roslyn#47778]
**Version Used**: Microsoft (R) Visual C# Interactive Compiler version 3.7.0-6.20412.3

**Steps to Reproduce**:

1. Create a new project targeting `netstandard2.1`

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>

</Project>
```

2. Add any class, for example:

```csharp
using System;

namespace ClassLibrary1
{
    public class Class1
    {
        public string Data { get; }

        public Class1(string data)
        {
            Data = data;
        }
    }
}
```

3. Build the project.
4. Start C# Interactive, either in Visual Studio, JetBrains Rider or on the command line.
5. Reference the compiled assembly:

```
#r "C:\Users\maart\Desktop\ClassLibrary1\ClassLibrary1\bin\Debug\netstandard2.1\ClassLibrary1.dll"
```

6. Use any of the types from the assembly:

```
new ClassLibrary1.Class1("test").Data
```

**Expected Behavior**:

The assembly is loaded properly, and the `Data` property's value is printed to the console.

**Actual Behavior**:

The assembly fails to load, because C# Interactive can't load the `netstandard 2.1.0.0` assemblies.

```
System.IO.FileNotFoundException: Could not load file or assembly 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
  + AsyncTaskMethodBuilder<TResult>.Start<TStateMachine>(ref TStateMachine)
```

**Supporting screenshots:**

![image](https://user-images.githubusercontent.com/485230/93425155-b3f46d00-f8b9-11ea-9499-c83ecca97328.png)

Omitting VS and Rider screenshots, as they use the C# Interactive executable under the hood, and exhibit the same behaviour.

**Comment by PathogenDavid** [comment]
This is happening because the C# interactive and `csi.exe` run on .NET Framework.

![image](https://user-images.githubusercontent.com/278957/93483507-7b0ec500-f8c6-11ea-8f94-105f2aabf2a4.png)

[.NET Standard 2.1 does not support any version of .NET Framework](https://dotnet.microsoft.com/platform/dotnet-standard#versions).

If you're running a preview version of Visual Studio, you can run `#reset core` to restart interactive in .NET Core mode:

![image](https://user-images.githubusercontent.com/278957/93484680-d55c5580-f8c7-11ea-8e3b-e38ba50b129d.png)

**Comment by jinujoseph** [comment]
cc @tmat
