### ISSUE TITLE
Generated C# code uses an obsolete enum member

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#47815]
[SharpLab.io](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQBMQGoA+ABAjAOjwE4AKAIgAk4AbageyQAIB3OhalMgSgG4g===)

```csharp
System.Console.WriteLine("Hello, world");
```

is compiled to:

```csharp
using System;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Security;
using System.Security.Permissions;

[assembly: CompilationRelaxations(8)]
[assembly: RuntimeCompatibility(WrapNonExceptionThrows = true)]
[assembly: Debuggable(DebuggableAttribute.DebuggingModes.Default | DebuggableAttribute.DebuggingModes.DisableOptimizations | DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints | DebuggableAttribute.DebuggingModes.EnableEditAndContinue)]
[assembly: SecurityPermission(SecurityAction.RequestMinimum, SkipVerification = true)]
[assembly: AssemblyVersion("0.0.0.0")]
[module: UnverifiableCode]
[CompilerGenerated]
internal static class <Program>$
{
    private static void <Main>$(string[] args)
    {
        Console.WriteLine("Hello, world");
    }
}
```

SecurityAction.RequestMinimum is obsolete, is it intended to use it?

**Comment by PathogenDavid** [comment]
`SecurityAction` is marked as obsolete because it's part of the partially trusted code infrastructure from .NET Framework that went bye-bye in .NET Core.

In this case the attribute is being added because the assembly was compiled with unsafe blocks enabled, which required full trust under this model.

While the runtime no longer has an understanding of these attribute and it doesn't make any sense for you to use it yourself, it isn't hurting anything for the compiler to emit them in situations where they probably aren't being used.

**Comment by Youssef1313** [comment]
@PathogenDavid So this is the expected behavior?

**Comment by PathogenDavid** [comment]
Correct. It's a legacy thing.

If you poke around, [there's even tests](https://github.com/dotnet/roslyn/blob/6ebca3944998fc585fde2a9a4beff2aa7cb82635/src/Compilers/CSharp/Test/Emit/Emit/CompilationEmitTests.cs#L3939) that explicitly check it is emitted when required.
