### ISSUE TITLE
Unable to Debug RC1 Source Generator

### ISSUE THREAD

**Issue by HurricanKai** [dotnet/roslyn#47837]
**Version Used**: 
dotnet version: 5.0.100-rc.1.20452.10
NuGet version: 3.8.0-3.final

**Steps to Reproduce**:
1. Make a generator project in RC1
2. Add `Debugger.Launch()` anywhere
3. start the build of a project referencing the generator.

**Expected Behavior**:
Debugger Select window to open

**Actual Behavior**:
Nothing happens, I believe the generator runs as it would without the statement.

I'm not sure whether this was just a "bug" fixed in RC1, but then I'd be interested in the recommended way of debugging generators.

**Comment by jmarolf** [comment]
cc: @chsienki

**Comment by PathogenDavid** [comment]
Is the project consuming the source generator using `<LangVersion>preview</LangVersion>`? I ran into a similar issue yesterday and it turned out that my generator was being loaded but wasn't actually running since it seems source generators are still locked behind the preview gate in RC1.

I've tested `Debugger.Launch` and it works as expected on my machine with Compiler version: '3.8.0-3.20458.6 (b446afd3)'. Language version: preview.

**Comment by HurricanKai** [comment]
🤔 Setting the consuming project to `preview` made it work, thanks!
It did work before, but I guess that wasn't intentional.

**Comment by chsienki** [comment]
Glad you figured this out. The change is because previously `<TargetFramework>net5.0</TargetFramework>` was implicitly targeting `<LangVersion>preview</LangVersion>` so you didn't have to opt into that. 

We've now updated `net5.0` to target lang version `9`, meaning to use source generators you have to explicitly opt in with lang version `Preview`. 

We'll be removing this restriction in an upcoming release.
