### ISSUE TITLE
Avoid serializing diagnostics for documents that do not support them

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#47859]
Currently diagnostics are calculated in OOP and sent back to the client that are in documents that do not support diagnostics. These are then filtered out. We should not calculate these diagnostics in the first place.

**Comment by mavasani** [comment]
@tmat I believe this is by design, let me add more context.

There are already multiple places where we bail out diagnostic computation based on `SupportsDiagnostics` API upfront: https://sourceroslyn.io/#Microsoft.CodeAnalysis.Workspaces/Workspace/Host/DocumentService/Extensions.cs,be2bda4138b49837,references

However, we still need to do a post-filtering based on `SupportsDiagnostics` API because an analyzer can report diagnostic on a different document when analyzing a specific document OR it can report diagnostics in compilation end actions when FSA is enabled in documents that do not support diagnostics.

**Comment by sharwell** [comment]
Also related to #34009
