### ISSUE TITLE
IDE0052 false positive when DataMemberAttribute is applied

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#47917]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1188074/ide0052-false-positive-when-datamemberattribute-is.html)._

---
[severity:It's more difficult to complete my work]
If you apply a [DataMemberAttribute] to a field this tells the compiler that the field is used in a data interface / data contract.
Thus, even if the code sets the field to a value and never reads it back, it obviously is because the field, once serialized, must be present in the output (which might be read by something else)
This false positive is a problem because when you "auto-fix" the problem for the whole solution you actually break a lot of data contracts thus breaking the code.

---
#### Feedback Bot on 9/17/2020, 00:13 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 9/21/2020, 03:43 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
I'm going to tentatively mark this as "by design".  The general feeling i ahve is that we should not have special cases for APIs that migth not be clear to users as it could lead to surprising behavior (i.e. a user is confused why they are not getting warnings about  unused members).

In a case like this, i think that suppressing the message is the better way to handle things.  It makes it explicit in source that it's intentional that this member is not used which help with understanding and documentation.
