### ISSUE TITLE
Use lambdas to implement interfaces and abstracts classes that have a single abstract method.

### ISSUE THREAD

**Issue by jmaine** [dotnet/roslyn#4801]
Use lambda's to implement interfaces and abstract classes that have a single abstract method defined.

Example interface.
```
interface Interface {
     Method()
}
```
Example method declaration:
```
void Call(Interface i) {
 //do work
}
```
Using a lambda to implement it.
```
obj.Call(() => { /* work } );
```

**Comment by svick** [comment]
What's the point? You can already use a delegate type for that.

And if you really want to have an interface, you can use both, see for example [the `Comparsison<T>` delegate type](https://msdn.microsoft.com/en-us/library/tfakywbh) and [the equivalent `IComparer<T>` interface](https://msdn.microsoft.com/en-us/library/8ehhxeaf).

**Comment by dsaf** [comment]
I see some level of similarity with #13.

**Comment by dsaf** [comment]
What happens if an abstract class has a private/protected field/property/method?

**Comment by gafter** [comment]
@jmaine Can you provide some motivation for why this change would be worth taking in the language?

Changing the lambda conversion like this would be a breaking change.

**Comment by jmaine** [comment]
Why would it be a breaking change?

**Comment by gafter** [comment]
@jmaine because there are existing types that are single-method interfaces and abstract classes. Therefore we would be adding a conversion that did not exist to existing code. That may make some methods that were previously inapplicable applicable. That could make some method calls that used to work fine into ambiguity errors.

For example

```cs
public interface ISAM { void M(); }
public delegate void DEL();

public class Zippy
{
    public static void Pinhead(ISAM sam) { }
    public static void Pinhead(DEL del) { }
}

class Client
{
    public static void Main(string[] args)
    {
        Zippy.Pinhead( () => {} );
    }
}
```

This is code that would compile and run just fine today, but under the proposed change it would be ambiguous (an error) because both `Pinhead` methods are applicable, but neither is more specific.

My question remains: what is your motivation for this change? How would it improve the plight of programmers? Or are you just suggesting it because Java did things that way? When I proposed the addition of lambda expressions to Java I specified it this way* because, among other reasons, Java does not have the concept of `delegate` types. But C# certainly *does* have the concept of delegate types and so doesn't need this accommodation.

*I specified the lambda conversion for Java to single-method interfaces only, not abstract classes, but the reason for that is a longer story.

**Comment by alrz** [comment]
@gafter 

This can be useful for interfaces that might be implemented by classes (OOP) but you might prefer a concise syntax to inline the implementation (FP), so delegates are not an option here. Local classes could be an alternative in these scenarios but still they are nothing like a single lambda expression.

As for backward compat we can use an attribute like `FunctionalInterface` so it won't break existing code.
```cs

// examples 

[FunctionalInterface]
interface IIterable<out T> {
  IIterator<T> GetIterator();
}

[FunctionalInterface]
interface IIterator<out T> {
  T? Next();
}

[FunctionalInterface]
interface IHandler<in T> {
  bool Handle(T value);
}

// OOP
class Node : IHandler<Message> { 
  Node() {
    // FP
    RegisterHandler(arg => { ... });
  }  
}
// OOP
class List<T> : IIterable<T> { 
  // FP
  public IIterator<T> GetIterator() {
    return () => { ... }
  }
}

// inline an iterable and iterator!
Method(() => () => { ... });
```
Also, sometime a delegate doesn't make sense at all,
```cs
public delegate bool Iterator<T>(out T value); 
```
Since C# is a OOP language in the first place (with functional features) this can be a useful addition to take advantage of best of the both worlds.

Can you please consider reopening this? Thanks!

**Comment by gafter** [comment]
The idea that the presence of an attribute in source would change the semantic meaning of an expression seems like a bad idea.

I am having a hard time imagining any places in my own code or code I've seen where this would improve things. As [the original author of the "single method functional interfaces" approach for Java](http://javac.info/) that ended up being taken into that language, I have a deep appreciation for its value in Java. I am just having a hard time seeing how any effort in that direction for C# would make anybody's life easier.

**Comment by alrz** [comment]
@gafter I think it would be a good addition when you are mixing functional and OO paradigms (which seems to be the direction that C# is following), a delegate cannot be implemented with a class and an interface is not compatible with a lambda expression. Anywho, I think I made my point, if you don't see any value in here, probably I should count on local classes in these situations. :)

**Comment by svick** [comment]
@alrz 
> a delegate cannot be implemented with a class

You can't do `Comparison<int> c = new MyComparisonClass();`, true. But using method group to delegate conversion is almost as good: `Comparison<int> c = new MyComparisonClass().Compare;`.

**Comment by alrz** [comment]
@svick My use case is the other way around, when you have an interface you will have to implement it. there is no way to work this around. I've seen classes like `DelegateWhatever` created just to implement an interface via a delegate. For example,
```cs
// this can't be a delegate because you might need to implement this
interface IHandler<in T> { bool Handle(T value); }
// (1) boilerplate class
class DelegateHandler<T> : IHandler<T> {
  readonly Func<bool, T> handler;
  public DelegateHandler(Func<bool, T> handler) { this.handler = handler; }
  // (2) double-invocation
  bool IHandler<T>.Handle(T value) => handler(value);
}

void RegisterHandler<T>(IHandler<T> handler) { ... }
// (3) additional overload
void RegisterHandler<T>(Func<T, bool> handler) => RegisterHandler(new DelegateHandler<T>(handler));
```
A lambda expression, specially in `return` would be bloody concise compared to this, specifically when you need to do this just once (so there would be no "helper overload"),
```cs
IIterator<T> GetIterator() {
  return () => { ... }; // YAY
}
```
After method references, this is the second feature that I missing from Java.
