### ISSUE TITLE
csharp_style_expression_bodied_methods: only non-void methods

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#48018]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1196184/csharp-style-expression-bodied-methods-only-non-vo.html)._

---
<p>It would be nice to have style option to prefer expression bodies only for methods that actually return a value.  Expression bodies for void functions don't make a lot of sense, since they are not actually expressions. This can cause confusion as the =&gt; without {} implies (at least to me) a return value.</p> <p><b><br></b></p>

---
#### Feedback Bot on 9/24/2020, 00:19 AM: 

Thank you for taking the time to provide your suggestion.&nbsp; We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.

**Comment by CyrusNajmabadi** [comment]
>  Expression bodies for void functions don't make a lot of sense, 

This does make sense and has been supported since we added expression bodies.  Lambdas, local functions, methods, etc. all support this and all support it for the void case :)

> This can cause confusion as the => without {} implies (at least to me) a return value.

this is not true :)

Note: if you want to block `=>` bodies for void members, tehn teh right way to do that is to write an analyzer that enforces that on your own codebase.  :)
