### ISSUE TITLE
Ensure that source generators work with Source Browser and/or Rich Navigation

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#48123]
We should make sure this works with Source Browser and/or Rich Navigation before converting anything that someone might want to search for.

_Originally posted by @sharwell in https://github.com/dotnet/roslyn/issues/48118#issuecomment-700164919_

**Comment by jasonmalinowski** [comment]
@KirillOsenkov: if I wanted to get a sourceroslyn.io instance tested against a branch of Roslyn to see if I'm breaking anything, how would I go about doing that?

**Comment by KirillOsenkov** [comment]
1. `git clone https://github.com/KirillOsenkov/SourceBrowser`
2. (optional) `git checkout SourceRoslynIO` -- master branch works as well but for full fidelity you can use this branch
3. Build.cmd
4. GenerateTestSite.cmd
5. RunTestSite.cmd
6. open http://localhost:5000 or whatever

Bonus points if you can index Roslyn sources, it's trickier ;) See below.

If you want to use MSBuildWorkspace, build Roslyn first and after successful build run this command:

```
J:\RoslynOpen\SourceBrowser\src\HtmlGenerator\bin\Debug\net472\HtmlGenerator.exe Roslyn.sln /serverPath:J:\s=https://github.com/dotnet/roslyn/tree/master /out:J:\Roslyn\index /nobuiltinfederations /federation:https://referencesource.microsoft.com /noplugins
```

But I found that recent builds of Roslyn have broken MSBuildWorkspace (opening Roslyn.sln has errors and no usable compilations). Instead of indexing an .sln using MSBuildWorkspace you can index a .binlog and bypass MSBuildWorkspace entirely. You'll retrieve Csc invocations from the binlog as described here: 
https://github.com/KirillOsenkov/SourceBrowser/wiki/Indexing-.binlogs

To index using a .binlog pass the Build.binlog instead of Roslyn.sln:

```
J:\RoslynOpen\SourceBrowser\src\HtmlGenerator\bin\Debug\net472\HtmlGenerator.exe J:\s\artifacts\log\Debug\Build.binlog /serverPath:J:\s=https://github.com/dotnet/roslyn/tree/master /out:J:\Roslyn\index /nobuiltinfederations /federation:https://referencesource.microsoft.com /noplugins
```

Ping me if I can help with anything!

**Comment by KirillOsenkov** [comment]
Oh, I may have misunderstood. You want to test whether SourceBrowser works when _using_ the latest Roslyn, not when _indexing_ the latest Roslyn.

That's very easy. You should just need to switch to use the NuGet package versions of your choice (and maybe add a custom NuGet feed to find them). Here's a sample commit where I update to Roslyn 3.8.0 beta3:
https://github.com/KirillOsenkov/SourceBrowser/commit/f9077a0df8bfd2561ad70b4da620d3e9f3946c73

Copying Roslyn binaries over to bin\Debug should work as well for testing purposes.

**Comment by jasonmalinowski** [comment]
@KirillOsenkov: the answer is probably both. :smile: We're working on switching some parts of the Roslyn build to use source generators, and it wouldn't surprise me if the indexing process is broken or other things are broken.

**Comment by jasonmalinowski** [comment]
RichNav has been updated as of https://github.com/dotnet/roslyn/pull/49306.

**Comment by Youssef1313** [comment]
@jasonmalinowski Is there anything left for this?

**Comment by sharwell** [comment]
@Youssef1313 Yes, rich navigation is still non functional for source generators. This can be reproduced as follows:

1. Navigate to the following line in the GitHub UI:

 
 
 
 https://github.com/dotnet/roslyn/blob/eddde7cd620f5499c5b3d29fa2e358f94c6f39f9/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Utilities/TypeStyle/CSharpUseExplicitTypeHelper.cs#L47

2. Click on `VariableDeclarationSyntax`

Expected result:

GitHub navigates to the definition of `VariableDeclarationSyntax`.

Actual result:

The use of a source generator to provide `VariableDeclarationSyntax` made it impossible to view the source of `VariableDeclarationSyntax` via the Rich Navigation experience.

**Comment by sharwell** [comment]
@Youssef1313 The problem appears to impact Source Browser (<http://sourceroslyn.io>) in the same way. It is not possible to view the source of `VariableDeclarationSyntax` there.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.  Roslyn doesn't own source-browser.  If they need anything they shoudl request it explicitly, and we can assign a dev/milestone to get it done.
