### ISSUE TITLE
No Intellisense is given while creating property without its matching closing brackets

### ISSUE THREAD

**Issue by conniey** [dotnet/roslyn#4815]
__Steps to Reproduce__
1. Copy code below
2. On line 12, enter . after `this.Source`
```csharp
namespace Test
{
  class Class1
  {
    public string Property1 { get; set; }
    public string Property2 { get; set; }
  }

  class Class2
  {
    public string Property1 { get { return this.Source.Property1; } }
    public string Property2 { get { return this.Source  // No intellisense after entering .
    public Class1 Source { get; set; }
  }
}
```
__Expected__
![image](https://cloud.githubusercontent.com/assets/10136526/9506046/8cf7c7ae-4bfa-11e5-8a2d-2a7ea26061e6.png)

__Actual__
Nothing is displayed

**Comment by Pilchie** [comment]
The problem here is parsing fault tolerance consumes `public Class` and `Source { get; set; }` as two additional `InvalidAccessorSyntax`es inside `Property2`.

We could consider having some lookahead after seeing `public` and popping out of the property context back to the main type member parsing loop to improve things here.

**Comment by Pilchie** [comment]
tag @CyrusNajmabadi @mattwar @gafter
