### ISSUE TITLE
Compiler emits invalid MSIL

### ISSUE THREAD

**Issue by steinmr** [dotnet/roslyn#4828]
I have a problem with the compiler in VS2015. The following code will crash the application with an InvalidProgramException. (But only if /optimize+ is passed). Is this a bug in the compiler, or am I doing something wrong?

**Compiler command line:**
```
"C:\Program Files (x86)\MSBuild\14.0\bin\csc.exe" /nostdlib+ /reference:C:\Windows\Microsoft.NET\Framework\v2.0.50727\mscorlib.dll  /optimize+ /out:App.exe /target:exe Program.cs
```

**Contents of Program.cs:**
```
namespace App
{
    class Program
    {
        static void Main(string[] args)
        {
            int a = 0;
            int b = a + a / 1;
        }
    }
}
```

**Emitted MSIL of the method that fails:**
```
.method private hidebysig static void  Main(string[] args) cil managed
{
  .entrypoint
  // Code size       7 (0x7)
  .maxstack  8
  IL_0000:  ldc.i4.0
  IL_0001:  pop
  IL_0002:  dup
  IL_0003:  ldc.i4.1
  IL_0004:  div
  IL_0005:  pop
  IL_0006:  ret
} // end of method Program::Main
```

**Exception message:**
```
Unhandled Exception: System.InvalidProgramException: Common Language Runtime detected an invalid program.
   at App.Program.Main(String[] args)
```

**Output from PEVerify.exe:**
```
"C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6 Tools\PEVerify.exe" /nologo App.exe
[IL]: Error: [C:\Src\OutsideTFS\RslnBug\RslnBug\App\App.exe : App.Program::Main][offset 0x00000002] Stack underflow.
1 Error(s) Verifying App.exe
```

**Comment by sharwell** [comment]
:bulb: Can you use a fenced code block instead of inline code? It will help readability:

    ```
    code here
    ```

**Comment by steinmr** [comment]
I tried to get it working, but I was unaware that I had to add a newline, fixed now.

**Comment by sharwell** [comment]
@steinmr The IL code seems obviously wrong for this case, even if you aren't targeting .NET 2.0. Does this fail with newer versions of .NET as well, or is it actually producing different code for .NET 2.0?

The `dup` instruction at `IL_0002` duplicates the top operand of the evaluation stack. The stack starts out empty because this is a static method, then the following occurs:

1. IL_0000: the value 0 is pushed onto the evaluation stack
2. IL_0001: the top value on the evaluation stack is removed (leaving it empty again)
3. IL_0002: a duplicate of the top value on the evaluation stack is pushed onto the evaluation stack (except there is no value on the evaluation stack!)

**Comment by steinmr** [comment]
Yes, it produces same same error for 4.0, 4.5 and 4.6.

**Comment by mikedn** [comment]
Yikes, the wonders of optimizing a stack based intermediate language where unused values actually require additional instructions. Since the result of the expression isn't used anywhere the compiler got rid of `add` and consequently popped its operands from the stack. Unfortunately the first operand of add is used by a `dup` inserted by the stack optimizer which now has nothing left to duplicate.

**Comment by KevinCathcart** [comment]
Is this a potential security bug? In general it is usually safer to assume that miscompilations introduce security holes (as was done with the RyuJIT bug), but here I'm not so sure.

In this, we get the `InvalidProgramException`. That is fine.  If there for some reason been another int on the stack, the remaining code would have been a convoluted no-op, so that is fine. What would happen though if we had some other data type on the stack? I think we would get an `InvalidProgramException`, again.

Trying some obvious modifications with potential side effects if it used a bad value from the stack (like an overflow on a checked add) and the code changed to become valid. If it is guaranteed that the invalid code will always be a no-op or raise an `InvalidProgramException`, then I suppose this is just a regular level bug.

**Comment by KodrAus** [comment]
This seems like an edge case that wouldn't appear in 'real' programs to me, but does that make it less worth fixing?

**Comment by chrisaut** [comment]
If its optimizing, shouldn't the entire body have been eliminated instead of just the add? b is never being used, the division by 1 (constant) does not have side effects, and neither does the add.

I'm sure its hard in the general case to eliminate dead code, but this seems as obvious an example as they can possibly get.

**Comment by mikedn** [comment]
@chrisaut Yes, the whole expression should have been eliminated in this particular case but it's not unusual for compilers to be conservative about division, see [OperatorHasSideEffects](https://github.com/dotnet/roslyn/blob/8fdc0214f73fd513e5b513573f8f916e02362961/src/Compilers/CSharp/Portable/CodeGen/EmitOperators.cs#L584). That said, I question the need for such an optimization in Roslyn, I don't think that this kind of code is common enough to warrant the risk.

**Comment by AlekseyTs** [comment]
@VSadov Please take a look. CodeGenerator pops stack local (right operand of +) from the stack before reaching Dup node inside the left operand of the +.

```
        [Fact()]
        [WorkItem(4828, "https://github.com/dotnet/roslyn/issues/4828")]
        public void OptimizeOutLocals_01()
        {
            const string source = @"
    class Program
    {
        static void Main(string[] args)
        {
            int a = 0;
            int b = a + a / 1;
        }
    }";
            var result = CompileAndVerify(source, options: TestOptions.ReleaseExe);

            result.VerifyIL("Program.Main",
@"
{
}
");
```

**Comment by jrmoreno1** [comment]
I have encountered what may be a variation of this bug.

    Public Class Frm
          Public Class BadCompiler
          Public Property Value As Date?
      End Class

      Private TestObj As BadCompiler = New BadCompiler()
      Public Sub IPE()
          Dim o as Object 
          o = TestObj.Value
      End Sub
    End Class

Compiled in release mode with optimizations on, IPE is invalid. 

Can anyone verify that it is related, or should it be reported as it's own bug?

**Comment by AlekseyTs** [comment]
@jrmoreno1 This issue is closed and it was about C#. If you can reproduce your problem with the current bits, please, open a separate issue. Include the invalid IL if you can. Thanks.
