### ISSUE TITLE
Intellisense should not a complete match in favor of a prefix match when typing commit characters

### ISSUE THREAD

**Issue by dpugh** [dotnet/roslyn#48370]
If I create a toy C# console application, delete the usings, and type "Console." in Main, ConsoleApp1 gets completed in favor of Console (which is what I actually typed), even though Console was in the completion list.
![completion](https://user-images.githubusercontent.com/11394666/95267197-8714e500-07e9-11eb-9e0b-c266e0eae4d2.png)

I understand the desire to avoid silently importing usings but, In this case, here, I don't want completion and there is no easy way not to get it (short of typing escape to dismiss completion before typing ".").

I'm not sure what would be the best solution here but it seems wrong to have completion override the user's typed text (e.g. Console.) without good reason, especially when the behavior is inconsistent (getting ConsoleApp1. if there is no using and Console. if there is). I could see treating <tab> and a completion character differently but that is pretty ugly from a consistency point of view too.

**Comment by CyrusNajmabadi** [comment]
This is intentional and appropriate.  THe "Exact match" is to a namespace *not* in scope.  We do *not* want to match to tehse when there are valid prefix names in scope.  We explicitly did this because we had the previous behavior and it aggravated people to no end as it was causing them to exactly matching things in namespaces they didn't care about and cause those namespaces to be added.

Tagging @genlu to confirm.

**Comment by CyrusNajmabadi** [comment]
> I don't want completion

This woudl be the case no matter what.  if you type a prefix of something in scope, and you're trying to refer to soemthing that does not exist, you may always get completion.  This has been behavior we've had since VS2005.  The option here if you do not want this behavior is to disable this:

![image](https://user-images.githubusercontent.com/4564579/95270436-54221f80-07f0-11eb-9030-694c93fcddaa.png)

Then, you can start unbound identifiers without having completion popping up and interfering.

**Comment by sharwell** [comment]
> THe "Exact match" is to a namespace not in scope. We do not want to match to tehse when there are valid prefix names in scope.

This is correct. One example that hit me all the time is some type in Elfie named `Read`. In any assembly that contained a reference to Elfie, I was not able to declare any `readonly` fields because it always ended up completing that type instead.

**Comment by sharwell** [comment]
> I don't want completion

Note that the specific scenario you describe is more likely covered by the Suggestion Mode option:

![image](https://user-images.githubusercontent.com/1408396/95350119-ad339700-0874-11eb-9e75-5e820a201b26.png)
