### ISSUE TITLE
Razor LSP: Bad completion experience when typing numbers

### ISSUE THREAD

**Issue by ajaybhargavb** [dotnet/roslyn#48573]
![intcompletion](https://user-images.githubusercontent.com/1579269/92031876-2728ab80-ed1e-11ea-86db-4090bdbf5021.gif)

**Comment by dibarbet** [comment]
Note - this occurs because razor passes us "invoked" as per the LSP spec.  In codespaces, when we pass trigger kind Invoked to the completion service, we get the as/is/switch... completion results in C# files as well.  However in local, when invoking via cntrl+space in the same location no completion shows.

So LSP completion here should not be returning results when explicitly invoked (so it matches local)
