### ISSUE TITLE
SQLitePersistentStorage.BulkPopulateProjectIds consumes significant CPU in large solutions

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#48597]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1105460/左下角-正在執行低優先序背景流程-疑似持續占用大量cpu資源.html)._

---
在完全沒有任何動作的狀態下，發現Visual Studo 持續有CPU 使用量

點開為左下角 "就緒"，發現有 "正在執行低優先序背景流程"，並顯示 "正在評估佇列中的2工作"

找不到任何方法可以瀏覽及關閉其佇列中的工作。

相似問題: https://social.msdn.microsoft.com/Forums/en-US/1fc07c99-2845-449b-b341-81e708e011c0/vs2019-1641-how-to-cease-all-the-background-tasks?forum=visualstudiogeneral

---
#### Feedback Bot on 7/8/2020, 02:29 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 7/15/2020, 04:46 PM: 

Thank you for reporting this issue to us. We have changed the title to better describe the problem so others can find and engage with it.
#### Feedback Bot on 7/15/2020, 04:49 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
This is primarily caused by an inefficient implementation of [`Project.Documents`](https://github.com/dotnet/roslyn/blob/7929ef216a69a83ebc2c8f119785672b1b859d2e/src/Workspaces/Core/Portable/Workspace/Solution/Project.cs#L173-L176). In order of impact (most impactful items first):

1. Each call to `GetDocument` produces a call to `ContainsDocument`, which is slow and unnecessary in this context
2. `ImmutableHashMap<TKey, TValue>.TryGetValue` is slow, particularly in the implementation of `HashBucket.Get`
3. `DocumentIds` is implemented with `ImmutableList<T>`, which has an inefficient enumerator
