### ISSUE TITLE
Why is it possible to disable nullable context errors through .editorconfig?

### ISSUE THREAD

**Issue by bpaczkowski** [dotnet/roslyn#48840]
I'm not entirely sure this is the correct repository to post this but here we go. We're using nullable context in all our new apps along with `<WarningsAsErrors>nullable</WarningsAsErrors>`. But it seems that without any changes to the project itself, it is possible to make a project compile by ignoring those checks entirely if one were to ignore them in .editorconfig, while these checks should prevent just that and should error out during compilation. Shouldn't it be the other way around? As in the more generic .editorconfig can be overridden in the more specific csproj?

**Comment by jaredpar** [comment]
@mavasani @chsienki to clarify the precedent of the various configurations here.

**Comment by mavasani** [comment]
This was fixed with https://github.com/dotnet/roslyn/pull/48125 (will first release in 16.9 Preview1). The new precedence rules after that PR are documented at https://docs.microsoft.com/dotnet/fundamentals/code-analysis/configuration-files?toc=%2Fvisualstudio%2Fcode-quality%2Ftoc.json&view=vs-2019#precedence.
