### ISSUE TITLE
VB can't split long lines at .

### ISSUE THREAD

**Issue by paul1956** [dotnet/roslyn#4885]
In the following code I want to split long lines at "." like I can in c#. If I split the lines the same way they are split in C# I get Error    BC30157 Leading '.' or '!' can only appear inside a 'With' statement.   

```
    Private Shared Iterator Function GenerateNewScript(ifBlock As MultiLineIfBlockSyntax) As IEnumerable(Of SyntaxNode)
        Dim ifStatement As IfStatementSyntax = GenerateInvertedIfStatement(ifBlock.IfStatement)
        Yield SyntaxFactory.MultiLineIfBlock(ifStatement).WithStatements(GenerateNewTrueStatement(ifBlock.ElseBlock.Statements)).WithLeadingTrivia(ifBlock.GetLeadingTrivia()).WithTrailingTrivia(ifBlock.GetTrailingTrivia()).WithAdditionalAnnotations(Formatter.Annotation)

        For Each stmt As StatementSyntax In ifBlock.Statements
            Yield stmt.WithAdditionalAnnotations(Formatter.Annotation)
        Next
    End Function
```

Desired code formatted like in C# below.

```
        static IEnumerable<SyntaxNode> GenerateNewScript(MultiLineIfBlockSyntax ifBlock)
        {
            var ifStatement = GenerateInvertedIfStatement(ifBlock.IfStatement);
            yield return SyntaxFactory.MultiLineIfBlock(ifStatement)
                .WithStatements(GenerateNewTrueStatement(ifBlock.ElseBlock.Statements))
                .WithLeadingTrivia(ifBlock.GetLeadingTrivia())
                .WithTrailingTrivia(ifBlock.GetTrailingTrivia())
                .WithAdditionalAnnotations(Formatter.Annotation);

            foreach (var stmt in ifBlock.Statements)
            {
                yield return stmt.WithAdditionalAnnotations(Formatter.Annotation);
            }
        }
```

**Comment by HaloFour** [comment]
Looks like you're using apostrophe characters instead of backticks for formatting code.

The problem with trying to format code like this in VB.NET is that the newline is a statement terminator.  The language does have support for automatic line continuation but only in the cases where it is not ambiguous, and the compiler will not read ahead to the next line to make that determination.  So, if you want to split your code over lines like that you'd need to either put the `.` on the previous line or use the explicit line continuation character `_`:

```vb
Dim sb As New StringBuilder()

Dim s1 As String = sb.Append("foo").Append("bar").Append("baz").ToString()

Dim s2 As String = sb.
    Append("foo").
    Append("bar").
    Append("baz").
    ToString()

Dim s3 As String = sb _
    .Append("foo") _
    .Append("bar") _
    .Append("baz") _
    .ToString()
```

**Comment by paul1956** [comment]
@HaloFour thanks for helping with both issues. My guess is that even with look ahead it would still be ambiguous if it was within a With block.

**Comment by jrmoreno1** [comment]
@HaloFour : is there a reason for the no peek rule? I would also like to break chained method calls with the . being on the next line, without using the line continuation character.

**Comment by MohammadHamdyGhanem** [comment]
@paul1956 @HaloFour @jrmoreno1 @shanselman 
We can put the role that it ls allowed as a line continuation outside With block. Inside With block any line starts with .  is relative to the With object. Things can be more intelligent: If the compiler found that the . member doesn't beling to the with block object, it considers it a line continuation if possible.
So I think @paul1956 should re-open this issue.

**Comment by CyrusNajmabadi** [comment]
>  Things can be more intelligent: If the compiler found that the . member doesn't beling to the with block object, it considers it a line continuation if possible.
So I think @paul1956 should re-open this issue.

The compiler has to first parse to produce a valid syntax tree.  it can then semantically analyze that tree.  Your approach requires the compiler to be able to understand semantics in order to figure out what's going on.  However, that would mean that parsing would need semantics, which isn't possible with the current architecture.

**Comment by MohammadHamdyGhanem** [comment]
@CyrusNajmabadi 
In With block, compiler do its thing as usual, but if it hits an error of type "member doesn't exsit in this type", it can try a differnt approach and assume this is a part of the last line. this is just an aditional step after doing every thing as usual. But, if it is not possible somehow, then the dot in the start of a line can be a line continuation outside the With block only. I can live with that. In fact I never uses the With block in VB.NET. It was useful in VB6, but I feel it is useless and confusing in VB.NET. I can alwasy assign any expression to a variable and use it instead ot the With block. which is more readable.

**Comment by paul1956** [comment]
Reopen pre request by @CyrusNajmabadi ,


@MohammadHamdyGhanem I love With Blocks they make lines much shorter and very clear without an extra variable that serves no real purpose.

**Comment by CyrusNajmabadi** [comment]
> In With block, compiler do its thing as usual, but if it hits an error of type "member doesn't exsit in this type", it can try a differnt approach and assume this is a part of the last line. 

That won't help since the syntax tree will still think this is the other type of syntax.  That will break the expectations of everything higher in the stack.  The tree would say that this was a member-access-expression, but it wouldn't be that at all.

**Comment by MohammadHamdyGhanem** [comment]
@CyrusNajmabadi 
I am speaking about simple try and error:
1- build syntax tree as usual.
2- If there is an error in With block, try add _ at the nd of previous line, and modify syntax tree of this block.
3- if 2 fails, undo, and give syntax error.

Any way, I don't think the problem is in how to do it. The problem is this syntax will be confusing to the readers, becuase they will need to check whicj object the dot refers to. So, I think it is OK to prevent line contiuation before the dot inside With block and the With {} initializer , but allow it elsewhere.

**Comment by CyrusNajmabadi** [comment]
> I am speaking about simple try and error:
1- build syntax tree as usual.
2- If there is an error in With block, try add _ at the nd of previous line, and modify syntax tree of this block.

You can't do this.  Because syntax trees are immutable in the context of a compilation.  This is what i said above: you are now making syntax dependent on semantics.  there is practically no change roslyn would ever do this.  It goes far too much against the deeply ingrained designs on how the compilers work.

**Comment by CyrusNajmabadi** [comment]
@MohammadHamdyGhanem I would recommend that if you're interesting in this that you help out by providing a proof of concept PR that demonstrates how this can be done.  It would be akin to the work @paul1956 has done to support trailing comments after line-continuation characters: https://github.com/dotnet/roslyn/pull/28327

It would help provide clarity to you why there would be so much difficulty here.  It's difficult to discuss some of these things with you because you make many assumptions about how the system actually works, and then presume that things will behave in a manner that they very often don't.  Actually doing the legwork here will help either:

1. figure out why this would not work in the existing system.
2. demonstrate that it is possible.

Either of these outcomes would be valuable.

**Comment by MohammadHamdyGhanem** [comment]
@CyrusNajmabadi 
As I said:
> Any way, I don't think the problem is how to do it. The problem is this syntax will be confusing to the readers, becuase they will need to check which object the dot refers to. So, I think it is OK to prevent line contiuation before the dot inside With block and the With {} initializer , but allow it elsewhere.

Thanks

**Comment by CyrusNajmabadi** [comment]
> It would help provide clarity to you why there would be so much difficulty here. It's difficult to discuss some of these things with you because you make many assumptions about how the system actually works, and then presume that things will behave in a manner that they very often don't. Actually doing the legwork here will help either:

1. figure out why this would not work in the existing system.
2. demonstrate that it is possible.

Either of these outcomes would be valuable.

**Comment by gafter** [comment]
If you write VB code such as
``` vb
    SomeMethod()
        .OtherMethod()
```
Then the first of these lines is a complete executable statement according to the VB language specification (because, unlike in C#, the end-of-line is significant). Although you would like it to be different, anything different would require a change to the VB language specification. Language change requests belong in the https://github.com/dotnet/vblang repository.

One thing you can do in the current VB language is put the `.` and the end of the previous line. That makes the VB language look for more of the statement on the following line.
