### ISSUE TITLE
[LSP] Remove RemoteLanguageServer and move cntrl+Q search inproc LSP server (that delegates to OOP)

### ISSUE THREAD

**Issue by dibarbet** [dotnet/roslyn#48853]
Currently cntrl+Q search is running in an LSP server that is provided entirely OOP - https://github.com/dotnet/roslyn/blob/master/src/Workspaces/Remote/ServiceHub/Services/RemoteLanguageServer/RemoteLanguageServer.cs

@tmat suggested that we should instead make the server itself run in-proc.  It can then delegate the work to the search service which runs OOP. 

We can then take advantage of all the work being done to retrieve the correct solution (instead of just the OOP primary solution), has all the shutdown / reboot logic, we can re-use the [workspace/symbols logic we already have](http://sourceroslyn.io/#Microsoft.CodeAnalysis.LanguageServer.Protocol/Handler/Symbols/WorkspaceSymbolsHandler.cs,af9e0c50e57b07f3), plus will use all the correct service broker logic to connect to the OOP and handle errors.

At some point in the future when OOP supports retrieving other arbitrary solutions we can consider moving the entire LSP server back out of proc

cc also @CyrusNajmabadi and @davidwengier

**Comment by davidwengier** [comment]
I like that idea. I was talking with @tmat yesterday about OOP and workspaces etc. and I think the new design of the request handlers, where they get given a solution and document to work on, but don't know/care where it comes from, lends itself well to this model.

**Comment by davidwengier** [comment]
Also this would change https://github.com/dotnet/roslyn/issues/45255 to be "move the handler to OOP", so I wonder if we can come up with some design to easily opt individual handlers into OOPiness?

**Comment by dibarbet** [comment]
@davidwengier the handlers would themselves run in-proc, but the workspace symbols handler calls the search service which immediately forwards the request OOP

**Comment by davidwengier** [comment]
But why? The handlers used to get the solution/document, map LSP types to roslyn types, then call services. That first step needs to happen in-proc, because thats where the workspaces are, but thats also not the job of the handlers any more. 

Maybe I'm making huge assumptions about what the services have to do to call OOP, but I guess in my ideal naive world, the handler execution bits would handle the transition to OOP, after they get the documents/solutions, and the handlers would be able to just declare where they want to run.

**Comment by dibarbet** [comment]
Hmm, that's potentially an option.  We'd have to ensure the handlers are able to run OOP and create a brokered service to call them.
