### ISSUE TITLE
Does FileChangeWatcher have a memory leak in its Task continuation chain?

### ISSUE THREAD

**Issue by AArnott** [dotnet/roslyn#48938]
While inspecting a hung shutdown, I noticed a _very_ long chain of what I believe to be task continuations that involve the `FileChangeWatcher` in Roslyn. In the screenshot below, notice it has "314 entries are hidden" as well, so there are many more than are visible here. Is task chaining being used here to ensure non-concurrent execution? Are the task continuations somehow retaining strong references to their antecedents perhaps, such that they can never be released although they complete execution?

![image](https://user-images.githubusercontent.com/3548/97246893-1c414300-17c4-11eb-909a-3f6be9cffaeb.png)

[Dump file](https://microsoft-my.sharepoint.com/:u:/p/andarno/EVRLzbZTWqlAqvJhDKJ6HAcB7k4K3DiTq17bXwxQMva-JA?e=MWRfT9)

**Comment by CyrusNajmabadi** [comment]
@jasonmalinowski @sharwell ?

**Comment by sharwell** [comment]
Well that's interesting!

**Comment by jasonmalinowski** [comment]
So to at least summarize from the first PR: no, there is not a leak here. The tasks that were in memory hadn't executed yet, and the async stack viewer assembled the chain into a single stack that made it look like there was a leak but there wasn't. Somewhat confusingly the stack was "backwards" because the algorithm used for normal async execution isn't helpful here: the "top" of the stack is what's executing and what will be unblocked is displayed visually farther down, but unlike the more common case what's being displayed further down, that's not stuff that's already executed (partially) but instead will execute later.

**Comment by CyrusNajmabadi** [comment]
@ToddGrun  i'm closing this out as i'm thinking you  resolved this.
