### ISSUE TITLE
Source generator fails to load referenced assembly

### ISSUE THREAD

**Issue by thomaslevesque** [dotnet/roslyn#49075]
I'm trying to use [Scriban](https://github.com/lunet-io/scriban) to generate code more easily from a source generator. However, it fails to load the assembly:

> CSC : warning CS8785: Generator 'StronglyTypedIdGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'FileNotFoundException' with message 'Could not load file or assembly 'Scriban, Version=2.1.4.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.' [C:\path`\to\my\project\src\MyProject\MyProject.csproj]

**Version Used**: 

```
> dotnet --version
5.0.100-rc.2.20479.15
```

Microsoft.CodeAnalysis.CSharp : 3.8.0-5.final

**Steps to Reproduce**:

1. Create a project for the generator, referencing Scriban from NuGet

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="3.8.0-5.final" PrivateAssets="All" />
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.3.1" PrivateAssets="All" />
    <PackageReference Include="Scriban" Version="2.1.4" />
  </ItemGroup>

</Project>
```

2. Write a source generator that uses Scriban
3. Reference the generator from another project and build

**Expected Behavior**:

Should just work

**Actual Behavior**:

Produces the error shown above.

I noticed that the Scriban assembly was not in the output folder. I tried setting `CopyLocalLockFileAssemblies` to true in my generator project, but I'm still getting the same error even though the assembly is now there.

How to create generators that use NuGet dependencies?

**Comment by PathogenDavid** [comment]
See [this answer and the related discussion](https://github.com/dotnet/roslyn/discussions/47517#discussioncomment-64145).

**Comment by jaredpar** [comment]
Closing as the linked discussion should address the issue here. @thomaslevesque please let us know if it doesn't.

**Comment by thomaslevesque** [comment]
@PathogenDavid I'll give it a try, thanks!

**Comment by thomaslevesque** [comment]
@PathogenDavid @jaredpar it worked, thanks!
The experience isn't ideal, though... The steps to make it work are not obvious at all, and not documented. It's difficult to find the discussion unless you're pointed to it. Are there plans to improve this and make it easier? Ideally, make it "just work" without additional work?

**Comment by PathogenDavid** [comment]
@thomaslevesque Glad it worked!

I can't say anything for certain since I'm not a Microsoft employee, but as far as I'm aware nothing has changed since [sharwell's comment](https://github.com/dotnet/roslyn/discussions/47517#discussioncomment-76675).

I believe analyzers have the same issue and (from my perspective) it hasn't really hurt their adoption, so it may just be the compiler team is waiting to see if this becomes more of a problem for source generators or not. I think the reason it isn't documented is it's considered a workaround rather than an official solution. (And as soon as they document it they might be less likely to hear about it being a pain point. -- Again, this is just the opinion of some guy who reads too many .NET issues.)

I think another aspect of why it isn't marketed as the official solution is it can break down in certain situations. (If I remember right the workaround runs into issues if you have two source generators targeting two different versions of the same assembly.) I think the recommended workaround in that situation is using something like ILMerge, which now means any official documentation needs to document that as well and all the problems and quirks that come with it.

**Comment by thomaslevesque** [comment]
> I think the recommended workaround in that situation is using something like ILMerge

Given than ILMerge doesn't support .NET Core or .NET Standard (or at least, it didn't last time I checked), I don't think it's a viable workaround...

**Comment by PathogenDavid** [comment]
Despite the issues on the ILMerge repo, it works fine for me:

![image](https://user-images.githubusercontent.com/278957/98181606-49c77400-1ec9-11eb-8e8d-d59e5d12e5a7.png)

Unmerged on the left, merged on the right. (Notice the missing library assemblies on the right.) This is a .NET 5.0 Console app and two .NET Standard 2.0 libraries all merged into one assembly. (`ILMergeCore` depends on `LibraryA` which depends on `LibraryB`)

I would suspect the people running into issues on the ILMerge repo are trying to merge the `.exe`, which isn't possible in post-framework .NET because the `.exe` isn't a .NET assembly anymore. (It's a thin apphost that bootstraps the runtime to run the actual assembly.) None of them provided a repro though so it's hard to say.

**Comment by thomaslevesque** [comment]
Oh, interesting. When we ported [FakeItEasy](https://github.com/FakeItEasy/FakeItEasy/) to .NET Core, we ran into issues with ILMerge, and decided to not merge assemblies for .NET Core (now we don't merge then for any TFM).

Thanks, maybe I'll try it again!

**Comment by nikolaidk** [comment]
https://github.com/dotnet/roslyn/discussions/47517#discussioncomment-1624292
