### ISSUE TITLE
CI runs fail with "Logs already exists for build"

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#49214]
Example run: https://dev.azure.com/dnceng/public/_build/results?buildId=877444&view=logs&j=7f45203e-c771-5e03-a313-4b8cfc15296a&t=9ba0a9f3-f509-5f5b-bb77-a8bffa790afb&l=28

I am wondering if it's impossible for test runs to succeed on retry sometimes because it can't upload logs at the end? I'm not sure if I'm interpreting the CI log properly or not.

/cc @jaredpar

**Comment by jaredpar** [comment]
The issue here is that we are using `PublishPipelineArtifact` task to upload our log files. That doesn't allow for overwriting unlike `PublishBuildArtifact` which does. Think we just need to include the attempt number in the log file name so that they are distinct names per attempt. Can just add a suffix like `Attempt-$(System.JobAttempt)`
