### ISSUE TITLE
"'new' expression can be simplified" is not offered if tuple element names were omitted from the constructor call

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#49291]
**Version Used**: 16.9-p1

To reduce the length and amount of redundancy in field initializer constructor calls, I have been in the habit of removing the tuple element names. This confuses IDE0090.

```cs
class C
{
    // 🚫 IDE0090 not offered
    List<(int SomeName, int SomeOtherName, int YetAnotherName)> f = new List<(int, int, int)>();
}
```

Expected:

```cs
class C
{
    // ℹ IDE0090 'new' expression can be simplified
    List<(int SomeName, int SomeOtherName, int YetAnotherName)> f = new List<(int, int, int)>();
}
```

💡 Use 'new(...)':

```cs
class C
{
    List<(int SomeName, int SomeOtherName, int YetAnotherName)> f = new();
}
```

**Comment by davidwengier** [comment]
@CyrusNajmabadi based on the existence of https://github.com/dotnet/roslyn/pull/42269 would this be by design? Or do you think its worth allowing tuple names to change in the specific case of the declaration having names, but the object creation having no names?

Same think would apply in reverse for Use Implicit Type I guess.

**Comment by CyrusNajmabadi** [comment]
I don't consider this one "by design".  In the 'var' case, we need to preserve to keep semantics.  Here, the semantics are preserved in that (at runtime), the explicit and implicit forms mean the same.  And in source form, you can't really perceive the difference here. 

So i think a fix here is fine (though not highly important).
