### ISSUE TITLE
FatalExecutionEngineError / InvalidCastException after sorting body-less properties in VB.NET file

### ISSUE THREAD

**Issue by carlos-j-quintero** [dotnet/roslyn#494]
See MS Connect bug:
https://connect.microsoft.com/VisualStudio/feedback/details/1071403/connect-fatalexecutionengineerror-invalidcastexception-after-sorting-body-less-properties-in-vb-net-file

That was my first bug report and I opened it only in MS Connect, not here in GitHub. The MS Connect bug report was closed as Resolved/Fixed but I want to be sure because I haven't seen it here in the list of bugs or fixes, and the code of roslyn/src/VisualStudio/VisualBasic/Impl/CodeModel/VisualBasicCodeModelService.CodeModelEventCollector.vb still contains this unchecked cast (in bold) in Function CompareMemberDeclarations(...) that causes InvalidCastException (Unable to cast object of type 'Microsoft.CodeAnalysis.VisualBasic.Syntax.PropertyBlockSyntax' to type 'Microsoft.CodeAnalysis.VisualBasic.Syntax.MethodBaseSyntax') in my scenario:

ElseIf TypeOf oldMember Is MethodBlockBaseSyntax OrElse
   TypeOf oldMember Is MethodBaseSyntax Then
   
   Return CompareMethods(
       If(TypeOf oldMember Is MethodBlockBaseSyntax, 
           DirectCast(oldMember, MethodBlockBaseSyntax).BlockStatement, 
           DirectCast(oldMember, MethodBaseSyntax)),
       If(TypeOf newMember Is MethodBlockBaseSyntax, 
           DirectCast(newMember, MethodBlockBaseSyntax).BlockStatement, 
           **DirectCast(newMember, MethodBaseSyntax)**),
       newNodeParent,
       eventQueue)

**Comment by DustinCampbell** [comment]
@basoundr fixed this issue before the Code Model code was on GitHub. So, the commit unfortunately didn't happen in Git.

The problem was actually due to the ordering of Ifs and ElseIfs in `CompareMethodDeclarations` in these lines of code:

https://github.com/dotnet/roslyn/blob/master/src/VisualStudio/VisualBasic/Impl/CodeModel/VisualBasicCodeModelService.CodeModelEventCollector.vb#L552-L574

Notice the comment at the top of the selected code. Originally, the checks for `MethodBlockSyntax` and `MethodBaseSyntax` appeared before `PropertyBlockSyntax`, `PropertyStatementSyntax`, `EventBlockSyntax` and `EventStatementSyntax`. Because both `PropertyStatementSyntax` and `EventStatementSyntax` inherit from `MethodBaseSyntax`, there was a potential `InvalidCastException`. Now that the code checks for events and properties first, the exception should be thrown.
