### ISSUE TITLE
I am PowerShell repo maintainer and I want to share a related feedback.

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#49417]
_Originally posted by @iSazonov in https://github.com/dotnet/roslyn/issues/43905#issuecomment-726640405_

I am PowerShell repo maintainer and I want to share a related feedback.
PowerShell consists of several csproj files that link to another ones (tree). We have a custom script and tool to generate a dictionary based on assemblies, one from cscroj-s (SDK,csproj) depends on. On first step, the script gets `Project.References` for the SDK,csproj using dotnet msbuild, custom target and build the project at design time. On second step, we use our custom tool to generate from the assembly list a dictionary (type name -> full-qualified assembly name). The dictionary is placed and used in another csproj (SMA.csproj).
I created a draft of a source generator and add reference to it in SDK,csproj file. After I run a build of whole PowerShell I get in the source generator the Compilation for _whole PowerShell_.
1. My expectations were that if I attached a generator to this SDK,csproj project, then I would receive a Compilation for this project and not for all csproj-s.
2. In the example I guess it is not critical to add the generated source code to the Compilation for whole PowerShell. But in general, projects could be more independent (ex.: in different nuget packages) and in the case a code could be generated in one project for another project.
3. I wonder does it make sense to reference a source generator not in a root csproj file?
4. I wonder is it possible to get more granular information from MSBuild  about build process (since source generators is for build process) now or in future?

Now I see the only way to resolve the problem - to use Workspace.OpenProject() with hard-coded path to SDK,csproj file. Thoughts?

**Comment by iSazonov** [comment]
Additional feedback:
5. There must be a way to differentiate between analyzers and generators
See the case https://github.com/OmniSharp/omnisharp-vscode/issues/4215
In short I'd want to run a source generator only in build time and not in design time and/or I'd want to run an analyzer only in design time and not in build time.

**Comment by jasonmalinowski** [comment]
@iSazonov I guess I'm a bit confused on your original post here.

> My expectations were that if I attached a generator to this SDK,csproj project, then I would receive a Compilation for this project and not for all csproj-s.

How did you add the prototype source generator to your project? If this is for the PowerShell repo is there a PR or commit to look at?

> In short I'd want to run a source generator only in build time and not in design time and/or I'd want to run an analyzer only in design time and not in build time.

I can understand various desires to only have analyzers run in design time, but what's the concern about having source generators running during design time?

**Comment by iSazonov** [comment]
> How did you add the prototype source generator to your project? If this is for the PowerShell repo is there a PR or commit to look at?

It is here https://github.com/iSazonov/PowerShell/tree/sg-typegen
I manually created there CorePsTypeCatalog.cs1 file as example of what and where we want to get.
Root project file is powershell-win-core.csproj (If you want to build PowerShell you should run PowerShell, import module Build.psm1 and run Start-PSBuild. See docs in PowerShell repo for details)
Currently I could be able compile whole project but (1) I did not find generated file on file system, (2) I get a list of assemblies not for Microsoft.PowerShell.SDK.csproj but for whole project (I see this in debug file I created in c:\tmp dir).

> I can understand various desires to only have analyzers run in design time, but what's the concern about having source generators running during design time?

If we say about "design time" we expect that we can open result file in IDE and benefit from IntelliSense.

In PowerShell scenario I shared, we see conflicts with previous scenario: the source generator is not run (1) in time and (2) place where we expect,
It also has unacceptable consequences. If I enable Analyzers in VS Code C# extension OmniSharp run the source generator too - not right time, not right place. (https://github.com/OmniSharp/omnisharp-vscode/issues/4215)

This leads me to believe that we must clearly distinguish between generators and analyzers in order to run them at the right time and in the right place.

Today the process is like this:
```
dotnet restore
dotnet build
dotnet publish
```
Maybe we need:
```
dotnet restore          <- After that we can able to run Analyzes in IDEs, not Source Generators
dotnet designbuild      <- Run Source Generators at early time
dotnet build            <- Run Analyzes to force warinings
dotnet publish
```
-------
Additional feedback.
If you look PowerShell.Common.props you can see we run `git` to get version/commit information and set this to assemblies.
At startup PowerShell read the version information from assembly metadata to display in welcome message. This delays PowerShell startup and it is important for us to reduce startup time and we could use a source generator  to create C# const string.
This suggests that generators could receive not only Compilation but all MSBuild properties as an Dictionary.

**Comment by jasonmalinowski** [comment]
So for the "design time build" command, the only real necessary step is to build the source generator project; that should cause it to get picked up in IDEs at that point. If that's not working then that's something we need to investigate.

> (2) I get a list of assemblies not for Microsoft.PowerShell.SDK.csproj but for whole project (I see this in debug file I created in c:\tmp dir).

So your reference list there would be the same reference list the compiler is getting -- the SDK transitively expands project references so you're going to get more than you may be expecting.

> This suggests that generators could receive not only Compilation but all MSBuild properties as an Dictionary.

There is support for this: https://github.com/dotnet/roslyn/blob/master/docs/features/source-generators.cookbook.md#consume-msbuild-properties-and-metadata

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of anything actionable here.
