### ISSUE TITLE
Exception was of type 'PlatformNotSupportedException' with message 'System.Data.SqlClient is not supported on this platform.

### ISSUE THREAD

**Issue by serenagrl** [dotnet/roslyn#49462]
Hi,

I was exploring the Source Generators but ran into the following error during compilation of my Test Application after adding a simple line of code to open a database connection.

_warning CS8785: Generator 'TestGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'PlatformNotSupportedException' with message 'System.Data.SqlClient is not supported on this platform.'_

I am not sure what is the problem. Please advise if accessing a SQL database is not a supported feature by the Source Generator or there are additional steps I need to take to make it work.

**Version Used**: 
Source Generator library: netstandard2.0
Test Application: netcoreapp3.1 and net5.0
System.Data.SqlClient 4.8.2
Microsoft.CodeAnalysis.Analyzers 3.3.1
Microsoft.CodeAnalysis.CSharp 3.8.0
Visual Studio 16.8.1

**Steps to Reproduce**:

1.  Create an simple Hello World Source Generator in netstandard2.0.
2.  Write code to open a database connection using SqlConnection.
3.  Resolve the references to System.Data.SqlClient (VS will install the nuget package)
4.  Modify Package reference to the following:
`<PackageReference Include="System.Data.SqlClient" Version="4.8.2" GeneratePathProperty="true" PrivateAssets="all" />`

5. Add the following:
`<PropertyGroup>`
`    <GetTargetPathDependsOn>$(GetTargetPathDependsOn);GetDependencyTargetPaths</GetTargetPathDependsOn>`
`  </PropertyGroup>`

`  <Target Name="GetDependencyTargetPaths">`
`    <ItemGroup>`
`      <TargetPathWithTargetPlatformMoniker Include="$(PKGSystem_Data_SqlClient)\lib\netstandard2.0\System.Data.SqlClient.dll" IncludeRuntimeDependency="false" />`
`    </ItemGroup>`
`  </Target>`

6. Create a net core 3.1 console application and add project reference to the source generator library.
7. Modify project reference to include  OutputItemType="Analyzer" ReferenceOutputAssembly="false"
8. Compile the solution.

**Expected Behavior**:
Able to use the functionality of SqlClient to connect to database and execute queries.

**Actual Behavior**:
CS8785: Generator 'TestGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'PlatformNotSupportedException' with message 'System.Data.SqlClient is not supported on this platform.

Thank You

Best Regards,
Serena

**Comment by jaredpar** [comment]
@chsienki believe this is a case where the dependencies aren't being packade properly. Can you can a  look?

**Comment by chsienki** [comment]
Hi @serenagrl 

It appears that `Sytem.Data.SqlClient` doesn't actually provide a `netstandard2.0` implementation, so when you load that version it just throws a `PlatformNotSupportedException`. 

Instead you will need to load a platform specific implementation. It doesn't look like SqlClient provides a `netcoreapp3.1` build, and unfortunately you can't load the earlier netcore builds without running into versioning issues. You can however load the `net461` version: netcore has a 'shim' mechanism that allows it to load .NET Framework assemblies, which is working in this case. Simply change 
`<TargetPathWithTargetPlatformMoniker Include="$(PKGSystem_Data_SqlClient)\lib\netstandard2.0\System.Data.SqlClient.dll" IncludeRuntimeDependency="false" />
` 
to

`<TargetPathWithTargetPlatformMoniker Include="$(PKGSystem_Data_SqlClient)\lib\net461\System.Data.SqlClient.dll" IncludeRuntimeDependency="false" />`

And it should work, although note that you'll only be able to use the functionality of the `net461` version of SqlClient.

--------------

Now, that being said I would **strongly** recommend against doing this :) 

Connecting to the database during compilation could cause all sorts of timing and connection issues, especially as the generator may be run many times a second when hosted in an IDE such as visual studio, and you can end up with correctness issues where the DB is updated, but a compilation doesn't happen because the compiler doesn't know that the data has changed.

For these kinds of scenarios I would recommend implementing the DB connection in a process _outside_ of the compiler that runs via MSBuild beforehand. That would then produce an artifact that contains the information your generator needs to actually run, which you would pass via the `AdditionalFiles` mechanism:
- Your external process could look at the last version of the data produced and the current one, and decide if it actually needs updating, which would ensure build correctness. 
- The IDE wouldn't run your process multi times a second, only on a 'full build' so you won't run into odd timing issues. 
- Because you own the process itself you can target `netcore2.1`, ensuring you have full control over the version of `SqlClient` in use and are back in a supported scenario for that library.

Hopefully that makes sense, but I'd be happy to put together a more in depth example if you want to adopt this path.

**Comment by chsienki** [comment]
I'm closing this as it's not directly a Roslyn issue.

**Comment by serenagrl** [comment]
Dear @chsienki,

Thank you for your reply and great suggestion. I did realized that the source generator would run many times in Visual Studio and was thinking to suggest a run-once feature for it. To give a bit more information on what I was trying to do, I wasn't going to read the data of tables in the database, I was going after the schema instead to generate models *Hehehe*. But either way, the potential issue you mentioned is very real.

Yes! I would take up on your offer for a more in-depth example as I am not very familiar with the MSBuild part.
