### ISSUE TITLE
Incorrect reference nullability

### ISSUE THREAD

**Issue by njy** [dotnet/roslyn#49502]
**Version Used**:
.NET Core 3.1
Visual Studio 2019 Professional (16.8.1)

**Steps to Reproduce**:

1. Create a new console app (c#)
2. Open Program.cs and replace everything with this:

```csharp
#nullable enable

using System;

var foo = new object();
Console.WriteLine(foo);
if (foo is null)
{
  var bar = 42;
}
else
{
  var baz = 42;
}
```

3. Hovering over `if (foo is null)` it says that "'foo' may be null here", which cannot be; in fact on the previous line (the `WriteLine` one) it says "'foo' is not null here".

**Expected Behavior**:
It should know that `foo` cannot possibly be null there.

**Actual Behavior**:
It seems to think that it may be null.

**Comment by Youssef1313** [comment]
This happens because of your explicit null check. If you already know that `foo` is not null (because you initialized it in the previous line), then you don't need the if condition at all.

I'm not sure whether this is by-design or not. @RikkiGibson to confirm.

**Comment by njy** [comment]
I agree the if condition is not necessary: in my case it was there because it was needed before, but then I made a change in the previous line and it became obsolete so I was about to remove it, and noticed the mismatch.

But I still don't understand why an explicit null check should change the nullability state in the analysis flow, though.

**Comment by Youssef1313** [comment]
@njy See #44834

**Comment by njy** [comment]
Ok, saw that: as @krwq said, he is not the only one that finds it confusing.

May I ask for even one single case when it is physically possible for the "may be null" thing to be actually true in a scenario like that? Because I mean, otherwise, it seems to be just plain wrong.

Also: if I do `foo = foo` it warns me that it is a useless assignment, why checking for something that is definitely null would be different?

**Comment by jaredpar** [comment]
> But I still don't understand why an explicit null check should change the nullability state in the analysis flow, though.

The reasoning here in the language is that if the customer writes code that believes a value can be `null` then we should believe them that the value can be `null`. Just as when they write code to assert a value is non-null we should believe them there too. 

That means whenever the user code does a "pure null check" the compiler will consider the value as "maybe-null" on all code paths reachable from that branch.

> if I do foo = foo; it warns me that it is a useless assignment;

That is because it is definitive here that this is useless. Redundant assignment has no observable side effects and hence this is almost certainly a typo or line of code that you didn't mean to write. 

> Why saying that something may be null when it is definitely not null should be different?

Nullable reference types though are not definitive, they're a feature about null guidance and it's very possible that the guidance is wrong in some scenarios. Consider for example that APIs can be mis-annotated. Or the author had a situation where an API returns non-null 99.9% of the time and only in a very specific extreme case it returned `null` and hence they opted to label the API non-null. In either case the consumer of that API can reasonably check for `null` here

Part of this is a choice of the compiler because it only tracks three states: not-null, maybe-null and maybe-default. The "not-null" though means that flow analysis believes it's not null, flow analysis is based off of annotations and hence not 100% definitive. We could have added a fourth state in the compiler called "provably-not-null" and warned on cases where users did explicit `null` checks. 

This was decided against for now though because it the cost is non-trivial and the impact is fairly low in the code that we looked at.

**Comment by njy** [comment]
> Part of this is a choice of the compiler because it only tracks three states: not-null, maybe-null and maybe-default. The "not-null" though means that flow analysis believes it's not null, flow analysis is based off of annotations and hence not 100% definitive. We could have added a fourth state in the compiler called "provably-not-null" and warned on cases where users did explicit `null` checks.
> 
> This was decided against for now though because it the cost is non-trivial and the impact is fairly low in the code that we looked at.

Thanks for the explanation, I can now see the reasoning behind it.

Just as a reference for future thinkings if to include a "provably-not-null" or similar state, one of the scenarios where I think it would be useful in is refactoring, where a condition that initially was necessary is now useless, because of some changes in the code above the condition itself.
This was in fact the situation I was into when I noticed this: I completed marking nullability for a class and was reducing the number of checks to simplify and speed up the code, and was relying on the static flow analysis to assist me with that.
Just my 2 cents.
