### ISSUE TITLE
Extract Method refactoring fails to capture inputs/outputs when unsafe blocks are included

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#4950]
From @AArnott:

``` C#
using System;

class Program {
    static void Main(string[] args) {
        object value = args;

        // extract from here
        IntPtr p;
        unsafe
        {
            object t = value;
            p = IntPtr.Zero;
        }
        // to here

        Console.WriteLine(p);
    }
}
```

Open the C# console app in Dev14 and the Program.cs file.
Select lines 7 - 12 and execute the Extract Method command.

_Expected_
A new method that takes an object as a parameter and returns an IntPtr is created, and an invocation of that method replaces the selected lines that passes in "value" as the parameter and assigns the result to "IntPtr p". 

_Actual_
A method is created that takes no parameters and returns void. Two compile errors are created by the refactoring as a result.

**Comment by AArnott** [comment]
This repros with `unchecked` blocks as well.

**Comment by gafter** [comment]
I suspect this may be a bug in the region analysis APIs.  If you discover that is the case, please assign to me and Area-Compilers.

**Comment by CyrusNajmabadi** [comment]
Yes.  this is a bug in the region analysis APIs.  Assigning to @gafter 

@gafter the core issue is here: We call `AnalyzeDataFlow` on the pair of statements `IntPtr p;` and `unsafe { }`.  This fails immediately with a non-successful result.  Debugging in a tiny bit, this is because the compiler doesn't get a boundnode for the `unsafe { }` block.  Because there's no end bound node, nothing works.
