### ISSUE TITLE
[VB.NET] No need for EndIf error 

### ISSUE THREAD

**Issue by VBAndCs** [dotnet/roslyn#49558]
For ages, I am used to write EndIf and the editor before Roslyn used to correct if to `End If`. Yesterday, it happened that I wrote some code where the editor didn't add `End If` for me when entering a new line after If statement (due to some syntax errors), So I added EndIf manually, just to get this error:
> 'EndIf' statements are no longer supported; use 'End If' instead

So, Why don't the editor just fix it to End If?
I thought that maybe EndIf is allowed as a var name, hence the editor is afraid to change it, but when I tried:
`Dim EndIf = 1`
I got an Error stating that EndIf is a keyword!
So, why this unnecessary error?
I suggest that the editor should change any EndIf to End If after any edit or paste. No need at all to raise an error here.

**Comment by DualBrain** [comment]
Strangely enough, this does appear to still work for for the *other* End If...

#If True Then
#EndIf

This will initially result in drawing of squiggles for the EndIf (and also draw the 'EndIf' as if it were a keyword).  After pressing enter again (or using the down arrow - I suppose anything that makes it clear to the IDE that you are no longer editing the *line*), the #EndIf is automatically converted to #End If (and the squiggles removed).

It is a bit annoying that it works in one place (as we would expect and have muscle memory in doing so) yet, for whatever reason, it no longer works in the more common, more often utilized scenario.

(Yes, I use #ifdefs a lot.) ;-)

**Comment by DualBrain** [comment]
After playing with this for a little bit longer (as I had another thought)... I think this is something that appears to be an artifact of something else recently introduced ("inline comments" maybe).  It does appear to autocorrect if you press two carriage returns.

Three different scenarios...

a)

if true then{down arrow}
endif{enter}
(squiggles)
{enter (or change focus)}
(reformatted and squiggles are removed)

b)

if true then{esc}{down arrow}
endif{enter}
{enter}
(reformatted as expected)

c)

(starting without the 'If' line)
endif{enter}
(immediately reformatted and expected error presented)

So it does reformat... eventually.  It's a little "odd" in feeling and something that would be nice if it could get resolved - or at least a definitive answer as to why the change in behavior so that it can be "explained away" (I suspect the recent inline comments).

**Comment by VBAndCs** [comment]
In fact the editor has many defects in VS 2019, especially with VB.NET, and I advice to review it all with full tests. This includes the debugger and error list. I usually don't report such errors that I can work around.
I will report a strange one for C# records as an example.

**Comment by VBAndCs** [comment]
And I remembered: one of the annoying broken features in VS 2019 is the Undo. It recently got insane that somersetting it undoes letter by letter  then suddenly remove a block of unrelated operations, so that you can get back to a middle of typing/editing var name!

**Comment by CyrusNajmabadi** [comment]
Closing as we are unlikely to be changing this experience.
