### ISSUE TITLE
Nullability bug in KeyValuePair/linq/tuples

### ISSUE THREAD

**Issue by miroslav22** [dotnet/roslyn#49560]
**Version Used**: 
net 5.0

**Steps to Reproduce**:

Paste this code into a project targeting net 5.0 with nullability checks enabled :

```cs
        private static (string, object?)[] ToTuples(Dictionary<string, object?> dict)
        {
            return dict.Select(i => (i.Key, i.Value)).ToArray();
        }
```

**Expected Behavior**:

Should compile as the Dictionary and hence its `KeyValuePair<string, object?>` matches the nullability of the return type array.

**Actual Behavior**:

Compilation fails with error:
`Nullability of reference types in value of type '(string Key, object Value)[]' doesn't match target type '(string, object?)[]`

If you insert a cast:

`dict.Select(i => (i.Key, (object?)i.Value)).ToArray();`

Then it does compile.  i.Value is however already object?

**Comment by miroslav22** [comment]
Sorry there seems to be a glitch in the code formatting on Github above so I've attached a code file too
[Program.txt](https://github.com/dotnet/roslyn/files/5580481/Program.txt)

**Comment by PathogenDavid** [comment]
This issue appears to have been fixed in master: [SharpLab](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxAN0QSwGYE8A+AxAHYCuANuRMOXAARzHW0CwAUAAIAMdHAjABYA3O268+AOgAymYgEcRbdkzBwoABwgBjegGEA9sSj7aAQXXq+7AN7s698QDZeAJnEB2Ow9tsHfp7wCdACyELIAFPxcANoAunQQCADmUACUXv50PpmZACKYWjCYhom4ADxRSHT6wABWcIUA/AB8dAAmBTB0ALx0xHAA7uGpihk59miJdDCk6rRQPe2dEgAq+iuz88OK4wC+7GN+6giYk/ABkXxcVTX1TalxdGsbc2rhMAAWmAv5hcVMCHKlWqdQaMBaS0K6V8OWy4wcHHckJgEgAynBaIVwpgeq1sRIANJwXBVTASABqEHIpDgqVSq30pgQCAguG2hwc+xh9i5XKAA)

(Also confirmed locally with Compiler version: '3.9.0-2.20573.10 (edf43e80)'. Language version: 9.0.)

--------------------------------

> Sorry there seems to be a glitch in the code formatting on Github above so I've attached a code file too

Blocks of code have to be formatted with `` ``` `` rather than `` ` ``, for example:

~~~
```csharp
using System.Collections.Generic;
using System.Linq;

namespace ConsoleApp1
{
    static class Program
    {
        static void Main(string[] args)
        {
            Dictionary<string, object?> dict = new();

            var tuples = dict.ToTuples();
        }

        private static (string, object?)[] ToTuples(this Dictionary<string, object?> dict)
        {
            return dict.Select(i => (i.Key, i.Value)).ToArray();
        }
    }
}
```
~~~

results in

```csharp
using System.Collections.Generic;
using System.Linq;

namespace ConsoleApp1
{
    static class Program
    {
        static void Main(string[] args)
        {
            Dictionary<string, object?> dict = new();

            var tuples = dict.ToTuples();
        }

        private static (string, object?)[] ToTuples(this Dictionary<string, object?> dict)
        {
            return dict.Select(i => (i.Key, i.Value)).ToArray();
        }
    }
}
```

**Comment by jaredpar** [comment]
Closing as this is fixed in master.
