### ISSUE TITLE
CodeLens doesn't find reference to type if it doesn't have an explicit constructor

### ISSUE THREAD

**Issue by thomaslevesque** [dotnet/roslyn#49636]
**Version Used**: C# 9, VS2019 16.8.1, SDK 5.0.100

**Steps to Reproduce**:

Write this code

```csharp
        private void Test()
        {
            var foo = new Foo();
        }

        class Foo
        {
        }
```

**Expected Behavior**:

CodeLens should show 1 reference to Foo

**Actual Behavior**:

CodeLens shows 0 reference to Foo (even though "Find all references" finds it)
If I add an explicit default constructor, then CodeLens shows 1 reference to the class and 1 reference to the constructor.

**Comment by MaStr11** [comment]
Constructor calls are not considered references to the class. Take the sample below:

![image](https://user-images.githubusercontent.com/24472128/101785466-15188f00-3afd-11eb-9a87-667a141edf4f.png)

The `1` reference on the class definition of `C` is the constructor definition. The `2` on the constructor definition are the calls `new C()`.

Find all references groups the references to the class and the references to the constructor when called on the class definition:

![image](https://user-images.githubusercontent.com/24472128/101785794-79d3e980-3afd-11eb-82e1-20e280787ba2.png)

But this is also inconsistent, but a bit different than described:

The reference count for `public class C` between FAR and CodeLens is inconsistent:

Listed references | Code Lens | Find all references | Find all references counting
-- | -- | -- | --
Direct references | Yes (counted and listed) | Yes | Counts `nameof`, `typeof`, static member calls, etc.
Constructor declarations | Yes (counted and listed) | Yes (listed below grouped by overload) | Counts calls to the constructor overload
Constructor invocations | No | Yes (listed below the grouped overload) |  

The two reference counts (FAR vs CodeLens) almost never add up, because CodeLens ignores calls to the constructors and FAR reports 1 if there is no reference (see e.g. `class C (1)` in the screenshot above).

**Comment by MaStr11** [comment]
Should constructor invocations be included in CodeLens on the class declaration (as FAR does)?

**Comment by thomaslevesque** [comment]
> Should constructor invocations be included in CodeLens on the class declaration (as FAR does)?

I think they should. Otherwise, it looks like the class is never used, and someone could remove it without realizing it's actually used.

**Comment by MaStr11** [comment]
@CyrusNajmabadi @jnm2 Any thoughts? ⬆️

**Comment by jnm2** [comment]
I agree with @thomaslevesque's expectations and have been thinking the same thing independently.
