### ISSUE TITLE
Type errors when returning object of generic type from switch expression

### ISSUE THREAD

**Issue by TannerBrunscheon** [dotnet/roslyn#49695]
**Version Used**: 
3.8.0-5.20515.7+713efb0e68d34ab75faaf709e071e5c2d8d4ed0e C#9.0

**Steps to Reproduce**:

```
public T GetGenericSwitch<T>()
	{
		return typeof(T) switch
		{
			Type x when x == typeof(int) => 0,
			Type x when x == typeof(string) => "Test",
			Type x when x == typeof(decimal) => 0.0,
			_ => default(T)
		};
	}
```

**Expected Behavior**:
Compile and return value of type T

**Actual Behavior**:
Errors in the console 

Cannot implicitly convert type int to T

Cannot implicitly convert type string to T

Cannot implicitly convert type decimal to T

**Comment by PathogenDavid** [comment]
C# doesn't support generic specialization like this, so changing this would require a language change. (I feel like there's others, but https://github.com/dotnet/csharplang/discussions/1315 is probably the closest proposal to this.)

The common pattern available to use today is to cast through `object` to convince the code to compile. In release builds the JIT will optimize away the unnecessary boxing and such. One caveat here though is that this pattern doesn't get optimized for switch expressions, so you need to use `if..else if` instead.

Compare the generated JIT assembly here: [SharpLab](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxNMAfAAgJgIwCwAUFgAwAEAygBYQIAOAMhMAHQBKArgHYwCWYOAG5ixLAGZyucgGFiAb2Lll5ANoApPjADicboj4BjABQwAnvTgB7AGbG+vAJSOAukpUB6Dxq279CI1MLazssPFJnNyIVNU0dPQMTc0tbYwATOEMBCAAbSPdlH3j/QOSQ4yhqKwQYfOiVCXIAFXJdYsTKAHctQ2oAHiaAPmNHYgBIRSIxsawAdnIy1KbHcihumF7xia2xpuDyAA9yTuo9Q/IAXguF4NSHWsvB8mNl4ytgACtM2tIkHb3LOcTmcjlcbilQuEVhcni9HG9Pt9HAAiJpwWDIv5TaYAuBA07cc5gxZ2DJZSB5R7PV7vL6GH6sUhgLHTMYAfSpGRsEE4ORgcK2AF8RFNBQVyOKin5EkEIfYnK5xV4pQkAklbpCIor6oU4tK1bLymTsnltTEVSV1XLKtVamaGpIWm19UYuj1qDgBsNRjryJMYjE+DZniS4ZdrqH7s5xTF5FJ5nCEXSfkJyGLfTE4DkoHigyGNWHiQWwlqYyo43NqfDaUjUeiYMjU+mAyosznyHnDUtoRGCwARTIm6MZ8vxqtJpGkRlgJtl5RtuBzv1jrk8vlw2e+9OCoA===).

Also note that you need to use an explicit `0.0m` for decimal here since the JIT will interpret it as a `double` constant cast to `decimal` otherwise due to the lack of a target type.
