### ISSUE TITLE
Open a Project during build

### ISSUE THREAD

**Issue by AlexEndris** [dotnet/roslyn#4974]
Now that I changed to 1.0, I've ran into a problem. I'm building a compile-time mocking framework for universal applications (source is here on GitHub). I've created a targets file that fires my build task on "AfterCompile". I need to open the very same project, though, with Roslyn (MSBuildWorkspace.OpenProjectAsync). This however throws an exception as there already is a Build process running. Is there any way to make this work? In the preview builds this was never a problem.

I should also mention that I'm talking about CodeAnalysis. In this case it's for C#

Thanks

**Comment by Pilchie** [comment]
@mattwar and @AArnott have some experience with doing this.

**Comment by AlexEndris** [comment]
So you're saying it is possible, I just need to tweak it a little?

**Comment by mattwar** [comment]
This is a limitation of msbuild, so MSBuildWorkspace won't work for you in this situation.  You can, however, use Roslyn if you construct an AdHocWorkspace and initialize it with project information manually. You'll have to translate the same msbuild variables that the csharp compiler tasks uses.  You can use the CommandLineProject class to convert command-line args into a Roslyn ProjectInfo class.

**Comment by AlexEndris** [comment]
Okay, just to sum up my scenario here, to be sure I understand it correctly. I want to open an existing csproj (unit test project universal window or windows phone) so I can scan the source code for something while also looking at the references to get some dll names.
Can I do this all using the AdHocWorkspace in the way you descriped it?  (I'm already using it to compile a new dll with the information gathered)

Thanks for the quick help and the clarification concerning MSBuild. (Could've sworn it worked once, although last time I tried was MSBuild 12 not 14)

**Comment by AlexEndris** [comment]
@mattwar: I've tried a little and it works so far for compiling the files.
I now open the .csproj file with XElement.Load() and gather all "Compile" nodes, extract the "include" file name, because those are all that I need at the moment, concerning code files.

One thing that I haven't figured out yet is how to add project references as command line arg string. Do you have some documentation what possible args there are?

**Comment by mattwar** [comment]
you can use /r or /reference.  You can find all the command line args via csc.exe /?

**Comment by AArnott** [comment]
An MSBuild task cannot spawn another MSBuild-based build. If it ever worked, it was never a good idea. The Roslyn MSBuildWorkspace spawns such a build, and as such cannot be used within an MSBuild task. As has already been suggested, you'll have to pass all the data from the project that you need directly to your MSBuild task so that such isn't necessary.

**Comment by AlexEndris** [comment]
@mattwar Oh, I was confused about what CommandLineProject would do, but yeah, makes sense that it starts csc.exe. I figured I do it a little differently, as /r wouldn't add the dll. Now I just add the dlls needed as MetadataReference to the ProjectInfo afterwards. Works at least :).

@AArnott Yup, that's the way I'm gonna do it now. But out of interest and curiosity, what is the reason it would never be a good idea? Always interested to learn more :)

**Comment by AArnott** [comment]
@AlexEndris A few reasons come to mind:

1. An MSBuild invocation a Task might make won't be hooked into the loggers, scheduler, etc. of the outer build. So depending on what you kick off, the results could be disastrous. You might cause overbuild (building the same thing multiple times), timing breaks (where the two schedulers that aren't coordinating end up building the same files at the same time and collide on disk), or at least not let the outer build log everything that actually occurred.

2. The outer build has a bunch of global properties set that determine exactly how the project will build. An MSBuild task does not have insight into those global properties and therefore cannot actually reproduce a build that is equivalent to the one in which it belongs. So your answers may be incorrect. 

3. It's inefficient. MSBuild already went to a great deal of trouble to evaluate and execute the project. If an MSBuild task were to invoke MSBuild again, all that work would be duplicated.

4. An MSBuild Task is supposed to do just one simple thing, given _only_ the information passed to it by the .targets file. That's why, for example, the Task doesn't simply have the ability to read _any_ project property. It helps keep the overall project and .targets maintainable to know that you can change _any_ property or item in the project without impacting a Task unless you explicitly pass one of them into the Task via a parameter. 

But I sympathize, and have often wanted Roslyn to find a way to author their MSBuild targets such that a chain of project extensions could get the command line for the compiler, perform code generation which then adds to the `@(Compile)` items, changing the command line, and then calls the next extension with the updated command line. If the command line were one of those parameters passed to your Task, then you wouldn't need an `MSBuildWorkspace` inside your task to do all the work with the Roslyn API that you wanted to.

**Comment by AlexEndris** [comment]
@AArnott Thank you very much for the extensive reasoning! All make a lot of sense and didn't even come to my mind, not knowing what happens in and around MSBuild.
I can see that, beyond what I personally want to do, that it would be potentially dangerous. For me, to sum up my project, RosMockLyn (also hosted on GitHub btw., and I know, I'm not creative at all xD):
 
A mocking solution for compile time where you don't have to do anything more than what you do in other mocking frameworks, like NSubstitute or Moq. It's realized with an MSBuild task that I spawn that analyses the unit test project it's attached to, finds usages of Mock.For<InterfaceToMock>. Then it takes the assembly from that interface to create a mock implementation (with syntax factory) and compile it to a new assembly that is then injected as a reference to original unit test. And the mock just works.

I've confirmed already that this approach is working. But I also ran into issues you mentioned there. Information isn't passed to the "inner MSBuild". Making output dir etc. potentially wrong. MSBuildWorkspace, in this case, was a very convenient way to get the Project and it's references and, of course, the code. I'll now pass the necessary information that I need into the task (like platform and configuration) and read from the csproj file what else I need. I already created a small solution where I tested all this. So thank to your and @mattwar's help, I now can construct it much better! 

:+1:

**Comment by AArnott** [comment]
You're welcome, @AlexEndris.

In case it's useful, here are links to my own code generator's [Task][2] and [targets][1].

[1]: https://github.com/AArnott/ImmutableObjectGraph/blob/master/src/ImmutableObjectGraph.CodeGeneration.NuGet/build/ImmutableObjectGraph.Generation.targets
[2]: https://github.com/AArnott/ImmutableObjectGraph/blob/master/src/ImmutableObjectGraph.CodeGeneration.Tasks/GenerateCodeFromAttributes.cs

**Comment by AlexEndris** [comment]
I'm not so deep into MSBuild to know what contains what. I kinda built my [targets](https://github.com/AlexEndris/RosMockLyn/blob/Develop/RosMockLyn.Build/RosMockLyn.targets) with extensive reverse engineering. Took me like straight 8 hours to find out about the AppxPackagePayload. Any how. What does @(Compile) contain? ALL files to compile (aka solution) or only the corresponding project? Although, only latter would make sense to me. But you never know :). Are there some docs about MSBuilds quirks? Or does it just come down to experience? Anyhow, thanks for sharing! :) That will most definitely reduce the stuff I have to get out of the project manually!

Oh, before I forget: @(ReferencePath) contains all referenced assemblies of that project, right? Even if it is a project reference? In that case that would help even more. I wouldn't have to evaluate what output path of the project reference to take.

**Comment by AArnott** [comment]
Everything in MSBuild is on an individual project basis. 
@(Compile) contains the source files to pass to the compiler. Note that this item list can grow over the course of the build up (but not including) to the CoreCompile target.
@(ReferencePath) contains the absolute paths for all assemblies to reference, *after* the ResolveReferences target runs. 
MSDN has some docs on MSBuild fundamentals as well as an API reference.

**Comment by AlexEndris** [comment]
Lots of thanks! Been a pleasure! :+1:
