### ISSUE TITLE
Unexpected application of CS8620 

### ISSUE THREAD

**Issue by madelson** [dotnet/roslyn#49770]
**Version Used**: 
Visual Studio 16.8.2

**Steps to Reproduce**:

1. (in a project whose LangVersion is 8.0)
```
public static class DictionaryExtensions
{
[return: MaybeNull] public static TValue GetValueOrDefault<TKey, TValue>(
    this IDictionary<TKey, TValue> dictionary, 
    TKey key, 
    [AllowNull] TValue defaultValue = default) =>
    dictionary.TryGetValue(key, out var result) ? result : defaultValue;
}
```
2.
Try to use it with a dictionary whose values are non-nullable reference types: 
```
var dictionary = new Dictionary<string, string>();
dictionary.GetValueOrDefault("a");
```

**Expected Behavior**:
Code compiles.

**Actual Behavior**:
> CS8620 Argument of type 'Dictionary<string, string>' cannot be used for parameter '@this' of type 'IDictionary<string, string?>' in 'string? UtilityExtensions.GetValueOrDefault2<string, string?>(IDictionary<string, string?> @this, string key, string? value = null)' due to differences in the nullability of reference types.

Removing the optional `TValue` parameter causes the code to compile without issue.

I may just be misunderstanding the expected behavior here, but this error doesn't make sense to me. I would not have expected the presence of an optional parameter to restrict one of the generic type arguments to be nullable.

**Comment by Youssef1313** [comment]
Looks similar to #49340

**Comment by RikkiGibson** [comment]
Presence of the diagnostic doesn't appear to be affected by the usage of the optional parameter. [SharpLab](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQBMQGoA+BiAdgVwBtCJhC4ACOXU8gWACgABABgqYEYAWAbkdfYcAdABEAlhADmuAPawxAYyhCAwjJRwAgjUIBPKGKh8G/AMyCAbOwBMFcQphiZNBLoCiAD3i4DzqIwBvRgoQigBtJgB2EAoAWQhdYDgAOSJCAF1g0KZzTisAFQA1CEJ8SgBxOBhi0rgAeQQROAAzCCIYAB58gGk4XSQKIpKygD4ACizQ0JgAC0MKAEl7R2cIVy7e/sGa0YoURRWXLcmpwc2KAGs+gEoToIZT0P2HJyOhfNdK6uG4MautmT4GAUABuawoCDgUHa12MjxCUQhUPacNCAF9GBiGEA=).

The diagnostic could be more clear, but the issue is that the Dictionary's TKey type parameter has a `notnull` constraint and your TKey type parameter does not have the constraint. To remove the warning you can simply add the `where TKey : notnull` constraint as shown [here](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQBMQGoA+BiAdgVwBtCJhC4ACOXU8gWACgABABgqYEYAWAbkdfYcAdABEAlhADmuAPawxAYyhCAwjJRwAgjUIBPKGKh8G/AMyCAbOwBMFcQphiZNBLoCiAD3i4DzqIwBvRgoQigBtJgB2EAoAWQhdYDgAOSJCAF1g0KZzTisAFQA1CEJ8SgBxOBhi0rgAeQQROAAzCCIYAB58gGk4XSQKIpKygD4ACizQ0JgAC0MKAEl7R2cIVy7e/sGa0YoURRWXLcmpwc2KAGs+gEoKAHcZxEoevooY2RgCYhOghlPQ/YOJxHIT5VyVarDOBjK5bGT4GAUABuawoCDgUHa12M/xCUTRGPaONCAF9GGSGEA).

**Comment by madelson** [comment]
@RikkiGibson I'm surprised that `Dictionary` has a `notnull` constraint on `TKey`. While it's true that null keys are rejected, there is nothing stopping you from creating a `Dictionary<int?, bool>` and it will work fine so long as null keys are rejected. Furthermore, I would think that the `IDictionary` interface would not rule out the possibility of null keys.

**Comment by Youssef1313** [comment]
@madelson `int?` is compiles to a struct `Nullable<int>`, so it isn't actually a real null.

**Comment by madelson** [comment]
@Youssef1313 I'm aware. I thought that `notnull` disallowed nullable value types but it seems like that isn't so.

**Comment by RikkiGibson** [comment]
Documentation indicates that nullable value types are disallowed as keys: https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/generics/constraints-on-type-parameters#notnull-constraint

That said, only a warning is given for violating the constraint, which the user can choose to suppress or ignore. `System.Nullable` dictionary keys have historically been and are still allowed at runtime and that compatibility will be maintained.
