### ISSUE TITLE
In ICommandHandler<T> implementations ExecuteCommand should respect GetCommandState

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#4993]
For example, in `RenameCommandHandler`, which implements `ICommandHandler<RenameCommandArgs>`, `GetCommandState` will delegate to the next handler if `IDocumentSupportsSuggestionService.SupportsRename` returns `false`, but `ExecuteCommand` doesn't consider `SupportsRename`.  As a result, the command will be executed even if it is a subsequent handler that indicates the command is available.

In general, `GetCommandState` will either indicate availability, indicate lack of availability or delegate to the next handler.  `ExecuteCommand` should only do work in the first case - it should never be called in the second and it should delegate in the third.

**Comment by amcasey** [comment]
FYI @dpoeschl

**Comment by Pilchie** [comment]
@CyrusNajmabadi can you take a look through all of our command handlers?  @amcasey If this particular case is an issue for interactive, can you fix the specific case?

**Comment by amcasey** [comment]
@Pilchie I think this is mostly a hygiene issue, since there's only one rename handler.

**Comment by amcasey** [comment]
While we're reviewing this code, why does ```GetCommandState``` take a ```Func<CommandState>```, rather than an ```ICommandHandler<RenameCommandArgs>``` for the next handler?  It seems like it would be much easier to debug without delegates.  Alternatively, "delegate to next" could be a possible return value and then the handler wouldn't have to know about the next handler at all.

**Comment by CyrusNajmabadi** [comment]
We don't want command handlers to be able to manipulate other command handlers. Imagine one GetCommandState calling Execute on another handler.

Also, some handlers need to call other handlers at different times. Some call them first. Some last.  Some in the middle.  So it can't just be a return value for ' delegate to next'.

    -- Cyrus
________________________________

**Comment by dpoeschl** [comment]
This keeps coming up as @amcasey works through his interactive scenarios, and there's two main problems, as far as I can tell:

1. As mentioned above, returning the result of ```nextHandler()``` in ```GetCommandState``` means that the same checks done when deciding to delegate to ```nextHandler()``` in the first place must be done in ```Execute```, but we found several places where this is not happening. By not checking this, we may hijack an ```Execute``` intended for another handler, without doing our desired opt-out checks.

2. Today some command handler returned ```Available```, but then didn't actually handle the command, so another command handler was getting the ```Execute``` on TAB without ever seeing the ```GetCommandState``` for it. This can happen any time an earlier handler fails in a way that's too expensive / difficult / impossible to account for in ```GetCommandState```, but the result is that the ```Execute``` method can't assume that the ```GetCommandState``` checks were ever run, even in cases where it would have returned a definitive ```NotAvailable```, and should therefore double-check the ```GetCommandState``` conditions before proceeding.

**Comment by CyrusNajmabadi** [comment]
> In general, GetCommandState will either indicate availability, indicate lack of availability or delegate to the next handler. ExecuteCommand should only do work in the first case - it should never be called in the second and it should delegate in the third.

Hrmm.  I disagree with this evaluation slightly.  Here's the subtle part that is missed.  GetCommandState may delegate to the next handler to and *still* want to execute the command later on.  This is because many command will delegate down to the final command handler to just decide on things like "is typing a character allowed?"    THis is very common so that every feature doesn't have to do things like check if the buffer is readonly, etc.

--

There are several issues here (which serious subtlety).  Let's look at the rename issue (reported by andrew).  Ideally the RenameCommandHandler would simply say "Unavaliable" if IDocumentSupportsSuggestionService.SupportsRename returned false.  However, if it did this, then that would override anything later in the command chain which did want to support this command. 

Because of that, 'Unavailable' means "i don't support this *and no one else is allowed to either*".  

I think what we want (maybe) is for CommandHandlers to be able to say:

1. I assert that the command is definitely available. (i.e. i will handle it).
2. I assert that the command is definitely not available.  i.e. this is the code in roslyn that ensures the command is not available at all, regardless of whatever anyone else wants.
3. I want to be part of the command chain if *someone* asserts that the command is available.
4. I do not want to participate in executing this command, even if someone asserted it was available.  if you execute the command, leave me out of it.

For something like Rename, it would say "i don't want to participate."  Other command handlers could say "yup, i support this" or "i want to be involved when this is executed."

**Comment by JoshVarty** [comment]
>3. I want to be part of the command chain if someone asserts that the command is available.

What commands require this? I can think of completion, rename etc. when a buffer is readonly or something. Are there any others?

>4. I do not want to participate in executing this command, even if someone asserted it was available. if you execute the command, leave me out of it.

Also what commands require this? Would it be solvable by enforcing strict ordering on commands?

**Comment by CyrusNajmabadi** [comment]
I'm closing this out.  Ideally the new command handler stuff @JoshVarty is working on with @rchande will help adress the fundamental issues here.
