### ISSUE TITLE
VB extension method invocations can be missing certain ancestor nodes

### ISSUE THREAD

**Issue by allisonchou** [dotnet/roslyn#49944]
Using 30811.73.main

Given the following code:
```VB
Module Program
    <Extension>
    Friend Function M(Of T As C)(c As T, Optional opt As Boolean = True) As T
        Return c
    End Function

    Sub M()
    End Sub
End Module

Class C
    Sub M2()
        Dim X  = New C().M
        Dim Y  = New C().M()
    End Sub
End Class
```

The ancestors of `M` in the following line are incorrect, as InvocationExpressionSyntax is missing from the list:

```VB
Dim X  = New C().M
```

![invocationmissing](https://user-images.githubusercontent.com/16968319/101975971-be42b080-3bf5-11eb-887a-a8aaf309b7d8.png)

Contrast this with the ancestors of `M()` in the following line - note InvocationExpressionSyntax is correctly included in the list:
```VB
Dim Y  = New C().M()
```

![invocationpresent](https://user-images.githubusercontent.com/16968319/101975972-c3076480-3bf5-11eb-8a6c-228c73148239.png)

The difference here is simply the parens `()`, but both are functionally the same.
Interestingly, this seems to only be an issue with extension methods.
This blocks #48090

**Comment by Youssef1313** [comment]
I believe this shouldnt be limites to extension methods only, and probably by design.

The syntax tree only shows the syntactical information, by looking at the syntax only, we cant tell if it is a property access or method invocation when parentheses are missing.

The IOperation should be used to know this info.

**Comment by jaredpar** [comment]
I agree with @Youssef1313 analysis here. This behavior is expected because it represents the syntax that is used by the code. In the first case it's a `SimpleMemberAccessExpression` while in the second case it's an `InvocationExpression`. True in VB that these semantically can compile down to the same code but syntactically they are different constructs and represented by different nodes.
