### ISSUE TITLE
Make class 'abstract' in VB.NET applies MustOverride incorrectly - should be MustInherit.

### ISSUE THREAD

**Issue by DualBrain** [dotnet/roslyn#50003]
**Version Used**: 

Visual Studio 2019 v16.8.3

**Steps to Reproduce**:

1.

Create a class as follows:

   Class C
       Public MustOverride Sub M()
   End Class

Notice the error shown as:

Error	BC31411	'C' must be declared 'MustInherit' because it contains methods declared 'MustOverride'.

2.

Hover over the C on the Class line and choose "Show potential fixes" displaying the:

*Make class 'abstract'*

Choose this and to apply the "fix".

3. 

Instead of applying MustInherit, its applying MustOverride; even though the description of the "fix" clearly states the correctly desired result of MustInherit.

**Expected Behavior**:

Apply MustInherit (not MustOverride) on the Class.

**Actual Behavior**:

Applies MustOverride which is completely incorrect and produces a completely different set of error(s) that shouldn't have happened if the right thing would have taken place.

Additionally, would be nice if it could state "Make class 'MustInherit'"; though this may be beyond the scope of what code fixes are capable of doing.

Thanks.

**Comment by ehasis** [comment]
I would like to help on this issue, I just need some guidance since I never contributed to this repo. I managed to track down a possible place where the problem is.

The method [GetDeclarationKind](https://github.com/dotnet/roslyn/blob/fcbb75db9971209e639f580343b0409e6166b6e9/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicSyntaxFacts.vb#L2166) is returning `DeclarationKind.None` because the Select Case does not treat `SyntaxKind.ClassStatement` which is what's coming in the `declaration.Kind`.

Right after that, in the method [GetModifierList](https://github.com/dotnet/roslyn/blob/fcbb75db9971209e639f580343b0409e6166b6e9/src/Workspaces/VisualBasic/Portable/CodeGeneration/VisualBasicSyntaxGenerator.vb#L2476), more precisely in this [line](https://github.com/dotnet/roslyn/blob/fcbb75db9971209e639f580343b0409e6166b6e9/src/Workspaces/VisualBasic/Portable/CodeGeneration/VisualBasicSyntaxGenerator.vb#L2508) the if evaluates false.

I have managed to make it work properly modifying the GetDeclarationKind to evaluates SyntaxKind.ClassStatement and return DeclarationKind.Class.

I can make a commit and push on my fork, but I at least would like some guidance in how I could create a test for this, I'm a bit lost on this.

**Comment by paul1956** [comment]
@ehasis There should already be a test for this area (see below), have you run all the existing tests and see if one or more is failing with your change. If so fix the existing test, if not test fail this is an area not covered and you will need to add a test. If you search BC31411 under Test Explorer you will find 2 tests BC31411ERR_MustOverridesInClass1_1 and BC31411ERR_MustOverridesInClass1_2 that might be the ones, if these are correct add another test there, if they are broken fix them.

**Comment by CyrusNajmabadi** [comment]
> I can make a commit and push on my fork, but I at least would like some guidance in how I could create a test for this, I'm a bit lost on this.

Hi @ehasis Tests for this feature would go in: https://github.com/dotnet/roslyn/blob/master/src/EditorFeatures/VisualBasicTest/MakeTypeAbstract/MakeTypeAbstractTests.vb

Let me know if you need more info :)
