### ISSUE TITLE
Unable to supress CS8901 error

### ISSUE THREAD

**Issue by samcragg** [dotnet/roslyn#50029]
**Version Used**: 
5.0.101

**Steps to Reproduce**:

I have a project targetting `netcoreapp3.1` and defines a class [UnmanagedCallersOnlyAttribute](https://github.com/samcragg/Autocrat/blob/main/src/Autocrat.NativeAdapters/UnmanagedCallersOnlyAttribute.cs) that is added to a public static method (this is to enable calling them from native code via CoreRT).

I have a separate unit test project that verifies the return values of this method.

**Expected Behavior**:

The above compiles fine with the 3.1 SDK and the unit tests pass, however, upgrading to the 5.0 SDK (i.e. not changing any of the code/projects, just installing the SDK) causes a compiler error `CS8901 ... is attributed with 'UnmanagedCallersOnly' and cannot be called directly` and the unit tests are unable to be ran.

**Actual Behavior**:

[This MR](https://github.com/dotnet/roslyn/pull/47311) introduced the diagnostics, however, I'm unsure why the compiler now issues an error for previously well behaving code? Can this be changed to a warning please, which I can then surpress in my unit test project?

**Comment by Youssef1313** [comment]
cc: @333fred

**Comment by PathogenDavid** [comment]
This attribute has special meaning to the C# compiler now, and it doesn't discriminate where it's defined because it's matched by shape. It previously only had meaning to CoreRT, which was and continues to be an experimental runtime.

Your best bet is probably to pin your compiler to an old version using [Microsoft.Net.Compilers.Toolset](https://github.com/dotnet/roslyn/blob/afd10305a37c0ffb2cfb2c2d8446154c68cfa87a/docs/compilers/Compiler%20Toolset%20NuPkgs.md).

Alternatively, move your unit tests to .NET 5 and your project to newer versions of CoreRT which use the attribute in the BCL. Then modify your unit tests to call the methods via function pointer as recommended in the spec and the error message.

**Comment by 333fred** [comment]
Good suggestions David. The other suggestion I would have is to conditionally attribute your methods, not attributing them when running your unit tests. `UnmanagedCallersOnly` does mean that the method cannot be called from managed code, and the .NET 5 runtime will actually throw an exception if you attempt to do so, so this isn't something that can or should be a warning. While I'm sympathetic to the use case, the attribute was only introduced publicly with .NET 5 (it was previously `NativeCallableAttribute`, and internal), and it has special meaning.

**Comment by 333fred** [comment]
Also /cc @MichalStrehovsky if you have any other guidance.

**Comment by MichalStrehovsky** [comment]
Yep, I agree what was said above. I assume this only worked because the CoreRT side was already ".NET 5" (CoreRT doesn't really version), but the unit test side was .NET Core 3.1 that doesn't know about the attribute.

If the unit test was also compiled with ".NET 5" CoreRT, it would [throw at runtime](https://github.com/dotnet/corert/pull/5015) too because UnmanagedCallersOnly methods can only be called through some sort of p/invoke.

**Comment by samcragg** [comment]
Wow, I thought you were exaggerating when you said you couldn't call it at runtime, as the generated IL for a method with the attribute is the same as one without (minus the attribute constructor), but the following proves bad things happen:

``` c#
public static unsafe class Program
{
    public static void Main()
    {
        var method = new DynamicMethod("TestMethod", null, null);
        ILGenerator generator = method.GetILGenerator();
        generator.Emit(OpCodes.Call, typeof(Program).GetMethod(nameof(StaticMethodWithAttribute)));
        generator.Emit(OpCodes.Ret);
        Action action = method.CreateDelegate<Action>();

        Console.WriteLine("Invoking delegate");
        action();
        Console.WriteLine("Done");
    }

    [UnmanagedCallersOnly(EntryPoint = "StaticMethodWithAttribute", CallConvs = new[] { typeof(CallConvCdecl) })]
    public static void StaticMethodWithAttribute()
    {
        Console.WriteLine("Inside method");
    }
}
```

Unfortunately, the shape matching seems to fail when trying to create a pointer to the method when targetting `netcoreapp3.1`. The following code fails to compile:
```c#
namespace System.Runtime.InteropServices
{
    [AttributeUsage(AttributeTargets.Method)]
    public sealed class UnmanagedCallersOnlyAttribute : Attribute
    {
        public Type[]? CallConvs { get; set; }
        public string? EntryPoint { get; set; }
    }
}
public class TestClass
{
    public void TestMethod
    {
        // CS8786 Calling convention of 'TestClass.StaticMethodWithAttribute()' is not compatible with 'CDecl'.	
        delegate* unmanaged[Cdecl]<void> method = &StaticMethodWithAttribute;
    }

    [UnmanagedCallersOnly(EntryPoint = "StaticMethodWithAttribute", CallConvs = new[] { typeof(CallConvCdecl) })]
    public static void StaticMethodWithAttribute()
    {
    }
}
```
I can, however, generate the `ldftn`+`calli` combo via reflection emit to invoke the method, so I think that compiler error is incorrect here (i.e. the code _does_ work at runtime).

Should I raise a seperate issue for CS8786 (note it would _really_ be helpful if the error told you what calling convention it was expecting - just saying that's not the right one isn't very helpful)?

**Comment by MichalStrehovsky** [comment]
> I can, however, generate the `ldftn`+`calli` combo via reflection emit to invoke the method, so I think that compiler error is incorrect here (i.e. the code _does_ work at runtime).

It does, but it's not a "normal call".

Placing the `UnmanagedCallersOnly` attribute on the method changes the calling convention. The machine code (not the IL) generated for the method will assume that it's getting called from native code, so at the beginning of the method, there will be code that sets up the GC/exception handling infrastructure in a way that says "entering managed code now". At the end of the method just before returning, it will do the opposite.

The `calli` is an unmanaged calli, so it does the opposite (sets up GC/EH infrastructure to say "leaving managed code" before invoking the function pointer and sets things up as "now in managed code" once the call returns).

Roslyn could make this transparent and do a ldftn/calli combo instead of a call, but as you can see, it has overhead. It would probably be disservice.

> when targetting netcoreapp3.1

When targetting netcoreapp3.1, the UnmanagedCallersOnly attribute is meaningless (runtime doesn't know about it to generate different machine code), so this becomes a managed method as any other. That's why there's a calling convention mismatch.
