### ISSUE TITLE
autocomplete for override keyword does not work immediately after class’s opening curly brace

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#50060]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/autocomplete-for-override-keyword-does-n/1291369)._

---
If I have code like this:

```csharp
abstract class MyBase {
  protected abstract void DoSomething();
}
class MyImplementation : MyBase {
}
```

If I type “override” followed by a space at the end of the line on the same line as the `{` in MyImplementation, I do not get an autocomplete which includes `DoSomething()`. If I instead type that on a new line after the `{`, I do get the expected autocomplete box.

Please fix the autocomplete to come up in any circumstance where I am typing `override` at the top level of inside of a class.

Example of lack of autocomplete on the same line as the curly: ! [not working on same line as opening curly] (https://i.imgur.com/d46diKd.png)

Example of working on a different line from the curly: ! [working on a different line from the opening curly] (https://i.imgur.com/IFw5llP.png).

Thanks.

---
#### Feedback Bot on 12/17/2020, 11:42 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Note that this was intentional and has been how the feature has worked since introduction nearly 17 years ago. The general idea I remember even then it's that we didn't want to interfere with typing on lines that ahead contain code of some form. 

This coding style does not seem common at all (I dunt believe we've heard this happening in decades), so I would generally be opposed to any changes here to support this.

**Comment by binki** [comment]
@CyrusNajmabadi
> Note that this was intentional and has been how the feature has worked since introduction nearly 17 years ago. The general idea I remember even then it's that we didn't want to interfere with typing on lines that ahead contain code of some form.

Hmm. So it looks like `override` autocomplete will trigger on a line if I type it prior to a comment but not if I type it on a line containing a property declaration or any semicolon or curly brace. It looks like this is to try to avoid triggering this in the middle of an existing property declaration. I never thought of typing something following a class’s opening `{` as being on the same line as a class member in that way. I feel like my scenario should be treated as if I were on the same line as a comment instead of being treated the way it is, but I guess I might be the only person thinking this way ;-).

> This coding style does not seem common at all (I dunt believe we've heard this happening in decades), so I would generally be opposed to any changes here to support this.

I don’t understand ;-). I am not using a coding style that is uncommon. I am using VisualStudio’s default automatic formatting as my style [wherever VisualStudio](https://github.com/dotnet/roslyn/issues/37375) [is willing to](https://github.com/dotnet/roslyn/issues/41323) [perform automatic indentation](https://github.com/dotnet/roslyn/issues/48856). I am just using VisualStudio’s automatic formatting feature to type fewer keystrokes, similar to how I rarely type an identifier’s full name thanks to IntelliSense or how I never type spaces within the `{ get; set; }` portion of an auto-implemented property.

I often have something like this:

```csharp
class X
{
}
```

Then I type something like this:

```csharp
class X
{string MyProperty{get;set;}
}
```

Upon typing the final `}` within the property, spaces are inserted within the auto-implemented property, giving me this but still leaving it on the same line as the opening curly (which I don’t want).

```csharp
class X
{string MyProperty { get; set; }
}
```

and then I run Edit/Advanced/Format Document (Ctrl+k,Ctrl+d). The result is this:

```csharp
class X
{
    string Myproperty { get; set; }
}
```

I don’t see the point in typing newlines if I can get VisualStudio to do this for me! ;-) So I have trained myself **not** to do so when introducing a new member to the beginning of the class. When I start introducing an `override` of a base class’s property, I don’t think of that as a special case where I need to manually insert a newline—until I remember that I researched why `override` was broken for me once and filed this issue.

When I rediscover this behavior, I keep trying to trigger the `override` autocomplete and I get a behavior indistinguishable from the scenario where there are no overridable members. Then I look at the base class, expecting to find that I forgot to put `virtual` or `abstract` on a member. And then I find out that I didn’t forget, just VisualStudio’s autocomplete isn’t triggering how I expect it to. And then I remember that I filed this issue and check up on it and find out that it’s not going to be fixed :'(. Well, I guess the justification for not fixing it is somewhat acceptable. I guess I have to start inserting newlines manually when overriding base members if I want VisualStudio’s help.
