### ISSUE TITLE
Inconsistent devirtualization with sealed/covariant returns

### ISSUE THREAD

**Issue by kevingosse** [dotnet/roslyn#50175]
Consider the following code ([sharplab](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxASwDYB8ACAmARgFgAoUnAZgAIJhYEIBjGK/KgIWjgGENopSAb1JVRrarXpMWAe2AArOMyoBZODAAWMgCYAKAJQBuUgF9S5alDgQMcbazxUAytdvaA8gDte/KiA5cPlACJMIkYuJUMgBuiAho2nCsBAAMqupaevpUALwAfFSeAK4YGMYkZmQklA7OrnZeapo6fgFWQSFhETVWNnZRsQjxiclpTZkGuQXFpeWVFrU4BADsVEIiYvh4G6JdEWKecADudX0e3nzBBgB04zoG5fsHx6dujRn3+rcfWY9iJhFTKQgA=)) :

```csharp
public abstract class BaseClass
{
    public abstract object Method();
}

public sealed class SealedOnClass : BaseClass
{
    public override string Method() => null;
}

public class SealedOnMethod : BaseClass
{
    public sealed override string Method() => null;
}

public class Program 
{
    public static void Main()
    {
        new SealedOnClass().Method();
        new SealedOnMethod().Method();
    }    
}
```

The `Main` method is compiled into:

```
        IL_0000: newobj instance void SealedOnClass::.ctor()
        IL_0005: callvirt instance string SealedOnClass::Method()
        IL_000a: pop
        IL_000b: newobj instance void SealedOnMethod::.ctor()
        IL_0010: call instance string SealedOnMethod::Method()
        IL_0015: pop
        IL_0016: ret
```

The compiler is devirtualizing the call when `sealed` is applied on the method, but not when its applied on the class, even though I believe both should be equivalent.

**Comment by jaredpar** [comment]
This behavior is "By Design". 

The CLI spec only allows a `.call` instruction on a virtual method in very specific cases. Roughly it comes down to:

- When the method is final (or `sealed` in C# terms) 
- When the receiver is `this`. This is to support scenarios like using `base.` to access the method higher up in the inheritance chain. 

The C# compiler behavior here is consistent with the CLI spec here. In the case of a `sealed` method it's legal to use `.call` but in the case of a `sealed class` it is not. 

The relevant section from the CLI spec is the following 

> When using the call opcode to call a non-final virtual method on an instance other than a boxed value type,
verification checks that the instance reference to the method being called is the result of ldarg.s 0, ldarg 0 and
the caller’s body does not contain starg.s 0, starg 0 or ldarga.s 0, ldarga 0.
