### ISSUE TITLE
AnalyzerDependencyChecker creates spurious warning regarding mscorlib

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#5065]
In response to #3020, several **System** assemblies were intentionally excluded from analysis by AnalyzerDependencyChecker. We are currently running into the same problem for **mscorlib** (see DotNetAnalyzers/StyleCopAnalyzers#1345 for reference). Should the same exclusion apply to this assembly as well?

**Comment by sharwell** [comment]
@tmeschter @mavasani Do you know if there are plans to eventually resolve this from the Roslyn side? I'm looking to communicate a resolution plan back to the StyleCop Analyzers users since we've had multiple reports now. :smile:

**Comment by mavasani** [comment]
@sharwell Yes, I hope to take a look at these issues next week.

**Comment by tmeschter** [comment]
@sharwell @mavasani We should certainly be excluding mscorlib, and I thought the AnalyzerDependencyChecker already did that. However, there were enough changes to it shortly before RTM that something could have been missed. :-(

**Comment by vbfox** [comment]
We have the exact same issue but with `Microsoft.CodeAnalysis.VisualBasic` in an internal project should I open a separate issue ?

The warning only happens when the project is reloaded (by changing the csproj on disk due to `git pull` for example), the first load never display them.

[RefactoringEssentials](https://github.com/icsharpcode/RefactoringEssentials) seem to [have an issue](https://github.com/icsharpcode/RefactoringEssentials/issues/98) with this dll too (In the same conditions).
