### ISSUE TITLE
Intellisense is allowing Method to be added that is not supported in runtime.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#50698]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Intellisense-is-allowing-Method-to-be-ad/1317210)._

---
[severity:It's more difficult to complete my work]
Windows 10. .NET 5.0  for a thread allows . Abort or . Suspend yet when you run the application you get 
 "System.PlatformNotSupportedException: 'Thread suspend is not supported on this platform.'"

Works Framework 4.7.

Why does Intellisense allow something for a framework where it will not actually run?

---
#### Feedback Bot on 1/21/2021, 07:18 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by Youssef1313** [comment]
The current behavior is the expected behavior. While the runtime implementation was changed (as a breaking change, which is documented [here](https://docs.microsoft.com/en-us/dotnet/core/compatibility/unsupported-apis)), the IDE can't disallow calling the method by itself. However, the compatibility analyzer should be able to warn you against these case.
