### ISSUE TITLE
List of compiler inputs that affect deterministic compiler output

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#5070]
We are aiming to make the compilers ultimately deterministic (#372). What that means is that the "same inputs" will cause the compilers to produce the "same outputs". This issue is a place for us to gather the list of things that are considered inputs to the compiler. At the moment the compiler also depends on the time of day and random numbers for GUIDs, so it is never deterministic unless you specify `/features:deterministic`.

The following will be considered inputs to the compiler for the purpose of determinism:

- The sequence of command-line flags
- The contents of the compiler's `.rsp` response file.
- The precise version of the compiler used, and its referenced assemblies
- Current full directory path (we are working to enable you to reduce this to a relative path; see #949)
- (Binary) contents of all files explicitly passed to the compiler, directly or indirectly, including
  - source files
  - referenced assemblies
  - referenced modules
  - resources
  - the strong name key file
  - `@` response files
  - Analyzers
  - Rulesets
- The current culture
- The default encoding (or the current code page) if the encoding is not specified
- The existence, non-existence, and contents of files on the compiler's search paths (specified, e.g. by `/lib` or `/recurse`)
- The CLR platform on which the compiler is run (e.g. the result of `double` arithmetic performed for constant-folding may use excess precision on some platforms).

What am I missing from this list? How shall we indicate, for example, the version of the platform you're compiling against? Are there other environment variables or resource settings that affect the compiler's output?

Once we start "supporting" determinism this list will be put in with the compiler documentation.

**Comment by tmeschter** [comment]
It's worth calling out that the order of arguments on the command line will affect compiler behavior. E.g., the relative order of `/nowarn` and `/warnaserror` switches, and, more subtly, the order in which analyzer assemblies are specified. We load analyzer assemblies in the order given, so if you have two analyzer assemblies with the same identity we will only load the first.

**Comment by gafter** [comment]
@tmeschter Thanks. I think I've changed the description to account for that. Please tell me if you think the changes are insufficient.

**Comment by gafter** [comment]
@tmeschter What do we do if the compiler (server) has already loaded a different version of an analyzer assembly from the one specified on the command line?

**Comment by tmeschter** [comment]
@gafter vbcsompiler.exe handles analyzer assembly loading in a different manner than csc.exe/vbc.exe, so I'll try to give a full description of both behaviors and why they are different.

csc.exe loads the analyzer assemblies in the order given on the command line, and doesn't worry about whether or not the identity of the loaded assembly matches the identity of the assembly on disk. For example, say you have two analyzer assemblies with different contents but the same identity

* C:\lib\MyAnalyzer\Foo.dll
* C:\lib\MyOtherAnalyzer\Foo.dll

Since these have the same identity, the runtime will really only load the first. When the compiler asks to load the second, the runtime just returns the first one again.

This means that builds are deterministic (the same analyzer is used every time) but one of your analyzers may not run, or may run incorrectly.

vbcscompiler.exe, on the other hand, cannot guarantee the order in which the assemblies are loaded. Instead, it tries harder to ensure that the assembly you asked for is actually the assembly you got. Every time it asks the runtime to load an analyzer, it checks the MVID of the loaded assembly against the MVID of the assembly on disk. If they match we assume the assemblies are identical and the compilation proceeds. If they *don't* match, vbcscompiler.exe rejects the submission, which will fallback to to spinning up a new copy of csc.exe/vbc.exe.

**Comment by gafter** [comment]
@tmeschter In either case (csc or vbcscompiler), we get deterministic behavior. Nice!

**Comment by gafter** [comment]
Anyone interested can review the proposed documentation at #7498 (please)
