### ISSUE TITLE
Build MS Solution fails when loading Roslyn libraries

### ISSUE THREAD

**Issue by VE-2016** [dotnet/roslyn#50737]
**Version Used**: 

NuGet version 3.8.0

Microsoft.CodeAnalysis

**Steps to Reproduce**:
 - create VS 2019 c# Project 
- install Microsoft.CodeAnalysis and Microsoft.CodeAnalysis.Workspaces.MSBuild - at present versions 3.8.0
- implement method to compile MS Build Solution in Visual Studio 2019 in dedicated Project
- compile vs Project
- run Project

When starting project, the following error occurs

System.IO.FileLoadException: 'Could not load file or assembly 'Microsoft.CodeAnalysis, Version=42.42.42.42, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)'

**Expected Behavior**:
No errors

**Actual Behavior**:

Maybe it has connection with my prior compiling Roslyn repository by standard scripts Restore / Build.cmd. Especially because this build was marked with libraries as 42.42.42.42 - but Nuget versions are 3.8.0

**Comment by Youssef1313** [comment]
@VE-2016 I'm not sure. But you could try deleting the nuget cache for these packages. You'll find them in `C:\Users\<your_username>\.nuget\packages`. In that directory, try deleting packages starting with `Microsoft.CodeAnalysis`. When you next run `dotnet restore`, these packages will be re-downloaded from NuGet instead of using the cached ones.

If this doesn't work, you can wait for an official answer by a Microsoft employee.

**Comment by VE-2016** [comment]
Hello,
it is configuration issue only. After recreating new project everything goes fine.

JK
