### ISSUE TITLE
Resource strings with format arguments.

### ISSUE THREAD

**Issue by Quantumplation** [dotnet/roslyn#508]
I very often find myself doing: 

``` csharp
String.Format(Resources.SomeMessage, CustomerName, OrderAmount);
```

I would love to be able to do:

``` csharp
Resources.SomeMessage(CustomerName, OrderAmount);
```

Perhaps with appropriately named parameters?

For example, if, instead of {0} and {1}, your format string was "Unable to place {0}'s order, totaling {1}.", the parameters to SomeMessage would be named appropriately.

Does anyone else have other ideas for similar syntactic convenience?

**Comment by HaloFour** [comment]
@Quantumplation I've submitted a request to UserVoice for this very thing:

[Support String Interpolation in Resources Project Items](https://visualstudio.uservoice.com/forums/121579-visual-studio/suggestions/6966938-support-string-interpolation-in-resources-project)

I think that it's more of a tooling concern than a language concern.  Some expansion of the resx designer to allow adding these special strings and associating a name and type with the required values.  The code generator could then spit out the appropriate methods which would call `String.Format` using the raw resource and the generated parameters.

**Comment by ilmax** [comment]
@Quantumplation @HaloFour have you tried using [resources.tt](https://github.com/aspnet/EntityFramework/blob/9f04089d5bf30ae6498ccefa7ed5a7c1b48bb03e/tools/Resources.tt) from entity framework? It solves this problem generating a method instead of a property + string.format. I agree that the rest gen tool could be revamped.

**Comment by khellang** [comment]
In the meantime, I use [this project](https://github.com/khellang/ResourceHelperGenerator) (yeah, the name sucks) for this very thing in all my projects. It's basically just a .targets file and a MSBuild task that's added to the project through NuGet that generates a strongly typed helper for your .resx files residing under the Properties folder :smile:

**Comment by khellang** [comment]
BTW, there's [a thread over at the .NET foundation forums](http://forums.dotnetfoundation.org/t/include-tools-in-the-open-source-efforts/470) going on about OSS'ing different tools. It might be worth it to add your :+1: on Resgen.exe over there as well? :smile:

**Comment by theoy** [comment]
I agree this is a good idea, though at the moment, the Roslyn/languages team is not currently the owner of this tool. But we're industrious at chasing down the right .NET partners. Assigning this to Mads for now because I remember localized resources came up during the design discussion for String Interpolation for C# 6.

**Comment by thomaslevesque** [comment]
It would be nice, but it has nothing to do with the C# language itself. I guess it could be done with a custom tool to use instead of ResxCodeFileGenerator, or with a T4 template.

BTW, if you want a better way to write resource strings with format args, you might be interested in [this](http://www.thomaslevesque.com/2014/11/17/stringtemplate-another-approach-to-string-interpolation/); it's a library that lets you do something like String.Format, but with named placeholders instead of numbers.

**Comment by gafter** [comment]
We are now taking language feature discussion on https://github.com/dotnet/csharplang for C# specific issues, https://github.com/dotnet/vblang for VB-specific features, and https://github.com/dotnet/csharplang for features that affect both languages.
