### ISSUE TITLE
Microsoft.CodeAnalysis.Common package dependencies are superfluous

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/roslyn#50832]
**Version Used**: Microsoft.CodeAnalysis.Common, 3.9.0-3.final

**Expected Behavior**: The package should not list any inbox dependencies for the .NETCoreApp,Version=3.1 configuration.

**Actual Behavior**: The package lists superfluous dependencies for the .NETCoreApp configuration which blocks dotnet/runtime using the package as it creates a restore cycle for inbox libraries like System.Collections.Immutable.

cc @sharwell

**Comment by jaredpar** [comment]
> The package should not list any inbox dependencies for the .NETCoreApp,Version=3.1 configuration.

Why do you believe that this is the case? There are APIs that we use from SRM in `netcoreapp3.1` that only exist in the `net5.0` version of SRM. Removing the dependency will essentially remove the APIs that we need here. 

This is not a one time problem either, it's a more general one. For many reasons the compiler, and really any other tool in the SDK, must target `netCurrent - 1` when the runtime is in active development of `netCurrent`. Hence we can never truly depend on APIs coming from `netCurrent` directly but instead always have to go through NuGet packages here.

**Comment by ViktorHofer** [comment]
That makes total sense but what prevents us from adding a net5.0 configuration to the package which wouldn't require the additional package dependencies? In response to NetCoreAppCurrent - 1.

**Comment by jaredpar** [comment]
That works but not at a regular cadence. Consider that at this very moment we could add a `net5.0` configuration which doesn't require a reference to SRM but if you back up to say July 2020 this would not be true as the ref only existed in SRM. Yes it did exist in the `net5.0` packages but we could not consume that SDK in roslyn for all the reasons it's difficult to grab SDK late in the cycle. Hence we were essentially stuck on an SDK for some time which didn't have it. 

Adding another configuration here does add a bit of overhead for us as well. It means we need to triple target our main binaries to `net472`, `netcoreapp3.1` and `net5.0` and as a result we have to also triple target our test assemblies. Today we only dual target them to `net5.0` and `net472`. That works fine due to roll forward. If we add `net5.0` here though then our test assemblies will be testing our `net5.0` versions (which ship absolutely nowhere) and no longer testing our `netcoeapp3.1` binaries (which ship everywhere)

**Comment by ViktorHofer** [comment]
CodeAnalysis.Common isn't apackage that we would want to consume right now so it's not a blocker but https://github.com/NuGet/Home/issues/6754 probably needs more attention as such issues will likely appear again in the future with any packages that have overlapping identities which we use during building.

Based on your feedback (which I agree on), nothing needs to be done for this specific package though.
