### ISSUE TITLE
Compiler does not give helpful error message when records aren't available.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#50887]
![image](https://user-images.githubusercontent.com/4564579/106221762-11b39280-6193-11eb-908b-8cbaf6014336.png)

This error is not actionable.  

1. it should tell me what i should do to be able to use records.
2. it should provide a fixer to move to be able to use records.

@jcouv ?

**Comment by CyrusNajmabadi** [comment]
Note: this is our default OOB experience creating a new project.

**Comment by jcouv** [comment]
This is pretty much the standard experience for new features :-/ 
You'd get a similar error for tuples or async-streams if you are not referencing a framework with the required types. 
I suspect there would be pushback on giving more details in the compiler message because the compiler should be oblivious to frameworks and TFMs (we're not even given that information, we only see sources and references).

**Comment by CyrusNajmabadi** [comment]
1. Can we provide a fixer to help here?
2. Can we make it so a default project can actually use the latest Lang features?

**Comment by CyrusNajmabadi** [comment]
> I suspect there would be pushback on giving more details in the compiler message 

I don't like that. I think it's fine to have the precise message, but it should say least mention how you might be able to get this type as an additional possible hint to get the user to the next step

**Comment by RikkiGibson** [comment]
This looks like the case where langversion is latest but target framework is out of date. It's also bad when the langversion is the default for the target framework. The record parses as a method in that case.

**Comment by jaredpar** [comment]
This can only happen though when you manipulate the language version directly. Essentially when you use `/langVersion:9` explicitly even though you're targeting say `net472`. That's an unsupported scenario. 

> This is pretty much the standard experience for new features :-/

@jcouv is correct here. When you use `/langVersion` in unsupported ways the error messages can be pretty raw and the recommendation to customers is to not do that. 

> Can we make it so a default project can actually use the latest Lang features?

It's unclear what default you used here but no default I'm aware of will produce this message. In order to get this message you need to be using `<LangVersion>9</LangVersion>`, other wise you'd get a different error here because we don't even attempt to parse records in 8 or lower. That is only ever implicitly set via `<TargetFramework>net5.0</TargetFramework>` in which case the code will compile successfully. 

If there is a project default that produced this message I'd be very interested in working with them to change it but there are none that I'm aware of here that do this.
