### ISSUE TITLE
Introduce DiagnosticBag.Null

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#50957]
There are lots of places that we need to pass a DiagnosticBag and discard it immediately.

Would it be possible to implement a singleton dummy DiagnosticBag that doesn't hold any data so we can just pass it directly without the need to call Free?

**Comment by jaredpar** [comment]
Doing this would require us to either add an inheritance hierarchy to `DiagnosticBag` or to complicate it's implementation quite a bit. The inheritance directly on `DiagnosticBag` would worry me a bit because it's pretty core to the project, not sure how it would impact perf if we added a string of virtual method invocations into that code path. Would definitely want to measure it. Complicating the internals is also a bit dicey. 

Part of me wonders if this would be better done with a wrapper like a disposable `ref struct` around `DiagnsosticBag` that automated this process. Not sure if that's worth it though.

@cston, @333fred for comment

**Comment by alrz** [comment]
>not sure how it would impact perf if we added a string of virtual method invocations into that code path

As far as I'm aware, the compiler already emits callvirt here (for null check).

>Part of me wonders if this would be better done with a wrapper like a disposable ref struct around DiagnsosticBag that automated this process. Not sure if that's worth it though.

While it does remove `Free` calls, using a no-op impl means that we are not doing unnecessary work, so it's not just for convenience.

**Comment by 333fred** [comment]
> As far as I'm aware, the compiler already emits callvirt here (for null check).

Yes, but actually having to do the virtual call lookup will be more expensive. The JIT is very good at making `callvirt` not incur penalties when you use it to call a non-virtual method.

The `ref struct` wrapper idea is interesting though.

**Comment by alrz** [comment]
`BindingDiagostics.Discard` already covers this.
