### ISSUE TITLE
unexpected CS8602 after null-forgiving

### ISSUE THREAD

**Issue by tmds** [dotnet/roslyn#51004]
Reproducer:

```cs
using System;

MyClass? instance = TryCreateInstance();
Foo(instance!);
int age = instance.Property; // warning CS8602: Dereference of a possibly null reference.

MyClass? TryCreateInstance() => new MyClass();
void Foo(MyClass p) { }

class MyClass
{
    public int Property { get; set; }
}
```

Expected:

null-forgiving on `Foo(instance!);` causes no warning on the next line.

Actual:

warning CS8602: Dereference of a possibly null reference.

**Comment by jaredpar** [comment]
Thanks for taking the time to file this issue, unfortunately this behavior is "By Design". 

The compiler only updates the state of a "maybe null" argument to "not null" when it gives a corresponding warning. The reasoning being that essentially we don't want to double warn for the same problem here. In this case no warning was issue, it was suppressed, hence the state of the argument is not changed. 

More discussion here https://github.com/dotnet/csharplang/discussions/4102#discussioncomment-128346

@RikkiGibson in case I missed a subtle issue here.

**Comment by tmds** [comment]
To be clear about the behavior:

```cs
Foo(instance);
int age = instance.Property;
```
gives a warning on the first line for `instance` being passed in as a _Possible null reference argument_ (CS8604).

And then adding a null-forgiving to it: `Foo(instance!);`.
causes the warning to move to the next line as _Dereference of a possibly null reference_ (CS8602).

**Comment by jaredpar** [comment]
Understood. That is the intended behavior by the current design.
