### ISSUE TITLE
VB Interactive: was never finished

### ISSUE THREAD

**Issue by paul1956** [dotnet/roslyn#51062]
**Version Used**: 
All
**Steps to Reproduce**:
N/A
@CyrusNajmabadi  asked that I open this issue
**Expected Behavior**:
VB Interactive is approved to be finished, or at least the NuGet Interactive Package includes the VB component. 

There are 2 separate but related issues,
1) There are consumers of the Roslyn Interactive NuGet package (including DotNet command line @dualbrain can provide more details here). It appears to add VB to the Package required an existing VB project be added to the NuGet package project file and not much else.

2) Visual Studio has C# and F# interactive windows, To add VB requires much more work then above, the C# interactive project assumes it is the only language so it would need some refactoring to abstract the common parts and then have the C# and VB parts implement the language specific parts, Or replicate (clone) the whole C# thing in VB and change it to handle VB, F# has a separate package. The second is not a huge task and could be handled by a community PR, but would be harder to support. The first is probably the correct approach and overall easier to support.

My question is, is anyone willing to support, first the NuGet Package that others can use and secondly the design work so that a community PR for a VB Interactive command line would be accepted.

I would be willing for work on the VB specific parts of a restructuring effort. I tried the clone method and it took less then a day but there was no easy way to do anything with given the existing Interactive Project Structure but if someone could address that I would work on that as well.

**Actual Behavior**:
VB interactive work appears to have stopped in 2015, and the many issues that say Help Wanted should be closed the underlying design has changed and the code they reference no longer exists.

**Comment by CyrusNajmabadi** [comment]
tagging @jinujoseph @mikadumont @tmat

**Comment by govert** [comment]
I would love to see, and can try to support in various ways, some progress on the Roslyn Scripting libraries and packages for VB, without having any built-in support for a VB interactive window in Visual Studio. 

There are now a number of downstream projects that use the Roslyn scripting libraries for C# under the `Microsoft.CodeAnalysis.Scripting.*` namespace. These projects include
* the [`dotnet script `](https://github.com/filipw/dotnet-script) tool by @filipw, 
* the .NET support for Jupyter as [.NET Interactive](https://github.com/dotnet/interactive) and 
* support for .csx files in VSCode via OmniSharp.
* support for C# scripting in tools like [RoslynPad](https://github.com/aelij/RoslynPad).

These projects have also added support for features like `#r nuget:..."` support and work towards having C# also available as a command-line shell scripting tool - a role that VBScript had for a long time (it was enabled by default in Windows until 2019).
Given that there is a long and successful history of VBScript in this role, it would be great to see an Roslyn-supported .vbx file format that can be used the same way, building on the modern dotnet infrastructure. So having VB support in the scripting can assist in the legacy VBScript -> .NET upgrade story.

Also, since F# has a similar .fsx scripting file format and support (NuGet etc.), having VB support at the compiler level motivates more .NET-related tools supporting not just C# but the trio of mainstream .NET languages.

To even consider adding VB support to these new generation scripting tools, it would be a great help to have parity at the Roslyn side which, as @paul1956 points out, might not be too hard to reach.

I don't know if there were any language-level issues and decisions outstanding related to the VB scripting / interactive. It so, that should probably be the first consideration. I don't know if anyone can comment or remember whether the Roslyn compiler and evaluation side got stalled for technical reasons, or whether that was just driven by a priorities from the VS side.

Broadly I think the steps would be:
* review and cleaning up the stale issues, 
* creating a list of current work items and 
* some indication that work on these could be considered for inclusion into the Roslyn repository, 
* finally leading to support and NuGet packages bringing VB scripting on par with C#.

Support for VB Interactive in Visual Studio might be added later, or could be done as an open source or even third-party extension. But Roslyn is spreading beyond Visual Studio, and the lack of a VB script story from Roslyn is holding VB back now.

**Comment by tmat** [comment]
If you'd like to see VB interactive working then first we'd need to finish implementation of VB scripts in the VB compiler and add good amount of tests. The compiler team would need to review and approve these changes. /cc @jaredpar 

Once that's done I see no reason not to publish Microsoft.CodeAnalysis.VisualBasic.Scripting package that could then be used in the projects that you mention above.

Getting VB Interactive Window enabled in VS would require additional work in Roslyn IDE layer, where we would need to make sure that all features work reasonably well in interactive context and are covered by tests.

**Comment by paul1956** [comment]
@tmat are there specific issues with VB Scripts? I use SourceCodeKind.Script extensively (assuming we are talking about the same thing ) and the only thing I have seen is the lack of Top Level Statement support, which I have easily worked around but would be nice.

**Comment by tmat** [comment]
Compare https://github.com/dotnet/roslyn/blob/932e0f15a7be82ff3ee7e829615f026fdda1d9ee/src/Compilers/CSharp/Test/Semantic/Semantics/ScriptSemanticsTests.cs with https://github.com/dotnet/roslyn/blob/932e0f15a7be82ff3ee7e829615f026fdda1d9ee/src/Compilers/VisualBasic/Test/Semantic/Semantics/ScriptSemanticsTests.vb.

and Microsoft.CodeAnalysis.CSharp.Scripting.UnitTests project with Microsoft.CodeAnalysis.VisualBasic.Scripting.UnitTests

We need at lease the same coverage as C# script tests.

**Comment by paul1956** [comment]
@tmat Thanks that helps, given the communities willingness provide the tests (C# has 76, VB has 3, so its tests that are missing), what else is lacking and would such as PR be approved. I still think we need to see everything required to get from here to a VB Scripting package to VB Interactive and potential milestones with approval from whoever needs to approve and who would review the PR's. I would sign up to look at the 76 tests.

**Comment by DualBrain** [comment]
> would such as PR be approved

> If you'd like to see VB interactive working then first we'd need to finish implementation of VB scripts in the VB compiler and add good amount of tests. The compiler team would need to review and approve these changes. /cc @jaredpar

@paul1956 and @tmat Would the above statement be enough of an "approval" to get the ball rolling or is something more definitive needed?

**Comment by tmat** [comment]
@paul1956 

> what else is lacking and would such as PR be approved

I don't actually know. The tests would facilitate discovery of what's lacking. The best approach would be to write the tests and document all missing features and bugs found in a form of issues.

I believe this list would also help the compiler team to decide if these changes are desirable.

**Comment by jaredpar** [comment]
> If you'd like to see VB interactive working then first we'd need to finish implementation of VB scripts in the VB compiler and add good amount of tests. The compiler team would need to review and approve these changes

At this time these changes would not meet the compiler teams bar.

**Comment by paul1956** [comment]
@tmat the C# tests use a version of CSharp Compilation that has more functionality then the VB version. It has an additional Constructor for starters that supports a SyntaxAndDeclarationManager. This part of the Code is part of the core compiler, would this be handled separately?

**Comment by tmat** [comment]
@paul1956 Yes, `SyntaxAndDeclarationManager` has been added to handle `#load` directives for scripts.

**Comment by paul1956** [comment]
@tmat without SyntaxAndDeclarationManager and the new constructor that uses it,  porting some of the tests would would not be possible but most of the tests can be converted. VB Top Level Statements is the other obstacle for some of the tests.

**Comment by sharwell** [comment]
Marking as blocked on compiler team bar

**Comment by paul1956** [comment]
@sharwell For those outsiders is "Blocked" the same as Dead/Closed/Never going to be done... if not please explain next steps? For example would adding the tests that currently could pass be accepted as "improving testing for VB Scripting" or is there no point in doing anything.

**Comment by sharwell** [comment]
@paul1956 this issue is assigned to the IDE team, but it depends on another team (compiler) committing to supporting the feature delivery. In general, we strive to keep issues marked as either "help wanted" or "needs design review" so it's clear what the next step to move forward would be. "Blocked" means it's not in one of those categories for reasons we don't directly control.

**Comment by paul1956** [comment]
I have ported the majority of C# tests listed above to VB without touching a single existing file except ScriptSemanticsTests.vb. where I added the 73 Tests (which could be added to another file), I added 4 files with new code, 1/2 of which belong elsewhere. Does that change the calculus? **If not should this be closed?**

I have not run the tests because they need to be converted from C# Syntax to VB and map the expected errors and I am not going down that path if there is no interest. This is just a Proof of Concept for the tests.

**Comment by jaredpar** [comment]
>  this issue is assigned to the IDE team, but it depends on another team (compiler) committing to supporting the feature delivery.

To be clear: this does not meet either the IDE or Compiler team's bar. 

Closing the issue to remove the confusion it's continuing to cause
