### ISSUE TITLE
Find proper name for shebang syntax node

### ISSUE THREAD

**Issue by brettfo** [dotnet/roslyn#5106]
As mentioned in PR #5019, shebang lines in C# script files were originally named `SyntaxKind.ShebangCommentTrivia` and then renamed to `SyntaxKind.ShebangTrivia`.  This issue is meant to be a continuation of that naming discussion.

**Comment by brettfo** [comment]
FYI for @DustinCampbell @jasonmalinowski @KevinH-MS @AnthonyDGreen who may be interested.

**Comment by DustinCampbell** [comment]
Thanks for filing this issue. Has it gone through the language design team yet?

Honestly, I'd say it's not really a comment and doesn't really serve the purpose of actually "commenting" code (like doc comments do). It seems like the decision was to make it a comment simply because there was a feeling that it should be colored green. The fact that it has structure and we perform analysis on it is a big strike against it as a "comment". :smile: Thanks for driving this one @CyrusNajmabadi.

**Comment by KevinH-MS** [comment]
I'm not strongly opposed to the name change, but just to reiterate, shebang does ***not*** have structure, and we should ***not*** perform semantic analysis on it.  The name includes "Comment", because it is parsed and handled by the same logic in the compiler as a single-line comment, except for the following details:

- start characters
- required position
- kind

In this way it is similar to the other types of comments in the language.

**Comment by DustinCampbell** [comment]
Didn't you mention in the PR that the compiler checked the path?

**Comment by KevinH-MS** [comment]
Nope, @jasonmalinowski said:

> You could even imagine the compiler would assert some reasonable-well-formedness rules to that (it must start with a leading /, for example.)

The compiler doesn't do that, and I would argue that it shouldn't, because there are no universally enforced rules for what appears after the ```#!``` (even amongst *nix command shells).  Further, we don't intend to limit this to *nix command shells (although that's the main scenario).  The text after the shebang is just a free-form "note" for the execution host.

**Comment by tmat** [comment]
+1 for what @KevinH-MS says.

**Comment by DustinCampbell** [comment]
@KevinH-MS -- thanks for clarification. I conflated a few responses.

Regardless, it still feels weird to me to make this a comment. If it's meaningful at all to the user, it shouldn't be a comment. Also, just because we don't do anything with it now, doesn't mean we shouldn't later.

All I've seen mentioned so far are differences, so I'm not sure how it is "similar to other types of comments" in the language. AFAICT, it is only way it is similar in that it is ignored by the compiler as comments are, which really isn't all that compelling. Are there similarities to comments I'm missing?

**Comment by KevinH-MS** [comment]
One other thing to consider is that all/most languages that support *nix shell scripting treat ```#``` as a single-line comment character in the language (think python, perl...even shell scripts themselves).  I guess part of my preference/bias is the prior art here.

Other than that, I think I'm out of arguments in support of "Comment".  At the end of the day, I'm happy as long as it has "Shebang" (or "Hashbang") and "Trivia" in the name. :smile:

**Comment by CyrusNajmabadi** [comment]
I agree that shebang doesn't have any strong guarantees on its structure.  However, it certainly has some weak ones that the IDE will likely take advantage of.  We'll likely want to classify it in a special manner, and will probably want to detect if it looks path-like and treat things appropriately.

That said, regardless of if it has structure or not, "ShebangTrivia" seems highly preferable to me over "ShebangCommentTrivia".  A 'comment' has some very commonly understood meaning among programing languages.  It's a mechanism for explaining code that shouldn't affect the final result.   That's not the case here for Shebang.  It's not used for explaining the code.  It's used literally as a directive to a shell to tell it what to execute.  

Anyways, I don't think there is much contention over ShebangTrivia.  So if brett's already made that change, I don't see much need to do anything more.  If brett hasn't, I can drive doing that.

**Comment by brettfo** [comment]
As of my PR #5019, it's `ShebangTrivia` in `master`.

**Comment by CyrusNajmabadi** [comment]
ShebangTrivia is appropriate.
