### ISSUE TITLE
Question: nullable result affected by later code 

### ISSUE THREAD

**Issue by karataliu** [dotnet/roslyn#51119]
### Analyzer source

**SDK**: [Built-in CA analyzers in .NET 5 SDK or later](https://docs.microsoft.com/dotnet/fundamentals/productivity/code-analysis)

**Version**: [SDK 5.0.100](https://dotnet.microsoft.com/download/dotnet/5.0)

### Describe the bug
null state prompted is decided by later null check. Is it by design?

### Steps To Reproduce
```
#nullable enable
    class K5
    {
        public static void Test()
        {
            {
                IDictionary<int, string> list = default!;

                foreach (var item in list)
                {
                    // Value is not null here
                    var _ = item.Value;
                }

                foreach (var item in list)
                {
                    // Value maybe null here
                    var _ = item.Value;
                    // Below line changed the behavior
                    if (item.Value == null) { }
                }
            }
        }
    }
```

![image](https://user-images.githubusercontent.com/10071498/107476194-52a6a080-6bb0-11eb-9ef8-280a9ed2f495.png)

![image](https://user-images.githubusercontent.com/10071498/107476162-46bade80-6bb0-11eb-8b2c-29ac9abe938f.png)

### Expected behavior
`if (item.Value == null) { }` won't change nullable check
### Actual behavior
`if (item.Value == null) { }` changed nullable check

**Comment by RikkiGibson** [comment]
What's happening is basically:

1. We see in the first analysis pass over the loop that item.Value is accessed, but its flow state is not-null, so it's no problem.
2. A null check is performed on item.Value. This tells the compiler that you're concerned that the thing might be null, thus we update the item.Value flow state to maybe-null after the `if`.
3. We visit the backwards branch to the start of the loop, and because variable states have changed, we do another analysis pass of the loop body.
4. This time, we see that item.Value is accessed, but its flow state is maybe-null. You get a warning.
