### ISSUE TITLE
Source Generator generated code not detected by Test Runner

### ISSUE THREAD

**Issue by kaladinstorm84** [dotnet/roslyn#51148]
**Version Used**: 
16.8.5
**Steps to Reproduce**:

1.  Copy Sample Hello World Source Generator,
2.  Add [TestFixture] to the class, and [Test] to method
3. Create Sample Project, and add the analyser
4. Build

**Expected Behavior**:
Tests to appear in Test Explorer
**Actual Behavior**:
Tests do not appear

**Comment by jaredpar** [comment]
@chsienki think this is a non-compiler bug but wanted you to take a look first. If it's not it's likely an issue in IDE / Test Explorer.

**Comment by shyamnamboodiripad** [comment]
@kaladinstorm84 could you please confirm that the sample project in question references the test adapter nuget package (NUnit3TestAdapter)? The adapter reference is required in order to discover tests.

**Comment by mrlacey** [comment]
I don't see this problem (using VS2022 - 17.1.0 Preview 2.0) 
I can see and run my generated tests in Test Explorer.
But, I'm using MSTest2.

See below: the generated test and it shown in solution explorer.
![image](https://user-images.githubusercontent.com/189547/148573999-0a6764eb-52a7-4662-8947-97061f9b6141.png)

What led me to this issue is that the Test Explorer can't see or navigate to the test because it reports "No source available"
Is this something I can influence with what I generate, or is this down to the test framework and adapter?

**Comment by CyrusNajmabadi** [comment]
Closing out as not repro, and no other reports of this.
