### ISSUE TITLE
Resolvable overload ambiguousness

### ISSUE THREAD

**Issue by makiuchi-d** [dotnet/roslyn#51232]
**Version Used**: 
master  branch (6e4fb9bcc59)

**Steps to Reproduce**:
1. Compile this code

```
using System;

public class Program
{
    static void F(Action<byte> a) { }
    static void F(Action<int> a) { }
    static void A(int n) { }

    public static void Main()
    {
        F(A);
    }
}
```

**Expected Behavior**:
Compile success.
The overloaded method invocation `F(A)` is resolved to `Program.F(Action<int>)`.

**Actual Behavior**:
```
Program.cs(11,9): error CS0121: The call is ambiguous between the following methods or properties: 'Program.F(Action<byte>)' and 'Program.F(Action<int>)'
```

**Reason**:
The method `void A(int)` cannot be converted to the delegate type `Action<byte>` because it does not have the delegate compatibility.
Therefore, the method `Program.F(Action<byte>)` should not be included in the overload resolution candidates.

**Cause**:
When looking for a conversion from the method `void A(int)` to the delegate type `Action<byte>`, the function applicability (each delegate parameter type has an implicit conversion to the method parameter type) was checked.
However, the delegate compatibility (each delegate parameter type has _an identity or an implicit reference conversion_ to the method parameter type) was not.

There is valid implicit conversion from `byte` to `int`, so that an (invalid) conversion from `void A(int)` to `Action<byte>` is found, and then the `F(Action<byte>)` becomes an overload resolution candidate.

**Solution**:
Add a delegate compatibility check to the function `Conversions.GetMethodGroupDelegateConversion`, which is looking for a conversion from the method group to the delegate.

**Comment by jaredpar** [comment]
> When looking for a conversion from the method void A(int) to the delegate type Action<byte>, the function applicability (each delegate parameter type has an implicit conversion to the method parameter type) was checked.
> However, the delegate compatibility (each delegate parameter type has an identity or an implicit reference conversion to the method parameter type) was not.

Can you specify what section of the spec, and which version of the spec you're using, that you think isn't being respected here?

**Comment by makiuchi-d** [comment]
The [overload resolution](https://github.com/dotnet/csharplang/blob/660f5a2e1c5c6e3b181a82d0b2bdb17821ef9b84/spec/expressions.md#overload-resolution) in the spec says:

> Given the set of applicable candidate function members, the best function member in that set is located.

It means that the best function member must be selected from the applicable function members.

The applicable function is described on the next section ([Applicable function member](https://github.com/dotnet/csharplang/blob/660f5a2e1c5c6e3b181a82d0b2bdb17821ef9b84/spec/expressions.md#applicable-function-member)).

> for a value parameter or a parameter array, an implicit conversion (Implicit conversions) exists from the argument to the type of the corresponding parameter

There is no implicit conversion from the argument `void A(int)` to the parameter type `Action<byte>` because there is no identity or implicit reference conversion from `byte` to `int`.

The method to delegate conversion is described on [here](https://github.com/dotnet/csharplang/blob/660f5a2e1c5c6e3b181a82d0b2bdb17821ef9b84/spec/conversions.md#method-group-conversions):
> An implicit conversion (Implicit conversions) exists from a method group (Expression classifications) to a compatible delegate type. 

The delegate compatibility is described on [here](https://github.com/dotnet/csharplang/blob/660f5a2e1c5c6e3b181a82d0b2bdb17821ef9b84/spec/delegates.md#delegate-compatibility):
> An identity or implicit reference conversion exists from the return type of M to the return type of D.

Therefore, the function `F(Action<byte>)` should not be a applicable function member.

In the current implementation of the method [`Conversions.GetMethodGroupDelegateConversion`](https://github.com/dotnet/roslyn/blob/6e4fb9bcc59b43f3192523e0483db31fb5546350/src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/Conversions.cs#L43),
the overload of the method `A` is resolved by the method `ResolveDelegateOrFunctionPointerMethodGroup` with the argument as `byte`.
The method `A(int)` is the applicable and the best function member because there is an implicit conversion from `byte` to `int` ([Implicit numeric conversions](https://github.com/dotnet/csharplang/blob/660f5a2e1c5c6e3b181a82d0b2bdb17821ef9b84/spec/conversions.md#implicit-numeric-conversions)).
Then the method `Conversions.GetMethodGroupDelegateConversion` returns a conversion from the method `A(int)` to the delegate `Action<byte>`, even though it has no delegate compatibility.

**Comment by AlekseyTs** [comment]
The behavior looks expected to me. Here is a quote from https://github.com/dotnet/csharplang/blob/master/spec/conversions.md#method-group-conversions.
`Begin quote`

An implicit conversion ([Implicit conversions](conversions.md#implicit-conversions)) exists from a method group ([Expression classifications](expressions.md#expression-classifications)) to a compatible delegate type. Given a delegate type `D` and an expression `E` that is classified as a method group, an implicit conversion exists from `E` to `D` if `E` contains at least one method that is applicable in its normal form ([Applicable function member](expressions.md#applicable-function-member)) to an argument list constructed by use of the parameter types and modifiers of `D`, as described in the following.

The compile-time application of a conversion from a method group `E` to a delegate type `D` is described in the following. Note that the existence of an implicit conversion from `E` to `D` does not guarantee that the compile-time application of the conversion will succeed without error.

*  A single method `M` is selected corresponding to a method invocation ([Method invocations](expressions.md#method-invocations)) of the form `E(A)`, with the following modifications:
    * The argument list `A` is a list of expressions, each classified as a variable and with the type and modifier (`ref` or `out`) of the corresponding parameter in the *formal_parameter_list* of `D`.
    * The candidate methods considered are only those methods that are applicable in their normal form ([Applicable function member](expressions.md#applicable-function-member)), not those applicable only in their expanded form.
*  If the algorithm of [Method invocations](expressions.md#method-invocations) produces an error, then a compile-time error occurs. Otherwise the algorithm produces a single best method `M` having the same number of parameters as `D` and the conversion is considered to exist.

`End quote`

There is an implicit conversion from ```byte``` to ```int```, therefore there is a conversion from method group ```A``` to ```Action<byte>```.  Note this in the last bullet point: "**and the conversion is considered to exist.**"    

Yes, the next bullet point in the specification says
`Begin quote`

*  The selected method `M` must be compatible ([Delegate compatibility](delegates.md#delegate-compatibility)) with the delegate type `D`, or otherwise, a compile-time error occurs.

`End quote`

However, this has nothing to do with determination whether conversion exists. Existing conversions could still be erroneous. This could be counterintuitive, but that is how the language is specified.

**Comment by makiuchi-d** [comment]
Thank you, AlekseyTs.

I have been closed the PR.

However, `A(int)` cannot convert to the delegate `Action<byte>`.
Theoretically, `F(Action<byte>)` can be removed from the candidate set at the compile time.

I'll try again.

**Comment by 333fred** [comment]
Unless I'm misreading this issue, this is actually https://github.com/dotnet/csharplang/issues/3277, which is championed and approved as an any time feature.
