### ISSUE TITLE
Fix all without preview dialog 

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#51310]
Direct customer feedback copying here: 

> 64bit version, being able to apply suggested fixes from analyzers without a preview dialog and without having to wait > 30 minutes to apply to a whole solution just to see VS crash with OOM or failing to apply silently. 
> It takes the same amount, or even more, of time as the fixes would take. So every time you try to bulk fix something you need twice the time. The dialog might also be the reason why it takes so long, and why VS crashes with OOM, in the first place as you can deselect single items.

**Comment by CyrusNajmabadi** [comment]
> So every time you try to bulk fix something you need twice the time.

This is not the case.  The expense is in computation.  Once we've computed the result, we can display it (or apply it).  

We OOM because the results are large, and VS is only 32bit.  Our options are:
1. to move fixing out of proc
2. or somehow get more memory in VS.  
3. allow the fix to apply to teh solution one part at a time so that we don't need to store it all in memory.

**Comment by CyrusNajmabadi** [comment]
Note: i made several PRs to help mitigate some of the OOMs we were seeing.  Specifically, we do not try to process the entire solution in parallel (which has a higher chance of OOMing).  Instead, we process each project at a time (though we do keep track of the changes in memory until we're ready to apply them to the workspace).

**Comment by CyrusNajmabadi** [comment]
Closing out as this shouldn't be an issue anymore.
