### ISSUE TITLE
assigning readonly fields from ModuleInitializer is not allowed by compiler.

### ISSUE THREAD

**Issue by tmds** [dotnet/roslyn#51388]
```cs
    static class Repro
    {
        static readonly int s_readonlyField;

        [ModuleInitializer]
        static internal void Initialize()
        {
            s_readonlyField = 10;
        }
    }
```

generates:
```
error CS0198: A static readonly field cannot be assigned to (except in a static constructor or a variable initializer)
```

**Comment by Youssef1313** [comment]
This could be by design. There is nothing that prevents calling `Initialize` method in other methods that shouldn't be allowed to modify readonly fields. e.g:

```csharp
using System.Runtime.CompilerServices;

class C
{
    [ModuleInitializer]
    static internal void Initialize()
    {
    }

    public void M()
    {
        Initialize(); // This is allowed.
    }
}
```

**Comment by tmds** [comment]
> Initialize(); // This is allowed.

I know this is permitted.

Module initializers are a good place to initialize readonly fields. Maybe `CS0198` can be relaxed a bit for this use-case.

**Comment by RikkiGibson** [comment]
This scenario could perhaps be solved by introducing an `init` modifier to methods and allowing such methods to be module initializers. (most relevant issue I can find for this is dotnet/csharplang#4454)

**Comment by jaredpar** [comment]
Thanks for taking the time to file this issue but as @Youssef1313  and @RikkiGibson noted the behavior is "By Design". The method here is just another method and can be invoked at any point in the program hence it can't be used to set `init` properties. The path forward for this to work is `init` methods which is dotnet/csharplang#4454 (as @RikkiGibson noted).
