### ISSUE TITLE
CodeAction suggestions overload

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#5139]
This is an actual screenshot of a code actions suggestion pane:

![image](https://cloud.githubusercontent.com/assets/4564579/9801868/ce8af412-57ca-11e5-8472-4f8a84024984.png)

There is a lot wrong here that we should improve:

1. I really don't like the merging of all the offerings from the same line in this code action.  I'd highly prefer the following approach:
  1. If the cursor intersects some issues, then show the fixes for those issues.  Right now it's seriously noisy when i want to fix a single issue and i get all this gunk about every other problem on that line.
  2. If the cursor does not intersect any issues then fall back to something (maybe showing the closest issues on either side, or maybe showing all.
2. Text it cutoff, making it impossible to distinguish variants.  We either need to simplify what we say to the user so that things fit.  Or we need to make the dropdown wider.  I'd prefer the former.
3. Spell checking suggestions are pretty universally bad.  Pretty much non of them should be offered here as the change is far too massive to indicate a misspelling.  

This really needs to be fixed as the experience is currently super poor in these situations.

**Comment by dpoeschl** [comment]
I think this is actually Area-IDE now...

**Comment by dpoeschl** [comment]
@CyrusNajmabadi See also #3312

**Comment by dpoeschl** [comment]
And @jmarolf may know of even more similar bugs...

**Comment by paul1956** [comment]
On top of the previous comments I want to know who is offering it. I many cases there are multiple providers offering almost identical fixes and I want to know who it is, especially when the fix is wrong or crashes.

**Comment by jmarolf** [comment]
@paulllll

I'd say https://github.com/dotnet/roslyn/issues/3312 
1.

**Comment by jmarolf** [comment]
@paul1956 we already have https://github.com/dotnet/roslyn/issues/5004 tracking the problem of determining where a codefix is coming from.

I'd call this a dupe of  #3312, but I think the presented solutions here are important to think through.

1. @shyamnamboodiripad worked with the editor team on what should be shown for overlapping codefixes on a line.  Shyam, do you remember why this behavior was selected? 
2. For some codefixes, we can simplify what the message is

**Comment by jmarolf** [comment]
@paul1956  that issue is already being tracked by https://github.com/dotnet/roslyn/issues/5004

@CyrusNajmabadi I think #3312 covers this issue but I think its important to think through how we should solve it.

1. @shyamnamboodiripad did a lot of work to determine which codefixes we show when they overlap on a line, Shyam do you remember why we chose this behavior?  I think the suggested behavior would be an improvement.

2. We could not fully qualify the names for most fixes, which would alleviate some of the problems.  We should also collapse all the the generate-type suggestions into one with flavored actions.  We could also add "Change 'x' to 'FullyQualified.x'" as a flavored action under Add Import since those two are logically grouped together.  

3. Can we file a bug that spelling suggestions shouldn't be given unless they meet some match threshold?

**Comment by CyrusNajmabadi** [comment]
I could have sworn when I implemented "fully qualify" back in ye old VS days, it just listed "FullyQualified.x" instead of "Change x to ...".  I wonder why it was changed.

As to which bug to keep.  Mine seems to have more suggestions. So keep mine :)

**Comment by Pilchie** [comment]
I'm not sure that we'll be able to address all of this in 1.1, but we should start thinking about it.

**Comment by shyamnamboodiripad** [comment]
CC @srivatsn 

Regarding 1, I agree we really need to reduce the number of issues offered in the list by default. Including all issues on the current line is indeed problematic and the problem will only get worse as more and more fixes and refactorings come into play.

We had discussed this with the VS IDE folks (who own the VS lightbulb APIs + the decision to ask the language IDEs for all fixes / refactorings on the current line line) on numerous occasions. The reason they wanted to include fixes for all issues on a given line was because the light bulb shows up in the margin as soon as user moves into a given line - for a user who clicks on this light bulb with the mouse, it would be weird if the set of fixes changed according to position of the text caret and they didn't want 'ctrl +.' and 'mouse click on light bulb' to display a different set of fixes in the same light bulb menu. But I agree we should rethink this design. I like the proposal to have some sort of window around the caret and only display fixes for issues that fall within this window (at least for the ctrl + . case where user is not using the mouse).

Regarding 2, The truncation of menu text is also something that the VS light bulb IDE does. If we want to increase the cutoff we would need to ask the VS light bulb folks to increase it. I agree with @CyrusNajmabadi however that the better approach would be to audit all the fixes and refactorings that we ship and make sure their names will always fit. This won't solve the problem in general though (i.e. all fix providers need to do this including third party ones...).

Regarding 3, I am not sure the VB spell checking fixes add much value. Do we know if these are popular? If not, we should just stop offering them. Or we should only offer them when the new spelling is very very close to the old one (i.e. an obvious mistyping).

I also like @jmarolf's suggestion to use flavored actions for the generate type and add imports fixes. We had discussed this but they didn't fit for v1.

@Pilchie @jmarolf I would like to propose that we should log separate issues for the above and see which of them could fit for 1.1 :)

**Comment by shyamnamboodiripad** [comment]
@paul1956 could you please log a separate issue (feature request) for your comment above. I agree this would be very useful. Iirc, we had discussed including provider info (perhaps at the top of the preview pane for the fix / when hovering over a fix in the menu with the mouse) but made a call to postpone this post v1.

This may potentially involve some work in the VS IDE's light bulb UI (depending on how we decide to implement this)..

**Comment by shyamnamboodiripad** [comment]
Ah sorry please ignore my comment above @paul1956. I missed the fact that @jmarolf had already addressed this in his response above...

**Comment by sharwell** [comment]
IntelliJ does something similar to item 1 in the proposal. I find it frequently frustrating because sometimes I can fix an issue by placing the caret anywhere on the line, and sometimes I cannot. This is compounded by the fact that while the light bulb UI is displayed, the <kbd>&larr;</kbd> and <kbd>&rarr;</kbd> keys don't actually allow you to move to a different location on the line.

The experience of this would be even worse if a Hidden diagnostic overlaps with the caret and a Warning or Error diagnostic appears elsewhere on the same line. In this case, filtering on the caret location would result in a refactoring provider preventing the user from accessing a code fix for a more important issue. It would be equally frustrating if the filtering were reversed, and a warning anywhere on the line disabled all refactoring operations, especially considering that a refactoring operation might [actually be providing the code fix for the warning](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/301).

**Comment by CyrusNajmabadi** [comment]
Another example: 

![image](https://cloud.githubusercontent.com/assets/4564579/9833149/3d8af588-5942-11e5-9758-04aa6bc17173.png)

**Comment by AdamSpeight2008** [comment]
What making them submenus? With the top menus being the provider / analyser name.

**Comment by Pilchie** [comment]
Note that one thing in favor of sub menus is that they can have different previews, where flavored actions share a single preview. So far we have used flavored actions to represent the scope of the change, but not conceptual differences in what the change is.

**Comment by Pilchie** [comment]
This is somewhat improved, but I think there is more to do in Update 2.  In particular, I'd like to collapse Generate property, field, readonly field, and local a bit as well.

**Comment by Pilchie** [comment]
Assigning back to @CyrusNajmabadi.  I think we decided that we wanted to consider bucketing more of the generate options, instead of just the generate type ones as another potential thing here.

**Comment by Pilchie** [comment]
Re-activating, because I reverted the change for a test failure.

**Comment by CyrusNajmabadi** [comment]
Fixed with b3ef5d6f25573328d1218918075fa6d02027760d
