### ISSUE TITLE
Roslyn is passing .Designer.cs with "autogenerated" header to analyzer

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#51574]
**Version Used**: VS 16.8.6

When I F5-debug an analyzer, it reports diagnostics in a `Resources.Designer.cs` file. The beginning lines of the file:

```cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
```

Why is Roslyn analyzing this file?

**Comment by AraHaan** [comment]
Happens with autogenerated TFM specific files with the following names ``*.AssemblyAttributes.cs``, ``*.AssemblyInfo.cs``, etc.

Also why is there 2 different comment styles for autogenerated code instead of a single style?
- ``// <autogenerated />`` or ``// <autogenerated/>``
- ``// <auto-generated></auto-generated>``

I feel like the with ``// <auto-generated></auto-generated>`` should get nuked entirely everywhere they are used (even if they are used in winforms designer files) for the newer much shorter version.

**Comment by CyrusNajmabadi** [comment]
Which analyzer?  Analyzers can choose their behavior here.  For example, a security analyzer would still want to analyze generated files in case tehy had security issues in them.

**Comment by CyrusNajmabadi** [comment]
> Also why is there 2 different comment styles for autogenerated code instead of a single style?

Roslyn is not involved in that.  You'd have to take it up with whoever is generating the file.

**Comment by sharwell** [comment]
Analyzers will get callbacks for generated code unless they explicitly opt-out by calling `ConfigureGeneratedCodeAnalysis`:

```csharp
context.ConfigureGeneratedCodeAnalysis(GeneratedCodeAnalysisFlags.None);
```

**Comment by AraHaan** [comment]
The analyzers in particular are the ones built into the .NET SDK (specifically it happens when using the .NET 6 Preview 1 SDK that can be installed on the aka.ms/dotnet-download link for me).

But also happens to jnm2 as well.

**Comment by jnm2** [comment]
Thanks @CyrusNajmabadi and @sharwell, that answers my question.

@AraHaan I guess a different issue is needed to figure out whether CA8019 is supposed to be analyzing generated code.

**Comment by AraHaan** [comment]
Sorry I did not realize it was CS8019 not CA8019 as CA8019 does not exist.
