### ISSUE TITLE
Should the Inheritance be respected for the types injected with "WithGlobalsType"?

### ISSUE THREAD

**Issue by gsferreira** [dotnet/roslyn#5164]
Hi!

I was trying the Interactive Scripting Api and I realized that in the following code, if the Globals class inherits from a *"ParentGlobals"*, the variables defined at *"ParentGlobals"* won't be considered.

           var script = CSharpScript.Create("X + Y").WithGlobalsType(typeof(Globals));
            var result = script.Run(new Globals { X = 1, Y = 2 });

This is happening because in the *"Microsoft.CodeAnalysis.Scripting.ScriptVariables"* class the *AddVariables* method has the *DeclaredOnly* binding flag.

Before submit a pull request I want to know if hierarchy should be considered?

Thanks in advance

**Comment by ManishJayaswal** [comment]
@gsferreira this is a bug. Hierarchy should be considered. Please submit a PR.

**Comment by tmat** [comment]
@gsferreira  It's kind of odd that "X" and "Y" are exposed as script variables. They are not script variables, they are properties on host object (globals). Script variable is a variable defined by the script itself. If we assume this definition the bug would be that "X" and "Y" are included. 

I'd prefer such change since the host has direct (compile-time) access to X and Y, so there is no need to access them dynamically thru reflection.

**Comment by gsferreira** [comment]
I'm closing this bug because I ran the tests against the latest master branch version and the hierarchy is already being respected. I was using an outdated fork. My bad, sorry.
