### ISSUE TITLE
Defining operators via Extension Methods

### ISSUE THREAD

**Issue by rftobler** [dotnet/roslyn#5165]
It is easy to define multi-dimensional vectors in a generic way, with all the necessary generic operations. In order to specialize such generics for arithmetic operations, it would be great if operators where allowed to be defined via extension methods.

This would allow to replace such things 

``` C#
public static class VectorOfDoubleExtensions
{
    public static Vector<double> Plus(this Vector<double> a, Vector<double> b)
    { ... }
}

Vector<double> a, b;
var c = a.Plus(b);
```

with operators:

``` C#
public static class VectorOfDoubleExtensions
{
    public static Vector<double> operator+(this Vector<double> a, Vector<double> b)
    { ... }
}

Vector<double> a, b;
var c = a + b;
```

**Comment by RichiCoder1** [comment]
I think this may have been mentioned before, but I can't find an issue. Either way, :+1:

**Comment by dsaf** [comment]
Same idea, different sample #4945.

**Comment by aluanhaddad** [comment]
I like this idea a lot. It would be useful for wring DSLs and for many other things. Can you add an example of using defining a generic extension operator to the proposal?
e.g:
```C#
// Silly example concatenates two sequences.
public static IEnumerable<T> operator+ <T>(this IEnumerable<T> xs, IEnumerable<T> ys) => xs.Concat(ys);
```

**Comment by gafter** [comment]
See also #3357

**Comment by grwGeo** [comment]
@aluanhaddad Trying to model some mathematical entities in the past I have come across the need to have generic operators. Although this is different to extending operators which belongs to 'Type Extensibility' (see e.g. [https://github.com/dotnet/roslyn/issues/3357]), I have needed something like:
`public class MyGenericClass<T>
{
     public static MyGenericClass<U> operator +<T, S>(MyGenericClass<T> first, MyGenericClass<S> second) 
    {
        return 'a MyGenericClass<U> where U depends on T and S';
    }
}`

**Comment by grwGeo** [comment]
@aluanhaddad Trying to model some mathematical entities in the past I have come across the need to have generic operators. Although this is different to extending operators which belongs to 'Type Extensibility' (see e.g. [#3357]), I have needed something like:
```C#    
public class MyGenericClass<T>
{
      public static MyGenericClass<U> operator +<T, S>(MyGenericClass<T> first, 
            MyGenericClass<S> second) 
      {
           //return 'a MyGenericClass<U> where U depends on T and S';
      }
}
```
Also type inference in this scenario is crucial.

**Comment by aluanhaddad** [comment]
@grwGeo I definitely think that kind of increased expressiveness would be valuable. Although, as you note, you're use case is not directly related to type extensibility, extending one of the types with a generic extension operator would indeed be an intuitive and practical way to accomplish it.

**Comment by gafter** [comment]
We are now taking language feature discussion in other repositories:
- https://github.com/dotnet/csharplang for C# specific issues
- https://github.com/dotnet/vblang for VB-specific features
- https://github.com/dotnet/csharplang for features that affect both languages

Features that are under active design or development, or which are "championed" by someone on the language design team, have already been moved either as issues or as checked-in design documents. For example, the proposal in this repo "Proposal: Partial interface implementation a.k.a. Traits" (issue 16139 and a few other issues that request the same thing) are now tracked by the language team at issue 52 in https://github.com/dotnet/csharplang/issues, and there is a draft spec at https://github.com/dotnet/csharplang/blob/master/proposals/default-interface-methods.md and further discussion at issue 288 in https://github.com/dotnet/csharplang/issues. Prototyping of the compiler portion of language features is still tracked here; see, for example, https://github.com/dotnet/roslyn/tree/features/DefaultInterfaceImplementation and issue 17952.

In order to facilitate that transition, we have started closing language design discussions from [the roslyn repo](https://github.com/dotnet/roslyn) with a note briefly explaining why. When we are aware of an existing discussion for the feature already in the new repo, we are adding a link to that. But we're not adding new issues to the new repos for existing discussions in this repo that the language design team does not currently envision taking on. Our intent is to eventually close the language design issues in the Roslyn repo and encourage discussion in one of the new repos instead.

Our intent is not to shut down discussion on language design - you can still continue discussion on the closed issues if you want - but rather we would like to encourage people to move discussion to where we are more likely to be paying attention (the new repo), or to abandon discussions that are no longer of interest to you.

If you happen to notice that one of the closed issues has a relevant issue in the new repo, and we have not added a link to the new issue, we would appreciate you providing a link from the old to the new discussion. That way people who are still interested in the discussion can start paying attention to the new issue.

Also, we'd welcome any ideas you might have on how we could better manage the transition. Comments and discussion about closing and/or moving issues should be directed to https://github.com/dotnet/roslyn/issues/18002. Comments and discussion about this issue can take place here or on an issue in the relevant repo.

-----------------

This may be close enough to https://github.com/dotnet/csharplang/issues/192, or perhaps even https://github.com/dotnet/csharplang/issues/110 and https://github.com/dotnet/csharplang/issues/164, that discussion can continue there.
