### ISSUE TITLE
Tuple deconstruction with TupleElementNames

### ISSUE THREAD

**Issue by ulln** [dotnet/roslyn#51687]
**Version Used**:

Compiler version: 3.9.0-6.21124.20 (db94f4cc)
Language version: 9.0

**Steps to Reproduce**:

```csharp
using System;

class Program
{
    static void Main()
    {
        var date1 = GetDate(); // type not apparent
        (int Year, int Cats, int Dogs) date2 = GetDate(); // error-prone
        (int, int, int) date3 = GetDate(); // preferred syntax

        Console.WriteLine(date1.Year);
        Console.WriteLine(date2.Year);
        Console.WriteLine(date3.Year);
    }

    static (int Day, int Month, int Year) GetDate()
    {
        return (20, 2, 2020);
    }
}
```

**Expected Behavior**:

Should compile without error.
The compiler should infer the tuple element names for date3 (like it does for date1)

**Actual Behavior**:

error CS1061: '(int, int, int)' does not contain a definition for 'Year'

**Comment by Youssef1313** [comment]
This appears to be by design to me. When you explicitly say `(int, int, int)`, the tuple is given `Item1`, `Item2`, `Item3`. etc

But I was expecting a warning CS8123 here.

> The tuple element name '{0}' is ignored because a different name or no name is specified by the target type '{1}'.

```csharp
class Program
{
    static void Main()
    {
        // This has warning as expected.
        (int, int, int) date1 = (Day: 20, Month: 2, Year: 2020);
        
        // No Warning
        (int, int, int) date2 = GetDate();
    }

    static (int Day, int Month, int Year) GetDate()
    {
        return (20, 2, 2020);
    }
}
```

@jaredpar Is this a warning wave candidate? or the warning isn't produced by-design?

**Comment by jaredpar** [comment]
The behavior described in the bug is "By Design". As @Youssef1313 noted in the third case you're explicitly giving the type of the tuple and it does not include names. 

> or the warning isn't produced by-design?

This behavior is also "By Design". The CS8123 warning is only emitted when the name of a tuple literal is ignored. The reason for this is that if you do it the other way, warn whenever a tuple name is ignored, then it means adding tuple names is a back compat breaking change. That makes them significantly less useful 😦

**Comment by ulln** [comment]
@jaredpar

I have intentionally not given names, because why should i?
I expected the compiler to figure this out.

I was afraid that this is by design.
Could you please elaborate on WHY the names are not inferred here?

If the answer is "because nobody implemented it" could this be turned into a feature request?

**Comment by jaredpar** [comment]
> Could you please elaborate on WHY the names are not inferred here?

In that case there is no type inference going on because you explicitly specified the tuple type as `(int, int, int)`. Names are a part of the type of the tuple, it's not an effect on top of them. It has a demonstrable impact on features like name lookup. Hence when you state the type as `(int, int, int)` it's an explicit statement that the tuple has no explicit names. Inference of names only occurs, when you use `var`, where the entire tuple type including the names is inferred. 

> If the answer is "because nobody implemented it" could this be turned into a feature request?

This is an explicit decision.

**Comment by svick** [comment]
@ulln I don't quite understand why you want it to work this way. Consider code like `(int, string) t = F();`. With your expected behavior, you can't tell what are the properties of `t`. If you see `t.Id`, you still don't know its type. So what would be the point in specifying the type like this?

You can either embrace not knowing and use `var`, or you can be explicit and specify the full type including names. But to me, it seems you're combining the worst of both words: It's more verbose than `var`, but doesn't actually tell you anything useful.
