### ISSUE TITLE
"notnull" generic constraint doesn't work with "class" or "struct" generic constraints

### ISSUE THREAD

**Issue by anreton** [dotnet/roslyn#51740]
**Version Used**: 
Microsoft Visual Studio Community 2019 Version 16.9.0
.NET 5.0

**Steps to Reproduce**:

1. Create generic class with **class** and **notnull** constraint.
```csharp
public class Foo<T> where T : class, notnull
{
}
```
2. Get an error.
> CS0449 The 'class', 'struct', 'unmanaged', 'notnull', and 'default' constraints cannot be combined or duplicated, and must be specified first in the constraints list.

**Expected Behavior**:
**notnull** generic constraint works with **class** generic constraint - to constrain a generic type to nonnullable reference types or to nonnullable value types (**notnull** + **struct** generic constraints).

**Actual Behavior**:
**notnull** generic constraint doesn't work with **class** generic constraint (or with **struct** generic constraint)

**Comment by jaredpar** [comment]
This behavior is "By Design". The reason is that the constraints `class` and `struct` by themselves are sufficient to specify that the type argument cannot be a nullable type. 

```c#
void M<T>() where T : class { }
M<string?>(); // warning
```

The point of the `notnull` constraint is to provide the developer a way to specify that the type argument, be it a `class` or `struct`, cannot be a nullable form. Combining it with either `class` or `struct` renders it excessive and hence the language does not allow it.
