### ISSUE TITLE
Question: How to I modify a VB ForStatementSyntax

### ISSUE THREAD

**Issue by paul1956** [dotnet/roslyn#5190]
I am trying to add the missing Type information, I am having trouble replacing the Control Variable with anything. I can't find a SyntaxFactory.ControlVariable. And it I try to use VariableDeclarator to replace the ControlVariable Node, I can't convert the original ControlVariable to a SeparatedSyntaxList(Of ModifiedIdentifierSyntax)., and I don't know if that will actually work.

If this is not the appropriate place to ask How To questions, where should this type of question be asked. I have scanned the Source but I can't find examples for anything like this.

**Comment by AnthonyDGreen** [comment]
@paul1956,

Sorry, I hadn't noticed this before. When you write this:

```VB.NET
For i = 1 To 10
Next
```

The way that's represented is that the 'i' is a reference to an implicitly declared local variable. It's not a declaration itself. Syntactically it has to be that way because if 'i' were a local variable, parameter, field (or anything really) in scope 'i' would bind to it, not create a new variable. For that reason, when there isn't an 'As' clause syntactically it's just an IdentifierNameSyntax. By convention IdentifierNames always represent a reference to a symbol, never a declaration.

Now, when one writes:

```VB.NET
For i As Integer = 1 To 10
Next
```

The 'i As Integer' part is unambiguously a declaration and is represented by a VariableDeclarator node. This is the same node used in local variable and field declarations. It contains a list of modified identifiers because such statements could take the form of:

```VB.NET
Dim x, y, z As Integer
```

And even more convoluted:

```VB.NET
Dim x?, y(), z As Integer ' Declares three variables of type Integer?, Integer(), and Integer
```
 
The ? and () modifiers on the base identifier token is why we have the ModifiedIdentifierSyntax node. ModifiedIdentifiers are always declarations and have no relation to the IdentifierNameSyntax. The only thing they share is an identifier token.

So to correctly convert from one to the other you'd write something like:

```VB.NET
Imports Microsoft.CodeAnalysis.VisualBasic.SyntaxFactory

Dim oldControlVariable As IdentifierNameSyntax = forStatement.ControlVariable
Dim newControlVariable =
        VariableDeclarator(
            SingletonSeparatedList(ModifiedIdentifier(oldControlVariable.Identifier)),
            SimpleAsClause(PredefinedType(Token(SyntaxKind.IntegerKeyword))),
            initializer:=Nothing
        )

forStatement = forStatement.WithControlVariable(newControlVariable)
```

That takes the original identifier content and inserts it in a new declaration.

I doubt you've been blocked on this for two months but hopefully that provides some background to you and/or whomever might stumble on this thread later.

Regards,

**-ADG**
