### ISSUE TITLE
Multi-line expression break non-verbatim interpolated strings

### ISSUE THREAD

**Issue by m0sa** [dotnet/roslyn#5211]
```
var foo = new { bar = "bar" }

// fails with CS1039 unterminated string literal
Console.WriteLine($"...{foo.
bar}...");
Console.WriteLine($"...{@"
"}..."

// works, but requires me to change all the surrounding escaping
Console.WriteLine($@"...{foo.
bar}...");
```

**Comment by kevin-montrose** [comment]
Glancing at the source, looks intentional.

[Some code](https://github.com/dotnet/roslyn/blob/98b075752c74e4a908b674b199d94f66f5273913/src/Compilers/CSharp/Portable/Parser/LanguageParser_InterpolatedString.cs#L33)

The punchline:  
> We don't want to make the scanner stateful (between tokens) if we can possibly avoid it.
The approach implemented here is

> (1) Scan the whole interpolated string literal as a single token. Now the statefulness of
the scanner (to match { }'s) is limited to its behavior while scanning a single token.

> (2) When the parser gets such a token, here, it spins up another scanner / parser on each of
the holes and builds a tree for the whole thing (resulting in an InterpolatedStringExpressionSyntax).

> (3) The parser discards the original token and replaces it with this tree. (In other words,
it replaces one token with a different set of tokens that have already been parsed)

> (4) On an incremental change, we widen the invalidated region to include any enclosing interpolated
string nonterminal so that we never reuse tokens inside a changed interpolated string.

> This has the secondary advantage that it can reasonably be specified.

> The substitution will end up being invisible to external APIs and clients such as the IDE, as
they have no way to ask for the stream of tokens before parsing.

**Comment by m0sa** [comment]
This actually prevents other types of trivia (like comments, preprocessor directives etc) on the interpolation expression as well.

**Comment by gafter** [comment]
A non-verbatim interpolated string may not have a newline anywhere inside it. That is intentional.
