### ISSUE TITLE
Please expose Compilation.GetBestTypeByMetadataName as a public API

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#52118]
The existing API, Compilation.GetTypeByMetadataName, ceases to work in unpredictable situations where one of the compilation's references internally declares a type with the same name which is never visible to the compilation. This is a pitfall that hurts code generation. For example, if my code fix provider wants to pass ObsoleteAttribute to SyntaxGenerator, I might grab the symbol using GetTypeByMetadataName. This will mysteriously begin failing if a user begins targeting `net5.0-windows` where `System.DirectoryServices` gets automatically referenced, declaring its own internal ObsoleteAttribute. (Repro shown at https://github.com/dotnet/roslyn/issues/52037).

Roslyn itself is banning the use of Compilation.GetTypeByMetadataName in all its own analyzers: https://github.com/dotnet/roslyn/issues/43341

Additionally, please add an obsoletion warning or RSxxxx warning on uses of Compilation.GetTypeByMetadataName redirecting people to GetBestTypeByMetadataName. I can open a separate issue for this part if that is more helpful.

**Comment by jnm2** [comment]
Also, 'best' is short, but 'Accessible' might be more self-explanatory. You're getting the single type that is accessible anywhere within the compilation, if there is exactly one.

**Comment by AlekseyTs** [comment]
I don't think we would want to change behavior of `GetTypeByMetadataName` API or mark it as obsolete. It does what it is supposed to do. It is quite possible that it is not the right API to use for some scenarios, that, however, doesn't make it a "bad" API. I would also recommend reevaluating whether it is appropriate to use any kind of lookup mechanism when a lookup comes to mind as the first thing to do. Often matching by fully qualified name rather than comparing to a symbol is the more appropriate thing to do.

Finally, there could be numerous ways one could want to resolve ambiguity during lookup, those could easily be implemented in the form of an extension method, given that the building blocks are there (there is a `GetTypeByMetadataName` API on assembly symbol). One can easily control in what order to perform the lookup, what  custom filtering to apply and how to deal with ambiguities (there is pretty much always a chance to have them). If there is a consensus that certain rules are going to be common. I would support adding such an API as an extension method to the common layer.

**Comment by jnm2** [comment]
@AlekseyTs I don't think the point is that it's a bad API. The focus is on dividing cases where people would be drawn to using it into cases where it's the right thing to use versus cases where it's a pitfall. What are the percentages? It's possible that it's worth putting friction in the path of the 0.01% (if that's what it is) rather than the path of the many (especially since this will be community).

**Comment by AlekseyTs** [comment]
> The focus is on dividing cases where people would be drawn to using it into cases where it's the right thing to use versus cases where it's a pitfall.

I am on the position that the decision about whether to use an API should be an explicit choice. First, one should clearly define what behavior is required. Then available APIs should be checked against requirements. If the first step is skipped, it is extremely unlikely to avoid a pitfall. A dev should know the tools that he/she is using.

**Comment by CyrusNajmabadi** [comment]
> A dev should know the tools that he/she is using.

I think the mismatch lies with us not being prescriptive enough.  The IDE team itself doesn't know what APIs to use in a situation like this.  In the past we were guided to use apis like GTBMN.  However, we learned later that those don't necessarily even work.  This caused us, and the analyzers team to both then switch to a new API to address this mismatch.  Later than that we even learned that this approach doesn't even work in teh first place (because it's not even how the compiler works under the covers).  HOwever, to most of us, the compiler is a black box, so we can only try to infer what we should be doing by what APIs are actually exposed.  

A core problem here, as i see it, is that we're not doing a good enough job working through real cases where we (or others) would want analyzers, and actually checking if each part is *correctly*, and *without pitfalls* using our APIs.  If we discover they aren't, tehn the onus is on *us* (not users) to identify those sections and then provide the suitable answers. 

> A dev should know the tools that he/she is using.

Devs will never reach that point.  We have decades of experience on our own team, and we've seen first hand how even we are misled and confused in scenarios like this.  External devs are at a much more significant disadvantage, *especially* as they need to trust our examples, and will assume that what we put forth is an indication of the right way to do things.  They're not going to second guess or pore over every inch of the compiler and language specs to find out where the deficiencies lay.  Nor are they likely able to come up with an alternate 'extension method' that truly encapsulate the accurate logic that the compiler has.  This is evidenced by the fact that the IDE team has tried this on numerous occasions and has continually either failed to get it right initially, or has seen drift over time as the compiler has changed, but the external api has not kept pace.

It is *our* responsibility here both in terms of education and in terms of providing appropriate apis.  

> First, one should clearly define what behavior is required

THis is already likely more challenging than what any external person could.  And it shifts the onus to the non-expert to fully define something that likely only a set of experts could do after significant effort.  We've seen this internally as our own teammates have attempted to make such apis and have themselves been thwarted (including several efforts by principal level devs).  What people, more often than not, are asking for is: i want to be able to answer this the way the compiler already clearly has to answer such a question today.  Part of our responsibility is to look out ourselves at how we explain these topics and how users are applying them and see where and when they go a path different from what we would think was appropriate.  These are the areas we need to take the personal responsibility for improving and then disseminating the information about.

**Comment by jnm2** [comment]
Cyrus's comment points out an ongoing frustration that is important to me and others that I've helped or collaborated with in the Roslyn analyzer ecosystem. I keep bringing this up. This pain is not theoretical. Death by juggling a thousand footguns amounts to a discouraging force against community building things.

**Comment by AlekseyTs** [comment]
> Nor are they likely able to come up with an alternate 'extension method' that truly encapsulate the accurate logic that the compiler has.

This API has nothing to do with what the compiler does or what language rules are. Language doesn't define resolution of metadata names. We have SemanticModel to represent name lookup and other language semantics. If that isn't clear from the APIs name, we can certainly adjust its doc comment to make it clear. I believe that we (Compiler) should not be in the business of defining any other "blessed" or "best" ways to lookup symbols. Marking the API as obsolete is simply inappropriate in my opinion. The IDE layer can define whatever helpers are appropriate for it. "If there is a consensus that certain rules are going to be common. I would support adding such an API as an extension method to the common layer."

I certainly can understand a situation when one misuses an API and then that gets copy pasted all over. Or it was used properly for some task and then got copy pasted for another task where its usage is inappropriate. Things like that can happen with any API. We cannot prevent anyone from publishing an analyzer that does whatever the author of the analyzer thinks appropriate to do about the usage of this API.

**Comment by jaredpar** [comment]
This discussion was originally brought up in #52037. Essentially tying the discussion of adding new API here to deprecating the `GetTypeByMetadataName`. That discussion derailed because it's conflating two separate problems that there is not general agreement should be tied together. I understand that several groups want the API deprecated by the Compiler team at this point does not agree with that direction. At the same time as indicated on previous issues and this one we're generally supportive of helping to define a new API that better serves the needs of customers who get tripped up by the behavior of the current API. 

The ask from Compilers in #52037 was to open two issues: one to discuss deprecation and one to discuss the new API proposal. The idea being that we should approach these separately. Lets chat about how to define an API that is more acceptable to customers in the analyzers / IDE space and a separate one to discuss if we want to find a way to discourage the usage of `GetTypeByMetadataName` in the same area. 

Instead this was opened which immediately again conflates the issues. The ask here is for us to tie a decision we simply don't agree with (deprecation / suggestion) to one which we are supportive of (new APIs that are better suited for the scenarios of analyzers / IDE). It's hard to make progress on the subject we all agree on when it keeps pushing back to subjects we've said we don't support at this time. 

I'm happy to continue listening to arguments for deprecation, suggestions for analyzers to use the new API, etc ... A new issue is a place where we can collect the issues users file, discuss the burden on the community when we deprecate, etc ... But as stated before when the ask is to  tie these two issues together it's hard to make progress because we simply don't agree with the deprecation one.

**Comment by jnm2** [comment]
@jaredpar Everything except the last paragraph is the motivation for exposing GetBestTypeByMetadataName. Before I file yet another issue that contains that whole motivation, do you see a problem with that being included as the motivation?

My mistake to say "Additionally, please add" at the end, since I didn't say "here's another issue, please keep discussion there."

**Comment by jaredpar** [comment]
> Everything except the last paragraph is the motivation for exposing GetBestTypeByMetadataName. Before I file yet another issue that contains that whole motivation, do you see a problem with that being included as the motivation?

The rest of the issue is fine. The last paragraph which ties deprecation to the ask is what I feel unnecessarily complicates the discussion.

**Comment by jnm2** [comment]
Thanks! Alright, I'll duplicate this issue but without that part.

**Comment by jnm2** [comment]
Redone: https://github.com/dotnet/roslyn/issues/52399
