### ISSUE TITLE
Support single-line null checks for 'Add null check'

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#52385]
**Version Used**: VS 16.9.3

This is the most frequent ReSharper command that I use. Roslyn's code fix requires tedious cleanup because it generates five lines per parameter. The chances are not high that I'm going to start being okay with five lines per parameter. The contrast in friction  is significant for me; with ReSharper, I'm not always cleaning up after I click.

```cs
using System;

public class C
{
    public void M(object first, object second, object third)
    {
        if (first is null)
        {
            throw new ArgumentNullException(nameof(first));
        }

        if (second is null)
        {
            throw new ArgumentNullException(nameof(second));
        }

        if (third is null)
        {
            throw new ArgumentNullException(nameof(third));
        }

        Console.WriteLine($"{first}: {second} ({third})");
    }
}
```

I want exactly what ReSharper does with a single command (except I have to insert the blank line myself, so Roslyn could even beat ReSharper here):

```cs
using System;

public class C
{
    public void M(object first, object second, object third)
    {
        if (first is null) throw new ArgumentNullException(nameof(first));
        if (second is null) throw new ArgumentNullException(nameof(second));
        if (third is null) throw new ArgumentNullException(nameof(third));

        Console.WriteLine($"{first}: {second} ({third})");
    }
}
```

**Comment by CyrusNajmabadi** [comment]
I think it woudl be very reasonable for us to do something better here. First, if the user has csharp_prefer_braces=always, we keep the current form. However, if they do not, we should opt toward the more lightweight: if (p is null) throw new ArgumentNullException(nameof(p));

THere are often many of these in a row, and requiring multiple lines for such a recognizable and symettric pattern is overkill.

**Comment by CyrusNajmabadi** [comment]
Also, we should follow a 'when in rome' approach here.  IF tehre is an existing null check, we should try to detect it and just follow whatever it does.

**Comment by CyrusNajmabadi** [comment]
Design decision notes:

Discussed if we should move to either fully using VS snippets, or moving to a template-lite approach (like we do with file_header) to allow user to customize the code that is generated.  Ultimately decided that was overkill and we would instead just drive updating the feature in the following manner: 

If the user has the following options: 

```
csharp_prefer_braces=false/when_multiline 
csharp_style_allow_embedded_statements_on_same_line_experimental=true 
```
 
Then we will just generate the single line form of the argument check, without braces. 

If the user has either `csharp_prefer_braces=true`, or `csharp_style_allow_embedded_statements_on_same_line_experimental=false` then we will enforce the old form for the code. 

 

Note that by default `csharp_style_allow_embedded_statements_on_same_line_experimental` is already true.  So the only thing a user needs to do is set `csharp_prefer_braces`.  Because `csharp_prefer_braces` is true by default, users who have not set anything will get the current form.
