### ISSUE TITLE
Suggestion: Remove "nameof()" from references list

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#52489]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Suggestion:-Remove-nameof-from-refer/1337827)._

---
![example](https://user-images.githubusercontent.com/46729679/114071835-6e4bc180-9856-11eb-9911-3977dba9c825.png)

When a references list of a method is opened, it also shows references where the method is used in a call to nameof(). Most of the times these do not interest me. I'm only concerned about the invocations of the method. So it would be a nice-to-have if the references to nameof() could be filtered out.

---
#### Feedback Bot on 2/14/2021, 10:04 PM: 

Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further. You will hear from us in about a week on our next steps.

#### Feedback Bot on 2/24/2021, 10:46 AM: 

<p>Your suggestion has been queued up for prioritization. Feature suggestions are prioritized based on the value to our broader developer community and the product roadmap. We may not be able to pursue this one immediately, but we will continue to monitor it for community input</p>

**Comment by BhaaLseN** [comment]
I'd rather _not_ have them removed; because it often shows me that the only usage of a propery in MVVM is in a `PropertyChanged` call while everything else is just XAML (but not actual code we write).

However, I can see this being its own classification at the back (where it usually says "Read", "Write", "Other" for the type of reference) - which _can_ be filtered to only list specific usages.

**Comment by HenriKwilia** [comment]
Very annoying when looking up references which i use all the time. Now i think a routines is used a lot more then it really is only because it is used in nameof.  I use nameof a lot for logging. 
If this is not rectified and removed from using i will revert back to putting the names as plain text instead of using nameof.

It should be removed because it is not a reference, nameof is a textual use of the method name. Therefore it is not correct

**Comment by CyrusNajmabadi** [comment]
>  should be removed because it is not a reference, 

It definitely is a reference. For example, if you change the name of the member, and don't update the nameof, then your code will break because the nameof won't be able to resolve that reference any more. 

One thing we can do, if we don't already, is make this one of the 'kinds' for the Kind column.  You can then filter those out of it's a kind you don't care about.

**Comment by HenriKwilia** [comment]
I'll explain my use case so you can better assess my problem. I use the Codelens feature references a lot to navigate through my source code. Because it is quick and easy accessible. Also it gives me a quick look where a method is used and how many times. And i can easily follow the flow of a program. But now the nameof() references are also shown there but it is not code which calls the function (executes it). If you could make it toggleable to filter it out or something other clever, it would be very nice. TIA

**Comment by CyrusNajmabadi** [comment]
Can you file a vs feedback issue?  Roslyn doesn't control codelens here. Thanks!

**Comment by CyrusNajmabadi** [comment]
Great. Will close out!

**Comment by RevitArkitek** [comment]
I tried opening a new case to change the CodeLens feature to remove nameof usages but they keep closing it as a duplicate of this thread.  https://developercommunity.visualstudio.com/t/Remove-nameof-from-references-in-the/10225669  Can someone please help?

**Comment by billybooth** [comment]
Perhaps point them to https://github.com/dotnet/roslyn/issues/52489#issuecomment-1234501069, which  specifically indicates that Roslyn is not responsible for CodeLens and that a separate VS feedback issue should be filed (which you're obviously trying to do). 😉

**Comment by Bokkeman** [comment]
Instead of just excluding nameof() references (which some might want), rather elevate this request to a more comprehensive feature: 
In the references pane, provide a filtering mechanism, i.e. buttons/pill toggles along the top that allows you to include/exclude different types of references, e.g.
- nameof
- assignment (calls to 'set')
- read references (calls to 'get')
Each of these can be turned on/off by a simple click on these buttons/pills and the settings remembered from one invocation to the next. The idea is that it should be easy to change these settings because for every invocation of the references pane the user is likely to use a different set of filters.

**Comment by RevitArkitek** [comment]
This is about the CodeLens pop up, not the references pane. (Although I agree that filtering should be added there.) The number of references above a method should be a quick indicator to know if a method is really being used. The pop up then allows you to navigate to them. If there was a setting to ignore nameof() references in that count, then it would be a big help.

**Comment by CyrusNajmabadi** [comment]
> is really being used.

That's a matter of interpretation.  As an example, people commonly say "if there are zero references, i can safely delete".  Under that *very reasonable* interpretation, being used in a `nameof` should count.  After all, it's a use of that symbol, and deletion of the symbol will break that reference.

**Comment by ankofl** [comment]
> Instead of just excluding nameof() references (which some might want), rather elevate this request to a more comprehensive feature: In the references pane, provide a filtering mechanism, i.e. buttons/pill toggles along the top that allows you to include/exclude different types of references, e.g.
> 
> * nameof
> * assignment (calls to 'set')
> * read references (calls to 'get')
> 
> Each of these can be turned on/off by a simple click on these buttons/pills and the settings remembered from one invocation to the next. The idea is that it should be easy to change these settings because for every invocation of the references pane the user is likely to use a different set of filters.

Is there currently an extension for Visual Studio capable of configuring link filtering in Codelens ?
