### ISSUE TITLE
NormalizeWhitespace on switch expressions behave weirdly

### ISSUE THREAD

**Issue by HurricanKai** [dotnet/roslyn#52543]
**Version Used**: 
3.9.0

**Steps to Reproduce**:

1. Create a switch expression syntax
2. call .NormalizeWhitespace()
3. print the result, ie using .ToFullString()

**Expected Behavior**:
like all other components, switch expressions are formatted nicely

example:
```cs
entryPoint switch
{
    "MessageBoxA" => MessageBoxA,
    "CreateWindowExA" => CreateWindowExA
}
```

**Actual Behavior**:
switch expressions are formatted oddly

example:
```cs
entryPoint switch
{
"MessageBoxA" => MessageBoxA, "CreateWindowExA" => CreateWindowExA
}
```
note that at the end there is two newlines too much, as a trailing semicolon is weirdly placed like
```cs
...
}

;
```

**Comment by Youssef1313** [comment]
In case you, or someone else, wanted to contribute a fix, the new line after comma can be simply fixed by checking `SwitchExpressionSyntax` here:

https://github.com/dotnet/roslyn/blob/f48d930173ffbd6c8ce5d2bd372f1003cd6f9bf3/src/Compilers/CSharp/Portable/Syntax/SyntaxNormalizer.cs#L239-L240

The new lines issue can be fixed in:

https://github.com/dotnet/roslyn/blob/f48d930173ffbd6c8ce5d2bd372f1003cd6f9bf3/src/Compilers/CSharp/Portable/Syntax/SyntaxNormalizer.cs#L333

**Comment by HurricanKai** [comment]
sure, I can submit a PR for that.

**Comment by bernd5** [comment]
Have you worked on? Would be nice if this could be fixed

**Comment by bernd5** [comment]
I created a PR https://github.com/dotnet/roslyn/pull/52680

**Comment by HurricanKai** [comment]
Sorry I didn't have the time yet. Thank you for submitting a PR!
