### ISSUE TITLE
WithAttributeLists() looses Parent property value

### ISSUE THREAD

**Issue by Molesox** [dotnet/roslyn#52569]
**3.9**: 

**Steps to Reproduce**:

Take a syntax node and call the method WithAttributeLists(SomeAttribute);
Also happens with AddAttributeLists();

If we look the debugger value of the Parent field before the call we see some parent. And after the call the Parent field becomes null. 

I'm currently using that in a PropertyDeclarationSyntax rewriter. I don't understand why the Parent -which is the class - is lost. 
Is this a normal behaviour? If yes, How could I keep that information (since there is no way to store it and set it later cauz the object is immutable and no setter is given.)

**Comment by bernd5** [comment]
This is by design - the rewriter start at the top, go to the very bottom and construct a new tree from the bottom up.
When you call WithAttributeLists, you do not adjust the node - you create a copy just with a different AttributeList.

But it is also possible to replace a node(s). Therefore you should call "ReplaceNode" on the root-node.

**Comment by Molesox** [comment]
I indeed understood the way rewriters work (in a general manner) and also that each and every method returns à copy with the desired modification since nodes are immutable. The thing that looks strange to me is that calling WithAttributeLists returns à copy but with the Parent field set to null. Why not returning a full/deep copy ?
Anyway, If I understand you, I should, instead of visiting properties, visit ClassDeclarationSyntax, find the nodes, modify them and then replace them. Right ? 
Seems a bit inefficient to me when the only thing I'd like to do is adding an attribut.

Thanks for your answer!

**Comment by Molesox** [comment]
And, then, by induction I suppose that every add we wanna do, must be done by a node remplacement if we wanna keep the tree structure ?

**Comment by bernd5** [comment]
Not really - just if you want to replace a single node (under the hood ReplaceNode is implemented with a CSharpSyntaxRewriter - it just simplifies it). You should just ignore the Parent property of the "adjusted-node".
Can you post a sample code?

**Comment by Molesox** [comment]
Since the code is part of a bigger project I'll try tomorrow at work to share a minimal example. Thanks

**Comment by CyrusNajmabadi** [comment]
This is by design.  The `With` operators do not set the parent.  To do this, they would need to clone the parents, which would require cloning all the other children of the parent, and so on and so forth.  So if you cloned the parent, you would end up with a clone of the  *entire tree*.  This would be hugely expensive and untenable.

If you want this behavior, just take the root, and do `root.ReplaceNode(attr, attr.WithAttributeLists(...))`.

**Comment by bernd5** [comment]
See a sample:
https://dotnetfiddle.net/FVZRc3
