### ISSUE TITLE
Audit the compiler for ignoring the return value of Stream.Read

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#5267]
Bug #5052 is one instance of this, but there are others, like the one in https://github.com/dotnet/roslyn/blob/0382e3e3fc543fc483090bff3ab1eaae39dfb4d9/src/Compilers/Core/Portable/CvtRes.cs#L207-L209

**Comment by svick** [comment]
Would that make sense as a general analyzer?

**Comment by agocke** [comment]
@svick Almost definitely. @stephentoub I presume your change to the Linux implementation to be more aggressive in fetching data means this is something people miss fairly often?

**Comment by stephentoub** [comment]
>  I presume your change to the Linux implementation to be more aggressive in fetching data means this is something people miss fairly often?

It's primarily because it's a semi-observable behavioral difference from Windows, and we're trying to minimize such differences as much as possible; if the Windows implementation of FileStream wasn't already doing this, I wouldn't have done it for Unix.  I've not heard of this biting people often, though that doesn't mean it doesn't happen... obviously :smile:

**Comment by agocke** [comment]
@stephentoub Fair enough.

@svick In fact, I think an even more general analyzer that makes sure people don't implicitly discard return values would probably be a good one.

**Comment by tmat** [comment]
You'd get a lot of false positives if you reported every ignored return value. Many APIs are designed that way. For example, https://msdn.microsoft.com/en-us/library/b4sc8ca8(v=vs.110).aspx

**Comment by AlekseyTs** [comment]
@agocke Please verify
