### ISSUE TITLE
Casting argument to dynamic inhibits type checking on return type of method

### ISSUE THREAD

**Issue by Szune** [dotnet/roslyn#53080]
### Disclaimer
I may have failed to understand the docs but logically the result is surprising anyhow.

### Description
When casting an argument to a method to dynamic, type checking is inhibited even on the return type.
I.e. assigning a variable of type `string` with the return value of a method with return type `SomeClass` will not cause a compiler error if the method is called with an argument that is cast to dynamic (or just is dynamic).

If the same is done with a local function instead of a method, the result is a compile time error (as I'd expect for both cases).

I apologize for being pretty bad at explaining it, but the code should make it clearer.

If this is working as intended however, maybe that could be cleared up in the docs?
I happened upon this whole thing when working with some SQL mapping with Dapper and was surprised to see there was no compiler error.

**Expected behavior:**
Compile time error/warning, the return type is not compatible with the variable type and will always(?) fail at runtime

**Actual behavior:**
Runtime error

**To reproduce:**
```csharp
// Uncomment - runtime error:
//string Val = new Test().Create((dynamic)1);

// except if it's a local function
// Uncomment - compiler error
//string Val = Create((dynamic)1);

InvalidValue Create(int value)
{
	return new InvalidValue(value);
}

class Test
{
	public InvalidValue Create(int value)
	{
		return new InvalidValue(value);
	}
}

class InvalidValue
{
	// from the docs:
	// Operations in which the result is not dynamic include: 
	// Constructor calls that include arguments of type dynamic.
	public InvalidValue(int value) 
	{
		// the result is the same whether or not `value` is declared as int or dynamic
		Value = value;
	}
	public int Value;
}
```

### Configuration
.NET 5
Windows 10 (x64)
Issue is likely not related to the configuration

**Comment by tfenise** [comment]
I have an idea on the logic. For `string Val = new Test().Create((dynamic)1)`, in general `class Test` may lie in a different assembly, and at runtime it could succeed because the `class Test` at runtime may have different methods with different return types (or implement `IDynamicMetaObjectProvider`?). The case with local functions is different, as local functions can only reside in the same assembly as the caller, and cannot change between runtime and compile time.

**Comment by jaredpar** [comment]
Thanks for taking the time to report this issue. Unfortunately the behavior is "By Design". 

```c#
// Uncomment - runtime error:
//string Val = new Test().Create((dynamic)1);
```

This is the because for normal functions when any argument is `dynamic` the entire expression is `dynamic`. This is not actually evaluated at compile time but rather by the dynamic binder at runtime. The compiler sees the call to `Create` as a `dynamic` expression and uses a dynamic conversion to `string` at the end. This is why the exception occurs at runtime, it's all in the dynamic binder. 

```c#
// except if it's a local function
// Uncomment - compiler error
//string Val = Create((dynamic)1);
```

This is because local functions do not support overloads hence there is no reason to involve the dynamic binder here. There is really nothing for the binder to decide on because the decision has only a single answer. Hence the compiler will resolve all dynamic arguments and statically pass them to the function.
