### ISSUE TITLE
When will we have code generation using net5.0 instead of netstandard2.0?

### ISSUE THREAD

**Issue by PunzunLtd** [dotnet/roslyn#53193]
We have a project that uses a collection of regular expressions that we used to compile into their own assembly. This assembly has been stable since 2019, meaning the last time we compiled it, we used .NET Fx 4.8, and just dropped the .dll into our .NET 5 update project.

We got all excited about the [improvements to regular expression handling](https://devblogs.microsoft.com/dotnet/regex-performance-improvements-in-net-5/) in .NET 5, so we tried running our regular expression compiler in .NET 5.

We got all sad because [DotNetCore no longer emits assemblies](https://www.github.com/dotnet/runtime/issues/15704).

We got all excited because a [source generator](https://devblogs.microsoft.com/dotnet/introducing-c-source-generators/) is a much better solution: we get the latest runtime, we can generate the code in our deployment pipeline, etc, etc.

Right now we're all sad because source generators run under netstandard2.0 only. Running them under net5.0 causes the compiler to complain "Could not load file or assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified." And [this is a known issue](https://github.com/dotnet/roslyn/issues/49249).

So. We'll downgrade our source generator to use netstandard2.0 (and refactor the C#9 syntax back to 7.3), but when the generated code runs in our net5.0 assembly, will it use the net5.0 Regex class?

And when will net5.0 projects be able to run source generators?

**Comment by sharwell** [comment]
> So. We'll downgrade our source generator to use netstandard2.0 (and refactor the C#9 syntax back to 7.3), but when the generated code runs in our net5.0 assembly, will it use the net5.0 Regex class?

The code generator runs at build time. The generated code is then compiled as part of the assembly, and will eventually execute on whatever framework the project targets. If you add generated code to a project that targets net5.0, that generated code will eventually run on net5.0.

> And when will net5.0 projects be able to run source generators?

There is no target framework restriction for a project that uses source generators. Only the source generator itself has a netstandard2.0 restriction.

**Comment by ThomasBleijendaal** [comment]
This netstandard2.0 restriction makes it hard to create a source generator that shares classes with projects that are build in net5.0. The shared classes must be pulled out the net5.0 projects and made sure that it is compatible with netstandard2.0. So while it's true that the source generator itself only has to be netstandard2.0, its also imposes that restriction on the dependencies of that source generator.

**Comment by mstancombe** [comment]
@ThomasBleijendaal I second that.  The most useful cases for source gen that I have come across are ones where it extends on in house code to remove repetition.  But in order to do that in a strongly typed way, we can't use .net 5 for those classes.  Ideally, we'd be able to emit code like " : {nameof(MyBaseClass)}", but of course, we can't. Instead we just need to put the names of base classses and methods in stringly typed.  
Having said that, the reason why it needs to target .net standard 2 seems to be mostly because VS2019 uses full framework, so source gens still need to use a cross platform assembly to be loaded (ie, .net standard).  Hopefully this will change soon, and we can get back to strong typed awesomeness.

**Comment by jaredpar** [comment]
> So while it's true that the source generator itself only has to be netstandard2.0, its also imposes that restriction on the dependencies of that source generator.

That is the case but it's a hard reality at the moment. The C# compiler continues to execute under both the .NET Framework as well as .NET Core runtimes. This occurs when it is run under `msbuild` and `dotnet build` respectively. Source generators run inside the compiler and hence they must operate under the same circumstances which is why `netstandard2.0` is the only realistic option here. 

In the longer term we are working to simplify this by having the C# compiler always run under .NET Core, even when invoked from `msbuild`, but we are at minimum a year away from that being a reality. Until then generators / analyzers must continue to target `netstandard2.0` in order to work in all the scenarios the compiler works on.
