### ISSUE TITLE
No snippets for autocomplete, only as and is operators

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#5336]
The autocomplete offers only **as** and **is** operators after values.

``` CSharp
  int i = 4
  for| // hit tab, changes to as
```

Not only this forces the developer to stop, delete what was wrongly autocompleted, go back and fix a missing semicolon to be able to continue whatever they were doing, but snippets are not offered in the autocomplete list even if applicable.

**Comment by dpoeschl** [comment]
Visual Studio 2013 offered all sorts of stuff in this particular context, including types/namespaces/members/snippets. I'd guess that reducing this set down in Visual Studio 2015 was a good move overall, since most typing in that location would be to actually continue the expression. 

I'm mostly for keeping the list uncluttered in this case, which helps the user type correct code (is/as, if that's what they're going for, without them being buried in a huge list) or helps them realize that something is off if they're expecting more things in the list (such as your case). Even if the for snippet completed here, it may format very strangely since it thinks it's part of some local declaration. But, I'm definitely happy to hear other opinions on this case!

(FYI: You can still invoke the snippet at that location, but you'll have to dismiss the completion list first and just hit "TAB" after the word "for" in the editor).

**Comment by sharwell** [comment]
This scenario is particularly interesting because assuming the user forgot an intended semicolon, code snippets are the most likely reason the user would hit <kbd>Tab</kbd>, and this is the only keystroke which causes `for` to be replaced with a value from the completion list.

Perhaps this is a compelling reason to continue to show code snippets in the completion list.

**Comment by miloush** [comment]
Indeed this is a good indication, the problem is that in previous versions, you could finish what you have been doing and then fix the problem, while unexpectedly turning `for` into `as` is much more disruptive. It is also true that you can dismiss the list, but this particular scenario bites when you hit keys mechanically without thinking about every list shown.

Another scenario when this behavior was a bit surprise was when I just wanted randomly inspect a type or member (i.e. just trigger autocomplete, intellisense or quick fixes). It used to be possible to place cursor almost everywhere in a member body and start typing. Now I need to take extra care where to do it.

Anyway, although this was not the problem for me in this case, I would have been definitely disappointed if I had snippets that started with operators or were comments and I couldn't use them anymore here.

**Comment by sharwell** [comment]
> I would have been definitely disappointed if I had snippets that ... were comments 

:thought_balloon: That's an interesting thought.

**Comment by CyrusNajmabadi** [comment]
Does not repro.  I get no completion here at all.

![image](https://user-images.githubusercontent.com/4564579/217120110-82ca92b5-9389-45aa-9931-62e86cd4da65.png)

**Comment by sharwell** [comment]
In addition to completion not being offered, I noticed that pressing <kbd>Tab</kbd> produces a snippet completion.
