### ISSUE TITLE
Inheritance Margin Icons are too small

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#53401]
Direct customer feedback copying here:

> The I and O icons are a little small though. Different colors would make them easier to tell apart.

Note: Making the icons larger is somewhat difficult. Notice once the icon is selected it's right border is almost across the line:
![inheritance-margin-icon](https://user-images.githubusercontent.com/46729679/118179705-7b764600-b3ea-11eb-8a07-e19036eb7ff2.png)

We can either incorporate different colors or make the icons larger and move them to a separate column next to the line number.

**Comment by JamesNK** [comment]
Also, the icon seems rather low resolution. It is noticeably blurry when the VS's zoom is high (150%+)

**Comment by CyrusNajmabadi** [comment]
FWIW, i love how it looks.  But that's at my particular DPI/Zoom level.  I think we should keep the current placement, but just focus on makign sure hte glyphs look good at varying resolutions/dpis/zooms.

**Comment by Cosifne** [comment]
I think this can be closed because 
1. The DPI settings problem has been fixed.
2. UX has redrawn the icon in this PR, the new icon will utilize more space. https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/340634

If later someone still feel it is too small, we could control the size of the icon after the linked PR is checked in
