### ISSUE TITLE
ConvertToSemanticTokenEdits can allocate a lot of Int32[]

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/roslyn#53499]
**Version Used**: VS 17.0.0 Preview1.0 31312.29.main

**Steps to Reproduce**:
1. Open a large Blazor App
2. Take a large portion (mine was ~40 lines) of Blazor code which contains a good mix of Components and C# and copy it.
3. Rapidly paste the above. My resulting file was >600 lines long.

**Expected Behavior**:
I'm obviously doing something artificially bad for perf, so some degree of allocations/CPU time is expected here.

**Actual Behavior**:
![The allocations were over 10GB](https://user-images.githubusercontent.com/14987221/118723698-94b03580-b7e2-11eb-9678-af36731d75f6.png)
Over 10GB of Int32[] allocations from `SemanticTokensEditsHandler.ConvertToSemanticTokenEdits`.

#### Suggestions
I had a very similar problem with the Razor implementation of this same endpoint and [landed on this solution](https://github.com/dotnet/aspnetcore-tooling/blob/main/src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/Services/SemanticTokensEditsDiffer.cs). If you have Benchmarking infrastructure which would work in this instance you might also want to replicate [parts of our benchmark tests](https://github.com/dotnet/aspnetcore-tooling/blob/main/src/Razor/benchmarks/Microsoft.AspNetCore.Razor.Microbenchmarks/LanguageServer/RazorSemanticTokensBenchmark.cs) to make sure you don't regress CPU time.

CC @allisonchou and @dibarbet were suggested as knowledgeable people who could tell me if I'm way off base. Y'all have clearly [already considered perf](https://github.com/dotnet/roslyn/blob/main/src/Features/LanguageServer/Protocol/Handler/SemanticTokens/SemanticTokensEditsHandler.cs#L102) in this area so it may be that the alternative is worse for your most common scenarios.

**Comment by dibarbet** [comment]
@allisonchou if you have room on your plate, would you be able to take a look?  I don't have room to take this up immediately

**Comment by allisonchou** [comment]
Yup! I can probably take a look in a bit, I'm pretty sure there's some room for optimization here.

**Comment by allisonchou** [comment]
Looked into this issue, tl;dr **Roslyn would probably be able to save on massive amounts of array allocation if we don't try to combine tokens into one edit**. However, taking this approach would mean we'd be returning an individual SemanticTokensEdit for every single changed token (similar to what Razor does today), as opposed to combining them into one larger edit (as Roslyn does today). I'll probably need to manually try implementing the new approach in Roslyn and do a benchmark comparison.

A couple differences between Roslyn and Razor's implementations:
- **Roslyn processes edits by token, while Razor processes edits by token part.** For example, if part of a token needs changing, Roslyn will replace the entire token, while Razor will only replace the specific part of the token that requires modification. Roslyn takes the whole-token approach to potentially save on computation costs when computing edits, since we can return early if part of the token doesn't match, as opposed to comparing each individual token part individually. This is a trade-off though, since we might be returning edits for parts of tokens that don't need modification.
- **Roslyn will try to group the maximum number of edits into a singular edit, while Razor seems to create multiple, smaller edits.** As far as I can tell, Razor creates a new edit for every single changed int. On the other hand, Roslyn attempts to combine edits. I believe this combination work results in the massive amounts of array allocation seen in Ryan's findings. Looked through and unfortunately I didn't see a lot of wiggle room to reduce Roslyn's array allocation if we stick to this approach.

The approach I'm going to try out and compare to the existing implementation: Roslyn will still process on a per-token basis, but will not try to group together edits minimally. Hopefully this will save on overall array allocations while still maintaining speed, will update here when I have results!

**Comment by jinujoseph** [comment]
cc @sharwell

**Comment by allisonchou** [comment]
https://github.com/dotnet/roslyn/pull/55430 changed our edits processing algorithm completely and I think perf should be much better now. @ryanbrandenburg if you still notice perf issues in the future, we can revisit this.
