### ISSUE TITLE
For methods and fields in C#, set the scope to protected for unless class is sealed

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#53560]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/For-methods-and-fields-in-C-set-the-sc/1412530)._

---
When creating a new field or method inside a class, the method should be protected if the class is not sealed, or private if the class is sealed. 

VS could suggest sealing the class when creating a class.

---
#### Feedback Bot on 5/6/2021, 01:21 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by sharwell** [comment]
> When creating a new field or method inside a class, the method should be protected if the class is not sealed, or private if the class is sealed.

Currently members are created as private, but can be increased to protected if necessary. Can you provide more information about the specific steps where this would save time?

> VS could suggest sealing the class when creating a class.

This is more challenging than it seems at first glance. In a previous discussion (https://github.com/dotnet/roslyn/issues/33092#issuecomment-467456754), we decided to not implement this due to complexity relative to limited benefit.
