### ISSUE TITLE
ExceptionHandlingClauses should work for async methods

### ISSUE THREAD

**Issue by nathan-fieldstack-com** [dotnet/roslyn#53700]
**Version Used**: 
Visual Studio Enterprise 2019 Version 16.9.4
C# Tools   3.9.0-6.21160.10+59eedc33d35754759994155ea2f4e1012a9951e3
**Steps to Reproduce**:
1. Create a public async method that has one try-catch block
2. Use `GetMethod(theMethodName).ExceptionClauses`

**Expected Behavior**:
The list would contain one ExceptionHandlingClause element
**Actual Behavior**:
The list is empty

Note that if the method is not async, this works as expected - the list contains one ExceptionHandlingClause element

Program.cs where this can be demonstrated
```
using System;
using System.Reflection;
using System.Threading.Tasks;

namespace ExceptionInspection
{
    class Program
    {
        public static void SyncExc()
        {
            try
            {
            }
            catch
            {
            }
        }

        public async static Task AsyncExc()
        {
            try
            {
            }
            catch
            {
            }
        }

        // Prints 1 and then 0
        static void Main(string[] args)
        {
            foreach (string methodName in new[] { "SyncExc", "AsyncExc" })
            {
                MethodInfo method = typeof(Program).GetMethod(methodName);
                var clauses = method.GetMethodBody().ExceptionHandlingClauses;
                Console.WriteLine(clauses.Count);
            }
        }
    }
}
```

**Comment by jaredpar** [comment]
Thanks for taking the time to file this issue but the behavior is "By Design". The compiler moves the bulk of the user code in `async` methods into helper types and methods. The reflection call here is inspecting the emitted code and it sees the stub the compiler generates to call into the actual `async` logic. That method does not have any exception handling information. 

This is a case where reflection is observing implementation details of the compiler. That is generally unsupported territory.
