### ISSUE TITLE
Clicking on inheritance margin does not open up (potentially due to VS being in Chinese)

### ISSUE THREAD

**Issue by ahdung** [dotnet/roslyn#53708]
Sorry about ask this question in here.

.netfx Winform project.
This icon appears after upgrading VS to **16.10.0**.

![image](https://user-images.githubusercontent.com/12094247/119749630-0c105400-beca-11eb-9ce1-b8d39d5aea42.png)

**Comment by CyrusNajmabadi** [comment]
It shows the inheritance chain for the type (the classes it inherits from and the interfaces it implements).  Clicking on it will let you easily jump to those.  See https://devblogs.microsoft.com/visualstudio/visual-studio-2019-v16-10-and-v16-11-preview-1-are-available-today/#visualize-and-navigate-inheritance-chains

**Comment by ahdung** [comment]
Thank you.
But when I hover on it, or click/right click it, nothing happen.
My OS: Windows server 2008 R2 SP1
VS using chinese language
![recording](https://user-images.githubusercontent.com/12094247/119757403-7c71a200-bed7-11eb-9dd5-a871cd2fb6e4.gif)

**Comment by CyrusNajmabadi** [comment]
Reactivating.  @Cosifne can you look into this?

**Comment by Cosifne** [comment]
Sorry for the late response, I was on vacation when this issue is created.

@ahdung 
The problem you show is quite weird, I haven't encountered this when using the margin. (Also tested in Chinese Language)
I even don't the the tooltip when the mouse is hoovering over the margin.

My best guess is, other margin 'hide' the inheritance margin. Could turn off the margin by tools -> text editor -> advanced -> show inheritance margin and see if there is any other margin? Or have you installed other extensions that also provide margin?

In all other cases, could you try turning it off -> on to refresh the margin? If this still doesn't work then this might be a bug in the editor.

**Comment by Cosifne** [comment]
One another possibility that just comes to my mind today is, the command inserting the breakpoint to the line might just handle the click, so, therefore, VS is thinking you are trying to add a breakpoint, instead of clicking the margin.

I will try to reach out to the debugger team and figure out a solution.

**Comment by ahdung** [comment]
@Cosifne Sorry for late response.
I do using ReSharper, and it is probably the reason, my test:
- In options > ReSharper, click "Suspend Now", OK, restart VS, not work.
- In extensions manager, Disable ReSharper and restart VS, it's worked. And I re-enable ReSharper in extensions manager and restart VS, issue return back.

So just suspend R# not work, must disable it. Maybe I should report this to JetBrains. Thank you sirs.

**Comment by silkfire** [comment]
I got the issue with all extensions disabled.

**Comment by Otiel** [comment]
Same issue here, disabling Resharper fixed it.

**Comment by Cosifne** [comment]
To anyone else who might hit this.
Now Inheritance margin of Visual Studio could be placed in a separate margin.  (Option under Text Editor -> C#/VB -> Inheritance Margin -> Combine inheritance margin with Indicator Margin)
My best guess about Resharper is it provides its own left margin above Visual Studio. (The left margin of VS is quite crowded)
But in any case, the option should be the best solution.

**Comment by ahdung** [comment]
@Cosifne Sorry, there's another issue I'd please you to take a look, the [developercommunity](https://developercommunity.visualstudio.com/t/VS2022-170-got-a-incorrect-edge-renderi/1611763) has no response for a long time. It's about the appearance of VS:

VS2022 17.x has a weird border on windows 2008 R2(I guess windows7 is same)
![image](https://user-images.githubusercontent.com/12094247/152913478-f7b4ad3f-c9ad-4bb4-a995-d0a321563186.png)

**Comment by Cosifne** [comment]
Hi ahdung,

The feedback ticket you posted is not related to Roslyn, so sorry I can't provide any help on that. From the screenshot I feel It's probably a issue related to the VS Shell. However, I can't tell the reason because I am not an expert in that area.

From the status of the ticket it seems like it has been directed to the corresponding team, and it's probably in someone's backlog.

**Comment by ahdung** [comment]
@Cosifne I understand, Thank you anyway.
