### ISSUE TITLE
CallerMemberName doesn't pass the class name to attribute constructor

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#53757]
See https://github.com/dotnet/roslyn/pull/53535#discussion_r641641163.

It's not clear whether this is a bug or not - and whether it should be fixed or not.

**Comment by jaredpar** [comment]
Believe the behavior is "By Design" here. From the spec 

> If a function invocation from a location within the body of a function member or within an attribute applied to the function member itself or its return type, parameters or type parameters in source code omits an optional parameter with the CallerMemberNameAttribute, then a string literal representing the name of that member is used as an argument to the invocation instead of the default parameter value.

Essentially the `CallerMemberName` is only replaced when it is used as an attribute on a function member, not when applied to a type declaration. 

I agree that this appears odd at a glance but reading through the spec it seems pretty deliberate. The spec for this section enumerates the places where it is allowed and goes into pretty good detail. Yet it omits type declarations. That makes me believe this is deliberate even though I can't discern the reasons.
