### ISSUE TITLE
[Responsiveness] Roslyn should disable MEF v2 path inside Visual Studio

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#53788]
It is very easy to initialize a Roslyn workspace on the path where it loads MEF v2 to initialize services inside Visual Studio. This bypasses VS MEF and its cache, and has resulted in at least 3 UI delays:

https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1290217
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1335572
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1277007/

Please disable this path inside Visual Studio to avoid future regressions.

**Comment by NTaylorMullen** [comment]
When fixing this we'll probably need to react in Razor so ping me when this work starts

**Comment by davkean** [comment]
Razor should move regardless of this change.

**Comment by NTaylorMullen** [comment]
> Razor should move regardless of this change.

Agree, it's more about a timing thing. Aka, if Cyrus gets to it before us then it'll break us 😄

**Comment by jasonmalinowski** [comment]
I admit it's not entirely clear to me how we'd do this -- the code at the lower layer doesn't know it's in VS. Short of setting a static bool to block it or have the code do "if processname == 'devenv'", and this would break any extensions doing this.

Is there some way we can flag methods as blocked in RPS?

**Comment by NTaylorMullen** [comment]
Razor's PR to move: https://github.com/dotnet/aspnetcore-tooling/pull/3707

**Comment by CyrusNajmabadi** [comment]
@jasonmalinowski We could just obsolete (with warning) `MefHostServices.DefaultHost`.  Then anyone who tries to use it gets a notification that they're likely not doing teh right thing and should provided the services themselves.

AdhocWorkspace is a bit more difficult as we really don't want to warn on someone just instantiating that type simply.  I would have normally thought that woudln't be mcuh of a problem.  However, as we've learned from Razor, we are creating those types internally.  I dn't have a good solution for that.

**Comment by sharwell** [comment]
> Please disable this path inside Visual Studio to avoid future regressions.

This is a valid public API inside of Visual Studio. We don't use it ourselves, but it is technically valid for an extension to use it. I recommend not making a change here.

**Comment by CyrusNajmabadi** [comment]
I'm open to brainstorm ways we could at least prevent first parties from doing what Razor/Xaml/etc. have done.  Namely unintentionally go through the paths that are causing problems instead of the preferred non-problematic paths.  It seems like a pretty easy pit of fail, and it seems unfortunate that our only way to deal with this is for Dave to analyze a ton of traces and discover the mistake.

**Comment by sharwell** [comment]
@CyrusNajmabadi those projects should not be using AdhocWorkspace _at all_. Roslyn already has a workspace inside Visual Studio for use.

**Comment by NTaylorMullen** [comment]
Just to add some clarity as to why Razor uses AdhocWorkspace: Razor's language server runs in VSCode and in VS and in VSCode there's no workspace immediately available. Surprisingly today Razor's language server depends on the workspace for only one reason: **services**. In the VS4Mac era the decision was made to utilize Roslyn's services infra on workspaces to build out many of our internal tooling pieces because in VS4Mac there can be multiple solutions active at a time resulting in multiple workspaces. It seemed like an "alright" decision at the time because things would "Just work" in the multiple solution scenario; however, in hindsight we probably should have picked another mechanism to hoist our services. So this brings us to today where we're trying to utilize that infra without boiling the ocean via `AdhocWorkspaces` for our VSCode compatible language server.

**Comment by CyrusNajmabadi** [comment]
>   @CyrusNajmabadi those projects should not be using AdhocWorkspace at all</task-lists></div>

Sure. But here we are. So the question for me is what we might do to prevent this from having happened. And what we can do to prevent it from happening in the future.

**Comment by CyrusNajmabadi** [comment]
Haven't been able to think of anything we could do to prevent this.  So going to close this out given that all the existing offenders were fixed.

**Comment by jasonmalinowski** [comment]
Agreed that there's nothing Roslyn can really do here short of "if process name == devenv" to block this path, and that's not something we should be checking into a library. What we might be able to do though -- is there a way in our internal performance tooling to flag certain methods that shouldn't be called and the tooling will generally look for them? I'm sure we've also had framework methods that we don't want people calling either (Thread.Sleep? :smile:) that would be good to similarly flag.

**Comment by sharwell** [comment]
> is there a way in our internal performance tooling to flag certain methods that shouldn't be called and the tooling will generally look for them

We could fire a telemetry event, since that will be ignored in applications where telemetry service hasn't been manually hooked up.
