### ISSUE TITLE
EditorConfig UI: Select language for Analyzers

### ISSUE THREAD

**Issue by BhaaLseN** [dotnet/roslyn#53834]
It appears there is no way to change the _language_ being used on the Analyzers tab at this point.

My Windows is German, but I use English as primary language across pretty much anything else (which includes Visual Studio; where Tools > Options, Environment > International Settings is set to English). Exceptions etc. are in English as well (which usually helps when searching for things), but the "Analyzers" tab insists on showing me (sometimes IMO cringy) German.
<sup>_(I should probably just go and install a language pack for Windows instead, but it seems odd that this is the only location insisting on using my OS language)_</sup>

Naively I'd suggest to honor the same setting already present in Tools > Options, Environment > International Settings, assuming that it should affect _all_ of Visual Studio (which includes the EditorConfig UI, and not just the main window).

_Originally posted by @BhaaLseN in https://github.com/dotnet/roslyn/discussions/53791_

**Comment by kirsan31** [comment]
> Naively I'd suggest to honor the same setting already present in Tools > Options, Environment > International Settings, assuming that it should affect all of Visual Studio (which includes the EditorConfig UI, and not just the main window).

**Totally agree.**

Now it's [honor](https://github.com/dotnet/roslyn/pull/54603) CurrentUICulture windows settings 😲 

For now due to this and multi target project analyzers bug (no analyzers for .Net5)
![image](https://user-images.githubusercontent.com/17767561/130187269-a27c51f3-45e5-4260-a696-3d67553e6e26.png)

the only way to maintain analyzers in VS is to force them on in net472 target too. That very bad idea because net472 target is dummy target for using old Net framework designer with .net5 (due not working new one) 😭 😭😭

**Comment by jmarolf** [comment]
fixed with https://github.com/dotnet/roslyn/pull/54603
