### ISSUE TITLE
Csc task does not initialize CommandLineArgs with assembly references

### ISSUE THREAD

**Issue by AArnott** [dotnet/roslyn#53920]
When executing the `CoreCompile` msbuild target with the `ProvideCommandLineArgs` property set to `true`, I expect to get a full representation of the csc command line in the msbuild `@(CscCommandLineArgs)` items. But this list omits all assembly references. Can these be included, please?

Alternatively, if this is really by design, is this documented anywhere? What would I use instead to initialize the language service?

Relevant source locations:

https://github.com/dotnet/roslyn/blob/9dc51cfd0b45ff87c595bd35d4edb65b743930f9/src/Compilers/Core/MSBuildTask/ManagedCompiler.cs#L126-L131

https://github.com/dotnet/roslyn/blob/c9eaa35cd4a2d7e4f99321e03e09097531d0e435/src/Compilers/Core/MSBuildTask/Microsoft.CSharp.Core.targets#L151

**Comment by jaredpar** [comment]
Can you provide some more info here?  This should be working just fine. If it's not then the compilation should fail because the essentially the same arguments passed to `CommandLineArgs` are what we pass to the compilation calls. 

Here is the output from a fresh console app (`dotnet new console; dotnet build /p:ProvideCommandLineArgs=true /bl`)`. 

![image](https://user-images.githubusercontent.com/146967/121904210-d8149b80-ccdd-11eb-830e-b0b506cda823.png)

**Comment by AArnott** [comment]
It's actually working for me at this point as well. I'm not sure why it didn't before. Maybe I hadn't run `restore` first. Sorry for the noise.

**Comment by jaredpar** [comment]
No problem. Glad it's working 😄
