### ISSUE TITLE
"Find All References" doesn't work on static member name in declaration of explicit interface implementation for properties and events

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#54022]
```
interface I2
{
    abstract static int P2 { get; set; }
}

class C2_2 : I2
{
    // Explicit implementation
    static int I2.P2 { get; set; }
}

interface I3
{
    abstract static event System.Action E3;
}

class C3_2 : I3
{
    // Explicit implementation
    static event System.Action I3.E3
    {
        add { }
        remove { }
    }
}
```

Try to "Find All References" on P2 in ```I2.P2``` and on E3 in ```I3.E3```.

Observed:
Nothing is found.

Expected:
The declaration as well as call sites should be found as it works for methods.

Note, it looks like this also doesn't work for instance properties/events.

**Comment by AlekseyTs** [comment]
CC @sharwell

**Comment by Cosifne** [comment]
Verified this is fixed by https://github.com/dotnet/roslyn/pull/54056
 
Event:
![image](https://user-images.githubusercontent.com/24360909/122300126-bff67500-ceb3-11eb-9095-1005575e8eba.png)

Property:
![image](https://user-images.githubusercontent.com/24360909/122300170-cd136400-ceb3-11eb-9baf-aa58d59a8a72.png)
