### ISSUE TITLE
Rename 'show potential fixes' bug

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#54030]
Direct customer ask copying here:

> The rename refactoring only works about ½ of the time. If I change the name of a procedure or a variable and hover over the changed item, the ‘Show Potential Fixes’, in the tooltip pop-up, displays properly. However, when you click on the ‘Show Potential Fixes’, the tooltip is removed but the Rename option never shows. I haven’t seen any patterns that would indicate the problem will occur. Example: If I have several variable names to change, refactoring for one change works fine but refactoring for another wont work. In that case I have to go to each error location and manually change the item. This problem started with VS 2015 and has continued with the latest version of VS 2019.

**Comment by ryzngard** [comment]
I'm not sure I follow this @mikadumont , do you know what the customer is talking about?

**Comment by mikadumont** [comment]
> I'm not sure I follow this @mikadumont , do you know what the customer is talking about?

It seems that the rename refactoring only applies one variable change and not the rest so has to manually apply the changes. Will follow up with more details.

**Comment by mikadumont** [comment]
@ryzngard the following image gives an idea of what the customer is talking about.
 
![ex](https://user-images.githubusercontent.com/46729679/121952678-6c4c2600-cd11-11eb-92dc-581a8bb653d5.png)

The hot keys don’t work ether. Some suggestions are shown but nothing to change the name.

**Comment by sharwell** [comment]
I tried this, but was not able to reproduce it in C# or Visual Basic. Can you provide a sequence of specific steps that produces this behavior?

**Comment by ryzngard** [comment]
This is related to ab#1342657

**Comment by rboberholz** [comment]
The above is my original reporting of the problem.
Additional Info: This issue is still a problem not only for VS2019 but also in VS2022. The refactoring attempt fails in a MouseDown event for the "Show Potential Fixes". If you left click and hold the mouse button down and the prompt remains, the refactoring will work. If you left click and hold the mouse button down and the prompt disappears, the refactoring will fail. There isn't any pattern when refactoring fails. I have had it fail when trying to refactor a variable in a short procedure and had it work when refactoring a variable or procedure in the entire solution.   
I hope this additional info helps.
