### ISSUE TITLE
Code snippets whose shortcuts start with # cannot be used

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#54038]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Code-snippets-whose-shortcuts-starts-wit/1447220)._

---
[severity:It's more difficult to complete my work]
I've just updated VS2019 to ver. 16.10.1 and all my code snippets whose shortcuts start with '#' (hash sign) cannot be used.

Steps to reproduce:
1. Create a code snippet (for C# in my case) and give it a shortcut '#abc'
2. Start editing a C# file
3. Type '#abc' and press Tab twice

Expected behaviour:
The code snipped should be inserted.

Actual behaviour:
The '#abc' text stays on the screen and two tabs are inserted afterwards.

---
#### Feedback Bot on 6/10/2021, 06:48 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by RaceRalph** [comment]
It's a regression.  Shortcuts starting with '#' were working in all versions of VS2019 preceding 16.10.

**Comment by sharwell** [comment]
📝 This behavior only occurs when Argument Completion is enabled. The error is caused by this code failing to handle the case where `token.Kind == None`:

https://github.com/dotnet/roslyn/blob/781dab82c6cc8a6e0d04e66bcbacf04ab16e2e91/src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetExpansionClient.cs#L741-L742
