### ISSUE TITLE
Record structs + copy constructor signature = missing compiler error

### ISSUE THREAD

**Issue by controlflow** [dotnet/roslyn#54413]
**Version Used**: 

main branch @ 26.06.2021

**Steps to Reproduce**:

Compile the following code:
```c#
record struct Value(string Text)
{
  private Value(int X) { } // error: must have this initializer
  private Value(Value original) { } // no error!
}

record class Boxed(string Text)
{
  private Boxed(int X) { } // error: must have this initializer
  private Boxed(Boxed original) { } // error: copy ctor must be public or protected
}
```

**Expected Behavior**:

Compiler error is missing - all non-primary constructors of `record struct` must have `this` initializer, there should be no exception for "copy constructor" signature unlike in ordinary records.

**Actual Behavior**:

Compiler recognizes copy constructor signature for `record struct` and do not emits "Must have this initializer" error in `record struct` declaration.

**Comment by RikkiGibson** [comment]
@jcouv could you please clarify whether the "actual" behavior described in this issue is expected? I wasn't able to find a resolution to this in the [record structs spec](https://github.com/dotnet/csharplang/blob/main/proposals/record-structs.md). The last LDM notes I was able to find said the decision around copy constructors/`Clone` in record structs is [on hold](https://github.com/dotnet/csharplang/blob/3c8559f186d4c5df5d1299b0eaa4e139ae130ab6/meetings/2021/LDM-2021-01-27.md#copy-constructors-and-clone-methods).

**Comment by jcouv** [comment]
@controlflow's description of expected behavior is correct. We should expect an error on `private Value(Value original) { }`.

**Comment by jcouv** [comment]
Fix merged into VS17.0p4
