### ISSUE TITLE
Remove ABI namespaces from fully qualified namespace suggestions

### ISSUE THREAD

**Issue by angelazhangmsft** [dotnet/roslyn#54544]
**Version Used**: 
17.0.0 Preview 2.0 [31427.69.main]

**Steps to Reproduce**:

1. Create a .NET 5 app (console, wpf, etc)
2. Change the `TargetFramework` to net5.0-windows10.0.19041.0
3. Use a WinRT API, such as: `var x = new Geolocator();`
4. Ctrl+. to open suggestions

**Expected Behavior**:
Fully qualified namespace suggestions should remove the ABI namespaces.

**Actual Behavior**:

Quick suggestions show:

Using Windows.Devices.GeoLocation.GeoLocator;
ABI.Windows.Devices.GeoLocation.GeoLocator
Windows.Devices.GeoLocation.GeoLocator
Generate Class ...

**Comment by Youssef1313** [comment]
@CyrusNajmabadi Your PR for this issue was merged into `main-vs-deps`. Was that intentional? `main-vs-deps` is never merged back into `main` by dotnet-bot (the opposite is true):

https://github.com/dotnet/roslyn-tools/blob/d8335317e2c09ee2b6a5d33bd87ba390ec534849/src/GitHubCreateMergePRs/config.xml#L26
