### ISSUE TITLE
Support Source Generators with .net core (5+)

### ISSUE THREAD

**Issue by aktxyz** [dotnet/roslyn#54605]
I searched thru the open issues and did not see this, but seems like it should be there somewhere, please close if dupe and sorry about not finding it.

Anyhoo, it would be great to be able to have a pure .netcore project including source generators, now I have to have .netstandard for the source gen projects, and then have to have .net standard versions of any libraries the source gens require.

Please allow source gen projects to be .netcore

**Comment by Youssef1313** [comment]
This is a known limitation.

The reason is that source generators should be able to run in both .NET Framework and .NET Core environments. This is because Visual Studio is built on .NET Framework, and the command-line builds are run on .NET Core. The target framework that can satisfy both is .NET Standard.
