### ISSUE TITLE
Member from base type can't be used in MemberNotNull

### ISSUE THREAD

**Issue by MrJul** [dotnet/roslyn#54658]
`MemberNotNullAttribute` and `MemberNotNullWhenAttribute` can't refer to accessible members defined in base types.

**Version Used**: 
VisualStudio.16.Release/16.10.3+31424.327
C# Tools 3.10.0-4.21318.11+7ceb633154acb9d716fd3eb2b6df1a0468d8e416

**Steps to Reproduce**:
```cs
#nullable enable

using System.Diagnostics.CodeAnalysis;

class A {
    public string? M { get; set; }
}

class B : A {
    [MemberNotNull(nameof(M))] // CS8776: Member 'M' cannot be used in this attribute.
    public void AssignM() => M = "a";
}
```

**Expected Behavior**:
I would expect the code to compile without warnings or errors since `M` is perfectly accessible.

**Actual Behavior**:
Warning: *CS8776: Member 'M' cannot be used in this attribute.*

**Comment by jaredpar** [comment]
Thanks for taking the time to file this issue, unfortunately this is by design. The C# language design team decided that `MemberNotNull` could only apply to declared members on the type where the attribute was used.

**Comment by Jehoel** [comment]
Given that this issue ( https://github.com/dotnet/roslyn/issues/56531 ) seems to be the same thing, but is kept open - does that mean the team has since changed direction on the issue and will now allow subclasses to make assertions about inherited supertype members?

What about the reverse-scenario: having `[MemberNotNull]` on a nonvirtual supertype method that points to a virtual member that's overridden in a derived-type?
