### ISSUE TITLE
Unexpected compile-time error when using inline initialization and null-conditional operator

### ISSUE THREAD

**Issue by avodovnik** [dotnet/roslyn#54711]
### Description

When the following snippet is compiled with `msbuild`, it works, as expected, but when it's compiled with `dotnet run` or `dotnet build`, it fails with:

```
C:\Users\anvod\src\triage\DotNet\BuildFailureRepro\BuildFailureRepro\BuildFailureRepro\Program.cs(12,35): error CS0165: Use of unassigned local variable 'result' [C:\Users\anvod\src\triage\DotNet\BuildFailureRepro\BuildFailureRepro\BuildFailureRepro\BuildFailureRepro.csproj]
```

Repro:

```csharp
using System;

namespace BuildFailureRepro
{
    class Program
    {
        static void Main(string[] args)
        {
            var r = new ReproSample();
            if (r?.DoSomething(out int result) ?? false)
            {
                Console.WriteLine(result);
            }
            Console.WriteLine("Hello World!");
        }

        private class ReproSample
        {
            public bool DoSomething(out int result)
            {
                result = 4;
                return true;
            }
        }
    }
}
```

This results in the weird situation where something will work within Visual Studio, i.e. Unit tests, but will fail on a CI environment. 

### (Relevant) Configuration

.NET 5.0.204
Windows 21H1 (19043.1052)

**Comment by jaredpar** [comment]
Thanks for taking the time to file this. Unfortunately this issue is "By Strange Design". 

What you are seeing in Visual Studio is a feature that we added in C# 10, enhancing our support around definite assignment to support a number of features (like `??`). These are features we added in a previous version of C# but neglected to update definite assignment for at that time. This was causing a number of friction points with developers and we cleaned a lot of them up in C# 10 in bulk. 

This type of feature is extremely hard to gate on `/langversion` though. Doing so would effectively cause us to re-run expensive parts of the compiler twice and diff the results. As such we decided that the better approach here was to just always turn this on. This does mean it can lead to a friction point, as you observed, when you mix old and new compilers with code that takes advantage of this feature. 

@RikkiGibson

**Comment by avodovnik** [comment]
Thanks for the clarification @jaredpar! 

Would it make sense/be less expensive to show a Warning for cases like this? 

FWIW, in my particular case that started this, I have:

```xml
<LangVersion>9</LangVersion>
```

in my `Directory.Build.props` so, while I understand the design reason, I feel like there might be a different issue somewhere :-).

**Comment by jaredpar** [comment]
> Would it make sense/be less expensive to show a Warning for cases like this?

For the new compiler to know it's hit a case where it disagrees with the old compiler it effectively requires doing the expensive analysis twice. Whether or not we report it as a warning or error isn't that different cost wise. The old compiler can't be updated to have a warning both because (a) it's already shipped and (b) the scenario needs to be an error not a warning. Accessing a variable before it's definitely assigned is a hard error in C# because it effectively allows developers to read uninitialized memory.
