### ISSUE TITLE
Can't compile more than 65,535 source files via msbuild

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#54775]
Context: is the following [tweet thread](https://twitter.com/funcOfJoe/status/1414696785570787328). Essentially a customer who has reasons for producing projects with an unusual number of source files. 

The limit here is coming in the communication between the MSBuild task and VBCSCompiler. The protocol limits the number of arguments to 65,535. Can't remember exactly why this was added but believe it was to protect against denial of service on the compiler (probably have to research a bit to remember why we did this).

Even if the limit is completely valid and needs to be kept the result of hitting the limit shouldn't be a failed compilation. Instead we should just fall back to the command line compilation.

**Comment by jaredpar** [comment]
@agocke do you remember why we added the 65,535 limit here?

**Comment by agocke** [comment]
There was an old bug in the VS targets due to checking things in and targets mismatch that ended up passing almost everything on the disk to the compiler, and it ended up DoSing the build machine instead of cleanly failing.

This was a convenient shortcut to prevent what I thought would not happen in practice. (😱)

No problem I remember with bumping the limit to `int` or `long`.
