### ISSUE TITLE
Introduce parameter issue for named tuple deconstruction

### ISSUE THREAD

**Issue by ryzngard** [dotnet/roslyn#54878]
When selecting a named tuple part, introduce parameter suggests adding this expression as a parameter. The change would always be invalid in this case

![image](https://user-images.githubusercontent.com/475144/126011435-380edf76-6bc0-4e80-94f1-3c4ffa38864c.png)

**Comment by davidwengier** [comment]
I'm not sure I follow why this is invalid. Do you mean because `uintPart` wouldn't be a valid identifier at the call site? I think that is just how Introduce Parameter works. Seems to do the same thing for a POCO too:

![image](https://user-images.githubusercontent.com/754264/126473182-1b68cca1-0900-4025-a11e-d826e11e03ca.png)

@akhera99 does this look right to you? or a bug?

**Comment by akhera99** [comment]
> I'm not sure I follow why this is invalid. Do you mean because `uintPart` wouldn't be a valid identifier at the call site? I think that is just how Introduce Parameter works. Seems to do the same thing for a POCO too:
> 
> ![image](https://user-images.githubusercontent.com/754264/126473182-1b68cca1-0900-4025-a11e-d826e11e03ca.png)
> 
> @akhera99 does this look right to you? or a bug?

I need to take a look. I would guess that we would not want to introduce a parameter in that case though.
