### ISSUE TITLE
System.BadImageFormatException: Bad IL Format

### ISSUE THREAD

**Issue by DavidSSL** [dotnet/roslyn#54938]
### Description

First off, I am an absolute newbie in the following but here is the problem. 

I am following the [example](https://github.com/JasonBock/CompilerAPIBook/blob/main/Chapter%201/Overview/CompileHelloWorld/Program.cs). 

and here is the code reproduced to speed things up:

```csharp
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using System.IO;
using System.Reflection;

namespace CompileHelloWorld
{
	public static class Program
	{
		public static void Main(string[] args)
		{
			var code =
@"using System;

namespace HelloWorld
{
	class Program
	{
		static void Main(string[] args)
		{
			Console.Out.WriteLine(""Hello compiled world"");
		}
	}
}";

			var tree = SyntaxFactory.ParseSyntaxTree(code);
			var compilation = CSharpCompilation.Create(
				"HelloWorldCompiled.exe",
				options: new CSharpCompilationOptions(OutputKind.ConsoleApplication),
				syntaxTrees: new[] { tree },
				references: new[] { MetadataReference.CreateFromFile(typeof(object).Assembly.Location) });

			using (var stream = new MemoryStream())
			{
				var compileResult = compilation.Emit(stream);
				var assembly = Assembly.Load(stream.GetBuffer());
				assembly.EntryPoint.Invoke(null, BindingFlags.NonPublic | BindingFlags.Static, 
					null, new object[] { null }, null);
			}
		}
	}
}
```

If the target compilation framework is .NET Framework, this will work no problem. However, if the target compilation is .NET Core it fails with the following:

```console
Unhandled exception. System.BadImageFormatException: Bad IL format.
   at System.Reflection.Assembly.Load(Byte[] rawAssembly, Byte[] rawSymbolStore)
   at System.Reflection.Assembly.Load(Byte[] rawAssembly)
   at CompileHelloWorld.Program.Main(String[] args) in ..\CompileHelloWorld\Program.cs:line 36
```

I have tried .NET Core 5, 3.1, 2.2, 2.1 and the same problem manifests itself. 

I even tried versions 1.1.1 and 3.1.0 of `Microsoft.CodeAnalysis`.

**Comment by svick** [comment]
You can see what the problem by inspecting `compileResult.Diagnostics` and you'll notice it has this:

> (9,4): error CS0103: The name 'Console' does not exist in the current context

This happens, because .Net Framework has all core types in the same assembly, while .Net Core/.Net 5+ has them split over multiple assemblies. One way to make your code work (at least on .Net 5) is:

```c#
var coreLib = typeof(object).Assembly.Location;

var referencePaths = new string[] { "System.Runtime.dll", "System.Console.dll" }
    .Select(file => Path.Combine(Path.GetDirectoryName(coreLib), file))
    .Prepend(coreLib);

var compilation = CSharpCompilation.Create(
    "HelloWorldCompiled.exe",
    options: new CSharpCompilationOptions(OutputKind.ConsoleApplication),
    syntaxTrees: new[] { tree },
    references: referencePaths.Select(path => MetadataReference.CreateFromFile(path)));
```

Note that this means referencing runtime assemblies. And while that is fine for experimentation or for small projects, you should reference the aptly named reference assemblies for more serious projects. Probably the easiest way to do that is to use [`Basic.Reference.Assemblies`](https://github.com/jaredpar/basic-reference-assemblies), but see https://github.com/dotnet/docs/issues/12317 for more details.

**Comment by DavidSSL** [comment]
Excellent explanation, fix and followup link.
