### ISSUE TITLE
DocumentationMode can be inconsistent when DocumentationFile property set in included MSBuild targets file

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#5525]
We have a very simple analyzer implemented as follows:

```csharp
private static void HandleSyntaxTree(SyntaxTreeAnalysisContext context) 
{ 
  if (context.Tree.Options.DocumentationMode != DocumentationMode.Diagnose) 
  { 
    context.ReportDiagnostic(Diagnostic.Create(Descriptor, context.Tree.GetLocation(new TextSpan(0, 0)))); 
  } 
} 
```

Today we received bug report DotNetAnalyzers/StyleCopAnalyzers#1572 regarding the behavior of this analyzer when the `<DocumentationFile>` MSBuild property is defined in an included project file as opposed to the main project file.

Since this is an intermittent bug that appears to only affect work inside the IDE, I'm not sure what other information might be helpful in resolving it.

**Comment by gafter** [comment]
Since the syntax tree options are set by the IDE code, I am dispatching this to the IDE team for investigation.

**Comment by Pilchie** [comment]
@sharwell Things to find out would be:

1. Does the build reliably produce documentation files on the command line?
2. Is the option specified correctly in IntelliSense builds (if it's set by the target, is the target guaranteed to run before CoreCompile)?

**Comment by Pilchie** [comment]
Without a repro this, this isn't actionable for us.

**Comment by Pilchie** [comment]
@jasonmalinowski is it possible that this flag isn't properly persisted in the IntelliSense build cache?

**Comment by stylpe** [comment]
Hi, I submitted DotNetAnalyzers/StyleCopAnalyzers#1572 and I have some news.
It's due to caching of imported .targets files somewhere in Visual Studio, but I have not been able to create a reliable repro; Something is different in my existing project, because a fresh project works somewhat better. I've not been able to isolate the behaviour, so I'll give as much detail as possible. 

- Triggers when editing `<Import>`ed .targets while affected projects are open in VS
- Performing project clean, rebuild, close and reload project, close and reload solution, delete all non-checked-in files (hg purge --all) gave varying results (at first, in my existing project, none of these worked after adding the `<DocumentationFile>`)
- Restarting Visual Studio always fixes the problem
- Checking the project properties, the Build page seems to be up to date (contradicting the analyzer warnings in the Errors List)
- It affects other things from the external .targets too, for example if the `<Analyzer>` references are removed while the project is open, Visual Studio will still have them and use them until it is restarted (and vice versa when adding them)
- And as noted in the referenced issue, building on the command line with msbuild always works.

So I guess this issue should be redefined, or closed and a new one opened. And it's a low priority for me, since editing the project files like this is a seldom event and I can afford to restart VS :), but it's nice to consolidate these things like code analysis and rulesets to something that can be shared, so I imagine I won't be the last to run into these problems.

**Comment by Pilchie** [comment]
Thanks. This sounds like a known issue where the project system doesn't re-evaluate files that are `<Imported>`ed, only the .*proj file itself.

We hope to address that in the next major VS release (not update) as part of a larger switch of the project system to use CPS.

Tagging @davkean and @jasonmalinowski so they see this too.
