### ISSUE TITLE
TableDataSource throws NullReferenceExceptions if there are items with no document ID

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#5545]
1. Attach a debugger to VS.
2. Add some broken analyzer to your project that won't load.
3. Watch null references get thrown by [line 97 here](https://github.com/dotnet/roslyn/blob/master/src/VisualStudio/Core/Def/Implementation/TableDataSource/TableItem.cs#L97)

It appears there should be a null check for `PrimaryDocumentId`.

**Comment by mavasani** [comment]
@heejaechang didn't you fix this recently?

**Comment by heejaechang** [comment]
@mavasani @jasonmalinowski yes. this is already fixed.

**Comment by jasonmalinowski** [comment]
How recently? I was seeing this just a few days ago.

**Comment by heejaechang** [comment]
quite recently? I think fix was done about a week ago but couldn’t be checked in due to all failures of our test infrastructure. So, probably checked in quite recently.

http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices/Implementation/TableDataSource/TableItem.cs,9af05afd2afed80c

souce.roslyn.io has updated source.


-          Heejae

**Comment by jasonmalinowski** [comment]
Ah this was fixed with pull request #5546, commit 6e87ff024fe4d1bfc1446bd456a7e69420276ebe.
