### ISSUE TITLE
No environnement name suggestion for Environnement.GetEnvironmentVariable()

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#55587]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/No-environnement-name-suggestion-for-Env/1478821)._

---
When calling Environment.GetEnvironmentVariable the first parameter is the environnement name variable to be retrived.

It would be nice to have a list of predefined and well know environnement (here like ASPNETCORE_ENVIRONMENT or any Windows/Linux standard environnement variable) variable name as an IntelliSense suggestion

---
#### Feedback Bot on 7/19/2021, 08:07 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

#### Mika Dumont [MSFT] on 7/30/2021, 09:12 AM: 

<p>Thanks for taking the time to provide this feedback! In 16.10 Preview 2 we added a completion option that automatically inserts arguments when writing a method call. This feature is off by default so you will need to enable it in Tools &gt; Options &gt; Text Editor &gt; C# &gt; IntelliSense and select Tab twice to insert arguments (experimental). Start writing a method call and press tab twice (tab+tab).The method call should includes arguments based on the method’s default values. You can then use parameter info to cycle through the list of arguments that you would like inserted by pressing the up and down arrow keys. Let me know if this works for your scenario.</p>
<p><strong>Why do we ask for more info?</strong><br>
We try to reproduce all issues reported with the information provided in the description and comments. When we can’t reproduce the issue, we ask you for more information so we can resolve the issue as quickly and efficiently as possible.<br>
In our <a target='_blank' href="https://aka.ms/vsfeedbackguidelines/#writing-a-good-bug-report-or-feature-suggestion">guidelines</a>, you can get tips on how to provide clear and simple reproducible steps.</p>

#### jeremie.leclercq on 8/2/2021, 00:48 AM: 

<p>Tried the mentionne option, how over is not adressing the initial suggestion.</p>
<p>Indeed the <strong>Environment.GetEnvironnementVariable</strong> has a single string parameter  and is NOT optional (so no default value) :</p>
<p><img src="https://aka.ms/dc/image?name=Bc5f3bac8771a4d3e8f959fc21ad91347637634870020138766_20210802-094321-image.png&amp;tid=c5f3bac8771a4d3e8f959fc21ad91347637634870020138766" alt="image.png"></p>
<p>I guess the proper way to adress is to create an enum at <strong>.Net level</strong> and to modify the method signature</p>
<p>=&gt; Method  <strong>Environment.GetFolderPath()</strong> is working this way</p>
<p><img src="https://aka.ms/dc/image?name=B48d30a7b26964c4d80a6e5fa9b8d05fe637634872764675310_20210802-094755-image.png&amp;tid=48d30a7b26964c4d80a6e5fa9b8d05fe637634872764675310" alt="image.png"></p>

**Comment by mikadumont** [comment]
@CyrusNajmabadi did we recently add this?

**Comment by CyrusNajmabadi** [comment]
No, we did not.  But a third party coudl by adding a completion provider for this.

**Comment by sharwell** [comment]
It seems like we could also add a string completion feature similar to how `InternalsVisibleTo` works for string literals.

**Comment by MaStr11** [comment]
## Where should such a provider be integrated into

There are at least three places, where such a provider could be integrated into:

### [EmbeddedLanguageCompletionProvider](https://github.com/dotnet/roslyn/blob/main/src/Features/Core/Portable/Completion/Providers/EmbeddedLanguageCompletionProvider.cs)

This approach is used by the [DateAndTimeEmbeddedCompletionProvider](https://github.com/dotnet/roslyn/blob/main/src/Features/Core/Portable/EmbeddedLanguages/DateAndTime/DateAndTimeEmbeddedCompletionProvider.cs) which does this suggestion:

![image](https://user-images.githubusercontent.com/24472128/144235614-50f31794-fe5f-402f-8ec0-9ac2a00906b4.png)

### [InternalsVisibleToCompletionProvider](https://github.com/dotnet/roslyn/blob/main/src/Features/CSharp/Portable/Completion/CompletionProviders/InternalsVisibleToCompletionProvider.cs)

This one completes `[InternalsVisibleTo("$$")]` by providing the assembly names of the solution. This one is based on `LSPCompletionProvider`.

### [ArgumentProvider](https://github.com/dotnet/roslyn/blob/main/src/Features/Core/Portable/Completion/ArgumentProvider.cs)

This isn't a completion provider and only seems to be able to suggest a single value. [DefaultArgumentProvider](https://github.com/dotnet/roslyn/blob/main/src/Features/CSharp/Portable/Completion/Providers/DefaultArgumentProvider.cs) is one of the derived types of this provider.

## What other argument value suggestions should be considered

It seems reasonable to me to create a base class for argument values suggestions, because there are other .Net types in the BCL that would benefit from such a completion:

* `System.Type.GetType("$$")` suggest fully qualified type names
* new System.IO.DriveInfo("$$") suggest drive letters `a` to `z`
* `Assembly.GetManifestResourceStream("$$")` suggest embedded resource names
* `new Uri("$$")` [PackUri](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/app-development/pack-uris-in-wpf?view=netframeworkdesktop-4.8#using-pack-uris-in-code) completion for WPF.

There are a lot of parameters, with types beyond strings, where argument values can be suggested:

* `System.Enum.GetValues($$)` suggest all enums in scope: `typeof(EnumInScope)`
* Parameter of type `CancelationToken` suggest `CancellationToken.None`
* Parameter of type  `Task` suggest `Task.CompletedTask`
* Parameter of type  `Task<T>` suggest `Task.FromResult()`
* Parameter of type  `ImmutableArray<T>` suggest `ImmutableArray<T>.Empty`
* Parameter of type  `IEnumerable<T>` suggest `Enumerable.Empty<T>()`
* Parameter of type  `EventArgs` suggest `EventArgs.Empty`
* Parameter of type  `StringComparer` (or related interfaces), suggest `StringComparer.Ordinal` and the like
* For any parameter suggest `new()` if the parameter type has a parameterless constructor
* For number parameters, suggest `Math.??` methods with the appropriate return type.

## What should the provider look like

I like the idea of the `ArgumentProvider` to pass an `ArgumentContext` to an abstract method that all providers need to implement (`ArgumentProvider` can't be used as a base class here because it serves a different purpose).

I would create a base class (e.g. `ArgumentValuesCompletionProviderBase`) that would be triggered, whenever the cursor is in an argument expression position. This base class would have a `abstract ProvideCompletionsAsync(ArgumentContext context)` method. `ArgumentContext` could be derived from `CompletionContext` or could embed `CompletionContext`. It would also contain the `IParameterSymbol` and some other useful information about the argument context.

A derived provider like a `abstract StringArgumentValuesCompletionProvider` could be used as base class for `Environment.GetEnvironmentVariable("$$")`, `System.Type.GetType("$$")` and so on (`[InternalsVisibleTo("$$")]` is probably out of scope because attribute arguments are different from method arguments).

Another derived provider could be `abstract TypeBasedArgumentValuesCompletionProviderBase`, which could serve as a base class for all the parameter types with static factory methods or static default properties (`CancellationToken.None`, `Task.FromResult()`, etc.).

@sharwell and @CyrusNajmabadi What do you think about the proposal?

**Comment by sharwell** [comment]
The proposal seems like an interesting place to start. Note that static properties (e.g. `CancellationToken.None` and `ImmutableArray<int>.Empty`) are already implemented in completion (#52163). Arguments are just one of the locations where they work.

**Comment by MaStr11** [comment]
I wasn't aware of #52163, but it solves 90% of the use cases I had in mind. It is also unclear, whether Roslyn should provide specialized suggestions for argument values. It is probably better to allow library authors to provide such suggestions, like they can provide diagnostics with analyzers (A nice use case are the _matchers_ in FakeItEasy https://fakeiteasy.readthedocs.io/en/stable/argument-constraints/#other-matchers A custom provider could suggest `A<string>.Ignore` in a `A.CallTo` context).

String arguments are different, though. @CyrusNajmabadi created the _EmbeddedLanguageCompletionProvider_ for such cases, and I'm not sure whether this one is extendable by library authors.

Are there any plans to open up Roslyn for library authors to extend completion in any of these places. If yes, suggestions for `Environnement.GetEnvironmentVariable()` should be based on that infrastructure. If there are no such plans, I would like to start with the `Environnement.GetEnvironmentVariable()` provider. @CyrusNajmabadi  Such a provider, should be based on `EmbeddedLanguageCompletionProvider`, right?

**Comment by CyrusNajmabadi** [comment]
Closing out as this could be handled by an externla completoin provider.  We are unlikely to add support for it ourselves.
