### ISSUE TITLE
Add option to stop Ctrl Click from checking references on hovering

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#55590]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Add-option-to-stop-Ctrl-Click-from-check/1497118)._

---
Currently when hovering with Ctrl pressed, VS will perform a check on references. After a medium-to-long session, even with a small-size project, the check will become quite slow, which is quite annoying to use. My suggestion is to add an option to disable that check. Hovering with Ctrl pressed will just underline the symbol immediately. Clicking with Ctrl pressed will just work as simply pressing F12. As a fan of Ctrl-Clicking, I will thank you so much for that option, and I don't feel any problem with an error dialog if it's impossible to find the definition.

---
#### Feedback Bot on 8/8/2021, 10:57 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by sharwell** [comment]
This feature is controlled by the following option. It can be disabled entirely, or it can be customized to work with a different modifier key.

![image](https://user-images.githubusercontent.com/1408396/133484592-62a823ef-ec23-4566-b109-78f6c6b7a0eb.png)

**Comment by tranconguoc** [comment]
The issue is about the performance, not about turning the feature off entirely. I have an impression the feature performs a check on references before underlining the symbols, and if that's true, I ask for the ability to turn it off, for a faster responsiveness.
On my machine (i7 8750H), if I point to a symbol, then press ctrl, it is quite fast, but sometimes there is still an 1s delay before the symbol is underlined. However if I hold ctrl then move pointer between symbols, sometimes it takes even 3s to underline symbols, which is completely unacceptable.
I want it to be fast in either cases, just like Visual Studio Code. Symbols are underlined nearly immediately. So smooth.
