### ISSUE TITLE
Type inference fails in lambda in incomplete object initializer

### ISSUE THREAD

**Issue by SLaks** [dotnet/roslyn#557]
Source: (note trailing comma)

```C#
var x = new {
	X = "".Select(c => c.
	Y = 0,
};
```

IntelliSense will not show any members for `c.`.

**Comment by Pilchie** [comment]
This issue is also happens in VS 2013.  Moving to the compiler, as we just ask them to bind c in this location, and it fails with the additional comma.

**Comment by bmay2** [comment]
It looks like "Y = 0" is being included as the end of a SimpleAssignmentExpression for c when it should be its own AnonymousObjectMemberDeclarator.

I'd like to continue with this, but I'm a little overwhelmed and not sure how or where to proceed. I've stepped through the CompilationWithAnalyzers and other Diagnostics, but that doesn't seem right. Any recommendations for background reading or other advice?

**Comment by diryboy** [comment]
This and #5498 both involves bad syntax trees, but when you look at the case I hit on #7520, it's a pretty clean syntax tree, and still fails to bind.

Interestingly, if the result type(type of the identifier left to the `=`) is given, rather than `var`, or in this case undetermined, the parameter type can be inferred.

So, instead looking at parser error recovery, I would place the bet on the binder,  `src\Compilers\CSharp\Portable\Binder\Binder_Lambda.cs` could be the place.

**Comment by diryboy** [comment]
OK, in line 2875 of `Binder_Expressions.cs`, you want to implement the `if (hasErrors)`. You may look into line 509 of `src\Compilers\CSharp\Portable\BoundTree\UnboundLambda.cs`: `public BoundLambda BindForErrorRecovery()`
