### ISSUE TITLE
Internal modifier added to partial classes breaks new project creation for WinForms, WebTools and anything using partial classes in their templates

### ISSUE THREAD

**Issue by merriemcgaw** [dotnet/roslyn#55703]
17.0.0 Preview 4.0 [31611.372.main]

**Steps to Reproduce**:

In latest internal VS builds, create a new WinForms C# project. Core, .NET 5+ or .NET Framework
Build the project

**Expected Behavior**:
Builds and runs as expected

**Actual Behavior**:
![MicrosoftTeams-image](https://user-images.githubusercontent.com/20996271/129956915-f2305a69-5d09-4a6a-93d4-d32838cdc8f7.png)

**Additional Notes**
The work done in #51935 and #55463 are likely culprits.
This is critically blocking dogfooding for several teams. 
Can we get an update on timelines when we can expect fixes?
/cc: @Youssef1313 , @sharwell, @davidwengier , @jinujoseph , @Pilchie

**Comment by CyrusNajmabadi** [comment]
Yup.  Looks like this would be an issue.  we'll need to do a semantic check here.

**Comment by DustinCampbell** [comment]
Yup 😄

**Comment by DustinCampbell** [comment]
I'm wondering if a semantic check is even possible with the current VS editor factory architecture. I believe that `FormatDocumentCreatedFromTemplate` is called for each template item as they are added to the project. If that's the case, a semantic check wouldn't be reliable because the template files won't all have been added yet.

**Comment by davidwengier** [comment]
If it's not possible to fix in Roslyn we could just change the template to include the `public` modifier on the designer file ¯\\\_(ツ)_/¯

**Comment by DustinCampbell** [comment]
I suppose, though we'd be introducing a known bug into the product that could break any template that worked just fine before, including customer templates. Partial classes are pretty standard for code generation scenarios, so I'm pretty certain this will be found outside of our own templates. Since it's already a bad breaking change, I would prefer removing this feature ASAP so that customers can create new projects that build. Then, let's figure out a good solution that isn't prone to the order in which VS adds template files from a project. Perhaps a new notification is needed from the shell to know when a project template has been added? Or, maybe that notification exists?

**Comment by davidwengier** [comment]
If we can't use semantics, and looking at the code I don't think we'll be able to reliably, if at all, I think we'll just no-op the accessibility modifier work if there is a `partial` modifier.

**Comment by DustinCampbell** [comment]
That's also a possibility, though it'd be unfortunate. Note that VB does not require a `Partial` modifier on all parts.

**Comment by davidwengier** [comment]
Good to know. The accessibility modifer operation doesn't have a VB implementation at the moment, so we lucked out there, but I'll leave a comment in the C# implementation as a warning for future explorers.

**Comment by Youssef1313** [comment]
Why the other partial just don't remove the accessibility there (on WinForms side)?

**Comment by DustinCampbell** [comment]
> Why the other partial just don't remove the accessibility there (on WinForms side)?

Sorry @Youssef1313, I didn't quite understand the question. Nothing happens on the WinForms side in this scenario.

**Comment by davidwengier** [comment]
I think Youssef meant removing the `public` modifier from `Form1.cs`, but this has the same problems as adding one to `Form1.Designer.cs`.

I've confirmed we don't have semantic information here (we don't even have a project) so will have to just use the syntactic check. It's not ideal but it beats disabling the operation altogether.

As a humourous aside, this issue doesn't repro in the latest VS builds because its being blocked by a different bug in our options handling 🤦‍♂️

**Comment by Youssef1313** [comment]
@DustinCampbell I think I misunderstood what's going on. I was thinking that the designer.cs (auto generated) has an explicit modifier, but apparently it doesn't, which is correct (and which was my suggestion 😄 )

I don't have access to the internal VS builds, but my best guess is that `.Form1.Designer.cs` gets updated. My proposed fix won't be ignoring partial, but reuse [`IsGeneratedCode`](https://github.com/dotnet/roslyn/blob/main/src/Compilers/Core/Portable/InternalUtilities/GeneratedCodeUtilities.cs#L55) and don't touch it (whether it's partial or not - doesn't matter)

**Comment by DustinCampbell** [comment]
Sorry, I added an edit [above](https://github.com/dotnet/roslyn/issues/55703#issuecomment-901456585) that explains the situation clearly. Note that this is _not_ just a WinForms problem, so I wouldn't focus on that. It also occurs in some of the Web templates. Essentially, it's a problem in any template that uses partial types, including customer-authored templates.

**Comment by DustinCampbell** [comment]
> I think Youssef meant removing the `public` modifier from `Form1.cs`, but this has the same problems as adding one to `Form1.Designer.cs`.

Unfortunately, that's is really a non-starter. The feature should work with existing templates.

> I've confirmed we don't have semantic information here (we don't even have a project) so will have to just use the syntactic check

Ah, yes. I remember that now. @jasonmalinowski and I looked at whether this many years ago and were surprised that `IVsEditorFactoryNotifiy` was so... unhelpful.

> As a humourous aside, this issue doesn't repro in the latest VS builds because its being blocked by a different bug in our options handling.

:smile:

**Comment by davidwengier** [comment]
> My proposed fix won't be ignoring partial, but reuse IsGeneratedCode and don't touch it (whether it's partial or not - doesn't matter)

That would work in this case, but the fact that it happens to be a designer file that is missing the modifier in this template is just a coincidence. It would be trivial to break an `IsGeneratedCode` check here, simply by hardcoding a modifier on `Form1.Designer.cs` and removing it on `Form1.cs` in the template.

**Comment by Youssef1313** [comment]
I see. Ignoring partial for now is probably the best and fastest, probably consider modifying the analyzer to only report a diagnostic if *all* partials doesn't have a modifier 😄

**Comment by DustinCampbell** [comment]
FWIW, I'd still be interested in learning whether there's another hook in VS we could use to determine when we should format newly added files. Clearly, `IVsEditorFactoryNotify` isn't good enough. If there isn't one, I think we should push to get one so a complete experience can be enabled. Just my 2 cents.

**Comment by davidwengier** [comment]
> probably consider modifying the analyzer to only report a diagnostic if _all_ partials doesn't have a modifier

The analyzer is fine, because it uses the existing accessibility if there is one. This is only an issue in the new file handling because at the point it tries to determine existing accessibility, it can't see everything.

**Comment by dibarbet** [comment]
Related integration test disabled in https://github.com/dotnet/roslyn/pull/55681
To be re-enabled once fixed
