### ISSUE TITLE
`JsonSourceGenerator` is Executing in Both `ServiceHub.RoslynCodeAnalysisService.exe` and `devenv.exe`

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#55723]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/JsonSourceGenerator-is-Executing-in-Bo/1507088)._

---
[severity:It bothers me. A fix would be nice]
Please see the attached recording.

I noticed that pressing a few keys in my text editor caused the CPU to attain high usage for about 15 seconds.  This seems high to me, but it is an improvement over what I have been dealing with in the past year.

Baby steps. :)

What I am reporting here is that I profiled both `ServiceHub.RoslynCodeAnalysisService.exe` and `devenv.exe` using dotTrace and both of them appear to be running `JsonSourceGenerator`, which seems redundant.  Shouldn't it only be running in one process?

Here is `devenv.exe`:

! [](https://i.imgur.com/zkFTJtr.png)

Here is `ServiceHub.RoslynCodeAnalysisService.exe`:
! [](https://i.imgur.com/2C1lhOW.png)

Expected: I know we are all about source generators these days, but one pass/process should be enough. 

---
#### Feedback Bot on 8/19/2021, 00:44 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
The observable overhead has been largely addressed by work to make these source generators incremental, in combination with efficiency improvements to the generator driver itself. However, it would still be nice to always run generators OOP when enabled, since it would reduce the total overhead used by the generator driver to track incremental state.

**Comment by gfraiteur** [comment]
We are hitting the same issue. We have a very memory- and CPU-intensive metaprogramming framework (https://blog.postsharp.net/post/announcing-caravela-preview-3.html) that integrates with source generators, analyzers and suppressors. 

Currently, the same computations must be processed twice, with double costs of memory and CPU.

The performance improvements of incremental generators do not address the problem in a relevant way for us because we have our own implementation of caching and incremental processing - it does not address the problem of double CPU and memory cost.

The current situation is not acceptable for us because of the scale of the problem we are solving, so we will be looking for a solution. 

As I understand, the in-process implementation is only used to feed syntax completion (Intellisense). We will probably have to implement our own remote call, so that our in-process source generator would do a remote call to the OOP implementation to synchronize the generated syntax trees. However this approach cause inconsistencies. We hope that, for the only sake of syntax completion, inconsistencies will be small enough and will not have any important effect on the developer experience. 

For a large-scale use of source generators, as we are doing, the solution would need to be built in Visual Studio, just as it is for other language services.

**Comment by CyrusNajmabadi** [comment]
> As I understand, the in-process implementation is only used to feed syntax completion (Intellisense). 

This is not the case. The in process implementation feeds any feature that runs in proc (many of them). Furthermore, it also feeds the in memory representation used by every vs extension that talks to roslyn. 

It is Paramount that this new fast and efficient.

**Comment by CyrusNajmabadi** [comment]
> However this approach cause inconsistencies.

Why does this cause inconsistencies?

**Comment by gfraiteur** [comment]
> This is not the case.

Thank you for clarification.

> Why does this cause inconsistencies?

My guess it that, If I implement a custom synchronization mechanism that pulls generated trees from the analyzer process to the IDE process, there will be inconsistencies because the latest result from the analyzer process will be possibly computed from a different compilation version than the one requested by the IDE process. 

I hope that these inconsistencies would be relatively harmless, and that we would be able to mitigate them using fake additional files that we actually use as a signaling mechanism between processes.

However it would be better if the synchronization service would be provided by Roslyn/VS. It seems more efficient to execute all source generators in the analyzer process and then synchronize, rather than to duplicate all processing.

> It is Paramount that this new fast and efficient.

We have implemented a workaround feature where the user can disable real-time for source generators in case of performance issue. When this real-time source generators are disabled, the files are generated at compile time, so the design-time experience remains acceptable.

**Comment by gfraiteur** [comment]
UPDATE: The examples in the article https://blog.postsharp.net/post/announcing-caravela-preview-3.html were broken when I posted my previous message. It's now fixed. For an example that integrates using source generators, see https://try.metalama.net/#tostring.

**Comment by jasonmalinowski** [comment]
So indeed this bug is still tracking us trying to reuse the OOP computation for in-proc as well, but the timeline for that isn't exactly clear. And our usual assumption is that if generators are fast, running "fast" twice shouldn't be slow.

@gfraiteur I'd encourage you to open a new bug and help us understand this:

> The performance improvements of incremental generators do not address the problem in a relevant way for us because we have our own implementation of caching and incremental processing - it does not address the problem of double CPU and memory cost.

If there's a feature gap in our incremental support we'd love to understand more and see if we can close that gap. Also, it'd help if we can understand what parts of your generator impact intellisense vs. the runtime code, since our incremental APIs are working to support targeted things to speed stuff up to.

**Comment by sharwell** [comment]
> 
The performance improvements of incremental generators do not address the problem in a relevant way for us because we have our own implementation of caching and incremental processing

@gfraiteur Note that it will not be possible to avoid _severe_ performance degradation if you use a `SyntaxReceiver` but do not update to the new incremental source generator APIs. With careful work, it is difficult but possible to approach the performance of incremental source generators provided you do not use a `SyntaxReceiver`.

**Comment by gfraiteur** [comment]
We are not using a SyntaxReceiver. We are diffing the compilations at the syntax level so we can know when there are potential changes to symbols (we don't care about method bodies at design time).

Currently, we are not using the new incremental APIs. I assume we will update to the new API but still do most of the caching ourselves.  The reason is that we are using a single pipeline to produce diagnostics, suppressions, generated code, and code fixes (also code overrides/interceptions but this is not relevant to the design-time experience). 

The last (but quite outdated) description of our integration with Roslyn is [here](https://sharpcrafters.sharepoint.com/:w:/g/EQUtNSDiuXhJnRdUPVyVGb0BakkbtcE1tUPFKJoDZPL1Qg?e=C4O2ls). 

I'm in e-mail contact with Mads Torgesen, Jared Parsons and Chris Sienkiewicz  regarding this project. I will contact them back after our next release. I will file a feature request after I understand better the limitations of the new API..

>  if generators are fast, running "fast" twice shouldn't be slow.

This is true for CPU performance, but not for memory consumption and caching. It is quite difficult to understand the performance design of Roslyn, but I assume that, in the _analyzer _process, the compilations are more symbol-resolved than they are in the IDE process. Keeping most symbol-based computations in the analyzer process seems to make sense to me because  I would could reuse already-cached semantic models and symbols. So, what is fast in the analyzer process does not need to be fast in the IDE process.

**Comment by sharwell** [comment]
Our design is heavily optimized for the scenario where the public APIs are being used.

> ... We are diffing the compilations at the syntax level ...

This is (likely) explicitly not a supported scenario; if your source generator is looking at syntax trees in the compilation but not using a `SyntaxReceiver` or the incremental generator APIs, the output of the compilation process as a whole is undefined.

**Comment by gfraiteur** [comment]
> This is (likely) explicitly not a supported scenario; 

I have read the disclaimer back then.

We are not using source generators at compile time (we have our own fork that supports transformation) so I'm not concerned about this scenario,

For the rest, we will see. Our integration with source integration is just a few percent of our code base so it is not a problem to change it if it proved wrong.

Generally speaking, looking back at the 15 years of experience we have implementing and supporting aspect-oriented for .NET, I don't see a single case where a source generator would need _syntax _at design time. All cases only need _symbols_. Syntax is only needed at compile time. An event channel that would notify of added/removed/changed symbols would be a better approach for the scenarios I have in mind.

**Comment by CyrusNajmabadi** [comment]
This generator was heavily fixed up to be very low overhead.  Closing out.
