### ISSUE TITLE
Inheritance margin: Show tooltip of fully qualified name

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#55790]
I can't easily navigate to the correct implementation I want when the type names are the same. For most cases, showing the fully qualified name directly will be very noisy, so I think a tooltip that shows when hovering makes sense.

![image](https://user-images.githubusercontent.com/31348972/130330102-1022810f-713c-4883-9039-f411e2780446.png)

**Comment by CyrusNajmabadi** [comment]
i also thin kit's appropriate that if display names are otherwise identical, more information is added to disambiguate them.  This may be something like adding ` (project name)` as a suffix, or adding a `(in somenamespace)` for the part of hte namespace that is unique.  

Compiler does this when they would report something bad like `"Foo" can't be converted to "Foo"`.  We should try something similar.

**Comment by CyrusNajmabadi** [comment]
Note: i'm also fine with this being a tooltip as it would likely naturally fall out from a descriptive quick-info display.  However, that feels like a bandaid when the core issue is allowing dupe display-texts in the first place.

**Comment by Youssef1313** [comment]
Fixed by https://github.com/dotnet/roslyn/pull/60992.
