### ISSUE TITLE
OpenSolutionAsync doesn't get include all Facade references needed to compile a project

### ISSUE THREAD

**Issue by garbervetsky** [dotnet/roslyn#560]
We try to get a compilation from a project loaded using OpenSolutionAsync, it fails reporting that some references are missing.

            var ws = MSBuildWorkspace.Create();
            var solution = ws.OpenSolutionAsync(path).Result;

Example: 

            string pathToDll = @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\";
            var metadataReferences = new string[] { 
                    "System.Runtime.dll", 
                    "System.Threading.Tasks.dll", 
                    "System.Reflection.dll",
                    "System.Text.Encoding.dll"}.Select(s => MetadataReference.CreateFromFile(pathToDll + s));
            solution = solution.AddMetadataReferences(solution.ProjectIds.First(), metadataReferences);

**Comment by garbervetsky** [comment]
I continue to with the description (sorry). 
I need to manually add the references mentioned in the examples in other to get a compilation without errors.

**Comment by khellang** [comment]
Shot in the dark: Isn't there something called [`MSBuildWorkspace.LoadMetadataForReferencedProjects`](http://source.roslyn.codeplex.com/#Microsoft.CodeAnalysis.Workspaces.Desktop/Workspace/MSBuild/MSBuildWorkspace.cs,515428588aa4c56a)? What happens if you set that to `true`?

**Comment by garbervetsky** [comment]
It didn't work.

Some of the references are working in with OpenSolutionAsync but I need it
to add some references manually as I shown in the example.

Thanks!

**Comment by khellang** [comment]
What errors do you get? Any of these? http://support2.microsoft.com/kb/2971005. Does the project build fine with VS?

**Comment by garbervetsky** [comment]
Yes. I build pertectly with VS.
The project has 30 already references when I loaded. When I add the
references y mentioned in the example I compile in Roslyn too.

**Comment by jasonmalinowski** [comment]
I suspect the problem here is we're not invoking MSBuild correctly to get façade references added. There really isn't a workaround here.

**Comment by scottcarr** [comment]
Is there any update on this?  It's a pretty big hurdle for my tool because I want to be able to open multiple complicated projects.  If, for example, I try to open all the projects in RoslynLight.sln, some are missing references and others aren't, so I can't just blindly add references like in the OP (or I get duplicate references).

It seems to me that for a given solution, there is no way to reliably open all the projects and get the diagnostics / semantic model using OpenSolutionAsync.  Am I missing something or mistaken?

**Comment by jasonmalinowski** [comment]
No, we haven't fixed the bug yet. (Sorry.) Why does the original workaround not work for you? Since it's updating the existing solution in-memory, once you've done the workaround you can use it as any other solution you got from OpenSolutionAsync.

**Comment by scottcarr** [comment]
I assume that you mean the original workaround is to add the missing references manually by AddMetaDataReferences.

It doesn't work for me because the idea for the tool I'm working on is: you give it the path to any arbitrary solution and it just does its thing (a source-to-source translation of sorts) to every project in that solution.  For some arbitrary solution/project I don't know what references Roslyn will miss, so I don't know which references to add.  It's not always "System.Runtime.dll" that is missing.  It could be any library.

I could theoretically parse the diagnostics and look for the missing references, or optimistically add a bunch of references and then parse the diagnostics for duplicate references but I was hoping to avoid that.

**Comment by jasonmalinowski** [comment]
The bug being tracked here is it will only miss Façade references for portable libraries. If you're seeing cases where other references are missing, then this isn't the bug you're looking for.

**Comment by scottcarr** [comment]
So should I create another issue or ...?

I made an SO question: http://stackoverflow.com/questions/29416135/how-can-i-resolve-all-references-with-roslyns-opensolutionasync

**Comment by jasonmalinowski** [comment]
@scottcar, oh, sorry, I was thinking you were describing a different issue. Guess it was the same, sorry for the confusion. :disappointed: I'll comment on the StackOverflow question shortly.

**Comment by Pilchie** [comment]
After investigating #1373, I think a workaround would be to use `            new MSBuildWorkspace.Create(new Dictionary<string, string> { { "CheckForSystemRuntimeDependency", "true" } });
`

**Comment by JoshVarty** [comment]
@Pilchie's solution works for me. I believe a number of people are going to keep running into this problem.

What do you guys think about making this property default to true for `MSBuildWorkspace`? I imagine the people who want to set it to false will at least already know it exists.

**Comment by Pilchie** [comment]
I'm trying to make this property stop existing and make msbuild do the right thing automatically in more places.  If that falls through, then yes, we should make this the default in `MSBuildWorkspace`.

**Comment by JoshVarty** [comment]
:+1:

**Comment by jasonmalinowski** [comment]
Yeah, @Pilchie's suggestion is most emphatically a workaround.

**Comment by OmerRaviv** [comment]
@Pilchie While you're working on this in the context of MSBuild/MSBuildWorkspace, I think it may be worthwhile to consider making Roslyn automatically handle adding references to the facade assemblies when using the *Compilation API* as well. I was initially unaware of facade assemblies when I reported #855, and since I'm using the Compilation API and not the Workspace API, I had to do a lot of work in my own project to facilitate this. I foresee this being a stumbling block for other newbie consumers of the Compilation API going forward.

**Comment by Pilchie** [comment]
@OmerRaviv: The compilation API doesn't add *any* references, and we don't really want it to.  Doing so would mean it would have to have logic to look for installed references, which we'd really like to avoid - we want to have completely app-local compilers for CoreCLR.  @jaredpar is already struggling with csc's logic to auto-reference mscorlib.

The compiler APIs were specifically designed to require you to be explicit about what references get passed, so that you can make sure you get the right ones if targeting a framework other than the one you are currently executing against.

**Comment by OmerRaviv** [comment]
@Pilchie Thanks for explaining your rationale, that makes a lot of sense.

**Comment by Pilchie** [comment]
This has been fixed by a change to MSBuild targets and the `ResolveAssemblyReferences` task.  Note that the fix is NOT part of VS2015 RC, so you'll need to continue to use the workaround until the next release.

**Comment by Pilchie** [comment]
Another facade related issue.

**Comment by dpoeschl** [comment]
Verified the MSBuild workspace repro via https://github.com/dotnet/roslyn/issues/1894
