### ISSUE TITLE
`Make container 'async'` try to insert an `async` at strange place

### ISSUE THREAD

**Issue by yyjdelete** [dotnet/roslyn#56006]
**Version Used**: 
VS2022 17.0.0 Preview 3.1

**Steps to Reproduce**:

![GIF1](https://user-images.githubusercontent.com/1819074/131354515-851dca8f-7ad9-4acc-a45a-dc29e5877ec5.gif)

**Expected Behavior**:
It should make the parent method async.

**Actual Behavior**:
It just insert an `async` before `await`.

**Comment by Youssef1313** [comment]
The root cause here is the compiler is producing a local function syntax, so we used that as the container where we put `async`.

@CyrusNajmabadi I'm not really sure how we can handle that. Any ideas?

**Comment by Youssef1313** [comment]
I think we should make sure the local function declaration has open brace token. If it doesn't, then check the next possible container.

**Comment by Youssef1313** [comment]
I also think we should introduce an option to enable/disable the feature in case other bugs like this appear.

**Comment by CyrusNajmabadi** [comment]
> I think we should make sure the local function declaration has open brace token. 

that, or a `=>`.

**Comment by CyrusNajmabadi** [comment]
> I also think we should introduce an option to enable/disable the feature in case other bugs like this appear.

I don't think we need to go to that point yet.  I want an option not to get around bugs, but because there's a genuine use case where you don't want this.  I'm not there yet.  In c#, `await` can only be in an `async` context.  So i think we should be trying to add this as much as is possible (as long as we feel the transformation is safe).
