### ISSUE TITLE
Add record struct classifications for EditorFeatures.Cocoa (VSMac)

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#56083]
Looks like we need to add all recent classifications to the VSMac side as well:
https://github.com/dotnet/roslyn/blob/main/src/EditorFeatures/Core.Cocoa/RoslynClassificationFormatDefinitions.cs

We're not seeing references to record structs classified properly. What other recent classifications are we missing?

![image](https://user-images.githubusercontent.com/679326/131735770-b1cffbe9-98e1-47ee-a0cb-51abc0d0ea4b.png)

**Comment by CyrusNajmabadi** [comment]
Why are there separate classification definitions here?

**Comment by DavidKarlas** [comment]
ClassificationTypeNames.ConstantName
ClassificationTypeNames.EnumMemberName
ClassificationTypeNames.EventName
ClassificationTypeNames.FieldName
ClassificationTypeNames.LabelName
ClassificationTypeNames.NamespaceName
ClassificationTypeNames.PropertyName
ClassificationTypeNames.ReassignedVariable
ClassificationTypeNames.RecordClassName
ClassificationTypeNames.RecordStructName
ClassificationTypeNames.StaticSymbol

Reason they are different because this code is referring to `System.Windows.Media.Color` aka. WPF so its per platform specific code. Fact that we also have `using System.Windows.Media;` in Cocoa world is ugly hack that you can ignore in this case :)

**Comment by davidwengier** [comment]
LSP will save us all!!



... right? 😛

**Comment by KirillOsenkov** [comment]
Wondering if we can use a linked file to share the source

**Comment by davidwengier** [comment]
At the very least, if I can't do that, I'll write a test that fails when the WPF side is updated if the Cocoa side doesn't match.

**Comment by davidwengier** [comment]
Linked file for the win:
<img width="260" alt="Screen Shot 2021-09-02 at 8 41 58 pm" src="https://user-images.githubusercontent.com/754264/131830091-3f841db9-0997-4fcb-a1b4-5a9a886f3e13.png">
