### ISSUE TITLE
CS0266 suggests invalid code fix

### ISSUE THREAD

**Issue by meziantou** [dotnet/roslyn#56141]
**Version Used**: 4.0.0-3.21403.23 (d51d1a73)

**Steps to Reproduce**:

````c#
int a = 0;
double b = 0;
a += b; // CS0266 Cannot implicitly convert type 'double' to 'int'. An explicit conversion exists (are you missing a cast?)
````

![image](https://user-images.githubusercontent.com/509220/131922927-846f441a-e8f6-4538-882d-8c18819dafc1.png)

**Expected Behavior**:

The code fix should generate:

````
int a = 0;
double b = 0;
a += (int)b;
````

**Actual Behavior**:

````
int a = 0;
double b = 0;
(void)(a += b);
````

**Comment by Youssef1313** [comment]
Is it more appropriate if the compiler reported the error only on "b" instead of the whole expression?

The span of CS0266 (`Cannot implicitly convert type 'TypeX' to 'TypeY') is mostly always on an expression of `TypeX'. The case of compound assignment seems different from the compiler-side.

**Comment by Youssef1313** [comment]
I think we need to update `spanNode` in this method when it's a compound assignment.

https://github.com/dotnet/roslyn/blob/534c0e8d04e58044c66ef4f66eeafd255a18749d/src/Features/CSharp/Portable/CodeFixes/AddExplicitCast/AddExplicitCastCodeFixProvider.cs#L61-L63

**Comment by RikkiGibson** [comment]
https://github.com/dotnet/csharpstandard/blob/draft-v6/standard/expressions.md#11183-compound-assignment for reference.

I speculate that what the compiler's doing internally is trying to implicitly convert `a + b` to `int` here, but it can't. i.e. the "fix" that preserves semantics here is `a = (int)(a + b);`.

I think it's reasonable for the IDE to approximate those semantics by saying: hey, instead of converting `a` to `double` and using `double operator +(double, double)`, we can cast `b` to `int` and use `int operator +(int, int)` .

Let's make sure to devise a test where adding a cast on the RHS *doesn't* work. For example: [SharpLab](https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLQAcoKgWzczAOwBoATEAagB8ABAZgAIaAmBgYQFgAoAb24YFNGNAIwA2BgBEGAe3QRsMGQgYUAFGwYAbCGBjEpDBAEsA5gAsYASgYBeAHxGzlgNz9B9JuIYQAHui1jAGNjGFl5RWV2NWlSGwcGQggAd2irNy4AX25uTxZDHgZsrlzhVlEAdm4+LkEhLwkaABYGAFkNBiCDWKt3ARq6uqC7Bg0rNWGKBjiXBgB6OdkAaz7Bydtp2YWfBAQotgBlAAZmMTEQdihCQhkw4xwA4NCtAE9OmUIANwUwmBf5BgAckkgIYSiBbEBADoGABBQg+fyBEJhIIfb4IZDGD6I4zIGDIUZYCAMF4yOAMHB4rGEUwMKCdKD4gD8vVqgmKxSAA==)

```cs
public class C
{
    public static D operator +(C left, D right) => right;
    public static explicit operator C(D d) => new C();
}

public class D { }

public class Program
{
    public static void M(C c, D d)
    {
        c = (C)(c + d); // ok
        c += d; // error CS0266: Cannot implicitly convert type 'D' to 'C'. An explicit conversion exists (are you missing a cast?)
    }
}
```

It's up to IDE team to decide what the fix behavior should be. cc @CyrusNajmabadi
