### ISSUE TITLE
Try catch with list of exception in C#

### ISSUE THREAD

**Issue by taschna** [dotnet/roslyn#5621]
It would be nice to be able to group exceptions which should be catched in a similar way, so that instead of writing:
```
    try
    {
        writable = new WriteableBitmap(bitmapSource);
    }
    catch (OverflowException)
    {
        return null;
    }
    catch (FileFormatException)
    {
        return null;
    }
```
one could write something like this:
```
    try
    {
        writable = new WriteableBitmap(bitmapSource);
    }
    catch (OverflowException, FileFormatException)
    {
        return null;
    }
```

**Comment by tmat** [comment]
```C#
 try
    {
        writable = new WriteableBitmap(bitmapSource);
    }
    catch Exception e) when (e is OverflowException || e is FileFormatException)
    {
        return null;
    }
```

**Comment by AlexanderTaeschner** [comment]
Nice. The documentation in VS2015 does not mention this new possibility at all! Even Google does not find any Microsoft site mentioning this new feature.

**Comment by svick** [comment]
@AlexanderTaeschner It's listed in [What's New for Visual C#](https://msdn.microsoft.com/en-us/library/hh156499.aspx) (search for "exception filters"), and [the linked article](https://msdn.microsoft.com/en-us/library/0yd65esw.aspx) contains few paragraphs about it. Although the example is incredibly bad: it uses the wrong keyword (`if` instead of `when`) and also contains two other errors on the same line (`Catch` instead of `catch` and smart quotes instead of `"`).

**Comment by gafter** [comment]
@taschna Does the new feature in C# 6 satisfy your need?

**Comment by taschna** [comment]
@gafter Yes, I think so. It is not as compact as my proposal, but it's okay.
