### ISSUE TITLE
Add API to clone document/project from one solution snapshot to another

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#56253]
## Background and Motivation

EnC needs to be able to clone document and project from one snapshot to another. Currently, we need to manually construct DocumentInfo/ProjectInfo and then call existing API AddDocument/AddProject.

## Proposed API

```
Solution Solution.AddDocument(Document)
Solution Solution.AddAdditionalDocument(AdditionalDocument)
Solution Solution.AddAnalyzerConfigDocument(AnalyzerConfigDocument)
Solution Solution.AddProject(Project)
```

These APIs would take a document/project that is not present in the current solution and add a new document/project that replicates the given one. The IDs of the added and original document/project would be the same. Documents contained in the specified project would also be mirrored to the new project (preserving their ID). The project references (if any) of the added would be recreated (this might require transitively adding more projects).

**Comment by jasonmalinowski** [comment]
> The project references (if any) of the added would be recreated (this might require transitively adding more projects).

So one detail to work out is what you want to do if the referenced project isn't there. _Technically_ the workspace API allows you via some APIs to create project references to projects that aren't there. This obscure behavior is why we have [Project.ProjectReferences](https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.project.projectreferences) and [Project.AllProjectReferences](https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.project.allprojectreferences). I could imagine that behavior might be useful here, since you can always clone the project in with all the references, and if you haven't cloned a dependency the reference won't work until the dependency is cloned. It would mean you don't have to worry about cloning in a certain order. On the other hand, I could imagine you would find this behavior confusing and repulsive, and want to get rid of it with much fire. I could see it going both ways. :smile:

And to give some background: @tmat and I discussed one alternative for this which was to make APIs to properly convert a Project and Document back to ProjectInfo/DocumentInfo, which you could then add via our existing APIs. I _suspect_ this will be much easier to implement, but also potentially much faster: doing the round trip to Infos and back would mean we'd be reparsing trees and such, whereas these APIs would make it easy to reuse the underlying ProjectState/DocumentStates.

**Comment by jasonmalinowski** [comment]
@tmat were you already working on this?

**Comment by tmat** [comment]
I have not worked on this.

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of movement.  If we need this for a particular release we should give to a dev/milestone for it to be done.
