### ISSUE TITLE
DiagnosticAnalyzer's Initialize method not getting called with VS 2019 upgrade

### ISSUE THREAD

**Issue by abhijitparkhi1983** [dotnet/roslyn#56449]
**Version Used**: 
3.11.0
**Steps to Reproduce**:

1. Created a .NET Standard 2.0 Class Library project referring to Microsoft.CodeAnalysis, Microsoft.CodeAnalysis.Analyzers and Microsoft.CodeAnalysis.CSharp.Analyzers. 
2. Created couple of DiagnosticAnalyzer analyzers overriding Initialize(AnalysisContext context) method and relevant code for analysis.
3. Added reference of this project to a Vsix project based on .NET Framework 4.7.2 and modified the source.extension.vsixmanifest to add Assets "Microsoft.VisualStudio.MefComponent" and "Microsoft.VisualStudio.Analyzer" along with Prerequisite "Visual Studio core editor ([16.0,17.0))" and Install Targets "Microsoft.VisualStudio.Pro ([16.0, 17.0))", "Microsoft.VisualStudio.Community ([16.0, 17.0))" and "Microsoft.VisualStudio.Enterprise([16.0, 17.0))"  

4. I had created this project using Visual Studios 2019 version 16.10.2.  and the analyzers were working all good. The `public override void Initialize(AnalysisContext context)` method was getting called as so does the registered Actions.

5. After upgrading Visual Studios 2019 to version 16.11.0, suddenly the DiagnosticAnalyzer has stopped working. I dont see the calls coming to `public override void Initialize(AnalysisContext context)` to any of the analyzers. There is no exception any where which will help me understanding whats the issue. I dont know where and how to debug this issue.

6. To counter verify, I also downloaded few open source plugins using DiagnosticAnalyzer which i had referred to during building my application.  All those plugins are not working any more as well.

7. I have again tried running my plugin and other same ones on VS 2019 16.10.0 and they seem to be working there. 

 **Expected Behavior**:
With upgrade to Visual Studios 2019 16.11.0 or higher, the  DiagnosticAnalyzer  workflow should work.

**Actual Behavior**:
DiagnosticAnalyzer  workflow is working for Visual Studios 2019 16.10.0 but is not working for Visual Studios 2019 16.11.0 or higher

**Comment by abhijitparkhi1983** [comment]
@shanselman  @AArnott @bratsche @radical  any updates around this issue ? 
One update, i tried using Security Code Scan VS 2019 Plugin on the same version 16.11.0 and its working. So here is some reference or some setting which i am missing in the plugin i am working on.

**Comment by AArnott** [comment]
@abhijitparkhi1983 Please don't @ mention arbitrary people to get traction on an issue. I and at least one other person on your list don't even work on this repo.

**Comment by abhijitparkhi1983** [comment]
Hi @AArnott  sorry for that. When i hit the @, ur name was seen. So I assumed that you are one of the contributors as well. 
Getting traction is not important, resolving this important issue is more important for me.

**Comment by sharwell** [comment]
Diagnostic analyzers are executed by default in a separate process from Visual Studio. Attaching the debugger to ServiceHub.RoslynCodeAnalysisService.exe (or ServiceHub.RoslynCodeAnalysisServiceS.exe, depending on system factors) will allow breakpoints to be set. There are a few other ways to impact this:

* For _all_ analyzer debugging purposes, I recommend writing unit tests for the analyzer and debugging those tests via Test Explorer. The experience will be easier, faster, and simpler than debugging inside Visual Studio, and you'll end up with a nice test suite at the end.
* Unchecking **Tools &rarr; Options... &rarr; Text Editor &rarr; C# &rarr; Advanced &rarr; Use 64-bit process for code analysis** will force the analyzers to run in **devenv.exe** instead of a second process
