### ISSUE TITLE
Override completion includes internal attributes when overriding in a different assembly

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#5646]
We should probably only copy attributes if they are accessible.

**Comment by CyrusNajmabadi** [comment]
Why do we copy attributes at all?  That doesn't make a lot of sense to me.

**Comment by joj** [comment]
I'm running into the same bug in Xamarin.iOS. Attributes used to not be included at all (checked in dev12). I don't think they should be.

**Comment by rolfbjarne** [comment]
For reference this is the bug reported for Xamarin.iOS: https://bugzilla.xamarin.com/show_bug.cgi?id=39779

**Comment by bradumbaugh** [comment]
In a Xamarin.iOS app in `AppDelegate.cs`, if I take the second autocomplete for `override ContinueUserActivity`, I get the below.  `[BlockProxy(typeof(NIDUIApplicationRestorationHandler))]` is a compile error. Removing it resolves the problem.

```csharp
public override bool ContinueUserActivity(UIApplication application, NSUserActivity userActivity, [BlockProxy(typeof(NIDUIApplicationRestorationHandler))] UIApplicationRestorationHandler completionHandler)
{
    return base.ContinueUserActivity(application, userActivity, completionHandler);
}

**Comment by divega** [comment]
This now repros with the attributes the compiler-generated attributes for nullable reference types, since we enabled the feature in the EF Core codebase. 

To repro:

1. Create a new .NET Core 3.0 console app in Visual Studio 16.0.0 Preview 4.0 build
2. Add an EF Core 3.00-preview3 from nuget.org:
   ``` xml
     <ItemGroup>
       <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.0.0-preview3.19153.1" />
     </ItemGroup>
   ```
3. Add using Microsoft.EntityFrameworkCore
4. Create a class that derives from DbContext: 
   ``` cshrap
      public class MyContext: DbContext
      {

      }
   ```
5. Start typing override OnConfiguring and <kbd>Enter</kbd> to auto-complete 

Result:
``` cshrap
        protected override void OnConfiguring([NullableAttribute(1)] DbContextOptionsBuilder optionsBuilder)
        {
            base.OnConfiguring(optionsBuilder);
        }
```

Expected:
`[NullableAttribute(1)]` (which isn't really available and doesn't compile) isn't included in the auto-complete output.
