### ISSUE TITLE
Add fully qualified Using statement

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#56505]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Add-fully-qualified-Using-statement/1523343)._

---
Hi, 

when I add some code and let Visual Studio 2019 to automatically import a missing Using statement (another class defined within my Solution), the Using statement is not fully qualified. 

I would like it to be fully qualified. 

All the best, 

Petr

---
#### Feedback Bot on 9/7/2021, 03:08 AM: 

We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.

**Comment by CyrusNajmabadi** [comment]
We'd need an example of what is happening here.

**Comment by sharwell** [comment]
This is likely a case where the user has specified using directives are placed _inside_ the namespace. In some cases, using directives at this location can have partially-qualified names due to accounting for the containing namespace. These directives would violate [SA1135: Using directives should be qualified](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1135.md).
