### ISSUE TITLE
ISymbol.ToDisplayString does not use fully qualified names for default enum parameter values

### ISSUE THREAD

**Issue by Dimension4** [dotnet/roslyn#56573]
I'm using the `ISymbol.ToDisplayString` method to generate source code from my source generator and it works fine in most cases. I guess this method's purpose is not to generate C# source code but I found it's the most convenient way to generate method signatures. I use my own format to generate the string:

```cs
private static readonly SymbolDisplayFormat FullyQualifiedSymbolFormat = new(
    typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameAndContainingTypesAndNamespaces,
    globalNamespaceStyle: SymbolDisplayGlobalNamespaceStyle.Omitted,
    kindOptions: SymbolDisplayKindOptions.IncludeNamespaceKeyword |
                 SymbolDisplayKindOptions.IncludeTypeKeyword |
                 SymbolDisplayKindOptions.IncludeMemberKeyword,
    genericsOptions: SymbolDisplayGenericsOptions.IncludeTypeParameters |
                     SymbolDisplayGenericsOptions.IncludeTypeConstraints |
                     SymbolDisplayGenericsOptions.IncludeVariance,
    parameterOptions: SymbolDisplayParameterOptions.IncludeName |
                      SymbolDisplayParameterOptions.IncludeType |
                      SymbolDisplayParameterOptions.IncludeDefaultValue |  // <-- this is a little iffy
                      SymbolDisplayParameterOptions.IncludeExtensionThis |
                      SymbolDisplayParameterOptions.IncludeParamsRefOut,
    memberOptions: SymbolDisplayMemberOptions.IncludeType |
                   SymbolDisplayMemberOptions.IncludeModifiers |
                   SymbolDisplayMemberOptions.IncludeAccessibility |
                   SymbolDisplayMemberOptions.IncludeParameters,
    miscellaneousOptions: SymbolDisplayMiscellaneousOptions.UseSpecialTypes |
                          SymbolDisplayMiscellaneousOptions.EscapeKeywordIdentifiers |
                          SymbolDisplayMiscellaneousOptions.RemoveAttributeSuffix |
                          SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier |
                          SymbolDisplayMiscellaneousOptions.AllowDefaultLiteral,
    propertyStyle: SymbolDisplayPropertyStyle.ShowReadWriteDescriptor,
    delegateStyle: SymbolDisplayDelegateStyle.NameAndSignature,
    localOptions: SymbolDisplayLocalOptions.IncludeType |
                  SymbolDisplayLocalOptions.IncludeConstantValue |
                  SymbolDisplayLocalOptions.IncludeRef);
```

The following snippets

```cs
namespace Foo
{
  public enum Foonum
  {
      A,
      B,
      C
  }
  
  public interface IDefaultValueScenario
  {
      void Do(Foonum x = Foonum.B);
  }
}
```

and

```cs
IMethodSymbol symbol = /* method symbol of IDefaultValueScenario.Do */
symbol.ToDisplayString(FullyQualifiedSymbolFormat)
```
produce the string:

```cs
void Do(Foo.Foonum x = B)
```
As you can see the default value is unqualified. Is this intentional or not? I would expect the default value to respect the rules defined via `typeQualificationStyle`.

I'm on .netstandard 2.0 with the following packages
```xml
<PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="3.11.0" />
<PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.3.2" PrivateAssets="all" />
<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="3.11.0" PrivateAssets="all" />
```

**Comment by Youssef1313** [comment]
Are you expecting this due to `SymbolDisplayTypeQualificationStyle.NameAndContainingTypesAndNamespaces`?

I think this option is (as the name implies) for "types" only. I don't think an enum member is considered a type. So we probably need a new option for this?

**Comment by Dimension4** [comment]
@Youssef1313 exactly. But you're right, the type qualification styles might not be the right place here. A new option would be fine for me, maybe something along these lines:
```cs
enum SymbolDisplayEnumValueOptions
{
  Name,
  TypeAndName,
  NamespaceAndTypeAndName
}
```
or perhaps just an additional flag in `SymbolDisplayParameterOptions`?

**Comment by andriipatsula** [comment]
Hello @jaredpar. On Friday, I had a call with @RikkiGibson, and I showed him exectly the same issue we are facing in Roslyn-based GenAPI. It affects the quality of reference package generation badly. Issue on our side: https://github.com/dotnet/arcade/issues/10270

cc @tkapin

**Comment by CyrusNajmabadi** [comment]
> I'm using the ISymbol.ToDisplayString method to generate source code from my source generator 

This is not a supported use case for this API. ToDisplayString is for displaying symbols for easy reading. It's never been a goal to use it to generate compilable code.

**Comment by 333fred** [comment]
Reopening, as the main issue is a new api request for a symbol display option.

**Comment by CyrusNajmabadi** [comment]
I think an API request should happen for that then. Not an issue. I also found the space definitely suspect. Ide asked for this API to be used for generation in the past and it was explicitly determined this was not to be used for that purpose. Which is why ide created an entire set of apis (two actually :-) ) for this need. 

If generating code is now a supported use case, then I think we'll need a lot more work and dedicated testing for this purpose here :-)

**Comment by 333fred** [comment]
I was treating this issue as the request, as it predates our process for API requests.

**Comment by thomhurst** [comment]
> > I'm using the ISymbol.ToDisplayString method to generate source code from my source generator
> 
> This is not a supported use case for this API. ToDisplayString is for displaying symbols for easy reading. It's never been a goal to use it to generate compilable code.

What's the best way to fully qualify something then?

**Comment by 333fred** [comment]
Depends on the type of symbol. We've since clarified our policy: for type symbols, ToDisplayString with the fully qualified format will be valid code. Anything else, you will need to manually do it.

**Comment by thomhurst** [comment]
> Depends on the type of symbol. We've since clarified our policy: for type symbols, ToDisplayString with the fully qualified format will be valid code. Anything else, you will need to manually do it.

Feels like that could be improved imo.
I'd expect to see something like `ToFullyQualifiedNamespaceAndType()`

I've found it's always safest to use fully qualified namespaces in generated code, to avoid conflicting with other similarly named namespaces. And since it's generally hidden when it's generated, it's not really a big deal if it's a little bit ugly.

Keen to hear what other people think on this though.

**Comment by 333fred** [comment]
> I'd expect to see something like ToFullyQualifiedNamespaceAndType()

What would this apply to other than types though? What would it even mean on a parameter symbol, like this issue is about, for example? Because that api already exists, it's ToDisplayString string with the fully qualified format.

**Comment by thomhurst** [comment]
> > I'd expect to see something like ToFullyQualifiedNamespaceAndType()
> 
> What would this apply to other than types though? What would it even mean on a parameter symbol, like this issue is about, for example? Because that api already exists, it's ToDisplayString string with the fully qualified format.

Well a parameter still will be of a certain type won't it. There's just also extra information you can associate with it also.  

For example I've used a source generator to implement a concrete class from an interface, so I needed to be able to fully qualify the parameter type

**Comment by CyrusNajmabadi** [comment]
> so I needed to be able to fully qualify the parameter type

Types are supported with ToDisplayString

**Comment by thomhurst** [comment]
> > so I needed to be able to fully qualify the parameter type
> 
> Types are supported with ToDisplayString

Yeah, that's what I'm doing, I'm just saying it becomes a confusing API when it works in some cases, but not others, hence this issue?

**Comment by CyrusNajmabadi** [comment]
As mentioned, This is by design. It was never intended for this purpose. :-)

**Comment by vladd** [comment]
> As mentioned, This is by design. It was never intended for this purpose. :-)

Ok, but is there an API which intends to convert an `ISymbol` to a compileable representation, which can be used for code generation?

---

As of now, there are basically two strategies of code generation. One could either go through RoslynQuoter-style API, which is quite cumbersome, and is not what the [code generation cookbook](https://github.com/dotnet/roslyn/blob/main/docs/features/source-generators.cookbook.md) endorses.

Another one is basically working with text, creating a text template filled with compileable names: 

```csharp
$$"""public {{CreateCompileableTypeName(...)}} {{CreateCompileableSymbolName(...)}} { get; set; }"""
```

On this way, for creating the type name and symbol name there is usually an `ISymbol` (or several ones) to generate the correct text from. `CreateCompileableSymbolName` is usually not a huge problem: it sometimes needs `this.` prepended, sometimes `@` prepended, which is in general detectable. But for `CreateCompileableTypeName` we need something different, perhaps with `global::` and so on, in order to avoid ambiguities. For parameters we need even more sophisticated code, which would properly detect modifiers and stringify them. So there is no uniform and reliable approach, it's especially very fragile when new syntactic features are added (e. g., obvious `typeSymbol.IsReferenceType ? "class" : "struct"` now needs to account for records, record structs, ref, readonly and whatnot).

As this way seems to be the endorsed by Roslyn team way of code generation, I suggest that there must be a relatively simple, uniform, "pit-of-success" way for symbol stringification.

**Comment by CyrusNajmabadi** [comment]
> but is there an API which intends to convert an ISymbol to a compileable representation, which can be used for code generation?

No. Not for arbitrary symbols.

**Comment by CyrusNajmabadi** [comment]
>  I suggest that there must be a relatively simple, uniform, "pit-of-success" way for symbol stringification.

Closing out. The position of the team is that we're only supporting this for types. A general purpose API to stringify all symbols is out of scope for Roslyn SG scenarios.
