### ISSUE TITLE
Add support for a nuget package to say it does not support HotReload

### ISSUE THREAD

**Issue by SimonCropp** [dotnet/roslyn#56681]
HotReload is unlikely to support all scenarios, at least not in its first iteration. Eg [support for IL weavers](https://github.com/dotnet/roslyn/issues/56678). 

It would be nice for a nuget package to have a means of communicating that it doesnt support HotReload. Then VS can warn the user at first package install time. note the warning should only happen on install and not update

**Comment by tmat** [comment]
Rather than NuGet package declaring lack of Hot Reload support I believe it would be better if the rewriter cleared this flag on the rewritten assembly: [DebuggableAttribute.DebuggingModesEnable.EditAndContinue](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.debuggableattribute.debuggingmodes?view=net-5.0). The flag is set by default in DEBUG builds. If the rewriter removed this flag it would block EnC and Hot Reload.

**Comment by tmat** [comment]
@SimonCropp Does the suggestion above (https://github.com/dotnet/roslyn/issues/56681#issuecomment-926759022) not work?

**Comment by SimonCropp** [comment]
@tmat does that achieve "Then VS can warn the user at first package install time. note the warning should only happen on install and not update"  ?

**Comment by tmat** [comment]
No, the user will see Hot Reload error when trying to use Hot Reload.

**Comment by SimonCropp** [comment]
in that case, yep that works for me. thanks

**Comment by tmat** [comment]
Cool. Of course, if you test it out and find the behavior suboptimal let us know. Thanks!

**Comment by SimonCropp** [comment]
actually. how will they know what nuget caused hot reload to not work?

**Comment by tmat** [comment]
They wouldn't, unless they are aware of using IL rewriter. The error would say something like "the module does not support hot reload/enc". If the rewriter placed some well-defined attribute on the assembly we could include it in the error message as a potential root cause. E.g. "assembly: [AssemblyMetadata("Postprocessor", "Xyz")]`.

**Comment by SimonCropp** [comment]
> we could include it in the error message as a potential root cause

if there were multiple `AssemblyMetadata("PostProcessor` how would you know which on prevented hot reload?

**Comment by tmat** [comment]
We would list all of them.
