### ISSUE TITLE
Handle satellite assemblies in analyzer loader

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#56708]
I observed that msbuild has special handling for satellite assemblies in their assembly loader:

https://github.com/dotnet/msbuild/blob/c144bfc4693abfd02803fbb8cd223c7b314b9ab3/src/Shared/MSBuildLoadContext.cs#L51-L53

Does Roslyn need to do the same when loading analyzers with localized resources? (fwiw, it does seem like the strategy of preferring assemblies in the same directory, then searching the entire set of provided assemblies, will work around the issue for us, but perhaps a satellite assembly test is missing.)

Also, the requirement that all analyzer dependencies be included in the same directory might also apply to satellite assemblies, which means that shipping the satellite assemblies in a nested folder is technically not supported.

**Comment by fubar-coder** [comment]
Maybe related to #29014 and dotnet/runtime#11463

**Comment by bjornhellander** [comment]
Any update on this? Or any way around it?
StyleCop Analyzers seems to be affected by this. as mentioned in https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/3397

**Comment by sharwell** [comment]
@jaredpar @mavasani  this is a localization bug impacting analyzer authors

**Comment by sixeyes** [comment]
Could @jaredpar comment on progress here? So far all that appears to have happened is milestone changes. It's been months since the last comment

**Comment by jaredpar** [comment]
Does anyone have a repro for this particular problem? The [shadow copy logic](https://github.com/dotnet/roslyn/blob/7eff5ed876f1d5f64dab9eb1b7d1c22e6ee587fa/src/Compilers/Core/Portable/DiagnosticAnalyzer/ShadowCopyAnalyzerAssemblyLoader.cs#L138) in the compiler handles resources today. The copied folder structure will match the original so hard to see where the error would be in the shadow layer here. Happy to dig into a repro.

**Comment by sixeyes** [comment]
Does the example in the first post [here](https://github.com/dotnet/roslyn/issues/29014) do what you require?

**Comment by jaredpar** [comment]
@sixeyes there are a set of issues that link off of that. My reading of them though is that earlier versions of .NET Core did not properly do satelite assembly loading. The CLR fixed that [here](https://github.com/dotnet/coreclr/pull/24191). Given that we're laying these out correctly now that should hlod together. 

Is this still happening on more recent SDKs? If so is there a repro to look at? That issue is from the .NET SDK 3 days, the repros are quite out of date.

**Comment by sharwell** [comment]
The easiest repro would likely be https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/3397

**Comment by sharwell** [comment]
I was able to test this by opening microsoft/vs-threading and adding `documentationMode` to the existing stylecop.json file. I observed the following:

1. ✅ Visual Studio background analysis used the correct culture
2. ✅ Building within Visual Studio appeared to use the correct culture
3. ❌ Building from the command line using `dotnet build /t:Rebuild` did not use the correct culture

**Comment by RikkiGibson** [comment]
So do we just need to change the implementation to observe that the assembly we are being asked to load is a satellite assembly, thus go up to the containing folder before looking up the ALC?

**Comment by jaredpar** [comment]
The MSBuild solution isn't 100% what we need. They're not as strict as we are about what is loaded. But more / less that is the strategy.

**Comment by jaredpar** [comment]
Good and bad news here. 

The good news is that by looking into this I was able to find a bug with satellite loading in the compiler. It was introduced when we moved to using stream based loading in Unix. Have a PR out to fix it. 

The bad news is I cannot reproduce the bad behavior described in StyleCop bugs. When I attempt to rebuild StyleCop using the instructions I get the expected diagnostics. The unit tests I added when fixing the stream bug demonstrates that satellite loading is working in all the contexts we expect (or will once the PR verifies the full suite). It also seems unlikely anyone who reported this issue ran into the stream bug that I just sent a PR for. That bug was introduced just a few months ago while some of these reports are much older. 

It's possible earlier versions of the compiler had a slightly different bug that caused this and we inadvertently fixed it. That's _possible_ but feels like a reach. I'm happy to look into other repos, particularly on anything 7.0.2xx or later, but right now I don't have one that shows this bug.
