### ISSUE TITLE
MissingMethodException when opening Typescript File

### ISSUE THREAD

**Issue by basoundr** [dotnet/roslyn#5692]
When I try to open a typescript file, I get this message thrown
![image](https://cloud.githubusercontent.com/assets/10550513/10289025/147f4ff6-6b51-11e5-8ee8-a7bc0b120dad.png)

Then this exception happens when I start clicking randomly in the file
{"Method not found: 'Void Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.QuickInfo.QuickInfoDisplayDeferredContent..ctor(Microsoft.CodeAnalysis.Editor.IDeferredQuickInfoContent, Microsoft.CodeAnalysis.Editor.IDeferredQuickInfoContent, Microsoft.CodeAnalysis.Editor.IDeferredQuickInfoContent, Microsoft.CodeAnalysis.Editor.IDeferredQuickInfoContent, Microsoft.CodeAnalysis.Editor.IDeferredQuickInfoContent, Microsoft.CodeAnalysis.Editor.IDeferredQuickInfoContent, Microsoft.CodeAnalysis.Editor.IDeferredQuickInfoContent)'."}

The Dump is \\mlangfs1\public\basoundr\TypescriptFileOpenDump

The file that I tried opening is in Coby [restclient.ts](https://github.com/basoundr/coby/blob/master/src/Client/CobyPortal/coby/core/restClient/restClient.ts)

**Comment by balajikris** [comment]
Yeah, I've seen this myself when you patch only roslyn bits on your box and don't update typescript to work with that version of roslyn. I've since installed latest update1 patches and typescript (quickinfo for this case) seems to be working quite fine.

this isn't a bug but just that you have mismatched components on your installation.
