### ISSUE TITLE
Annotate `SyntaxNode.CopyAnnotationsTo()` with `NotNullIfNotNull`?

### ISSUE THREAD

**Issue by tiesmaster** [dotnet/roslyn#56949]
**Version Used**: `3.9.0`

[As discussed](https://discord.com/channels/143867839282020352/598678594750775301/894394625106788362) on the community Discord, when enabling NRTs for my analyzer, I noticed that `SyntaxNode.CopyAnnotationsTo()` returns `T?`, however, I didn't expected that. Looking [at the implementation](https://github.com/dotnet/roslyn/blob/ca8398b08b142baab1eaa5d4d89eeea61c415565/src/Compilers/Core/Portable/Syntax/SyntaxNode.cs#L1254-L1267), I noticed it only returns `null`, when the incoming `node` is `null`. This looks like this method might benefit from adding the `NotNullIfNotNull` attribute to signal this behavior, and allows me to omit the `!`, since I know that method doesn't return `null` in my scenario.

**Comment by RikkiGibson** [comment]
Wondering if it would make sense to change the signature as follows:

```cs
public T CopyAnnotationsTo<T>(T node) where T : SyntaxNode?
```

**Comment by tiesmaster** [comment]
@RikkiGibson Thanks for the suggestion, and I just tried that out with #57992. However, that comes back with CS8603 ("Possible null reference return"), so I think that the `NotNullIfNotNull` is more suited, wouldn't you say?

**Comment by RikkiGibson** [comment]
Yes, I think it would be fine to solve this using NotNullIfNotNullAttribute instead.

The warning on 'return null' is a limitation of nullable analysis. Essentially we can't observe that because the value of type T was null, then the type argument must have been nullable.

I think it can be worked around by returning the parameter we know to be null instead of a null literal.
