### ISSUE TITLE
Proposal: Library method for iterating over IEnumerable concurrently (ForEachConcurrent)

### ISSUE THREAD

**Issue by sashas79** [dotnet/roslyn#570]
ForEachConcurrent iterator over a collection. See below for implementation.

[Explanation](http://csharpandsuch.tumblr.com/post/111076020413/concurrent-collections-with-c-foreachconcurrent)

        public static List<TD> ForEachConcurrent<T, TD>(this IEnumerable<T> src, Func<T, TD> concurrentAsync, bool isRunAsync = false, short magnitude = 2, params object[] args)
        {
            var arDataTasks = new ConcurrentStack<TD>();

            List<Tuple<Func<T, TD>, T>> tasks = src
                .Select(thing => new Tuple<Func<T, TD>, T>(concurrentAsync, thing))
                .ToList();

            var states = new ConcurrentStack<IAsyncResult>();

            tasks
                .SplitInBatchesOf(magnitude.BitMultiplesOf8())
                .ForEach(batch => batch
                    .ForEach(task =>
                    {
                        var async = task.Item1;

                        var arg = task.Item2;

                        var state = async.BeginInvoke(arg, result =>
                        {
                            using (result.AsyncWaitHandle)
                            {
                                arDataTasks.Push(async.EndInvoke(result));

                                result.AsyncWaitHandle.Close();
                            }
                        }, args);

                        //waitHandles
                        states.Push(state);
                    }));

            bool isWait = !isRunAsync;

            while (isWait)
                if (states.ToList().All(itm => itm.IsCompleted || itm.CompletedSynchronously) && arDataTasks.ToList().Count >= tasks.Count)
                    isWait = false; //break;

            return arDataTasks.ToList();
        }

        public static List<List<T>> SplitInBatchesOf<T>(this IEnumerable<T> source, int batchSize)
        {
            return source
                .SplitInBatchesOf(batchSize, itm => new List<T>(itm ?? new List<T>()))
                .ToList();
        }

        static IEnumerable<TR> SplitInBatchesOf<T, TR>(this IEnumerable<T> source, int size, Func<IEnumerable<T>, TR> resultSelector = null, Func<T, TR> selector = null)
        {
            return batchElements(source, size, resultSelector ?? (itm => itm.Select(selector ?? (x => default(TR))).FirstOrDefault()));
        }

        private static IEnumerable<TR> batchElements<T, TR>(this IEnumerable<T> source, int size, Func<IEnumerable<T>, TR> resultSelector)
        {
            T[] batch = null;
            var count = 0;

            foreach (var item in source)
            {
                if (batch == null)
                    batch = new T[size];

                batch[count++] = item;

                if (count != size)
                    continue;

                yield return resultSelector(batch.Select(x => x));

                batch = null;
                count = 0;
            }

            if (batch != null && count > 0)
                yield return resultSelector(batch.Take(count));
        }

**Comment by jmarolf** [comment]
Could you please explain how this is different from [Parallel.ForEach](http://referencesource.microsoft.com/#mscorlib/system/threading/Tasks/Parallel.cs,2817)?  If you pass in ParallelOptions.MaxDegreeOfParallelism = 64 (or whatever concurrency level you want) it will execute at that concurrency level (this depends on the task scheduler, but the default threadpool acts this way).

**Comment by khellang** [comment]
Also, aren't these requests best suited for https://github.com/dotnet/corefx?

**Comment by svick** [comment]
Based on your article, you seem to have some issues with PLINQ. Why not ask for improvements of PLINQ, instead of creating a completely new API?

Specific comments regarding your article:

> The problem I have faced when using `AsParallel` on collections is that the performance benefits are far outstripped by the complications which arise with threading in general. In ASP.NET specifically, it is mostly harmful since it confuses the IIS/Katana wrapper threading model under which it runs.

PLINQ uses the ThreadPool, just like ASP.NET, which can indeed sometimes cause issues. But your implementation using `BeginInvoke()` uses the same ThreadPool, so I don't see how it solves anything.
In fact, I belive your version is much worse, because it starts all the delegates at the same time.

> On top of that, AsParallel is severely limited to 8 threads

No, it's not. By default, PLINQ will use as many threads as you have CPU cores, because it assumes your work is CPU-bound. If your work is not CPU-bound, then:

1. You can manually specify how many threads to use by calling `WithDegreeOfParallelism()`.
2. You would be better off with using the `await` you seem to hate so much. It was build to solve exactly this problem, *especially* in ASP.NET.

> there is no way to track completion of tasks requiring the code base to be sprayed with “global” variables checking for completion, locking, etc. 

I'm not quite sure what does this mean, but I don't see how does your code improve that.

> All async/await implementations force method’s callees to be async

They don't. It's the recommended way to do it, because it makes the most sense (you don't waste a thread waiting) and because it avoids the common deadlock issue. But you're not forced to do this (the deadlock issue is easily solved by using something like `Task.Run(YourAsyncMethod).Wait()`).

> spawn new batches of operations to run concurrently when the previous batch is finished executing

You don't actually do that though, because you never wait for the previous batch to finish.

**Comment by gafter** [comment]
Please take this suggestion to https://github.com/dotnet/corefx
