### ISSUE TITLE
String duplication concatenating a StringBuilder

### ISSUE THREAD

**Issue by CyraxSputnik** [dotnet/roslyn#57006]
**Version Used**: 

.NET 6 RC 1, Visual Studio 2022 Preview and Windows 7

**Steps to Reproduce**:

```
string folio = "331442";

StringBuilder builder = new();

// (<TargetFramework>net5.0</TargetFramework>): F-331442
// (<TargetFramework>net6.0</TargetFramework>): F-331442 F-331442
builder.Append($"F-{folio} {builder}");

WriteLine(builder.ToString());
ReadKey();
```

**Expected Behavior**:

w/ .NET 5
F-331442 

**Actual Behavior**:

w/ .NET 6
F-331442 F-331442

**Comment by 333fred** [comment]
This is not a dup, this is an intentional break. There is a behavior difference here between .NET 5 and 6 that we considered acceptable. In .NET 5, that `builder.Append` turns into the following code:

```cs
builder.Append(string.Format($"F-{0} {1}", folio, builder));
```

This in turn means that the implementation of `string.Format` will call `ToString` on the `builder` _before_ the first bits are added to the builder, meaning the builder will be empty and `ToString()` returns the empty string. In .NET 6, this is the equivalent:

```cs
var handler = new StringBuilderAppendHandler(3, 2, builder);
handler.AppendLiteral("F-");
handler.AppendFormatted(folio);
handler.AppendLiteral(" ");
handler.AppendFormatted(builder); // Here's the changed behavior!
builder.Append(handler);
```

When the `handler.AppendFormatted(builder);` line is called, the `StringBuilder` has already been added to via the previous `handler.AppendX` lines, and is _not_ empty at that point. So the content that has already been added to the builder is added to the string.

@CyraxSputnik you have 2 possible workarounds here:

1. Don't put the `builder` in the interpolated string in the first place (I assume this was a simplified example?)
2. Call `ToString` on the builder _before_ the interpolated string and save it into a temp variable, then use that temp variable where you're using `builder` in the interpolated string.

@stephentoub fyi.

**Comment by 333fred** [comment]
@stephentoub?

**Comment by stephentoub** [comment]
https://github.com/dotnet/docs/issues/26428
