### ISSUE TITLE
Update the default language version for Visual Basic/VB to 16.9

### ISSUE THREAD

**Issue by KathleenDollard** [dotnet/roslyn#57093]
The language versions for VB currently have 16 as the default and 16.9 as latest. 16.9 should be the latest.

**Comment by Youssef1313** [comment]
Given the current issue about 16.0 vs 16.9, it looks like it's matching what the docs say?

https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/configure-language-version

> The special strings default and latest resolve to the latest major and minor language versions installed on the build machine, respectively.

Default maps to latest major (16.0), and latest maps to latest minor (16.9)

**Comment by DualBrain** [comment]
Are there two different conversations here?  There is *default* and *latest* being equal (or not).  There is also the question of which version of VB should be "current" in the project templates.  In my mind, *default* and *latest* are basically the same given that VB is **stable**.  More specifically, *default* should mean *latest stable* and *latest* should be *latest bleeding edge* (of course, which doesn't necessarily exist... at this time - but things could possibly change.)  With that said, I do find it rather annoying that I as a VB dev have to remember to update the project template in order to be *current* (16.9) especially if I'm taking advantage of cross-language development features - specifically in the example of consuming C# records in VB.  I shouldn't have to think about this... it should "just work".  I get that the current situation is "by design", but the design doesn't seem to fit the environment that is what VB (the language) currently stands.  The "default" should be the latest "stable" release... which in my mind is 16.9; and, given how VB is progressing, the *latest* should be consider the "stable" release (meaning the default) with the ability to **opt-in** to an earlier version if the need should arise.  In other words, I shouldn't have to modify my projects to be "latest"... that should simply be what it is and if (and only **if**) I encounter a problem should I have to modify which (earlier) version is currently utilized due to most likely have some sort of problem that I need to work around (of which I'm currently not aware of any in my personal experience).

**Comment by 333fred** [comment]
@DualBrain within a VS version, we generally don't change the meaning of `Default`: we only do that when a new major version of VS is released. We should have done this with 17.0, but missed it, so we will be doing it in 17.1.
