### ISSUE TITLE
Applying a suggested code change fails to apply to the solution -With Recording

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#57106]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Applying-a-suggested-code-change-fails-t/1506165)._

---
[severity:It's more difficult to complete my work]
This is the recording for: https://developercommunity.visualstudio.com/t/applying-a-suggested-code-change-fails-to-apply-to/1498066?from=email -- which I was not able to attach as a comment.

---
#### Sam Harwell [MSFT] on 8/17/2021, 02:31 PM: 

<p>Hi @<a target='_blank' href="https://developercommunity.visualstudio.com/users/87622/dustinellis.html">dustin.ellis</a>,</p>
<p>Thank you for providing the additional details. I do want to rule out the possibility of a third-party extension interfering with this operation. Can you try disabling the CodeMaid extension and let us know if the problem persists?</p>
<p>Thank you,<br>
Sam Harwell</p>

#### dustin.ellis on 8/17/2021, 04:21 PM: 

<p>I just tried disabling CodeMaid and I still have this issue.</p>

#### Feedback Bot on 8/17/2021, 05:54 PM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
This is definitely a poor experience and we should do something about this.  Effectively, it's possible to invoke code-actions and have them silently do nothing.  This happens when teh code-action produces a new solutoin, but we're unable to apply it because the workspae has registered another change in the background.  Because we don't want the solution-application to undo the change the workspace already applied, we just insta fail.

We have a few paths we can take here, with varying levels of engineering cost and benefit to the user experience.

First, we could continue the policy of not applying such an action.  However, we should at least notify the user about what happened, and more importantly *why*.  For example, we could say that this wasn't applied because a change to some doc/proj got us out of sync with the change teh code action wanted to apply.

Second, we could augment the above with some more smarts about what the code action was trying to do.  For example, it's often the case that a code action just wants to edit the text of some file.  We could certainly detect if a change had happened to *that* specific file, and if not allow the application to go through, only changing that file.  

Third, we could detect when this situation arises and ask the user what they want to do?  Put them in control of deciding "i do nto want to proceed" vs something like "attempt to merge in these changes with the changes that happened externally".
