### ISSUE TITLE
CallerFilePath not passed for dynamic

### ISSUE THREAD

**Issue by SimonCropp** [dotnet/roslyn#57189]
When passing a dynamic to a method that has a `[CallerFilePath]` the  file path is not passed.

```
[Fact]
public void MissingCallerFilePath()
{
    var output = (dynamic)"Value";
    Foo(output);
}

static void Foo(object target, [CallerFilePath] string sourceFile = null!)
{
    Assert.NotNull(sourceFile);
    Assert.True(File.Exists(sourceFile));
}
```

## Environment:

 * c# 10
 * net48, net6, net461

### VS Version

Microsoft Visual Studio Professional 2022 Preview
Version 17.0.0 Preview 5.0
VisualStudio.17.Preview/17.0.0-pre.5.0+31808.319

### dotnet --info

```
 Version:   6.0.100-rc.2.21505.57
 Commit:    ab39070116

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-rc.2.21505.57\

Host (useful for support):
  Version: 6.0.0-rc.2.21480.5
  Commit:  6b11d64e7e

.NET SDKs installed:
  6.0.100-rc.1.21463.6 [C:\Program Files\dotnet\sdk]
  6.0.100-rc.2.21505.57 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-rc.1.21452.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-rc.2.21480.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.1.21451.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.2.21480.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-rc.1.21451.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-rc.2.21501.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by jaredpar** [comment]
Thanks for taking the time to file this issue, unfortunately the current behavior is by design. 

From the language spec 

> Caller information does not affect overload resolution. As the attributed optional parameters are still omitted from the source code of the caller, overload resolution ignores those parameters in the same way it ignores other omitted optional parameters

Caller information substitution happens as essentially the last operation in binding a method invocation. It will only occur when the method statically resolves to an overload that has both one of the caller info attributes and no matching value at the call site. 

This means that `dynamic` will never substitute caller info arguments. That is because all invocations that involve at least one `dynamic` argument turn into `dynamic` invocations which are resolved at runtime, not compile time. Hence the method overload is not statically known hence no substitution occurs. This behavior is called out in the spec 

> Also, calls that are dynamically bound will not substitute caller information
