### ISSUE TITLE
Disable most test jobs in PR builds

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#57313]
We have some valuable data on how frequently PR merges are blocked by flaky tests.
- roslyn-ci: https://runfo.azurewebsites.net/view/definition/15/
- roslyn-integration-ci: https://runfo.azurewebsites.net/view/definition/245/

At the time of writing, roslyn-ci passed less than 75% of the time on "Merged PR Attempt 1"--the first attempt on the commit eventually used to merge the PR. That means over 25% of the time a developer had to either ask an admin to force merge or spend hours re-kicking test jobs to verify that the failure really was just flakiness.

roslyn-integration-ci is considerably more impacted, with just over 10% of the "Merged PR Attempt 1" runs passing in the last 7 days. This seems to be impacted by some specific issue in dev17 preview 5 which we're working on addressing. Still, the rates in longer windows are still quite bad: about 33% over 14 days and 41% over 21 days.

One of the big reasons that these runs fail so often is that they fan the test suite out to so many configurations. **12 different test jobs in roslyn-ci** and **4 in roslyn-integration-ci**. Each additional test job is an additional opportunity for flakiness to pop up and fail the entire run.

This not only affects developers' ability to merge their changes but our ability to flow code and insert the product on a regular basis. This month I have almost always needed to manually go into dotnet-bot and merge the codeflow PRs or re-kick the tests on them. We end up getting fewer main-vs-deps insertions and it can sometimes be harder to get meaningful RPS data for this reason.

There's significant reason to believe that most of the test runs we perform are not actually necessary in practice on PRs. We think that if we just cover the following, we will have enough coverage for 99.99% of PRs:
1. Windows netframework debug 64
2. Linux netcore debug 64
3. Windows netframework spanish release 32
4. Integration release 64

This issue tracks making the change to run only the above listed test jobs for PR runs. Rolling builds will continue to run all the jobs, and we will have to put someone in charge of monitoring those jobs and noticing when they are failing regularly.

In addition to this we should budget some time to identify and more aggressively disable flaky tests, as well as work to onboard to the new Helix Retry feature and to rationalize the way we retry tests across our different CI jobs.

cc @jmarolf.

**Comment by dibarbet** [comment]
> I would love it if we could have a bot that just creates an issue on github and assigned @dotnet/roslyn-infrastructure
> 
> >

If we run these on all rolling builds, we could potentially tag the PR author owner on the issue as well?  So that they're notified if tests fail.

**Comment by dibarbet** [comment]
> Though I would be interested to learn if this ever happens for a non-flakey test reason.
If they never failed for a non-flakiness issue then I would guess theres would be no need for these legs at all.  But I presume we have the legs for a reason

**Comment by jmarolf** [comment]
> If they never failed for a non-flakiness issue then it seems like there would be no need for these legs at all. But I presume we have the legs for a reason

I do not think these legs really exist for any quantifiable reason other than "more test scenarios is better". I would love to learn of bugs we've caught because they failed in only one test leg. 

Best explanations I can give:

- windows desktop framework x64: this is the environment code runs in for visual studio so we should probably test this :)
- 32-bit tests: I do not think we have _ever_ had a test case failure that only reproduces on 32-bit. The one case I can think of is verifying that the compiler doesn't use up too much stack space. but that should just go in the build-boss suite of tests. no need to run hundreds of thousands of tests just to ensure once stack space test runs
- Spanish: folks where checking in tests that would fail in you were on a locale other than english so this caught real stuff
- linux: path stuff is very different, so it makes sense to run tests here
- osx: it has weird file handle limits that we ran into for a while on the compiler server though we stopped running these for a while and the world didn't end. If we care, we could run the compiler server end-to-end tests here (if we have any I do cannot recall if we ever wrote regression tests for this case).
- debug/release - compiler behavior is very different under a debug build so we should run these. I cannot recall any case where release failed and debug passed. I think this is just test-matrix-completeness syndrome

**Comment by RikkiGibson** [comment]
@jmarolf is this task essentially complete now?

**Comment by RikkiGibson** [comment]
It would be nice if we could connect this change with increases in the "Merged PR Attempt 1" rate. 

https://runfo.azurewebsites.net/view/definition/15/?TargetBranch=main#
@jaredpar @dibarbet is there a way to see back further than 21 days with this metric?
