### ISSUE TITLE
Roslyn generated executables cannot be run without the dotnet command

### ISSUE THREAD

**Issue by mfeemster** [dotnet/roslyn#57347]
**Version Used**: 
Visual Studio 2019, .NET 5.0.11, Windows 10

**Steps to Reproduce**:

1. Create source code from within a .NET 5 Microsoft.WindowsDesktop.App project, which also uses Microsoft.NETCore.App
2. Use SyntaxFactory.ParseSyntaxTree() and CSharpCompilation.Create() to compile the code
3. Write output to exe file
4. Run exe file from command line

**Expected Behavior**:
The generated exe should run

**Actual Behavior**:
The exe does not run, and I get this error:
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

However, if I run like so:
dotnet myprogram.exe

Then it works fine.

I have scoured all of the posts here and on SO about properly adding references to various assemblies, and distinguishing between reference and implementation assemblies, and none of it resolves my problem.

I want to be able to either run the exe from the command line, or double click on it, and have it "just work", just like every other executable.

I am assuming such a thing is possible, because any exe built from within Visual Studio runs fine. However, any exe built using Roslyn appears to be unable to run on its own.

The reason I am posting this is because I absolutely need the generated exe to be able to run on its own without specifying "dotnet" first.

Please let me know if this is possible.

**Comment by svick** [comment]
Note: I'm assuming you want to build a .Net 5 application, the answer would be quite different (and much simpler) for .Net Framework 4.8.

This is because of the nature of .Net Core/.Net 5+. .Net Framework is a part of Windows, so Windows knows how to execute .Net Framework assemblies. .Net Core/.Net 5+ is a separate thing, which means you need some native executable to start your .Net code.

If you build a regular .Net 5 executable project from Visual Studio (or using `dotnet build`), your code is compiled into a .dll file and a native .exe file is added to it (called an "app host"), which starts the .Net runtime for you. And a couple of JSON files are sprinkled on top.

I tried to replicate this process for a Hello World application, and [it seems to work](https://gist.github.com/svick/7c29e29a9db532af0c619e6f3e32e814). But I did it mostly to satisfy my own curiosity and I still don't really know what it's doing, so I don't think you should use that as any kind of guide.

Instead, if you want to build a .Net application programmatically, I think your best option is to use MSBuild/`dotnet`, which already understands all the necessary parts (including advanced options, like producing single-file executables).

**Comment by mfeemster** [comment]
Thank you so much @svick , that worked!

I believe this information is very important, because if you search around, you see some people asking it on forums in various forms. Something like this should be included with the .NET 5 Roslyn documentation.

I am closing this issue.

**Comment by mfeemster** [comment]
One final question @svick . Your gist was great, but I noticed you hard coded the path to

"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Host.win-x64\5.0.11\runtimes\win-x64\native\apphost.exe"

Do you know of a way to programmatically get this folder or something close to it? I'd prefer that over hard coding it, which will change with every .NET version.

**Comment by svick** [comment]
I suspect it's intentional none of this is documented, because doing this on your own is not supported with all that entails (like none of this working the same way in future versions of .Net).

Like I said, all that information is in MSBuild and I think you should rely on that as much as possible. But if you really want just to get the path to the app host, you can [use use the MSBuild API to do that](https://gist.github.com/svick/ffaa5d3fc3ef66479a6aa5811a3cd8e9).

**Comment by mfeemster** [comment]
Thanks, I will try that.
