### ISSUE TITLE
SyntaxToken.GetLocation().GetLineSpan() crashes with an ArgumentOutOfRangeException when visiting XmlTextLiteralNewLineToken

### ISSUE THREAD

**Issue by siegfriedpammer** [dotnet/roslyn#57413]
**Version Used**: Roslyn 3.11.0 nuget packages

**Steps to Reproduce**:

1. Create new console project
2. Add references to Roslyn 3.11.0
3. Add to Program.cs:

```csharp
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using System;

namespace ConsoleApp3
{
    class Program
    {
        static void Main(string[] args)
        {
            var tokens = SyntaxFactory.ParseTokens("\t\t/// <summary>\r\n\t\t/// Creates an immutable snapshot of this document.\r\n\t\t/// </summary>\r\n\t\tIDocument CreateDocumentSnapshot();\r\n");

            var visitor = new TestWalker();

            foreach (var token in tokens)
            {
                visitor.VisitToken(token);
            }
        }
    }

    class TestWalker : CSharpSyntaxWalker
    {
        public TestWalker()
            : base(SyntaxWalkerDepth.StructuredTrivia)
        {
        }

        public override void VisitToken(SyntaxToken token)
        {
            base.VisitToken(token);

            var span = token.GetLocation().GetLineSpan();
            Console.WriteLine(token.Kind() + " " + span);
        }
    }
}
```

**Expected Behavior**:

Prints a list of tokens and their line spans.

**Actual Behavior**:

`token.GetLocation().GetLineSpan()` crashes with a

```
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'position')
   at Microsoft.CodeAnalysis.Text.SourceText.LineInfo.IndexOf(Int32 position)
   at Microsoft.CodeAnalysis.Text.SourceText.LineInfo.GetLineFromPosition(Int32 position)
   at Microsoft.CodeAnalysis.Text.TextLineCollection.GetLinePosition(Int32 position)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTree.GetLinePosition(Int32 position)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTree.GetLineSpan(TextSpan span, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.SourceLocation.GetLineSpan()
   at ConsoleApp3.TestWalker.VisitToken(SyntaxToken token) in Program.cs:line 35
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor.VisitXmlText(XmlTextSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.XmlTextSyntax.Accept(CSharpSyntaxVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor.VisitDocumentationCommentTrivia(DocumentationCommentTriviaSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.DocumentationCommentTriviaSyntax.Accept(CSharpSyntaxVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.VisitTrivia(SyntaxTrivia trivia)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.VisitLeadingTrivia(SyntaxToken token)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.VisitToken(SyntaxToken token)
   at ConsoleApp3.TestWalker.VisitToken(SyntaxToken token) in Program.cs:line 33
   at ConsoleApp3.Program.Main(String[] args) in Program.cs:line 19
```

**Comment by AlekseyTs** [comment]
The tokens have correct span in relation to the original input of the ```SyntaxFactory.ParseTokens```. However, the ```SyntaxFactory.ParseTokens``` doesn't produce a syntax tree and doesn't even produce a syntax node that encapsulates all the parsed tokens. At the same time, getting a location (location and span are different things) or its line span makes sense only in context of a syntax tree. For example, ```NoLocation.Singleton``` is returned as a location for each visited token, except those encapsulated under the structured trivia. Line span for ```NoLocation.Singleton``` is ```default(FileLinePositionSpan)```. Tokens encapsulated under the structured trivia have parent node and, when Location is requested, a syntax tree is synthesized for it. The problem is that this process can only recover text for the node itself, text for previous or following tokens cannot be included, they are not linked in any way by the ```SyntaxFactory.ParseTokens```. This causes a mismatch between the recovered text and token positions, anything preceding and following the structured trivia in the original text is not included. Therefore, tokens at the end of the structured trivia have position that is beyond the end of the synthesized syntax tree. This is the cause of the exception.   

Also, note that ```SyntaxFactory.ParseTokens``` has a parameter that allows to specify the initial position for the produced token sequence. So, the absolute value of positions can easily be outside of bounds of the original text, per user's request. 

I think that the ideal behavior would be to return ```NoLocation.Singleton``` as a location for absolutely all tokens produced by the ```SyntaxFactory.ParseTokens``` API. Unfortunately, at the moment I do not have an idea how to do that without capturing additional information in the tokens and increasing the memory usage, and without increasing complexity. Also, it doesn't look like we can change anything about the synthesized syntax tree. One can still request it and face the same inconsistencies between token positions and the synthesized text. Perhaps, it would be acceptable to simply recognize that behavior of ```GetLineSpan``` is unspecified for tokens produced by the ```SyntaxFactory.ParseTokens``` API.

**Comment by CyrusNajmabadi** [comment]
> Perhaps, it would be acceptable to simply recognize that behavior of GetLineSpan is unspecified for tokens produced by the SyntaxFactory.ParseTokens API.

I think that would be potentially acceptable.  Would have to doc it accordingly.

**Comment by siegfriedpammer** [comment]
> > Perhaps, it would be acceptable to simply recognize that behavior of GetLineSpan is unspecified for tokens produced by the SyntaxFactory.ParseTokens API.
> 
> I think that would be potentially acceptable. Would have to doc it accordingly.

While I agree with this, I am wondering how a user of Roslyn should be able to properly work with `DisabledTextTrivia`? I need the locations of the disabled tokens, comments, etc. I worked around this by just getting the "full string" of the disabled trivia, then tokenizing it and setting the `initialTokenPosition` to get correct locations, then visiting it just as it were part of the syntax tree anyway. This worked until I stumbled across this bug.

Do you have a suggestion on how to solve this? I found similar questions on SO with no solution. Thanks!

**Comment by siegfriedpammer** [comment]
Of course, I always could go back to writing my own C# lexer, but that would defeat the purpose of Roslyn.

**Comment by siegfriedpammer** [comment]
For context, currently I am doing something similar to this:

https://github.com/dotnet/roslyn/blob/4a24b8b1b26fe6fe668007b2dcfb5270bc4df372/src/Workspaces/CSharp/Portable/Classification/Worker.cs#L234-L252

**Comment by AlekseyTs** [comment]
> Of course, I always could go back to writing my own C# lexer, but that would defeat the purpose of Roslyn.

I think there is no problem with Roslyn's lexer. It produces tokens with correct Span. The location "services" do not work reliably on tokens produced by the ```SyntaxFactory.ParseTokens``` because the API doesn't preserve all required information  . However, the caller of the ```SyntaxFactory.ParseTokens``` has all that information, can translate the spans (or use proper ```initialTokenPosition```) to the spans within the original SyntaxTree (the tree originally containing the tokenized text). Create  locations within that syntax tree ```SyntaxTree.GetLocation(TextSpan)```. Then the ```GetLineSpan``` can be called, etc.

**Comment by siegfriedpammer** [comment]
Thank you for clearing up this misunderstanding. Didn't know that this could be done.
