### ISSUE TITLE
Disable "Implement abstract class" for VB when inheriting from C# abstract record

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#57510]
VB currently does not support inheriting from C# abstract record and the refactoring generates bad code:

```C#
public abstract record R(int A);
```

```VB
Class S
    Inherits R

    Public Overrides Function <Clone>$() As R
        Throw New NotImplementedException()
    End Function
End Class
```

**Comment by Youssef1313** [comment]
Does the code initially generate `BC30610: must either be declared 'MustInherit' or override the following inherited 'MustOverride' member(s): ....`?

https://github.com/dotnet/roslyn/blob/30c493a2692ff211ebcae46c66b00f629562d4a7/src/Features/VisualBasic/Portable/ImplementAbstractClass/VisualBasicImplementAbstractClassCodeFixProvider.vb#L18

We can improve the produced diagnostics while fixing the IDE error as well (two birds with one stone).

Instead of producing BC30610, let's produce a new error: `Class 'S' can't inherit from 'R' because 'R' contains an identifier that is not valid in VB`

That way, if in future `<Clone>$` is renamed to a "speakable" name. The feature will work on its own.

**Comment by CyrusNajmabadi** [comment]
We would take a small community pr here.
