### ISSUE TITLE
Improper precedence of or operator in combination with not in pattern matching?

### ISSUE THREAD

**Issue by X-7r3em** [dotnet/roslyn#57575]
**Version 5**: 

**Steps to Reproduce**:

System.Data.ParameterDirection.Output is not (System.Data.ParameterDirection.Input or System.Data.ParameterDirection.Output) will return false,

but 
System.Data.ParameterDirection.Output is not System.Data.ParameterDirection.Input or System.Data.ParameterDirection.Output will return true

Have in mind that the pattern and the second operand of the or operator need to be the same for this to be reproduced.

**Expected Behavior**:
What I expected from an or operator is for the not to be applied after the or. However, it seems that without the parentheses, this is not the case. This has led to some nasty bugs in our products.

I tried ParameterDirection.Output is not ParameterDirection.Input or not ParameterDirection.Output, however it returned true as well. Soo it seems that there is some very very tricky moment with the operator precedence. Could you elaborate in what order are the operators resolved, and what is the reason behind it? Or is this not expected? I surely did not expect it.

**Actual Behavior**:
Well, I stated it in the steps to reproduce :)

Have a great day :)

**Comment by CyrusNajmabadi** [comment]
This is def by design, and matches normal expression precedence.  if you have `!a || b` then that is `(!a) || b` *not* `!(a || b)`.  It would both be a bad breaking change to change this, and also very inconsistent with teh general rules of the language here in the parallel expression side of things.

> This has led to some nasty bugs in our products.

Note: if we were to change this, it would certainly introduce nasty bugs.  And even if we had had this formalization originally, it would also have led to nasty bugs as it would be reasonable for people to think that pattern precedence worked like expression precedence :)

> Could you elaborate in what order are the operators resolved

In general, this will be resolved similarly to expressions (though @RikkiGibson can def correct me if i'm wrong).   

For `not System.Data.ParameterDirection.Input or System.Data.ParameterDirection.Output`

First, we'll see what `System.Data.ParameterDirection.Input` evaluates to.  Then we'll apply the `not` pattern to that to flip it.  If this results in `true` we won't bother with the `or` part (as we shortcircuit here just like with expressions.  If it results in `false`, we will then evaluated `System.Data.ParameterDirection.Output` and return that as the result.

Doing this evaluation `System.Data.ParameterDirection.Output` being the thing tested produces:

`System.Data.ParameterDirection.Output is System.Data.ParameterDirection.Input` is `false`.  We negate that with `not` to `true`.  As such we skip the RHS of hte `or` and just return `true` (which is what you saw when you ran this).

--

For `not (System.Data.ParameterDirection.Input or System.Data.ParameterDirection.Output)`

We'll first evaluate `System.Data.ParameterDirection.Input`.  If that is `true`, we can shortcircuit the other side (because of `or`) and return `false` immediately (because we `not` the `true`) value.  If `System.Data.ParameterDirection.Input` is `false`, then we execute the rhs and immediately `not` the result of that.

Doing this evaluation `System.Data.ParameterDirection.Output` being the thing tested produces:

`System.Data.ParameterDirection.Output is System.Data.ParameterDirection.Input` is `false`.  So we need to check the RHS of the `or` pattern.
`System.Data.ParameterDirection.Output is System.Data.ParameterDirection.Output` is `true`.  So the value of the `or` pattern is `true`.  We then negate this with `not`, producing a final value of `false` (which is what you saw when you ran this).

**Comment by X-7r3em** [comment]
Yes, a few hours after I wrote this, I tried some examples, and I came to the same conclusion that it is as you have written :). It is tricky in the begging before you wrap your head around it though. The tricky part is that "not" is not an operator on the "is" operator, but rather the result of the "is" expression. But eh :D
