### ISSUE TITLE
Feedback for new global usings feature

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#57599]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Feedback-for-new-global-usings-feature/1571043)._

---
1) Please don't use IDE0005 for unused global usings
I want to have warning for unused using because this is usually triggered by refactoring and forgetting to modify usings block in the header. In contrary when I specify global using then I explicitly ask for the namespace to be imported into the scope and I DO NOT want to be warned that the using is unused. The sole fact that I specify global using means that I think it will be needed in future.

2) Allow us to disable implicit usings in Visual Studio IDE. It's actually very annoying to manually change enable to disable in csproj file after each project is generated. I want the code to be self descriptive and some "magic" implicit imports are a feature that I don't like at all.

3) Allow us to set in Visual Studio that implicit usings are generated into Globals.cs file. This is the correct way because then then it's well documented in code which usings are actually imported into the scope.

---
#### Feedback Bot on 11/3/2021, 11:13 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
'2' and '3' need to go to the sdk team.  :)
'1' is part of roslyn.

**Comment by davidwengier** [comment]
2 and 3 are covered by https://github.com/dotnet/project-system/issues/7488

**Comment by vatsalyaagrawal** [comment]
Design meeting notes:

- There are several ways for user to address this scenario.
- We are open to a separate diagnostics. But implementation would get complicated. 

Decision: Won't fix, as existing functionality address this scenario.

**Comment by davidwengier** [comment]
As per design meeting, closing this as won't fix.

There are a few workarounds that can be put in place if a user wants global usings to not trigger IDE0005, including adding a `#pragma` suppression in the file where they are stored. The generated global usings from the SDK do not trigger it due to being in a generated file, and if more granular control is needed, for example to specify a separate severity level, then likely a well placed .editorconfig file can achieve this. We don't think the IDE should be trying to determine whether a user intentially added a using versus a global using.
