### ISSUE TITLE
Simplify some convoluted code

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#5760]
The [following code](https://github.com/dotnet/roslyn/blob/master/src/EditorFeatures/CSharp/UseAutoProperty/UseAutoPropertyAnalyzer.cs#L76-L81) was being ridiculed [in a twitter comment](https://twitter.com/vreshetnikov/status/650764140101799936):

```cs
            else if (expression.Kind() == SyntaxKind.IdentifierName)
            {
                return true;
            }

            return false;
```

It can be replaced by

```cs
            return expression.Kind() == SyntaxKind.IdentifierName;
```

**Comment by tmat** [comment]
or even 
```return expression.IsKind(SyntaxKind.IdentifierName)```

**Comment by CyrusNajmabadi** [comment]
I wrote this code, and the pattern was intentional.  I was trying to very specifically enumerate the cases that were being handled, with the code to handle them as necessary.  i.e. I think it's actually clearer to write code like so:

```
if case1
  code to handle case one
else if case2
  code to handle case two
else if case3
  code to handle cast three

default handling
```

Yes, it is true that this occasionally means the final case and the default case can be merged.  But that's not necessarily clearer IMO.  I would prefer this code not be changed.

**Comment by CyrusNajmabadi** [comment]
I don't like the idea that we're simply changing code because someone (even Vlad) was mocking it.  As someone who has maintained code like this I picked the pattern intentionally.  It allows for very simple handling of changes in the future, especially in the early days of a code-analyzer where you may want to tweak things.   For example, if I wanted to do something special in the case where it was an identifier (like analyzing anything else), then it would be simple to do so in the form I wrote.  Not so in the more compact form.

I could have even written the original extremely compactly by doing the following:

```c#
return expression.IsKind(SyntaxKind.SimpleMemberAccessExpression)
  ?  ((MemberAccessExpressionSyntax)expression).Expression.Kind() == SyntaxKind.ThisExpression && ((MemberAccessExpressionSyntax))expression).Name.Kind() == SyntaxKind.IdentifierName
  : expression.Kind() == SyntaxKind.IdentifierName;
```

But I specifically chose not to because I felt that being so compact actually hampered readability.  I like the nature of being able to use all the 'if' expression clauses to see what node shapes we care about.  Then for each node shape we can see how they're handled.  Switching to Vlad's suggestion means I not only have to examine the 'if' clauses, but also then check and see that the final bail out case handles yet another node shape.

**Comment by gafter** [comment]
@CyrusNajmabadi I think you're hinting that you're going to "Will Not Fix" this.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/5822
