### ISSUE TITLE
How to get ISymbol from CompletionItem

### ISSUE THREAD

**Issue by yevgeni-zolotko** [dotnet/roslyn#57677]
How do I get `ISymbol` from a `CompletionItem` returned from `completionService.GetCompletionsAsync`?
For example, `Recommender.GetRecommendedSymbolsAtPositionAsync` provides such information. As I imagine, the `GetCompletionsAsync` list is partially built using `ISymbol`s. Is there way to access them?

**Comment by CyrusNajmabadi** [comment]
You cannot.  It's intentionally by design that ISymbol's are not exposed as:

1. they wouldn't make sense for other languages (like F# and VB)
2. many normal items won't have them.  There's only a loose connection from a completion item to an ISymbol for it.
3. these apis are intended to work cross process.  As such, rich tree/graph-like data cannot be part of it as it wouldn't be feasible at all to serialize that over the wire
4. eventually this will all be through LSP, which takes an even less-symbolic view of these things.

If you want symbols, that's exactly what Recommender is for as it's the C#/VB symbol-centric view of things that other features layer on top of :)
