### ISSUE TITLE
Follow up on the issue with duplicating `when` expressions in DAG

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#57730]
I think we should try implementing option 1 listed at https://github.com/dotnet/roslyn/pull/55981#discussion_r697893041. As we no longer under tight time pressure and our understanding of the DAG machinery grows. I think I will be interested in giving this a try.

**Comment by AlekseyTs** [comment]
I looked at the current approach and the option 1 doesn't feel simpler or more robust.

**Comment by alrz** [comment]
I think caching the when-expression result doesn't even work because these when-nodes never appear in the same path.

It's quite interesting to see how F# handles this:

https://sharplab.io/#v2:EYLgtghglgdgNAGxAMwM4B8D2AHApjAAgGUBPVAF1zAFgAoBXcg5AgNQEEAZAVQFEDgARgEAmAgF46BApHIBjABZsufAgHco5BVILpmEBKlzqF+AcIC0APgKCdegPomzwMdYIj7BcgCcArsbuAMxeTu4ALDrS0THSUbEJcbRAA==

```fs
let f s b1 b2 =
  match s with
  | false when b1 -> 1
  | _ when b2 -> 2
  | true -> 3
  | _ -> 4
```
```cs
public static int f(bool VALUE, bool b1, bool b2)
{
    if (!s && b1) // testing `s`
    {
        return 1;
    }
    if (b2)
    {
        return 2;
    }
    if (s) // testing `s` again
    {
        return 3;
    }
    return 4;
}
```
To do that the compiler needs to know what when-clauses are going to be "problematic" ahead of time. F# implementation[0] is not prefect though since it could still generate duplicated expressions (or even tests) if you push it hard enough.

[0] https://github.com/dotnet/fsharp/blob/main/src/Compiler/Checking/PatternMatchCompilation.fs#L1714

As far as I could understand it, it's lowering when-clauses clause-by-clause but it doesn't have a separate lowering phase and directly generates code so the solution doesn't exactly apply to C#.
