### ISSUE TITLE
'is not' and [DoesNotReturn]

### ISSUE THREAD

**Issue by Djoums** [dotnet/roslyn#57798]
### Description

Functions with the `[DoesNotReturn]` attribute are not handled correctly with the `is not` operator.

### Reproduction Steps

```
[DoesNotReturn]
private static void InvalidOperation() => throw new InvalidOperationException();

public static void Main()
{
    object obj = new List<int>();

    if (obj is not List<int> list)
        InvalidOperation();

    Console.WriteLine(list.Count); // CS0165: Use of unassigned local variable 'list'
}
```

### Expected behavior

`list` must be defined, because of the `[DoesNotReturn]` attribute.

### Actual behavior

CS0165: Use of unassigned local variable 'list'

### Regression?

Didn't test previous versions.

### Known Workarounds

Surprisingly, declaring the function as nested does work.

```
public static void Main()
{
    object obj = new List<int>();

    if (obj is not List<int> list)
        InvalidOperation();

    Console.WriteLine(list.Count); // Works

    [DoesNotReturn]
    static void InvalidOperation() => throw new InvalidOperationException();
}
```

### Configuration

Using .Net 6 on Windows 10, VS Code.

**Comment by 333fred** [comment]
`DoesNotReturn` is a nullable-related attribute only. It does not have the strong guarantees needed to actually prevent your code from compiling if your method does actually return, similar to all the rest of the nullable code-analysis attributes. Because of this, definite assignment cannot take it into account. See https://github.com/dotnet/csharplang/issues/538 for the language proposal that would create a stronger guarantee via a bottom type, which would enable this scenario.

**Comment by Djoums** [comment]
Then why does it work for a nested function ? Seems like an inconsistency to me.

**Comment by 333fred** [comment]
> You only addressed half of the issue here, why does it work for a nested function ? Is that also 'by design' ?

Yes, that is also by design. That's not the attribute doing anything at all: while definite assignment cannot do whole program analysis (as we can't solve the halting problem) it can look inside local functions. You can see in [this](https://sharplab.io/#v2:EYLgtghglgdgNAExAagD4AEBMBGAsAKHQAYACdbAFgG4CCB7YAKwFMBjAFxIcZIF4SYzAO4kAMlADO7ADyx2APgAUAShr4CUAGYlF3EpIF1O4qbJgKSAG0ntlBEg5IBJGADcI1hAHkADswBOEOxQdDAqagTkAJyK1lIAdADCdACu5qokAPSZJADqdP4A1hK0hNgAbGQUzm4eUN5+gcGhKnzyJOwAFv50IoIiLu6evgFBITAAogAerMw+zWGqQA==) example that, even with the attribute removed, definite assignment can pay attention to the body of the local function.
