### ISSUE TITLE
Partial Class File Function List Should List Only the Function in the File

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#57839]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Partial-Class-File-Function-List-Should-/1584964)._

---
When using multiple code files for a partial class, the drop down list which lists all of the functions for a file should list ONLY the functions contained in the file, not the functions for the entire partial class across all of its files. In the example screenshot, the drop down highlights the functions which are contained in the file being edited, but it also lists all other functions and objects from the entire partial class. It should list only the things defined in the given single code file being edited, i.e., only the highlighted functions as per the screenshot should appear at all.

! [function list.jpg] (https://aka.ms/dc/image?name=B0d5f3a8716af491b90835aabad7e77b3637726309062111251_function_list.jpg&tid=0d5f3a8716af491b90835aabad7e77b3637726309062111251)

---
#### Feedback Bot on 11/15/2021, 11:22 PM: 

We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.

**Comment by CyrusNajmabadi** [comment]
This is very much by design.  This is how people can jump to sibling methods in different parts :)

**Comment by user29A** [comment]
Bit also leads to clutter when a partial class becomes very large. So skip to a desired function in a code file with 100 definitions then requires scanning through the other 1000 definitions in the other files.

The behaviour could be made optional.

**Comment by CyrusNajmabadi** [comment]
If you have a type with a thousand members, it might be time to break it up :-) <3

**Comment by user29A** [comment]
It's for a form project where they all perform on the single task at hand.

**Comment by user29A** [comment]
In fact, the behavior I am discussing is the behavior when the Form project is written in C++.net, which has a header file to which you can #include multiple code files to where the callbacks are defined. Partial classes sort of do the same thing as #include...but then you get the unwanted behavior as discussed. In C++.net winforms projects, when you are editing the included file which contains the callbacks for the form, it only lists the functions in the file.

**Comment by CyrusNajmabadi** [comment]
As mentioned above, this is by design.  The navbar has had this behavior since 2005 where this was deliberately done precisely to allow people to navigate between parts of type exactly so that people can get to the rest of their members.  It's not meant to be a structural search, but a symbolic one.

Note: if you want to quickly navigate structurally, you have a few options at your disposal.  You can collapse to definitions and just go to the one you care about (the collapsed definitions will form a syntactic list like what you're asking for in nav bar).

You can also use go-to-all, but filtered to file scope which can then let you search by name, while only finding results in that file:

![image](https://user-images.githubusercontent.com/4564579/142485357-ee848e9d-e0a9-4b62-aeed-8f16c4ca6047.png)

**Comment by user29A** [comment]
Yes, this still places us back to the request, because the behavior is different for C++.net projects which use other code files to define functions which are declared in the header file, and the other code files will list only the functions which they contain. This is quite helpful because as the various code file grow so large, the scroll list navbar become unnavigable.

So what is being requested is that the navbar optionally replicate its behavior as it performs it for C++ projects, but for C# projects which are basically doing the same thing with partial classes and separate code files as opposed to a header file and separate code files.

Collapsing the entire document to definitions isn't as efficient as the navbar and its behavior in C++ project files, because the navbar conveniently lists the functions alphabetically.

Another problem with the navbar in C# partial class winform projects is that it also lists all of the definitions for the objects on the form, whereas typically what one is interested in, and how it worked with C++ projects, is to only list the function and callback definitions, as typically one would never need to navigate to the definition of a Form object control.

Thus, there's lots of room here for improvement and making the behavior optional. The navbar become ineffective when it lists 1000 other functions from other files, but you wish to only nav through the few dozen function definitions of the particular file you have open where you know a function will exist due to organizational logic.

Thanks!

**Comment by CyrusNajmabadi** [comment]
C++ and C# do not do the same thing here.  As mentioned, it is intentional in C#'s part to not hide this information and to make it possible to get to all members from a single nav bar.  If C++ chooses differently, that's their choice here.

Note: at hte 1000 member level, you're going to have pain no matter what.  Some of your parts are simply going to be too large for many features to effectively provide a reasonable experience.  I would recommend breaking things up to separate out concerns.

**Comment by user29A** [comment]
I am talking about how Visual Studio treats the approach to its own C++ and C# projects. In terms of partial classes you have almost the exact same precise idea as a header file with separate code files.

Using separate code files for a partial class is precisely "breaking things up to separate out concerns".

However, the development environment, Visual Studio, does not reflect that intention.

Surely I am not the only C# project in the world with 1000 or more member levels? Is my project really the largest ever conceived? I am very proud, if so! Perhaps I can be given an award recognition. The Visual Studio team should be so happy that their environment can handle such a large project.

In any case, given the myriad options provided to users, it would be nice if the requested behavior were an optional setting, such as to assist code development for large files.

Otherwise, there is really no point to having partial class files, since separating out definitions into separate files doesn't actually become reflected in the development environment anyway. It would be just as well to put the 1000 definitions into the single file, since Visual Studio makes no note of it.

So perhaps I will simply put all 1000 definitions into the single file, instead of trying to organize the large project with separate files and partial class definitions.

Or, I can revert the project back to C++ and dispense with C# since the development environment doesn't really support C# partial classes anyway?

At the least, please make the behavior user-optional.

**Comment by CyrusNajmabadi** [comment]
> I am talking about how Visual Studio treats the approach to its own C++ and C# projects. In terms of partial classes you have almost the exact same precise idea as a header file with separate code files.

That's not the case.  In C++ headers and impl files are very different (including in their compilation model).  In C#, all parts are equivalently equal.  

> Using separate code files for a partial class is precisely "breaking things up to separate out concerns".

It's separating them out syntactically, but not semantically.  And we view navbars as a semantic feature (and have done so for 15+ years). :)

> Surely I am not the only C# project in the world with 1000 or more member levels? 

1000 members is *extreme*.  Enormously so.  Conventional rule of thumb would likely be to break things up as you start to get to the unwieldy point (often tahts' a couple dozen members max :)).

> Surely I am not the only C# project in the world with 1000 or more member levels? 

So, we're wary of making one-off options just for issues a tiny group has asked for (or, in this case, a single customer in 15 years).  This is a maintenance burden for us as we have to doc and maintain this, and it may cause problems later on down the line through the lifetime of these features.  We do not aim to make any and all decisions we made user controllable just because a single person finds it not helpful for their use case.  Rather, we want options when there is often a much more reasonable split of users (like 70/30), with no clear view on what is the 'right' single way to do things. 

 > At the least, please make the behavior user-optional.

We can consider it.  But it will likely take a lot more feedback from the rest of the community that there's an issue here for this to realistically happen.  Thanks for the feedback though!  We'll keep this on the backlog to see if things change in teh future :)

**Comment by user29A** [comment]
Thanks CyrusNajmabadi,

However, you cannot possibly tell me that navigating to a form control definition is actually useful. There is almost no scenario where one would need to navigate to the declaration of a form control in the Form1.Designer.cs file.

Honestly I think you're deflecting from what is an apparent weakness of the environment. At least the navbar should not have all of the form control definitions also listed.

Would you like help making the improvements? Make me a part of the project and I can have a look at the way that the navbar is populated, and see if there are some simple things that could be done to make is more selective and useful rather than global and not useful. I would be happy to help!

This failing of the navbar really does make the C# development environment in VS difficult to want to keep using. I recently ported the project from C++.net winforms, and now it is much more difficult to manage. Perhaps the C++ team has more experience making working with large projects more efficient, and C# isn't really intended for complex programs, etc.

Thanks! As I said - if you need help, if you would like me to look at how the navbar is populated and if there are some simple things that could be done to improve it and make it useful, let me know! Glad to provide assistance :)

**Comment by CyrusNajmabadi** [comment]
> However, you cannot possibly tell me that navigating to a form control definition is actually useful. There is almost no scenario where one would need to navigate to the declaration of a form control in the Form1.Designer.cs file.

I commonly do this.  

> Honestly I think you're deflecting

I have not deflected.  I've answered honestly how we view these areas, and what our bar is for adding options for certain scenarios.  The item was not closed, but was put on the backlog, which is where we put issues that may be done in the future if the priority on it rises.

> Would you like help making the improvements?

In this case, thsi is not a bug-fix, this is a feature request (esp. as there is a request for a new option to be made).  So the question is not about being able to resource the work.  The question is about if this is the right thing to do for the product.  As i mentioned above, options are introduced *sparingly*, and not just to deal with a single complaint from one person over 15 years.

> Thanks! As I said - if you need help

Help is always appreciated.  If a design can be made here that doesn't regress important scenarios we care about, then we could be amenable to it.

**Comment by user29A** [comment]
Appreciated!
