### ISSUE TITLE
Select builder item if nothing in the CompletionList matches what user typed

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn#57846]
We could potentially soft-select it (though we need to try that out to be sure).  However, we must not soft select it in the case where the user has written something that would match against one of the items in the list.  for example, it's very common for me to write things like:
 
 
![image](https://user-images.githubusercontent.com/788783/142336992-fb7acab6-ef36-4662-bace-c5114b1fb90e.png)

 
Here i'm writing 'bb' because it will camel-case match against the offered items, allowing me to quickly tab this out to be:
 
![image](https://user-images.githubusercontent.com/788783/142337009-24e23cc9-e733-4467-a333-d3d722c7426a.png)

 
 
That's a core muscle memory feature we've had for a while that allows really quick generation of names provided very little user typing.  If we soft select 'bb' here, this will 100% break me (and other users who do this).

**Comment by sharwell** [comment]
The soft selection of an item which is not the builder item is intentional. It serves two purposes:

1. It allows the user to type any item uninterrupted (via the builder).
2. It allows the user to tab-complete a different item _or_ use the <kbd>&uarr;</kbd>/<kbd>&darr;</kbd> keys to select a different item starting at the soft-selected item (as opposed to forcing it to start at the top of the list). This is beneficial because the soft-selected item "sticks" to the last known good suggestion as soon as the user types a character which eliminates all matches.

For the specific situation of suggesting names for new variables, the completion list will always contain one or more matching items once #55593 is implemented, so there might not be any need to proceed with this change.

**Comment by AmadeusW** [comment]
I agree with @sharwell.
Hitting space accepts whatever user typed
Hitting tab picks last selected item from the list
Trivial example of where this is useful, is where I make a typo:
![completiontypo](https://user-images.githubusercontent.com/1673956/144302315-b061f24d-c795-4f8e-ba1f-1862c1d1ff5e.gif)
I see the whole line completion in its current state as a separate interaction.
If it was integrated into completion list, then hitting Tab to complete the "whole line" item would be consistent with the existing experience.
