### ISSUE TITLE
confusion over whether string is nullable

### ISSUE THREAD

**Issue by DickBaker** [dotnet/roslyn#57974]
**Version Used**: 
VS2002 (64-bit)-Preview v 17.1.0 Preview 1.1

**Steps to Reproduce**:

in my console app [where the .csproj file includes "&lt;Nullable&gt;enable&lt;/Nullable&gt;"] I have a line
foreach (var line in File.ReadLines(fil))

**Expected Behavior**:
the docs state "public static IEnumerable&lt;string&gt; ReadLines(string path)", so the implicit type should be "string"

**Actual Behavior**:
hovering over the "var" token you get "class System.String" whereas hovering over the "line" variable gives "(local variable) string? line"

because the docs state "IEnumerable&lt;string&gt;" and not "IEnumerable&lt;string?&gt;", the returned value cannot be null (if the source text file has a blank line with no whitespace enumerator would simply return string.Empty and never null). Ditto the enumerator would never return an explicit null even at EOF.

As a workaround I have now explicitly defined my line variable with "string line" [and I don't seem to get any noise from analyzers], but  imho Roslyn hasn't smelled the right coffee on this one.

**Comment by RikkiGibson** [comment]
See the following for why 'var' declarations are nullable when the type is a reference type:

https://github.com/dotnet/csharplang/blob/main/meetings/2019/LDM-2019-12-18.md

**Comment by RikkiGibson** [comment]
FWIW, this question has come up many times. It might be worth the reduction in developer confusion to simply make the variable type the same as the expression type, and refrain from giving the CS8600 "non-safety" warning when assigning 'null' into such variables.

**Comment by sharwell** [comment]
> It might be worth the reduction in developer confusion to simply make the variable type the same as the expression type

The real alternative here is to use flow analysis to determine if any later assignment to the same variable involves a maybe-null value, and only infer a nullable type if that is the case. We have the option of implementing this alternative in the UI layer (i.e. part of resolving Quick Info), since we already need the ability to make this determination as part of #41243.

**Comment by RikkiGibson** [comment]
> The real alternative here is to use flow analysis to determine if any later assignment to the same variable involves a maybe-null value, and only infer a nullable type if that is the case

I think this could be done using the infrastructure we already have to reinfer the nullability of type arguments during flow analysis. In the compiler layer the local symbol would always have an annotated type, but in public API it could have whatever best type we determined through flow analysis.

I don't think this would be more expensive, because we already have to do a nullable analysis when you query about things inside a method body with nullable enabled.

**Comment by CyrusNajmabadi** [comment]
@RikkiGibson That would be nice.  Note: if that causes breaks for some reason, it might warrant adding new fields to TypeInfo to expose the differences.  So there would be three values:

1. Type, without any concept of nullability.
2. The type, including nullability, wrt to the language rules, ignoring flow analysis.
3. The type, including nullability, looking at flow analysis results.

**Comment by RikkiGibson** [comment]
Let's give it a try. Opened #58645.
