### ISSUE TITLE
Broken double-checked locking (data race) in RazorDocumentServiceProviderWrapper

### ISSUE THREAD

**Issue by chselab** [dotnet/roslyn#58004]
**Version Used**: 
dac98b9 (latest commit on the main branch as of this writing), the most recent commit to the document is 0e94007

**Steps to Reproduce**:
The code of [RazorDocumentServiceProviderWrapper](https://github.com/dotnet/roslyn/blob/0e940070b483a1631cb2dd8f86716a8de573c454/src/Tools/ExternalAccess/Razor/RazorDocumentServiceProviderWrapper.cs) is formally incorrect in terms of parallelism. It applies the double-checked locking pattern without marking the respective fields as `volatile`.

**Expected Behavior**:
One possible solution is marking the fields `_spanMappingService`, `_excerptService`, and `_documentPropertiesService` as `volatile` to conform to C#'s memory-model.

**Actual Behavior**:
Formally incorrect, see [Exploring the Singleton Design Pattern (docs.microsoft.com)](https://docs.microsoft.com/en-us/previous-versions/msp-n-p/ee817670(v=pandp.10))

**Comment by sharwell** [comment]
Per @stephentoub:

> Entering a lock has read acquire semantics and exiting a lock has store release semantics

In the context of this issue, let's examine the access of `_spanMappingService`. Since `_spanMappingService` is only written inside a `lock (_lock)`, we know that exiting that lock region will have store release semantics. When a thread later enters the `lock (_lock)` region, it will have read acquire semantics, and thus cannot have a stale read of the `_spanMappingService` field. Together, this means the current double-checked locking approach does not need to use explicit volatile operations to achieve correctness.

This statement is not meant to be a claim that the current code is optimal and/or cannot be simplified. It is merely a statement that the formal correctness is not a problem as suggested by this issue.

**Comment by sharwell** [comment]
On further review, there does appear to be a problem in theory (not in practice) related specifically to the return. Consider the following:

```csharp
if (x is null)
{
  lock (_lock)
  {
    if (x is null)
      x = new Value { A = 3; };
  }
}

return x;
```

Notice how it's possible to reach `return x` without entering the lock.

There are two theoretical problems with the above code under strict adherence to ECMA rules:

1. In the absence of a volatile write to `x`, ECMA would allow a write as part of an object initialization (e.g. `A = 3`) to be reordered relative to the write to `x` itself. If this occurred, it would be possible for `return x` to observe a non-null `x` which has not been fully initialized. In practice, however, current implementations of the runtime do not allow the reordering of object initialization writes past the assignment of the reference itself.
2. In the absence of a volatile read of `x`, ECMA would allow the read as part of the `return x` to be reordered with respect to the read of `x` in the null check. The resulting runtime code might look like this:

    ```csharp
    var tmp = x;
    if (x == null)
    {
      // this block is not entered...
    }

    return tmp;
    ```

    While possible in theory, current runtimes do not allow this reordering to occur. @stephentoub mentioned that certain Itanium builds may have allowed this reordering at some point, but large amounts of real-world code would start to break if this reordering ever started to occur in practice.
