### ISSUE TITLE
Source generators don't work with visual studio 2022

### ISSUE THREAD

**Issue by musictopia2** [dotnet/roslyn#58000]
I created the most simple source generator here
https://github.com/musictopia2/FailedGeneratorSample 

I used the sample from https://docs.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/source-generators-overview

Even though I followed step by step, I get a runtime error saying "No defining declaration found for implementing declaration of partial method 'Program.HelloFrom(string)"

Would be disappointing if source generators don't work anymore except for what was already compiled.

**Comment by Youssef1313** [comment]
The error you're getting is *not* a runtime error. It's a compile time error, and it's an error in the generated code, meaning the code was actually generated and the source generator is indeed run.

The problem is the source generator code has a bug, it's trying to enclosing the `Program` class in a namespace. So this is a doc bug.

**Comment by Youssef1313** [comment]
To be more clear, either the generated needs to handle the class being in the global namespace, or just enclose your `Program` class in a namespace.

**Comment by musictopia2** [comment]
Its a doc bug then.  Because I started out by copying the code from the docs.

**Comment by musictopia2** [comment]
The docs needs to be updated to show how it would work with a console app that is using the new top level statements.
