### ISSUE TITLE
Provide access to semantic model during filtering phase of incremental source generator

### ISSUE THREAD

**Issue by CollinAlpert** [dotnet/roslyn#58112]
I am trying to port my existing Source Generators to the new Incremental Source Generators. Currently I am relying on a bunch of `ISyntaxContextReceiver`s to discover types on which the Source Generators perform actions for. I am also relying on the `SemanticModel` to check attribute's namespaces etc.

From what I understand, the `predicate` passed to `incrementalGeneratorInitializationContext.SyntaxProvider.CreateSyntaxProvider` is supposed to be fast and filter out types which are needed as soon as possible so the generator does not need to perform more work than strictly necessary. 
However, the predicate does not give me access to the semantic model, only the `transform` function does this. This leaves me with having to filter out unwanted types a step later than I would like, since I only have access to the semantic model then. This doesn't seem ideal, since it doesn't exclude as many types as possible initially and also it feels a bit weird to do filtering in the "transform" step.

I am wondering if this is the "correct way" to do it if one needs access to the semantic model and if so, why this design was intentional. Or is it something which wasn't considered because of missing use cases?

**Comment by jaredpar** [comment]
@chsienki

**Comment by chsienki** [comment]
Yes, this is by design and you're using it correctly. 

From our experience with the `ISyntaxReceiver` implementations we know that syntax discovery is often the most expensive part of a generator. By splitting it out we can actually be more efficient. The first lambda allows the compiler to know *which* syntax you (might) be using. Most edits result in only a single syntax tree changing (such as typing in a different file in the IDE) we can know that the syntax hasn't changed in the other files, so there is no need to re-walk their trees (which is expensive).

The second lambda then lets you analyze the collected nodes with the semantic model. This can't be cached: typing in one file can change the semantic meaning of a node in another file, so any time any syntax changes we have to re-run the transformation for each selected node.

In the pathological case of the first lambda just being `return true` we can still be more efficient as we don't have to re-walk the trees of each file in order to run the second lambda where you have access to the semantic model.

**Comment by CollinAlpert** [comment]
That makes sense, thanks a lot for the clarification!
