### ISSUE TITLE
GetEnumerator pattern with a ref returning 'this ref' extension method 

### ISSUE THREAD

**Issue by NinoFloris** [dotnet/roslyn#58122]
I didn't see any specific example in the test plan (https://github.com/dotnet/roslyn/issues/43184) for the case where you add an extension method onto a mutable struct for the sole purpose of making it iterable with foreach.

I'm explicitly interested in this for ref structs wrapping a SequenceReader, which is a mutable struct itself, allowing you to wrap the byte parsing into something a bit higher level to iterate over blocks/messages/frames.

Think in the direction of this example (restartability could be achieved via dispose):
```cs
public ref struct ProtocolReader
{
    // This could also be the SequenceReader keeping this state.
    int _consumed; 
    bool MoveNext() {
        consumed++;
        return true;
    } 
    int Current => 0;
} 

public static class ProtocolReaderExtensions
{
    public static ref ProtocolReader GetEnumerator(this ref ProtocolReader reader) => ref reader;
}

// Errors today at the foreach with [CS1510] A ref or out value must be an assignable variable.
// Isn't reader an assignable variable?

var reader = new ProtocolReader();
foreach(var message in reader) {}
```

Is this an oversight or a real limitation?

**Comment by jaredpar** [comment]
I believe this is likely an oversight as the goal of the [extension enumerator](https://github.com/dotnet/csharplang/blob/main/proposals/csharp-9.0/extension-getenumerator.md) was to expand the set of applicable `GetEnumerator` methods, not change what is or isn't considered legal. Given that you can have a [ref returning GetEnumerator today](https://sharplab.io/#v2:EYLgtghglgdgNAFxFANgHwAICYCMBYAKEIDcIAnAAhQHsBjCFCgXgpgFMB3CgYQAoBKANyEAZtTJsItABYVepSrQCulWFToN+FAN6EK+ioQC+hQhgDMFAM4IyS2ggoBRHYYIGKFisGrVGAWWpiNgA5NgAPBAFmAD4KBGkyai4YJRQUYXcDL1hHbhUJGEcmOISklLSM41MCL2weHT1sywkRZwoAcTYEJ1SwNjIIBHFokvjE5NZKzKMgA=) it seems like it should be possible in the extension case. 

At the same time this is likely not going to give you the behavior that you are looking for. Even though the enumerator can be returned by `ref` it is stored in a local by value, not as a `ref` local.  

@333fred in case he remembers any extra details here.

**Comment by 333fred** [comment]
This is intentional, and we have a test verifying the current behavior here: https://github.com/dotnet/roslyn/blob/main/src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenForEachTests.cs#L4157-L4188, for exactly the reason you mentioned @jaredpar. I suppose you could do some tricks with `Span` to get a ref to the passed in value (which, in this case, is explicitly a ref struct) to make this work "safely", but until we have ref fields, I don't know about enabling this scenario. /cc @YairHalberstadt.

**Comment by jaredpar** [comment]
Upon further thinking this is more of a language request vs. compiler bug and as such closing. If there is desire to push forward with this we should open an issue on csharplang as a request. 

The reason this is a request is that it has larger impacts. Consider that once we have a `ref` local then it impacts other items like lambda capture, async methods, etc ... It effectively prevents those from being used because there is no way to capture a `ref` here. That needs to be considered.
