### ISSUE TITLE
Renaming file(with type) freezes UI

### ISSUE THREAD

**Issue by DavidKarlas** [dotnet/roslyn#58188]
**Version Used**: 
4.0.0-5.21479.6+91a7a90557a9bd8e8e120d1899f077077c829ce6

**Steps to Reproduce**:

1. Rename C# file that contains type with same name in huge .NET Framework solution
2. When dialog appears confirm that you want to rename type
3. IDE freezes for multiple seconds, without dialog to cancel it

**Expected Behavior**:
Wait dialog should appear which offers cancellation of rename.

**Actual Behavior**:
Visual Studio just freezes until rename is complete.

**Solution**:
Put `IVsThreadedWaitDialog` around [AbstractCodeModelService.cs#L497](https://github.com/dotnet/roslyn/blob/8751f99/src/VisualStudio/Core/Impl/CodeModel/AbstractCodeModelService.cs#L497) and pass `CancellationToken` to `Renamer.RenameSymbolAsync`.

**Comment by DavidKarlas** [comment]
This was created by me(working on .NET Framework Project System(old one written in C++)) and we are talking via COM aka. CodeModel.

So we have two options:
1) Do `IVsThreadedWaitDialog` inside this code as proposed above.
2) Introduce new CodeElement3 interface that adds new version of [RenameSymbol](https://docs.microsoft.com/en-us/dotnet/api/envdte80.codeelement2.renamesymbol?view=visualstudiosdk-2022#EnvDTE80_CodeElement2_RenameSymbol_System_String_) that accepts some kind(COM) of cancellation token.

**Comment by ryzngard** [comment]
Adding a thread await dialog here is tricky. If we want to fix this a new interface is probably. @jasonmalinowski what do you think?

**Comment by DavidKarlas** [comment]
There is also option 3 I guess, which is, figure out Rename to be so much faster we don't have to do this :D

**Comment by jasonmalinowski** [comment]
I would be hesitant to add a threaded wait dialog into that code simply because it's a public API that may very well have other callers. Displaying a thread-wait dialog may be problematic since other callers may already be displaying their own; respecting cancellation from our own displayed dialog might mean other features wouldn't know the triggered rename can be cancelled and might break as well.

The "native" project system does still have some components in managed code that live in Microsoft.VisualStudio.CommonIDE; I'd be curious what an estimate would look like to put code there to call the public Roslyn API, and then there's just a private API between the native project systems and that so we don't have to manage another cross-repo private API.

I'd also hesitate to recommend any extensions to the CodeModel API, simply because that's not aligned with any future goals we have for VS Extensibility; unless we're planning to finally 100% deprecate csproj/msvbprj soon, you're probably going to end up with having to eventually call our managed code directly...it might just be better to do that now and pull off the bandaid.

**Comment by sharwell** [comment]
Resolving as external. Code which uses CodeModel APIs _will_ cause UI delays. Roslyn maintains its implementation for functional compatibility only, but all performance issues arising from this can only be fixed by eliminating the use of the API (alternatives have been available for many years).
