### ISSUE TITLE
How do i update roslyn for Visual Studio 2015

### ISSUE THREAD

**Issue by wanton7** [dotnet/roslyn#5819]
Issue #2790 has been hitting me hard.
How do I build and install latest roslyn so that I can use it with Visual Studio 2015?

**Comment by jaredpar** [comment]
@wanton7 right now it's not possible to reinstall Roslyn on top of Visual Studio.  There is a limitation in VS that is being addressed in update 1 that will enable us to do this.  

Short term though you can just disable the compiler server so that it doesn't start up at all when building.  To do this add the following line to your csproj / vbproj file

``` xml
<UseSharedCompilation>false</UseSharedCompilation>
```

**Comment by flipchart** [comment]
@jaredpar Is this possible now? There are some issues (#12254 and #12530) which have been fixed in master that I would love to have as they are very frustrating for day-to-day work. Alternatively, when is the next VS update that includes these fixes expected?

**Comment by jaredpar** [comment]
@flipchart yes.  At this point you can clone this repo, run `Restore.cmd`, open Roslyn.sln and F5 the solution.  The resulting Visual Studio instance will reflect changes you make to the code base.
