### ISSUE TITLE
dotnet-bot gets a bit too enthusiastic

### ISSUE THREAD

**Issue by bkoelman** [dotnet/roslyn#5823]
For example, see https://github.com/dotnet/roslyn/pull/5780. It posts the same message five times in a row.

**Comment by Pilchie** [comment]
@tannergooding @mmitche - any ideas here?

**Comment by mmitche** [comment]
I think it's posting that way because it wants to launch 5 different jobs for PR which this person doesn't have access to run.  It's doing what it's supposed to.  For instance, if we wanted to allow just one of those jobs we could specify an 'allow' phrase specific to that job.  In this case though, it's saying the same thing for each of the 5 jobs.  I would argue that it could probably elide messages if they are the same, but there isn't easy way to do this.

**Comment by bkoelman** [comment]
It did not do this a few days ago. And it seems not related to the size of
the PR, as https://github.com/dotnet/roslyn/pull/5822 only applies to two
files.

**Comment by mmitche** [comment]
Hmm.  Well...if you catch it in action again, cc me on the PR and I can check the rolling logging for this component to see what it thinks it's doing.

**Comment by tannergooding** [comment]
FYI. @ManishJayaswal 

@bkoelman, we dynamically generate our jobs now and it was an issue with the netci.groovy script (I missed specifying that anyone could run the jobs). It was fixed several days ago.

Pull requests coming from the community should only be seeing this request (and only one request) for a single job which runs the Visual Studio Integration tests (and requires review of the code before running).
