### ISSUE TITLE
Move WPF tests to Xunit.StaFact

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#58237]
We might be able to run WPF tests in parallel without multi-proc by adopting https://github.com/AArnott/Xunit.StaFact.

cc @jasonmalinowski @AArnott

**Comment by jasonmalinowski** [comment]
@RikkiGibson How does that work compared to what we're doing now?

**Comment by jmarolf** [comment]
@jasonmalinowski my understanding is that StaFact's [WpfFact](https://github.com/AArnott/Xunit.StaFact/blob/main/src/Xunit.StaFact/WpfFactAttribute.cs) and [WpfTheory](https://github.com/AArnott/Xunit.StaFact/blob/main/src/Xunit.StaFact/WpfTheoryAttribute.cs) attributes are the same as ours expect much more work has been done on the runner implementation so you can actually run these sorts of tests in parallel. Our implementation does not allow for multiple tests to be run at once.

**Comment by jasonmalinowski** [comment]
I guess I'd be interested to know how that works or how it's maintaining isolation. I know the VS editor has various WPF statics in it that are initialized and then can't be used on different threads; we keep our tests on a single thread for that reason.

**Comment by sharwell** [comment]
> We might be able to run WPF tests in parallel without multi-proc 

This will break all the code we have to force test isolation through unique export providers (tests using MEF will not be able to run in parallel without sacrificing our ability to diagnose container violation errors).

**Comment by jmarolf** [comment]
> tests using MEF will not be able to run in parallel

Can you elaborate Sam? the 500 WpfFact tests we have today cannot run in parallel. How is this related? Are we re-using MEF compositions across tests? If so why?

**Comment by sharwell** [comment]
> Are we re-using MEF compositions across tests?

We do not re-use MEF compositions. We have validation that only one MEF container exists at any given time, and we force that container to be invalidated at the end of each test. This validation ensures we do not have multiple MEF containers active in a test, which can lead to extremely difficult to diagnose errors if multiple instances of an item believed to be a singleton exist.

**Comment by sharwell** [comment]
In my past investigations, I found the following:

1. There is no advantage to changing our parallelization strategy for CI (we already run tests in parallel there, and there aren't enough cores present to realize meaningful changes for a different strategy)
2. The compiler layer tests would benefit _locally_ from running in parallel, but in past work from @333fred the proposed change to allow parallel testing was rejected as it introduced a small amount of flakiness locally that did not reproduce in CI
3. Most workspaces layer tests are designed to not run in parallel. The amount of work required to pass this hurdle is vast, and does not make sense if it's going to get blocked by (1) and (2).
4. The one case where parallelization might make sense is code fix and/or refactoring tests that have already been migrated to Microsoft.CodeAnalysis.Testing _and_ do not customize `CreateWorkspaceImpl`. These tests do not need `WpfFact` and we can enable parallelization by moving them into a different xunit container (similar to how the integration tests use `[Collection(nameof(SharedIntegrationHostFixture))]`).

**Comment by RikkiGibson** [comment]
> There is no advantage to changing our parallelization strategy for CI (we already run tests in parallel there, and there aren't enough cores present to realize meaningful changes for a different strategy)

I think there's a potential correctness advantage. We recently had a bug #53080 come in where someone observed that a few different test projects were straight up not running in CI. This is because RunTests works by discovering and deciding which assemblies contain unit tests, and which classes within those assemblies contain unit tests. It turns out there were 2 separate bugs in RunTests which were causing test assemblies to get dropped on the floor.

By opening this issue I think I ended up obscuring the real goal that I had in mind. What I'm really looking for is how we can avoid reimplementing and being on the hook for things like test discovery, and also run our tests in a more consistent fashion in a variety of environments. I imagined this would happen by running directly on top of `dotnet test`. And it is indeed annoying to have to dig up one set of commands to run a single test assembly with parallelism with `RunTests`, and dig up a different set of commands to run a specific test in VS or on the command line via the Test Explorer or `dotnet test`.

It's not clear to me that parallelization via another separation mechanism like multi-proc is unworkable if we run the test assembly directly via `dotnet test`.

**Comment by jmarolf** [comment]
> This validation ensures we do not have multiple MEF containers active in a test, which can lead to extremely difficult to diagnose errors if multiple instances of an item believed to be a singleton exist.

I would appreciate it if some of this could be written down. xUnits default test collection parallelism mechanism certainly could be extended for cases where shared test context is involved and we need to communicate that to the test runner. I do not understand why this dictates that our tests must run serially. Is it just that we have a lot of technical debt because when all the test case infrastructure was written without considering parallelism? Was this a temporary workaround or is this considered the correct fix for the underlying issues?

**Comment by jmarolf** [comment]
> There is no advantage to changing our parallelization strategy for CI

Agree that there isn't likely to be better throughout but as @RikkiGibson we only have the throughput we have today because of all the work that was done to write a custom test executor. @RikkiGibson a reasonable next step is to file an uber issue and link to this one capturing all the context sam has given.

I agree with the goal of not having an extremely custom test runner that we are on the hook for maintaining, but we need to spec out all the work involved. 

At the very least I would like a tracking issue for moving all the code-fix tests to use Microsoft.Codeanalysis.Testing as that will be both more performant and have better correctness guarantees right @sharwell ?

**Comment by RikkiGibson** [comment]
Closing this issue out in favor of a higher-level discussion at #58261.

**Comment by sharwell** [comment]
> > This validation ensures we do not have multiple MEF containers active in a test, which can lead to extremely difficult to diagnose errors if multiple instances of an item believed to be a singleton exist.
> 
> I would appreciate it if some of this could be written down. xUnits default test collection parallelism mechanism certainly could be extended for cases where shared test context is involved and we need to communicate that to the test runner.

Here is some of the existing documentation:

https://github.com/dotnet/roslyn/blob/31d3e34bec4dd45cef33e0a85c5e41252e4731ed/src/Workspaces/CoreTestUtilities/MEF/UseExportProviderAttribute.cs#L24-L43

https://github.com/dotnet/roslyn/blob/31d3e34bec4dd45cef33e0a85c5e41252e4731ed/src/Workspaces/CoreTestUtilities/MEF/UseExportProviderAttribute.cs#L200-L208

https://github.com/dotnet/roslyn/blob/31d3e34bec4dd45cef33e0a85c5e41252e4731ed/src/Workspaces/CoreTestUtilities/MEF/UseExportProviderAttribute.cs#L76-L87

> I do not understand why this dictates that our tests must run serially. Is it just that we have a lot of technical debt because when all the test case infrastructure was written without considering parallelism? Was this a temporary workaround or is this considered the correct fix for the underlying issues?

It's theoretically possible to design a system that allows parallelization without sacrificing the current guarantees. However, this is _super_ non-trivial since it has to validate static fields/properties and other shared storage locations (e.g. TLS, anything hidden in the runtime, anything hidden in libraries like `ThreadHelper`) are either blocked from use in tests or implemented in a way that allows each test to see its own copy. For example, in netcoreapp3.1 testing, we could keep the shared `TestComposition` objects in a root AssemblyLoadContext, and then instantiate and run the tests within their own AssemblyLoadContext. Within a given ALC, tests would run serially, but as a whole the tests could run in parallel.

**Comment by sharwell** [comment]
> At the very least I would like a tracking issue for moving all the code-fix tests to use Microsoft.Codeanalysis.Testing as that will be both more performant and have better correctness guarantees right @sharwell ?

We're migrating them over time. Not sure a tracking issue would provide any real value here (developers wouldn't take action in response to the issue, nor would they update its progress over time). It would just be an issue that exists for the purpose of existing.
