### ISSUE TITLE
Source generated file keeps Miscellaneous Files color/message even if features are enabled

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#58329]
![image](https://user-images.githubusercontent.com/1408396/146065407-8a48d711-edc3-4fb8-806d-0e5632a957a9.png)

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/1408396/146065316-8aae167b-bab2-4f01-b1ad-24cfb0afc1c1.png)

**Comment by jasonmalinowski** [comment]
This is likely happening because even though the document is associated with the real workspace on the Roslyn side, the running document table will still say the Miscellaneous Files IVsHierarchy is owning the file. We probably need to transition the file to the IVsHierarchy and back, which if we're not careful may break the project system.

**Comment by jasonmalinowski** [comment]
@CyrusNajmabadi also hit this in solution explorer:

![MicrosoftTeams-image](https://user-images.githubusercontent.com/201340/146066388-05f4804f-c92a-40d6-870a-c7c439ae8fe3.png)

You can turn a checkbox on that shows the files owned by misc files IVsHierarchy, and that's showing that there.

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.
