### ISSUE TITLE
'is' operator reports seemingly wrong results for interface over enum array

### ISSUE THREAD

**Issue by roji** [dotnet/roslyn#58378]
In the code below, the `is` operator returns true when the generic IList parameter isn't the correct enum type:

```c#
var foos = new Foo[5];
IList<Foo> foosAsIList = foos;
Console.WriteLine(foos is IList<Bar>); // false
Console.WriteLine(foosAsIList is IList<Bar>); // true???

enum Foo {}
enum Bar {}
```

Is this somehow by-design according to the language specs?

**Comment by HobbsCode** [comment]
Also happens when comparing with IList<int> and IList<uint>. So is it just checking for compatible underlying integral type?

**Comment by ufcpp** [comment]
This is by design.

https://www.c-sharpcorner.com/uploadfile/b942f9/how-to-convert-unsigned-integer-arrays-to-signed-arrays-and-vice-versa/

```cs
var foos = new int[5];
object foosAsObject = foos;
Console.WriteLine(foos is uint[]); // compile-time. C# disallows the cast.
Console.WriteLine(foosAsObject is uint[]); // runtime. .NET allows the cast.
```

**Comment by jaredpar** [comment]
As @ufcpp noted this is by design. 

The first check is done using C# type semantics and that does not allow the specified conversion. Hence the compiler just replaces that expression with the literal `false`. The second expression though is interface to interface conversion which can only be determined by the runtime hence the compiler uses `isinst` instructions.

This is a case where the CLR allows greater flexibility than C#. The CLR allows this due to the nature of arrays hence the conversion works.
