### ISSUE TITLE
Wrong circular base type dependency errors on nested type inheritance

### ISSUE THREAD

**Issue by Blackclaws** [dotnet/roslyn#58424]
**Version Used**:  Dotnet 6.0.100

**Steps to Reproduce**:

1.  Create a file with this content:
```
    public class Test : Test.IInner.IOuter {
    
        public interface IInner : Other {

            public interface IOuter
            {
                
            }
        }
    }

    public interface Other
    {
        
    }
 ```
2.  Try to compile it

**Expected Behavior**:
Compiles without error

**Actual Behavior**:
CS0146 Circular base type dependency.

**Further Info**
This seems conditional on the first inner interface inheriting from something else. This happens neither if the double nested interface inherits nor if there is no inheritance.

If the outer type implements just the nested interface that inherits everything is fine as well.

**Comment by jaredpar** [comment]
@cston for triage

**Comment by AlekseyTs** [comment]
The error is reported because, while binding ```Test```'s bases, we are binding ```IInner```'s bases as well. Lookup triggers that binding while resolving "IOuter", it tries to look for this name within ```IInner```'s bases, that tries to resolve the "Other" and the error is reported once we try to look it up within ```Test```, which needs ```Test```'s bases and the circle completes.

In the particular scenario we can avoid an attempt to lookup "IOuter" within ```IInner```'s bases because, we first look in the ```IInner``` itself (without inheritance). If we found the type there, no reason to look for it in ```IInner```'s bases, anything found will be shadowed by the immediate result anyway. BTW, the shadowing check causes a stack overflow, see #62795.

Avoiding the error in a more general case is likely to add more complexity to circularity analysis in bases. Not sure if it is worth it.

**Comment by Blackclaws** [comment]
I think if you know of more general cases where this would fail even though it shouldn't it might be worth fixing it. I also wonder how often this sort of resolution logic would be called. I can't really say how compilation times might be affected either.
