### ISSUE TITLE
IAsyncEnumerable codegen doesn't properly cleanup after end of iteration which causes memory leaking

### ISSUE THREAD

**Issue by hez2010** [dotnet/roslyn#58444]
**Version Used**: .NET 6.0.1

**Steps to Reproduce**:
Given this code:
```csharp
using System;
using System.Collections;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Test
{
    class Program
    {
        static async Task Main()
        {
            {
                var weakRefs = new List<WeakReference<Foo>>();
                var r = new AsyncReader();
                await foreach (var i in r)
                {
                    weakRefs.Add(new(i));
                }
                GC.Collect();
                foreach (var i in weakRefs)
                {
                    Console.WriteLine(i.TryGetTarget(out _));
                }
            }
            {
                var weakRefs = new List<WeakReference<Foo>>();
                var r = new AsyncReader();
                foreach (var i in r)
                {
                    weakRefs.Add(new(i));
                }
                GC.Collect();
                foreach (var i in weakRefs)
                {
                    Console.WriteLine(i.TryGetTarget(out _));
                }
            }
        }
    }

    class Foo
    {

    }

    class AsyncReader : IEnumerable<Foo>, IAsyncEnumerable<Foo>
    {
        IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();

        public IEnumerator<Foo> GetEnumerator()
        {
            yield return new Foo();
            yield return new Foo();
            yield return new Foo();
        }

        public async IAsyncEnumerator<Foo> GetAsyncEnumerator(CancellationToken cancellationToken = default)
        {
            await Task.Delay(100);
            yield return new Foo();
            await Task.Delay(100);
            yield return new Foo();
            await Task.Delay(100);
            yield return new Foo();
        }
    }
}
```

The `IAsyncEnumerable` doesn't set `current` to `null` after end of iteration, which prevents GC from collecting and causes memory leaking, while `IEnumerable` can properly handles it. The performance impact can be huge especially while using `Channel<T>`, please consider fixing this behavior.

Related: https://github.com/dotnet/runtime/issues/63006

**Expected Behavior**:
```
False
False
False
False
False
False
```

**Actual Behavior**:

```
False
False
True
False
False
False
```

**Comment by jaredpar** [comment]
@jcouv

**Comment by jcouv** [comment]
I have a fix pending. You're right, I think it's correct to expect the async-iterator state machine to clear the `Current` item when the enumeration ends.

However I want to call out that the fix won't fix the case described in OP because of a JIT/GC subtlety.
The JIT uses a local for the item (line `weakRefs.Add(new(i));`) and the JIT is free to extend the life of locals beyond their scopes. So `GC.Collect()` *may* not be able to collect one of the items if it's still held in a local (a register in my experiment). 
The code can be modified around that, by extracting the `await foreach` enumeration into a non-inlinable method, so that we can guarantee that the local is gone before `GC.Collect()`.

Looking at the second part of the OP code (that pertains to a non-async iterator), for whatever reason, the JIT didn't decide to extend the life of that local, so it happens to work, but that's not guaranteed.
