### ISSUE TITLE
Struct ': this()' initializers should not have definite assignment errors

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#58790]
Started poking at this scenario a bit and I observed what I think is a bug. [SharpLab](https://sharplab.io/#v2:EYLgtghglgdgNAExAagD4AEBMBGAsAKAPQGYACAZwBcAnAVwGNLSBlAgbwNK9NiYA9SAXlLYA3J269SAT3GF83UgHolFABYB7WgBsEpYAFNSEbdo0B3AwglcVpAA4HqaiPfKkABiFKU1UcgAUAJQe6lq6+kYA5L7+QqQIBgBmEDqUolE2yqq+BjCkdPlJUAYRsFCUUCZQAF5O5FkkLAFS0kGk3rGBQVkcCtwAvgQDQA=)

```cs
public struct S
{
    int x = 1;
    int y;

    // should be allowed
    // perhaps `: this()` should be 'this = default;'
    // then run field initializers
    public S(int y) : this()
    {
    }
}
```

Tagging @cston

_Originally posted by @RikkiGibson in https://github.com/dotnet/csharplang/issues/5552#issuecomment-1010460568_

**Comment by jaredpar** [comment]
I believe that it is correct that this is not allowed when there is at least one field initializer and no explicitly declared parameterless constructor. The syntax here is using the chaining syntax which implies that the parameterlesss constructor is being called. 

Yes prior to C# 10 we allowed this syntax even though we did not allow, nor did we actually call a parameterless constructor. At the same time we didn't allow field initializers hence replacing `: this()` with effectively `this = default` was a transparent change. That is not the case anymore because we do allow parameterless constructors and in the presence of field initializers they do have an impact on the execution of the program. 

Consider the following:

```c#
struct S {
  int x = 42;
  S(int y) : this() {
    Console.WriteLine(x); 
  }
}
```

If we allowed the syntax I think the expectation from customers is that the constructor printed out `42` not `0`. If it did print `0` though why should the output change if I add an explicit parameterless ctor to the type:

```c#
struct S2 {
  int x = 42;
  S2(int y) : this() {
    // Why should this print 42 but S(int) prints 0? 
    Console.WriteLine(x); 
  }
  S2() { }
}
```

Overall I think the behavior here is correct. The [LDM notes](https://github.com/dotnet/csharplang/blob/main/meetings/2022/LDM-2022-01-03.md) don't explicitly call out this scenario but they are clear that all parameterless ctor must be explicitly declared in the presence of a field initializer. I think this scenario follows from that. Happy to check with LDM later though.

**Comment by jaredpar** [comment]
@cston pointed out to me that the output is always `42` because we are going to execute the initializers either way. 

At the same time I still believe this is the right decision based on the LDM discussion.

**Comment by RikkiGibson** [comment]
I don't agree that this behavior is correct. Presence of `: this()` should have the effect of making `this` definitely assigned at the start of the constructor body, regardless of whether `this()` refers to the default value type constructor, or if it refers to any parameterless struct constructor (the synthesized ones are no longer in the language, but also a user-defined one would apply here).

**Comment by RikkiGibson** [comment]
I think this is still a bug even if dotnet/csharplang#5737 is shipped in C# 11.

**Comment by RikkiGibson** [comment]
It looks like the behavior might have been introduced in #54811. However, it's not clear how the reading of the related [spec section](https://github.com/dotnet/csharplang/blob/main/proposals/csharp-10.0/parameterless-struct-constructors.md#executing-field-initializers) indicates that the `this()` default value type constructor should not run.

**Comment by RikkiGibson** [comment]
We've discussed offline and we feel the behavior is acceptable for C# 10, but the spec should be updated to make it clear what's happening.

**Comment by 333fred** [comment]
Discussed in LDM 03/30: https://github.com/dotnet/csharplang/blob/main/meetings/2022/LDM-2022-03-30.md.
Decision: No error, zero fields before running initializers. Look into code style options to alert users to the redundant `: this()` initializers in C# 11.
