### ISSUE TITLE
Missing CS8970 when applying attribute class having unsupported type arguments from containing type

### ISSUE THREAD

**Issue by akarpov89** [dotnet/roslyn#58837]
**Version Used**: 
sharplab.io main 6 Jan 2022

**Steps to Reproduce**:
Compile the following code:

```csharp
using System;

[A<(int A, int B)>.B]
class C
{
}

class A<T>
{  
  public class B : Attribute
  {
  }
}
```

**Expected Behavior**:
Error CS8970 on attribute application.

**Actual Behavior**:
No errors.

**Comment by jcouv** [comment]
@RikkiGibson Assigned to you for triage. Thanks

**Comment by Youssef1313** [comment]
@RikkiGibson What are the exact rules of this? I'm interested in taking a look.

It also looks like this is currently allowed in `typeof`, should it be disallowed there as well?

**Comment by RikkiGibson** [comment]
It looks like we are missing a number of checks on the containing type of an attribute.

[SharpLab](https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLR2RVUBeivBwCWANgCaoC2UAxgBZEB2KAPgAIBMAjALABQ/TgAIAwgHtGMKEwgIAPABUAfPwDe/IZqEBtAIIwY85QF0hAejNDZCMQmRCo9iAA8ADhBowIZDVuEjePi0hdSCtAF9fTSidfUNxSWlmIyUAOjiEUwshZDoxOHIrBBsEABohQhghMjEURgByGBj/DhjQ4Mi+TsEOIQzFJSEQPoMEIkqIEKFuvmEMhKkZFLVosM02AGYhOdGhkcNxuC82mODNoQUhADUoEjhJ1SEAcwgYAG4c14/Ojv5woA===)
```cs
using System;

class Container<T>
{
    [Attr<T>] // errors as expected
    class C1
    {
    }
    
    [AttrContainer<T>.Attr] // should error, but doesn't
    class C2
    {
    }
}

class Attr<T> : Attribute { }

class AttrContainer<T>
{  
    public class Attr : Attribute
    {
        public T Value { get; set; }
    }
}
```

I think the checks that occur here should change from occurring just on the immediate type's type arguments, but also on the type arguments of containing types. Not certain whether we need to defend from the possibility of the containing type itself being `dynamic`, `nint`, etc. here. We definitely block stuff like `[MyType?.MyAttribute]` because we just won't parse it.

https://github.com/dotnet/roslyn/blob/255e967640f66ad8a0861e75e9f8eb154d667060/src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs#L1166-L1177
