### ISSUE TITLE
Provide setting to hide "var" visually and replace it with the explicit type

### ISSUE THREAD

**Issue by FreyAtGit** [dotnet/roslyn#58995]
It is currently possible to show the explicit type AFTER the "var" keyword in VS 22. I would like to improve it some more so that "var" is not even visible and not taking the space.
In addition, it should have a slightly different visualization so that you see that this is just a visual replacement.
And a code-fix for changing it from var to explicit type would be nice.

![image](https://user-images.githubusercontent.com/98160615/150521690-9f9f1035-56e7-40d5-8b10-ffe293605ad8.png)

**Comment by CyrusNajmabadi** [comment]
> And a code-fix for changing it from var to explicit type would be nice.

That code-fix already exists :)

**Comment by Youssef1313** [comment]
I'm feeling it would be pretty odd if an actual code in source is hidden.

**Comment by CyrusNajmabadi** [comment]
> more so that "var" is not even visible and not taking the space.

We tried this, but it does work well.  If you want to then go edit things, the experience is very funky given tehre are two textual sources of truth.

Note: if you have inline-hints off, but use alt-f1 to *ephemerally* show the hints, then we will overwrite 'var' in this manner.  but that's just because it's ephemeral, there's no concern about how typing could interfere with things.

**Comment by CyrusNajmabadi** [comment]
Subsumed by the fixer and inline-hints.
