### ISSUE TITLE
RE0001 improperly handles string formatting hole in source suppression

### ISSUE THREAD

**Issue by stephentoub** [dotnet/roslyn#59072]
**Version Used**: 
Version 17.1.0 Preview 4.0 [32120.378.d17.1]

**Steps to Reproduce**:

1. Create a new C# project.
2. Add this code:
```C#
using System.Text.RegularExpressions;

var r = new Regex("[abc");
```
3. Suppress the rule in source.

**Expected Behavior**:
Triggers the RE0001 warning about the malformed regex and injects a suppression like this:
```C#
using System.Text.RegularExpressions;

#pragma warning disable RE0001 // Regex issue: Unterminated [] set
var r = new Regex("[abc");
#pragma warning restore RE0001 // Regex issue: Unterminated [] set
```

**Actual Behavior**:
Triggers the RE0001 warning about the malformed regex, but injects a suppression with an improperly string formatted argument:
```C#
using System.Text.RegularExpressions;

#pragma warning disable RE0001 // Regex issue: {0}
var r = new Regex("[abc");
#pragma warning restore RE0001 // Regex issue: {0}
```
<img width="811" alt="image" src="https://user-images.githubusercontent.com/2642209/151093964-569b295f-c274-45eb-9e8d-b40a3bea1640.png">

**Comment by stephentoub** [comment]
cc: @CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
Super weird.  Not sure how suppressions work at all actually.  @mavasani thoughts on what could cause this?

**Comment by mavasani** [comment]
The issue is here: https://github.com/dotnet/roslyn/blob/315c2e149ba7889b0937d872274c33fcbfe9af5f/src/Features/Core/Portable/EmbeddedLanguages/RegularExpressions/AbstractRegexDiagnosticAnalyzer.cs#L30-L31

Fix is to ensure that the `title` argument to the base constructor initializer does not have any format specifiers.

The Regex analyzer specifies the same string as the message format and the title, i.e. `Regex issue: {0}`. It is fine for message format to have format specifiers as the individual diagnostic instance reported by the analyzer would supply the message arguments to be substituted in place of the format specifiers. However, the title string should never have any format specifiers, as the title is metadata attached to the descriptor, which is not changed for each diagnostic instance.

The preview for code fixes shows `{DiagnosticId}: {Message}`, which is `RE0001: Regex issue: Unterminated [] set` here, with `Unterminated [] set` being the message argument. The suppression code fix adds the descriptor's title as the comment at the end of the the pragma directive: `#pragma warning disable {DiagnosticId} // {Title}`, which is `#pragma warning disable RE0001 // Regex issue: {0}`

**Comment by Youssef1313** [comment]
I opened https://github.com/dotnet/roslyn-analyzers/issues/5819 since I've seen this bug a lot while code reviewing.
