### ISSUE TITLE
Create more thorough determinism E2E tests

### ISSUE THREAD

**Issue by tannergooding** [dotnet/roslyn#5912]
We need an E2E test for the new compiler deterministic flag. The feature itself is currently broken for the E2E scenario and we need a test to validate that it is working (once the fix comes out) and continues to work moving forward.

**Comment by tannergooding** [comment]
FYI. @dotnet/roslyn-compiler, @ManishJayaswal, @tmat

**Comment by jaredpar** [comment]
The basics of this test need to be the following:

1. Create a project with a representative set of code samples from the language.
2. Compile the project with determinism enabled. 
3. Record the hash of the ouput binary
4. Rebuild 
5. Ensure the hash of the newly created binary matches the one from step 3

**Comment by TyOverby** [comment]
Are there examples of these end-to-end tests in the repo somewhere?  

What do you think is a "representative set" of code samples?

**Comment by jaredpar** [comment]
@TyOverby 

> Are there examples of these end-to-end tests in the repo somewhere?

no.  That's part of the fun of this bug :smile:  

> What do you think is a "representative set" of code samples?

Mostly the set of features that gave us issues with determinism: anonymous types, dynamic, and a few others.  @gafter will have the full set.

**Comment by tmat** [comment]
Why don't we compile Roslyn with /deterministic?

**Comment by jaredpar** [comment]
@tmat we will be very soon (today hopefully).  Until we get the native change though it won't help much because we'll still be non-deterministic on the PDB info.

**Comment by tmat** [comment]
I mean as a test. Ignoring PDBs.

**Comment by tmat** [comment]
(We can also switch on Portable PDB)

**Comment by jaredpar** [comment]
@tmat I've thought about that.  I don't think it would work for any of our current scenarios because it would break our dev experience.  Even on Jenkins not having a real PDB would eliminate line numbers from test failures (which are very valuable).  

Possibly though we could have another job which just built Roslyn using Portable PDB ,stashed the results, rebuild using Portable and verified the hashes were the same ...

**Comment by tmat** [comment]
Yeah, that's what i had on mind. We don't need another job though, we can do it for Mac and Linux.

**Comment by jaredpar** [comment]
@tmat that's a good idea.  May want to limit it to Linux for now as it's a bit more stable (uses CoreCLR).  But yeah that's very doable.

**Comment by gafter** [comment]
> Mostly the set of features that gave us issues with determinism: anonymous types, dynamic, partial, and a few others. @gafter will have the full set.

See #372 for a checklist.

**Comment by TyOverby** [comment]
Would it be safe to say that Roslyn uses these features and could *be* the test by doing a deterministic test on Linux?

**Comment by jaredpar** [comment]
@TyOverby it's a potential short term solution.  Long term we need an actual definitive test.

**Comment by TyOverby** [comment]
Ok.  I'm not sure what the long-term solution would be though.  Take the float parsing bug as an example.  That one simply wouldn't have been found if we only tested on 64-bit machines.  I'd imagine that in order to test determinism _correctly_, we'd need 3 * 2 computers (linux, osx, windows) * (32-bit, 64-bit) and compute the hash on each in order to verify that there weren't any platform-dependent non-deterministic bits.

I'll bring this up with my meeting with Tanner today.

**Comment by gafter** [comment]
I doubt Roslyn exercises some of the issues with anonymous types and/or netmodules.

**Comment by jaredpar** [comment]
Several of the tests have been added.  Rest can be safely added in 1.2 hence moving.
