### ISSUE TITLE
Nullability analysis could be improved after ReferenceEquals checks

### ISSUE THREAD

**Issue by drieseng** [dotnet/roslyn#59157]
**Version Used**: 
VS 2022 v17.1.0 Preview 2.0

**Steps to Reproduce**:

Add the following class:
```cs
#nullable enable

public class Foo
{
    public int Id { get; set; }

    public static bool operator ==(Foo? left, Foo? right)
    {
        // When ReferenceEquals returns false, left and right cannot both be null.
        if (ReferenceEquals(left, right))
        {
            return true;
        }

        // When ReferenceEquals returns false, neither left nor right can be null.
        if (ReferenceEquals(left, null))
        {
            return false;
        }

        return left.Id == right.Id;
    }

    public static bool operator !=(Foo? left, Foo? right)
    {
        return !(left == right);
    }
}
```

**Expected Behavior**:

In the equality operator of **Foo**, I would expect no CS8602 for invoking the **Id** property on the `right` argument as it has been proven not to be **null** by the two `Object.ReferenceEquals` calls.

**Actual Behavior**:

```txt
Foo.cs(21,27,21,32): warning CS8602: Dereference of a possibly null reference
```

**Comment by Youssef1313** [comment]
This is by-design. A similar issue is https://github.com/dotnet/roslyn/issues/58211.

Basically the compiler analysis doesn't do things like "left and right cannot both be null". Each variable just has a state, either not null or maybe null.

**Comment by RikkiGibson** [comment]
Thanks for reporting this issue. @Youssef1313 is correct here that the observed behavior is by design. Also, the logic in the issue description seems incorrect. [SharpLab](https://sharplab.io/#v2:EYLgtghglgdgNAFxAJwK4wD4DcLIAQBmAjHgLx4wCmA7ngGID2DAFAJQDcAsAFBQF7NiZcjFQAbMazwBvPAF8ePAAIBmPEoBM9Jj2k88B9WtgI8ASQAmMvAHNKCdngDO9xwu77Dq9UQBseYCYxPAYAB0pkCAQGfFJSZkYGAH48MUoCBDhtZLxkKBsACwRWTwM9bkNKvAB6arwAdQLKGDwAJXSI5oBjSgBRAEdUCDEndQB2UYJhlyy0jLwIGCs8wtMuxZgGU0CEAoDKCnExADpSqr4BdoJOmB6BoZHmOczc/KLWEoqqsrPvgyUxngEGhKFwvt93L9DLUGk0WlcbndBtNxpNppQslQoLsIql0qZNvgVkU8OsWsADqIJKdwed+MwEchun1kY9npijh8oT9aX9xoR0WC+ZDeV5Ac9jpZhK9VpKLELDCLKt4lH4AkEQuFItF8ABCeKJFLs7IpYnFM7lPkAvC6p746VmjhndxyIA==)
