### ISSUE TITLE
Conditional Return Expression

### ISSUE THREAD

**Issue by rctec-at** [dotnet/roslyn#59268]
## Background and Motivation

Using nullables introduces a lot of lines like the following. Getting a Conditional return statement would shrink the code vertically a lot and may brings more possibilities with pattern matching
```c#
var myValue = SomeFuncThatCouldReturnNull();
if(myValue is null) 
{
    return false;
}
```

## Proposed API

A Conditional Return statement could look like:
```c#
return false when myValue is null;
```

I Removed the other Template pints, sinde i think they dont apply.
This is my first Language Proposal, any feedback (also to the "style" of the proposal will be really helpfull)

**Comment by svick** [comment]
[As mentioned in the readme](https://github.com/dotnet/roslyn#c-and-visual-basic-language-feature-suggestions), language feature suggestions belong to the dotnet/csharplang repository.

And there already is an open discussion about a very similar suggestion: https://github.com/dotnet/csharplang/discussions/1493 (the only difference is it uses `if` instead of `when`).

Because of that, I'm going to close this issue. If you want to talk about this feature, I'd suggest using the csharplang discussion I linked to above.

**Comment by rctec-at** [comment]
@svick sorry, i did not see the open discussion. 
Also i didnt realize there is a csharplang repository.
