### ISSUE TITLE
False code suggestion for a not existing Problem

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#59291]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/False-code-suggestion-for-a-not-existing/1652582)._

---
Visual Studio identifies false "Unnecessary assignment of a value to 'correlationId'"

![image](https://user-images.githubusercontent.com/1408396/153276082-22c026b7-355a-454f-bd95-f8eb792b8b05.png)

If I would apply the suggested changes it would break the application

![image](https://user-images.githubusercontent.com/1408396/153276099-adf3fdb0-4ea1-496d-a161-e4eb319f1671.png)

Code snippet

```cs
if (Request?.Headers.TryGetValue("X-OSI-CorrelationID", out StringValues correlationId) ?? false
                && Guid.TryParse(correlationId, out correlationGuid))
            {
                log.CorrelationId = correlationGuid;
            }
```

---
#### Feedback Bot on 2/2/2022, 10:19 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
The problem here is actually that the code is incorrect.  This is parsed as `?? (false && Guid.TryParse(...)`  So the RHS of the && is actually unreachable.  So the assignment in the out var has has no meaning, and can be replaced with a discard.

Note: we have an analyzer that actuallyr eports this confusing precedence and parenthesizes to make it clear what's going on.
