### ISSUE TITLE
Test for Source generators - attribute (ConstructorArguments) data is empty in unit tests (ok in actual execution)

### ISSUE THREAD

**Issue by MihailsKuzmins** [dotnet/roslyn#59323]
Not really sure whether or not it's a bug. Maybe I'm not doing something right

**Version Used**: 
Microsoft.CodeAnalysis: 4.0.1
Microsoft.CodeAnalysis.CSharp.SourceGenerators.Testing.XUnit: 1.1.0

**Steps to Reproduce**:

1. Clone the repository https://github.com/MihailsKuzmins/ConsoleApp2
2. Rebuild `ConsoleApp2` - not that the source is generated
![image](https://user-images.githubusercontent.com/47413092/152695628-5b53ec0b-d2d7-4f97-9491-105faa3d5544.png)

3. Run the test `UnitTest1` -> `Test`. Test fails with the exception
![image](https://user-images.githubusercontent.com/47413092/152695782-acaab192-8b96-45c1-9eee-dfcceafa9d81.png)

**Expected Behavior**:
Property `ConstructorArguments` has the actual value - not empty

**Actual Behavior**:
Property `ConstructorArguments` is empty.

My source generator generates both attributes and a source which is attributed with the attributes. So in order that the attributes are available in the syntax tree I manually execute this code and everything works very well with the real code. However, when I run the source generator in tests all fields are empty.

Could you please help?
```cs
private static Compilation AddSourceEx(in GeneratorExecutionContext @this, Compilation compilation, string fileName, string source)
{
	var srcText = SourceText.From(source, Encoding.UTF8);
	@this.AddSource(fileName, source);

	var options = (CSharpParseOptions)((CSharpCompilation)compilation).SyntaxTrees[0].Options;
	return compilation.AddSyntaxTrees(CSharpSyntaxTree.ParseText(srcText, options));
}
```

**Comment by Youssef1313** [comment]
Hi @MihailsKuzmins 👋 

It looks like your generated attribute is missing a `using System;`. This works for the project because of `ImplicitUsings` SDK feature that you have enabled.

As to how you can investigate this, you can notice that `attributeData.AttributeClass` is an error symbol. The easiest way of knowing the reason is to call `.GetDiagnostics()` on the compilation object. You'll see that it doesn't recognize the types in `System` namespace because of the missing `using System;`

Anything else I can help with?

**Comment by MihailsKuzmins** [comment]
@Youssef1313, thank you for the fast and valuable reply! Indeed `compilation.GetDiagnostics()` returned some errors that the `System` is not defined, therefore, adding `using System;` solves the issue. Hadn't known about `compilation.GetDiagnostics()` so again thank you for this tip 🙇

Then maybe a new question. Is it possible to enable the `<ImplicitUsings>` option for `CSharpSourceGeneratorTest`? It is possible to override `CreateCompilationOptions`, but I'm not sure whether or not it's the right place to do it

**Comment by Youssef1313** [comment]
@MihailsKuzmins In my opinion you shouldn't use `ImplicitUsings` in tests if your generator is intended to be publicly used because you don't know if the generator consumers will use `ImplicitUsings` or not. So it's safer to add all the needed usings.

But anyway, if you want to simulate `ImplicitUsings` in tests, you can try casting `CompilationOptions` to `CSharpCompilationOptions` and use `WithUsings` like the following:

```csharp
		var opts = (CSharpCompilationOptions)base.CreateCompilationOptions();
		opts = opts.WithUsings(ImmutableArray.Create("System", "System.Collections.Generic", "System.IO", "System.Linq", "System.Net.Http", "System.Threading", "System.Threading.Tasks"));
```

I captured the list of usings from:

https://github.com/dotnet/sdk/blob/bd566f7fa170f953925de4889d71626d63f4170c/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.CSharp.props#L27-L35

**Comment by MihailsKuzmins** [comment]
@Youssef1313, great thank you very much.

No, this source generator is for the internal use and it's known that the consumer of the generator has implicit usings enabled. So everything is safe 😄 

So again thank you for helping me out. I didn't really expected it to be solved SO fast. Have a great forthcoming week 😉

**Comment by Youssef1313** [comment]
Happy to help!
