### ISSUE TITLE
CSC : warning AD0001: Analyzer 'MyApp.Analyzers.MyAnalyzer' threw an exception of type 'System.IO.FileNotFoundException' with message 'Could not load file or assembly 'Microsoft.CodeAnalysis.Workspaces, Version=2.9.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.'.

### ISSUE THREAD

**Issue by amruthrajv-dev** [dotnet/roslyn#59367]
**Version Used**: 
Microsoft.CodeAnalysis.CSharp.Workspaces 2.9.0
**Steps to Reproduce**:

1.  Use Microsoft.CodeAnalysis.FindSymbols.SymbolFinder in the analyzer (.Net standard 1.3) to find references
2.  Add analyzer dll to the project created in VS2017 or VS2022 (.Net Framework 4.8)
3.  Rebuild the solution

**Expected Behavior**:
No errors should be displayed in the output window.
**Actual Behavior**:
Getting a CSC error in the output window. The same issue is checked with multiple versions of 'Microsoft.CodeAnalysis.Workspaces'.
CSC : warning AD0001: Analyzer 'MyApp.Analyzers.MyAnalyzer' threw an exception of type 'System.IO.FileNotFoundException' with message 'Could not load file or assembly 'Microsoft.CodeAnalysis.Workspaces, Version=2.9.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.'.
This issue happens only if I use Microsoft.CodeAnalysis.FindSymbols.SymbolFinder class in my analyzer.

**Comment by sharwell** [comment]
This behavior is by design. The workspaces layer is not present for command line compilation, and therefore cannot be used in analyzers. The easiest way to ensure the analyzer doesn't accidentally reference the workspaces layer is to create the analyzer using the **Analyzer with Code Fix** template. This produces one project for the analyzer which doesn't reference the workspaces layer, and a second project for any code fixes which does allow workspace references.

![image](https://user-images.githubusercontent.com/1408396/153288261-00d446e6-885c-4887-8aef-8f977d9030b9.png)

**Comment by Meir017** [comment]
@sharwell How can one use the `DocumentEditor` & `SyntaxGenerator` in code fixers?
