### ISSUE TITLE
`namedTySym.WithNullableAnnotation` isn't (apparently) working to remove annotations

### ISSUE THREAD

**Issue by ltcmelo** [dotnet/roslyn#59535]
Consider a type parameter `Foo?` and that `tySym` (below) is its symbol. I'd like to have that unannotated version of `Foo?`, ie, `Foo`.

This doesn't seem to work:
```
var namedTySym_P = namedTySym.WithNullableAnnotation(NullableAnnotation.NotAnnotated);
```

Neither this:
```
var namedTySym_P = namedTySym.WithNullableAnnotation(NullableAnnotation.None);
```

If I get the `TypeArgument[0]`, then it works.

A snippet for testing:

```
if (tySym is INamedTypeSymbol namedTySym)
{                
    var origTySym = namedTySym.OriginalDefinition;
    if (origTySym.SpecialType == SpecialType.System_Nullable_T
                && namedTySym.TypeArguments.Any())
    {
        // doesn't give me Foo
        var namedTySym_P = namedTySym.WithNullableAnnotation(NullableAnnotation.NotAnnotated);
        var namedTySym_PP = namedTySym.WithNullableAnnotation(NullableAnnotation.None);

        // gives me Foo
       var namedTySym_PPP = namedTySym.TypeArgument[0];
    }
}
```

Might also be of help as a C# program with such type parameters:

```
public class B
{
    public void O<Q>(Q? item){}
}
public class Test
{
    public void f()
    {
     	B o = null;
	Foo v;
 	o.O<Foo?>(v);
   }
}
```

**Comment by RikkiGibson** [comment]
It looks like you are falling into the gap between nullable reference types and nullable value types. Basically, `System_Nullable_T` only refers to value types (i.e. `TStruct?`). So getting the type argument is indeed the correct way of getting the underlying `TStruct`.

I would expect that `namedTySym` has a `None` NullableAnnotation, as only types "not known to be value type" use the nullable annotation in a meaningful way. It's fairly arcane, I know. The things we do for compat..

**Comment by jcouv** [comment]
This is expected. The type is `System.Nullable<Foo>`. Trying to change annotations isn't going to give you a different type (`Foo`).

**Comment by ltcmelo** [comment]
@jcouv could you clarify what that API is for? 

This is my understanding of it:

- `X?` is a short hand for `System.Nullable<X>`.
- the `?` is a nullable annotation.
- `tySym.With…` with argument `NullableAnnotation.Annotated` gives me `X?` and with argument `NullableAnnotation.NotAnnotated` gives me `X`

**Comment by jcouv** [comment]
> - X? is a short hand for System.Nullable<X>.

Only when `X` is a value type.

> - the `?` is a nullable annotation.

Only for types that are not value types.

**Comment by ltcmelo** [comment]
Thanks, but it then falls into an API issue then, in my opinion. In particular, you will find a [nullable annotation terminology in .NET's own docs of nullable reference types](https://docs.microsoft.com/en-us/dotnet/csharp/nullable-references). If I'm not missing anything, then this API is misleading.

**Comment by CyrusNajmabadi** [comment]
That's an article about nullable *reference* types

**Comment by ltcmelo** [comment]
Correct @CyrusNajmabadi and that's my point: it mentions nullable annotation. In other words, how is nullable annotation `?` in a reference type to a value type. In particular, consider the [sentence below from that article](https://docs.microsoft.com/en-us/dotnet/csharp/nullable-references#nullable-variable-annotations):

"_A nullable reference type is noted using the same syntax as [nullable value types](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/nullable-value-types): a ? is appended to the type of the variable._"

To me, it appears there's terminology overloading without correspond API.

**Comment by CyrusNajmabadi** [comment]
> To me, it appears there's terminology overloading without correspond API.

Nullable value types *already* have their corresponding APIs.  They've been there since Roslny was released :)  For NVTs, just use `Nullable<T>`.  That's it.  It's a direct mapping from the underlying runtime type to the C# type.

For NRT  there needs to be a way to distinguish between the underlying runtime type (like `string`) and the C# NRT type (like `string?`).  This can't be done with `Nullable<T>` because, well, that's not what it is.  Similarly for NVT, we cannot use the same Nullable-Annotation that NRT uses because... welll... that's not what it is either.

THe core point here is that these are entirely different type systems, and so they are represented differently.  Note: the sentence you mention doesn't contradict that.  It says:  "A nullable reference type is noted using the same syntax as nullable value types".

THat is true.  *Syntactically* tehy are represented the same way.  However, at the semantic/symbolic level (which are the APIs you're using), they are very different (and the APIs reflect that).

**Comment by ltcmelo** [comment]
I understand (and agree with) everything you said @CyrusNajmabadi , but that doesn't change my opinion as there's an API issue with the method in question. Specifically:

Given `ITypeSymbol.WithNullableAnnotation(…)` and the fact that the term nullable annotation exists for both reference and value types, what can a user of said API expect?

Also note the description of the API:  "_Returns the same type as this type but with the given nullable annotation._"

**Comment by CyrusNajmabadi** [comment]
> Also note the description of the API: "Returns the same type as this type but with the given nullable annotation."

We'd happily take doc updates here.  

> Given ITypeSymbol.WithNullableAnnotation(…) and the fact that the term nullable annotation exists for both reference and value types, 

Nullable annotation doesn't exist for value types.  Nullable value types have a *syntactic* representation, but at the symbolic level they do not.  I agree we should doc that this will have no effect for types it doesn't work for.

**Comment by ltcmelo** [comment]
The doc is a first step ;-) 

> Nullable annotation doesn't exist for value types. Nullable value types have a syntactic representation, but at the symbolic level they do not

They do, from the moment that the language specification/documentation refers to the `?` as a nullable annotation and allow it on value type syntax; it doesn't matter much whether they exist symbolically. This reminds me of the discussion about `partial` types and an "is partial type" method in the symbols API… (In the end, the API was added.)

**Comment by CyrusNajmabadi** [comment]
> They do, from the moment that the language specification/documentation refers to the ? as a nullable annotation and allow it on value type syntax; it doesn't matter much whether they exist symbolically. 

It very much does matter.  This is a core part of what hte language actually is.  

`int?` is not `int` with a `nullable annotation`.  It is literally `Nullable<int>`.  It has been that way in roslyn since the beginning.  That is not going to change.  Similarly, we are not going to represent `string?` as `Nullable<string>`.  It's not that type.  It's `string`? with a `nullable annotation` stating what sort of nullability it has.  

Both of these are correct and accurate API representations of the distinct concept here (both at the semantic and runtime level).  The syntactic API provides a uniform representation because it is uniform at the syntactic level.  THe semantic APIs will represent teh language's actual semantic view of things.

You are welcome to layer on top of this your own API which attempts to give what you feel is a consistent experience on both domains.   You are also welcome to file issues on the docs (or just submit PRs to also update them if you want).  However, we will not be changing the APIs here as the view you putting forth does not actually match the *language's* view of things, and it's a core principle that the APIs we have be tightly tied to the actual language perspective, and not an overlay view on how people intuit things.

**Comment by CyrusNajmabadi** [comment]
>This reminds me of the discussion about partial types and an "is partial type" method in the symbols API… (In the end, the API was added.)

I don't know what you mean.  The symbol API doesn't have such a concept.  The only place we expose 'partial' is the following on IMethodSymbol:

```c#
public interface IMethodSymbol
{
        IMethodSymbol? PartialDefinitionPart { get; }
        IMethodSymbol? PartialImplementationPart { get; }
        bool IsPartialDefinition { get; }
```
