### ISSUE TITLE
Find Reference index construction should appear in Task Status Center

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#59688]
Currently the Find References index is updated as a background task, but the task does not appear as a background operation in the Task Status Center. This confuses users who observe sustained periods of moderate CPU activity without any visual indication in the IDE itself.

🔗 [AB#1485721](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1485721) (internal)

**Comment by CyrusNajmabadi** [comment]
This is originally how things worked. We got rid of it because of complaints of noisiness and that the message provided no value. Other messages at least explained a "not ready"->"ready" transition which was useful to users. Or they told you when something you were waiting on was done. 

However, for a background indexing task, you basically always got these messages continuously after loading/editing forever. And it wasn't something you ever need to wait on as FAR is always available, and this just acts to accelerate it.

**Comment by CyrusNajmabadi** [comment]
I'm curious if the solution crawler has the concept of "initial indexing work"...

**Comment by CyrusNajmabadi** [comment]
Closing out.  We do not have a background task that does this.
