### ISSUE TITLE
SA1210 is inconsistent with IDE's Remove and Sort Usings (casing) 

### ISSUE THREAD

**Issue by alexanderjung-sdxag** [dotnet/roslyn#59873]
I have a reference (over wich I have no control) which does not adhere to naming conventions (unfortunately) and uses lowecase for namespaces.

Using "sort usings", the IDE sorts this by lowercase first, SA1210 checks case insensitive:

IDE:
using company.xxx;
using Company.AAA;

SA1210 expects:
using Company.AAA;
using company.xxx;

According to https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/3467, the IDE behavior is the one that should be fixed.

**Comment by jinujoseph** [comment]
cc @JoeRobich

**Comment by CyrusNajmabadi** [comment]
Note: as per discussion in the linked issue, i'm wary of changing this.  We've behaved this way for nearly 20 years.  So i'm leaning towards wanting to keep the status quo here and to indicate we do piecewise comparisons as we always have.

**Comment by JoeRobich** [comment]
We could provide an additional option `dotnet_sort_directives_ignore_case` which defaults to `false`, but I'm not sure the benefit pays for the cost of the option.

**Comment by CyrusNajmabadi** [comment]
I definitely would not create a setting here.  This is a single report (in 20 years).  We want options for things we know the community has tons of people using/wanting. :)

**Comment by alexanderjung-sdxag** [comment]
Several thoughts on not fixing this:
- The tooling is behaving inconsistent!
- The behavior in VS is unexpected!
- How many people are actually not follow regular naming guidelines and would be affected
- If it happens, VS actually automates the fix
- In the past, every update to FxCop, StyleCop and sometimes the compiler yielded new warnings

Just my 0,02€

**Comment by CyrusNajmabadi** [comment]
> The tooling is behaving inconsistent!

VS has behaved this way for nearly 20 years at this point.  If we change it, then the new versions will be inconsistent with older versions which can impact people. 

> The behavior in VS is unexpected!

It's been 20 years and this is the first report in all that time. I'm wary of stating this is unexpected. C# is a case sensitive Language. So it feels strange and unexpected to me to expect it to not take casing into account when sorting here. 

> How many people are actually not follow regular naming guidelines and would be affected

That's very hard to say. Which is why I'm wary of touching this. For all we know there are thousands of customers who may now be affected by this. 

> If it happens, VS actually automates the fix

That doesn't help people who do not want to upgrade and now get new errors or warnings when they didn't have them before. It also doesn't help projects where people/teams are using multiple versions of vs at the same time. 

Changing the meaning of this seeing makes things incompatible across that version boundary. I'm very very very wary about doing that for something that has only once been reported as a problem by a single user in 20 years. 

> In the past, every update to FxCop, StyleCop and sometimes the compiler yielded new warnings

But this is not an update to those optional tools. This is an update to vs. The rules and philosophy we have around this are different.

**Comment by alexanderjung-sdxag** [comment]
>That doesn't help people who do not want to upgrade and now get new errors or warnings when they didn't have them before.

Changing how "sort usings" actually sorts does NOT create new warnings.
Changing how "sort usings" actually sorts does NOT impact people by itself. It only reorders the usings if they actually ASK for this.
The current way it sorts actually DOES create warnings when it clashes with the expected order in SA1210.

Anyway, I'm not that invested in _how_ VS sorts usings, my concern ist that VS an StyleCop contradict each other.
Let me know when this becomes a decission, and I will reopen the issue with StyleCop.

**Comment by CyrusNajmabadi** [comment]
Closing this out.  We won't change VS here.  The behavior here is what we've had literally since the feature was initially implemented and has had only this report on the topic in that entire time.  The behavior matches out beliefs around the case sensitivity of the language and is behaving as expected.

If you want the tools to be consistent, you can ask style-cop to be consistent with VS here.
