### ISSUE TITLE
Escape analysis inconsistency (CS8353)

### ISSUE THREAD

**Issue by hypeartist** [dotnet/roslyn#59908]
**Version Used**: 
.NET 6.0.200
Visual C# Compiler version 4.2.0-1.22108.11

**Steps to Reproduce**:

1.
```csharp
	static char Method1()
	{
		Span<char> buffer;
		buffer = stackalloc char[2];
		return buffer[0];
	}
``` 
2. 
```csharp
	static char Method2()
	{
		Span<char> buffer = stackalloc char[2];
		return buffer[0];
	}
``` 

**Expected Behavior**:
Both cases compile without errors

**Actual Behavior**:
In case 1 compiler failed with:
```
CS8353: A result of a stackalloc expression of type 'Span<char>' cannot be used in this context because it may be exposed outside of the containing method
```

**Comment by jcouv** [comment]
This is by-design. From the spec on [safe-to-escape rules](https://github.com/dotnet/csharplang/blob/main/proposals/csharp-7.2/span-safety.md#safe-to-escape):
1. > A local of ref struct type and uninitialized at the point of declaration is safe-to-return from the entire enclosing method.
2. > A stackalloc expression is an rvalue that is safe-to-escape to the top-level scope of the method (but not from the entire method itself).

If we allowed the assignment `buffer = stackalloc char[2];` then we'd allow the `stackalloc` to escape the entire enclosing method, which is bad.

If the local has an initializer, then the local gets its "safe-to-return" scope from the initializer. That's why case 2 compiles.
> Otherwise the variable's type is a ref struct type, and the variable's declaration requires an initializer. The variable's safe-to-escape scope is the same as the safe-to-escape of its initializer.
