### ISSUE TITLE
`async foreach` binds to `IAsyncDisposable.DisposeAsync()` rather than pattern based `DisposeAsync()`

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#59955]
The following prints `IAsyncDisposable.DisposeAsync()`:

```csharp
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

await foreach (var i in new AsyncEnumerable())
{
}

struct AsyncEnumerable : IAsyncEnumerable<int>
{
    public AsyncEnumerator GetAsyncEnumerator(CancellationToken token) => new AsyncEnumerator();
    IAsyncEnumerator<int> IAsyncEnumerable<int>.GetAsyncEnumerator(CancellationToken token) => new AsyncEnumerator();
}

struct AsyncEnumerator : IAsyncEnumerator<int>
{
    public int Current => 0;
    public async ValueTask<bool> MoveNextAsync() => false;
    public async ValueTask DisposeAsync() { Console.WriteLine("DisposeAsync()"); }
    async ValueTask IAsyncDisposable.DisposeAsync() { Console.WriteLine("IAsyncDisposable.DisposeAsync()"); }
}
```

See [sharplab.io](https://sharplab.io/#v2:EYLgtghglgdgNAFxAJwK7wCYgNQB8ACATAIwCwAUPgAwAE+xALANwXV3EB0AKgBbICmEDLADmLSrXoBWcawCcNAGYB7ARADGPGgAoAbhGQ0oRmDRj8A7jQCCAZwCeMdQFEYqMP2QRgAG37aASgCKAG8KAF8KClsENHUEGwcnV3dPbz8aEBoASTtHFzcPL19+AB5YBAA+UIoaOroAZkT8lKKIBFUaAHF+BDzkwrSO5G0AYQgnfh8fdqhlGC5lAGt+Uw6VmACaAF5Ks0tmgdSvYcDxepz+guP21XKYKsuk67aS+6qOHr7n1qHVMYm6imMwQcwWy1WNHWqy2u32ViuvxO/wC4ki5GisVQ8UOLz+hiyuR+g2RyHe1XIYXIF3wTQqNFGqGQAgeOz2VHO9VpdAAHDQAGoQHyofj4ABspWAymUPj2AFllLp+AA5fgAD2++UCbKUQts/E5dW5+D5guForFNAAIlBbAAHZT6q7akLsOTaABENvtjv4zoCHtRNHRNNNQpF4qe+W9Dts6X4HBjvv9NFd9HdHqJ0dtsfjiZzyeegUDTGDESAA===).

From [async-streams spec](https://github.com/dotnet/csharplang/blob/main/proposals/csharp-8.0/async-streams.md#pattern-based-compilation):
> The compiler will bind to the pattern-based APIs if they exist, preferring those over using the interface (the pattern may be satisfied with instance methods or extension methods).

**Comment by bernd5** [comment]
@jcouv I were really surprised that just Dispose is not preferring pattern based methods...
I found no clear statement about it in the spec - but for consistency reasons I agree that this is maybe a bug...

Your sample is a bit wrong - because the non interface GetAsyncEnumerator method is not invocable without a parameter. In this case the compiler must call the interface based method (the enumerator is of type ` IAsyncEnumerator<int>`).

But if you change that - the compiler still uses the explicit interface implementation of DisposeAsync. This is not really a big problem because it is executed with a constrained call - no Boxing:

```IL
IL_00f0: constrained. AsyncEnumerator
IL_00f6: callvirt instance valuetype [System.Private.CoreLib]System.Threading.Tasks.ValueTask[System.Private.CoreLib]System.IAsyncDisposable::DisposeAsync()
```

This is required by the spec for foreach in general - not just async foreach.

See fixed code: [link](https://sharplab.io/#v2:EYLgtghglgdgNAFxAJwK7wCYgNQB8ACATAIwCwAUPgAwAE+xALANwXV3EB0AKgBbICmEDLADmLSrXoBWcawCcNAGYB7ARADGPGgAoAbhGQ0oRmDRj8A7jQCCAZwCeMdQFEYqMP2QRgAG37aASgCKAG8KAF8KClsENHUEGwcnV3dPbz8aEBoASTtHFzcPL19+AB5YBAA+UIoaOroAZkT8lKKIBFUaAHF+BDzkwrSO5G0AYQgnfh8fdqhlGC5lAGt+Uw6V0wBeGgx+RQhUHwQAmk3Ks0tmgdSvYcDxepz+gpv21XKYKqekl7aSj6qHB6fR+rSGqjGE3UUxmCDmC2Wqxo61WJzC5Eej3ocm0ACJcqDBsU/ADKkDes8wbdVLiAg9MXV8AB2C5WSlEt4jOm1R6Rch86KxVDxK6/cGGLIEloc4akmoY+r4JoVGijVDIASfU7nKj0xlNABqEB8qH4+AAbKVgMplD5zgBZZS6fgAOX4AA8QflAtqaEaTWbzRwAGLIZRgABK/FshwQ2n2Pls/G5Cv1fuNpotNAAIlBbAAHZRJ54+kLsHG43MFov8EsBWlMOgs/2ZoOjcP5vwIfgYC2NvmPFuB775KuF2zpfgcMc1us0MvYvFSpwziclad58e1n6BBtN9MBi0cdtgTu9Ht9mh88JAA)

**Comment by jcouv** [comment]
Re: "I found no clear statement about it in the spec"

I've added a note to OP with the statement from [async-streams spec](https://github.com/dotnet/csharplang/blob/main/proposals/csharp-8.0/async-streams.md?rgh-link-date=2022-03-04T21%3A35%3A45Z#pattern-based-compilation) that clarifies expectations:
> The compiler will bind to the pattern-based APIs if they exist, preferring those over using the interface (the pattern may be satisfied with instance methods or extension methods).

That said the [usings spec](https://github.com/dotnet/csharplang/blob/main/proposals/csharp-8.0/using.md#pattern-based-using) doesn't seem to mention order.

Tagging @chsienki in case the precedence order as implemented was intended (TL;DR: foreach generally picks pattern-based first, then interface; async-streams spec agree; but implementation does reverse).
