### ISSUE TITLE
`GetHashCode` of `Span<T>` is not suggested in `nameof` context

### ISSUE THREAD

**Issue by DoctorKrolic** [dotnet/roslyn#59998]
Noticed while working on https://github.com/dotnet/roslyn/pull/59884. But this issue was true even before it, so it is a separate one

**Version Used**:
VS 17.2 Preview 1

**Steps to Reproduce**:
```
var sp = Span<int>.Empty;
_ = nameof(sp.$$);
```

**Expected Behavior**:
`GetHashCode` is one of suggested names

**Actual Behavior**:
![devenv_Zk7C3XY9Ur](https://user-images.githubusercontent.com/70431552/157107235-a19e2191-6670-4d91-8d45-6b2f1d949b56.png)

**Comment by jcouv** [comment]
Moved to area IDE. The problem might be with `SyntaxTreeExtensions.IsExpressionContext` and/or `SymbolCompletionProvider`. There's a possibility this could be a compiler API issue (with `LookupSymbols` API, but feels less likely.

If this issue is taken up by a contributor, possible tests would be `SymbolCompletionProviderTests` or `CSharpCompletionCommandHandlerTests`.

**Comment by RikkiGibson** [comment]
It might be because 'GetHashCode' and other methods have non-browsable overrides on this type.

https://github.com/dotnet/runtime/blob/4e969f54ac5200993555c7ba74b47d80aa459845/src/libraries/System.Private.CoreLib/src/System/Span.cs#L187

**Comment by DoctorKrolic** [comment]
@RikkiGibson So what is an expected behaviour here? Maybe if this method have `EditorBrowsableState.Never` then it shouldn't be shown in `nameof` context as well? I'm not sure here.

**Comment by jcouv** [comment]
@RikkiGibson Good point. `sp.GetHashCode` doesn't complete outside of `nameof` either, so the attribute is likely the cause of the behavior. The current behavior seems by-design.

**Comment by genlu** [comment]
> So what is an expected behaviour here?

The expected behavior is APIs marked with `EditorBrowsableState.Never` should not participate in any IDE features. Although in reality the IDE behavior might not be very consistent among features, completion is definitely one of those that enforce this.

I think this is similar to the discussion re: hiding object methods from ref struct in https://github.com/dotnet/roslyn/pull/59884#discussion_r819138593. Using of `Span.GetHashCode` would throw therefore `EditorBrowsableState.Never` is used to hide them from IDE features. @DoctorKrolic are you making a feature request to include `EditorBrowsableState.Never` APIs when completion is triggered in nameof context?

**Comment by DoctorKrolic** [comment]
> @DoctorKrolic are you making a feature request to include `EditorBrowsableState.Never` APIs when completion is triggered in nameof context?

No. I agree with the folowing:
> The expected behavior is APIs marked with `EditorBrowsableState.Never` should not participate in any IDE features.

It would be odd, if `EditorBrowsableState.Never` has some exception cases in my opinion. When creating this issue, I thought, that the method is hidden, because it is marked as `Obsolete`, and if it turned out to be the case, I would say, that hiding `Obsolete` members in `nameof` context is not the right thing. But it is pretty clear, that `EditorBrowsableState.Never` should, well, never be displayed in any kind of situation. Closing the issue

**Comment by genlu** [comment]
> hiding Obsolete members in nameof context is not the right thing

@DoctorKrolic FYI, regarding `Obsolete`, the plan is to still show them in the completion but have the item strikethrough 
https://github.com/dotnet/roslyn/issues/26488#issuecomment-682119757

**Comment by DoctorKrolic** [comment]
Wow, that's a nice user experience IMO! I didn't know, that it is even possible to have completion item strikethrough
