### ISSUE TITLE
Jenkins reports "Build failed no problems identified"

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#6027]
If we had the information necessary to fail the build, surely we can get Jenkins to print something other than "No identified problems" :smile:

**Comment by rchande** [comment]
cc @jmarolf

**Comment by rchande** [comment]
cc @jasonmalinowski

**Comment by davkean** [comment]
This isn't really actionable. That thing that says "No identified problems" is a plug-in; it runs a set of custom regex's looking for issues to highlight on that front page. If you run into a build failure that says "No identified problems", then it's because no one has registered one.

They are easy to register, and when you encounter a build failure where we didn't identify something, add one:

1. Visit http://dotnet-ci.cloudapp.net/
2. Click __Log In__ on the top right
3. Click __Failure Cause Management__ then __Create New__

I've been adding them as I encounter them.

**Comment by davkean** [comment]
Based on above, going to close this.
