### ISSUE TITLE
when input is dynamic the compiler infers the output as dynamic

### ISSUE THREAD

**Issue by VisualBean** [dotnet/roslyn#60527]
Im not sure if this is a roslyn thing, but please direct me to right place if not :) 

I have a weird thing happening currently.
![image](https://user-images.githubusercontent.com/5294032/161308400-eb3e957a-3e18-4330-ac7b-0f0cd6d03595.png)
With a method signature that clearly returns `Task<GuardRail.ValidationState>`
The inferred return type, is shown as `dynamic`
![image](https://user-images.githubusercontent.com/5294032/161308636-7eae8ef6-22d6-4d72-a97d-fbbc8a8e84e7.png)

This seems to be based off of the input though, as if I change the input type from `dynamic` to something else
![image](https://user-images.githubusercontent.com/5294032/161308755-37c9badf-47b7-4af8-9da4-6ee4535320ef.png)
The inferred return type is caught by the compiler correctly.
Ive confirmed this to be the case running this code as well (just to eliminate weird IDE problems).
It was caught by an extension method, that suddenly started to throw after we changed to using a dynamic type instead.

Target framework is .Net 6.

**Comment by svick** [comment]
This is the expected behavior. `dynamic` means that overload resolution is deferred until runtime, and that includes overloads that may exist at runtime, but not at compile time. And so the single overload that is visible at compile time might not be the one that's actually executed at runtime. Which means the return type is genuinely unknown and represented as `dynamic`.

**Comment by VisualBean** [comment]
Took me a double take to fully understand it. Yeah that makes sense.

**Comment by jcouv** [comment]
Thanks @svick. Closing as by-design.
