### ISSUE TITLE
Inheritance margin should add more information to disambiguate identically named items.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#60627]
![image](https://user-images.githubusercontent.com/4564579/162268424-fe5ab07d-784b-429c-9e30-cede483e2c8d.png)

An option here would be to include the shortest suffix/prefix pieces of the project name to disambiguate these.  So ` (VisualBasic.Features)` and ` (CSharp.Features)` added at the end of each.

**Comment by DoctorKrolic** [comment]
Showing source language of implementation is good thing to have as well. For instance, as a swall icon of language before the icon of each member. I struggled a lot with inheritance margin when working with roslyn, because every time I see this, I need to guess, which reference is pointing to C# implementation and which is pointing to VB

**Comment by CyrusNajmabadi** [comment]
Agreed.  If the difference is in language, just having a language glyph included in the info would be sufficient and nicely small in size.

**Comment by Youssef1313** [comment]
Also https://github.com/dotnet/roslyn/issues/55790.
