### ISSUE TITLE
`foreach` autocompletion should be offered when ctrl+. is pressed on a variable representing a collection

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#60628]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/foreach-autocompletion-should-be-offer/1697317)._

---
There are several things that happen over and over again in programming. One of them is implementing `foreach` loops for variables.

Consider the following:

```
string[] names = new string[] {"John", "Peter", "Dan"};
names // press CTRL+. on `names` variable
```

at this point I would love to have an option in the context menu that would implement:

```
string[] names = new string[] {"John", "Peter", "Dan"};
foreach (string name in names) {
   // caret here
}
```

PS: I know I can write `foreach` and press tabulator twice and it helps but it still requires quite a lot of manual work to get it to required code.

Thank you for considering this feature.

---
#### Feedback Bot on 3/21/2022, 07:33 AM: 

(private comment, text removed)

**Comment by jmarolf** [comment]
related to https://github.com/dotnet/roslyn/issues/56541

**Comment by CyrusNajmabadi** [comment]
Design meeting review 4/25/2022.

1. We are highly in favor of improving the experiences here.  
2. There are two closely related avenues that we want to improve the experience here with.
3. First, we think 'semantic snippets' will be a great way for people to discover powerful snippets when they start typing a statement/expression.  
4. Second, we think postfix-completion would be highly useful here as well.  We already have such a feature for `await` where you can type `.await` (or `awaitf`) and have a complex change happen that can be very useful.  We think expanding on that for things like `.for` `.foreach` `.null` etc. etc. would be great.  The benefit of postfix-completion is that it can then use information about what is being completed off of to filter down to only relevant completions.

We also discussed if this should be in the space of intellicode/prose.  Our feelings were that this is more appropriate for us to do so that users can have confidence that these features are always available and work in a deterministic fashion every time they try to use them.
