### ISSUE TITLE
Tuple type cast in pattern matching becomes a no-op

### ISSUE THREAD

**Issue by hez2010** [dotnet/roslyn#60699]
**Version Used**: .NET 6

**Steps to Reproduce**:

```csharp
(object, bool) a = ("", false);
if (a is (string, bool) b)
{
    Console.WriteLine(b.GetType());
    var s = b.Item1; // s is still object here
}
```

**Expected Behavior**:
```
System.ValueTuple`2[System.String,System.Boolean]
```

**Actual Behavior**:
```
System.ValueTuple`2[System.Object,System.Boolean]
```

**Comment by Youssef1313** [comment]
While it appears confusing, I think it's by design.

https://github.com/dotnet/csharplang/blob/main/proposals/csharp-8.0/patterns.md#positional-pattern

> - If *type* was omitted and the input value's type is a tuple type, then the number of subpatterns is required to be the same as the cardinality of the tuple. Each tuple element is matched against the corresponding *subpattern*, and the match succeeds if all of these succeed. If any *subpattern* has an *identifier*, then that must name a tuple element at the corresponding position in the tuple type.

**Comment by jcouv** [comment]
This is indeed by design, but confusing. This is not a type pattern with a designation, but rather a positional pattern with a designation.

The input value can be deconstructed (ie. there's a shortcut for doing that given that the input type is a tuple type), and each part is subjected to a type test, then the value is saved into `b`.
If you want a type pattern, you must use `System.ValueTuple<string, bool>` explicitly.
It's annoying, but the ambiguity in syntax could not be resolved...
