### ISSUE TITLE
IDE0200 "Lambda expression can be removed" codefix can delete code comments

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/roslyn#60741]
**Version Used**: 

Version 17.3.0 Preview 1.0 [32411.231.main]

**Steps to Reproduce**:

```c#
class C
{
    void M1()
    {
        M2(() =>
        {
            // I hope M2 doesn't call M1!
            M1();
        });
    }

    void M2(Action a)
    { }
}
```

The lambda is marked as removable. Invoking the code fix gives:

```c#
class C
{
    void M1()
    {
        M2(M1);
    }

    void M2(Action a)
    { }
}
```

**Expected Behavior**:

The comment is not deleted. Either it is moved to an outer scope somewhere, or the codefix is not offered at all.

**Actual Behavior**:

Comment is deleted.

**Comment by CyrusNajmabadi** [comment]
Acceptable final forms would be:

```c#
    void M1()
    {
        M2(
            // I hope M2 doesn't call M1!
            M1);
    }
```

or

```c#
    void M1()
    {
        // I hope M2 doesn't call M1!
        M2(M1);
    }
```

**Comment by wizofaus** [comment]
I also note that the warning is sometimes incorrect - e.g. using Moq, it warns for:

`mockDevices.Setup(m => m.GetEnumerator()).Returns(() => devices.GetEnumerator());`

That the lambda expression can be "removed". But it doesn't work if you do, because in that case "GetEnumerator()" only gets evaluated once, whereas it needs to be evaluated every time the mock object's GetEnumerator() method is called.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/76015
