### ISSUE TITLE
Inconsistency around accessibility checks for interface implementations

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#60885]
Assembly 1:
```
public interface I1
{
    internal abstract void M1(); 
}
```

Assembly 2:
```
class Test2 : I1
{
    void I1.M1() // error CS0122: 'I1.M1()' is inaccessible due to its protection level
    {
    }
}
```

Assembly 3:
```
class Test3 : I1
{
    public void M1() // No error. Treated as an implicit implementation 
    {
    }
}
```

Recently we allowed implicit implementations for non-public members:
https://github.com/dotnet/roslyn/pull/54182
https://github.com/dotnet/csharplang/blob/main/meetings/2021/LDM-2021-05-19.md#protected-interface-methods

As part of that work the public accessibility check was completely removed for implicit implementations. We used to check if the interface member was public or not (rather than if it was accessible). It is quite possible that I misinterpreted the LDM decision to replace the check with true accessibility check.

In any case, the current behavior seems inconsistent. An inaccessible member can be implemented implicitly, but cannot be implemented explicitly. 
Some options:
- Should we perform true accessibility check for implicit implementations? This can bring back the scenario where adding an internal virtual member to an interface breaks existing code. 
- Should we relax accessibility requirements for explicit implementations? I.e. remove them? Runtime probably doesn't care in this case. Especially that sometimes we emit MethodImpl entries for implicit implementations as well.

**Comment by MadsTorgersen** [comment]
A third option that I think I prefer is to mimic classes as closely as possible. This is the behavior for classes:

Assembly 1:

``` c#
public class C1
{
    internal virtual void M1() { }
    internal virtual void M2() { }
}
```

Assembly 2:

``` c#
class C2 : C1
{
    internal void M1() { }          // No error, no overriding
    internal override void M2() { } // Error: No method to override
}
```

For interfaces I think this means that your `Test3.M1` above should be allowed (it is an ordinary member declaration after all), but should not implement the interface member `I1.M1`. In your example this would lead to an error that `Test3` does not implement `I1`. I think this error is useful, and allows interface authors to ensure that implementations can only exist within their own assembly.

If `I1.M1` had had a default implementation, then that's what would be used to implement it in `Test1`.

I realize it can be a bit confusing that a class member silently does _not_ implicitly implement an interface member just because that member isn't accessible. But that's exactly what happens with inherited class members as well: Not so much as a warning on `C2.M1` above that you're shadowing an internal member from another assembly.

If we're uneasy about it, though, we could perhaps give a warning that the member doesn't implement the interface member, and you could remove the warning with the `new` modifier.

**Comment by 333fred** [comment]
Discussed in LDM on April 25th, 2022: https://github.com/dotnet/csharplang/blob/main/meetings/2022/LDM-2022-04-25.md#inconsistencies-around-accessibility-checks-for-interface-implementations

Conclusion: We need to come up with more ideas.

**Comment by Neme12** [comment]
I agree that the method should just shadow the interface method and not implement it. If it's internal, the other assembly shouldn't even know it exists, and therefore shouldn't automatically implement it *or* show an error.

**Comment by 333fred** [comment]
Discussed in LDM on May 11th, 2022: https://github.com/dotnet/csharplang/blob/main/meetings/2022/LDM-2022-05-11.md#inconsistency-around-accessibility-checks-for-interface-implementations

Conclusion: Perform a real accessibility check for implementations of internal interface methods, and error if the check fails.
