### ISSUE TITLE
Extremely high OOP memory usage

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#61314]
My OOP temporarily spiked to over 60GB of memory usage.  Managed to capture a trace (attached).  Symptom is here:

![image](https://user-images.githubusercontent.com/4564579/168389354-12607087-284d-44c7-9d81-4798ebc5ce09.png)

@sharwell do you know what could be causing this?

**Comment by CyrusNajmabadi** [comment]
Trace is at: https://teams.microsoft.com/l/message/19:880daa5569e3460eadcae690247f1402@thread.skype/1652475706302?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=4ba7372f-2799-4677-89f0-7a1aaea3706c&parentMessageId=1652475706302&teamName=.NET%20Developer%20Experience&channelName=IDE&createdTime=1652475706302

**Comment by Neme12** [comment]
It looks like `DirectMemoryAccessStreamReader`(https://github.com/dotnet/roslyn/blob/4ca1035c55c88a0be12ceb79edf40b4285496878/src/Workspaces/Core/Portable/TemporaryStorage/TemporaryStorageServiceFactory.cs#L429
should override `ReadToEnd`, because the [base `ReadToEnd` implementation](https://referencesource.microsoft.com/#mscorlib/system/io/textreader.cs,144) does some allocations that can be avoided if we provide a specialized implementation. It still doesn't make sense to me why it would add up to gigabytes though. Is it called so many times?

**Comment by Neme12** [comment]
Although ideally, `SourceText.From` would be constructible from a `ReadOnlySpan` (it would still copy of course to ensure immutability) - if that was the case, the hacky `TextReaderWithLength` solution wouldn't be necessary.

**Comment by sharwell** [comment]
The trace didn't provide the necessary data for this investigation. We will need either a heap dump, or a trace collected with the [standard event sources enabled](https://github.com/dotnet/roslyn/blob/main/docs/wiki/Recording-performance-traces-with-PerfView.md#general-purpose) after #61187 is available.
