### ISSUE TITLE
"Generate constructor" doesn't work on records

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/roslyn#61338]
**Version Used**: 

**Steps to Reproduce**:

1. In a C# program declare:
   ```c#
   record Foo(string Bar);
   ```
2. With the caret on `Foo` invoke "Generate constructor"
3. Dialog appears:
   ![image](https://user-images.githubusercontent.com/350947/168523920-8a108990-42f2-4a11-b8e8-49e91175833f.png)
4. Click ok

**Expected Behavior**:

Code is transformed into:

```c#
record Foo
{
    public string Bar { get; init; }

    public Foo(string bar)
    {
        Bar = bar;
    }
}
```

**Actual Behavior**:

The dialog closes. No change is made to the code. No error message or other feedback is given.

Alternatively, the "Generate constructor" command should not be offered when it wouldn't work.

**Comment by davidwengier** [comment]
I agree, the bug here seems to be that Generate Constructor is offered at all.

Though I think a different code action could potentially be offered to get the expected result (except with an `init;` accessor on the property 😛), to convert the primary constructor to a full constructor, like we offer to convert an auto-property to a full property.

**Comment by drewnoakes** [comment]
> except with an init; accessor on the property 😛

Ooh. Updated.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
