### ISSUE TITLE
"Extract base class" shouldn't be the first item in the light bulb

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/roslyn#61334]
To maximize keyboard productivity, operations that are more commonly invoked should be near the top of the light bulb menu. Currently, "Extract base class", a rarely invoked operation, comes ahead of "Use expression body for methods" which is much more common.

![image](https://user-images.githubusercontent.com/116161/168489727-8636b9b0-1c47-47bd-974b-ec505cdf1cac.png)

**Comment by vatsalyaagrawal** [comment]
@CyrusNajmabadi FYI..

**Comment by CyrusNajmabadi** [comment]
I agree with @DustinCampbell .  Though it woudl be good to be data driven here.  @mikadumont what are the invoke numbers for each of these actions?  We should order based on that.  Thanks!

**Comment by Bosch-Eli-Black** [comment]
Similarly, I almost always want to use "Extract interface" on a class, rather than "Generate constructor" 🙂

**Comment by CyrusNajmabadi** [comment]
So this is actually a tough call @DustinCampbell .  For a particular time period, extract class is at 1.75M hits, while 'use expression body' is at only 1.25M...

For extract-interface vs generate-constructor, we have 500K vs 2.1M.  

So, i'd say in both cases, we are sorting properly based on what hte majority uses.

**Comment by DustinCampbell** [comment]
That smells fishy to me. Could the data skewed from accidental clicks since Extract Class is the first item?

**Comment by CyrusNajmabadi** [comment]
I'll check the undo counts

**Comment by Neme12** [comment]
> That smells fishy to me. Could the data skewed from accidental clicks since Extract Class is the first item?

That did actually happen to me many times 😄 Expresison/block body is almost always the first thing on method declarations so I'm used to that.

**Comment by CyrusNajmabadi** [comment]
I'm not seeing undo's on ExtractClass, whereas we do have >1% undo's on expression-body usage.

That said, what we oculd do is potentially reorder if you're on a member vs on the class decl.  On the class decl it could have priority, but on a member decl it could be lower pri.

**Comment by DustinCampbell** [comment]
Does the telemetry trigger even if they cancel the dialog?

**Comment by DustinCampbell** [comment]
This just seems *really* surprising to the degree that I'm having a hard time believing the data. 😄

**Comment by CyrusNajmabadi** [comment]
It's possible it's all wrong.  I know Manish is redoing all our data collectio here.  I'll bring up with him.  In the meantime though, i think teh approach i mentioned above should be viable and appropriate.  :)

**Comment by CyrusNajmabadi** [comment]
> Definitely! Does the telemetry get broken down by context? E.g. on type vs. method declaration?

Unfortunately, no.  And that's a real pity.  Will bring that up with manish to see if we can get sub-categories here to help break things down.

**Comment by CyrusNajmabadi** [comment]
Opened https://github.com/dotnet/roslyn/issues/61665 to track that.

**Comment by DustinCampbell** [comment]
> > Definitely! Does the telemetry get broken down by context? E.g. on type vs. method declaration?
> 
> Unfortunately, no.  And that's a real pity.  Will bring that up with manish to see if we can get sub-categories here to help break things down.

Yeah, it feels like those added contexts could be used to drive AI in this area.

**Comment by mikadumont** [comment]
> I agree with @DustinCampbell . Though it woudl be good to be data driven here. @mikadumont what are the invoke numbers for each of these actions? We should order based on that. Thanks!

Based on telemetry here is the order of most frequently used refactorings in that list: Extract base class, Use expression body, Change signature, Pull members up so it is already somewhat ordered correctly based on telemetry.

**Comment by DustinCampbell** [comment]
Right. But to Cyrus's point is that the correct order in this particular context?

**Comment by CyrusNajmabadi** [comment]
Fix incoming :)

**Comment by mikadumont** [comment]
> Right. But to Cyrus's point is that the correct order in this particular context?

Ya unfortunately we dont have data on that.

**Comment by CyrusNajmabadi** [comment]
https://github.com/dotnet/roslyn/pull/61666 to fix thsi issue.  Will work with @mavasani on a plan around https://github.com/dotnet/roslyn/issues/61665 so we can understand these cases better in the future.

**Comment by DustinCampbell** [comment]
> Right. But to Cyrus's point is that the correct order in this particular context?

E.g. are more people choosing Extract Base Class from a method declaration than a convert to expression body on method declarations? Why is Extract Base Class even available on method declarations when Extract Interface isn't?

It looks to me like the context where this should be available wasn't made consistent with similar refactorings. As a user, it feels unpolished to me.

**Comment by DustinCampbell** [comment]
At least, *I* keep bumping into it. 😁😁😁

**Comment by CyrusNajmabadi** [comment]
I agree.  I think ew need another pass on the refactorings/fixes and their locations/consistency.

I like the idea of taking individual actions and bucketing with their conceptual partners (even if they don't share impl) to make sure they behave the same way.

**Comment by DustinCampbell** [comment]
I wonder if we could use AI to answer other questions around fixers and refactorings. For example, what if AI were used to determine the best place to position the caret/selection after invocation for maximum typing productivity? I'd pay for that! 😁

**Comment by CyrusNajmabadi** [comment]
Tagging @dibarbet  ^

**Comment by dibarbet** [comment]
> I wonder if we could use AI to answer other questions around fixers and refactorings. For example, what if AI were used to determine the best place to position the caret/selection after invocation for maximum typing productivity? I'd pay for that! 😁

@DustinCampbell 

So I think there are multiple things we could think about in this area.
1.  What we already are working on is the 'intent' based detection which allows intellicode to suggest refactorings based on what you were already doing in the document (e.g. when you add a field and then move to the constructor, we suggest adding that field).  We're looking at expanding this beyond just the constructor refactorings right now.
2.  I think you bring up some good ideas around potentially learning what the most likely refactorings to be chosen from the list are.  The thing to be careful about here is having a non-deterministic order (so that the same keystrokes always bring you to the same refactoring).  I wonder though if we could potentially learn a user-specific preferred order (aka 90% of the time when both extract base and use expression bodied members are shown they pick the second) and statically adjust the list per person (maybe per project?) so that the preferred refactoring comes first.  
3.  It sounds possible to learn the most common place to put the caret after an invocation, however I myself haven't noticed this as a problem, so I'd be super interested if you have a motivating example where we don't do the right thing today.

An alternative non-AI question I would like to ask here is - when both extract base class and expression bodied code actions are in the list, which one do people pick most often?  In general, what is the invocation count of code action X relative to the rest of the code actions that it is shown with?  Because I bet extract base shows up more often than use expression bodied members and so simply may have a higher invocation count because of that.

Then we might be able to do interesting things like when we have both code actions, we prefer expression bodied action over extract base (and in general for any code action).

**Comment by DustinCampbell** [comment]
> The thing to be careful about here is having a non-deterministic order (so that the same keystrokes always bring you to the same refactoring). I wonder though if we could potentially learn a user-specific preferred order (aka 90% of the time when both extract base and use expression bodied members are shown they pick the second) and statically adjust the list per person (maybe per project?) so that the preferred refactoring comes first.

I agree. Many years ago, when I was at another company building refactoring tools, we introduced reordering to the available refactoring list based on the current user's usage within a particular context and had good results, so long as the list was complete. Eventually, the list became fairly stable per user. This would be interesting to experiment with, but I'm also cognizant of your warning around non-deterministic order. However, I wonder if list is already relatively non-deterministic anyway. Consider the following:

1. Every time a new refactoring or fix is added, the list can shift around. We can address that by only adding new actions to the bottom of the list, but that doesn't really help users stay productive if the new action is high traffic.
2. The more granular the context, the more opportunity there is for unique lists with different ordering.
3. We show fixes for diagnostics on the current line, even if the caret isn't within the diagnostic span. These also affect ordering.

> It sounds possible to learn the most common place to put the caret after an invocation, however I myself haven't noticed this as a problem, so I'd be super interested if you have a motivating example where we don't do the right thing today.

Currently, caret position/selection after a refactoring usually just stays where it was when the refactoring was initiated. However, productivity gains can be achieved by moving the caret to the next obvious place where the user will want to type code. Again, this is something that other tools invest a lot of thought and effort in per fix/refactoring. This can also be a bit contentious. :smile:

A simple example is something like "Move Declaration Near Reference". Currently, the caret stays right where it is, even if the declaration is moved off screen. Or, consider something like Invert If in a scenario like this:

```C#
class C
{
    int M(int x, int y)
    {
        int z = 4;

        if (x > y)
            z = 42;

        Console.WriteLine(z);

        return z;
    }
}
```

Try placing the caret after `if (x > y)` and invoke "Invert If". The caret gets moved here:

![image](https://user-images.githubusercontent.com/116161/171746553-75ee6dfe-efdb-43f4-9ade-f92736014463.png)

Is that the next place the user wants to type? Maybe? However, I suspect that little to no thought was given to caret position after the refactoring, so the actual text changes push the caret along.

That's not a great motivating example. I'm really just trying to point out that it matters. :smile:

**Comment by CyrusNajmabadi** [comment]
> Eventually, the list became fairly stable per user. This would be interesting to experiment with, but I'm also cognizant of your warning around non-deterministic order.

Note: we've done this for the 'wrapping' refactoring, and we've definitely heard from people that htey have no idea what's going on and that they dont' like that the items can move around.  That said, maybe the set that is perturbed by this is much smaller than the set of people that just don't even notice and like the behavior.

**Comment by CyrusNajmabadi** [comment]
> This can also be a bit contentious.

This definitely worries me as we've made some of these decisions, only to roll them back when people don't like it.  I do agree there are a set of cases where the caret moving is a non-sensical thing.  e.g. it happens because we effectively generate new tree, determine diff, and splat in teh text edits.  When the edit actually interacts with teh caret location, it's non trivial to determine where it should go (i know, i spend ages trying to tweak that for a lot of our string-literal-editing features).  

Primarily, i think a core issue here is that the overall cost to make this work is disproportionately high.  We've focused heavily on making it trivial to express a tree transform.  But certain edges fo that transform are extremely hard to get right.  Even now things like properly handling all trivia, indentation, or caret-placement are all in those buckets of: this would likely be N times more code and complexity than the core logic of the feature today.  So it's hard to justify that much work for the end effect.  At least, not without a strong argument that this is what is needed for the business needs.
