### ISSUE TITLE
API Additions for Required Members

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#61444]
## Background and Motivation

C# 11 is adding required members. These are the public apis we're adding for the feature.

## Proposed API

```diff
namespace Microsoft.CodeAnalysis
{
    public interface IFieldSymbol
    {
+        public bool IsRequired { get; }
    }
    public interface IPropertySymbol
    {
+        public bool IsRequired { get; }
    }
}
namespace Microsoft.CodeAnalysis.CSharp
{
     public enum SyntaxKind
     {
+        RequiredKeyword = 8447
     }
}
namespace Microsoft.CodeAnalysis.Editing
{
    public struct DeclarationModifiers
    {
+        public static DeclarationModifiers Required { get; }
+        public bool IsRequired { get; }
+        public DeclarationModifiers WithRequired(bool isRequired);
    }
}
```

**Comment by Neme12** [comment]
I think that one thing that will be important for Roslyn consumers is to be able to ask "given that an object is created with a certain constructor, is member X required to be initialized?"

They could of course check for the presence of the "SetsRequiredMembers" attribute, but this is really a language feature so I feel like there should be a specific API for this in the symbol APIs. The language decided to do this via attributes, but it could as well have been a special syntax and I feel like if the language went with a special syntax for this instead, then this info *would* be present in the symbol APIs. I think it should be there even if it's done via attributes.

It's a shame that there's no `IConstructorSymbol` - that would be an appropriate place to put this API in, but it could look like this even on `IMethodSymbol`:
```c#
public bool SetsRequiredMembers { get; }
```
This covers the attribute, but to make this future-proof, a better API would be to be able to ask for individual members, because I can imagine that the language can make the attributes more granular in a future release, and in that case, the API above could become incorrect when someone uses the more granular attributes. I think this would be better:
```c#
public bool SetsRequiredMember(IFieldSymbol field);
public bool SetsRequiredMember(IPropertySymbol property);
```
The problem with this shape is what to return if the member isn't actually required. It could of course throw. Or return `false` since the member isn't even required - but given that the scenario would be to check whether a member is required in the initializer after calling the constructor, that would mean checking the negative of this, and for that scenario, it would make a lot more sense to return `true` for non-required members - because it's as if they were required but the constructor set them, meaning they're not required at the construction site. But a proper API for that scenario would actually be this:
```c#
public bool IsMemberRequired(IFieldSymbol field);
public bool IsMemberRequired(IPropertySymbol property);
```
This would be opposite of the `SetsRequiredMember` API above and I think that this one would be more useful and much easier to use. It would answer the question that given the object is constructed with this constructor, is this member required to be initialized in the initializer? If the member is not required, this would return `false`. If it is but the constructor is annotated as setting the member, this would return `false`. Otherwise, this would return `true`.
Alternatively, instead of checking each member manually, the API could return all members that are required to be initialized given a certain constructor:
```c#
public ImmutableArray<ISymbol> GetRequiredMembers();
```

Also, as opposed to putting these on `IMethodSymbol` and throwing if the method isn't a constructor, I think there should really be an `IConstructorSymbol` interface added. I imagine that this isn't the only API that is useful for constructors but not other kinds of methods.

**Comment by CyrusNajmabadi** [comment]
I don't see the need for an IConstructorSymbol. This would be similar to having INamedTypeSymbol but no subtypes for things like delegates, enums, tuples, etc.  But we still have members specific to those subtypes available.

**Comment by CyrusNajmabadi** [comment]
> I think it should be there even if it's done via attributes.

It feels like this could just be added as an extension method on top of whatever API we deliver. 

--

Ashley, what scenarios are you envisioning that need these apis?

**Comment by Neme12** [comment]
> This would be similar to having INamedTypeSymbol but no subtypes for things like delegates, enums, tuples, etc. But we still have members specific to those subtypes available.

Yes, there are members specific to subtypes on more general types, but I think this generally makes the APIs confusing if you have a property or method that is irrelevant to what you're dealing with. For example, it's confusing that you have things like `IsVirtual` and `IsSealed` on local variables. This also makes it harder to use because you have nullable APIs where they wouldn't have to be nullable if they only existed on symbols they're applicable to, or at least were specialized there to be non-null - e.g. things like `ContainingSymbol`. I think having more derived interfaces for the appropriate symbol kinds would make the APIs easier to use in general.

**Comment by CyrusNajmabadi** [comment]
> Yes, there are members specific to subtypes on more general types, but I think this generally makes the APIs confusing if you have a property or method that is irrelevant to what you're dealing with.

**Comment by CyrusNajmabadi** [comment]
> I think having more derived interfaces for the appropriate symbol kinds would make the APIs easier to use in general.

Such a discussion shoudl likely be pulled out of this feature API area.  If you have an idea/proposal, can you open another API issue on that?

**Comment by Neme12** [comment]
> Ashley, what scenarios are you envisioning that need these apis?

For example, something like a code fix to initialize all required members if there's a compiler error that they're not initialized when constructing an object.

**Comment by Neme12** [comment]
Checking for whether the member is required could be sufficient for that for now but that's not future proof.

**Comment by CyrusNajmabadi** [comment]
@Neme12 i feel like we can just tell that by looking at the constructor called, the set of members in the type, and the set of members initialized at the construction site.  Given the API listed above, it seems sufficient.

**Comment by Neme12** [comment]
Also, my point is that `SetsRequiredMembers` is a language feature and it doesn't feel like the proper way to do this to check the attributes of the constructor - there should be at least a property on the constructor symbol IMO.

**Comment by CyrusNajmabadi** [comment]
> Checking for whether the member is required could be sufficient for that for now but that's not future proof.

Future proof is a non-goal here.  It's effectively impossible as we have no idea what the future will bring in the language.  Even if there were some change, it may come along with other thigns a feature woudl have to check.  IT's also potentially harmful to introduce APIs that have a certain concept, which we hope will fit a future design, and then have it be incompatible with whatever those future designs are.  THen we'll need a parallel api to whatever we add which is the "no really... this is the one that actually answers the question" :)

The API we have should match and model the language change we're making.  And we should ensure that our features can eb built on top of that.

**Comment by CyrusNajmabadi** [comment]
> Also, my point is that SetsRequiredMembers is a language feature and it doesn't feel like the proper way to do this to check the attributes of the constructor - there should be at least a property on the constructor symbol IMO.

I think that general point is fine.  Though my counterpoint to it stands:

> It feels like this could just be added as an extension method on top of whatever API we deliver.

My general question though was on your other APIs you were suggesting.  I'm trying to figure out the use cases for them that require them to be delivered by the compiler as APIs in the initial release here.

**Comment by 333fred** [comment]
If we come across a use case in the future, I'm not opposed to having an API to expose whether a constructor requires that members be set or not. I did not need any such api for the initial ide support, so I did not add one.

> something like a code fix to initialize all required members if there's a compiler error that they're not initialized when constructing an object

No such api would be needed here: you'd have a compiler error for every missing member. You'd just trigger on that error.
