### ISSUE TITLE
Close a region at the #endregion code

### ISSUE THREAD

**Issue by Elantonio** [dotnet/roslyn#61596]
Enable to close a region at the #endregion code, for large regions., instead of having to scroll back, where the matching #region tag is easy overlooked. the ctrl-] does not work well and is counter intuitive.

**Comment by sharwell** [comment]
💡 This already works if you double click in the left margin. If this is not sufficient, I would suggest using the [Report a Problem](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022) workflow since this UI is not controlled by this repository.

**Comment by Elantonio** [comment]
Very nice to close it but i've been tapping the left margin dozen of times and nothing happens.
Can you show how it's done?
