### ISSUE TITLE
Can't add semi-colon to end of line

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#61638]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Cant-add-semi-colon-to-end-of-line/10058391)._

---
Add these two lines to a cs file:

                            string fileName = string.Concat(project, ".", Path.GetFileName(packageCache)
                            File.WriteAllText(Path.Combine(options.ArchivePath, )));

Now try to put a semi-colon at the end of the first line. I'm running Version 17.2.2 and whne I type ";", the cursor moves the end of the next line and add "; ", leaving me with this:

                            string fileName = string.Concat(project, ".", Path.GetFileName(packageCache)
                            File.WriteAllText(Path.Combine(options.ArchivePath, ))); ;

And if I do it a bunch of times, moving to the end of the list line each time, I get:

                            string fileName = string.Concat(project, ".", Path.GetFileName(packageCache)
                            File.WriteAllText(Path.Combine(options.ArchivePath, ))); ; ; ; ; ; ; ; ; ; ; ; ;

---
#### Feedback Bot on 5/31/2022, 08:15 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by Youssef1313** [comment]
This is a feature called complete statement. The goal of the feature is to allow let you type a semicolon when you're not at the end of statement. For example if you type `Console.WriteLine(`, you'll find that Visual Studio wrote the `)` for you and the cursor is between the `(` and `)`. Normally, if you want to type the semicolon, you'll hit the right arrow then type `;`. With this feature, you can type `;` when you're between the opening and closing parenthesis and it will go to the end of the line.

For the case above, the feature got a little bit confused because you're missing a closing parenthesis  in the first line. I'm not sure if there is a good way to improve the feature.

But anyway, if you want to disable the feature, you can do that from **Tools** → **Options** → **Text Editor** → **C#** → **IntelliSense** → uncheck **Automatically complete statement on semicolon**:

![image](https://user-images.githubusercontent.com/31348972/171554097-d37548b6-14b9-4a7b-868a-8136a6f71702.png)

**Comment by sharwell** [comment]
> For the case above, the feature got a little bit confused because you're missing a closing parenthesis in the first line.

It's confused because there was a missing `)` on the first line _and also_ there was an extra unnecessary `)` on the second line. This means the parentheses are already balanced and the `;` was placed outside them. Typing <kbd>Ctrl</kbd>+<kbd>Z</kbd> (Undo) for this case will restore it to the location where it was typed.
