### ISSUE TITLE
.editorconfig doesn't affect ctrl-shift-B / command-line builds?

### ISSUE THREAD

**Issue by stephentoub** [dotnet/roslyn#61724]
**Version Used**: 
Version 17.3.0 Preview 2.0 [32525.520.main]

**Steps to Reproduce**:
```C#
var o = new object();
Console.WriteLine(o);
```

**Expected Behavior**:
Red squiggles / error in VS.
Build error with ctrl-shft-B.

**Actual Behavior**:
Red squiggle in VS, but no build error with ctrl-shft-B.
<img width="833" alt="image" src="https://user-images.githubusercontent.com/2642209/172224236-46cf1e62-96ee-4706-a965-684406e34495.png">

**Comment by CyrusNajmabadi** [comment]
@jmarolf do you know what would cause this?

**Comment by jmarolf** [comment]
As of now you need to add [`EnforceCodeStyleInBuild`](https://docs.microsoft.com/dotnet/core/project-sdk/msbuild-props#enforcecodestyleinbuild) to your Dirs.props

```xml
<PropertyGroup>
  <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
</PropertyGroup>
```

This is still opt-in because, once you do this, the version of the compiler in your SDK must be the same or newer as the one you are using in VS. This is likely fine for dotnet/runtime as you are always using preview SDKs.

but if folks have a global.json to restrict to the 6.0.300 SDK and they use the 17.2 version of Visual Studio (which uses the 6.0.200 version of the compiler). They will get build errors in Visual Studio about not being able to load these code-style analyzers.

**Comment by Youssef1313** [comment]
Another thing to add is setting code-style options from EditorConfig UI uses the `option = value:severity` syntax only (at least that's how it worked last time I used the UI). Setting the severity this way is respected only by the IDE, not by the compiler. So a `dotnet_diagnostic.IDExxxx.severity = error` is also needed in `.editorconfig`.

**Comment by louis-z** [comment]
> It's also showing me _two_ errors in VS, both for the same error: <img alt="image" width="525" src="https://user-images.githubusercontent.com/2642209/172224526-5882a1ad-717c-42c1-8159-0a36bc71f365.png">

This was reported in https://github.com/dotnet/roslyn/issues/57647.
