### ISSUE TITLE
IDisposable analyzer

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/roslyn#61850]
**Brief description:**
A class that implements ```IDisposable``` is special because it may represent a resource (potentially unmanaged) that should be freed.  As C# is increasingly used to write low-level code, this continually becomes more and more important.

An analyzer should exist that will flag when classes that implement ```IDisposable``` are created that:
1. Are not disposed of (either explicitly or via ```using```)
2. (if possible), do not escape the current method (either via return, out, or assignment to a property, or by being passed into a method that would cause it to escape).
3. Offered a fixer that would change ```var x = new <IDisposable Type>``` to ```using var x = new <IDisposable Type>```

Additionally, it would be nice if the Visual Studio editor provided some type of unique colorization for variables that are of types that implement IDisposable.

**Comment by Youssef1313** [comment]
Have you seen [CA2000: Dispose objects before losing scope](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca2000)?

Other `IDisposable`-related analyzers:

https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2213
https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1063
https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2215
https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1001

**Comment by vatsalyaagrawal** [comment]
Closing. Please reopen if you have more questions.

**Comment by achobanov** [comment]
@Youssef1313 @vatsalyaagrawal landed here looking for an alternative of CA2000 as It seems to be conservative with its flagging. For example:
```c#
var request = new HttpRequestMessage(...) // flagged
var response = await httpClient.SendAsync(request); // not flagged
```

I read somewhere that it only flags instances that it's sure are owned by the user, so it flags request, because it detects its constructor usage, but not response, because it was returned from another method. I understand this line of thought, but is not possible to improve further? Maybe an attribute that flags the response of `SendAsync` as consumer-owned?
