### ISSUE TITLE
csc/vbc crashes on coreclr -23419 on Linux

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#6187]
ExecutionEngineException while trying to load satellite assemblies. Note sure what the root cause is, yet. -23413 works.

**Comment by janvorli** [comment]
@agocke There was a bad merge in the coreclr repo for several days, which by mistake reverted few commits, including my fix to an unhandled exception processing when the exception was caused e.g. by an assembly referencing an assembly that didn't exist. 
So your issue can be caused by that. It was fixed again last night.

**Comment by agocke** [comment]
@janvorli Great, thanks! Do we expect a new MyGet upload soon that contains the fix?

**Comment by janvorli** [comment]
I don't actually know how often is the coreclr packaged. 
@mmitche do you know that?

**Comment by weshaggard** [comment]
@janvorli it is packaged and uploaded daily. When did the code fix for this go in?

**Comment by janvorli** [comment]
@weshaggard It went in yesterday at 11:24 pm PST

**Comment by weshaggard** [comment]
OK I would expect the package for tonight's official build would have the fix and should be published tomorrow morning.

**Comment by agocke** [comment]
Confirmed fixed by #6402
