### ISSUE TITLE
Enabling rules from solution explorer doesn't do anything if there's a nowarn in the project

### ISSUE THREAD

**Issue by srivatsn** [dotnet/roslyn#619]
Repro Steps
- Create a project and add the FxCop analyzers to the project. 
- Add some code to fire a violation (say - create an empty enum). Enable CA1008 from solution explorer  and see that the violation is reported.
- Now edit the csproj file and add a <NoWarn>CA1008</NoWarn> to the project.
Note that in Solution explorer, the rule now shows up as disabled. Try to enable it.

**Actual**: Nothing happens.
**Expected**: Some indication of activity. I don't think we want to trawl through the csproj and check to see if there was any configuration - won't be possible if the property was inherited. But I think we should give throw up an error if we try to change the severity and the effective severity is still the same.

**Comment by tmeschter** [comment]
@srivatsn There's currently no way for us to determine that the effective severity has not changed. We write the new severity to the .ruleset file and at some later point the language services see that it has updated on disk, read the file, and push the new options to the workspace.

We could write a message to the status bar indicating that we updated the rule set file.

**Comment by tmeschter** [comment]
Per further discussion with @srivatsn we're going to do the following:

  1. Update the context menu you see when right-clicking on a diagnostic to show the severity in the rule set file, rather than the effective severity. The icons in Solution Explorer will continue to reflect the effective severity.
  2. Move the severity menu items (Error, Warning, Info, etc.) into a submenu called "Set Rule Set Severity" to make it clearer what exactly is going to be changed when you click those.
  3. Add a Default severity menu item (though that's really part of the fix for #468).

**Comment by tmeschter** [comment]
Assigning back to @srivatsn for verification.

**Comment by srivatsn** [comment]
I've verified steps 1 and 2 are complete. However, step 3 is not done and #1512 tracks an issue related to that. Let's just use that issue to track the remaining work. I'll mark this bug as verified.
