### ISSUE TITLE
IBraceCompletionService is ILanguageService, but its implementations are not exported via ExportLanguageService

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#61935]

**Comment by sharwell** [comment]
The underlying issue here is `IBraceCompletionService` is meant to have more than one implementation at a time, but `ILanguageService` is only intended to have one implementation. The simple solution is to remove `ILanguageService` from the list of interfaces implemented by `IBraceCompletionService` (it's not being used today as a language service, so this is a trivial change).

**Comment by tmat** [comment]
Sounds good. I wasn't sure what the intent was. I'll remove ILanguageService from IBraceCompletionService
