### ISSUE TITLE
VS doesn't navigate to Source Link for Console.WriteLine

### ISSUE THREAD

**Issue by chuckries** [dotnet/roslyn#61942]
**Version Used**: 
Microsoft Visual Studio Enterprise 2022 (64-bit) - main
Version 17.3.0 Preview 3.0 [32613.413.main]

**Steps to Reproduce**:

1. Create a net6.0 console app
2. F12 on `WriteLine` of the Cosnole.WriteLine

**Expected Behavior**:
VS navigates to the Source Link file for the definition of Console.WriteLine
**Actual Behavior**:
VS navigates to metadata

Output log:
Navigating to symbol 'System.Console.WriteLine(string?)' from 'System.Console'.
Symbol found in assembly path 'C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.5\ref\net6.0\System.Console.dll'
Symbol found in assembly path 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.5\System.Console.dll'
Could not find implementation of symbol 'WriteLine'

FWIW, F12'ing to Console does navigate to the Source Link file for Console.

**Comment by davidwengier** [comment]
Looks like this is caused by SymbolKey resolution failing, I think maybe because of nullability differences. No idea how symbol key resolution works though :)

**Comment by chuckries** [comment]
What do you mean by SymbolKey resolution? Is the debugger failing to return a PDB? Or is this a MetaData issue?

**Comment by davidwengier** [comment]
No, sorry, its a roslyn thing. Basically we have a compilation with a bunch of reference assemblies, and you're navigating to `Console.WriteLine(string)` from there. That method has a metadata token we know about. When we find the implementation assembly that its in, we have to find the method again, because the metadata token will be different, so we try to resolve `Console.WriteLine(string)` from the new DLL. Unfortunately that is failing because the parameter type, string, is not in that DLL.

**Comment by davidwengier** [comment]
Yep, already doing that, this was just an issue with how I created a minimal temporary compilation.. it was a little too minimal :)
