### ISSUE TITLE
Unexpected CS0529 and CS0146

### ISSUE THREAD

**Issue by DoctorKrolic** [dotnet/roslyn#62006]
**Version Used**:
Latest main

**Steps to Reproduce**:
```cs
public interface IInterface : IInterface.IInterface2
{
    public interface IInterface2 { }
}

public class MyClass : MyClass.C
{
    public class C { }
}
```

**Expected Behavior**:
No errors, but I might be wrong here.

**Actual Behavior**:
CS0529: Inherited interface 'IInterface.IInterface2' causes a cycle in the interface hierarchy of 'IInterface'
CS0146: Circular base type dependency involving 'MyClass.C' and 'MyClass'
[sharplab](https://sharplab.io/#v2:C4LgbgpgTglgZgTwD4AEDMACGA7Y04CGAxhBgJJm77GkjmV5SEkB0FVTNATALABQAb34YRGdFg7NS7RlK4YBGAL78VffuJTyAsggDCAGwIBnYxjq7DJ4yz38hfUWMxaMehctVA==)

**Comment by Youssef1313** [comment]
Similar issue https://github.com/dotnet/roslyn/issues/58424

**Comment by CyrusNajmabadi** [comment]
https://github.com/dotnet/csharpstandard/blob/draft-v6/standard/classes.md#14242-base-classes says:

> It is a compile-time error for a class to depend on itself. For the purpose of this rule, a class directly depends on its direct base class (if any) and directly depends on the nearest enclosing class within which it is nested (if any). Given this definition, the complete set of classes upon which a class depends is the transitive closure of the directly depends on relationship.

In this case, C depends on 'MyClass' (since MyClass is the nearest enclosing class which it is nested).  'MyClass' also directly depends on 'C' since that is its direct case class.  So there is a transitive circularity and that's a compile-time error.

From my reading, this should not be allowed.  If you feel like my interpretation of hte spec is incorrect, please let me know.

**Comment by DoctorKrolic** [comment]
@CyrusNajmabadi I took me about 10 minutes to think it through and in the end I agreed with you, thanks!
