### ISSUE TITLE
Allow ref field of the containing type

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#62098]
Allow the following:
```csharp
ref struct R<T>
{
    public ref R<T> Next;
}
```

Relates to test plan https://github.com/dotnet/roslyn/issues/59194

**Comment by RikkiGibson** [comment]
Is this planned for C# 11?

**Comment by jaredpar** [comment]
> Is this planned for C# 11?

No. This section of the proposal is attempting to keep track of what will make C# 11 vs. later releases 

https://github.com/dotnet/csharplang/blob/main/proposals/low-level-struct-improvements.md#what-will-make-c-110

**Comment by John0King** [comment]
any news on here ?  
[demo link](
https://sharplab.io/#v2:EYLgtghglgdgNAFxAJwK7wCYgNQB8ACATAIwCwAUPgAwAE+xAdAEroJRgCmDAwgPZgAHKABsOyAMpiAblADGHAM4BuCtTqMWMNpwYBJLWN4DJyGfOWra9Zq3Zd9CQ8elzFDALIRkCgBYRhwrAA5irkqgDMNMgcAGY0Cghosgg0ACrRHAByvBgcADypAHwUAN4UNBU0APRVANoAYlAcwhgA8jExChwIABRUAJQAuuWV+JHRcak0ADKxCKGVNCMVNQ1NLe2d3T0AHEPLdOOxaTRMUEE+8wcUAL4UEXSE6gDspQdjNOgKEDEc6gBsdAALDRPLAev0DmVyItFlIvPEaABeeJQABeHF4MR66Q4WRy+WEvBgQUK/QWsIq9AAnD0FOSDotGZV4ch4sRkaiMVicRlsrk8rAEGSKZSaXTiAyYZSaKz4k8UQp0Zjsbj8QLfLxkMKpTL1LSFIRdZU7uQbkA)
<img width="786" alt="image" src="https://user-images.githubusercontent.com/13639146/211986867-65db5da1-ec20-4c42-9a56-131ef7ae9ff8.png">

since the ref field  is a `T&`   in IL   and it size is fixed to 8 byte on x64,   this could allow us to wirte a  struct `TreeNode<T>`  instead of using class

by the way,  Java can optimize `class` to be allocate on stack ,  and I think that why it‘s "binary-trees“ benchamark faster than C# 
https://benchmarksgame-team.pages.debian.net/benchmarksgame/fastest/csharp.html

**Comment by jaredpar** [comment]
Closing as ref fields of ref struct are not permitted by the language spec. It's not specific to containing type.
