### ISSUE TITLE
Public API to compare symbols across different compilations

### ISSUE THREAD

**Issue by mcpiroman** [dotnet/roslyn#62465]
## Background and Motivation

I'm working on project with multiple `CSharpCompoiation`s. When I get the same symbol from two of them (e.g. one of them compiled class `Foo` and the other one referenced that class), they are (sometimes?) not considered equal by the `SymbolEqualityComparer.Default`, even though their full name and other properties match.

The compilations either do have the exact same References provided, or one compilation is a referenced by another via `a.AddReferences(b.ToMetadataReference()))`.
## Proposed API

There is internal `SymbolEqualityComparer.CLRSignature` which looks like it is meant for such comparation. Maybe just expose it as public? Or just alter the behaviour of `SymbolEqualityComparer.Default`.

**Comment by CyrusNajmabadi** [comment]
We've avoided this as there is no well defined meaning of waht 'equality' is across a compilation.  So the expectation is that you would roll your own based on your needs.

As an example: all symbols are effectively reachable from all others.  Which means you can observe any difference across compilations (including location).  So even typing a single space in a file will mean that there are observable differences.  So deciding if symbols in these situations are equal or not is ultimately up to the individual domain.

**Comment by CyrusNajmabadi** [comment]
>  not considered equal by the SymbolEqualityComparer.Default, even though their full name and other properties match.

This may be because the symbols are retargetted.  

If you truly think these symbols should be considered the same, then can you please supply a repro project where they are not, and someone can take a look to see if it's a bug, or it's actually working as intended.  Thanks!

**Comment by mcpiroman** [comment]
OK, but is there something that would compare symbols the same way as a .NET runtime does? Of course not for ones like ILocalSymbol or IAliasSymbol as they probably do not exist at runtime.

I have just found out that comment:
> The FAQ (https://github.com/dotnet/roslyn/wiki/FAQ) states repeatedly: "Comparing symbols from different compilations has undefined results."

But I can't find anything like that in the docs now.

**Comment by AlekseyTs** [comment]
We explicitly do not support equality of symbols across compilations. Equality result is well defined only for symbols obtained through the same compilation. Note, that in some situations symbols obtained through one compilation could be reference identical to symbols obtained through another compilation. That is happening due to an optimization meant to reduce memory consumption. Obviously, such symbols will be considered equal.

> to weigh in on if we expect the above code to print true, or if 'false (or undefined-behavior)' is expected.

From the example as written, I expect the code to print ```true```. However, the devil is in the details. If in the real scenario symbols of compilation 'A' are not reused by compilation 'B' (for example, due to references mismatch, etc.), I expect the result to be ```false```.
