### ISSUE TITLE
bug either in Roslyn or in the C# language spec — example with `ReadOnlySpan` in a `foreach` expansion

### ISSUE THREAD

**Issue by ltcmelo** [dotnet/roslyn#62747]
This is an issue [I originally reported in the C# lang. spec repo](https://github.com/dotnet/csharplang/issues/6289). My original report was for the C# specification, as my assumption was that the specified `foreach` expansion was inaccurate. Consider the program below, which is compiled **without** errors.

```
public class C
{
    public async Task M()
    {
        IReadOnlyList<string> o = null;
        foreach (ReadOnlySpan<char> c in o) {}        
        return;
    }
}
```

Expanding its `foreach` as [according to the specification](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/statements#1295-the-foreach-statement) introduces a diagnostic:

_error CS4012: Parameters or locals of type 'ReadOnlySpan<char>' cannot be declared in async methods or async lambda expressions._

But it turns out that, according to @CyrusNajmabadi and @333fred , the real issue is that my original program is ilegal, even accepted by Roslyn. So I was told to open an issue here.

**Comment by CyrusNajmabadi** [comment]
> Expanding its foreach as according to the specification introduces a diagnostic:

> error CS4012: Parameters or locals of type 'ReadOnlySpan' cannot be declared in async methods or async lambda expressions.

For completeness, and ot prevent people from accidentally expanding things differently than how you're expanding htings, can you include your expansion so there's no confusion down the line?

**Comment by CyrusNajmabadi** [comment]
@ltcmelo  i don't mean your code that does the expansion. I mean the code that your expansion *generated*.  e.g. the code that caused this error to be reported:

> error CS4012: Parameters or locals of type 'ReadOnlySpan' cannot be declared in async methods or async lambda expressions.

**Comment by ltcmelo** [comment]
> I mean the code that your expansion generated

It's the one that you'd get by expansion from the specification. :-) 
The error is reported at:

```
ReadOnlySpan<char> c  = (ReadOnlySpan<char>)(string)e.Current;
```

Which corresponds (in the specification) to:

```
V v = (V)(T)e.Current;
```

**Comment by CyrusNajmabadi** [comment]
> It's the one that you'd get by expansion from the specification

For completeness, and ot prevent people from accidentally expanding things differently than how you're expanding htings, can you include your expansion so there's no confusion down the line?

**Comment by ltcmelo** [comment]
>  prevent people from accidentally expanding things differently than how you're expanding htings

@CyrusNajmabadi , how I'm (or anyone else is) expanding it is circumstantial—the expansion is governed by the language specification. But here it is, as you ask:

```
public class C
{
    public async Task M()
    {
        IReadOnlyList<string> o = null;
        {
              var e_L10C8 = ((IEnumerable<string>)o).GetEnumerator();
              while (e_L10C8.MoveNext())
              {
                  ReadOnlySpan<char> c =(ReadOnlySpan<char>)(string)e_L10C8.Current;
                  {}
              }
        }
        return;
    }
}
```

Note: The `_L10C8` suffix is just a convention to indicate that the (original) expression occurs at Line 10 and Column 8.

**Comment by Joe4evr** [comment]
For the record: this issue has nothing to do with spans in `foreach` ([your sample code works perfectly fine if the method is simply `void` instead of `async Task`](https://sharplab.io/#v2:EYLgtghglgdgPgAQEwEYCwAoBAGABAlAFgG5MEBmfJXAYUwG9Ndn9KFDcBZACgEomWjDCxG4AkgCUAphAAmAeRgAbAJ4AZKAGcALgB4C2AHy4A9rgC8uGAFclS0sNHMAZiYBOMgMYALXN2lyiqoAygAOEDC6PhBuxp64sKa8uPQAvk7MAk4IAOwOIqmYqUA=)) but everything to do with the fact that it is illegal to declare local variables of spans/ref-structs in `async` methods (which is clearly explained to you in your error message).

**Comment by bernd5** [comment]
The same is true for code like:

```CSharp
using System;

F.GetArr().AsSpan()[2] += 3;
await System.Threading.Tasks.Task.CompletedTask;

static class F
{
    private static int[] a = {1, 2, 3};
    public static int[] GetArr(){
        return a;
    }
}
```

The spec says: 
For a binary operator op, a compound assignment expression of the form
```CSharp
x op= y
```

is equivalent to

```CSharp
x = x op y
```

except that x is only evaluated **once**.


==> To get similar code we would need to declare a temporary of a ref-struct type (which is what the compiler actually does).

```
.method private final hidebysig newslot virtual 
            instance void MoveNext () cil managed 
        {
            .override method instance void [System.Runtime]System.Runtime.CompilerServices.IAsyncStateMachine::MoveNext()
            // Method begins at RVA 0x20d4
            // Code size 166 (0xa6)
            .maxstack 3
            .locals init (
                [0] int32,
                [1] valuetype [System.Runtime]System.Span`1<int32>, //<-- HERE
                [2] valuetype [System.Runtime]System.Runtime.CompilerServices.TaskAwaiter,
                [3] class [System.Runtime]System.Exception
            )

            // sequence point: hidden
            IL_0000: ldarg.0
            IL_0001: ldfld int32 Program/'<<Main>$>d__0'::'<>1__state'
            IL_0006: stloc.0
            .try
            {
                // sequence point: hidden
                IL_0007: ldloc.0
                IL_0008: brfalse.s IL_0056

                IL_0
```

**Comment by ltcmelo** [comment]
> this issue has nothing to do with spans in foreach  

@Joe4evr  you're right… but that isn't why my issue is about; even though the title is misleading so I'll adjust it.

@bernd5 I don't see a relation of your comment to the issue I'm raising… 

It seems you both pointing to a possible cause of the issue or explanation of the language rules. I'm not interested neither in the cause nor in an explanation; I'm just pointing that there's either a bug in the Roslyn or in the C# language spec.

**Comment by bernd5** [comment]
Similar to the foreach expansion, the "expansion" of operator "+=" is sometimes not possible in async code without the usuage of ref struct temps (which are prohibited by user code)...

You can't write / expand it to:
```csharp
using System;
var span = F.GetArr().AsSpan();
span[2] = span[2]+ 3;
await System.Threading.Tasks.Task.CompletedTask;

static class F
{
    private static int[] a = {1, 2, 3};
    public static int[] GetArr(){
        return a;
    }
}
```

(Btw. ref structs locals are allowed in generator methods - but because `yield return` / `yield break` is a statement - safety rules are easier to prove)

**Comment by bernd5** [comment]
Oh, you are right - I missed the point.

**Comment by CyrusNajmabadi** [comment]
> how I'm (or anyone else is) expanding it is circumstantial

That's why I asked for it for completeness. You said you got a particular error. I wanted to make sure that we don't do things differently, leading to not getting that error.

**Comment by TessenR** [comment]
@333fred interesting, but couldn't the same logic be applied to `using (expr)` which is disallowed in the pull request above?

i.e. like this [sharplab.io](https://sharplab.io/#v2:EYLgtghglgdgNAExAagD4AEBMACdBGAdgFgAoAb1OyvQGZc8A2XADlwBZsBZaGACgEpKVCiSpjqABmy8AwgHs5AaygBTAHQyATiogAXFQMGjxwoSep4AnAIDcZ8QF8zTki9LaAZtgDOuzQFcAY11seSVVUhFqOnwmMOUVUO09A35sAF4APmwYFQB3W3shWnZsABEobwAHOW9U7DJsFwcgA==):
```csharp
class Program
{
   public static async void Main()
   {
       using (Cookie.Create())
       {
         Console.WriteLine();
       }
   }
}

ref struct Cookie
{
  public static Cookie Create() => new();
    
  public void Dispose() { }
}
```

As long as there's no awaits inside the using statement, which seems easy to verify, the variable is never exposed to the user and never hoisted to the state machine. Shouldn't such code be allowed then?

**Comment by TessenR** [comment]
I'm asking because the implemented change is a breaking change for one of the code bases I'm working with.

If you need more context for the scenario where it was used - it was very convenient to use a disposable ref struct to encapsulate a lock in such a manner, in order to prevent potential context switches under a lock and limit the lock's lifetime. `using (LockCookie.Create())` ensured a lock over a section _and_ disallowed awaits in it at the same time as long as the created value is a ref struct.

The trick worked perfectly for years - emitting a compile time error for `await` expressions under such using statements and compiling correctly as long as there were not `await`'s. Now the code is broken and a nice mechanism for additional control over critical sections is gone for no apparent benefit, as it seems that there was nothing inherently wrong with the code except for the fact that its expansion according to spec wasn't valid.

Perhaps, it would be possible to apply the same logic from the interpolated string handler to `using (ref_struct_expr)`? As long as the `using` variable is not exposed to the developer, the compiler has exclusive control over its lifetime and can ensure that there are no awaits during its lifetime, the code might be allowed to compile.
