### ISSUE TITLE
Major performance regression of the array initialization pattern 

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/roslyn#62864]
In https://github.com/dotnet/performance/pull/2534 I've bumped BDN version to see if @MichalStrehovsky fix (https://github.com/dotnet/BenchmarkDotNet/pull/2046) helped. It did, but new issue popped out.

86 out of 4334 benchmarks that were working fine in the past (2 months ago was the last time I run them), are now failing with `PlatformNotSupportedException`:

```log
 System.PlatformNotSupportedException: Operation is not supported on this platform.
    at Internal.Runtime.CompilerHelpers.ThrowHelpers.ThrowPlatformNotSupportedException() + 0x24
    at System.Net.Primitives.Tests.IPAddressPerformanceTests.<ByteAddresses>d__0.MoveNext() + 0x45
    at System.Linq.Enumerable.<OfTypeIterator>d__65`1.MoveNext() + 0x6b
    at System.Linq.Enumerable.MaxInteger[TSource, TResult](IEnumerable`1, Func`2) + 0x48
    at System.Net.Primitives.Tests.IPAddressPerformanceTests..ctor() + 0x9d
    at BenchmarkDotNet.Autogenerated.Runnable_1..ctor() + 0x2a
    at BenchmarkDotNet.Autogenerated.Runnable_1.Run(IHost, String) + 0x6e
    at BenchmarkDotNet.Autogenerated.UniqueProgramName.AfterAssemblyLoadingAttached(String[]) + 0x1a2
```

for code that seems to be very simple:

https://github.com/dotnet/performance/blob/062e33e11c917ce408ce4b447552185d6565b035/src/benchmarks/micro/libraries/System.Net.Primitives/IPAddressPerformanceTests.cs#L17-L26

I have moved this code to a standalone app and was not able to repro the issue.

Repro steps:

```cmd
git clone https://github.com/dotnet/performance.git
cd performance
py .\scripts\benchmarks_ci.py -f nativeaot7.0 --filter System.Net.Primitives.Tests.IPAddressPerformanceTests.Ctor_Span --bdn-arguments "--keepFiles true"
```

BDN reports the path where to project is stored (the last path in the line below):

```log
// start dotnet  build -c Release -r win-x64 --no-restore /p:UseSharedCompilation=false /p:BuildInParallel=false /m:1 /p:Deterministic=true /p:Optimize=true /p:NuGetPackageRoot="D:\projects\performance\artifacts\packages" in D:\projects\performance\artifacts\bin\MicroBenchmarks\Release\net7.0\Job-NYBBDR
```

cc @jkotas

**Comment by jkotas** [comment]
Please revert #62392 ASAP. 

It breaks the pattern matching done by the JIT for array initialization. It will result in major performance regression on most runtime and it breaks NativeAOT that does not support non-standard array initialization patterns currently.

**Comment by jkotas** [comment]
Quick standalone performance test:
```csharp
using System;
using System.Diagnostics;
using System.Runtime.CompilerServices;

Stopwatch sw = new Stopwatch();
sw.Start();
for (int i = 0; i < 1_000_000; i++)
    CreateInitializedArray();
Console.WriteLine(sw.ElapsedMilliseconds);

[MethodImpl(MethodImplOptions.NoInlining)]
static int[] CreateInitializedArray()
{
    return new int[] { 1, 2, 3, 4 };
}
```
Run using:
```
set DOTNET_TieredCompilation=0
dotnet run -c Release`
```

.NET 7 SDK Preview 6: 106ms
Bleeding edge Roslyn (4.4.0-1.22371.1): 10899ms

As you can see, this change introduced 100x regression of the simple array initialization pattern used in this micro-benchmark.

BTW: I do not see any performance numbers in #62392 . In dotnet/runtime, we require performance numbers demonstrating the improvement for any performance optimizations PR. It is not unusual for performance optimizations to not have the intended effect.

**Comment by tannergooding** [comment]
> As you can see, this change introduced 27x regression of the simple array initialization pattern used in this micro-benchmark.

Even with Roslyn reverting the change, we should likely have an issue in the dotnet/runtime repo tracking fixing this on our end. There is no reason that `GC.AllocateUninitializedArray` for constant inputs can't be replaced with a call to `newarr` to ensure there is no regression for "small inputs". That would remove an existing "pit of failure" from an API that looks performance oriented. However, additionally, there is really no reason why we couldn't also optimize `GC.AllocateUninitializedArray` for non-constant length but constant `pinned = false` to also have the correct fast paths so that there is no real perf difference.

Someone just needs to do the work to ensure the relevant handling exists and to ensure that the JIT can properly optimize the code. The actual method is "large" today and isn't inline friendly, even though the checks being done are effectively all constant. For a non-constant length, this function should really be getting inlined as: `if (length < 2048 / sizeof(T)) { return new T[length]; } else { return AllocateNewArray(...); }` -or- even better, have a `CORINFO_HELP_NEWARR_*` API to ensure that this is really just `newarr` with a "should I zero or not" flags check (particularly since the "failure" cases are really just dependent on whether `T` is a reference type or contains references, which is always known at JIT time).

**Comment by jkotas** [comment]
Yes, we can do all that, but the benefits are vanishingly small.

`GC.AllocateUninitializedArray` is also a security trap due to uninitialized data. I kind of like that the API is a performance trap since it forces people to use it only in places where it is actually needed.

**Comment by kasperk81** [comment]
the original api proposal issue is still active. AllocateUninitializedArray is only profitable for larger arrays https://github.com/dotnet/runtime/issues/27146#issuecomment-666721600. we should have an analyzer to clarify it, overall its name is very confusing and it can easily lead developers to thing it's pro performance.

**Comment by tannergooding** [comment]
> Yes, we can do all that, but the benefits are vanishingly small.

Part of this is the existing overhead. For large allocations, the costs can be fairly visible and there are cases where those are frequent enough or where they are happening in contexts where the costs do matter.

> GC.AllocateUninitializedArray is also a security trap due to uninitialized data.

This is no more a trap than `NativeMemory.Alloc` and while `NativeMemory.Alloc` is often a suitable choice, there are many scenarios where it is not.

>  I kind of like that the API is a performance trap since it forces people to use it only in places where it is actually needed.

I don't think that a performance oriented API should be a performance trap. If we want people to be aware of the potential pitfalls of it, that's something that `[UnsafeCallersOnly]` or similar should be for. As the API stands today, it has paths in it to handle the small case but to use it "correctly" (even in cases where it is actually needed), the devs realistically need to duplicate those same checks.

I'm all for telling people "this is dangerous, be mindful of the holes". However, I don't think we should be intentionally making it more problematic to use correctly where there is a decently simple fix that can be made.

**Comment by jkotas** [comment]
Submitted doc update at https://github.com/dotnet/dotnet-api-docs/pull/8249

**Comment by jkotas** [comment]
> use it "correctly" (even in cases where it is actually needed), the devs realistically need to duplicate those same checks.

I disagree. We are using it correctly in our own CoreLib in StringBuilder, ArrayPool and number of other places. Number of these places were heavily micro-benchmarked when the uses of this API were introduced to make sure that there is no regression.

> there is a decently simple fix that can be made.

I do not think that the fix is simple. The GC is heavily optimized for giving you zero-initialized memory. If we were to build uninitialized memory path that is as optimized as the existing zero-initialized path, it would be fairly complex change, and it would be hard to make it pay-for-play.
