### ISSUE TITLE
CS8604 Compiler Warning despite previous null checking against the parameter

### ISSUE THREAD

**Issue by gwake1** [dotnet/roslyn#62975]
**Version Used**: 
net6

**Steps to Reproduce**:
[Gist of Code to Reproduce the Bug](https://gist.github.com/gwake1/f8eb7e8740b00b118981733ff564c93b)

1. Within the project Nullable is enabled
2. When a nullable object is allowed on the method signature
3. After null checking has been performed on the desired object and it's properties
4. When accessing the object and it's already initialized property, the compiler warns CS8604 - Possible null reference argument for parameter.

**Expected Behavior**:
When the project nullable property is enabled, there are no nullability reference compiler warnings for the nullable object after performing null checks.

**Actual Behavior**:
When the project nullable property is enabled, the CS8605 nullable reference compiler warning appears for the nullable object after performing null checks.

**Comment by Youssef1313** [comment]
On [SharpLab](https://sharplab.io/#v2:EYLgtghglgdgPgAQEwEYCwAoBAGABAlAFgG5Md8UA6AGVgEdSMyBmfJXAYVwG9Nd/8rBIVwBZABQBKHnwEBfTAqZYh7AEoBTAM4AHAPYwtGzLwwDBFZgB4C2AHyc9AGycaAxgBcoBgPIAzAGUPACdYAHMtHlwwjQ9iXCM43DlcAF5cAFEYAFcwDWCIYFdKDLAdDwBPGxR7KUYlTBY2TicoDRgPE1l+AGIcl0LXXHbB4wwASFtcAAVgvTdtLU1dAyNxZf1DDQB+XGDtTaNJTHHTcfGoP1xxfZWt3ChI/qdpE9O3/g8ACzmAd1wYBp/gBBYJhXLtDwZAAeC3K3hg4gARAAVL4aPYHVYYx4A7IuShIySMc4NCYXK7iACEt0OGkoHGcrk8CP8QVCMAilGBMAqUmO5LO52+fwBQNwoPBeQ6MLhXgMyLRGNp2IA5JE3Ez3PKYLg9FdbJFcRoypVCcTuuZko1yQgAOyYu5GBlalm+QIhcJaSgAMSgwS0Hh8wQAIho/BB8R5xNC0g5oSU6NkIE4tMiAHL4pycdFuADWet1PmAACttbgIDAACaOFzahG4HRzHT5SoVpz7CBVioPGBQLwpqAALw0VaRABpcOzwoyyhBQloDJRg1XYCmAJJhGB6fYcCBHC1mfhKJRAA), I see only `warning CS8603: Possible null reference return.` (not CS8604), and the warning looks correct because `FirstOrDefault` can indeed return null.

Can you clarify more?

**Comment by gwake1** [comment]
![image](https://user-images.githubusercontent.com/9039253/181309836-d3da9d62-58a0-4900-9e67-482850faaa2d.png)

**Comment by gwake1** [comment]
Screenshot in Visual Studio reproduces the error. Was not able to reproduce in SharpLab.

[Link to Updated Code](https://gist.github.com/gwake1/c1338f32e800ca92beb39bbce4d3f0d2)

**Comment by gwake1** [comment]
Hi Youssef,

I have updated the code and included a screenshot from Visual Studio.

Thank you.

**Comment by Youssef1313** [comment]
@gwake1 The warning in the screenshot is correct. `FirstOrDefault` can return null, and the string parameter of `ClientResponse` constructor isn't annotated as nullable.

You're not able to reproduce in SharpLab because you're enabling nullable reference types in a portion of the code. If you moved `#nullable enable` to the very top, you should be able to reproduce.

**Comment by gwake1** [comment]
Nullable is enabled in the project.

![image](https://user-images.githubusercontent.com/9039253/181358437-64ce584b-2291-44b9-af60-fb0cd4824ec3.png)

**Comment by gwake1** [comment]
The highlighted message from earlier screenshot is not about FirstOrDefault.

**Comment by RikkiGibson** [comment]
> The highlighted message from earlier screenshot is not about FirstOrDefault.

The argument for parameter `value` in `ClientResponse(string value)` is the return value of `FirstOrDefault()`. `FirstOrDefault()` with a predicate is really for the case that you aren't sure whether any element in the collection will match the predicate. If the caller is supposed to pass a collection where some element *will* match the predicate, you could consider calling `First()` instead. Otherwise, you'll have to do a null check here and decide what the method should do if no element matched the predicate.
