### ISSUE TITLE
Generator types are sometimes being loaded twice

### ISSUE THREAD

**Issue by chsienki** [dotnet/roslyn#63189]
As seen here: https://github.com/dotnet/roslyn/pull/63062 we're hitting an issue where the generator driver is receiving multiple copies of the same generator. 

Looking at the binlog, the specific generator is only passed once, so it appears to be an issue with how we're instantiating the generators. It also seems to be somewhat non deterministic when this is happening.

**Comment by jaredpar** [comment]
Dug into this issue this morning after @JoeRobich, @RikkiGibson saw this hit again on the servicing branch. 

> Looking at the binlog, the specific generator is only passed once, so it appears to be an issue with how we're instantiating the generators.

This is not the case. It is definitely being passed more than once.

<img width="676" alt="image" src="https://user-images.githubusercontent.com/146967/187482820-262c6858-2aa2-424b-bdc8-6522ef0f6754.png">

At the time of this bug at least three of us confirmed we weren't passing the generator twice into the binlog. I think the reason why is because prior to #63236 the binlog had a lot more failures. The build essentially limited along after a bootstrap failure and we ended up with lots of failed compilations. After #63236 though we essentially fail fast on the build and are left with a minimum amount of failed compilations to dig through. It makes the picture a lot clearer. 

Now with the clearer picture it's easy to see this build is one with duplicate copies of the Json generator. 

<img width="371" alt="image" src="https://user-images.githubusercontent.com/146967/187483386-5e283360-50d6-4aac-a861-53f38ab5d5a4.png">

That means we're really just hitting the following bug in our build. 

https://github.com/dotnet/wpf/pull/6680

**Comment by RikkiGibson** [comment]
The external issue has been resolved.
