### ISSUE TITLE
 Intermediate Generator outputs

### ISSUE THREAD

**Issue by chsienki** [dotnet/roslyn#63291]
## Background and Motivation

Today, generators act like a 'black box. Inputs go in at one end, generated source files come out at the other end. As we continue to enable and support DSL-like experiences there becomes a desire to be able to 'see' into the workings of the generator. This is especially true for tooling scenarios (such as razor) that are using the generator infrastructure to handle compilation: the tooling
needs a way of getting extra information out of the generator beyond simply the generated files.

This proposal adds a new output type, known as an Intermediate Output, that consists of a simple key value pair, that allows generators to emit arbitrary data. This can then be accessed from the generator run result by any interested party. Much like source file hint names, the key must be unique within a generator, but will not collide across generators.

It is expected that this API would only take effect in IDE scenarios, and be a no-op on command line builds.

## Proposed API

```diff
namespace Microsoft.CodeAnalysis
{
    public readonly partial struct IncrementalGeneratorInitializationContext
    {
+       public void RegisterIntermediateOutput<TSource>(IncrementalValueProvider<TSource> source, Action<IntermediateOutputContext, TSource> action);
+
+       public void RegisterIntermediateOutput<TSource>(IncrementalValuesProvider<TSource> source, Action<IntermediateOutputContext, TSource> action);
    }

+   public readonly struct IntermediateOutputContext
+   {
+       public CancellationToken CancellationToken { get; }
+
+       public void AddOutput(string name, object value);
+   }

    public readonly struct GeneratorRunResult
    {
+       public ImmutableDictionary<string, object> Intermediates { get; }
    }
}
```

## Usage Examples

``` C#
public void Initialize(IncrementalGeneratorInitializationContext context)
{
    var provider = context.CompilationProvider.Select(/* .. */);

    // make outputs available to other consumers
    context.RegisterIntermediateOutput(provider, (context, value) =>
    {
        context.AddOutput("key", value);
    });

    // NOTE: can still do more with the provider
    var provider2 = provider.Select(/* .. */);

    // regular source output
    context.RegisterSourceOutput(provider2, (context, value) => /* .. */);
}
```

**Comment by CyrusNajmabadi** [comment]
> public ImmutableDictionary<string, object> Intermediates { get; }

Don't love the name 'Intermediates'.  How about 'IntermediateOutputs'.  We could also just call this `AddProperty` and then ahve `Properties`.

**Comment by jasonmalinowski** [comment]
A few small questions since I may not be able to attend the in-person meeting tomorrow:

1. Does it make sense to allow the key to be specified in the call to RegisterIntermediateOutput as opposed to specifying it in the context? For example:
    ```
    context.RegisterIntermediateOutput("key", provider, (context, value) =>
    {
        context.SetOutput(value);
    });
    ```
    If IDE components are going to need to request this, latency may matter in those cases. If there's multiple outputs _and_ we know which registration corresponds to which values, then we could run only the part that matters rather than having to run more.

2. Similarly to that point, does there need to be some option passed to the generator driver for controlling whether these should be ran or not? I could again imagine the IDE wanting to be able to incrementally run just one output rather than needing all of them, so I'm not sure what those options might look like.

My only last concern isn't something that's really fixable, but something that's potentially scary for the IDE: the ability to generally produce "objects" out of the system means this may force us to think more about how generators interact with our out-of-process model we have today. Right now, we synchronize the in-process Solution snapshot out of process, but we don't attempt to pass along generator outputs or synchronize those in any way; we assume that the generators will simply produce the same output in that case in both processes, and we just let them run twice. (If you're thinking "wait, that assumption seems like a bad idea!", well, yes, it is for many reasons.) This duplicate work is, well, duplicate, so an expensive generator means we're hurting performance in both processes at once.

One obvious fix is to only run the generators in one process, and if the other process needs the information, we marshal it across. When the generator's only output is text, that's easy. But if the generator is able to produce arbitrary object outputs, we can't assume it's marshallable anymore. So with this API we have to land in a place where one of these are true:

1. We have stopped needing generator outputs in one process entirely. Either we've gotten rid of our OOP process, or we've moved all analysis OOP and nothing needs it in-proc anymore. One of these is likely where Roslyn ends up, but we don't know which yet, or a timeline for that happening.
2. We still are running generators in both places, but we know only one process needs the intermediate outputs like this, so we just don't have to worry about either a duplicate cost or marshalling it.
3. We are still running it in both places, and we're OK with that. This might be no different than the current world, honestly, where the Razor IDE components are already duplicating some of this analysis _even in the same process_.

The first will happen one day, and it's possible the second or third is something that we already know to be true. But hopefully we can figure out which that is before building atop the architectural direction this API implies.

**Comment by CyrusNajmabadi** [comment]
> One obvious fix is to only run the generators in one process, and if the other process needs the information, we marshal it across. When the generator's only output is text, that's easy. But if the generator is able to produce arbitrary object outputs, we can't assume it's marshallable anymore. So with this API we have to land in a place where one of these are true:

Yes.  this is a very important concern.  It's also why things like Diagnostics contain no arbitrary objects as part of their public surface area.  We should def consider if this should just be `AddProperty(string, string)`.

**Comment by jasonmalinowski** [comment]
@CyrusNajmabadi I admit I'm not sure that's usable for things like Razor, since their enumeration of tag helpers or the like produces a lot richer information than what might be a fairly simple list of strings.

**Comment by CyrusNajmabadi** [comment]
> @CyrusNajmabadi I admit I'm not sure that's usable for things like Razor, since their enumeration of tag helpers or the like produces a lot richer information than what might be a fairly simple list of strings.

tehy coudl serialize it into a string.  i'm not sure why razor needs this tbh.  

The motivating scenario just says: As we continue to enable and support DSL-like experiences there becomes a desire to be able to 'see' into the workings of the generator. 

I'm not sure why we'd need rich objects for that.  Is this an API to get insights? Or an api to do funky side-channel passing along of objects.  If hte latter i'm *extremely* wary.

**Comment by 333fred** [comment]
### API Review

* The razor source generator don't just produce C#, it produces semantic info the editor needs to run
* Razor tooling wants not just razor source, but even the generated C# source. With the suppressed generator today, this isn't possible.
* We need to think about OOP in this API, since we may need to communicate between the generator running in a different process and the tooling running in the same process.
  * Would maybe need to serialize/deserialize in the same process, but we already say this is necessary for C# source
* Are these just a non-source artifact?
  * Intermediate might not be the right word in this case?
  * Maybe `AddNonSourceOutput`?
* Could a user just get a stage of the pipeline and see the output of that stage?
  * May be ok, but it might also not be that the intermediate step has the exact thing you want
  * Serialization concerns for this.
* Razor already needs serialization for tag helpers, so perhaps it doesn't matter that we start with just strings.
* We do want to think about some of these intermediate outputs not needing to be written to disk. These intermediate pieces of info don't need to be written to disk for razor, but might for generators that want to write config files.
* We could also look into allowing outputs to be `ROS<byte>` or similar, and users can serialize and rehydrate however they choose.

**Comment by chsienki** [comment]
Closing for now, as we solved it in Razor via IVT, and don't have anything else wanting to use this API.
