### ISSUE TITLE
VS 17.4 p1 Marking files as readonly

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#63340]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VS-174-p1-Marking-files-as-readonly/10116416)._

---
[severity:I'm unable to use this version] [regression] [worked-in:17.3 P4]
Hello,

Just updated to 17.4 p1 and it seems that VS is marking my files as readonly. When I attempt to do [CTRL + R, CTRL + R] (Rename macro) i get an error "You cannot rename this element because it is contained in a read-only file." After this, no changes to the file are allowed.

I have to close and reopen the file in order to continue editing it.

---
#### Feedback Bot on 8/10/2022, 08:21 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by danFbach** [comment]
Hello,

I'm the original reporter. 
This issue seems to have resolved itself. I was able to replicate it for the feedback recording, but I recently restarted my machine and all of my vs instances were closed and restarted, the bug no longer occurs.

**Comment by CyrusNajmabadi** [comment]
Thanks @danFbach .  I'm going to close this out.  Both because you aren't experiencing it again, and because it's pretty unlikely this for this to be Roslyn (though not impossible).  We rarely would be hte component marking anything 'read only'.  We do have some codepaths for that (for example, when we use Source-Generators to generate files), but it would be highly unlikely for that to be affecting other files. 

If you experience again, let us know!

**Comment by danFbach** [comment]
Hi @CyrusNajmabadi , I've had this happen again. I've used vs daily since i reported this and have not had it occur but, it just occurred again. There is a bug of _some kind_ but it appears to be rare and I don't know what is triggering it. 
I've been working on this project on and off throughout the day without issue. Then I just jumped into the already open project, used the [CTRL + R] + [CTRL + R] rename macro and I'm getting the same error. Closing and reopening the file allows me to continue editing, but using the rename macro again makes the file readonly again. If there's any way I can provide more information to help narrow down what is causing this, I would love to help.

**Comment by danFbach** [comment]
@CyrusNajmabadi 
For the sake of being thorough, I also tried renaming the variable using the right click dialog menu and from Edit => Refactor => Rename. 

Just like the keyboard shortcut, the first attempt does _nothing_, from my perspective at least.
The second time clicking rename, I am given the error message that the file is read only.

yes, i didn't supply that detail before... The first keyboard shortcut attempt does _nothing_, the second throws the error.
