### ISSUE TITLE
Expose service to determine what change are allowed, without going back to a Workspace

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#63457]
## Background and Motivation

Roslyn-IDE would like very much to remove the capability for features to go from a Solution back to a Workspace.  This is because a workpace is a mutable concept that we have to hope people are on their best honor to not muck around with when we're calling out to them to perform purely functional operations.  We intend to ban this outright for our own code, and ideally gently deprecate/remove this capability in teh future.

One API that the workspace currently has that some features need is the `CanApplyChange(ApplyChangeKind)` api: https://github.com/dotnet/roslyn/blob/3ebf3e529e5ed18e5307934b23dfc060f8f21c67/src/Workspaces/Core/Portable/Workspace/Workspace.cs#L1151

This allows features (like codeactions) to determine what sort of workspace mutations are allowed.  For example, if they can add documents (as opposed to just mutating a document).

Being able to query for this information is desirable, but we would like to avoid going through the WOrkspace itself for this. To taht end we propose:

## Proposed API

```diff
namespace Microsoft.CodeAnalysis
{
    public interface ISupportedChangesService : IWorkspaceService
    {
+        /// <inheritdoc cref="Workspace.CanApplyChange"/>
+        bool CanApplyChange(ApplyChangesKind kind);

+        /// <inheritdoc cref="Workspace.CanApplyParseOptionChange"/>
+        bool CanApplyParseOptionChange(ParseOptions oldOptions, ParseOptions newOptions, Project project);

+        /// <inheritdoc cref="Workspace.CanApplyCompilationOptionChange"/>
+        bool CanApplyCompilationOptionChange(CompilationOptions oldOptions, CompilationOptions newOptions, Project project);
    }

    public class Workspace
    {
-        protected virtual bool CanApplyCompilationOptionChange(CompilationOptions oldOptions, CompilationOptions newOptions, Project project)
+        public virtual bool CanApplyCompilationOptionChange(CompilationOptions oldOptions, CompilationOptions newOptions, Project project)
    }
}
```

**Comment by 333fred** [comment]
### API Review

- Continued work in discouraging Solution->Workspace directionality
- Do we need the other `CanApplyX` methods?
  - CanApplyParseOptionChange - Used for changing language version
  - CanApplyCompilationOptionChange - Protected today? Maybe we don't need this one?
- CodeFixes and refactorings can access all of VS and import MEF services. Are we going to want to have an analyzer to prevent this at some point in the future?
  - Could start with a warning in the code fix provider
- Should this be a service that can be queried, instead of a method on the context?
  - We forsee that we could add this in other locations. A service probably makes more sense.

**Conclusion**: Generally approved in the service form. We need a followup email chain to name the service, and see what `CanApplyCompilationOptionChange` is used for and whether it should be included.
