### ISSUE TITLE
IDE0220 on foreach (Match m in regex.Matches) – Should Not Occur

### ISSUE THREAD

**Issue by SetTrend** [dotnet/roslyn#63470]
Using the following code snippet results in Roslyn analyzer adding an informational warning to the list of analysis results:

```c#
foreach (Match m in regex.Matches(text))
{
  ...
}
```

```
IDE0220  'foreach' statement implicitly converts 'object' into 'System.Text.RegularExpressions.Match'. Add an explicit cast to indicate your intention as it may fail at runtime.
```

[`MatchCollection.Item[]`](https://docs.microsoft.com/dotnet/api/system.text.regularexpressions.matchcollection.item), however, doesn't return `object`. It returns a [`Match`](https://docs.microsoft.com/dotnet/api/system.text.regularexpressions.match).

## Version Used 

.NET 6

## Steps to Reproduce

1. Create a [regular expression](https://docs.microsoft.com/dotnet/api/system.text.regularexpressions.regex) object.
2. Run the [`Regex.Matches()`](https://docs.microsoft.com/dotnet/api/system.text.regularexpressions.regex.matches) method on that regular expression and feed immediately to a [`Match`](https://docs.microsoft.com/dotnet/api/system.text.regularexpressions.match) variable in a `foreach` loop.

## Expected Behavior

This should be analyzed by the Roslyn analyzer without flaw.

## Actual Behavior

The Roslyn analyzer adds an information to the analysis result (roughly translated by me from German to English):

```
IDE0220  'foreach' statement implicitly converts 'object' into 'System.Text.RegularExpressions.Match'. Add an explicit cast to indicate your intention as it may fail at runtime.
```

**Comment by CyrusNajmabadi** [comment]
What version of .net are you compiling against. It's likely your MatchCollection only implements IEnumerable, not `IEnumerable<T>`.

**Comment by twest820** [comment]
Hi Cyrus, I just hit this in a .NET 6.0 project after updating to VS 17.3.0. In .NET 6.0 it's

    public class MatchCollection : IList<Match>, IReadOnlyList<Match>, IList

so this might be a regression in 17.3.0 that's raising IDE0220 incorrectly because of something like 1) neither `IList<Match>` or `IReadOnlyList<Match>` are getting seen as `IEnumerable<Match>` or 2) the rule's grabbing onto `IList` and missing both `IList<Match>` and `IReadOnlyList<Match>` .

So now I have

    [assembly: SuppressMessage("Style", "IDE0220:Add explicit cast", Justification = "https://github.com/dotnet/roslyn/issues/63470", Scope = "member", Target = "~M:<method(args)>)")]

in GlobalSuppressions.cs as a workaround.

**Comment by Youssef1313** [comment]
@CyrusNajmabadi This will happen regardless of whether `MatchCollection` implements `IEnumerable<T>` or not. See [this SharpLab](https://sharplab.io/#v2:EYLgtghglgdgNAFxAJwK4wD4AEBMBGAWACgsAGAAizwDoBhAewBtGBTAYwSnpgGcBuYmUp4ALAJIUq1ACosAHgmoAlFgHNUjCMgCicgA7IWPHl17jiANy3k25ALzkYLAO7laACgCU4gGb1DEGwAFuTuALIQCMHkcuSwNp7EAN7EAL7EggDMlDhu5CDCmQA8EVFBAHzJxOQ1lNkAktowqGAsyJH+5ADiLAhNLW0dyF725Y4u5P2t7Qj+XnzkAPSLNvRgelCsyOQbbADWPOQIQVCHftvHLOTnLIEhjPT0etQZRLXkjc3TQyWRwWNUYqlf7UHp9L6DWbDTyjRwaRgLZardabNrkAAm9CMMAA5AhyKgeFdjqcXkRqrUDFArAgrrhJhCZp0Cp8BkzkBSaik3u9alhsvRgAArdj42ioZCGGD4uxjABEAGUEMhYKo5eYeby6uRgI9GOQwvQLCwAHLyBBeTm87larVYADsRzQLHEtvI6XJmt5/MoInIKiJFsSXveNttHveHtSQA=)

**Comment by RikkiGibson** [comment]
PR #60210, which added this analyzer, includes these  notes:

> 3\. for legacy APIs it's acceptable for ergonomic reasons to leave the cast off.  A legacy API is one that doesn't implement `IEnumerable<T>` and returns `object` values.

It sounds like maybe `MatchCollection` adopted `IEnumerable<T>` while keeping its `GetEnumerator()` with `object Current { get; }` for binary compat reasons. Maybe what we want to do (what @Youssef1313 is maybe already doing) is relax the analysis so that when some object `source` implements `IEnumerable<T>`, and its enumerator has `object Current { get; }`, then we permit `foreach (T t in source)`.

**Comment by twest820** [comment]
That looks like #60120 rather than #60210. [MatchCollection](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/MatchCollection.cs) defines

        public IEnumerator GetEnumerator() => new Enumerator(this);

        IEnumerator<Match> IEnumerable<Match>.GetEnumerator() => new Enumerator(this);

with Enumerator having

            public Match Current { get { ... } }

            object IEnumerator.Current => Current;

Naively, I'd expect both `foreach` and the rule to find the strongly typed path but perhaps that's not what happens.

**Comment by m-gallesio** [comment]
This still applies to .NET 7.0.

**Comment by janusqa** [comment]
This still happens in .NET 8.0.
