### ISSUE TITLE
Incorrect CS8166 when calling [UnscopedRef] method to assing to a scoped local

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/roslyn#63524]
**Version Used**:  4.4.0-2.22419.1 (ae566380)

**Steps to Reproduce**:

1. Paste the following code:
```csharp
ref struct A
{
    [UnscopedRef]
    public Span<byte> GetSpan() => default;
}

class Foo
{
    void Bar(ref A a)
    {
        scoped Span<byte> span1 = a.GetSpan();
    }
}
```

**Expected Behavior**:

The code should compile fine, as `GetSpan()` is escaping the `ref`, but the result is also `scoped`.

**Actual Behavior**:

The build fails with:

> "CS8166: cannot return a parameter by reference 'a' because it is not a ref parameter"

![](https://user-images.githubusercontent.com/10199417/186025868-df1545c6-e69f-4819-b1ca-2c40a4335810.png)

cc. @cston

**Comment by Sergio0694** [comment]
This might potentially be the same as #63529 (as in, that being a duplicate of this one), given the trimmed down repro for that one is effectively the same as this one, except the build error is when just calling the method, before even assigning it to a local at all. Which seems to be the case here too, at least looking at where the red squiggly lines are 🤔

**Comment by Sergio0694** [comment]
@jaredpar Should this be in the 17.4 milestone too, given it's preventing legitimate uses of `[UnscopedRef]`?
We're also hitting this in the Store (I have a branch where I'm dogfooding C# 11 bits, which is how I discovered this) 😄

**Comment by jaredpar** [comment]
Yes it should be. Just missed it when I was assigning out labels.

**Comment by jaredpar** [comment]
This behavior is "By Design". 

This is unintuitive but easier to understand if you rewrite the repro a bit. Consider that the above sample is roughly the following:

```csharp
static void GetSpan([UnscopedRef]ref A p);
```

Essentially a method which takes a unscoped `ref` to a `ref struct`. This is fully unscoped here so the compiler has to assume the following case is in play: 

```csharp
static void GetSpan([UnscopedRef]ref A p)
{
  p.refField = ref p.someOtherField;
}
```

Essentially that `Getspan` does an evil cyclic self ref assign. As such the compiler correctly identifies the following call as an error:

```csharp
void M(ref A a) 
{
  GetSpan(ref a);
}
```

In this case the `ref` is implicitly `scoped` yet the compiler has to assume that it's self ref assigned via `GetSpan` and correctly flags it as an error. 

When you mix a mutable `struct` and `[UnscopedRef]` you end up in a situation where you need to be `[UnscopedRef]` all the way down, or using locals. If you're not you end up in these situations. 

Note: `readonly struct` does not have this problem because the compiler knows the self assign can't happen
