### ISSUE TITLE
string keyword is added by IntelliSense in error when specifying HtmlAttributes for LabelFor HTML Helper

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#63558]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/string-keyword-is-added-by-IntelliSense-/10110911)._

---
Whenever I add a `LabelFor` HTML Helper to a Razor view and hit the comma after the first parameter and then begin typing to add the htmlAttributes parameter, after I type the `new` keyword and then the opening brace, IntelliSense - every single time - inserts the `string` keyword before the curly brace. This is never the correct behaviour - htmlAttributes will always be an object.

The problem is best illustrated by the little screen capture I've attached, but the result is that, thanks to IntelliSense, I end up with the following, in which I never typed `string`:
`@Html.LabelFor(model => model.FirstName, new string { })`

This hasn't always been a problem. I feel like it's a bug that was introduced a few versions ago, but I can't say for sure when.

---
#### Feedback Bot on 8/4/2022, 00:10 PM: 

(private comment, text removed)
#### Feedback Bot on 8/4/2022, 04:07 PM: 

(private comment, text removed)
#### Andrew Hall 🤘 [MSFT] on 8/20/2022, 06:08 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by davidwengier** [comment]
User report says its a Razor file, but its with the legacy editor, which means C# projection buffers, which means Roslyn. Repros in a normal .cs file too. Essentially the user wants to use an object initializer, but completion has preselected `string` after they typed `new`, and completing with `{` inserts `string`.

![CompletionPreselection](https://user-images.githubusercontent.com/754264/186327931-c6829f9d-ab42-41f4-85cd-f1fdfab7a74b.gif)

**Comment by DoctorKrolic** [comment]
@davidwengier Sorry for offtop, but what program did you use to create such gif with keybord pressed keys shown?

**Comment by davidwengier** [comment]
I use ScreenToGif (https://www.screentogif.com/).

Since it's not obvious in the program how to add keystrokes, you can either:
* add them manually after the fact by clicking the "Key Strokes" button on the "Image" toolbar
* create an "Automated Task" in the Options screen, and add the "Key Strokes" task so that they're automatically added to every recording.

**Comment by philipstratford** [comment]
> User report says its a Razor file, but its with the legacy editor
I was the person that raised this originally on the Developer Community. I'm just curious - when you say this is the legacy editor, is that inevitable because I'm targeting .NET Framework? When our organisation (finally!) moves to .NET 6 will I automatically be using the non-legacy editor, or is that a change I need to make manually?

**Comment by genlu** [comment]
It looks like the completion might be a bit too confident in making a default (hard) selection based on the inferred types? If so, one potential solution is to use soft-selection instead of hard-select if user hasn't typed anything in this context (i.e. object creation)

**Comment by CyrusNajmabadi** [comment]
This is razor, so closing out.
