### ISSUE TITLE
Build fails for transitive nuget references, introduced in 17.3

### ISSUE THREAD

**Issue by jakubcermak** [dotnet/roslyn#63596]
# Issue description
If a .Net Fw project A has reference to a netstandard2.0 project B that references a nuget that is used in project B but not project A however project A uses classes from project B it fails to build.
It works on version 17.2, this behavior was introduced in 17.3.0.

# Example
[BuildBugMinimalExample.zip](https://github.com/dotnet/msbuild/files/9423017/BuildBugMinimalExample.zip)
This sln contains 4 projects:
**ClassLibrary1** - this servers as a "base" library, it references Microsoft.Extensions.Diagnostics.HealthChecks nuget and declares interface ICustomHealthCheck which extends IHealthCheck from the mentioned nuget. It is netstandard2.0

**ClassLibrary2** - this uses the ICustomHealthCheck interface in a class. In previous versions this compiles OK, now it fails with an error:
The type 'IHealthCheck' is defined in an assembly that is not referenced. You must add a reference to assembly 'Microsoft.Extensions.Dia
gnostics.HealthChecks.Abstractions, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
It's worth mentioning that the problem is in 
```
 public List<ICustomHealthCheck> xx { get; set; }
```
If I change it to
```
 public ICustomHealthCheck xx { get; set; }
```
it compiles OK even in 17.3 version.
It uses .NET Fw 4.7.2

**NetFwWithPackageReference** - this is the same code as in previous project, however it doesn't use packages.config for referencing nugets, it uses <PackageReference> in csproj. This suprisingly compiles OK.

**NetStdWorkingExample** - same code however with netstandard2.0. This also compiles OK.

# Actual behavior
The ClassLibrary2 project fails to build with error The type 'IHealthCheck' is defined in an assembly that is not referenced. You must add a reference to assembly 'Microsoft.Extensions.Dia
gnostics.HealthChecks.Abstractions, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'

# Expected behavior
It builds ok  same as in msbuild 17.2

**Comment by svick** [comment]
This sounds quite similar to https://github.com/dotnet/sdk/issues/27342.

**Comment by jaredpar** [comment]
This behavior is "By Design". 

In this case the compiler is not receiving all of the references required for compilation to succeed. Essentially the transitive set of references are not available. 

It is possible that one version of the compiler will succeed with the incomplete set and the next version will fail. This is not considered a bug though (the bug is passing incomplete reference sets). The compiler makes a best effort attempt to not regress the set of required references between versions. However sticking firmly to this would prevent many bug fixes and features in the compiler, hence between versions we may require missing references we previously did not.
