### ISSUE TITLE
Convert to file-scoped namespace when typing semi-colon fails in the presence of specific trivia

### ISSUE THREAD

**Issue by davidwengier** [dotnet/roslyn#63792]
_Originally posted by @uzinable in https://github.com/dotnet/roslyn/issues/57564#issuecomment-1236084479_

if open brace have comment, and there is commented class inside the namespace, it doesn't allow automatic inline namespace to be done :

Before 
![image](https://user-images.githubusercontent.com/34981862/188264692-ad886711-13ae-4ac7-a6e9-43d7bfddc511.png)
After:
![image](https://user-images.githubusercontent.com/34981862/188264708-64ba2059-0e1c-493a-9b3d-e874963d4693.png)

but if we remove the comments for the class, it does :

Before
![image](https://user-images.githubusercontent.com/34981862/188264737-2feccd7a-d425-4221-813c-e0b67f173712.png)
After
![image](https://user-images.githubusercontent.com/34981862/188264742-0b9a1717-c46c-44f3-badf-dd28597eecfc.png)

**Comment by DoctorKrolic** [comment]
Duplicate of https://github.com/dotnet/roslyn/issues/63542

**Comment by uzinable** [comment]
Hello,

There is still a case where the parser is lost, when there an unusual comment and either commented code or nothing.

```
namespace Test
{ // unusual comment

    //internal class Class1
    //{
    //}
}
```
```
namespace Test
{ // unusual comment

}
```
This two don't transform to single line namespace on magic ";". I promess i won't test anymore, as i'm happy with the last update and don't do those comment  anymore since very long time, just to let you know :)
