### ISSUE TITLE
[Regression] "Rename symbol's file" option gets forgotten

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#63810]
**Version Used**: 
Version 17.4.0 Preview 3.0 [32904.27.main]

**Steps to Reproduce**:

1. Press F2 on a class and enter new name
2. Check "Rename symbol's file"
3. Click Apply
4. Press F2 on a class _member_ and dismiss it
5. Press F2 on a class again 

**Expected Behavior**:
For "Rename symbol's file" to be checked
![image](https://user-images.githubusercontent.com/1103906/188523968-b908a79d-bcc3-4d9b-b5a6-4028f19fe155.png)

**Actual Behavior**:
Its unchecked
![image](https://user-images.githubusercontent.com/1103906/188523952-a10b3e1a-44f1-4073-b579-6b7b930e20c3.png)

This is a regression from a prior release, I've never had to think about checking this option before.

**Comment by philiphenriksen** [comment]
I've had this issue since 17.2.3, I think, and I know it affects my whole team.

We've had multiple cases were changes to class names are pushed to Git, but the file name is unchanged because of this issue.\
This checkbox was usually either on by default, or manually switched once and then remembered in previous releases.
