### ISSUE TITLE
Code that compiles on dotnet 6 gives compile errors on dotnet 7 preview

### ISSUE THREAD

**Issue by danwalmsley** [dotnet/roslyn#64000]
It seems dotnet 7 preview may have broken language specification? 

https://github.com/AvaloniaUI/Avalonia/blob/master/src/Markup/Avalonia.Markup/Markup/Parsers/BindingExpressionGrammar.cs#L302

This line compiles fine targetting net6.0, but targetting net7.0 it gives the following compile error...

```
C:\Users\danwa\source\repos\Avalonia\src\Markup\Avalonia.Markup\Markup\Parsers\BindingExpressionGrammar.cs(302,79): err
or CS8168: Cannot return local 'reader' by reference because it is not a ref local 
```

**Comment by Sergio0694** [comment]
In this bit ([here](https://github.com/AvaloniaUI/Avalonia/blob/6a3804bfde7867ab0c419a71d504636f1e196b4b/src/Markup/Avalonia.Markup/Markup/Parsers/BindingExpressionGrammar.cs#L321)) (simplified code below):
```csharp
private static TypeName ParseTypeName(ref CharacterReader r)
{
    // Code...
}
```

You're taking a `ref` to `CharacterReader` (which has RSTE return-only) and returning `TypeName`, which is a `ref struct`. The compiler has to assume that `ref r` could escape through `TypeName`, but that's not actually what the code is doing as far as I can tell - it's just using the reader to parse spans and then returning that. If you change that `r` parameter definition to `scoped ref CharacterReader r`, the logic in the method will be the same and the method should compile fine 🙂

That said, it's also possible you've hit one of the local declaration scoping inference bugs (eg. see #64394), because even with that parameter not being `scoped`, the compiler should just implicitly mark the returned value as `scoped`, which would then also be safe. Either way, adding `scoped` when possible is still a good idea anyway to make the code clearer.

**Comment by cston** [comment]
The compiler is incorrectly evaluating ref safety in deconstruction. 

A simple repro from https://github.com/dotnet/roslyn/issues/64448:
```csharp
ref struct R
{
    public R(ref int i) { }
    public void Deconstruct(out int x, out int y) => throw null;
}

class Program
{
    static void Main()
    {
        int i = 0;
        var r = new R(ref i);
        int x, y;
        (x, y) = r; // error CS8352: 'r' ... may expose referenced variables
    }
}
```
