### ISSUE TITLE
Add a lightbulb option for remove and sort usings

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#64089]
In addition to having the `remove and sort usings` in the toolbar menu we should add an option in the lightbulb since we also have an option to `remove unnecessary usings` there too.

**Comment by kimsey0** [comment]
I'll have a go at this.

**Comment by kimsey0** [comment]
A few questions discovered during my work implementing this so far:
1. Should this be a new code fix for the existing `RemoveUnnecessaryImportsFixable` diagnostic, which would thus show up whenever there's unnecessary usings, or should it be a new type of diagnostic that's triggered only when there's unnecessary usings _and_ usings that are in the wrong order?

I've implemented the former, while the latter seems to require more work, since `RemoveUnnecessaryImportsFixable` is a special kind of _trigger diagnostic_ I don't know about, and determining if usings are in order from an analyzer seems to require sorting them with the user's `PlaceSystemNamespaceFirst` and `SeparateImportDirectiveGroups` options.

2. If this is implemented as another code fix for the existing `RemoveUnnecessaryImportsFixable`, should it be above or below the existing _Remove Unnecessary Usings_ in the lightbulb? I assume below.
3. What should be the label of this new option in the lightbulb? It could be _Remove and Sort Usings_ like in the toolbar menu, but that differs a little bit from the existing _Remove Unnecessary Usings_ label.

**Comment by CyrusNajmabadi** [comment]
> or should it be a new type of diagnostic that's triggered only when there's unnecessary usings and usings that are in the wrong order

It should be this.

> should it be above or below the existing Remove Unnecessary Usings in the lightbulb? I assume below.

Correct, it should be below.

> It could be Remove and Sort Usings

Let's go with this for now.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of movement.
