### ISSUE TITLE
Invalid hyperlink in JavaScript diagnostics

### ISSUE THREAD

**Issue by MariaSolOs** [dotnet/roslyn#64145]
**Version Used**: 4.4.0-2.22405.13

**Steps to Reproduce**:
1. Create a new JavaScript file in Visual Studio.
2. Write the following code inside: `var # = 0;`
3. Open the error list and click on the `TS1127` hyperlink.

**Expected Behavior**: The browser opens [this 404 page](https://learn.microsoft.com/en-us/visualstudio/ide/not-in-toc/default?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(keywords_removed)%26rd%3Dtrue&view=vs-2022). 

**Actual Behavior**: Since the diagnostic doesn't include a valid documentation URL, the error code shouldn't be a hyperlink.

This happens with all JavaScript and TypeScript errors, as well as with some C# errors (like CS8199).

**Comment by MariaSolOs** [comment]
FYI @mavasani

**Comment by Youssef1313** [comment]
> as well as with some C# errors (like CS8199).

For C#, these are not-yet-documented errors. Links should work normally after they're documented.

**Comment by mavasani** [comment]
I investigated this a bit and see that the behavior is controlled by the platform side. It queries for a help link, and if available and non-null it navigates to it. Otherwise, it queries for help keyword for F1 help and if available and non-null it navigates to the URL for F1 help, which seems to be the case for TS diagnostics.

This is Roslyn's implementation for the queries for help link and help keyword: https://github.com/dotnet/roslyn/blob/0f83d53179cd936842c743ad5dd48bc41cbbfb80/src/VisualStudio/Core/Def/TableDataSource/VisualStudioBaseDiagnosticListTable.LiveTableDataSource.cs#L369-L374

We return the diagnostic ID as the help keyword, so basically error list is invoking the global VS Help service with TS diagnostic ID and navigating to it. I checked the history and see that both Roslyn and Error list implementation have been in place for many years, so this is not a recent regression from either of these.

If you want to fix this behavior and prevent F1 help from kicking in from TS diagnostics, we can make a change in Roslyn's implementation. For example, you can add a special custom tag, say _"DoesNotSupportF1Help"_ or some such well-known name, to your diagnostics. Roslyn's implementation I pointed to above will return the diagnostic ID for F1 help keyword only if the above custom tag is not present on the diagnostic. We likely want to expose this special custom tag string via TS ExternalAccess layer to avoid any breaks in case the Roslyn code is changed/refactored.

**Comment by MariaSolOs** [comment]
That sounds like a good plan @mavasani!
