### ISSUE TITLE
Confusing error message mentioning `WindowsRuntime` when trying to await an `IAsyncEnumerable`

### ISSUE THREAD

**Issue by anthony-c-martin** [dotnet/roslyn#64170]
**Version Used**: .NET 6

**Steps to Reproduce**:

1. Clone https://github.com/Azure/bicep (can also use Codespaces to quickly get an environment).
2. Try and create a new file at `src/Bicep.Core/Test.cs` with following contents:
    ```csharp
    using System;
    using System.Threading.Tasks;
    using System.Collections.Generic;

    namespace Bicep.Core
    {
        public class Test
        {
            public async Task Blah(IAsyncEnumerable<string> input)
            {
                await input;
            }
        }
    }
    ```
3. This totally perplexing error occurs (note - this is a x-platform project, building on Ubuntu):
    <img width="1042" alt="image" src="https://user-images.githubusercontent.com/38542602/191394780-6a5e637b-f799-4a60-aa3e-5c09735dbe65.png">
4. Same error occurs with `dotnet build`:
    ```
    /workspaces/bicep/src/Bicep.Core/Test.cs(13,13): error CS0012: The type 'IAsyncAction' is defined in an assembly that is not referenced. You must add a reference to assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime'. [/workspaces/bicep/src/Bicep.Core/Bicep.Core.csproj]
    /workspaces/bicep/src/Bicep.Core/Test.cs(13,13): error CS0012: The type 'IAsyncActionWithProgress<>' is defined in an assembly that is not referenced. You must add a reference to assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime'. [/workspaces/bicep/src/Bicep.Core/Bicep.Core.csproj]
    /workspaces/bicep/src/Bicep.Core/Test.cs(13,13): error CS0012: The type 'IAsyncOperation<>' is defined in an assembly that is not referenced. You must add a reference to assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime'. [/workspaces/bicep/src/Bicep.Core/Bicep.Core.csproj]
    /workspaces/bicep/src/Bicep.Core/Test.cs(13,13): error CS0012: The type 'IAsyncOperationWithProgress<,>' is defined in an assembly that is not referenced. You must add a reference to assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime'. [/workspaces/bicep/src/Bicep.Core/Bicep.Core.csproj]
    ```

**Expected Behavior**: A clear message is displayed explaining that this type cannot be awaited.

**Actual Behavior**: See repro. Note that I wasn't able to repro this on https://sharplab.io/.

**Comment by jaredpar** [comment]
The reason why this is occurring is because the set of references passed to the Bicep.Core project is incomplete. At least one of the references provided has a reference to `Windows` at version 255.255.255.255 (generally a WinRT ref). That means the transitive reference graph is incomplete. 

During the processing of `await input` the compiler is looking for possible `GetAwaiter` calls on `IAsyncEnumerable<T>`. That includes extension methods. One of the extension methods defined has a parameter of type `IAsyncAction` but the type isn't available due to the missing reference and thus it leads to a compilation error. 

The assembly causing the issue in this case is `System.Windows.Runtime.dll`. There isn't much you can do to prevent this in the current configuration because the extension methods are defined in the `System` namespace so the compiler is going to look there. The only fix is to add the missing references or remove this one.

**Comment by anthony-c-martin** [comment]
Thanks for the explanation!
