### ISSUE TITLE
IntelliSense doesn't work for interface statics when dotting a type parameter

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#64182]
This is a bad code I introduced in https://github.com/dotnet/roslyn/pull/53942 :)

`abstractsOnly` local should be removed altogether and the take the "false" code path for any condition relies on it.

Repro from @Sergio0694:

![image](https://user-images.githubusercontent.com/31348972/191501823-9192641e-ce08-4505-99b3-257f795e24ba.png)

**Comment by arkalyanms** [comment]
Tagging both Cyrus and Youssef as they have the most context.

**Comment by Sergio0694** [comment]
Kinda unfortunate this didn't make it to 17.4, as this greatly hurts discoverability of all the new generic math APIs 🥲

**Comment by CyrusNajmabadi** [comment]
That's fine. That's why we continue to have new versions. 

What surprises me is that no tests caught this. Looks like something maybe missed in the static abstracts test pass? @jcouv @333fred ?

**Comment by Sergio0694** [comment]
> "That's fine. That's why we continue to have new versions."

Of course, agreed it's not a big deal in the grand scheme of things. Was just thinking that with VS 17.4 being the version that will ship with .NET 7, and with generic math now finally being released out of preview and people trying it out, it might make adoption a bit less smooth especially for people not familiar with this, given generic math as a whole (or really, static abstracts in general) are a completely new feature that many devs haven't even ever heard of before. So I expect a few folks might see the blog posts, try things out, and then be confused when none of the APIs they see mentioned will show up for them in IntelliSense, is all 😅

But of course, nothing that can't be fixed in vNext indeed 😄

**Comment by jcouv** [comment]
> Looks like something maybe missed in the static abstracts test pass?

Looking at the test plan (https://github.com/dotnet/roslyn/issues/60968), I see that there's already an issue for this scenario: https://github.com/dotnet/roslyn/issues/61255

**Comment by CyrusNajmabadi** [comment]
Is this feature still in preview?  Or has it been released?  If the latter, I'm surprised as intellisense is part of our minbar for new lang features.

**Comment by jcouv** [comment]
C#11 (ie. VS 17.5 and .NET 7) have not been released yet. They ship in November though, so I agree this should be prioritized.

**Comment by jcouv** [comment]
Including @AlekseyTs, who probably has more context on this issue and any discussions with IDE buddy.

**Comment by AlekseyTs** [comment]
The issue #61255 is opened in May, has all the right labels, was triaged by IDE team, in all that time it was assigned to no one.

**Comment by Youssef1313** [comment]
I'll take a look and open a PR.
