### ISSUE TITLE
Change of Compilation/SyntaxNode Action emitting order

### ISSUE THREAD

**Issue by uppi** [dotnet/roslyn#6418]
Using Roslyn version from [releases/VS2015](https://github.com/dotnet/roslyn/tree/releases/VS2015) branch, the following code

```csharp
context.RegisterSyntaxNodeAction(ctx => Console.WriteLine("PropertyDeclaration Action", ctx.Node), 
                                 SyntaxKind.PropertyDeclaration);
context.RegisterCompilationAction(ctx => Console.WriteLine("Compilation Action"));
```

gives me the following output:

```
PropertyDeclaration Action
PropertyDeclaration Action
PropertyDeclaration Action
Compilation Action
```

But if I use the version from master branch on the same input, I get the follwing output:

```
Compilation Action
PropertyDeclaration Action
PropertyDeclaration Action
PropertyDeclaration Action
```

Is that change of order intended, and if it is, is there a way to subscribe to something that is emitted after all syntax node events are handled?

**Comment by tmeschter** [comment]
@uppi Only the compilation start action, compilation end action, code block start action, code block end action, and syntax node actions registered within a code block start action have any ordering guarantees. Otherwise, the actions may be called in any order.

Please see https://github.com/dotnet/roslyn/blob/master/docs/analyzers/Analyzer%20Actions%20Semantics.md for the actual spec, in particular the "Ordering of actions" section.

To answer your specific question, only the compilation end action is guaranteed to be called after all of the syntax node actions.

**Comment by uppi** [comment]
@tmeschter Thank you so much, I was confused by previous API change which just moved *EndActions to the StartContext instead of renaming.
