### ISSUE TITLE
Switch pattern matching with throwing default returns object with wrong boxed datatype

### ISSUE THREAD

**Issue by jesperasv** [dotnet/roslyn#64196]
**Version Used**: Any

**Steps to Reproduce**: [sharplab](https://sharplab.io/#v2:CYLg1APgAgTAjAWAFDIARQMzpuuB2ZAbzVVM1wDZ0AWVAWQEMBLAOwAoo4AGAbQF1UDAE4BzAM4BKEqWJJS8+QDdhqIQFMxAVwA2AFwAyAexYjUAXlQBxNbrYBBAKItNAWwB0RkxIDc0hamUhVQ0dXQBJFl1zKxt7J1c3CN0fPwVA4K09ABE1AGNo61tHZ3cc3JSUOX8yOABONgASACJCdUyDYxEAX1RWkL1PETdCgBUATwAHNTYJLqaK6pr65r72sp7V0LLhm3GpmbmFxc5llrbQpI3zvSSd3T3p2fnfKtIu5D8JoSZlXTVKVCGABGACs8lFCnESqhdJM1FJXr1UvIoHgYXDUGIAO5MXS5AAWyJkRP8xQSg3MAD5UHB9AAaEkKMnuJJU1AwBmIxaoZluMpsjB0TnchQAfTZunxQkMWNQLDUsrsolcakiAHlNLo1QAzABKDBMagcAA9cmoJromMY2CwGC41IZtWxYVMJAjuV0Xgp3pUFORVa4efEXH5ZNyksLFoNI9Uyn4fV0gA=)

**Expected Behavior**: That the object returned from the method have a boxed type that is the same type that was returned in the switch case.

**Actual Behavior**: The objects boxed type is not the same type that is returned. And in the example above is always System.Decimal.

Workarounds is not throwing the exception on default. Or using a regular switch statement. Or if an other datatype than a number is returned from the switch, example System.String gives the correct types.

**Comment by TahirAhmadov** [comment]
I'm positive this is working as expected. The return type of the entire `switch` expression is determined first by looking at its individual cases; in the provided example, the most common type is `decimal` - obviously, both `int` and `long` convert to it, but not the other way around. Then, the `decimal` returning switch expression is boxed, which is why it's always `decimal`.

**Comment by jesperasv** [comment]
Yes. But it's a big gotcha that a switch expression returns a datatype that wasn't the type of the returning case, even more so considering a normal switch statement doing logically the exact same thing returns the object with the type from the case. [sharplab, expression vs normal switch](https://sharplab.io/#gist:91df348b12899990439286d462a6a4e2)

**Comment by svick** [comment]
@jesperasv 

> it's a big gotcha that a switch expression returns a datatype that wasn't the type of the returning case, even more so when considering a normal switch statement doing logically the exact same thing returns the object with the type from the case

Maybe, but I don't think that can be fixed, since it would be a significant breaking change.

@TahirAhmadov 

> I'm not sure if IDE does that today, but perhaps the suggestion to use a `switch` expression instead of a `switch` statement should check the return type and not suggest when the behavior can change like this.

VS does the right thing today:

![](https://user-images.githubusercontent.com/287848/191748101-742a765d-3afb-491e-8855-2dea9527eedb.png)

Notice how how it adds a cast to `object` to one of the cases, which ensures that the behavior does not change.

**Comment by jesperasv** [comment]
I tried it out in VS. And you're correct it does refactor to a version of a switch expression that gives the correct result.

I still think it's a bug since you can write it as an switch expression from the beginning. But since someone already had this in mind when they wrote the refactor help signals to me that this could have already have been fixed but it can't/won't be fixed.

Thanks for the help.
