### ISSUE TITLE
Missing ref safety error inside `foreach`

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#64218]
```
class Program
{
    static void Main()
    {
        int i0 = 0;
        S s0 = new S(ref i0);
        {
            int i1 = 1;
            for (S s1 = new S(ref i1);;) {
                s0 = s1; // 1
                break;
            }
        }
        {
            int i1 = 1;
            foreach (S s2 in Enumerable1.Create(ref i1)) {
                s0 = s2; 
                break;
            }
        }
    }
}
ref struct S
{
    public S(ref int i) { }
}

class Enumerable1
{
    public static Enumerable1 Create(ref int p) => default;
    public Enumerator1 GetEnumerator() => default;
}

class Enumerator1
{
    public S Current => throw null;
    public bool MoveNext() => false;
}
```

Observed:
```
error CS8352: Cannot use variable 's1' in this context because it may expose referenced variables outside of their declaration scope
                s0 = s1; // 1
                     ~~
```

Expected one more error:
```
error CS8352: Cannot use variable 's2' in this context because it may expose referenced variables outside of their declaration scope
                s0 = s2; 
                     ~~
```

**Comment by jjonescz** [comment]
This bug seems invalid to me. `class Enumerable1` cannot store `ref i1` in safe code. And when changed to `ref struct`, it correctly reports the error: [SharpLab](https://sharplab.io/#v2:EYLgtghglgdgPgAQEwAIEEYDsBYAUAbzxWLXQDY0AWFAWWhgAoBKIkw3EzlWAF24AYUAXhT8A3Ky4oAyigDOgkTACmAdxkMATsoBmAphI5SU7Y117d0wlOkNnOOgPaaUDWXKtK1G7XqjoDMSYTSXtOBWsPMRQAehibULDiYG0IAGs7JIBfRJIcoylTJIt/a1tcqSdUgGMAC1d3VFgUAFEYAFcwZU0IYAAbZXQAOgBhVJ5lLV1LJmCipJIIkTkkaLiUJAr7FOV0zLD8s0O8vHzfeR5Nduq+aTx5tABmH2mSuZR8/LxzuUvrvjanW6vQG6HuoQQzwwFEBXR6/UGKDGuwmUz8MD4AAdgkIAHwoAAmugg7T6PH2T1aHThEB4zisAHFlDxYcC6ZpmMJ8USdCSyYYvrhkFSgT12WCCBDnrIRu1NNoMVyUDxappHOoOn0+hTIShgI5HH1aI4AG7KAByygAHjxOXiULy+nJlAKgA)

The code that does the checking only performs the check if the return type is ref-like which seems correct to me since non-ref-like types cannot store refs:
https://github.com/dotnet/roslyn/blob/de96b01ccc6c51d2ad0501df18475079fbe2c7e1/src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs#L3031-L3035

**Comment by cston** [comment]
It looks like we're reporting an error when the enumerator type is a `class` and the enumerable is a `ref struct`. Should we only report an error when both are `ref struct` types?

**Comment by jjonescz** [comment]
> It looks like we're reporting an error when the enumerator type is a `class` and the enumerable is a `ref struct`. Should we only report an error when both are `ref struct` types?

I've tried to implement this by obtaining value escape for `collection.GetEnumerator()` call:

https://github.com/dotnet/roslyn/blob/ae8e2c24c07d8febb209d77b744e4df134babff8/src/Compilers/CSharp/Portable/Binder/ForEachLoopBinder.cs#L258-L261

But the `GetEnumerator()` call can be quite complex and to handle all cases, I would need access to `LocalRewriter` to avoid duplicating all this work, I guess:

https://github.com/dotnet/roslyn/blob/e263437db49b0650dbc72fca3331df654e05987c/src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_ForEachStatement.cs#L142-L147

Or do you have another idea how to implement that?
