### ISSUE TITLE
Incorrect scoped lifetime inference for out locals

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/roslyn#64394]
**Version Used**: 4.4.0-3.22479.16 (23ecea2c)

**Steps to Reproduce**:

```csharp
ref struct ByteContainer
{
    public byte B;

    public static void GetSpan(ref ByteContainer @this, out Span<byte> span)
    {
        span = new(ref @this.B); // Ok: @this has RSTE to return-only, and out is STE return-only by default
    }

    public static void Test1(scoped ref ByteContainer container)
    {
        // error CS9075: Cannot return a parameter by reference 'container' because it is scoped to the current method
        // error CS8350: This combination of arguments to 'ByteContainer.GetSpan(ref ByteContainer, out Span<byte>)' is disallowed because it may expose variables referenced by parameter 'this' outside of their declaration scope
        GetSpan(ref container, out Span<byte> span);
    }
}
```

**Expected Behavior**:

The code should compile fine, and `span` should be implicitly `scoped`.

**Actual Behavior**:

Code fails to compile with the errors above.

**Additional notes**:

Related to #64318 (cc. @jaredpar as discussed on Discord).

**Comment by jaredpar** [comment]
It looks like we aren't doing correct local lifetime inference for declaration expressions. That seems like a longer standing issue but it's easier to expose now.

**Comment by RikkiGibson** [comment]
https://github.com/jaredpar/csharplang/blob/out/proposals/csharp-7.2/span-safety.md#locals

I think a spec change is needed here. We don't currently do anything special to determine the val escape scope for declaration expressions, so we just default to calling method.

I am thinking the RSTE should be calculated as normal (based on the scope where the local is declared) but the STE should be calculated as the narrowest of:
- calling method
- if out variable's type is ref struct:
    - STE of any argument where its corresponding parameter has STE of ReturnOnly or wider
    - RSTE of any argument where its corresponding parameter has STE of ReturnOnly or wider
where we temporarily assume that the STE of a declaration-expression argument is *calling method*.

**Comment by jaredpar** [comment]
> I think a spec change is needed here. We don't currently do anything special to determine the val escape scope for declaration expressions, so we just default to calling method.

Yeah the original spec doesn't really cover declaration expressions. The decision to always use _calling method_ had holes even before the introduction of _return only_ but it requires a bit more effort to hit. 

```csharp
ref struct RS {
  public RS(Span<int> span) { ... } 
  public void M(out Span<int> span) { ... n
  static void Example() {
    RS local = new RS(stackalloc int[42]); 
    local.M(out Span<int> span); // error
  }
}
```

The introduction of _return only_ and `scoped` locals does make it easier to hit this though. 

> where we temporarily assume that the STE of a declaration-expression argument is calling method.

I largely agree with your rule proposal but am not quite grasping why this part is necessary. Can you elaborate?

**Comment by RikkiGibson** [comment]
We want to avoid making the definition of an argument's STE depend on itself recursively. Suppose we want to determine the STE of `out var rs4` in the following example.

```cs
ref struct RS { }

class Program
{
    // RSTE of rs1 is ReturnOnly. STE of rs2 is ReturnOnly.
    static void M0(ref RS rs1, out RS rs2) => throw null!;

    static void M1(scoped ref RS rs3)
    {
        // RSTE of rs3 is CurrentMethod
        // STE of rs4 (local variable) is also CurrentMethod
        M0(ref rs3, out var rs4);
    }
}
```

In this part of the spec:
> * STE of any argument where its corresponding parameter has STE of ReturnOnly or wider

We are being asked to determine STE of `out var rs4`, which is what we're already in the process of doing. If we used the normal method of determining that STE, the algorithm would never terminate. Since we know this STE is really just an "aggregate" of escape scopes of other arguments, we ignore it during this step of determining the narrowest argument scope, by treating this argument as though it has the widest scope.

**Comment by jaredpar** [comment]
> We want to avoid making the definition of an argument's STE depend on itself recursively
> If we used the normal method of determining that STE, the algorithm would never terminate.

But why is the STE of this included at all? The spec says that arguments corresponding to `out` parameters don't contribute to the STE of the returned values. It seems that here we should be excluding all `out` arguments as well otherwise we will end up with incorrect lifetimes. 

Consider as an example the following: 

```csharp
void M(ref Span<int> span, out Span<int> out1, out Span<int> out2) { ... }
void G(ref Span<int> p1) {
  Span<int> local = stackalloc int[42]; 
  M(ref p1, out local, out var p2);
}
``` 

If `out` arguments are included in the analysis then your spec would infer _current method_ for `p2` where as I would expect _calling method_.

**Comment by RikkiGibson** [comment]
Agreed, thanks. Edited https://github.com/dotnet/roslyn/issues/64394#issuecomment-1264125559.
