### ISSUE TITLE
BoundBlock should have a constructor which defaults the localFunctions parameter.

### ISSUE THREAD

**Issue by tannergooding** [dotnet/roslyn#6440]
BoundBlock was modified in v2.0 to support `localFunctions`. Presently, all calls to the BoundBlock constructor have been modified to explicitly pass `ImmutableArray<LocalFunctionSymbol>.Empty`. 

Instead, this should be the default behavior of the primary constructor and an override should exist which allows explicit setting of the `localFunctions` parameter (the same defaults might be provided for the `locals` and `statements` parameters as well, depending on how often `ImmutableArray.Empty` is passed to them).

**Comment by tannergooding** [comment]
FYI. @dotnet/roslyn-compiler

**Comment by VSadov** [comment]
It would be very common for a block to not have nested function so it should have a ctor overload that does not take nested functions parameter.
For the local and statements - I am not sure. Generally block has either one or another and I am not sure which is more frequent.

**Comment by TyOverby** [comment]
It looks like adding another constructor will be hard because BoundBlock is a class that is generated from BoundNodes.xml.  

There are some static methods that act like constructors which I could add to, but it looks like [there are already some methods there](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/BoundTree/Constructors.cs,526) that would fit what you want.

**Comment by AlekseyTs** [comment]
We can always add constructors we need, they don't have to be all produced by the generator. The class is partial right? See src\Compilers\CSharp\Portable\BoundTree\Constructors.cs for example.
