### ISSUE TITLE
CodeLens reports method references for unselected targets

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/roslyn#64422]
**Version Used**: Version 17.4.0 Preview 3.0 [32930.306.main]

**Steps to Reproduce**:

1. Create a project multi-targeting .NET Standard 2.0 and .NET 6.
1. Paste the following code:
```csharp
internal class Foo
{
    public void Test()
    {
#if NET6_0_OR_GREATER
        Bar();
#endif
    }

    private void Bar()
    {
    }
}
```
1. Select the .NET Standard 2.0 target from the dropdown in the IDE

**Expected Behavior**:

CodeLens should have the number of references matching IntelliSense, ie. 0 references. I'd expect CodeLense to match IntelliSense and report 0 references, given there are in fact 0 on the currently selected target.

**Actual Behavior**:

CodeLens shows 1 reference, which directly contradicts IntelliSense graying out the method and saying it's unused.

**Screenshot**:

<img width="346" alt="image" src="https://user-images.githubusercontent.com/10199417/193413761-e4fdb2bc-e023-4179-8da6-a91a638f7f99.png">

**Comment by CyrusNajmabadi** [comment]
FindReferences should find that item regardless of what flavor you were in when you invoked it. We originally didn't do this but got massive feedback of how undesirable this was because it caused people to miss important references. Users wanted the full picture for operations like this. Not slices.

**Comment by Sergio0694** [comment]
I see. That makes sense, but I do think the current UX is a bit confusing with the method being grayed out and marked as unused (correctly), but with CodeLens still showing references. Not sure how I'd improve this though, and I do absolutely want the method to keep being marked as unused here 🤔

**Comment by lsoft** [comment]
![image](https://user-images.githubusercontent.com/5988558/193548455-f1d76c23-3238-427d-bd25-d73a9bda5fa1.png)

this would be cool, I think!

**Comment by jasonmalinowski** [comment]
This is indeed by design; the combo box really only controls what is used for classification, since other features merge the results across all of the various targets.  That's not unique to just code lens but also things like completion as well. And people very much expect that zero references means something can be deleted, which isn't the case here. Perhaps there's some other way we could distinguish that but we wouldn't simply make the counter go to zero.

There are also some trickier design questions to answer too -- in the screenshot above it's fairly easy to reason about how this works since it's only a single file, but how does this work if the references are in different projects that might have a different set of project targeting. Does a library that multitargets one set of TFMs but is consumed in a project with a different set of TFMs chase across the project references and filters accordingly? But what if you do want to see all of them?

If we get more requests here perhaps we can figure out a good design, but until then let's keep this as is.
