### ISSUE TITLE
Fix up integration tests and make it required in PR validation

### ISSUE THREAD

**Issue by arkalyanms** [dotnet/roslyn#64545]
Starting with Joey to close out his open PRs to evaluate if we need further work here. @Cosifne can help as needed.

**Comment by Cosifne** [comment]
A couple of thing on my list :
1. Navigate test might be flaky (not very flaky) The root reason seems like http://index/?leftProject=Microsoft.VisualStudio.Shell.UI.Internal&leftSymbol=mrcrzs7nl8wa&file=Packages%5CSearch%5CPackage%5CPackageAllInOneSearchButtonPresenter.cs&line=67 This fire and forget task
2. Timeout. This looks like caused because 
          a. https://sourceroslyn.io/#Microsoft.VisualStudio.LanguageServices.IntegrationTests/VisualBasic/BasicWinForms.cs,17
           Some tests here 
![timeout (21)](https://user-images.githubusercontent.com/24360909/194407815-d3cc727a-9f44-4dee-a2a0-51840aab183d.png)
A mystery that it is saving resx file???

b. Either this [test](https://sourceroslyn.io/#Microsoft.VisualStudio.LanguageServices.New.IntegrationTests/CSharp/CSharpCodeActions.cs,1247) or [this](https://sourceroslyn.io/#Microsoft.VisualStudio.LanguageServices.New.IntegrationTests/CSharp/CSharpCodeActions.cs,1169)
is waiting forever so it caused a timeout.
![timeout (27)](https://user-images.githubusercontent.com/24360909/194410479-fe245c9c-69f1-4937-9867-f1b35cda7fcf.png)

**Comment by JoeRobich** [comment]
Will need to investigate why QuickInfo session was being returned as `null` in Workspace ProjectProperties tests https://github.com/dotnet/roslyn/issues/64672

**Comment by JoeRobich** [comment]
I asked @jasonmalinowski to look at https://github.com/dotnet/roslyn/issues/64721, but he may not have time for a few days.

**Comment by Cosifne** [comment]
Closed the issue because Integration tests has a good pass rate now and it is enabled as required again.
