### ISSUE TITLE
UnscopedRef ref returning method acts differently than its property counterpart

### ISSUE THREAD

**Issue by NinoFloris** [dotnet/roslyn#64606]
UnscopedRef ref returning method acts differently than its property counterpart, this seems like a bug after carefully reading the spec.

Given the following example, only repro 1 and 3 compile.

```cs
class Repro
{
    ref struct Data
    {
        Span<byte> _span;

        [UnscopedRef]
        public ref Span<byte> Span => ref _span;

        [UnscopedRef]
        public ref Span<byte> GetSpan() => ref _span;
    }

    void Repro1(ref Data data)
    {
        ref var span = ref data.Span;
    }

    void Repro2(ref Data data)
    {
        // [CS8166] Cannot return a parameter by reference 'data' because it is not a ref parameter
        ref var span = ref data.GetSpan();
    }

    void Repro3([UnscopedRef]ref Data data)
    {
        ref var span = ref data.GetSpan();
    }
}
```

SDK Version: 7.0.0-rc1

**Comment by jaredpar** [comment]
Thanks for taking the time to report this. The issue was fixed after RC1 fixed and you can see the change here 


https://sharplab.io/#v2:EYLgtghglgdgNAExAagD4AEBMBGAsAKHQAYACdbAOgBEoIBzGAewGcAXKAY2YoGFGEApgEEYEADYBPZlGYBuAgSwkASgIAOAJ0YEA3gRIGSGgQDMSbDQFcOrElQisI+w3vyH3JAMpqIMADzAEqwCAHwkAPrMPjDy+M4eJADaAKowzByMagIIqiYAuvEe6ADMRqZe0QFBoRW+JAC8YcZmkdGxhe4paRlZOaYFbglkpc21/oHBYQDiAqzevgAUAJQNTeWtvrHuAL4KgwboACwq6lrYC6P2jiQIDhBLha5DZWYAbhAa5tENLzd3FPMYoVdnF9mRjqpNIxMBdylcIH9HA8wU8hgB6NFJHieAAc2AAbPi8iQeL4mLZ0AB2EgInwaCBgWYCT6BF7MgQwDgCEgAclujh5JGAAg4EEszG5UFsMhI5JpvzpDKZGg6hlG70+UTq9V+/IgFBmc2iyy2hhBhSOJyhxQWXXSmWyuTylzuiPuj1VBnVHy+2t1/0NgJNwII5vwokZWq5ZEoNHoTDYnG4fEEInEUhkugtmBIqXtvVyQlYrA0UGAlmCJBAJCLJbLFYEOhIIO2QA==

Note that `Repo3` still has an error but the work to support `[UnscopedRef]` on explicit `ref` parameters was moved to post .NET 7 RTM. Will be taken as a servicing fix after.
