### ISSUE TITLE
Concord (Microsoft.VisualStudio.Debugger.{Metadata,Engine}) supplied as in-tree binary blobs

### ISSUE THREAD

**Issue by SamB** [dotnet/roslyn#6486]
Okay, so technically it's supplied as textual IL code, but either way it looks ugly, and results in a bunch of crufty-looking references throughout the ExpressionEvaluator/ tree of the forms:

    <Reference Include="$(OutDir)Microsoft.VisualStudio.Debugger.Engine.dll" />
    <Reference Include="$(OutDir)Microsoft.VisualStudio.Debugger.Metadata.dll" />

Which, to the uninitiated, look sort of like something left over from the days before project.json.

Then there's also the fact that the DLL files we build seem to just be reference assemblies, and all the other reasons that it's annoying to have non-source or non-free blobs sitting around in a repository (though at least these things are somewhat diff-friendly, and so probably benefit from git's delta compression).

**Comment by KevinH-MS** [comment]
@SamB what's the request here?

We need to support compiling the EE against a fixed version of these assemblies (not whatever's installed with the developer's VS version).  We don't want to check the binaries into our git repo, and they aren't available as nugets, so we've checked in an IL file that we compile on the fly.  It's relatively convenient for us to generate a new IL file whenever we need to update to a new version of this assembly and using IL (rather than the original source file) means we don't have entanglements with proprietary Visual Studio source code.

**Comment by ManishJayaswal** [comment]
@SamB closing this for now. Please reactivate if you still have concerns/questions.
