### ISSUE TITLE
Keywords in the completion list: foreach as a keyword and as a snippet?

### ISSUE THREAD

**Issue by dpugh** [dotnet/roslyn#64967]
**Version Used**: 
Version 17.5.0 Preview 1.0 [33019.161.main]

**Steps to Reproduce**:

Why am I seeing a “foreach” keyword (in addition to the “foreach” snippet but not a “for” keyword (though I do see the “for” snippet)?
![image](https://user-images.githubusercontent.com/11394666/197834362-e5ad03d3-b177-4805-847b-92fa5de3475a.png)
The inconsistency between for and foreach feels like a bug, but I don’t know in which direction.

**Expected Behavior**:
No "foreach" keyword

**Actual Behavior**:
A keyword for "forech" but not "for".

**Comment by CyrusNajmabadi** [comment]
@akhera99 ?

**Comment by akhera99** [comment]
This is with the new snippet experience. I replace the new snippets with the old snippets and, if the snippet is a keyword, have the keyword also present in the completion list since there is no longer double-tab behavior. 
Foreach is present and not for because there is no for snippet currently in.
If you'd like to switch the new experience off, go to Tools -> Options -> TextEditor -> C# -> Intellisense -> "Show new snippet experience (experimental)"

As an aside, do you think this should be turned off by default for preview 5?

**Comment by genlu** [comment]
Before semantic snippets, we would add both "for" keyword and snippet items into the list, and when we deduplicate items, the keyword item would be "overwritten" by snippet, which means you will see a "for" snippet item only. The same was true for "foreach", you'd only see a "foreach" snippet item.

Now we have added a new "foreach" semantic snippet (the one with inline description), and removed the old "foreach" snippet. As a result of this, the "foreach" keyword item is no longer being "overwritten" (since the corresponding snippet is not there anymore)

If you turn off semantic snippet, you'd only see snippets but not keywords for both "for" and "foreach"
![image](https://user-images.githubusercontent.com/788783/197849785-b7989af1-8e69-4294-bff1-32ae95744648.png)

**Comment by CyrusNajmabadi** [comment]
Closing out as we are unlikely to change this.
