### ISSUE TITLE
Negative number in pattern matching

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#65338]
### Discussed in https://github.com/dotnet/roslyn/discussions/65337

<div type='discussions-op-text'>

<sup>Originally posted by **CreateAndInject** November 10, 2022</sup>
```C#
        object obj = null;
        if (obj is short x && x == -1) // How to simplify by pattern matching
            Console.WriteLine();
```

Should be `if (obj is short and -1)`?
It's invalid, but why `if (obj is short and 1)` is valid?
</div>

**Comment by jcouv** [comment]
It seems to be a parsing issue. `obj is short and (-1)` works fine, but `obj is short and -1` yields "unexpected token '-'".

**Comment by jcouv** [comment]
I think this is intentional and meant to preserve backwards compatibility. See the following logic and comment in `IsValidPatternDesignation`:
`if (SyntaxFacts.IsBinaryExpression(tk)) return true; // `e is int and && true` is valid C# 7.0 code with `and` being a designator`

So in this scenario, `short and` is parsed as a type followed by a variable designation/identifier "and", like we would for `is short x` followed by some binary operator.

I'll close as by-design.
