### ISSUE TITLE
Intellisense switch expression produces invalid code from `not` pattern

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#65683]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Intellisense-switch-expression-produces-/10214198)._

---
\[severity:It bothers me. A fix would be nice\]

```  
string Func()
	{
        object value = 3;
        if (value is not int intValue)
            return string.Empty;

        return intValue.ToString();
    }
```

Intellisense option to change this to a switch expression produces this invalid code:

```  
return value switch
        {
            not int intValue => string.Empty,
            _ => intValue.ToString(culture)
        };
  
```

It should be:

```  
return value switch
        {
            int intValue => intValue.ToString(culture),
            _ => string.Empty
        };
  
```

---
#### Tracy Wang [MSFT] on 11/28/2022, 00:24 AM: 

(private comment, text removed)
#### Nick Bauer on 11/28/2022, 08:02 AM: 

(private comment, text removed)
#### Nick Bauer on 11/28/2022, 07:11 PM: 

(private comment, text removed)
#### Tracy Wang [MSFT] on 11/28/2022, 06:29 PM: 

(private comment, text removed)
#### Feedback Bot on 11/28/2022, 07:58 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by victor-pogor** [comment]
I understand this could not be a real code but I was thinking about the case when having duplicate `if .. is not int` statements, I cannot imagine how the fixed analyzer must handle this :)

```csharp
string Func()
{
    object value = 3;
    if (value is not int intValue)
        return "-1";

    if (value is not int intValue2) // Duplicate "if .. is not int", maybe not a real use case but is allowed by the compiler :)
        return "0";

    return intValue.ToString() + intValue2.ToString(); // Output: "33"
}

// Translated to

string Func()
{
    object value = 3;
    return value switch
    {
        not int intValue => "-1", // Error CS8780 A variable may not be declared within a 'not' or 'or' pattern.
        not int intValue2 => "0", // Same error + Error CS8510 The pattern is unreachable. It has already been handled by a previous arm of the switch expression or it is impossible to match.
        _ => intValue.ToString() + intValue2.ToString() // Error CS0103 The name 'intValue' does not exist in the current context
    };
}
```

**Comment by sdelarosbil** [comment]
I could take this, but looking into it, it seems there's only 2 cases to keep in mind:

1. The original issue
2. Having more than 1 if not with declaration

I think the original issue can work as suggested since it's only inverting the expression and if we know there's only one if not, we can be sure it would work.

However, for number 2, I don't see any way to handle it. The main issue here is the nullability: confirming a negative on a if not like this makes it for sure not null so we can't reuse the original value because it looses that nullability and we can't declare it in the expression because of syntax limitations. We are at an impasse here: I don't see how you can convert it such that it remains semantically equivalent.

So my proposed solution would be:

- If we run into case number 2, don't offer the code action
- If we run into case number 1, offer it, but invert it such that it fits with the swich expression

Does this sound reasonable?

**Comment by CyrusNajmabadi** [comment]
Honestly, the emitted code seems totally reasonable to me.  It matches the original semantics, and scales up properly no matter how many ifs there are.  Flipping 'not'ed code is a different sort of feature.  One which i suppose someone could offer on the final switch if we felt it was important enough.  Closing out as working as expected.
