### ISSUE TITLE
Find All References fails to find some references

### ISSUE THREAD

**Issue by VladimirReshetnikov** [dotnet/roslyn#661]
* Sync Roslyn git repo to commit `cc4b4333309df6de992de5ca5170698911d5b153`
* Open Roslyn.sln in Visual Studio (with Roslyn language service installed)
* Go to file `src\EditorFeatures\Test2\Simplification\AbstractSimplificationTests.vb`
* At line 19, column 109 there is a `StartsWith` identifier that binds to `string.StartsWith(string)`
* Try to Find All References of this symbol.

__ACTUAL:__
Some references are not found, in particular:
 * `src\EditorFeatures\Test2\Simplification\AbstractSimplificationTests.vb`, line 19, column 109
 * `src\Compilers\VisualBasic\Test\CommandLine\CommandLineTests.vb`, line 5181, column 36

__EXPECTED:__
All references are found

**Comment by VladimirReshetnikov** [comment]
It looks like there is a problem with finding references within VB lambdas.

**Comment by brettfo** [comment]
After syncing to the specified commit I was unable to build due to various errors and that ultimately led to finding all references on the original symbol to return nothing.  After trying this on the latest sources, however, I was able to find all references appropriately, including the examples you specified; both to and from symbols contained in VB lambdas.

Let me know if you find another repro.
