### ISSUE TITLE
What is the best approach to create diagnostic which relies on symbol references?

### ISSUE THREAD

**Issue by Przemyslaw-W** [dotnet/roslyn#66100]
Hi,

I need to raise a diagnostic for a member declaration if it is not used as it is supposed to be used. Normally, I would create DiagnosticAnalyzer, register the proper symbol action and within this action I would find references to my member using the SymbolFinder.FindReferencesAsync(). Then I would analyze these references and report diagnostic if necessary. Unfortunately, I don't have a Solution instance necessary for SymbolFinder.FindReferencesAsync(...) call.

What is a recommended approach to create this diagnostic?

**Comment by Przemyslaw-W** [comment]
Anyone?

**Comment by CyrusNajmabadi** [comment]
There is no way to do this.  Analyzers have no view of the entire solution.  This is very much due to the design of how compilation works at a fundamental level.  Consider how things are compiled when a build is kicked off.  MSbuild will invoke the compiler on a single set of source-files.  There is no way for that compiler to know all the downstream projects that depend on these files, and may have references to symbols within them.

For use cases like this, teh solution is to instead write a standalone app that loads the solution (with something like MSBuildWorkspace) and then processes that.

**Comment by Przemyslaw-W** [comment]
Thank for the explanation.
