### ISSUE TITLE
"Replace property with method" shouldn't convert expression body to block body

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/roslyn#66113]
**Version Used**: 

Version 17.5.0 Preview 3.0 [33219.13.main]

**Steps to Reproduce**:

```c#
public bool IsEnabled => true;
```

1. Caret on member name
2. Ctrl + .
3. select "Convert 'IsEnabled' to method"

**Expected Behavior**:

```c#
public bool GetIsEnabled() => true;
```

**Actual Behavior**:

```c#
public bool GetIsEnabled()
{
    return true;
}
```

**Comment by CyrusNajmabadi** [comment]
This feature should respect your recommended style preference for the destination. So if your default is to prefer block bodies, it should respect that.  If it is too prefer expression bodies, it should prefer that. 

(This is a note for whoever looks info this issue)

**Comment by drewnoakes** [comment]
I live in a middle ground where I leave it to my discretion whether a member should be expression or block bodied. If I've decided that for a property, the decision holds for a method (and vice versa). It's been a while since I tried setting up a rule for body style, but from memory I couldn't configure it how I wanted.

**Comment by CyrusNajmabadi** [comment]
Generally, the idea would be to stick to the defaults here. Someone converting to a method , for example, us likely doing so so they can add more to the body.  And the defaults for methods is to prefer blocks since that's the general preference of the ecosystem. So we convert so that we both follow the preference and so if you need to add code, you can do so easily. 

If you do want to keep these as exprs when converting, that should be respected if you set such a preference.  If it is not respected, that's something we should fix on our end.
