### ISSUE TITLE
Conditional null access produces weird error for nullable value types

### ISSUE THREAD

**Issue by DoctorKrolic** [dotnet/roslyn#66143]
**Version Used**:
Latest `main`

**Steps to Reproduce**:
```cs
byte? value = 255;
object? boxedValue = value?.Value;
```

**Expected Behavior**:
Either successful compilation or adequate error message, explainig why I cannot use conditional access operator on nullable value types

**Actual Behavior**:
`CS1061: 'byte' does not contain a definition for 'Value' and no accessible extension method 'Value' accepting a first argument of type 'byte' could be found (are you missing a using directive or an assembly reference?).`

Type of `value` is `byte?`, why the error message tells about `byte` type?

**Comment by svick** [comment]
> Type of `value` is `byte?`, why the error message tells about `byte` type?

Because that's what the `?.` operator does: it lets you access members of the underlying type. For example, `value?.ToString()` is effectively the same as `value is null ? null : value.Value.ToString()`.

**Comment by jcouv** [comment]
Introducing a better error message in this scenario would require that we try binding the `a?.b` expression as `a.b` to see if member `b` is available on nullable type `A` rather than its underlying type. Then we could report that the `?.` was unnecessary. 
I don't think this is worthwhile. I'll go ahead and close.
