### ISSUE TITLE
`default` constraint of generic type is not generated

### ISSUE THREAD

**Issue by andriipatsula** [dotnet/roslyn#66382]
## Context
One of the steps to close the gap between the existing official build and the [.NET source-build](https://github.com/dotnet/source-build) is enabling prebuilt detection on the individual product repository level. 

Our goal is to introduce prebuilt detection on an individual product repo level so that developers could detect prebuilts during their PR validation and resolve the problem by generating the SBRPs themselves with minimum assistance from the A&D team. 

Unfortunately, the current [SPRB](https://github.com/dotnet/source-build-reference-packages/tree/main/src/referencePackageSourceGenerator) (Source Build Reference Package generation tooling), [GenAPI](https://github.com/dotnet/arcade/tree/main/src/Microsoft.DotNet.GenAPI), is not sufficient for this scenario as it uses the old Microsoft Common Compiler Infrastructure (Microsoft CCI) to generate the API surface for individual packages. The Microsoft CCI backend needs to be periodically updated to reflect the latest language changes which is often a time-consuming task requiring significant expertise.

We developed a [Roslyn-based GenAPI](https://github.com/dotnet/sdk/tree/main/src/GenAPI) tool that aims to replace the CCi-based version. During the testing we found several bugs in the API (Workspaces) all summarized at [Summary of issues found during testing of the Roslyn-based GenAPI](https://github.com/dotnet/arcade/issues/12009) issue in dotnet/arcade.

---

**Version Used**: 4.5.0-3.22601.3 (~main)

**Steps to Reproduce**:
Issue: on our side: https://github.com/dotnet/arcade/issues/10526

Example:
```C#
public abstract partial class A
{
    public abstract TResult? Accept<TResult>(int a);
}

public sealed partial class B : A
{
    public override TResult? Accept<TResult>(int a) where TResult : default { throw null; }
}
```
After roundtrip: source -> ISymbol-> SyntaxGenerator -> source:
```C#
public abstract partial class A
{
    public abstract TResult? Accept<TResult>(int a);
}
public sealed partial class B : A
{
    /// error CS0508: 'B.Accept<TResult>(int)': return type must be 'TResult' to match overridden member 'A.Accept<TResult>(int)'
    /// error CS0453: The type 'TResult' must be a non-nullable value type in order to use it as parameter 'T' in the generic type or method 'Nullable<T>'
    public override TResult? Accept<TResult>(int a) { throw null; }
}
```

**Diagnostic Id**:

**Expected Behavior**:

**Actual Behavior**:

**Comment by jcouv** [comment]
@andriipatsula From your description, it sounds like two components might be suspect: 1. `ISymbol` API, 2. your syntax generator.
I don't recall that any API would flag the `default` constraint, since it means unconstrained. I suspect this situation needs to be handled by the syntax generator.
If you think the problem is with the `ISymbol` API, what is the precise API and expected vs. actual behavior for said API?

**Comment by jcouv** [comment]
FYI @DoctorKrolic @CyrusNajmabadi, I suspect this is a SyntaxGenerator issue (rather than a compiler symbol issue).
The situation is when a `T?` symbol that is an annotated reference type (as opposed to a nullable value type) appears in an override. In such situations, `where T : default` must be used, otherwise `T?` means `System.Nullable<T>` (the nullable value type interpretation is preferred in this context for back compat).

**Comment by CyrusNajmabadi** [comment]
Need help from compiler on this (@cston ).  Basically, i don't see anything on ITypeParameter symbol to know thta this type parameter has the `default` constraint on it.  Absent that, i'm not sure how we would know we need to generate this here.
