### ISSUE TITLE
CSC0165 unassigned local if assigned in await

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#6648]
```C#
int val;
await Task.Run(() => val = 4);
int use = val;
```
or, similarly
```C#
int val;
await Task.Run(() => MakeUp(out val));
int use = val;
```

results in CS0165 Use of unassigned local variable 'val'.
Is there a way how this could happen?

**Comment by pdelvo** [comment]
This is by design. The compiler should not make assumptions about the object it awaits on. You can write a different method then Task.Run that does not call the delegate it gets at all and then the variable would be not uninitialized. What you can do is just give val a default value and then it should work.

**Comment by miloush** [comment]
Yep that's the way I was looking for. Thanks!
