### ISSUE TITLE
Optimize string concatenation using an interpolated string

### ISSUE THREAD

**Issue by khellang** [dotnet/roslyn#6669]
It would be nice if the compiler optimized interpolated strings where you're basically just doing concatenation. `string.Concat` is faster than `string.Format`, at least for up to 3-4 strings.

See https://github.com/aspnet/HttpAbstractions/pull/460 for reference. There's a benchmark at https://gist.github.com/NickCraver/fce9754c50aa7a4c9593.

## Example

```csharp
var result = $"{a}{b}";
```

becomes

```csharp
var result = string.Concat(a, b);
```

instead of

```csharp
var result = string.Format("{0}{1}", a, b);
```

**Comment by bbarry** [comment]
I'm going to redo that before submitting it upstream... I think it is in the wrong place.

The idea is that if there are no format string *alignment* or *formatString* parameters, it should be faster to do a `string.Concat` call instead of `string.Format` always.

However this lowering only handles interpolated strings. I think it should be done for all calls of `string.Format` where the first parameter is a constant string that matches `^(?:\{\{|\{\s*\d+\s*\}|\}\}|[^\{\}])*$`.

**Comment by bbarry** [comment]
So... where would I start on intercepting the calls for `string.Format` to rewrite them (and should that be done)? 

Playing around with dotpeek, I notice:

```csharp
var s = "s";
Console.WriteLine("" + "abc" + s + "");
Console.WriteLine(string.Concat( "", "abc", s, ""));
Console.WriteLine($"abc{s}");
```

becomes:

```
IL_0001: ldstr        "s"
IL_0006: stloc.0      // s

// Console.WriteLine("" + "abc" + s + "");
IL_0007: ldstr        "abc"
IL_000c: ldloc.0      // s
IL_000d: call         string [mscorlib]System.String::Concat(string, string)
IL_0012: dup          

IL_0013: brtrue.s     IL_001b
IL_0015: pop          
IL_0016: ldstr        ""
IL_001b: call         void [mscorlib]System.Console::WriteLine(string)
IL_0020: nop          

// Console.WriteLine(string.Concat( "", "abc", s, ""));
IL_0021: ldstr        ""
IL_0026: ldstr        "abc"
IL_002b: ldloc.0      // s
IL_002c: ldstr        ""
IL_0031: call         string [mscorlib]System.String::Concat(string, string, string, string)
IL_0036: call         void [mscorlib]System.Console::WriteLine(string)
IL_003b: nop          

// Console.WriteLine($"abc{s}");
IL_003c: ldstr        "abc"
IL_0041: ldloc.0      // s
IL_0042: call         string [mscorlib]System.String::Concat(string, string)
IL_0047: call         void [mscorlib]System.Console::WriteLine(string)
IL_004c: nop          
IL_004d: ret    
```

...

It looks like `"" + "abc" + s + ""` becomes `string.Concat("abc", s) ?? ""` but `string.Concat( "", "abc", s, "")` is left unchanged. Since my change skips the binary operators for string concat I don't get those optimizations (I'm not sure if they are worth it though).

Anyway my point is when an author uses `"" + "" ...` they get an optimization pass in LocalRewriter_StringConcat.cs, but when they use `string.Concat` they don't. If this was intentional, should I not intercept `string.Format` then?

**Comment by gafter** [comment]
See https://github.com/dotnet/roslyn/pull/6738#issuecomment-156257037 for why this is likely to never happen.

**Comment by bbarry** [comment]
Actually trying to benchmark the changes that I think could be done yield some performance differences, including relatively common cases (ex: $"test: {a} and {b} and {c}") where you hit the `string.Concat(string[])` method but if you were using `string.Format` you would have hit one of the overloads without the array (in which case the `Format` way is faster).

https://gist.github.com/bbarry/4b25a2ae1ab87a425825
