### ISSUE TITLE
Nullable state isn't propagated from out parameters if the return value is stored in local

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#66807]
**Version Used**: 

Version 17.6.0 Preview 2.0 [33407.517.main]

**Steps to Reproduce**:

```C#
using System.Diagnostics.CodeAnalysis;

var success = TryGet(out var x);
if (success)
{
    Console.WriteLine(x.ToString());
}

bool TryGet([NotNullWhen(true)] out object? x)
{
    x = new object();
    return true;
}
```

**Expected Behavior**:

No warnings.

**Actual Behavior**:

```
Program.cs(6,23,6,24): warning CS8602: Dereference of a possibly null reference.
```

This works as expected:

```C#
if (TryGet(out var x))
{
    Console.WriteLine(x.ToString());
}
```

**Comment by RikkiGibson** [comment]
Root cause is same as #27011. See also https://github.com/dotnet/roslyn/issues/66693#issuecomment-1416871548.

It's not clear whether a tractable design exists which handles cases like these. Some fairly deep investigation would be needed to determine that which is better done on the csharplang side.
