### ISSUE TITLE
CS8602 Nullable warning is missing

### ISSUE THREAD

**Issue by ogxd** [dotnet/roslyn#66921]
### Description

The CS8602 warning "Dereference of a possibly null reference" is missing under the following setup, while it seems obvious that an NRE could happen.     
I am not sure exactly what is causing the warning to not work for the moment, I'll adjust the issue title accordingly when it gets clearer.

### Reproduction Steps

Create two files, the first one having NRT disabled:
```csharp
#nullable disable
    
public class NonNullable
{
    public Dictionary<int, string> strings = new Dictionary<int, string> { { 0, null } };
}
```

And the second file, with NRT enabled:
```csharp
#nullable enable

NonNullable obj = new NonNullable();

if (obj.strings.TryGetValue(0, out string? value)) {
    Console.WriteLine(value.Trim());
    //                     ^ there is no warning here
}
```

### Expected behavior

I would expect to see a CS8602 warning since `out string? value` is marked explicitly as nullable and the parameter is tagged with the `MaybeNullWhen(false)` attribute.

### Actual behavior

The warning is missing

### Configuration

- dotnet sdk 7.0.100
- macOS ARM64
- Jetbrains Rider

**Comment by RikkiGibson** [comment]
#44063 is somewhat related here.

We don't expect the nullable annotation on `out string? value` to tell us that the value may be null even if `TryGetValue` returns true. We expect that the out variable always has a nullable annotation when it may be of reference type, whether the dictionary `TValue` type is nullable or not, because we want to have something we are allowed to assign null to in the case the key is not present in the dictionary.

So, unfortunately, the out variable at the usage site is not a viable point of control for the usage pattern you want. One way you might be able to get the kind of checking you want would be to convert the dictionary from using the oblivious types from the nullable-disabled context, to using non-nullable types in the nullable-enabled context. You could do this with an extension, an explicitly-typed local variable, or any other way that causes `obj.strings` to be converted. [SharpLab](https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLQAUEEsC2UECeAwgPYB2yMCcAxjCQsgDQAmIA1AD4DEZcANvyjB+EAAQssyYaICwAKAUABAEwBGZQAYxStQBYA3AuUBmHSrEA5cpYFCREBQG8FYtzrMARLHSzl8BAA8WGQwTDpqmgB8EZrIYgC8YmQQAO5i3r7+hMGh4brRYk5FYprhfIJiAL7VRvJVxvK8djLiEGStjboAbOZiAKIAHjDOru5KZj0ZPjB+HTkhYbEA/DG2gq0AylQhAObIABQwABZSVjYtDmIkwABWAJSJMTe3AHQFyHUNivKqEQDso3k7h0ejEAFkDvcxm4XMCQe5rGR1vZRNc7olkmlzsjLqIoXUYQisGAxAcXq8UVsdmR9lDXgAVQgAcQgMAAalB+HAIAcytc4DAVmIAG5cnn3R5whEyiIATgOYu5EEZ2BwUPuBjEAHptWJUvgyHsiSDvqaFFUgA=).

```cs
#nullable disable

using System;
using System.Collections.Generic;

public class NonNullable
{
    public Dictionary<int, string> strings = new Dictionary<int, string> { { 0, null } };
}

#nullable enable

static class Ext
{
    public static Dictionary<int, string?> NullableStrings(this NonNullable obj) => obj.strings;
}

class Program
{
    void M()
    {
        NonNullable obj = new NonNullable();

        if (obj.NullableStrings().TryGetValue(0, out string? value)) {
            Console.WriteLine(value.Trim()); // warning
        }
    }
}
```

**Comment by jcouv** [comment]
Based on the description in OP, I put together a simplified repro that doesn't involve `Dictionary`: [sharplab](https://sharplab.io/#v2:CYLg1APgAgTAjAWAFBQAwAIpwCwG5nIDEAdgK4A25AhgEbkCm69xtDBSAcgPbEcXV1GXGgCt0AXnTF6Ad3Tde/VvQAUASnxJkASwBm6FQr6VlAOgAqAJwCeAcXoAXAGpVypVagA06LqQeY4VAB+dAA3V3c1NXQAb2R0BICAThVwt3oLS20AW3UNeMSAekLE0rLyxIA9dAcAC3pLRm0AZykudBkqS2JtYgBzdHrG5ABfdhIlQXRgFuUChOQoAGZMGHkeYwE2JDikUuWAgDZ0Gi4ucnQrO0cXdJVe/21vX38sDDTIiQA+GtrLLjkZEomhGQA==) repro. 
There is no warning because oblivious APIs are considered to return non-nullable value. The fact that the variable is declared as `string?` does not affect the local's nullable-state during the nullability analysis.
Closing the issue as this is by-design for current language rules.
