### ISSUE TITLE
Better error recovery for statement directly inside a switch statement

### ISSUE THREAD

**Issue by svick** [dotnet/roslyn#66971]
Consider [the following code](https://sharplab.io/#v2:C4LgbgpgTglgZgTwD4AEBMBGAsAKFwZwHcZgBjACwAIAKAOwkMoHsAjAKwlOGoEofcA3rkojKLJkwA2lAMpMAthAAqEfNx6UAvAD5mlGPkoAWNAG5cw0aQCG+CPtrBKhchFqyFy1epCXRolAwATmoAImtaImhQnnMcf38WKAhrAGs4gF8gA=):

```c#
switch (new object())
{
    bool SomeTest() => o is 42;

    case int when SomeTest():
        Console.WriteLine("answer");
        break;
}
```

It contains a single, fairly simple mistake: the local function isn't allowed to be located directly inside the body of the `switch` statement. The problem is that this produces many errors, none of them particularly clear about the actual issue:

> error CS1513: } expected
> error CS1022: Type or namespace definition, or end-of-file expected
> error CS1003: Syntax error, ',' expected
> error CS1002: ; expected
> error CS1022: Type or namespace definition, or end-of-file expected
> error CS1022: Type or namespace definition, or end-of-file expected
> error CS0103: The name 'o' does not exist in the current context
> error CS0139: No enclosing loop out of which to break or continue

I think this should be improved. Ideally, there should be a single, clear error message here.

Note that this doesn't seem to be specific to local functions, the result is very similar if the erroneous statement is `int i;`.

**Comment by CyrusNajmabadi** [comment]
Definitely odd.  Here's how error recovery should have worked:

We should be in list parsing mode inside the switch. Seeing something invalid, we should ask if we should skip it or pop out of the list and end the switch. Since the invalid thing (the local function) is valid in the containing scope, we should terminate the switch and parse out the local function. Then, seeing a naked `case` we should report that this is invalid because we have no switch. We should then create a new switch node with missing nodes/tokens preceding the `case`, then resume parsing it. 

So I would expect two errors. `} missing` (before the local function), then `case is not legal outside of a switch statement`.

**Comment by CyrusNajmabadi** [comment]
Ok fixed.  Thanks for the report!
