### ISSUE TITLE
Improvements to documentation comments (that compilers output).

### ISSUE THREAD

**Issue by dfkeenan** [dotnet/roslyn#67]
Hi,

**Please add `<inheritdoc />` tag or similar:**

I think it would be really handy if the compiler(s) when outputting the documentation XML file if it could use inherited documentation where available/requested.  Though I am not sure what should be output if there is no documentation available.

**Please add the ability to add documentation comments for Namespace/Assembly:**

Currently if you want to do this for tools that generate documentation html etc. you have to add a dummy class and add the documentation comments to them. This one is a bit trickier because there aren't any viable options for doing them directly in code.  There is nothing you could put the assembly documentation against in code and namespaces are "declared" possibly in multiple files.  The only thing I could really think of is a separate XML file that gets merged into the documentation XML file that is output.

Cheers,
dfkeenan

P.S. A Diagnostic and Code Fix that generates document comments for me would also great :smiley:

**Comment by maxtoroq** [comment]
:+1: `<inheritdoc/>`

**Comment by matkoch** [comment]
Looking at how it works in [Sandcastle](https://ewsoftware.github.io/XMLCommentsGuide/html/86453FFB-B978-4A2A-9EB5-70E118CA8073.htm), I would like to argue against having the `select` attribute, because it's very likely to change documentation unintentionally (e.g., `select="para[last()]"`).

Some use cases:
- `/// <inheritdoc />` copies all tags like `summary`, `remarks` and so on
- `/// <inheritdoc /><summary><inheritdoc /> Additional text</summary>` inherits all tags, except `summary`, which is re-declared, but also can inherit
- `/// <summary><inheritdoc cref="System.Exception" /></summary>` in case there are multiple base classes/interfaces (apart from `System.Object`)

**Comment by gafter** [comment]
This seems like a nice potential enhancement to the expressiveness of the doc facility.

**Comment by gafter** [comment]
We are now taking language feature discussion on https://github.com/dotnet/csharplang for C# specific issues, https://github.com/dotnet/vblang for VB-specific features, and https://github.com/dotnet/csharplang for features that affect both languages.

**Comment by drauch** [comment]
@gafter: Should we reopen the issue at https://github.com/dotnet/csharplang or do you think it is okay to leave the docfx#1306 open?

**Comment by daveaglick** [comment]
@drauch @gafter DocFx is a separate tool and not part of the language or compiler. As the author of a .NET documentation tool I would really like to see support for `<inheritdoc>` exposed through the Roslyn XML documentation objects directly. I'm happy to reopen this over at csharplang if needed.

**Comment by gafter** [comment]
I think it would require language (and therefore compiler) support, so if you are still interested an issue at csharplang makes sense.

**Comment by drauch** [comment]
@daveaglick : Would love to see that 👍

**Comment by gafter** [comment]
This request is now tracked at https://github.com/dotnet/csharplang/issues/313
