### ISSUE TITLE
Source code generator compiles with 0 erros, but I get "This generator is not generating files"

### ISSUE THREAD

**Issue by wamfish** [dotnet/roslyn#67214]
https://github.com/wamfish/SourceGenTest.git

The above linked source code generator solution uses the following in the code generator project:

Microsoft.CodeAnalysis.Analyzers Version ="3.3.4"
Microsoft.CodeAnalysis.CSharp.Workspaces =  Version="4.5.0"

This solution contains 3 projects:

TestApp:

The AppTestDerived class is a partial class that has a base class of RecData that is defined in TestLib. TestCodeGen generates source for this class and compiles with 0 erros, but under Dependencies/Analysers/TestCodeGen/TestCodeGen.CodeGen we get: This generator is not generating files.

TestLib:

The LibTestDerived class is a partial class that also has a base class of RecData, The same base class as AppTestDerived above. TestCodeGen generates source for this class and compiles with 0 erros and Dependencies/Analysers/TestCodeGen/TestCodeGen.CodeGen works as expected. The only difference that I can see is that LibTestDerived is in the same project as
its base class, where AppTestDerived uses it from a referenced library.

TestCodeGen:

This is the source code generator project that both TestLib and Testapp reference.

I have noticed though, if I comment out the StatusCode field in RecData, so that only the abstract methods remain, TestApp will also work as expected.  So it seems if my source code generator adds to a partial class that is derived from an abstract class defined in a library project, there are limitations on what the abstract class can define. I do not know if this scenario is unsupported by Source code generators, or if this a bug?

**Comment by Skyppid** [comment]
I am experiencing these kinds of issues as of lately. We have two generators. One which generates returnable classes for our commands and queries which can be mapped to IActionResults and one that generates a developer-friendly model wrapper around our MongoDB entities.

For a while now it happens frequently that after opening the solution in a perfectly fine and valid state, the models just keep disappearing. Usually it's fixed by cleaning the solution, rebuilding the source generator only and then restart (sometimes multiple times) Visual Studio until they generate again.

Debugging it I could never find any issues. The outputs seem valid but it looks like a tooling issue. Visual Studio often doesn't seem to find the files although the generator in theory outputs the right ones. Maybe generation works but saving the files does not (afaik they're saved in some temporary folder).

It's kinda sad that SGs were implemented back in .NET 5 and tooling is still more than bad. It sure is a big task, but now that we rely on them it's a bummer that this works so poorly. Really considering copying the generated code once and keep maintaining it manually. I really hope they fix these issues soon, but I kinda doubt that. Seems to be to niche and low priority for it to happen anytime soon.

**Comment by CyrusNajmabadi** [comment]
> Really considering copying the generated code once and keep maintaining it manually

If you can do this, I would *highly* recommend doing so. SGs should be used only as a last resort, and only when no other options are viable.  I hope we'll be able to assign some resources to this in the future. But, for now, it's a very niche use case that is lower priority than all the rest if the things we've got on our plate. 

That said, if this is a super important area to you, and you are interested in contributing improvements, we'd certainly appreciate that. 

Thanks!

**Comment by wamfish** [comment]
I love the power of the source code generators. It was a bit of a gut punch to find out after creating mine, the limitations with the tooling as described in my initial post. I considered doing as Skyppid suggeted, but am using a different hacky approach to
solve the problem for now. 

I put all of my classes that need generation in a library project by themselves, and link to  the library from my application. I included the library project below. It is a bit of a hack and a bit cluggy when changing or adding classes to the library, as I have to clean, build often to keep  the compiler happy (as Skyppid described).  Since my solution is a bit of a hack, It feels like it could break on some future version of Visual Studio. For now it is a work around for my issue, but I will keep hoping that a proper fix
will be included in a patch at some point in the future.


```
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net7.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>disable</Nullable>
		<EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
		<CompilerGeneratedFilesOutputPath>Generated</CompilerGeneratedFilesOutputPath>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\WFLib\WFLib.csproj" />
		<ProjectReference Include="..\WFLibCG\WFLibCG.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
	</ItemGroup>
	<ItemGroup>
		<GenFiles Include="Generated\**\*.cs" />
	</ItemGroup>
	<Target Name="GenFixBeforeBuild" BeforeTargets="BeforeBuild">
		<Delete Files="@(GenFiles)" />
		<ItemGroup>
			<Compile Remove="@(GenFiles)" />
		</ItemGroup>
	</Target>
	<Target Name="GenFixAfterBuild" BeforeTargets="AfterBuild">
		<ItemGroup>
			<Compile Include="@(Genfiles)" />
		</ItemGroup>
	</Target>
</Project>
```
The hack above basically has the compiler place the generated source code into the "Generated" folder of the project. I 
remove the generated files in the BeforeBuild target, and put them right back in the AfterBuild target. This fools Visual Studio
into seeing the generated source files. I prefer having the generated files in my project anyway. On  a different thread I have read and understand the teams view on why they did not implement doing it this way in the first place. I just don't agree with it.  My 2 cents is to add a project  option to enable this behavior with out the cluggy parts included. ;-)

Anyway thanks for the input from the both of you.

**Comment by Skyppid** [comment]
> > Really considering copying the generated code once and keep maintaining it manually
> 
> If you can do this, I would _highly_ recommend doing so. SGs should be used only as a last resort, and only when no other options are viable. I hope we'll be able to assign some resources to this in the future. But, for now, it's a very niche use case that is lower priority than all the rest if the things we've got on our plate.
> 
> That said, if this is a super important area to you, and you are interested in contributing improvements, we'd certainly appreciate that.
> 
> Thanks!

I figured so. It's a bit sad since it was announced quite big yet after two major .NET versions it's still more like an early preview. And nowhere it's stated that it's not even recommended using productively.

Well I guess when we find that time we're gonna do it manually then. I'd love to participate but I guess without studying the fundamentals of MSBuild, VS and some portions of Roslyn it's hard to do any good as an external developer. Find the time to do this being a whole 'nother topic.

**Comment by jcouv** [comment]
I downloaded the project and spent some time looking at it this afternoon, but couldn't observe where "This generator is not generating files" is happening or supposed to happen. This repro is not streamlined. Sorry, I wouldn't have time to investigate further unless it is shrunk to the bare minimum.
