### ISSUE TITLE
All Quick Actions should have assignable shortcuts

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#67413]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/All-Quick-Actions-should-have-assignable/10203590)._

---
I’ve decided to give pure VS without Resharper a go, but I find shortcut support really lackluster and disappointing. Only some of Quick Actions have an assignable shortcut (i.e. Extract interface), many of them don’t (Move type to X.cs, Generate constructor). I believe all actions available under Alt+Enter menu should have their own shortcut, even if disabled by default.

---
#### Feedback Bot on 11/17/2022, 04:18 AM: 

(private comment, text removed)

**Comment by eduarddejong** [comment]
I was about to create a new issue for this, until I found this ticket and github issue, because Quck Actions really _want_ to be made a lot more user friendly!

I am working with Visual Studio, when I have a LOT of code that needs the same quick action applied, having easier shortcuts is a real need-to-have in my opinion.
In too many cases we still both don't get the option to a chosen action to many places at the same time as well as also don't have a direct way to choose the action by a simple key combination.

What actually happans is that after pressing Ctrl+. or Alt+Enter, the upper option that I don't need in the majority of time gets selected automatically and very often it has submenus that also automatically open.

So that I either need to grab the mouse repetitively for each case, increasing the risk for RSI - I want to need the mouse as little as possible when coding.
Or I really need to repetitively use the arrow keys in order to close the unwanted submenus first (left-press), followed by repetitive key presses in order to navigate to the right menu option (a lot of up / down presses) in order to eventually reach the option that I want.
And this whole thing over and over again for every case.

So again, yes improvement here would be very much appreciated!

**Comment by CyrusNajmabadi** [comment]
Closing out as external.  Editor/platform is tracking improvements here (including quick ways to invoke actions using the keyboard).
