### ISSUE TITLE
Please stop changing automatic bracket completion

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#67440]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Please-stop-changing-automatic-bracket-c/10316869)._

---
[severity:It's more difficult to complete my work]
In the past, automatic bracket completion i.e., adding a "}" when you open a "{", made sense. BAsed on, I assume, you're editor configuration it would add a "{" on a new line, your insertion point would be tabbed, then your "}":

```
void DoFoo()
{
    <insertion point>
}
```

At some point in recent history, that insertion point changed to, IIRC, right after "{". I had to hit return to put it in the "right" place, but that was fine. But with this most recent update to 17.6, now it's right in front of "}" which breaks IntelliSense since there's no whitespace right after:

```
void DoFoo()
{
<insertion point>}
```

This is worse because I have to arrow up then over then hit enter. I don't know why it changed in the first place since it seemed perfect before, but it'd be great if this quits changing or, better, goes back to how it used to work. Our repo has a .editorconfig file but that hasn't changed in a _long_ time.

It's gotten bad enough that I've now turned off bracket completion in my settings. It's negatively affected my productivity.

---
#### Feedback Bot on 3/21/2023, 10:14 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by heaths** [comment]
I was the one who opened this feedback but it didn't transfer entirely correctly. The first code snippet should have a `<insertion point>` on the seemingly blank line properly tabbed based on the user's settings.

The second code snippet should show the insertion point on the last line i.e., `<insertion point>}` (notice the closing bracket at the end). This effectively breaks IntelliSense because there's no whitespace. Correcting this requires at least 3 key presses which kills efficiency.

**Comment by CyrusNajmabadi** [comment]
This was not an intentional change.  @tmat could this be related to options not syncing properly?

**Comment by genlu** [comment]
Yea, I suspect it is this [bug](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1758005).
