### ISSUE TITLE
SyntheticBoundNodeFactory can emit Array.Empty<T> for arrays

### ISSUE THREAD

**Issue by bartdesmet** [dotnet/roslyn#6759]
In the following method:

```csharp
public BoundExpression Array(TypeSymbol elementType, ImmutableArray<BoundExpression> elements)
```

a special case for an empty array could be added, causing it to emit a call to Array.Empty (if available to the compilation) in lieu of allocating an empty array.

**Comment by bbarry** [comment]
So if I add this to that method:

    if (elements.Length == 0)
    {
        MethodSymbol arrayEmpty = Compilation.GetWellKnownTypeMember(CodeAnalysis.WellKnownMember.System_Array__Empty) as MethodSymbol;
        if (arrayEmpty != null)
        {
            arrayEmpty = arrayEmpty.Construct(ImmutableArray.Create(elementType));
            return Call(null, arrayEmpty);
        }
    }

the only place I hit a breakpoint on that return when running every test on the master branch under Compilers is `CodeGenExprLambdaTests.MethodCallWithParams` (2,000 left still to run in VisualBasic)...

I was expecting it to hit on `CodeGenTests.ParamCallUsesCachedArray` and [this test that I wrote](https://gist.github.com/bbarry/0c48af28e2a95ba0a938).

**Comment by gafter** [comment]
@bbarry The expression `new T[0]` is required to allocate a new array instance each time it is executed.

**Comment by bartdesmet** [comment]
The place where I noticed the unnecessary allocation of empty arrays was for the calls to the expression factories. Those copy the supplied array to a read-only collection so the uniqueness of the reference is invisible to the user after the factory runs, so it'd be fine to optimize there. However, the may be other places where the optimization may result in something visible to the user, e.g. when they put those arrays in a set of dictionary, assuming they are always unique. However, that argument could be made for empty params arrays too (receiver could store them somehow) and I believe we use Array.Empty unconditionally (unless unavailable) there in Roslyn as well.

**Comment by bbarry** [comment]
@gafter yes I initially looked at that method change and was wondering what it was supposed to do since making it and running tests had 0 effect on test results. So my comment initially was intended to be to the effect of "what is this change supposed to be doing?"

So I searched for every regex match `"new\s+\w+\s*\[0\]"` to attempt to figure out what kinds of things could be missing (like tests that were against output instead of IL). I noticed `CodeGenTests.ParamCallUsesCachedArray` and thought (incorrectly) that this test should fail with the change, but it doesn't. So I put a breakpoint on the `return Call` line and it doesn't run in that test or an additional one I wrote. So I debugged every test to see if I could hit that breakpoint in VS and wrote the above comment.

After I made the comment I realized there could be code out there that depended on the condition `!object.ReferenceEquals(new T[0], new T[0])` and that someone who was making a casual observation about a particular method deep in the middle of this repository should probably already know that. Then I noticed @bartdesmet created the issue and made the connection to it being something specific about expression tree generation. So I extracted the only test and ran it through the commandline compiler and looked at it with dotpeek (which fails to disassemble correctly to c#; I imagine these sorts of optimizations get to be rather painful for authors of tools like that one). Finally I updated the comment with what you now see.

----

I think there must be some missing tests around this but I'm not sure what they are. It seems to me that code running a visitor pattern over the expression tree could be using ReferenceEquals to keep track of objects used (thinking about things like linq to sql or linq to nhibernate) yet I am unsure if it possibly matters to such libraries that two empty arrays of the same type are different objects.

**Comment by bartdesmet** [comment]
Expression APIs will already turn any ICollection whose count is 0 (thus including an empty array) into a singleton ReadOnlyCollection object. See ToReadOnly on (IIRC) System.Dynamic.Utils.CollectionUtils in System.Core. So there's no concern about a change in publicly observable reference equality introduced by this change.

**Comment by jaredpar** [comment]
I agree with @gafter.  This optimization can't be done in the compiler because it breaks behavior guaranteed by the spec. We've been able to get away with using `Array<T>.Empty` in the `params` case because there was no guarantee of uniqueness.

**Comment by bartdesmet** [comment]
I agree for the general case, but it may still make sense for the expression APIs. Minor improvement though, because those empty arrays are very short lived given that the factories turn them into collections, so likely not worth the trouble.

**Comment by bartdesmet** [comment]
Actually, the much bigger language/framework design theme here is around construction of immutable collections so the factories could do away with all the collection cloning into TrueReadOnlyCollection instances.

**Comment by bbarry** [comment]
@jaredpar This doesn't affect `new T[0]` in the general case, it is only intended to avoid allocations on expression APIs using a constructor that is compiler generated where that constructor is expecting an array and the array is empty.

https://gist.github.com/bbarry/03caf16580a747c819df/revisions?diff=split

That is the full IL diff for this change in the only test in the master branch that hits a breakpoint in that added code: `CodeGenExprLambdaTests.MethodCallWithParams` (the test still passes). 

It looks like the method for [`Expression.NewArrayInit`](https://msdn.microsoft.com/en-us/library/system.linq.expressions.expression.newarrayinit%28v=vs.110%29.aspx) has a `params ...[]` parameter and no overload without (to avoid those allocations). The same is true for [`Lambda`](https://msdn.microsoft.com/en-us/library/system.linq.expressions.expression.lambda%28v=vs.110%29.aspx) so the change described here uses `Array.Empty<>` for those calls instead of `new T[0]`. I count 47 such cases on `System.Linq.Expressions.Expression` but I don't think all of them can be generated by the compiler.

**Comment by jaredpar** [comment]
It looks like htis would change the structure of expression trees.  That's been a very fragile area for us.  Even simple changes have caused breaks in components that used them.  I would be very hesistant to change them intentionally given the problems we've seen.

**Comment by bartdesmet** [comment]
The structure of the resulting tree will be identical. It's just the Expression[] passed into the factory methods that would change from seeing unique new Expression[0] instances to seeing the same instance each time. Under any circumstance those will be turned into a singleton empty ReadOnlyCollection<Expression> by the factory's call to a ToReadOnly helper method which turns every empty collection into that singleton instance. That instance is what ends up in the field backing publicly accessible properties on Expression nodes. Any original reference for collections passed in to those factories does not survive to the resulting nodes because of ToReadOnly's behavior.

To be clear, this does *not* change the quoted representation of new T[0] in an expression tree. In fact, the params optimization is explicitly suppressed in the quotation logic for MethodCallExpression. It's *only* changing the way the Expression factory methods get called by the emitted code.

E.g. for a x.ToString() call in an expression tree, the compiler now generates Expression.Call(xExpr, toStringMethod, new Expression[0]). The last parameter would change to Array.Empty<Expression>().

In the following:


var m1 = Expression.Call(xExpr, toStringMethod, new Expression[0]);
var m2 = Expression.Call(xExpr, toStringMethod, Array.Empty<Expression>());
Debug.Assert(object.ReferenceEqual(m1.Arguments, m2.Arguments));

succeeds because of the mentioned factory behavior.

**Comment by bartdesmet** [comment]
(Posting from my phone, looks like some angle brackets got dropped.)

**Comment by jaredpar** [comment]
Okay I think I understand the issue a bit better now.  Expression trees are still a bit out of my area though so will leave @VSadov make the call here.

**Comment by VSadov** [comment]
Seems like a viable optimization roughly equivalent to the optimization that we do when calling with empty params.
