### ISSUE TITLE
CSC.RSP reference lines produce error

### ISSUE THREAD

**Issue by mak3nsh1** [dotnet/roslyn#67590]
**Version Used**: 

**Steps to Reproduce**:

1. Copy CSC.rsp into unity
2. Compile 
3. Receives error because of the whitespace in rsc.

**Step to Resolve**:
Comment lines start with #
# Reference the common Framework libraries

Needs to be:
#'Reference the common Framework libraries'

Why:
This throws an error for each word in the sentence.
![2023-03-30 23_49_05-SysInfoU - Loadingscreen - Windows, Mac, Linux - Unity 2021 3 18f1 Personal _DX1](https://user-images.githubusercontent.com/30743697/229025421-771e1e96-4387-4dcc-9859-2783ef36be8d.png)

**Comment by jcouv** [comment]
@mak3nsh1 It is hard for me to evaluate whether this is a bug without more information. 
My guess from your description is that it starts with or contains "#Reference the common Framework libraries" which the compiler is unable to parse or recover from smartly, so this results in multiple errors reported. 
Let me know if that's not the case.
If that's the case, that line must be removed and I'm not sure how this is a compiler bug. 

Is your request that the compiler should produce one error instead of multiples? I'm not sure on what grounds we would justify that design (the compiler would have to treat `#` specially in the `.rsp` file, but I'm not sure there's a good reason to do that).

**Comment by mak3nsh1** [comment]
You are correct that depending on the compiler it might not parse the lines
appropriately at the top.  For this, ensuring the comment is truly
commented (correct syntax) is required or one deletes that out of the
header of the CSC.RSP

**Comment by jcouv** [comment]
Your response confirms that the `.rsp` file used incorrect syntax and thus the compiler is justified in producing an error. Given the question is only whether to give one error or multiple, but I believe the current behavior is correct, I will close this as by-design.
