### ISSUE TITLE
Support "remove unused references/packages" 

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#6763]
Before VS2015, VB suppported a "Remove unused references" button in it's property pages, but that was never implemented as part of Roslyn.

Reported in http://connect.microsoft.com/VisualStudio/feedback/details/2005014/unused-references-button-missing-from-visual-studio-2015 and internal bug 163717.

User Scenario
Users should be able to

see unused assemblies, packages, and project references
remove unused references
Design

  1.	#37768 The compiler team will provide an API to list used references in the compilation (or the same: unused references in the compilation). These are individual assembly references.

  2.	https://github.com/dotnet/sdk/issues/10414 The build team will generate a file with a map of assemblies, packages which can be checked for usage/non-usage. MS Build will generated the file. If other environments are used, they have to provide this file on their own.

  3.	dotnet/project-system#5258 The project-system team will provide an API for fixing issues.

  4.	#37769 The IDE team will look for both the compiler API, the file generated and the project-system API, and provide an analyzer with a fixer that will report references which can be removed.

  5.	The project-system team will help with driving UI implementation. It can be grey out references with actions in the context menu or a special user control like one described below. This can be decided later based on restrictions found on previous steps.

**UX Model**
The functionality should be available in the Solution Explorer. In an ideal case, we should grey out unused references directly in the Solution Explorer (https://github.com/dotnet/project-system/issues/76) and add an option in the context menu to remove them. If this is not available e.g. due to performance reasons, please see the UX model below.

Here is the UX model in case if we cannot arrange this directly in the Solution Explorer:

1. In the Solution Explorer right click on either a project, a solution or the References node of a project.

2. Have 2 of the following options:
     A. Right-click the selection and choose an option to Remove Unused References in the context menu.
     B. Or a keyboard shortcut to Remove Unused References.

3. When selecting Remove Unused References have a dialogue that displays all references that have no actual usages in source code in a tree view grouped by projects. By default, all references are selected for deletion. If necessary, deselect references that you want to keep.

![image](https://user-images.githubusercontent.com/12449387/62799910-de5cdf80-ba96-11e9-9518-aa55c6da8e28.png)

Then select update to remove the unused references/nuget packages.

**Comment by alrz** [comment]
Would this also uninstall corresponding nuget packages?

**Comment by Pilchie** [comment]
Well, as implemented in VS2013 and before it did not, but I think if we were going to bring the feature back we would want it to understand NuGet.

**Comment by carlcom** [comment]
I am in messy reference hell. This feature is long overdue.

**Comment by Korporal** [comment]
@Pilchie - Me too...https://github.com/dotnet/roslyn/issues/21672

**Comment by kendrahavens** [comment]
Additional external ask: https://developercommunity.visualstudio.com/content/idea/540381/add-c-project-feature-to-remove-unused-references.html

**Comment by alrz** [comment]
this would be extremely helpful with moving 
to aspnetcore 3 - it is mostly about package references..

**Comment by davidhjones** [comment]
Currently moving to .netcore3. This would be extremely helpful. Any update?

**Comment by ChristophWeigert** [comment]
Any update on this one?

**Comment by TheMrAnderson** [comment]
Any update?  Devs shouldn't have to pay for ReSharper to get this functionality and face the performance hit that entails.  This has been open for 5 years.  Come on already.

**Comment by tuzumkuru** [comment]
Is there any update? Is this such a hard thing to develop?

**Comment by sercanparan** [comment]
I totally agree with @TheMrAnderson. Can't wait to hear from @JoeRobich soon. :)

**Comment by JoeRobich** [comment]
Well, since everyone is asking about it, this feature is in active development. So far, the Compiler team has completed their necessary work, the Project System team is getting in the last of their changes, and I have begun implementation of the analysis. After that will be UI work to display this information and allow the removal of references. So, we are seeing the light at the end of the tunnel for this feature.

**Comment by kpranavk** [comment]
I am sooo much waiting for this feature as well :) I think of this every day and wish it was already there by now. I have installed Resharper so many times for this specific feature and uninstalled for other performance reasons.

**Comment by malcolmrs** [comment]
Any updates in this? Waiting eagerly

**Comment by CyrusNajmabadi** [comment]
It's still being worked on.

**Comment by DennyOne** [comment]
Hi, thanks for working on the Remove Unused References feature! 

I used to use it in VB projects all the time and would like very much to see it in C#.  I just installed 16.10.0 Preview 1 and made sure the option to show it is on; however, there is no menu item for this in the Project or References node context menus. This is a .NET Framework 4.8 project. 

Thanks!

**Comment by ahdung** [comment]
hope it for multiple targets sdk project.

**Comment by Varorbc** [comment]
Is it possible to remove duplicate dependency packages?

**Comment by jasonmalinowski** [comment]
@mikadumont @JoeRobich Should this be closed now?

**Comment by JoeRobich** [comment]
Thanks @jasonmalinowski! Enhancements are being tracked in https://github.com/dotnet/roslyn/issues/50054

**Comment by DennyOne** [comment]
It looks like it is in .Net6 projects but not .Net Framework 4.8 projects. If this is important enough, you can leave it open; otherwise you can close it. Please see images below, Thanks!
_____

Visual Studio 2019 (Version **16.11.18**) / .Net Framework 4.8 project / Solution Project menu
![image](https://user-images.githubusercontent.com/65730742/189215339-0b1ae14c-9c3c-4650-b188-78a6cfeadf91.png)

Visual Studio 2022 (Version **17.3.3**) / .Net Framework 4.8 project / Solution Project menu
![image](https://user-images.githubusercontent.com/65730742/189212861-52bbf440-439c-43b1-9fd2-0614aabd67e3.png)

Visual Studio 2022 Preview (Version **17.4.0**) / .Net Framework 4.8 project / Solution Project menu
![image](https://user-images.githubusercontent.com/65730742/189213566-df3f6421-5c42-40b8-a1a8-8d2e58811158.png)
_____

Visual Studio 2019 (Version **16.11.18**) / .Net Framework 4.8 project / References menu
![image](https://user-images.githubusercontent.com/65730742/189214664-0bbbcfae-6124-47eb-ad2e-4ef6d9ecd686.png)

Visual Studio 2022 (Version **17.3.3**) / .Net Framework 4.8 project / References menu
![image](https://user-images.githubusercontent.com/65730742/189213278-0c1e3b5e-0226-451d-943f-ac7d55a3f562.png)

Visual Studio 2022 Preview (Version **17.4.0**) / .Net Framework 4.8 project / References menu
![image](https://user-images.githubusercontent.com/65730742/189213695-c3ce3e6a-1c4b-4a22-ba48-c9b5c115b8f3.png)
_____

Visual Studio 2022 (Version **17.3.3**) / .Net6 SDK project / Solution Project menu
![image](https://user-images.githubusercontent.com/65730742/189211169-e192c67d-acf3-4431-a4cd-a07dca109217.png)

Visual Studio 2022 Preview (Version **17.4.0**) / .Net6 SDK project / Solution Project menu
![image](https://user-images.githubusercontent.com/65730742/189211657-d3508de2-7272-4afc-a566-ce4dce002ef5.png)
_____

Visual Studio 2022 (Version **17.3.3**) / .Net6 SDK project / Dependencies menu
![image](https://user-images.githubusercontent.com/65730742/189211247-a75a7bf7-ea91-4703-9217-5e33ac9e4c0b.png)

Visual Studio 2022 Preview (Version **17.4.0**) / .Net6 SDK project / Dependencies menu
![image](https://user-images.githubusercontent.com/65730742/189211762-b6791e41-cf14-422b-8ef4-359e3ff5f755.png)

**Comment by DennyOne** [comment]
Sorry, you closed it while I was preparing the comment!

**Comment by JoeRobich** [comment]
Hi @DennyOne, the enhancement to support .NET Framework projects is tracked in https://github.com/dotnet/roslyn/issues/54801.

**Comment by malcolmrs** [comment]
Why am I on this ticket?
________________________________
