### ISSUE TITLE
Colors are inconsistent for types with "alias to any type"

### ISSUE THREAD

**Issue by KathleenDollard** [dotnet/roslyn#67641]
**Version Used**: 

**Steps to Reproduce**:

Paste this code into VS:

```c#
using TupleExample = (string, int);
using ArrayExample = int[];
using NullableInt = int?;
using S1 = string;
using NeverUse = dynamic;
```

**Diagnostic Id**: None

**Expected Behavior**:

All of the alias types are the same color.

**Actual Behavior**:

![aliasbug3](https://user-images.githubusercontent.com/5844318/229912970-79036cbd-2e6f-42fb-bab9-4bfd4d886d3e.png)

**Comment by tmat** [comment]
This is a bit inconsistent:
![image](https://user-images.githubusercontent.com/41759/229915324-a1b4fc1a-bba5-4f6f-8468-4c485be38024.png)

**Comment by CyrusNajmabadi** [comment]
keyword takes precedence if htere, otherwise you get the user-type classification (Reference type for the latter).  'Dynamic' is its own type and has no classification optino to specify what you want for it.  So it gets keyword.

If someone wants to add a classification for it, that might be ok. But it would def be on the backlog.
