### ISSUE TITLE
Switch statement population should be available as a refactoring (not just as a snippet function)

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#6766]
If you have the following in a method:
```C#
System.ConsoleModifiers c = default(System.ConsoleModifiers);
```
And on the next line you type ```switch<tab><tab>c<enter><enter>```, the snippet function auto-populates the switch body with all cases.

This same functionality should be available in a refactoring (many people don't know about the snippet function, and it can only be used upon creation).

**Comment by dpoeschl** [comment]
This request came up in a conversation with @mattwar

**Comment by bbarry** [comment]
When the following conditions are met:

* editor caret is inside a *switch-block* 
* the switch statement expression has an `enum` type NOT marked by a `[Flags]` attribute
* the switch statement does not have any errors
* the `default` label or at least one `case` label is missing from the set representing the `enum` type

A Quick Action "Generate Missing Switch Labels" should be available. This action will generate *switch-sections* containing a *switch-label* followed by the statement `break;` and will append these sections to the *switch-block*.

After the action, the caret will be placed after the colon of the first generated *switch-label*. 

### Examples:

All examples use the following `enum` type:

    enum A { A1, A2, A3, A4 };

Example 1. Empty *switch-body*. Before:

    switch (e) 
    { }

after:

    switch (e)
    {
        case A.A1:|
            break;
        case A.A2:
            break;
        case A.A3:
            break;
        case A.A4:
            break;
        default:
            break;
    }

Example 2. missing sections, has no `default:` section. Before:

    switch (e)
    {
        case A.A2:
            break;
        case A.A3:
            break;
        case A.A4:
            break;
    }

After:

    switch (e)
    {
        case A.A2:
            break;
        case A.A3:
            break;
        case A.A4:
            break;
        case A.A1:|
            break;
        default:
            break;
    }

Example 3: has `default:`, has labels not separated from `default:` by `break;`. Before:

    switch (e)
    {
        case A.A4:
        case A.A1:
        default:
            break;
    }

After:

    switch (e)
    {
        case A.A4:
        case A.A1:
        default:
            break;
        case A.A2:|
            break;
        case A.A3:
            break;
    }

----

When determining if the action is available, it is sufficient to count the number of switch labels to determine if any are missing. This number should always be one more than the number of items in the enum (one for each item + `default:`).

I think it is important to generate these sections together in one span inside the *switch-block*. Perhaps another action would be useful to reorder switch blocks based on the order they are listed in the enum, though an interface similar to the one used for Change Signature may be better.

**Comment by Giftednewt** [comment]
While I agree in the most part with the example I think it would feel more natural if this was surfaced as a warning and the squigqlies showed up on the IdentifierName ```e```. Then the code action could be invoked from there rather than having to put the caret within the switch block to get the refactoring. The warning could then also be treated as an error if the user has this option set. This would help to prevent cases where you are using a library outside of your control where the enumeration has new values added and you don't realise.

Also I think that determining whether the action is available just from the number of switch labels would cause issues. Take the following for example:

```csharp
switch (e)
{
    case A.A1:
    case A.A2:
        break;
    case A.A4:
        break;
    case (A)5:
        break;
    default:
        break;
}
```
This compiles and runs fine due to the fact that the enum defined in the example is using the default underlying type of int. So by counting the total number of labels in the switch it would cause the action to never show. The refactoring should look for values in the enumeration where no case label exists.

There could also potentially be a separate refactoring for case labels such as :
```csharp
case (A)5:
```
where an enumeration value has been introduced (due to updating an external library) with which the label could be refactored to:
```csharp
case A.A5:
```

**Comment by bbarry** [comment]
I don't think it can be made a warning because that could break user code (maybe an excuse could be made as part of the new pattern matching functionality).

Good point on the counting not being sufficient. I hadn't realized that syntax was valid. Unfortunately that means the implementation has to enumerate over the switch labels and compare them to the enum in all cases where `count(switch labels) > count(enum identifiers)`.

**Comment by Giftednewt** [comment]
I get what you mean about the warning potentially "breaking" user code, but the argument could also be made that the user code is already broken if it's not handling all cases (especially if a default label doesn't exist).

Yes this would need to enumerate the case labels. I think it would need to happen in all cases not just where ```count(switch labels) > count(enum identifiers)``` otherwise the following wouldn't cause the refactoring to be shown
```csharp
switch (e)
{
    case A1:
    case A2:
    case A3:
        break;
    default:
        break;
}
```

And this would (but shouldn't)
```csharp
switch (e)
{
    case A1:
    case A2:
    case A3:
        break;
    case A4:
        break;
    default:
        break;
}
```
Also, this would only need to happen if the identifier was an enum without the flags attribute and in my experience the most common uses of enums tend represent a small set of values (though I have seen ones with 30+ identifiers) so the performance cost may not be that great.

**Comment by bbarry** [comment]
I meant you need to enumerate to determine if the code fix applies in that case (it always applies if there are fewer labels than identifiers). It is fairly important in these actions to short circuit computations where possible because eventually they directly impact the user experience. 

I've updated https://github.com/dotnet/roslyn/issues/6766#issuecomment-156878851

**Comment by Giftednewt** [comment]
I agree with short circuiting where possible but I'm not sure it is because of the ability to cast a value to the enum.

A short circuit would exist where zero labels exist (this is surfaced as CS1522) as, like you say it would be creating cases for all the declared values and one for the default label. So this will always return the action.

When one or more switch sections exist it's going to have to check them. It'll have to iterate all sections and then all labels in the section. If at the start a list was primed with all declared enum values removing them from the list as they are found it could short circuit when the list is empty and a default label has been found. This short circuit would not cause a code action to show.

If it makes it out of the section loop you cam be certain that it's going to be showing a code action.

If nobody has any objections I'll put something together along these lines and we can look at potential optimizations then.

**Comment by bbarry** [comment]
Go for it :+1:

**Comment by Pilchie** [comment]
I like the idea of it being invokable from inside the switch's expression as well.  We certainly won't make this a new warning reported by the compiler for compat reasons.  We probably wouldn't make it a warning in the IDE (at least by default) either, for similar compat reasons, but it should be configurable via a ruleset if you want it too.  (I believe there is already a stylecop rule for the case where you don't handle all possible values - @sharwell probably knows :smile:)

**Comment by sharwell** [comment]
@Pilchie This type of semantic analysis is beyond the scope of StyleCop. I wouldn't be surprised to see it as a future FxCop rule.

**Comment by Pilchie** [comment]
I'm sure I've seen this rule in some existing static analysis already, but I forget which one.

**Comment by Giftednewt** [comment]
pretty sure I've seen it in resharper

**Comment by Pilchie** [comment]
That wouldn't be it, as I'm not a R# user.

**Comment by Giftednewt** [comment]
Is there a way that I can set the caret position within a Code fix that is applied?

**Comment by Hosch250** [comment]
I am working on this issue.  If you have any comments or edge cases in addition to the ones above, please let me know.

**Comment by Pilchie** [comment]
Tag @DustinCampbell for his opinion, about whether @Hosch250 should implement this as an analyzer+fix with default severity of Hidden, or as a CodeRefactoring.

**Comment by DustinCampbell** [comment]
I generally not in favor analyzers+fixes with hidden severity unless there is some other indication in the editor that something is available at that position (e.g. faded out code). I think a warning is totally fine. After all, the user can configure that. Later when we have #9582, we can pick something a little "lighter".

**Comment by Hosch250** [comment]
Should I place the warning span on the switch expression or over the entire switch?

**Comment by DustinCampbell** [comment]
I'd say either the switch expression on the switch keyword.

**Comment by Hosch250** [comment]
OK, thank you for the comments.
