### ISSUE TITLE
params for ValueType array

### ISSUE THREAD

**Issue by CreateAndInject** [dotnet/roslyn#67710]
```c#
class Program
{
    static void Main()
    {
        Test("1", "2", "3");
        Test(1, 2, 3);
        string[] strs = { "1", "2", "3" };
        int[] ints = { 1, 2, 3 };
        Test(strs);
        Test(ints);
        Console.ReadKey();
    }

    public static void Test(params object[] args)
    {
        Console.WriteLine(args.Length + " : " + string.Concat(args));
    }
}
```

Output:
```
3 : 123
3 : 123
3 : 123
1 : System.Int32[]
```

Bug or expected?

**Comment by svick** [comment]
This is expected. `string[]` is convertible to `object[]`, thanks to array covariance. But that only works for reference types, which is why `int[]` is not convertible to `object[]`. `int[]` is still convertible to `object`, so it's interpreted as the `params object` argument, not as a `object[]` argument.

**Comment by CreateAndInject** [comment]
But why `ValueType[]` isn't convertible to `object[]` by design like `ReferenceType[]`?

**Comment by CyrusNajmabadi** [comment]
Because they have different representations in memory. Say you have an int[], that's an array of 32bit integers. If you have a reftype[] then that's an array of pointers.
