### ISSUE TITLE
Unable to sort `global using` directives using type aliases

### ISSUE THREAD

**Issue by SunnieShine** [dotnet/roslyn#67768]
**Version Used**: 

VS 17.6p3

**Steps to Reproduce**:

```csharp
global using AliasType = int;
global using AnotherAliasType = delegate*<void>;
```

**Expected Behavior**:

Click "Remove and sort usings" command, using directives will be sorted.

**Actual Behavior**:

No matter what order of any type aliases, they cannot be sorted.

Case 1:

```csharp
global using AliasType = int;
global using AnotherAliasType = delegate*<void>;
```

Case 2:

```csharp
global using AnotherAliasType = delegate*<void>;
global using AliasType = int;
```

Both cases cannot be sorted.

**Comment by nih0n** [comment]
I added a unit test for this case at [OrganizeUsingsTests](https://github.com/dotnet/roslyn/blob/903a8421c195bb71c8a112e82a5a756bb0f0c8f5/src/Workspaces/CSharpTest/OrganizeImports/OrganizeUsingsTests.cs) and its passing

```csharp
[Fact]
public async Task TypeAliases()
{
    var initial =
@"using AnotherAliasType = delegate*<void>;
using AliasType = int;";

    var final =
@"using AliasType = int;
using AnotherAliasType = delegate*<void>;
";

    await CheckAsync(initial, final);
}
```

The `IOrganizeImportsService` is working fine, maybe the bug is somewhere else.

**Comment by SunnieShine** [comment]
Close this issue as solved.
