### ISSUE TITLE
Wiki is outdated

### ISSUE THREAD

**Issue by pjt33** [dotnet/roslyn#6795]
https://github.com/dotnet/roslyn/wiki/Samples-and-Walkthroughs says that the samples include

> - **AsyncPackage** - A set of diagnostics and code fixes that help you use the await/async keywords correctly.

I haven't done a full bisection, but this sample disappeared somewhere between the tag [toolset_2](https://github.com/dotnet/roslyn/tree/toolset_2/src/Samples/CSharp/AsyncPackage) and the tag [toolset_3](https://github.com/dotnet/roslyn/tree/toolset_3/src/Samples/CSharp/AsyncPackage).

It would be helpful to update the wiki page to either point at a suitable tag / branch / commit for people who want this sample or to remove the mention entirely.

**Comment by davkean** [comment]
@jmarolf?

**Comment by chaitanyagurrapu** [comment]
Another outdated instruction. Step 8 of this walk through https://github.com/dotnet/roslyn/wiki/Getting-Started-C%23-Semantic-Analysis has the following instructions ...

![image](https://cloud.githubusercontent.com/assets/853059/11323048/31bf542c-9152-11e5-903c-b14d3f068d2d.png)

Which doesn't work as we are passing in a string where an assembly is expected
![image](https://cloud.githubusercontent.com/assets/853059/11323072/2afb40c8-9153-11e5-90ce-b11776fb5973.png)


But passing in an assembly doesn't work either as this method has since been obsoleted.

![image](https://cloud.githubusercontent.com/assets/853059/11323079/48b1c4a2-9153-11e5-9e5d-923f67e4dd01.png)

The correct way seems to be 

![image](https://cloud.githubusercontent.com/assets/853059/11323084/58e436f2-9153-11e5-88a8-dbbc717f1f9f.png)


The downside of putting all this documentation in the Wiki is that the community cannot send pull requests to update it or suggest improvements. Perhaps the team should consider using the gh-pages feature of github for the documentation .

**Comment by jmarolf** [comment]
Issue moved to [dotnet/roslyn-sdk #47](https://github.com/dotnet/roslyn-sdk/issues/47) via [**ZenHub**](https://www.zenhub.com/)
