### ISSUE TITLE
Checksum's usage of a native hash algorithm resulting in thread starvation

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#67995]
**Version Used**: 
Investigating thread starvation in Speedometer's CopyRichNotAccurate, I see Checksum's usage of CAPI SHA256 hash algorithm is one of the cause of the starvations. It appears the following code path instantiates large number of finalizable objects (ie the underlying SafeHandle) on multiple threads at the same in a short burst. This hits a lock in the CLR's CFinalize::RegisterForFinalization causing contention and resulting in a lot of blocked time on the thread pool, 10% of the blocked time on these threads is this bug.

**Steps to Reproduce**:
1. Download trace from any run of Speedometer's CopyRichNotAccurate tests (ask me offline for how to do this)
2. Look at blocked time via Thread Time Stacks under CFinalize::RegisterForFinalization.
<img width="662" alt="image" src="https://user-images.githubusercontent.com/1103906/234774177-fb6aa74a-a37e-42d7-adbd-5e4a9dc7c649.png">

I had a look at SHA265Cng and it has a similar path so is likely not the path forward. Maybe the managed version of the algorithm? Or alternative, a customer wrapper around CNG that avoids creating a finalizable safe handle over and over again?

**Comment by CyrusNajmabadi** [comment]
@stephentoub any suggestions on a good way to utilize this api while avoiding this problem?

**Comment by stephentoub** [comment]
On .NET 5+ you can use the one-shot methods... zero allocation (finalizable or otherwise):
<img width="889" alt="image" src="https://user-images.githubusercontent.com/2642209/234882476-688e0f88-dd43-4737-9071-b7d797f08963.png">
These are the way to go when targeting .NET 5+ surface area.

If you're stuck on .NET Framework, you can at least use SHA256.Create(), which unless FIPS is enabled will create a SHA256Managed instance and, while there will be a lot of allocation:
<img width="745" alt="image" src="https://user-images.githubusercontent.com/2642209/234885879-4008bb54-4ec2-4b63-af97-8ea54a22df9e.png">
I don't believe any of it will be finalizable (though I'd need to check).

It looks like IncrementalHash is being used by Roslyn.  IncrementalHash is just a thin wrapper around the underlying HashAlgorithm instance, so you could just do what it does manually with your SHA256 instance: each time you use it for a new operation, call Initialize; call TransformBlock for each block of data (with a null output), and then when you want the result call TransformFinalBlock with an empty array and access the resulting Hash.

**Comment by sharwell** [comment]
@CyrusNajmabadi Sounds like `RoslynIncrementalHash` is about to exist. :)
