### ISSUE TITLE
Jenkins hudson null pointer exception

### ISSUE THREAD

**Issue by TyOverby** [dotnet/roslyn#6801]
PR: [#376](https://github.com/dotnet/roslyn-internal/pull/376) *Change order of setting allGreen on test failure. Add more monitoring.* by @TyOverby
Failure: http://dotnet-ci.cloudapp.net/job/roslyn-internal_prtest_win_vsi_p0/31/

**Comment by TyOverby** [comment]
@dotnet/roslyn-infrastructure

**Comment by davkean** [comment]
@mmitche Have you seen this before?

**Comment by mmitche** [comment]
@davkean I think this is a bug.  https://github.com/jenkinsci/git-plugin/blob/master/src/main/java/hudson/plugins/git/extensions/impl/SubmoduleOption.java.  I think this actually line 89 now not 82.  Anyways I think this is a "first time build" (maybe because settings changed, indicated by "First time build. Skipping changelog." in the log, lastBuild is null and causes the NPE.  My guess is that this doesn't repro in the normal case because there aren't submodules, and I'm guessing it won't repro on a rerun.  I'll report it.

**Comment by TyOverby** [comment]
This is happening on every single build that I try to kick off.
http://dotnet-ci.cloudapp.net/job/roslyn-internal_prtest_win_vsi_p0/33/consoleFull#-189703977632a17391-2a49-433b-8c56-ce15b905a2b5

**Comment by mmitche** [comment]
Working on a fix.  Any idea what might have changed to cause this to start to fail?

**Comment by davkean** [comment]
Your guess is as good as ours

**Comment by mmitche** [comment]
@davkean @TyOverby They accepted and saw the potential NPE in the code, so they'll fix it in the next release.  For now I put in what I think might be the right fix and the system is restarting now.

**Comment by mmitche** [comment]
@TyOverby Can you retest and see what happens, at the very least it shouldn't NPE now, though I'm not totally positive whether my fix was correct.

**Comment by TyOverby** [comment]
@mmitche Restarting now

**Comment by TyOverby** [comment]
@mmitche Looks like it worked!  Thanks!
