### ISSUE TITLE
Type of range variable cannot be determined if the query statement is incomplete

### ISSUE THREAD

**Issue by jhinder** [dotnet/roslyn#68032]
**Version Used**: VS 17.6 P5

**Steps to Reproduce**:
1. Open the completion list at the marked location and type "x". Look at the tooltip.
2. Open Quick Info for the `x` identifier token you just typed.
3. Uncomment the `let` line and repeat step 1 after the equals token.

```csharp
class C
{
    void M()
    {
        _ = from x in new int[0]
//          let y = 
            select $$;
    }
}
```

**Expected Behavior**:
The type can always be determined.

**Actual Behavior**:
1. The type cannot be determined, leading to a question mark being displayed for the type: "(range variable) ? x"
2. The type can be determined and it is displayed in the tooltip: "(range variable) int x"
3. The type cannot be determined, like 1.

**Notes**:
It appears that the type cannot be determined [in `SymbolDisplayVisitor.GetRangeVariableType()`](https://github.com/dotnet/roslyn/blob/550609c7774812e009a6aaf1e7fef8df24e5b0c2/src/Compilers/CSharp/Portable/SymbolDisplay/SymbolDisplayVisitor_Minimal.cs#L219) because the query body cannot be found: `token` is the semicolon token (in case 1) or the equals token (in case 3), and in both cases `GetQueryBody()` returns `null`. In addition the token's parent is not an `IdentifierNameSyntax` in either case, so the type cannot be determined via that branch.

**Comment by jcouv** [comment]
LINQ queries are processed as a syntactic rewriting (detailed [here](https://github.com/dotnet/csharpstandard/blob/draft-v7/standard/expressions.md#122035-from-let-where-join-and-orderby-clauses)). This results in a series of chained calls, such as `. Select ( x => new { x , y = ... } )` for `from x in e let y = ...`. In a series of chained calls such as `e.Select(...).Select(...)`, we can't bind the second `.Select` when the first one has an error, because we don't know the type of the receiver.
I don't think we'll be able to improve this.
