### ISSUE TITLE
Allow features to take ownership of the workspace and deny external changes

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#681]
Specific instances where we want to suppress the lightbulb (and probably other workspace features):
- Inline Rename
- Debugging (but not broken into)

**Comment by shyamnamboodiripad** [comment]
This issue specifically mentions rename. However, the workspace ownership is a general problem in other scenarios too. For example, when a debug session is active but code is not at a breakpoint we have similar problem where light bulb offers fixes - but fixes silently fail because workspace refuses to apply the changes in this mode. If we had a mechanism to track workspace ownership, then we could just hide the light bulb in such cases / at least avoid failing silently (we could say that debugger owns the workspace and hence a fix can't modify it).

It would be good to add such mechanism to track workspace ownership (light bulb would be one consumer of this mechanism - but there could be others too).

**Comment by shyamnamboodiripad** [comment]
Thank you @dpoeschl

**Comment by CyrusNajmabadi** [comment]
Not planning on doing anything here absent a strong customer ask, and very clear semantics on how this would work.
