### ISSUE TITLE
CDATA Block is not formatter correctly in VS

### ISSUE THREAD

**Issue by arkalyanms** [dotnet/roslyn#68134]
Copied from https://github.com/dotnet/SqlClient/issues/2013#issue-1676512366

The function descriprion includes a comment CDATA block is not completely formatted in Visual Studio. I mean the XREF hyperlink, it stil visible in popup...

Will it be fixed?

see attached image
![image](https://user-images.githubusercontent.com/60013978/236952460-6294dab7-677a-4d68-8d35-0416d59df10c.png)
![image](https://user-images.githubusercontent.com/60013978/236952504-f0afab27-0d30-46fe-a171-be4129445e70.png)

**Comment by svick** [comment]
I don't think this is a problem with Roslyn. The XML documentation file inside the Microsoft.Data.SqlClient package contains DocFx markdown, which it really shouldn't. And since this looks like a package authoring problem, I think this issue should be closed and https://github.com/dotnet/SqlClient/issues/2013 should be reopened.

**Comment by sharwell** [comment]
Roslyn appears to be formatting the block correctly (in accordance with the syntax written for this type). I'll follow up on the original issue.
