### ISSUE TITLE
Source Generators support AddSource with SyntaxNode for possible future perf improvements

### ISSUE THREAD

**Issue by Khitiara** [dotnet/roslyn#68155]
## Background and Motivation

Source generators should support adding source from a `SyntaxNode` instead of string source.
This would permit skipping the re-parsing of generated source text during compilation, allowing for optimization.

## Proposed API
```diff
namespace Microsoft.CodeAnalysis
{
    public readonly struct SourceProductionContext
    {
+      public void AddSource(string hint, SyntaxNode source);
    }

    public readonly struct GeneratorExecutionContext
    {
+      public void AddSource(string hint, SyntaxNode source);
    }
}
```

## Usage Examples

``` C#
var tree = SyntaxFactory.FileScopedNamespaceDeclaration(SyntaxFactory.ParseName("TexelFormats"))
			.AddUsings(GenUsings().Select(s => SyntaxFactory.UsingDirective(SyntaxFactory.ParseName(s))).ToArray())
			.AddMembers(SyntaxFactory.ClassDeclaration("TexelFormat")
				.AddModifiers(SyntaxFactory.Token(SyntaxKind.PartialKeyword))
				.AddMembers(GenEntries().ToArray())).NormalizeWhitespace();
// new method
context.AddSource("New.cs", tree);

// old method
context.AddSource("Old.cs", tree.ToFullString());
```

## Alternative Designs

I am unsure if there is a clean way to work this into `SourceText` instead of passing a `SyntaxNode` directly

## Risks

Depending on implementation, this new API might not provide performance improvement at first (the trivial implementation is to call `ToFullString()` and pass through to the existing string-based API), but I believe it to be worthwhile for the possibility of future performance improvements

**Comment by CyrusNajmabadi** [comment]
> Source generators should support adding source from a SyntaxNode instead of string source.
This would permit skipping the re-parsing of generated source text during compilation, allowing for optimization.

We would still have to convert this node to text, and then reparse.  That's because SyntaxNodes can represent illegal states (and specifically different results than what the parser would produce).  This breaks a core design goal that if you emit your SG file to disk, and then want to use that in the future, that you get the same results.

Examples of where this doesn't work:

```c#
classC{}
```

Can be a generated as a legal class node just using syntax, but would be illegal as per the parser.

However, worse case is:

```c#
class C
{
    void M()
    {
        CorrectMethodToCall();
    }
    
    void CorrectMethodToCall() {}
    void IncorrectMethodToCall(){}
```

The SyntaxNode, when emitted to source would be the above, but in memory could actually have a call to 'IncorrectMethodToCall' (nothing ensures that an identifiers 'Value' matches its 'Text').

this is why Syntax is only acceptable as an intermediary value, but that it always must go through raw-text so we can be sure that the final tree is exactly what hte user would get if htey parsed themselves.
