### ISSUE TITLE
VS 2022 constantly complains about inconsistent line ends

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#68236]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VS-2022-constantly-complains-about-incon/10347656)._

---
[severity:It bothers me. A fix would be nice]
I'm only editing Visual Studio code files on one Windows machine with one version of Visual Studio. 
However after adding new class files or moving them to another folder when opening them the next time, Visual Studio complains that the file contains inconsistent line endings, thus somehow VS introduces Lf instead of CrLf in some places for some weird reason

---
#### Feedback Bot on 4/25/2023, 03:47 AM: 

(private comment, text removed)
#### Sam Harwell [MSFT] on 4/25/2023, 08:13 AM: 

(private comment, text removed)
#### SchramKa on 5/9/2023, 08:48 AM: 

It appears that one way where it happened was when I took the call to the base constructor and pressed Enter before the colon. The new line ends in Lf instead of CrLf

![image](https://github.com/dotnet/roslyn/assets/1408396/5ca4f351-426b-49ff-9b5a-4203ac1478f3)

(private comment, text removed)
#### Feedback Bot on 5/12/2023, 11:25 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by karsten-schramm** [comment]
It also happens when you insert the `ctor` snippet:

![image](https://github.com/dotnet/roslyn/assets/144887725/6ac0fd30-0be2-40a3-9d71-5cc0a62f2f56)

then

![image](https://github.com/dotnet/roslyn/assets/144887725/ad067053-78d2-4860-99c8-15c7e5b24c59)

renders:

![image](https://github.com/dotnet/roslyn/assets/144887725/414a37ab-d707-47d3-a6ef-49ccf00cab80)

BTW: Showing non-printable characters like line-breaks in VS would be helpful

Microsoft Visual Studio Professional 2022 (64-bit) - Current
Version 17.8.4

**Comment by CyrusNajmabadi** [comment]
Closing out as there was an editor bug a while back that was causing this tha thas since been fixed.
