### ISSUE TITLE
MyJsonContext need implete GetTypeInfo

### ISSUE THREAD

**Issue by lozn00** [dotnet/roslyn#68245]
mycode
```
   [JsonSourceGenerationOptions(GenerationMode = JsonSourceGenerationMode.Serialization)]
    [JsonSerializable(typeof(JSONResultInfo))]
    [JsonSerializable(typeof(System.Object))]
    [JsonSerializable(typeof(Newtonsoft.Json.Linq.JObject))]
    [JsonSerializable(typeof(System.Boolean))]
    [JsonSerializable(typeof(VersionModel))]
    [JsonSerializable(typeof(VersionModel[]))]
    [JsonSerializable(typeof(System.Collections.Generic.Dictionary<System.String, System.String>))]
      internal partial class MyJsonContext : JsonSerializerContext
    {
    }
```

use 7.0 compile 
```
 “MyJsonContext”不实现继承的抽象成员“JsonSerializerContext.GetTypeInfo(Type)”
1\MyJsonContext.cs(24,30,24,43): error CS0534: “MyJsonContext”不实现继承的抽象成员“JsonSerializerContext.GeneratedSerializerOptions.get”
```

**Comment by ericstj** [comment]
Credit to @rainersigwald for find the root cause of this in https://github.com/dotnet/msbuild/pull/8674#issuecomment-1552134099

Problem is due to https://github.com/dotnet/roslyn/commit/cf29abef6cb865f2f55572ec658733e9545cc485#diff-1ea18ff65faa2ae6fed570b83747086d0317f5e4bc325064f6c14319a9c4ff67L297-R302

However the host process is missing a bindingRedirect for this 7.0.0.0 - probably still at 6.0.0.0.  I think the host could be msbuild.exe, devenv.exe, csc.exe, or vbcscompiler.exe.  Depending on which is running into this, you could modify it's config file as a workaround.

**Comment by jaredpar** [comment]
> I think the host could be msbuild.exe, devenv.exe, csc.exe, or vbcscompiler.exe. 

For the 17.6 / 7.0.3xx devenv.exe, csc and vbcscompiler all have the binding redirects for 7.0.0.

**Comment by jaredpar** [comment]
Thanks for following up with your resolution and glad you were able to work it out.
