### ISSUE TITLE
Code Cleanup Hangs When Attempting To Fix CS1998

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#68249]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Code-Cleanup-Hangs-When-Attempting-To-Fi/10337562)._

---
\[severity:It’s more difficult to complete my work\]  
Our development team is using the Code Cleanup functionality in Visual Studio. We mark the CS1998 as a warning in our .editorconfig. All of the available fixers are selected to be run in Code Cleanup.

The problem is that when there is a CS1998 issue present, Visual Studio’s Code Cleanup popup/progress hangs indefinitely and/or when it finally stops it doesn’t actually fix the CS1998 problem.

The code can be as simple as this

```  
        public override async Task DisposeAsync()
        {
        }
  
```

Additional note, after I finished my recording for this issue, all of my VS instances crashed…
[EDIT]
Sorry, VS didn't crash, they just hung for a few minutes and started being responsive again.

---
#### Feedback Bot on 4/13/2023, 06:47 AM: 

(private comment, text removed)
#### Feedback Bot on 4/17/2023, 11:24 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by mavasani** [comment]
I am able repro this huge delay by adding the above stub DisposeAsync method to LanguagerParser.cs and attempting to apply "Make method synchronous code fix". The issue seems to be that the code fix is attempting to rename the method to remove the async suffix, and this is pretty expensive for public methods in big projects/solutions.

https://github.com/dotnet/roslyn/blob/1cd0dccbde864966f39c13eefd5549acc6008a2d/src/Analyzers/Core/CodeFixes/MakeMethodSynchronous/AbstractMakeMethodSynchronousCodeFixProvider.cs#L82-L83

Should we skip the rename application from this code fixer for public methods? Another alternative is to skip it just for the Code cleanup path.

**Comment by CyrusNajmabadi** [comment]
What happens if you try to fix this outside of code cleanup?  Is it also slow?  If so, then I don't think code cleanup should behave differently. 

If we are worried about perf of code cleanup, we could take this cleanup item out of it completely.
