### ISSUE TITLE
IDE0063 doesn't identify "simple using statement" in top-level expressions

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/roslyn#68285]
**Version Used**: Version 17.7.0 Preview 2.0 [33721.22.main]

## `Program.cs`

```c#
using (var foo = new MyDisposable()) // not suggested here
{
}

class C
{
    void M()
    {
        using (var foo = new MyDisposable()) // suggested here
        {
        }
    }
}
```

I can't see a reason not to suggest it in the top-level context as well.

I'm working on a solution that has a lot of sample code, and therefore a lot of top-level statements. I want to fix up these samples to use modern patterns, and this will need to be done manually.

**Comment by kandicst** [comment]
@CyrusNajmabadi I think I was able to figure out this one, however I'm having a problem with getting the test case to pass because the I keep getting an additional newline character to the fixed code and adding a new line to an expected string causes a _CS8805: Program using top-level statements must be an executable_ which I can't seem to get around.

Could you maybe take a quick look ([fork link](https://github.com/kandicst/roslyn/commit/7a6c66919d749262036e4da72894320c4c9a8575#diff-96b2bcb09c1f14269ca79400242f45e0bfb5b95a31d673023e88f9ae4d05d421R33)) and see if you maybe spot the issue before I submit a PR for this?

**Comment by CyrusNajmabadi** [comment]
Can you ping me later this week?   Thanks!

**Comment by kandicst** [comment]
@CyrusNajmabadi ping 😄

**Comment by CyrusNajmabadi** [comment]
Not sure.  @sharwell ?  Something that @kandicst has to set up in the test harness?

**Comment by CyrusNajmabadi** [comment]
Closing out due to lacck of broad feedback on this.
