### ISSUE TITLE
IDE0060 (remove unused parameter) reported for primary constructor parameters.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#68501]
C:\github\roslyn\src\Workspaces\SharedUtilitiesAndExtensions\Compiler\Core\Options\OptionDefinition.cs(102,41): warning IDE0060: Remove unused parameter 'serializer' (https://docs.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0060) [C:\github\roslyn\src\CodeStyle\Core\Analyzers\Microsoft.CodeAnalysis.CodeStyle.csproj]

We need to address this as it immediately causes issues for trying to use primary constructors.

**Comment by CyrusNajmabadi** [comment]
Actually,  Tagging @akhera99  since this was supposed to be fixed.

**Comment by CyrusNajmabadi** [comment]
Affects this PR: https://github.com/dotnet/roslyn/pull/68299

**Comment by mavasani** [comment]
@akhera99 @CyrusNajmabadi This seems to be due to the fact that Roslyn main is on a pretty old version of CodeStyle package: https://github.com/dotnet/roslyn/blob/ac66ae2ee1db52a8c0c4ff9565752e8c0028aea2/eng/Versions.props#L26-L27

Updating to a later version of CodeStyle package would also require us bumping up the minimum VS version required to work on Roslyn, and we want to at least ensure that a public preview of that VS version is available so the community members can continue contributing. I can see at https://learn.microsoft.com/en-us/visualstudio/releases/2022/release-notes-preview that VS2022 17.7 Preview2 is the latest available preview build, which means we can safely bump up the CodeStyle package version to 4.7.0-2.final, but the latest released package on nuget.org is `[4.7.0-1.final](https://www.nuget.org/packages/Microsoft.CodeAnalysis.CSharp.CodeStyle/4.7.0-1.final). This is the feed for publishing the CodeStyle packages generated from each CI build: https://dev.azure.com/dnceng/public/_artifacts/feed/dotnet-tools/NuGet/Microsoft.CodeAnalysis.CSharp.CodeStyle. I can try to move to latest 4.7.0-2.xxx version from this feed, but I am not sure if @akhera99's fix is contained in that package.

**Comment by mavasani** [comment]
https://github.com/dotnet/roslyn/pull/68608

> I see that #67167 made it into 17.6, so we should be good to bump the above version to 4.6.0, which means anyone on VS2022 17.6 or later should be fine. I'll work on this change.

https://github.com/dotnet/roslyn/pull/68608
