### ISSUE TITLE
async/await Visual Studio autocomplete

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#68512]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/asyncawait-Visual-Studio-autocomplete/1638212)._

---
If my understanding is correct you have to await an async method and you can only use await in an async method.  Why then cannot VS look at the method being called and automatically use await.
Similarly an async method must return a Task, so if it is marked as async why can VS not automatically change the type to Task<type>

There must be a better way than having to remember to manually type the Task and await words every time when using async code

---
#### Feedback Bot on 1/16/2022, 11:49 PM: 

(private comment, text removed)
#### Feedback Bot on 1/24/2022, 10:09 AM: 

(private comment, text removed)
#### Feedback Bot on 3/23/2023, 11:05 AM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
>  Why then cannot VS look at the method being called and automatically use await.

Because 'awaiting' isn't necessarily what is wanted.  Working with the tasks directly is a normal strategy for doing async/concurrent work.

>  Why then cannot VS look at the method being called and automatically use await.

An async method can return anything task-like.  like "ValueTask".  

>  so if it is marked as async why can VS not automatically change the type to Task

We do do this:

![image](https://github.com/dotnet/roslyn/assets/4564579/f2dd46f0-11ac-43db-806a-e8e77b64b538)

We also just add 'async' automatically to the method if you try to complete out `await` in your method body.
