### ISSUE TITLE
CSharpRazor vsi test is flaky

### ISSUE THREAD

**Issue by TyOverby** [dotnet/roslyn#6851]
http://dotnet-ci.cloudapp.net/job/roslyn-internal_prtest_win_vsi_p3/47/consoleFull#-70887886987b2fba6-0f8e-4a04-a3ae-ceac18a86066

Bounty

**Comment by TyOverby** [comment]
I've disabled this test in the internal test suite.

**Comment by TyOverby** [comment]
Disabled here:
https://github.com/dotnet/roslyn-internal/pull/392/files

**Comment by dpoeschl** [comment]
Dup'ing this against #6906, which will gather more data for these failures. We'll reopen when we have more data.

**Comment by davkean** [comment]
This test is still disabled and wasn't reenabled, we should do that.

**Comment by DustinCampbell** [comment]
@balajikris -- is this still failing? If not, can we get it enabled? If so, can we fix it?

**Comment by DustinCampbell** [comment]
Note that this is marked Urgency-Now because of a big regression we just had with web projects.

**Comment by balajikris** [comment]
The linked logs have expired. I cannot run these tests locally due to Apex / Product version mismatch. We're on update 1 (locally) and apex libraries are on RTM version (to be compatible with jenkins queues). So, we're blocked until we move our queues to Update 1.

**Comment by balajikris** [comment]
- [ ] To be unblocked by #7537

**Comment by davkean** [comment]
We're on VS Update 1 now, so this should be no longer blocked.

**Comment by balajikris** [comment]
The blocked label has been removed and there is a PR out. Unfortunately, it seems that the PR needs more work.

**Comment by jaredpar** [comment]
@balajikris been 3 months since there was an update to this issue.  What is the status?

**Comment by balajikris** [comment]
@jaredpar I seem to have lost all context about this :cry: I'll take a look again.

**Comment by balajikris** [comment]
Update: Figured out this one. Somewhere after vs2015 the webteam likely updated the project and item templates. This test creates a razor project from an empty template and adds an empty html page to it (that used to support razor syntax). Now I'm seeing that adding the html page no longer supports razor syntax and by looking at the product UI - the add item options have changed (add view page etc.)

So, adding a different item template thats supported makes this works. That said, `GetProjectItemTemplate` doesn't seem to be able to find the path for said item templates. So the only option is to either manually construct the item template path, or just create a fully populated MVC project from the project template instead of creating an empty project and adding files to it. I'll likely go with the latter. 

PR https://github.com/dotnet/roslyn-internal/pull/1112 tests this theory with an hardcoded item template path and the test passes. whew!

**Comment by mavasani** [comment]
Seems to have failed again: http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p3_prtest/272/

Reopening this issue.

**Comment by balajikris** [comment]
@mavasani Please open a new bug, this is a different issue. Its likely catching the failing scenario for which the test was added, the fix though isn't in master yet.
