### ISSUE TITLE
"Move type to" code action using C# Dev Kit incorrectly moves the type to the root folder.

### ISSUE THREAD

**Issue by tmitchel2** [dotnet/roslyn#68550]
**Version Used**: 
v0.1.83

**Steps to Reproduce**:

1. Create a project with a folder structure
2. Add a new type within one of the folders, ensure the file name does not match the type name so you enable the "Move type to" code action 
3. Highlight the type and select the "Move type to" code action.
4. 

A minimal repro, with source-code provided, is ideal.  Using [sharplab](https://sharplab.io/) is preferred for compiler/language issues whenever possible.

**Diagnostic Id**:

If this is a report about a bug in an analyzer, please include the diagnostic if possible (e.g. `"IDE0030"`).

**Expected Behavior**:
The type should be moved to a new file but remain in the same folder

**Actual Behavior**:
You will see the type is moved to the root folder

**Comment by tmitchel2** [comment]
In addition, the expected behaviour should be that the new file is automatically opened in a new tab.

**Comment by Cosifne** [comment]
@tmitchel2 
The original problem is fixed in the linked PR. It should be in the release channel in a few weeks.
For the second point you mentioned, yes it would be good if everything would be the same in VS.
However, most of our VS Code features rely on LSP (Language Server Protocol), and I don't see it giving the server ability to open the created document when providing code action. We can extend that behavior to a certain degree, but that seems another issue.
So I would mark this as completed and create a new one for the second problem

**Comment by tmitchel2** [comment]
Makes sense re: opening the doc.  Continual incremental improvement is great in my book.  Many thanks
