### ISSUE TITLE
[BUG] Analyzers and code fixes not working in C# Dev Kit?

### ISSUE THREAD

**Issue by arkalyanms** [dotnet/roslyn#68588]
From vscode-dotnettools created by [DaRosenberg](https://github.com/DaRosenberg): microsoft/vscode-dotnettools#61  

### Describe the Issue

Not sure if this is exposing a bug or just a missing feature for now. Can you clarify whether analyzers and code fixes should be working yet or not?

### Steps To Reproduce

Works:
- Analyzers are run during build, and issues surfaced as problems (errors and warnings)

Does NOT work:
- Analyzers do not run automatically (neither for solution nor for open documents)
- No command to run analyzers imperatively either
- Detected issues are highlighted in source (squigglies) but no fixes appear 
- No settings to enable analyzers or control analysis behavior

### Expected Behavior

I expect analyzers functionality to be on par with Visual Studio, or at least on par with the previous OmniSharp-powered C# extension.

### Environment Information

- OS: macOS Ventura
- VS Code: 1.78.2
- Extension: C# Dev Kit v0.1.8

**Comment by mavasani** [comment]
> Analyzers do not run automatically (neither for solution nor for open documents)

This should be fixed with https://github.com/dotnet/vscode-csharp/pull/5868. C# extension would now have two options to control the analysis scope for your solution:
- Analyzer diagnostics scope: Open documents OR Entire solution OR completely turned off
- Compiler diagnostics scope: Open documents OR Entire solution OR completely turned off

> No command to run analyzers imperatively either

Currently, there is no equivalent of `Run Code Analysis` command in VSCode. I'll open a separate issue to track this feature request

> Detected issues are highlighted in source (squigglies) but no fixes appear

This should also be fixed with the above changes. If not, kindly open a separate issue with further details.

> No settings to enable analyzers or control analysis behavior

Mentioned above
