### ISSUE TITLE
[BUG] Order Modifiers fixer does not result in any changes via Code Cleanup

### ISSUE THREAD

**Issue by oborsha** [dotnet/roslyn#68659]
**Version Used**: 
17.6.3 (Visual Studio)

**Steps to Reproduce**:

1.  Make sure Order Modifiers fixer is active on Code Cleanup Profile1 
2.  Run Code Cleanup on any code file with methods/properties that have modifiers out of order.
3.  Code Cleanup does _not_ re-order the modifiers as expected.

**Diagnostic Id**:
If this is a report about a bug in an analyzer, please include the diagnostic if possible (e.g. `"IDE0030"`).

**Expected Behavior**:
Code Cleanup with Order Modifiers fixer active should order the modifiers according to configuration.

**Actual Behavior**:
Code Cleanup does nothing to reorder the members of the class that have modifiers out of order.

Cross-reference previous story that was closed prematurely:
https://github.com/dotnet/roslyn/issues/42575

**Comment by sharwell** [comment]
I was not able to reproduce this. When I place modifiers in the wrong order, IDE0036 is reported:
![image](https://github.com/dotnet/roslyn/assets/1408396/971c587a-de2b-4009-906c-03cee86ff57f)

When I run Code Cleanup with the Order Modifiers fixer enabled, the issue is fixed:
![image](https://github.com/dotnet/roslyn/assets/1408396/f48359c5-c688-4d6c-b22a-6aa76b068fe2)

**Comment by oborsha** [comment]
To be clear, the related editorconfig would show something like:

**csharp_preferred_modifier_order = public,private,protected,internal,file,static,extern,new,virtual,abstract,sealed,override,readonly,unsafe,required,volatile,async**

**Comment by CyrusNajmabadi** [comment]
This analyzer and fixer only affects the order of modifiers in a single declaration. It will not impact how multiple declarations are ordered against each other. 

All the accessibility modifiers are in the ordering string because all of them should come before items later in the string and should come after items earlier than then in the string

**Comment by oborsha** [comment]
Thank you for clarification.
