### ISSUE TITLE
Documents from different projects with the same path are considered the same since 4.6.0

### ISSUE THREAD

**Issue by svick** [dotnet/roslyn#68814]
**Version Used**: 4.6.0

**Steps to Reproduce**:

Have the following .csproj:

```csproj
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <RoslynVersion Condition="$(RoslynVersion) == ''">4.6.0</RoslynVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="$(RoslynVersion)" />
  </ItemGroup>

</Project>
```

And this Program.cs:

```c#
using System.Diagnostics;
using Microsoft.CodeAnalysis;

var workspace = new AdhocWorkspace();

var p1 = workspace.AddProject("p1", LanguageNames.CSharp);
var p1Document = p1.AddDocument("code.cs", "// p1 code", filePath: "code.cs");

Debug.Assert(workspace.TryApplyChanges(p1Document.Project.Solution));

var p2 = workspace.AddProject("p2", LanguageNames.CSharp);
var p2Document = p2.AddDocument("code.cs", "// p2 code", filePath: "code.cs");

Debug.Assert(workspace.TryApplyChanges(p2Document.Project.Solution));

var project = workspace.CurrentSolution.Projects.Single(p => p.Name == "p2");
var document = project.Documents.Single();

Console.WriteLine(await document.GetTextAsync());
```

**Expected Behavior**:

When executed on any Roslyn version, the code above returns the document from the second project and prints `// p2 code`.

**Actual Behavior**:

When executed on Roslyn 4.6.0, it prints `// p1 code`:

```
> dotnet run -p:RoslynVersion=4.5.0
// p2 code
> dotnet run -p:RoslynVersion=4.6.0
// p1 code
```

**Comment by sharwell** [comment]
I've run into some cases while testing where Roslyn assumed something was an absolute file path and not just a file name. `filePath` above might be one of those cases.

**Comment by CyrusNajmabadi** [comment]
This is *currently* expected behavior. The concept of a linked file is precisely "has the same path".  So, of contents change for one, they are applied to the other when the workspace resolves itself. 

We actually moved to a strict form of this as we previously had codepaths that would allow the contents of each to diverge, which then broke features that operated on documents and assumed all the contents of each linked doc must be the same (for example all the features that tell you if you're doing something in one tfm that is not available in another). 

What's your use case where you want these to have the same path (absolute, or relative from solution root) and you do not want them to have the same contents?  And how would that work in practice with any workspace that actually represents the data on disk (the mainline case)?

Thanks!

**Comment by svick** [comment]
> What's your use case where you want these to have the same path (absolute, or relative from solution root) and you do not want them to have the same contents?

It was a unit test that worked on 4.5.0, but started failing on 4.6.0.

It was easy to modify the test to use different paths for the two different documents, so it's not an actual problem for us anymore.

But I still think it's a bad design that the contents of the second document (`"// p2 code"`) are simply ignored. Maybe adding a different document with the same path should throw an exception? Or it should require that the text is the same? Or something along those lines.

**Comment by CyrusNajmabadi** [comment]
> Or it should require that the text is the same? Or something along those lines.

We tried the, but it was far too onerous.  All code actions the manipulate documents started failing since the code actions had to consider the linked case. 

Imo, if this is just a unit test, then it's fine and expected that this broke as a natural consequence of enforcing this consistency. I would cost this out as expected
