### ISSUE TITLE
CS1654 for no obvious reason

### ISSUE THREAD

**Issue by danmoseley** [dotnet/roslyn#68882]
I'm using 8.0.100-preview.5.23303.2 SDK.

What is the compiler trying to protect against here? In order to remove the method, I had to change the using statement to manually dispose to avoid the error.
```
using System;
public class C {
    public static void Main() {
        using var s = new S();
        s.Value = 42; //  error CS1654: Cannot modify members of 's' because it is a 'using variable'
        //s.SetValue(42); // ok
    }
}

struct S : IDisposable
{
    public int Value;
    public void SetValue(int value) => Value = value;
    public void Dispose() { }
}
```

**Comment by CyrusNajmabadi** [comment]
`using` variables are 'readonly' so that the user code cannot overwrite the original value with some new value.  This is because it woudl be confusing as to waht that meant.  Specifically, was the original value disposed, or the new value disposed?  

However, 'readonly-ness' is a statement about a storage location.  For a struct, the storage location is the value itself (there's no pointer to the value).  So, because of this, you cannot do anything considered a 'write' to the struct value.  That includes assigning over the value *fully* or potentially assigning over any *portion* of the value.

**Comment by CollinAlpert** [comment]
That makes sense, but if anything considered a 'write' to the struct value is prohibited, why is `s.SetValue(42);` allowed?

**Comment by CyrusNajmabadi** [comment]
methods, by default, are assumed to not write (since back then tehre was no way to know for certain if it was a safe method or not).  But distinct setter-calls are assumed to write since properties are intended to represent 'stateful like things'.  Nowadays, we would be able ot mark methods/properties with teh `readonly` modifier as appropriate.  But we didn't have it at the time, so this was a 'good enough' heuristic.

**Comment by danmoseley** [comment]
Cc @stephentoub in our case was the write (previously through a method) causing us to fail to dispose the original? But perhaps that doesn't make functional difference in this case.

With respect to the heuristic, should it now be extended to non read only methods (ie requiring everyone add readonly)

**Comment by CyrusNajmabadi** [comment]
> With respect to the heuristic, should it now be extended to non read only methods (ie requiring everyone add readonly)

That would quite possibly break an enormous amount of code.  A proposal could be made on this.  But it would have a high bar to clear to be considered ok.  This is likely just a thing we live with as choices made in 1.0 that now have 25 years of use cases piled onto them.

**Comment by danmoseley** [comment]
Yeah - perhaps with an analyzer/fixer and a way to opt in. Do you believe many bugs would be caught though? I assume so if we think it's worth an error for field writes.

**Comment by quixoticaxis** [comment]
> > With respect to the heuristic, should it now be extended to non read only methods (ie requiring everyone add readonly)
> 
> That would quite possibly break an enormous amount of code.  A proposal could be made on this.  But it would have a high bar to clear to be considered ok.  This is likely just a thing we live with as choices made in 1.0 that now have 25 years of use cases piled onto them.

We use method workaround to change fields of structs in our production codebase.

What is the risk of changing a struct? The `using` statement is guaranteed to emit constrained call, AFAIU, so there is no ambiguity of what is being disposed.
