### ISSUE TITLE
Rename feature (CRTL + R + R) does not work as intended in an edge case

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#68880]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Rename-feature-CRTL--R--R-does-not-w/10405410)._

---
[severity:It's more difficult to complete my work]
When using the rename function, every letter typed after the 7th letter is duplicated, and pressing backspace exits the renaming function entirely.

This only happens on renaming the last variable inside a class. If you add another item after the item that is failing to rename, then renaming works fine again.

Repairing Visual Studio, nor restarting my computer, helps.

The variables are inside a Unity game script.

In the screenshot, the second "d" -letter was not typed on my keyboard, but instead it was somehow added from just one press of the "d" -key.

---
#### Feedback Bot on 7/2/2023, 08:29 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
Steps to reproduce:

1. Create a new class library with the following code:

```cs
namespace ClassLibrary1;

public class Class2
{
    public int Field123;
}
```

2. Place the caret on `Field123`
3. Press <kbd>F2</kbd>
4. Type <kbd>F</kbd>, <kbd>i</kbd>
5. Type <kbd>e</kbd>, <kbd>l</kbd>, <kbd>d</kbd>, <kbd>1</kbd>, <kbd>2</kbd>, <kbd>3</kbd>

Expected behavior:

1. After step 4, the preview and editor show the new name as `Fi`
2. After step 5, the preview and editor show the new name as `Field123`

**Comment by CyrusNajmabadi** [comment]
@Cosifne @ryzngard can this be looked at asap.  We're getting lots of reports from people on this.  (To the level that i'm tempted to roll back to the old, rock-solid, UI).

**Comment by Cosifne** [comment]
Looking this now

**Comment by Cosifne** [comment]
Fixed in the linked PR above.
