### ISSUE TITLE
Optimize+ doesn't seem to fully discard all unreachable code

### ISSUE THREAD

**Issue by eFail** [dotnet/roslyn#68929]
**Version Used**: 3.11.0-4.22108.8 (d9bef045)

**Steps to Reproduce**:
1. Inside Visual Studio, create a new C# `Class Library (.NET Framework)` project.  The type of C# project isn't too important, this is just used for simplicity.
2. Replace the contents of `Class1.cs` with the following code:
```cs
namespace ClassLibrary1
{
    static class Settings
    {
        public static bool IsSpecialMode
        {
            get
            {
                #if SPECIAL_FLAG
                    return true;
                #else
                    return false;
                #endif
            }
        }
    }

    public class Class1
    {
        public string DoSomething()
        {
            if (Settings.IsSpecialMode) {return "Doing something SPECIAL.";}
            else                        {return "Doing something.";}
        }
    }
}
```
4. Build the solution in `Release` mode, then use a developer command prompt to navigate into the output directory and open the built DLL using _ILDASM_.: `ildasm.exe ClassLibrary1.dll`.
5. Navigate down to the `DoSomething()` method and double-click it to bring up the IL.

![image](https://github.com/dotnet/roslyn/assets/1672416/b2f19d7a-234b-496e-934b-107c3955e9ae)

**Expected Behavior**:
It's my understanding that the `Optimize+` compiler flag removes unreachable code.  Based on whether `SPECIAL_FLAG` is defined, the `Settings.IsSpecialMode` property will always return either `true` or `false`.  As a result of this, there is only a single code path the `DoSomething()` method can ever execute.  It is expected here that the generated IL would reflect this.  Only one string should be seen in the IL.

**Actual Behavior**:
Both strings can be seen in the IL.  Even though one block of the `if` statement in the `DoSomething()` method is unreachable, both blocks are always kept around by the compiler.

**Remarks**
The code above was kept simple for demonstration purposes, but either block of the `if` statement could contain thousands of lines of code.  The compiler should be smart enough to detect this and remove the unreachable code.

Additionally, the idea behind the code above is that a production build should not define `SPECIAL_FLAG`, and all the special code associated with that flag should be compiled out of the final assembly.  Because the unreachable code is not being removed by the compiler, it can still be viewed and coerced into being executed by someone.  The intermediate `IsSpecialMode` property is used to avoid having to clutter the codebase with preprocessor directives.

**Comment by CyrusNajmabadi** [comment]
You have a property here, not a constant. Neither the language nor c#-to-IL compiler fold out non-constant code. 

The jit may do this though when it applies things like inlining.

This is working as intended, with the relevant posts of the *entire* compiler stack doing the types of optimizations relevant to their layers.

**Comment by eFail** [comment]
Based on the information you provided, I realized that the solution here is to use the `#if` preprocessor directive a slightly different way.  Rather than have it control the contents of a property, it can instead be used to _either_ define a property that runs some code to determine whether "special" mode is applicable, _or_ to define a constant that is `false`.  Not only does this now work as expected, but the unreachable code inside the `DoSomething()` method is also being greyed out, which is even better than it occuring only behind the scenes.

![image](https://github.com/dotnet/roslyn/assets/1672416/be89b252-6437-4204-94bb-15098e406a56)

@CyrusNajmabadi: I know you marked this as closed, but with implementation details aside (properties vs. constants vs. inlining vs. knowing about layers of the compiler), am I way off in saying that the above code still demonstrates a clear way in which C# compiler optimization could be improved?  If the end result of a property is that it will return a constant value, then why doesn't the compiler convert that to a constant, and then remove all the unreachable code associated with it?  That's the sort of thing I'd expect from a "plus" version of optimization (`optimization+`).  If it's not Roslyn that would be responsible for this sort of thing, is there another team/repository where this feature/bug/suggestion could be made?  Or maybe there's a reason I'm not thinking of as to why this would be undesirable?

**Comment by CyrusNajmabadi** [comment]
>  If the end result of a property is that it will return a constant value, then why doesn't the compiler convert that to a constant,

Because that would violate the semantics of what is going on here.  *Specifically*, the very idea of a "property" in *the first place* is that it is computed.  The C#-to-IL compiler should not make any assumptions here since this code absolutely may be swapped out with something else that computes a different value when all of this finally runs.  

The reason to use a property is *precisely* for this purpose, and it's why we have distinct concepts around things like "constants" versus "computed" values.  If you choose a constant, that is an up front declaration stating this variable has one and only one value.  Indeed, it goes even further than that.  If you make something a constant the language/compiler will actually take that variable's value and use that in all referenced places *always*.  That means once you compile the code that references on the constant, if you ever change what hte constant is, the already-compiled, referencing code, will not be updated unless you recompile that too.

This is, of course, not how 'computed' properties work.  In that case, the reference to the property always calls into it so that if the implementation of the property changes, teh referencing code will pick it up *without needing to be recompiled*.  This is crucial to how properties work.  They do not leak out if they are constants are not, and that's precisely so that they can change at any time, and everything works.  If they leaked out that they were constants, and referencing code then embedded that information (including throwing away code), you would have terrible breaks if their impl ever changed.

**Comment by CyrusNajmabadi** [comment]
> If it's not Roslyn that would be responsible for this sort of thing, is there another team/repository where this feature/bug/suggestion could be made? Or maybe there's a reason I'm not thinking of as to why this would be undesirable?

The runtime is responsible for doing things like inlining code, and eliminating unnecessary stuff like this.  And, if you look at the JIT asm generated for your original code, you'll see that it has understood this case, and that DoSomething's ASM will literally just be the return of the specific string constant.

**Comment by eFail** [comment]
Got it.  Thanks for the very detailed explanation Cyrus, very insightful!

**Comment by CyrusNajmabadi** [comment]
You're welcome!
