### ISSUE TITLE
Test 'TargetTests.CompilerApiVersionIsSet' fails locally

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#68961]
**Version Used**: 77f28318aec4e3536b6919837370ef8d56008d0a

**Steps to Reproduce**:

`.\Build.cmd -testCoreClr` locally

```
Assert.Equal() Failure
Expected: 4.8
Actual:   4.7

Stack trace:
   at Microsoft.CodeAnalysis.BuildTasks.UnitTests.TargetTests.CompilerApiVersionIsSet() in src\Compilers\Core\MSBuildTaskTests\TargetTests.cs:line 917
```

Test was added in #56460

Somehow I feel like the `dotnet --list-sdks` output could be relevant:

```
> dotnet --list-sdks
7.0.400-preview.23274.1 [C:\Program Files\dotnet\sdk]
8.0.100-preview.5.23303.2 [C:\Program Files\dotnet\sdk]
```

cc @jaredpar @chsienki. It feels like there are weird environment-specific issues that have continuously impacted behavior of local coreclr tests. Something like a different runtime being chosen for the tests locally versus in CI. Less sure of what's happening in this case.

**Comment by chsienki** [comment]
Hmm, so I guess we updated the Roslyn version number? 

The file that contains the `roslyn4.x` property is generated as part of the build here: https://github.com/dotnet/roslyn/blob/3ccd155e0933411be1c5ca1504ca7dedfa296596/src/Compilers/Core/MSBuildTask/Microsoft.Build.Tasks.CodeAnalysis.csproj#L95C11-L95C11

I *thought* the unit tests where pulling the targets from the locally deployed ones, rather than the SDK, but I might be wrong. If it's pulling from the SDK it's going to need a matching newer SDK. You can grab a binlog for the specifc test by uncommenting here https://sourceroslyn.io/#Microsoft.Build.Tasks.CodeAnalysis.UnitTests/TargetTests.cs,6 which should let you see where that file is being consumed from.

**Comment by jaredpar** [comment]
Try deleting `artifacts\obj\Microsoft.Build.Tasks.CodeAnalysis\Debug` and re-running the tests. That fixed the issue for me. That leads me to believe it's an authoring issue in the project file (also would explain why it passes in CI).
