### ISSUE TITLE
Cast Char to String.

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#69]
Would it be beneficial to have a `Char` to be cast-able to a `String`? 
You could think of it as a String of one character in length.

**Comment by mikedn** [comment]
As an implicit conversion? Certainly not, that can lead to unnecessary string allocations.

As an explicit conversion? Maybe, but it's not different from calling ToString() and, at least in my experience, rarely necessary.

**Comment by alanfo** [comment]
In practice, you can do:

`"" + c`

rather than :

`c.ToString()`

So I'm not sure that:

`(string)c`

would be a worthwhile improvement.

However, `$c` would be a nice shorthand for `$"{c}"` and it needn't be limited to character expressions.

**Comment by paulomorgado** [comment]
You're not implying those are the same thing. Are you?

**Comment by alanfo** [comment]
If I've understood string interpolation correctly, then `$"{c}"` is the same thing as `c.ToString()`.

If it were considered desirable to have a shorter way of converting a `char` to a `string` (rather than use hacks such as `"" + c`), then I was thinking that `$c` might be a better proposal than a cast.

It also occurred to me that this syntax needn't be limited to converting character expressions to strings - you could convert other types as well - and could be thought of as a shorthand for `$"{c}"`.

**Comment by paulomorgado** [comment]
@alanfo 

> If I've understood string interpolation correctly, then  $"{c}"  is the same thing as  c.ToString() .

No it isn't.

Have a look at this post: [Customizing string interpolation in C# 6](http://www.thomaslevesque.com/2015/02/24/customizing-string-interpolation-in-c-6/)
