### ISSUE TITLE
Use primary constructor (and remove fields) removes code comments

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/roslyn#69012]
**Version Used**: Version 17.8.0 Preview 1.0 [33911.468.main]

**Steps to Reproduce**:

```c#
class C
{
    // This class has a comment here.

    private readonly string _field;

    public C(string field)
    {
        _field = field;
    }
}
```

Invoke "Use primary constructor (and remove fields)".

```c#
class C(string field)
{
}
```

**Expected Behavior**:

The comment is not stripped from the class.

```c#
class C(string field)
{
    // This class has a comment here.
}
```

FYI @CyrusNajmabadi

**Comment by drewnoakes** [comment]
Real world example.

![image](https://github.com/dotnet/roslyn/assets/350947/afca055e-0538-4a69-ba39-5ae6379f2997)

**Comment by MykolaBalakin** [comment]
I would like to fix the issue, but I want to confirm the expected behavior. Right now, all trivia of a removed node is lost except for XML documentation, which is converted to the primary constructor XML documentation.

What should be the expected behavior in a more general sense? Should I try to attach all the comments trivia (except for XML documentation) of a removed node to the next non-removed node in the class, or should it become part of the corresponding XML documentation element in the primary construction trivia?

**Comment by CyrusNajmabadi** [comment]
1. If hte comment trivia has any blank lines between it and the member, we should attempt to keep it within the body of hte class.
2. if the comment trivia does not have any blank lines between it and the member my caring is less.  But keeping it within the body of the class is fine.

We should not move these normal comments to be part of doc comments in any way.

**Comment by CyrusNajmabadi** [comment]
> I would like to fix the issue, 

That would be awesome.  Thanks!

**Comment by MykolaBalakin** [comment]
Here is the PR: #69518, but I feel I have overcomplicated the fix. Looks too clumsy for my liking.

Also, the issue affects not only comment trivia, but some other — `#line`, `#warning`, etc. Should I add similar logic to those?
