### ISSUE TITLE
Merging CodeStyle and Features layers

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#69077]
Currently, we have majority of IDE analyzers and fixers in shared projects, which get compiled into a CodeStyle NuGet package as well as into the Features layer assemblies. This enables us to ship the CodeStyle NuGet package, which enables build time enforcement of IDExxxx diagnostics. CodeStyle NuGet package or assemblies ship inside the .NET SDK and are disabled by default. They do not ship inside VS, and these analyzers/fixers are enabled in a default VS environment via the copy compiled into the Features layer. CodeStyle layer has access only to public Roslyn APIs, just like a third party NuGet package, while the Features layer has IVT access to Workspaces.

There are couple of issues that the above architecture causes:
1. Maintenance: Because we compile the same analyzers/fixers into two separate layers, which have access to different set of Roslyn APIs, lot of the code in this share layer needs to have `#if CODE_STYLE` preprocessor directives spread all over the place. We are also forced to define same instances of some types in two different namespaces to ensure that we avoid namespace clashes. Code in the shared layer has grown to become very hard to decipher, maintain and reason about and adds to lot of developer pain for Roslyn devs.
2. Functionality: As the same analyzers/fixers gets compiled into separate assemblies with differing code based on the conditional preprocessor directives, users get unintentional behavior changes in the IDE when they switch between CodeStyle package and in-built VS analyzers/fixers from Features layer.

We can consider two alternative approaches here to improve the state of our code base:

1. Remove the IDE analyzers/fixers/refactorings shipping from Features layer, and then include CodeStyle assemblies directly in-box within VS. This was a no-go last time we discussed few years ago as it will introduce a bunch of new assembly loads in a default VS session where a .NET project is opened (I think it was 6 or 9 extra assemblies getting loaded). Note that one pain point that this approach introduces will be that we can no longer quickly ship a new IDExxxx analyzer/fixer which consumes some internal Roslyn APIs from the Workspace layer, because CodeStyle layer can only access public Roslyn APIs. We can workaround this by temporarily putting such a new analyzer/fixer in the Features layer only, and then once the required APIs are made public, move it to CodeStyle layer, avoiding duplicate compile into both assemblies.

2. Give IVT access from Roslyn to CodeStyle layer, so we don't need the #if CODE_STYLE directives everywhere. This has the downside that already shipped CodeStyle packages can break with internal API changes. I think there are few others downsides of this approach, which might make this non-feasible.

We may want to re-open this discussion, and consider if some improvements can be made here. We can probably push for 1. again if additional assembly loads can be justified.

**Comment by tmat** [comment]
Definitely agree that the current state is too complex and hard to understand. A simplification is absolutely needed. 

Isn't the main problem that we are trying to reuse code between code style and features? If all analyzers were in code style layer and used public API then we could still use source packages or shared projects to include the source code in a single assembly, instead of referencing dlls, no? So I think the issues of assembly loads and ifdefs are two separate issues and can be addressed separately.

Re using internal APIs - I think we can address that in two steps. First, review those analyzers that have been using internal APIs for a while now. For these APIs we can be pretty sure about their usefulness and shape. Let's invest into polishing them and making them public then.

Once we are done with this API pass then we should have no or very little internal APIs that are needed for analyzers (perhaps for newer language/runtime features where are are not sure yet). We can create External Access layer for these APIs and for any other new, work-in-progress API. Since we should only have a few of these APIs the extra implementation overhead of External Access should be acceptable.

**Comment by CyrusNajmabadi** [comment]
By and large, the most important thing i'd like to come out of this is some sort of Sanity wrt options.  I literally have no idea how they work, and i'm constantly dumbfounded trying to make things work when i write new code.  My only viable approach has been to just copy/paste existing features that do things.

Lord help me if i hit an option/optinos-provider that has a `#if !CODESTYLE` somewhere in it :)

**Comment by tmat** [comment]
What is the issue specifically about options in analyzers?

It's very straightforward to use options in analyzers: get (AnalyzerOptionsProvider)[https://sourceroslyn.io/#Microsoft.CodeAnalysis.Features/AnalyzerOptionsProvider.cs,a54fbaf513f0c6fe,references] from one of the contexts (https://sourceroslyn.io/#Microsoft.CodeAnalysis.Features/AnalyzerOptionsProvider.cs,74715dca514b3c45,references) and then get the option you need from there.

**Comment by tmat** [comment]
I can think of two areas where options get complex in code style/analyzers: 1) fallbacks to IDE options, 2) option containers being internal types. These would be certainly addressed if we removed the fallbacks to IDE and added public APIs.

**Comment by CyrusNajmabadi** [comment]
honestly, it's that i don't know how to reason about this stuff:

![image](https://github.com/dotnet/roslyn/assets/4564579/1b82ad8f-944d-4023-a1e3-58a8088975cc)

![image](https://github.com/dotnet/roslyn/assets/4564579/78b435b4-971c-476f-822e-374d50f998cf)

etc. etc.

**Comment by tmat** [comment]
`XxxOptionsProvider` types are an indirection mostly used for fallback options or other cases where pre-fetching options would be expensive or undesirable for whatever reason. The indirection is needed e.g. when we have an API that potentially operates on documents/projects that potentially have different language. In this case, we don't know upfront what are the options to fetch (for which language). Such API would take `XxxOptionsProvider` and calls it to fetch options when it needs them (and at which point it knows for which language).

The ifdefs are there because `LanguageServices` type used in the `OptionsProvider<T>` isn't available in code style :(

**Comment by tmat** [comment]
So yeah, the core issue is that code style doesn't have concept of `LanguageServices`.

**Comment by CyrusNajmabadi** [comment]
so my general point is:  i often start with code.  it uses these types fine.  then i move that code down to CodeStyle, and now it doesn't work.  But i'm very unsure of what the actual right thing to do in that case.  Is it:

1. ifdef out that code, and have default behavior in code style?
2. find a way to implement that code in the code style layer?
3. use some other means to get that info?

etc. :)

my basic approach is find some other code and copy it and hope that that other code is correct :)

**Comment by tmat** [comment]
Ah, yes, I agree. That definitely is not limited to options and would be great to address across the board.

**Comment by sharwell** [comment]
> I think we should actually find out how much impact this truly has

The last time this came up, the impact made no difference. I brought data to the meeting regarding the exact impact, and it was overruled by policy saying the data didn't matter even if the data indicated there would not be a user problem resulting from the change.

**Comment by CyrusNajmabadi** [comment]
>  brought data to the meeting regarding the exact impact, and it was overruled by policy saying the data didn't matter even if the data indicated there would not be a user problem resulting from the change.

Bring me to the meeting.  I can overrule.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
