### ISSUE TITLE
Ensure HasAnonymousFunctionConversion returns without binding lambda body for explicitly-typed lambda

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#69093]
> **Warning**: The assumptions made in this post appear to be incorrect. See https://github.com/dotnet/roslyn/issues/69093#issuecomment-1640973220.

81.1% of the CPU time spent on the IntelliSense thread in #67926 is calling `HasAnonymousFunctionConversion`.

This issue relates to the following code:

https://github.com/dotnet/roslyn/blob/ebc284116ad778360cc986bc2f870296aa60253f/src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/ConversionsBase.cs#L1059-L1064

This code should return without binding the contents of the lambda if the lambda explicitly declares all types related to its signature. For example, the following lambda declares its parameter types and its return value explicitly, and therefore can be evaluated for having a conversion without further binding.

```
SomeInvocation(int (string arg) => { /* none of this matters */ });
```

While this guarantee doesn't automatically fix the problem described in #67926, it provides the user with a viable workaround in nested lambda cases where they can explicitly declare the types and avoid further costs.

**Comment by cston** [comment]
There may be edge cases where skipping binding the lambda body might lead to a breaking change, with captured variables for instance.

For example, the following binds successfully to the extension method rather than the instance method, because binding the lambda body fails for the instance method (see [sharplab.io](https://sharplab.io/#v2:CYLg1APgAgTAjAWAFDNgAgILIN7LftKOANkIBY0BZAQwEsA7ACgEo8DckCu0B7AIwBWAUwDGAFzQAPNAF40cANxtuaAG7UATmmqy09IQHdMLJZxXaAdADE4jSQBo0AT1kA+NFZiMGElm+fMzKZcAL7IyuQecAA8ACqujLFSjlAArHGOPu4AZsxo2GhhZvhEpD4eXmnRWWi5/tkmyEWoJIQwaABCOBFQAMyErVAUNoxiABa0AM6Y2o78wuLJhOk+mfRiOXkFRUVAA)).
```csharp
using System;

class A
{
    static void Main()
    {
        object x = 1;
        var a = new A();
        a.F1(x, y => F2(int () => y));
    }

    void F1<T>(T x, Func<T, int> f) { }
    static int F2(Func<int> f) => f();
}

static class B
{
    public static void F1(this A a, object x, Func<int, int> f) { }
}
```

**Comment by jaredpar** [comment]
@cston your example though uses an implicitly typed lambda where as the issue is about explicitly typed lambdas. This is how I would explictly type out that lambda 

```csharp
a.F1(x, int (int y) => F2(int () => y));
```

At that point why do we need to look at the lambda body here? The instance method is just going to fail at the generic inference phase.

**Comment by sharwell** [comment]
@jaredpar I believe the failure from @cston example is during type inference for the _outer_ lambda. For inferring the type of `y`, we can't assume `int () => y` can be converted to the target delegate based on `int () =>` alone.

**Comment by cston** [comment]
For the [example above](https://github.com/dotnet/roslyn/issues/69093#issuecomment-1640973220), it looks like there **would not be a breaking change** if the compiler ignored the lambda body when determining whether the inner lambda expression is convertible to the delegate type.

The reason is because the *outer lambda* is an argument to an overloaded method, and even if we skip binding the body of the *inner lambda* when determining convertibility to the delegate parameter in `F2`, and therefore consider `F2` applicable, we'll still bind the inner lambda body as a part of determining the convertibility of the outer lambda to the delegate parameter in `F1` since the outer lambda is not explicitly typed.

**Comment by jaredpar** [comment]
Discussed this in LDM today and we confirmed that we want to change behavior here. For a lambda with a full explicit signature (return type and parameters) then for purposes of conversion we will only consider that signature. There is no need to bind the lambda body to see if it matches that signature for the purposes of determining if a conversion is legal.
