### ISSUE TITLE
Generics are assumed to be nullable types and lose nullable annotations

### ISSUE THREAD

**Issue by peter-elliott-ms** [dotnet/roslyn#69103]
When annotating an unconstrained generic T as nullable (T?) the compiler treats this as equivalent to T which is only true if it was already a nullable type. if you add where T : struct, then the nullable info is preserved.

**Version Used**: 
Compiler version: '4.6.0-3.23259.8 (c3cc1d0c)'. Language version: 11.0.

**Steps to Reproduce**:

```c#
#nullable enable

// Case 1
int? a = default(int?);
Console.WriteLine((a == null)? "null" : "not null");

// Case 2
T? dflt<T>() {
    return default(T?);
}

int? b = dflt<int>();
Console.WriteLine((b == null)? "null" : "not null");

// Case 3
T dflt2<T>() {
    return default(T);
}

int? c = dflt2<int?>();
Console.WriteLine((c == null)? "null" : "not null");

// Case 4
T? dflt3<T>() where T : struct
{
    return default(T?);
}

int? d = dflt3<int>();
Console.WriteLine((d == null)? "null" : "not null");

```

**Expected Behavior**:
prints:

```
null
null
null
null
```

**Actual Behavior**:

prints:

```
null
not null
null
null
```

**Comment by CyrusNajmabadi** [comment]
This is by design. With *unconstrained* generics, `T?` does not mean 'can be null'. It means 'can be *default*'. 

In your test you get `default(int)` back, which is just 0 (which is not null). 

For class-constrained `T?` means (can be reference-null).  For struct-constrained, it means you get `Nullable<T>` back.

Unfortunately, due to how the runtime fundamentally works, there is no unification here.
