### ISSUE TITLE
CS0052: Compilation error when trying to compile class with internal protected member which has internal type

### ISSUE THREAD

**Issue by mgalczynski** [dotnet/roslyn#69175]
**Version used**:MSBuild version 17.6.8+c70978d4d for .NET
17.6.8.32104

**Steps to Reproduce**:
Minimal repro file:
```csharp
using System;
internal class A
{
}
public class B
{
    internal protected A AProperty {get;set;}
}
```

**Diagnostic Id**:
CS0052

**Expected Behavior**:
Code compiles

**Actual Behavior**:
Code does not compile, CS0052 is a error code

**Comment by CyrusNajmabadi** [comment]
This is by design.  a `protected` member has greater accessibility than an internal one.  So *any* subclass of B in *any* assembly would see this member.  But it wouldn't be able to use it because that member references 'A', which is only available in the starting assembly.


Put another way, `internal protected` means `internal OR protected`.  So it's available both within the assembly, OR from any subclass.  It's the latter part you are in conflict with.

If you want `internal AND protected` we have the terrible syntax `private protected` to reflect that concept.  If you pick `private protected` then the member is only available from subclasses within that assembly.
