### ISSUE TITLE
Spurious CS8769 on String Property Setter of Interface Implementation

### ISSUE THREAD

**Issue by memiamap** [dotnet/roslyn#69337]
**Version Used**: 
VS 2022 x64 17.3.5
C# Tools   4.3.0-3.22470.13+80a8ce8d5fdb9ceda4101e2acb8e8eb7be4ebcea
.Net Core 6.0

**Steps to Reproduce**:

1. Create a class that implements `IDbCommand` (although other interfaces with a string-based property have the same issue).
2. Implement the `CommandText `property (string get/set).
3. CS8769 shown on setter.

Repro showing issue: [sharplab](https://sharplab.io/#v2:CYLg1APgAgTAjAWAFBQAwAIpwHQBECGALvgNzLJQDMmM6AwuiOgJK4BGdA9gLbf4B2wZAG9k6cZjgYA+gGMefQQBUApgA9CZJGIlV6ACgCUO8aKQSL6OQoHBVG9AF5JqbAFFuAB0IBPLRYBfcnNdKRZ2Ll5bbEjFO3VCdGF0AHMVRMcAPit5KOUEknQAZ3SnbOs8+IdnADd8ABsAVxVCoJDxAEt+RNYOG0EY/rsO7hVORsTktIzswgALACdOAHd0fhVVgDlOQmYvepVR7pVgNzVZFW8Ozn4jQpKZ9Hml1fWtnb3PA6PCE7OLq43O7oNoWWK2JQ+TwqcJ9SqDSqQ6FJVKlLJPRYrNYbdDbXb7Q4qY6nc6XQjXW6Ge5o2aY144vGfb5E34kgHkoFUkEmWFcfjrWQc/gAfl5Q0G/JUgopKOmZQxL2x73xX0JxP+ZIpwIe8ueWLeuI+BJ+f1JgMprWCFlYRHwAAV8At8KNfgsuPUDtKbmL4Q6nS6VAsirq6UrDSrmeqzUK7laJL0lE7+EV8F6RT64thEwIU2nZTSFfqGUbVSa2ZrOdTHnr6cqmWrWRrzcDQRIAKqeYBEFQAJRWAGVxgsLhnoh2u6y+8tB41hzCpgWa2HGcaWab2VquTr0UuDSvS2vy82uW0eVAACyjgZ0AQXepGHlmSwSXfFiMN9cVi080/tWEEYg/WddJAyvYAYgWFRuyAgMFgfP8n2fQta3DesyybGMqR/ONxAvcIOiKTxOBTNgDjwAiiJKeCLEQ59XzrVcow3StsO0P8uh6CJxTOKUJhUbZ+AARWaBYfGoiRaMsejUMYxto03fwJF/a0APwHsoOAUDenBAYeNkPj1PwTS4OMBCeQsaT90jOTmO/P9lPjVTDOMsD3DUXjfmcwN9B04AACEVDmfAamuBZ0DYQLgtC0yaPMl9Qz3EtrM/Y9FPEBzxE4NgACspUIUVtO49z9N+ftZAaR1xNMOLxEspKPyPTC0u5NiLDwwrfUgzxHRUKqkhq5Dl3q9D5JY+zkACIA=).

Screenshot from Sharplab because it doesn't always show CS8769 unless the offending code is typed again:

![image](https://github.com/dotnet/roslyn/assets/38524655/e3d0eabb-a7ed-4e12-95bb-8a0536940814)

**Diagnostic Id**:

CS8769

**Expected Behavior**:

CS8769 seems spurious to me.  The interface definition for `IDbCommand` clearly shows that `CommandText `is a `string`, and not `string?`, so what is the setter complaining about?

Definition of [IDbCommand.CommandText](https://learn.microsoft.com/en-us/dotnet/api/system.data.idbcommand.commandtext?view=net-7.0#system-data-idbcommand-commandtext).

I would not expect to see CS8769 in this scenario.  The property is a non-nullable string.

**Actual Behavior**:

As outlined in steps to reproduce, and shown in screenshot below, CS8769 is shown on the setter.

![image](https://github.com/dotnet/roslyn/assets/38524655/60c0fe06-4599-436c-92b5-a9e4e76df926)

**Comment by jaredpar** [comment]
The issue here is that `IDbCommand` has `[AllowNull]` attribute on the property which means the `set` parameter is effectively `string?` ([code](https://source.dot.net/#System.Data.Common/System/Data/IDbCommand.cs,12)). Once the [sharplab](https://sharplab.io/#v2:CYLg1APgAgTAjAWAFBQAwAIpwHQBECGALvgNzJqY64CW+A5gHYD2AzodQMYvYDCTwAUwCCDfABsAni2osyScgGZMMdD3Qh0ASVwAjPgFt9+BsGQBvZOiuUMAfQ5NDx4ABUBAD0JzL1qEp4AFACUPlYWSNaR6PaORiZunugAvDbYAKL6AA6EEnKRAL6h6EUA2kJiYkwA7gByAK4VALpFWBjaerHOvJ3xHoToZuh0Av1JAHzRDk69niToLCPJEzHTrn3J6ABu4nUCc4UR1tQM/e0GccDdqy7U+gJMdf2Dw6MThAAWAE7V6AwCVegakxCJosmIBHcTgJgGl3BwBNlqEwGME5gtXugPt8AX8AUCQWCIQIoTC4Qj2MjUegDpFzs4XBJMgItLo6SYrhcGUyBkNFuNMV8frjAcDQZlwZDCNDYfDEZSgmi+W9BTj/iKCeKiSSZeSkSiFdSimdkX8OBSGAB+FkdVbdBim808l5LAXY35q/FiiXEqWk2Xmqnol1YoUe0WEyXSsly/X7ZBGgjEAAK+E++DuUs+fAqAjNeutbMuKbTGYEnxYwZV7rx4c1kb9uvl3kOVnaLjTDBY+DzyKtxtt7eMXZ7DCdStdoZrGu92ujAYNQf5IdVU69Wt9OpjVJp1gAqplgEQBAAlaoAZQen3hBZ6l33h99p6qF7qV+Zz3Hy+r6rX9c388VDEv2FT0Ix9KN/T1bd4xbTAABYb1tHhjHhMRgiKcIomsYCw2ndcIMbWMigOBMdETfBi3TEYy0Qi5eE+AQj0o0tPnQ2DMKwicVx/MDZ0gptiJgyIoAQ7QZEyVh8B0cE8HE1gBDYyIOKwnDV14jc5yghVBPkWDjlOVlb3Sdxc0eAQgQYABFXZPgkRTrGUqJVJ4utwIbLdtNgkjYO0Ih8GPRjBE+WiulhUypQC/AgvssIikiZzQNcvjCNRHSEz8yKgpC9kwo4MzMrLAJCwAIQEd58E2JFgp0MqKqqkJ2Li7CqxA2sZw0/iiK8oTrCYHQACtc0IPtDNtXKzLPDhxFTGKBiaqwEra/D3IAtLYJE7KiwYzJUwUhqlPmrjv0S9qCI8vJrAOfIgA) sample is updated to have `[AllowNull]` the warning becomes a lot clearer

**Comment by memiamap** [comment]
I thank you for clarifying the underlying cause of the CS8769 warning, your guidance is appreciated.

I feel that documentation should be clearer about this: [IDbCommand.CommandText](https://learn.microsoft.com/en-us/dotnet/api/system.data.idbcommand.commandtext?view=net-7.0#system-data-idbcommand-commandtext)

It says nowhere here that the value is permitted to be nullable.
It was not possible to understand what was occuring here without browsing the source code for IDbCommand.  Even "Go To Definition" in VS2022 doesn't reveal that the property is nullable.
