### ISSUE TITLE
Honor DoesNotReturn attribute

### ISSUE THREAD

**Issue by tamlin-mike** [dotnet/roslyn#69486]
Imagine you are implementing an interface, and for whatever reason you don't want to implement a method right now. You _can_ do
```
  bool method1() => throw new System.NotImplementedException();
```
and magically both compiler and analyzers see "Aha, code can never flow out of this method; let's disable that (class of) compiler error(s) here".

Now imagine you do this for N methods with varying return types. Now you get the urge to refactor that redundant stuff into something more maintainable. You add

```
  [System.Diagnostics.CodeAnalysis.DoesNotReturn]
  private static void NotImpl([System.Runtime.CompilerServices.CallerMemberNameAttribute] string caller = "") { throw new System.NotImplementedException(caller); }
```

and intend to use that for all places doing this manually, i.e.

```
  bool method1() => NotImpl();
```

only to be greeted with `error CS0029: Cannot implicitly convert type 'void' to 'bool'`.

That is ... in lack of better words to describe it, bullshit. I can't view this as anything but a compiler bug.

Suggestion: Disable **all** code-flow analysis after a sequence point calling a function or method tagged with `System.Diagnostics.CodeAnalysis.DoesNotReturnAttribute`.

Risk: Nada, zip, zilch, none.

Impact: Allows writing better code.

**Comment by CyrusNajmabadi** [comment]
> [System.Diagnostics.CodeAnalysis.DoesNotReturn]

DoesNotReturn is just a hint.  It has no actual meaning or enforcement.  As such, the compiler must actually behave based on what the signature of the method is (namely that it is void).  

Consider, for example, even a simple case of compiling against this method, and then the body changing in some future release.  It would have the same binary signature, but would now break badly (since void cannot be converted to bool).

> I can't view this as anything but a compiler bug.

Compiler is operating as the language requires.  If you'd like the language to make this a first-class concept, please open a discussion on dotnet/csharplang first.  An approved language change there will be necessary in order to actually change what hte compiler is doing here.

**Comment by CyrusNajmabadi** [comment]
> Risk: Nada, zip, zilch, none.

There is def risk here.  Including now making it a breaking change to actually add/remove this attribute to a method (never a breaking change before), and quite possibly causing things like corruption if things are not handled super carefully here.
