### ISSUE TITLE
CSC : error CS7038: Failed to emit module '_': Unable to determine specific cause of the failure. 

### ISSUE THREAD

**Issue by chanos-dev** [dotnet/roslyn#69579]
**Version Used**: 

Visual Studio 2022, .NET 6 - C# 10

**Steps to Reproduce**:

- Use "Target-typed new expressions" provided by c#9 for delegate.

Occurs in my visual studio or dotnet cli. Provide example code as [sharplab](https://sharplab.io/#v2:CYLg1APgAgTAjAWAFDKgZgASwwMQPZ7IDeyGZGADgE4CWAbgIYAuAphsCwDYsDmzbUACy4CAES69+ACgCUAblLlFZavX5Zh+PAHkAdi1nKMJJOTNY4ATikAiLRj0sAhE5vyjAX2RHVjVhpE8ABUAdzxDU3ITc3IoK1t7ULwXNwVIsi8UdKxMIQwABVpdJgizIjMjMwB6KowAZwBXAGMmljq6yvIawPFuPn8AMzEJfrYAXkDHNJiybqG8Xsl/MAmtJLkMTrItjG7GlraO7OrarUXRjHnz9Qn9EJ6R6S1Hd2Ou2qvH5duWe7OvgxrMLyTZvbZg3a1FhUKh4Kg7f59dSfJH+H73KTPfSvGaXYaotgrDB3DCYghJEHeCEopYsAB0AEldHQ8ABrAw48iZDxAA).

**Diagnostic Id**:

- error `CS7038`: Failed to emit module '_': Unable to determine specific cause of the failure.

**Expected Behavior**:

- Successful complie.

**Actual Behavior**:

- The compiler issues "Unable to determine specific cause of the failure".

[jcouv update:] Copied the sharplab snippet below:
```
using System;

public class Foo
{
    private delegate void FooDelegate();
    
    private void FooOne()
    {
        Console.WriteLine("Foo One!!");
    }

    private void FooTwo()
    {
        Console.WriteLine("Foo Two!!");
    }

    public void Print()
    {    
        // success
        // FooDelegate fooDelegate = FooOne;
        // fooDelegate += FooTwo; 
        
        // success
        // FooDelegate fooDelegate = new FooDelegate(FooOne);
        // fooDelegate += new FooDelegate(FooTwo); 
        
        // error
        FooDelegate fooDelegate = new (FooOne);
        fooDelegate += new (FooTwo); 

        fooDelegate.Invoke();
    }
}
```

**Comment by jcouv** [comment]
@alrz Would you like to take a look?

**Comment by alrz** [comment]
>**Expected Behavior:**
>
>Successful complie.

Non-equality operators are not allowed for neither `new()` nor `default` (also repros for the same reason) but since this already works with events I guess this should compile for both. 

Note that this doesn't happen with an untyped switch `d += e switch { _ => new/default };`  because overload resolution succeeds (not restricted).

A possible fix is to skip [this check](https://sourceroslyn.io/#Microsoft.CodeAnalysis.CSharp/Binder/Binder_Operators.cs,1285) if coming from compound assignment for delegates but I'm not sure if that's the right fix.

**Comment by chanos-dev** [comment]
Is there a chance that it can be modified? If it's difficult, then it seems like the accurate error message would be necessary.
