### ISSUE TITLE
editor taking spacebar to mean acceptance of autocompletion suggestions 

### ISSUE THREAD

**Issue by arunchndr** [dotnet/roslyn#69591]
From vscode-dotnettools created by [claudiaregio](https://github.com/claudiaregio): microsoft/vscode-dotnettools#222  

### Describe the Issue

I am typing and I will get autocompletion suggestions. I try to hit the spacebar just because I am moving onto a new word but the editor is taking spacebar to mean acceptance of the suggestion thus putting things I don't want in my code. I have to go back and delete it or press esc first. 

### Steps To Reproduce

Type anything that gives you autocompletion suggestions and press space when it comes up 

### Expected Behavior

For just tab or enter to be acceptance of an autocompletion or at least have a setting to turn off this functionality. It doesn't occur in other language files (python for example) and it got super frustrating that I had to go back and continuously remove code I wasn't even typing. As I'm typing I don't want to have to hit esc before moving onto my next words continuously 

### Environment Information

Apple M2 Pro
OS: Ventura 13.2.1
C# Dev Kit: v0.1.103
C#: v0.1.103
Intellicode for C# Dev: v0.1.23

**Comment by genlu** [comment]
> acceptance of the suggestion thus putting things I don't want in my code

@claudiaregio Could you please provide more detail on this? There are difference scenarios that might cause the issue you are experiencing:
- Were you trying to use a symbol doesn't exist in the current scope? (e.g. an undefined variable/method/type/etc.?) In this case, the completion would select the item closest to what being typed, causing the issue you described above. In this case, the behavior is expected and you'd need to use `ESC` to explicitly dismiss completion. 
- Or were you trying to declare a symbol (e.g. `var $$`, `class $$`, etc.)? In this case, any suggested item should only be committed by typing TAB, it's a bug otherwise.
- Or the symbol you tried to type exist in the list, but somehow not being selected. This would be a bug in our matching/selection code.

> For just tab or enter to be acceptance of an autocompletion or at least have a setting to turn off this functionality.

This seems to be a request for "suggestion mode". There's `editor.suggest.selectionMode` in VSCode, could you see if it does what you want? Note it's different from the [SuggestionMode in VS](https://github.com/MicrosoftDocs/visualstudio-docs/blob/4b4a3854aaf42daaf358813d2b0d350d77576c5d/docs/ide/using-intellisense.md?plain=1#L41), as it doesn't try to select anything, in contrast to hard vs soft selection in VS.
