### ISSUE TITLE
Missing CS0169 for ref fields without ref-assignments

### ISSUE THREAD

**Issue by controlflow** [dotnet/roslyn#69736]
**Version Used**: main branch

**Steps to Reproduce**:

Compile the following code:
```c#
ref struct S {
  private readonly int field1; // CS0169
  private readonly int field2;
  private readonly ref int field3; // CS0169
  private readonly ref int field4; // no CS0169, this is wrong
    
  int Prop {
   init {
     field2 = value;
     field4 = value; // NRE, not initialized
   }
  }
}
```

**Diagnostic Id**:

`CS0169`

**Expected Behavior**:

`CS0169` produced for both `field3` and `field4`

**Actual Behavior**:

`CS0169` is only produced for `field3`

**Comment by controlflow** [comment]
same story with the `CS0649`

**Comment by RikkiGibson** [comment]
I think #69283 has somewhat improved the situation

**Comment by jaredpar** [comment]
The present behavior is "by design". 

The CS1069 diagnostic is issued for `field1` and `field3`. That is expected as both `field2` and `field4` are used as assignment is usage here. 

The lack of CS0649 for the `ref` fields is the result of an [explicit LDM decision](The https://github.com/dotnet/csharplang/blob/main/meetings/2022/LDM-2022-06-06.md#question-4-constructor-that-does-not-set-ref-field)
