### ISSUE TITLE
Can not resolve symbol method when using System.Diagnostics.Conditional

### ISSUE THREAD

**Issue by ffbh123456** [dotnet/roslyn#69773]
version:  .NET Standard 2.1
1. If I defined the "SOME_DEFINE", no error showed.

2. Removed the scripting define symbol of "SOME_DEFINE" and the error occurred which I think is a bug because the invocation of the DoMethod was removed by the compiler so what matters if it can not find the symbol of "DoABC"?

```

#if SOME_DEFINE

        private void DoABC()

        {

        }

#endif

        [Conditional("SOME_DEFINE")]

        private void DoMethod(Action action)

        {

            action();

        }

        public void Test()

        {

            DoMethod(DoABC);

        }

        

```

For now, I have to add duplicate **#if SOME_DEFINE** for each function call like this to avoid the error which is annoying.

```

#if SOME_DEFINE

        private void DoABC()

        {

        }

#endif

        [Conditional("SOME_DEFINE")]

        private void DoMethod(Action action)

        {

            action();

        }

        public void Test()

        {

#if SOME_DEFINE

            DoMethod(DoABC);

#endif

        }

```

**Comment by CyrusNajmabadi** [comment]
This is by design. The method call is elided when the condition does not hold. But the call to it (including all arguments) still has to be legal. That means references within it must all bind, and be correct as far as the rules of the language are concerned. 

Another way to think about it:

The conditional part is just about doing the eliding at the final emit stage. Everything prior to that must still be legal.
