### ISSUE TITLE
Builds not reporting source-build prebuilts as errors

### ISSUE THREAD

**Issue by mthalman** [dotnet/roslyn#69846]
The Roslyn CI pipeline includes a `Source-Build (Managed)` build leg which builds the repo in the context of source-build. When source-build [prebuilts](https://aka.ms/dotnet/prebuilts) are detected, they are reported in that build leg. However, they are being reported as a warning and not an error. This seems to be unique to the roslyn repo since other repos are correctly reporting prebuilts as errors. It's not clear why this is happening. This is a problem since it lets changes get merged which cause prebuilts to be introduced. This will then fail later on in dependency flow (e.g. https://github.com/dotnet/installer/pull/17319) which does detect the prebuilts and reports them as an error.

cc @MichaelSimons @mmitche

**Comment by genlu** [comment]
@333fred I think you are the expert here? :)

**Comment by mthalman** [comment]
Here are some binlogs to compare between roslyn, which doesn't reported prebuilts as errors, and sdk, which does: [binlogs.zip](https://github.com/dotnet/roslyn/files/12561052/binlogs.zip). Search for the `ValidateUsageAgainstBaseline` task in the binlog viewer. I don't see any difference in the parameters being passed. I see that `TreatWarningsAsErrors` is set to true.

The weird thing is that `FailOnPrebuiltBaselineError` is always set to false. So I don't know how this actually works in all the other repos.

**Comment by mmitche** [comment]
What appears to be happening is that TreatWarningsAsErrors is set to false for the SB leg. This is the default in the roslyn repo https://github.com/dotnet/roslyn/blob/main/eng/build.sh#L76 unless --warnaserror is explicitly passed.

The other issue, as @mthalman has found, is that the baseline comparison task is not automatically failing on a failed baseline comparison. We were essentially relying on the typical repo setting of treating warnings as errors to get an error out.

I think the right thing to do here is to change the arcade infra to default to error on a baseline comparison failure, rather than changing roslyn's behavior. Roslyn only enables warnaserror for its code check leg, and primarily we just want to be as close to the default repo behavior for the source-build leg.

**Comment by mmitche** [comment]
https://github.com/dotnet/arcade/issues/14022

**Comment by 333fred** [comment]
@mthalman @mmitche is there anything for Roslyn to do here? It seems like the linked issue is closed?

**Comment by mmitche** [comment]
Nope, I think this can be closed.

**Comment by 333fred** [comment]
Thanks!
