### ISSUE TITLE
Intellisense not suggesting extension methods from source generated code

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#69887]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Intellisense-not-suggesting-extension-me/10457424)._

---
- Visual Studio 2022 `V17.7.3`
- [x] `Show items from unimported namespaces`

## Problem
- I have a source generator that creates extension methods (in one class) for all entities in my `DbContext` that projects from `IQueryable<DbEntity>` to `IQueryable<GeneratedEntity>`
- In any of my repository files, without importing the namespace of the generated extensions, when I start typing the name of the extension method it is not populated in the intellisense menu, and even if I type the full name out and try `Ctrl-.`, it never finds the method
- If I manually import the namespace, intellisense works, and even go to definition will bring me to the source generated file
- I have other source generators in the same project that don't output extension methods, and their code is found by intellisense just fine
- The generated extension method file is `560` lines of code

---
#### Feedback Bot on 9/4/2023, 06:35 PM: 

(private comment, text removed)
#### Feedback Bot on 9/11/2023, 00:02 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by genlu** [comment]
Probably because we skipped source generated documents when querying our syntax index
https://github.com/dotnet/roslyn/blob/d080175cabfe297ebf079af099279b61913bcc28/src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ExtensionMethodImportCompletionHelper.cs#L269

We can do something similar to [this](https://github.com/CyrusNajmabadi/roslyn/blob/94803bb2e2c7926d4a7bff3cf8cc05a18b133ce6/src/Workspaces/Core/Portable/FindSymbols/FindReferences/DependentTypeFinder_ProjectIndex.cs#L58)

**Comment by CyrusNajmabadi** [comment]
Note: getting SG information is unbounded in time.  So if we do this, we need to ensure it does not regress perf here.
