### ISSUE TITLE
VBCSCompiler doesn't load changed dll referenced as analyzer reference

### ISSUE THREAD

**Issue by kugushev** [dotnet/roslyn#70053]
**Version Used**: 
8.0.100-preview.4.23260.5

**Steps to Reproduce**:
Create a solution with 2 projects: 

- Project A: a project with a source generator 
- Project B: has analyzer reference to Project A and uses generated code

1. Specify some usage of the generated file in Project B
2. Build using `dotnet build`
3. Make changes in Project A, e.g. change the generated class name
4. Build using `dotnet build` again

**Expected Behavior**:
The generated code in Project B is changed based on the changes in Project A source generators. The same behavior in Visual Studio

**Actual Behavior**:
The generated code in Project B has not changed

**Workaround**:
Shutdown VBCSComiler instance by specifying `dotnet build-server shutdown`

### Root Cause

The current Shadow Copy Assembly loader doesn't check the MVID of the built assembly, so once you build dll and it is loaded to VBCSComiler, it will be in the memory till the end of the process

But why does everything work fine in Visual Studio? There is an AnalyzerConsistencyChecker that checks the Mvid of compiled assemblies and returns an error if the Mvid is different. So once VBCSCompiler returns an error it closes and restarted by Visual Studio.

Unfortunately, this checker is disabled for NetCore: https://github.com/dotnet/roslyn/commit/158ba3aaff230b1b89284406323fcc79fa2d04e2

So at this moment, CLT tools don't allow us to work with local Source Generators properly, without shutting down VBCSComiler before every build.

**Comment by mavasani** [comment]
Moving to compilers, @jaredpar is the expert in this space.

**Comment by jaredpar** [comment]
> The current Shadow Copy Assembly loader doesn't check the MVID of the built assembly, so once you build dll and it is loaded to VBCSComiler, it will be in the memory till the end of the process

The VBCSCompiler process was originally designed under the assumption that the file system is unchanged during compilation. That was an _okay_ assumption in the early days of Roslyn but not now where generators and analyzers are more integral into the build system. Unfortunately unwinding that knot has been a bit of a challenge. There are a lot of baked in assumptions that are very thorny to unwind given the variety of hosting scenarios that we have to support.

> There is an AnalyzerConsistencyChecker that checks the Mvid of compiled assemblies and returns an error if the Mvid is different.

The MVID check was meant to solve a slightly different problem. Effectively it wanted to solve the problem of conflicting analyzers dependencies within a build. That can't be resolved within a .NET Framework process due to limitations of `AppDomain` loading. It is not a problem in .NET Core though as `AssemblyLoadContext` gives us the ability to isolate correctly. 

This check though was masking the problem where VBCSCompiler views the file system as unchanging. May have to bring it back in a limited form until I can rework the server to remove the assumption of an unchanging file system.
