### ISSUE TITLE
C# dynamic parameter influences handling methods return

### ISSUE THREAD

**Issue by DarkGraySun** [dotnet/roslyn#70163]
### Description

When converting a passed value into the dynamic type to a function, the type of return of the function is no longer checked by the compiler.

### Reproduction Steps

Minimal console program:
```
internal class Program
{
    private static void Main(string[] args)
    {
        var qq = new TestDynamicClass();
        qq.TestHandling();
        Console.ReadLine();
    }

    internal class TestDynamicClass
    {
        internal void TestHandling()
        {
            long idNullable = 0;
            idNullable = TestDynamic((dynamic)7);
            Console.WriteLine(idNullable.ToString());
            // Runtime Exception Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 
            idNullable = TestDynamic((dynamic)42);
            Console.WriteLine(idNullable.ToString());
        }

        internal long? TestDynamic(long id)
        {
            if (id == 7)
            {
                return id;
            }
            else
            {
                return null;
            }
        }
    }
}
```

### Expected behavior

The program should not be compilable because the compiler checks the return value regardless of the value passed.

### Actual behavior

The program compiles, but throws a "Microsoft.CSharp.RuntimeBinder.RuntimeBinderException" at runtime

### Known Workarounds

If I set the function as an inline function, the compiler throws an error as expected.
 ```
private static void Main(string[] args)
 {
     var qq = new TestDynamicClass();
     qq.TestHandling();

     Console.ReadLine();
     // can not compile
     long test= TestDynamic((dynamic)42);

     long ? TestDynamic(long id)
     {
         if (id == 7)
         {
             return id;
         }
         else
         {
             return null;
         }
     }
 }
```

### Configuration

Error occurs on .Net 7 with VS 2022 (17.7.4)

**Comment by jaredpar** [comment]
This behavior is "By Design". Once any part of an expression contains a `dynamic` element the entire expression is treated as `dynamic` including the return value. The compiler assumes that however the return value is handled is correct and will not validate that assumption until runtime binding occurs. 

The one exception to this rule is local functions. In a local function there is no ability for overload resolution to interfere with `dynamic` evaluation (there is only one answer). As such the compiler will do extra validation there.
