### ISSUE TITLE
Tidy Up after Cmd Line build and test.

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#7017]
`msbuild /v:m /m BuildAndTest.proj /p:PublicBuild=true /p:DeployExtension=false`

What can be done, so that this command cleans up after it has run.
I have 11 x `MSBuild.exe` and 12 x `VBCSCompiler.exe` still running after completion.

**Comment by jaredpar** [comment]
The MSBuild processes are by design.  

VBCSCompiler is interesting though.  That should shut down after runs of BuildAndTest.  Where are they all running from and where are you sync'd to.

**Comment by AdamSpeight2008** [comment]
Let me rerun it, so that I can get some additional info. (~20min)

**Comment by AdamSpeight2008** [comment]
Also why is running 
"C:\Users\Adam\AppData\Local\Temp\RoslynTests\e20d19cb-30bd-4851-b8d4-91034c3cc717\VBCSCompiler.exe" "-pipename:Adam.True.7NzEQzPe1iLJk90ZpzltThNlc71E626OOFHtOd9_G2k" ?

When I'm sure I redirected the Folder to `H:\Temp\RoslynTest` an SSD?

**Comment by AdamSpeight2008** [comment]
Initial post synced to latest `Future`
Also switched to a different branch synced to latest `Master` and it's the same.

**Comment by davkean** [comment]
+ @agocke  Maybe we're spawning the VBCSCompiler's in tests and not tearing them down?

The MSBuild instances will tear down after ~10 minutes. You can avoid this by passing /nodeReuse:false.

**Comment by AdamSpeight2008** [comment]
@davkean That solves the `MSBuild.exe` but not the `VBCSCompiler.exe` aspect.

**Comment by davkean** [comment]
Yep, I think VBCSCompiler is due to tests not cleaning up.

**Comment by AdamSpeight2008** [comment]
@davkean 
Just I'm looking at adding a second CPU for christmas, which double the number of threads to 24. So don't want going through the running task and killing them each time I run the command.

**Comment by davkean** [comment]
Understood, as a workaround, from the command line you can run the following after running tests:
```
taskkill /F /IM vbcscompiler.exe
```

Alternatively, you can simply run:

```
cibuild
```

Which will go through our normal CI build process and tear down the compiler servers.

**Comment by davkean** [comment]
You shouldn't need the last two parameters on your command either, you should be able to just run:

```
msbuild /v:m /m BuildAndTest.proj

```

**Comment by jaredpar** [comment]
@davkean VBCSCompiler isn't spun up as a process anymore during unit tests.   Instead it gets spun up in process on separate threads.   I changed that behavior about two weeks ago because the process management logic was incorrect and really couldn't be done correctly and test the aspects we needed to test.  

This is why I asked about where the repo was sync'd to when this behavior was observed.  If it's recent then it's not a unit test issue, it's something else entirely.  

Also in order to track this down we need to know which VBCSCompiler is being spawned repeatedly.  There are at least three candidates:

1. The version installed into MSBuild
2. The one which comes in the NuGet toolset package that builds the repo 
3. The one which results from building our solution.  

It's possible and expected that 1 and 2 are running simultaneously.  That should be it though.

**Comment by AdamSpeight2008** [comment]
@jaredpar 
The paths are
```
\Temp\RoslynTests\89afcdf6-d0f6-48e1-90bf-74a0c830f669\VBCSCompiler.exe
\Temp\RoslynTests\872cd9d3-19c8-49b3-b715-ef7035315c30\VBCSCompiler.exe
```
Version number `42.42.42.42`

**Comment by AdamSpeight2008** [comment]
Christmas came a little early, second cpu added to my workstation. Build and Test of ~8min.

**Comment by jaredpar** [comment]
I'm seeing the extra processes locally as well.  Seems like a bug in the unit tests.  Investigating.
