### ISSUE TITLE
`SemanticModel.GetAliasInfo` returns null when non named types are aliased

### ISSUE THREAD

**Issue by sagi1623** [dotnet/roslyn#70269]
**Version Used**: 

**Steps to Reproduce**:

1.  Call `SemanticModel.GetAliasInfo` for the "Point" IdentifierNameSyntax node from the parameter list in the example below

```
using Point = (int x, int y);

public class Methods
{
    void SingleParameter(Point p) { }
}
```

**Expected Behavior**:

Shuld return info about the aliased non named type.

**Actual Behavior**:

Returns null.

**Comment by jcouv** [comment]
I was surprised by this bug report because the test plan for the "alias any type" feature included verifying the `GetAliasInfo` API. So I ran the test below (added to the `UsingAliasTests.cs` file) and it ran fine. It shows that `GetAliasInfo` returns a proper result, with both the name of the alias and the target type.

I'm going to close the issue as not-repro, but please re-open if you can provide a code snippet or unittest like the one below showing the problem. Thanks

```

        [Fact, WorkItem("https://github.com/dotnet/roslyn/issues/70269")]
        public void TODO2()
        {
            var comp = CreateCompilation("""
                using Point = (int x, int y);

                public class Methods
                {
                    void SingleParameter(Point p) { }
                }
                """).VerifyDiagnostics();

            var tree = comp.SyntaxTrees.Single();
            var model = comp.GetSemanticModel(tree);
            var parameter = tree.GetRoot().DescendantNodes().OfType<ParameterSyntax>().Single();
            Assert.True(parameter.Type is IdentifierNameSyntax);
            var x = model.GetAliasInfo(parameter.Type);
            Assert.Equal("Point", x.ToTestDisplayString());
            Assert.Equal("(System.Int32 x, System.Int32 y)", x.Target.ToTestDisplayString());
        }
```
