### ISSUE TITLE
Replace string literal with `nameof`

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#7043]

**Comment by chborl** [comment]
@dotnet/roslyn-ide and @dotnet/roslyn-analysis, I would like to get your thoughts on how best to approach this based on what I've found in C# Essentials and other analyzer tools on the web, and also how I've seen nameof used in Roslyn.  Please comment on the following scenarios and possible approaches. Which ones do you think should be covered?

Scenario 1) Parameters
Look for arguments that are string literals and align with a parameter named "paramName".  Then see if that string matches any parameters currently in scope.  This is the approach taken in C# Essentials.

Scenario 2) INotifyPropertyChanged
Look for arguments that are string literals and align with a parameter named "propertyName" for the INotifyPropertyChanged case.  Then see if that string matches any members in the current type/document (syntactically)   This INotifyPropertyChanged pattern is used in our Roslyn code and WPF.

Scenario 3) Const strings
Look for declarative statements where a constant string is set equal to a string literal.  For example, public const string Field = nameof(Field).  This pattern is used frequently in Roslyn.

Scenario 4) all other cases
   Option A) Trigger on any string literal that is an argument regardless of what it's corresponding parameter name is and look for any variable you could get syntactically.
   Option B) Trigger on any string literal and look for any variable you could get syntactically.
   Option C) Trigger on any string literal and look at code completion for any matches.  This would be very expensive so would be good for a refactoring but not for an analyzer.

**Comment by alrz** [comment]
we could run a look up on any string literal that maches identifier regex, if it succeed, there is a symbol with the same name and we can offer the fix.

**Comment by jasonmalinowski** [comment]
I would avoid (or at least deprioritize) Scenario 3. That pattern is a pattern we use in Roslyn when we need a string literal but we otherwise don't really care what the value is; I'm not sure that is necessarily the case for customers. For many, the point of a constant is the value is "fixed" by some external definition (network protocol spec, for example) and renaming a constant shouldn't actually impact semantics.

For the first and second scenario, would this include an analyzer that would flag paramNames that aren't actually naming a parameter Even if restricted to just ArgumentException and ArgumentNullException, I suspect we'd find plenty of places (even in Roslyn) where we didn't have nameof yet and failed to manually update it. You'd want to fix those too, but your Scenario 1 as described wouldn't actually trigger, and those are probably the ones you want to trigger _most_ since those are actual bugs.

**Comment by chborl** [comment]
Fixed in Roslyn Analyzers repo: https://github.com/dotnet/roslyn-analyzers/pull/1367
