### ISSUE TITLE
Code Style: OptionSet API available at compiler layer for analyzer authors to use

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#7059]

**Comment by sharwell** [comment]
I believe this issue is related to the general ability of analyzers to define and/or consume configuration options at an API level. It is not necessarily the location where the user stores these options. For that, see the following for related work on actually storing these:

* #7060
* #7061
* dotnet/roslyn-analyzers-contrib#3
* [dotnet/roslyn-analyzers-contrib: Inventory of Epics](https://github.com/dotnet/roslyn-analyzers-contrib/blob/master/docs/Inventory-of-Epics.md)
* [DotNetAnalyzers/StyleCopAnalyzers: Configuration.md](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/Configuration.md)

**Comment by Pilchie** [comment]
Agreed.

**Comment by Pilchie** [comment]
Sadly, this editorconfig work isn't going to fit for 15.3, but we're going to continue targeting the next foundation update.

**Comment by jasonmalinowski** [comment]
The work of moving the API down is complete, the rest is tracked by https://github.com/dotnet/roslyn/projects/18. This bug is too vague for further handling.
