### ISSUE TITLE
Make sure that CallerFilePath returns the correct filename, even in case of partial classes, split over different files

### ISSUE THREAD

**Issue by scampsd** [dotnet/roslyn#70619]
## Background and Motivation

I have a class, split over different files, and while using `CallerFilePath` I see the path of the main definition, not of the specific one.

## Proposed API

I have a large class `Manager`, being spread over different files `Manager.cs`, `Manager.Specific1.cs`, `Manager.Specific2.cs`, ..., it looks as follows:

(In `Manager.cs`)
```
public partial class Manager:
...
    public void GenericMethod1() {}
    public void GenericMethod2() {}
...
```

(In `Manager.Specific1.cs`)
```
public partial Manager:
...
    public void SpecificMethod1.1() {}
    public void SpecificMethod1.2() {}
...
```

I add `[CallerFilePath] string filePath = ""` to the signature of one of the specific methods, so that becomes:

```
public void SpecificMethod1.1([CallerFilePath] string filePath = "") {}
...
    string filename = filePath.Substring(filePath.LastIndexOf("\\") + 1);
    Log.Debug($"Current filename=[{filename}]");
```

In the logfile, I was expecting to see `Current filename=Manager.Specific1.cs`.

What I am seeing, is: `Current filename=Manager.cs`.

Some extra remarks:

1. This bug report is a direct result of [the following StackOverflow post](stackoverflow.com/questions/77374401).
2. This is my first bug report on this website. I might have done some things wrong. In that case, please just inform me what needs to be done instead of just closing/deleting my question.

Best regards

**Comment by jcouv** [comment]
@scampsd If I understood the example properly, the code for the `Manager` class is spread across multiple files and one of the methods (`SpecificMethod1.1` in `Manager.Specific1.cs`) uses `CallerFilePath`. You're expecting that parameter to receive a value of `Manager.Specific1.cs` because that's where the method `SpecificMethod1.1` is defined.

That seems the wrong expectation. The value passed to a `CallerFilePath` parameter is the file path of the **caller** (see [spec](https://github.com/dotnet/csharpstandard/blob/standard-v7/standard/attributes.md#22553-the-callerfilepath-attribute)), so where the method is defined is irrelevant.  
The question is, where is the code that calls `SpecificMethod1.1`?

**Comment by scampsd** [comment]
The place where `SpecificMethod1.1` is called is irrelevant: I want to see the name of the file where that method is defined (which is in this case `Manager.Specific1.cs`). If ever I want to see the place where `SpecificMethod1.1` is called, I can add `CallerFilePath` to the header of that particular method.

**Comment by jcouv** [comment]
Closing as by-design. 

> I want to see the name of the file where that method is defined

That's not what `CallerFilePath` does.

However, it should be possible to use a trick with a local function:
```
void M()
{
  local();
  void local([CallerFilePath] string path = null) { }
}
```
