### ISSUE TITLE
Implicit Conversion to FormattableString Fails with Ternary Operator

### ISSUE THREAD

**Issue by qpakzk** [dotnet/roslyn#70689]
### Description

When assigning a string interpolated value to a `FormattableString` variable, implicit conversion works as expected. However, when using a ternary operator for conditional string interpolation, the implicit conversion fails, and an explicit cast is required.

### Reproduction Steps

1. Create a new console application.
2. Use the following code snippet to replicate the issue.

### Expected behavior

I think the ternary operator should implicitly convert interpolated strings to `FormattableString` without error, just like direct assignment.

### Actual behavior

An error is thrown indicating a failure to implicitly convert the type 'string' to 'System.FormattableString'.

Code Samples:

```csharp
string kr = "Korea";
string jp = "Japan";
FormattableString str = $"Hello {kr}"; // Works fine

// Fails with an implicit conversion error
FormattableString str2 = code == "KR" ? $"Hello {kr}" : $"Hello {jp}";
```

Error Message:

```sh
Error CS0029: Cannot implicitly convert type 'string' to 'System.FormattableString'
```

**Comment by CyrusNajmabadi** [comment]
I believe this is by design. Legacy ternary behavior is to always look for the type of the ternary first, and not use the target typing unless that fails. Since the type of the ternary succeeds at finding 'String' no fallback to target typing happens. 

This is unfortunate, and probably unlikely to change as adding more complexity around ternary expressions is probably not worth it.
