### ISSUE TITLE
Suggestion: Make strict mode default for C# language version 6 and up

### ISSUE THREAD

**Issue by leppie** [dotnet/roslyn#7086]
I have been recently bitten by trying to fix issues that are indeed handled correctly in strict mode, but due to bugs in the legacy compiler, the behavior has been made compatible in Roslyn.

As a conforming language is desirable, can strict mode not be enabled by default for language version 6 and up (also assuming the language version is default the latest version)?

**Comment by gafter** [comment]
@jaredpar This is possibly worth considering for the next major version?

**Comment by leppie** [comment]
A compiler flag might be nice before the next major version.

**Comment by gafter** [comment]
@leppie The features flag is supported in the project file in Update 2 (i.e. imminently).

**Comment by paulomorgado** [comment]
What is "strict mode"?

**Comment by pdelvo** [comment]
The "old" compiler did have some bugs where code would compile that should, by specification, not. To not break compatibility those bugs were also implemented in roslyn. strict mode is a mode in which the compiler does produce errors in these cases.

**Comment by paulomorgado** [comment]
How can I activate that strict mode.

**Comment by leppie** [comment]
@paulomorgado pass `/features:strict` to the commandline compiler.

**Comment by paulomorgado** [comment]
But there's no Visual Studio project switch for that. Is there?

**Comment by jaredpar** [comment]
> As a conforming language is desirable, can strict mode not be enabled by default for language version 6 and up (also assuming the language version is default the latest version)?

When discussing defaults it's important to understand there are actually several layers of default:

1. Default behavior of the C# compiler executable
2. Defaults established by options in the standard csc.rsp file 
3. Defaults established by the targets files / tasks in MSBuild 
4. Defaults established project templates 

Each of these areas establishes a defacto default for a given C# setting.  They must all come into play when considering changes to defaults, new arguments, etc ...  Need to establish what change we want for each of the cases.  

Taking a step back though there is an bigger rule we have to follow when it comes to compiler changes:

> If a user has code which builds fine today, it should build fine after installing Visual Studio updates, or updating to an entirely new version of Visual Studio: More generally speaking when upgrading the compiler. 

This is a rule we simply can't break.  Or break only when there is an overwhelming reason to do so or we're technically backed into a corner (as can happen with new versions of Visual Studio).  Breaking this prevents customer upgrades, results in lots of negative feedback and generally us scrambling to fix the unintentional break.  

This directly ties into default changes because it's **extremely** difficult to change behavior without breaking an existing customer build.  There are so many scenarios in which the compiler can be invoked that it's hard to get them all right.  For example:

- MSBuild project
- Directly invoking compiler using csc.rsp 
- Directly invoking compiler without csc.rsp 
- Make files
- dotnet cli 

Each we can guard against default changes to a degree.  But there are always gaps.  

In the case of strict by default I don't see the benefit being so large that it's worth inevitably breaking a number of customers who don't care about it (which is arguably most customers).  I'm very much in favor of making it a more prominent option to use but seems difficult to make this the default.

**Comment by MgSam** [comment]
Perhaps having Visual Studio settings that alter the default project templates would be a good way to handle this. Such settings files could be shared between team members, and this way your new projects would always contain the settings you wanted.

**Comment by mirhagk** [comment]
If this is just added to the msbuild file for new projects then you'd get the benefit moving forward while older projects would still compile. This does prevent you from copying and pasting from older projects potentially, so I guess it'd be a matter of how likely the code is vs how much the code should be discouraged.

**Comment by gafter** [comment]
Since we're not going to do this, closing.
