### ISSUE TITLE
Use Primary Constructor makes variables visible to the class that weren't before.

### ISSUE THREAD

**Issue by grosch-intl** [dotnet/roslyn#70899]
**Version Used**:  .NET 8

**Steps to Reproduce**:

Given this code:

```csharp
public class Example {
    private readonly LampContext _context;

    public Example(IDbContextFactory<LampContext> contextFactory) {
        _context = contextFactory.CreateDbContext();
    }

    public void Something() {
        _context.SaveChanges();
    }
}
```
 
and then running the Use Primary Constructor refactoring, I end up with this code.

```csharp
public class Example(IDbContextFactory<LampContext> contextFactory) {
    private readonly LampContext _context = contextFactory.CreateDbContext();

    public void Something() {
        _context.SaveChanges();
    }
}
```

**Diagnostic Id**:

IDE0290

**Expected Behavior**:

Method `Something` should not have access to the context factory.

**Actual Behavior**:

The context factory is now visible to the entire class.

**Comment by CyrusNajmabadi** [comment]
Choosing out as by design. If someone asks to make the constructor info a primary constructor, we will do so. An aspect of primary constructors *from a language level* is that the parameters are in scope for the entire type. 

So this behavior is the outcome that is being requested and is thus by design.

**Comment by CyrusNajmabadi** [comment]
> In both cases, our previously readonly field is now stored in assignable bar, changing the assignability of the item passed to the constructor.

If you assign to a field and then attempt to reassign the parameter, we will warn. 

Similarly, we will also stop even suggesting the parameter to you in completion lists. 

So the assignability is the same. Just like the original code, the parameter is not assigned to. And if you try, we warn. 

If you ask to not have the field, then you don't get this. But that's why that's not the default option, but one someone has to choose. 

> Primary constructors are a great feature but IDE0290 is being suggested in places that it shouldn't.

Ask these examples where this should be offered.

**Comment by grosch-intl** [comment]
The real fix here is that primary constructors just need a way to be able to flag as private and read-only.  In the video during your conference they even mentioned that people were talking about needing that and maybe they should implement it.  Please, implement it :)

**Comment by CyrusNajmabadi** [comment]
Providing a way to make them readonly is something we are considering.  After a lot of usage of PC and PCPs i've found i've personally not needed it.  But the interest in there.
