### ISSUE TITLE
Equals sign (`=`) no longer valid in a project name with .net8.0

### ISSUE THREAD

**Issue by mrlacey** [dotnet/roslyn#71022]
### Description

With the change to .net8.0 the equals sign (`=`) is no longer valid as part of a file name. 
It was with valid .net7.0 MAUI project and is with other .net8.0 project types.

### Steps to Reproduce

1. Create a File>New MAUI App that includes a `=` sign as part of the name and targets .net8.0
2. Try and build the generated project.
3. See it fails to build

Repeat but target net7.0 and see that it builds without issue.

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.49

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

.net8.0

### Did you find any workaround?

No workaround, other than don't use this character.

Ok, admittedly, this is a super edge case and I've never seen this character used in a real project but it raises a bunch of questions and concerns:

- Was this deliberate?
  - If so, why?
  - Where is it documented?
- If not deliberate, why was this code changed?
- Are there other characters that are no longer supported?
- Can you please provide an updated list of supported characters as part of a project name in a .NET MAUI app; And explain why it's different from other projects?

**Comment by danmoseley** [comment]
This might be the most traveled issue yet..!

**Comment by jaredpar** [comment]
This bug is occuring in `net8.0` because there is a new reference being passed to the `net8.0-android` portion of the build: `_Microsoft.Android.Resource.Designer.dll`. Not sure the purpose of this DLL but it's placed into a sub-directory of the project output. On my machine the reference looks as follows: 

> /reference:C:\Users\jaredpar\temp\maui\net8.0\Maui=App\Maui=App\obj\Debug\net8.0-android\_Microsoft.Android.Resource.Designer.dll

As @rainersigwald noted this is failing in C# parsing because it's being interpreted as an `extern alias` reference as the value has the `alias=file` form. The compiler then errors out because the alias portion isn't a valid C# identifier. This works in `net7.0` because the `_Microsoft.Android.Resource.Designer.dll` reference is not passed to the compiler. 

The behavior in the compiler is by design in the compiler and this issue would not move us to change it. Argument parsing in the compiler is already extremely complicated and adding yet another layer of escaping would require a rather compelling scenario.
