### ISSUE TITLE
Symbol loading issue in Visual Studio: 'Go to Definition' in solution with solution filters only opens metadata of class

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#71074]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Symbol-loading-issue-in-Visual-Studio:-/10527598)._

---
When using the ‘Go to definition’ feature in Visual Studio, only the metadata of the file is loaded if solution filters are used in combination with project references. This works as expected if the target project is loaded in the solution. However, if a solution filter is opened that does not include the target project, Visual Studio only opens the metadata of the class.

In the ‘Output’ window, the ‘Navigate to External Sources’ tab displays the following output:

Navigating to symbol ‘ProjectRefSymbolsLib.TestClass.TestExecute()’ from ‘ProjectRefSymbolsLib’.  
Symbol found in assembly path ‘C:\\Temp\\ProjectRefSymbolsRepro\\ProjectRefSymbolsLib\\obj\\Debug\\net8.0\\ref\\ProjectRefSymbolsLib.dll’  
Source is a reference assembly, not enough information to find PDB.

Our internal development process involves using solutions with a lot of projects and we use solution filters to make Visual Studio faster to work with. We often open solution filters that include only one or a few projects, but we still want the ability to navigate to other types in order to examine their implementations.

I have added an attachment with a repro solution. After building the entire solution, you can open the solution filter (ProjectRefSymbolsRepro\\ProjectRefSymbolsMain.slnf ). When you go to the definition of the method ‘TestExecute’, you can see that only the metadata is loaded.

---
#### Feedback Bot on 11/28/2023, 05:56 PM: 

(private comment, text removed)
#### Feedback Bot on 12/4/2023, 09:48 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
AFAICT, this is by-design.  The project is not within the solution-filter scope.  So there's no project/source to nav to.  So we navigate to the metadata.  @jasonmalinowski 

> However, if a solution filter is opened that does not include the target project, Visual Studio only opens the metadata of the class.

That seems... expected.

**Comment by desdesdes** [comment]
Normally when a project is not within the solution-filter scope it uses the pdb to locate and show the external source code. 

You can see this in the attached example where you can open the solution and use Go to definition (F12) on ```MyClassLibrary1.MyClass1.GetName()``` in the MyConsoleApp1\Program.cs file.

If you then open the MyConsoleApp1\MyConsoleApp1.csproj file and then remark
```xml
  <ItemGroup>
    <Reference Include="MyClassLibrary1">
      <HintPath>..\MyClassLibrary1\bin\Debug\net8.0\MyClassLibrary1.dll</HintPath>
    </Reference>
  </ItemGroup>
```
and unremark
```xml
  <!--<ItemGroup>
    <ProjectReference Include="..\MyClassLibrary1\MyClassLibrary1.csproj" />
  </ItemGroup>-->
```

The display of the source code when using Go to definition (F12) still works. But as soon as you unload the the ```MyClassLibrary1``` project from the solution the pdb cannot be located and visual studio falls back to displaying the metadata. So the problem is that visual studio does not locate the pdb correctly then using unloaded project references, which is does on file references (and also on nuget packages, but i have not added an example here).

[References Demo VS.zip](https://github.com/dotnet/roslyn/files/13841027/References.Demo.VS.zip)

Thanks in advance.

**Comment by desdesdes** [comment]
I am feeling that you are not reading my replies are looking at the supplied sample.

I am not asking for the same behavior between loaded and unloaded projects. I am asking for the same behavior between unloaded projects and directly referenced dll's, which would solve my issue. 

Directly referenced dll are being resolved at at compile time because intellisense knows the types it contains. This is also the case for unloaded projects. I do understand the metadata only contains the dll reference in both cases, not the source files. But hitting F12 (= Go to definition (F12)) works differently in both scenario's and the unloaded project scenario is much more unclear than the referenced dll scenario.

I would understand that this is not a scenario you are willing to invest in, but "If it is unloaded, we do not have any understanding of it beyond metadata." is not a response that would make a valid point but actually the metadata you have is enough to solve the issue.

**Comment by CyrusNajmabadi** [comment]
> but actually the metadata you have is enough to solve the issue.

The diagnostics indicate this is a ref assembly, so I'm not sure what you mean by us having enough to solve the issue. 

This is a known limitation of such assemblies, and as I mentioned above, as that's an the info we have is unclear what we could do differently here. 

What are you recommending we do in this situation?

**Comment by desdesdes** [comment]
For some reason when it is a ref assembly it finds the dll and the pdb in the same directory beside it (the location where the project file hint path points to). '

But then is an unloaded project it does find the dll (in the projects obj\Debug\net8.0\ref\ProjectRefSymbolsLib.dll folder) but ignores the pdb in the same directory. If it would locate it i would expect the same screens to popup when I hit F12.

You can see this behavior in the sample for 5 January.

Thanks in advance.
