### ISSUE TITLE
Unable to open solution in MSbuild

### ISSUE THREAD

**Issue by Ann-1024** [dotnet/roslyn#71198]
**Version Used**: 
net 6.0 Visual studio2022
"Microsoft.Build.Framework" Version="17.8.3" ExcludeAssets="runtime"
"Microsoft.Build.Locator" Version="1.6.10" 
"Microsoft.Build" Version="17.8.3" ExcludeAssets="runtime" 
"Microsoft.Build.Utilities.Core" Version="17.8.3" ExcludeAssets="runtime" 
"Microsoft.CodeAnalysis.Workspaces.MSBuild" Version="4.8.0" 

**Steps to Reproduce**:

1. clone a WPF repositories(such as https://github.com/HandyOrg/HandyControl or https://github.com/lepoco/wpfui)
2. use MSbuild to open the solution and throw error like that
  System.TypeLoadException
  HResult=0x80131522
  Message=Could not load type 'System.Runtime.Remoting.RemotingServices' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
  Source=Microsoft.Build
  StackTrace:
   at Microsoft.Build.BackEnd.TaskExecutionHost.Dispose(Boolean disposing) in Microsoft.Build.BackEnd\TaskExecutionHost.cs:line 329
   at Microsoft.Build.BackEnd.TaskExecutionHost.Finalize() in Microsoft.Build.BackEnd\TaskExecutionHost.cs:line 103

```
using Microsoft.Build.Locator;
using Microsoft.CodeAnalysis.MSBuild;

//MSBuildLocator.RegisterDefaults(); can not use, throw error as can bot find msbuild
MSBuildLocator.RegisterMSBuildPath("C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\Msbuild\\Current\\Bin");
var msWorkspace = MSBuildWorkspace.Create();
var solution = msWorkspace.OpenSolutionAsync("HandyControl.sln").Result;
```

**Comment by jasonmalinowski** [comment]
This will likely be fixed with the 4.9.0-2.final NuGet packages once we get them uploaded. Once those are, you can remove your use of MSBuildLocator since we'll be doing the right thing in potentially different processes.

Are you running in a .NET Core application? If so, that'd somewhat explain the problem with RegisterDefaults() or the error, since you'd be pulling in the .NET Framework MSBuild that VS uses into a .NET Core process, which will result in strange errors. The new packages now smartly launch processes in the background to avoid mixing things like that.

**Comment by jasonmalinowski** [comment]
And those packages are now uploaded, so @Ann-1024 can you give the 4.9.0-2.final packages a shot? You don't need to use MSBuildLocator anymore with them.

**Comment by Ann-1024** [comment]
The problem is fixed now, thanks
