### ISSUE TITLE
Poor codegen for collection expression spread (ROS<T> -> ImmutableArray<T>)

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/roslyn#71292]
Related to #71195

**Version Used**: 4.9.0-ci (https://github.com/dotnet/roslyn/commit/a8119d1e97dd6e926ad3d6599c6c15ae6e5f2a8f)

**Steps to Reproduce**:

```csharp
using System;
using System.Collections.Immutable;

static unsafe ImmutableArray<byte> Foo(byte* p, int length)
{
    return [.. new ReadOnlySpan<byte>(p, length)];
}
```

[sharplab](https://sharplab.io/#v2:EYLgtghglgdgPgAQEwEYCwAoBAGABAlAOgGEB7AG3IFMBjAFylJgGdCBJMMAVzomGoDcmTAQBsuLiwgAzKrg7de/KgEEATmogBPADzAtdKgD5cAMVKkAFPsMAqXAAcANLlh1c1GAHM6ACwCUmADemLhh+ADsuADahIS4MFQA7rgASlQQACYA8jDkWgDKDhAwegbGls4eVN5+/gC6QhgAvkA=) 

**Expected Behavior**:

```csharp
ReadOnlySpan<byte> readOnlySpan = new ReadOnlySpan<byte>(p, length);
return ImmutableArray.CreateRange(readOnlySpan);
```

**OR**

```csharp
ReadOnlySpan<byte> readOnlySpan = new ReadOnlySpan<byte>(p, length);
return ImmutableCollectionsMarshal.AsImmutableArray(readOnlySpan.ToArray());
```

**Actual Behavior**:

```csharp
ReadOnlySpan<byte> readOnlySpan = new ReadOnlySpan<byte>(p, length);
int num = 0;
byte[] array = new byte[readOnlySpan.Length];
ReadOnlySpan<byte>.Enumerator enumerator = readOnlySpan.GetEnumerator();
while (enumerator.MoveNext())
{
    byte b = (array[num] = enumerator.Current);
    num++;
}
return ImmutableCollectionsMarshal.AsImmutableArray(array);
```

cc. @RikkiGibson maybe a missed case from your other optimization work? 🤔

**Comment by RikkiGibson** [comment]
I think sharplab may not have had the spread optimization present at the time this issue was filed. Seeing the following codegen now [SharpLab](https://sharplab.io/#v2:EYLgtghglgdgPgAQEwEYCwAoBAGABAlAOgGEB7AG3IFMBjAFylJgGdCBJMMAVzomGoDcmTAQBsuLiwgAzKrg7de/KgEEATmogBPADzAtdKgD5cAMVKkAFPsMAqXAAcANLlh1c1GAHM6ACwCUmADemLhh+ADsuADahIS4MFQA7rgASlQQACYA8jDkWgDKDhAwegbGls4eVN5+/gC6QhgAvphAA===)

```cs
return ImmutableCollectionsMarshal.AsImmutableArray(new ReadOnlySpan<byte>(p, length).ToArray());
```

I'll close as no repro. Feel free to follow up here if I missed something. Thanks
