### ISSUE TITLE
Minimize using extension methods

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#71306]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Minimize-using-extension-methods/10463901)._

---
Currently, it’s a hassle to find the right NuGet package for many of the .NET Core libraries because a blatantly overwhelming amount of extension methods exists, anonymously adding “methods” to arbitrary classes.

**Extension methods testify a bad library design.**

It’s confusing, unneccessary and adds minor benefit.

If you feel you need to add methods to a class, derive from it and add methods to that derived class. Or use an object as plain first parameter, without the `this` qualifier, if single inheritance doesn’t suffice your needs. – But refrain from inventing more and more completely unrelated “anonymous” classes just for grafting new methods to another class. That’s something that should be done only for patching a running system, as a last resort.

Using .NET is more and more becoming a rocket science, making people wasting their time hunting for ideas anywhere on the Internet by anyone who allegedly knows how to solve a challenge.

So, please, get straight. Re-think and improve your framework design by getting rid of extension methods.

---
#### Feedback Bot on 9/12/2023, 10:54 PM: 

(private comment, text removed)

**Comment by vibeeshan025** [comment]
I have used .net for more than 10 years and I really liked this feature of extension methods. 

May be I am not thinking from a freshers point of view.

Are you suggesting removal of the extension methods feature. I believe it will not be possible due to the fact it has been used both by the framework and third party libraries extensively.

Any how, if you have any ideas to make it easier for new members, I love to explore new ideas.

**Comment by CyrusNajmabadi** [comment]
Closing out as this def isn't either a VS or Roslyn concern.  It appears to be a request about the design pattern of certain libraries.  But such feedback should go to those libraries, which can decide what is best for their consumers' needs.
