### ISSUE TITLE
Remove and Sort Usings across solution

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#71316]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Remove-and-Sort-Usings-across-solution/10433641)._

---
I would like an option to Remove and Sort Usings by right clicking on the Solution root and have it applied to all C# files in the entire solution.

This feature should be part of VS itself without needing to install any 3rd part extensions.

---
#### Feedback Bot on 8/8/2023, 06:47 PM: 

(private comment, text removed)

**Comment by HedgehogNSK** [comment]
I join to your request.

Please, can someone explain why this kind of formatting everytime causes difficulties?
I searched for solution more then a week already. During the search I found out that everytime there was issues: when main LSP was Omnisharp, before Omnisharp. And with new LSP Razor we have same issue. I don't want to permanently switch to Omnisharp, because, as I understood, it's obsolete. Although I've tried to switch to the Omnisharp and still there was difficulties with a such basic function for format documents in my book.

I already wrote an extension to provide this function.  But unfortunately for some reason `vscode.languages.getDiagnostics(document.uri)` returns only small amount of information for a file, that hasn't been opened yet or that just has been opened. And LSP evaluates unnecessary usings for the opened file only after several seconds. 
Is there any way to force LSP diagnostic for certain file? Or any option to subscribe to LSP diagnostic process to proceed my function after LSP finished it's diagnostics?

```ts
 return vscode.languages.getDiagnostics(document.uri)
        .filter(diagnostic => {
            let code = diagnostic.code;
            return code !== 'undefined' && code instanceof Object && 'IDE0005' === code.value?.toString();
        })
        .map(x => x.range);
}
```
If you have any suggestions for this block of code, I'd glad to read them. 

Thank you <3

**Comment by HedgehogNSK** [comment]
So I destributeed extension for fixing usings to marketplace. Hope it will be helpful to someone.
https://marketplace.visualstudio.com/items?itemName=HedgehogNSK.cscodepolisher

Also I hope that Roslyn dev team will make their own fix that will allow to work with default formatter from C# dev kit, without any other extension.

**Comment by CyrusNajmabadi** [comment]
Closing out as this is well handled by an extension.  Thanks @HedgehogNSK !
