### ISSUE TITLE
IDE0057 Fires for slice-like method calls where substitution to range operator is not valid

### ISSUE THREAD

**Issue by neon-sunset** [dotnet/roslyn#71435]
### Analyzer

**Diagnostic ID**: [IDE0057](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0057)

### Describe the improvement

Consider the following snippet:
```cs
var text = (U8String)"Привіт, Всесвіт!"u8;
var sliced = text.SliceRounding(0, 11); // An autofix is offered to change to 'suggested'
var suggested = text[..11]; // Throws exception
```

A fix suggested by `IDE0057` meaningfully changes the behavior and unexpectedly fires for a method that is neither named `.Slice` nor `.Substring`.

### Additional context

I believe while it is reasonable to assume that `.Slice` methods implemented in user code more or less achieve the same goal, the same cannot be said for methods named differently or that have `Slice{Suffix}`. By no means serious, this suggestion may promote unsound changes to developers just starting out with C# or a specific library that uses slicing.

Thanks!

**Comment by CyrusNajmabadi** [comment]
Yes.  This was intentional as there were several patterns we found where the name was not 'Slice'.  We could move to a specific allow-list.  But the feeling at the time was that it was better to be more permissive and catch more case than to be restrictive and not offer in areas where the method *was* a slice method, but had a different name.

Given the years this has been out, with only one report, i'm feeling we should just keep this as is and just have this one odd api suppress this analyzer.

**Comment by neon-sunset** [comment]
Okay, thanks. As discussed on Discord, `DiagnosticSuppressor` works for me so I'll be closing this issue.

Should someone else have the same issue - feel free to post here and I'll reopen.
