### ISSUE TITLE
Add options to disable automatically import "using static xxxxx;"

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#71464]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Add-options-to-disable-automatically-imp/10424280)._

---
For example, I have a class named `Ftp`, when I paste code, it will automatically add `using static System.Net.WebRequestMethods;`.

Reproduce step, 
```c#
using var busy = this.ShowBusy("正在删除...");
using (var ftp = await Ftp.Create())
{
    foreach (var dir in dirs)
    {
         await ftp.DeleteDir(dir);
    }
}
```

When I copy the `foreach` code and paste it above `using var busy`, the `using static System.Net.WebRequestMethods;` will be automatically added.

---
#### Feedback Bot on 7/27/2023, 07:03 PM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
Can be disabled here: 

![image](https://github.com/dotnet/roslyn/assets/4564579/f6514b7a-2c4e-4948-8e68-7e6e8193ddda)

**Comment by kg** [comment]
Came here to report a variation on this issue. For me, this specific using directive gets added randomly, *even though it's not missing or being used*:

```csharp
using static System.Collections.Specialized.BitVector32;
```

My best guess is that it's because BitVector32 exposes a public static ToString method, but I haven't been able to figure out what specific code snippet causes it since it's done silently when copying and pasting without drawing your attention. I periodically find it in my .cs files when reviewing commits and have to strip it out. It's always BitVector32 for me, and I *never* have used this type in any of my code.

It feels like there is an actual bug in this functionality, and the user shouldn't have to disable 'add missing using directives on paste' to fix it. Are there diagnostic logs I can provide to help identify why this is happening?
