### ISSUE TITLE
Update feature status and Roadmap of Roslyn project

### ISSUE THREAD

**Issue by FrankBakkerNl** [dotnet/roslyn#7158]
I try to keep up with the discussions regarding Roslyn here on Github. However right now I am a bit lost about the roadmap and current feature status. Which features are under consideration for vNext and what lies ahead. What about the features that were cut from last release?
The latest language feature overview https://github.com/dotnet/roslyn/wiki/Languages-features-in-C%23-6-and-VB-14 is about C#6 and VB 14 which are released products and the roadmap https://github.com/dotnet/roslyn/wiki/Roadmap is very hi level.
It would be nice to get an updated status quo without digging through all the discussion.

**Comment by MattGertz** [comment]
Coincidentally, some of us were just talking about this very thing.  Internally, I've been polishing up a "road ahead" set of documents for the team, which was good enough for us to start entering work items against it -- now I just need to massage the text into something postable (i.e., which does not rely on abstract local knowledge).  This will likely first take the form of a higher-level blog post, for which I already have a draft, followed by a somewhat more detailed set of directions posted here in the repo.

The exact timing will be slightly fuzzy on this -- once Thanksgiving has hit, it gets harder to get everyone together until the new year due to vacations, which in turn impacts getting the finer details documented.  But I hope to be posting something Real Soon Now.

**Comment by dhusemann** [comment]
perhaps a list a roadmap of language specs that are not tied to a version yet also.  Ecmascript has a strawman, and then specs in certain stages.  stage 3 and stage 4 are at the ecma standard level to add  to the spec.

**Comment by gafter** [comment]
@MattGertz I suspect @dhusemann is mainly interested in a roadmap for *language features*. @jaredpar is preparing the doc about our language design workflow and will publish it quite soon, after it has been reconciled with our use of issue labels on github.

**Comment by thorgeirk11** [comment]
Any news on this front?

**Comment by gafter** [comment]
We're pedaling as fast as we can. As soon as we have something a little more settled, we'll publish it.

**Comment by gafter** [comment]
We are now taking language feature discussion on https://github.com/dotnet/csharplang for C# specific issues, https://github.com/dotnet/vblang for VB-specific features, and https://github.com/dotnet/csharplang for features that affect both languages.
