### ISSUE TITLE
Primary constructor parameters do not work with MemberNotNull attributes

### ISSUE THREAD

**Issue by RenderMichael** [dotnet/roslyn#71710]
**Version Used**: 

Main branch of Sharplab

**Steps to Reproduce**:

``` csharp
using System.Diagnostics.CodeAnalysis;

public class C(object? obj)
{
    [MemberNotNullWhen(true, nameof(obj))]
    public bool Available => obj is not null;   
}
```

**Diagnostic Id**:

`CS8776`: Member 'obj' cannot be used in this attribute.

**Expected Behavior**:

No warning

**Actual Behavior**:

Warning

**Comment by jaredpar** [comment]
Believe this behavior is "By Design". The `MemberNotNullWhen` attribute only allows the name of fields and properties to be used. In this case `obj` is a parameter. Yes it's a bit of a special parameter because it's implicitly available in all members but still a parameter. If we wanted to extend the design to support this I wouldn't object. But my instinct is that if you want this type of complex behavior then capture the parameter into a field / property and use `MemberNotNull` on that. 

@RikkiGibson, @AlekseyTs

**Comment by AlekseyTs** [comment]
I agree, this is by design, parameters are not members.

**Comment by sharwell** [comment]
I changed the title, since we do still expect primary constructor parameters to work with `[DisallowNull]`, `[AllowNull]`, `[NotNull]`, `[MaybeNull]`.
