### ISSUE TITLE
When opening IntelliSense using Ctrl - J, current item is not in alphabetical order

### ISSUE THREAD

**Issue by TahirAhmadov** [dotnet/roslyn#71745]
## Summary

If a member name is already typed in and Ctrl - J is pressed, the "current" suggestion is on top, as well as suggestions which contain the current text entirely: 

![image](https://github.com/dotnet/roslyn/assets/16783987/6d0fd80c-9188-43fb-be20-164b15aaa3be)

And not among the list in its alphabetical position, like it used to be in previous versions of VS:

![image](https://github.com/dotnet/roslyn/assets/16783987/5fc10299-c782-447d-b218-5881d3406447)

## Background and Motivation

Frequently members are near each other by alphabetical order "naturally" due to their names starting with similar words. It's very easy 
to quickly jump from one member to another, such as from `ToLower` to `ToUpper`, etc.

## Proposed Feature

Restore behavior as it was in previous versions of VS - Ctrl-J places the "current" suggestion in its alphabetical position in the list.

## Alternative Designs

N/A

**Comment by CyrusNajmabadi** [comment]
@genlu please state if this is by design or not.  if so, please close out.

**Comment by genlu** [comment]
This is by design. We made this change when adding support for items from unimported namespaces. We don't want those items to overwhelm in-scope symbols in the completion list (as would happen with pure alphabetical ordering) but also want them to be easily noticeable if they are reasonably good match for what has been typed so far.
