### ISSUE TITLE
Imperfect IEnumerable<T> -> Span<T> collection expression conversion 

### ISSUE THREAD

**Issue by RenderMichael** [dotnet/roslyn#71755]
Trying out the new collection expressions on existing code, there are some areas where perf and memory allocation could be brought up to par with already-existing code.

Currently, converting from IEnumerable<T> to Span<T> goes through numerous unnecessary allocations. in [.NET 8](https://sharplab.io/#v2:CYLg1APgAgTAjAWAFBQAwAIpwCwG5lqZwB0AMgJYB2AjvkgQMyYzoDCyA3ut+sj5kywA2dABV0AMQBOAewC2AeQA2wADyiAfAAosDdRvQA3AIZKArgFMAzgEo+PDvf7coAdkmy5rGVItaT5tbEojIAglJSxgCeWjbEoVYAygAOxpSxNnT8AL5OvEj8UIJwIuLS8gByFgDu+jpweppGppa2eY4Fzi7u5V4+fgDaxMTNgVYAupl5uZ3ceclS5CYALhZEpR7y3r51KWn6o612s+gdXdwA+ugAvIfWWedu6MAWAGbGZkrLAIQP3DPZIA) and in the [current main](https://sharplab.io/#v2:EYLgtghglgdgNAExAagD4AEBMBGAsAKHQAYACdbAFgG4DizsA6AGVgEcb9aBmMzEgYQIBvEqJIExZHuQBsJACokAYgCcA9mADyAGwQAeeQD4AFOS4HDJAG4RtAVwCmAZwCUEsUPeTR6AOzL1MH41FQdjG3tnBnk1AEEVFQgAT2MXBlinAGUABwgYVJcOSQBfL3F8SXRpbDlFVQ0AOQcAdwtTbHMja1tHVzLPCu8ff3qgkLCAbQYGbsinAF1CstLB0TLslSgbABcHelqAjWDQtpy8i1net1WSAaHRAH0SAF5L5yL7vxIEBwAzCDs2m2AEIPqIVsUgA===), these are both inferior to the simple `Enumerable.ToArray` method.

Benchmark:

<details>
<summary>Benchmark code</summary>

``` csharp
// dotnet run -c Release -f net8.0 --filter "*"

using System.Diagnostics.CodeAnalysis;

using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;

BenchmarkSwitcher.FromAssembly(typeof(Tests).Assembly).Run(args);

[HideColumns("Error", "StdDev", "Median", "RatioSD")]
[MemoryDiagnoser(false)]
public class Tests
{
    public IEnumerable<object> Numbers()
    {
        yield return new string[] { "a", "b", "c", "d" };

        yield return new List<string> { "a", "b", "c", "d" };

        yield return new string[] { "adminToken2", "adminToken3", "adminToken4", "adminToken5", "adminToken6", "adminToken7", "adminToken8", "adminToken9", "adminToken10", "adminToken11", "adminToken12", "adminToken13" };

        yield return GetTokenNames();
    }

    private static IEnumerable<string> GetTokenNames()
    {
        yield return "adminToken2";
        yield return "adminToken3";
        yield return "adminToken4";
        yield return "adminToken5";
        yield return "adminToken6";
        yield return "adminToken7";
        yield return "adminToken8";
        yield return "adminToken9";
        yield return "adminToken10";
        yield return "adminToken11";
        yield return "adminToken12";
        yield return "adminToken13";
    }

    [Benchmark]
    [ArgumentsSource(nameof(Numbers))]
    public string RunFromOld(IEnumerable<string> values)
    {
        return FromOld(values);
    }

    [Benchmark]
    [ArgumentsSource(nameof(Numbers))]
    public string RunFromNewNet8(IEnumerable<string> values)
    {
        return FromNewNet8(values);
    }

    [Benchmark]
    [ArgumentsSource(nameof(Numbers))]
    public string RunFromNewMain(IEnumerable<string> values)
    {
        return FromNewMain(values);
    }

    public static T FromOld<T>(IEnumerable<T> values)
    {
        return FromCore(values.ToArray().AsSpan());
    }

    public static T FromNewNet8<T>(IEnumerable<T> values)
    {
        List<T> list = new List<T>();
        IEnumerator<T> enumerator = values.GetEnumerator();
        try
        {
            while (enumerator.MoveNext())
            {
                T current = enumerator.Current;
                list.Add(current);
            }
        }
        finally
        {
            if (enumerator != null)
            {
                enumerator.Dispose();
            }
        }
        return FromCore(new Span<T>(list.ToArray()));
    }

    public static T FromNewMain<T>(IEnumerable<T> values)
    {
        List<T> list = new List<T>();
        list.AddRange(values);
        return FromCore(new Span<T>(list.ToArray()));
    }

    private static T FromCore<T>(Span<T> values)
    {
        if (values.IsEmpty)
        {
            ThrowArgumentEmptyException();
        }
        return values[Random.Shared.Next(0, values.Length)];
    }

    [DoesNotReturn]
    private static void ThrowArgumentEmptyException() => throw new ArgumentException("'options' cannot be empty", "options");
}
```

</details>

| Method         | values               | Mean      | Allocated |
|--------------- |--------------------- |----------:|----------:|
| RunFromOld     | Syste(...)ring] [48] |  29.17 ns |      56 B |
| RunFromNewNet8 | Syste(...)ring] [48] | 101.84 ns |     184 B |
| RunFromNewMain | Syste(...)ring] [48] |  65.35 ns |     144 B |
| RunFromOld     | String[12]           |  48.91 ns |     120 B |
| RunFromNewNet8 | String[12]           | 187.63 ns |     480 B |
| RunFromNewMain | String[12]           |  89.81 ns |     272 B |
| RunFromOld     | String[4]            |  35.01 ns |      56 B |
| RunFromNewNet8 | String[4]            |  85.19 ns |     176 B |
| RunFromNewMain | String[4]            |  69.62 ns |     144 B |
| RunFromOld     | Tests(...)>d__1 [25] | 212.73 ns |     384 B |
| RunFromNewNet8 | Tests(...)>d__1 [25] | 214.77 ns |     480 B |
| RunFromNewMain | Tests(...)>d__1 [25] | 231.45 ns |     480 B |

**Version Used**: 

.NET 8, as well as current main.

**Steps to Reproduce**:

[Sharplab](https://sharplab.io/#v2:EYLgtghglgdgNAExAagD4AEBMBGAsAKHQAYACdbAFgG4DizsA6AGVgEcb9bN6B2AgbwIlhZAMxkKJAGIAnAPZgA8gBsEAHgAqAPgAU5UZq0kAbhGUBXAKYBnAJRCRg/CJfT5YAMJyZlnaYs2DBpyAIIyMhAAnjq2DCHWAMoADhAwMbYcLgC+DsK5YhJuCgBylgDuhnrYBtomZlZ2+U6uIrIKXj46ANoMDHUB1gC6Gfk5nM4i6OLokm2e3paVyamG/Q32E8LNLSQA+iQAvGs2mSJjWUA=).

**Expected Behavior**:

Collection expressions are at least as fast as the old way.

**Actual Behavior**:

Collection expressions are can't keep up in terms of perf and memory allocations.

**Comment by RikkiGibson** [comment]
This is similar to #71296, perhaps the solution should be generalized to both.

**Comment by RenderMichael** [comment]
@RikkiGibson It looks like the similarities with that issue is that `IEnumerable<T>` has a similar strategy for both. Whereas the solution to each issue that the conversion between `IEnumerable<T>` and other types should be more granular, in that issue it can convert to `ImmutableArray<T>` and in my case into a `Span<T>`.

Though I guess spans and ROS's can piggyback off of the solution for arrays.

**Comment by RikkiGibson** [comment]
Currently I think we are fine at converting collection-exprs containing IEnumerable spreads to List. We simply new-up a List and call AddRange. Maybe we don't pass the count to the List constructor but whatever, that's just work. We can get it done at some point.

Our gap right now seems to be when IEnumerable is converted to Array. We basically populate a list per the above then finally copy it into an array. Kinda bad.

As far as what we would want to do instead. Yes, for `[.. enumerable]`, `Enumerable.ToArray` will work well. We can start doing that.

For `[elems, .. enumerable]` I less sure what to do.

I think what we want is:
- before creating the array, evaluate each spread element to temp and call IEnumerable.TryGetNonEnumeratedCount. If this ever returns false then fall back to the List.ToArray strategy (general strategy for unknown length).
    - we already have various heuristics to avoid creating excessive amounts of temps for complex collection-exprs, we will reuse that here.
- To populate the array with an IEnumerable, do a runtime type test to see if it implements `ICollection<T>` where `T` is the result collection element type. If yes, then do `((ICollection<T>)elem).CopyTo(result, index)`. Otherwise, foreach and copy elementwise into the resulting array.
    - this logic sounds complex enough that we might want to synthesize a compilation-level helper. Is there a helper that does basically this job in the runtime? (copy an IEnumerable to a target array starting at a given index, using any smarts about the IEnumerable's runtime type to do it the best possible way.)

Needing to fallback to foreach for any given IEnumerable spread, and needing to possibly fallback entirely to unknown-length List at runtime, feels like a lot of codegen. Also, I am guessing that we really want to avoid evaluating the user code in two places, that will make code coverage and all kinds of other features super wacky.

This problem feels complex enough that we might want the compiler to generate a builder type which can create an array with either known or unknown length, with optimization for the known length case (a la `ImmutableArray.Builder.MoveToImmutable()`).

In fact, if ImmutableArray.Builder were able to produce mutable arrays, it might be ideal for our purpose. Which it can do with `ToArray`... if it had `DrainToArray` in addition to `DrainToImmutable`, we might be in business.

**Comment by CyrusNajmabadi** [comment]
> This problem feels complex enough that we might want the compiler to generate a builder type 

This was always the recommendation in the original proposal. Either a builder type, or just helper methods that we emit as well that our codegen can then call into. :-)

**Comment by RikkiGibson** [comment]
I think we could synthesize a type like the following. We can even make it a value type because compiler is the only user of it, we aren't worried about it being copied and getting into an inconsistent state.

```cs
internal struct __ArrayBuilder<T>
{
    private int _count;
    private int _capacity;
    private T[] _array;

    // capacity can grow, compiler chooses some default when length is not known
    internal __ArrayBuilder(int capacity);

    internal void Add(T elem);
    internal void AddRange(IEnumerable<T> enumerable);
    internal void AddRange(ReadOnlySpan<T> span);
    internal T[] DrainToArray();
}
```

I could def be missing something. But it seems like the most straightforward way to contain all this logic and would have some upsides in terms of allocs.

It seems somewhat cleaner than asking ImmutableArray.Builder to change in order to do something it's not quite designed to do, and if we need some additional thing tacked on in the future, we just add it, and if we stop needing something, we remove it.

**Comment by RikkiGibson** [comment]
At this point I am thinking, let's just knock the fix out for the `[..enumerable]` case, and set aside the multiple elements with enumerable spreads case. If it is important, users will let us know.

**Comment by DustinCampbell** [comment]
I'll keep watch here. I find that I'm spending too much time checking the generated code for various scenarios, and I think the resolution of this issue will have the positive effect of reducing my time in SharpLab. :smile:

**Comment by RikkiGibson** [comment]
Let's use this issue to track the "single spread of IEnumerable to Span" case, and use #75863 to track the "multiple spreads/elements of the same" case.
