### ISSUE TITLE
Upgrading CodeAnalysis downgrades Microsoft.Composition 

### ISSUE THREAD

**Issue by paul1956** [dotnet/roslyn#7175]
With Update 1 installed.

![image](https://cloud.githubusercontent.com/assets/12789369/11527218/6f41d93e-9894-11e5-9d68-b5e975541652.png)

Every time I upgrade some VSIX, Microsoft.Composition gets downgraded from .30 to .27.

![image](https://cloud.githubusercontent.com/assets/12789369/11527315/22cde95c-9895-11e5-97ee-c5f8709c556e.png)

**Comment by jaredpar** [comment]
CC @amcasey and @agocke.  It's a NuGet issue that may be related to the items you're working on.

**Comment by davkean** [comment]
We have "must be this version" dependency here?

**Comment by amcasey** [comment]
Microsoft.CodeAnalysis.Workspaces.Common.nuspec has 
```
<dependency id="Microsoft.Composition" version="[1.0.27]" />
```

**Comment by amcasey** [comment]
@jmarolf updated it from
```
<dependency id="Microsoft.Composition" version="1.0.27" />
```

**Comment by davkean** [comment]
@jmarolf Why do we explicitly specify a version?

**Comment by jmarolf** [comment]
Because we do not work with the newer versions.  I believe @jasonmalinowski first discovered this problem.

**Comment by davkean** [comment]
Where are the bugs on this? This is a problem if we don't work with the newer versions as they are supposed to be compatible.

**Comment by jasonmalinowski** [comment]
I don't know why we wouldn't work with a newer version. At one point when we were pre-release I specified exact versions for our dependencies that were on pre-release packages because we were breaking APIs all the time and it was almost assured that a different version would fail miserably. But since this is stable we should be great.

I suspect this was an over-aggressive codefix that just made them all fixed versions in the name of consistency.

**Comment by jasonmalinowski** [comment]
@agocke, @amcasey: I believe we were doing a respin of the NuGet packages, right? Any chance we can get the fix in for this too?

**Comment by amcasey** [comment]
@jasonmalinowski The fix is just to drop the square brackets?

**Comment by jasonmalinowski** [comment]
Yes.

**Comment by agocke** [comment]
@jasonmalinowski would you or John like to volunteer to make this change?

**Comment by jasonmalinowski** [comment]
Oh never mind, this was changed to #3973. That bug should have been Won't Fixed, since the NuSpec was correct. The "real problem" was either NuGet or MSBuild failed to generate the binding redirects they should have generated which would have made @KirillOsenkov's life easier.

@KirillOsenkov: do you know why you didn't get the redirects in that case?

**Comment by davkean** [comment]
Yep, please undo that change, all dependencies should be open ended.

**Comment by amcasey** [comment]
I've undone the change.  The fix should be included in our next version.

**Comment by KirillOsenkov** [comment]
Ouch. Sorry. I didn't know what I was doing.

**Comment by paul1956** [comment]
I should add upgrading Microsoft Composition downgrades CodeAnalysis.*, you get to pick which one you want to upgrade.

**Comment by davkean** [comment]
This has been fixed.
