### ISSUE TITLE
IDE0305 suggests changing away from dedicated ToArray method

### ISSUE THREAD

**Issue by stephentoub** [dotnet/roslyn#71788]
**Version Used**: 
Version 17.10.0 Preview 1.0 [34516.246.main]

**Steps to Reproduce**:
```C#
public class C
{
    public int[] M(object o)
    {
        if (o is IProvidesArrays<int> pa) return pa.ToArray();
        return null;
    }
}

interface IProvidesArrays<T> : IEnumerable<T>
{
    T[] ToArray();
}
```

**Diagnostic Id**:
IDE0305

**Expected Behavior**:
Either no IDE0305, or `[.. pa]` would compile down to using `pa.ToArray()`.

**Actual Behavior**:
IDE0305 triggers, suggesting rewriting `pa.ToArray()` to `[.. pa]`, and then that compiles down to:
```C#
		List<int> list = new List<int>();
		list.AddRange(arrayProvider);
		return list.ToArray();
```

We have an interface like this in the implementation of LINQ, where lots of the operators implement this interface to more efficiently produce arrays; if they were to switch to the suggested syntax instead, it would significantly reduce efficiency.

**Comment by RikkiGibson** [comment]
It may be reasonable to say that if the type has some method ToArray returning an array which is callable with no arguments..that it's perhaps the best way to convert the type to an array. However, I am starting to get slightly concerned about how far the compiler is willing to assume about "non-well-known" types in order to optimize things here.

Let's try to rationalize the IDE view and compiler lowering view of these scenarios. Basically, it feels like when IDE recommends to change something to collection-expression, it is assuming that compiler can or should generate code which is equally good. If we review the criteria the IDE feature is using here, then perhaps we can anticipate more of these bugs before they are reported. And, it's possible we will discover that the IDE recommendation is making some assumption that the compiler layer is not willing to make, at which point we will have to decide whether it is fine to simply not optimize there, or if IDE and compiler need to come to some sort of compromise in order to give the best holistic user experience.

**Comment by CyrusNajmabadi** [comment]
> or if IDE and compiler need to come to some sort of compromise in order to give the best holistic user experience.

Basically, teh feedback from teh compiler in the past is: we won't give you an api to know if we optimize things.

That leaves IDE in a bad place wrt to making any sorts of decisions.  We can either not have any of these sorts of features, because we have no idea what is going on.  Or we can try to understand exactly what the compiler is doing, fragily trying to reimplement the exact set of checks you do in order to determine this stuff.

Our position so far is: we're not really willing to do that.  If there's an api we can use, great, we'll switch to that.  Otherwise, we'll take an approach of saying: this patterns seems very normal/reasonable.  So we'll show you how to write it idiomatically, and our hope is that idiomatic forms should result in good perf.  If idiomatic forms do not, that is something that will confuse a user, so it's on us to invest in.

**Comment by CyrusNajmabadi** [comment]
For now, i'll work on a workaround on the IDE layer with either a whitelist or blacklist.

**Comment by CyrusNajmabadi** [comment]
@stephentoub can you point me to the def of this interface?

**Comment by stephentoub** [comment]
> @stephentoub can you point me to the def of this interface?

https://github.com/dotnet/runtime/blob/main/src/libraries/System.Linq/src/System/Linq/IIListProvider.cs

**Comment by manfred-brands** [comment]
The IIListProvider interface was removed in https://github.com/dotnet/runtime/pull/98969/files#diff-93d0cff8990ba07edecc55e2f77aaff5d5be22b6ab155740ebd1ebf70ab8cfbd

How does this affect this?

**Comment by dzhukovsky** [comment]
@CyrusNajmabadi

@akhera99, @sharwell FYI
(tagging as reviewers of PR #71796)

Hi, this issue isn’t resolved yet. Could we reopen it?

When casting collections such as `ICollection<T>` or `IReadOnlyList<T>` to arrays using the spread operator, the IL code generated enumerates the collection via `IEnumerable` and `foreach` rather than calling `.ToArray()`, which also triggers an IDE diagnostic.

**Example:**
```cs
ICollection<object> collection = [1, 2, 3];
object[] array = [..collection];
```

**Diagnostic Id:**
IDE0305

**Expected Behavior:**
Either no IDE0305 diagnostic, or compilation should use `collection.ToArray()`.

**Actual Behavior:**
The compiler generates IL code like this:

```cs
ICollection<object> metadata = error?.Metadata;
int index = 0;
object[] objArray = new object[metadata.Count];
foreach (object obj in (IEnumerable<object>)metadata)
{
    objArray[index] = obj;
    ++index;
}
```
This creates inefficiencies and doesn’t match the typical behavior of `.ToArray()`.

**Comment by CyrusNajmabadi** [comment]
The position we have is that hte compiler should generate efficient code for idiomatic C# patterns.  That includes calling .ToArray if appropriate.  I believe there are already existing issues on the compiler tracking this.
