### ISSUE TITLE
Expose directive APIs on CSharpSyntaxTree

### ISSUE THREAD

**Issue by davidfowl** [dotnet/roslyn#72]
I'd love to access this member without using private reflection:

https://github.com/dotnet/roslyn/blob/b6484300dfafb43af0c27e542ec457a7583e1aa8/src/Compilers/CSharp/Portable/Syntax/CSharpSyntaxTree.cs#L116

The use case is the DNX compiler. I'd like to be able to do more efficient cross compiling (per target framework) by reusing syntax trees that are don't contain #ifdefs.

https://github.com/dotnet/roslyn/blob/b6484300dfafb43af0c27e542ec457a7583e1aa8/src/Compilers/CSharp/Portable/Syntax/CSharpSyntaxTree.cs#L136

**Comment by jaredpar** [comment]
Chatted a bit with @davidfowl about this request.  The end goal here is to make it easy to share SyntaxTree values between compilations when there are no `#ifdef / #else / etc ...`.  This helps support their cross compilation goals.  

The particular item mentioned here, `_hasDirectives` doesn't quite meet this goal.  It is really tracking whether or not any directive is present in the file.  That includes `#pragma, #region, etc ...` which have no impact on cross compilation.  

Instead in order to support this scenario, and many others, we should add a new API of roughly the following form:

```csharp
public IList<DirectiveTriviaSyntax> GetDirectiveTokens();
```

This API would make it easy to detect the items that inhibit sharing SyntaxTree items between Compilation values.

**Comment by AlekseyTs** [comment]
@davidfowl, @jaredpar It feels like this already can be achieved with:
```
tree.GetRoot().DescendantNodes(descendIntoTrivia:true).OfType<CSharp.Syntax.DirectiveTriviaSyntax>().ToArray();
```

**Comment by jaredpar** [comment]
@AlekseyTs the concern with that is the cost of descending the tree for values which are already present on the SyntaxTree value.

**Comment by AlekseyTs** [comment]
@jaredpar I am not sure I am following. Let's talk offline.

**Comment by jaredpar** [comment]
It turns out we already have the API: [SyntaxNode.ContainsDirectives](http://source.roslyn.io/#Microsoft.CodeAnalysis/Syntax/SyntaxNode.cs,803ffe303a53c668,references).  

This API can be called on any `SyntaxNode` (or `SyntaxToken`) and reports if there are directives inside the span of the node.  Calling it on the root will give you information for the entire file.

Note: this will return whether there is any type of directive: `#region`, `#if`, etc ...  It's possible the code may want to filter further to see if there is any directive which could effect cross compilation.
