### ISSUE TITLE
CallerMemberName doesn't recognize local functions

### ISSUE THREAD

**Issue by stephentoub** [dotnet/roslyn#72095]
**Version Used**: 
Version 17.10.0 Preview 2.0 [34611.17.main]

**Steps to Reproduce**:
```C#
using System.Runtime.CompilerServices;

internal class Program
{
    private static void Main()
    {
        A();

        static void A() => B();

        static void B([CallerMemberName] string? caller = null) => Console.WriteLine(caller);
    }
}
```

**Expected Behavior**:
Prints `A`

**Actual Behavior**:
Prints `Main`

Is this expected behavior? I can see an argument for why it behaves the way it does (a local function isn't a "member"), but it's not what I was expecting, since even though it's called "member", I think of it logically as who is your calling function/method, and A is the calling function here.

**Comment by Youssef1313** [comment]
This was explicitly done in https://github.com/dotnet/roslyn/pull/14551

**Comment by stephentoub** [comment]
If this is by design, what mechanism can be used to get the local function? Or if the local function's name is needed, a local function shouldn't be used?

**Comment by jaredpar** [comment]
Looked through the history and it appears that we deliberately decided to exclude this because it's not a _member_ and `[CallerMemberName]` is only supposed to work with _members_. The current behavior puts it more in line with other function local constructs like lambdas, expression trees, etc ... The current implementation is in line with the original spec intent of the feature.

I agree it's non-intuitive though. The first few times I hit this I expected it to print the local function name, or perhaps the local function name prefixed with the member. Changing it at this point would be a breaking change as the behavior's been in place since ~2016. We could consider a new attribute here but that feels a bit heavy.
