### ISSUE TITLE
Symbol Display does not display the name for a parameter symbol unless SymbolDisplayParameterOptions.IncludeName is specified

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/roslyn#7211]
From the title, it might initially seem like the behavior is correct, but it's actually a misuse of the `SymbolDisplayParameterOptions`. Consider the following code:

```C#
class C
{
    void M(int p) { }
}
```

Given the parameter symbol, `p`, calling `ToDisplayString()` will return the following:

```
"int"
```

This is especially bizarre because `SymbolDisplayParameterOptions.IncludeType` is *not* specified by default.

By default, `SymbolDisplayTypeQualificationStyle.NameOnly` is specified, which should affect the symbol that that `ToDisplayString()` is being called for. `SymbolDisplayParameterOptions` should control the display of any parameters owned by that symbol, not the symbol itself if it happens to be a parameter.

**Comment by gafter** [comment]
This is by design. I suspect we don't fully understand the intended behavior.

`SymbolDisplayTypeQualificationStyle.NameOnly` is to control how types are qualified (or not). It should not affect how the main symbol is displayed (unless the main symbol is a type).

The symbol display format is organized into sets of options, each set for a different subset of symbols or aspect. parameterOptions is the only one that is intended to affect the handling of parameters.

For a `ParameterSymbol` *p*, calling [`p.ToDisplayString()`](https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Portable/Symbols/Symbol.cs#L599-L602) [uses the default format](https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Portable/SymbolDisplay/SymbolDisplay.cs#L70), which is defined as follows in [`SymbolDisplayFormat.cs`](https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/Portable/SymbolDisplay/SymbolDisplayFormat.cs#L13-L32):

```cs
        /// <summary>
        /// Formats a symbol description as in a C# compiler error message.
        /// </summary>
        public static SymbolDisplayFormat CSharpErrorMessageFormat { get; } =
            new SymbolDisplayFormat(
                globalNamespaceStyle: SymbolDisplayGlobalNamespaceStyle.OmittedAsContaining,
                typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameAndContainingTypesAndNamespaces,
                propertyStyle: SymbolDisplayPropertyStyle.NameOnly,
                genericsOptions: SymbolDisplayGenericsOptions.IncludeTypeParameters,
                memberOptions:
                    SymbolDisplayMemberOptions.IncludeParameters |
                    SymbolDisplayMemberOptions.IncludeContainingType |
                    SymbolDisplayMemberOptions.IncludeExplicitInterface,
                parameterOptions:
                    SymbolDisplayParameterOptions.IncludeParamsRefOut |
                    SymbolDisplayParameterOptions.IncludeType,
                // Not showing the name is important because we visit parameters to display their
                // types.  If we visited their types directly, we wouldn't get ref/out/params.
                miscellaneousOptions:
                    SymbolDisplayMiscellaneousOptions.EscapeKeywordIdentifiers |
                    SymbolDisplayMiscellaneousOptions.UseSpecialTypes |
                    SymbolDisplayMiscellaneousOptions.UseAsterisksInMultiDimensionalArrays |
                    SymbolDisplayMiscellaneousOptions.UseErrorTypeSymbolName);
```

As you can see, the type is to be included and the name is *not* to be included for parameters.

**Comment by DustinCampbell** [comment]
I can imagine that `SymbolDisplayTypeQualificationStyle.NameOnly` shouldn't control parameters, but it still seems very inconsistent. For example, why are method names returned by the format above?

I'm OK with the by design, it just didn't match my expectations, and I'm a little bit (though not terribly) concerned with the inconsistency of various member names being returned by `ToDisplayString()`. This seems a bit fishy to me.

**Comment by gafter** [comment]
> why are method names returned by the format above

Members, such as methods, have their names included always. It is not optional.

**Comment by DustinCampbell** [comment]
But not properties, there's an option for that? `SymbolDisplayPropertyStyle.NameOnly` :smile:

**Comment by gafter** [comment]
No, you always get the *name* for a property. That option lets you suppress other stuff.

**Comment by DustinCampbell** [comment]
Well, then why does `SymbolMemberDisplayOptions.None` have a doc comment that says, "Includes only the name of the member."? Why isn't it `SymbolMemberDisplayOptions.NameOnly` like `SymbolDisplayPropertyStyle.NameOnly`?

Can't we just say they're inconsistent and live with it? :smile:

**Comment by DustinCampbell** [comment]
Seems like #7201 is suffering by this particular design as well.

**Comment by gafter** [comment]
Um... yes.
