### ISSUE TITLE
Completion: list partial classes after "partial class"

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#7213]
```C#
namespace blah
{
    partial class $$
}
```

Would be nice to see a builder and a list of all the partial classes in my namespace.

**Comment by rchande** [comment]
We already do something similar for methods.

**Comment by Pilchie** [comment]
Also namespaces after `namespace`.  We should show existing names as well as a builder.

**Comment by diryboy** [comment]
+1, I like the idea.

**Comment by lorcanmooney** [comment]
I'd like to try and implement this over the next few weeks. If there are no objections, I'll get started with the partial class scenario since there's already an implementation for VB which I can refactor/port. That should give me enough experience to work on the new namespace provider.

**Comment by Pilchie** [comment]
Love it!  Definitely, and let us know if you have any questions. @rchande, @DustinCampbell and I should be able to help

**Comment by lorcanmooney** [comment]
- [ ] Refactor and port PartialTypeCompletionProvider.vb for C# - **[In Progress](/lorcanmooney/roslyn/tree/issue7213)**
- [ ] Implement namespace provider for C#
- [ ] Implement namespace provider for VB

**Comment by lorcanmooney** [comment]
@Pilchie @rchande You both mention a "builder" in your comments. Mind explaining what this refers to, and how it differs from regular completion lists?

**Comment by rchande** [comment]
@lorcanmooney: The builder (AKA "suggestion mode") is a UI affordance we have to make it easier for users to type items that aren't in the completion list. You see it in action if you hit CTRL-ALT-{space} with the completion list open. It adds a field to the top of the list that displays what the user has currently typed, or a tooltip if nothing has been typed. When the builder is first displayed, character that normally commit the selected item based on filtering (like "."), instead insert the contents of the builder. 

If you want to see other builder examples, check out `SuggestionModeCompletionProvider`.

**Comment by lorcanmooney** [comment]
Got it, thanks! I must admit, I never noticed the subtly of the modes in `SuggestionModeCompletionProvider`.

So, just to be clear, the intent in both of the above scenarios is to _always_ show the builder, regardless of the users suggestion mode preference?

**Comment by Pilchie** [comment]
Yes, because in this case you the syntax is ambiguous - you could be *either* introducing a new name, or referring to an existing name. In those sort of cases we force the builder to be on, so as not to interfere with typing muscle memory for people who are typing new names.

**Comment by lorcanmooney** [comment]
I've been working on the namespace completion, by updating `CSharpRecommendationService` to understand this scenario, but I've hit a small problem.

Take a file with an existing namespace declaration, and start a new declaration before the existing one. Because the braces are missing/unbalanced until the user completes the declaration, the existing namespace will be parsed as a child of the new namespace, even though it may turn out to be a peer depending on where the user puts the missing closing brace. Based on that, I think the name of the existing namespace should be included in the recommendation list.

It's easy enough to detect this case and include the correct sub-namespaces. However, using the existing source-symbols results in a misleading tooltip for the user:

![symbols](https://cloud.githubusercontent.com/assets/13181165/15807385/0975fe74-2b55-11e6-9fb4-b70334cf78b3.png)

So, my question: is it possible to synthesize a symbol with the correct full name for a scenario like this? (And all the other implicit questions: if so, would it be correct, is it worth the hassle, etc.)

**Comment by DustinCampbell** [comment]
I would argue that it's not worth the hassle. IMO, the proper way to address this would be to change the parser recovery, but I don't think it's worth it. We do our best to make broken code scenarios behave sensibly to the user but there is definitely a point of diminishing returns.

**Comment by lorcanmooney** [comment]
As it turns out, finding all the potential candidates in this error-scenario involved a lot of convoluted code for recursively walking up then down all the possible declaration nestings. And that's without considering the symbol issue described above. Between this and @DustinCampbell's suggestion that a proper fix would go elsewhere, I agree that it's not worth the trouble. In the end, the only time this problem will show up is if that subsequent namespace is _only_ declared in the file being edited.

I've opened PR #11786 with this bit of special-casing removed, but I've left a couple of commented-out tests cases if anyone want's to get a feeling for the cases that would need to be handled.
