### ISSUE TITLE
Do the CodeModel tests need to be WpfFacts?

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#7214]
See https://github.com/dotnet/roslyn/pull/7212/files#r46619069

/cc: @DustinCampbell @jasonmalinowski

**Comment by jasonmalinowski** [comment]
Fixing this right now. The answer: no.

**Comment by jasonmalinowski** [comment]
The answer actually changed: yes. Any test that creates CodeElements is affinitized because the node table is affinitzed to a UI thread, and that's not something I was comfortable removing. When I did the WpfFact -> Fact thing I updated my tracking code to be aware of this dependency. It's something we can do at a later date but I think isn't worth fixing for now.
