### ISSUE TITLE
VB Syntax is too sensitive

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#72190]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VB-Syntax-is-too-sensitive/10584135)._

---
As soon as I type the opening double quote for a string, all my collapsed routines below it automatically expand. This ruins my navigation and organization. This behavior has existed for a long time, but now it seems faster in 17.8.6. 
I like the syntax checking. It is what keeps me from switching to C#, but can it be toggled to wait until the line is completed. Pop up intellisense is good, but everything else can wait.

---
#### Feedback Bot on 2/16/2024, 10:55 PM: 

(private comment, text removed)
#### Wenwen Fan [MSFT] on 2/18/2024, 05:03 AM: 

(private comment, text removed)
#### Ed Lyons on 2/18/2024, 09:43 AM: 

(private comment, text removed)
#### Wenwen Fan [MSFT] on 2/18/2024, 11:13 PM: 

(private comment, text removed)
#### Ed Lyons on 2/20/2024, 11:36 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
We've discussed this in teh past.  Basically, our position is really that this is the experience you get when you do not have brace matching on.  If you have brace matching on, you'll be fine:

![image](https://github.com/dotnet/roslyn/assets/4564579/a1d1b7d1-64ca-4f10-a71c-7ab1fed96ddd)


I tried the scenario the user has `public shared name as string = "`  and i get the expected behavior where the quote completes out.   Attaching gif:
