### ISSUE TITLE
[Bug]: Building a .NET Core Function SDK 8.0.201 on a MAC with M1 chip

### ISSUE THREAD

**Issue by HeHubo** [dotnet/roslyn#72393]
### Issue Description

Currently I getting an error while try to build my azure function project with the .NET SDK 8.0.201. I use an MAC with an M1 chip. On a Windows device with windows 11, the build runs successful.

![image](https://github.com/dotnet/msbuild/assets/61828377/bafa7967-6e8b-4f28-80d2-54a5e42a89a4)

I try many thinks to fix this error:

- Reinstall SDK
- Reinstall Rider
- Reset and a complete new installation of the Mac OS

### Steps to Reproduce

- Open the project
- Build in Jetbrains Rider or VS Code
- getting this error

### Expected Behavior

should compile ;-)

### Actual Behavior

Error CS 8078 occurs

### Versions & Configurations

MSBuild version 17.9.4+90725d08d for .NET
SDK 8.0.201

**Comment by jaredpar** [comment]
Unfortunately on .NET 8 and earlier the default stack size on Mac machines is much smaller than Windows / Linux. That means the compiler, which is naturally recursive in places, can run into limitations on Mac that it doesn't hit on other OS. That appears to be what is happening here.

If possible would you be able to share the file in question here? I want to see if there is a particular pattern that we could recommend the function team change to make it harder to hit this issue. 

Note: in .NET 9 the situation should improve as the runtime team took steps to [normalize stack space][size] across OS

[size]: https://github.com/dotnet/runtime/pull/98007

**Comment by HeHubo** [comment]
The problem is that I can't tell exactly which file or files are causing this error. Only a reduction of the files in the function project brings success. Perhaps the problem could also come from the fact that our function has between 300 and 400 APIs. I am not aware of any complex code that could cause this stack overflow.

**Comment by jaredpar** [comment]
@HeHubo based on the screen shot it's from a generated file called GeneratedFunctionExecutor.g.cs. I'm not 100% sure what is producing that but the file will either be in one of two places: 

1. Inside the `obj` directory, maybe in `obj\Debug`. 
2. If a source generator file then passing `-p:EmitCompilerGeneratedFiles=true` on the command line will put the file in the `obj` directory

If this is code you can share out I'm happy to take a quick look at it and just find the file for you. If you need to share privately can file a VS Feedback issue, post the link here and we can get it going from that point.

**Comment by HeHubo** [comment]
After I setting the EmitCompilerGeneratedFiles property in the project file, the build creates the file with the error.

![image](https://github.com/dotnet/roslyn/assets/61828377/28bcbc41-0f57-4a3d-975b-ba61af2c31ea)

Here is the file:
[GeneratedFunctionExecutor.g.cs.zip](https://github.com/dotnet/roslyn/files/14534256/GeneratedFunctionExecutor.g.cs.zip)

**Comment by jaredpar** [comment]
@cston looking at the generated code here, i'm not seeing the usual candidates for why the compiler hits stack limits. There is a very long chain of `else if` in an `async` method but I'd be surprised if that caused deep stack recursion.

**Comment by cston** [comment]
It looks like the parser will fail if there are too many `else if` cases.

For instance, the following results in `error CS8078: An expression is too long or complex to compile` beyond a certain number of cases, even with earlier builds of the compiler.
```csharp
class Program
{
    static void F(int i)
    {
        if (i == 0) { }
        else if (i == 0) { }
        else if (i == 0) { }
        else if (i == 0) { }
        /* ... */
    }
}
```

**Comment by jaredpar** [comment]
That seems like something we should fix. There are limits that are hard to fix with nested exprs but chained statements like this should be oka.y

**Comment by cston** [comment]
An `else if` statement is represented as an `if` statement nested in the enclosing `else`. To remove the limit on the number of `else if` cases, we'll need to update the parser and also update binding and lowering to handle arbitrarily deeply nested `IfStatementSyntax`.

**Comment by Solxanich** [comment]
Also experiencing this chained `else if` on tModLoader project.
Wondering if there is an estimated timeline on this?

We had to forcefully downgrade to SDK 8.0.102 for our project to build in CI, so we do have a workaround, but it sounds like this could show up again if cross a magic number of chain length.  
https://github.com/tModLoader/tModLoader/commit/0eb2a4cd3e1fbd61ef1a4120412a40408abf0f97

Erroring build:
https://github.com/tModLoader/tModLoader/actions/runs/8023721868
![image](https://github.com/dotnet/roslyn/assets/59670736/e1d22cf7-5a16-4ca1-a19f-00d8611cefbd)

Referenced line is ~75% way through an `else if` chain spanning 8000+ lines / 600+ else-if.  

We've also observed that Visual Studio based Build / Debugging does not trigger this issue compared to `dotnet build`. Not sure what exactly is different, but may be useful?

**Comment by jaredpar** [comment]
> Wondering if there is an estimated timeline on this?

A fix for this is likely to show up in the VS 17.11 / .NET SDK 8.0.300 timeframe. 

> https://github.com/tModLoader/tModLoader/actions/runs/8023721868

How do you get the source for that file? 

> We've also observed that Visual Studio based Build / Debugging does not trigger this issue compared to dotnet build

That is a little surprising. The original bug filed here was due to compiling on Mac. The stack size on a Mac is significantly smaller than Windows / Linux hence hitting stack limitations in the compiler is more common there. The same stack size applies to `msbuild` and `dotnet build` on Windows. Having one crash and one not suggests the code was already right on the edge of the Windows limit but a subtle change in the new compiler pushed it over the limit.

**Comment by Mirsario** [comment]
> A fix for this is likely to show up in the VS 17.11 / .NET SDK 8.0.300 timeframe.

Great to hear!

> How do you get the source for that file?

The actual source file causing us the error comes from a game modding project, which, while open source in patch form, we aren't allowed to *publicly* distribute the source files for. I can provide the source-code privately via email if you would like.
*Or, if by chance you happen to own a [Steam Windows copy of Terraria](https://store.steampowered.com/app/105600) - the basic instructions for using our development setup tool (decompiler + patcher) are [here](https://github.com/tModLoader/tModLoader/wiki/tModLoader-guide-for-contributors#code-patcher).*

Since we operate on patches, it's not very ideal for us to introduce new ones to split up functions into smaller parts, but we may do that in this case, as it seems like it's only one function that is failing to compile. That comes to my surprise however, as *a lot* of the game's logic happens to be unbelievably large else-if chains, and so yes, our project has most likely always been close to the compiler's limits. 🙃

**Comment by jaredpar** [comment]
> I can provide the source-code privately via email if you would like.

You can send to jaredpar@microsoft.com or open a VS feedback ticket, upload there and post a link in this issue. Either works for me.

**Comment by cston** [comment]
To support arbitrary length chains of `else if` statements, we'll need to update various visitors in the compiler that walk syntax or bound nodes to avoid recursion for nested `if` statements. The set of visitors includes:
- `LanguageParser`
- `Binder`
- `LocalBinderFactory`
- `LocalRewriter`
- `Optimizer`
- `AbstractFlowAnalysis`
- `CSharpOperationFactory`

**Comment by CyrusNajmabadi** [comment]
@cston for the ide, the set would also need to handle SyntaxWalker and SyntaxRewriter.  Ide will likely die immediately due to our dependency on those compiler types, and their recursive behavior.

**Comment by hamza-abdullah-ss** [comment]
We have observed that when using `MSBuild` instead of `dotnet build` the build completes successfully, I assume this is what VS is using internally as well? and therefore why people including us can't recreate in the IDE

**Comment by hamza-abdullah-ss** [comment]
And in our case it seems to be linked with the number of Azure Functions we have 500+ in the project

**Comment by vinid223** [comment]
We are having the same issue after migrating our Azure Function App from .net 6 in-process to .Net 8 isolated.

As a workaround for now, downgrading the package Microsoft.Azure.Functions.Worker.Sdk to 1.16.2 seems to do the trick. It starts failing to build starting in version 1.16.3.

It's definitely not a fix, but it allows the build to work.

**Comment by LloydNicholson** [comment]
We are getting this issue due to using this library -> `<PackageVersion Include="Microsoft.DurableTask.Generators" Version="1.0.0-preview.1" />`

There is a large `else if` block inside `GeneratedFunctionExecutor.g.cs` and it's failing due to the large number of functions in our project and this is causing the issue. Removing the above package and using the manual process `CallActivityAsync("executorName")` would solve this issue but it's not ideal.
