### ISSUE TITLE
Error rewriting expression tree with converted nullable enum literals

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#7241]
Source: http://stackoverflow.com/questions/34085367/why-does-roslyn-crash-when-trying-to-rewrite-this-lambda-visual-studio-2015-up

This bug is a regression over the VS 2015 RTM behavior.  Here is a sample of the problem:

``` csharp
using System;
using System.Linq.Expressions;

namespace Bug461
{
  class Program
  {
    enum Test { }

    static void Main()
    {
      Expression<Func<Test?, bool>> x = t => t == (Test?)null;
    }
  }
}
```

**Comment by cyanite** [comment]
I updated my PR to fix this.

**Comment by davkean** [comment]
Workaround for this bug, is to change ```(Test?)null``` to ```default(Test?)```.

**Comment by cyanite** [comment]
Another workaround is to remove `(Test?)`, although it does generate a somewhat different expression tree. In general, there are several differences in the generated expression trees compared to the pre-Roslyn compiler. Some of them are not easy to fix (since they can't be distinguished in the rewrite code).
