### ISSUE TITLE
Select clause sometimes copies range variable to local in generated method

### ISSUE THREAD

**Issue by jhinder** [dotnet/roslyn#72417]
**Version Used**: 4.10 / "main (19 Jan 2024)"

**Steps to Reproduce**:
Inspect the generated IL for the code below.

```csharp
public IEnumerable<string> QuerySyntax(IEnumerable<int> i) {
    return from x in i select x.ToString();
}

public IEnumerable<string> LinqMethods(IEnumerable<int> i) {
    return i.Select(x => x.ToString());
}
```

[Sharplab](https://sharplab.io/#v2:EYLgtghglgdgPgAQAwAIEEYAsBuAsAKGTXQDoAZWARz3wIQGY0AmFAYRQG8CUe1GN6AHgxIAfCgCKAVwCmAJwCeAZQUwALhAAeACgGDYa8VACUnbrwsIA7CgBmcgPZgUmlLDcoAzjIA2MgMZqLiQAKg5KanKwAObaxjQWAL4E5jwMxEIi4hQwlACyMmoAFg4AJp666EIGRqZc+BaWNlAkSr4BatquALzimqHhkTFx8akoyfiJQA=)

**Expected Behavior**: Both generated methods for the select expression have the same IL in release mode.

**Actual Behavior**: In the variant using the query syntax there's an additional copy of the input parameter (`int num = x`), whereas the Linq method variant does not produce such a copy.

Interestingly this does not happen every time, for many other expressions this copy does not occur.

**Comment by CyrusNajmabadi** [comment]
Query parameters are readonly.  So it's possible the compiler is injecting a copy to ensure that the original is not mutated.  That said, i thought we also knew that certain methods (like `Int32.ToString()`) won't mutate, and thsu we can avoid the copy.

(I may also be way off as to what's going on here).

**Comment by jaredpar** [comment]
> Both generated methods for the select expression have the same IL in release mode.

That is not the correct expected behavior though. As @CyrusNajmabadi noted, the range variable here is unasisgnable (similar to `readonly` in a lot of ways) and the compiler creates defensive copies as a result. These defensive copies could be smarter and take into account `readonly` semantics however I don't think that is quite justified here. The savings for avoiding the defensive copies is small compared to the overhead of LINQ. Essentially if you're using LINQ then the defensive copies are likely not the performance issue. 

Closing as I think it's unlikely that we'd take a change here.
