### ISSUE TITLE
VS 2015 Update 1 breaks previously functional analyzers

### ISSUE THREAD

**Issue by bradwilson** [dotnet/roslyn#7257]
In addition to some internal analyzers, we also found that RefactoringEssentials was broken by the installation of VS 2015 Update 1.

Our project causes all analyzers to fail with errors like this:

`CSC : error AD0001: Analyzer 'RefactoringEssentials.CSharp.Diagnostics.ReplaceWithSingleCallToFirstOrDefaultAnalyzer' threw an exception of type 'System.TypeInitializationException' with message 'The type initializer for 'RefactoringEssentials.TypeExtensions' threw an exception.'. [C:\BuildAgent\work\cb37e9acf085d108\src\xunit.runner.utility.desktop\xunit.runner.utility.desktop.csproj]`

I haven't been able to come up with a simple repro, other than to say that this happened with multiple projects (internal and OSS), across multiple machines, with multiple analyzers (RefactoringEssentials is the only public one we use; others are private).

xUnit.net's usage of RefactoringEssentials started failing on all machines with VS 2015 Update 1, when it was passing with VS 2015 RTM. If you clone to this commit, you should be able to reproduce the problem: xunit/xunit@f75eb26

I haven't found the magic sauce to repro it with new projects yet.

**Comment by Suchiman** [comment]
This is mostly due to RefactoringEssentials accessing internal types through reflection which were refactored inbetween RTM and Update 1.

E.g. see these commits which fixed Update 1 support:
https://github.com/icsharpcode/RefactoringEssentials/commit/2dd5434c753cd486d87121c8638c8505f0a4c05a
https://github.com/icsharpcode/RefactoringEssentials/commit/179bb4301d19d94411b8d1c2aa835becc12f31b9

Your exception might indicate further not yet fixed reflection hacks: https://github.com/icsharpcode/RefactoringEssentials/blob/cc1171ff9cb41c6764ab8563b3e630a6cec2b95b/RefactoringEssentials/Util/TypeExtensions.cs#L22-L29

The only bad thing the roslyn team might have done here is hiding useful APIs :smile:

**Comment by srivatsn** [comment]
We promoted AD001 to a warning from Info. Since MSBuild doesn't repo Info diagnostics on the command line, the issue in RefactoringEssentials wouldn't have shown up before Update 1. This is an intentional change to ensure that faulty analyzers don't get silently ignored.
