### ISSUE TITLE
RenameAnnotation should take an optional string that is a suggestion for a new name

### ISSUE THREAD

**Issue by srivatsn** [dotnet/roslyn#7285]
A codefix that has a `RenameAnnotation` drops the user in an inline-rename session. If that annotation took an optional string that is an initial suggestion for the name, we can write a whole bunch of naming related analyzers\fixers.

**Comment by srivatsn** [comment]
@CyrusNajmabadi

**Comment by Pilchie** [comment]
What is the case where you would want to leave the user in inline rename, as opposed to the fix just running Renamer.RenameAsync and changing to the new name?

**Comment by srivatsn** [comment]
Three cases that I can think of:
- When you are issuing a diagnostic that says that the current name is unsuitable but most other names would be fine. So the fix can't just pick a name but can maybe suggest something.
- When a fix adds some new thing and in order to make sure that it is semantically correct, the fix generates local1 or field3 or some such very "safe" name. It would be good to leave the user in a rename session so that they can clean it up.
- When there are rename conflicts, the rename API clobbers the code. It would be good to let users have a warning about the conflicts through the rename dashboard.

**Comment by Pilchie** [comment]
Scenario 2 is what we already use the rename annotation for.  Just generate the new thing with the suggested name...

Scenario 1 seems like basically the same thing, have the fix rename to the suggested name, but then leave the annotation so that the user is in a rename session.  (This does potentially involve performance penalties of doing the rename in the fix, and then again in the session afterward).

For scenario 3, I agree that is an issue, but it seems like surfacing those directly in the calling code's preview is a better solution than forcing the user into inline rename.

**Comment by Pilchie** [comment]
Tagging @DustinCampbell for this too.

**Comment by Pilchie** [comment]
@DustinCampbell and I chatted - but without a clearer scenario, we don't think there is anything to do here yet.
