### ISSUE TITLE
Find references reports references in in both methods in a duplicate method scenario

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#7291]
Copy the following into a new C# project:

``` C#
using System;

class Program
{
    public void Foo(int a, int b)
    {
        Console.WriteLine(a);
        Console.WriteLine(b);
    }

    public void Foo(int a, int b)
    {
        Console.WriteLine(a);
        Console.WriteLine(b);
    }
}
```

Then, click on any parameter a.

_Expected:_ only the usages in one method are found
_Actual:_ we find some uses in both methods, which seems bizzare

**Comment by Pilchie** [comment]
I've seen numerous related issues around rename.  It would be good to fix this.

**Comment by dpoeschl** [comment]
The parameters are treated as equivalent, which is why this happens. If, in `AbstractReferenceFinder.OriginalSymbolsMatchCore`, we compare symbols from the same project directly instead of via the SymbolEquivalenceComparer, then this scenario works as expected. I'll add some tests then investigate to see if that behavior regresses other things.

**Comment by CyrusNajmabadi** [comment]
As per last design meeting, this is one of those cases where there is an error scenario and there is some fallout like the above.  In this case, the fallout seems minor (some extra references found), and it would likely be non-trivial to have to detect and workaround this case for all the normal find-refs cases.  So closing out as acceptable behavior.
