### ISSUE TITLE
CS0171 should be smarter when checking structs with LayoutKind.Explicit

### ISSUE THREAD

**Issue by orthoxerox** [dotnet/roslyn#7323]
Let's say I have the following struct:

``` c#
    [StructLayout(LayoutKind.Explicit)]
    internal struct SingleOrUInt32
    {
        [FieldOffset(0)]
        public readonly float Single;
        [FieldOffset(0)]
        public readonly uint UInt32;

        public SingleUInt32(float value)
        {
            //UInt32 = 0;
            Single = value;
        }
    }
```

It's obvious to any human ("LayoutKind.Explicit [...] affects both managed and unmanaged layout, for both blittable and non-blittable types.") that the fields occupy the same memory and only one of them has to be initialized in the constructor. However, C# compiler will not be satisfied unless you uncomment the other assignment.

**Comment by leppie** [comment]
What is wrong with?
```
public SingleOrUInt32(float value) : this() 
{
   Single = value;
}
```

**Comment by gafter** [comment]
We are now taking language feature discussion in other repositories:
- https://github.com/dotnet/csharplang for C# specific issues
- https://github.com/dotnet/vblang for VB-specific features
- https://github.com/dotnet/csharplang for features that affect both languages

Features that are under active design or development, or which are "championed" by someone on the language design team, have already been moved either as issues or as checked-in design documents. For example, the proposal in this repo "Proposal: Partial interface implementation a.k.a. Traits" (issue 16139 and a few other issues that request the same thing) are now tracked by the language team at issue 52 in https://github.com/dotnet/csharplang/issues, and there is a draft spec at https://github.com/dotnet/csharplang/blob/master/proposals/default-interface-methods.md and further discussion at issue 288 in https://github.com/dotnet/csharplang/issues. Prototyping of the compiler portion of language features is still tracked here; see, for example, https://github.com/dotnet/roslyn/tree/features/DefaultInterfaceImplementation and issue 17952.

In order to facilitate that transition, we have started closing the least recently active language design discussions from [the roslyn repo](https://github.com/dotnet/roslyn) with a note briefly explaining why. When we are aware of an existing discussion for the feature already in the new repo, we are adding a link to that. But we're not adding new issues to the new repos for existing discussions in this repo that the language design team does not currently envision taking on. Our intent is to eventually close the language design issues in the Roslyn repo and encourage discussion in one of the new repos instead.

Our intent is not to shut down discussion on language design - you can still continue discussion on the closed issues if you want - but rather we would like to encourage people to move discussion to where we are more likely to be paying attention (the new repo), or to abandon discussions that are no longer of interest to you.

If you happen to notice that one of the closed issues has a relevant issue in the new repo, and we have not added a link to the new issue, we would appreciate you providing a link from the old to the new discussion. That way people who are still interested in the discussion can start paying attention to the new issue.

Also, we'd welcome any ideas you might have on how we could better manage the transition. Comments and discussion about closing and/or moving issues should be directed to https://github.com/dotnet/roslyn/issues/18002. Comments and discussion about this issue can take place here or on an issue in the relevant repo.

I am not confident that the LDM would be willing to act on this request, so I am not moving it to the new repo. I recommend you write your constructor this way:

``` c#
    public SingleOrUInt32(float value) : this()
    {
        //UInt32 = 0;
        Single = value;
    }
```
