### ISSUE TITLE
Using IDisposable will dispose before Task Continuation is completed.

### ISSUE THREAD

**Issue by EdLichtman** [dotnet/roslyn#73264]
**Version Used**: 

**Steps to Reproduce**:

Look at my gist, as it's pretty much all there. I have 3 functions, "RunChildWithSimplifiedUsings", "RunChildWithVerboseUsings" and "RunChildWithManualDisposal".

https://sharplab.io/#gist:3f9e6c6546141bd97208d9fb74360eec

I almost gave up trying to reproduce, until I realized that this bug has something to do with the fact that I have .ContinueWith() present. If ContinueWith were not present, the Child Cancellation Token Source would cancel when the parent did. Now, with ContinueWith present, if you create a LinkedCancellationSource with a using statement, and then ContinueWith, the link will somehow become severed.

**Expected Behavior**:
I expect that if I have a CancellationTokenSource that has been linked off of a parent, and the parent is cancelled, then the child is cancelled immediately.

**Actual Behavior**:
The link between parent and child is severed, and when the parent cancels, the child never cancels.

**Comment by EdLichtman** [comment]
I don't have write-permissions, but this should be regarding the roslyn compiler, not the analyzers.

**Comment by huoyaoyuan** [comment]
This is not a compiler issue. It's a runtime issue and should be opened at https://github.com/dotnet/runtime/issues.

The compiled code of simplified `using` and traditional `using` should be same. They are both lowered into following structure:

```csharp
var obj = using_obj;
try
{
    do_something;
}
finally
{
    obj.Dispose();
}
```

If exception happens in `do_something`, the `Dispose` will still be invoked.

If I modify your code like this:

```csharp
    public static Task RunChildWithManualDisposal(CancellationToken parentToken)
    {
        // Within an asynchronous task, 
        Task.Run(async () =>
        {
            // create the linked token source
            var currentTokenSource = CancellationTokenSource.CreateLinkedTokenSource(parentToken);
            //grab reference to only the token.
            var childToken = currentTokenSource.Token;
            try
            {

                // await a task that should be cancelled by the parent token
                await Task.Run(
                    async () =>
                    {
                        // Log information about the running tokens
                        _ = Task.Run(async () =>
                        {
                            while (!childToken.IsCancellationRequested)
                            {
                                await Task.Delay(TimeSpan.FromMilliseconds(500));
                                LogTokenCancellation(parentToken, nameof(parentToken));
                                LogTokenCancellation(childToken, nameof(childToken));
                            }
                        }, childToken);
                        childToken.Register(() => Console.WriteLine("{0} has been cancelled", nameof(childToken)));

                        // figure out how to break out of this task with a completion source
                        var completeTask = new TaskCompletionSource();

                        // Delay for 5 seconds, then cancel the child.
                        await Task.Run(async () =>
                        {
                            await Task.Delay(TimeSpan.FromSeconds(3));
                            completeTask.SetResult();
                        }, childToken).ContinueWith(
                            (task, state) =>
                            {
                                Console.WriteLine("Finished setting result.");
                            },
                            new(),
                            parentToken);

                        // wait (forever) until this task breaks
                        await completeTask.Task;
                    }, parentToken);
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Exception: {ex}");
                throw;
            }
            currentTokenSource.Dispose();
        });
        return Task.CompletedTask;
    }
```

It will print that exception is thrown, so **your manual `Dispose` is never invoked**. That's the source of behavioral difference.

When a linked cancellation token is disposed, it dissociates its link with upstreams. So your child token will not be canceled by parent token. In fact, a disposed `CancellationTokenSource` will never become canceled from uncanceled because all cancellation mechanisms are disposed. It will remain the state at the moment it was disposed.

**Comment by genlu** [comment]
@huoyaoyuan thanks for looking into this!
@EdLichtman This sounds like an issue in your code. I'm closing it as it's not a roslyn bug, but feel free to continue discussion here

**Comment by EdLichtman** [comment]
@huoyaoyuan, thanks for responding. I am confused since, when I run ManualDisposal, there seems to be no error thrown, but when I wrapped it with a try/catch, it threw the exception. What causes this behavior? I'd imagine that if an error were to occur, it would be thrown regardless of being in a try/catch?

**Comment by huoyaoyuan** [comment]
> What causes this behavior?

Because the top-level task is forgotten:

```csharp
    public static Task RunChildWithManualDisposal(CancellationToken parentToken)
    {
        // Within an asynchronous task, 
        Task.Run(async () =>
```

It catches exceptions from child task, but nobody handles the exception in top-level task, because it's not `await`ed, nor its `Result` get accessed.

**Comment by EdLichtman** [comment]
That makes sense. So why does my manual disposal function fire off
correctly given what you describe when i do not include a 'finally"?

**Comment by huoyaoyuan** [comment]
It does not fire off correctly.

You don't include a finally -> the `Dispose` is not called -> the link between child `CancellationTokenSource` and parent is not dissociated -> you can observe the cts as cancelled.

Otherwise, when you use `using`,
`using` statement uses finally -> the `Dispose` is not called -> the link between child `CancellationTokenSource` and parent is dissociated -> it will never be canceled in any way.

You are giving incorrect expectation to `CancellationTokenSource`. Once disposed, the instance will be immediately frozen and disconnect with any signals.
