### ISSUE TITLE
Make IDocumentNavigationService Public available

### ISSUE THREAD

**Issue by CSharpDevChris** [dotnet/roslyn#7328]
At the moment we have to use DTE2 for navigating to text positions after we added new method declarations to the SyntaxTree. 
If the IDocumentNavigationService interface would be public, we could get the service from the VisualStudioWorkspace and could navigate to the correct position with one line of code.

So it will be very helpfully if you could make the IDocumentNavigationService interface public.

**Comment by DustinCampbell** [comment]
Yes, we should rationalize this and make it public. There are some odd methods on this interface that are historical and need to be thought through (or just removed).

**Comment by CyrusNajmabadi** [comment]
This would need to go through an API proposal.  in general, the reason we don't just make things public is because it increases maintenance costs and locks down our ability to change things in teh future.  We can open things up, but we have a process that requests need to go through to make sure the appropriate people weigh in and the right API shape is determined and shipped.
