### ISSUE TITLE
Erroneous "Use of unassigned local variable" for out parameter used inside collection expression

### ISSUE THREAD

**Issue by JakeYallop** [dotnet/roslyn#73376]
Sharplap: https://sharplab.io/#v2:C4LgTgrgdgNAJiA1AHwPSuACwJYGcAEAZgIbYA2uAsAFAACAjAAwDaAuvgG74C8+AhADV6ACgBEuUTHwB7CME7Ew+XPQCU+ZMn4CATGNw7JMuQqUHVNfFfwB+fMxVSDrS9ZD3Ro1gG4aNdFh4+ADu0mAA1gQAVhC48oTYUACmNByKnPQASkm4EGTyvEL6RrLyaWYAzKq+1OWcOtm5+Tz4uvqGUqWmygAs1TQMLOwcOi18HFk5efKa/CON065Wdg4VTj0u1Nb47syePn7UA/QAbPgARtLSZK0ig/jAOcCdJvfSWElgFtQA3ksyHyUvCgeTIfBq21oAHYiMQKEkagBfQ4MM6Xa6tPT3R5xF7yN6AnTfP5bazvTCfUbA0Hg/7Q2HwpFAA==
```csharp
//this fails
string[] v = !V1("s", out var s1) || !V2("s2", out var s2)
    ? [s1, s2]
    : [""];

//this works just fine
var v1Result = V1("s", out var s3);
var v2Result = V2("s2", out var s4);
string[] v2 = !v1Result || !v2Result
    ? [s3, s4]
    : [""];


static bool V1(string test, out string other)
{
    other = null!;
    return false;
}

static bool V2(string test, out string other2)
{
    other2 = null!;
    return false;
}
```

**Expected Behavior**:
No error, as output variables are guaranteed to be initialized when the method returns.

**Actual Behavior**:
Error.

**Comment by CyrusNajmabadi** [comment]
This is unrelated to collection expressions.  The problem is simply with: 

```c#
!V1("s", out var s1) || !V2("s2", out var s2)
```

Here there is a codepath where you execute `[s1, s2]` without executing both of those clauses.  Namely, if `!V1("s", out var s1)` is true, then the `||` is short circuited, and the `? ...` clause runs.  In that case `!V2("s2", out var s2)` never runs, so `s2` is never assigned.  The compiler tells you this.

```c#
var v1Result = V1("s", out var s3);
var v2Result = V2("s2", out var s4);
```

This is not the same case.  Here, you are unilaterally running both calls.  And so s3 and s4 are always assigned.
