### ISSUE TITLE
VB Span Perf Issue

### ISSUE THREAD

**Issue by CoolCoderSuper** [dotnet/roslyn#73387]
**Version Used**: 

**Steps to Reproduce**:

1. Loop over a span
2. 
3. 

https://sharplab.io/#v2:EYLgtghglgdgNAGxAN2HAJiA1AHwJJgAOA9gE4AuAzgAQDKAnpeQKZgB0AMrAI4CwAUARIUaDJqwEAFAK7AEUAMbUAwggiUaygdR3UZcxXVnUAsgAoAlNt02AIlDDUIpUtQC81AN4BfNgEFKWkIIGGsbHQAxMmoAUQgFAAtqYmo8GCcXMPCAOWYAD3IsmJh0I2ABYtLVdUogA===
https://sharplab.io/#v2:EYLgtghglgdgNAExAagD4AEBMBGAsAKHQGYACLEgYRIG8CT6zT0AWEgWQAoBKGuh/gMoAHCDAA8Ae2AArAKYBjAC4A+EhABO6kgF4SAbQC6Abj796AMwnrZEeQAsSHAG4aSU6SVhrNPWvjMBJKZmAL7BYfghQA==

**Expected Behavior**:
The c# and vb version should the same
**Actual Behavior**:
The vb version allocates an enumerator where as the c# just loops like a normal array.

**Comment by huoyaoyuan** [comment]
There's no performance issue in this case.

First, you are viewing the code of Debug configuration. Performance should always be discussed under Release.
The enumerator is not *allocated* because it's a struct. See the definition at https://github.com/dotnet/runtime/blob/de4fa45b047cb1f03da9d03c4d98f7518d02cc93/src/libraries/System.Private.CoreLib/src/System/Span.cs#L228 . Struct enumerator is used for many collections, for example `List<T>`.
C# has more support to span so the `foreach` is translated like an array. For VB, the compiler is using the enumerator definition as-is.

**Comment by CoolCoderSuper** [comment]
OK, that makes sense. I ran some benchmarks and they showed memory allocations, but after more debugging it was RuntimeHelpers call which is only there because its an object.
