### ISSUE TITLE
Cannot define a raw string literal ending in double-quote

### ISSUE THREAD

**Issue by weitzhandler** [dotnet/roslyn#73677]
**Version Used**: 
12

**Steps to Reproduce**:

Try to create a raw string literal of the following regex pattern ending in `"` or `\"`:

**Diagnostic Id**:

- https://dotnetfiddle.net/r8nzL5 (tried sharplab.io but it failed to save).
- https://regexr.com/80oti

**Expected Behavior**:
Should try to match the number of quotes both beginning to end (and perhaps vice versa), searching from end of string as well. This way, when the literal terminates in 3 dbl-quotes, even preceeded by another one will still compile.

**Actual Behavior**:
Doesn't compile.

**Comment by CyrusNajmabadi** [comment]
This is by design.  Single line raw-strings cannot start or end with a `"`.  You need to use a multi-line literal for that. 

You need to write it like so: https://sharplab.io/#v2:EYLgtghglgdgNAFxFANgHwAICYCMBYAKAEgSTCMBmAAmxpwHZCBvQo7LVl4ogeh6oAqAJwCesAOZUEAeyoBjIQFMICRVIAWUAM5UASovGKAHlQAOK1UJhUA7lATqqEKkIg26ABiop7i1ylZefnUEBFMtED4lQyMhADo5aTAeAA4PaQQoQMC+KgBVLQkNJTUARwBXDMUtQIA3CCFixUUARUrVHQBeKgAiPsIqQaHhwYAdTtGegAoAbQgAWgAvAF0AagBKSYGRnb6egG4ybiI6hqoAM2lyoTaqrt697Z3h8cnZhZWNrYJnkb2D1gAX0IgKAA==

```c#
using System;
					
public class Program
{
	public static void Main()
	{
		// Trying to create this Regex pattern with a raw string literal
		// https://regexr.com/80oti
		
		// Using three quotes
		var threeQuotes = """
            \=\"([a-z]+)\"
            """;		
			
		var fourQuotes = """"
            \=\"([a-z]+)\"
            """";
	}
}
```
