### ISSUE TITLE
Wrong type with Concat and litteral collection []

### ISSUE THREAD

**Issue by olivier-net** [dotnet/roslyn#74309]
**Version Used**: 

.net 8

**Steps to Reproduce**:

1. This code doesn't work: `new List<byte>().Concat([0x01]) `
2. This code works: `new List<byte>().AddRange([0x01]) `

Repro: https://sharplab.io/#gist:8e2f47a3bd1ec7856838a9a3a1f660ec

**Diagnostic Id**:

Error CS1929 : 'List<byte>' does not contain a definition for 'Concat' and the best extension method overload 'ParallelEnumerable.Concat<int>(ParallelQuery<int>, IEnumerable<int>)' requires a receiver of type 'System.Linq.ParallelQuery<int>'

**Expected Behavior**:

It should know that the array in Concat contains byte and not int.

**Actual Behavior**: 

It thinks that the value in Concat is an collection of int instead of an collection of byte.

**Comment by jaredpar** [comment]
@cston looks like an inference issue. Is this expected?

**Comment by cston** [comment]
The behavior is by design.

For `new List<byte>().Concat([0x01])`, there are several candidate methods for `Concat` when compiling with .NET8, all with similar signatures.

For instance, from `System.Linq.Enumerable`:
```
public static IEnumerable<TSource> Concat<TSource>(this IEnumerable<TSource> first, IEnumerable<TSource> second);
```

For that overload, method type inference infers the following for `TSource` (see [type inference](https://github.com/dotnet/csharplang/blob/main/proposals/csharp-12.0/collection-expressions.md#type-inference)):
- an exact bound of `byte` from the first argument `new List<byte>()`, and
- a lower bound of `int` from the *element expression* in the second argument `[0x01]` (since the type of `0x01` is `int`).

Since there is no implicit conversion from `int` to `byte`, type inference fails, and the overload is not applicable. The same is true for the other overloads, so overload resolution fails.

**Comment by olivier-net** [comment]
I understand. If it is a method the compiler uses the class type, but if it is an extension method, it tries to use the lower bound of the passed parameters. This is why AddRange works but not Concat.

Personally, I find inconsistant code confusing, there is no way to know just by reading the code that Concat is an extension method.

I hope is can be unified with extension method or in the future Extension Types 😉
