### ISSUE TITLE
implicit `return 0` for <top-level-statements-entry-point>

### ISSUE THREAD

**Issue by kasperk81** [dotnet/roslyn#74385]
no error:

```c#
Console.WriteLine("Hello World!");
```

error `CS0161: '<top-level-statements-entry-point>': not all code paths return a value`

```c#
if (args.Length < 3)
{
    Console.WriteLine("Insufficient arguments.");
    return 1;
}

Console.WriteLine("Hello World!");
```

compiler can assume it's 0 in second case as well.

**Comment by CyrusNajmabadi** [comment]
In the first case, there's just a `void Main` method.  In the second, there's an `int Main` so that contract needs to be abided by. 

> compiler can assume it's 0 in second case as well.

We never assume an implicit return anywhere.  If you want the language to support this, this will have to start as a discussion on csharplang to change the language. Thanks!
