### ISSUE TITLE
How to prevent visual studio from inserting <see langword=""/> in comments

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#74417]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/How-to-prevent-visual-studio-from-insert/10678311)._

---
[severity:It bothers me. A fix would be nice]
When typing keywords in comments, visual studio inserts a see link.
For instance type property and when entering the space it is transformed to <see langword="property"/>.
I then have to remove the whole thing and type the word property again. This happens with a lot of keywords, so it is super annoying.

So, where is the option to turn this off?

---
#### Feedback Bot on 6/11/2024, 00:51 AM: 

(private comment, text removed)
#### Wenwen Fan [MSFT] on 6/11/2024, 03:22 AM: 

(private comment, text removed)
#### saskia on 6/11/2024, 03:33 AM: 

(private comment, text removed)
#### saskia on 6/20/2024, 08:17 AM: 

(private comment, text removed)
#### saskia on 6/21/2024, 06:16 AM: 

(private comment, text removed)
#### Wenwen Fan [MSFT] on 6/24/2024, 02:20 AM: 

(private comment, text removed)
#### Maik.Schumann on 6/26/2024, 04:09 AM: 

(private comment, text removed)
#### saskia on 7/2/2024, 01:40 AM: 

(private comment, text removed)
#### Wenwen Fan [MSFT] on 6/19/2024, 04:35 AM: 

(private comment, text removed)
#### Wenwen Fan [MSFT] on 6/19/2024, 04:37 AM: 

(private comment, text removed)
#### Wenwen Fan [MSFT] on 6/20/2024, 09:51 PM: 

(private comment, text removed)
#### Wenwen Fan [MSFT] on 7/11/2024, 03:53 AM: 

(private comment, text removed)
#### saskia on 7/15/2024, 04:55 AM: 

(private comment, text removed)
#### Wenwen Fan [MSFT] on 7/16/2024, 02:21 AM: 

(private comment, text removed)
#### Maik.Schumann on 7/16/2024, 03:00 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
This issue only occurs when "Show completion list after a character is deleted" is enabled (the default value for this option is disabled).
![image](https://github.com/user-attachments/assets/d89b8250-57dd-4bed-a159-763765234ff9)

It is reproducible by the typing the following sequence inside a comment:

<kbd>i</kbd>, <kbd>Backspace</kbd>, <kbd>i</kbd>, <kbd>n</kbd>, <kbd>Space</kbd>

To resolve this bug, the handling for completion after a character is deleted inside a comment should be updated to behave like "Show completion after a character is typed", and not show the completion list where one would not otherwise show.
