### ISSUE TITLE
Code action "Allow unsafe code in this project" has no effect

### ISSUE THREAD

**Issue by just-ero** [dotnet/roslyn#74472]
### Version Used

Compiler: 4.12.0-1.24359.11 (7e282662)  
.NET: 9.0.100-preview.5.24307.3  
Visual Studio Code: 1.91.1, `f1e16e1e6214d7c44d078b1f0607b2388f29d729`, x64  
C# Extension: v2.39.28  
C# Dev Kit Extension: v1.9.8

### Steps to Reproduce

1. Create or open a C# project in Visual Studio Code. Ensure `AllowUnsafeBlocks` is not set to `true`.
2. Add the `unsafe` keyword in any valid location.
3. Apply the code fix to the symbol emitting `CS0227`.
4. Observe the project property not being set to `true`.

### Expected Behavior

The property `AllowUnsafeBlocks` is added to the project file with a value of `true`, or, if already present with a value not equal to `true`, changes its value to `true`.

### Actual Behavior

The project file is not changed.

**Comment by CyrusNajmabadi** [comment]
i could see this not working iwth C# extension.  But i would expect this to work with DevKit.  @dibarbet  what sort of Workspace do we have in DevKit.  We basically need the following to flow through it to the backing project system: `project.Solution.WithProjectCompilationOptions(project.Id, compilationOptions.WithAllowUnsafe(true))`

**Comment by dibarbet** [comment]
@CyrusNajmabadi there is currently no ability in the C# extension or devkit for Roslyn to update the project file, so this not working is expected.   The current system doesn't allow us to provide project file edits through LSP.

In order to make this work, we need to work with the DevKit project system side to design an API that allows us to retrieve the actual text edits that should be made to the project file in order to apply the code action.  These file edits would be returned as part of the LSP code action response.

We cannot just have `WithProjectCompilationOptions` apply the action internally as it is the client's responsibility to apply a code action (Roslyn just returns the data needed to apply it)

**Comment by CyrusNajmabadi** [comment]
@dibarbet  to triage and decide what we want to do here.   if we want to support this, please ensure it's in the right milestone.  if we do not intend on supporting this, please close out.

**Comment by just-ero** [comment]
Maybe the code fix suggestion should be removed if this will not be implemented?
