### ISSUE TITLE
Microsoft.VisualStudio.LanguageServices.DevKit.csproj attempted to copy files to output directory during design time build

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#74801]
**Version Used**: ee863ed

**Steps to Reproduce**:

Open Roslyn.sln in Visual Studio.

**Expected Behavior**:

Design time build does not attempt to copy files to output (bin) directory.

**Actual Behavior**:

![image](https://github.com/user-attachments/assets/d5c5842c-68f1-46a3-9f9c-97c8d0bb2d53)

The caller appears to be target `_CopyDevKitExtensionFiles` in Microsoft.CodeAnalysis.LanguageServer.UnitTests.csproj. Design time build is broken, leading to lack of IDE features during development.

**Comment by tmeschter** [comment]
There are two issues here:
1. Since this is an error reported through the normal MSBuild mechanisms (as opposed to an uncaught exception or a missing target or something like that) it is reasonable to expect that it will be shown in the VS Error List.
2. Regardless of the error reporting you probably don't want `_CopyDevKitExtensionFiles` to run during a design-time build. The definition of the target should be updated to include `Condition="'$(DesignTimeBuild)' != 'true'`.
