### ISSUE TITLE
EE: IntPtr/UIntPtr values are always shown in decimal

### ISSUE THREAD

**Issue by plnelson** [dotnet/roslyn#7481]
IntPtr and UIntPtr values are always shown in decimal regardless of format specifiers and the "Hexadecimal Display" setting.  One of our Debug Managed Memory tests is disabled because of this difference in behavior between the old/new EEs.

**Repro:**
Debug the following code:

``` C#
using System;
static class Program
{
    static void Main()
    {
        IntPtr p = (IntPtr)0x8000000;
        UIntPtr u = (UIntPtr)0x8000000;
        System.Diagnostics.Debugger.Break();
    }
}
```

View locals window

**Result:** Both values are formatted as {13427728} because of the `ToString()` methods.  This is value is arguably incorrect for the IntPtr when the process is 32bit.  Also pointer values are generally expected to be in hex anyway.

**Comment by KevinH-MS** [comment]
@pnelsonmsft I think that the ```ToString()``` implementation should be smarter (although realistically, it will never be changed for back compat reasons).

If you expand the local an look at m_value, we'll always show that in hex, but special casing the Value of these types (and ignoring the string-conversion function) seems a little fishy to me (regardless of what the old EE did).

Thoughts?

**Comment by pnelsonmsft** [comment]
I don't consider ToString to be there exclusively to be called by the EE and we already special case all of the other built in types.  The first built in type I looked at was System.Int32 and it also has a ToString method that we ignore in the debugger.
Requiring the user to expand an IntPtr in order to see the hex value seems too cumbersome to me and I don't see what value we have by showing the underlying representation (Int32 has an Int32 field and expanding Int32 is equally useless).

I'm still of the opinion that we should format these for the user as we do the other built in types

**Comment by pnelsonmsft** [comment]
BTW, I don't think we can always show as hexadecimal except unless the user adds the "d" format specifier because of the API.  I'll update the issue to remove that text.  I suggest simply copying the old EE's behavior

**Comment by KevinH-MS** [comment]
IntPtr and UIntPtr aren't built in types, which is what makes this odd.  For System.Int32, etc we also suppress expansion.  Should we do that for IntPtr/UIntPtr as well, or is there value in seeing the members?

**Comment by pnelsonmsft** [comment]
IntPtr/UIntPtr are built in types:
IntPtr = `ELEMENT_TYPE_I` or `native int` in cil
UIntPtr = `ELEMENT_TYPE_U` or `native uint` in cil

I don't think there's any value in allowing them to be expanded.

**Comment by KevinH-MS** [comment]
They're not C#/VB language built-ins (which is why our ObjectFormatter doesn't handle them).  If we don't care about expansion, it would seem easy/harmless to add them though.

**Comment by r-ramesh** [comment]
@KevinH-MS I have checked in a change on the debugger side to add a DebuggerDisplay attribute to autoexp for IntPtr/UIntPtr, which fixes this issue.

**Comment by plnelson** [comment]
@r-ramesh Thanks Ramkumar!  Can you provide the attribute you added to autoexp.cs?  This will allow people to work around the bug with older versions of VS.

**Comment by KevinH-MS** [comment]
Awesome!  That's actually a better fix. 😄 Thanks @r-ramesh!

**Comment by r-ramesh** [comment]
Workaround for older VS:

I added the following attributes to autoexp.cs (typically "C:\Program Files (x86)\Microsoft Visual Studio\Visual Studio 2015\Common7\Packages\Debugger\Visualizers\Original\autoexp.cs")

```
[assembly: DebuggerDisplay(@"{m_value}", Target = typeof(IntPtr))]
[assembly: DebuggerDisplay(@"{m_value}", Target = typeof(UIntPtr))]
```

From a developer command prompt, build:
`>csc /t:library autoexp.cs`

which can replace the existing autoexp.dll. Subsequent debug sessions will use the hex value instead of the decimal value for IntPtr/UIntPtr.

**Comment by plnelson** [comment]
Fix was submitted by @r-ramesh and verified (internal PR 51661).
