### ISSUE TITLE
What have you done with ~ on byte

### ISSUE THREAD

**Issue by mklemarczyk** [dotnet/roslyn#7490]
Why expression byte n = ~m; does not work?

m is byte number (byte m = 231)

What have you done?
It says that ~m is a int. How it can be int?

I need to go around and implement it by myself:
byte m = 231;
byte c = 255;
byte n = c ^ m;

**Comment by GeirGrusom** [comment]
unchecked((byte)~(byte)231)

**Comment by svick** [comment]
The concept is explained in §7.3.6 Numeric promotions of the C# spec:

> […] the effect is to select the first of the operators for which implicit conversions exist from the operand types […]
> Unary numeric promotion simply consists of converting operands of type `sbyte`, `byte`, `short`, `ushort`, or `char` to type `int`.

The built-in overloads of `~` are listed in §7.7.4 Bitwise complement operator.

The reason is explained in [The Annotated C# standard](https://books.google.cz/books?id=g6axWRRpJZwC&pg=PA239) to be efficiency: common processors do need to make the calculation in `int`s, so the available operator overloads reflect this.

**Comment by alrz** [comment]
If you want a concise code, I believe you'll be able to declare an extension operator (#5165) for `byte` since `~` is overridable; and do the cast there.

**Comment by alrz** [comment]
@GeirGrusom According to the spec, `unchecked` only affects enums.

**Comment by SaxxonPike** [comment]
@alrz: `unchecked` is used so that the cast back to `byte` has no chance to throw an overflow exception. Instead, it will just take the lowest 8 bits of the result.

**Comment by alrz** [comment]
@SaxxonPike But it doesn't throw for any possible value of `byte m`..

**Comment by GeirGrusom** [comment]
@alrz I first wrote the expression using a literal (123) which at that point required `unchecked`. But when i switched to variables it's no longer required as unchecked is the default behavior. I probably should have removed it, but it didn't cross my mind.

**Comment by mklemarczyk** [comment]
@svick Common processors can also make computing on shortest data than int.
In your way you want to cast all  types to long in future?

That is crazy when no one overflow exception can occurs.

**Comment by mikedn** [comment]
> Common processors can also make computing on shortest data than int.

I'm pretty sure that ARM CPUs do not have byte instructions and they're pretty common.

But I don't think these rules exists only due to the way CPUs work. They also keep the language (and the compilers) simple and prevent developers from shooting themselves in the foot. This is nothing new, C and C++ have the same rules, the only difference is that they allow implicit narrowing conversions.

**Comment by gafter** [comment]
We are now taking language feature discussion on https://github.com/dotnet/csharplang for C# specific issues, https://github.com/dotnet/vblang for VB-specific features, and https://github.com/dotnet/csharplang for features that affect both languages.

**Comment by mklemarczyk** [comment]
I just switched to another language that works properly.
