### ISSUE TITLE
"csc.exe" exited with code -2146232797 when using IEnumerable<ReadOnlySpan<>> as a return value

### ISSUE THREAD

**Issue by jhgbrt** [dotnet/roslyn#75569]
While experimenting with C# 13 features, stumbled upon the following issue:

**Version Used**: 
9.0.100-rc.2.24474.11

**Steps to Reproduce**: try to compile the following

```
static class CSharpCompilerCrash
{
    public static IEnumerable<ReadOnlySpan<char>> Lines(string data)
    {
        yield break;
    }
}
```

Error message:

1>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(89,5): error MSB6006: "csc.exe" exited with code -2146232797.

**Comment by cston** [comment]
System.InvalidOperationException : Unexpected value 'NoConversion' of type 'Microsoft.CodeAnalysis.CSharp.ConversionKind'

ExceptionUtilities.UnexpectedValue(Object o) line 22
CodeGenerator.EmitConversion(BoundConversion conversion) line 178
CodeGenerator.EmitConversionExpression(BoundConversion conversion, Boolean used) line 63
CodeGenerator.EmitExpressionCore(BoundExpression expression, Boolean used) line 127
CodeGenerator.EmitExpressionCoreWithStackGuard(BoundExpression expression, Boolean used) line 83
CodeGenerator.EmitExpression(BoundExpression expression, Boolean used) line 71
CodeGenerator.EmitReturnStatement(BoundReturnStatement boundReturnStatement) line 867
...

**Comment by AlekseyTs** [comment]
IEnumerator.Current cannot be implemented because a ref struct cannot be converted to `object`. Perhaps `IEnumerable<T>` should not be changed to allow ref structs for `T`. 
CC @stephentoub

**Comment by stephentoub** [comment]
> IEnumerator.Current cannot be implemented because a ref struct cannot be converted to object. Perhaps IEnumerable<T> should not be changed to allow ref structs for T.

Iterators can't be used because the compiler stores a yielded item on the enumerator object, but manual implementations are possible, and the non-generic IEnumerator.Current can just throw, e.g.

https://github.com/dotnet/runtime/blob/b780069abf78978112cb860f9c636f767d0b4437/src/libraries/System.Text.Json/tests/Common/MetadataTests.cs#L639-L654

https://github.com/dotnet/runtime/blob/b780069abf78978112cb860f9c636f767d0b4437/src/libraries/System.Runtime/tests/System.Runtime.Tests/System/Collections/Generic/IEnumerableTests.cs#L23-L39

**Comment by AlekseyTs** [comment]
> but manual implementations are possible, and the non-generic IEnumerator.Current can just throw, 

That is, certainly, one way to approach the problem. However, in my opinion, while possible, that is not a proper way to implement the interface.

**Comment by Warpten** [comment]
Going to throw in my two cents as I ran into this today and was solidly confused for a good few hours. Sorry for the necro.

This directly conflicts with https://github.com/dotnet/runtime/pull/102795; as I had been churning out `IEnumerable<T>` where `T` is a ref-like type left and right until I hit the build button and Roslyn broke on me.

The IDE tooling says it can be done but Roslyn says no.

Sure, it works with a custom iterator type, but for code using yield statements this is quite unwieldy and does not make it immediately obvious that the __workaround__ is to avoid yield return and provide a custom iterator type (on top of documenting the fact that the non-generic version is unusable).

I believe this needs clarification in the error message, as all that would technically be needed for `IEnumerable<T>` to actually work with ref-like types would be to break the connection with non-generic `IEnumerable` - which is obviously an impossible change , so maybe introducing something like `IRefEnumerable<T>` could be an option, and hinting at that to the user.

**Comment by AlekseyTs** [comment]
@Warpten Could you provide more specific details about what you see as a problem? Perhaps, with examples. Could you also be specific about what change you are asking for/suggesting?

**Comment by Warpten** [comment]
Here's my understanding of this issue, how it was fixed, and how it interacts with https://github.com/dotnet/runtime/pull/102795. Let me know if I'm wrong.

This change to Roslyn effectively forces every `yield ...` function ("Enumerator functions", I think Roslyn calls them?) to be rewritten as a manual implementation of `IEnumerable<T>` when `T` is a `ref struct`, because of the inheritance down to `System.Collections.IEnumerable` and its `IEnumerable.Current` property; in previous versions of .NET 9, Roslyn is unable to generate code for that property when using `yield ...` statements and crashes. This was fixed by effectively blocking ref-like types from such methods.

However, the core library (https://github.com/dotnet/runtime/pull/102795) explicitely allows `IEnumerable<T>` to take ref-like type arguments, meaning there is no diagnostic for this function:

```cs
public static IEnumerable<Span<byte>> Foo() { yield break; }
```
because the IDE tooling sees `IEnumerable<T> where T : allows ref struct` and concludes all is fine. Things **only** break when calling `dotnet build` (because there is obviously no conversion from .

The direct consequence is that there is nothing to explicitely show that `yield` statements cannot be used with ref-like types **when writing the code**, leading to confusion when suddenly a rather obscure compile-time error pops up.

Effectively, Roslyn and the language disagree here in a specific use case: Roslyn forbids ref-like types in iterator types (in `yield` functions), but the core library accepts them in `IEnumerable<T>`, where we've been told to rely on `yield` statements instead of hand-rolling an implementation of `IEnumerable`.

I believe there are three ways to fix this:
1. Clarify the error from Roslyn and explain to the user that they should not rely on the compiler to do their bidding and instead return a hand-rolled implementation of `IEnumerable<T>` where `IEnumerator.Current` throws (and document it in their code). Arguably this is not desirable behavior.
2. Something similar to partial specializations from C++ (I'm not too invested in the language so I'm not aware of any current proposal that matches this idea) where, if `T` is a ref-like type, IEnumerator is **not** implemented.
3. Similar to 2., but the check is done at runtime somehow (trying to do it manually with `RuntimeHelpers` does not appear to work, extra machinery needed?)
4. Refer users to a new interface called `IRefEnumerator<T>` that does **not** implement `IEnumerable`. I don't think this would break anything as foreach loops use duck typing. It does however break Linq, since that is on `IEnumerable<T>`, so there would either be duplication work to be done (which I personally feel a bit extreme) or no Linq for these.

**Comment by jjonescz** [comment]
> the IDE tooling sees `IEnumerable<T> where T : allows ref struct` and concludes all is fine. Things **only** break when calling `dotnet build` (because there is obviously no conversion from a ref-like type to `object`.
> 
> The direct consequence is that there is nothing to explicitely show that `yield` statements cannot be used with ref-like types **when writing the code**, leading to confusion when suddenly a rather obscure compile-time error pops up.

This sounds like you are using an older IDE than SDK, which of course means your IDE doesn't yet contain the fix for this and so you only see the error with `dotnet build`. Once the fix flows to your IDE, you should see the error immediately while writing the code.

**Comment by stephentoub** [comment]
> Refer users to a new interface called IRefEnumerator<T> that does not implement IEnumerable

That also wouldn't help here unless IRefEnumerator<T> was a ref struct (which as an interface it couldn't be). With the way code for an iterator is generated, yielded items need to be stored into the enumerator instance so that they can then be accessed from Current, and if T is a ref struct, that's only possible if the enumerator is also a ref struct.
