### ISSUE TITLE
EE - How can I troubleshoot frequent "Internal error in the expression evaluator" errors?

### ISSUE THREAD

**Issue by Przemyslaw-W** [dotnet/roslyn#7560]
I often get said message instead of actual value either in watch window or when calling EE API. How can I troubleshoot what went wrong so that I can fill meaningful bug reports here? Is there a log somewhere to investigate?

I'm using VS2015 Update 1, but it was the same situation in RTM as well.

**Comment by davkean** [comment]
tag @amcasey

**Comment by KevinH-MS** [comment]
Hi @Przemyslaw-W, the best thing you can do is grab a dump at the point of the unhandled Exception (that's what's happening under the covers that results in the "Internal error...").

Assuming that you're debugging a 32-bit process, you do that by attaching (Managed) to devenv.exe (with another instance of VS), then change your Exception Settings to break when any managed Exception is thrown:
![desktop](https://cloud.githubusercontent.com/assets/6464209/11986902/75820ba0-a98a-11e5-9cd3-e21c05663536.PNG)

Next, re-evaluate whatever's giving the error.

When the debugger stops in the attached instance of VS, do "Debug > Save Dump As..."

If you're debugging a 64-bit process, the steps are the same, but you'll want to start by attaching to msvsmon.exe instead of devenv.exe.  If you don't hit an Exception in msvsmon.exe, you'll need to try attaching to devenv.exe and repeating steps again (most often, then Exception will be in msvsmon though).

If you have any other questions, let me know--thanks!

**Comment by Przemyslaw-W** [comment]
Ok, I am uploading dump to google drive. Please give me an email, so I can send the link

**Comment by KevinH-MS** [comment]
kevinh@microsoft.com
