### ISSUE TITLE
Interactive- dots on line continuations

### ISSUE THREAD

**Issue by MgSam** [dotnet/roslyn#7563]
The dots on line continuations are included when selecting code in the Interactive Window, making copying extremely painful. For example, 

``` C#
> var a =
.     5;
```
When you select and copy this code somewhere else it will include the dot. I think the dots on line continuations should either be removed or not included in the selection.

**Comment by KevinH-MS** [comment]
Hi @MgSam, we attempt to be smart about when we include the prompts an when we don't.  What application are you pasting into?

**Comment by genlu** [comment]
Hi @MgSam, when pasting text copied from interactive window into VS code editor, the prompts should be stripped out automatically (this is fixed by #6323). If you are pasting it into other editors, we have just added a "Copy Code" command to interactive window (#7419). Could you please let me know if it solves your problem?

**Comment by MgSam** [comment]
I'm pasting into a text editor. Why would you ever want to include the dots in the copied text? This seems like it is *always* a bug. I can't see any reason someone would want to include the dots. 

Honestly, I don't want to have to right click and select a special "Copy Code" command. I want to just hit CTRL + C. I'm copying from a REPL, obviously I want to copy code. This should be the default behavior.

**Comment by genlu** [comment]
The expected behavior for CTRL + C is always copy anything being selected IMHO.

Besides, the text in REPL is actually a mix of prompts, code and output, with CTRL + C dedicated to code only, there would be no way to copy output, which is definitely something people would do.

With a "Copy Code" command (shortcut is CTRL + SHIFT + C), the expected copy behavior is preserved (thus providing flexibility, you can copy whatever you want) without making copy-code too much of a hassle (just one extra key stroke).

@dotnet/roslyn-interactive Any thought on this?

**Comment by lorcanmooney** [comment]
> The expected behavior for CTRL + C is always copy anything being selected IMHO.

The question then becomes: why are the prompts/dots selectable at all? In the context of VS at least, it seems like they should behave more like the line numbers in a regular editor window, occupying a separate, unselectable column to the side.

**Comment by amcasey** [comment]
I understand that, in the Python community, it is common for people - especially novices - to copy and paste entire interactive sessions for the purpose of requesting (or providing) clarification.  In such cases, would it be useful to have the prompt punctuation to differentiate the input from the output?

**Comment by lorcanmooney** [comment]
If that's the case, then maybe a middle ground could be to have a prompt margin and select only code- and output-text unless/until the user explicitly moves the caret/cursor across the margin, at which point the prompts corresponding to the selected lines would also be included.

I think that would be a much more natural experience than adding a special copy command with yet another key combination, although I wonder if the payback would justify the additional complexity.

**Comment by genlu** [comment]
@lorcanmooney One major problem with your proposal is you can't select multiple line of code without also selecting prompts (assuming you are using stream selection, as box selection would require even more extra effort than existing "Copy Code" shortcut.)

@MgSam I'm closing this issue. If someone has a better solution than "Copy Code" command that addresses all the problems mentioned in this thread, feel free to reactivate this.
