### ISSUE TITLE
Small method body cache is nondeterministic 

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#7595]
It appears the addresses of data referenced in `PrivateImplementationDetails` is not deterministic.  Repeatedly compiling and diffing Roslyn.Compilers.CSharp.Emit.UnitTests reveals the following change to the IL.

``` diff
  .field static assembly initonly valuetype '<PrivateImplementationDetails>'/'__StaticArrayInitTypeSize=24' '020A03BB567626B273281CD96437D973439215D0' at I_0095B7FC
  .field static assembly initonly valuetype '<PrivateImplementationDetails>'/'__StaticArrayInitTypeSize=24' '020A03BB567626B273281CD96437D973439215D0' at I_0095B7E8
```

This is  just a small window of the change.  Every field in the PrivateImplementationDetails section appears to be shifted by the same amount.  

The actual delta is in the location of the data.  Here is the last token:
- Run 0: at I_0095B7FC
- Run 1: at I_0095B7E8

These line up with changes in address of values in the data entries of the IL. 

```
.data cil I_0095B7FC = bytearray (
.data cil I_0095B7E8 = bytearray (
```

This seems to repro for both Roslyn.Compilers.CSharp.Emit.UnitTests and Roslyn.Compilers.CSharp.Symbol.UnitTests.  The latter repros more frequently and easily.

**Comment by gafter** [comment]
I have not been able to reproduce this outside msbuild. I captured the compile command being run by msbuild.

I do note that one of the input files to the compiler changes every time we build using msbuild. The file GeneratedAssemblyInfo_42.42.42.42.cs is different each time due to a comment as its last line

```cs
// Generated by the MSBuild WriteCodeFragment class on 1/4/2016 4:05:17 PM.
```

That is enough to cause the PDB to be different, which will change the PDB's ID, which will change the assembly's ID, which will change the .data section.

@jaredpar If you can reproduce this reliably, please package up a set of source files along with a command-line build script that just invokes csc.exe in a way that demonstrates the issue. If you cannot please close this as not repro.

**Comment by jaredpar** [comment]
> That is enough to cause the PDB to be different, which will change the PDB's ID, which will change the assembly's ID, both of which will change the contents of the .data section. 

Can you elaborate on this?  When I was diffing the IL it seems that the address of the data was changing between builds.  It appeared to oscillate between two values.  It's unclear to me how a change in a comment could cause this behavior.  

I understand the PDB ID changes but not the length of the ID (that's constant).  How does the changing of the value of the PDB ID change the offset / token of data values?

**Comment by gafter** [comment]
For determinism we sometimes sort values that are placed in various sections. The PDB ID is placed into the assembly so that can move around other things. If the input is not stable it doesn't bother me that CSC is not producing the same output. For determinism we only promise the same output when the inputs do *not* change.

I've been running csc over and over again on Roslyn.Compilers.CSharp.Emit.UnitTests (for about 20 hours so far) and getting identical assemblies every time.

**Comment by jaredpar** [comment]
Further testing has revealed this to be an actual bug.  To reproduce:

1. Check out the [deter-use](https://github.com/jaredpar/roslyn/tree/deter-use) branch in [my fork](https://github.com/jaredpar/roslyn) of roslyn.  
2. Remove the Emit and Symbols DLLS from the skipped list in build/scripts/test-determinism.ps1 
3. Run: `cibuild.cmd /testDeterminism`

This fork fixes the `WriteCodeFragment` issue and has identical source on all compilations.  It will be merged into master in the next day or so.

**Comment by jaredpar** [comment]
Assigning to @tmat as we determined this is related to small method body caching issues.

**Comment by tmat** [comment]
Unless someone else takes this it won't happen in 1.2

**Comment by jaredpar** [comment]
@tmat right now Roslyn, by virtue of being deterministic, is working around this by disabling the small method body cache during compilation.  How impactful is this?  If it's impactful we need to push to fix this.  If it's not significant then we can push out.

**Comment by tmat** [comment]
I'm just saying I have 0 bandwidth working on this.

**Comment by jaredpar** [comment]
@tmat understood.  But can you answer my Q?  Essentially how impactful to Roslyn is it to disable small method body caching?  That's what we're doing right now to work around this bug.

**Comment by gafter** [comment]
@jaredpar You can answer that question by comparing the size of an assembly when compiled with determinism enabled (i.e. including the duplicated bodies) and when compiled with determinism disabled (i.e. with duplicate bodies removed). Any difference is due to the workaround. If the difference is small or large, that is your answer about how impactful it is.

**Comment by jaredpar** [comment]
It does not appear to be significant here.  Saw a .4% increase in MS.CA.dll.

**Comment by jaredpar** [comment]
This bug was fixed by disabling the cache during deterministic builds.  The following issues tracks turning it back on. 

https://github.com/dotnet/roslyn/issues/17052
