### ISSUE TITLE
Text Editor does not Center when I select a Method in Document Outline Window

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#76242]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Text-Editor-does-not-Center-when-I-selec/10796950)._

---
Please see the Screenshot below.

![image.png](https://aka.ms/dc/image?name=B1359f22f6069409bac6bf1a236611b85638678328174443375_20241121-194016-image.png&tid=1359f22f6069409bac6bf1a236611b85638678328174443375)

---
#### Feedback Bot on 11/21/2024, 08:00 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 11/26/2024, 00:06 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

**Comment by sharwell** [comment]
It's not clear whether the current behavior should be considered correct. Some features center the view on navigation, while many others use `TryMoveCaretToAndEnsureVisible` which does not center the view. The current behavior for Document Outline has been in place since the feature was first enabled by default in #65641.

**Comment by Axium7** [comment]
I am curious, why did this issue get moved here?[ https://developercommunity.visualstudio.com/t/Text-Editor-does-not-Center-when-I-selec/10796950
](url)

It centers when the method is not visible on the screen so why not make it center always?  That would make it consistent and spare the user from having to look for it somewhere on the screen.

Ideally the entire Method name would be Highlighted as well without having to turn ON **_Highlight references to symbol under cursor_** in Settings.

**Comment by CyrusNajmabadi** [comment]
> why did this issue get moved here?

The code for this lives in this repo.

**Comment by CyrusNajmabadi** [comment]
> so why not make it center always?

General navigation philosophy is to not do that to maintain spatial consistent when possible. 

People navigate a *lot* to something already on screen, while still wanting to see the code they are currently on.  Always moving something to the center flights against that.  

There's no right/wrong approach here. Just trade-offs and heuristics that can better things for some users while making it worse for others.

**Comment by Axium7** [comment]
> People navigate a _lot_ to something already on screen, while still wanting to see the code they are currently on. Always moving something to the center flights against that.

Below is an image of my current IDE Setup.  The Document Outline Window is always open for me and Pinned because it's crucial for navigation.  95%+ of the time, when I select something in the Document Window it's not on the screen, hence it gets centered on the screen.   The Odd time that this does not happen my Flow gets interrupted and I have to figure out what happened... why is it not centered? where is the method?  Is it above?  Is it below?   This breaks my train of thought / flow.

![Image](https://github.com/user-attachments/assets/d38d443d-8178-4e2d-8f7e-b6362cf830a3)

It would also be nice if the entire method signature could be highlighted like this and the ability to modify the background color in settings.   Document Window is the 3rd most important window for me in VS after Text Editor and Solution Explorer.

![Image](https://github.com/user-attachments/assets/c0e2a2ad-67f0-4afd-b02f-341b77f05580)

**Comment by Axium7** [comment]
Thank you for implementing this.  I noticed it working now in VS 17.13.1.  This is a huge help!

Thank you again.

**Comment by Axium7** [comment]
Thank you for implementing this.  I noticed it working now in VS 17.13.1.  This is a huge help!

Thank you again.

**Comment by CyrusNajmabadi** [comment]
You're welcome :)
