### ISSUE TITLE
The compiler does not flag the code as an error when missing parentheses for extension methods that embed string interpolation

### ISSUE THREAD

**Issue by Nora-Zhou01** [dotnet/roslyn#76255]
**Version Used**: .NET SDK 10.0.100-alpha.1.24573.1

**Steps to Reproduce**:

1. Launch the [StringInterpolationFeature.zip](https://github.com/user-attachments/files/17916664/StringInterpolationFeature.zip) project
2. View Test.cs code

**Issue description**:
When miss the parentheses for an extension method that embeds string interpolation, the compiler does not flag the code as an error and the code compiles without errors

**.NET 10.0 (.NET 8.0 and .NET 9.0 with the same results)**

![Image](https://github.com/user-attachments/assets/ef688802-a3e5-4c74-849f-7d8f145c4d56)

**.NET 7.0 （.NET 6.0 results are the same)**

![Image](https://github.com/user-attachments/assets/ce585d11-f564-48a1-9f9c-d987aae43023)

**.NET 5.0**

![Image](https://github.com/user-attachments/assets/499b6e55-8362-4ee1-b7f0-f0c6182ed3b0)

**More Info**:

The issue copied from https://github.com/dotnet/winforms/issues/12547

**Comment by huoyaoyuan** [comment]
The error message is not for "missing parentheses". It's about overloading. C# 10 allows methods to be converted to `var` or `object` with implicit delegate type, but only non overloaded method because there's only single candidate for a given name.
`ToLower` has two overloads. If replace with `ToLowerInvariant`, the behavior is the same with the extension `ToCountryCapacity`.

For conversion to `object`, there is a warning CS8974 for 'do you intend to invoke the method'. It can be applied to string interpolation, but not yet.
