### ISSUE TITLE
Interceptors suppress analyzer warnings when location is the entire `InvocationExpressionSyntax`, but not when location is `InvocationExpressionSyntax.Expression`

### ISSUE THREAD

**Issue by jtschuster** [dotnet/roslyn#76266]
Version 4.13.0-2.24570.4

In the ILLink analyzer, we provide warnings on the entire invocation syntax, but for `RequiresX` warnings, it makes more sense to warn only on the reference to the method. https://github.com/dotnet/runtime/pull/110086 changes these warning to be on the `InvocationExpressionSyntax.Expression` rather than the entire `InvocationExpressionSyntax`, but it causes new warnings to appear on invocations that have been intercepted to call non-warnings methods. I would expect that since the location of the warning is contained within the original location that it would still be silenced by the interception of the call site.

Should all warnings with locations contained within in the invocation location be silenced? Or are there cases where that behavior would be an issue? Is there another way to work around this?

**Comment by RikkiGibson** [comment]
Something seems odd here. I do not think the interceptors feature suppresses any analyzer warnings. My expectation is that ILLink is shipping a diagnostic suppressor which calls the API specified in #72093 as part of deciding whether to suppress a warning. It's possible that suppressor needs to be updated in order to do the right thing when it finds a diagnostic with the new location form.

**Comment by jtschuster** [comment]
Ah, it was a diagnostic suppressor for Microsoft.Extensions.Configuration that suppressed based on the entire InvocationExpression. Thanks for your help!
