### ISSUE TITLE
Compilation error involving dynamic parameter not being detected

### ISSUE THREAD

**Issue by mus65** [dotnet/roslyn#76322]
**Version Used**: 

.NET SDK 9.0.101

The following code compiles successfully and crashes at runtime instead. This is somehow caused by the dynamic parameter.

```
class Program
{
    static void Main() => ReturnString(0);
    static string ReturnString(dynamic p) => ReturnInt(p);
    static int ReturnInt(dynamic p) => 0;
}
```

`dotnet run`:

```
Unhandled exception. Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot implicitly convert type 'int' to 'string'
   at CallSite.Target(Closure, CallSite, Object)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at Program.ReturnString(Object p) in Program.cs:line 4
   at Program.Main() in Program.cs:line 3
```

Weirdly enough, when removing the class, the compilation error is detected correctly:

```
static string ReturnString(dynamic p) => ReturnInt(p);
static int ReturnInt(dynamic p) => 0;
ReturnString(0);
```

**Expected Behavior**:

Compilation error: `Cannot implicitly convert type 'int' to 'string'`

**Actual Behavior**:

No compilation error and runtime crash.

**Comment by jaredpar** [comment]
> The following code compiles successfully and crashes at runtime instead.

This behavior is "By Design". Once any part of a normal method call is `dynamic` then the entire call goes through dynamic dispatch. That means `ReturnInt` is not bound until runtime and at that point the binder determines it's `int` return type is not compatible with `string` and throws. 

> Weirdly enough, when removing the class, the compilation error is detected correctly:

When you remove the class the methods become local functions, those don't go through dynamic dispatch. That has the effect of moving certain errors from runtime to compile time.
