### ISSUE TITLE
rename operation corrupts unrelated source code

### ISSUE THREAD

**Issue by weltkante** [dotnet/roslyn#76439]
**Version Used**: 

VS 2022 17.13.0 Preview 2.0

**Steps to Reproduce**:

start with pasting

```csharp
public class Program
{
    public void Main()
    {
        int count = 10, n = 15;

        for (int metaInput = -(count + 2); metaInput < n; metaInput++)
        {
            for (int input2 = -(count + 2); input2 < n; input2++)
            {
            }
        }
    }
}
```

and place the cursor on one of the `metaInput` references. Then rename to `input1` with F2.

**Expected Behavior**:

Renaming doesn't touch unrelated code

**Actual Behavior**:

The inner for loop gets corrupted in various ways depending on which occurence of the variable you tried to rename:

`for (int input2 = -(count + 2); ); input2 < n; input2++)`
`for (int input2 = -(count count + 2); input2 < n; input2++)`
`for (int (int input2 = -(count + 2); input2 < n; input2++)`

**Comment by jcouv** [comment]
FWIW, I was able to repro this problem in 17.13p2 (but not in 17.12).
![Image](https://github.com/user-attachments/assets/93020b03-4790-46ec-8c11-ec76ca2667db)
FYI @CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
@genlu @Cosifne @AmadeusW @gundermanc Related to any of the recent changes with the rename dialog?

**Comment by gundermanc** [comment]
> [@genlu](https://github.com/genlu) [@Cosifne](https://github.com/Cosifne) [@AmadeusW](https://github.com/AmadeusW) [@gundermanc](https://github.com/gundermanc) Related to any of the recent changes with the rename dialog?

I'm no longer on the Editor team. Tagging @olegtk for added visibility.

**Comment by AmadeusW** [comment]
This reproes with copilot rename completely disabled.
Notice in the preview that colorization is off. In this state, the code will break upon commit
![Image](https://github.com/user-attachments/assets/6d21ec82-8edb-4e17-8494-86108c2c9064)

Notice that colorization is fine during preview when renaming to most common words
![Image](https://github.com/user-attachments/assets/97fd4b90-bb6f-4947-8342-c1e670e5f778)

The colorization breaks (and the bug is now triggered) when the renamed identifier is also a certain language keyword that and needs to be prefixed with `@`. It seems to be the case for `in`, `out` but not for others like `static` or `public`
![Image](https://github.com/user-attachments/assets/d1b271b8-f457-4967-b3c3-19b86419ecb6)

**Comment by CyrusNajmabadi** [comment]
Looking to see if i can figure out why incremental parsing is breaking.

**Comment by CyrusNajmabadi** [comment]
Ok.  So the 'new text' (what we're trying to parse), contains:

`for (int in = -(count + 2); in < n; in++)`

But the tree we incrementally parse produces:

`for (int in = -(count + 2); < n; in++)`

instead.  Will see if i can make a small incremental parser repro.

**Comment by CyrusNajmabadi** [comment]
Ok.  Fix available.
