### ISSUE TITLE
IDE0058 triggers on expressions with 'out' params

### ISSUE THREAD

**Issue by AbakumovAlexandr** [dotnet/roslyn#76477]
**Version Used**:  17.12.1

**Steps to Reproduce**:

1. Add a code:
```
    var d = new Dictionary<int, int>();

    // Option 1
    var value = 0;
    d.TryGetValue(1, out value); // IDE0058
    Console.WriteLine(value);

    // Option 2
    d.TryGetValue(1, out var value); // IDE0058
    Console.WriteLine(value);
```

**Diagnostic Id**:  IDE0058

**Expected Behavior**:  There shouldn't be the IDE0058 warning, since both expressions obviously have the side effect of declaring and\or assigning a local variable `value`. So the intent of this expression is pretty obvious and the only option of adding a discard doesn't seem to ['improves code clarity by explicitly showing the intent to discard an unused value.'](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0058#overview)

**Actual Behavior**:  The IDE0058 warning is displayed.

**Comment by CyrusNajmabadi** [comment]
@AbakumovAlexandr 'value' doesn't appear to be used in your example.  As such, the code is less clear as it declares something with a name that isn't used.  Using an explicit discard makes the code clearer by having the code be explicit in its intent that it will not use this out variable.  Absent more info for the repro, this looks by design.

**Comment by AbakumovAlexandr** [comment]
> [@AbakumovAlexandr](https://github.com/AbakumovAlexandr) 'value' doesn't appear to be used in your example. 

I've edited the original samples above with a dummy usage of the 'value' variable, but it still produces the `IDE0058` warning,

>  Using an explicit discard makes the code clearer by having the code be explicit in its intent that it will not use this out variable. Absent more info for the repro, this looks by design.

As far as I understand it from the [reference](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0058#overview), the `IDE0058: Remove unnecessary expression value` warning is designed to flag expressions which it thinks are unnecessary. However, both the expressions in the samples are clearly necessary. They don't perform an assignment in a form of `var result = MethodCall();`, but they do the assignment in a form of an 'local variable = out param'. It looks like a missing case in the rule's implementation, doesn't it?

**Comment by CyrusNajmabadi** [comment]
> but it still produces the IDE0058 warning,

That seems like a bug then.

**Comment by CyrusNajmabadi** [comment]
> However, both the expressions in the samples are clearly necessary. 

I was only referring to your original example, where they did not seem necessary.

**Comment by AbakumovAlexandr** [comment]
> I was only referring to your original example, where they did not seem necessary.

Sorry for confusion. My initial intent was to make the samples as short as possible, but it definitely was not a good idea in terms of clarity :)

**Comment by CyrusNajmabadi** [comment]
This is by design.  The analyzer is correctly reporting that you're ignoring the return value of TryGetValue (the boolean that says if it actually succeeded or not).  While it is sometimes ok to ignore this value, it is not a normal coding pattern with APIs like this, and the analyzer is pointing that out.   To indicate that this was intentional, you write:

```c#
_ = d.TryGetValue(1, out value);
```

This allows the code to be explicit in its ignoring of the value, allowing future readers to know it was intentional and not an accidental omission.
