### ISSUE TITLE
Do not use the var keyword

### ISSUE THREAD

**Issue by ateregulov** [dotnet/roslyn#7710]
I suggest not to use this operator because of its redundancy.

before:

    var x = 5;
    var list = new List<int>();

after:

    x = 5;
    list = new Lisr<int>();

**Comment by orthoxerox** [comment]
Not a good idea, look:

```
longvariablename = 1;
a = TrueOrFalse();
if (a) 
    longvarialbename = CalculationThatReturns1000(); 
WriteLine(longvariablename); //Still 1?! have fun debugging that;
```

**Comment by ateregulov** [comment]
@orthoxerox, let's compare:

    var longvariablename = 1;
    a = TrueOrFalse();
    if (a) 
        longvarialbename = CalculationThatReturns1000(); 
    WriteLine(longvariablename); //Still 1?! have fun debugging that;

Is there a difference?

The problem you have described is classical argument to using immutable variables. 
Also, code can be moved into the method, that is preferable.
And, also available to use the old optional 'var' in both lines.

I believe this specific problem does not affect the variable declarations.

**Comment by HaloFour** [comment]
It's great when a typo leads to the accidental creation of a new variable.  Explicit variable creation is on the short-list of language features which aid in avoiding the pit of failure.  Copying bad-and-discouraged practices from the non-strict versions of dynamic languages is a terrible idea.

**Comment by bondsbw** [comment]
@ateregulov 
> ```c#
var longvariablename = 1;
a = TrueOrFalse();
if (a) 
    longvarialbename = CalculationThatReturns1000(); 
WriteLine(longvariablename); //Still 1?! have fun debugging that;
```
> Is there a difference?

Depends on whether you are using your proposal or C# as it already exists:
* C# plus your proposal:  No difference, the result is identical
* C# as it already exists:  Error CS0103, the name 'longvarialbename' does not exist in the current context

Perhaps you intended this example:
```c#
var longvariablename = 1;
a = TrueOrFalse();
if (a) 
    var longvarialbename = CalculationThatReturns1000(); 
WriteLine(longvariablename);
```
which might be a legal code snippet in today's C#.  The difference is that it's much clearer that the body of the if statement declares a new variable instead of setting an existing variable's value.

**Comment by gafter** [comment]
@HaloFour explains very well why we'd never do this.
