### ISSUE TITLE
"ProjectReference" for Analyzers?

### ISSUE THREAD

**Issue by steffenloesch** [dotnet/roslyn#7729]
I'm in the situation where I want to apply an analyzer to a project of the **same** solution that analyzer is in. Project-file wise, is there something like a "ProjectReference" for analyzers, something like 
`<ProjectAnalyzer Include="..\MyAnalyzer\MyAnalyzer.csproj" />`?

**Comment by srivatsn** [comment]
No there's no such thing. The primary reason for that is that since analyzers are loaded in the VS process and the CLR doesn't let you unload assemblies, every time a build happens, VS would need to restarted for the new analyzer to take effect. This would reduce any utility a project reference might have and so we decided to not spend time implementing it. You can always add a file reference to the dll in the bin\debug folder but you'll have the same headache of having to restart on every build. Ideally you have the analyzer in a separate "toolset" location which you can choose to update once in a while.
