### ISSUE TITLE
Proposal: Type inferred default value

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#7737]
Currently, if you want to use default values you have to specify the exact type for `default` operator,

``` cs
public T F<T>(CancellationToken ct = default(CancellationToken)) => default(T);
```

However, compiler could infer the desirable type from the target,

``` cs
public T F<T>(CancellationToken ct = default) => default;
```

#1419 rules can also help to infer the best type for the resultant default value.

**Comment by lachbaer** [comment]
I think it is better to leave the `default` keyword as a 'function', when inside a body.

First, it is concise, not one time a 'function' another time a 'keyword';

Second, it is better to always write down, what default is returned; maybe one time it may be the class, the other time it may be a derived class.

verbosity is one of the advantages of C#, just see the 'superfluid' `abstract` keyword on the before the `class` keyword, because it is clear that it must be an abstract class, as at least one function inside is abstract - greetings from C++ ;-)

For instanciation, like in the optional parameter above, it could really ease typing and reading the code.

**Comment by alrz** [comment]
@lachbaer Your argument can be applied to `var`, verbosity is good as long as it's not reduntant. And this has nothing like what `abstract` implies. `default` has been always a keyword and not a "function". And also, you don't need to always omit the type (like what you said, you can use it only for default parameters as a convention), as for `var` which you can simply prefer verbosity and be explicit. It's more of a preference but just like `var` you might prefer conciseness.

**Comment by lachbaer** [comment]
@alrz Don't take me to literal, that's why I put function in hyphens :-)

**Comment by alrz** [comment]
Moved to https://github.com/dotnet/csharplang/issues/102
