### ISSUE TITLE
Formatting of automatic properties in WPF and UWP apps

### ISSUE THREAD

**Issue by SBArbeit** [dotnet/roslyn#7768]
Hi!

When I'm editing a WPF or UWP app in Visual Studio 2015, and I'm creating an automatic property in C#, I type something like: 
```C#
public string Whatever {get
```
but when I type the semicolon after the get, the get; moves down to the next line, regardless of my editor formatting settings in Visual Studio.
```C#
public string Whatever {
    get;
```

This does not happen in ASP.NET applications. Hardly a showstopper, but annoying and breaks my flow for a moment.

Thanks!
Scott

**Comment by CyrusNajmabadi** [comment]
Note: this issue only reproes if the completion is up (due to typeing "get") when the semicolon is typed.  If the completion list is not up, then no errant formatting occurs.  If the completion list is up, you get the bad behavior.

Of course, because we pop up the completion list on "get" by default, the common case is for this to repro.

**Comment by balajikris** [comment]
Also, Automatic brace completion must be turned off, to be able to repro this.
