### ISSUE TITLE
Make ChangeSignature API public

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#7828]
There must have been an issue tracking this somewhere, but I couldn't find it.

This came up again today on Gitter. Such an API would be useful for making things like "Remove unused parameter" and "Move CancellationToken parameter to last position", etc.

**Comment by CyrusNajmabadi** [comment]
This would need to go through an API proposal.  in general, the reason we don't just make things public is because it increases maintenance costs and locks down our ability to change things in teh future.  We can open things up, but we have a process that requests need to go through to make sure the appropriate people weigh in and the right API shape is determined and shipped.
