### ISSUE TITLE
Missing check for an ability to emit DynamicAttribute in SynthesizedFieldSymbolBase.AddSynthesizedAttributes

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#7840]
Note the assumption comment in the code below. I believe the assumption is incorrect. For example, a dynamic local, for which we don't verify the presence of the attributes, can become a field in a lambda closure.  
```
            if (this.Type.TypeSymbol.ContainsDynamic())
            {
                // Assume that someone checked earlier that the attribute ctor is available and has no use-site errors.
                AddSynthesizedAttribute(ref attributes, compilation.SynthesizeDynamicAttribute(this.Type.TypeSymbol, this.Type.CustomModifiers.Length));
            }
```

 I think this code should use the same logic that is used by SynthesisedParameterSymbol.AddSynthesizedAttributes at the moment.

**Comment by jcouv** [comment]
@AlekseyTs 
The code you copied above doesn't match `SynthesizedFieldSymbolBase.AddSynthesizedAttributes` or its history.

Looking at the current code for that method and after the fix for #7809, `Compilation.TrySynthesizeAttribute` (called from `SynthesizeDynamicAttribute`) should now perform those checks and return null. So the attribute won't be added if the types aren't available or have a use-site error.
So I would just remove the assumption comment, which is no longer relevant. There are also one or two other callers of `SynthesizeDynamicAttribute` that could be updated.

That said, I noticed something odd in `SynthesizeDynamicAttribute`. In some other cases than the one discussed above, it could emit a dynamic attribute using `System_Runtime_CompilerServices_DynamicAttribute__ctorTransformFlags`. But that attribute type isn't optional, whereas `System_Runtime_CompilerServices_CompilerGeneratedAttribute__ctor` is.
My guess is that it should be optional too. I'll stop by to discuss desired behavior.
