### ISSUE TITLE
Code reformatting introduces "wrong" indentation with nested delegates

### ISSUE THREAD

**Issue by Tragetaschen** [dotnet/roslyn#7876]
When doing automatic code formatting for the following snippet
```csharp
a.Add(()=>b(() =>
{
}));
```
The result is this
```csharp
a.Add(() => b(() =>
  {
  }));
```
Where the curly braces have been indented with two spaces.

I would have expected the braces to not be moved, but I can see how this could be seen correct behavior. After all in the first line, there are the two spaces introduced around the first fat arrow.

**Comment by orthoxerox** [comment]
I think the indentation is introduced because the `Add()` call has been split across several lines.

**Comment by Pilchie** [comment]
@Tragetaschen we're unable to reproduce this.  Can you explain how you invoked formatting?  Do you mean when you hit `;`?  Have you changed any of your formatting options from the defaults?

**Comment by Tragetaschen** [comment]
Actually, it happens "all the time": Both when invoking the "Format Document" function and when typing the final semicolon. I have made it a strict habit in my developer live, to never ever change the formatting options that ship with VS.

To reproduce, I create a blank "Console Application (Package)" (the new and shiny ASP.NET RC1 Update 1 world) and put the above snippet in the Program's `Main` method.

Before:
![indent before](https://cloud.githubusercontent.com/assets/1947968/12250186/4f6a6b8e-b8c5-11e5-842c-55dfa78720ad.png)
One key stroke later:
![indent after](https://cloud.githubusercontent.com/assets/1947968/12250182/4b7e6b6a-b8c5-11e5-8f1a-1452d36dd83c.png)

**Comment by Tragetaschen** [comment]
Is this intentionally closed? I cannot reopen (would need to be collaborator).

**Comment by Pilchie** [comment]
Okay - I understand what is happening here now.  Our formatting engine doesn't really prescribe an indentation for the braces of anonymous methods or lambdas, but it *does* try to preserve the indentation of those braces relative to the start of the lambda.

In the above example, this is happening because in the initial code there are no spaces around the `=>` of the first lambda.  When that is formatted so that a space is inserted on either side, the start of the second lambda shifts two characters to the right, and the formatting engine preserves that relationship by also shifting the braces two characters to the right.

I'm going to change the resolution tag, but I actually think formatting is doing the right thing here.

**Comment by Tragetaschen** [comment]
Then my intuition in the OP was correct :)

The only pro-bug argument I can think of is that after the automatic formatting, the curly braces are not on the four-spaces indentation "grid" where they normally appear. But as I said, I can see where it's coming from and was just surprised the first time I saw it happen.
