### ISSUE TITLE
Proposal: using exclusions

### ISSUE THREAD

**Issue by LazyBui** [dotnet/roslyn#7931]
It's really obnoxious when you have a single conflict between two namespaces but want everything else that doesn't conflict between the two namespaces.

For example, perhaps you have a `Panel` control in a namespace that has other useful code and have a need to reference `System.Web.UI.WebControls`. Or perhaps you need a specific `ListItem` from a different namespace but there's also one in `System.Web.UI.WebControls`. It would be really helpful to be able to exclude the conflict specifically and keep everything else without explicit qualification.

Syntactically, I would imagine this to be a fairly simple grammar change. It would not apply to `using` aliases.

It would only be relevant to `using static` and regular `using` declarations. The exclusion operator would be optional. As such you could do something like:

`using static System.Math exclude Abs;`
`using static System.Math exclude [Abs, Tan];`
`using System.Web.UI.WebControls exclude Panel;`

Obviously there's bikeshedding to be done, but this should be illustrative.

**Comment by Unknown6656** [comment]
I absolutely love this idea, as I always have resorted to expressions like
```
using p1 = Very.Long.Namespace.No1.Panel;
using p2 = Very.Long.Namespace.No2.Panel;
// etc.
```

**Comment by asvishnyakov** [comment]
+1

**Comment by alrz** [comment]
also `using` for non concrete types, like
```
using System.Action;
// equivalent to
using Action = System.Action;
```

**Comment by ViIvanov** [comment]
@alrz 

What about
```cs
// Assembly1
namespace MyCompany
{
  public class Value1 { }
}

// Assembly1 or another Assembly2
namespace MyCompany.Value1
{
  public class Value2 { }
}
```

What does mean
```cs
using MyCompany.Value1;
```
?

**Comment by alrz** [comment]
@Vilvanov You example has already a conflict for `Value1`, new syntax would make no difference. (Although, I'm not sure if this would be a breaking change for existing code or not, probably it would).

**Comment by alrz** [comment]
@Vilvanov Your example has already a conflict for `Value1`, new syntax would make no difference. (Although, I'm not sure if this would be a breaking change for existing code or not, probably it would).

**Comment by ViIvanov** [comment]
@alrz Thanks!

Yes, we already can not use classes and namespaces with same names (without extern aliases).

Sorry, will compile code before post next time :о)

**Comment by alistair** [comment]
Another alternative syntax ( for exclusion ) would be to use the keyword hiding

    using static System.Math hiding Abs;
    using static System.Math hiding {Abs, Tan};
    using System.Web.UI.WebControls hiding Panel;


could I suggest the opposite.   using inclusions?

    using static System.Math.{Abs};
    using static System.Math.{Abs, Tan};
    using System.Web.UI.WebControls.{Panel};

which would only include those classes or methods (in the static using case).


I've never looked to the reasoning for it but I have always been surprised at how 'eager' namespace loading is the c# way.  This is in contrast with java where even static imports are usually (by style) explicitly declared.  .* (inclusive) imports are considered bad style (at least in teams i've worked in).

**Comment by svick** [comment]
I don't understand why would you need exclusions when you effectively already have inclusions using type aliases.

So, instead of the proposed:

```c#
using System.Web.UI.WebControls exclude Panel;
using SomeOtherNamespaceContainingPanel;
```

You can already write:


```c#
using System.Web.UI.WebControls;
using SomeOtherNamespaceContainingPanel;
using Panel = SomeOtherNamespaceContainingPanel.Panel;
```

**Comment by LazyBui** [comment]
It's boilerplate that I'd rather not have to write and in the particular case of `System.Web.UI.WebControls`, that means I would be committed to:
```csharp
using System.Web.UI.WebControls;
using SomeOtherNamespaceContainingPanel;
using SomeOtherNamespaceContainingListItem;
using Panel = SomeOtherNamespaceContainingPanel.Panel;
using ListItem = SomeOtherNamespaceContainingListItem.ListItem;
```

And so on and so forth. Each one you'd like to exclude ends up adding quite a bit of boilerplate. I would rather be able to specify that one or some of the things from a particular namespace are not things I'm interested in while I am interested in everything else. It's obviously not Earth-shattering and that's probably why I couldn't find a proposal about it, but it would certainly be a boilerplate reduction. I've hit it enough times now that I felt like I wanted to at least have it proposed.

@alistar I think there are a couple reasons that strike me as likely why explicit inclusion isn't the model.

C#'s `using` is more of a project-level facility while traditional imports are more of a file-level facility. If you think about Python, Rust, Java, and many other languages, the physical structure and the logical structure are tightly linked.

That's not the case in C#. You're pretty free to define the logical structure in any way you'd like physically in terms of files/folders. Many projects utilize the same structure for both because it's just the easiest to do. But conceptually it means that C# is more project-focused (or concerned more on the logical structure of the project) than it is file-structured (which would be more concerned with the physical structure of the project).

In such a context, you could still do explicit imports. But it would run contrary to this model of not forcing its idea of physical structure upon you. If you had to explicitly qualify everything, you could have a lot of imports for not a lot of code. Which would encourage you to make more files to reduce the surface area. This might also increase coupling since the distinctions between the files may be arbitrary in order to obtain fewer imports.

It's also more effort to use, which seems likely to be the actual reason why it is the way it is. C# is designed to be comfortable and I don't think anyone would argue against explicit qualification requiring more changes more frequently than the current model.

**Comment by gafter** [comment]
We are now taking language feature discussion in other repositories:
- https://github.com/dotnet/csharplang for C# specific issues
- https://github.com/dotnet/vblang for VB-specific features
- https://github.com/dotnet/csharplang for features that affect both languages

Features that are under active design or development, or which are "championed" by someone on the language design team, have already been moved either as issues or as checked-in design documents. For example, the proposal in this repo "Proposal: Partial interface implementation a.k.a. Traits" (issue 16139 and a few other issues that request the same thing) are now tracked by the language team at issue 52 in https://github.com/dotnet/csharplang/issues, and there is a draft spec at https://github.com/dotnet/csharplang/blob/master/proposals/default-interface-methods.md and further discussion at issue 288 in https://github.com/dotnet/csharplang/issues. Prototyping of the compiler portion of language features is still tracked here; see, for example, https://github.com/dotnet/roslyn/tree/features/DefaultInterfaceImplementation and issue 17952.

In order to facilitate that transition, we have started closing language design discussions from [the roslyn repo](https://github.com/dotnet/roslyn) with a note briefly explaining why. When we are aware of an existing discussion for the feature already in the new repo, we are adding a link to that. But we're not adding new issues to the new repos for existing discussions in this repo that the language design team does not currently envision taking on. Our intent is to eventually close the language design issues in the Roslyn repo and encourage discussion in one of the new repos instead.

Our intent is not to shut down discussion on language design - you can still continue discussion on the closed issues if you want - but rather we would like to encourage people to move discussion to where we are more likely to be paying attention (the new repo), or to abandon discussions that are no longer of interest to you.

If you happen to notice that one of the closed issues has a relevant issue in the new repo, and we have not added a link to the new issue, we would appreciate you providing a link from the old to the new discussion. That way people who are still interested in the discussion can start paying attention to the new issue.

Also, we'd welcome any ideas you might have on how we could better manage the transition. Comments and discussion about closing and/or moving issues should be directed to https://github.com/dotnet/roslyn/issues/18002. Comments and discussion about this issue can take place here or on an issue in the relevant repo.

-----------------

I am not moving this particular issue because I don't have confidence that the LDM would likely consider doing this.
