### ISSUE TITLE
Dictionary parameter names Dictionary<TKey nameKey, TValue nameVal>

### ISSUE THREAD

**Issue by vildar82** [dotnet/roslyn#7945]
Dictionary parameter names Dictionary<TKey nameKey, TValue nameVal>

**Comment by bondsbw** [comment]
I'm not sure what this is proposing.  What use would the names be?

**Comment by vildar82** [comment]
Enhance readability, remember what it is the key and value.

**Comment by bondsbw** [comment]
Provide an example of how you would declare it and how you would reference it later.  I'm just not seeing how that would work.

**Comment by alrz** [comment]
if the sole use case is for "remembering" what they are used for, there is already a fully fledged feature just for this purpose called comments.

**Comment by vildar82** [comment]
```c#
var panels = new Dictionary<string MarkKey, Panel PanelVal>();
var panelPair = panels.Where(p => p.markKey == "M-1").First();
string mark = panelPair.MarkKey;
Panel panel = panelPair.PanelVal;
```

**Comment by alrz** [comment]
@vildar82 The way you used `Dictionary<,>` you don't need to. This is possible using tuples (#347),
```cs
var panels = new List<(string MarkKey, Panel PanelVal)>();
var panelPair = panels.Where(p => p.MarkKey== "M-1").First();
string mark = panelPair.MarkKey;
Panel panel = panelPair.PanelVal;
```

**Comment by vildar82** [comment]
@alrz and how to ensure the uniqueness of the entries in the list?

**Comment by alrz** [comment]
@vildar82 I said "the way you used it in your example", I think you should use indexers for that,
```cs
var panels = new Dictionary<string, Panel>();
var panel = panels["M-1"];
```
done.

**Comment by Thaina** [comment]
Maybe you could use HashSet<tuple>

You can write IEqualityComparer<tuple> to compare only what you want to be a key. Then use it in HashSet constructor

**Comment by gafter** [comment]
We are now taking language feature discussion in other repositories:
- https://github.com/dotnet/csharplang for C# specific issues
- https://github.com/dotnet/vblang for VB-specific features
- https://github.com/dotnet/csharplang for features that affect both languages

Features that are under active design or development, or which are "championed" by someone on the language design team, have already been moved either as issues or as checked-in design documents. For example, the proposal in this repo "Proposal: Partial interface implementation a.k.a. Traits" (issue 16139 and a few other issues that request the same thing) are now tracked by the language team at issue 52 in https://github.com/dotnet/csharplang/issues, and there is a draft spec at https://github.com/dotnet/csharplang/blob/master/proposals/default-interface-methods.md and further discussion at issue 288 in https://github.com/dotnet/csharplang/issues. Prototyping of the compiler portion of language features is still tracked here; see, for example, https://github.com/dotnet/roslyn/tree/features/DefaultInterfaceImplementation and issue 17952.

In order to facilitate that transition, we have started closing language design discussions from [the roslyn repo](https://github.com/dotnet/roslyn) with a note briefly explaining why. When we are aware of an existing discussion for the feature already in the new repo, we are adding a link to that. But we're not adding new issues to the new repos for existing discussions in this repo that the language design team does not currently envision taking on. Our intent is to eventually close the language design issues in the Roslyn repo and encourage discussion in one of the new repos instead.

Our intent is not to shut down discussion on language design - you can still continue discussion on the closed issues if you want - but rather we would like to encourage people to move discussion to where we are more likely to be paying attention (the new repo), or to abandon discussions that are no longer of interest to you.

If you happen to notice that one of the closed issues has a relevant issue in the new repo, and we have not added a link to the new issue, we would appreciate you providing a link from the old to the new discussion. That way people who are still interested in the discussion can start paying attention to the new issue.

Also, we'd welcome any ideas you might have on how we could better manage the transition. Comments and discussion about closing and/or moving issues should be directed to https://github.com/dotnet/roslyn/issues/18002. Comments and discussion about this issue can take place here or on an issue in the relevant repo.

This may be close enough to https://github.com/dotnet/csharplang/issues/280 that discussion can continue there.
