### ISSUE TITLE
Would it be possible to support finding extension methods at runtime?

### ISSUE THREAD

**Issue by NullVoxPopuli** [dotnet/roslyn#7953]
here is my scenario:

``` csharp
dynamic myTable = db.Send(RelationshipName);
var myInclude = myTable.Include(i => ((object)i).Send(relationship));
```

`myTable.Include` throws a compile-time error, due to dynamics currently not being able to find extension methods.

Since dynamic stuff is all run-time anyway, couldn't the extension method just be looked up at runtime?
or, why can't it?

Could there be an implementation that would allow finding extensions methods at runtime?

Originally / Incorrectly posted here: https://github.com/aspnet/dnx/issues/3310

**Comment by alrz** [comment]
Why are you using `dynamic` here? I really want to know.

**Comment by NullVoxPopuli** [comment]
I'm writing a wrapper around ef to maintain filters on specific models as you navigate the relation tree. Such as filtering out private objects if the user doesn't have permission too view private objects.  Send is a method which returns an object of unknown type at compile time.

**Comment by alrz** [comment]
@NullVoxPopuli So why you don't return an interface if you know it has the `Include` method? Also, I see you are casting `i` to `object`, it's because it's `dynamic` right? I think all this wouldn't be necessary if you write your code statically typed, because C# is statically typed. As long as you are not working with DLR I can't undrestand what is the need for `dynamic` considering its huge performance hit.

**Comment by NullVoxPopuli** [comment]
There isn't an interface between the models, I thought? They are just pocos.
In my situation, the scaffolded models from the database can't be change, or have too many changes, cause they would need to be regenerated when the database changes (database-first)

**Comment by alrz** [comment]
my instinct tells me something's wrong with this, but with the example you gave there's no way of knowing.

**Comment by NullVoxPopuli** [comment]
What I ended up doing, actually was abandoning dnx / ef7, and re-do my project in .net4.5 / ef6... which I'm not excited about.. but:
EF6 has lazy loading, so I don't need to rely on EF7's requirement to use `.Include` -- which was the main issue I was trying to get around.

**Comment by gafter** [comment]
We are now taking language feature discussion in other repositories:
- https://github.com/dotnet/csharplang for C# specific issues
- https://github.com/dotnet/vblang for VB-specific features
- https://github.com/dotnet/csharplang for features that affect both languages

Features that are under active design or development, or which are "championed" by someone on the language design team, have already been moved either as issues or as checked-in design documents. For example, the proposal in this repo "Proposal: Partial interface implementation a.k.a. Traits" (issue 16139 and a few other issues that request the same thing) are now tracked by the language team at issue 52 in https://github.com/dotnet/csharplang/issues, and there is a draft spec at https://github.com/dotnet/csharplang/blob/master/proposals/default-interface-methods.md and further discussion at issue 288 in https://github.com/dotnet/csharplang/issues. Prototyping of the compiler portion of language features is still tracked here; see, for example, https://github.com/dotnet/roslyn/tree/features/DefaultInterfaceImplementation and issue 17952.

In order to facilitate that transition, we have started closing language design discussions from [the roslyn repo](https://github.com/dotnet/roslyn) with a note briefly explaining why. When we are aware of an existing discussion for the feature already in the new repo, we are adding a link to that. But we're not adding new issues to the new repos for existing discussions in this repo that the language design team does not currently envision taking on. Our intent is to eventually close the language design issues in the Roslyn repo and encourage discussion in one of the new repos instead.

Our intent is not to shut down discussion on language design - you can still continue discussion on the closed issues if you want - but rather we would like to encourage people to move discussion to where we are more likely to be paying attention (the new repo), or to abandon discussions that are no longer of interest to you.

If you happen to notice that one of the closed issues has a relevant issue in the new repo, and we have not added a link to the new issue, we would appreciate you providing a link from the old to the new discussion. That way people who are still interested in the discussion can start paying attention to the new issue.

Also, we'd welcome any ideas you might have on how we could better manage the transition. Comments and discussion about closing and/or moving issues should be directed to https://github.com/dotnet/roslyn/issues/18002. Comments and discussion about this issue can take place here or on an issue in the relevant repo.

I am not moving this particular issue because I don't have confidence that the LDM would likely consider doing this.
