### ISSUE TITLE
Add IsLValue Property on IReferenceExpression

### ISSUE THREAD

**Issue by basoundr** [dotnet/roslyn#8032]
Add a property, called `IsLValue` or something similar, on IReferenceExpression which says whether the expression is a fetch or an assignment target.

**Comment by JohnHamby** [comment]
While the VB bound trees contain enough information to implement such a property, the C# bound trees do not. Because this is a useful property, we should consider enhancing the C# compiler to track this. However, it won't happen for Update 2.

**Comment by JohnHamby** [comment]
The information in the VB bound trees turns out not to be sufficient to implement the desired capability. What the compiler tracks is whether a reference could be used for a store, not whether it actually has been used for a store.

Implementing this property would require work in both the VB and C# compilers.

**Comment by jinujoseph** [comment]
Turned out we probably don't need this any more.
