### ISSUE TITLE
Specify Variance in Delegates.

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#8132]
It would good to be able to specify the variance of the generic type parameters of delegates.
So that this following was able to compile.
```VB.net
Dim f As Func(of out object, boolean) = AddressOf Foo

Function Foo( ByRef output As object) As Boolean
End Function
```

**Comment by HaloFour** [comment]
Generic type variance is set by the delegate itself, not an instance of the delegate.  That is a function of the CLR, not the language.  Also, your example is not one of variance, you're trying to use a completely different signature:  `&System.Object` vs. `System.Object`.

**Comment by gafter** [comment]
What is this I don't even

**Comment by AnthonyDGreen** [comment]
Hey Adam!

If I understand you right you'd like to be able to specify some kind of variance modifier at the use site--when you construct the delegate--rather than or in addition to within the definition of the delegate itself. **Is that correct?**

The specific example you've given where you believe this will be useful is in specifying that ByRef parameter in a target method could satisfy a ByVal parameter in the original delegate. **Is that the specific real-world scenario you have that you feel motivates this?**

**Would this request also be satisfied by extending VBs existing delegate relaxation capabilities to handle this case?**

**Comment by AdamSpeight2008** [comment]
@AnthonyDGreen 

All the types specified in a `Func(Of Tin, TResut)` are `ByVal`. I know of no way of specifying that a parameter is `ByRef`  
**Workaround**
Except for I think of defining a new delegate, for me to be able to specify the `ByRef` parameter,

```VB.net
    Dim D As New Dee(AddressOf Foo)

    Delegate Function Dee(x As Integer, ByRef y As Integer) As Boolean
```

**Desired**
```
Dim dee = Function( x as integer, byref y as integer) as boolean
```
The compiler would do some *Type-Fu* and I'd have a  `Func(Of <In> Integer, <InRef> Integer, <Out> Boolean>`. That doesn't tie me to some explicitly specified delegate definition. Eg (`dee`)

**Comment by HaloFour** [comment]
There is no type-fu that VB.NET can do to make any of the delegates in the `Func` or `Action` family accept a `ref` or `ByRef` parameter.  Even if the parameter *looked* `ByRef` to the caller, it couldn't be `ByRef` to the callee, and any changes made to the parameter would be lost.  The signature of the delegate is simply different.  The type of `ByVal Integer` is fundamentally different from `ByRef Integer` according to the CLR.  The latter involves pushing a pointer onto the stack.  Any such type-fu would still have to dereference that pointer and push the raw value onto the stack, otherwise the callee will simply fail.

The solution to this problem is simple:  define a delegate that accepts the parameters you want as `ref` and stop trying to pound a square peg into a round hole.

**Comment by AdamSpeight2008** [comment]
Wasn't the point of `Func<T>` to reduce the number of custom delegates?

**Comment by HaloFour** [comment]
To reduce the number of custom delegates in most cases.  Most methods don't need `ref` parameters.  If you need something special-purpose, such as this, that's why you're free to define your own delegate types at will, and still enjoy all of the language support such as lambdas.
