### ISSUE TITLE
Null propagation - do we need extra brackets?

### ISSUE THREAD

**Issue by dsaf** [dotnet/roslyn#8150]
Works:
```csharp
            const string someSampleText = "Some sample text";

            if ((someSampleText?.Contains("sample")).GetValueOrDefault())
            {
                // Some code...
            }
```

Doesn't work *CS1061	'bool' does not contain a definition for 'GetValueOrDefault'...*:
```csharp
            const string someSampleText = "Some sample text";

            if (someSampleText?.Contains("sample").GetValueOrDefault())
            {
                // Some code...
            }
```

Doesn't work *CS0266	Cannot implicitly convert type 'bool?' to 'bool'...*:

```csharp
            const string someSampleText = "Some sample text";

            if (someSampleText?.Contains("sample"))
            {
                // Some code...
            }
```

**Comment by dsaf** [comment]
http://stackoverflow.com/questions/25666993/c-sharp-null-propagating-operator-conditional-access-expression-if-blocks

This also works:
```csharp
            const string someSampleText = "Some sample text";

            if (someSampleText?.Contains("sample") == true)
            {
                // Some code...
            }
```

**Comment by dsaf** [comment]
It feels justified but counterintuitive.

**Comment by HaloFour** [comment]
It's necessary because you need to close the null-propagating expression in order to be able to evaluate it.  Without those parenthesis the compiler treats the call to `GetValueOrDefault()` as a part of the null-propagating expression, where the target is `bool`, not `bool?`, and if `someSampleText` is `null` it will skip the call to `GetValueOrDefault()`.

Note that the following does also work:

```cs
if (someSampleText?.Contains("sample") ?? false)
{
    // Some code
}
```
