### ISSUE TITLE
Inconsistent behaviour regarding nameof(instanceProperty.Property) from static method

### ISSUE THREAD

**Issue by yaakov-h** [dotnet/roslyn#8220]
Given the following sample:

```C#
using System;

namespace RoslynPropertyNameof
{
	class Program
	{
		Foo foo;

		static void Main(string[] args)
		{
			Console.WriteLine(nameof(foo.Bar));
		}
	}

	class Foo
	{
		public object Bar { get; set; }
	}
}
```

This fails to compile with the following error:

> error CS0120: An object reference is required for the non-static field, method, or property 'Program.foo'

However, Intellisense will happily suggest `Bar` and other options, after typing `nameof(foo.`.

If `foo` is static, this compiles and prints `"Bar"`.

I'd suggest one of the following changes are made:

1. Allow nameof(...) on an instance field/property from a static method
2. Remove the suggestions from Intellisense, as `nameof(foo.Anything)` is invalid from a static method.

**Comment by leppie** [comment]
Calling on an instance seems counter-intuitive. `nameof(Foo.Bar)` is better, and the correct way.

**Comment by yaakov-h** [comment]
I agree, but Intenseness appears to support calling it on an instance, which makes this confusing. I didn't even know that you could `nameof(thingInScope.Property)`.

**Comment by davkean** [comment]
I believe this is by design - but I'll let @Pilchie correct me. 

IntelliSense specifically handles these cases, to avoid getting in your way. For example, as you are writing that line, you might be planning ahead to make `Main` an instance method, or `foo` a static field, which will make code valid.

**Comment by Pilchie** [comment]
As @davkean says, in the IDE we generally have a principle that we prefer to show more rather than less.  This allows you to type things as you're thinking of them, even if it isn't in the exact right order, rather than having to back up and correct something somewhere else before IntelliSense will let you proceed.
