### ISSUE TITLE
IntelliSense in typeof doesn't add angle brackets

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#8318]
`typeof(Fun<Ctrl+Space>)`

Expected: 
`typeof(Func<>)`
Actual: 
`typeof(Func)`

As long as all overloads of the type have generic parameters, IntelliSense should add the arrows when I commit. 
If there is a non-generic overload, committing after selecting the completion for the generic overload should add arrows. 
If the generic overloads all have multiple parameters, it should also add the minimum number of commas.

**Comment by rchande** [comment]
FYI @slaks

**Comment by SLaks** [comment]
On further thought, I'm not sure if adding commas (from my last point) is wise, since that would make the normal typing experience weird.

**Comment by dmytrolypai** [comment]
Hi! I am trying to implement this and there are a couple of questions I would like to ask.
1. Should it autocomplete arrows only inside typeof? It probably could be useful outside as well, but then it might be inconsistent with other completions, like method calls (see second question).
2. Maybe it should insert only one arrow? This probably would make for a better typing experience, since one would not need to go back one character to fill in the type inside arrows (if any). On the other hand, this would be inconsistent with method calls' autocompletion, since that does not insert an opening paren, but rather relies on brace completion to insert the closing one after the opening one has been typed, leaving a caret position in the nice place inside the parentheses. Considering this behaviour, maybe arrows should not be added at all then?

Thank you!

P.S. I am not sure, maybe this discussion is better suited for a corresponding pull request?

**Comment by rchande** [comment]
Hi @dmytrolypai! 

Let's start by only changing the behavior in typeof.
This may be tricky to implement. Ideally, the second brace would be tracked by brace completion so that committing the list and then typing backspace would remove both arrow.
Furthermore, if we always insert the braces, we need to have the caret move between them (otherwise typing the type parameters will be really awkward). 

Thoughts @Pilchie @DustinCampbell ?

**Comment by SLaks** [comment]
I think this should apply both in and out of `typeof`.

Method names don't insert parentheses (partly) because method groups can also be used without parentheses.
However, a generic typename can never be used without arrows (except in `nameof`), so I think they should always be inserted.

And, yes; you should only insert the closing arrow if it works with brace completion.

**Comment by dmytrolypai** [comment]
From what I've seen so far: it should be easier to implement this for everything, rather than for just `typeof`. There is only `AbstractSyntaxContext` nearby, which does not have the stuff about `typeof`. I guess, it should be common for both C# and VB and the latter does not have `typeof`?
Just inserting one arrow should not be hard to do, I think it is just pushing down things from http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp.Features/Completion/CompletionProviders/SymbolCompletionProvider.cs,77 to http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp.Features/Completion/CompletionProviders/SymbolCompletionProvider.ItemRules.cs,49 plus some logic to fix the display text. I don't think brace completion triggers in this case (if implemented like in the previous sentence), though, and I don't know why.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback and no movement in 8 years.
