### ISSUE TITLE
Conflicts resolved during rename should be formatted if appropriate.

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#8334]
Ported from internal bug 100093 (/cc: @brettfo)

1.  Paste into a C# editor:

  ```C#
    static class E
    {
        public static C Bar(this C x, int i) { return x; }
    }
    class C
    {
        int Foo(int i)
        {
            return this.Bar(1).Foo(2);
        }
    }
  ```
2.  Rename 'Bar' to 'Foo'
 
RESULT:
`return E.Foo(this,1).Foo(2);`
There is no space before the 1.
 
EXPECTED:
`return E.Foo(this, 1).Foo(2);`
There should be a space before the 1.

**Comment by bmay2** [comment]
I'm trying to narrow down where the fix for this should go. It looks like the new "this" argument and comma are injected without leading/trailing trivia into Foo() in CSharpSimplificationService.RewriteExtensionMethodInvocation() . Do you think it makes sense to add trivia there or wait until somewhere later in RenamedSpansTracker.SimplifyAsync() to format the whole Solution?

**Comment by brettfo** [comment]
You should be able to add elastic trivia to both the `this` keyword and the comma, then the formatter will take care of it.  I think the syntax is something like

``` C#
syntaxNode.WithLeadingTrivia(SyntaxFactory.ElasticMarker)
    .WithTrailingTrivia(SyntaxFactory.ElasticMarker)
    .WithAnnotation(Formatter.Annotation);
```

**Comment by bmay2** [comment]
It looks like just adding the formatter annotation is sufficient.
