### ISSUE TITLE
CSharpParseOptions has no public constructor that takes feature flags

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#8354]
You have to call a constructor and then call .WithFeatures() as opposed to passing stuff in a constructor. This seems wasteful to recreate multiple instances.

**Comment by jaredpar** [comment]
This is a conversation I've been thinking about having with the compiler team.  I'd almost prefer we had only empty constructors and forced all usages to be built up with `With` calls.  The reason being that maintaining the current constructor with 30 or so parameters and default values is nothing short of a nightmare.

**Comment by gafter** [comment]
It is too late to have only empty constructors, though we could soft-deprecate (obsolete with a warning) the long form of creation and only add `.With` methods going forward. However, I don't think there is enough independent value in obsoleting the existing forms to annoy our users with that warning.

@AnthonyDGreen @jaredpar @mattwar I hereby propose that we stop adding new public overloads of the constructor for `CSharpParseOptions` (and similarly for VB) going forward, and document our policy to only add `.With` methods rather than constructor overloads in the future. If you both accept, I'll add the documentation and close this issue.

**Comment by mattwar** [comment]
@gafter yes, let's just add With methods going forward instead of making additional public constructor overloads.

**Comment by jaredpar** [comment]
I agree.

**Comment by jasonmalinowski** [comment]
As original filer of the bug I have no concerns either.
