### ISSUE TITLE
Duplicate generated code detectors are inconsistent

### ISSUE THREAD

**Issue by SLaks** [dotnet/roslyn#8451]
http://source.roslyn.io/#Microsoft.CodeAnalysis/DiagnosticAnalyzer/AnalyzerDriver.GeneratedCodeUtilities.cs
http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/GeneratedCodeRecognition/GeneratedCodeRecognitionServiceFactory.cs

The compiler also looks at comments & attributes, whereas the IDE does not.

**Comment by srivatsn** [comment]
Can we get the IDE to just use the compiler's heuristics?

**Comment by SLaks** [comment]
The compiler's implementation is below the MEF level, so it wouldn't be injectible.
If you're OK with losing that (or if you wrap the compiler's code in a MEF LanguageService), you could easily make the compiler's code a `public static class`.

**Comment by mavasani** [comment]
This belongs to the IDE area path - Generated Code Recognition service might consider using links files to share the heuristic with AnalyzerDriver generated code utilities.

**Comment by CyrusNajmabadi** [comment]
I started going down this path a while ago.  However, it turned out to be pretty complex. The problem is that the IDE would need to go to the source/tree to make some of the determinations that the compiler does.  This means that we need to make things async (as we have a Document, not a Tree/SourceText).  This async escapes out virally, hitting a *ton* of callers.

**Comment by CyrusNajmabadi** [comment]
PR for this is here: https://github.com/dotnet/roslyn/pull/15118

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/15118
