### ISSUE TITLE
Proposal: Access to container

### ISSUE THREAD

**Issue by vbcodec** [dotnet/roslyn#8462]
Any object is aware of his members, but not containers. By container I mean object that store some object as field. This may be useful, to simplify access to containers, without creating 'wrapping and abstracting' infrastructure in classical approach.

Some example:

```
Public Class ContainerClass
    Public ContInt As Integer = 0
    Dim RefSubObj As SomeClass
End Class

Public Class SomeClass
    Public Sub FS()
        CType(Container(0), ContainerClass).ContInt += 1
    End Sub
End Class
```

Even better is to specify possible containers explicitly, to simplify access and limit possible containers:

```
Public Class SomeClass
    Container ContainerClass        

    Public Sub FS()
        Container(0).ContInt += 1
    End Sub
End Class
```

**Comment by HaloFour** [comment]
Are you effectively stating that it's impossible to declare an instance of `SomeClass` that isn't a field of `ContainerClass`?  What about as a local variable?  Establishing a circular dependency in that fashion seems pretty brittle.  What is an actual use case for using something like this?

**Comment by vbcodec** [comment]
@HaloFour 
You may create SomeClass objects, and assign them to local variables, global variables and shared variables inside shared classes. All these assignment won't add container to the list, because there is not object behind them. Container will be added only if object is assigned to field within container and  only if types are matched - container must be type (or derived type) specified inside contained class.
There is not problem with creating circular dependency:

    Public Class SomeClass
        Container ContainerClass        

        Public SubObj As SomeClass
    End Class

    ...
    Dim o1 As New SomeClass
    Dim o2 As New SomeClass
    o1.SubOnj = o2 ' o2 container(0) is o1
    o2.SubObj = o1 ' o1 container(0) is o2
    ...
As for use cases, this is helpful to enable access to ambient data. For example, each logged user have set of data, there are executing procedures, creating objects of some classes, and some of these classes need access to user's data. For now, these ambient (user) data must be propagated via constructors through all participating objects, which is overkill. Better way is to use thread identity to reach these ambient data, but there are limitations and uncertainties. With access to containers, is is easy to create chain that enables to 'look back' and reach ambient data.

**Comment by gafter** [comment]
We are now taking language feature discussion in other repositories:
- https://github.com/dotnet/csharplang for C# specific issues
- https://github.com/dotnet/vblang for VB-specific features
- https://github.com/dotnet/csharplang for features that affect both languages

Features that are under active design or development, or which are "championed" by someone on the language design team, have already been moved either as issues or as checked-in design documents. For example, the proposal in this repo "Proposal: Partial interface implementation a.k.a. Traits" (issue 16139 and a few other issues that request the same thing) are now tracked by the language team at issue 52 in https://github.com/dotnet/csharplang/issues, and there is a draft spec at https://github.com/dotnet/csharplang/blob/master/proposals/default-interface-methods.md and further discussion at issue 288 in https://github.com/dotnet/csharplang/issues. Prototyping of the compiler portion of language features is still tracked here; see, for example, https://github.com/dotnet/roslyn/tree/features/DefaultInterfaceImplementation and issue 17952.

In order to facilitate that transition, we have started closing language design discussions from [the roslyn repo](https://github.com/dotnet/roslyn) with a note briefly explaining why. When we are aware of an existing discussion for the feature already in the new repo, we are adding a link to that. But we're not adding new issues to the new repos for existing discussions in this repo that the language design team does not currently envision taking on. Our intent is to eventually close the language design issues in the Roslyn repo and encourage discussion in one of the new repos instead.

Our intent is not to shut down discussion on language design - you can still continue discussion on the closed issues if you want - but rather we would like to encourage people to move discussion to where we are more likely to be paying attention (the new repo), or to abandon discussions that are no longer of interest to you.

If you happen to notice that one of the closed issues has a relevant issue in the new repo, and we have not added a link to the new issue, we would appreciate you providing a link from the old to the new discussion. That way people who are still interested in the discussion can start paying attention to the new issue.

Also, we'd welcome any ideas you might have on how we could better manage the transition. Comments and discussion about closing and/or moving issues should be directed to https://github.com/dotnet/roslyn/issues/18002. Comments and discussion about this issue can take place here or on an issue in the relevant repo.

-----------------

I am not moving this particular issue because I don't have confidence that the LDM would likely consider doing this.
