### ISSUE TITLE
Proposal: Singleton Class

### ISSUE THREAD

**Issue by reghrafa** [dotnet/roslyn#8522]
Using Singletons is a relatively common approach.
However using Singletons in code is not very charming, since we always have to access he required function/ property via the singletons Instance/Context/ whatever:
Singleton definition:

```
public class SchroedingersCat
    {
        private static SchroedingersCat _instance;
        public static SchroedingersCat Instance  => _instance ?? (_instance = new SchroedingersCat());

        public bool? IsAlive => return /*{...}*/;

        /*
         * Implementations
         * */
    }
```

Access member:
`SchroedingersCat.Instance.IsAlive;`

However it would be interesting to get rid of the "Instance" Implementation in the class itself and provide a way to directly access the class members (like object in Scala) by introducing the `singleton`keyword.
The class would behave like a singleton class but would be accessible like a "static class with constructor":

New Class implementation:

```
public singleton class SchroedingersCat
    {
        public bool? IsAlive => return /*{...}*/;
        /*
         * Implementations
         * */
    }
```

Access members:
`SchroedingersCat.IsAlive;`

Benefits:
- Saving some precious lines of code
- Makes singleton-heavy code more readable 
- Would work perfectly with `using static`

**Comment by DavidArno** [comment]
Singletons are at least a code smell, if not an outright anti-pattern. They are after all glorified global variables that put huge hurdles in the way of anyone trying to create automated tests of the code.

We should be seeking to discourage their use, rather than make them easier to write. Therefore any change to the language to directly support them would send completely the wrong message about where the language is heading and would be a big step backward in my view.

**Comment by p-e-timoshenko** [comment]
But this idea has something interesting.
```C#
    static class Utils
    {
        public static void Tool1() { }
        public void Tool2() { } // Error: Cannot declare instance members in a static class
    }
```
The "static" operators are writtten too much. A static class is already the singleton. Therefore, it may be worth to write without 'static' keyword in members:
```C#
    static class Utils
    {
        public void Tool1() { }
        public void Tool2() { }
    }
```

**Comment by DavidArno** [comment]
@p-e-timoshenko,

A static class is only a singleton if it has state. Leaving that aside, your suggestion of not needing to repeat the static keyword has merit. It would have to be changed from mandatory to optional, rather than it being an error to use it, as it would be a breaking change otherwise.

You should create a new proposal issue to suggest that as a future change.

**Comment by Clockwork-Muse** [comment]
@reghrafa :
As a side note, your current singleton definition isn't thread-safe.  This is usually the **other** big hurdle when dealing with singletons.  It's a rather non-trivial problem to solve (in a performant manner), it turns out.

**Comment by HaloFour** [comment]
@p-e-timoshenko @DavidArno 

The requirement to repeat the `static` modifier on the members of a `static` class was intentional and written into the C# specification (§ 10.1.1.3).  I believe that the intent was to have the compiler simplify and enforce the existing pattern for writing purely static classes rather than recreating VB's Modules.

Having worked on a couple of projects recently that had mixed IoC and singletons together (not using the container's scope facilities) I have to agree that encouraging manually-defined singleton classes is not a very good idea.  They encourage global state and make maintenance and testing a real pain.

**Comment by gafter** [comment]
We are now taking language feature discussion in other repositories:
- https://github.com/dotnet/csharplang for C# specific issues
- https://github.com/dotnet/vblang for VB-specific features
- https://github.com/dotnet/csharplang for features that affect both languages

Features that are under active design or development, or which are "championed" by someone on the language design team, have already been moved either as issues or as checked-in design documents. For example, the proposal in this repo "Proposal: Partial interface implementation a.k.a. Traits" (issue 16139 and a few other issues that request the same thing) are now tracked by the language team at issue 52 in https://github.com/dotnet/csharplang/issues, and there is a draft spec at https://github.com/dotnet/csharplang/blob/master/proposals/default-interface-methods.md and further discussion at issue 288 in https://github.com/dotnet/csharplang/issues. Prototyping of the compiler portion of language features is still tracked here; see, for example, https://github.com/dotnet/roslyn/tree/features/DefaultInterfaceImplementation and issue 17952.

In order to facilitate that transition, we have started closing language design discussions from [the roslyn repo](https://github.com/dotnet/roslyn) with a note briefly explaining why. When we are aware of an existing discussion for the feature already in the new repo, we are adding a link to that. But we're not adding new issues to the new repos for existing discussions in this repo that the language design team does not currently envision taking on. Our intent is to eventually close the language design issues in the Roslyn repo and encourage discussion in one of the new repos instead.

Our intent is not to shut down discussion on language design - you can still continue discussion on the closed issues if you want - but rather we would like to encourage people to move discussion to where we are more likely to be paying attention (the new repo), or to abandon discussions that are no longer of interest to you.

If you happen to notice that one of the closed issues has a relevant issue in the new repo, and we have not added a link to the new issue, we would appreciate you providing a link from the old to the new discussion. That way people who are still interested in the discussion can start paying attention to the new issue.

Also, we'd welcome any ideas you might have on how we could better manage the transition. Comments and discussion about closing and/or moving issues should be directed to https://github.com/dotnet/roslyn/issues/18002. Comments and discussion about this issue can take place here or on an issue in the relevant repo.

-----------------

I am not moving this particular issue because I don't have confidence that the LDM would likely consider doing this.
