### ISSUE TITLE
Diagnostic system only runs on compilations.

### ISSUE THREAD

**Issue by mkrueger** [dotnet/roslyn#853]
Inside an IDE the use case is:

+ Large project
+ Single files are opened & edited
+ Diagnostics should be shown for just that file and updated during editing.

Currently it's only possible to analyze compilations with:

```
var compilationWithAnalyzer = localCompilation.WithAnalyzers (providers, null, cancellationToken); 
compilationWithAnalyzer.GetAnalyzerDiagnosticsAsync () 

```

That works and I could filter out diagnostics which aren't in the local file. But the problem is doing that every few key strokes - for the whole project - is a bit over the top. It would be nice if I could request analyzerdiagnostics just for a single syntax tree inside the compilation or have another way of solving that use case.

**Comment by gafter** [comment]
I think we went too far removing the SemanticModel API that returns compiler diagnostics for that source file.

**Comment by mkrueger** [comment]
Not just compiler diagnostics.

Esp. the use case:
'I have a custom list of analyzers and want them to run on a single file' is very important.

**Comment by srivatsn** [comment]
@gafter - The API to return compiler diagnostics is still [there](https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/Portable/Compilation/SemanticModel.cs#L345) and hence this is not a compat issue.

@mkrueger  is asking for a way to get analyzer diagnostics for a single file. AnalyzerDriver is the type that has a way to do this but it is far too complicated with a single golden path that it doesn't make an API that we can maintain and support and so temporarily it has been made internal. We definitely want to expose an API that hosts can use to run analyzer in a more fine-grained fashion. The VS IDE itself today doesn't use the AnalyzerDriver and we want to expose APIs in the compiler so that the IDE can simply ask the compiler to run the analyzers. We have some thoughts on what the API shape would be and would like to get to it soon.

**Comment by gafter** [comment]
Ah, right, we can trigger the analyzes with this api, but there is no way to get the results of the analyzers before the compilation is done.

**Comment by srivatsn** [comment]
We've added an API that can give analyzer diagnostics for a single file [here](http://source.roslyn.io/#Microsoft.CodeAnalysis/DiagnosticAnalyzer/CompilationWithAnalyzers.cs,7efdf3edc21e904a)
