### ISSUE TITLE
Increase the number of build artifacts we save

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#8553]
We only save 25 builds worth of artifacts - we should increase that once we stop saving binaries: in https://github.com/dotnet/roslyn/issues/8550.

**Comment by davkean** [comment]
Talk to @mmitche to see what the maximum amount we should increase this to.

**Comment by mmitche** [comment]
@davkean sounds good.  I'd actually like to limit it by number of days.  Right now we save 14 days of artifacts and 30 days of builds standard.  The code that runs through at the end of the job and does the pruning is actually pretty expensive so limiting it by date is best.

I may actually lower the standard for artfiacts down to like 7 days, at least for PR tests, based on how much space we end up using (right now we are at 3.5 TB)

**Comment by davkean** [comment]
@mmitche We're reducing the size of our artifacts so that will make it better. 7 days isn't enough - lots of our flaky tests take a couple of weeks to get investigated, by which time they'll be deleted. 

PR jobs are almost always what we investigate - because there's more of them, and they are more likely to run into issues.

Where is this stored? Against who exactly would be the best place to file a bug so that we can have an option to only save failed builds? We never want artifacts on good builds.

**Comment by mmitche** [comment]
The server has a 7TB raid array on it .  Expect that there will be some reduction in other jobs' artifacts as CoreCLR/CoreFx, etc. switch to models where they don't need to save everything.

Such an option exists already (and I *think* we have the plugin installed).  It's called flexible publish, and allows conditional execution of the publish steps.  So you can say that under X result, publish this, otherwise no.  We do need the support in the Utilities functionality.  That would be the best place to add this, then replace the artifacting functionality in the roslyn repo with the Utility calls.

**Comment by davkean** [comment]
Okay, so reducing the amount of data we save and only saving them for failed builds - should mean that we can increase this a lot (at least for Roslyn). 

Write now, I want to have to avoid caching the logs myself when I file a bug - as that defeats the purpose of the artifacts in the first place.

**Comment by davkean** [comment]
@CyrusNajmabadi Can you pick this up?

**Comment by dpoeschl** [comment]
@CyrusNajmabadi @otawfik-ms @tmat Was any progress made on this?

/cc: @davkean @jasonmalinowski

**Comment by davkean** [comment]
no progress made.
