### ISSUE TITLE
[Add Using] Only project suggested even if assembly matches

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#8563]
- Create three projects
    - Create class library `ClassLibrary1` that contains type `Test`
    - Create class library `ClassLibrary2` references type `Test` as an assembly reference
    - Create class library `ClassLibrary3` that does not reference either the project or the binary but has the following code
```CSharp
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ClassLibrary3
{
    public class Class3
    {
        static void Main(string[] args)
        {
            var t = new Test();
        }
    }
}
```

Add using for `new Test()` in `ClassLibrary3`

**Expected**: Both project and metadata references are offered as fixes

**Actual**: Only the addition of a project reference is suggested

**Comment by jmarolf** [comment]
@CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
Currently "by design".  We unilaterally think that your source is more likely what you wanted to reference in cases where you happen to have a name that matches a name in metadata.  

It's also an attempt to be slightly better for perf.  i.e. if you have a name that matches a source name, we can show the code fix faster as we don't have to search metadata.

**Comment by DustinCampbell** [comment]
Triage agrees. We think this is a better experience.
