### ISSUE TITLE
[Add Using] Add project reference is not offered if project is renamed

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#8565]
- Create three projects
    - Create class library `ClassLibrary1` that contains type Test
    - Create class library `ClassLibrary2` that does not reference `ClassLibrary1` but contains the following code:
```CSharp
namespace ClassLibrary2
{
    public class Class2
    {
        static void Main(string[] args)
        {
            var t = new Test();
        }
    }
}
```
- Rename `ClassLibrary1` to `ClassLibrary0`

**Expected**: Reference to class `ClassLibrary0` is offered

**Actual**:  `ClassLibrary0` is not offered until solution is closed and re-opened Or until an edit happens within "ClassLibrary0" is made

![image](https://cloud.githubusercontent.com/assets/9797472/12962168/202a3e58-cff9-11e5-8268-6677c04bd889.png)

**Comment by jmarolf** [comment]
@CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
Or until an edit happens within "ClassLibrary0" is made.

**Comment by DustinCampbell** [comment]
Cache invalidation is hard.

**Comment by CyrusNajmabadi** [comment]
@heejaechang Currently the solution crawler infrastructure does not recrawl a project when it's name changes.  It may need to as analyzers/fixers may be dependent on a project name and may need to rerun.  Would this make sense to add to the WorkCoordinator?

**Comment by heejaechang** [comment]
@CyrusNajmabadi if projectId has changed, it should have run. but the fact it didn't, I believe projectId hasn't changed. in that case, there are certain set of property we check off project.

http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/SolutionCrawler/WorkCoordinator.cs,506

you can add one you need there. but remember it will affect all analyzers.

**Comment by CyrusNajmabadi** [comment]
Great.  I'll add a project name check there.  I think this is rare enough that it's ok that it will affect all analyzers.

**Comment by heejaechang** [comment]
@CyrusNajmabadi by the way, why is it depends on project name rather than assembly name?

**Comment by CyrusNajmabadi** [comment]
1. This is unrelated to assembly name.  We're not actually using hte assembly name for anything.
2. The reason for this bug is that we use solution crawler to go around and analzye projects and build our cache of information about them.  Later when we are queried we ask "is the current project semantic versin the same as the semantic version we have cached?"  If not, we don't return anything.  The problem is: when the project name changes, it's semantic version changes (since it's project file is updated).  However, because we're not re-analyzed, we still have the cache from before.  And when a caller tries to retrieve information with the later project version they don't get anything back.

**Comment by CyrusNajmabadi** [comment]
A more appropriate fix might be to ask "is the projects semantic version different from before.  If so, we need to reanalyze it."

**Comment by heejaechang** [comment]
my question was, more like, can the cache use assembly name rather than project name. since we have so many people attached to different thing but similar stuff like project name and assembly name. if only changed thing is project name but no content has changed, as long as one can get the cache but, its information is still valid, isn't it?

**Comment by CyrusNajmabadi** [comment]
The cache does not use the project name *or* the assembly name.  The cache updates and caches the data when it hears from solution crawler that the project's version has changed.  The problem is that, in this case, the version has changed, but we're not told by solution crawler.

**Comment by CyrusNajmabadi** [comment]
> as long as one can get the cache then, its information is still valid, isn't it?

We have no way to tell.  We come in saying "give us the information for Project version 2" and the cache says "sorry, i only have information for V1, please try again later".

But later doesn't help because we are never asked again to update our information (unless hte user manually makes a change in that project).

**Comment by heejaechang** [comment]
I see.
