### ISSUE TITLE
EnvDTE.CodeElement GetStartPoint(EnvDTE.vsCMPart.vsCMPartBody).Line returns wrong result if declaration uses more than one line

### ISSUE THREAD

**Issue by carlos-quintero** [dotnet/roslyn#857]
See MS Connect bug report:

EnvDTE.CodeElement GetStartPoint(EnvDTE.vsCMPart.vsCMPartBody).Line returns wrong result if declaration uses more than one line
https://connect.microsoft.com/VisualStudio/feedback/details/1148659/envdte-codeelement-getstartpoint-envdte-vscmpart-vscmpartbody-line-returns-wrong-result-if-declaration-uses-more-than-one-line

I think that in past CTPs the problem also happened with a VB.NET class using the Implements or Inherits keyword on a next line but that seems fixed in CTP6.

**Comment by carlos-j-quintero** [comment]
The problem seems to be in file: CodeModel\VisualBasicCodeModelService.NodeLocator.vb

Line 307 (Function GetTypeBlockStartPoint):

                        Dim statement As StatementSyntax = typeBlock.BlockStatement
                        While statement IsNot Nothing
                            Dim [next] = statement.GetNextNonEmptyStatement()
                            If [next] IsNot Nothing AndAlso
                              ([next].Kind = SyntaxKind.InheritsStatement OrElse
                               [next].Kind = SyntaxKind.ImplementsStatement) Then
                                statement = [next]
                                Continue While
                            Else
                                Exit While
                            End If
                        End While

Line 495 (Function GetMethodBlockStartPoint)

Case EnvDTE.vsCMPart.vsCMPartBody,
   EnvDTE.vsCMPart.vsCMPartBodyWithDelimiter
 
   Dim startLine = text.Lines.GetLineFromPosition(NavigationPointHelpers.GetHeaderStartPosition(methodBlock))
   startPosition = text.Lines(startLine.LineNumber **+ 1**).Start

And maybe other code elements that can have attributes or whose declaration can be split

**Comment by Pilchie** [comment]
Per @carlos-j-quintero comments in #2461, moving out of 1.0 for risk of breaking people who have already worked around this bug.

**Comment by Pilchie** [comment]
Now moving to 1.2,

**Comment by Pilchie** [comment]
At this point, I don't think we should fix this anymore, since people have likely already worked around it.

**Comment by DustinCampbell** [comment]
seems reasonable to me
