### ISSUE TITLE
cref's IntelliSense orders types by longest arity

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#8623]
![image](https://cloud.githubusercontent.com/assets/1103906/13001914/3708d324-d11f-11e5-83ac-acacdcc80aef.png)

It seems to me, that this order should be reversed to match the sig helper and probably the more used type:

![image](https://cloud.githubusercontent.com/assets/1103906/13001925/510c6402-d11f-11e5-861a-652bcbf2c45b.png)

**Comment by DustinCampbell** [comment]
Yeah, that looks pretty silly. I'm surprised we never noticed it.

**Comment by dmytrolypai** [comment]
Hi! I would like to try to fix this.
It is pretty funny, actually, and has to do with the ordering between ">" and "," :)
The main problem is writing a test, I think, but probably that discussion is for a pull request.

**Comment by davkean** [comment]
@dmytrolypai Sure, feel free to pick it. It sounds like, from what you are saying, that we're doing an order based on the full name including generic arguments - that sounds incorrect.

**Comment by dmytrolypai** [comment]
@davkean Yes, AbstractCompletionService.cs:201 (`totalItems.Sort()`) is where it goes out of order, which boils down to `CompletionItem`'s `CompareTo`, which uses the `SortText` property. That one is set just to symbol's text by the `CrefCompletionProvider`.

It would still need to look (somehow) at all the generic arguments to decide that the ones with the smaller number of them should go first, right? My initial idea was to just let the `SortText` be the insertion text/symbol text but with spaces instead of `<>` or `{}`, since the sorting is text based anyway. This would work and I am not sure if it should be more than that?

What seems like a real struggle is testing. At first I tried to do something at the `CrefCompletionProviderTests` level, but there everything is OK and it goes wrong later.

**Comment by davkean** [comment]
@rchande Do you have some recommendations here?

**Comment by rchande** [comment]
@dmytrolypai--that sounds like the right fix. Can you elaborate on your testing problems?

**Comment by rchande** [comment]
Also, instead of depending on the sort order of the names of the type parameters, I imagine you could use the metadataname (ie "Action`1").

**Comment by davkean** [comment]
You can't rely on the metadata name; Action`2 and Action`10 would be ordered incorrectly.

**Comment by rchande** [comment]
We also can't use "whitespace and identifier character strings with type parameter names either":

`genericType ztypeparameter` would be sorted after `generictype atypeparameter btypeparameter`.

**Comment by DustinCampbell** [comment]
Note that we have pretty specific comparison logic for signatures in sig help. Can we leverage that somehow? https://github.com/dotnet/roslyn/blob/a4e375b95953e471660e9686a46893c97db70b0e/src/Workspaces/Core/Portable/Shared/Utilities/SignatureComparer.cs

**Comment by dmytrolypai** [comment]
@rchande About the testing: as I mentioned in the previous comment, I tried to do it in `CrefCompletionProviderTests`, but that turned out to be too early, since the order becomes broken later (`... ModelComputer -> AbstractCompletionService.GetCompletionListAsync -> AbstractCompletionService.MergeAndPruneCompletionLists`). I don't seem to find existing tests on those levels.

**Comment by rchande** [comment]
Ah. We test those [here](http://source.roslyn.io/#Roslyn.Services.Editor.UnitTests2/IntelliSense/CSharpCompletionCommandHandlerTests.vb,bdbfa8b430fd4d61)

**Comment by dmytrolypai** [comment]
Oh, VB, did not see that coming. I have never written a line of VB before, maybe it is time :) Thanks!

**Comment by dmytrolypai** [comment]
@rchande I certainly agree that using "whitespace and identifier character strings with type parameter names" is not entirely correct, but on the other hand, if someone has a generic type with `<A, B>` and `<B>`, well, it is probably quite OK if they come in that order. I would say that this issue is (only) annoying for types like `Action`/`Tuple` with gazillion overloads that all have a pretty regular naming convention. But that's only my opinion.

**Comment by dmytrolypai** [comment]
I created a pull request #9356 for what I had so far.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/70929.
