### ISSUE TITLE
VB XML doc inconsistency between template and IntelliSense for property (template contains <returns>, IntelliseSense not)

### ISSUE THREAD

**Issue by DzonnyDZ** [dotnet/roslyn#8627]
Related to #8546, there is inconsistency between what gets inserted when I type ''', and what IntelliSense offers for properties.
When I type ''' above property <summary>

 and <returns> gets inserted. But when I delete <returns> and want to insert it again, IntelliSense does not offer it.
![vbprop](https://cloud.githubusercontent.com/assets/2221259/13007609/d1f9d636-d191-11e5-9dba-7366a04bda80.png)

**Comment by DzonnyDZ** [comment]
BTW: This <returns> is inconsistent with C#. C# neither includes it by default,l nor offers it in IntelliSense. Which is strange, because <returns> is widely used in .NET Framework itself.

**Comment by DustinCampbell** [comment]
@DzonnyDZ, the reason for the inconsistency between C# and VB is because the inconsistency has *always* been there -- since VB got XML doc comment support back in VS 2003. We didn't want to change the defaults for C# users as we expected many people would be annoyed and delete the extra field every time.

**Comment by DustinCampbell** [comment]
The fact that "returns" is missing from IntelliSense in VB is a bug though -- thanks!

**Comment by sharwell** [comment]
❗️ `<returns>` is not typically used for a property. Properties use the `<value>` element instead of `<returns>`. The correct resolution is to correct the template for the automatically inserted text to use `<value></value>` instead of `<returns></returns>`.

See the following links for more information:

* [value (Sandcastle XML Comments Guide)](http://ewsoftware.github.io/XMLCommentsGuide/html/f512d714-e100-4296-916c-99a46e572e9d.htm)
* [SA1609 Property documentation must have value (StyleCop Analyzers documentation)](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1609.md)
* [SA1615 Element return value must be documented (StyleCop Analyzers documentation)](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1615.md)

**Comment by sharwell** [comment]
@EWSoftware would you agree with my interpretation of these elements for properties? Specifically the following two points:

1. The `<value>` element is valid for all properties (read, write, and read/write)
2. The `<value>` element is always preferred to a `<returns>` element when documenting properties
3. The `<returns>` element, even if allowed, is not considered an expected top-level element for documenting a property

**Comment by EWSoftware** [comment]
@sharwell  Yes, I agree.  The XML comments guide was put together using info from a few different sources (Microsoft's documentation for VB and C#, NDoc references, and a few whitepapers).  All were consistent in that `value` was to be used for properties and `returns` was to be used for methods.  All the API documentation on MSDN backs that up too since I don't think you'll find a property with a Return Value.  It's always Property Value and any description there is obtained from the `value` element.

I'd also add that `value`, if used, supplements the information in the summary so I don't consider it a requirement.  It's not added by default in C# and I wouldn't want that to change.

**Comment by sharwell** [comment]
@EWSoftware Thanks. My proposed change in #21475 fully aligns with your expectation.

The one thing that really surprised me was the XML documentation files alongside the framework reference assemblies. Those appear to prefer `<returns>` to `<value>`, even though the latter is what consistently appears in rendered documentation.

**Comment by KathleenDollard** [comment]
@sharwell and @DustinCampbell 

I agree in principle, but am worried about consistency, so stating my assumptions:

- All existing code that had XML comments added currently have "returns" 
- Are there any templates or snippets that also insert this block

Where are <returns> and <value> used for a property (not IntelliSense, but doc generators?)

I have linked this issue in the VBLang where there are more VB folks. I would like to give that a week to percolate unless you have a deadline. Yes, I realize this is an old issue. 

I would like to also work with the community to create an analyzer that would either update all use of <returns> on properties or remove it, or change unless it's empty or identical.

**Comment by reduckted** [comment]
I don't use `<value>` or `<returns>` on properties. I find the `<summary>` tag is usually enough (and adding either of the other two tags would just duplicate what is already in the summary). 

Admittedly I don't usually compile the documentation using Sandcastle or any other tools like that, so I may not be seeing the problems with leaving those tags out. I just see what Visual Studio's intellisense shows me, which is just the summary and nothing else:

```vb
Public Structure Foo
    ''' <summary>
    ''' This is the summary.
    ''' </summary>
    ''' <value>This is the value.</value>
    ''' <returns>This is the returns.</returns>
    Public Property Beep As Integer
End Structure
```

![image](https://user-images.githubusercontent.com/10321525/35178506-991a8b72-fdd5-11e7-94b3-cb2049296449.png)

On a side note, I remember when Visual Studio used to allow you to [customize what was added in those templates and what was available in intellisense](https://blogs.msdn.microsoft.com/lisa/2010/05/24/how-to-customize-the-xml-comments-that-are-inserted-by-the-visual-basic-code-editor/). That feature was removed in VS 2015 I think. 😢

**Comment by KathleenDollard** [comment]
You had a tear for losing the XML customization? Did you use that? 

Since returns is wrong, I agree with Sam about removing it. I'm not sure whether we should replace it with <value> or just remove it.

**Comment by reduckted** [comment]
I used to use it, yes. Primarily it was to get rid of the `<remarks>` tags that were added by default, though they don't seem to be added by default anymore, so I wouldn't need it for that. 

Removing the `<returns>` (or `<value>`) tags from properties is something that I _might_ consider using it for if it were still available today. Having said that, I currently use a custom code formatter that removes empty XML document tags when I save a file, so using it to modify the default tags that are added is not something I'd worry about. _But_ being able to add custom elements to the intellisense list (like `<overloads>`) _could_ be useful. I guess it depends on what the documentation compilers actually do with those custom tags though.

All in all, while I was disappointed that it was removed, it's not something that I desperately want back.

For what it's worth, other's have noticed that it was removed as well:
* https://stackoverflow.com/q/32287626/4397397
* https://blogs.msdn.microsoft.com/lisa/2010/05/24/how-to-customize-the-xml-comments-that-are-inserted-by-the-visual-basic-code-editor/#comment-1713

**Comment by sharwell** [comment]
@KathleenDollard @DustinCampbell I found existing two cases where `<returns>` documentation was displayed in Visual Studio but `<value>` was ignored. Pull request #36491 updates these two cases to also support `<value>`.

In future features, e.g. #31618, both of these elements will be handled.

**Comment by KathleenDollard** [comment]
Great!

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback/movement here.

**Comment by SetTrend** [comment]
Referring to this thread and [XML Documentation doesn't provide for adding return values to properties](https://developercommunity.visualstudio.com/t/XML-Documentation-doesnt-provide-for-ad/10814168), wouldn't it make sense to rephrase the generated `Returns:` header displayed for a property's `value` when generating meta data information, to `Value:` ?

This would help avoiding confusion in the first place.

**Comment by paul1956** [comment]
@SetTrend I just finished going through the WinForms repo and manually changing all the returns to value.

**Comment by SetTrend** [comment]
Wonderful! That gonna be my this year's charming Christmas present.
