### ISSUE TITLE
Local functions: do not show up in Navigate To results

### ISSUE THREAD

**Issue by balajikris** [dotnet/roslyn#8650]
Searching for `Local` in NavigateTo does not show any results. It should now look for local functions, like how it looks for nested classes.

```C#
class Class1
{
    public int Main()
    {
        int Local()
        {
            return 1;
        }

        return Local();
    }
}
```

**Comment by DustinCampbell** [comment]
Triage thinks this would be challenging to implement (since local functions aren't in the decl table) and it also opens up a can of worms. For example, if we should local functions in navigate to, should we show other local declarations, such as variables? I think we're OK not doing this unless people start requesting it once local functions are out there.
