### ISSUE TITLE
[NuGet Add Using] You are not offered to add a (binary/NuGet) reference after you remove it

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#8688]
Repro 1:

1) Create 2 console applications
2) Add a reference to System.Speech to one of them
3) In the other one write the following:

``` C#
    class Program
    {
        static void Main(string[] args)
        {
            DictationGrammar
        }
    }
```

4) Resolve and accept a reference
![image](https://cloud.githubusercontent.com/assets/1103906/13031622/00ec2f3c-d289-11e5-92af-7ec4c2a95f5f.png)
5) Immediately delete the added reference
6) Right-click and attempt to resolve again 

__Expected:__ To be offered the same as above
__Actual:__
![image](https://cloud.githubusercontent.com/assets/1103906/13031624/18a94862-d289-11e5-84a4-d61ea32d8540.png)

Repro 2:

1)
 ``` C#
    class Program
    {
        static void Main(string[] args)
        {
            JToken
        }
    }
```
2) Resolve and install JSON.NET
3) Immediately delete the reference
4) Attempt to resolve,

__Expected:__ to be offered the same as above
__Actual:__ 
![image](https://cloud.githubusercontent.com/assets/1103906/13031651/cb94d414-d289-11e5-9a25-ad653d34a69a.png)

**Comment by davkean** [comment]
tag @CyrusNajmabadi

**Comment by davkean** [comment]
Wonder if this is just another repro of: https://github.com/dotnet/roslyn/issues/8688.

**Comment by CyrusNajmabadi** [comment]
The issue here is that the presence of the "using directive" is making us ignore this fix.  Will address shortly.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/commit/4a60068790263cc83ca3af3396c3438099964ec6

**Comment by michaelcfanning** [comment]
I did not observe that this issue is fixed using the VSIX you provided offline. You stated you'd refreshed this version with latest, right?

**Comment by CyrusNajmabadi** [comment]
When i refreshed, i may not have fixed this bug yet.

**Comment by CyrusNajmabadi** [comment]
I've retried and this appears fixed to me.

**Comment by michaelcfanning** [comment]
This still repros if the user deletes the package reference via the project 'References' node but leaves the reference in packages.config.

**Comment by CyrusNajmabadi** [comment]
There are two different cases.  The first is with regular references and the second is with nuget packages.  With regular references everything seems to work properly.  

In the case of nuget references, i have no idea what should be the general policy for people who leave their project in such a state.  From Nuget's perspective, the package is still installed (because it is in packages.config).  Furthermore, as Nuget is responsible for all reference management for htese packages, there's nothing we can do.  It's not like Roslyn knows what binaries are in a nuget package.  So there's not really anything we can do here.

Ideally, what should happen is that either:
1. you can't actually manually delete references that come from nuget packages.
2. if you were allowed to delete references that came from nuget packages, then nuget would consider the package no longer installed.

**Comment by davkean** [comment]
Ah, so you are querying NuGet for the state of the package? Fair enough. In project.json world, you can't remove the assembly - it doesn't show up in the tree, only the package.

**Comment by CyrusNajmabadi** [comment]
Beautiful.  So we do '1'...  But only for project.json projects?  And not all other projects?  Wonderful... 

> Ah, so you are querying NuGet for the state of the package? 

Yes.

**Comment by CyrusNajmabadi** [comment]
This has been fixed to the extent of our ability on the Roslyn side.

There is still a general issue *independent* of the 'add nuget reference' smart tag.  Specifically, if you manually delete a reference from the project view, then nuget still considers the nuget package installed.
