### ISSUE TITLE
Proposal: Property implementation interface and syntax for complex logics

### ISSUE THREAD

**Issue by lachbaer** [dotnet/roslyn#8713]
## Background

During the discussion of Property-scoped fields (#850) there came the question by the assigned implementor whether to allow also property scoped classes, methods, etc. I do not think that this is a good idea with respect to the layout of code, and that it is probably better to put more complex logic, that needs additional methods and internal classes into extra classes.

But maybe it is a good idea to have a default, framework carried way to support this approach.
## Implementation

First of all we need a new abstract framework class

``` C#
    public interface IPropertyAccessors<T>
    {
        T GetValue();
        void SetValue(T value);
    }
```

then you can implement an accessor class

``` C#
    internal class MyPropertyLogic<T> : IPropertyAccessors<T>
    {
        T _backingField;
        public T GetValue()
        {  /* my very complicated getter logic */   }

        public void SetValue(T value)
        {  /* my even more complicated setter logic */   }

        // add some more very complex methods, properties, fields, nested classes, etc...
    }
```

**now comes the thrilling part** - how can you use that self-written-complicated-accessor-class?

``` C#
    class A {
        public int Prop : MyPropertyLogic<int> { get; private set; }
    }
```

Let me suffocate some arguments before the discussion starts:
- Many language features already rely on framework support. `using` needs `IDisposable`, LINQ even requires a new framework version. So I see no reason, why this would be different.
- The new, divergent property declaration seems fine to me, even if I only had a rough understanding of the language: 1. it looks like a property (no `()` after the identifier, no additional keyword like `class` or `interface`); 2. it seems to have a public getter, but only a private setter; 3. seems that it inherits (it's logic) from somewhere.
- Implementation by the compiler can be done like

``` C#
    class A {
        // the compiler actually names the backing field <MyPropertyLogic>k__backingField;
        public int Prop {
            IPropertyAccessors<int> k__backing = new MyPropertyLogic<int>(); // #850 syntax
            get => k__backing.GetValue();   // #7881 syntax
            set => k__backing.SetValue(value);   // #7881 syntax
        }
    }
```

Some requirements must be met for this syntax:
- The implementing logic class must have a public parameterless constructor
- The generic interface type parameter is of the type of the property
- In cases like above, where the implementing class is generic, the coder has to take care of the correct type parameters in the inheritance part after the `:` colon.

**Comment by HaloFour** [comment]
This doesn't seem to hit the mark of the mention in #850 at all.  There the scoped helpers would be specific to the implementation of the logic of that property.  In this proposal the helper couldn't be locked or scoped to that property.

I don't see why this should be a language feature at all.  It's already quite simple to declare helper classes/methods and then use them within property accessors and doesn't require verbose syntax to accomplish.  Despite this it is not a common scenario so it does not warrant special syntax.

Using any specific interface locks the implementation and also locks the feature to a specific BCL version.  By being an interface you also require an allocation.  Even if the helper were a `struct` the compiler would still have to box that `struct` and perform a virtual dispatch since interface members can be implemented privately and with any name.  Any locked convention/interface for this property helper diminishes its utility.  For example, your pattern would make it impossible for the setter to modify the value.  The setter also cannot directly allocate the backing field making atomic operations impossible.  Nor can it work with potentially multiple backing fields.

**Comment by alrz** [comment]
This is very similar to Kotlin delegated properties. I think proper mixins are thoroughly prefered over any other feature involving delegation.

**Comment by DavidArno** [comment]
This proposal seems even worse than the one for hiding variables inside properties. If you really need `/* my very complicated getter logic */` or `/* my even more complicated setter logic */`, then use methods. Properties are intended to be a way of encapsulating a field; not a place to put complex logic.

**Comment by lachbaer** [comment]
@HaloFour 
> This doesn't seem to hit the mark of the mention in #850 at all

No, it does not. I want to propose a way that would eliminate the need to allow all kinds of declarations within the delegate body - just because the question came up once there.
> I don't see why this should be a language feature at all

It shall ease the integration of this *design pattern*, as does the `using` directive for implicitly calling `IDisposable` instances. And like `using` it shall *encourage* developers to outsource complex algorithms to classes - in case that they cannot circumvent them at all.
> The setter also cannot directly allocate the backing field making atomic operations impossible.

That's not the intent.
>Nor can it work with potentially multiple backing fields.

Yes it can, in the outsourced class. That - obviously - can be as complex as anyone like it to be with as many backing fields. This extension shall not replace the current working of properties?!

@DavidArno 
>  Properties are intended to be a way of encapsulating a field; not a place to put complex logic.

My say! It is just a proposal for a language integrated design pattern, in case one can't resist.

Please, see the following 2 snippets, the first what can be done already today. And then tell me please, that the 2nd isn't clear what's going on behind the scenes and that it is less readable
```C#
private MyPropertyLogicClass _storage = new MyPropertyLogicClass();
public int Prop {
    get { return _storage.Get(); }
    set { _storage.Set(value); }
}
```
```C#
public int Prop : MyPropertyLogicClass { get; set; }
```
But for the latter to work, besides the syntax changes, some common interface is needed.

About the first snippet, that is current syntax:
@HaloFour I want to point out that here the programmer intentionally created a class for complex logic, that cannot be directly bound to the setter call.
@DavidArno I want to point out that here the programmer intentionally created a class for complex logic, because she couldn't resist ;-)

**Comment by HaloFour** [comment]
@lachbaer 

Probably the closest pattern to this that I can say that I've ever see in code is dependency properties, and it is quite incompatible with this design.  The fact that you can invent some code and claim that it is a pattern does not justify amending the language to support it.  If this was a pattern that was employed quite frequently *and* the existing code either made it difficult or troublesome to implement then that might justify a language pattern.  This proposal does not come close to passing either test.

**Comment by lachbaer** [comment]
I'm waiting for someone to put the 'Pedantic' label to it :-D
This discussion is a good place to suffocate the need for *cooooomplex syntax features* for properties ;-)

**Comment by DavidArno** [comment]
@lachbaer ,

> @DavidArno I want to point out that here the programmer intentionally created a class for complex logic, because she couldn't resist ;-)

And that is why I think some of these proposals are so dangerous. Remember the "pit of success" principle: changes to the language should all be geared toward ensuring we all naturally fall into the pit of success. Not doing so should be harder work. Thus:

    public int P { get; }

is good. It is quick to write and encourages immutability. Likewise, so does:

    public int P => _p;

Sadly, we have the legacy of the following pointless piece of code being easy to write:

    public int P { get; set; }

but fixing that would be a breaking change. So it has to remain. Beyond that though, if you want a setter, you should have to type more code; you should have to work hard at climbing out of the pit of success. Thus, anything like:

    public int Prop : MyPropertyLogicClass { get; set; }

or

    public int Prop 
    {
        IPropertyAccessors<int> k__backing = new MyPropertyLogic<int>();
        get => k__backing.GetValue();
        set => k__backing.SetValue(value);
    }
    
is a step in the wrong direction. You are providing a ladder to enable folk to easily escape that pit, rather than making them work at it.

**Comment by alrz** [comment]
>Sadly, we have the legacy of the following pointless piece of code being easy to write

Isn't it useful specifically for writing POCOs (considering that records are immutable by default)?

**Comment by DavidArno** [comment]
@alrz,

In my head at least, records replace POCO's, DTO's etc as those objects should be written to be immutable anyway.

**Comment by alrz** [comment]
Yeah, as long as you don't have to deal with UI which is mutable by nature. C# has to deal with it anyway, because it is meant to be used to write UI applications.

**Comment by DavidArno** [comment]
@alrz, the UI isn't a POCO...

**Comment by alrz** [comment]
I'm not talking about UI itself, I'm talking about what lies underneath e.g. VM or EF model, all mutable.

**Comment by DavidArno** [comment]
@alrz, 

The data layer is not not wired directly to the UI. There's layers in between. These all should pass around immutable data objects. Sure you have mutability at the point of I/O with a data source and with controls on a UI. Nothing else need be mutable in a well designed system.

**Comment by lachbaer** [comment]
@DavidArno (and others ;-)

I like a `T Prop { get; set; }`!

In any presentation I heard someone of MS talking about its purpose to define an API with properties, that *could* be altered with individual code later in the process.

Also accessing public fields is discouraged for the same reason. Maybe when your code evolves during the developing process (it "evelops", so to say :-) you need to cut off the direct access to the field and introduce a property with individual logic instead. That **is** API breaking! Designing your objects with auto-properties instead of fields instead is therefore much better in severe software engineering!

That's is inter alia one reason why I like to take properties one step further in the language. Because the **are** so important!

**Comment by DavidArno** [comment]
@lachbaer,

In no way am I proposing the use of public fields instead of properties. With hindsight, fields should have defaulted to `private readonly` if no modifiers were specified and we again should have to work at making them more accessible than that. We can't make that change though, so we are stuck with it being easier to use fields badly, than to use them well and with it needing less typing to make a public field than a public property.

I do not have a problem with properties; my concerns lie with mutable properties. If you need to specify anything other than `T Prop { get; }`, then you should need good reason to do so and should be prepared to write the extra code needed to make that happen. Therefore making it easier to write mutable properties is the wrong way to develop the language.

**Comment by lachbaer** [comment]
@DavidArno 
> In no way am I proposing the use of public fields instead of properties

I've never alleged that :-) It was just something to emphasize my like for even auto-properties.

> fields should have defaulted to `private readonly` if no modifiers were specified

Interesting idea, somehow! But I think that as in no other common language fields default to this behaviour it would have really been hard to tell programmers that their "variables of the class" aren't variable any more. And that making the break-trough of C# and .NET very, very hard!!!

> my concerns lie with mutable properties

Maybe you are probably a very advanced programmer who is writing a lot of enterprise software. Maybe even with Java EE. Then I could understand your concerns from what I have heard about it. Well, I am not, I'm just a "regular" small business software devoper. And I can tell you that mutable objects are lying around my desktop everywhere in a *vast* majority :-) And I don't see any problems with them. Actually I really, really like them ;-)

**Comment by Licshee** [comment]
I have a sense that an improved version of this proposal can be useful for implementing DependencyProperty, and therefore make XAML developers' life easier.

Since C# (also VB.NET) is general-purposed language, it is not acceptable to add features directly support XAML, thus developers always have to write the necessary code unless using tools to generate code automatically.

then how about something this:

    public DependencyProperty MakeDependencyProperty(
      [CallerName]string name,
      [CallerDataType]Type propertyType, // new attribute need to implement
      [CallerOwnerType]Type ownerType    // ditto
    ) => DependencyProperty.Register(name, propertyType, ownerType);
    /* ... */
    public int Count {
      MakeDependencyProperty();
      get; 
      private set; 
    }

**Comment by HaloFour** [comment]
@Licshee There's so much more of the DependencyProperty pattern that such syntax would miss.  At the very least you'd need the public static field (IIRC required for XAML to work) and the property accessor methods needs to call base classes of `DependencyObject` with that field in order to read the value and there are a variety of other properties of a DependencyProperty.  Trying to come up with C# syntax to try to simplify that in a general-purpose way would likely be very messy.  I honestly think it's a better candidate for meta-programming, allowing a tool to automatically generate the code to implement a feature or pattern based on attributes or similar.  #5292 #5561

**Comment by Licshee** [comment]
Calling to getter & setter methods is what @lachbaer asked for, public static field is what I missed, but I just checked #850 and believe it can work in a way, just my example was wrong, I need to perfect it.

During the perfection I find my idea is now more of #850, then I'm going discuss this under #850.
Thank you for your opinion.

**Comment by lachbaer** [comment]
After some time of thought I think that this proposal is of no need. Indeed properties should only be lightweight in the first place. Everything that gets more complicated should stay verbose and implemented manually, so that other readers can comprehend what is going on.

I nevertheless leave this topic open in case anyone else wants put hut his two cents to it ;-)

**Comment by gafter** [comment]
We are now taking language feature discussion on https://github.com/dotnet/csharplang for C# specific issues, https://github.com/dotnet/vblang for VB-specific features, and https://github.com/dotnet/csharplang for features that affect both languages.
