### ISSUE TITLE
BasicExpressionEvaluator Integration Test Failing

### ISSUE THREAD

**Issue by tannergooding** [dotnet/roslyn#8724]
The BasicExpressionEvaluator Integration Test is failing after the switch to Update 1.

error BC35000: Requested operation is not available because the runtime library function 'Microsoft.VisualBasic.CompilerServices.Operators.AddObject' is not defined.

This only impacts scenario 5.

**Comment by ManishJayaswal** [comment]
@tannergooding is this still an issue?

**Comment by tannergooding** [comment]
@ManishJayaswal, I believe so.

**Comment by ManishJayaswal** [comment]
@tannergooding Ok, I will leave it on your plate then.

**Comment by tannergooding** [comment]
Assigning this to @jinujoseph for retriage

**Comment by ivanbasov** [comment]
Attempted to migrate the test to xUnit. Still see the same issue. That is, I can reproduce it locally without any frameworks. It is not caused by Tao. It seems to be a regression in VB compiler services.

Here is a repro scenario:
1. Create a VB console application with the code.
```VisualBasic
Module Module1
    Sub Main()
        'Dim x = (Function(val) (val + val))(1)
        System.Diagnostics.Debugger.Break()
    End Sub
End Module
```
2. Start debugging up to the breakpoint.
3. Type `?(Function(val) (val + val))(1)` in the immediate window.
**Expected**
`2`
**Actual**
`error BC35000: Requested operation is not available because the runtime library function 'Microsoft.VisualBasic.CompilerServices.Operators.AddObject' is not defined.`
4. Also Microsoft.VisualBasic.dll is not loaded in Debug -> Modules.
5. Uncomment the line in the code and run it again.
6. `?(Function(val) (val + val))(1)`  will work in the immediate window. 
7. Microsoft.VisualBasic.dll will be loaded in Debug -> Modules.

@cston, could you please help with this?

**Comment by cston** [comment]
Is `Microsoft.VisualBasic.dll` referenced by the compiled exe? If there are no references to that assembly in the exe, the assembly may not be available at debug time.

**Comment by ivanbasov** [comment]
One can get the following message
> A reference to 'Microsoft.VisualBasic' could not be added. This component is already automatically referenced by the build system.

Trying to add a reference to it.
