### ISSUE TITLE
RenameSymbolAsync cannot rename all occurences of a base class

### ISSUE THREAD

**Issue by javagg** [dotnet/roslyn#8727]
namespace MyNs
{
     public class Message {} // only in this line, the symbol Message has changes
     public class Command : Message {} // In this line, Message has not changed!
}

when I use RenameSymbolAsync rename Message to Message_, not all the occurences was renamed.
Does RenameSymbolAsync can be used to accomplish such task?

**Comment by dpoeschl** [comment]
@javagg I wasn't able to reproduce this locally. The "Rename Tracking" feature calls the public RenameSymbolAsync method and produces the expected result in this case (try starting with the code you posted in Visual Studio, add the `_` to the end of `Message`, and then use Ctrl+\<dot\> to see the `Rename 'Message' to 'Message_'` rename option, with [source code here](http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures/Implementation/RenameTracking/RenameTrackingTaggerProvider.RenameTrackingCommitter.cs,93)):

![image](https://cloud.githubusercontent.com/assets/235241/13209834/a5a31108-d8dd-11e5-9fa3-8a109f899ec0.png)

Can you post a more complete example of your usage of `RenameSymbolAsync` API so that I can reproduce the problem here? Thanks!

**Comment by dpoeschl** [comment]
Closing for now. Feel free to ping me with more detailed steps to reproduce. Thanks!
