### ISSUE TITLE
see cref xml doc validation fails for IDictionary{object, object}

### ISSUE THREAD

**Issue by ajaybhargavb** [dotnet/roslyn#8750]
Repro:
compilationOptions in project.json
```json
"compilationOptions": {
    "emitEntryPoint": true,
    "warningsAsErrors": true,
    "xmlDoc": true
},
```

Method:
```C#
/// <see cref="IDictionary{object, object}" />
public static void Main(string[] args)
{
    Console.WriteLine("Hello World!");
}
```

When I run I get:
error CS1584: XML comment has syntactically incorrect cref attribute 'IDictionary{object, object}'
error CS1658: Type parameter declaration must be an identifier not a type. See also error CS0081.
error CS1658: Type parameter declaration must be an identifier not a type. See also error CS0081.

When I change `IDictionary{object, object}` to `IDictionary{Object, Object}` it compiles successfully.

**Comment by ajaybhargavb** [comment]
This could be a different bug. Both of the below types doesn't work.
1. `<see cref="IEnumerable{KeyValuePair{string, object}}"/>`
2. `<see cref="IEnumerable{KeyValuePair{String, Object}}"/>`

**Comment by Pilchie** [comment]
This is by design.  The compiler doesn't allow you to refer to specific constructions in `cref` tags.  You can only introduce a new type parameter name.  So, `IDictionary{String, Object} works because it's creating new type variables types named `String` and `Object`.  It is NOT, referring to `System.String` and `System.Object`.

`IEnumerable{KeyValuePair{String, Object}}` doesn't work because `KeyValuePair{String, Object}` isn't a valid name for a type variable.

**Comment by ajaybhargavb** [comment]
Got it. Thanks
