### ISSUE TITLE
IOperation: There is no way to expose receiver for static members via IMemberReferenceExpression 

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#8895]
```
        /// <summary>
        /// Instance of the type. Null if the reference is to a static/shared member.
        /// </summary>
        IOperation Instance { get; }
```

If receiver for a static member is a value (an error in C#, a warning in VB, but it is not evaluated), I think it should be exposed. SemanticModel answers questions within receivers like this.

There is the same issue is for IInvocationExpression.Instance

**Comment by jinujoseph** [comment]
**Design Decision Meeting** 

We should do it.  
We will likely need to mark this as 'optional' for scenarios that can't provide this information (for example, IL in the future).
In order to be able to represent something like "Static1.Static2.M" we may end up needing some sort of TypeReferenceOperation so taht we can talk about 'Static1' and fit it into the IOperation system.

We'll likely want to also rename 'Instance' to 'Receiver'.

**Comment by jinujoseph** [comment]
Verify and close (VB scenario)

**Comment by AlekseyTs** [comment]
Looks fixed in https://github.com/dotnet/roslyn/pull/22972
