### ISSUE TITLE
Code Style: Enable one-click cleanup

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#8928]
The first thing customers are going to ask for is a "one-click" experience for cleaning up code style in a file/project/solution. 

Note: we should not remove ifdef'd usings

**Comment by smmalis37** [comment]
One addition that would also be really nice is something similar to Resharper's Inspect -> Code Issues In Solution/Project view that shows you all the style issues that could be cleaned up. Personally I like to go through them myself since there are some places where I might be violating a style rule deliberately, but others where I want the rule to apply.

**Comment by jinujoseph** [comment]
This is completed in 16.1
