### ISSUE TITLE
Build infrastructure for compiling training data for DSR.PortablePDB

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#8969]

**Comment by davkean** [comment]
This is assigned to infrastructure, but there not enough information on this for me schedule or put on the backlog. Are you planning on doing this yourself? If so, please move the Area to interactive (we're using Area paths to indicate team's that own it, not where the work needs to occur). Otherwise, if you would like us to pick it, I'll need more details filled out.

**Comment by tmat** [comment]
@davkean Moved to Area-Interactive.
