### ISSUE TITLE
Proposal: semicolon-terminated empty-bodied void virtual methods syntax sugar

### ISSUE THREAD

**Issue by dsaf** [dotnet/roslyn#8985]
It's not uncommon to have empty-bodied void virtual methods as a way of providing optional [extensibility](http://stackoverflow.com/questions/5536201/virtual-methods-without-body).
However at the moment they are still required to have an empty body code block:

```csharp
public abstract void DoMandatoryWork(object argument);
public virtual void DoOptionalWork(object argument) {}
```

It's obviously a minor syntax sugar request, but it still has it's small benefits:

1) the intent is *even* more clear;
2) don't have to change default automatic code formatting to keep parenthesis on the same line;
3) one character less and one space less - *slightly* faster to read :).

Non-void virtual methods are already taken care of with expressions:

```csharp
public virtual int DoOptionalWork(object argument) => default(int);
```

**Comment by alrz** [comment]
I like this only for constructors in order to change the access modifier,
```cs
public class Foo {
  private Foo();
}
```
But I don't like the implicit default, I think #7737 can paly well with empty `virtual` methods (as long as they are not returning `void`).

**Comment by orthoxerox** [comment]
I wouldn't mind if `void` was allowed to have a single value, and that value was `null` or something similar. This would solve so many corner cases, including this one.

**Comment by Joe4evr** [comment]
I'm not so sure, though. Just earlier today, I happened to [read this question that Eric Lippert answered](http://stackoverflow.com/a/3807583/1519914). He says:
> There is only one kind of expression in C# which does not produce some sort of value, namely, an invocation of something that is typed as returning void.

I have no idea what the implications would be if that were to change, so I'll leave it to someone who's much more familiar with the language internals to answer that.

Unless I'm completely off the mark on what you meant.

**Comment by alrz** [comment]
I think it doesn't hurt if type inferred `default` (#7737) works in a expression-bodied void-returning method,
```cs
protected virtual void F() => default;
```

**Comment by bondsbw** [comment]
It's curious, this is [allowed](https://github.com/dotnet/roslyn/issues/8364#issuecomment-179183113):

```c#
private int x;
public void set_X(int value) => this.x = value;
```
but this is not:
```c#
public virtual void DoOptionalWork(object argument) => ;
```

Not sure if that's any more helpful though.

**Comment by alrz** [comment]
Assignment *is* an expression, an empty statement is not.

**Comment by lachbaer** [comment]
For abstract functions and body-less constructors this is a good idea, I think! (Abstract functions already support this).

But for virtual functions, there *must* always be a body, even if it is empty. Because a virtual function is a valid function in a full instanciable class. It should be clear what happens if this function is invocated, even if it only returns the default value or is empty for `void` returning functions.

Abstract functions however *may* implement a body. Abstract functions make the class abstract, too (that's why the `abstract` modifier for the class is mandatory, to make that clear from the very beginning). And what is optional may be left out.

Also I think it is better to leave the `default` keyword as a 'function'. First, it is concise, not one time a 'function' another time a 'keyword'; Second, it is better to always write down, what default is returned; verbosity is one of the advantages of C#, just see the 'superfluid' `abstract` keyword on the before the `class` keyword, because it is clear that it must be an abstract class, as at least one function inside is abstract - greetings from C++ ;-)

**Comment by gafter** [comment]
Really? A language proposal to save one character?

**Comment by lachbaer** [comment]
> 2) don't have to change default automatic code formatting to keep parenthesis on the same line;

In VS2015 this already works for me, just typing `{` on the same line as the declaration puts me the `}` directly on the same line, nicely formatted.

I also think, the short semicolon terminated declaration should only be for external and abstract declarations. Indeed when you *redefine* the accessibility of a constructor - as the word says - you *define* something, not just *declare* it. A definition should always have the `{ }` braces.

**Comment by dsaf** [comment]
I guess it's not worth it :).
