### ISSUE TITLE
Why is SymbolFinder.FindSymbolAtPositionAsync an async method?

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#9054]
The `SymbolFinder` API has the following methods now:

- `FindSymbolAtPosition`
- `FindSymbolAtPositionAsync`

These methods have identical parameter sets.  In API review it seemed that this method is either inherently sync or inherently async.  If it's the latter then should we mark the former as `Obsolete` to push users in the correct direction.

**Comment by jaredpar** [comment]
The same question applies for `Recomender.getRecomendedSymbolsAtPositionAsync`

**Comment by CyrusNajmabadi** [comment]
These methods are inherently async.  While they take a semantic model, they still need to perform an async operation to go from that SemanticModel's SyntaxTree to the root node.  That's because nothing about a SemanticModel ensure the tree has actually been realized.   In IDE scenarios this realization may actuallly involve expensive work as we read the tree out of our persistence service and rematerialize it.

**Comment by CyrusNajmabadi** [comment]
(so i'm adding hte obsolete attribute on the sync versions).

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/issues/9163
