### ISSUE TITLE
VB Completion: Need to show instance members off types that are part of "My.Forms".

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#9087]
1. Create a VB Winforms project.
2. Add a second form named `frmOther`.
3. Double click on Form1 to get a Loaded event handler.
4. In the event handler, type `frmOther.`
## Result

Completion shows only `Shared` members from `Form`, `Control`, etc.
## Expected

Should show instance members of `frmOther`, since the compiler will redirect through `MyProject.Forms.frmOther` in this case.

**Note**: Also reported in internal bug TFS#214801.

**Comment by KDWOOD** [comment]
Greetings, I recently opened a ticket with MS on this very issue.  I understand that this is not slated for fix until Update-3.   What is the anticipated timeline for Update-3?   It was very disappointing that this bug was missed and even more disappointing to learn that a quick fix is not available.

**Comment by FinPlec** [comment]
Any update on this? Really annoying issue that needs to be fixed.

**Comment by rchande** [comment]
@dpoeschl Our EditorBrowsable stuff appears to be filtering out MyForms members--will keep investigating.

**Comment by rchande** [comment]
Sorry, @dpoeschl--scratch that.

**Comment by rchande** [comment]
@AlekseyTs @TyOverby I think I've found the underlying issue. Can you guys weigh in here?

Consider:
```VB
    Private Sub Form1_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        frmOther.$$ = False
    End Sub
```
In this case, the frmOther before $$ binds to the type `WindowsApplication1.frmOther` in both GetTypeInfo and GetSymbolInfo. Because we are only able to bind it as a a type, the IDE only attempts to look up static members. 

However, manually typing an instance property of frmOther after the dot causes GetSymbolInfo to return `My.MyProject.MyForms.frmOther`
```VB
    Private Sub Form1_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        frmOther.AutoScroll = False
    End Sub
```
In this case, because we're able to bind it as a property, the IDE looks up static and instance members.

My questions are:
* Should GetSymbolInfo return the MyForms property for `frmOther` even if there's no instance member typed after the dot?
* If not, what's the best way for us to ask if a given type is also accessible through the `My` namespace?

**Comment by AlekseyTs** [comment]
> Should GetSymbolInfo return the MyForms property for frmOther even if there's no instance member typed after the dot?

I believe the answer is no. According to the Language Specification (11.6.2.1 Default Instances and Type Names), a type name is interpreted as a default property access only in contexts where the type name is not allowed. So, until we know what is after the dot, in the example above, the type name is treated as a type reference. 

> If not, what's the best way for us to ask if a given type is also accessible through the My namespace?

Try speculatively binding an expression of the form ```<type name>()```. I think it will be bound as a property access.

**Comment by rchande** [comment]
@AlekseyTs That seems to work. I'd like to construct an IDE layer test for this that doesn't actually require the full project system. However, the compiler tests for My namespace related features appear to use internal helpers to set up Compilations with a My namespace. Any recommendations for doing this at the workspaces and above layer?

**Comment by AlekseyTs** [comment]
If you are targeting forms, try defining preprocessor symbol _MYTYPE = "WindowsForms". It might just work after that.

**Comment by TyOverby** [comment]
@rchande Should this issue be closed?
