### ISSUE TITLE
Please unseal DiagnosticDescriptor

### ISSUE THREAD

**Issue by JayBazuzi** [dotnet/roslyn#9124]
So I can replace

```
    new DiagnosticDescriptor("...", "Foo is bad", "...", );
```

with

```
    class FooIsBadDiagnosticDescriptor
    {
        ctor()
           : base("...", "Foo is bad", "...", )
        {}
   }

   new FooIsBadDiagnosticDescriptor();
```

**Comment by CyrusNajmabadi** [comment]
This would need to go through an API proposal.  in general, the reason we don't just make things public is because it increases maintenance costs and locks down our ability to change things in teh future.  We can open things up, but we have a process that requests need to go through to make sure the appropriate people weigh in and the right API shape is determined and shipped.
