### ISSUE TITLE
Extract interface 'IReportDiagnostic' from SymbolAnalysisContext and SyntaxNodeAnalysisContext

### ISSUE THREAD

**Issue by JayBazuzi** [dotnet/roslyn#9125]
```
    interface IReportDiagnostic
    {
        public void ReportDiagnostic(Diagnostic diagnostic);
    }
```

**Comment by JayBazuzi** [comment]
So that I can easily write a code that deals with both kinds of contexts.

**Comment by CyrusNajmabadi** [comment]
This would need to go through an API proposal.  in general, the reason we don't just make things public is because it increases maintenance costs and locks down our ability to change things in teh future.  We can open things up, but we have a process that requests need to go through to make sure the appropriate people weigh in and the right API shape is determined and shipped.
