### ISSUE TITLE
'.=' Operator - Syntactic Sugar

### ISSUE THREAD

**Issue by Unknown6656** [dotnet/roslyn#9134]
I know, that this is something rather small but imagine the following tree:

	public static class foo
		public static class bar
			...
				public static class bizz
					public static IEnumerable<int> list { set; get; }
					
And I want to reverse the IEnumerable, so I have to type:

	foo.bar. ... .bizz.list = foo.bar. ... .bizz.list.reverse();
	
One could shorten this a lot by using the new Operator `.=`, which is identical to the code above:

	foo.bar. ... .bizz.list .= reverse();
	
The `.=`-Operator assigns the field/property/variable to the value of the function result.
The `.=`-Operator onyl accepts the following:

	T .= func(...)
	// where T is mutable
	// where func is a method/extension method,
    //       with the result type and the first argument type being typeof(T)
	
**Pros:**
- Shortens some overlarge code snippets
- Easy to implement (does not require CLR-changes)
- Does not influence performance as generated OP-codes are identical
- Faster to read
- Simple usage / Intuitive usage as it works similarly to Operators like `+=`, `-=`, `*=`, `/=`, `%=`, etc.

**Cons:**
- Could be confusing when used in some one-liners

<hr/>
_Maybe one could also implement the pointer-counterpart to this operator (meaning the operator `->=`) -- but this may result in un-readable code ;)_

**Comment by DavidArno** [comment]
From the [Nested Types Design Guidlines](https://msdn.microsoft.com/en-us/library/ms229027%28v=vs.110%29.aspx):

> **X DO NOT** use public nested types as a logical grouping construct; use namespaces for this.
**X AVOID** publicly exposed nested types...

Your design violates these, very sensible, design guidelines. I'd suggest therefore the design needs a rethink, rather than having syntactic sugar that simplifies using such a design.

**Comment by HaloFour** [comment]
Also, you can legally alias a nested type:

```cs
using bizz = foo.bar.bizz;
// later
bizz.list = bizz.list.reverse();
```

**Comment by manixrock** [comment]
This seems to me to be a self-or-copy problem. For example if you have a class `Vector` and you want to add methods like `Add(Vector vector)`, `Multiply(double value)`, etc. should they change the current vector (and maybe return it too), or should they return a modified copy of the vector?

Both are useful and used often. Modifying the vector is necessary for performance reasons (instead of creating a modified copy and assigning it to itself), while returning a copy is shorter than cloning an existing object then modifying it.

I think the ideal way to solve this is to implement both cases, where the copy-methods call the self-method:

```C#
class Vector {
    public Vector Copy() => new Vector(this);

    public Vector AddSelf(Vector vector) { this.x += vector.x; ... }
    public Vector MultiplySelf(double value) { this.x *= value; ... }

    public Vector Add(Vector vector) => Copy().AddSelf(vector);
    public Vector Add(double value) => Copy().MultiplySelf(value);
}
```

In your case if you implemented your code like this, you'd then simply call:

```C#
foo.bar. ... .bizz.list.ReverseSelf();
```

This would be shorter code than your solution, faster since it doesn't involve any copying, and require no new operators.

**Comment by Unknown6656** [comment]
@HaloFour, @DavidArno  : I know the `alias`-instruction and I know that writing nested classes is not very good - but what if you have 'nested' properties and not nested classes? (I have to agree that my example was a bit crappy)

@manixrock: good point - I did not think about that .... that does indeed render my `.=`-operator uselessly.....

**Comment by Unknown6656** [comment]
_EDIT:_ with nested properties I mean the following: You want to edit a property of an type instance, which itself is called by an property etc. <br/>e.g.:

	public class MyControl : Control
		public Control Parent { set; get; } 
		public IEnumerable<int> ExampleList { set; get; } 

and you want to change the list order _(or whatever else)_ of the 50th parent of the mycontrol-instance:

	MyControl crtl = .....;
	
	ctrl.Parent.Parent.Parent. ..... . Parent.ExampleList = ctrl.Parent.Parent.Parent. ..... . Parent.ExampleList.Reverse();
	
could be easier written as:

	ctrl.Parent.Parent.Parent. ..... . Parent.ExampleList .= reverse();

**Comment by HaloFour** [comment]
@Unknown6656 

Or you could assign the next-to-last result from the properties to a temporary variable:

```cs
MyControl ctrl = .....;
Control parent = ctrl.Parent.Parent.Parent.Parent.Parent.Parent.Parent;
parent.ExampleList = parent.ExampleList.Reverse();
```

**Comment by Unknown6656** [comment]
@HaloFour Yes of course - you are right....
Well this renders indeed the need for a `.=`-operator into nothingness :smile:
