### ISSUE TITLE
Proposal: Dynamic classes

### ISSUE THREAD

**Issue by henrikklarup** [dotnet/roslyn#9142]
It would be nice to see a possibility to create dynamic classes, which would take some properties from class A, and some from class B, and inherit all from class C, but exclude some of them.
So sort of like multiple inheritance, but even cooler.

**Comment by HaloFour** [comment]
I'm not sure that I get what the purpose would be in "inheriting" only parts of a parent contract.  You wouldn't be able to upcast the "derived" type to any of the "parent" types since it wouldn't satisfy the contract.

The inheritance model of C# is pretty much baked directly into the CLR.  At most C# could offer some convoluted delegation or copypasta, but I couldn't imagine why it would be useful other than as a novelty.
