### ISSUE TITLE
Proposal: Conditional summeries

### ISSUE THREAD

**Issue by henrikklarup** [dotnet/roslyn#9143]
It would be nice to see conditional summary values, based on what value a certain parameter of the given method had.
Especially if the parameter was of type generic this could be some part of the summary replaced based on the type of the given parameter.

**Comment by svick** [comment]
I have no idea what are you proposing here. Maybe an example would help?

**Comment by henrikklarup** [comment]
Something like this:

<Summary>
This is a generic summary

@{a == 5} ? If a is five this part of the summart will be shown
@{a == 2} ? If a is two this part of the summart will be shown, but not the other parts
@{a == 1} ? If a is one this part of the summart will be shown, but not the other parts
</Summary>
public void someMethod(int a)


So when using someMethod somewhere, it will show the summary on hover based on what input has been given.

someMethod(5); //Will show: This is a generic summary    If a is five this part of the summart will be shown

**Comment by svick** [comment]
So it's an extension to XML documentation comments? Could you explain when would this be useful?

I think that documentation should not be conditional, especially since a parameter doesn't have to be a constant. In your example, if I write `someMethod(i)`, or when I'm in the middle of writing (`someMethod(`), I probably need to know all the details. Would those situations show all the conditional parts?

**Comment by alrz** [comment]
That's interesting. So the documentation for the method totally changes if you use a set of restricted values? That means you probably shan't be able to use `someMethod(0)`? This seems like strategy pattern, if so I think you should use enum for those specific values and document the specific behavior on enum members.

**Comment by gafter** [comment]
@DustinCampbell This sounds a bit like an IDE feature request, no?

**Comment by DustinCampbell** [comment]
@gafter -- not exactly. If the language chose to support this feature in XML doc comments, and the compiler encoded it in XML documentation file, the IDE would need to support it. However, this would need to be supported across the .NET ecosystem, so an update to XML doc comments from the language design and compiler would be appropriate.

FWIW, I don't think we'd do this. The design-time evaluation is pretty heavy-handed and potentially complicated for a small benefit. It's a cool idea though!

**Comment by gafter** [comment]
We are now taking language feature discussion in other repositories:
- https://github.com/dotnet/csharplang for C# specific issues
- https://github.com/dotnet/vblang for VB-specific features
- https://github.com/dotnet/csharplang for features that affect both languages

Features that are under active design or development, or which are "championed" by someone on the language design team, have already been moved either as issues or as checked-in design documents. For example, the proposal in this repo "Proposal: Partial interface implementation a.k.a. Traits" (issue 16139 and a few other issues that request the same thing) are now tracked by the language team at issue 52 in https://github.com/dotnet/csharplang/issues, and there is a draft spec at https://github.com/dotnet/csharplang/blob/master/proposals/default-interface-methods.md and further discussion at issue 288 in https://github.com/dotnet/csharplang/issues. Prototyping of the compiler portion of language features is still tracked here; see, for example, https://github.com/dotnet/roslyn/tree/features/DefaultInterfaceImplementation and issue 17952.

In order to facilitate that transition, we have started closing language design discussions from [the roslyn repo](https://github.com/dotnet/roslyn) with a note briefly explaining why. When we are aware of an existing discussion for the feature already in the new repo, we are adding a link to that. But we're not adding new issues to the new repos for existing discussions in this repo that the language design team does not currently envision taking on. Our intent is to eventually close the language design issues in the Roslyn repo and encourage discussion in one of the new repos instead.

Our intent is not to shut down discussion on language design - you can still continue discussion on the closed issues if you want - but rather we would like to encourage people to move discussion to where we are more likely to be paying attention (the new repo), or to abandon discussions that are no longer of interest to you.

If you happen to notice that one of the closed issues has a relevant issue in the new repo, and we have not added a link to the new issue, we would appreciate you providing a link from the old to the new discussion. That way people who are still interested in the discussion can start paying attention to the new issue.

Also, we'd welcome any ideas you might have on how we could better manage the transition. Comments and discussion about closing and/or moving issues should be directed to https://github.com/dotnet/roslyn/issues/18002. Comments and discussion about this issue can take place here or on an issue in the relevant repo.

-----------------

I am not moving this particular issue because I don't have confidence that the LDM would likely consider doing this.
