### ISSUE TITLE
Perf run identifiers

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#9145]
There needs to be a defined conversion from a SHA to the build identifier and vice versa.  This will allow us to lookup a build run, should it exist for a SHA, and go to a commit from a build identifier.  

The existing mapping should meet this but even if it does the documentation on the transformation needs to be written.

**Comment by TyOverby** [comment]
# Formats

### Sha

A sha1 hash of the commit 
Example: `873cea30798dd53615422a491fc3bff72dcb64df`

### Build Identifier

Composed of three parts:

* The date-time that the most recent commit was timestamped
* The branch that was being tested 
* The shortened hash

Example: `2016-02-17T15:24:59-08:00-master-873cea3`

# Converting between the two

### Build Identifier -> Sha

This is really easy because the sha is a part of the Build Identifier.  Just take the last segment.

`2016-02-17T15:24:59-08:00-master-873cea3` -> `873cea3`

### Sha -> Build Identifier

To go from Sha -> Build Identifier you also need to provide the branch name that the test was done on.

This is necessary because a commit could be perf-tested on multiple branches and context is important.

`873cea3` on `master` -> `2016-02-17T15:24:59-08:00-master-873cea3`  Where the date was pulled via `git show --format="%aI" 873cea3`.
