### ISSUE TITLE
VS unresponsive, eating 100% CPU during rename

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#919]
With dogfood build 226.4.

Dumps and ETL traces %internal_share%\tomat\919

**Comment by Pilchie** [comment]
Can you take a look?

**Comment by balajikris** [comment]
This is fixed by #1113 The perf traces show 100% of CPU time was spent in BloomFilter.ReadBitArray(). Incidentally, @tmat was the one who made a bloom filter change but forgot to update the serialization version number :wink: Deleting the .vs folder cache should fix this, if you do not have the fix sync -ed yet.
