### ISSUE TITLE
Short hand use of nameof (name of current method/class)

### ISSUE THREAD

**Issue by series0ne** [dotnet/roslyn#9197]
Do you think it would be possible (_this is a feature request_) to have a short hand syntax for `nameof` in future?

**Example:**

```
public class MyLovelyClass
{
    public string MyLovelyMethod()
    {
        return nameof();
    }

    public string AnotherLovelyMethod()
    {
        return nameof(this);
    }
}

var instance = new MyLovelyClass();
instance.MyLovelyMethod(); // would return "MyLovelyMethod"
instance.AnotherLovelyMethod(); // would return "MyLovelyClass"
```

**Explanation:**
1. Since `nameof();` has empty parenthesis, it is scoped to it's parent, in this case `MyLovelyMethod`.
2. `nameof(this);` would refer to it's container at the class/struct level, in this case `MyLovelyClass`.

**Rationale:**

Well overall it could be useful, but sometimes there are cases where extremely long method names are used - unit tests for example...

```

public string SendingMenToTheMoonShouldResultInASpaceRaceBetweenAmericaAndRussia()
{
    ....
}

nameof(); // nice and succinct
nameof(SendingMenToTheMoonShouldResultInASpaceRaceBetweenAmericaAndRussia); //LONG!
```

**Comment by alrz** [comment]
#7031

**Comment by jrmoreno1** [comment]
@alrz:  #7031 has a couple of extra options, namely var and base. It seems that resolving var would require changing how type resolution is done, and thus is off the table.  But I'd like to see base.  Also, I'd suggest that the "class" be used instead of this, as it is a keyword in both vb and c#.

**Comment by gafter** [comment]
We are now taking language feature discussion in other repositories:
- https://github.com/dotnet/csharplang for C# specific issues
- https://github.com/dotnet/vblang for VB-specific features
- https://github.com/dotnet/csharplang for features that affect both languages

Features that are under active design or development, or which are "championed" by someone on the language design team, have already been moved either as issues or as checked-in design documents. For example, the proposal in this repo "Proposal: Partial interface implementation a.k.a. Traits" (issue 16139 and a few other issues that request the same thing) are now tracked by the language team at issue 52 in https://github.com/dotnet/csharplang/issues, and there is a draft spec at https://github.com/dotnet/csharplang/blob/master/proposals/default-interface-methods.md and further discussion at issue 288 in https://github.com/dotnet/csharplang/issues. Prototyping of the compiler portion of language features is still tracked here; see, for example, https://github.com/dotnet/roslyn/tree/features/DefaultInterfaceImplementation and issue 17952.

In order to facilitate that transition, we have started closing language design discussions from [the roslyn repo](https://github.com/dotnet/roslyn) with a note briefly explaining why. When we are aware of an existing discussion for the feature already in the new repo, we are adding a link to that. But we're not adding new issues to the new repos for existing discussions in this repo that the language design team does not currently envision taking on. Our intent is to eventually close the language design issues in the Roslyn repo and encourage discussion in one of the new repos instead.

Our intent is not to shut down discussion on language design - you can still continue discussion on the closed issues if you want - but rather we would like to encourage people to move discussion to where we are more likely to be paying attention (the new repo), or to abandon discussions that are no longer of interest to you.

If you happen to notice that one of the closed issues has a relevant issue in the new repo, and we have not added a link to the new issue, we would appreciate you providing a link from the old to the new discussion. That way people who are still interested in the discussion can start paying attention to the new issue.

Also, we'd welcome any ideas you might have on how we could better manage the transition. Comments and discussion about closing and/or moving issues should be directed to https://github.com/dotnet/roslyn/issues/18002. Comments and discussion about this issue can take place here or on an issue in the relevant repo.

-----------------

I think the best place to continue this discussion would be https://github.com/dotnet/csharplang/issues/345.
