### ISSUE TITLE
Rename tracking is noticeably faster than inline rename

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#9203]
I've noticed several instances where renaming a parameter through rename tracking is massively faster than inline rename. Rename tracking commits almost instantly while inline rename spends a lot of time at "computing rename information" after I hit enter.

**Comment by Pilchie** [comment]
This isn't something that we're hearing a bunch of feedback on.

**Comment by tamlin-mike** [comment]
@Pilchie Then consider this at least one more vote. Inline rename (of parameters) can be horribly slow. A test I did this very instant took 16+ seconds to rename one method argument, referenced 27 times in the method. Even worse is renaming methods or fields; it can take literally minutes to rename them - even when so simple as the pop-up with checkboxes saying "3 references in 1 file". I'm not exaggerating.

O/T:
Potential reasons for not getting a lot of feedback on many things, could be due to Microsoft (as claimed by MS PM's) mainly reacts only on crashing bugs, and by "voting popularity" for non-crashing bugs. I have myself pretty much given up on MS due to the mentioned fact, despite having encountered hundreds of more bugs. I made an exception in this case since it seems to be suffering from the "popularity vote" syndrome, and this issue is so severe that going back to 2013 + R# for refactoring and maintenance starts to look like the best option.

**Comment by rchande** [comment]
@tamlin-mike This bug is specifically about my perception that rename tracking is faster than inline rename. Have you compared inline rename with rename tracking in the scenarios that are bothering you? (To use inline rename, simply modify an identifer, and the lightbulb should appear with the option to rename that symbol). We have definitely received feedback (internal and external) about inline rename being slow, but it's helpful in our investigations to know that the same rename is fast using the "rename tracking" feature.

**Comment by tamlin-mike** [comment]
@rchande Rename of one (unused) method argument:

Inline: 2 seconds after return until dialog, then 15-17 seconds "Computing...".

Tracking, scenario 1:
Typing new name + approx 22 seconds of "Gathering suggestions" after CTRL+'.', then 1 second with no feedback after selecting the Rename option + another 22 seconds displaying the "Renaming ..." dialog.

Tracking, scenario 2:
Typing new name, waiting ~10 seconds for the bulb to pop up, waiting another 45-50 seconds för CPU churn to stop, clicking bulb, waiting another 20+ seconds for the spinning ring to disappear, followed by another 20-ish seconds for CPU churn to stop, selecting the Rename operation was instant.

So yeah, when VS has finally stopped the (horrible) background CPU consumption, Tracking is at least three-five orders of magnitude faster than inline renaming.

Both are, however, still at least three to five orders of magnitude too slow. IMHO, of course.

**Comment by rchande** [comment]
@tamlin-mike That's great info, thank you! One additional thing: Can you use the "Send Feedback" tool at the top of the VS window to send a recording of Visual Studio while you wait for inline rename? That will send us a performance trace we can use to diagnose the cause of the slowness. Feel free to mention me (rchande) in the description, that will help me search for it.

**Comment by IanKemp** [comment]
@rchande Am having the exact same issue, have sent a performance recording to MS.

**Comment by CyrusNajmabadi** [comment]
Haven't seen any reports/logs on this, and no vs feedback info.  THis system was already refactored heavily (with perf in mind).  closing out.
