### ISSUE TITLE
WPF exception during AppDomain exit 

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#9247]
http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit32/4417/

```
System.ComponentModel.Win32Exception (0x80004005): Not enough quota is available to process this command
   at MS.Win32.ManagedWndProcTracker.HookUpDefWindowProc(IntPtr hwnd)
   at MS.Win32.ManagedWndProcTracker.OnAppDomainProcessExit()
   at MS.Win32.ManagedWndProcTracker.ManagedWndProcTrackerShutDownListener.OnShutDown(Object target, Object sender, EventArgs e)
   at MS.Internal.ShutDownListener.HandleShutDown(Object sender, EventArgs e)
```

**Comment by jaredpar** [comment]
Granting an exception for this flaky behavior.  

The WPF layer has logic that executes on `AppDomain` exit to unhook native and managed resource pairings.  For example removing customer WNDPROC values.  The way this is hooked means it unconditionally runs on process exit.  

This code is simply not well insulated against error.  There are at least two known cases where this code throws due to what appear to be implementation errors in WPF.  It's possible these represent Roslyn bugs which manifest as WPF crashes but I doubt it.  The errors are deep in the plumbing of WPF and after a day of debugging I couldn't see a meaningful way that we could influence it.  

The manner in which this code is hooked up and its lack of insulation against errors means that from time to time we're going to have flaky behavior of this nature.

**Comment by jasonmalinowski** [comment]
I'm unfamiliar with the code you're mentioning -- can you give a pointer to them? Curious to see what workarounds exist.

**Comment by jaredpar** [comment]
@jasonmalinowski see the stack trace in the bug report.  

> Curious to see what workarounds exist.

None. WPF is hooking the `AppDomain` exit logic.  Unhandled exceptions from this call back result in process failure.  There is no way for us to hook this call.  

I've actually brought this up to the CLR team because it's one of many cases where we keep getting bitten by unhandled exceptions from `AppDomain` exit.

**Comment by davkean** [comment]
We've hit this once, haven't seen it since. Let's reopen if we hit again.

**Comment by netetireallyhuman** [comment]
Hello everyone, I have migrated a larger WPF desktop application to .Net 8.0.
Environment: Windows 10 Pro 22H2 19045.4170, Runtimes 8.0.2.

Since then, exceptions occur sporadically when exiting the application.
Since I have not yet been able to find a clean solution to the problem, I have
a workaround that seems to work.
Maybe this is also interesting for some of you.
Everything else in the code below...

[STAThread]
public static void Main(string[] args)
{
		...

    // MessageBox.Show("Application is terminating.");
    // At this point, the application would be terminated normally
    // without any additional actions or error messages.
    // However, an exception occurs sporadically in WPF in the subsequent
    // AppDomainExit of the runtime system, which can no longer be intercepted
    // there, as the application has actually already ended:
    //   System.ComponentModel.Win32Exception (1816): Not enough quota available,
    //   to process this command.
    //   at MS.Win32.ManagedWndProcTracker.HookUpDefWindowProc(IntPtr hwnd)
    //   at MS.Win32.ManagedWndProcTracker.OnAppDomainProcessExit()
    // See also: https://github.com/dotnet/roslyn/issues/9247
    // Despite intensive research, I have not yet been able to find a workaround,
    // let alone a solution.
    // In the meantime, I have developed the following workaround for myself:
    // WPF-AppDomain-Exit is not run at all, but in the routine "App.AssistedSuicide"
    // an external exe is called, which kills this application.
    // Although this is "dirty coding", it has worked perfectly so far.
    App.AssistedSuicide();
}

...

private static void AssistedSuicide()
{
    Process externalProcess = new Process();
    externalProcess.StartInfo.FileName = "ProcessTerminator.exe"; // external app - kills this application
    externalProcess.StartInfo.Arguments = Process.GetCurrentProcess().Id.ToString() + " 1000"; // prozess-Id and delay
    externalProcess.Start();
    externalProcess.WaitForExit(); // The wait never reaches its end, as this application is terminated beforehand.
}
