### ISSUE TITLE
Please preserve order of subexpression visiting in PatternVariableFinder

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#9258]
See https://github.com/dotnet/roslyn/pull/9216/files#r54207731

/cc @AlekseyTs

**Comment by AlekseyTs** [comment]
The order of visiting is important because it affects which declaration is considered to be a duplicate in case their names are matched. This in turn affects error location and the result of binding of an identifier matching the name. The current behavior is inconsistent with the way local declarations are handled, for example.
