### ISSUE TITLE
Add IOperation feature flag

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn#9270]
Revert changes made in #10627 .

**Comment by genlu** [comment]
Done in #9583

**Comment by genlu** [comment]
Reopened and updated this since we added the flag back for all branches.

**Comment by ManishJayaswal** [comment]
Changing title since we may need to add the flag as the flag is not present in master anymore.

**Comment by genlu** [comment]
The flag is added here: #12035.
We need to figure out a way to enable IOperation for IDE features while still hide it behind the feature flag for other usage.

**Comment by ManishJayaswal** [comment]
Current POR is to keep IOperations public entry points behind a feature flag for Dev15 RTM and add corresponding private entry points, which the public entry points would call into. IDE code and the Analyzer code would call the private entry point via reflection. When IOperations is ready we will update the IDE and Analyzer code to call the public entry point and get rid of the reflection code. 
We will do this work close to end of 2.0 RC milestone so I will leave this on your plate for now.

**Comment by asoifer** [comment]
I added features entry with ioperation value in csproj, but when i open the solution there is not the feature loaded. debugging roslyn we saw two different procedures for load projects, in GetProjectFileInfoAsync method (CSharpProjectFileLoader.CSharpProjectFile.cs) there are these lines:
1. **BuildAsync**("Csc", compilerInputs, cancellationToken)
2. **InitializeFromModel**(compilerInputs, executedProject)
the first one returns the msbuild task, the second fills compilerInputs "manually" like this:
--> compilerInputs.SetFeatures(this.ReadPropertyString(executedProject, "**Features**"));
The IOperation feature is only enabled when you execute the 2nd method, but this occurs when the first one failed. 
I've already installed the last version of MSBuild and the behaviour didn't change.
What do you think about?
Thanks

**Comment by genlu** [comment]
@asoifer I'm not very familiar with MSBuild so I might be wrong, but I think `BuildAsync` would attempt to initialize `compilerInput`, unless something went wrong, then `InitializeFromModel` would be called and do the initialization. So the feature flag should be parsed from project file either way. Could you provide us more details about your setup? How do you know `IOperation` is disabled? What version of VS you are using, and what's the version of Roslyn you are referencing (if you are building an analyzer or something similar that uses `IOperation`)?

**Comment by genlu** [comment]
Close this issue since the feature flag is reinstated (as far as I know, corresponding compiler is released with[ VS 15 Preview 4)](https://blogs.msdn.microsoft.com/visualstudio/2016/08/22/visual-studio-15-preview-4/). 
@asoifer please feel free to keep using this issue or create a new one and tag me to discuss the problem you are encountering.

**Comment by asoifer** [comment]
@genlu thanks for your quick reply, I think IOperation is disabled because when I call to GetOperation method with a syntax node it throws the exception "Feature IOperation is disabled".
i'm currently using visual studio 2015 with the last update, and i pulled to master two days ago. I also installed Microsoft Build Tools for 2015. Its true that BuildAsync attempts to initialize compilerInput, but i thought that it was through msbuild because the invocations inside BuildAsync used MSB libraries. This is confusing for me because InitializeFromModel initializes the feature and BuildAsync not. 
Regards

**Comment by genlu** [comment]
@asoifer I did some tests on VS 2015 update 3, with latest roslyn bit built from master branch deployed. I was able to correctly run an `IOperation` based analyzer (which uses `RegisterOperationAction`, `SemanticModel.GetOperation` and co) in a simple console project I created from template. 

One caveat I noticed is the feature flag is case-sensitive, i.e. `<Features>IOperation</Features>` works whereas `<Features>ioperation</Features>` doesn't. Could you please check your project file to make sure? If this is not the cause for your issue, then the next logically step would be for you the share the project/analyzers/whatever that can help me repro this.

**Comment by asoifer** [comment]
@genlu I tried again creating a new project, but its still the same. I checked the flag, and it is correct (in the first <PropertyGroup>, <Features>IOperation</Features>).  I think its correct because if I call InitializeFromModel it works well.

My analyzer program is: 
var sln = @"solution path";
var workspace = MSBuildWorkspace.Create();
var userSolution = workspace.OpenSolutionAsync(sln).Result;
var userProject = userSolution.Projects.First();
var originalCompilation = (CSharpCompilation)userProject.GetCompilationAsync().Result;
// Here I check the features: (and I dont see the IOperation feature)
var features = originalCompilation.SyntaxTrees.First().Options.Features;
// And here Im trying to get any IOperation instance:
// The exception is thrown is when I call GetOperation
var semanticModel = originalCompilation.GetSemanticModel(originalCompilation.SyntaxTrees.First());
var operation = semanticModel.GetOperation(originalCompilation.SyntaxTrees.First().GetRoot());

We're not hurry for this, we can wait for the official ioperation release because we are currently using a modified version from november 2015. Do you know what is the estimation for the official enabled release? Thank you again @genlu.

**Comment by asoifer** [comment]
@genlu I discussed this issue with @edgardozoppi an intern who has came back from Microsoft and he told me that I can add this feature flag programatically like this:

var options = aProject.ParseOptions.WithFeatures(aProject.ParseOptions.Features.Union(new KeyValuePair<string, string>[] { new KeyValuePair<string, string>("IOperation", "true") }));
 aProject = aProject.WithParseOptions(options);
 var originalCompilation = (CSharpCompilation)aProject.GetCompilationAsync().Result;

Previously we reviewed the configuration and it was ok. Now its working fine, but I wanted to leave this here.
Thanks againt for your help.

**Comment by msbasanth** [comment]
Hi all,

I tried adding parsing options and updating the workspace. But it thew an exception. System.NotSupportedException: Changing parse options is not supported.
   at Microsoft.CodeAnalysis.Workspace.CheckAllowedProjectChanges(ProjectChanges projectChanges)
   at Microsoft.CodeAnalysis.Workspace.CheckAllowedSolutionChanges(SolutionChanges solutionChanges)

// Code I tried
var workspace = MSBuildWorkspace.Create();
            var originalProject = await workspace.OpenProjectAsync(projectFile);
            var solution = originalProject.Solution;
            var newSolution = solution;

            var project = newSolution.GetProject(originalProject.Id);
            var options = project.ParseOptions.WithFeatures(project.ParseOptions.Features.Union(new [] { new KeyValuePair<string, string>("IOperation", "true") }));
newSolution = newSolution.WithProjectParseOptions(project.Id, options);
            workspace.TryApplyChanges(project.Solution);

It looks like MSBuildWorkSpace does not allow updating the parseoptions. Which is the work space that I should use if I want to update the parse options.

Thanks
Bachu

**Comment by msbasanth** [comment]
I tried even with VisualStudioWorkspace same error. Is this feature of modifying the project properties using Roslyn is in plan?

**Comment by asoifer** [comment]
@msbasanth Hi, I see you are trying to update parse options to the solution instead of updating the project, also I think you dont have to apply any changes to the workspaces or solutions because that objects are inmutables. Did you try our solution?
