### ISSUE TITLE
Proposal: Extend the Query Comprehension Syntax with Take and Skip support

### ISSUE THREAD

**Issue by Eirenarch** [dotnet/roslyn#9273]
First of all I would like to apologize for lacking the skills for a quality proposal possibly with a prototype implementation but it seems to me that more competent people haven't thought about this issue so I decided to propose it.

I like the LINQ query comprehension a lot and I do believe that it greatly improves the readability compared to the equivalent extension methods/lambda based code. However some LINQ methods are not supported in the query comprehension syntax. The most prominent example and the case that forces me out into query comprehensions and into extension methods is the paging scenario where I make a query and then have to do paging on top of it.

Example:

```
var result = (from p in DataContext.Products
              where p.Price > maxPrice
              orderby p.Name
              select p).Skip(page * pageSize).Take(pageSize);
```

Note how the lack of support for paging in the query comprehension syntax forces a lot of parenthesis and breaks the pretty flow of the English-like syntax. I believe there could be a syntax like this:

```
var result = from p in DataContext.Products
             where p.Price > maxPrice
             orderby p.Name
             select p
             skip page * pageSize 
             take pageSize;
```

Based on my personal experience it seems that this is the scenario that will reduce the need to exit the query comprehension syntax and drop into extension methods by ~80%. It also seems like a relatively easy to implement feature as it only affects the query comprehensions. Of course I do realize there are issues like skip and take being used as variable names in existing code.

**Comment by HaloFour** [comment]
Kind of covered by #100 although that proposal is a bit more general purpose.  Notably VB.NET has always had `Skip` and `Take` LINQ clauses.

**Comment by Eirenarch** [comment]
Oh you are right. Strange that this proposal wasn't in the top result when I did the search.

**Comment by gafter** [comment]
We are now taking language feature discussion in other repositories:
- https://github.com/dotnet/csharplang for C# specific issues
- https://github.com/dotnet/vblang for VB-specific features
- https://github.com/dotnet/csharplang for features that affect both languages

Features that are under active design or development, or which are "championed" by someone on the language design team, have already been moved either as issues or as checked-in design documents. For example, the proposal in this repo "Proposal: Partial interface implementation a.k.a. Traits" (issue 16139 and a few other issues that request the same thing) are now tracked by the language team at issue 52 in https://github.com/dotnet/csharplang/issues, and there is a draft spec at https://github.com/dotnet/csharplang/blob/master/proposals/default-interface-methods.md and further discussion at issue 288 in https://github.com/dotnet/csharplang/issues. Prototyping of the compiler portion of language features is still tracked here; see, for example, https://github.com/dotnet/roslyn/tree/features/DefaultInterfaceImplementation and issue 17952.

In order to facilitate that transition, we have started closing language design discussions from [the roslyn repo](https://github.com/dotnet/roslyn) with a note briefly explaining why. When we are aware of an existing discussion for the feature already in the new repo, we are adding a link to that. But we're not adding new issues to the new repos for existing discussions in this repo that the language design team does not currently envision taking on. Our intent is to eventually close the language design issues in the Roslyn repo and encourage discussion in one of the new repos instead.

Our intent is not to shut down discussion on language design - you can still continue discussion on the closed issues if you want - but rather we would like to encourage people to move discussion to where we are more likely to be paying attention (the new repo), or to abandon discussions that are no longer of interest to you.

If you happen to notice that one of the closed issues has a relevant issue in the new repo, and we have not added a link to the new issue, we would appreciate you providing a link from the old to the new discussion. That way people who are still interested in the discussion can start paying attention to the new issue.

Also, we'd welcome any ideas you might have on how we could better manage the transition. Comments and discussion about closing and/or moving issues should be directed to https://github.com/dotnet/roslyn/issues/18002. Comments and discussion about this issue can take place here or on an issue in the relevant repo.

-----------------

I recommend continuing this discussion in [csharplang #101](https://github.com/dotnet/csharplang/issues/101).
