### ISSUE TITLE
Navigating symbol definition API

### ISSUE THREAD

**Issue by Mylan719** [dotnet/roslyn#9281]
Hi,
I would like to ask for some API similar to GoToDefinitionHelpers, or for GoToDefinitionHelpers to be public.
My goal is to be able to be able to use "Go to definition" feature in my visual studio 2015 extension that would have the same behavior in my markup as it has in C#/VB code.  Or is there any better piece of API to use for navigating when I only know an ISymbol from semantic model?

**Comment by DustinCampbell** [comment]
Hi @Mylan719, if your extension is in Visual Studio 2015, you should be able to MEF import `VisualStudioWorkspace` from the [Microsoft.VisualStudio.LanguageServices package](http://www.nuget.org/packages/Microsoft.VisualStudio.LanguageServices/1.1.1). That has a [TryGoToDefinition API](http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices/Implementation/ProjectSystem/VisualStudioWorkspace.cs,df551525aaa71999) that should do what you're looking for. Does that answer your question?

**Comment by Mylan719** [comment]
Thank you for answer, this seems to be the "Better piece of API" I was looking for. ;) 
Originaly I thought that if there is `Renamer`, `Formater`, `SymbolFinder` etc.. I should be looking for some static helper to do the trick. Also I studied what `GoToDefinitionCommandHandler` uses aand apparently that set me on a wrong track.
 It is sometimes hard to find something that does what i need :)

**Comment by DustinCampbell** [comment]
@Mylan719 -- yes, there's certainly a large API surface area! :smile: This particular API is on `VisualStudioWorkspace` because it is host-dependent on Visual Studio. It satisfies all of the functionality of Go to Definition inside Visual Studio, such as navigating to metadata-as-source (or even Object Browser in VB), populating the Find Results window when their are many symbols, etc. This is the API that the XAML editor uses to perform a C# or VB Go to Definition within VS.

**Comment by negyxo** [comment]
Hi,

I just stumbled on this, is there any plan to expose IMetadataAsSourceFileService class? Currently it is internal implementation and there is no way to access programmatically metadata as a source in the VS except to enumerate through opened windows (IVsWindowFrame) and then grab the IVsTextView.

Thanks
