### ISSUE TITLE
Calls to auto properties get_ and set_ methods

### ISSUE THREAD

**Issue by lachbaer** [dotnet/roslyn#9339]
When accessing auto-properties within the same class, the emitted IL calls the corresponding get_ and set_ methods (VS2015U1) . Wouldn't it be more performant to access the backing field directly, at least in the same class and ancestor classes, as long as they are in the same assembly?

As I could see the newly proposed features for C# 7 make extensive use of auto properies (e.g. simple records).

**Comment by axel-habermaier** [comment]
The JIT compiler will inline those calls, so at least performance-wise, there should be no difference.

**Comment by HaloFour** [comment]
Read-only auto-properties already do this in the constructor, but that's because they are required to since the backing field is `readonly`.  It would be possible to have the compiler directly set the backing field elsewhere in the same class for normal auto-properties, but as @axel-habermaier mentioned there'd be no performance benefit since the JIT will certainly inline those method calls.  If the property is `virtual` the accessor methods would certainly need to be called since a derived class could override the property and add logic.

**Comment by lachbaer** [comment]
Ok, if the JIT is that smart :-) Just saw it while analysing IL code

**Comment by jaredpar** [comment]
In general the compiler doesn't make such optimizations and instead relies on the JIT to do so.
