### ISSUE TITLE
Discussion: Additional Patterns

### ISSUE THREAD

**Issue by HaloFour** [dotnet/roslyn#9485]
I wanted to start this issue as a discussion for the types of patterns that have not yet been speced out in the [pattern matching proposal](https://github.com/dotnet/roslyn/blob/future/docs/features/patterns.md).  I'd like to keep it pretty open but focused on the types of patterns that have been mentioned in the proposal but not yet fleshed out, patterns from other languages or patterns that may apply to unique circumstances in C#.

I'll start with the list of patterns already speced out (to some degree):
1. Type patterns
2. Constant patterns
3. Variable patterns
4. Wildcard patterns
5. Record/Recursive patterns
6. Property patterns

And here is a list of patterns mentioned in the proposal but not yet speced out:
1. Arrays
2. Lists (and other collections) #5811
3. Dictionaries #5811
4. Tuples
5. Anonymous types
6. Null patterns (possible covered by Constant patterns)
7. Dynamic

Here is a list of additional patterns from F#:
1. And patterns (conjunctive)  #6235
2. Or patterns (disjunctive)  #6235
3. Parenthesized patterns (associativity)
4. Cons(tructs) patterns
5. Identifier patterns (for exception handling) #6789

Here are some additional patterns from Scala:
1. XML patterns
2. Regular expression patterns #5806 #5811

Other community proposed patterns:
1. (Lambda) Expression patterns #8990

This list is not meant to be exhaustive, nor is it meant to represent all of the patterns that should be introduced to C# or VB.NET.  Many of these scenarios could probably be covered by existing patterns or active patterns (assuming that they're implemented).

**Comment by HaloFour** [comment]
I'd like to consider this issue a syntax playground.

If I missed something in the mentioned languages or there are other novel forms of patterns in other language feel free to comment and I'll update this list.  Same if I missed a proposal already made to this repository.

/cc @alrz

**Comment by alrz** [comment]
- Slice patterns (#120, #8987) - also can be introduced as list flattening syntax (Rust)
- Range patterns - also can be introduced as a construction syntax (as proposed in #7632)
- Sequence wildcard patterns (proposed in #5811 but usable in tuples and recursive patterns)
- Runtime type patterns (#8194). I think this should be considered as a pattern per [this comment](https://github.com/dotnet/roslyn/issues/206#issuecomment-144395536)
- Type test patterns e.g. `case is T` useful when you want to omit the pattern variable (Swift/F#)
- JSON patterns (#6949) - symmetry between construction and deconstruction
- `let` patterns ([#206 comment](https://github.com/dotnet/roslyn/issues/206#issuecomment-183263331)) (Swift)
- `out` patterns ([#9005 comment](https://github.com/dotnet/roslyn/issues/9005#issuecomment-188395560))
- `ref` patterns (#118) (Rust)
- `await` patterns. This is fairly related to #5187 and [joinads](http://tomasp.net/blog/fsharp-variations-joinads.aspx/),
```cs
switch(FuncAsync1(), FuncAsync2())
{
  case(await true, *):
  case(*, await true):
    return true;
  default:
    return false;
}
```
Implementing this with `WhenAny` is not as effective because you wouldn't know that which task is completed and you have to compare the returned task with each one of them. Also this would work with any awaitable including `IOservable<T>` via Rx.

**Comment by gafter** [comment]
We are now taking language feature discussion in other repositories:
- https://github.com/dotnet/csharplang for C# specific issues
- https://github.com/dotnet/vblang for VB-specific features
- https://github.com/dotnet/csharplang for features that affect both languages

Features that are under active design or development, or which are "championed" by someone on the language design team, have already been moved either as issues or as checked-in design documents. For example, the proposal in this repo "Proposal: Partial interface implementation a.k.a. Traits" (issue 16139 and a few other issues that request the same thing) are now tracked by the language team at issue 52 in https://github.com/dotnet/csharplang/issues, and there is a draft spec at https://github.com/dotnet/csharplang/blob/master/proposals/default-interface-methods.md and further discussion at issue 288 in https://github.com/dotnet/csharplang/issues. Prototyping of the compiler portion of language features is still tracked here; see, for example, https://github.com/dotnet/roslyn/tree/features/DefaultInterfaceImplementation and issue 17952.

In order to facilitate that transition, we have started closing language design discussions from [the roslyn repo](https://github.com/dotnet/roslyn) with a note briefly explaining why. When we are aware of an existing discussion for the feature already in the new repo, we are adding a link to that. But we're not adding new issues to the new repos for existing discussions in this repo that the language design team does not currently envision taking on. Our intent is to eventually close the language design issues in the Roslyn repo and encourage discussion in one of the new repos instead.

Our intent is not to shut down discussion on language design - you can still continue discussion on the closed issues if you want - but rather we would like to encourage people to move discussion to where we are more likely to be paying attention (the new repo), or to abandon discussions that are no longer of interest to you.

If you happen to notice that one of the closed issues has a relevant issue in the new repo, and we have not added a link to the new issue, we would appreciate you providing a link from the old to the new discussion. That way people who are still interested in the discussion can start paying attention to the new issue.

Also, we'd welcome any ideas you might have on how we could better manage the transition. Comments and discussion about closing and/or moving issues should be directed to https://github.com/dotnet/roslyn/issues/18002. Comments and discussion about this issue can take place here or on an issue in the relevant repo.

I am not moving this particular discussion issue because discussion seems to have died down. But you're welcome to create a new issue in csharplang if you want to start it back up.
