### ISSUE TITLE
PDB format and caller file name arguments include full path names in compiler output

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#949]
Because the PDB file format includes the full path name of source files, the Roslyn C# and VB compilers will produce different output when the paths are different from one compilation to another. In particular, in a cloud build environment the build output might not be deterministic from one build machine to another.

Related to this, the caller file name attribute encodes the full path name. That is another way in which the full path name is encoded into the output assembly.

@tmat suggests we do what the Microsoft C++ compiler does, which is to provide a source/directory map command-line option that normalizes the directory names in the compiler-produced outputs.

It was also suggested that, in the context of this work, we also normalize file separators to `/`, which works on all platforms.

**Comment by ufcpp** [comment]
I'd like also the #line directive to have the same option, especially for T4 template. T4 generates a full path #line directive.

**Comment by gafter** [comment]
@tmat @jaredpar Do either of you (or anyone else, for that matter) know what the C++ compiler's command-line flags are for this? I was not able to find documentation for them.

**Comment by gafter** [comment]
This is proposed to be solved as follows:

1. [`SourceReferenceResolver.NormalizePath`](https://github.com/dotnet/roslyn/blob/0382e3e3fc543fc483090bff3ab1eaae39dfb4d9/src/Compilers/Core/Portable/Compilation/SourceReferenceResolver.cs#L20-L26) shall be used to produce names for these contexts (paths that are output of the compilers) and for no other purposes.
2. The command line shall be augmented to include support for `/pathMap:X1=Y1;X2=Y2...` which causes a prefix of X1 followed by a path separator to be replaced by Y1 followed by a path separator, and so on for each following pair. That command-line data will be held by the compiler's internal implementation of `SourceReferenceResolver` to implement the correct behavior.
3. There will be no change to `CompilationOptions` for this feature as it already contains a `SourceReferenceResolver`.

Separately we will need a change to the project file and msbuild so that this option can flow through the build process to the compilers. When this work is done I'll file a separate issue for that work.

**Comment by tmat** [comment]
@gafter In addition we need to deal with one more path - The PE file stores a path to the PDB. Currently we store a full path (e.g. "C:\Temp\Foo.pdb"). I propose we store just the file name with extension (e.g. "Foo.pdb") if the PDB is compiled into the same directory as the PE file. Otherwise we use the full path. Deterministic compilation would then require the PDB stored next to the PE. Is that too much to require? If so we'd need another command line option (e.g. /pdbPath) that specifies what path should be written to the PE debug directory.

**Comment by gafter** [comment]
@tmat Could we store the pdb filename and extension (without path) no matter its location?

**Comment by tmat** [comment]
@gafter No, that would break local debugging scenarios. If the customer sets the output path for PDB to a different directory than the DLL the debugger would have no way to find it.

**Comment by gafter** [comment]
@tmat Don't most debugging engines have a way to specify the path where PDBs are to be found, and the capability to acquire them when missing?

**Comment by tmat** [comment]
@gafter Yes, but it requires extra steps and actions from the user. Right now it just works without setting anything.

**Comment by tmat** [comment]
@gafter Perhaps we could disable support for /pdb (report an error that the two options are not compatible) when deterministic is on. We'd always save it next  to the .dll.

**Comment by gafter** [comment]
@tmat If the user went to the extra trouble to move the PDB elsewhere and enable determinism, that same user can go to the trouble of accommodating those choices when using the debugger. Is that reasonable?

**Comment by gafter** [comment]
Adding to the spec here:

4. When a PDB is produced, the generated assembly shall reference the PDB's filename without including path components (directory). For example, instead of referring to `"D:\Project\Bin\Program.DLL"` in the assembly, it shall refer to `"Program.DLL"`.

We still need to consult with users of this data to ensure it is OK.

**Comment by tmat** [comment]
@gafter ... you probably meant ```Program.PDB```, not ```Program.DLL```.

**Comment by gafter** [comment]
Yes. Fixed.

**Comment by gafter** [comment]
We may also need to map file names appearing in diagnostics.

**Comment by tmat** [comment]
@gafter Additional processing is needed to ensure that the normalized paths don't depend on the underlying OS:
Consider compiling on Windows with ```/pathMap:C:\foo\bar=/foo``` and a source path ```C:\foo\bar\baz.cs```. Then the resulting path stored in the PDB should be ```/foo/baz.cs``` rather than ```/foo\baz.cs```. That is if that target path in the path map consistently uses '/' as a separator we should flip all separators to '/'. If it includes both separators ('/' and '\') or neither we should keep the remaining separators in the source path as they are.

Using this approach it is possible to always produce the same paths regardless of whether the compilation happens on Linux or Windows.
