### ISSUE TITLE
[Proposal]: borrow Pascal's "with" operator

### ISSUE THREAD

**Issue by XuTpuK** [dotnet/roslyn#951]
It's unnecessary to say how it reduces code when many fields should be initialized!

    with (var ClickedColumnInSecondGrid = GetColumn()) {
        .Width = 100;
        .OnWidthChanged += Action;
    }

Note that opposite to automatic property initializer, here we can assign event handlers too!
And of course multiple objects can be "with"-ed:

    with (config, window) {
        .Width = .MainWindowWidth; // take prop from config and init window's width
    }

OFFTOP: I think this feature is way more useful than "static import", which brings method mess into the code.

**Comment by Joe4evr** [comment]
1) I think VB already has this, at least in large part, so this would at least provide some more feature parity.
2) You can't assign event handlers in object initializers? Never tried that before, so I didn't know.
3) In your second example, how is it determined which property belongs to which object?

**Comment by mkosieradzki** [comment]
I generally don't like introducing features encouraging nasty (imperative ;) ) programming style. I don't think that any state alteration should be made easier in C#, but that's mine point of view. 

For me It's perfectly ok that there are tons of initialization helpers which give strong preference towards functional style and there are no helpers like this for imperative code (state alteration MUST hurt by design).

**Comment by XuTpuK** [comment]
@Joe4evr  Easy as 123 - by uniqueness of column names. And if _used_ names are equal, you have to specify which object you access.

**Comment by XuTpuK** [comment]
@mkosieradzki If you like "functional" style, what are you doing in C#? Use power of F# before you loose your power on USELESS comments.

**Comment by gafter** [comment]
Is this different than #133 ?

**Comment by HaloFour** [comment]
@XuTpuK 

This has been requested since long before C# went 1.0 and the designers already weighed in on it many, many times.

My opinion is that `with` has no purpose.  You can get the same semantics by assigning an expression to a simple short-name variable within a specific scope.  Then you can at least continue to refer to the result of the expression, which you cannot do with `with` which is additional functionality actually requested of VB.NET.

And, yet again, please stop acting like an obnoxious little toddler.  I'm just going to write-off every comment you ever make because it's clear that you cannot engage in constructive or intelligent conversation.
