### ISSUE TITLE
[Proposal] Extend nameof to handle non visible members too

### ISSUE THREAD

**Issue by tvsonar** [dotnet/roslyn#9599]
This is a proposal to extend `nameof` to handle inaccessible members. There are similar proposals to include the full name of the referenced construct with namespaces, so ideally the syntax should support all these extensions.

Given the following code, the test is not resilient to changes to the private member name.
```C#
public class MySubject
{
    private int SomeVeryComplexLogic()
    {
        return 42;
    }
}

[TestClass]
public class Test
{
    [TestMethod]
    public MySubject_SomeVeryComplexLogic()
    {
        var subject = new MySubject();
        PrivateObject accessor = new PrivateObject(subject);
        var res = accessor.Invoke("SomeVeryComplexLogic");
    }
}
```

However, with minimal changes to `nameof`, we could write something like this:
```C#
var res = accessor.Invoke(nameof(MySubject.SomeVeryComplexLogic, private));
```

**Comment by svick** [comment]
The problem I have with this is that it effectively makes names of *private* members part of the *public* contract.

Another problem is that it would mean that referencing a reference assembly and referencing an implementation assembly suddenly start behaving differently.

Also, I don't think the language should make unsupported operations easier (even if they are sometimes necessary).

**Comment by DavidArno** [comment]
I 100% agree with @svick. In my opinion this would severely damage the ability to encapsulate the inner workings of a class. 

> Given the following code, the test is not resilient to changes to the private member name

The test should never, have been written in the first place. Tests should only ever access public APIs; they should never directly access any inner workings of an assembly or class.

**Comment by tvsonar** [comment]
@DavidArno I understand that private methods should not be directly tested, and all tests should operate on the public interface. In real life however this is not always possible, otherwise I don't see why Microsoft would give you a class (`PrivateObject`) that does exactly this. 

Violating the encapsulation is a strong reason, and I guess introducing this extension to `nameof` would not bring enough to the table to overweigh the drawbacks. In any case it would make life a lot easier in some cases.

**Comment by paulomorgado** [comment]
@DavidArno, one should never say never! :smile: 

But, still, :-1: on this proposal.

**Comment by DavidArno** [comment]
@paulomorgado,

I can't help it; I'm a man of absolutes. Never compromise on code quality. Damn, I said "never", again...

**Comment by markhurd** [comment]
I've had the similar thoughts with documentation: why can't I refer to private code in XML comments? The answers are similar.

**Comment by paulomorgado** [comment]
Besides @svick's points, why would you want to poke/look into my privates?

**Comment by weltkante** [comment]
@tvsonar I'd argue that the 'PrivateObject' class is the wrong thing to use in the first place, it looks just like a poor mans reflection, so you get what you asked for. It should not be getting additional support by the language/compiler.

The "right thing" for your use case is improving the tooling to generate a strongly typed proxy class exposing the private implementation details you want to test. This allows you to exactly get the behavior you want, but its something to do on the testing framework/tooling side and shouldn't be part of the language.

If you really wanted to carry this to the language level, you should not have made this stuff private in the first place. You can already make it internal and have your testing code reside in a friend-assembly which can see your internal APIs. If you want to make changes to the language it should improve that scenario to allow better control over 'internal' visibility, instead of suggesting to expose all private metadata to everyone (even if its just for 'nameof').
