### ISSUE TITLE
[Proposal] AddRange in object initializers

### ISSUE THREAD

**Issue by erik-kallen** [dotnet/roslyn#963]
I try to always make collection properties readonly, like

```
class C {
    public List<int> MyList { get; private set; }
    public C() {
        MyList = new List<int>();
    }
}
```

This saves NullReferenceExceptions and is IMO a very good idea to do, but it does cause a problem: I can't use the class in an object initializer when the number of elements are not known compile-time.

Today I need to write

```
int[] myList = GetMyList();
var c = new C();
foreach (var i in myList)
    c.MyList.Add(i);
```

I propose extending object initializers so I could instead write

```
int[] myList = GetMyList();
var c = new C { MyList = { myList } };
```

The compiler should be able to figure out that it should use AddRange initialization based type information in the assigned expression and the property.

**Comment by chrisaut** [comment]
Well, your code as posted would throw NRE because nowhere do you set MyList to anything. I assume you mean you set this in the constructor of C. I'm also not sure why this would change if the compiler knew the number of items at compile time.

So what your asking is that in any object initializer if a property with a non public setter whose type has a public AddRange(IEnumerable<T> items) method and value being set is convertable to IEnuerable<T> that this method is called instead of a write to the property?

If so, they same should be done with a potential Add method, just so the two behave the same.

I personally don't understand the fascination with object initializers, sure setting properties is fine, but I feel like all these special rules about Add methods etc. make the language just more complex with very little gain. And this proposal would just once again take it a step further.

Next week someone will ask for string properties with multiple "Add calls" to be replaced by a generated stringbuilder and append calls.

I don't think its a bad suggestion, I can see it being useful at times, but is it useful enough to warrant making the language more complex?

**Comment by erik-kallen** [comment]
1. Yes, I meant that the constructor initializes the list (updated sample to reflect this). If I know the number of items compile-time, I can write

    var c = new C { MyList = { item1, item2, item3 } };

2. No, my proposed syntax (at least this time) is that if a collection initializer contains one element and a call to an Add method would not compile, then try AddRange instead.

3. You are right; perhaps this is a suggestion for corefx instead.

**Comment by svick** [comment]
What if the collection initializer could result in a call to *extension method* called `Add`? That way, I think the rules would be actually simpler (it would behave more like normal overload resolution) and you could easily create an extension that looks something like `public static void Add<T>(this List<T> list, IEnumerable<T> items)`.

**Comment by SolalPirelli** [comment]
> What if the collection initializer could result in a call to extension method called Add?

This is already the case as of C# 6. ([source](http://roslyn.codeplex.com/wikipage?title=Language%20Feature%20Status&referringTitle=Documentation))

**Comment by svick** [comment]
@SolalPirelli You're right. But I think that means that this proposal doesn't make much sense, since the desired syntax can already be achieved.

**Comment by gafter** [comment]
We are now taking language feature discussion in other repositories:
- https://github.com/dotnet/csharplang for C# specific issues
- https://github.com/dotnet/vblang for VB-specific features
- https://github.com/dotnet/csharplang for features that affect both languages

Features that are under active design or development, or which are "championed" by someone on the language design team, have already been moved either as issues or as checked-in design documents. For example, the proposal in this repo "Proposal: Partial interface implementation a.k.a. Traits" (issue 16139 and a few other issues that request the same thing) are now tracked by the language team at issue 52 in https://github.com/dotnet/csharplang/issues, and there is a draft spec at https://github.com/dotnet/csharplang/blob/master/proposals/default-interface-methods.md and further discussion at issue 288 in https://github.com/dotnet/csharplang/issues. Prototyping of the compiler portion of language features is still tracked here; see, for example, https://github.com/dotnet/roslyn/tree/features/DefaultInterfaceImplementation and issue 17952.

In order to facilitate that transition, we have started closing language design discussions from [the roslyn repo](https://github.com/dotnet/roslyn) with a note briefly explaining why. When we are aware of an existing discussion for the feature already in the new repo, we are adding a link to that. But we're not adding new issues to the new repos for existing discussions in this repo that the language design team does not currently envision taking on. Our intent is to eventually close the language design issues in the Roslyn repo and encourage discussion in one of the new repos instead.

Our intent is not to shut down discussion on language design - you can still continue discussion on the closed issues if you want - but rather we would like to encourage people to move discussion to where we are more likely to be paying attention (the new repo), or to abandon discussions that are no longer of interest to you.

If you happen to notice that one of the closed issues has a relevant issue in the new repo, and we have not added a link to the new issue, we would appreciate you providing a link from the old to the new discussion. That way people who are still interested in the discussion can start paying attention to the new issue.

Also, we'd welcome any ideas you might have on how we could better manage the transition. Comments and discussion about closing and/or moving issues should be directed to https://github.com/dotnet/roslyn/issues/18002. Comments and discussion about this issue can take place here or on an issue in the relevant repo.

-----------------

I am not moving this particular issue because I don't have confidence that the LDM would likely consider doing this.
