### ISSUE TITLE
Setup Authoring generated for Roslyn_Microsoft.VisualStudio.LanguageServices.Telemetry_Microsoft.VisualStudio.LanguageServices.Telemetry.pkgdef

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#9638]
**Steps to Reproduce**:
1. Build `Roslyn.sln`
2. Build `Setup.proj`

**Expected Behavior**:
No telemetry setup authoring

**Actual Behavior**:
```XML
  <Fragment>
    <Component Id="Roslyn_Microsoft.VisualStudio.LanguageServices.Telemetry_Microsoft.VisualStudio.LanguageServices.Telemetry.pkgdef_$(var.Chip)" Directory="CommonRoslynExtensions_Microsoft.VisualStudio.LanguageServices.Telemetry.3643236F_FC70_11D3_A536_0090278A1BB8">
      <File Id="Roslyn_Microsoft.VisualStudio.LanguageServices.Telemetry_Microsoft.VisualStudio.LanguageServices.Telemetry.pkgdef_$(var.Chip)" Source="!(bindpath.sources)\ExternalApis\Roslyn\LanguageServiceRegistration\Microsoft.VisualStudio.LanguageServices.Telemetry\Microsoft.VisualStudio.LanguageServices.Telemetry.pkgdef" />
    </Component>
  </Fragment>
```

**Comment by davkean** [comment]
Why is no setup authoring expected for this?

**Comment by tannergooding** [comment]
@davkean, I would assume because we haven't had it before (it is a new file being generated).

That being said, it only contains the binding redirects for the assemblies included in the VSIX, so I would question why we haven't had it before and say that we should be including it.

**Comment by davkean** [comment]
Assemblies don't contain binding redirects - pkgdef's do. What does this assembly actually do?

**Comment by tannergooding** [comment]
The setup authoring is for a new pkgdef file that was not being created before (it is 'new' as of the commit which switched us to semantic version 1.3), and the pkgdef contains the binding redirects for our Telemetry assembly (which collects our telemetry data).

**Comment by davkean** [comment]
oh, so this looks valid. What branch is this Jon?

**Comment by davkean** [comment]
This is by design - we added some binding redirects to the pkgdef.

**Comment by Pilchie** [comment]
Hey @jasonmalinowski,  @davkean says that this is by design.  Right now, we've excluded this from setup authoring is that safe?

On the other hand, is it safe to just install it even if it has no effect for now to avoid an exclusion that might come back to bite us later?

**Comment by jasonmalinowski** [comment]
So here's the back story:

1. The telemetry VSIX was missing the .pkgdef redirects we need to be able to F5 this project like we do with all our existing projects.
2. I added the redirects so I could debug into it as a part of a bug.
3. Since this assembly is not any part of any public API, there's no requirement for us to have the binding redirects there, since there's no redirecting needed. The only assembly you'll ever have on your machine is the one we shipped.
4. There should be no harm in shipping this .pkgdef anyways, since it's just applying a redirect.

I'm of the opinion we should just install it, since then nothing is expectional. I could understand we might want to _not_ do that for 1.2, just out of "there's always risk if something changes", but going forward let's just install it.
