### ISSUE TITLE
Proposal : readonly setter for auto property

### ISSUE THREAD

**Issue by sbrickey** [dotnet/roslyn#9656]
Many classes have fields which are only assignable during constructor (readonly field), but need to be exposed externally, which is best implemented as a property.

Example:

    private readonly string basePath;
    public string BasePath { get { return basePath; } }

To reduce the code, I would like to propose a READONLY modifier for auto properties, presumably only useful on the setter.

Example:

    public string BasePath { get; readonly set; }

Additionally, using the C# auto property initializers, the following would be possible:

    public string StartTime { get; readonly set; } = DateTime.Now;

**Comment by sbrickey** [comment]
obviously, the syntax is open to suggestion... the intention is to simply to enable cleaner code

**Comment by lachbaer** [comment]
Since C# 6 (VS 2015) you can use get-only autoproperties for this:
```C#
public strinag BasePath { get; } = "C:\InitialPath\";
```

**Comment by lachbaer** [comment]
But it would be nice to have a 'readonly' setter ;-) i.e. a setter that can only be called from the constructor. So the check-logic for a valid value could be with the property. I know that there is no CLR support for this. But maybe a `readonly` with the property and an analyzer checking for this constraint would help? The only addition would be the `readonly` keyword, that is represented in the API.

**Comment by stepanbenes** [comment]
`readonly set` sounds strange...

**Comment by lachbaer** [comment]
The syntax I propose is
```C#
public readonly string BasePath { get; } = "C:\InitialPath\";
```

**Comment by HaloFour** [comment]
C# 6.0 does allow you to assign the value of readonly auto-implemented properties in the constructor:

```cs
public class Foo {
    public string BasePath { get; }
    public Foo(string path) {
        BasePath = path;
    }
}
```

Readonly auto-implemented properties are given a private readonly backing field, which is what the constructor is assigning to directly.  The property could not have a "proper" setter accessor method because the CLR will enforce that only constructors of that type may assign a value to that field and the CLR has no concept of methods that may only be called within a constructor.

**Comment by sbrickey** [comment]
well. Nevermind then :)
