### ISSUE TITLE
BasicVenus.Script Block: Smart Indent On Moving out of current line

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#9671]
PR: [#9648](https://github.com/dotnet/roslyn/pull/9648) *\* by @
Failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p1/466/

**1 Test Failures:**
BasicVenus.Script Block: Smart Indent On Moving out of current line

**Issue 1: Individual TAO Test Failure**
Failing integration tests: 

BasicVenus.xml

Bounty

**Comment by Pilchie** [comment]
Does this log include the new diagnostics you just added to try to help track this down?

**Comment by brettfo** [comment]
It doesn't include the checks I added (verifying the current line is `End Sub`), but since the expected line has been case corrected but not yet un-indented it does tell us that the test is proceeding too quickly. When I'm back in on Monday I can look further into why the formatting and indention aren't synchronous like expected.

**Comment by davkean** [comment]
And again: http://dotnet-ci.cloudapp.net/job/roslyn-internal_future_win_vsi_p1/201/

**Comment by balajikris** [comment]
One more instance of this here: http://dotnet-ci.cloudapp.net/job/roslyn-internal_future_win_vsi_p1/367/

**Comment by genlu** [comment]
Another instance here: 
https://ci.dot.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p1_open_prtest/557/

**Comment by Pilchie** [comment]
Moving to 2.1 - we wouldn't take a fix here at this point without an understood customer impact.

**Comment by CyrusNajmabadi** [comment]
Closing as venus is deprecated.
