### ISSUE TITLE
Standardize naming convention for unit test projects and automatically pull in XUnit.targets

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#9747]
We should automatically pull in Roslyn.Toolsset.Xunit.targets for tests. I propose that we automatically do this based on a naming convention; if the project ends in "Tests" we automatically pull it in.

**Comment by Pilchie** [comment]
We run tests based on them matching *.UnitTests*.dll, so I think that's a better match.  Note that there are analyzer samples checked in that use mstest but have the .Test.dll naming pattern.

**Comment by jasonmalinowski** [comment]
@jaredpar added a convention where we tag the projects via a property, which does pulls stuff in now.

**Comment by jaredpar** [comment]
@jasonmalinowski long term I think we're going to end up moving to the project name convention. Roslyn is pretty much alone now in using a property vs. project name. A lot of core infrastructure (repotoolset) is banking on the project name convention. This is one place where we may have to adjust to get it line with the org. 

I had a change + tool to make this happen over the witner break. But delayed it because I didn't want to add to the existing fires. Likely to come up again in the next month or two.

**Comment by jasonmalinowski** [comment]
@jaredpar Fine then. I'm not going to keep that on the backlog (this item made sense because prior to your original change we just had chaos). If/when we have a reason to move, we'll just do it.
