### ISSUE TITLE
[Proposal] While scoped variable

### ISSUE THREAD

**Issue by UnoSD** [dotnet/roslyn#9794]
Would be nice to be able to declare variables in a while condition and keep the scope internal:

```
// Maybe someone can come up with a better syntax than this:
while((var variable = statement).Condition)
{
      ....
      variable.Condition = false; // Exit loop.
}
```

Maybe:
```
while(var variable = statement; variable.Condition)
{
}
```

So we avoid declaring a variable outside the loop and the garbage collector can claim it as soon as we get out of the loop.

**Comment by HaloFour** [comment]
@UnoSD 

That's why we have `for` loops:

```cs
for (var variable = statement; ; variable.Condition) {
}
```

> So we avoid declaring a variable outside the loop and the garbage collector can claim it as soon as we get out of the loop.

This is not the case.  Variable scope within a method is a trick of the compiler.  To the CLR all local slots are scoped for the entire method.  If you leave a reference allocated in a local that reference will not be eligible for collection until that method exits.  You'd have to explicitly set the local to `null`.

The exception to this rule is when you have multiple variables of the same type in two non-overlapping scopes.  In that case the compiler may use a single slot to represent both variables, and in that case the second use of that local may result in the reference being overwritten which would permit the previous reference to be eligible for collection.

**Comment by UnoSD** [comment]
Such a silly request from me; I even knew I could do that with for. I'll close it.
