### ISSUE TITLE
Restore issues warnings around about downgrading a package

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#9841]
This is in master:
1. Run Restore.cmd:

```
WARNING: Detected package downgrade: Microsoft.Build.Framework from 0.0.0 to 0.1.0-preview-00005
 ToolsetPackages (>= 1.0.0) -> Roslyn.Build.Util (>= 0.9.2-portable) -> Microsoft.Build.Utilities.Core (>= 0.1.0-preview-00005) -> Microsoft.Build.Framework
 ToolsetPackages (>= 1.0.0) -> Roslyn.Build.Util (>= 0.9.2-portable) -> Microsoft.Build.Framework (>= 0.1.0-preview-00005)
```

I'm unsure if this is a real issue or not, 0.0.0 -> 0.1.0 isn't a downgrade, it's a upgrade. Is the warning reversed?

tag @agocke

**Comment by agocke** [comment]
I don't think this a real issue – I saw this but haven’t had a chance to follow up yet.

I think the problem is that the Microsoft.Build* packages reference other packages with version=”” which maps to 0.0.0. Technically, this is a downgrade because we’re going to 0.1.0-preview-0005 – a prerelease version, as opposed to 0.0.0, a release version.

MSBuild just needs to stop doing this and the warning should go away.

**Comment by davkean** [comment]
Oh, just NuGet treats released -> pre-release a downgrade? Hmm, I'll file a bug to make that a lot clearer. Not obvious.

**Comment by agocke** [comment]
Filed a bug here: https://github.com/Microsoft/msbuild/issues/528

**Comment by jaredpar** [comment]
This is completed and new warnings cause the CI build to fail.
