### ISSUE TITLE
Issue with updating lightbulb for new analyzers

### ISSUE THREAD

**Issue by KathleenDollard** [dotnet/roslyn#99]
I'm hoping someone can repro this, but I'm sure this is what happened on my machine.

- Created a Class library. By happenstance, closed and reopened VS
- Added FxCop rules via NuGet
- Broke one (CA1012) got the green squiggly
- *Did not get margin lightbulb*
- Hovered over the class name (squiggled) and got the message *did not get the lightbulb popup*
- Closed and reopened Visual Studio
- Still do not get margin lightbulb
- Now I do get the popup lightbulb when I hover over the squigglie

1) I expect to get a margin lightbulb because there is a fix available (changing public to protected on the constructor). 

2) I expect to get the popup lightbulb without closing and reopening Visual Studio

**Comment by srivatsn** [comment]
@KathleenDollard - from the conversation in the insiders mailing list, I assume the margin lightbulb didn't come up because the cursor wasn't on the line that had the issue (which is the current design of the lightbulb). Your feature request of showing all lightbulb on a keypress has been noted by the editor team. So I'll close this issue as external\bydesign.
