### ISSUE TITLE
Proposal: Type views - completes tuples support

### ISSUE THREAD

**Issue by vbcodec** [dotnet/roslyn#9924]
**Description**
Type views is notion that exhibit members and their types from underlying type. This notion works above existing types and can capture types: classes, records, structs, anonymous types, tuples, interfaces and arrays. Views simplifies working with types, reducing needs for using interfaces, exist only on language level and do not require any CLR support. 

**Mapping type members to views**

Positional mapping
Members in view maps members in underlying type, depending on position. Member in view can have different name than those in underlying type, but types of members must be the same.

```
class Car
{
   string Name;
   int Speed;
   int Length;
}

(string name_of_car, int speed) 
```

because underlying types may have more members than we want to expose, we can skip some of them

`(string name_of_car, , int length_of_car)`

Direct mapping
Direct mapping requires that mapped members must have the same names, as specified in view definition. Additionally direct mapping allow to specify members in any order.

`(! int Length, string Name)`

**View variables and assigment**

Views must always be associated with types. Definition like

`var (int X, int Y) m;`

is illegal, because inferred type of m is Object, and Object don't have members X and Y. Views do not replace types, just add new level of abstraction that exhibit types in more friendly way. That;s why declaration of view's variable must be combined with assignment of value.

Some examples of initializing variables of view:

```
var (string name, int speed) x1 = new Car(); // for classes, records and structs
var (int length, int speed) x2 = new (int len, int spd) { len = 0, spd = 0 }; // for tuples (autogenerated as ValueTuple<int, int>)
var (int length, int speed) x3 = (ISomeInterface)i; // for interfaces, x3 type is ISomeInterface
var (int len, string msg) x4 = new { Length = 10, Message = "Hello" }; // for anonymous types
var (int length, int speed) x5 = new int [] {10, 20}; // for homogeneous arrays. Only positional mapping
var (Object length, Object speed) x6 = new Object [] {10, "abc"}; // for homogeneous arrays. Only positional mapping
```

There may be added support for non-homogeneous arrays in language, like {10, "abc"}. Then these arrays can be conusmed by non-homogeneous views like (int length, string name). 

**Casting views to types or other view**

Views are always associated with given type, so extracting this type is straightforward

```
var List<(int X, int Y)> vl = new List<Point>();
var List<Point>() tl = vl;
```

Views are one-level mapping, there are no cascaded mapping between views. Mapping previous view to new view causes mapping captured type from previous view to new view. 

```
var (string name, int speed) x1 = new Car();
var x2 = ((, int speed, int len))x1;
```

**Nested views**

Views can be nested for increase potential of type exhibition

(int name, int speed, (int horsepower, int rpm) engine)

**Views in functions**
Input parameters:
Views can't be used as input parameters, for the reason specified above (lack of known underlying type). Instead of views, tuples will be generated as types for input values.

`function f1 ((string name, int length) input) {..}`

will generate 

`function f1 (TupleValue<string, int> input) {..}`

Output value
It is possible to use view as output definition, but all possible paths must return the same type and this type must be compatible with specified output view definition. Reflected output type will be type returned by code path(s).

**Views in fields and properties**

For the same reason as with unassigned variables and input parameters to functions, views can't be used as fields and properties.

**Possible improvement**
There is possibility to use views for unassigned variables, input parameters to functions, fields and properties. This can be done at expense of using Object type in these places, and code to perform runtime checks if assigned value meet requirements set by view definition.Other option is to treat views as tuples, when type on member is not specified:
`var (int X, int Y) m; // m undelying type is ValueTuple<int, int>`

Best way is to implement type views to CLR. Views at CLR can act like dynamic interfaces, that no need to be implemented.

**Comment by paulomorgado** [comment]
Can you show some practical uses of this?

What can you do with this that you can't without this?

**Comment by gafter** [comment]
We are now taking language feature discussion in other repositories:
- https://github.com/dotnet/csharplang for C# specific issues
- https://github.com/dotnet/vblang for VB-specific features
- https://github.com/dotnet/csharplang for features that affect both languages

Features that are under active design or development, or which are "championed" by someone on the language design team, have already been moved either as issues or as checked-in design documents. For example, the proposal in this repo "Proposal: Partial interface implementation a.k.a. Traits" (issue 16139 and a few other issues that request the same thing) are now tracked by the language team at issue 52 in https://github.com/dotnet/csharplang/issues, and there is a draft spec at https://github.com/dotnet/csharplang/blob/master/proposals/default-interface-methods.md and further discussion at issue 288 in https://github.com/dotnet/csharplang/issues. Prototyping of the compiler portion of language features is still tracked here; see, for example, https://github.com/dotnet/roslyn/tree/features/DefaultInterfaceImplementation and issue 17952.

In order to facilitate that transition, we have started closing language design discussions from [the roslyn repo](https://github.com/dotnet/roslyn) with a note briefly explaining why. When we are aware of an existing discussion for the feature already in the new repo, we are adding a link to that. But we're not adding new issues to the new repos for existing discussions in this repo that the language design team does not currently envision taking on. Our intent is to eventually close the language design issues in the Roslyn repo and encourage discussion in one of the new repos instead.

Our intent is not to shut down discussion on language design - you can still continue discussion on the closed issues if you want - but rather we would like to encourage people to move discussion to where we are more likely to be paying attention (the new repo), or to abandon discussions that are no longer of interest to you.

If you happen to notice that one of the closed issues has a relevant issue in the new repo, and we have not added a link to the new issue, we would appreciate you providing a link from the old to the new discussion. That way people who are still interested in the discussion can start paying attention to the new issue.

Also, we'd welcome any ideas you might have on how we could better manage the transition. Comments and discussion about closing and/or moving issues should be directed to https://github.com/dotnet/roslyn/issues/18002. Comments and discussion about this issue can take place here or on an issue in the relevant repo.

-----------------

I am not moving this particular issue because I don't have confidence that the LDM would likely consider doing this. I also don't understand it based on the description provided.
