### ISSUE TITLE
CSC crashes (instead of emitting error CS0154) when dotting off a setter-only property of type dynamic

### ISSUE THREAD

**Issue by ljw1004** [dotnet/roslyn#9945]
**Version Used**: 
VS2015 Update 2 RC

**Steps to Reproduce**:

Create a console app with the following code, and build it:

```cs
class Program
{
    static void Main()
    {
        I i = null;
        System.Type ts = i.s.GetType();  // compile-time error CS0154
        System.Type td = i.d.GetType();  // compile-time CRASH with error code -2146232797
    }

    public interface I
    {
        string s { set; }
        dynamic d { set; }
    }
}
```

**Expected Behavior**:

Both `GetType()` lines should emit CS0154 "property cannot be used in this context because it lacks a get accessor"

**Actual Behavior**:

The second `GetType()` line causes a compiler crash with

**Comment by jaredpar** [comment]
The crash will not reproduce with the code as written in the bug.  In order to hit the crash the code needs to remove the first `GetType` line and leave only the following:

``` csharp
    static void Main()
    {
        I i = null;
        System.Type td = i.d.GetType();  // compile-time CRASH with error code -2146232797
    }
```

Having the first `GetType` line issues an error which prevents the compiler from going to code generation where the bug occurs.  Once that is deleted the code does indeed throw an exception in `LocalRewriter.MakePropertyAccess`
